# -*- coding: utf-8 -*-
"""B02 'Tissues & Body Structure' — Part 2 data (75 items).
Order: epithelial-connective (5 of 25), joints-movement (25), muscular-nervous-tissue (20), organization-repair (25).
Tuple: (topic, difficulty, q_hi, q_en, options_hi[4], options_en[4], correct_idx, exp_hi, exp_en)
"""

PART2 = [
    # ---------------- epithelial-connective-tissues (remaining 5) ----------------
    ("epithelial-connective-tissues", "medium",
     "लसीका (lymph) को ऊतकों के वर्गीकरण में किस वर्ग में रखा जाता है?",
     "Under the classification of tissues, lymph is placed in which category?",
     ["उपकला ऊतक", "द्रव संयोजी ऊतक", "तंत्रिका ऊतक", "रेखित पेशी ऊतक"],
     ["Epithelial tissue", "Fluid connective tissue", "Nervous tissue", "Striated muscular tissue"],
     1,
     "रक्त की भाँति लसीका का मैट्रिक्स भी द्रव होता है, अतः इसे द्रव संयोजी ऊतक की संज्ञा दी जाती है।",
     "Like blood, lymph has a fluid matrix, so it is also classed as a fluid connective tissue."),

    ("epithelial-connective-tissues", "medium",
     "निम्न में से कौन संयोजी ऊतक नहीं है?",
     "Which of the following is NOT a connective tissue?",
     ["टेंडन", "उपास्थि", "न्यूरॉन", "वसा ऊतक"],
     ["Tendon", "Cartilage", "Neuron", "Adipose tissue"],
     2,
     "न्यूरॉन तंत्रिका ऊतक की इकाई है; शेष तीनों संयोजी ऊतक के रूप हैं।",
     "The neuron is the unit of nervous tissue; the other three are forms of connective tissue."),

    ("epithelial-connective-tissues", "medium",
     "विदरक (areolar) ऊतक में ताकत और लचीलापन किन तंतुओं के कारण आता है?",
     "Which fibres give areolar tissue its strength and elasticity?",
     ["लिग्निन और सुबेरिन", "केराटिन और म्यूसिन", "एक्टिन और मायोसिन", "कोलेजन और इलास्टिन"],
     ["Lignin and suberin", "Keratin and mucin", "Actin and myosin", "Collagen and elastin"],
     3,
     "सफेद कोलेजन तंतु ताकत देते हैं और पीले इलास्टिन तंतु लचीलापन — दोनों मिलकर विदरक ऊतक को भराव व रक्षा योग्य बनाते हैं।",
     "White collagen fibres provide strength and yellow elastin fibres elasticity — together they make areolar tissue a filler and protector."),

    ("epithelial-connective-tissues", "medium",
     "रुधिर वाहिकाओं (blood vessels) की भीतरी परत की उपकला कौन-सी होती है?",
     "Which epithelium forms the inner lining of blood vessels?",
     ["स्तंभाकार", "शल्की (squamous)", "घनाकार", "ग्रंथिल"],
     ["Columnar", "Squamous", "Cuboidal", "Glandular"],
     1,
     "वाहिकाओं के भीतर पतली शल्की उपकला (एण्डोथेलियम) रहती है जिससे रक्त का प्रवाह घर्षण-रहित होता है।",
     "A thin squamous epithelium (endothelium) lines the vessels, allowing friction-free blood flow."),

    ("epithelial-connective-tissues", "hard",
     "निम्न में से गलत तौलिया-बंदी (incorrectly matched) युग्म कौन-सा है?",
     "Which of the following pairs is incorrectly matched?",
     ["रक्त — द्रव मैट्रिक्स", "अस्थि — कठोर कैल्शियम मैट्रिक्स", "उपास्थि — लचीला मैट्रिक्स", "टेंडन — द्रव मैट्रिक्स"],
     ["Blood — fluid matrix", "Bone — hard calcium matrix", "Cartilage — flexible matrix", "Tendon — fluid matrix"],
     3,
     "टेंडन का मैट्रिक्स द्रव नहीं बल्कि सघन तंतुमय (कोलेजन-प्रधान) होता है; शेष तीनों युग्म सही हैं।",
     "A tendon's matrix is not fluid but dense and fibrous (collagen-rich); the other three pairs are correct."),

    # ---------------- joints-movement (25) ----------------
    ("joints-movement", "easy",
     "संधि (joint) से क्या तात्पर्य है?",
     "What is meant by a joint?",
     ["पेशी का एक भाग", "दो या अधिक अस्थियों का मिलन स्थल", "रक्त वाहिका का जोड़", "त्वचा की सिलवट"],
     ["A part of a muscle", "The meeting place of two or more bones", "A junction of blood vessels", "A fold of skin"],
     1,
     "जहाँ दो या अधिक अस्थियाँ आपस में मिलती हैं, वहाँ संधि बनती है।",
     "A joint is formed where two or more bones meet."),

    ("joints-movement", "easy",
     "कंधे की संधि किस प्रकार की होती है?",
     "What type of joint is the shoulder joint?",
     ["कबंध (hinge)", "गेंद-गर्त (ball and socket)", "अक्ष (pivot)", "स्थिर (fixed)"],
     ["Hinge", "Ball and socket", "Pivot", "Fixed"],
     1,
     "कंधे में बाँह की गोल सिर अस्थि कंधे की गड्ढे में घुमती है — गेंद-गर्त संधि, जो हर दिशा में गति देती है।",
     "In the shoulder, the ball-shaped head of the arm bone rotates in a socket — a ball-and-socket joint allowing movement in all directions."),

    ("joints-movement", "easy",
     "कोहनी की संधि किस प्रकार की होती है?",
     "What type of joint is the elbow?",
     ["गेंद-गर्त", "अक्ष", "कबंध (hinge)", "फिसलनी (gliding)"],
     ["Ball and socket", "Pivot", "Hinge", "Gliding"],
     2,
     "कोहनी दरवाज़े के कबंध की तरह केवल एक ही तल में मुड़ती-सीधी होती है, इसलिए यह कबंध संधि है।",
     "The elbow bends and straightens in one plane like a door hinge — hence a hinge joint."),

    ("joints-movement", "medium",
     "कूल्हे (hip) की संधि का प्रकार क्या है?",
     "What type of joint is the hip joint?",
     ["कबंध", "गेंद-गर्त", "स्थिर", "फिसलनी"],
     ["Hinge", "Ball and socket", "Fixed", "Gliding"],
     1,
     "कूल्हे में जंघिका का गोल सिर श्रोणि की गड्ढे में जुड़ता है — गेंद-गर्त संधि।",
     "In the hip, the ball of the femur fits into the socket of the pelvis — a ball-and-socket joint."),

    ("joints-movement", "medium",
     "घुटने की संधि का प्रकार क्या है?",
     "What type of joint is the knee?",
     ["गेंद-गर्त", "अक्ष", "कबंध", "स्थिर"],
     ["Ball and socket", "Pivot", "Hinge", "Fixed"],
     2,
     "घुटना भी कोहनी की तरह एक ही तल में मुड़ता है — कबंध संधि।",
     "Like the elbow, the knee bends in one plane only — a hinge joint."),

    ("joints-movement", "easy",
     "खोपड़ी की अस्थियों के बीच की संधियाँ कैसी होती हैं?",
     "What kind of joints are present between the bones of the skull?",
     ["चलायमान", "अचल (स्थिर)", "अर्धचलायमान", "गेंद-गर्त"],
     ["Freely movable", "Immobile (fixed)", "Slightly movable", "Ball and socket"],
     1,
     "कपाल की अस्थियाँ दाँतों की रूपरेखा जैसी सिलवटों (sutures) से पूर्णतः जुड़ी रहती हैं; ये अचल संधियाँ मस्तिष्क की ढाल बनाती हैं।",
     "Skull bones are locked by saw-toothed sutures; these immovable joints form a helmet for the brain."),

    ("joints-movement", "medium",
     "सिर को 'नहीं' की दिशा में घुमाने में कौन-सी संधि सहायक होती है?",
     "Which joint helps in shaking the head side to side ('no' movement)?",
     ["अक्ष (pivot)", "कबंध", "गेंद-गर्त", "स्थिर"],
     ["Pivot", "Hinge", "Ball and socket", "Fixed"],
     0,
     "गर्दन में पहली और दूसरी कशेरुकाएँ मिलकर अक्ष संधि बनाती हैं जिससे सिर अपने अक्ष पर घूमता है।",
     "The first and second neck vertebrae form a pivot joint that lets the head rotate on its axis."),

    ("joints-movement", "hard",
     "कलाई (wrist) की छोटी अस्थियों के बीच पाई जाने वाली संधियाँ किस प्रकार की होती हैं?",
     "What type of joints are found between the small bones of the wrist?",
     ["कबंध", "गेंद-गर्त", "अक्ष", "फिसलनी (gliding)"],
     ["Hinge", "Ball and socket", "Pivot", "Gliding"],
     3,
     "कलाई-व टखने की छोटी अस्थियाँ एक-दूसरे पर सरकती हैं; ऐसी फिसलनी संधियाँ सीमित सरकाव देती हैं।",
     "The small wrist and ankle bones slide over one another; such gliding joints allow limited sliding motion."),

    ("joints-movement", "easy",
     "कबंध (hinge) संधि में गति कैसी होती है?",
     "What kind of movement occurs at a hinge joint?",
     ["सभी दिशाओं में घूमना", "केवल एक ही तल में आगे-पीछे मुड़ना", "कोई गति नहीं", "केवल घूर्णन"],
     ["Rotation in all directions", "Bending forward and backward in one plane only", "No movement at all", "Rotation only"],
     1,
     "कबंध संधि दरवाज़े के कबंध की तरह एक ही तल में खुलती-बंद होती है, जैसे कोहनी और घुटना।",
     "A hinge joint opens and closes in one plane like a door hinge, as at the elbow and knee."),

    ("joints-movement", "medium",
     "गेंद-गर्त संधि की विशेषता क्या है?",
     "What is the special feature of a ball and socket joint?",
     ["केवल एक तल में गति", "सभी दिशाओं में गति संभव", "कोई गति नहीं", "केवल घूर्णन संभव"],
     ["Movement in one plane only", "Movement possible in all directions", "No movement", "Only rotation possible"],
     1,
     "गोल सिर गड्ढे में घूमती है, इसलिए ऐसी संधि में अग्र-पश्च, ऊपर-नीचे और घूर्णन — तीनों गतियाँ संभव हैं।",
     "The ball swivels in the socket, so forward-back, up-down and rotational movements are all possible."),

    ("joints-movement", "easy",
     "संधि के अस्थि-सिरों पर चिकनी उपास्थि की परत क्यों होती है?",
     "Why do the bone ends at a joint bear a smooth layer of cartilage?",
     ["रक्त बनाने के लिए", "घर्षण घटाकर सहज गति के लिए", "अस्थि को मोटा करने के लिए", "दर्द उत्पन्न करने के लिए"],
     ["To produce blood", "To reduce friction and allow smooth movement", "To thicken the bone", "To produce pain"],
     1,
     "चिकनी उपास्थि संधि की सतहों को घिसने से बचाती है और हड्डियों को घर्षण-रहित सरकने देती है।",
     "Smooth cartilage stops the joint surfaces from grinding and lets the bones glide without friction."),

    ("joints-movement", "medium",
     "संधि-गुहा में भरा रहने वाला साइनोवियल द्रव क्या कार्य करता है?",
     "What does the synovial fluid filling the joint cavity do?",
     ["अस्थि की वृद्धि करता है", "रक्त बनाता है", "संधि का स्नेहन (lubrication) करता है", "पेशी को सिकोड़ता है"],
     ["It grows the bone", "It makes blood", "It lubricates the joint", "It contracts muscles"],
     2,
     "यह द्रव संधि को चिकनाई देकर घर्षण लगभग समाप्त कर देता है और उपास्थि को पोषण भी पहुँचाता है।",
     "The fluid lubricates the joint, nearly eliminating friction, and also nourishes the cartilage."),

    ("joints-movement", "easy",
     "बाँह मुड़ाने पर बाँह की अग्र-भुजा की ओर आती है — इस समय बाइसेप्स पेशी की क्या अवस्था होती है?",
     "When you bend your arm at the elbow, what is the state of the biceps muscle?",
     ["वह संकुचित (contract) होती है", "वह शिथिल (relax) होती है", "वह दोनों अवस्थाओं में नहीं होती", "वह कट जाती है"],
     ["It contracts", "It relaxes", "It is in neither state", "It gets cut"],
     0,
     "बाँह मोड़ने पर बाइसेप्स संकुचित होती है और ट्राइसेप्स शिथिल रहती है; सीधा करने पर यह क्रम उलट जाता है।",
     "Bending the arm, the biceps contracts while the triceps relaxes; straightening reverses this."),

    ("joints-movement", "medium",
     "जब युग्म में कार्य करने वाली एक पेशी संकुचित होती है, तो उसकी विपरीत-क्रिया करने वाली पेशी क्या करती है?",
     "When one muscle of an antagonistic pair contracts, what does its partner muscle do?",
     ["वह शिथिल हो जाती है", "वह भी संकुचित हो जाती है", "वह फट जाती है", "वह अस्थि से चिपक जाती है"],
     ["It relaxes", "It also contracts", "It tears apart", "It sticks to the bone"],
     0,
     "बाइसेप्स-ट्राइसेप्स जैसे विपरीत-युग्म में एक संकुचित होती है और दूसरी शिथिल, तभी अस्थि एक दिशा में घूमती है।",
     "In antagonistic pairs like biceps-triceps, one contracts while the other relaxes, letting the bone swing one way."),

    ("joints-movement", "easy",
     "पेशियाँ अस्थियों पर कौन-सी क्रिया कर सकती हैं?",
     "What action can muscles perform on bones?",
     ["केवल खींच (pull) सकती हैं", "केवल धकेल (push) सकती हैं", "खींच और धकेल दोनों", "न खींच सकती हैं, न धकेल"],
     ["Only pull", "Only push", "Both pull and push", "Neither pull nor push"],
     0,
     "पेशी संकुचन के कारण केवल खींच सकती है; 'धकेलने' का भ्रम उल्टी दिशा में जुड़ी दूसरी पेशी के खिंचाव से बनता है।",
     "A muscle can only pull by contracting; apparent 'pushing' is really the pull of an oppositely attached muscle."),

    ("joints-movement", "medium",
     "कशेरुकाओं के बीच की संधियाँ कितनी गति प्रदान करती हैं?",
     "How much movement do the joints between vertebrae allow?",
     ["कोई गति नहीं", "अल्प (सीमित) गति", "पूर्ण घूर्णन", "सभी दिशाओं में स्वतंत्र गति"],
     ["No movement", "Slight (limited) movement", "Full rotation", "Free movement in all directions"],
     1,
     "कशेरुकाएँ आपस में गद्दियों सहित जुड़ी हैं, इसलिए प्रत्येक संधि थोड़ी-बहुत ही गति देती है — पर सब मिलकर पीठ को व्यापक लचीलापन देती हैं।",
     "Vertebrae are joined via discs, so each joint moves only slightly — but together they give the back a wide range of flexibility."),

    ("joints-movement", "medium",
     "संधि में लिगामेंट के अत्यधिक खिंचने या मरोड़ने की चोट को क्या कहते हैं?",
     "What is the injury called when a ligament gets overstretched or twisted at a joint?",
     ["भंग (fracture)", "मोच (sprain)", "अवस्थापन (dislocation)", "रक्तस्राव"],
     ["Fracture", "Sprain", "Dislocation", "Bleeding"],
     1,
     "मोच में स्नायु खिंचते या आंशिक फटते हैं; अस्थि नहीं टूटती — टूटे तो वह भंग होता।",
     "In a sprain, ligaments stretch or partially tear; the bone does not break — that would be a fracture."),

    ("joints-movement", "hard",
     "स्वतंत्र चलायमान (synovial) संधियों की पहचान क्या है?",
     "What is the identifying feature of freely movable (synovial) joints?",
     ["इनमें संधि-गुहा और स्नेहक द्रव होता है", "इनमें अस्थियाँ पिघली हुई जुड़ी होती हैं", "इनमें कोई गुहा नहीं होती", "इनमें अस्थियाँ केवल उपास्थि से जुड़ी होती हैं"],
     ["They have a joint cavity and lubricating fluid", "The bones are joined by fusion", "They lack any cavity", "The bones are joined only by cartilage"],
     0,
     "साइनोवियल संधि में अस्थियों के बीच गुहा होती है जिसमें साइनोवियल द्रव रहता है — यही ढीला जोड़ व्यापक गति संभव करता है।",
     "A synovial joint has a cavity between the bones filled with synovial fluid — this loose fit makes wide movement possible."),

    ("joints-movement", "medium",
     "टखने (ankle) की संधि किस प्रकार की होती है?",
     "What type of joint is the ankle?",
     ["गेंद-गर्त", "अक्ष", "स्थिर", "कबंध"],
     ["Ball and socket", "Pivot", "Fixed", "Hinge"],
     3,
     "टखना पैर को एक ही तल में ऊपर-नीचे मोड़ता है — कबंध संधि।",
     "The ankle moves the foot up and down in one plane — a hinge joint."),

    ("joints-movement", "medium",
     "हथेली पलटने (pronation-supination) की क्रिया में अग्रभुजा की रेडियस और अल्ना अस्थियों के बीच कौन-सी संधि सहायक होती है?",
     "Which joint between the radius and ulna of the forearm assists in turning the palm up and down?",
     ["कबंध", "अक्ष (pivot)", "गेंद-गर्त", "स्थिर"],
     ["Hinge", "Pivot", "Ball and socket", "Fixed"],
     1,
     "रेडियस अल्ना पर अपने अक्ष पर घूमती है (अक्ष संधि), जिससे हथेली ऊपर-नीचे होती है।",
     "The radius pivots over the ulna (pivot joint), letting the palm turn up and down."),

    ("joints-movement", "medium",
     "पक्षियों में उड़ान भरने वाली विशाल पेशियाँ मुख्यतः किस अस्थि से जुड़ी होती हैं?",
     "The huge flight muscles of birds are attached mainly to which bone?",
     ["वक्षास्थि (स्टर्नम)", "फीमर", "पटेला", "क्लाइविकल"],
     ["Sternum (breastbone)", "Femur", "Patella", "Clavicle"],
     0,
     "छाती की वक्षास्थि से उड़ान पेशियाँ जुड़ती हैं; यही अस्थि शरीर के आकार को उड़ान के अनुकूल रखती है।",
     "Flight muscles anchor to the breastbone (sternum), which also shapes the body for flight."),

    ("joints-movement", "easy",
     "शरीर में गति किन संरचनाओं के सम्मिलित कार्य से संभव होती है?",
     "Body movement is possible by the combined action of which structures?",
     ["केवल अस्थियों से", "अस्थियों, संधियों और पेशियों से", "केवल त्वचा से", "केवल रक्त से"],
     ["Bones alone", "Bones, joints and muscles", "Skin alone", "Blood alone"],
     1,
     "पेशी संकुचित होकर अस्थि खींचती है और संधि उस खिंचाव को घूमने में बदल देती है — तीनों आवश्यक हैं।",
     "Muscles contract and pull bones, and joints convert that pull into rotation — all three are essential."),

    ("joints-movement", "medium",
     "किस संधि में एक अस्थि अपने ही अक्ष पर दूसरी अस्थि के चारों ओर घूमती है?",
     "In which joint does one bone rotate on its own axis around another bone?",
     ["गेंद-गर्त", "अक्ष (pivot)", "स्थिर", "फिसलनी"],
     ["Ball and socket", "Pivot", "Fixed", "Gliding"],
     1,
     "अक्ष संधि में घूर्णन एक ही अक्ष पर होता है, जैसा गर्दन या अग्रभुजा में होता है।",
     "In a pivot joint, rotation occurs around a single axis, as in the neck or forearm."),

    ("joints-movement", "medium",
     "पसलियाँ उरोस्थि (sternum) से जुड़ती हैं — यह जोड़ कितनी गति देता है?",
     "The ribs join the sternum — how much movement does this junction allow?",
     ["अचल", "अल्प चलायमान (slightly movable)", "पूर्ण चलायमान गेंद-गर्त", "कोई संधि नहीं होती"],
     ["Immovable", "Slightly movable", "Freely movable ball and socket", "No joint exists"],
     1,
     "पसलियाँ उरोस्थि से उपास्थि के माध्यम से जुड़ती हैं; यह जोड़ अल्प गति देता है जो श्वसन के लिए पर्याप्त है।",
     "Ribs join the sternum via cartilage; this slightly movable joint gives just enough play for breathing."),

    ("joints-movement", "medium",
     "हम कंधे को गोलाकार घुमा सकते हैं परंतु कोहनी को पूर्ण वृत्त में नहीं — कारण क्या है?",
     "We can swing the shoulder in a full circle but not the elbow — why?",
     ["कोहनी की कबंध संधि केवल एक ही तल में गति करती है", "कोहनी में पेशी नहीं होती", "कंधे में अस्थियाँ अधिक नर्म होती हैं", "कोहनी की उपास्थि मृत होती है"],
     ["The elbow's hinge joint moves in only one plane", "The elbow has no muscles", "The shoulder bones are softer", "The elbow cartilage is dead"],
     0,
     "कंधा गेंद-गर्त संधि है — सभी दिशाओं में घूमता है; कोहनी कबंध संधि है — केवल एक तल में मुड़ती है।",
     "The shoulder is a ball-and-socket joint rotating in all directions; the elbow is a hinge bending in one plane."),

    # ---------------- muscular-nervous-tissue (20) ----------------
    ("muscular-nervous-tissue", "easy",
     "ऐच्छिक (voluntary) रेखित पेशियाँ मुख्यतः कहाँ जुड़ी होती हैं?",
     "Where are voluntary striated muscles mainly attached?",
     ["अस्थियों से", "हृदय से", "आँत की दीवार से", "रुधिर वाहिकाओं से"],
     ["To bones", "To the heart", "To the intestinal wall", "To blood vessels"],
     0,
     "रेखित पेशियाँ अस्थियों से जुड़ी होती हैं और हमारी इच्छा से संकुचित होती हैं — जैसे हाथ-पैर की पेशियाँ।",
     "Striated muscles attach to bones and contract at our will — like the muscles of the limbs."),

    ("muscular-nervous-tissue", "medium",
     "आँत में भोजन आगे बढ़ता रहता है — यह गति किसके कारण संभव होती है?",
     "Food keeps moving forward inside the intestine — which tissue makes this possible?",
     ["भित्ति में रेखित पेशियों के कारण", "भित्ति में अरेखित पेशियों की लहरदार संकुचन-क्रिया के कारण", "रक्त वाहिकाओं के दबाव के कारण", "भोजन नली की उपकला के स्राव के कारण"],
     ["Due to striated muscles in the wall", "Due to wave-like contractions of smooth (unstriated) muscles in the wall", "Due to pressure of blood vessels", "Due to secretion of the lining epithelium"],
     1,
     "अरेखित पेशियाँ लहर की तरह क्रमशः संकुचित होती हैं — यही नाल-संचालन (peristalsis) भोजन को नीचे धकेलता है।",
     "Smooth muscles contract in a wave — this peristalsis pushes the food onward."),

    ("muscular-nervous-tissue", "easy",
     "हमारी इच्छा से रुक-चल सकने वाली धड़कन नहीं होती — इसका कारण हृदय की पेशी की कौन-सी प्रकृति है?",
     "The heartbeat cannot be started or stopped at will — which nature of heart muscle explains this?",
     ["वह ऐच्छिक (voluntary) पेशी है", "वह अनैच्छिक (involuntary) पेशी है", "वह उपकला ऊतक है", "वह तंत्रिका ऊतक है"],
     ["It is a voluntary muscle", "It is an involuntary muscle", "It is epithelial tissue", "It is nervous tissue"],
     1,
     "हृदयी पेशी अनैच्छिक है — वह अपने आप, नियमित लय में संकुचित होती रहती है; हम उसे इच्छा से नहीं रोक सकते।",
     "Cardiac muscle is involuntary — it beats automatically in a set rhythm and cannot be willed to stop."),

    ("muscular-nervous-tissue", "medium",
     "हृदयी (cardiac) पेशी की कोशिकाएँ कैसी होती हैं?",
     "How are the cells of cardiac muscle?",
     ["अनैच्छिक, रेखित और शाखायुक्त (branched)", "ऐच्छिक और अशाखित", "अरेखित और बहुकेंद्रकी", "मृत और केंद्रक-रहित"],
     ["Involuntary, striated and branched", "Voluntary and unbranched", "Unstriated and multinucleate", "Dead and without nuclei"],
     0,
     "हृदयी पेशी कोशिकाएँ रेखित तो हैं पर शाखायुक्त होती हैं और आपस में जुड़ी होती हैं; नियंत्रण अनैच्छिक है।",
     "Cardiac muscle cells are striated but branched and interconnected; their control is involuntary."),

    ("muscular-nervous-tissue", "medium",
     "अरेखित (smooth) पेशी की कोशिका का आकार कैसा होता है?",
     "What is the shape of a smooth (unstriated) muscle cell?",
     ["लंबी, बेलनाकार और बहुकेंद्रकी", "तर्कुएकार (spindle-shaped) और एककेंद्रकी", "शाखायुक्त और चपटी", "गोल और केंद्रकहीन"],
     ["Long, cylindrical and multinucleate", "Spindle-shaped and uninucleate", "Branched and flat", "Round and enucleate"],
     1,
     "अरेखित पेशी की कोशिकाएँ दोनों सिरों पर नुकीली, बीच में चौड़ी — तर्कुए सी — और एक ही केंद्रक वाली होती हैं।",
     "Smooth muscle cells are pointed at both ends, widest in the middle — spindle-like — with a single nucleus."),

    ("muscular-nervous-tissue", "hard",
     "रेखित (striated) ऐच्छिक पेशी की कोशिकाएँ कैसी होती हैं?",
     "How are the cells of voluntary striated muscle?",
     ["लंबी, बेलनाकार, अशाखित और बहुकेंद्रकी", "छोटी, तर्कुएकार और एककेंद्रकी", "शाखायुक्त, चपटी और एककेंद्रकी", "गोल, केंद्रक-रहित और मृत"],
     ["Long, cylindrical, unbranched and multinucleate", "Short, spindle-shaped and uninucleate", "Branched, flat and uninucleate", "Round, enucleate and dead"],
     0,
     "रेखित पेशी तंतु बहुत लंबे बेलनाकार कोशिकाएँ हैं जिनमें कई केंद्रक परिधि की ओर रहते हैं।",
     "Striated muscle fibres are very long cylindrical cells with many nuclei placed towards the periphery."),

    ("muscular-nervous-tissue", "easy",
     "पेशी अस्थि को खींचती है — यह बल किस संरचना के द्वारा अस्थि तक पहुँचता है?",
     "A muscle pulls on a bone — through which structure is this force transmitted to the bone?",
     ["लिगामेंट", "टेंडन", "उपास्थि", "तंत्रिका"],
     ["Ligament", "Tendon", "Cartilage", "Nerve"],
     1,
     "टेंडन पेशी के अंत को अस्थि से जोड़ता है और संकुचन का पूरा बल अस्थि तक स्थानांतरित करता है।",
     "The tendon ties the muscle's end to the bone and transfers the whole force of contraction to it."),

    ("muscular-nervous-tissue", "medium",
     "हृदय की पेशी जीवन भर बिना थके कार्य करती है — इसका कारण क्या है?",
     "The heart muscle works lifelong without tiring — why?",
     ["यह निर्धारित लय में संकुचित होती है और प्रत्येक चक्र में उसे विश्राम-अवधि मिलती है", "यह कभी संकुचित नहीं होती", "उसमें केंद्रक नहीं होते", "वह अस्थि से बनी होती है"],
     ["It contracts in a set rhythm and gets a rest phase in every cycle", "It never contracts", "It has no nuclei", "It is made of bone"],
     0,
     "हृदयी पेशी लयबद्ध संकुचन-विश्राम चक्र में चलती है; हर धड़कन के बीच का विश्राम-क्षण उसे थकने नहीं देता।",
     "Cardiac muscle cycles rhythmically between contraction and rest; the brief rest between beats prevents fatigue."),

    ("muscular-nervous-tissue", "easy",
     "तंत्रिका ऊतक मुख्यतः शरीर के किन भागों में पाया जाता है?",
     "In which parts of the body is nervous tissue mainly found?",
     ["यकृत और फेफड़ों में", "मस्तिष्क, मेरुरज्जु और तंत्रिकाओं में", "आँत और आमाशय में", "त्वचा और बालों में"],
     ["Liver and lungs", "Brain, spinal cord and nerves", "Intestine and stomach", "Skin and hair"],
     1,
     "तंत्रिका ऊतक संचार-तंत्र का आधार है और यह मुख्यतः मस्तिष्क, मेरुरज्जु तथा तंत्रिकाओं में सघन रहता है।",
     "Nervous tissue forms the communication network, concentrated in the brain, spinal cord and nerves."),

    ("muscular-nervous-tissue", "easy",
     "न्यूरॉन में सूचना किस भाग द्वारा ग्रहण की जाती है?",
     "Which part of a neuron receives information?",
     ["डेंड्राइट", "एक्सॉन", "माइलिन म्यान", "साइनैप्स"],
     ["Dendrite", "Axon", "Myelin sheath", "Synapse"],
     0,
     "डेंड्राइट शाखाएँ उद्दीपन ग्रहण कर कोशिका-शरीर तक पहुँचाती हैं।",
     "The dendritic branches pick up stimuli and pass them to the cell body."),

    ("muscular-nervous-tissue", "medium",
     "न्यूरॉन में तंत्रिका आवेग किस क्रम में यात्रा करता है?",
     "In which sequence does a nerve impulse travel through a neuron?",
     ["डेंड्राइट → कोशिका शरीर → एक्सॉन", "एक्सॉन → डेंड्राइट → कोशिका शरीर", "कोशिका शरीर → पेशी → एक्सॉन", "कोई निश्चित क्रम नहीं होता"],
     ["Dendrite → cell body → axon", "Axon → dendrite → cell body", "Cell body → muscle → axon", "There is no fixed sequence"],
     0,
     "आवेग डेंड्राइट से ग्रहण होकर कोशिका-शरीर से होता हुआ एक्सॉन के अंत तक जाता है, जहाँ से वह अगली कोशिका को सौंपा जाता है।",
     "The impulse is received by the dendrite, passes through the cell body and travels to the axon tip, where it is handed to the next cell."),

    ("muscular-nervous-tissue", "medium",
     "'तंत्रिका' (nerve) वास्तव में क्या होती है?",
     "What exactly is a 'nerve'?",
     ["तंत्रिका तंतुओं (एक्सॉन) का बंडल", "एक अकेली कोशिका", "एक प्रकार की पेशी", "एक रक्त वाहिका"],
     ["A bundle of nerve fibres (axons)", "A single cell", "A kind of muscle", "A blood vessel"],
     0,
     "कई लंबे एक्सॉन मिलकर बंडल बनाते हैं जिन्हें तंत्रिका कहा जाता है — जैसे विद्युत के तारों का केबल।",
     "Many long axons bundle together to form a nerve — like a cable of electrical wires."),

    ("muscular-nervous-tissue", "hard",
     "दो न्यूरॉनों के बीच जहाँ आवेग एक से दूसरे में सौंपा जाता है, उस संक्रमण-स्थल को क्या कहते हैं?",
     "What is the junction called where an impulse is passed from one neuron to the next?",
     ["माइलिन म्यान", "सिनैप्स (synapse)", "डेंड्राइट शाखा", "कोशिका शरीर"],
     ["Myelin sheath", "Synapse", "Dendritic branch", "Cell body"],
     1,
     "दो न्यूरॉन के बीच सूक्ष्म अंतराल होता है — सिनैप्स — जहाँ रसायन के द्वारा आवेग अगले न्यूरॉन तक पहुँचता है।",
     "Between two neurons lies a tiny gap — the synapse — where chemicals carry the impulse to the next neuron."),

    ("muscular-nervous-tissue", "medium",
     "न्यूरॉन के कोशिका-शरीर (cyton) मुख्यतः कहाँ स्थित होते हैं?",
     "Where are the cell bodies (cytons) of neurons mainly located?",
     ["मस्तिष्क और मेरुरज्जु में", "रक्त प्लाज्मा में", "त्वचा की बाह्य परत में", "यकृत में"],
     ["In the brain and spinal cord", "In blood plasma", "In the outer skin layer", "In the liver"],
     0,
     "न्यूरॉन के कोशिका-शरीर मस्तिष्क व मेरुरज्जु में सघन रहते हैं, जबकि लंबे एक्सॉन तंत्रिकाओं के रूप में शरीर भर में फैलते हैं।",
     "Neuron cell bodies cluster in the brain and spinal cord, while their long axons run through nerves all over the body."),

    ("muscular-nervous-tissue", "medium",
     "तंत्रिका ऊतक को शरीर का 'दूरसंचार तंत्र' क्यों कहा जाता है?",
     "Why is nervous tissue called the body's 'telecommunication system'?",
     ["क्योंकि यह भोजन भंडारित करता है", "क्योंकि यह रक्त बनाता है", "क्योंकि यह उद्दीपन की सूचना अत्यंत तीव्र गति से दूर तक पहुँचाता है", "क्योंकि यह अस्थियों को जोड़ता है"],
     ["Because it stores food", "Because it makes blood", "Because it carries stimulus information extremely fast over long distances", "Because it joins bones"],
     2,
     "तंत्रिका ऊतक विद्युत-रासायनिक आवेगों से पलक झपकते सूचना शरीर के एक सिरे से दूसरे सिरे तक पहुँचाता है।",
     "Using electro-chemical impulses, nervous tissue relays information from one end of the body to the other in a blink."),

    ("muscular-nervous-tissue", "medium",
     "एक्सॉन के चारों ओर लिपटी माइलिन म्यान का क्या कार्य है?",
     "What is the function of the myelin sheath wrapped around an axon?",
     ["आवेग के तीव्र और सुरक्षित संचरण में सहायक होना", "भोजन बनाना", "पेशी को अस्थि से जोड़ना", "रक्त बनाना"],
     ["It helps in fast and safe transmission of impulses", "It prepares food", "It joins muscle to bone", "It makes blood"],
     0,
     "माइलिन एक विद्युतरोधी (insulating) म्यान है जो आवेग को रास्ते में ऊर्जा-हानि के बिना तेज़ चलाता है।",
     "Myelin is an insulating sheath that speeds impulses along with no loss of energy on the way."),

    ("muscular-nervous-tissue", "medium",
     "मानव शरीर की सबसे लंबी कोशिका कौन-सी मानी जाती है?",
     "Which is considered the longest cell in the human body?",
     ["पेशी तंतु", "रुधिर कणिका", "न्यूरॉन", "एपिडर्मल कोशिका"],
     ["Muscle fibre", "Red blood cell", "Neuron", "Epidermal cell"],
     2,
     "न्यूरॉन का एक्सॉन मीटरों लंबा हो सकता है (जैसे पैर की तंत्रिका में), इसलिए उसे शरीर की सबसे लंबी कोशिका माना जाता है।",
     "A neuron's axon can run for metres (as in leg nerves), making it the longest cell of the body."),

    ("muscular-nervous-tissue", "easy",
     "इनमें से कौन-सी पेशी हमारी इच्छा से गति करती है?",
     "Which of these muscles moves at our will?",
     ["हृदय की पेशी", "आँत की पेशी", "बाँह की पेशी", "रुधिर वाहिका की भित्ति की पेशी"],
     ["Heart muscle", "Intestinal muscle", "Arm muscle", "Blood-vessel wall muscle"],
     2,
     "बाँह की पेशी ऐच्छिक पेशी है — हम चाहें तो बाँह उठाते हैं, चाहें तो नहीं; हृदय, आँत और वाहिकाएँ अनैच्छिक हैं।",
     "The arm muscle is voluntary — we choose to raise the arm; the heart, gut and vessels are involuntary."),

    ("muscular-nervous-tissue", "medium",
     "पेशी-तंतु एक-दूसरे से बंडलों में बंधे रहते हैं; ऐसे पेशी-बंडल बनाने वाला आवरण कौन-सा ऊतक है?",
     "Muscle fibres are bound together in bundles; which tissue wraps such muscle bundles?",
     ["संयोजी ऊतक", "तंत्रिका ऊतक", "उपकला ऊतक", "विभज्योतक"],
     ["Connective tissue", "Nervous tissue", "Epithelial tissue", "Meristematic tissue"],
     0,
     "पेशियों में संयोजी ऊतक की परतें तंतुओं को बंडलों में बाँधती हैं और उनमें वाहिकाएँ-तंत्रिकाएँ भी चलाती हैं।",
     "Sheets of connective tissue bind muscle fibres into bundles and also carry vessels and nerves within."),

    ("muscular-nervous-tissue", "hard",
     "रेखित पेशी में सूक्ष्मदर्शी से दिखने वाली धारियाँ (striations) किसके कारण बनती हैं?",
     "What causes the striations seen under the microscope in striated muscle?",
     ["एक्टिन-मायोसिन प्रोटीन तंतुओं की नियमित व्यवस्था", "वसा की बूंदों की पंक्तियाँ", "रुधिर कणों की परतें", "उपास्थि के वलय"],
     ["Regular arrangement of actin-myosin protein filaments", "Rows of fat droplets", "Layers of blood cells", "Rings of cartilage"],
     0,
     "कोशिका में प्रोटीन तंतु (एक्टिन/मायोसिन) एकांतरित रूप से जमे होते हैं; प्रकाश पड़ने पर यही धारीदार रेखांकन दिखता है।",
     "Actin and myosin filaments alternate regularly inside the cell, creating the striped look under light."),

    # ---------------- organization-repair (25) ----------------
    ("organization-repair", "easy",
     "ऊतक (tissue) से क्या तात्पर्य है?",
     "What is meant by a tissue?",
     ["समान संरचना और कार्य वाली कोशिकाओं का समूह", "भिन्न-भिन्न कोशिकाओं का मिश्रण", "एक अकेली कोशिका", "अनेक अंगों का समूह"],
     ["A group of cells with similar structure and function", "A mixture of dissimilar cells", "A single cell", "A collection of many organs"],
     0,
     "एक ही कार्य के लिए विशेषीकृत, समरूप कोशिकाओं के समूह को ऊतक कहते हैं — जैसे पेशी ऊतक, उपकला ऊतक।",
     "A group of similar cells specialised for one function is a tissue — e.g. muscle tissue, epithelial tissue."),

    ("organization-repair", "easy",
     "जीव के शरीर-संगठन में सही क्रम कौन-सा है?",
     "Which is the correct sequence of body organisation in organisms?",
     ["कोशिका → ऊतक → अंग → अंग-तंत्र", "ऊतक → कोशिका → अंग → अंग-तंत्र", "अंग → कोशिका → ऊतक → अंग-तंत्र", "कोशिका → अंग → ऊतक → अंग-तंत्र"],
     ["Cell → tissue → organ → organ system", "Tissue → cell → organ → organ system", "Organ → cell → tissue → organ system", "Cell → organ → tissue → organ system"],
     0,
     "कोशिकाएँ मिलकर ऊतक, ऊतक मिलकर अंग, और अंग मिलकर अंग-तंत्र बनाते हैं — यही संगठन का क्रम है।",
     "Cells form tissues, tissues form organs, and organs form organ systems — this is the hierarchy of organisation."),

    ("organization-repair", "easy",
     "अंग (organ) किसे कहते हैं?",
     "What is an organ?",
     ["केवल एक ही प्रकार के ऊतक का बना भाग", "विभिन्न ऊतकों का संयोजन जो एक विशेष कार्य करता है", "केवल पेशियों का समूह", "केवल रक्त का समूह"],
     ["A part made of only one type of tissue", "A combination of different tissues performing a specific function", "Only a group of muscles", "Only a mass of blood"],
     1,
     "अंग में एक से अधिक प्रकार के ऊतक व्यवस्थित रूप से मिले रहते हैं — जैसे हृदय में पेशी, उपकला, संयोजी और तंत्रिका ऊतक।",
     "An organ contains more than one tissue type arranged together — e.g. the heart has muscular, epithelial, connective and nervous tissue."),

    ("organization-repair", "medium",
     "आमाशय, यकृत और आँत मिलकर मुख्यतः किस अंग-तंत्र के अंग हैं?",
     "Stomach, liver and intestine are mainly organs of which organ system?",
     ["पाचन तंत्र", "श्वसन तंत्र", "उत्सर्जन तंत्र", "परिसंचरण तंत्र"],
     ["Digestive system", "Respiratory system", "Excretory system", "Circulatory system"],
     0,
     "भोजन के पाचन में सहयोगी ये अंग पाचन तंत्र के घटक हैं।",
     "These organs cooperate in digesting food and form parts of the digestive system."),

    ("organization-repair", "easy",
     "निम्न में से कौन-सा पौधे का अंग (organ) है?",
     "Which of the following is a plant organ?",
     ["जाइलम", "मृदूतक", "पत्ती", "द्वार कोशिका"],
     ["Xylem", "Parenchyma", "Leaf", "Guard cell"],
     2,
     "जड़, तना, पत्ती, फूल पौधे के अंग हैं; जाइलम ऊतक है, मृदूतक ऊतक है और द्वार कोशिका केवल एक कोशिका।",
     "Root, stem, leaf and flower are plant organs; xylem and parenchyma are tissues, a guard cell is just one cell."),

    ("organization-repair", "medium",
     "निम्न में से कौन-सा ऊतक है, अंग नहीं?",
     "Which of the following is a tissue, not an organ?",
     ["जड़", "पत्ती", "जाइलम", "फूल"],
     ["Root", "Leaf", "Xylem", "Flower"],
     2,
     "जाइलम कोशिकाओं का एक समूह (ऊतक) है जो केवल जल-परिवहन का कार्य करता है; जड़, पत्ती, फूल विभिन्न ऊतकों से बने अंग हैं।",
     "Xylem is a group of cells (tissue) doing only water transport; root, leaf and flower are organs built of many tissues."),

    ("organization-repair", "easy",
     "बहुकोशिकीय जीवों में 'श्रम-विभाजन' (division of labour) से क्या तात्पर्य है?",
     "What is meant by 'division of labour' in multicellular organisms?",
     ["प्रत्येक कोशिका-समूह का अपना विशेष कार्य होना", "सभी कोशिकाओं का एक ही कार्य करना", "कोशिकाओं का कार्य न करना", "केवल प्रजनन कोशिकाओं का कार्य करना"],
     ["Each cell group having its own special function", "All cells doing the same job", "Cells doing no work", "Only reproductive cells working"],
     0,
     "विभिन्न ऊतक विभिन्न कार्य विशेषज्ञता से करते हैं — पेशी गति, तंत्रिका संचार, रक्त परिवहन — यही श्रम-विभाजन है।",
     "Different tissues specialise in different jobs — muscle for movement, nerve for signalling, blood for transport — this is division of labour."),

    ("organization-repair", "medium",
     "पौधों में वृद्धि किन भागों तक सीमित रहती है?",
     "In plants, growth remains restricted to which parts?",
     ["सम्पूर्ण शरीर में समान रूप से", "केवल शीर्ष (tips) जैसे विशिष्ट वृद्धि-क्षेत्रों में", "केवल पत्तियों में", "कहीं भी नहीं"],
     ["Uniformly all over the body", "Only in specific growing regions such as tips", "Only in the leaves", "Nowhere at all"],
     1,
     "पौधों में विभज्योतक केवल कुछ निश्चित क्षेत्रों (जड़-तने के शीर्ष, पर्वाधार) में होता है, इसलिए वृद्धि स्थानीयकृत रहती है; प्राणियों में वृद्धि अधिक समव्यापी होती है।",
     "In plants, meristem occurs only at fixed spots (root/shoot tips, node bases), so growth is localised; in animals growth is more uniform."),

    ("organization-repair", "medium",
     "स्थिर पौधों और चल प्राणियों के ऊतकों में भिन्नता का मूल कारण क्या है?",
     "What is the basic reason for the difference between the tissues of stationary plants and mobile animals?",
     ["दोनों की जीवन-शैली भिन्न है — पौधे को सहारे और प्राणी को गति के ऊतक चाहिए", "दोनों के ऊतक पूर्णतः समान हैं", "पौधों में ऊतक होते ही नहीं", "प्राणियों में ऊतक होते ही नहीं"],
     ["Their life modes differ — plants need supporting tissues, animals need tissues for movement", "Their tissues are identical", "Plants have no tissues", "Animals have no tissues"],
     0,
     "पौधा एक स्थान पर जड़ से स्थिर रहता है अतः उसे दृढ़ सहारा देने वाले ऊतक चाहिए; प्राणी भोजन-रक्षा हेतु घूमते हैं अतः उन्हें गति व संचार के ऊतक चाहिए।",
     "A plant is anchored and needs strong support tissues; animals roam for food and safety and need tissues for movement and quick communication."),

    ("organization-repair", "medium",
     "त्वचा को नीचे की पेशियों से जोड़ने वाला ढीला-ढाला भराव ऊतक कौन-सा है?",
     "Which loose packing tissue connects the skin to the muscles beneath?",
     ["विदरक (areolar) ऊतक", "अस्थि", "उपास्थि", "तंत्रिका ऊतक"],
     ["Areolar tissue", "Bone", "Cartilage", "Nervous tissue"],
     0,
     "विदरक ऊतक त्वचा व पेशियों के बीच का लचीला जोड़ और भराव है जो संक्रमण से लड़ने में भी सहायक है।",
     "Areolar tissue is the flexible link and filler between skin and muscle that also helps fight infection."),

    ("organization-repair", "hard",
     "बच्चों की अस्थियों के सिरों पर लंबाई बढ़ाने वाला क्षेत्र किस ऊतक से बना होता है?",
     "The length-growing region at the ends of children's bones is made of which tissue?",
     ["वसा ऊतक", "उपास्थि (कार्टिलेज)", "कॉर्क", "रुधिर ऊतक"],
     ["Adipose tissue", "Cartilage", "Cork", "Blood tissue"],
     1,
     "लंबी अस्थियों के सिरों पर उपास्थि की वृद्धि-पट्टिका रहती है जो नई कोशिकाएँ जोड़ती है; ये कोशिकाएँ बाद में अस्थीभूत हो जाती हैं।",
     "A cartilaginous growth plate at bone ends adds new cells that later ossify, lengthening the bone."),

    ("organization-repair", "medium",
     "तंत्रिका कोशिकाओं की गंभीर क्षति के बाद कार्य अक्सर स्थायी रूप से बिगड़ जाता है — कारण?",
     "Why does function often remain permanently impaired after serious damage to nerve cells?",
     ["क्योंकि नए न्यूरॉन बनाने की उनकी क्षमता लगभग नहीं के बराबर है", "क्योंकि न्यूरॉन बहुत छोटे होते हैं", "क्योंकि न्यूरॉन मृत होते हैं", "क्योंकि उनमें कोई कार्य नहीं होता"],
     ["Because their ability to form new neurons is almost nil", "Because neurons are very small", "Because neurons are dead", "Because they have no function"],
     0,
     "परिपक्व न्यूरॉन प्रायः विभाजित नहीं होते; एक बार नष्ट होने पर उनका पुनर्निर्माण सामान्यतः नहीं हो पाता — इसीलिए मेरुरज्जु की गंभीर चोटें स्थायी होती हैं।",
     "Mature neurons rarely divide; once destroyed they are generally not replaced — which is why serious spinal injuries are permanent."),

    ("organization-repair", "medium",
     "निम्न में से कौन-सा उदाहरण अंग-तंत्र (organ system) का है?",
     "Which of the following is an example of an organ system?",
     ["हृदय", "परिसंचरण तंत्र", "रुधिर", "न्यूरॉन"],
     ["Heart", "Circulatory system", "Blood", "Neuron"],
     1,
     "हृदय अंग है, रुधिर ऊतक और न्यूरॉन कोशिका; हृदय+वाहिकाएँ+रक्त मिलकर परिसंचरण तंत्र बनाते हैं।",
     "Heart is an organ, blood a tissue, neuron a cell; heart + vessels + blood together form the circulatory system."),

    ("organization-repair", "medium",
     "टेंडन और लिगामेंट दोनों किस वर्ग के ऊतक हैं?",
     "Tendons and ligaments both belong to which class of tissue?",
     ["उपकला ऊतक", "संयोजी ऊतक", "पेशी ऊतक", "तंत्रिका ऊतक"],
     ["Epithelial tissue", "Connective tissue", "Muscular tissue", "Nervous tissue"],
     1,
     "दोनों संघन तंतुमय संयोजी ऊतक हैं — टेंडन में कोलेजन, लिगामेंट में कोलेजन सहित इलास्टिन अधिक।",
     "Both are dense fibrous connective tissues — tendon collagen-rich, ligament collagen plus abundant elastin."),

    ("organization-repair", "medium",
     "पत्ती की नसों (veins) में जाइलम-फ्लोएम का साथ-साथ बंडल किस नाम से जाना जाता है?",
     "The xylem-phloem bundles running together in leaf veins are known as what?",
     ["संवहन बंडल (vascular bundle)", "रंध्र", "क्यूटिकुल", "माइलिन"],
     ["Vascular bundle", "Stomata", "Cuticle", "Myelin"],
     0,
     "जाइलम और फ्लोएम का संयुक्त बंडल संवहन बंडल कहलाता है जो पत्तियों में नसों के रूप में स्पष्ट दिखता है।",
     "A combined strand of xylem and phloem is a vascular bundle, visible in leaves as veins."),

    ("organization-repair", "medium",
     "त्वचा को शरीर का सबसे बड़ा अंग क्यों माना जाता है?",
     "Why is skin considered the largest organ of the body?",
     ["क्योंकि वह केवल एक ऊतक से बनी है", "क्योंकि वह विभिन्न ऊतकों से बनी है और उसका क्षेत्रफल सबसे अधिक है", "क्योंकि वह सबसे मोटी होती है", "क्योंकि वह रक्त बनाती है"],
     ["Because it is made of only one tissue", "Because it is built of several tissues and has the largest surface area", "Because it is the thickest", "Because it produces blood"],
     1,
     "त्वचा में उपकला, संयोजी, स्वेद-ग्रंथि, पेशी व तंत्रिका ऊतक मिले हैं और वह पूरे शरीर को ढकती है — अतः सबसे बड़ा अंग।",
     "Skin combines epithelial, connective, glandular, muscular and nervous tissues and covers the whole body — the largest organ."),

    ("organization-repair", "hard",
     "इमारती लकड़ी (काष्ठ/wood) का निर्माण मुख्यतः किसके द्वारा होता है?",
     "What is timber (wood) mainly formed of?",
     ["पार्श्व विभज्योतक द्वारा बनाए गए द्वितीयक जाइलम द्वारा", "पत्तियों के एपिडर्मिस द्वारा", "फ्लोएम द्वारा", "कॉर्क कोशिकाओं द्वारा"],
     ["Secondary xylem produced by the lateral meristem", "Leaf epidermis", "Phloem", "Cork cells"],
     0,
     "कैम्बियम (पार्श्व विभज्योतक) वर्षों में भीतर की ओर विपुल द्वितीयक जाइलम जोड़ता है — यही संचित लकड़ी है।",
     "The cambium (lateral meristem) lays down masses of secondary xylem inward over the years — this accumulated wood is timber."),

    ("organization-repair", "easy",
     "जड़, तना, पत्ती और फूल पौधे की किस श्रेणी में आते हैं?",
     "Root, stem, leaf and flower fall under which category in a plant?",
     ["ऊतक", "अंग", "कोशिकाएँ", "कोशिकांग"],
     ["Tissues", "Organs", "Cells", "Organelles"],
     1,
     "ये सभी विभिन्न ऊतकों से बने पौधे के अंग हैं।",
     "Each is a plant organ built from several different tissues."),

    ("organization-repair", "hard",
     "मानव भ्रूण का प्रारंभिक कंकाल मुख्यतः किससे बना होता है?",
     "The early skeleton of a human embryo is mainly made of what?",
     ["उपास्थि, जो बाद में अस्थीभूत (ossify) हो जाती है", "दृढ़ ऊतक", "कॉर्क", "वसा ऊतक"],
     ["Cartilage, which later ossifies into bone", "Sclerenchyma", "Cork", "Adipose tissue"],
     0,
     "भ्रूण का अधिकांश कंकाल उपास्थि का होता है; विकास के साथ इसमें कैल्शियम जमकर अस्थि बन जाती है — कुछ उपास्थि (नाक, कान, संधि-सतह) जस की तसा रह जाती है।",
     "Most of the embryonic skeleton is cartilage; during development calcium deposits turn it to bone — some cartilage (nose, ear, joint surfaces) stays as it is."),

    ("organization-repair", "medium",
     "आमाशय जैसे अंग में कितने प्रकार के ऊतक एक साथ कार्य करते हैं?",
     "How many kinds of tissue work together in an organ like the stomach?",
     ["केवल एक", "केवल दो", "अनेक — उपकला, पेशी, संयोजी और तंत्रिका ऊतक", "कोई नहीं"],
     ["Only one", "Only two", "Several — epithelial, muscular, connective and nervous tissues", "None"],
     2,
     "आमाशय की भित्ति में ग्रंथिल उपकला (अम्ल-रस स्राव), चिकनी पेशियाँ (मिश्रण), संयोजी ऊतक (आवरण-वाहिकाएँ) और तंत्रिका ऊतक (नियंत्रण) साथ चलते हैं।",
     "The stomach wall unites glandular epithelium (acid/juice secretion), smooth muscle (churning), connective tissue (cover and vessels) and nervous tissue (control)."),

    ("organization-repair", "medium",
     "अस्थि को 'अंग' कहा जा सकता है — क्यों?",
     "A bone can be called an 'organ' — why?",
     ["क्योंकि उसमें अस्थि ऊतक के साथ वाहिकाएँ, तंत्रिकाएँ और मज्जा जैसे विविध ऊतक होते हैं", "क्योंकि वह एक अकेली कोशिका है", "क्योंकि उसमें कोई ऊतक नहीं होता", "क्योंकि वह केवल कैल्शियम का टुकड़ा है"],
     ["Because along with bone tissue it contains vessels, nerves and marrow — several diverse tissues", "Because it is a single cell", "Because it has no tissue", "Because it is just a piece of calcium"],
     0,
     "हड्डी में अस्थि ऊतक, रक्त वाहिकाएँ, तंत्रिकाएँ, उपास्थि और मज्जा — अनेक ऊतक होते हैं जो मिलकर एक इकाई कार्य करते हैं; यही अंग की परिभाषा है।",
     "A bone contains bone tissue, blood vessels, nerves, cartilage and marrow — many tissues working as one unit, which is the definition of an organ."),

    ("organization-repair", "medium",
     "निम्न में से कौन-सा उदाहरण ऊतक-स्तर (tissue level) का है, अंग-स्तर का नहीं?",
     "Which of the following is an example of the tissue level, not the organ level?",
     ["हृदय", "रुधिर", "यकृत", "पाचन तंत्र"],
     ["Heart", "Blood", "Liver", "Digestive system"],
     1,
     "रुधिर एक ऊतक है (कोशिकाएँ द्रव मैट्रिक्स में); हृदय-यकृत अंग हैं और पाचन तंत्र अंग-तंत्र।",
     "Blood is a tissue (cells in fluid matrix); heart and liver are organs, the digestive tract is a system."),

    ("organization-repair", "medium",
     "किसी अंग की क्षमता उसके भीतर कार्य करने वाले विभिन्न ऊतकों के बीच किस बात पर निर्भर करती है?",
     "The capability of an organ depends on what among its different working tissues?",
     ["उनके पारस्परिक सहयोग और समन्वय पर", "केवल एक ऊतक की उपस्थिति पर", "केवल रक्त की मात्रा पर", "अंग की उम्र पर"],
     ["Their mutual cooperation and coordination", "The presence of just one tissue", "Only the amount of blood", "The age of the organ"],
     0,
     "हृदय तभी धड़कता है जब पेशी, तंत्रिका व संयोजी ऊतक समन्वित रहते हैं; कोई एक अकेला अपूर्ण है।",
     "The heart beats only while its muscle, nerve and connective tissues stay coordinated; any one alone is incomplete."),

    ("organization-repair", "medium",
     "अस्थिमज्जा प्रत्यारोपण (bone marrow transplant) कुछ रोगों में जीवनरक्षक होता है — ऐसे रोग कौन-से हैं?",
     "Bone marrow transplants can be life-saving in certain diseases — which ones?",
     ["रक्त-निर्माण से जुड़े रोग जैसे ल्यूकेमिया (रक्त कैंसर)", "अस्थि भंग", "मोच (sprain)", "उपास्थि का कैंसर"],
     ["Blood-forming diseases such as leukaemia (blood cancer)", "Bone fracture", "Sprain", "Cancer of cartilage"],
     0,
     "लाल अस्थिमज्जा ही रक्त कणिकाएँ बनाती है; जब यह तंत्र रोग से नष्ट हो जाए तो स्वस्थ मज्जा प्रत्यारोपित कर रक्त-निर्माण पुनः चालू किया जा सकता है।",
     "Red marrow makes blood cells; when disease destroys this system, transplanting healthy marrow can restart blood production."),

    ("organization-repair", "medium",
     "बहुकोशिकीय जीवों में कोशिकाओं का विशेषीकरण (specialisation) लाभदायक क्यों है?",
     "Why is specialisation of cells beneficial in multicellular organisms?",
     ["इससे प्रत्येक कार्य अधिक कुशलता से होता है", "इससे ऊर्जा की खपत घट जाती है", "इसका कोई लाभ नहीं है", "इससे जीव की वृद्धि रुक जाती है"],
     ["Each task is then performed more efficiently", "Energy consumption falls", "There is no benefit", "The organism stops growing"],
     0,
     "एक ही कार्य पर केंद्रित कोशिकाएँ उसे अधिक दक्षता से करती हैं — जैसे RBC केवल गैस-परिवहन, पेशी केवल संकुचन — इससे पूरा जीव कुशल होता है।",
     "Cells focused on a single task do it better — RBCs solely carry gases, muscles solely contract — making the whole organism efficient."),
]
