# -*- coding: utf-8 -*-
"""B02 'Tissues & Body Structure' — Part 1 data (75 items).
Order: skeletal-system (30), advanced-plant-tissues (25), epithelial-connective (20 of 25).
Tuple: (topic, difficulty, q_hi, q_en, options_hi[4], options_en[4], correct_idx, exp_hi, exp_en)
"""

PART1 = [
    # ---------------- skeletal-system (30) ----------------
    ("skeletal-system", "easy",
     "वयस्क मानव के शरीर में कुल कितनी अस्थियाँ (हड्डियाँ) होती हैं?",
     "How many bones are there in total in an adult human body?",
     ["306", "206", "216", "106"],
     ["306", "206", "216", "106"],
     1,
     "वयस्क मानव के कंकाल में 206 अस्थियाँ होती हैं; नवजात शिशु में यह संख्या लगभग 300 होती है जो बाद में जुड़कर घट जाती है।",
     "The adult human skeleton has 206 bones; a newborn has about 300, which later fuse to reduce the count."),

    ("skeletal-system", "easy",
     "कपाल (खोपड़ी) का मुख्य कार्य क्या है?",
     "What is the main function of the skull (cranium)?",
     ["भोजन को पचाना", "मस्तिष्क की रक्षा करना", "रक्त बनाना", "श्वसन में सहायता"],
     ["Digesting food", "Protecting the brain", "Producing blood", "Helping in breathing"],
     1,
     "कपाल एक कठोर अस्थि-पिंजरा है जो मस्तिष्क को चोट से बचाता है।",
     "The skull is a hard bony box that shields the brain from injury."),

    ("skeletal-system", "easy",
     "पसलियों का पिंजरा (रिब केज) मुख्यतः किन अंगों की रक्षा करता है?",
     "Which organs does the rib cage mainly protect?",
     ["मस्तिष्क", "रीढ़ की हड्डी", "हृदय और फेफड़े", "यकृत और आमाशय"],
     ["Brain", "Spinal cord", "Heart and lungs", "Liver and stomach"],
     2,
     "छाती की गुहा में स्थित हृदय और फेफड़े पसलियों के पिंजरे द्वारा सुरक्षित रहते हैं।",
     "The heart and lungs in the chest cavity are protected by the rib cage."),

    ("skeletal-system", "easy",
     "रीढ़ की हड्डी (कशेरुक स्तंभ) की नली के भीतर कौन-सा भाग सुरक्षित रहता है?",
     "Which structure remains protected inside the canal of the vertebral column?",
     ["मेरुरज्जु (स्पाइनल कॉर्ड)", "शुद्ध रक्त", "वायु नली", "भोजन नली"],
     ["Spinal cord", "Pure blood", "Windpipe", "Food pipe"],
     0,
     "कशेरुक स्तंभ की केंद्रीय नली में मेरुरज्जु रहती है, जिसकी रक्षा यह अस्थि करती है।",
     "The spinal cord runs through the central canal of the vertebral column, protected by the bone."),

    ("skeletal-system", "medium",
     "मानव में पसलियों के जोड़े (pairs of ribs) कितने होते हैं?",
     "How many pairs of ribs are present in humans?",
     ["10", "11", "12", "14"],
     ["10", "11", "12", "14"],
     2,
     "मनुष्य में 12 जोड़े यानी कुल 24 पसलियाँ होती हैं।",
     "Humans have 12 pairs of ribs, i.e. 24 ribs in total."),

    ("skeletal-system", "medium",
     "मानव रीढ़ की हड्डी में कशेरुकाओं (vertebrae) की संख्या कितनी होती है?",
     "How many vertebrae are present in the human vertebral column?",
     ["30", "32", "33", "36"],
     ["30", "32", "33", "36"],
     2,
     "मानव कशेरुक स्तंभ में 33 कशेरुकाएँ होती हैं, जो गर्दन से लेकर पुच्छ तक विभाजित हैं।",
     "The human vertebral column has 33 vertebrae, arranged from the neck down to the tailbone."),

    ("skeletal-system", "easy",
     "मानव शरीर की सबसे लंबी अस्थि कौन-सी है?",
     "Which is the longest bone in the human body?",
     ["प्रगंडिका (रेडियस)", "जंघिका (फीमर)", "अंगुली की अस्थि", "अनुजंघिका (टिबिया)"],
     ["Radius", "Femur", "Finger bone", "Tibia"],
     1,
     "जाँघ की अस्थि जंघिका (फीमर) शरीर की सबसे लंबी और सबसे मजबूत अस्थि है।",
     "The thigh bone (femur) is the longest and strongest bone of the body."),

    ("skeletal-system", "medium",
     "शरीर की सबसे छोटी अस्थि कहाँ पाई जाती है?",
     "Where is the smallest bone of the body found?",
     ["कान के मध्य भाग में (स्टेपीज)", "नाक में", "कलाई में", "आँख की कोटर में"],
     ["In the middle ear (stapes)", "In the nose", "In the wrist", "In the eye socket"],
     0,
     "स्टेपीज कान के मध्य भाग की सबसे छोटी अस्थि है और यही शरीर की सबसे छोटी अस्थि भी है।",
     "The stapes in the middle ear is the smallest bone of the human body."),

    ("skeletal-system", "medium",
     "लाल रक्त कणिकाओं (RBC) का निर्माण मुख्यतः कहाँ होता है?",
     "Where are red blood cells (RBCs) mainly produced?",
     ["यकृत में", "अस्थिमज्जा (बोन मैरो) में", "प्लीहा में", "फेफड़ों में"],
     ["In the liver", "In the bone marrow", "In the spleen", "In the lungs"],
     1,
     "लंबी अस्थियों की लाल अस्थिमज्जा रक्त कणिकाओं का निर्माण करती है — यह कंकाल का एक महत्वपूर्ण कार्य है।",
     "The red bone marrow inside long bones produces blood cells — an important function of the skeleton."),

    ("skeletal-system", "easy",
     "कशेरुक स्तंभ का मुख्य कार्य क्या है?",
     "What is the main function of the vertebral column?",
     ["रक्त बनाना", "शरीर को सहारा देना और मेरुरज्जु की रक्षा करना", "भोजन पचाना", "वायु को शुद्ध करना"],
     ["Producing blood", "Supporting the body and protecting the spinal cord", "Digesting food", "Purifying air"],
     1,
     "रीढ़ की हड्डी धड़ का मुख्य सहारा है और उसकी नली मेरुरज्जु की रक्षा करती है।",
     "The backbone supports the trunk and its canal protects the spinal cord."),

    ("skeletal-system", "medium",
     "कंधे की अस्थियाँ मिलकर कौन-सी संरचना बनाती हैं जो बाँह को धड़ से जोड़ती है?",
     "The shoulder bones together form which structure that attaches the arm to the trunk?",
     ["श्रोणि मेखला", "कंधा मेखला (अंस मेखला)", "उरोस्थि", "कशेरुक स्तंभ"],
     ["Pelvic girdle", "Pectoral (shoulder) girdle", "Sternum", "Vertebral column"],
     1,
     "कंधे की प्रगंडिका व कंठास्थि मिलकर अंस मेखला बनाती हैं जिससे बाँह जुड़ती है।",
     "The scapula and clavicle form the pectoral girdle to which the arm attaches."),

    ("skeletal-system", "medium",
     "टाँगों को धड़ से जोड़ने वाली मेखला कौन-सी है?",
     "Which girdle attaches the legs to the trunk?",
     ["अंस मेखला", "उरोस्थि", "श्रोणि मेखला (पेल्विक)", "कंठास्थि"],
     ["Pectoral girdle", "Sternum", "Pelvic girdle", "Clavicle"],
     2,
     "श्रोणि मेखला दोनों टाँगों की अस्थियों को रीढ़ की हड्डी से जोड़ती है।",
     "The pelvic girdle connects the bones of both legs to the vertebral column."),

    ("skeletal-system", "easy",
     "नाक की नोक और कान का ऊपरी भाग मुलायम-लचीला क्यों होता है?",
     "Why are the tip of the nose and the upper ear soft and flexible?",
     ["वहाँ अस्थि होती है", "वहाँ पेशी होती है", "वहाँ उपास्थि (कार्टिलेज) होती है", "वहाँ केवल त्वचा होती है"],
     ["They contain bone", "They contain muscle", "They contain cartilage", "They contain only skin"],
     2,
     "इन स्थानों पर लचीली उपास्थि पाई जाती है, इसीलिए वे दबाने पर मुड़ जाते हैं।",
     "These parts contain flexible cartilage, so they bend when pressed."),

    ("skeletal-system", "medium",
     "अस्थियाँ कठोर और दृढ़ क्यों होती हैं?",
     "Why are bones hard and rigid?",
     ["उनमें वसा भरी होती है", "उनमें जल अधिक होता है", "उनमें कैल्शियम लवण जमा होते हैं", "उनमें वायु भरी होती है"],
     ["They are filled with fat", "They contain excess water", "They contain deposited calcium salts", "They are filled with air"],
     2,
     "अस्थियों की मैट्रिक्स में कैल्शियम लवण जमा होने से वे कठोर होती हैं।",
     "Deposits of calcium salts in the bone matrix make bones hard."),

    ("skeletal-system", "medium",
     "एक्स-रे चित्र में अस्थियाँ बाकी भागों की तुलना में स्पष्ट क्यों दिखती हैं?",
     "Why do bones appear clearly in an X-ray image compared to other body parts?",
     ["अस्थियाँ सफेद रंग की होती हैं", "अस्थियों में कैल्शियम होने से वे X-रे किरणों को रोकती/अवशोषित करती हैं", "अस्थियों में रक्त सबसे अधिक होता है", "अस्थियाँ हमेशा गतिशील रहती हैं"],
     ["Bones are white in colour", "Calcium in bones blocks/absorbs X-rays", "Bones contain the most blood", "Bones are always moving"],
     1,
     "अस्थियों का कैल्शियम X-रे किरणों को अवशोषित कर लेता है, इसलिए चित्र पर वे गहरी और स्पष्ट दिखती हैं।",
     "Calcium in bones absorbs X-rays, so bones stand out sharply on the image."),

    ("skeletal-system", "medium",
     "उड़ने के अनुकूलन के रूप में पक्षियों की अस्थियाँ कैसी होती हैं?",
     "As an adaptation for flight, how are the bones of birds?",
     ["ठोस और भारी", "बहुत लंबी और मोटी", "अत्यंत चौड़ी और समतल", "खोखली और हल्की"],
     ["Solid and heavy", "Very long and thick", "Extremely broad and flat", "Hollow and light"],
     3,
     "पक्षियों की अस्थियाँ खोखली (वायुयुक्त गुहाओं वाली) होती हैं, जिससे शरीर का भार कम रहता है और उड़ना सरल हो जाता है।",
     "Bird bones are hollow (with air cavities), reducing body weight and making flight easier."),

    ("skeletal-system", "medium",
     "मनुष्य की गर्दन (सर्विकल क्षेत्र) में कशेरुकाओं की संख्या कितनी होती है?",
     "How many vertebrae are present in the human neck (cervical region)?",
     ["5", "7", "12", "33"],
     ["5", "7", "12", "33"],
     1,
     "गर्दन में 7 सर्विकल कशेरुकाएँ होती हैं; अधिकांश स्तनधारियों में यही संख्या होती है।",
     "The neck has 7 cervical vertebrae; most mammals share this same number."),

    ("skeletal-system", "medium",
     "छाती के मध्य स्थित समतल अस्थि का नाम क्या है?",
     "What is the name of the flat bone located in the middle of the chest?",
     ["स्कैपुला", "उरोस्थि (स्टर्नम)", "फीमर", "पटेला"],
     ["Scapula", "Sternum (breastbone)", "Femur", "Patella"],
     1,
     "उरोस्थि छाती के आगे मध्य रेखा पर स्थित समतल अस्थि है, जिससे ऊपरी पसलियाँ जुड़ती हैं।",
     "The sternum is the flat bone on the midline of the chest to which upper ribs attach."),

    ("skeletal-system", "medium",
     "निम्न में से कौन-सी समतल (flat) अस्थि है?",
     "Which of the following is a flat bone?",
     ["फीमर", "ह्यूमरस", "पसली (रिब)", "पटेला"],
     ["Femur", "Humerus", "Rib", "Patella"],
     2,
     "पसली समतल अस्थि है जो छाती के अंगों को ढाल की तरह रक्षा प्रदान करती है।",
     "The rib is a flat bone that shields the chest organs like armour."),

    ("skeletal-system", "hard",
     "निम्न में से कौन-सी अस्थि अपांडिकुलर (उपांगीय) कंकाल का भाग है?",
     "Which of the following bones is part of the appendicular skeleton?",
     ["कपाल", "पसलियाँ", "कशेरुक स्तंभ", "फीमर"],
     ["Skull", "Ribs", "Vertebral column", "Femur"],
     3,
     "अपांडिकुलर कंकाल में अंग (हाथ-पैर) और मेखलाओं की अस्थियाँ आती हैं; फीमर जाँघ की अस्थि है। शेष तीन अक्षीय कंकाल के भाग हैं।",
     "The appendicular skeleton includes limb bones and girdles; the femur is a limb bone. The other three belong to the axial skeleton."),

    ("skeletal-system", "easy",
     "लंबी अस्थियों के खोखले मध्य भाग (छड़) में क्या भरा रहता है?",
     "What fills the hollow middle shaft of long bones?",
     ["वायु", "अस्थिमज्जा (बोन मैरो)", "पेशी", "उपास्थि"],
     ["Air", "Bone marrow", "Muscle", "Cartilage"],
     1,
     "लंबी अस्थियों की खोखली छड़ में अस्थिमज्जा रहती है जो रक्त कणिकाएँ बनाती और वसा संचित करती है।",
     "The hollow shaft of long bones contains marrow, which makes blood cells and stores fat."),

    ("skeletal-system", "medium",
     "पीली अस्थिमज्जा का मुख्य कार्य क्या है?",
     "What is the main function of yellow bone marrow?",
     ["रक्त बनाना", "वसा का संचय", "नई अस्थि बनाना", "उपास्थि बनाना"],
     ["Making blood cells", "Storing fat", "Forming new bone", "Forming cartilage"],
     1,
     "पीली मज्जा मुख्यतः वसा का भंडार है; रक्त-निर्माण मुख्यतः लाल मज्जा करती है।",
     "Yellow marrow is mainly a fat store; blood formation is done chiefly by red marrow."),

    ("skeletal-system", "easy",
     "घुटने के सामने स्थित छोटी, अंडाकार अस्थि को क्या कहते हैं?",
     "What is the small, rounded bone in front of the knee called?",
     ["टिबिया", "फीमर", "पटेला (घुटने की चक्की)", "फिबुला"],
     ["Tibia", "Femur", "Patella (kneecap)", "Fibula"],
     2,
     "पटेला घुटने के सामने स्थित छोटी अस्थि है जो घुटने के जोड़ की रक्षा करती है।",
     "The patella is the small bone at the front of the knee that protects the knee joint."),

    ("skeletal-system", "easy",
     "खोपड़ी की अधिकांश अस्थियाँ किस प्रकार की होती हैं?",
     "Most bones of the skull are of which type?",
     ["लंबी नलाकार", "छोटी गोल", "चपटी/समतल", "अनियमित स्पंजी"],
     ["Long tubular", "Small round", "Flat", "Irregular spongy"],
     2,
     "कपाल की अस्थियाँ समतल चपटी होती हैं जो जुड़कर मस्तिष्क के चारों ओर मजबूत ढाल बनाती हैं।",
     "Skull bones are flat plates that join to form a strong shield around the brain."),

    ("skeletal-system", "hard",
     "अस्थि भंग (fracture) में चिकित्सक हड्डी को पट्टी/प्लास्टर से स्थिर क्यों कर देते हैं?",
     "Why do doctors immobilise a fractured bone with a cast?",
     ["केवल दर्द कम करने के लिए", "क्योंकि नई अस्थि बनकर सटीक रूप से जुड़ने तक हड्डी को हिलना नहीं चाहिए", "क्योंकि रक्त बनने के लिए स्थिरता चाहिए", "क्योंकि प्लास्टर में कैल्शियम होता है जो हड्डी चूसती है"],
     ["Only to reduce pain", "Because the new bone must stay undisturbed until it joins correctly", "Because blood formation needs stillness", "Because the cast's calcium is absorbed by the bone"],
     1,
     "भंग स्थल पर नई अस्थि कोशिकाएँ जुड़ती हैं; गति से जुड़ाव गड़बड़ हो सकता है, इसलिए स्थिरीकरण आवश्यक है।",
     "New bone cells bridge the break; movement disturbs proper union, hence immobilisation is essential."),

    ("skeletal-system", "medium",
     "शार्क का कंकाल मुख्यतः किससे बना होता है?",
     "What is the skeleton of a shark mainly made of?",
     ["अस्थि", "उपास्थि (कार्टिलेज)", "दृढ़ ऊतक", "काइटिन"],
     ["Bone", "Cartilage", "Sclerenchyma", "Chitin"],
     1,
     "शार्क उपास्थि-मछली (कार्टिलेजिनस फिश) है; उसका पूरा कंकाल लचीली उपास्थि का बना होता है।",
     "Sharks are cartilaginous fish; their entire skeleton is made of flexible cartilage."),

    ("skeletal-system", "medium",
     "नवजात शिशु में अस्थियों की संख्या वयस्क से अधिक क्यों होती है?",
     "Why does a newborn have more bones than an adult?",
     ["क्योंकि वयस्कों में कई अस्थियाँ बढ़ते हुए आपस में जुड़ (fuse) जाती हैं", "क्योंकि शिशु में केवल उपास्थि होती है जिसे अस्थि गिनते हैं", "क्योंकि वयस्कों में अस्थियाँ घुल जाती हैं", "क्योंकि शिशु की हड्डियाँ दोगुनी गति से बनती हैं और बाद में आधी टूट जाती हैं"],
     ["Because many bones fuse together as a person grows into an adult", "Because an infant has only cartilage that is counted as bone", "Because bones dissolve in adults", "Because an infant's bones form at double speed and half of them later break"],
     0,
     "शिशु में लगभग 300 अस्थियाँ होती हैं; वृद्धि के साथ कई अस्थियाँ जुड़कर 206 रह जाती हैं — जैसे कपाल की अस्थियाँ और श्रोणि।",
     "An infant has about 300 bones; many fuse during growth leaving 206 — e.g. skull and hip bones fuse."),

    ("skeletal-system", "medium",
     "कशेरुकाओं के बीच उपास्थि की गद्दियों (इंटरवर्टेब्रल डिस्क) का कार्य क्या है?",
     "What is the function of the cartilage pads (intervertebral discs) between vertebrae?",
     ["झटकों को सोखना और पीठ को मुड़ने में सहायता देना", "रक्त बनाना", "मेरुरज्जु का निर्माण करना", "शरीर का भार बढ़ाना"],
     ["Absorbing shocks and helping the back bend", "Making blood cells", "Forming the spinal cord", "Increasing body weight"],
     0,
     "ये गद्दियाँ चलने-कूदने के झटके सोखती हैं और रीढ़ को सीमित लचीला घुमाव देती हैं।",
     "These discs absorb shocks from walking and jumping and allow limited flexible movement of the spine."),

    ("skeletal-system", "medium",
     "ऊपरी बाँह (भुजा) की एकमात्र लंबी अस्थि कौन-सी है?",
     "Which is the single long bone of the upper arm?",
     ["रेडियस", "अल्ना", "ह्यूमरस", "क्लाइविकल"],
     ["Radius", "Ulna", "Humerus", "Clavicle"],
     2,
     "ह्यूमरस कंधे से कोहनी तक ऊपरी बाँह की एकमात्र अस्थि है; रेडियस-अल्ना अग्रभुजा में होती हैं।",
     "The humerus is the only bone of the upper arm between shoulder and elbow; radius and ulna lie in the forearm."),

    ("skeletal-system", "easy",
     "शरीर के सम्पूर्ण अस्थि-ढाँचे को क्या कहते हैं?",
     "What is the entire bony framework of the body called?",
     ["संधि", "मेखला", "कंकाल", "उपास्थि"],
     ["Joint", "Girdle", "Skeleton", "Cartilage"],
     2,
     "सभी अस्थियों और उपास्थियों का मिलकर बना ढाँचा कंकाल कहलाता है, जो शरीर को आकार और सहारा देता है।",
     "The framework formed by all bones and cartilages is the skeleton, which shapes and supports the body."),

    # ---------------- advanced-plant-tissues (25) ----------------
    ("advanced-plant-tissues", "easy",
     "पौधे की नई जड़ें और शाखाएँ किन कोशिकाओं से बनती हैं?",
     "Which cells give rise to new roots and branches of a plant?",
     ["परिपक्व मृदूतक से", "सक्रिय विभाजन करने वाली विभज्योतक कोशिकाओं से", "कॉर्क कोशिकाओं से", "द्वार कोशिकाओं से"],
     ["Mature parenchyma", "Actively dividing meristematic cells", "Cork cells", "Guard cells"],
     1,
     "विभज्योतक कोशिकाएँ लगातार विभाजित होकर नई कोशिकाएँ बनाती रहती हैं, जिनसे नए अंग विकसित होते हैं।",
     "Meristematic cells divide continuously to generate new cells from which new organs develop."),

    ("advanced-plant-tissues", "medium",
     "विभज्योतक की कोशिकाओं में निम्न में से कौन-सी विशेषता नहीं पाई जाती?",
     "Which feature is NOT found in meristematic cells?",
     ["पतली कोशिका भित्ति", "सघन काइटोप्लाज्म", "बड़ी स्थायी रिक्तिका", "निरंतर विभाजन की क्षमता"],
     ["Thin cell wall", "Dense cytoplasm", "Large permanent vacuole", "Continuous dividing ability"],
     2,
     "विभज्योतक कोशिकाओं में रिक्तिकाएँ लगभग अनुपस्थित होती हैं; बड़ी रिक्तिका तो परिपक्व स्थायी ऊतक कोशिकाओं की पहचान है।",
     "Meristematic cells lack vacuoles almost entirely; a large vacuole is a hallmark of mature permanent tissue cells."),

    ("advanced-plant-tissues", "medium",
     "यदि किसी पौधे की ऊँचाई बढ़ना बंद हो जाए, तो कौन-सा विभज्योतक निष्क्रिय हुआ है?",
     "If a plant stops growing taller, which meristem has become inactive?",
     ["शीर्षस्थ (apical) विभज्योतक", "पार्श्व (lateral) विभज्योतक", "अंतरावेशित विभज्योतक", "कॉर्क कैम्बियम"],
     ["Apical meristem", "Lateral meristem", "Intercalary meristem", "Cork cambium"],
     0,
     "तने और जड़ के शीर्ष पर स्थित शीर्षस्थ विभज्योतक ही लंबाई में वृद्धि कराता है; उसके निष्क्रिय होने पर ऊँचाई रुक जाती है।",
     "The apical meristem at shoot and root tips drives lengthwise growth; if it turns inactive, height stops increasing."),

    ("advanced-plant-tissues", "hard",
     "पेड़ के तने की मोटाई (परिधि) की वृद्धि किस विभज्योतक के कारण होती है?",
     "Which meristem is responsible for the increase in girth (thickness) of a tree trunk?",
     ["शीर्षस्थ विभज्योतक", "पार्श्व विभज्योतक (कैम्बियम)", "अंतरावेशित विभज्योतक", "शीर्ष तथा अंतरावेशित दोनों"],
     ["Apical meristem", "Lateral meristem (cambium)", "Intercalary meristem", "Both apical and intercalary"],
     1,
     "तने में पार्श्व रूप से स्थित कैम्बियम कोशिकाएँ बाह्य और भीतर की ओर नई कोशिकाएँ जोड़ती हैं, जिससे मोटाई बढ़ती है।",
     "The laterally placed cambium adds new cells outward and inward, thickening the trunk."),

    ("advanced-plant-tissues", "medium",
     "अंतरावेशित (intercalary) विभज्योतक सामान्यतः कहाँ मिलता है?",
     "Where is intercalary meristem commonly found?",
     ["जड़ की अग्रांश पर", "पर्वसंधियों (nodes) के पास घास-बाँस जैसे पौधों में", "पुराने तने की छाल में", "फल के भीतर बीज में"],
     ["At the root tip", "Near the nodes of grasses and bamboo-like plants", "In the bark of old stems", "Inside the seed within the fruit"],
     1,
     "घास, गन्ने, बाँस जैसे पौधों में पर्वों के आधार पर अंतरावेशित विभज्योतक रहता है।",
     "In grasses, sugarcane and bamboo, intercalary meristem lies at the base of nodes."),

    ("advanced-plant-tissues", "easy",
     "स्थायी ऊतकों का निर्माण किन कोशिकाओं से होता है?",
     "Permanent tissues are formed from which cells?",
     ["एपिडर्मल कोशिकाओं से", "विभज्योतक कोशिकाओं से, जब उनका विभाजन रुक जाता है", "कॉर्क कोशिकाओं से", "द्वार कोशिकाओं से"],
     ["Epidermal cells", "Meristematic cells, once they stop dividing", "Cork cells", "Guard cells"],
     1,
     "जब विभज्योतक से बनी कोशिकाएँ विभाजन बंद कर आकार-कार्य में विशेषीकृत हो जाती हैं, तो वे स्थायी ऊतक बनाती हैं।",
     "When cells derived from meristem stop dividing and specialise in shape and function, they form permanent tissues."),

    ("advanced-plant-tissues", "easy",
     "मृदूतक, कोलेन्काइमा और स्क्लेरेन्काइमा में समानता क्या है?",
     "What is common among parenchyma, collenchyma and sclerenchyma?",
     ["तीनों जटिल ऊतक हैं", "तीनों सरल स्थायी ऊतक हैं", "तीनों विभज्योतक हैं", "तीनों मृत कोशिकाओं से बनते हैं"],
     ["All three are complex tissues", "All three are simple permanent tissues", "All three are meristems", "All three are made of dead cells"],
     1,
     "ये तीनों एक ही प्रकार की कोशिकाओं से बने सरल स्थायी ऊतक हैं; मृदूतक जीवित, कोलेन्काइमा जीवित और स्क्लेरेन्काइमा मृत होता है।",
     "All three are simple permanent tissues made of one cell type each; parenchyma and collenchyma are living, sclerenchyma is dead."),

    ("advanced-plant-tissues", "medium",
     "मृदूतक (parenchyma) की कोशिकाओं की पहचान क्या है?",
     "How are parenchyma cells identified?",
     ["लिग्निन युक्त मोटी भित्ति", "पतली भित्ति तथा बीच में अंतरकोशिकीय स्थान", "बिल्कुल मृत खोखली कोशिकाएँ", "बिना केंद्रक की कोशिकाएँ"],
     ["Thick lignified walls", "Thin walls with intercellular spaces between them", "Completely dead hollow cells", "Cells without nuclei"],
     1,
     "मृदूतक में पतली प्राथमिक भित्ति वाली जीवित कोशिकाएँ ढीले ढंग से रहती हैं और उनके बीच अंतरकोशिकीय स्थान होते हैं।",
     "Parenchyma has thin-walled living cells arranged loosely, leaving intercellular spaces."),

    ("advanced-plant-tissues", "easy",
     "पौधों में भोजन का भंडारण मुख्यतः किस ऊतक में होता है?",
     "In plants, food is stored mainly in which tissue?",
     ["स्क्लेरेन्काइमा", "मृदूतक (parenchyma)", "जाइलम", "एपिडर्मिस"],
     ["Sclerenchyma", "Parenchyma", "Xylem", "Epidermis"],
     1,
     "मृदूतक कोशिकाएँ भोजन संचित करती हैं — जैसे आलू, गाजर और अन्य भंडारण अंग मुख्यतः मृदूतक से भरे होते हैं।",
     "Parenchyma cells store food — potato, carrot and other storage organs are packed with parenchyma."),

    ("advanced-plant-tissues", "medium",
     "प्रकाश-संश्लेषण करने वाला हरित मृदूतक किस नाम से जाना जाता है?",
     "What is the green photosynthetic parenchyma known as?",
     ["एरेन्काइमा", "पर्णहरित मृदूतक (क्लोरेन्काइमा)", "स्क्लेरेन्काइमा", "कॉर्क"],
     ["Aerenchyma", "Chlorenchyma", "Sclerenchyma", "Cork"],
     1,
     "जब मृदूतक में हरितलवक होते हैं और वह प्रकाश-संश्लेषण करता है, तो वह पर्णहरित मृदूतक (क्लोरेन्काइमा) कहलाता है।",
     "When parenchyma contains chloroplasts and photosynthesises, it is called chlorenchyma."),

    ("advanced-plant-tissues", "hard",
     "जलीय पौधों में पाया जाने वाला वायुकोशी (एरेन्काइमा) ऊतक पौधे के लिए क्या करता है?",
     "What does the aerenchyma tissue found in aquatic plants do for the plant?",
     ["भोजन का भंडारण करता है", "रोगों से रक्षा करता है", "उत्प्लावकता प्रदान करके पौधे को जल पर तैरने में सहायता करता है", "जल का उल्वहन करता है"],
     ["Stores food", "Protects from disease", "Provides buoyancy, helping the plant float on water", "Transports water upward"],
     2,
     "एरेन्काइमा में बड़ी वायु रिक्तिकाएँ होती हैं जो पौधे को उत्प्लावकता देती हैं — जैसे कमल में।",
     "Aerenchyma has large air cavities that give buoyancy — as in the lotus."),

    ("advanced-plant-tissues", "medium",
     "कोलेन्काइमा की कोशिका भित्ति कहाँ मोटी होती है?",
     "Where is the cell wall thickened in collenchyma?",
     ["सम्पूर्ण भित्ति पर समान रूप से", "कोनों पर", "केवल भीतरी सतह पर", "केवल बाहरी सतह पर"],
     ["Uniformly over the whole wall", "At the corners", "Only on the inner surface", "Only on the outer surface"],
     1,
     "कोलेन्काइमा में सेल्युलोज की मोटी भित्ति कोनों पर जमा होती है, जिससे लचीला सहारा मिलता है।",
     "Collenchyma has thick cellulose deposits at the corners, giving flexible support."),

    ("advanced-plant-tissues", "medium",
     "स्क्लेरेन्काइमा को मृत ऊतक क्यों कहा जाता है?",
     "Why is sclerenchyma called a dead tissue?",
     ["क्योंकि लिग्निन युक्त अत्यंत मोटी भित्तियाँ जम जाने पर उनके भीतर का काइटोप्लाज्म और केंद्रक नष्ट हो जाते हैं", "क्योंकि उसमें जल नहीं होता", "क्योंकि वह नई कोशिकाएँ बनाता नहीं", "क्योंकि उसमें हरितलवक नहीं होते"],
     ["Because once extremely thick lignified walls are laid down, the cytoplasm and nucleus inside are lost", "Because it contains no water", "Because it does not form new cells", "Because it lacks chloroplasts"],
     0,
     "लिग्निन की मोटी परत जमते ही कोशिका की जैविक सामग्री मर जाती है; बची रहती है केवल कठोर भित्ति जो यंत्रण बल (tensile strength) देती है।",
     "Once the thick lignin layer is deposited the cell contents die; only the tough wall remains, providing tensile strength."),

    ("advanced-plant-tissues", "easy",
     "नारियल के छोंद (हस्क) की कठोरता किस ऊतक के कारण होती है?",
     "The hardness of coconut husk is due to which tissue?",
     ["मृदूतक", "स्क्लेरेन्काइमा", "एरेन्काइमा", "विभज्योतक"],
     ["Parenchyma", "Sclerenchyma", "Aerenchyma", "Meristem"],
     1,
     "नारियल के छोंद में मृत स्क्लेरेन्काइमा तंतुओं की गाँठें होती हैं, इसीलिए वह कठोर और रेशेदार होता है।",
     "Coconut husk contains bundles of dead sclerenchyma fibres, making it hard and fibrous."),

    ("advanced-plant-tissues", "medium",
     "पत्ती की तनी (leaf stalk) मुड़ने पर आसानी से टूटती नहीं, इसका लचीला सहारा किस ऊतक से मिलता है?",
     "The leaf stalk bends without breaking easily; which tissue gives this flexible support?",
     ["स्क्लेरेन्काइमा", "कोलेन्काइमा", "जाइलम", "कॉर्क"],
     ["Sclerenchyma", "Collenchyma", "Xylem", "Cork"],
     1,
     "कोलेन्काइमा लचीला यांत्रिक सहारा देता है — कठोर तो स्क्लेरेन्काइमा भी है पर वह भंगुर-कठोर है, लचीला नहीं।",
     "Collenchyma provides flexible mechanical support — sclerenchyma is rigidly hard, not flexible."),

    ("advanced-plant-tissues", "medium",
     "जाइलम और फ्लोएम को 'संवहन ऊतक' क्यों कहा जाता है?",
     "Why are xylem and phloem called 'vascular (conducting) tissues'?",
     ["क्योंकि दोनों की कोशिकाएँ समान होती हैं", "क्योंकि दोनों पादप शरीर में पदार्थों का परिवहन (संवहन) करते हैं", "क्योंकि दोनों में हरितलवक होते हैं", "क्योंकि दोनों केवल जड़ में पाए जाते हैं"],
     ["Because both have identical cells", "Because both transport (conduct) materials through the plant body", "Because both contain chloroplasts", "Because both occur only in roots"],
     1,
     "जाइलम जल व खनिज लवणों का और फ्लोएम भोजन का परिवहन करता है — यही संवहन कार्य इन्हें संवहन ऊतक बनाता है।",
     "Xylem conducts water and minerals, phloem conducts food — this transport role makes them vascular tissues."),

    ("advanced-plant-tissues", "medium",
     "जाइलम में भंडारण तथा जल के पार्श्व (side-wise) प्रवाह में सहायक जीवित घटक कौन-सा है?",
     "Which living xylem component helps in storage and side-wise (lateral) movement of water?",
     ["वाहिका (vessel)", "वाहिनिका (tracheid)", "जाइलम मृदूतक", "जाइलम तंतु"],
     ["Vessels", "Tracheids", "Xylem parenchyma", "Xylem fibres"],
     2,
     "जाइलम में वाहिका, वाहिनिका और तंतु मृत होते हैं; केवल जाइलम मृदूतक जीवित रहता है और भंडारण-पार्श्व प्रवाह में सहायक होता है।",
     "In xylem, vessels, tracheids and fibres are dead; only xylem parenchyma stays living and assists storage and lateral flow."),

    ("advanced-plant-tissues", "hard",
     "चालनी नलिका (sieve tube) की कोशिका भित्ति में पाए जाने वाले छिद्रों (sieve pores) का कार्य क्या है?",
     "What is the function of the sieve pores present in the walls of sieve tube cells?",
     ["जल का उद्वर्तन", "भोजन का एक कोशिका से दूसरी कोशिका में प्रवाह", "वायु का विनिमय", "नई कोशिकाओं का निर्माण"],
     ["Ascent of water", "Flow of food from one cell to the next", "Exchange of gases", "Formation of new cells"],
     1,
     "छिद्रों के द्वारा ही फ्लोएम में बना भोजन प्रत्येक सदस्य कोशिका से अगली में सरलता से प्रवाहित होता है।",
     "Through the pores, the food made in phloem flows easily from one member cell to the next."),

    ("advanced-plant-tissues", "medium",
     "जाइलम में जल व खनिजों का संवाहन करने वाले मुख्य घटक कौन-से हैं?",
     "Which are the main water- and mineral-conducting components of xylem?",
     ["चालनी नलिका व सह-कोशिका", "वाहिका (vessels) व वाहिनिका (tracheids)", "द्वार कोशिकाएँ", "कॉर्क कोशिकाएँ"],
     ["Sieve tubes and companion cells", "Vessels and tracheids", "Guard cells", "Cork cells"],
     1,
     "मृत, लंबी, नलीदार वाहिका एवं वाहिनिका ही जाइलम के मुख्य जल-संवाहक घटक हैं।",
     "The dead, elongated, tubular vessels and tracheids are the chief water-conducting elements of xylem."),

    ("advanced-plant-tissues", "medium",
     "एपिडर्मिस की परत पौधे का मुख्यतः क्या कार्य करती है?",
     "What is the chief role of the epidermal layer of a plant?",
     ["भोजन बनाना", "आवरण के रूप में सुरक्षा करना", "जल का संवहन", "कोशिका-विभाजन"],
     ["Preparing food", "Protection as a covering", "Transporting water", "Cell division"],
     1,
     "एपिडर्मिस सम्पूर्ण पौधे की बाह्य सुरक्षा-परत है जो जल-हानि और रोगाणुओं से रक्षा करती है।",
     "The epidermis is the plant's outer protective layer guarding against water loss and germs."),

    ("advanced-plant-tissues", "medium",
     "रंध्र (stomata) का खुलना और बंद होना कौन नियंत्रित करता है?",
     "What controls the opening and closing of stomata?",
     ["एपिडर्मल रोम (trichomes)", "द्वार कोशिकाएँ (guard cells)", "कॉर्क कोशिकाएँ", "सह-कोशिकाएँ"],
     ["Epidermal hairs (trichomes)", "Guard cells", "Cork cells", "Companion cells"],
     1,
     "द्वार कोशिकाएँ जल की मात्रा घटकर फूलती-सिकुड़ती हैं और रंध्र छिद्र खोलती-बंद करती हैं।",
     "Guard cells swell and shrink with water content, opening and closing the stomatal pore."),

    ("advanced-plant-tissues", "medium",
     "पत्तियों की सतह पर पाई जाने वाली मोम जैसी क्यूटिकुल परत का क्या कार्य है?",
     "What is the function of the waxy cuticle found on leaf surfaces?",
     ["प्रकाश को अंदर लाना", "वायु-विनिमय बढ़ाना", "जल की हानि (वाष्पोत्सर्जन) को घटाना", "कीटों को आकर्षित करना"],
     ["Letting light inside", "Increasing gas exchange", "Reducing water loss (transpiration)", "Attracting insects"],
     2,
     "जलीय पौधों को छोड़कर स्थलीय पौधों की पत्तियों पर मोमा क्यूटिकुल जल की हानि रोकती है।",
     "In land plants, the waxy cuticle on leaves checks loss of water."),

    ("advanced-plant-tissues", "medium",
     "पुराने तनों में जमने वाली कॉर्क कोशिकाओं की भित्तियों में कौन-सा पदार्थ होता है?",
     "Which substance is present in the walls of cork cells formed in old stems?",
     ["लिग्निन", "सुबेरिन", "क्लोरोफिल", "माइलिन"],
     ["Lignin", "Suberin", "Chlorophyll", "Myelin"],
     1,
     "कॉर्क कोशिकाओं में सुबेरिन होता है जो जल-अपारगम्य (जलरोधी) बना देता है और कोशिकाएँ मृत हो जाती हैं।",
     "Cork cells contain suberin, which makes them water-impermeable; the cells then die."),

    ("advanced-plant-tissues", "hard",
     "पेड़ के मोटे तने पर बनने वाली 'छाल' (bark) मुख्यतः किससे बनी होती है?",
     "The 'bark' formed on the thick trunk of a tree is mainly made of what?",
     ["जीवित विभज्योतक से", "मृत कॉर्क कोशिकाओं से", "पर्णहरित मृदूतक से", "वायुकोशी ऊतक से"],
     ["Living meristem", "Dead cork cells", "Chlorenchyma", "Aerenchyma"],
     1,
     "बाह्य छाल कैम्बियम से बने कॉर्क की मृत, सुबेरिन-युक्त परतों से बनती है जो भीतरी जीवित ऊतकों की रक्षा करती है।",
     "The outer bark consists of dead, suberin-rich cork layers that protect the living tissue inside."),

    ("advanced-plant-tissues", "medium",
     "घास को काटने के बाद वह फिर से उग आती है — इसका कारण क्या है?",
     "Grass grows again after being cut — what is the reason?",
     ["शीर्षस्थ विभज्योतक", "पार्श्व विभज्योतक", "पर्वों के आधार पर स्थित अंतरावेशित विभज्योतक", "कॉर्क कैम्बियम"],
     ["Apical meristem", "Lateral meristem", "Intercalary meristem at the base of nodes", "Cork cambium"],
     2,
     "घास के पर्वों के आधार में अंतरावेशित विभज्योतक सक्रिय रहता है, इसलिए काटे जाने पर भी पत्तियाँ दोबारा बढ़ती हैं।",
     "The intercalary meristem at the base of grass nodes stays active, so leaves regrow even after cutting."),

    # ---------------- epithelial-connective-tissues (first 20 of 25) ----------------
    ("epithelial-connective-tissues", "easy",
     "उपकला ऊतक की कोशिकाएँ किस प्रकार सजी रहती हैं?",
     "How are the cells of epithelial tissue arranged?",
     ["बहुत कम अंतराल के साथ सघन रूप से", "बड़े अंतराल में बिखरी हुई", "मैट्रिक्स में गड़ी हुई", "मृत और खोखली"],
     ["Closely packed with very little space in between", "Scattered with wide gaps", "Embedded in a matrix", "Dead and hollow"],
     0,
     "उपकला कोशिकाएँ एक-दूसरे से चिपककर निरंतर परत बनाती हैं; बीच में अंतरकोशिकीय द्रव्य लगभग नहीं होता।",
     "Epithelial cells form continuous sheets with almost no intercellular material between them."),

    ("epithelial-connective-tissues", "easy",
     "फेफड़ों की वायु-कोशिकाओं (एल्वियोलाइ) की भित्ति में कौन-सी उपकला पाई जाती है?",
     "Which epithelium is found in the walls of the air sacs (alveoli) of the lungs?",
     ["घनाकार", "शल्की (पतली-चपटी)", "स्तंभाकार", "पक्षमाभीय"],
     ["Cuboidal", "Squamous (thin and flat)", "Columnar", "Ciliated"],
     1,
     "अत्यंत पतली शल्की उपकला से गैसों का विसरण सरल हो जाता है।",
     "The very thin squamous epithelium makes diffusion of gases easy."),

    ("epithelial-connective-tissues", "medium",
     "गुर्दे की नलिकाओं (uriniferous tubules) की भित्ति किस उपकला से ढकी होती है?",
     "The walls of the kidney tubules are lined with which epithelium?",
     ["शल्की", "घनाकार (cuboidal)", "स्तंभाकार", "बहुस्तरित"],
     ["Squamous", "Cuboidal", "Columnar", "Stratified"],
     1,
     "गुर्दे की नलिकाओं में घनाकार उपकला होती है जो अवशोषण और स्राव में सहायक है।",
     "Kidney tubules are lined by cuboidal epithelium, which helps in absorption and secretion."),

    ("epithelial-connective-tissues", "medium",
     "आँत की भीतरी परत (lining) किस उपकला से बनी होती है?",
     "The inner lining of the intestine is made of which epithelium?",
     ["स्तंभाकार (columnar)", "शल्की", "घनाकार", "संवहनी"],
     ["Columnar", "Squamous", "Cuboidal", "Vascular"],
     0,
     "आँत में स्तंभाकार उपकला होती है जिसका कार्य अवशोषण और स्राव है।",
     "The intestine has columnar epithelium whose roles are absorption and secretion."),

    ("epithelial-connective-tissues", "medium",
     "श्वसन-नली (trachea) की भीतरी परत में जो उपकला पाई जाती है, वह किस विशेषता के लिए जानी जाती है?",
     "The epithelium lining the trachea is known for which special feature?",
     ["बाल जैसी पक्षमों (cilia) की उपस्थिति", "अत्यधिक मोटाई", "वसा स्राव", "रक्त निर्माण"],
     ["Presence of hair-like cilia", "Great thickness", "Fat secretion", "Blood formation"],
     0,
     "श्वासनली की पक्षमाभीय उपकला की पक्षमें धूल-कणों और श्लेष्मा को ऊपर की ओर धकेलती रहती हैं।",
     "The ciliated epithelium of the trachea constantly pushes dust particles and mucus upward."),

    ("epithelial-connective-tissues", "easy",
     "ग्रंथिल (glandular) उपकला का मुख्य कार्य क्या है?",
     "What is the main function of glandular epithelium?",
     ["संकुचन", "स्राव (secretion)", "संवहन", "उत्सर्जन"],
     ["Contraction", "Secretion", "Conduction", "Excretion"],
     1,
     "ग्रंथिल उपकला विशिष्ट पदार्थ — जैसे पाचक रस, स्वेद, लार — का स्राव करती है।",
     "Glandular epithelium secretes specific substances such as digestive juices, sweat and saliva."),

    ("epithelial-connective-tissues", "medium",
     "त्वचा की बाह्य परत में उपकला कोशिकाएँ कई स्तरों में जमी होती हैं; ऐसी व्यवस्था क्यों उपयोगी है?",
     "Epithelial cells of the outer skin are arranged in many layers; why is this useful?",
     ["इससे रक्त बनता है", "इससे घर्षण-क्षति सहने और नीचे के ऊतकों की रक्षा की क्षमता बढ़ती है", "इससे पाचन तेज़ होता है", "इससे वायु-विनिमय होता है"],
     ["It helps produce blood", "It improves tolerance to wear and tear and protects underlying tissues", "It speeds up digestion", "It enables gas exchange"],
     1,
     "बहुस्तरित व्यवस्था लगातार घिसाव सहती है — बाह्य स्तर झड़ता रहता है और नीचे की कोशिकाएँ नई बनती रहती हैं।",
     "The stratified arrangement withstands constant wear — the outer layer sheds while cells below renew it."),

    ("epithelial-connective-tissues", "medium",
     "निम्न में से कौन-सा कार्य उपकला ऊतक का नहीं है?",
     "Which of the following is NOT a function of epithelial tissue?",
     ["शरीर की सतहों को ढकना", "अवशोषण", "स्राव", "संकुचन द्वारा गति उत्पन्न करना"],
     ["Covering body surfaces", "Absorption", "Secretion", "Producing movement by contraction"],
     3,
     "संकुचन और गति पेशी ऊतक का कार्य है, उपकला का नहीं।",
     "Contraction and movement are the job of muscular tissue, not epithelium."),

    ("epithelial-connective-tissues", "easy",
     "संयोजी ऊतक की पहचान उसकी किस विशेषता से होती है?",
     "By which feature is connective tissue identified?",
     ["इसकी कोशिकाएँ अंतरकोशिकीय मैट्रिक्स में निहित रहती हैं", "इसकी कोशिकाएँ बिना अंतराल चिपकी रहती हैं", "इसकी सभी कोशिकाएँ मृत होती हैं", "इसमें कोशिकाएँ होती ही नहीं"],
     ["Its cells are embedded in an intercellular matrix", "Its cells are packed together without spaces", "All its cells are dead", "It has no cells at all"],
     0,
     "संयोजी ऊतक में कोशिकाएँ विरल रूप से एक गैर-जीवित मैट्रिक्स (जेली/द्रव/कठोर) में बिखरी रहती हैं — यही इसकी पहचान है।",
     "In connective tissue, cells are sparsely scattered in a non-living matrix (jelly/fluid/hard) — its defining feature."),

    ("epithelial-connective-tissues", "easy",
     "विदरक (areolar) ऊतक मुख्यतः कहाँ पाया जाता है?",
     "Where is areolar tissue mainly found?",
     ["अस्थि के भीतर", "त्वचा के नीचे और आंतरिक अंगों के बीच", "रक्त प्लाज्मा में", "रीढ़ की नली में"],
     ["Inside bones", "Below the skin and between internal organs", "In blood plasma", "In the spinal canal"],
     1,
     "विदरक ऊतक त्वचा को नीचे की पेशियों से जोड़ता और अंगों के बीच भराव करता है; यह रोगों से रक्षा में भी सहायक है।",
     "Areolar tissue connects skin to underlying muscles and fills gaps between organs; it also aids defence against infection."),

    ("epithelial-connective-tissues", "medium",
     "वसा ऊतक (adipose tissue) का मुख्य कार्य क्या है?",
     "What is the main function of adipose tissue?",
     ["वसा का संचय और ऊष्मा-रोधन (इन्सुलेशन)", "रक्त कणिकाएँ बनाना", "शरीर में गति उत्पन्न करना", "जल का संवहन"],
     ["Fat storage and heat insulation", "Making blood cells", "Producing body movement", "Transporting water"],
     0,
     "वसा ऊतक त्वचा के नीचे जमा होकर ऊर्जा-भंडार का कार्य करता है और शरीर की गर्मी बनाए रखता है।",
     "Adipose tissue under the skin stores energy and keeps body heat in."),

    ("epithelial-connective-tissues", "easy",
     "टेंडन (tendon) क्या जोड़ता है?",
     "What does a tendon connect?",
     ["अस्थि को अस्थि से", "पेशी को अस्थि से", "पेशी को पेशी से", "अस्थि को उपास्थि से"],
     ["Bone to bone", "Muscle to bone", "Muscle to muscle", "Bone to cartilage"],
     1,
     "टेंडन तंतुमय संयोजी ऊतक है जो पेशी के बल को अस्थि तक पहुँचाता है।",
     "A tendon is fibrous connective tissue that transmits muscle force to the bone."),

    ("epithelial-connective-tissues", "easy",
     "लिगामेंट (स्नायु) क्या जोड़ता है?",
     "What does a ligament connect?",
     ["अस्थि को अस्थि से", "पेशी को अस्थि से", "पेशी को पेशी से", "त्वचा को पेशी से"],
     ["Bone to bone", "Muscle to bone", "Muscle to muscle", "Skin to muscle"],
     0,
     "लिगामेंट दो अस्थियों को संधि पर बाँधता है और अत्यधिक गति को रोकता है।",
     "A ligament binds two bones at a joint and prevents excessive movement."),

    ("epithelial-connective-tissues", "medium",
     "लिगामेंट में टेंडन की तुलना में लचीलापन अधिक क्यों होता है?",
     "Why is a ligament more flexible than a tendon?",
     ["क्योंकि इसमें प्रचुर मात्रा में इलास्टिन तंतु होते हैं", "क्योंकि इसमें कैल्शियम जमा होता है", "क्योंकि यह उपकला से बना है", "क्योंकि इसमें रक्त वाहिकाएँ अधिक होती हैं"],
     ["Because it contains abundant elastin fibres", "Because it deposits calcium", "Because it is made of epithelium", "Because it has more blood vessels"],
     0,
     "स्नायु में पीले इलास्टिन तंतु अधिक होते हैं जिससे वे खिंचकर वापस आ जाते हैं; टेंडन में सफेद कोलेजन प्रधान है जो दृढ़ता देता है।",
     "Ligaments are rich in yellow elastin fibres that stretch and recoil; tendons are dominated by white collagen giving strength."),

    ("epithelial-connective-tissues", "medium",
     "शरीर में सर्वाधिक व्यापक रूप से वितरित (सबसे अधिक जगह पाया जाने वाला) ऊतक कौन-सा है?",
     "Which is the most widely distributed tissue in the body?",
     ["उपकला ऊतक", "संयोजी ऊतक", "तंत्रिका ऊतक", "रेखित पेशी"],
     ["Epithelial tissue", "Connective tissue", "Nervous tissue", "Striated muscle"],
     1,
     "संयोजी ऊतक के रूप — विदरक, वसा, अस्थि, उपास्थि, रक्त — शरीर के लगभग हर भाग में फैले हैं।",
     "Forms of connective tissue — areolar, adipose, bone, cartilage, blood — spread through almost every part of the body."),

    ("epithelial-connective-tissues", "medium",
     "रक्त को संयोजी ऊतक क्यों कहा जाता है?",
     "Why is blood called a connective tissue?",
     ["क्योंकि इसकी कोशिकाएँ प्लाज्मा नामक द्रव मैट्रिक्स में तैरती रहती हैं", "क्योंकि यह हृदय से जुड़ा होता है", "क्योंकि इसमें लिग्निन होता है", "क्योंकि यह कठोर होता है"],
     ["Because its cells float in a fluid matrix called plasma", "Because it is attached to the heart", "Because it contains lignin", "Because it is hard"],
     0,
     "संयोजी ऊतक की परिभाषा — कोशिकाएँ मैट्रिक्स में — रक्त पर भी लागू होती है; यहाँ मैट्रिक्स द्रव (प्लाज्मा) है और कोशिकाएँ उसमें निलंबित रहती हैं।",
     "The connective-tissue definition — cells in a matrix — fits blood too; here the matrix is fluid (plasma) with cells suspended in it."),

    ("epithelial-connective-tissues", "easy",
     "निम्न में से किस स्थान पर उपास्थि (cartilage) नहीं पाई जाती?",
     "At which of the following locations is cartilage NOT found?",
     ["कान का ऊपरी भाग", "नाक की नोक", "जाँघ की लंबी अस्थि का मध्य भाग", "श्वासनली के छल्ले"],
     ["Upper part of the ear", "Tip of the nose", "Shaft of the long thigh bone", "Rings of the trachea"],
     2,
     "जाँघ की अस्थि का मध्य भाग कठोर अस्थि ही होता है; उपास्थि वहाँ केवल सिरों के जोड़ने वाले भाग (articulating surface) पर होती है।",
     "The shaft of the femur is hard bone; cartilage there occurs only on the articulating surfaces at the ends."),

    ("epithelial-connective-tissues", "medium",
     "अस्थि (bone) में छोटे-छोटे छिद्रों और नहरों का क्या महत्व है?",
     "What is the significance of the small pores and canals in bone?",
     ["इनसे अस्थि हल्की होती है", "इनके द्वारा रक्त वाहिकाएँ और तंत्रिकाएँ अस्थि के भीतर पोषण पहुँचाती हैं", "इनसे अस्थि में वायु भरती है", "ये केवल बालों के मूल होते हैं"],
     ["They make the bone light", "They let blood vessels and nerves carry nourishment inside the bone", "They fill the bone with air", "They are merely hair roots"],
     1,
     "अस्थि जीवित ऊतक है; छिद्रों से गुजरने वाली वाहिकाएँ-नसें उसे पोषक तत्व देती हैं और क्षति की सूचना देती हैं।",
     "Bone is living tissue; vessels and nerves passing through its canals feed it and signal damage."),

    ("epithelial-connective-tissues", "hard",
     "खिलाड़ियों में उपास्थि की चोट (cartilage injury) ठीक होने में अक्सर बहुत समय क्यों लगता है?",
     "Why do cartilage injuries in sportspersons often take very long to heal?",
     ["क्योंकि उपास्थि में रक्त वाहिकाएँ नहीं होतीं, इसलिए पोषण धीरे-धीरे विसरण से मिलता है", "क्योंकि उपास्थि में कोशिकाएँ होती ही नहीं", "क्योंकि उपास्थि पूर्णतः मृत ऊतक है", "क्योंकि उपास्थि में कैल्शियम बिल्कुल नहीं होता"],
     ["Because cartilage has no blood vessels, so nutrition reaches it slowly by diffusion", "Because cartilage has no cells", "Because cartilage is completely dead tissue", "Because cartilage has no calcium at all"],
     0,
     "उपास्थि रक्त-वाहिका-रहित (avascular) ऊतक है; भोजन-ऑक्सीजन की आपूर्ति केवल आसपास के द्रव्य से विसरण द्वारा होती है, इसलिए मरम्मत धीमी रहती है।",
     "Cartilage is avascular; food and oxygen reach it only by diffusion from surrounding fluid, so repair is slow."),

    ("epithelial-connective-tissues", "medium",
     "श्वासनली (trachea) में उपास्थि के छल्ले किस उद्देश्य से होते हैं?",
     "What is the purpose of the rings of cartilage in the trachea?",
     ["श्वासनली को खुला (dilate) रखने के लिए", "भोजन को पचाने के लिए", "आवाज़ उत्पन्न करने के लिए", "रक्त को शुद्ध करने के लिए"],
     ["To keep the air passage open (dilated)", "To digest food", "To produce voice", "To purify blood"],
     0,
     "छल्ले नली को बाहरी दबाव से दबने नहीं देते, जिससे वायु का मार्ग सदैव खुला रहता है।",
     "The rings stop the tube from collapsing under outside pressure, keeping the airway permanently open."),
]
