# -*- coding: utf-8 -*-
"""B03 'Diversity & Classification of Living Organisms' — Part 2 data (95 items).
Order: five-kingdoms (25), plant-diversity (25), heredity-variation (25), habitats-adaptations (20).
Tuple: (topic, difficulty, q_hi, q_en, options_hi[4], options_en[4], correct_idx, exp_hi, exp_en)
"""

PART2 = [
    # ---------------- five-kingdoms (25) ----------------
    ("five-kingdoms", "easy",
     "पाँच जगतों वाला वर्गीकरण किसने प्रस्तावित किया?",
     "Who proposed the five-kingdom classification?",
     ["कैरोलस लिनियस", "आर.एच. व्हिटेकर", "ग्रेगर मेंडल", "रॉबर्ट हुक"],
     ["Carolus Linnaeus", "R.H. Whittaker", "Gregor Mendel", "Robert Hooke"],
     1,
     "व्हिटेकर ने जीवों को पाँच जगतों — मोनेरा, प्रोटिस्टा, फंजाई, प्लांटी और एनिमेलिया — में बाँटा।",
     "Whittaker divided organisms into five kingdoms — Monera, Protista, Fungi, Plantae and Animalia."),

    ("five-kingdoms", "easy",
     "व्हिटेकर के वर्गीकरण में पाँचों जगतों के नाम बताने वाला सही विकल्प कौन-सा है?",
     "Which option correctly names all five kingdoms in Whittaker's classification?",
     ["मोनेरा, प्रोटिस्टा, फंजाई, प्लांटी, एनिमेलिया", "मोनेरा, वायरल, फंजाई, प्लांटी, एनिमेलिया", "प्रोटिस्टा, बैक्टीरिया, शैवाल, कवक, प्राणी", "प्लांटी, एनिमेलिया, फंजाई, वायरस, मोनेरा"],
     ["Monera, Protista, Fungi, Plantae, Animalia", "Monera, Viral, Fungi, Plantae, Animalia", "Protista, Bacteria, Algae, Fungi, Animals", "Plantae, Animalia, Fungi, Virus, Monera"],
     0,
     "पाँच जगत हैं — मोनेरा (प्रोकैरियोट), प्रोटिस्टा (एककोशिकीय यूकैरियोट), फंजाई (कवक), प्लांटी (पादप) और एनिमेलिया (प्राणी)।",
     "The five kingdoms are Monera (prokaryotes), Protista (unicellular eukaryotes), Fungi, Plantae and Animalia."),

    ("five-kingdoms", "easy",
     "निम्न में से कौन व्हिटेकर के पाँच जगतों में से नहीं है?",
     "Which of the following is NOT one of Whittaker's five kingdoms?",
     ["मोनेरा", "प्रोटिस्टा", "वायरस", "फंजाई"],
     ["Monera", "Protista", "Virus", "Fungi"],
     2,
     "वायरस किसी जगत में नहीं रखा गया क्योंकि वे विशिष्ट जीव-लक्षणों से रहित, कोशिका-रहित संरचनाएँ हैं।",
     "Viruses are placed in no kingdom because they are acellular structures lacking definitive living characters."),

    ("five-kingdoms", "medium",
     "पाँच जगतों का वर्गीकरण किन मुख्य आधारों पर किया गया?",
     "On which main bases was the five-kingdom classification made?",
     ["केवल आवास", "कोशिका-संरचना, देह-संगठन, पोषण-विधि", "केवल आकार", "केवल रंग"],
     ["Habitat alone", "Cell structure, body organisation and mode of nutrition", "Size alone", "Colour alone"],
     1,
     "कोशिका का प्रकार (प्रोकैरियोटिक/यूकैरियोटिक), शरीर का संगठन (एककोशिकी/बहुकोशिकी) और पोषण का तरीका — ये तीन मुख्य आधार रहे।",
     "Type of cell (prokaryotic/eukaryotic), body organisation (unicellular/multicellular) and mode of nutrition — these were the three main bases."),

    ("five-kingdoms", "easy",
     "मोनेरा जगत के जीव किस प्रकार के होते हैं?",
     "Organisms of the kingdom Monera are of which type?",
     ["यूकैरियोटिक और बहुकोशिकीय", "प्रोकैरियोटिक और एककोशिकीय", "यूकैरियोटिक और एककोशिकीय", "निर्जीव"],
     ["Eukaryotic and multicellular", "Prokaryotic and unicellular", "Eukaryotic and unicellular", "Non-living"],
     1,
     "मोनेरा में बैक्टीरिया जैसे प्रोकैरियोटिक जीव आते हैं — इनकी कोशिकाओं में संगठित केंद्रक नहीं होता।",
     "Monera contains prokaryotic organisms like bacteria — their cells lack an organised nucleus."),

    ("five-kingdoms", "easy",
     "नीली-हरी शैवाल (cyanobacteria) किस जगत में रखी जाती हैं?",
     "Blue-green algae (cyanobacteria) are placed in which kingdom?",
     ["प्लांटी", "मोनेरा", "प्रोटिस्टा", "फंजाई"],
     ["Plantae", "Monera", "Protista", "Fungi"],
     1,
     "प्रकाश-संश्लेषण करने के बावजूद ये प्रोकैरियोटिक हैं, इसलिए इन्हें पादप जगत नहीं बल्कि मोनेरा में रखा जाता है।",
     "Despite photosynthesising, they are prokaryotes, so they sit in Monera rather than the plant kingdom."),

    ("five-kingdoms", "medium",
     "प्रोटिस्टा जगत के जीवों की मुख्य विशेषता क्या है?",
     "What is the main feature of organisms of the kingdom Protista?",
     ["एककोशिकीय प्रोकैरियोट", "एककोशिकीय यूकैरियोट", "बहुकोशिकीय प्रोकैरियोट", "बहुकोशिकीय निर्जीव"],
     ["Unicellular prokaryotes", "Unicellular eukaryotes", "Multicellular prokaryotes", "Multicellular non-living"],
     1,
     "अमीबा, पैरामीशियम जैसे एककोशिकीय यूकैरियोटिक जीव प्रोटिस्टा में रखे जाते हैं — केंद्रक अच्छी तरह संगठित होता है।",
     "Unicellular eukaryotes like Amoeba and Paramecium are placed in Protista — with a well-organised nucleus."),

    ("five-kingdoms", "easy",
     "अमीबा और पैरामीशियम किस जगत के सदस्य हैं?",
     "Amoeba and Paramecium are members of which kingdom?",
     ["मोनेरा", "फंजाई", "प्रोटिस्टा", "प्लांटी"],
     ["Monera", "Fungi", "Protista", "Plantae"],
     2,
     "ये एककोशिकीय यूकैरियोट हैं, इसलिए प्रोटिस्टा जगत में रखे जाते हैं।",
     "Being unicellular eukaryotes, they are kept in the kingdom Protista."),

    ("five-kingdoms", "medium",
     "यूग्लीना (Euglena) को प्रोटिस्टा में क्यों रखा गया है?",
     "Why is Euglena placed in Protista?",
     ["क्योंकि वह बहुकोशिकीय है", "क्योंकि वह एक ही जीव में पौधे जैसा (प्रकाश-संश्लेषण) और जंतु जैसा (गति-पोषण) लक्षण दोनों दिखाता है", "क्योंकि वह प्रोकैरियोटिक है", "क्योंकि वह मृत नहीं होता"],
     ["Because it is multicellular", "Because in one organism it shows both plant-like (photosynthesis) and animal-like (motility-nutrition) traits", "Because it is prokaryotic", "Because it is immortal"],
     1,
     "यूग्लीना में हरितलवक होने से भोजन बनाता है पर जंतुओं की तरह गति और परपोषण भी करता है — ऐसे मिश्र-लक्षण जगत-निर्धारण कठिन बनाते हैं।",
     "Euglena makes food with chloroplasts yet moves and feeds like an animal — such mixed traits make its kingdom-placement tricky."),

    ("five-kingdoms", "medium",
     "फंजाई (कवक) अपना भोजन कैसे प्राप्त करते हैं?",
     "How do fungi obtain their food?",
     ["प्रकाश-संश्लेषण से", "स्वपोषी होकर", "मृत जीव-पदार्थों से अवशोषण द्वारा (अपघटक/परपोषी)", "जल को तोड़कर"],
     ["By photosynthesis", "As autotrophs", "By absorption from dead organic matter (decomposers/parasites)", "By splitting water"],
     2,
     "कवकों में हरितलवक नहीं होते; वे मृत पदार्थों पर उगकर भोजन अवशोषित करते हैं या जीव-होस्ट पर परजीवी बनते हैं।",
     "Fungi lack chlorophyll; they grow on dead matter absorbing food or live as parasites on hosts."),

    ("five-kingdoms", "easy",
     "मशरूम और मोल्ड किस जगत के जीव हैं?",
     "Mushroom and mould belong to which kingdom?",
     ["प्लांटी", "फंजाई", "प्रोटिस्टा", "एनिमेलिया"],
     ["Plantae", "Fungi", "Protista", "Animalia"],
     1,
     "छत्रक (मशरूम), मोल्ड, यीस्ट — सभी कवक हैं और फंजाई जगत में रखे जाते हैं।",
     "Mushroom, mould and yeast are all fungi, placed in the kingdom Fungi."),

    ("five-kingdoms", "medium",
     "फंजाई की कोशिका भित्ति मुख्यतः किससे बनी होती है?",
     "The cell wall of fungi is mainly made of what?",
     ["सेल्युलोज", "काइटिन", "लिग्निन", "सुबेरिन"],
     ["Cellulose", "Chitin", "Lignin", "Suberin"],
     1,
     "पौधों की भित्ति सेल्युलोज की होती है जबकि कवकों की भित्ति काइटिन की — यही अंतर दोनों जगतों को अलग करता है।",
     "Plant walls are of cellulose while fungal walls are of chitin — a key difference separating the two kingdoms."),

    ("five-kingdoms", "medium",
     "लाइकेन (lichen) में कौन-से दो जीव सहजीवी रूप से रहते हैं?",
     "Which two organisms live symbiotically in a lichen?",
     ["कवक और शैवाल", "कवक और बैक्टीरिया-जड़", "शैवाल और मॉस", "कवक और फर्न"],
     ["A fungus and an alga", "A fungus and a root-bacterium", "An alga and a moss", "A fungus and a fern"],
     0,
     "लाइकेन में कवक जल-खनिज अवशोषित करता है और शैवाल भोजन बनाता है — दोनों का साझा लाभ सहजीवन है।",
     "In a lichen the fungus absorbs water and minerals while the alga makes food — mutual benefit in symbiosis."),

    ("five-kingdoms", "easy",
     "प्लांटी (पादप) जगत के जीवों की पोषण-विधि क्या है?",
     "What is the mode of nutrition of organisms of the kingdom Plantae?",
     ["परपोषी", "स्वपोषी (प्रकाश-संश्लेषण)", "अपघटक", "मिश्रित"],
     ["Heterotrophic", "Autotrophic (photosynthesis)", "Saprophytic", "Mixed"],
     1,
     "पादप हरितलवकों की सहायता से सूर्य-प्रकाश में भोजन स्वयं बनाते हैं — यही स्वपोषण है।",
     "Plants prepare their own food in sunlight with the help of chloroplasts — this is autotrophic nutrition."),

    ("five-kingdoms", "easy",
     "एनिमेलिया जगत के जीव भोजन कैसे प्राप्त करते हैं?",
     "How do animals of the kingdom Animalia obtain food?",
     ["स्वयं बनाकर", "अन्य जीवों का सेवन करके (परपोषी)", "अवशोषण द्वारा", "प्रकाश से"],
     ["By making it themselves", "By consuming other organisms (heterotrophic)", "By absorption", "From light"],
     1,
     "प्राणी हरितलवकविहीन हैं, अतः भोजन पचाने-ग्रहण करने के लिए अन्य जीवों पर निर्भर रहते हैं।",
     "Animals lack chlorophyll, so they depend on ingesting and digesting other organisms."),

    ("five-kingdoms", "medium",
     "बैक्टीरिया को पौधों से अलग किसने बताकर मोनेरा जगत बनाया गया — उनकी कोशिकाओं की क्या कमी इसका कारण है?",
     "Bacteria were separated into Monera — what deficiency in their cells is the reason?",
     ["कोशिका भित्ति का अभाव", "संगठित केंद्रक व केंद्रकीय झिल्ली का अभाव", "राइबोसोम का अभाव", "झिल्ली का अभाव"],
     ["Absence of cell wall", "Absence of an organised nucleus and nuclear membrane", "Absence of ribosomes", "Absence of a cell membrane"],
     1,
     "बैक्टीरिया प्रोकैरियोट हैं — केंद्रक-पदार्थ झिल्ली से घिरा नहीं होता; यही मौलिक भिन्नता उन्हें अलग जगत का अधिकारी बनाती है।",
     "Bacteria are prokaryotes — nuclear material is not membrane-bound; this fundamental difference earns them a separate kingdom."),

    ("five-kingdoms", "medium",
     "डायटम (सिलिका-कवक जैसे सूक्ष्म शैवाल) किस जगत में वर्गीकृत हैं?",
     "Diatoms (microscopic silica-shelled algae) are classified in which kingdom?",
     ["मोनेरा", "फंजाई", "प्रोटिस्टा", "प्लांटी"],
     ["Monera", "Fungi", "Protista", "Plantae"],
     2,
     "एककोशिकीय होने के कारण डायटम जैसे सूक्ष्म शैवाल प्रोटिस्टा में रखे जाते हैं, भले ही वे प्रकाश-संश्लेषण करते हों।",
     "Being unicellular, microscopic algae like diatoms go to Protista even though they photosynthesise."),

    ("five-kingdoms", "hard",
     "व्हिटेकर ने कवकों को पौधों से अलग जगत देने का सबसे बड़ा कारण क्या था?",
     "What was Whittaker's biggest reason for giving fungi a kingdom separate from plants?",
     ["कवक बड़े होते हैं", "कवकों की पोषण-विधि भिन्न है — हरितलवक रहित अवशोषण-पोषी", "कवक जल में नहीं रहते", "कवकों में कोशिका नहीं होती"],
     ["Fungi are large", "Their mode of nutrition differs — chlorophyll-less absorbers", "Fungi do not live in water", "Fungi have no cells"],
     1,
     "पोषण-विधि को व्हिटेकर का मुख्य आधार माना गया — पौधे स्वपोषी, कवक अवशोषण-पोषी; इसी भिन्नता से फंजाई अलग जगत बना।",
     "Nutrition was Whittaker's chief axis — plants autotrophic, fungi absorptive; this difference created the separate kingdom Fungi."),

    ("five-kingdoms", "hard",
     "कवकों और पौधों में एक साथ दो अंतर बताने वाला सही विकल्प कौन-सा है?",
     "Which option states TWO differences between fungi and plants together correctly?",
     ["कवकों में हरितलवक होते हैं, भित्ति सेल्युलोज की", "कवकों में हरितलवक नहीं होते और भित्ति काइटिन की होती है", "कवक एककोशिकीय होते हैं, पौधे प्रोकैरियोटिक", "कवक स्वपोषी होते हैं, पौधे अपघटक"],
     ["Fungi have chlorophyll and cellulose walls", "Fungi lack chlorophyll and have chitin walls", "Fungi are unicellular and plants prokaryotic", "Fungi are autotrophs and plants decomposers"],
     1,
     "दोनों अंतर एक साथ केवल दूसरे विकल्प में सही हैं — हरितलवक का अभाव और काइटिन भित्ति।",
     "Only the second option holds both differences together — absence of chlorophyll and chitinous wall."),

    ("five-kingdoms", "medium",
     "बहुकोशिकीय, स्वपोषी और सेल्युलोज भित्ति वाला जीव किस जगत का सदस्य होगा?",
     "A multicellular, autotrophic organism with cellulose cell walls belongs to which kingdom?",
     ["फंजाई", "प्लांटी", "एनिमेलिया", "प्रोटिस्टा"],
     ["Fungi", "Plantae", "Animalia", "Protista"],
     1,
     "बहुकोशिकीयता + स्वपोषण + सेल्युलोज भित्ति = पादप जगत की तीनों निशानियाँ।",
     "Multicellularity + autotrophy + cellulose walls = the three signatures of the plant kingdom."),

    ("five-kingdoms", "medium",
     "'प्रोटोजोआ' कहलाने वाले अमीबा-जैसे जीव आधुनिक वर्गीकरण में कहाँ गए?",
     "Where did Amoeba-like organisms, once called 'protozoa', go in modern classification?",
     ["मोनेरा में", "प्रोटिस्टा में", "एनिमेलिया में", "फंजाई में"],
     ["Into Monera", "Into Protista", "Into Animalia", "Into Fungi"],
     1,
     "पुराने 'प्रोटोजोआ' (अमीबा, पैरामीशियम) अब प्रोटिस्टा जगत में रखे जाते हैं — एककोशिकीय यूकैरियोट होने से।",
     "The old 'protozoa' (Amoeba, Paramecium) now sit in Protista — for being unicellular eukaryotes."),

    ("five-kingdoms", "hard",
     "निम्न में से किस जगत-उदाहरण युग्म सही है?",
     "Which kingdom-example pair among these is correct?",
     ["यीस्ट — प्रोटिस्टा", "स्पाइरोगाइरा — मोनेरा", "स्लाइम-मोल्ड — प्रोटिस्टा", "साइनोबैक्टीरिया — फंजाई"],
     ["Yeast — Protista", "Spirogyra — Monera", "Slime mould — Protista", "Cyanobacteria — Fungi"],
     2,
     "स्लाइम-मोल्ड प्रोटिस्टा के सदस्य हैं; यीस्ट फंजाई का, स्पाइरोगाइरा थैलोफाइटा (पादप) का और साइनोबैक्टीरिया मोनेरा का सदस्य है।",
     "Slime moulds are protists; yeast belongs to Fungi, Spirogyra to Thallophyta (plants) and cyanobacteria to Monera."),

    ("five-kingdoms", "easy",
     "पाँच जगतों में सबसे सरल (कम जटिल) जीवों का जगत कौन-सा माना जाता है?",
     "Which kingdom is considered to have the simplest (least complex) organisms?",
     ["एनिमेलिया", "प्लांटी", "मोनेरा", "फंजाई"],
     ["Animalia", "Plantae", "Monera", "Fungi"],
     2,
     "मोनेरा के प्रोकैरियोटिक जीव संगठित केंद्रक जैसी जटिलता से रहित हैं — इसीलिए सबसे सरल कहलाते हैं।",
     "Monera's prokaryotes lack complexities like an organised nucleus — hence called the simplest."),

    ("five-kingdoms", "medium",
     "यीस्ट (yeast) सतही रूप से पौधों जैसा जीव होने के बावजूद किस जगत में रखा जाता है?",
     "Despite superficially plant-like appearance, in which kingdom is yeast placed?",
     ["प्लांटी", "फंजाई", "मोनेरा", "प्रोटिस्टा"],
     ["Plantae", "Fungi", "Monera", "Protista"],
     1,
     "यीस्ट एककोशिकीय कवक है — हरितलवक नहीं, काइटिन भित्ति, अवशोषण-पोषण; अतः फंजाई में।",
     "Yeast is a unicellular fungus — no chlorophyll, chitin wall, absorptive feeding; hence Fungi."),

    ("five-kingdoms", "medium",
     "व्हिटेकर के वर्गीकरण में एक जगत से दूसरे जगत में रखने का निर्णय सबसे अधिक किस लक्षण पर टिका है?",
     "In Whittaker's scheme, the decision to place an organism in one kingdom over another rests most on which character?",
     ["आकार", "रंग", "कोशिका-प्रकार और पोषण-विधि", "गति की गति"],
     ["Size", "Colour", "Cell type and mode of nutrition", "Speed of movement"],
     2,
     "प्रोकैरियोट/यूकैरियोट और स्वपोषी/परपोषी का संयोजन ही जगत-निर्धारण की रीढ़ है — बाकी लक्षण गौण हैं।",
     "The prokaryote/eukaryote and autotroph/heterotroph combinations form the backbone of kingdom-assignment; other traits are secondary."),

    # ---------------- plant-diversity (25) ----------------
    ("plant-diversity", "easy",
     "थैलोफाइटा (Thallophyta) के पौधों की देह कैसी होती है?",
     "What is the body of thallophyte plants like?",
     ["अच्छी तरह जड़-तना-पत्ती में विभाजित", "जड़-तना-पत्ती में विभाजित नहीं (थैलस जैसी)", "केवल जड़ों वाली", "केवल पुष्पों वाली"],
     ["Well differentiated into root, stem and leaves", "Not differentiated into root, stem and leaves (thallus-like)", "Only roots", "Only flowers"],
     1,
     "शैवाल जैसे थैलोफाइटों की देह सरल थैलस होती है जिसमें विशेष जड़-तना-पत्तियों का विभाजन नहीं होता।",
     "In algae-like thallophytes the body is a simple thallus without distinct root, stem or leaves."),

    ("plant-diversity", "easy",
     "स्पाइरोगाइरा और उल्वा किस पादप-समूह के उदाहरण हैं?",
     "Spirogyra and Ulva are examples of which plant group?",
     ["ब्रायोफाइटा", "थैलोफाइटा", "टेरिडोफाइटा", "जिम्नोस्पर्म"],
     ["Bryophyta", "Thallophyta", "Pteridophyta", "Gymnospermae"],
     1,
     "ये सरल शरीर-विन्यास वाले शैवाल हैं — थैलोफाइटा के सदस्य।",
     "These are simple-bodied algae — members of Thallophyta."),

    ("plant-diversity", "medium",
     "शैवाल (algae) में पाए जाने वाले वर्णक मुख्यतः किस कार्य करते हैं?",
     "The pigments found in algae mainly serve which function?",
     ["जल सोखना", "प्रकाश-संश्लेषण करना", "स्वाभाविक रूप से वाष्प छोड़ना", "भूमि में एंकर बनाना",
     ],
     ["Absorbing water", "Carrying out photosynthesis", "Releasing vapour", "Anchoring in soil"],
     1,
     "शैवालों में हरित व अन्य वर्णक प्रकाश ग्रहण कर भोजन-निर्माण में सहायक होते हैं।",
     "Green and other pigments in algae capture light to help build food.",
     ),

    ("plant-diversity", "easy",
     "किस पादप-समूह को 'पादप जगत के उभयचर' कहा जाता है?",
     "Which plant group is called the 'amphibians of the plant kingdom'?",
     ["थैलोफाइटा", "ब्रायोफाइटा", "जिम्नोस्पर्म", "एंजियोस्पर्म"],
     ["Thallophyta", "Bryophyta", "Gymnospermae", "Angiospermae"],
     1,
     "मॉस-लिवरवर्ट जमीन पर तो रहते हैं पर लैंगिक प्रजनन के लिए जल के छिछले जल-स्त्रोत पर निर्भर रहते हैं — इसीलिए उभयचर कहलाते हैं।",
     "Mosses and liverworts live on land yet need a film of water for sexual reproduction — hence plant-amphibians."),

    ("plant-diversity", "medium",
     "मॉस (काई) की जड़ों की जगह क्या होता है?",
     "What takes the place of true roots in moss?",
     ["राइज़ॉइड (बाल जैसी संरचनाएँ)", "स्टोलोन", "बल्ब", "ट्यूबर"],
     ["Rhizoids (hair-like structures)", "Stolons", "Bulbs", "Tubers"],
     0,
     "ब्रायोफाइटों में सच्ची जड़ें नहीं — केवल राइज़ॉइड होते हैं जो देह को टिकाने और जल सोखने का काम करते हैं।",
     "Bryophytes lack true roots — only rhizoids anchor the body and soak water."),

    ("plant-diversity", "medium",
     "ब्रायोफाइटों में जल-संवहन के लिए विशेष ऊतक (xylem-phloem) की स्थिति क्या है?",
     "What is the status of special conducting tissue (xylem-phloem) in bryophytes?",
     ["पूर्ण रूप से विकसित", "अनुपस्थित", "केवल जड़ों में", "केवल पत्तियों में"],
     ["Fully developed", "Absent", "Only in roots", "Only in leaves"],
     1,
     "ब्रायोफाइटों में संवहन ऊतक नहीं होता; इसीलिए ये छोटे आकार के और नम स्थानों के होते हैं।",
     "Bryophytes lack vascular tissue; hence they stay small and confined to moist spots."),

    ("plant-diversity", "medium",
     "टेरिडोफाइटा (फर्न-समूह) की पहचान क्या है?",
     "What identifies the Pteridophyta (fern group)?",
     ["बीज बनाते हैं", "वास्तविक जड़, तना, पत्तियाँ और संवहन ऊतक — पर बीज नहीं, बीजाणु बनाते हैं", "केवल एककोशिकीय होते हैं", "फूल बनाते हैं"],
     ["They produce seeds", "True roots, stem, leaves and vascular tissue — but no seeds, they make spores", "They are unicellular", "They produce flowers"],
     1,
     "फर्न में जड़-तना-पत्ती का पूर्ण विभाजन और जाइलम-फ्लोएम होते हैं, फिर भी ये बीज नहीं बीजाणु से बढ़ते हैं।",
     "Ferns have full root-stem-leaf differentiation and xylem-phloem, yet they multiply by spores, not seeds."),

    ("plant-diversity", "easy",
     "मार्सीलिया और फर्न किस पादप-समूह के उदाहरण हैं?",
     "Marsilea and ferns are examples of which plant group?",
     ["थैलोफाइटा", "ब्रायोफाइटा", "टेरिडोफाइटा", "एंजियोस्पर्म"],
     ["Thallophyta", "Bryophyta", "Pteridophyta", "Angiospermae"],
     2,
     "फर्न, हॉर्सटेल, मार्सीलिया — ये सब टेरिडोफाइटा के सदस्य हैं।",
     "Fern, horsetail and Marsilea are all members of Pteridophyta."),

    ("plant-diversity", "medium",
     "जिम्नोस्पर्म का शाब्दिक अर्थ उनकी किस विशेषता से जुड़ा है?",
     "The literal meaning of 'gymnosperm' is tied to which of their features?",
     ["खुले फूल", "नग्न बीज — बिना फल-ावरण के", "खुली जड़ें", "नग्न तना"],
     ["Naked flowers", "Naked seeds — without a fruit covering", "Exposed roots", "Naked stem"],
     1,
     "'जिम्नोस्पर्म' = नग्न बीज; इनके बीज अंडाशय से ढके नहीं होते, फल नहीं बनता।",
     "'Gymnosperm' = naked seed; their seeds are not enclosed in an ovary and no fruit forms."),

    ("plant-diversity", "easy",
     "चीड़ (Pinus) और साइकस किस पादप-समूह के हैं?",
     "Pinus (pine) and Cycas belong to which plant group?",
     ["जिम्नोस्पर्म", "टेरिडोफाइटा", "ब्रायोफाइटा", "थैलोफाइटा"],
     ["Gymnospermae", "Pteridophyta", "Bryophyta", "Thallophyta"],
     0,
     "चीड़, साइकस, देवदार जैसे शंकुधारी वृक्ष जिम्नोस्पर्म हैं।",
     "Cone-bearing trees like pine, Cycas and deodar are gymnosperms."),

    ("plant-diversity", "medium",
     "जिम्नोस्पर्म के शंकु (cones) में क्या विकसित होते हैं?",
     "What develops in the cones of gymnosperms?",
     ["फल", "अनावृत बीज", "फूल की पंखुड़ियाँ", "कंद"],
     ["Fruits", "Naked seeds", "Flower petals", "Tubers"],
     1,
     "शंकुओं के भीतर बीज खुले रूप में विकसित होते हैं; फल का निर्माण नहीं होता।",
     "Seeds develop exposed inside the cones; no fruit is formed."),

    ("plant-diversity", "easy",
     "एंजियोस्पर्म (आवृतबीज) के बीज कैसे होते हैं?",
     "How are the seeds of angiosperms?",
     ["नग्न रूप से खुले", "फल के भीतर ढके हुए", "शंकु में खुले", "पानी में तैरते खुले"],
     ["Naked and exposed", "Enclosed inside a fruit", "Exposed in cones", "Floating exposed in water"],
     1,
     "एंजियोस्पर्म के बीज अंडाशय-व्युत्पन्न फल के भीतर सुरक्षित रहते हैं — इसीलिए 'आवृतबीज' कहलाते हैं।",
     "Angiosperm seeds stay protected inside a fruit derived from the ovary — hence 'covered seeds'."),

    ("plant-diversity", "easy",
     "फूल और फल केवल किस पादप-समूह में पाए जाते हैं?",
     "Flowers and fruits are found only in which plant group?",
     ["टेरिडोफाइटा", "ब्रायोफाइटा", "जिम्नोस्पर्म", "एंजियोस्पर्म"],
     ["Pteridophyta", "Bryophyta", "Gymnospermae", "Angiospermae"],
     3,
     "फूल बनाना और फल में बीज ढकना केवल एंजियोस्पर्म की विशेषता है।",
     "Bearing flowers and enclosing seeds in fruits is exclusive to angiosperms."),

    ("plant-diversity", "medium",
     "एंजियोस्पर्म को एकबीजपत्री और द्विबीजपत्री में किस आधार पर बाँटा जाता है?",
     "On what basis are angiosperms divided into monocots and dicots?",
     ["बीजों के रंग से", "भ्रूणपत्र (cotyledon) की संख्या से", "तने की मोटाई से", "जड़ की लंबाई से"],
     ["Colour of seeds", "Number of cotyledons", "Thickness of stem", "Length of root"],
     1,
     "भ्रूण में एक भ्रूणपत्र = एकबीजपत्री (गेहूँ), दो = द्विबीजपत्री (चना) — यही विभाजन-आधार है।",
     "One cotyledon in the embryo = monocot (wheat); two = dicot (gram) — that is the dividing basis."),

    ("plant-diversity", "easy",
     "गेहूँ और मक्का किस श्रेणी के एंजियोस्पर्म हैं?",
     "Wheat and maize are angiosperms of which category?",
     ["द्विबीजपत्री", "एकबीजपत्री", "नग्नबीजी", "बीजाणुजन्य"],
     ["Dicots", "Monocots", "Naked-seeded", "Spore-bearing"],
     1,
     "गेहूँ, मक्का, धान के बीज में एक ही भ्रूणपत्र होता है — अतः एकबीजपत्री।",
     "Wheat, maize and rice seeds hold a single cotyledon — hence monocots."),

    ("plant-diversity", "medium",
     "चना, मटर और आम के पौधे किस श्रेणी में आते हैं?",
     "Gram, pea and mango plants fall under which category?",
     ["एकबीजपत्री", "द्विबीजपत्री", "जिम्नोस्पर्म", "पर्णहरी शैवाल"],
     ["Monocots", "Dicots", "Gymnosperms", "Leafy algae"],
     1,
     "इनके बीजों में दो भ्रूणपत्र होते हैं — ये द्विबीजपत्री एंजियोस्पर्म हैं।",
     "Their seeds carry two cotyledons — they are dicot angiosperms."),

    ("plant-diversity", "medium",
     "'क्रिप्टोगैम' (गुप्त जननांगी) किन पादप-समूहों को कहा जाता है?",
     "Which plant groups are called 'cryptogams' (hidden reproductive organs)?",
     ["थैलोफाइटा, ब्रायोफाइटा, टेरिडोफाइटा", "केवल जिम्नोस्पर्म", "केवल एंजियोस्पर्म", "जिम्नोस्पर्म और एंजियोस्पर्म"],
     ["Thallophyta, Bryophyta, Pteridophyta", "Only gymnosperms", "Only angiosperms", "Gymnosperms and angiosperms"],
     0,
     "इन तीनों समूहों में बीज नहीं बनते — जननांग छिपे होते हैं और बीजाणु से वृद्धि होती है।",
     "These three groups make no seeds — reproductive organs stay hidden and growth occurs via spores."),

    ("plant-diversity", "medium",
     "'फैनेरोगैम' (प्रकट जननांगी) पौधों की पहचान क्या है?",
     "How are 'phanerogams' (visible reproductive organs) identified?",
     ["ये बीजाणु से बढ़ते हैं", "इनमें सुविकसित बीज बनते हैं", "इनमें जड़ें नहीं होतीं", "ये सभी जलीय होते हैं"],
     ["They grow from spores", "They produce well-developed seeds", "They lack roots", "They are all aquatic"],
     1,
     "जिम्नोस्पर्म और एंजियोस्पर्म में बीज बनते हैं जिनके जननांग स्पष्ट दिखते हैं — यही फैनेरोगैम हैं।",
     "Gymnosperms and angiosperms bear seeds with clearly visible reproductive organs — the phanerogams."),

    ("plant-diversity", "medium",
     "संवहन ऊतक (जाइलम-फ्लोएम) किस क्रम में पौधों में पहली बार पूर्ण रूप से दिखते हैं?",
     "Vascular tissue (xylem-phloem) appears fully for the first time in which group of plants?",
     ["थैलोफाइटा", "ब्रायोफाइटा", "टेरिडोफाइटा", "शैवाल"],
     ["Thallophyta", "Bryophyta", "Pteridophyta", "Algae"],
     2,
     "थैलोफाइटा-ब्रायोफाइटा में संवहन ऊतक नहीं; टेरिडोफाइटा से आगे के सभी पौधों में जाइलम-फ्लोएम पाए जाते हैं।",
     "Thallophytes and bryophytes lack vascular tissue; from pteridophytes onwards all plants have xylem and phloem."),

    ("plant-diversity", "medium",
     "मॉस-लिवरवर्ट सामान्यतः कैसे स्थानों पर उगते हैं?",
     "Mosses and liverworts usually grow in what kind of places?",
     ["शुष्क रेगिस्तान में", "नम और छायादार स्थानों पर", "समुद्र के खारे जल में", "ऊँची चट्टानों की धूप में"],
     ["Dry deserts", "Moist and shady places", "Salty sea water", "Sunny high rocks"],
     1,
     "संवहन ऊतक न होने और जल-आवश्यकता के कारण ब्रायोफाइटा नम-छायादार भूमि पर ही जीवित रह पाते हैं।",
     "Lacking vascular tissue and needing water, bryophytes survive only on moist shady ground."),

    ("plant-diversity", "medium",
     "फर्न की पत्तियों की पीठ (नीचे की सतह) पर बीजाणु कहाँ बनते हैं?",
     "Where on the underside of fern leaves are the spores formed?",
     ["जड़ों पर", "पत्तियों की निचली सतह पर बीजाणु-थैलों में", "तने के भीतर", "फूलों में"],
     ["On the roots", "In spore sacs on the lower surface of leaves", "Inside the stem", "In flowers"],
     1,
     "फर्न की पत्तियों के नीचे धब्बेदार बीजाणु-थैले (sori) दिखते हैं जिनसे सूक्ष्म बीजाणु गिरते हैं।",
     "Spotted spore sacs (sori) on the fern's leaf underside release the tiny spores."),

    ("plant-diversity", "medium",
     "एक पेड़ में बीज हैं पर फल नहीं बनता — शंकुओं में बीज खुले दिखते हैं; यह पेड़ किस समूह का है?",
     "A tree bears seeds but forms no fruit — its seeds lie exposed in cones; which group does it belong to?",
     ["एंजियोस्पर्म", "जिम्नोस्पर्म", "टेरिडोफाइटा", "ब्रायोफाइटा"],
     ["Angiosperm", "Gymnosperm", "Pteridophyta", "Bryophyta"],
     1,
     "फल-कवच के अभाव में शंकुओं में खुले बीज = जिम्नोस्पर्म की निशानी; फल में बंद बीज एंजियोस्पर्म बनाते हैं।",
     "Seeds exposed in cones with no fruit coat = gymnosperm hallmark; seeds sealed in fruit mark angiosperms."),

    ("plant-diversity", "hard",
     "देह-जटिलता बढ़ने का सही क्रम (सरल से जटिल की ओर) कौन-सा है?",
     "Which is the correct sequence of increasing body complexity (simple to complex)?",
     ["टेरिडोफाइटा → ब्रायोफाइटा → थैलोफाइटा → जिम्नोस्पर्म", "थैलोफाइटा → ब्रायोफाइटा → टेरिडोफाइटा → जिम्नोस्पर्म → एंजियोस्पर्म", "एंजियोस्पर्म → जिम्नोस्पर्म → टेरिडोफाइटा → ब्रायोफाइटा", "ब्रायोफाइटा → थैलोफाइटा → एंजियोस्पर्म → टेरिडोफाइटा"],
     ["Pteridophyta → Bryophyta → Thallophyta → Gymnospermae", "Thallophyta → Bryophyta → Pteridophyta → Gymnospermae → Angiospermae", "Angiospermae → Gymnospermae → Pteridophyta → Bryophyta", "Bryophyta → Thallophyta → Angiospermae → Pteridophyta"],
     1,
     "सरल थैलस से लेकर फूल-फल वाले जटिल पौधों तक क्रम है — थैलो → ब्रायो → टेरिडो → जिम्नो → एंजियो।",
     "From a simple thallus to complex flowering plants the order runs — thallo → bryo → pterido → gymno → angio."),

    ("plant-diversity", "hard",
     "बीजाणु (spores) से नई संतति बनाने वाले पौधे कौन-से हैं?",
     "Which plants raise new progeny from spores?",
     ["केवल जिम्नोस्पर्म", "थैलोफाइटा, ब्रायोफाइटा और टेरिडोफाइटा", "केवल एंजियोस्पर्म", "जिम्नोस्पर्म और एंजियोस्पर्म दोनों"],
     ["Only gymnosperms", "Thallophyta, Bryophyta and Pteridophyta", "Only angiosperms", "Both gymnosperms and angiosperms"],
     1,
     "शैवाल, मॉस और फर्न बीज नहीं बनाते — बीजाणुओं से बढ़ते हैं; जिम्नोस्पर्म/एंजियोस्पर्म बीज से बढ़ते हैं।",
     "Algae, mosses and ferns make no seeds — they grow from spores; gymnosperms and angiosperms grow from seeds."),

    ("plant-diversity", "hard",
     "फर्न किसी बगीचे में उगा है — उसकी पहचान के लिए सबसे उपयुक्त लक्षण-त्रयी कौन-सी है?",
     "A fern grows in a garden — which triad of features best identifies it?",
     ["नग्न बीज, शंकु, सदाबहार", "जड़-तना-पत्ती का विभाजन, संवहन ऊतक, बीजाणु बनना", "फूल, फल, दो भ्रूणपत्र", "राइज़ॉइड, थैलस, बीज"],
     ["Naked seeds, cones, evergreen", "Root-stem-leaf differentiation, vascular tissue, spore formation", "Flower, fruit, two cotyledons", "Rhizoids, thallus, seeds"],
     1,
     "फर्न = टेरिडोफाइटा — पूर्ण देह-विभाजन + जाइलम-फ्लोएम + बीजाणु-प्रजनन; यही तीन लक्षण मिलकर पहचान देते हैं।",
     "Fern = pteridophyte — full body differentiation + xylem-phloem + spore reproduction; together these three clinch the ID."),

    # ---------------- heredity-variation (25) ----------------
    ("heredity-variation", "easy",
     "आनुवंशिकता (heredity) के अध्ययन का आधार बनने वाले प्रयोग किसने किए?",
     "Who performed the experiments that became the foundation of the study of heredity?",
     ["ग्रेगर जोहान मेंडल", "आर.एच. व्हिटेकर", "रॉबर्ट हुक", "कार्ल लिनियस"],
     ["Gregor Johann Mendel", "R.H. Whittaker", "Robert Hooke", "Carl Linnaeus"],
     0,
     "मेंडल ने मटर के पौधों पर प्रयोग कर आनुवंशिकता के नियम दिए; इसीलिए उन्हें आनुवंशिकी का जनक कहते हैं।",
     "Mendel derived the laws of inheritance from pea-plant experiments; hence he is called the father of genetics."),

    ("heredity-variation", "easy",
     "मेंडल ने अपने प्रयोग किस पौधे पर किए थे?",
     "On which plant did Mendel conduct his experiments?",
     ["सरसों", "मटर (Pisum sativum)", "गेहूँ", "धान"],
     ["Mustard", "Garden pea (Pisum sativum)", "Wheat", "Rice"],
     1,
     "मटर के पौधे में स्पष्ट विपरीत लक्षणों वाली किस्में उपलब्ध थीं और जीवन-चक्र छोटा था — यही कारण चुनाव का था।",
     "Pea plants offered varieties with clearly contrasting traits and a short life cycle — the reason for the choice."),

    ("heredity-variation", "medium",
     "मेंडल ने मटर को ही अपना प्रयोग-पौधा क्यों चुना?",
     "Why did Mendel choose the pea as his experimental plant?",
     ["क्योंकि वह बहुत बड़ा होता है", "क्योंकि उसमें स्पष्ट विपरीत लक्षण जोड़े थे और आत्मपरागण संभव था", "क्योंकि वह बिना पानी के जीता है", "क्योंकि उसके फूल रंग-बिरंगे होते हैं"],
     ["Because it grows very large", "Because it had clear contrasting trait pairs and allowed self-pollination", "Because it survives without water", "Because its flowers are colourful"],
     1,
     "लंबा-बौना, गोल-झुर्रुआ जैसे सात स्पष्ट विपरीत लक्षण, आत्मपरागण की सुविधा और छोटा जीवन-चक्र — ये गुण मटर को आदर्श बनाते हैं।",
     "Seven clear contrasting traits (tall-dwarf, round-wrinkled), easy self-pollination and a short life cycle made the pea ideal."),

    ("heredity-variation", "easy",
     "प्रभावी (dominant) लक्षण की परिभाषा क्या है?",
     "How is a dominant trait defined?",
     ["जो लक्षण F1 में अदृश्य रह जाता है", "जो लक्षण संकरण में अपने विपरीत लक्षण को ढककर स्वयं प्रकट होता है", "जो लक्षण केवल बीज में होता है", "जो लक्षण कभी वंश में नहीं आता"],
     ["The trait that stays hidden in F1", "The trait that masks its opposite partner and expresses itself in a cross", "The trait present only in seeds", "The trait that never reaches the progeny"],
     1,
     "प्रभावी लक्षण युग्मविकल्पी में से स्वयं प्रकट हो जाता है; अप्रभावी (recessive) लक्षण उसके सामने छिप जाता है।",
     "Of a pair, the dominant trait expresses itself; the recessive partner stays hidden before it."),

    ("heredity-variation", "easy",
     "जीन-प्ररूप (genotype) और लक्षण-प्ररूप (phenotype) में क्या अंतर है?",
     "What is the difference between genotype and phenotype?",
     ["दोनों एक ही हैं", "जीन-प्ररूप = जीनों की आंतरिक संरचना; लक्षण-प्ररूप = दिखने वाला बाह्य लक्षण", "जीन-प्ररूप केवल पौधों में होता है", "लक्षण-प्ररूप केवल जानवरों में होता है"],
     ["Both are the same", "Genotype = internal genetic makeup; phenotype = observable outward trait", "Genotype occurs only in plants", "Phenotype occurs only in animals"],
     1,
     "Tt का जीन-प्ररूप भिन्न है पर लक्षण-प्ररूप (लंबा) TT जैसा ही — आंतरिक बनाम बाह्य का यही अंतर है।",
     "Tt differs in genotype yet matches TT in phenotype (tall) — internal makeup versus outward appearance."),

    ("heredity-variation", "medium",
     "समयुग्मजी (homozygous) और विषमयुग्मजी (heterozygous) में क्या भेद है?",
     "What distinguishes homozygous from heterozygous?",
     ["समयुग्मजी में दोनों जीन-प्रतिरूप समान होते हैं, विषमयुग्मजी में भिन्न", "समयुग्मजी में जीन नहीं होते", "विषमयुग्मजी सदैव अप्रभावी होता है", "कोई भेद नहीं"],
     ["Homozygous has both gene copies alike; heterozygous has different copies", "Homozygous lacks genes", "Heterozygous is always recessive", "No difference"],
     0,
     "TT या tt = समयुग्मजी (एक जैसे प्रतिरूप); Tt = विषमयुग्मजी (एक प्रभावी + एक अप्रभावी)।",
     "TT or tt = homozygous (alike copies); Tt = heterozygous (one dominant + one recessive)."),

    ("heredity-variation", "easy",
     "TT (लंबा) × tt (बौना) संकरण की F1 पीढ़ी कैसी होगी?",
     "What will the F1 generation of a TT (tall) × tt (dwarf) cross be like?",
     ["सभी बौने", "सभी लंबे (Tt)", "आधे लंबे, आधे बौने", "मध्यम ऊँचाई"],
     ["All dwarf", "All tall (Tt)", "Half tall, half dwarf", "Intermediate height"],
     1,
     "प्रत्येक F1 पौधे को जनकों से T और t मिलता है — सभी Tt; T प्रभावी होने से सब लंबे दिखते हैं।",
     "Every F1 plant receives T from one parent and t from the other — all Tt; with T dominant, all appear tall."),

    ("heredity-variation", "hard",
     "Tt × Tt संकरण की F2 पीढ़ी में लंबे : बौने का अनुपात क्या होता है?",
     "In the F2 generation of a Tt × Tt cross, what is the ratio of tall : dwarf?",
     ["1 : 1", "2 : 1", "3 : 1", "9 : 3"],
     ["1 : 1", "2 : 1", "3 : 1", "9 : 3"],
     2,
     "F2 में TT, Tt, Tt, tt बनते हैं — तीन लंबे एक बौना; अर्थात् 3 : 1 लक्षण-प्ररूप अनुपात।",
     "F2 yields TT, Tt, Tt, tt — three tall to one dwarf; the 3:1 phenotypic ratio."),

    ("heredity-variation", "hard",
     "Tt × Tt की F2 पीढ़ी में जीन-प्ररूप (genotypic) अनुपात क्या है?",
     "What is the genotypic ratio in the F2 generation of Tt × Tt?",
     ["3 : 1", "1 : 2 : 1", "9 : 3 : 3 : 1", "2 : 2"],
     ["3 : 1", "1 : 2 : 1", "9 : 3 : 3 : 1", "2 : 2"],
     1,
     "TT : Tt : tt = 1 : 2 : 1 — यही जीन-प्ररूप अनुपात है; लक्षण-प्ररूप 3 : 1 से इसे भ्रमित न करें।",
     "TT : Tt : tt = 1 : 2 : 1 — the genotypic ratio; do not confuse it with the 3:1 phenotypic ratio."),

    ("heredity-variation", "medium",
     "अप्रभावी (recessive) लक्षण कब प्रकट होता है?",
     "When does a recessive trait express itself?",
     ["जब एक भी प्रभावी जीन हो", "जब दोनों जीन-प्रतिरूप अप्रभावी हों (जैसे tt)", "कभी नहीं", "केवल F1 में"],
     ["Even when one dominant gene is present", "Only when both gene copies are recessive (as in tt)", "Never", "Only in F1"],
     1,
     "अप्रभावी लक्षण केवल समयुग्मजी अप्रभावी अवस्था (tt) में ही दिखता है; एक T आते ही वह ढक जाता है।",
     "A recessive trait appears only in the double-recessive state (tt); a single T masks it."),

    ("heredity-variation", "hard",
     "Tt × Tt संकरण के F2 में बौने पौधों का प्रतिशत कितना होगा?",
     "What percentage of the F2 of a Tt × Tt cross will be dwarf?",
     ["25%", "50%", "75%", "100%"],
     ["25%", "50%", "75%", "100%"],
     0,
     "चार संततियों में एक tt होता है — यानी 25% बौने; 75% लंबे।",
     "One of the four offspring is tt — 25% dwarf; the other 75% are tall."),

    ("heredity-variation", "medium",
     "मेंडल के 'कारक' आज किस नाम से जाने जाते हैं?",
     "By what name are Mendel's 'factors' known today?",
     ["कोशिकाएँ", "जीन", "प्रोटीन", "वायरस"],
     ["Cells", "Genes", "Proteins", "Viruses"],
     1,
     "मेंडल ने लक्षणों को संचारित करने वाली इकाइयों को कारक कहा; आज ये जीन कहलाती हैं।",
     "Mendel called the units transmitting traits 'factors'; today we know them as genes."),

    ("heredity-variation", "medium",
     "युग्मविकल्पी (alleles) क्या होते हैं?",
     "What are alleles?",
     ["एक ही जीन के दो वैकल्पिक रूप जो एक ही लक्षण को नियंत्रित करते हैं", "दो भिन्न जीन", "कोशिका के दो अंग", "दो अलग गुणसूत्र"],
     ["Two alternative forms of the same gene controlling one trait", "Two different genes", "Two cell organelles", "Two separate chromosomes"],
     0,
     "लंबाई जीन के T और t रूप युग्मविकल्पी हैं — एक ही लक्षण के दो प्रतिरूप।",
     "The T and t forms of the height gene are alleles — two versions of the one trait."),

    ("heredity-variation", "medium",
     "गुणसूत्रों के युग्म से संतति को जीन कैसे मिलते हैं?",
     "How does an offspring receive its genes from a chromosome pair?",
     ["दोनों जीन एक ही जनक से", "प्रत्येक जनक से एक-एक प्रतिरूप (गुणसूत्र के वियोजन से)", "केवल माता से दोनों", "यादृच्छिक तीन जनकों से"],
     ["Both genes from one parent", "One copy from each parent (through separation of chromosomes)", "Both only from the mother", "Randomly from three parents"],
     1,
     "प्रत्येक जनक अपने युग्म में से एक गुणसूत्र यादृच्छिक रूप से देता है — इसी वियोजन से संतति को एक-एक प्रतिरूप मिलता है।",
     "Each parent passes one chromosome of the pair at random — through this separation the young gets one copy apiece."),

    ("heredity-variation", "easy",
     "'विविधता' (variation) से क्या तात्पर्य है?",
     "What is meant by 'variation'?",
     ["एक ही जाति के जीवों में पाए जाने वाले अंतर", "सभी जीवों की समानता", "जीवों का एक-सा भोजन", "निर्जीव वस्तुओं के अंतर"],
     ["The differences found among individuals of the same species", "Similarity of all organisms", "Identical food of organisms", "Differences among non-living things"],
     0,
     "एक ही जाति के सदस्य भी रंग, ऊँचाई, रूप में भिन्न होते हैं — यही विविधता है।",
     "Members of one species still differ in colour, height and form — that is variation."),

    ("heredity-variation", "medium",
     "नई संततियों में विविधताएँ किन प्रक्रियाओं से उत्पन्न होती हैं?",
     "By which processes do variations arise in new progeny?",
     ["केवल भोजन से", "लैंगिक प्रजनन के दौरान जीन-संयोजन और डीएनए-प्रतिरूपण की लघु त्रुटियों से", "केवल व्यायाम से", "केवल जलवायु से"],
     ["From food alone", "From gene combinations during sexual reproduction and minor errors of DNA copying", "From exercise alone", "From climate alone"],
     1,
     "दो जनकों के जीन मिलने के अनगिनत संयोजन और डीएनए कॉपी में आने वाली सूक्ष्म गलतियाँ — दोनों विविधता के स्रोत हैं।",
     "Countless combinations of two parents' genes and tiny DNA-copying slips — both feed variation."),

    ("heredity-variation", "medium",
     "किसी जाति के लिए विविधता (variation) महत्वपूर्ण क्यों है?",
     "Why is variation important for a species?",
     ["यह सभी जीवों को समान बनाती है", "परिस्थितियाँ बदलने पर कम-से-कम कुछ सदस्यों के जीवित रहने की संभावना बढ़ाती है", "यह प्रजनन रोकती है", "इसका कोई महत्व नहीं"],
     ["It makes all organisms identical", "If conditions change, it raises the chance that at least some members survive", "It stops reproduction", "It has no importance"],
     1,
     "यदि पर्यावरण में प्रतिकूल बदलाव आए तो विविध लक्षणों वाली आबादी में से कुछ जीव उसे झेल लेते हैं — जाति बची रहती है।",
     "Should the environment turn hostile, some members of a varied population withstand it — the species persists."),

    ("heredity-variation", "easy",
     "मानव नर (पुरुष) के लिंग-गुणसूत्र कौन-से होते हैं?",
     "Which are the sex chromosomes of a human male?",
     ["XX", "XY", "YY", "XO"],
     ["XX", "XY", "YY", "XO"],
     1,
     "पुरुष में एक X और एक Y गुणसूत्र होता है; स्त्री में दोनों X होते हैं।",
     "A male has one X and one Y chromosome; a female has two X chromosomes."),

    ("heredity-variation", "easy",
     "मानव मादा (स्त्री) के लिंग-गुणसूत्र कौन-से होते हैं?",
     "Which are the sex chromosomes of a human female?",
     ["XY", "XX", "YY", "XYY"],
     ["XY", "XX", "YY", "XYY"],
     1,
     "स्त्री में दोनों लिंग-गुणसूत्र X होते हैं — इसीलिए अंडे में सदैव X ही जाता है।",
     "Both sex chromosomes of a female are X — hence her egg always carries an X."),

    ("heredity-variation", "hard",
     "संतान का लिंग निर्धारण में वास्तव में किसके शुक्राणु पर निर्भर करता है?",
     "The sex of the child in fact depends on whose gamete?",
     ["माता के अंडे पर", "पिता के शुक्राणु पर (X या Y वहन करने पर)", "दोनों पर समान रूप से", "निर्भर नहीं करता"],
     ["The mother's egg", "The father's sperm (carrying either X or Y)", "Equally on both", "It depends on neither"],
     1,
     "माता का अंडा तो सदैव X देता है; पिता का शुक्राणु X दे तो कन्या (XX), Y दे तो पुत्र (XY) — अतः निर्णायक पिता है।",
     "The mother's egg always gives an X; the father's sperm gives X for a girl (XX) or Y for a boy (XY) — the father is decisive."),

    ("heredity-variation", "medium",
     "मानव में पुत्र या पुत्री होने की प्रायिकता कितनी होती है?",
     "What is the probability of a human child being a boy or a girl?",
     ["पुत्र 75%, पुत्री 25%", "दोनों 50%–50%", "पुत्री 75%, पुत्र 25%", "निश्चित क्रम में बदलती है"],
     ["Boy 75%, girl 25%", "Both 50%–50%", "Girl 75%, boy 25%", "Changes in a fixed order"],
     1,
     "X-शुक्राणु और Y-शुक्राणु बनने की संख्या बराबर होती है, इसलिए दोनों लिंग की संभावना समान 50% रहती है।",
     "X-bearing and Y-bearing sperms form in equal numbers, so each sex has an equal 50% chance."),

    ("heredity-variation", "medium",
     "मानव मादा के अंडे (ovum) में लिंग-गुणसूत्र क्या होता है?",
     "What sex chromosome does a human female's egg always carry?",
     ["सदैव Y", "सदैव X", "कभी X कभी Y", "कोई नहीं"],
     ["Always Y", "Always X", "Sometimes X, sometimes Y", "None"],
     1,
     "स्त्री का लिंग-युग्म XX है, अतः हर अंडे में X ही जाता है; Y तो केवल शुक्राणु से आ सकता है।",
     "A female's pair is XX, so every egg carries an X; a Y can only come from the sperm."),

    ("heredity-variation", "medium",
     "संतान का लिंग किस क्षण तय हो जाता है?",
     "At which moment is a child's sex decided?",
     ["जन्म के समय", "गर्भ के पाँचवें माह में", "निषेचन (fertilisation) के समय जब शुक्राणु अंडे से मिलता है", "भोजन के प्रकार से बाद में"],
     ["At birth", "In the fifth month of pregnancy", "At fertilisation, when the sperm meets the egg", "Later, depending on food type"],
     2,
     "शुक्राणु (X/Y) और अंडे (X) के मिलने पर ही युग्म तय हो जाता है — लिंग निषेचन के क्षण निर्धारित है।",
     "The pairing of sperm (X/Y) with the egg (X) settles the combo — sex is fixed at the moment of fertilisation."),

    ("heredity-variation", "hard",
     "तैरना सीख लेने से बनी मजबूत बाँहें अगली पीढ़ी में क्यों नहीं जातीं?",
     "Why are stronger arms acquired by learning to swim not passed to the next generation?",
     ["क्योंकि अर्जित लक्षण जीन में परिवर्तन नहीं करते — केवल जन्यु (inherited) लक्षण ही संतति को मिलते हैं", "क्योंकि बाँहें जीन से नहीं बनतीं", "क्योंकि तैरना निषेध है", "क्योंकि जीन जन्म के बाद बदल जाते हैं"],
     ["Because acquired traits do not alter genes — only inherited traits reach the progeny", "Because arms are not built by genes", "Because swimming is forbidden", "Because genes change after birth"],
     0,
     "जीवनकाल में अर्जित (acquired) परिवर्तन जनन कोशिकाओं के डीएनए में नहीं लिखे जाते; केवल जन्यु लक्षण ही संतान को मिलते हैं।",
     "Changes acquired during a lifetime are not written into the DNA of germ cells; only inherited traits reach offspring."),

    ("heredity-variation", "medium",
     "निम्न में से कौन-सा मानवीय लक्षण जन्यु (inherited) है, अर्जित नहीं?",
     "Which of the following human traits is inherited, not acquired?",
     ["साइकिल चलाना", "मोटी हो गई बाहें", "कान की पतली निचली पत्ती (free earlobe)", "तेज चलने की आदत"],
     ["Cycling", "Thickened arms", "Free earlobe", "The habit of walking fast"],
     2,
     "कान-पत्ती का जुड़ा होना या मुक्त होना जीनों से तय होता है; साइकिल चलाने जैसे गुण अनुभव से अर्जित होते हैं।",
     "Whether the earlobe is attached or free is gene-decided; skills like cycling are acquired by experience."),

    # ---------------- habitats-adaptations (20) ----------------
    ("habitats-adaptations", "easy",
     "'आवास' (habitat) से क्या तात्पर्य है?",
     "What is meant by 'habitat'?",
     ["जीव का भोजन", "वह स्थान जहाँ जीव रहता है और जहाँ उसे भोजन-जल-आश्रय मिलता है", "जीव का रंग", "जीव की आयु"],
     ["An organism's food", "The place where an organism lives and finds food, water and shelter", "An organism's colour", "An organism's age"],
     1,
     "आवास जीव का घर-क्षेत्र है — जैसे मछली का जल और ऊँट का रेगिस्तान।",
     "A habitat is an organism's home ground — water for a fish, desert for a camel."),

    ("habitats-adaptations", "easy",
     "'अनुकूलन' (adaptation) किसे कहते हैं?",
     "What is called an 'adaptation'?",
     ["जीव का एक स्थान से दूसरे स्थान जाना", "अपने आवास में जीवित रहने के लिए जीव में पाई जाने वाली विशेष विशेषताएँ", "जीव का सो जाना", "जीवों का परस्पर भोजन"],
     ["An organism moving from one place to another", "Special features found in an organism that help it survive in its habitat", "An organism sleeping", "Organisms feeding each other"],
     1,
     "ऊँट की पलकें, मछली के पंख — ये अनुकूलन हैं जो अपने-अपने आवास में जीवन सुगम बनाते हैं।",
     "A camel's eyelashes, a fish's fins — adaptations that ease life in their respective habitats."),

    ("habitats-adaptations", "easy",
     "जल में रहने वाले जीवों का आवास किस प्रकार का होता है?",
     "What type of habitat do water-dwelling organisms have?",
     ["स्थलीय", "जलीय (aquatic)", "वायवीय", "भूमिगत"],
     ["Terrestrial", "Aquatic", "Aerial", "Underground"],
     1,
     "मछली, झींगा, उल्ली जैसे जीव जलीय आवास के हैं; स्थलीय आवास ज़मीन पर होता है।",
     "Fish, prawn, octopus live in aquatic habitats; terrestrial ones lie on land."),

    ("habitats-adaptations", "easy",
     "मछली की श्वसन-संरचना कौन-सी है जो उसे जल में साँस लेने देती है?",
     "Which respiratory structure lets a fish breathe in water?",
     ["फेफड़े", "गलफड़े (gills)", "त्वचा", "श्वासनली"],
     ["Lungs", "Gills", "Skin", "Trachea"],
     1,
     "गलफड़े जल से घुली ऑक्सीजन लेते हैं — यह जलीय जीवन का मुख्य अनुकूलन है।",
     "Gills extract oxygen dissolved in water — the prime adaptation for aquatic life."),

    ("habitats-adaptations", "easy",
     "मछली की धारारेखीय (streamlined) देह उसे कैसे सहायक है?",
     "How does a fish's streamlined body help it?",
     ["जल में घर्षण घटाकर सरलता से तैरने में", "जमीन पर चलने में", "उड़ने में", "गहराई में ऑक्सीजन बनाने में"],
     ["By reducing water resistance for easy swimming", "In walking on land", "In flying", "In producing oxygen at depth"],
     0,
     "संकरी-पतली देह जल को आसानी से काटती है — तेज़ और ऊर्जा-कुशल तैराकी धारारेखीय आकार का लाभ है।",
     "The narrow tapering body cuts water easily — fast, energy-efficient swimming is the payoff of the stream shape."),

    ("habitats-adaptations", "easy",
     "मछली के पंख (fins) मुख्यतः क्या करते हैं?",
     "What do the fins of a fish mainly do?",
     ["श्वसन", "तैरते समय संतुलन और दिशा-नियंत्रण", "भोजन पचाना", "जनन"],
     ["Breathing", "Balance and steering while swimming", "Digesting food", "Reproduction"],
     1,
     "पंख रुड़ी का काम करते हैं — मोड़ना, रुकना और संतुलन रखना।",
     "Fins work like rudders — turning, stopping and keeping balance."),

    ("habitats-adaptations", "medium",
     "रेगिस्तान में कैक्टस जैसे पौधों की पत्तियाँ काँटों में क्यों बदल गई हैं?",
     "Why have leaves of desert plants like cactus turned into spines?",
     ["जिससे जल की हानि कम से कम हो", "जिससे प्रकाश अधिक मिले", "जिससे जड़ें गहरी जाएँ", "जिससे फूल सुंदर लगें"],
     ["To minimise the loss of water", "To receive more light", "To send roots deeper", "To make flowers attractive"],
     0,
     "काँटे बनने से पत्ती-सतह लगभग समाप्त हो जाती है — वाष्पीकरण से जल की बचत होती है; भोजन तने में बनता है।",
     "Becoming spines removes almost all leaf surface — water saved from vapour loss; food is made in the stem."),

    ("habitats-adaptations", "medium",
     "रेगिस्तान के ऊँट के कूबड़ (hump) में सामान्यतः क्या भरा रहता है?",
     "What does the hump of a desert camel generally store?",
     ["जल", "वसा", "प्रोटीन", "वायु"],
     ["Water", "Fat", "Protein", "Air"],
     1,
     "कूबड़ वसा का भंडार है, पानी का नहीं — यही वसा जरूरत पर ऊर्जा और उप-उत्पाद के रूप में जल देती है; 'कूबड़=पानी' एक प्रसिद्ध भ्रम है।",
     "The hump stores fat, not water — on demand it yields energy plus metabolic water; 'hump = water' is a famous myth."),

    ("habitats-adaptations", "medium",
     "ध्रुवीय भालू के शरीर की मोटी वसा-परत (blubber) क्या कार्य करती है?",
     "What does the thick fat layer (blubber) of a polar bear do?",
     ["ठंड से रक्षा और ऊर्जा-भंडार", "जल में डूबने में सहायता", "गर्मी में शीतलन", "रंग बदलना"],
     ["Protection from cold and an energy store", "Help in sinking in water", "Cooling in summer", "Changing colour"],
     0,
     "बर्फीले आवास में वसा-परत शरीर की गर्मी रोकती है और भुखमरी के दिनों में ऊर्जा देती है।",
     "In an icy habitat the fat layer traps body heat and supplies energy through starving days."),

    ("habitats-adaptations", "medium",
     "पहाड़ी बकरी जैसे जीवों की खुर (hooves) कैसे होते हैं?",
     "What are the hooves of mountain goats like?",
     ["चौड़े और चपटे", "मजबूत और खुरों वाले — चट्टानों पर पकड़ के लिए", "लंबे नाखूनदार", "झिल्लीदार"],
     ["Broad and flat", "Strong and split — for grip on rocks", "Long clawed", "Webbed"],
     1,
     "खुरों वाले मजबूत पैर ढलानों पर चिपकने और कूदने में सहायक हैं — पहाड़ी आवास का अनुकूलन।",
     "Strong hoofed legs grip and leap on slopes — the mountain-habitat adaptation."),

    ("habitats-adaptations", "medium",
     "मेंढक अपना जीवन कैसे व्यतीत करता है?",
     "How does the frog spend its life?",
     ["पूर्णतः जल में", "पूर्णतः स्थल पर", "जल में भी और स्थल पर भी — दोनों जगह", "केवल पेड़ों पर"],
     ["Entirely in water", "Entirely on land", "Both in water and on land", "Only on trees"],
     2,
     "मेंढक जल के पास रहता है — नम त्वचा और जल में अंडे देने के कारण वह दोनों जगहों से जुड़ा है।",
     "The frog stays near water — its moist skin and water-laid eggs tie it to both worlds."),

    ("habitats-adaptations", "medium",
     "रेगिस्तान के कई जीव (जैसे कंगारू-चूहा) दिन में बिल में छिपे रहते और रात में सक्रिय होते हैं — क्यों?",
     "Many desert animals (like the kangaroo rat) hide in burrows by day and stay active at night — why?",
     ["दिन की तेज़ गर्मी और जल-हानि से बचने के लिए", "क्योंकि उन्हें अंधेरा पसंद है", "क्योंकि दिन में भोजन उपलब्ध नहीं", "क्योंकि रात में शिकारी सो जाते हैं"],
     ["To avoid the intense daytime heat and water loss", "Because they like darkness", "Because food is unavailable by day", "Because predators sleep at night"],
     0,
     "रात्रिचर होना रेगिस्तान का क्लासिक अनुकूलन है — ठंडी रात में घूमने से जल की बचत होती है।",
     "Being nocturnal is the classic desert adaptation — roaming in the cool night saves body water."),

    ("habitats-adaptations", "medium",
     "सभी जीवों में समान रूप से पाई जाने वाली जीवन-प्रक्रिया कौन-सी है?",
     "Which life process is found equally in all living beings?",
     ["प्रकाश-संश्लेषण", "श्वसन", "पुष्पन", "डिंब-जनन"],
     ["Photosynthesis", "Respiration", "Flowering", "Egg-laying"],
     1,
     "एककोशिकीय से मानव तक सब जीव ऊर्जा के लिए श्वसन करते हैं; प्रकाश-संश्लेषण केवल हरे पौधों में।",
     "From single-celled life to humans, all respire for energy; photosynthesis belongs only to green plants."),

    ("habitats-adaptations", "easy",
     "बच्चे का शरीर समय के साथ बढ़ता है — यह किस जीवन-लक्षण का उदाहरण है?",
     "A child's body increases in size with time — this exemplifies which life characteristic?",
     ["वृद्धि (growth)", "उत्सर्जन", "प्रजनन", "चालन"],
     ["Growth", "Excretion", "Reproduction", "Locomotion"],
     0,
     "जीव अपने शरीर के भीतर से नई कोशिकाएँ जोड़कर बढ़ते हैं — वृद्धि जीवन की मूल पहचान है।",
     "Living beings grow by adding new cells from within — growth is a basic signature of life."),

    ("habitats-adaptations", "medium",
     "छूने पर छुई-मुई (Mimosa) की पत्तियाँ मुड़ जाती हैं — यह किस लक्षण का प्रमाण है?",
     "The leaves of the touch-me-not (Mimosa) fold on touching — proof of which characteristic?",
     ["वृद्धि", "उद्दीपन के प्रति अनुक्रिया (responsiveness)", "उत्सर्जन", "प्रजनन"],
     ["Growth", "Response to stimulus (responsiveness)", "Excretion", "Reproduction"],
     1,
     "जड़ें-तने होते हुए भी स्पर्श की अनुभूति और तुरंत प्रतिक्रिया पौधे के जीवित होने का संकेत देती है।",
     "Despite having no nerves, sensing touch and reacting instantly marks the plant as living."),

    ("habitats-adaptations", "medium",
     "उत्सर्जन (excretion) की परिभाषा क्या है?",
     "How is excretion defined?",
     ["भोजन का पचाया जाना", "शरीर में बने हानिकारक अपशिष्ट को शरीर से बाहर निकालना", "ऑक्सीजन का लेना", "जल का सोखना"],
     ["Digestion of food", "Removal of harmful wastes produced in the body", "Taking in oxygen", "Absorbing water"],
     1,
     "उत्सर्जन जीवन-प्रक्रियाओं में बने निकम्मे-हानिकारक पदार्थों को बाहर करना है — मानव में मूत्र-प्रणाली द्वारा।",
     "Excretion is throwing out the useless-harmful by-products of life processes — via the urinary system in humans."),

    ("habitats-adaptations", "medium",
     "रेगिस्तानी पौधों की जड़ें प्रायः बहुत गहरी जाती हैं — इससे लाभ क्या है?",
     "Desert plant roots usually go very deep — what is the benefit?",
     ["हवा में ऑक्सीजन सीधी लेना", "भूजल-स्तर तक पहुँचकर जल प्राप्त करना", "पत्तियों को ठंडा करना", "कीटों को दूर भगाना"],
     ["To take oxygen straight from air", "To reach the water table and obtain water", "To cool the leaves", "To chase insects away"],
     1,
     "गहरी मुख्य-जड़ें सतही सुखाव से नीचे छिपे भूजल तक पहुँचती हैं — रेगिस्तान में जल-प्राप्ति का यही अनुकूलन है।",
     "Deep taproots pass the dry surface to the hidden water table — the desert adaptation for water supply."),

    ("habitats-adaptations", "hard",
     "पहाड़ों पर रहने वाले लोगों में श्वसन कुशलता धीरे-धीरे बढ़ जाती है — यह बदलाव उनकी संतानों में जन्म से ही क्यों नहीं मिलता?",
     "Mountain dwellers gradually become efficient breathers — why is this change not found in their children from birth?",
     ["क्योंकि यह अर्जित लक्षण है जो जीन में नहीं लिखा जाता", "क्योंकि बच्चे कमज़ोर पैदा होते हैं", "क्योंकि पहाड़ों की हवा विषैली है", "क्योंकि जीन पहाड़ों पर बदल जाते हैं"],
     ["Because it is an acquired trait that is not written into the genes", "Because children are born weak", "Because mountain air is toxic", "Because genes change on mountains"],
     0,
     "वातावरण के कारण जीवन में अर्जित गुण जनन कोशिकाओं तक नहीं पहुँचते — केवल जन्यु लक्षण ही संतान में जाते हैं।",
     "Qualities acquired from the environment during life never reach the germ cells — only inherited traits pass to offspring."),

    ("habitats-adaptations", "medium",
     "जीवित रहने हेतु ऊर्जा किससे मिलती है?",
     "Where do living beings get the energy to stay alive?",
     ["केवल सूर्य-स्नान से", "भोजन के श्वसन द्वारा विघटन से", "जल पीने से", "नींद से"],
     ["Only from sunbathing", "From breaking down food through respiration", "From drinking water", "From sleep"],
     1,
     "भोजन का ऑक्सीजन में विघटन (श्वसन) ही ऊर्जा की देनदार प्रक्रिया है — सभी जीवों में।",
     "Breaking down food with oxygen (respiration) is the energy-paying process — in every organism."),

    ("habitats-adaptations", "hard",
     "किसी नदी-किनारे रहते जीव के लिए निम्न में से कौन-सा अनुकूलन-युग्म सही नहीं है?",
     "For an organism living on a riverbank, which adaptation pair is INCORRECT?",
     ["जल-कीट के पैरों की झिल्ली — तैराकी", "गोल शरीर और मुलायम त्वचा दरारों से भरी — जल बचाना", "मछली की धारारेखीय देह — तेज़ तैराकी", "पक्षी की खोखली अस्थियाँ — हल्की उड़ान"],
     ["Webbed legs of a water insect — swimming", "Round body with soft cracked skin — saving water", "Streamlined fish body — fast swimming", "Hollow bones of a bird — light flight"],
     1,
     "दरारों से भरी त्वचा जल-संरक्षण की उलटी स्थिति है — जल-संरक्षण के लिए मोमी/शल्की आवरण चाहिए; शेष युग्म सही हैं।",
     "Cracked skin is the opposite of water conservation — waxy or scaly coverings do that; the other pairs are correct."),
]
