# -*- coding: utf-8 -*-
"""B03 'Diversity & Classification of Living Organisms' — Part 1 data (55 items).
Order: animal-diversity (30), classification-hierarchy (25).
Tuple: (topic, difficulty, q_hi, q_en, options_hi[4], options_en[4], correct_idx, exp_hi, exp_en)
"""

PART1 = [
    # ---------------- animal-diversity (30) ----------------
    ("animal-diversity", "easy",
     "स्पंज जैसे जीव, जिनके शरीर में अनेक छिद्र (pores) होते हैं, किस संघ के अंतर्गत आते हैं?",
     "Sponge-like animals, whose bodies bear many pores, fall under which phylum?",
     ["पोरिफेरा", "सीलेंटरेटा", "एनीलिडा", "मोलस्का"],
     ["Porifera", "Coelenterata", "Annelida", "Mollusca"],
     0,
     "पोरिफेरा का अर्थ ही 'छिद्र धारक' है; इन छिद्रों से जल शरीर में प्रवाहित होता है और भोजन पकड़ा जाता है।",
     "Porifera literally means 'pore-bearers'; water flows through these pores and food is captured."),

    ("animal-diversity", "easy",
     "हाइड्रा (Hydra) किस संघ का उदाहरण है?",
     "Hydra is an example of which phylum?",
     ["प्लेटीहेल्मिन्थीज", "सीलेंटरेटा", "निमेटोडा", "इकाइनोडर्मेटा"],
     ["Platyhelminthes", "Coelenterata", "Nematoda", "Echinodermata"],
     1,
     "हाइड्रा की देह में खोखला गुहा और वेष्टनी (tentacles) होती हैं — यही सीलेंटरेटा की पहचान है।",
     "Hydra has a hollow gut and tentacles — the defining features of Coelenterata."),

    ("animal-diversity", "medium",
     "फीताकृमि (tapeworm) और यकृत-फ्लूक किस संघ के परजीवी हैं?",
     "Tapeworm and liver fluke are parasites of which phylum?",
     ["प्लेटीहेल्मिन्थीज (फैटवर्म)", "एनीलिडा", "आर्थ्रोपोडा", "मोलस्का"],
     ["Platyhelminthes (flatworms)", "Annelida", "Arthropoda", "Mollusca"],
     0,
     "इनकी देह चपटी, पत्ते के समान होती है; इसीलिए इन्हें फैटवर्म यानी प्लेटीहेल्मिन्थीज कहा जाता है।",
     "Their bodies are flat and leaf-like; hence they are called flatworms, i.e. Platyhelminthes."),

    ("animal-diversity", "easy",
     "गोलकृमि (roundworm) जैसे आस्केरिस के शरीर की बनावट कैसी होती है?",
     "What is the body shape of roundworms like Ascaris?",
     ["चपटी और फीते जैसी", "बेलनाकार (cylindrical) और नली जैसी", "खंडों में विभाजित", "काँटेदार और तारे जैसी"],
     ["Flat and ribbon-like", "Cylindrical and tube-like", "Divided into segments", "Spiny and star-like"],
     1,
     "निमेटोडा के जीव लंबी गोल नली के समान होते हैं, इसीलिए इन्हें गोलकृमि कहा जाता है।",
     "Nematodes are elongated like a round tube, which is why they are called roundworms."),

    ("animal-diversity", "easy",
     "केंचुआ और जोंक किस संघ के उदाहरण हैं?",
     "Earthworm and leech are examples of which phylum?",
     ["एनीलिडा", "आर्थ्रोपोडा", "मोलस्का", "पोरिफेरा"],
     ["Annelida", "Arthropoda", "Mollusca", "Porifera"],
     0,
     "इन दोनों की देह लगभग समान वलयों (खंडों) में बँटी होती है — यह एनीलिडा की मुख्य पहचान है।",
     "Both bodies are divided into similar ring-like segments — the chief hallmark of Annelida."),

    ("animal-diversity", "medium",
     "एनीलिडा संघ के जीवों की सबसे बड़ी पहचान क्या मानी जाती है?",
     "What is considered the biggest identifying feature of annelids?",
     ["देह का बाहरी काइटिन कवच", "देह का समान खंडों (metameres) में विभाजित होना", "नंगी और गीली त्वचा", "कवच के भीतर बंद देह"],
     ["An outer chitinous covering", "Division of the body into similar segments (metameres)", "Naked moist skin", "A shell-enclosed body"],
     1,
     "'एनीलिडा' नाम वलय/खंड से बना है — केंचुए की देह एक-से-एक दिखने वाले खंडों की माला जैसी होती है।",
     "The name Annelida comes from 'little rings' — an earthworm's body is a chain of look-alike segments."),

    ("animal-diversity", "medium",
     "पृथ्वी पर जीवों का सबसे बड़ा संघ (सर्वाधिक प्रजातियाँ वाला) कौन-सा है?",
     "Which is the largest phylum of organisms on Earth (with the most species)?",
     ["मोलस्का", "आर्थ्रोपोडा", "कॉर्डेटा", "इकाइनोडर्मेटा"],
     ["Mollusca", "Arthropoda", "Chordata", "Echinodermata"],
     1,
     "कीट, मकड़ी, केकड़ा, झींगुरा — आर्थ्रोपोडा में प्रजातियों की संख्या सबसे अधिक है; वर्णित प्रजातियों में बहुमत इसी का है।",
     "Insects, spiders, crabs, centipedes — Arthropoda has the most species; the majority of all described species belong to it."),

    ("animal-diversity", "easy",
     "आर्थ्रोपोडा संघ के जीवों की पहचान उनकी किन संरचनाओं से होती है?",
     "By which structures are arthropods identified?",
     ["जुड़े हुए टाँगें (jointed appendages)", "वेष्टनी", "छिद्र", "पंख"],
     ["Jointed appendages (legs)", "Tentacles", "Pores", "Wings"],
     0,
     "'आर्थ्रोपोडा' का अर्थ है 'जुड़े पाँव' — टाँगों के जोड़ इस संघ की सबसे पक्की पहचान है।",
     "'Arthropoda' means 'jointed feet' — joints in the legs are the firmest identification of this phylum."),

    ("animal-diversity", "easy",
     "कीटों (insects) के पैरों के कितने जोड़े होते हैं?",
     "How many pairs of legs do insects have?",
     ["दो", "तीन", "चार", "पाँच"],
     ["Two", "Three", "Four", "Five"],
     1,
     "कीटों के तीन जोड़े यानी छह टाँगें होती हैं; मकड़ी के चार जोड़े और झींगुरे के अनेक जोड़े होते हैं।",
     "Insects have three pairs, i.e. six legs; spiders have four pairs and centipedes many pairs."),

    ("animal-diversity", "medium",
     "झींगा (prawn) और केकड़ा आर्थ्रोपोडा के किस वर्ग के सदस्य हैं?",
     "Prawn and crab belong to which class of Arthropoda?",
     ["इन्सेक्टा", "अरैक्निडा", "क्रस्टेशिया", "मायरियापोडा"],
     ["Insecta", "Arachnida", "Crustacea", "Myriapoda"],
     2,
     "जलीय, कवचयुक्त आर्थ्रोपोड जिनके शरीर के खंडों पर अनेक टाँगें होती हैं, क्रस्टेशिया वर्ग में रखे जाते हैं।",
     "Aquatic, armoured arthropods with several legs on their body segments are placed in the class Crustacea."),

    ("animal-diversity", "medium",
     "बिच्छू और मकड़ी के पैरों के जोड़े कितने होते हैं?",
     "How many pairs of legs do scorpion and spider have?",
     ["तीन", "चार", "पाँच", "अनेक"],
     ["Three", "Four", "Five", "Many"],
     1,
     "अरैक्निडा वर्ग के सदस्यों (बिच्छू, मकड़ी) के चार जोड़े टाँगें होती हैं — कीटों के तीन से भिन्न।",
     "Members of the class Arachnida (scorpion, spider) have four pairs of legs — unlike the three pairs of insects."),

    ("animal-diversity", "easy",
     "घोंघा और ऑक्टोपस किस संघ के जीव हैं?",
     "Snail and octopus belong to which phylum?",
     ["मोलस्का", "इकाइनोडर्मेटा", "एनीलिडा", "निमेटोडा"],
     ["Mollusca", "Echinodermata", "Annelida", "Nematoda"],
     0,
     "मोलस्का का अर्थ है 'नरम देह' — घोंघे की नरम देह कवच में और ऑक्टोपस की देह बाह्य कवच के बिना होती है।",
     "Mollusca means 'soft body' — the snail's soft body sits in a shell while the octopus lacks an external shell."),

    ("animal-diversity", "medium",
     "मोलस्का के अधिकांश जीवों की देह किससे ढकी रहती है?",
     "The body of most molluscs remains covered by what?",
     ["काइटिन के कवच से", "चूने का कवच (shell) से", "रोएँदार त्वचा से", "शल्कों से"],
     ["A chitinous coat", "A calcareous shell", "Hairy skin", "Scales"],
     1,
     "घोंघे-क्लैम जैसे मोलस्क की नरम देह के ऊपर प्रायः चूने का बना कठोर कवच रहता है।",
     "In molluscs like snails and clams, a hard shell of lime usually covers the soft body."),

    ("animal-diversity", "easy",
     "स्टारफिश (तारा मछली) किस संघ का जीव है?",
     "Starfish belongs to which phylum?",
     ["इकाइनोडर्मेटा", "पिसेस", "मोलस्का", "सीलेंटरेटा"],
     ["Echinodermata", "Pisces", "Mollusca", "Coelenterata"],
     0,
     "इकाइनोडर्मेटा का अर्थ है 'काँटेदार त्वचा'; स्टारफिश की त्वचा पर कैल्शियम के काँटे होते हैं और देह तारे जैसी होती है।",
     "Echinodermata means 'spiny skin'; a starfish has calcium spines on its skin and a star-shaped body."),

    ("animal-diversity", "medium",
     "इकाइनोडर्मेटा संघ के जीव केवल कहाँ पाए जाते हैं?",
     "Where are echinoderms exclusively found?",
     ["मीठे जल में", "समुद्र में", "रेगिस्तान में", "घने वनों में"],
     ["In fresh water", "In the sea", "In deserts", "In dense forests"],
     1,
     "स्टारफिश, समुद्री अर्चिन जैसे इकाइनोडर्म सब समुद्री जीव हैं; इनके जीवन का संपूर्ण चक्र खारे जल में ही चलता है।",
     "Starfish, sea urchins and other echinoderms are all marine; their entire life cycle runs in salt water."),

    ("animal-diversity", "hard",
     "कॉर्डेटा संघ के सभी जीवों में जीवन के किसी न किसी अवस्था में कौन-सी संरचना अवश्य पाई जाती है?",
     "Which structure is found at some stage of life in all chordates?",
     ["रीढ़ की हड्डी", "नोटोकॉर्ड (दृढ़ रज्जु)", "कवच", "वेष्टनी"],
     ["Vertebral column", "Notochord", "Shell", "Tentacles"],
     1,
     "कॉर्डेटा की पहचान नोटोकॉर्ड है — तंत्रिका रज्जु के नीचे पाई जाने वाली दृढ़ छड़; कशेरुकियों में यही रीढ़ की हड्डी बन जाती है।",
     "Chordates are defined by the notochord — a stiff rod below the nerve cord; in vertebrates it develops into the vertebral column."),

    ("animal-diversity", "easy",
     "मछलियाँ जल में घुली किस गैस का श्वसन करती हैं?",
     "Fish respire using which gas dissolved in water?",
     ["जलवाष्प", "कार्बन डाइऑक्साइड", "घुली ऑक्सीजन", "नाइट्रोजन"],
     ["Water vapour", "Carbon dioxide", "Dissolved oxygen", "Nitrogen"],
     2,
     "मछलियों के गलफड़े (gills) जल में घुली ऑक्सीजन लेते और कार्बन डाइऑक्साइड छोड़ते हैं।",
     "The gills of fish take in oxygen dissolved in water and release carbon dioxide."),

    ("animal-diversity", "medium",
     "पिसेस (मछलियों) के हृदय के कक्ष कितने होते हैं?",
     "How many chambers does the heart of Pisces (fishes) have?",
     ["दो", "तीन", "तीन और एक आधा", "चार"],
     ["Two", "Three", "Three and a half", "Four"],
     0,
     "मछलियों का हृदय दो कक्षीय होता है — एक अलिंद और एक निलय; रुधिर शीतल रहता है।",
     "A fish's heart is two-chambered — one auricle and one ventricle; the blood stays cold."),

    ("animal-diversity", "medium",
     "उभयचरों की त्वचा कैसी होती है?",
     "What kind of skin do amphibians have?",
     ["सूखी और शल्की", "नम और बिना शल्कों की", "रोएँदार", "मोटी और सींगदार प्लेटों वाली"],
     ["Dry and scaly", "Moist and without scales", "Hairy", "Thick with horny plates"],
     1,
     "मेंढक-टोड की त्वचा नम और चिकनी होती है; शल्क नहीं होते — यही सरीसृपों से अंतर है जिनकी त्वचा शुष्क-शल्की होती है।",
     "Frog and toad skin is moist and smooth, without scales — unlike reptiles whose skin is dry and scaly."),

    ("animal-diversity", "medium",
     "साँप, छिपकली और कछुआ किस वर्ग के जीव हैं?",
     "Snake, lizard and turtle belong to which class?",
     ["एम्फीबिया", "रेप्टिलिया", "एवीज़", "पिसेस"],
     ["Amphibia", "Reptilia", "Aves", "Pisces"],
     1,
     "शुष्क शल्की त्वचा और स्थल पर चर्मसार अंडे देने वाले ये जीव सरीसृप (रेप्टिलिया) वर्ग के हैं।",
     "With dry scaly skin and leathery eggs laid on land, these are reptiles (class Reptilia)."),

    ("animal-diversity", "hard",
     "निम्न में से कौन-सा सरीसृप अपवाद स्वरूप चार-कक्षीय हृदय रखता है?",
     "Which reptile, as an exception, has a four-chambered heart?",
     ["साँप", "छिपकली", "मगरमच्छ", "कछुआ"],
     ["Snake", "Lizard", "Crocodile", "Turtle"],
     2,
     "सरीसृपों का हृदय प्रायः तीन-कक्षीय होता है, पर मगरमच्छ का हृदय चार कक्षों वाला है — यही इस वर्ग का प्रसिद्ध अपवाद है।",
     "Reptile hearts are generally three-chambered, but the crocodile's heart has four chambers — the famous exception of this class."),

    ("animal-diversity", "medium",
     "जलपक्षियों जैसे बतख के पैरों में झिल्ली (webbed feet) किस कारण उपयोगी है?",
     "Why are webbed feet useful in water birds like ducks?",
     ["पेड़ों पर पकड़ के लिए", "जल में तैरते समय खेने (paddling) में सहायता के लिए", "शिकार पकड़ने के लिए", "उड़ान के लिए"],
     ["For gripping branches", "For paddling while swimming in water", "For catching prey", "For flight"],
     1,
     "उंगलियों के बीच की झिल्ली चपटी तथा चौड़ी सतह बनाती है जिससे बतख पानी को धकेलकर आसानी से तैरती है।",
     "The membrane between the toes forms a broad paddle surface, letting the duck push water and swim easily."),

    ("animal-diversity", "medium",
     "पक्षियों के हृदय के कक्ष कितने होते हैं?",
     "How many chambers does a bird's heart have?",
     ["दो", "तीन", "चार", "एक"],
     ["Two", "Three", "Four", "One"],
     2,
     "पक्षी और स्तनधारी दोनों का हृदय चार-कक्षीय होता है — शुद्ध और अशुद्ध रुधिर पूर्णतः अलग रहता है।",
     "Both birds and mammals have four-chambered hearts — oxygenated and deoxygenated blood stay fully separate."),

    ("animal-diversity", "easy",
     "स्तनधारियों (mammals) की सबसे अनूठी पहचान क्या है?",
     "What is the most unique identification of mammals?",
     ["पंख", "स्तन ग्रंथियाँ (mammary glands)", "शल्क", "गलफड़े"],
     ["Wings", "Mammary glands", "Scales", "Gills"],
     1,
     "स्तन ग्रंथियाँ जो शावकों को दूध पिलाती हैं, केवल स्तनधारियों में पाई जाती हैं — इसी से इनका नाम पड़ा।",
     "Mammary glands, which suckle the young with milk, occur only in mammals — the group is named after them."),

    ("animal-diversity", "medium",
     "शुद्ध और अशुद्ध रुधिर को पूर्णतः अलग रखने वाला हृदय किन दो वर्गों के जीवों में होता है?",
     "A heart keeping oxygenated and deoxygenated blood fully separate occurs in the animals of which two classes?",
     ["पिसेस और एम्फीबिया", "रेप्टिलिया और एम्फीबिया", "एवीज़ और मैमेलिया", "पिसेस और रेप्टिलिया"],
     ["Pisces and Amphibia", "Reptilia and Amphibia", "Aves and Mammalia", "Pisces and Reptilia"],
     2,
     "चार-कक्षीय हृदय केवल पक्षियों और स्तनधारियों में होता है — दोनों गर्म-रुधिर वर्ग हैं।",
     "Only birds and mammals possess a four-chambered heart — both are warm-blooded classes."),

    ("animal-diversity", "medium",
     "गर्म-रुधिर (warm-blooded) जीवों की परिभाषा क्या है?",
     "How are warm-blooded animals defined?",
     ["जिनका शरीर-ताप बाहर के ताप के साथ बदलता रहता है", "जिनका शरीर-ताप परिवेश से स्वतंत्र रहकर स्थिर रहता है", "जो केवल गर्मियों में सक्रिय रहते हैं", "जिनका रुधिर गर्म होता है पर ताप बदलता है"],
     ["Whose body temperature keeps changing with the surroundings", "Whose body temperature stays constant regardless of the surroundings", "Who are active only in summers", "Whose blood is warm but temperature fluctuates"],
     1,
     "पक्षी और स्तनधारी अपने शरीर-ताप को स्थिर रखते हैं — यही गर्म-रुधिरता है; मछली, उभयचर, सरीसृप शीतल-रुधिर हैं।",
     "Birds and mammals hold their body temperature steady — that is warm-bloodedness; fish, amphibians and reptiles are cold-blooded."),

    ("animal-diversity", "hard",
     "प्लैटिपस अंडे देता है फिर भी उसे स्तनधारी क्यों माना जाता है?",
     "The platypus lays eggs, so why is it still considered a mammal?",
     ["क्योंकि उसके पंख होते हैं", "क्योंकि उसमें बाल और स्तन ग्रंथियाँ होती हैं", "क्योंकि वह चार-कक्षीय हृदय वाला नहीं है", "क्योंकि वह जल में रहता है"],
     ["Because it has wings", "Because it has hair and mammary glands", "Because it lacks a four-chambered heart", "Because it lives in water"],
     1,
     "वर्गीकरण मूल संरचनात्मक लक्षणों पर होता है — बाल और दुग्ध-ग्रंथियाँ पाए जाने से प्लैटिपस अंडे देने के बावजूद स्तनधारी है; यह अपवाद है।",
     "Classification rests on core structural traits — having hair and milk glands makes the platypus a mammal despite egg-laying; it is an exception."),

    ("animal-diversity", "hard",
     "किसी जीव की देह पर संधित उपांग, काइटिन का बाह्य कवच और खुला रुधिर-परिसंचरण पाया जाता है — यह जीव किस संघ का होगा?",
     "An animal shows jointed appendages, a chitinous outer covering and open circulation — which phylum does it belong to?",
     ["मोलस्का", "आर्थ्रोपोडा", "एनीलिडा", "इकाइनोडर्मेटा"],
     ["Mollusca", "Arthropoda", "Annelida", "Echinodermata"],
     1,
     "ये तीनों लक्षण — संधित पाँव, काइटिन कवच, खुला परिसंचरण — आर्थ्रोपोडा की निशानी हैं।",
     "All three traits — jointed legs, chitinous coat, open circulation — are signatures of Arthropoda."),

    ("animal-diversity", "hard",
     "निम्न जीव-संघ युग्मों में से गलत सुमेलित कौन-सा है?",
     "Among these animal-phylum pairs, which one is wrongly matched?",
     ["नीरिस — एनीलिडा", "स्पंजिला — पोरिफेरा", "प्लैनेरिया — प्लेटीहेल्मिन्थीज", "लीच — आर्थ्रोपोडा"],
     ["Nereis — Annelida", "Spongilla — Porifera", "Planaria — Platyhelminthes", "Leech — Arthropoda"],
     3,
     "जोंक आर्थ्रोपोडा नहीं, बल्कि एनीलिडा की सदस्य है (खंडित देह); शेष तीनों युग्म सही हैं।",
     "The leech is not an arthropod but a member of Annelida (segmented body); the other three pairs are correct."),

    ("animal-diversity", "medium",
     "व्हेल और डॉल्फिन समुद्र में रहते हुए भी मछलियाँ क्यों नहीं मानी जातीं?",
     "Why are the whale and the dolphin not considered fish despite living in the sea?",
     ["क्योंकि उनकी देह बड़ी होती है", "क्योंकि वे स्तनधारी हैं — फेफड़ों से श्वास लेती हैं, बच्चों को दूध पिलाती हैं", "क्योंकि वे अंडे देती हैं", "क्योंकि उनमें पूँछ नहीं होती"],
     ["Because their bodies are huge", "Because they are mammals — they breathe with lungs and suckle their young", "Because they lay eggs", "Because they lack a tail"],
     1,
     "आवास के बजाय संरचना और कार्य तय करते हैं — फेफड़े, बाल, स्तन ग्रंथियाँ और चार-कक्षीय हृदय व्हेल-डॉल्फिन को स्तनधारी बनाते हैं।",
     "Structure and function decide, not habitat — lungs, hair, mammary glands and a four-chambered heart make whales and dolphins mammals."),

    # ---------------- classification-hierarchy (25) ----------------
    ("classification-hierarchy", "easy",
     "द्विपद नामकरण (binomial nomenclature) की खोज का श्रेय किसे दिया जाता है?",
     "Who is credited with developing binomial nomenclature?",
     ["आर.एच. व्हिटेकर", "कैरोलस लिनियस", "ग्रेगर मेंडल", "चार्ल्स डार्विन"],
     ["R.H. Whittaker", "Carolus Linnaeus", "Gregor Mendel", "Charles Darwin"],
     1,
     "लिनियस ने प्रत्येक जीव को दो शब्दों वाला वैज्ञानिक नाम देने की पद्धति दी, इसीलिए उन्हें वर्गीकरण का जनक भी कहते हैं।",
     "Linnaeus gave the system of two-word scientific names for every organism, and is also called the father of classification."),

    ("classification-hierarchy", "easy",
     "जीव वर्गीकरण की श्रेणियों का सही क्रम (बड़े से छोटे की ओर) कौन-सा है?",
     "Which is the correct sequence of taxonomic categories (from largest to smallest)?",
     ["जगत → संघ → वर्ग → गण → कुल → वंश → जाति", "जगत → वर्ग → संघ → गण → कुल → जाति → वंश", "संघ → जगत → गण → वर्ग → वंश → कुल → जाति", "जगत → संघ → गण → वर्ग → कुल → वंश → जाति"],
     ["Kingdom → Phylum → Class → Order → Family → Genus → Species", "Kingdom → Class → Phylum → Order → Family → Species → Genus", "Phylum → Kingdom → Order → Class → Genus → Family → Species", "Kingdom → Phylum → Order → Class → Family → Genus → Species"],
     0,
     "जगत सबसे बड़ी और जाति सबसे छोटी श्रेणी है; क्रम याद रखें — जगत, संघ, वर्ग, गण, कुल, वंश, जाति।",
     "Kingdom is the largest and species the smallest category; remember the order — Kingdom, Phylum, Class, Order, Family, Genus, Species."),

    ("classification-hierarchy", "medium",
     "वर्गीकरण की सबसे छोटी और मूल श्रेणी कौन-सी मानी जाती है?",
     "Which is considered the smallest and basic unit of classification?",
     ["वंश (genus)", "कुल (family)", "जाति (species)", "गण (order)"],
     ["Genus", "Family", "Species", "Order"],
     2,
     "जाति मूल श्रेणी है — इसके सदस्य समान होते हैं और आपस में प्रजनन कर सकते हैं।",
     "Species is the basic unit — its members are alike and can interbreed."),

    ("classification-hierarchy", "medium",
     "जाति (species) को परिभाषित करने वाली मुख्य क्षमता क्या है?",
     "What key ability defines a species?",
     ["एक ही क्षेत्र में रहना", "आपस में स्वतंत्र रूप से प्रजनन कर की उपजाऊ संतति देना", "एक ही आकार का होना", "एक ही रंग का होना"],
     ["Living in the same area", "Freely interbreeding among themselves to produce fertile offspring", "Having the same size", "Having the same colour"],
     1,
     "एक जाति के सदस्य आपस में प्रजनन कर उपजाऊ संतति दे सकते हैं — यही जाति की कसौटी है।",
     "Members of one species can interbreed to produce fertile offspring — that is the test of a species."),

    ("classification-hierarchy", "easy",
     "वैज्ञानिक नाम के दो शब्द क्रमशः क्या दर्शाते हैं?",
     "The two words of a scientific name respectively denote what?",
     ["कुल और गण", "वंश और जाति", "वर्ग और संघ", "जगत और वंश"],
     ["Family and order", "Genus and species", "Class and phylum", "Kingdom and genus"],
     1,
     "पहला शब्द वंश (genus) और दूसरा जाति (species) होता है — जैसे Mangifera में Mangifera वंश है।",
     "The first word is the genus and the second the species — as in Mangifera, where Mangifera is the genus."),

    ("classification-hierarchy", "medium",
     "वैज्ञानिक नाम लिखते समय कौन-सा नियम पालनीय है?",
     "Which rule must be followed while writing a scientific name?",
     ["दोनों शब्द बड़े अक्षरों में", "पहला शब्द बड़े अक्षर में, दूसरा छोटे अक्षर में और नाम तिरछा (italic) लिखा जाए", "दोनों शब्द छोटे अक्षरों में", "नाम हमेशा अलग-अलग रेखा में लिखे जाएँ"],
     ["Both words in capitals", "First word capital, second small, and the name in italics", "Both words in small letters", "The words must always be on separate lines"],
     1,
     "उदाहरण — Homo sapiens: वंश Homo बड़े अक्षर से, जाति sapiens छोटे अक्षर से, और पूरा नाम इटैलिक में लिखा जाता है।",
     "Example — Homo sapiens: genus Homo with a capital, species sapiens in lower case, the whole name in italics."),

    ("classification-hierarchy", "easy",
     "Mangifera indica किस फल-वृक्ष का वैज्ञानिक नाम है?",
     "Mangifera indica is the scientific name of which fruit tree?",
     ["आम", "केला", "पपीता", "नारियल"],
     ["Mango", "Banana", "Papaya", "Coconut"],
     0,
     "Mangifera indica आम का द्विपद नाम है — Mangifera वंश और indica जाति सूचक शब्द है।",
     "Mangifera indica is the binomial name of the mango — Mangifera the genus and indica the species epithet."),

    ("classification-hierarchy", "easy",
     "Panthera tigris किस जीव का वैज्ञानिक नाम है?",
     "Panthera tigris is the scientific name of which animal?",
     ["शेर", "बाघ", "चीता", "तेंदुआ"],
     ["Lion", "Tiger", "Cheetah", "Leopard"],
     1,
     "बाघ का नाम Panthera tigris है; tigris जाति-वाचक शब्द है और Panthera वंश शेर-बाघ-तेंदुए साझा रखते हैं।",
     "The tiger is Panthera tigris; tigris is the species epithet, while the genus Panthera is shared with lion and leopard."),

    ("classification-hierarchy", "hard",
     "शेर (Panthera leo) और बाघ (Panthera tigris) के नामों से क्या पता चलता है?",
     "What do the names Panthera leo (lion) and Panthera tigris (tiger) tell us?",
     ["दोनों एक ही जाति के हैं", "दोनों एक ही वंश के भिन्न जातियाँ हैं", "दोनों एक ही कुल के भिन्न वंश हैं", "दोनों के वंश भिन्न हैं"],
     ["Both belong to the same species", "Both are different species of the same genus", "Both are different genera of the same family", "Their genera are different"],
     1,
     "साझा पहला शब्द Panthera समान वंश दर्शाता है; दूसरा शब्द leo बनाम tigris उन्हें अलग जातियाँ बनाता है।",
     "The shared first word Panthera marks the same genus; the second words leo versus tigris make them separate species."),

    ("classification-hierarchy", "medium",
     "श्रेणी-सीढ़ी में कुल (family) का स्थान कहाँ है?",
     "Where does the family category sit in the taxonomic ladder?",
     ["गण के ऊपर, वर्ग के नीचे", "वंश के नीचे, जाति के ऊपर", "गण के नीचे, वंश के ऊपर", "संघ के ऊपर, जगत के नीचे"],
     ["Above order, below class", "Below genus, above species", "Below order, above genus", "Above phylum, below kingdom"],
     2,
     "क्रम है — ...वर्ग → गण → कुल → वंश → जाति; अतः कुल गण के नीचे और वंश के ऊपर आता है।",
     "The rung order is ...Class → Order → Family → Genus → Species; so family lies below order and above genus."),

    ("classification-hierarchy", "hard",
     "श्रेणियों की सीढ़ी में नीचे की ओर जाने पर क्या होता है?",
     "What happens as we move down the taxonomic ladder?",
     ["समानताएँ घटती हैं और सदस्य संख्या बढ़ती है", "समानताएँ बढ़ती हैं और सम्मिलित जीवों की संख्या घटती है", "समानताएँ और संख्या दोनों बढ़ती हैं", "कोई परिवर्तन नहीं होता"],
     ["Similarities decrease while membership increases", "Similarities increase while the number of organisms included decreases", "Both similarities and numbers increase", "Nothing changes"],
     1,
     "जगत में असंख्य जीव हैं पर समानता कम; जाति में बहुत कम सदस्य पर समानता सर्वाधिक — सीढ़ी जाते ही समानता घनी होती जाती है।",
     "A kingdom holds countless but dissimilar members; a species holds very few but nearly identical ones — similarity tightens as you descend."),

    ("classification-hierarchy", "medium",
     "वर्गीकरण में वंश (genus) की स्थिति क्या है?",
     "What is the position of genus in classification?",
     ["कुल और गण के बीच", "जाति और कुल के बीच", "वर्ग और संघ के बीच", "जगत और संघ के बीच"],
     ["Between family and order", "Between species and family", "Between class and phylum", "Between kingdom and phylum"],
     1,
     "वंश, जाति से ठीक ऊपर और कुल से ठीक नीचे की श्रेणी है।",
     "Genus sits just above species and just below family."),

    ("classification-hierarchy", "easy",
     "जीवों का वर्गीकरण आवश्यक क्यों है?",
     "Why is classification of organisms necessary?",
     ["जीवों की संख्या बहुत विशाल है — अध्ययन व्यवस्थित और सरल बनाने के लिए", "जीवों को नाम देना अनावश्यक है", "सभी जीव एक-समान हो गए हैं", "केवल सुंदर नाम देने के लिए"],
     ["The number of organisms is vast — to make their study systematic and easy", "Naming organisms is unnecessary", "All organisms have become alike", "Just to give fancy names"],
     0,
     "लाखों प्रजातियों के बीच वर्गीकरण ही समानता-भिन्नता पहचानने, नामकरण और अध्ययन को सरल बनाता है।",
     "Amid millions of species, classification alone makes spotting similarities, naming and study manageable."),

    ("classification-hierarchy", "medium",
     "जीवों को संघों में बाँटने का आधार कौन-से लक्षण नहीं हैं?",
     "Which of these is NOT a basis for dividing animals into phyla?",
     ["नोटोकॉर्ड का होना या न होना", "देह-गुहा (coelom) का प्रकार", "देह की सममिति", "जीव का आवास"],
     ["Presence or absence of notochord", "Type of body cavity (coelom)", "Body symmetry", "Habitat of the organism"],
     3,
     "आवास वर्गीकरण का आधार नहीं है — एक ही आवास में भिन्न संघ के अनेक जीव रहते हैं; संरचनात्मक लक्षण ही आधार हैं।",
     "Habitat is not a classificatory basis — many phyla share one habitat; structural characters are the basis."),

    ("classification-hierarchy", "medium",
     "द्विपार्श्विक (bilateral) सममिति से क्या तात्पर्य है?",
     "What is meant by bilateral symmetry?",
     ["किसी भी तल से दो समान अर्ध बनते हों", "केवल एक विशेष अक्ष-तल से देह दो समान दर्पण-अर्धों में बँटती हो", "देह तीन बराबर भागों में बँटती हो", "देह के टुकड़े पुनर्जनित होते हों"],
     ["Two equal halves form by any plane", "The body splits into two mirror halves by one particular plane only", "The body divides into three equal parts", "Body parts regenerate"],
     1,
     "मनुष्य-मछली की भाँति बायाँ-दायाँ आधा समान होता है — केवल मध्य-तल से; यह द्विपार्श्विक सममिति है।",
     "As in humans and fish, left and right halves match — only through the midline plane; this is bilateral symmetry."),

    ("classification-hierarchy", "medium",
     "त्रिज्य (radial) सममिति किस जीव में देखी जाती है?",
     "Radial symmetry is seen in which of the following?",
     ["मेंढक", "हाइड्रा", "केंचुआ", "मनुष्य"],
     ["Frog", "Hydra", "Earthworm", "Human"],
     1,
     "हाइड्रा की देह केंद्र से गुजरने वाले किसी भी तल से समान अर्धों में बँटती है — यह त्रिज्य सममिति है।",
     "Hydra's body splits into equal halves by any plane passing through the axis — that is radial symmetry."),

    ("classification-hierarchy", "hard",
     "असममित (asymmetrical) देह वाले जीवों में से एक कौन-सा है?",
     "Which of the following animals has an asymmetrical body?",
     ["स्पंज", "स्टारफिश", "हाइड्रा", "केंचुआ"],
     ["Sponge", "Starfish", "Hydra", "Earthworm"],
     0,
     "अधिकांश स्पंजों की देह किसी तल से समान अर्धों में नहीं बँटती — यही असममिति है; शेष तीनों में किसी न किसी सममिति है।",
     "Most sponges cannot be divided into equal halves by any plane — true asymmetry; the other three show some symmetry."),

    ("classification-hierarchy", "medium",
     "सही देह-गुहा (true coelom) से क्या तात्पर्य है?",
     "What is meant by a true coelom?",
     ["कोशिकाओं के बीच का जल", "ऊतकों से निर्मित पूर्ण देह-गुहा जो भीतर के अंगों को स्थान देती है", "देह के बाहर की खाली जगह", "रुधिर वाहिकाओं का जाल"],
     ["Water between cells", "A full body cavity lined by tissue that houses the internal organs", "Empty space outside the body", "A network of blood vessels"],
     1,
     "सही सीलोम देह-भित्ति की परतों से ढका हुआ गुहा है जिसमें पाचन-अंग जैसे अंग सुरक्षित रहते हैं।",
     "A true coelom is a cavity fully lined by body-wall tissue, housing and cushioning organs like the gut."),

    ("classification-hierarchy", "hard",
     "'कूट-सीलोम' (pseudocoelom) वाले जीव किस संघ के होते हैं?",
     "Animals with a 'pseudocoelom' belong to which phylum?",
     ["प्लेटीहेल्मिन्थीज", "निमेटोडा", "एनीलिडा", "मोलस्का"],
     ["Platyhelminthes", "Nematoda", "Annelida", "Mollusca"],
     1,
     "गोलकृमियों (निमेटोडा) में देह-गुहा पूर्ण ऊतक-आवरण से ढकी नहीं होती — इसलिए उसे कूट-सीलोम कहते हैं।",
     "In roundworms (Nematoda) the body cavity is not fully lined by tissue — hence it is called a pseudocoelom."),

    ("classification-hierarchy", "medium",
     "द्विस्तरीय (diploblastic) जीवों की पहचान क्या है?",
     "How are diploblastic animals identified?",
     ["देह भित्ति में तीन कोशिका-स्तर होते हैं", "देह भित्ति में दो कोशिका-स्तर होते हैं — बाह्य और भीतरी", "देह में कोई स्तर नहीं होता", "देह भित्ति चार स्तरों की होती है"],
     ["Their body wall has three cell layers", "Their body wall has two cell layers — outer and inner", "Their body has no layers", "Their body wall has four layers"],
     1,
     "सीलेंटरेटा जैसे जीवों में केवल दो जनन स्तर होते हैं; तीन स्तर वाले जीव त्रिस्तरीय कहलाते हैं (प्लेटीहेल्मिन्थीज से आगे के अधिकांश जीव)।",
     "Animals like coelenterates have just two germ layers; three-layered animals are triploblastic (most animals from flatworms onwards)."),

    ("classification-hierarchy", "easy",
     "वर्गीकरण में 'वर्ग' (class) और 'गण' (order) में से कौन अधिक व्यापक श्रेणी है?",
     "Between class and order, which is the broader category?",
     ["गण", "वर्ग", "दोनों बराबर", "निर्भर करता है जीव पर"],
     ["Order", "Class", "Both are equal", "Depends on the organism"],
     1,
     "वर्ग, गण से ऊपर की श्रेणी है और उसमें अनेक गण समाहित होते हैं — जैसे स्तनधारी वर्ग में अनेक गण।",
     "Class sits above order and contains many orders — as the mammal class holds several orders."),

    ("classification-hierarchy", "easy",
     "टैक्सोनोमी (taxonomy) का कार्य क्या है?",
     "What is the work of taxonomy?",
     ["केवल जीवों का चित्र बनाना", "जीवों की पहचान, वर्गीकरण और नामकरण करना", "जीवों का शिकार करना", "जीवों को पालना"],
     ["Only drawing pictures of organisms", "Identification, classification and naming of organisms", "Hunting organisms", "Rearing organisms"],
     1,
     "टैक्सोनोमी के तीन कार्य हैं — पहचान (identification), वर्गीकरण और नामकरण।",
     "Taxonomy does three jobs — identification, classification and nomenclature of organisms."),

    ("classification-hierarchy", "medium",
     "स्थानीय नामों के बजाय वैज्ञानिक द्विपद नाम क्यों अपनाए गए?",
     "Why were scientific binomial names adopted instead of local names?",
     ["क्योंकि स्थानीय नाम सुनने में अच्छे नहीं होते", "क्योंकि प्रत्येक क्षेत्र के स्थानीय नाम भिन्न होते हैं — एक सार्वभौमिक नाम भ्रम दूर करता है", "क्योंकि कानून ऐसा माँगता है", "क्योंकि स्थानीय नाम लिखे नहीं जा सकते"],
     ["Because local names sound bad", "Because local names differ from region to region — one universal name removes confusion", "Because the law demands it", "Because local names cannot be written"],
     1,
     "एक ही जीव के अनेक स्थानीय नाम और एक नाम के अनेक अर्थ — वैज्ञानिक नाम इस अराजकता को समाप्त कर विश्वभर में एकरूपता लाता है।",
     "One creature, many local names; one name, many creatures — the scientific name ends this chaos with worldwide uniformity."),

    ("classification-hierarchy", "medium",
     "द्विपद नामकरण पद्धति में प्रत्येक जीव का वैज्ञानिक नाम कितने शब्दों का होता है?",
     "In the binomial system, how many words make up an organism's scientific name?",
     ["एक", "दो", "तीन", "चार"],
     ["One", "Two", "Three", "Four"],
     1,
     "'द्विपद' का अर्थ ही दो शब्द है — वंश और जाति; यही नाम संपूर्ण विश्व में उस जीव की पहचान है।",
     "'Binomial' itself means two words — genus and species; this name identifies the organism worldwide."),

    ("classification-hierarchy", "medium",
     "लिनियस ने पहले कितने जगतों (kingdoms) वाला वर्गीकरण प्रस्तावित किया था?",
     "How many kingdoms did Linnaeus originally propose in his classification?",
     ["तीन", "दो", "पाँच", "छह"],
     ["Three", "Two", "Five", "Six"],
     1,
     "लिनियस का वर्गीकरण दो जगतों — पादप (Plantae) और जंतु (Animalia) — पर आधारित था; बाद में यह अपर्याप्त सिद्ध हुआ।",
     "Linnaeus's scheme rested on two kingdoms — Plantae and Animalia; it later proved inadequate."),
]
