# -*- coding: utf-8 -*-
"""B04 'Plant Life & Plant Functions' — Part 2 data (65 items).
Order: plant-parts-functions (25), crop-production (40, incl. animal husbandry).
Tuple: (topic, difficulty, q_hi, q_en, options_hi[4], options_en[4], correct_idx, exp_hi, exp_en)
DENY: B08 root-hair/root-pressure/transpiration/xylem-phloem-transport; B02 veins-vascular/guard-cells;
B09 flower-parts/pollination/germination-conditions; B08 potato-tuber phloem-sink framing.
"""

PART2 = [
    # ---------------- plant-parts-functions (25: E9/M13/H3) ----------------
    ("plant-parts-functions", "easy",
     "जड़ का मुख्य कार्य क्या है?",
     "What is the main function of the root?",
     ["भोजन बनाना", "पौधे को मिट्टी में स्थिर रखना (स्थिरीकरण) और जल-खनिज लेना", "फूल खिलाना", "बीज बनाना"],
     ["Making food", "Holding the plant firm in the soil (anchorage) and taking in water-minerals", "Blooming flowers", "Making seeds"],
     1,
     "जड़ पौधे की नींव है — मिट्टी में पकड़ और भूमिगत आपूर्ति, दोनों उत्तरदायित्व उसी के।",
     "The root is the plant's foundation — grip in soil and underground supply, both its charge."),

    ("plant-parts-functions", "easy",
     "तने का प्रमुख कार्य क्या है?",
     "What is the chief function of the stem?",
     ["जल सोखना", "पत्तियों-फूलों-फलों को धारण कर ऊपर उठाए रखना और सहारा देना", "भोजन पचाना", "मिट्टी बनाना"],
     ["Absorbing water", "Bearing leaves-flowers-fruits, holding them up and giving support", "Digesting food", "Making soil"],
     1,
     "तना पौधे का खंभा और शाखायुक्त ढाँचा है — सभी ऊपरी अंग इसी पर टिके हैं।",
     "The stem is the plant's pillar and branching frame — all upper organs rest on it."),

    ("plant-parts-functions", "easy",
     "पौधे के किस भाग को 'भोजन-कारखाना' कहा जाता है?",
     "Which part of the plant is called the 'food factory'?",
     ["जड़", "पत्ती", "फूल", "फल"],
     ["Root", "Leaf", "Flower", "Fruit"],
     1,
     "हरी पत्ती में क्लोरोफिल होता है और प्रकाश-संश्लेषण सबसे अधिक यहीं होता है।",
     "The green leaf holds chlorophyll and hosts the most photosynthesis."),

    ("plant-parts-functions", "easy",
     "पत्ती को तने से जोड़ने वाले डंठल को क्या कहते हैं?",
     "What is the stalk that joins the leaf to the stem called?",
     ["पर्णफलक (lamina)", "पर्णवृंत (petiole)", "मध्य शिरा", "अपस्थानिक कली"],
     ["Lamina", "Petiole", "Midrib", "Axillary bud"],
     1,
     "पर्णवृंत पत्ती का हैंडल है — इसी से पत्ती तने पर लटककर हवा-धूप में घूम सकती है।",
     "The petiole is the leaf's handle — by it the leaf hangs free to turn in air and sun."),

    ("plant-parts-functions", "easy",
     "पत्ती की चौड़ी, चपटी, हरी मुख्य सतह का नाम क्या है?",
     "What is the name of the broad, flat, green main surface of a leaf?",
     ["पर्णवृंत", "पर्णफलक (lamina)", "बाह्य त्वचा", "रोम-कूप"],
     ["Petiole", "Lamina", "Epidermis", "Hair pore"],
     1,
     "पर्णफलक ही वह चपटा प्रकाश-पकड़ भाग है जिस पर प्रकाश-संश्लेषण चलता है।",
     "The lamina is that flat light-catching expanse where photosynthesis runs."),

    ("plant-parts-functions", "easy",
     "गाजर और मूली का मोटा भाग वास्तव में किस कार्य के लिए रूपांतरित जड़ है?",
     "The thick part of carrot and radish is a root modified for which function?",
     ["श्वसन के लिए", "भोजन संग्रह के लिए", "जल उत्सर्जन के लिए", "प्रकाश पकड़ने के लिए"],
     ["For breathing", "For storing food", "For giving out water", "For catching light"],
     1,
     "द्विवर्षीय पौधे जड़ में भोजन जमा कर रखते हैं — गाजर/मूली भंडार-जड़ के उदाहरण हैं।",
     "Biennial plants bank food in the root — carrot/radish are store-root examples."),

    ("plant-parts-functions", "easy",
     "आलू और अदरक में भोजन जमा होने वाला भाग किस रूपांतरित ऊतक-भाग है?",
     "In potato and ginger, the food-storing part is a modified form of which plant part?",
     ["जड़ का", "तने का (भूतल-कंद)", "पत्ती का", "फूल का"],
     ["Of the root", "Of the stem (underground tuber)", "Of the leaf", "Of the flower"],
     1,
     "आलू-अदरक भूमिगत तने हैं जिनमें स्टार्च जमा होता है — 'आलू जड़ नहीं, तना है' यही पहचान है।",
     "Potato-ginger are underground stems packed with starch — 'potato is a stem, not a root' is the identity test."),

    ("plant-parts-functions", "easy",
     "कैक्टस की पत्तियाँ किस रूप में बदली होती हैं?",
     "In what form are the leaves of a cactus modified?",
     ["चौड़ी पत्तियाँ", "काँटों (spines) में", "पतली जड़ों में", "फूलों में"],
     ["Broad blades", "Into spines", "Into thin roots", "Into flowers"],
     1,
     "मरुस्थल में जल-बचत और चराव से बचाव के लिए पत्तियाँ काँटों में रूपांतरित हो गईं।",
     "In the desert, leaves turned into spines to save water and dodge grazers."),

    ("plant-parts-functions", "easy",
     "पौधे का ऊपरी भाग — तना, पत्तियाँ, फूल और फल — सम्मिलित रूप से क्या कहलाता है?",
     "What is the upper part of a plant — stem, leaves, flowers and fruits — collectively called?",
     ["मूल्रूप (root system)", "प्ररोह तंत्र (shoot system)", "बीजांड तंत्र", "वाहिका तंत्र"],
     ["Root system", "Shoot system", "Ovule system", "Vascular system"],
     1,
     "जमीन के ऊपर का सारा ढाँचा प्ररोह तंत्र है — मूल तंत्र जमीन के नीचे।",
     "The whole framework above ground is the shoot system — the root system lies below."),

    ("plant-parts-functions", "medium",
     "मुख्य जड़ से पतली पार्श्व जड़ें निकलने वाली जड़-प्रणाली बनाम समूह में फैली घास जैसी जड़ें — इन्हें क्रमशः क्या कहते हैं?",
     "A root system with side roots branching from one main root versus a tuft of spreading grass-like roots — what are these respectively called?",
     ["रेशेदार और कूड़ा", "मूसला (tap) और रेशेदार (fibrous)", "दोनों मूसला", "दोनों रेशेदार"],
     ["Fibrous and tapery", "Tap and fibrous", "Both tap", "Both fibrous"],
     1,
     "सरसों-गाजर जैसी एक-मुख्य-जड़ = मूसला; गेहूँ-घास जैसी बराबर गुच्छी = रेशेदार।",
     "Mustard-carrot type one-main-root = tap; wheat-grass type equal tuft = fibrous."),

    ("plant-parts-functions", "medium",
     "बरगद (बट वृक्ष) की मोटी जड़ें नीचे जमीन से निकलकर शाखाओं को सहारा देती हैं — इन्हें क्या कहते हैं?",
     "The thick roots of a banyan tree come down from branches and support them — what are they called?",
     ["अपस्थानिक जड़ें", "स्तंभमूल (prop roots)", "श्वसनमूल", "परजीवी जड़ें"],
     ["Adventitious roots", "Prop roots", "Breathing roots", "Parasitic roots"],
     1,
     "बरगद की खंभे जैसी स्तंभमूलें फैली शाखाओं का भार उठाती हैं — जीवित सहारा-सेतु।",
     "The banyan's pillar-like prop roots shoulder the spread of heavy branches — living buttresses."),

    ("plant-parts-functions", "medium",
     "मक्का और गन्ने के तने के निचले हिस्से से निकली जड़ें लंबे तने को गिरने से बचाती हैं — ये क्या कहलाती हैं?",
     "Roots arising from the lower nodes of maize and sugarcane stalks keep the tall stem from falling — what are they called?",
     ["स्तंभमूल", "अवलंबमूल (stilt roots)", "जलजड़ें", "भंडारमूल"],
     ["Prop roots", "Stilt roots", "Water roots", "Storage roots"],
     1,
     "आधार-स्थित तिरछी अवलंबमूलें ऊँचे पौधे को तूफान में भी सीधा रखती हैं।",
     "Base-borne slanting stilt roots keep the tall plant upright even in storms."),

    ("plant-parts-functions", "medium",
     "मटर के पौधे की पतली, कुंडलित पत्ती-रूपांतर संरचना किस काम आती है?",
     "What is the use of the thin, coiled leaf-modified structure of the pea plant?",
     ["भोजन बनाना", "कमजोर तने को सहारा देकर चढ़ना (tendril)", "जल संग्रह", "कीट पकड़ना"],
     ["Making food", "Helping the weak stem climb by gripping support (tendril)", "Storing water", "Catching insects"],
     1,
     "पत्ते के रूपांतरित प्रतान (tendril) जाली/डंडी को लपेटकर नाजुक तने को ऊपर खींचता है।",
     "The leaf-turned tendril coils round a lattice/stick and hauls the delicate stem up."),

    ("plant-parts-functions", "medium",
     "कैक्टस की पत्तियाँ छोटे-मोटे काँटे बनने से पौधे को दोहरा लाभ क्या मिलता है?",
     "What double benefit does the cactus gain from its leaves becoming small spines?",
     ["सुंदरता और रंग", "जल-हानि न्यूनतम और चरने वाले जानवरों से रक्षा", "प्रकाश ज्यादा पकड़ना और ठंड", "जल ज्यादा सोखना और गति"],
     ["Beauty and colour", "Minimum water loss and protection from grazing animals", "Catching more light and cooling", "Soaking more water and motion"],
     1,
     "छोटी-कठोर सतह = वाष्प-निकास घिरना + काँटा = काँटेदार कवच — मरुस्थल की दोहरी रणनीति।",
     "Tiny hard surface = vapour exit squeezed shut + spine = spiked armour — the desert's dual strategy."),

    ("plant-parts-functions", "medium",
     "पत्तियाँ पतली-चपटी क्यों होती हैं?",
     "Why are leaves thin and flat?",
     ["हवा में उड़ने के लिए", "अधिकतम सूर्य-प्रकाश पकड़ने के लिए विशाल, पतला प्रकाश-पर्दा बनाने में", "जल रोकने के लिए", "जड़ों को ढकने के लिए"],
     ["To fly in air", "To spread a huge thin light-curtain that catches maximum sunlight", "To hold water", "To cover the roots"],
     1,
     "चपटापन प्रकाश-ग्रहण क्षेत्र बढ़ाता है और पतलापन भीतर तक प्रकाश-वायु पहुँचाता है।",
     "Flatness enlarges the light-catching area; thinness lets light and air reach inside."),

    ("plant-parts-functions", "medium",
     "पत्तियाँ तने पर वैसे क्यों लगी रहती हैं कि एक-दूसरे को ढकें नहीं (जैसे नारंगी छिलके की व्यवस्था)?",
     "Why are leaves arranged on the stem so that they do not shade one another (like a mosaic)?",
     ["सुंदर दिखने के लिए", "ताकि प्रत्येक पत्ती को पर्याप्त सूर्य-प्रकाश मिले — प्रकाश-प्रतिस्पर्धा से बचाव", "बारिश में गिरने से बचने के लिए", "कीड़ों को भगाने के लिए"],
     ["To look beautiful", "So every leaf gets enough sunlight — avoiding mutual shading", "To avoid falling in rain", "To scare away insects"],
     1,
     "पत्र-विन्यास (phyllotaxy) प्रकाश की साझेदारी की योजना है — हर पत्ती का धूप-हक सुरक्षित।",
     "Leaf arrangement (phyllotaxy) is a sunshine-sharing plan — every leaf's sun-right secured."),

    ("plant-parts-functions", "medium",
     "पर्णफलक के बीच से गुजरने वाली मोटी केंद्रीय शिरा क्या कहलाती है?",
     "What is the thick central vein running through the middle of the lamina called?",
     ["पर्णवृंत", "मध्यशिरा (midrib)", "उपफलक", "तिलक"],
     ["Petiole", "Midrib", "Sub-lamina", "Stipule"],
     1,
     "मध्यशिरा पर्णफलक की रीढ़ है — इसी से पतली शिराएँ दोनों ओर फैलती हैं और पत्ती को तानती हैं।",
     "The midrib is the lamina's spine — thin veins spread from it on both sides and rib the leaf."),

    ("plant-parts-functions", "medium",
     "पत्तियों में शिराओं की जालीनुमा (जाल जैसी) बनाम समानांतर (एक-सीधे रेखांकित) व्यवस्था को क्रमशः क्या कहते हैं?",
     "The net-like versus the parallel arrangement of veins in leaves are respectively called what?",
     ["समानांतर और जालीदार", "जालीदार (reticulate) और समानांतर (parallel) शिराविन्यास", "स्तंभित और वलयित", "केंद्रित और बिखरे"],
     ["Parallel and reticulate", "Reticulate and parallel venation", "Columnar and annular", "Centred and scattered"],
     1,
     "आम-पपीते जैसी जाल = जालीदार; घास-गन्ना जैसी सीधी रेखाएँ = समानांतर विन्यास।",
     "Mango-papaya net = reticulate; grass-sugarcane straight lines = parallel venation."),

    ("plant-parts-functions", "medium",
     "प्याज़ का गूँथा भाग वास्तव में क्या है?",
     "What actually is the swollen part of an onion?",
     ["जड़ का भंडार", "मांसल पत्तों का भंडार-गुच्छा (बल्ब)", "तने का कंद", "फूल का आधार"],
     ["A store-root", "A store-tuft of fleshy leaves (bulb)", "A stem tuber", "The base of a flower"],
     1,
     "प्याज़ की परतें मांसल भंडार-पत्तियाँ हैं — भूमिगत बल्ब में जमा भोजन।",
     "Onion layers are fleshy storage leaves — food banked in an underground bulb."),

    ("plant-parts-functions", "medium",
     "बीज बोए जाने पर सबसे पहले बाहर निकलने वाला भाग कौन-सा होता है?",
     "Which part comes out first when a seed is sown?",
     ["पत्ती", "मूलिका (radicle) — जो जड़ बनती है", "फूल की कली", "तने की कली"],
     ["The leaf", "The radicle — which becomes the root", "A flower bud", "A shoot bud"],
     1,
     "अंकुरण में मूलिका पहले निकलकर तुरंत पकड़ और जल-आपूर्ति सुनिश्चित करती है — फिर प्ररोह खुलता है।",
     "In germination the radicle exits first to secure grip and water supply at once — only then the shoot opens."),

    ("plant-parts-functions", "medium",
     "पहाड़ी ढलानों और नदी-किनारों पर पेड़ लगाने से मिट्टी का कटाव (erosion) क्यों रुक जाता है?",
     "Why does soil erosion stop on hill slopes and riverbanks when trees are planted?",
     ["पेड़ मिट्टी खा जाते हैं", "वृक्षों की फैली जड़ें मिट्टी-कणों को जाल में बाँध लेती हैं — बारिश-जल कण बहा नहीं पाता", "पत्तियाँ पानी पी लेती हैं", "तना मिट्टी ढक लेता है"],
     ["Trees eat the soil", "The trees' spreading roots net the soil particles together — rainwater cannot wash them away", "The leaves drink the water", "The stem covers the soil"],
     1,
     "जड़-जाल मिट्टी की बुनाई बन जाता है — वर्षा की मार से भूमि स्थिर रहती है; यही जड़ का बाँधने-वाला (soil-binding) कार्य है।",
     "The root-net becomes the soil's weave — the land stays firm under the rain's beating; this is the root's soil-binding role."),
    ("plant-parts-functions", "medium",
     "लता (जैसे मनी प्लांट) और सीधा वृक्ष — दोनों के तने में मूल भिन्नता क्या है?",
     "What is the basic difference between the stems of a vine (like money plant) and an upright tree?",
     ["दोनों में कोई अंतर नहीं", "लता का तना कमजोर — सहारा खोजकर चढ़ता है; वृक्ष का तना मजबूत-काष्ठय — स्वयं सीधा खड़ा रहता है", "लता का तना भोजन नहीं बनाता", "वृक्ष का तना जमीन के नीचे होता है"],
     ["No difference at all", "The vine's stem is weak — it climbs seeking support; the tree's stem is strong-woody — stands upright by itself", "The vine's stem makes no food", "The tree's stem is underground"],
     1,
     "तने की मजबूती ही वृक्ष-बनाम-लता का आधार है — सहारा माँगना बनाम खुद खड़ा रहना।",
     "Stem strength is the tree-vs-vine basis — seeking support versus standing self-made."),

    ("plant-parts-functions", "hard",
     "संशोधन और कार्य का सही मेल कौन-सा है?",
     "Which is the correct matching of modification and function?",
     ["बरगद की स्तंभमूल — भोजन संग्रह", "गाजर की जड़ — भोजन संग्रह; मटर का प्रतान — चढ़ना; कैक्टस का काँटा — जल-बचत/रक्षा", "आलू — प्रकाश पकड़ना", "प्याज़ की जड़ — श्वसन"],
     ["Banyan's prop roots — food storage", "Carrot's root — food storage; pea's tendril — climbing; cactus spine — water-saving/protection", "Potato — catching light", "Onion's root — breathing"],
     1,
     "प्रत्येक संशोधन का अपना उद्देश्य निश्चित है — स्तंभमूल = सहारा (भंडारण नहीं), गाजर = भंडारण, प्रतान = चढ़ाई, काँटा = रक्षा।",
     "Each modification has its fixed purpose — prop root = support (not storage), carrot = storage, tendril = climbing, spine = defence."),

    ("plant-parts-functions", "hard",
     "मैंग्रोव (डूबते-उभरते जंगल) पौधों की जड़ें कीचड़ से ऊपर हवा में खड़ी दिखती हैं — कारण?",
     "In mangroves, roots stand up out of the mud into the air — why?",
     ["प्रकाश पकड़ने के लिए", "कीचड़ में ऑक्सीजन नहीं होती — श्वसनमूल (pneumatophores) हवा से ऑक्सीजन लेती हैं", "फूल बनाने के लिए", "बीज फैलाने के लिए"],
     ["To catch light", "The mud lacks oxygen — breathing roots (pneumatophores) take oxygen from the air", "To make flowers", "To scatter seeds"],
     1,
     "गाद-भरी नमकीन मिट्टी में श्वसन दम तोड़ता है — खुले श्वसनमूल ही ऑक्सीजन-द्वार बनते हैं।",
     "In oxygen-starved salty mud, breathing would choke — the exposed breathing roots become oxygen doorways."),

    ("plant-parts-functions", "hard",
     "केला 'वृक्ष' कहलाता है पर वानस्पतिक रूप से वृक्ष नहीं है — क्यों?",
     "The banana is called a 'tree' but botanically is not a tree — why?",
     ["यह बहुत छोटा होता है", "इसका तना रसीला-नरम (आधार-कंद वाला छद्म-तना) है — काष्ठय धड़ और शाखाएँ नहीं होतीं", "इसमें जड़ें नहीं होतीं", "यह जमीन पर फैलता है"],
     ["It is very small", "Its stem is succulent-soft (a base-swollen pseudo-stem) — it has no woody trunk or branches", "It has no roots", "It spreads on the ground"],
     1,
     "काष्ठ-निर्माण (द्वितीय वृद्धि) के बिना वृक्ष की परिभाषा पूरी नहीं होती — केला विशाल पर्ण-गुच्छ का रसीला छद्म-तना है।",
     "Without wood-formation (secondary growth) the definition of a tree fails — the banana is a leafy tuft on a succulent pseudo-stem."),

    # ---------------- crop-production (40: E15/M20/H5) ----------------
    ("crop-production", "easy",
     "निम्न में से कौन-सी खरीफ फसल है?",
     "Which of the following is a kharif crop?",
     ["गेहूँ", "धान (पaddy)", "सरसों", "चना"],
     ["Wheat", "Paddy (rice)", "Mustard", "Gram"],
     1,
     "वर्षा-ऋतु में बोई जाने वाली धान-मक्का जैसी फसलें खरीफ कहलाती हैं।",
     "Rainy-season crops like paddy-maize are called kharif."),

    ("crop-production", "easy",
     "निम्न में से कौन-सी रबी फसल है?",
     "Which of the following is a rabi crop?",
     ["धान", "मक्का", "गेहूँ", "मूंगफली"],
     ["Paddy", "Maize", "Wheat", "Groundnut"],
     2,
     "शरद/शीत ऋतु में बोई जाने वाली गेहूँ-सरसों जैसी फसलें रबी कहलाती हैं।",
     "Winter-season crops like wheat-mustard are called rabi."),

    ("crop-production", "easy",
     "खरीफ फसलें किस ऋतु में बोई जाती हैं?",
     "In which season are kharif crops sown?",
     ["शीत ऋतु (अक्टूबर-नवंबर) में", "वर्षा ऋतु (जून-जुलाई) में", "ग्रीष्म की धूप में", "किसी भी महीने"],
     ["In winter (October-November)", "In the rainy season (June-July)", "In summer sun", "Any month"],
     1,
     "खरीफ = वर्षा पर आधारित — जून-जुलाई की बुवाई, सितंबर-अक्टूबर की कटाई।",
     "Kharif = rain-based — sown June-July, harvested September-October."),

    ("crop-production", "easy",
     "रबी फसलें किस ऋतु में बोई जाती हैं?",
     "In which season are rabi crops sown?",
     ["वर्षा ऋतु में", "शीत ऋतु (अक्टूबर-नवंबर) में", "मानसून के शिखर पर", "जून में"],
     ["In the rainy season", "In winter (October-November)", "At the monsoon peak", "In June"],
     1,
     "रबी = शीत-ऋतु फसल — अक्टूबर-नवंबर की बुवाई, मार्च-अप्रैल की कटाई।",
     "Rabi = winter crop — sown October-November, harvested March-April."),

    ("crop-production", "easy",
     "जुताई (ploughing) से क्या तात्पर्य है?",
     "What is meant by ploughing?",
     ["बीज बोना", "मिट्टी को खोदकर लुढ़काना/पलटना", "फसल काटना", "खेत में जल देना"],
     ["Sowing seeds", "Digging, loosening and turning the soil", "Cutting the crop", "Giving water to the field"],
     1,
     "हल/ट्रैक्टर से मिट्टी पलटना-भूरभूरा करना ही जुताई है — बुवाई की पहली सीढ़ी।",
     "Turning and crumbling the soil with plough/tractor is ploughing — the first step before sowing."),

    ("crop-production", "easy",
     "बुवाई (sowing) का अर्थ क्या है?",
     "What is meant by sowing?",
     ["पकी फसल काटना", "खेत में बीज डालना", "खाद मिलाना", "खरपतवार निकालना"],
     ["Cutting the ripe crop", "Putting seeds into the field", "Mixing manure", "Removing weeds"],
     1,
     "अच्छे बीजों को मिट्टी में उचित गहराई पर डालना ही बुवाई है।",
     "Placing good seeds in soil at the right depth is sowing."),

    ("crop-production", "easy",
     "खाद (manure) किससे बनती है?",
     "What is manure made from?",
     ["रासायनिक कारखानों में", "पशु-पौध अपशिष्टों के सड़ने से (जैविक)", "खनिज पत्थरों से", "वायु से"],
     ["In chemical factories", "From rotting animal-plant wastes (organic)", "From mineral rocks", "From air"],
     1,
     "गोबर, मूत, फसल-अवशेष के खाद-निर्माण से बना पदार्थ = खाद — पूर्णतः जैविक।",
     "Dung, urine, crop residues composted together = manure — fully organic."),

    ("crop-production", "easy",
     "उर्वरक (fertilizer) क्या होता है?",
     "What is a fertiliser?",
     ["जैविक सड़ा पदार्थ", "फैक्ट्री-निर्मित रासायनिक पदार्थ जिसमें विशिष्ट पोषक (NPK) हों", "मिट्टी की चट्टान", "वर्षा का पानी"],
     ["Rotted organic matter", "Factory-made chemical substance containing specific nutrients (NPK)", "Soil rock", "Rainwater"],
     1,
     "उर्वरक औद्योगिक रूप से बने पोषक-संकेंद्रित लवण हैं — यूरिया, DAP उदाहरण।",
     "Fertilisers are industrially made nutrient-concentrated salts — urea, DAP examples."),

    ("crop-production", "easy",
     "सिंचाई (irrigation) का अर्थ बताइए।",
     "State the meaning of irrigation.",
     ["फसल काटना", "फसलों को आवश्यकतानुसार जल पहुँचाना", "बीज छाँटना", "खेत जोतना"],
     ["Cutting the crop", "Supplying water to crops as needed", "Sorting seeds", "Tilling the field"],
     1,
     "वर्षा पर्याप्त न होने पर नहर/कुएँ/नलकूप से फसल को जल देना ही सिंचाई है।",
     "When rain falls short, giving the crop water via canal/well/tubewell is irrigation."),

    ("crop-production", "easy",
     "खरपतवार (weeds) क्या होते हैं?",
     "What are weeds?",
     ["वांछित फसल-पौधे", "अवांछित जंगली पौधे जो फसल के साथ उग आते हैं", "खाद के कीड़े", "बीज के दाने"],
     ["Wanted crop plants", "Unwanted wild plants that grow along with the crop", "Manure insects", "Seed grains"],
     1,
     "खेत में अपने-आप उगे अनचाहे पौधे खरपतवार हैं — फसल के प्रतिद्वंद्वी।",
     "Self-sown unwelcome plants in the field are weeds — the crop's rivals."),

    ("crop-production", "easy",
     "फसल की कटाई (harvesting) कहलाती है —",
     "The cutting and gathering of a ripe crop is called —",
     ["बुवाई", "जुताई", "कटाई/फसल-कर्तन (harvesting)", "गुड़ाई"],
     ["Sowing", "Ploughing", "Harvesting", "Weeding"],
     2,
     "पकी फसल के दाने/फल काटकर इकट्ठा करना ही कटाई है — खेती-चक्र की पूर्ति।",
     "Cutting and collecting the grain/fruit of the ripe crop is harvesting — the farming cycle's completion."),

    ("crop-production", "easy",
     "दाने और भूसे को हवा की सहायता से अलग करने की क्रिया को क्या कहते हैं?",
     "What is the act of separating grain from chaff with the help of wind called?",
     ["ओखली", "फटकनी/वायु-पृथक्करण (winnowing)", "खरल", "छलनी"],
     ["Mortar", "Winnowing", "Grinder", "Sieve"],
     1,
     "हल्का भूसा हवा में दूर उड़ता है, भारी दाना नीचे गिरता है — यही फटकने का सिद्धांत।",
     "Light chaff blows away, heavy grain drops below — that is winnowing's principle."),

    ("crop-production", "easy",
     "मुर्गीपालन (poultry) का संबंध किससे है?",
     "Poultry is related to what?",
     ["मछलियों का पालन", "मुर्गियों का पालन — अंडा व मांस हेतु", "मधुमक्खी पालन", "बकरी पालन"],
     ["Rearing fish", "Rearing fowl — for eggs and meat", "Bee-keeping", "Goat-rearing"],
     1,
     "मुर्गीपालन अंडा-उत्पादन और मांस हेतु की जाने वाली पशुधन-शाखा है।",
     "Poultry is the livestock branch for egg production and meat."),

    ("crop-production", "easy",
     "मधुमक्खीपालन (apiculture) क्या है?",
     "What is apiculture?",
     ["रेशम के कीट पालना", "मधुमक्खियों का पालन — शहद एवं मोम हेतु", "कृमि पालन", "मुर्गी पालन"],
     ["Rearing silkworms", "Rearing honeybees — for honey and wax", "Rearing worms", "Rearing fowl"],
     1,
     "एपिस मधुमक्खियों के डिब्बों में पालन से शहद और मोम दोनों मिलते हैं।",
     "Keeping Apis bees in boxes yields both honey and wax."),

    ("crop-production", "easy",
     "डेयरी (dairy) का अर्थ है —",
     "Dairy means —",
     ["ऊन उत्पादन", "दुधारू पशुओं से दूध-उत्पादन एवं उसका प्रबंधन", "फसल-भंडारण", "मछली पकड़ना"],
     ["Wool production", "Milk production from milch animals and its management", "Crop storage", "Catching fish"],
     1,
     "गाय-भैंस जैसे दुधारू पशुओं का पालन-दुहन-प्रसंस्करण मिलाकर डेयरी है।",
     "Rearing, milking and processing of milch animals like cow-buffalo together form dairy."),

    ("crop-production", "medium",
     "बुवाई से पहले मिट्टी को जोड़ना-पलटना क्यों ज़रूरी है?",
     "Why is it necessary to loosen and turn the soil before sowing?",
     ["मिट्टी सुंदर दिखे", "खुली-भुरभुरी मिट्टी में हवा-नमी घुलती है और जड़ें आराम से गहरी उतरती हैं", "खरपतवार उगना बंद हो जाता है", "बीज रंगीन दिखते हैं"],
     ["Soil looks beautiful", "Open crumbly soil lets in air-moisture and roots descend easily", "Weeds stop germinating", "Seeds look colourful"],
     1,
     "जुती मिट्टी = साँस लेती मिट्टी — जड़-विस्तार, सूक्ष्मजीव-गतिविधि और जल-निकास सब बेहतर।",
     "Tilled soil = breathing soil — root spread, microbe activity and drainage all improve."),

    ("crop-production", "medium",
     "हल (plough), कुदाल-गुड़ाई (harrow) और कल्टीवेटर किस क्रम-उद्देश्य से प्रयुक्त होते हैं?",
     "Plough, harrow and cultivator are used in which order-purpose?",
     ["केवल एक ही उपकरण के नाम", "हल — गहरी जुताई; गुड़ाई — मिट्टी भूरभूरी/समतल; कल्टीवेटर — ट्रैक्टर से एक साथ कई फावड़े", "हल — कटाई; गुड़ाई — बुवाई; कल्टीवेटर — भंडारण", "तीनों सिंचाई उपकरण"],
     ["Just three names of one tool", "Plough — deep tilling; harrow — crumbling/levelling; cultivator — several plough-shares pulled together by tractor", "Plough — harvest; harrow — sowing; cultivator — storage", "All three are irrigation tools"],
     1,
     "तीनों मिट्टी-तैयारी की सीढ़ियाँ हैं — गहराई, बारीकी, और यंत्र-शक्ति में वृद्धि क्रम।",
     "The three are steps of soil-prep — in order of depth, fineness, and machine power."),

    ("crop-production", "medium",
     "बुवाई के लिए बीज कैसे छाँटे जाते हैं?",
     "How are seeds sorted for sowing?",
     ["रंग के आधार पर", "स्वस्थ, चुस्त और शुद्ध किस्म के बीज — हल्के-टूटे-रोगी बीज अलग कर", "आकार के आधार पर", "सभी बीज बिना छँटाई बो दिए जाते हैं"],
     ["On the basis of colour", "Healthy, vigorous and pure-variety seeds — separating light-broken-diseased ones", "On the basis of size", "All seeds are sown without sorting"],
     1,
     "अच्छा बीज = अच्छी फसल का आधा काम; खराब अंकुरण व रोग बीज-छँटाई से ही रुकते हैं।",
     "Good seed = half the job of a good crop; poor germination and disease are checked at sorting itself."),

    ("crop-production", "medium",
     "बीज-ड्रिल (seed drill) का उपयोग किस दृष्टि से लाभदायक है?",
     "In what respect is using a seed drill advantageous?",
     ["बीज बिखर जाते हैं", "बीज एक-सी गहराई और एक-से अंतर पर बोए जाते हैं तथा मिट्टी से ढक जाते हैं — खपत घटती है, अंकुरण सुधरता है", "खेत छोटा दिखता है", "सिंचाई बढ़ती है"],
     ["Seeds get scattered", "Seeds are sown at uniform depth and spacing and get covered by soil — less wastage, better germination", "The field looks smaller", "Irrigation increases"],
     1,
     "ड्रिल की नलियाँ बीज को मापे हुए अंतर-गहराई पर उतारती हैं — हाथ-बुवाई की अनियमितता खत्म।",
     "The drill's tubes drop seeds at measured spacing-depth — hand-sowing's unevenness gone."),

    ("crop-production", "medium",
     "धान की फसल में बीज-बिखरी बुवाई के बजाय रोपाई (transplantation) क्यों की जाती है?",
     "Why is transplantation done in paddy instead of broadcasting seeds?",
     ["क्योंकि धान के बीज बहुत बड़े होते हैं", "पौधशाला में उगे हृष्ट-पुष्ट पौधे खेत में उखाड़कर लगाने से एक-सी दूरी और बेहतर जीवित रहन मिलता है", "क्योंकि धान को प्रकाश नहीं चाहिए", "क्योंकि रोपाई में जल की जरूरत नहीं"],
     ["Because paddy seeds are very large", "Uprooting sturdy nursery seedlings and planting them in the field gives uniform spacing and better survival", "Because paddy needs no light", "Because transplantation needs no water"],
     1,
     "पौधशाला में पौधे सुरक्षित-सघन बढ़ते हैं; रोपाई पर खेत में नियंत्रित पंक्ति-अंतरण मिलता है।",
     "Seedlings grow safe-and-dense in a nursery; transplantation gives controlled row-placement in the field."),

    ("crop-production", "medium",
     "खाद और उर्वरक में मूल अंतर क्या है?",
     "What is the basic difference between manure and fertiliser?",
     ["दोनों एक ही हैं", "खाद जैविक — मिट्टी-संरचना और जैविक-सक्रियता सुधारती है; उर्वरक अजैविक — विशिष्ट पोषक तेज़ी से देता है", "खाद रासायनिक होती है", "उर्वरक गोबर से बनता है"],
     ["Both are the same", "Manure is organic — improves soil structure and biological activity; fertiliser is inorganic — delivers specific nutrients fast", "Manure is chemical", "Fertiliser is made from dung"],
     1,
     "खाद मिट्टी का संपूर्ण स्वास्थ्य-केंद्र, उर्वरक लक्षित-पोषक इंजेक्शन — दोनों की भूमिका अलग।",
     "Manure is the soil's all-round health-centre; fertiliser is targeted nutrient injection — different roles."),

    ("crop-production", "medium",
     "अधिक मात्रा में उर्वरक डालने का परिणाम क्या हो सकता है?",
     "What can be the result of applying fertiliser in excess?",
     ["फसल दुगनी उगती है", "जल-स्रोतों में नाइट्रेट बहकर जल-प्रदूषण और मिट्टी-स्वास्थ्य गिरावट", "मिट्टी की उर्वरा शक्ति स्थायी रूप से बढ़ती है", "कोई प्रभाव नहीं"],
     ["The crop doubles", "Nitrates run off into water sources causing water pollution and declining soil health", "Soil fertility rises permanently", "No effect"],
     1,
     "पौधा जितना ले सकता है उससे अधिक घुला लवण वर्षा-जल के साथ तालाब-नदी में बह जाता है।",
     "Salts dissolved beyond what plants can take flow with rainwater into ponds and rivers."),

    ("crop-production", "medium",
     "कंपोस्ट खाद बनाने की विधि क्या है?",
     "What is the method of making compost?",
     ["पत्थर पिसकर", "गोबर, फसल-अवशेष आदि गड्ढे में डालकर ढक देना — सड़न-खाद से कुछ सप्ताह/महीनों में जैविक खाद तैयार", "रासायनिक विलयन मिलाकर", "जलते में जलाकर"],
     ["By grinding stones", "Putting dung, crop residues etc. in a pit and covering — decomposition turns it into organic manure over weeks/months", "By mixing a chemical solution", "By burning in fire"],
     1,
     "सड़ने वाले सूक्ष्मजीव अपशिष्ट को अपघटित कर अन्न-गुणवत्ता वाली काली खाद बना देते हैं।",
     "Decomposing microbes break the waste down into nutrient-rich dark manure."),

    ("crop-production", "medium",
     "वर्मीकंपोस्ट (vermicompost) की विशेषता क्या है?",
     "What is special about vermicompost?",
     ["यह रासायनिक उर्वरक है", "इसे केंचुए (earthworms) अपशिष्ट खाकर बनाते हैं — अति-गुणवत्ता जैविक खाद", "यह केवल गोबर से बनती है", "यह जल में घोलकर छिड़कते हैं"],
     ["It is a chemical fertiliser", "Earthworms make it by eating waste — an extra-high-quality organic manure", "It is made only from dung", "It is sprayed dissolved in water"],
     1,
     "केंचुओं की पाचन-नली अपशिष्ट को 'काला सोना' खाद में बदल देती है।",
     "The earthworm's gut turns waste into 'black gold' manure."),

    ("crop-production", "medium",
     "टपक सिंचाई (drip irrigation) को जल-किफायती क्यों कहा जाता है?",
     "Why is drip irrigation called water-efficient?",
     ["इसमें जल पूरे खेत पर बरसता है", "नलिकाओं के छिद्रों से बूँद-बूँद जल सीधे जड़-क्षेत्र में जाता है — वाष्पीकरण-अपव्यय न्यूनतम", "इसमें जल ऊपर हवा में फव्वारा बनता है", "इसमें जल की जगह खाद जाती है"],
     ["It rains water over the whole field", "Water drips from holed pipes straight into the root zone — evaporation-wastage minimal", "It sprays water into the air", "Manure goes instead of water"],
     1,
     "बूँद-सिंचाई जड़ों तक सीधी डिलीवरी करती है — दुर्लभ-जल क्षेत्रों और बागानों के लिए आदर्श।",
     "Drip delivers straight to the roots — ideal for water-scarce regions and orchards."),

    ("crop-production", "medium",
     "खेत में लगातार भरा पानी खड़ा रहने पर फसल पीली पड़ जाती है — कारण?",
     "A crop turns yellow when water keeps standing in the field — why?",
     ["जल में विटामिन नहीं", "जलभराव (waterlogging) में जड़ों को ऑक्सीजन नहीं मिलती — श्वसन रुकता है और जड़ें निष्क्रिय हो जाती हैं", "पानी ज्यादा ठंडा होता है", "खेत में खाद घुल जाती है"],
     ["Water lacks vitamins", "In waterlogging the roots get no oxygen — respiration stops and the roots go inert", "The water is too cold", "The manure dissolves away"],
     1,
     "जड़ें भी साँस लेती हैं — डूबी जड़ की ऑक्सीजन-हाहाकार ही पीलापन बनता है।",
     "Roots breathe too — a drowned root's oxygen-cry turns into yellowing."),

    ("crop-production", "medium",
     "खरपतवार निकालने की विधियाँ कौन-सी हैं?",
     "Which are the methods of removing weeds?",
     ["केवल हाथ से उखाड़ना", "खुरपी/हाथ से उखाड़ना और उचित अवसर पर खरपतवारनाशी (जैसे 2,4-D) छिड़कना", "केवल फसल जला देना", "सिंचाई बंद कर देना"],
     ["Only uprooting by hand", "Uprooting with khurpi/hand and spraying weedicide (like 2,4-D) at the right stage", "Only burning the crop", "Stopping irrigation"],
     1,
     "मैनुअल गुड़ाई + रासायनिक नियंत्रण — दोनों समयबद्ध उपयोग खरपतवार-प्रबंधन के स्तंभ हैं।",
     "Manual hoeing + chemical control — both used on schedule are the pillars of weed management."),

    ("crop-production", "medium",
     "खरपतवार फसल के लिए हानिकारक क्यों हैं?",
     "Why are weeds harmful to crops?",
     ["ये खेत की शोभा बढ़ाते हैं", "ये फसल से जल, पोषक, प्रकाश और स्थान के लिए प्रतिस्पर्धा कर फसल को कमजोर करते हैं", "ये मिट्टी को जोड़ते हैं", "ये जड़ों की रक्षा करते हैं"],
     ["They beautify the field", "They compete with the crop for water, nutrients, light and space, weakening it", "They bind the soil", "They protect the roots"],
     1,
     "अनचाहे मेहमान थाली का हिस्सा खा जाते हैं — फसल का उत्पादन गिरता है।",
     "Uninvited guests eat into the plate — the crop's yield falls."),

    ("crop-production", "medium",
     "कीटनाशक/खरपतवारनाशी का प्रयोग करते समय किस सावधानी का ध्यान रखा जाता है?",
     "What precaution is observed while applying pesticides/weedicides?",
     ["जितना हो उतना छिड़क देना", "निर्धारित मात्रा-समय का पालन, पूरी सुरक्षा-वेशभूषा और फसल-कटाई से पहले पर्याप्त अंतराल (विषाक्त-अवशेष से बचाव)", "हवा के विपरीत छिड़कना", "बारिश में ही छिड़कना"],
     ["Spray as much as possible", "Follow the prescribed dose-time, wear full protective gear and keep a sufficient gap before harvest (avoiding toxic residue)", "Spray against the wind", "Spray only in rain"],
     1,
     "रासायनिक अवशेष मानव-स्वास्थ्य तक पहुँचता है — मात्रा-अंतराल का अनुशासन ही सुरक्षा है।",
     "Chemical residue reaches human health — discipline of dose and gap is the safety."),

    ("crop-production", "medium",
     "कंबाइन (combine) नामक यंत्र क्या काम करता है?",
     "What does the machine called 'combine' do?",
     ["केवल बोता है", "एक ही चलन में कटाई और दाना-भूसा पृथक्करण (threshing) दोनों", "केवल सिंचाई करता है", "केवल जुताई करता है"],
     ["Only sows", "Harvests and separates grain from straw (threshing) in one pass", "Only irrigates", "Only ploughs"],
     1,
     "कंबाइन = हार्वेस्टर + थ्रेशर — दो श्रम-चरणों का एक यंत्रीकरण।",
     "Combine = harvester + thresher — two labour steps merged into one machine."),

    ("crop-production", "medium",
     "अनाज को भंडारण से पहले सुखाना क्यों ज़रूरी है?",
     "Why must grain be dried before storage?",
     ["रंग सुंदर बनाने के लिए", "आर्द्रता रहने पर फफूंद-कीट पनपते हैं — सूखा दाना सुरक्षित रहता है", "वजन बढ़ाने के लिए", "गिनती आसान के लिए"],
     ["To make the colour pretty", "Leftover moisture breeds fungus-insects — dry grain stays safe", "To increase weight", "For easy counting"],
     1,
     "नमी = सूक्ष्मजीवों का निमंत्रण; सुखाया अनाज भंडार-कीटों का खाना नहीं बनता।",
     "Moisture = an invitation to microbes; dried grain does not become store-insect food."),

    ("crop-production", "medium",
     "बड़े पैमाने पर अनाज-भंडारण के लिए किन व्यवस्थाओं का प्रयोग होता है?",
     "What arrangements are used for large-scale grain storage?",
     ["खुले मैदान में ढेर", "साइलो/गोदाम — वायुरोधी, सूखे, फुमिगेशन (धूम्र-उपचार) से कीट-रहित", "प्लास्टिक थैलियों में खुला", "नदी-तट पर"],
     ["Heaps in open fields", "Silos/godowns — airtight, dry, insect-free by fumigation (smoke treatment)", "Open in plastic bags", "On riverbanks"],
     1,
     "भारत में FCI के साइलो-गोदाम बफर-भंडार रखते हैं — सुरक्षित भंडारण = खाद्य-सुरक्षा का आधार।",
     "FCI's silos-godowns in India keep buffer stocks — safe storage = the base of food security."),

    ("crop-production", "medium",
     "पशुपालन (animal husbandry) का अर्थ क्या है?",
     "What is meant by animal husbandry?",
     ["जंगली जानवरों का शिकार", "पालतू पशुओं का वैज्ञानिक प्रबंधन — भोजन (दूध/मांस/अंडा/शहद) एवं अन्य उत्पाद हेतु", "पशुओं का बाजार में क्रय-विक्रय", "पशु चिकित्सा केवल"],
     ["Hunting wild animals", "Scientific management of domestic animals — for food (milk/meat/egg/honey) and other products", "Buying-selling animals in market", "Only veterinary care"],
     1,
     "भोजन-उत्पादन की यह शाखा दूध-अंडा-मांस-शहद जैसे प्रोटीन-समृद्ध खाद्य देती है।",
     "This branch of food production gives protein-rich foods like milk-egg-meat-honey."),

    ("crop-production", "medium",
     "दुधारू (milch) और कर्षण (draught) पशुओं में अंतर क्या है?",
     "What is the difference between milch and draught animals?",
     ["दोनों एक ही हैं", "दुधारू — दूध हेतु (गाय, भैंस); कर्षण — बोझ-खींचने/जुताई हेतु (बैल, ऊँट)", "दुधारू पशु केवल बकरी है", "कर्षण पशु अंडे देते हैं"],
     ["Both are the same", "Milch — for milk (cow, buffalo); draught — for hauling/tilling (bullock, camel)", "Milch animals are only goats", "Draught animals lay eggs"],
     1,
     "पशुधन का यही द्विविभाजन डेयरी-बनाम-कृषि-शक्ति निर्धारित करता है।",
     "This very two-way split of livestock decides dairy versus farm-power."),

    ("crop-production", "medium",
     "मत्स्यपालन (pisciculture) का संबंध किससे है?",
     "Pisciculture is related to what?",
     ["मुर्गी पालना", "मछलियों का कृत्रिम पालन — जलीय कृषि", "रेशम कीट", "मधुमक्खी"],
     ["Rearing fowl", "Artificial rearing of fish — aquafarming", "Silkworm", "Honeybee"],
     1,
     "तालाब-बाँध-जाल में मछली का पोषण-प्रबंधन = मत्स्यपालन — प्रोटीन का जलीय स्रोत।",
     "Fish reared-managed in ponds-dams-nets = pisciculture — an aquatic source of protein."),

    ("crop-production", "hard",
     "जुताई के बाद खेत को समतल (level) करना क्यों ज़रूरी माना जाता है?",
     "Why is levelling the field considered necessary after ploughing?",
     ["खेत दूर से चौकोर दिखे", "समतलीकरण से सिंचाई-जल का एक-सा वितरण होता है और वर्षा-जल मिट्टी-कटाव से ऊपरी परत बहाकर नहीं ले जाता", "बीजों का रंग निखरता है", "खरपतवार खड़े नहीं होते"],
     ["The field looks square from afar", "Levelling distributes irrigation water evenly and stops rainwater from carrying away the topsoil by erosion", "The seeds' colour brightens", "Weeds cannot stand"],
     1,
     "ढालू खेत में जल एक ओर जमा और दूसरी ओर सूखा — समतलता ही संसाधन-न्याय की गारंटी।",
     "On a sloped field water logs one side and starves the other — levelness alone guarantees resource justice."),

    ("crop-production", "hard",
     "रासायनिक उर्वरक तत्काल पोषक देता है, फिर भी खाद को मिट्टी-संरचना सुधारने वाला क्यों कहा जाता है?",
     "Chemical fertiliser gives instant nutrients, so why is manure called the improver of soil structure?",
     ["खाद में पोषक नहीं होते", "खाद का जैविक पदार्थ मिट्टी को भुरभुरा बनाता है — जल-धारण, वायु-संचार और सूक्ष्मजीव-गतिविधि बढ़ती है; यह लाभ उर्वरक को नहीं", "खाद तेज़ घुलती है", "खाद की गंध मिट्टी को बचाती है"],
     ["Manure has no nutrients", "Manure's organic matter crumbens the soil — water retention, aeration and microbial activity rise; fertiliser gives no such benefit", "Manure dissolves fast", "Manure's smell protects soil"],
     1,
     "खाद मिट्टी का घर-सुधार करती है, उर्वरक केवल रसोई-आपूर्ति — दीर्घकालिक स्वास्थ्य जैविक पदार्थ से।",
     "Manure renovates the soil's home; fertiliser only supplies the kitchen — long-term health comes from organic matter."),

    ("crop-production", "hard",
     "2,4-D जैसा खरपतवारनाशी गेहूँ-जैसी घासफसलों की फसल को नुकसान नहीं पहुँचाता — इसकी व्याख्या क्या है?",
     "A weedicide like 2,4-D does not harm grass crops like wheat — what explains this?",
     ["यह पानी में घुलता नहीं", "यह चयनात्मक (selective) है — चौड़ी-पत्ती खरपतवारों की वृद्धि-हार्मोन तंत्र को भंग करता है, संकरी-पत्ती घासफसलें सुरक्षित रहती हैं", "यह केवल रंग बदलता है", "यह मिट्टी में तुरंत नष्ट हो जाता है"],
     ["It does not dissolve in water", "It is selective — it breaks the growth-hormone system of broad-leaved weeds, while narrow-leaved grass crops stay safe", "It only changes colour", "It is destroyed in soil at once"],
     1,
     "चयनात्मक विषैलापन ही खरपतवारनाशी-प्रौद्योगिकी का आधार है — लक्ष्य-पौधे की केवल शत्रु प्रभावित।",
     "Selective toxicity is the very basis of weedicide technology — only the target's enemy is hit."),

    ("crop-production", "hard",
     "वायुरोधी साइलो में भी अनाज को निर्धारित नमी-स्तर तक सुखाकर ही रखा जाता है — क्यों?",
     "Even in airtight silos, grain is dried to a set moisture level before storing — why?",
     ["वजन कम करने के लिए", "बीस/अनाज की अपनी श्वसन-गतिविधि और बची नमी अंदर ही गर्मी-फफूंद पैदा कर सकती है — सूखा दाना निष्क्रिय-सुरक्षित रहता है", "गिनती में सुविधा", "रंग की चमक"],
     ["To reduce weight", "The grain's own respiration plus leftover moisture can breed heat-fungus inside — dry grain stays inert-safe", "Ease of counting", "Colour shine"],
     1,
     "बंद टंकी में भी जीवित दाना साँस लेता है — नमी+श्वसन की आंतरिक गर्मी ही भंडारण का छिपा शत्रु।",
     "Even in a sealed tank a living grain breathes — the internal heat of moisture+respiration is storage's hidden enemy."),

    ("crop-production", "hard",
     "दुधारू पशुओं के भोजन में चारा (roughage) और दाना-मिश्रण (concentrate) दोनों क्यों दिए जाते हैं?",
     "Why are both roughage and concentrate given in the feed of milch animals?",
     ["स्वाद बदलने के लिए", "चारा भरपेट-रेशा-पाचन देता है, दाना सघन ऊर्जा-प्रोटीन देता है — दूध-उत्पादन हेतु दोनों आवश्यक", "एक ही चीज़ के दो नाम", "केवल सस्ते भोजन के लिए"],
     ["To vary the taste", "Roughage gives bulk-fibre-digestion, concentrate gives dense energy-protein — both are needed for milk yield", "Two names of the same thing", "Just for cheap feed"],
     1,
     "दूध बनाने की फैक्ट्री को मात्रा (चारा) और गुणवत्ता (दाना) दोनों कच्चे माल की चाहिए।",
     "The milk-making factory needs both quantity (roughage) and quality (concentrate) of raw material."),
]
