# -*- coding: utf-8 -*-
"""B04 'Plant Life & Plant Functions' — Part 3 data (20 items).
Topic: photosynthesis-experiments (E5/M13/H2).
Tuple: (topic, difficulty, q_hi, q_en, options_hi[4], options_en[4], correct_idx, exp_hi, exp_en)
DENY: B08 polythene-bag & cobalt-chloride transpiration experiments; B07 germinating-seed
lime-water & thermos experiments (different facts, different setups).
"""

PART3 = [
    ("photosynthesis-experiments", "easy",
     "पत्ती में स्टार्च की जाँच किस विलयन से होती है और धनात्मक परिणाम का रंग क्या होता है?",
     "Which solution tests a leaf for starch, and what colour marks a positive result?",
     ["बेंग़ाल-लाल से — गुलाबी", "आयोडीन विलयन से — नीला-काला", "लिटमस से — लाल", "फेनोल्थैलीन से — गुलाबी"],
     ["Bengal red — pink", "Iodine solution — blue-black", "Litmus — red", "Phenolphthalein — pink"],
     1,
     "आयोडीन स्टार्च के साथ विशिष्ट नीला-काला संकुल बनाता है — यही स्टार्च-उपस्थिति का प्रमाण है।",
     "Iodine forms a specific blue-black complex with starch — proof of starch's presence."),

    ("photosynthesis-experiments", "easy",
     "प्रयोग से पहले पौधे को लगातार दो-तीन दिन अंधेरे में क्यों रखा जाता है (विरंजन/destarching)?",
     "Why is the plant kept in darkness for two-three days before the experiment (destarching)?",
     ["पौधे को आराम देने के लिए", "ताकि पत्तियों का पहले से जमा स्टार्च खर्च हो जाए — जो स्टार्च बाद में मिले वह निश्चित रूप से प्रयोग की स्थितियों में बना हो", "पत्तियाँ मुलायम हो जाएँ", "कीट भाग जाएँ"],
     ["To rest the plant", "So the leaf's stored starch is spent — any starch found later must have formed under the experiment's conditions", "Leaves become soft", "Insects flee"],
     1,
     "पुराना स्टार्च हटाना = कैनवास साफ करना; अब हर नीला-काला दाग प्रयोग की ही देन होगा।",
     "Removing old starch = wiping the canvas clean; now every blue-black stain is the experiment's own doing."),

    ("photosynthesis-experiments", "easy",
     "पत्ती को इथाइल एल्कोहल में उबालने से क्या होता है?",
     "What happens when the leaf is boiled in ethyl alcohol?",
     ["पत्ती नीली हो जाती है", "पत्ती का हरा रंग (क्लोरोफिल) निकलकर पत्ती रंगहीन-सफेद हो जाती है", "स्टार्च नष्ट हो जाता है", "पत्ती पक जाती है"],
     ["The leaf turns blue", "The leaf's green colour (chlorophyll) leaves and the leaf turns colourless-white", "Starch is destroyed", "The leaf cooks"],
     1,
     "रंगहीन पत्ती पर ही आयोडीन का नीला-काला रंग साफ दिखता है — हरी पत्ती में छिप जाता।",
     "Only on a colourless leaf does iodine's blue-black show clearly — on a green leaf it hides."),

    ("photosynthesis-experiments", "easy",
     "पानी में डुबाई हाइड्रिला (जल-पौधा) टिंकी में धूप में रखने पर जो छोटे बुलबुले चिपकते रहते हैं वे किस गैस के होते हैं?",
     "The tiny bubbles that keep sticking to a submerged Hydrilla (water plant) kept in a sunlit tank are of which gas?",
     ["CO₂", "ऑक्सीजन", "नाइट्रोजन", "हाइड्रोजन"],
     ["CO₂", "Oxygen", "Nitrogen", "Hydrogen"],
     1,
     "धूप में प्रकाश-संश्लेषण चलता है और ऑक्सीजन बुलबुलों के रूप में मुक्त होती है।",
     "In sunlight photosynthesis runs and oxygen is released as bubbles."),

    ("photosynthesis-experiments", "easy",
     "एक विरंजित (डार्क-डिस्टार्च्ड) पौधे की पत्ती को घंटों धूप में रखकर आयोडीन से जाँचने पर नीला-काला रंग आया — इससे क्या सिद्ध हुआ?",
     "A destarched leaf kept in sun for hours turns blue-black with iodine — what does this prove?",
     ["पत्ती में जल था", "प्रकाश की उपस्थिति में पत्ती ने नया स्टार्च (अर्थात् भोजन) बनाया", "पत्ती मर गई", "आयोडीन खराब था"],
     ["The leaf had water", "In the presence of light the leaf made fresh starch (i.e., food)", "The leaf died", "The iodine was spoiled"],
     1,
     "पहले सारा पुराना स्टार्च खत्म था — अब जो मिला वह धूप में निर्मित नया भोजन ही है।",
     "All old starch was gone — what appeared now must be newly made sun-food."),

    ("photosynthesis-experiments", "medium",
     "प्रयोग में पत्ती को पहले पानी में उबाला जाता है — इस पहले चरण का उद्देश्य क्या है?",
     "The leaf is first boiled in water in the experiment — what is the purpose of this first step?",
     ["स्टार्च निकालना", "कोशिकाओं को मारकर (kill) और मुलायम करके अगले रसायनों के लिए भीतर तक प्रवेश द्वार खोलना", "रंग गाढ़ा करना", "पत्ती को बचाना"],
     ["To extract starch", "To kill and soften the cells, opening the way for the next chemicals to reach inside", "To deepen the colour", "To preserve the leaf"],
     1,
     "गरम पानी कोशिका-झिल्ली की जीवंतता रोककर मार्ग खोलता है — नरम पत्ती में एल्कोहल/आयोडीन अच्छे से घुलपटते हैं।",
     "Hot water stops membrane life and opens the way — alcohol/iodine soak better into a soft leaf."),

    ("photosynthesis-experiments", "medium",
     "एल्कोहल में पत्ती उबालते समय सीधी लौ पर बर्तन क्यों नहीं रखा जाता?",
     "While boiling the leaf in alcohol, why is the vessel not placed directly on the flame?",
     ["पत्ती जल जाती है", "एल्कोहल अत्यंत ज्वलनशील है — जल-स्नान (water bath) में उबालकर ही सुरक्षित गर्म किया जाता है", "रंग उड़ जाता है", "काँच टूट जाता है"],
     ["The leaf burns", "Alcohol is highly inflammable — it is heated safely in a water bath", "The colour evaporates", "The glass cracks"],
     1,
     "एल्कोहल की भाप आग पकड़ लेती है — जल-स्नान अप्रत्यक्ष गर्मी का सुरक्षा-कवच है।",
     "Alcohol vapour catches fire — the water bath is the safety-shield of indirect heating."),

    ("photosynthesis-experiments", "medium",
     "पत्ती-परीक्षण के सही क्रम को चुनिए।",
     "Choose the correct order of the leaf-testing steps.",
     ["आयोडीन → एल्कोहल → पानी उबाल", "पानी में उबाल → एल्कोहल में विरंजन → ठंडे जल में धोवन → आयोडीन बूँदें", "एल्कोहल → सीधे आयोडीन", "धोना → सुखाना → जलाना"],
     ["Iodine → alcohol → boiling water", "Boil in water → decolourise in alcohol → rinse in cold water → drops of iodine", "Alcohol → straight to iodine", "Wash → dry → burn"],
     1,
     "मृदुकरण → विरंजन → पुनर्जलीकरण → विलयन-जाँच — यही क्रम साफ परिणाम देता है।",
     "Soften → decolourise → rehydrate → test — this order alone gives a clean result."),

    ("photosynthesis-experiments", "medium",
     "एल्कोहल से निकाली पत्ती को आयोडीन से पहले ठंडे पानी में क्यों धोया जाता है?",
     "Why is the alcohol-treated leaf washed in cold water before iodine?",
     ["पत्ती ठंडी हो जाए", "पत्ती पर बचा एल्कोहल निकल जाए — वरना आयोडीन का रंग-परिवर्तन अवरुद्ध/अस्पष्ट हो जाता है और भंगुर पत्ती फैलती है", "स्टार्च बढ़े", "क्लोरोफिल लौटे"],
     ["So the leaf cools", "To wash off leftover alcohol — else iodine's colour change is blocked/unclear, and the brittle leaf also spreads out", "So starch grows", "So chlorophyll returns"],
     1,
     "एल्कोहल-अवशेष आयोडीन से टकराता है; ठंडा जल पत्ती को पुनः फैलाकर परीक्षण-योग्य बनाता है।",
     "Alcohol residue clashes with iodine; cold water re-spreads the leaf into a testable state."),

    ("photosynthesis-experiments", "medium",
     "काले कागज़/पन्नी से आधी ढकी पत्ती (विरंजित पौधे पर) धूप में रखी जाती है — आयोडीन परीक्षण में क्या परिणाम आता है?",
     "A leaf half-covered with black paper/foil (on a destarched plant) is kept in sun — what is the iodine result?",
     ["पूरी पत्ती नीली-काली", "केवल खुला (अनावृत) आधा भाग नीला-काला; ढका भाग भूरा-पीला रहता है", "केवल ढका भाग नीला", "कहीं नीला नहीं"],
     ["The whole leaf blue-black", "Only the exposed half turns blue-black; the covered half stays brown-yellow", "Only the covered half blue", "No blue anywhere"],
     1,
     "जहाँ प्रकाश पहुँचा वहीं स्टार्च बना — ढके भाग का ऋणात्मक परिणाम प्रकाश-आवश्यकता का प्रमाण है।",
     "Starch formed only where light reached — the covered half's negative result proves light's necessity."),

    ("photosynthesis-experiments", "medium",
     "आधी-ढकी पत्ती वाले प्रयोग की दृष्टि से एक ही पत्ती का उपयोग करना किस रूप में उचित अभिकल्पना (fair design) है?",
     "Using the same leaf for the half-covered experiment is a fair design in what sense?",
     ["पत्ती बचती है", "एक ही पत्ती में नियंत्रित भाग (ढका) और परीक्षित भाग (खुला) — प्रकाश के अतिरिक्त शेष सभी शर्तें (पौधा, आयु, CO₂, जल) स्वतः समान रहती हैं", "रंग गहरा आता है", "समय कम लगता है"],
     ["A leaf is saved", "In one leaf the covered part is the control and the open part the test — every condition except light (plant, age, CO₂, water) stays equal by itself", "The colour deepens", "It takes less time"],
     1,
     "एक-पत्ती-दो-भाग अभिकल्पना में केवल प्रकाश ही चर बदलता है — निष्कर्ष निर्विवाद होता है।",
     "In the one-leaf-two-parts design only light varies — the conclusion becomes unarguable."),

    ("photosynthesis-experiments", "medium",
     "बेलनाकार काँच-घड़ी में KOH (पोटैशियम हाइड्रॉक्साइड) रखने वाले प्रयोग में KOH का कार्य क्या है?",
     "In the bell-jar experiment with KOH (potassium hydroxide) kept inside, what is KOH's role?",
     ["ऑक्सीजन छोड़ना", "वायु की CO₂ सोख लेना — ताकि पौधे के पास कार्बन डाइऑक्साइड न बचे", "प्रकाश देना", "जल देना"],
     ["To release oxygen", "To absorb the air's CO₂ — so no carbon dioxide remains available to the plant", "To give light", "To give water"],
     1,
     "KOH CO₂-शोषक है — उसकी उपस्थिति वाले घड़ी-पौधे में स्टार्च नहीं बनता, अनुपस्थिति वाले (नियंत्रण) में बनता है।",
     "KOH is a CO₂-absorber — the jar-plant with it makes no starch, the control without it does."),

    ("photosynthesis-experiments", "medium",
     "KOH-युक्त घड़ी में रखा विरंजित पौधा धूप में रहने पर भी आयोडीन-ऋणात्मक रहा — निष्कर्ष क्या है?",
     "A destarched plant in a KOH-containing bell jar stays iodine-negative despite sunlight — what is the conclusion?",
     ["प्रकाश की जरूरत नहीं", "प्रकाश और क्लोरोफिल के बावजूद CO₂ अनुपलब्ध रहने पर स्टार्च नहीं बना — अतः प्रकाश-संश्लेषण हेतु CO₂ आवश्यक है", "KOH ने स्टार्च खा लिया", "पौधा बीमार था"],
     ["Light is unnecessary", "Despite light and chlorophyll, no starch formed because CO₂ was unavailable — hence CO₂ is essential for photosynthesis", "KOH ate the starch", "The plant was sick"],
     1,
     "तीन शर्तों में से एक (CO₂) हटाते ही भोजन-निर्माण रुका — अनुपस्थित-चर विधि से कारक-प्रमाण।",
     "Removing just one of the three conditions (CO₂) stopped food-making — proof of the factor by the missing-variable method."),

    ("photosynthesis-experiments", "medium",
     "चितकबरी (variegated) पत्ती — जिसमें कुछ भाग हरे और कुछ सफेद — वाले प्रयोग का परिणाम क्या होता है?",
     "What is the result of the variegated-leaf experiment — a leaf with green and white patches?",
     ["पूरी पत्ती नीली-काली", "केवल हरे (क्लोरोफिल-युक्त) भाग नीले-काले होते हैं; सफेद भाग ऋणात्मक", "केवल सफेद भाग नीले", "पत्ती रंगहीन हो गई"],
     ["The whole leaf blue-black", "Only the green (chlorophyll-bearing) patches turn blue-black; the white patches stay negative", "Only the white patches blue", "The leaf turns colourless"],
     1,
     "एक ही पत्ती में प्रकाश-CO₂ समान, केवल क्लोरोफिल वाले भाग ने भोजन बनाया — क्लोरोफिल-आवश्यकता सिद्ध।",
     "Same leaf, same light-CO₂ — only the chlorophyll patches made food — chlorophyll's necessity proven."),

    ("photosynthesis-experiments", "medium",
     "जल-पौधे के बुलबुल-प्रयोग में प्रकाश-स्रोत को पास लाने पर बुलबुलों की दर बढ़ जाती है — इससे क्या संबंध सिद्ध होता है?",
     "In the water-plant bubble experiment, bringing the light source closer raises the bubble rate — what relation does this prove?",
     ["बुलबुल गर्मी से बनते हैं", "प्रकाश-संश्लेषण की दर प्रकाश की तीव्रता बढ़ाने के साथ बढ़ती है", "पानी उबलने लगता है", "पौधा तैरता है"],
     ["Bubbles come from heat", "The rate of photosynthesis rises with increasing light intensity", "The water boils", "The plant floats"],
     1,
     "बुलबुल = ऑक्सीजन = दर-सूचक; प्रकाश-तीव्रता और दर समानुपाती निकले।",
     "Bubbles = oxygen = rate-indicator; light intensity and rate came out proportional."),

    ("photosynthesis-experiments", "medium",
     "बुलबुल-प्रयोग में 'प्रति मिनट बुलबुलों की संख्या' किस कहलाती है?",
     "In the bubble experiment, 'bubbles per minute' is called what?",
     ["नियंत्रित चर", "आश्रित (मापी गई) चर — प्रकाश-तीव्रता जैसे स्वतंत्र चर के बदलने पर इसका मान बदलता है", "स्थिरांक", "त्रुटि"],
     ["Controlled variable", "The dependent (measured) variable — it changes as an independent variable like light intensity is altered", "A constant", "An error"],
     1,
     "जो चर अपने आप नहीं बदलता, किसी कारक के प्रभाव से बदलता दिखे, वही आश्रित चर है।",
     "The quantity that shifts not by itself but under a factor's influence is the dependent variable."),

    ("photosynthesis-experiments", "medium",
     "यदि प्रयोग से पहले पौधे को अंधेरे में रखकर विरंजित (destarch) न किया जाए तो परिणाम कैसे भ्रमित होंगे?",
     "If the plant is not destarched before the experiment, how will the results get confused?",
     ["कोई फर्क नहीं पड़ता", "ढके/अंधेरे भाग में भी पुराना जमा स्टार्च नीला-काला दिखा देगा — लगेगा कि प्रकाश बिना भी भोजन बना", "पत्ती गिर जाएगी", "आयोडीन काम नहीं करेगा"],
     ["No difference at all", "Old stored starch will turn even the covered/dark part blue-black — it will seem food formed without light", "The leaf drops", "Iodine stops working"],
     1,
     "बिना रिक्त-कैनवास के पुराना लेखा ही नया दिखेगा — नियंत्रण टूट जाता है।",
     "Without a blank canvas the old ledger shows as new — the control breaks."),

    ("photosynthesis-experiments", "medium",
     "हाइड्रिला-टिंकी से एकत्र गैस-बुलबुलों पर जलती हुई अगरबत्ती ले जाने पर वह चमक उठती है — यह किस गैस की पुष्टि है?",
     "A glowing incense stick bursts into flame when brought near the gas bubbles collected from a Hydrilla tank — confirmation of which gas?",
     ["कार्बन डाइऑक्साइड", "ऑक्सीजन — दहन-सहायक गैस", "नाइट्रोजन", "मीथेन"],
     ["Carbon dioxide", "Oxygen — the combustion-supporting gas", "Nitrogen", "Methane"],
     1,
     "ऑक्सीजन ही बुझती लौ को पुनर्जीवित करती है — प्रकाश-संश्लेषण-उत्पाद की पहचान परीक्षा।",
     "Only oxygen rekindles a dying flame — the identity test of the photosynthesis product."),

    ("photosynthesis-experiments", "hard",
     "CO₂-आवश्यकता सिद्ध करने हेतु सही अभिकल्पना कौन-सी है?",
     "Which is the correct design to prove the necessity of CO₂?",
     ["दो अलग-अलग जाति के पौधे लें", "दोनों विरंजित पौधे धूप में — एक खुली हवा में (नियंत्रण), दूसरा KOH-युक्त बंद घंटी-जार में (परीक्षण); केवल CO₂ की उपलब्धता बदले", "एक पौधा अंधेरे में, दूसरा धूप में", "एक ही पौधे की दो पत्तियों पर आयोडीन और लिटमस डालें"],
     ["Take two plants of different species", "Both plants destarched and in sun — one in open air (control), the other in a closed bell jar with KOH (test); only CO₂ availability differs", "One plant in dark, another in sun", "Put iodine on one leaf and litmus on another of the same plant"],
     1,
     "एक चर-बदल सिद्धांत: सब समान, केवल CO₂ हटाई — घंटी-भीतर ऋणात्मक आने पर कारक निर्विवाद सिद्ध।",
     "One-variable-change principle: all same, only CO₂ removed — a negative inside the jar proves the factor beyond doubt."),

    ("photosynthesis-experiments", "hard",
     "चितकबरी-पत्ती प्रयोग में सफेद भाग 'built-in नियंत्रण' (control) क्यों कहलाता है?",
     "In the variegated-leaf experiment, why is the white patch called a 'built-in control'?",
     ["वह सुंदर लगता है", "उसी पत्ती के सफेद भाग पर प्रकाश-CO₂ समान उपलब्ध थे, केवल क्लोरोफिल नहीं — उसका ऋणात्मक परिणाम बताता है कि अंतर केवल क्लोरोफिल का है", "वहाँ जल ज्यादा था", "वह कृत्रिम रूप से रंगा गया है"],
     ["It looks pretty", "The white patch of the same leaf had equal light-CO₂, only no chlorophyll — its negative result shows the difference is due to chlorophyll alone", "It had more water", "It is artificially dyed"],
     1,
     "प्रकृति का अपना प्रतिरूप-प्रयोग: एक ही पत्ती में '+' और '−' भाग — कारक का पृथक्करण स्वतः।",
     "Nature's own model experiment: '+' and '−' parts in one leaf — the factor isolated by itself."),
]
