# -*- coding: utf-8 -*-
"""B05 'Animal Life & Body Functions' — Part 2 data (70 items).
Order: organization-overview (25), movement (25), sense-organs (20).
Tuple: (topic, difficulty, q_hi, q_en, options_hi[4], options_en[4], correct_idx, exp_hi, exp_en)
DENY reminders: B02 division-of-labour, skin-largest-organ, bone-as-organ, stomach-organ-system,
stomach-tissue-kinds, plant-animal-tissue-difference, joint-def & joint-types, biceps/triceps states,
antagonistic-partner-state, muscles-pull-bones, tendon-force, ligament-connects/flexibility/class,
combined-bone-joint-muscle, flight-muscles-keel, bird-hollow-bones, muscle-type-cell questions;
B01 movement-by-contraction, muscle/tissue-type lists, neuron-unit-tissue-framing; B03 fins,
blubber, adaptation-framings; B07 muscle-cramps-lactic, diaphragm; B06 tongue-taste-buds, tongue-job;
B02 skin-outer-tissue, nose-hairs (B07), excretion-def (B03).
"""

PART2 = [
    # ---------------- organization-overview (25: E9/M13/H3) ----------------
    ("organization-overview", "easy",
     "बहुकोशिकीय जीव के शरीर-संगठन की सीढ़ी का सही क्रम क्या है?",
     "What is the correct order of the body-organisation ladder in a multicellular organism?",
     ["अंग → कोशिका → तंत्र → ऊतक", "कोशिका → ऊतक → अंग → अंग-तंत्र", "तंत्र → अंग → ऊतक → कोशिका", "ऊतक → कोशिका → अंग → तंत्र"],
     ["Organ → cell → system → tissue", "Cell → tissue → organ → organ-system", "System → organ → tissue → cell", "Tissue → cell → organ → system"],
     1,
     "ईंट (कोशिका) → दीवार (ऊतक) → कमरा (अंग) → पूरा भवन-खंड (तंत्र) — निर्माण की सीढ़ी नीचे से ऊपर।",
     "Brick (cell) → wall (tissue) → room (organ) → whole building-block (system) — the building ladder from bottom up."),

    ("organization-overview", "easy",
     "संगठन-सीढ़ी में कोशिका और ऊतक के बाद तीसरे स्तर पर कौन-सी इकाई आती है?",
     "Which unit comes at the third level of the organisation ladder, after cell and tissue?",
     ["अंग-तंत्र", "अंग (organ) — विभिन्न ऊतकों से बनी कार्य-इकाई जैसे गुर्दा, आँख", "जीवाणु", "अणु"],
     ["Organ system", "The organ — a work-unit built of different tissues, like the kidney or eye", "Bacterium", "Molecule"],
     1,
     "कोशिका → ऊतक → अंग — तीसरी सीढ़ी पर विभिन्न ऊतकों की मिलीजुली कार्य-इकाई बैठती है।",
     "Cell → tissue → organ — on the third step sits the joint work-unit of different tissues."),

    ("organization-overview", "easy",
     "एक ही व्यापक कार्य संभालने के लिए जुटे हुए अनेक अंगों के समूह-स्तर की इकाई कौन-सी है?",
     "Which is the unit-level of many organs joined to manage one broad function together?",
     ["ऊतक-स्तर की इकाई", "अंग-तंत्र (organ system) — जैसे गुर्दे-मूत्रवाहिनी-मूत्राशय का उत्सर्जी दल", "कोशिका-झिल्ली", "केवल एक अंग"],
     ["A tissue-level unit", "The organ system — like the excretory squad of kidneys-ureters-bladder", "The cell membrane", "Only a single organ"],
     1,
     "कई अंग जब एक महाकार्य के लिए दल बनाते हैं तो संगठन-सीढ़ी का वह चौथा स्तर — अंग-तंत्र — बनता है।",
     "When many organs form a squad for one mega-task, that fourth level of the ladder — the organ system — arises."),

    ("organization-overview", "easy",
     "तंत्रिका तंत्र में कौन-कौन-से मुख्य अंग सम्मिलित हैं?",
     "Which main organs are included in the nervous system?",
     ["मस्तिष्क, मेरुरज्जु और तंत्रिकाएँ", "हृदय और रुधिर", "पेट और आँत", "गुर्दे और मूत्राशय"],
     ["The brain, the spinal cord and the nerves", "The heart and blood", "The stomach and intestine", "The kidneys and bladder"],
     0,
     "केंद्र (मस्तिष्क-मेरुरज्जु) + तार-जाल (नसें) = तंत्रिका तंत्र की पूरी टोली।",
     "The centres (brain-spinal cord) + the wire-network (nerves) = the nervous system's full team."),

    ("organization-overview", "easy",
     "उत्सर्जी तंत्र के सदस्य-अंग कौन-से हैं?",
     "Which are the member-organs of the excretory system?",
     ["फेफड़े और श्वासनली", "गुर्दे, मूत्रवाहिनी, मूत्राशय, मूत्रमार्ग", "आँख, कान, नाक", "भोजन-नली और पेट"],
     ["The lungs and trachea", "Kidneys, ureters, urinary bladder, urethra", "Eye, ear, nose", "The food-pipe and stomach"],
     1,
     "जो अंग मिलकर अपशिष्ट-निकासी चलाते हैं — वही उत्सर्जी तंत्र की सूची में आते हैं।",
     "The organs that together run waste-removal — those alone figure on the excretory system's list."),

    ("organization-overview", "easy",
     "संगठन-सीढ़ी में आँख किस स्तर पर आती है?",
     "At which level of the organisation ladder does the eye fall?",
     ["कोशिका-स्तर", "ऊतक-स्तर", "अंग-स्तर — कई ऊतकों से बनी दृष्टि-इकाई", "तंत्र-स्तर"],
     ["Cell level", "Tissue level", "Organ level — a sight-unit built of many tissues", "System level"],
     2,
     "आँख अकेली एक अंग है; वहीं आँख+तंत्रिका-मार्ग+मस्तिष्क-केंद्र मिलकर देखने का तंत्र बनाते हैं।",
     "The eye alone is an organ; eye + nerve-path + brain-centre together form the system of seeing."),

    ("organization-overview", "easy",
     "न्यूरॉन (तंत्रिका कोशिकाएँ) मिलकर कौन-सा ऊतक बनाती हैं?",
     "Neurons (nerve cells) together form which tissue?",
     ["पेशीय ऊतक", "तंत्रिका ऊतक", "उपकला ऊतक", "अस्थि ऊतक"],
     ["Muscular tissue", "Nervous tissue", "Epithelial tissue", "Bone tissue"],
     1,
     "एक-एक न्यूरॉन कोशिका करोड़ों की संख्या में जुड़कर शरीर-व्यापी तंत्रिका-ऊतक बुनते हैं।",
     "Single neuron cells, joined in crores, weave the body-wide nervous tissue."),

    ("organization-overview", "easy",
     "शरीर की संगठन-सीढ़ी में सबसे छोटी इकाई कौन-सी है?",
     "Which is the smallest unit in the body's organisation ladder?",
     ["अंग-तंत्र", "अंग", "ऊतक", "कोशिका"],
     ["Organ system", "Organ", "Tissue", "Cell"],
     3,
     "कोशिका ही जीवन की सबसे छोटी ईंट है — ऊपर की पूरी इमारत इसी से उठती है।",
     "The cell is the smallest brick of life — the whole edifice above rises from it."),

    ("organization-overview", "easy",
     "निम्न में से कौन-सा एक अंग-तंत्र का सही उदाहरण-युग्म है?",
     "Which of the following is a correct example-pair of an organ and its system?",
     ["गुर्दा — उत्सर्जी तंत्र", "गुर्दा — पाचन तंत्र", "मस्तिष्क — उत्सर्जी तंत्र", "आँख — उत्सर्जी तंत्र"],
     ["Kidney — excretory system", "Kidney — digestive system", "Brain — excretory system", "Eye — excretory system"],
     0,
     "गुर्दे का अपना तंत्र उत्सर्जी है — जिस काम का अंग, उसी काम का तंत्र।",
     "The kidney's own system is excretory — the organ of a work belongs to that work's system."),

    ("organization-overview", "medium",
     "संगठन-सीढ़ी पर चढ़ते हुए कार्य की प्रकृति कैसी होती जाती है?",
     "How does the nature of the work change as one climbs the organisation ladder?",
     ["सरल से जटिल होती जाती — कोशिका छोटे-छोटे काम, ऊतक-अंग-तंत्र क्रमशः बड़े-व्यापक काम", "जटिल से सरल", "कोई नियम नहीं", "सब समान"],
     ["Turns simple-to-complex — cells do tiny jobs, tissue-organ-system progressively bigger-broader works", "Complex to simple", "No rule", "All equal"],
     0,
     "जितना ऊँचा स्तर, उतना व्यापक कार्य — नाली-कोशिका से लेकर पूरे मूत्र-तंत्र तक की गाथा।",
     "The higher the level, the broader the task — the saga from a duct-cell to the whole urinary system."),

    ("organization-overview", "medium",
     "एक ऊतक की तुलना में एक अंग किन कार्यों को संभाल पाता है?",
     "Compared with a tissue, what kinds of tasks can an organ handle?",
     ["केवल एक ही काम", "कई प्रकार के सहायक कार्य एक साथ — विभिन्न ऊतकों के विशेषज्ञों की संयुक्त टोली बनने से", "कोई काम नहीं", "केवल रुधिर बनाना"],
     ["Only a single job", "Several supporting tasks at once — because specialists of different tissues form a joint team", "No work", "Only making blood"],
     1,
     "गुर्दे में छलनी-ऊतक, नली-ऊतक, रुधिर-नली-ऊतक, तंत्रिका-नियंत्रण — सबकी मिलीजुली पेशकश।",
     "In a kidney: sieve-tissue, duct-tissue, vessel-tissue, nerve-control — a pooled offering of all."),

    ("organization-overview", "medium",
     "ऊतक और अंग में मूल अंतर किस आधार पर सबसे साफ होता है?",
     "On what basis is the basic difference between tissue and organ clearest?",
     ["रंग के आधार पर", "ऊतक = समान कोशिकाओं का एक-काम समूह; अंग = विभिन्न ऊतकों का बहु-पेशेवर संयुक्त ढाँचा", "आकार के आधार पर ही", "दोनों एक ही हैं"],
     ["On colour", "Tissue = a one-job group of similar cells; organ = a multi-professional joint frame of different tissues", "Only on size", "Both are the same"],
     1,
     "बनावट-भेद ही आधार है — समान कोशिकाओं की टुकड़ी बनाम भिन्न टुकड़ियों की मंडली।",
     "The make-up difference is the basis — a squad of similar cells versus an assembly of different squads."),

    ("organization-overview", "medium",
     "कोशिकाओं का समूह बनाकर ऊतक बनाने से जीव को क्या फायदा है?",
     "What benefit does an organism gain by grouping cells into tissues?",
     ["शरीर का रंग बदलता है", "एक जैसे काम वाली कोशिकाएँ एक जगह जुटकर उस काम को बड़े पैमाने और निरंतर रूप से कर पाती हैं", "वजन घटता है", "कोई फायदा नहीं"],
     ["The body's colour changes", "Cells of the same job, gathered at one place, can do that job on a large scale and continuously", "Weight falls", "No benefit"],
     1,
     "अकेली कोशिका की पहुँच सीमित — जुड़ी कोशिकाओं की टोली वही काम असीमित बल से करती है।",
     "A lone cell's reach is limited — a joined team does the same job with unbounded force."),

    ("organization-overview", "medium",
     "पेशियाँ, अस्थियाँ और संधियाँ मिलकर मुख्यतः किस शारीरिक कार्य की सेवा करती हैं?",
     "Muscles, bones and joints together mainly serve which bodily function?",
     ["पाचन", "गति और स्थिरता (movement & support)", "उत्सर्जन", "दृष्टि"],
     ["Digestion", "Movement and support", "Excretion", "Vision"],
     1,
     "तीनों साथी मिलकर शरीर का चलने-ढुलकने-संभलने का तंत्र बनाते हैं — गति-सेवा की तिकड़ी।",
     "The three mates together form the body's moving-steadying system — the trio in motion's service."),

    ("organization-overview", "medium",
     "मस्तिष्क से गुर्दे तक और गुर्दे से मस्तिष्क तक लगातार संदेश-लेन-देन का उदाहरण किस संगठन-सिद्धांत को दर्शाता है?",
     "The constant message-exchange between brain and kidney illustrates which principle of organisation?",
     ["अंग अकेले काम करते हैं", "अंग-तंत्र परस्पर निर्भर और संबद्ध रहते हैं — संचार-तंत्र उत्सर्जी-तंत्र की गतिविधि की सूचना लेता-देता रहता है", "हर तंत्र बंद रहता है", "कोशिकाएँ तंत्र नहीं पहचानतीं"],
     ["Organs work alone", "Organ-systems stay interdependent and linked — the nervous system keeps taking and giving news of the excretory system's activity", "Every system stays shut", "Cells do not recognise systems"],
     1,
     "शरीर एक जुड़ा उद्यम है — मूत्र-मात्रा का निर्णय भी मस्तिष्क-गुर्दा संवाद से होता है।",
     "The body is one connected enterprise — even the decision on urine-amount comes from brain-kidney dialogue."),

    ("organization-overview", "medium",
     "संगठन-सीढ़ी के स्तरों में से कौन-सा युग्म 'से बना है' संबंध में सही है?",
     "Among the levels of the organisation ladder, which pair is correct in the 'is made of' relation?",
     ["तंत्र कोशिकाओं से सीधे बना है", "अंग ऊतकों से बना है; ऊतक कोशिकाओं से", "कोशिका अंगों से बनी है", "ऊतक तंत्रों से बना है"],
     ["A system is made directly of cells", "An organ is made of tissues; a tissue of cells", "A cell is made of organs", "A tissue is made of systems"],
     1,
     "सीढ़ी के हर डंडे अपने नीचे वाले से ही बनता है — कोई स्तर कदम छोड़कर नहीं बनता।",
     "Each rung of the ladder is built from the one below it — no level forms skipping a step."),

    ("organization-overview", "medium",
     "निम्न में से कौन-सा तंत्र-अंग संबंध सही नहीं है?",
     "Which of the following organ-system relations is NOT correct?",
     ["मस्तिष्क — तंत्रिका तंत्र", "गुर्दा — उत्सर्जी तंत्र", "पेशी-अस्थि-संधि — गति-तंत्र", "गुर्दा — तंत्रिका तंत्र का मुख्य अंग"],
     ["Brain — nervous system", "Kidney — excretory system", "Muscle-bone-joint — movement system", "Kidney — the chief organ of the nervous system"],
     3,
     "गुर्दा उत्सर्जी तंत्र का मुख्य अंग है — तंत्रिका तंत्र का नहीं; तंत्रिका तंत्र का मुखिया मस्तिष्क है।",
     "The kidney is the excretory system's chief organ — not the nervous system's; the nervous system's head is the brain."),

    ("organization-overview", "medium",
     "एक ऊतक में कोशिकाएँ किस प्रकार की होती हैं?",
     "What kind of cells does a tissue contain?",
     ["बिल्कुल भिन्न-भिन्न काम वाली", "समान संरचना और समान कार्य वाली — एक ही विशेषज्ञता की साथी", "केवल रुधिर कोशिकाएँ", "केवल तंत्रिका कोशिकाएँ"],
     ["Of entirely different jobs", "Of similar structure and similar function — mates of one specialisation", "Only blood cells", "Only nerve cells"],
     1,
     "एक ऊतक एक विशेषज्ञ-दल है — पेशी-ऊत की सब पेशी, तंत्रिका-ऊत की सब तंत्रिका कोशिकाएँ।",
     "A tissue is a specialist squad — all muscle in muscle tissue, all nerve cells in nervous tissue."),

    ("organization-overview", "medium",
     "वृद्धि और जीवन-परिचालन में 'कोशिका-से-तंत्र' संगठन क्यों जीव की सफलता का आधार है?",
     "Why is the 'cell-to-system' organisation the basis of an organism's success in growth and life-management?",
     ["इससे शरीर सुंदर दिखता है", "इससे एक साथ कई जटिल कार्य व्यवस्थित रूप से चल सकते हैं — हर कार्य की अलहदा विशेषज्य टोली बनती है", "इससे भोजन स्वादिष्ट लगता है", "इससे नींद अच्छी आती है"],
     ["The body looks beautiful", "It lets many complex tasks run in an ordered way at once — a separate specialist team forms for every task", "Food tastes better", "Sleep improves"],
     1,
     "संगठित शरीर ही बड़ा-जटिल जीवन संभाल पाता है — असंगठित कोशिका-भीड़ बड़े जीव नहीं बन पाती।",
     "Only an organised body can manage a big-complex life — an unorganised cell-crowd cannot become large beings."),

    ("organization-overview", "medium",
     "गुर्दा-तंत्र और संचार-तंत्र का परस्पर-संबंध किस अवयव से स्थापित होता है?",
     "Through which link is the relation between the excretory and circulatory systems established?",
     ["जीभ से", "रुधिर-वाहिकाओं से — गुर्दे रुधिर ही छानते हैं और शुद्ध रुधिर वाहिकाओं से ही लौटता है", "कान से", "आँख से"],
     ["Through the tongue", "Through blood vessels — the kidneys filter blood itself and clean blood returns via vessels alone", "Through the ear", "Through the eye"],
     1,
     "रुधिर-मार्ग ही तंत्रों की मुलाकात-सड़क है — उत्सर्जी छलनी संचार-धारा पर ही बैठी है।",
     "The blood-route is the meeting-street of systems — the excretory sieve sits right on the circulatory stream."),

    ("organization-overview", "medium",
     "निम्न में से कौन-सा तंत्रिका तंत्र का घटक नहीं है?",
     "Which of the following is NOT a component of the nervous system?",
     ["मस्तिष्क", "मेरुरज्जु", "तंत्रिकाएँ", "मूत्राशय"],
     ["The brain", "The spinal cord", "The nerves", "The urinary bladder"],
     3,
     "मूत्राशय उत्सर्जी-परिवार का सदस्य है — तंत्रिका-परिवार की सूची में नहीं आता।",
     "The bladder is a member of the excretory family — it does not figure on the nerve family's list."),

    ("organization-overview", "medium",
     "एक ही अंग में विभिन्न ऊतक होने का फायदा क्या है?",
     "What is the advantage of having different tissues within one organ?",
     ["रंग-बिरंगा दिखना", "अंग का कार्य-चक्र पूरा हो — जैसे गुर्दे में छलनी, नली, वाहिका और तंत्रिका-नियंत्रण चारों ऊतक जुड़कर मूत्र-निर्माण संभव करते हैं", "वजन बढ़ना", "गंध आना"],
     ["Looking colourful", "The organ's work-cycle completes — e.g., in the kidney the sieve, duct, vessel and nerve-control tissues join to make urine-formation possible", "Gaining weight", "Emitting smell"],
     1,
     "एक अंग कई-कदम का कारखाना है — हर कदम का अलग ऊतक-विशेषज्ञ।",
     "An organ is a many-step factory — a separate tissue-specialist for each step."),

    ("organization-overview", "hard",
     "संगठन-सीढ़ी में सबसे ऊपर (सबसे जटिल स्तर) कौन-सा जीव-स्तर आता है?",
     "Which level of the organism comes at the top (most complex level) of the organisation ladder?",
     ["कोशिका-स्तर", "ऊतक-स्तर", "अंग-स्तर", "अंग-तंत्र मिलकर बना संपूर्ण जीव (organism)"],
     ["Cell level", "Tissue level", "Organ level", "The complete organism formed of organ-systems together"],
     3,
     "सारे तंत्र एक साथ जुड़कर जो चलता-फिरता जीव बनते हैं — वही सीढ़ी की सबसे ऊँची सीढ़ है।",
     "All systems joined together make the living moving being — that is the ladder's topmost step."),

    ("organization-overview", "hard",
     "'तंत्र' स्तर की विशेषता अंग-स्तर से किस रूप में भिन्न है?",
     "In what way is the 'system' level's character different from the organ level?",
     ["दोनों में कोई भेद नहीं", "अंग स्वयं एक ढाँचा है, तंत्र समन्वय-व्यवस्था है — अनेक अंगों का क्रम-बद्ध प्रवाह-जाल", "तंत्र छोटा होता है", "अंग तंत्र से बना होता है"],
     ["No difference between the two", "An organ is itself a structure; a system is a coordination-arrangement — an ordered flow-network of many organs", "A system is smaller", "An organ is made of systems"],
     1,
     "अंग ईंट-चिनाई है, तंत्र उस चिनाई की नल-बत्ती-व्यवस्था — स्तर का भाव बदल जाता है।",
     "An organ is the brickwork; a system is that brickwork's plumbing-wiring plan — the very sense of level changes."),

    ("organization-overview", "hard",
     "यदि किसी तंत्र का एक अंग बंद हो जाए तो केवल उसी अंग पर प्रभाव क्यों नहीं रुकता?",
     "If one organ of a system shuts down, why does the effect not stay limited to that organ alone?",
     ["क्योंकि अंग एक-दूसरे से नफरत करते हैं", "तंत्र के अंग श्रृंखला में जुड़े हैं — एक कड़ी का रुकना पूरी तंत्र-सेवा और उससे जुड़े अन्य तंत्रों के काम पर भी बोझ डालता है", "क्योंकि शरीर छोटा है", "क्योंकि कोशिकाएँ सोती हैं"],
     ["Because organs hate each other", "A system's organs are joined in a chain — one link stalling burdens the whole system's service and the work of linked systems too", "Because the body is small", "Because cells sleep"],
     1,
     "गुर्दा रुका तो केवल गुर्दा नहीं — रुधिर-रसायन, जल-संतुलन, रुधिर-दाब की पूरी साजिश बिगड़ने लगती है।",
     "If the kidney halts, not just the kidney — the whole tableau of blood-chemistry, water-balance, blood-pressure starts spoiling."),

    # ---------------- movement (25: E8/M14/H3) ----------------
    ("movement", "easy",
     "गति (movement) और स्थानांतरण/लोकोमोशन (locomotion) में क्या अंतर है?",
     "What is the difference between movement and locomotion?",
     ["दोनों एक ही हैं", "गति = शरीर या उसके भाग का हिलना (जगह बदले बिना भी); लोकोमोशन = पूरे शरीर का एक स्थान से दूसरे स्थान जाना", "गति केवल पौधों में", "लोकोमोशन केवल जड़ पदार्थों में"],
     ["Both are the same", "Movement = the body or its parts stirring (even without changing place); locomotion = the whole body going from one place to another", "Movement occurs only in plants", "Locomotion occurs only in non-living things"],
     1,
     "पेड़ की पत्ती हिलना = गति; तितली पंख फड़ाकर दूर जाना = गति + स्थानांतरण।",
     "A tree's leaf trembling = movement; the butterfly fluttering away far = movement + locomotion."),

    ("movement", "easy",
     "जंतु एक स्थान से दूसरे स्थान क्यों जाते हैं — लोकोमोशन की मुख्य वजहें क्या हैं?",
     "Why do animals move from one place to another — what are the main reasons for locomotion?",
     ["केवल खेलने के लिए", "भोजन की खोज, शिकार/खतरे से बचाव, अनुकूल आवास और प्रजनन-साथी की तलाश", "केवल नींद के लिए", "बिना कारण"],
     ["Only to play", "Searching food, escaping danger/predators, finding suitable habitat and a mate", "Only for sleep", "Without reason"],
     1,
     "भोजन-बचाव-घर-साथी — चारों जरूरतें शरीर को चलाने वाली चार मोटर हैं।",
     "Food-safety-home-mate — the four needs are the four motors that drive the body onward."),

    ("movement", "easy",
     "मेंढक की बड़ी पिछली टाँगें उसे किस गति में सहायक हैं?",
     "The frog's big hind legs help it in which movement?",
     ["उड़ने में", "लंबी छलांग लगाने और तैरने में — पानी-जमीन दोनों जगह", "रेंगने में", "खुदाई में"],
     ["In flying", "In long leaps and swimming — both on land and in water", "In crawling", "In digging"],
     1,
     "मेंढक की पिछली टाँगें जमीन पर धनुष-तीर और पानी में चपल-पंख हैं — दोहरा इंजन।",
     "The frog's hind legs are a bow-and-arrow on land and nimble fins in water — a double engine."),

    ("movement", "easy",
     "पक्षी उड़ान भरने के लिए मुख्यतः कौन-से अंगों की मदद लेते हैं?",
     "Which limbs do birds mainly use for flying?",
     ["पिछली टाँगें", "पंखों में बदली अगली टाँगें — छाती की विशाल पेशियों से फड़फड़ाती हैं", "पूँछ ही", "चोंच"],
     ["The hind legs", "The front limbs turned into wings — flapped by the huge chest muscles", "Only the tail", "The beak"],
     1,
     "पक्षी की अगली टाँगें ही पंख बनी हैं — छाती की भारी पेशियाँ उन्हें थपथपाती हैं।",
     "The bird's front limbs themselves became wings — the heavy chest muscles flap them."),

    ("movement", "easy",
     "घोड़ा-आदि चौपाये तेज़ दौड़ने में अपने चारों पैरों का प्रयोग कैसे करते हैं?",
     "How do four-legged runners like the horse use their four legs in fast running?",
     ["चारों एक साथ उठाकर", "पैरों का एक-एक कर बारी-बारी क्रम में जमीन पटकना — संतुलित गैलप-लय", "केवल दो पैरों पर", "पूँछ से उछलकर"],
     ["Lifting all four together", "Bringing the legs down one by one in turn — a balanced gallop-rhythm", "On only two legs", "Bouncing off the tail"],
     1,
     "चार-पहिया गाड़ी की तरह एक-एक पैर जमीन पर आता है — कभी पूरा शरीर हवा में, कभी संतुलन जमीन पर।",
     "Like a four-wheeled cart one leg lands after another — the body now wholly in air, now balanced on ground."),

    ("movement", "easy",
     "टिड्डी (grasshopper) की मोटी पिछली टाँगें उसे कैसे चलाती हैं?",
     "How do the grasshopper's thick hind legs carry it?",
     ["तैरने में", "झटकेदार उछाल (jump) भरने में — तह वाली लंबी टाँगें झट से सीधी होकर शरीर उड़ा देती हैं", "उड़ने भर में", "खुदाई में"],
     ["In swimming", "In springing jumps — the folded long legs snap straight and launch the body", "Only in flying", "In digging"],
     1,
     "तह-टाँग = दबी हुई कमान — खुलते ही स्प्रिंग की तरह शरीर हवा में।",
     "A folded leg = a compressed bow — on release, like a spring, the body is airborne."),

    ("movement", "easy",
     "मछली को पानी में आगे बढ़ना सहज क्यों लगता है?",
     "Why does a fish find moving forward in water effortless?",
     ["उसके पंख बड़े होते हैं", "उसका शरीर तरल-मित्र आकृति (streamlined) का है — जल-प्रतिरोध न्यूनतम रहता है", "उसकी आँखें बड़ी होती हैं", "उसका वजन नहीं होता"],
     ["Its fins are big", "Its body has a fluid-friendly (streamlined) shape — water-resistance stays minimal", "Its eyes are big", "It has no weight"],
     1,
     "तीर-आकार शरीर पानी को चीरता नहीं, सरकता है — घर्षण-भार घटा तो गति बढ़ी।",
     "The arrow-shaped body does not tear the water, it slides — less friction-load, more speed."),

    ("movement", "easy",
     "निम्न में से किस जीव की गति-विधि 'रेंगना' मानी जाती है?",
     "Whose mode of movement among the following is counted as 'crawling'?",
     ["ईगल", "छिपकली/साँप — भूमि से सटकर शरीर की लहरों से आगे", "डॉल्फ़िन", "गौरैया"],
     ["Eagle", "Lizard/snake — pressed to the ground, advancing by body-waves", "Dolphin", "Sparrow"],
     1,
     "साँप-छिपकली की भूमि-सटी लहर-चाल ही रेंगने की मिसाल है — तिरछी स्केल-पट्टियाँ भी जोड़ती हैं।",
     "The ground-hugging wave-walk of snake-lizard is the very specimen of crawling — the slanting scale-plates add grip too."),

    ("movement", "medium",
     "केंचुआ अपनी किरकिरा-बालों (setae) की मदद से कैसे चलता है?",
     "How does an earthworm walk with the help of its bristle-hairs (setae)?",
     ["पंखों से", "शरीर को पीछे की ओर खींचकर सेटा से मिट्टी पकड़ना, फिर अगला भाग आगे बढ़ाना — दो-चरण पकड़-खिंचाव", "पैरों की जोड़ी से", "पूँछ से"],
     ["With wings", "Gripping the soil with setae as the rear is drawn up, then extending the front part forward — a two-step grip-and-stretch", "With pairs of legs", "With the tail"],
     1,
     "पकड़ो और खिंचो की बारी-बारी — काँटेदार ब्रिसल मिट्टी में एंकर जमाती हैं, पेशी-लहर शरीर खिसकाती है।",
     "Grip and stretch by turns — the bristly spikes anchor in soil, muscle-waves slide the body ahead."),

    ("movement", "medium",
     "केंचुए का शरीर मोटा-पतला होते रहना उसकी चाल का कौन-सा आधार है?",
     "The earthworm's body thickening and thinning is which basis of its gait?",
     ["श्वास का", "इसकी वलय-पेशियाँ सिकुड़कर शरीर लंबा-पतला और दाबकर मोटा-छोटा करती हैं — यही वैकल्पिक दबाव आगे की रेंगन-लहर बनाता है", "दृष्टि का", "भोजन का"],
     ["Of breath", "Its circular muscles contract to make it long-thin and squeeze to make it fat-short — this alternating pressure builds the forward crawling-wave", "Of sight", "Of food"],
     1,
     "लंबा-मोटा का खेल: वलय पेशी और अनुदैर्घ्य पेशी की बारी-बारी की जीत ही रेंगने का इंजन है।",
     "The long-and-thick game: the alternating victory of circular and longitudinal muscles is the crawling engine."),

    ("movement", "medium",
     "मछली अपने शरीर और पूँछ को किस तरह इस्तेमाल करके पानी में आगे बढ़ती है?",
     "In what way does a fish use its body and tail to push forward in water?",
     ["शरीर सीधा रखकर केवल पंख हिलाकर", "शरीर-पूँछ को दाएँ-बाएँ लहरों में घुमाकर पानी को पीछे धकेलती है — प्रतिक्रिया उसे आगे बढ़ाती है", "गोल घूमकर", "केवल ऊपर-नीचे"],
     ["Keeping the body straight, moving only the fins", "Swinging body-and-tail in right-left waves, pushing water backward — the reaction drives her forward", "By spinning round", "Only up and down"],
     1,
     "पानी को पीछे ठेलो, खुद आगे बढ़ो — मछली-चाल का क्रिया-प्रतिक्रिया सिद्धांत।",
     "Push the water back, move yourself ahead — the action-reaction principle of fish-motion."),

    ("movement", "medium",
     "मनुष्य चलते समय अपनी भुजाओं को इस्तेमाल कैसे करता है?",
     "How does a person use the arms while walking?",
     ["भुजाएँ स्थिर रखता है", "दोनों भुजाएँ पैरों के विपरीत दिशा में आगे-पीछे डोलती हैं — शरीर का संतुलन बना रहता है", "भुजाएँ ऊपर उठाता है", "भुजाएँ पीठ में बाँधता है"],
     ["Keeps the arms still", "Both arms swing forward-back opposite to the legs — the body's balance stays put", "Raises the arms up", "Ties the arms behind"],
     1,
     "बाएँ पैर-दाहिना हाथ की साथ-चाल ही चाल की लय-संतुलन है — भुजा-दोलन प्रकृति का संतुलन-दण्ड।",
     "The left leg-right hand co-march is walking's rhythm-balance — the arm-swing is nature's balancing pole."),

    ("movement", "medium",
     "मेंढक के पैरों की झिल्लीदार (webbed) बना होना किस कार्य की तैयारी है?",
     "The webbed build of a frog's feet is a preparation for which task?",
     ["दौड़ने की", "तैरते समय जल को पीछे धकेलने की — बड़ा चपल क्षेत्र बल देता है", "खुदाई की", "उड़ान की"],
     ["For running", "For pushing water back while swimming — a broad paddle area gives thrust", "For digging", "For flight"],
     1,
     "झिल्ली-पैर = जुड़ा चप्पू — पानी में प्रत्येक चाल अधिक पानी उठाकर अधिक धक्का देती है।",
     "A webbed foot = a joined paddle — each stroke in water scoops more and pushes harder."),

    ("movement", "medium",
     "अमीबा अपने शरीर के बिना-पैर प्रवाह (flow) से कैसे खिसकता है?",
     "How does Amoeba slink along by the flow of its own footless body?",
     ["पूँछ से", "शरीर से कूड़-पाँव (pseudopodia) फैलाकर उसी में अपना द्रव्य बहाकर आगे सरकता है", "पंखों से", "रोमकों से"],
     ["With a tail", "Extending pseudopodia from its body and streaming its own substance into them to creep forward", "With fins", "With cilia"],
     1,
     "शरीर ही मार्ग बनाता है — जहाँ बहे, वहीं अमीबा पहुँच जाता है।",
     "The body itself makes the road — wherever it flows, the Amoeba arrives."),

    ("movement", "medium",
     "पैरामीशियम का तेज़ तैरना उसके शरीर की किन संरचनाओं के ताल-मेल से होता है?",
     "Paramecium's brisk swimming happens by the rhythm of which structures on its body?",
     ["कूड़-पाँव", "हज़ारों रोमक (cilia) — छोटे बाल एक-सी लय में झपटकर जल-धाराएँ बनाते हैं", "पंख", "पैर-जोड़े"],
     ["Pseudopodia", "Thousands of cilia — tiny hairs beating in one rhythm to build water-currents", "Fins", "Leg-pairs"],
     1,
     "रोमक-पंक्तियों का एकस्वर झपट्टा ही उसका नाव-इंजन है।",
     "The unison stroke of cilia-rows is its boat-engine."),

    ("movement", "medium",
     "विपरीत-कार्य पेशी-जोड़ी (antagonistic pair) से क्या समझा जाता है?",
     "What is understood by an antagonistic pair of muscles?",
     ["एक ही काम करने वाली दो पेशियाँ", "जिन दो पेशियों का कार्य आपस में उलटा हो — एक हड्डी को एक दिशा में, साथी दूसरी दिशा में ले जाती है", "पास-पास रहने वाली पेशियाँ", "एक ही पेशी के दो नाम"],
     ["Two muscles doing the same job", "Two muscles whose actions are opposite — one takes the bone one way, the partner the other way", "Muscles lying close together", "Two names of one muscle"],
     1,
     "एक सिकुड़े तो दूसरा ढीला — इसी उलट-काम जोड़ी से अंग दोनों दिशाओं में चल पाता है।",
     "One contracts while its partner slackens — by this opposite-work pair the limb can move both ways."),

    ("movement", "medium",
     "पेशी और अस्थि का गति-कार्य में बँटवारा कैसा है?",
     "How is the work divided between muscle and bone in movement?",
     ["दोनों एक ही काम करते हैं", "पेशी सक्रिय-इंजन है जो बल देती है; अस्थि निष्क्रिय-उत्तमाशा ढाँचा है जिस पर बल काम करता है", "अस्थि सिकुड़ती है", "पेशी कठोर ढाँचा है"],
     ["Both do the same work", "The muscle is the active engine supplying force; the bone is the passive lever-frame on which the force works", "The bone contracts", "The muscle is a rigid frame"],
     1,
     "इंजन (पेशी) + लीवर (अस्थि) = गति-समीकरण — बल एक का, टिकाऊ ढाँचा दूसरे का।",
     "Engine (muscle) + lever (bone) = the motion equation — force from one, the rigid frame from the other."),

    ("movement", "medium",
     "संधियों (joints) के बिना कंकाल की दशा क्या होती?",
     "What would be the state of the skeleton without joints?",
     ["गति और अधिक होती", "सारा ढाँचा एक सख्त ढलाई जैसा — मुड़ना-घूमना असंभव, केवल अडिग मूर्ति-सी अवस्था", "कोई फर्क नहीं पड़ता", "हड्डियाँ बढ़ जातीं"],
     ["Movement would increase", "The whole frame would be like a single rigid casting — bending-turning impossible, a mere immobile statue-state", "No difference would occur", "The bones would grow longer"],
     1,
     "हड्डी-श्रृंखला में कब्ज़े (जोड़) ही तो मोड़ देते हैं — कब्ज़े गए तो दरवाज़ा ही नहीं खुलेगा।",
     "The hinges (joints) alone give the bone-chain its bends — hinges gone, the door cannot open at all."),

    ("movement", "medium",
     "जल-कीट पानभुज (water boatman) या डुबकी-भरती जीव अपने चप्पू-नुमा पैरों से कैसे चलते हैं?",
     "How do water-rowing creatures like the water boatman move with their paddle-like legs?",
     ["पैरों को हवा में फड़फड़ाकर", "पैरों को एक साथ झटके से पीछे की ओर घुमाकर जल-खेंच बनाते हैं — धक्का आगे मिलता है", "केवल तैरते रहते हैं", "तल पर रेंगते हैं"],
     ["By fluttering the legs in air", "Sweeping the legs together backward in one stroke, making a water-pull — the push comes forward", "They just float", "They crawl on the bottom"],
     1,
     "चप्पू-पैर पीछे का जल खींचते हैं — न्यूटन का धक्का आगे उड़ा देता है।",
     "The paddle-legs pull water backward — Newton's push launches them forward."),

    ("movement", "medium",
     "मानव-हाथ की पकड़ बंदर-हाथ से व्यापक क्यों है?",
     "Why is the human hand's grip broader than a monkey's?",
     ["नाखूनों के कारण", "अंगूठा अंगुलियों के सामने घूमकर आ सकता है — हर आकार की वस्तु को मुट्ठी में कसने की क्षमता इसी से आती है", "हथेली बड़ी होने से", "त्वचा मोटी होने से"],
     ["Because of the nails", "The thumb can swing around to face the fingers — the capacity to fist-grip objects of any shape comes from this", "Because the palm is big", "Because the skin is thick"],
     1,
     "सामने-आ-अंगूठा (opposable thumb) ही औज़ार-पकड़ की कुंजी है — पत्थर से कलम तक सब इसी की देन।",
     "The thumb-that-meets (opposable thumb) is the key of tool-grip — from stone to pen, all its gift."),

    ("movement", "medium",
     "साँप की उदर-पट्टियाँ (scales) रेंगने में क्या योगदान देती हैं?",
     "What contribution do a snake's belly-plates (scales) make to crawling?",
     ["वे शरीर को उठाती हैं", "मोटी तिरछी पट्टियाँ जमीन पर टिककर पीछे की ओर खिसकने से रोकती हैं — शरीर की मोड़-लहरें उसी टिकाव से आगे का धक्का पाती हैं", "वे पंख का काम करती हैं", "वे पानी रोकती हैं"],
     ["They lift the body", "The broad slanted plates bite the ground and stop backward slip — the body's winding waves get their forward push from that grip", "They work as fins", "They block water"],
     1,
     "टिकाऊ-खुरचना: पट्टियाँ पीछे नहीं फिसलने देतीं — लहर का बल सीधा आगे उतरता है।",
     "Grip-and-grate: the plates forbid backward slide — the wave's force lands straight ahead."),

    ("movement", "medium",
     "पंख का नीचे का झटका (down-stroke) पक्षी को किस प्रकार ऊपर रखता है?",
     "How does the wing's downstroke keep the bird up?",
     ["हवा बंद करके", "झटके से पंख नीचे की हवा को धकेलता है — ठेली हवा का प्रतिक्रिया-बल पक्षी को ऊपर एवं आगे उठाता है", "पंख गरम करके", "चुंबकीय खिंचाव से"],
     ["By blocking air", "In the stroke the wing pushes the air below — the reaction-force of the pushed air lifts the bird up and forward", "By warming the wing", "By magnetic pull"],
     1,
     "हवा को नीचे पटको, खुद ऊपर उठो — उड़ान का दूसरा नाम निरंतर क्रिया-प्रतिक्रिया है।",
     "Slam the air down, rise yourself up — flight's other name is ceaseless action-reaction."),

    ("movement", "hard",
     "यदि किसी जोड़ी की दोनों पेशियाँ एक ही समय पर सिकुड़ जाएँ तो अंग की दशा क्या होगी?",
     "What will be the state of the limb if both muscles of a pair contract at the same time?",
     ["अंग तेज़ी से घूमेगा", "अंग अकड़कर मध्य-अवस्था में जकड़ जाएगा — न घूमेगा न मुड़ेगा; शरीर-नियंत्रण में एक-साथ-संकुचन होता ही नहीं", "अंग लंबा खिंच जाएगा", "कुछ नहीं होगा"],
     ["The limb will spin fast", "The limb will stiffen locked in a mid-state — neither turning nor bending; body-control never lets both contract at once", "The limb will stretch long", "Nothing will happen"],
     1,
     "रस्साकशी में दोनों ओर बराबर खींच — पताका जगह पर जमी रहेगी; इसीलिए तंत्रिका-तंत्र एक को सिकुड़ने देता है, दूसरे को ढीला।",
     "A tug-of-war with equal pull on both sides — the flag stays pinned; hence the nervous system lets one contract, the other slacken."),

    ("movement", "hard",
     "कीटों का बाहरी कंकाल (exoskeleton) और मनुष्य का भीतरी कंकाल (endoskeleton) — गति-दृष्टि से मूल भेद क्या है?",
     "Insects' outer skeleton (exoskeleton) versus the human inner skeleton (endoskeleton) — what is the basic movement-level difference?",
     ["दोनों में कोई भेद नहीं", "कीट में पेशियाँ खोल के भीतर सतह से खींचकर चलाती हैं (कवच-कंधे); मनुष्य में पेशियाँ अस्थि-स्तंभों पर बाहर से जुड़ी हैं — पेशी-जुड़ाव की दिशा उलटी", "कीट में हड्डी नहीं होती ही", "मनुष्य में पेशी नहीं होती"],
     ["No difference between the two", "In an insect, muscles pull from the shell's inner surface (armour-shoulders); in a human, muscles attach externally on bone-pillars — the direction of muscle-attachment is reversed", "An insect has no bones at all", "A human has no muscles"],
     1,
     "खोल-कंकाल में पेशी कवच के भीतर खिंचती है, भीतरी-कंकाल में अस्थि पर बाहर से — दो विपरीत इंजीनियरिंग।",
     "In a shell-skeleton the muscle pulls inside the armour; in an inner skeleton it rides the bone outside — two opposite engineerings."),

    ("movement", "hard",
     "ऑक्टोपस/जेलीफिश बिना पैर-पंख के तेज़ी से कैसे चलते हैं?",
     "How do octopuses/jellyfish move fast without legs or fins?",
     ["लहरों पर तैरते हैं", "जेट-चालक सिद्धांत — शरीर से जल भरकर नाली से झट से बाहर फेंकते हैं; उछले जल का प्रतिक्रिया-धक्का शरीर को विपरीत दिशा में भगा देता है", "पत्थर से टकराकर", "हवा में उड़कर"],
     ["They drift on waves", "The jet-propulsion principle — they fill the body with water and fling it out through a funnel in a snap; the reaction-push of the ejected water shoots the body the opposite way", "By hitting stones", "By flying in air"],
     1,
     "जल-रॉकेट: भीतर का जल पीछे का दरवाज़ा खोलते ही शरीर आगे की सवारी बन जाता है।",
     "A water-rocket: the moment the inner water opens the rear door, the body becomes the forward rider."),

    # ---------------- sense-organs (20: E7/M12/H1) ----------------
    ("sense-organs", "easy",
     "मानव के पाँच ज्ञानेंद्रियों (sense organs) कौन-सी हैं?",
     "Which are the five sense organs of humans?",
     ["आँख, कान, नाक, जीभ, त्वचा", "हृदय, फेफड़े, गुर्दे, यकृत, पेट", "हाथ, पैर, सिर, पेट, पीठ", "बाल, नाखून, दाँत, होंठ, ठुड्डी"],
     ["Eyes, ears, nose, tongue, skin", "Heart, lungs, kidneys, liver, stomach", "Hands, feet, head, belly, back", "Hair, nails, teeth, lips, chin"],
     0,
     "पाँच द्वार, पाँच अनुभव — देखना, सुनना, सूँघना, चखना, छूना।",
     "Five gates, five experiences — seeing, hearing, smelling, tasting, touching."),

    ("sense-organs", "easy",
     "ध्वनि (sound) का बोध किस ज्ञानेंद्रिय से होता है?",
     "Through which sense organ is sound perceived?",
     ["आँख से", "कान से", "नाक से", "त्वचा से"],
     ["Through the eyes", "Through the ears", "Through the nose", "Through the skin"],
     1,
     "कान श्रवण-द्वार है — हवा की ध्वनि-लहरें यहीं घूमती हैं।",
     "The ear is the hearing-gate — the air's sound-waves circle here."),

    ("sense-organs", "easy",
     "बाहरी कान (outer ear) का मुख्य कार्य क्या है?",
     "What is the main function of the outer ear?",
     ["संतुलन रखना", "ध्वनि-लहरों को इकट्ठा करके भीतर के कान तक केंद्रित करना", "रुधिर छानना", "श्वास लेना"],
     ["Keeping balance", "Collecting sound-waves and focusing them into the inner ear", "Filtering blood", "Breathing"],
     1,
     "बाहरी कान एक पकड़-कीप है — आसपास की आवाज़ को भटकने नहीं देता।",
     "The outer ear is a catching-funnel — it does not let nearby sound stray away."),

    ("sense-organs", "easy",
     "गंध (smell) का बोध किस अंग से होता है?",
     "Through which organ is smell perceived?",
     ["जीभ से", "नाक से — घ्राण-ग्राही उद्दीपन पकड़ते हैं", "कान से", "आँख से"],
     ["Through the tongue", "Through the nose — its smell-receptors catch the stimulus", "Through the ear", "Through the eye"],
     1,
     "नाक की छत पर घ्राण-क्षेत्र है — हवा में घुली गंध-कणिकाएँ वहीं पहुँचती हैं।",
     "On the nose's roof lies the smell-zone — odour particles dissolved in air land right there."),

    ("sense-organs", "easy",
     "पलकें और बाल-पलक (eyelashes) आँख के लिए क्या करती हैं?",
     "What do the eyelids and eyelashes do for the eye?",
     ["देखने में मदद", "आँख की ढाल — धूल-कण और अचानक प्रकाश-झटके से रक्षा", "रुधिर बनाती हैं", "आँख ठंडी करती हैं"],
     ["Help in seeing", "The eye's shield — protection from dust and sudden light-shocks", "Make blood", "Cool the eye"],
     1,
     "पलक तुरंत-परदा है, पलक-बाल धूल-जाली — दोनों मिलकर सुरक्षा-परत।",
     "The lid is the instant-curtain, the lashes the dust-screen — together the protective layer."),

    ("sense-organs", "easy",
     "त्वचा किन संवेदनाओं का ग्रहण करती है?",
     "Which sensations does the skin receive?",
     ["केवल गर्मी", "स्पर्श, दबाव, गर्मी-ठंड और पीड़ा (दर्द)", "केवल रंग", "केवल ध्वनि"],
     ["Only heat", "Touch, pressure, heat-cold and pain", "Only colour", "Only sound"],
     1,
     "त्वचा स्पर्श-महल है — छूने से लेकर जलने तक हर छू-अनुभव इसी की ग्राही-पंक्तियों पर।",
     "The skin is the touch-palace — from a caress to a burn, every touch-experience on its receptor-rows."),

    ("sense-organs", "easy",
     "आँख में प्रकाश सर्वप्रथम किस स्वच्छ ढ़ाल से होकर भीतर जाता है?",
     "Through which clear shield does light first pass into the eye?",
     ["रेटिना से", "कॉर्निया (cornea) से — आँख की सामने की पारदर्शी खिड़की", "अक्षिका से", "पुतली से ही सीधे"],
     ["The retina", "The cornea — the eye's transparent front window", "The lens", "Straight through the pupil alone"],
     1,
     "कॉर्निया भीतर आने वाली प्रकाश-पट्टी की पहली मोड़-काँच है — पारदर्शी प्रवेश-द्वार।",
     "The cornea is the first bend-glass of the incoming light-beam — the transparent entry gate."),

    ("sense-organs", "medium",
     "पुतली (pupil) का कार्य क्या है?",
     "What is the pupil's function?",
     ["रंग देती है", "भीतर जाने वाले प्रकाश की मात्रा का द्वार — छोटी-बड़ी होकर नियंत्रित करती है", "प्रकाश पकड़ती है", "द्रव बनाती है"],
     ["It gives colour", "The gateway of the light-amount entering — controlling it by shrinking and widening", "It traps light", "It makes fluid"],
     1,
     "पुतली आँख का कैमरा-एपर्चर है — तेज़ रोशनी में सिकुड़े, धुंधलके में खुले।",
     "The pupil is the eye's camera-aperture — narrowing in bright light, opening in dim."),

    ("sense-organs", "medium",
     "रेटिना (retina) की भूमिका क्या है?",
     "What is the retina's role?",
     ["प्रकाश छानती है", "प्रकाश-संवेदी परदा — प्रतिबिंब बनाकर उसे तंत्रिका-संकेत में बदलती है", "रुधिर बनाती है", "आँख सफेद बनाती है"],
     ["It filters light", "The light-sensitive screen — forming the image and converting it into nerve-signals", "It makes blood", "It whitens the eye"],
     1,
     "कैमरे की फिल्म-परत रेटिना ही है — यहीं प्रकाश स्नायु-भाषा में अनूदित होता है।",
     "The camera's film-layer is the retina — right here light gets translated into the nerve language."),

    ("sense-organs", "medium",
     "रेटिना से बना दृश्य-संकेत मस्तिष्क तक कौन ले जाता है?",
     "Who carries the visual signal formed in the retina to the brain?",
     ["श्रवण तंत्रिका", "दृष्टि तंत्रिका (optic nerve)", "घ्राण तंत्रिका", "रुधिर-नली"],
     ["The auditory nerve", "The optic nerve", "The olfactory nerve", "A blood vessel"],
     1,
     "प्रकाश की खबर नेत्र-तंत्रिका के तार से मस्तिष्क के दृष्टि-केंद्र पहुँचती है — देखना अंततः मस्तिष्क ही करता है।",
     "The light-news travels the optic nerve's wire to the brain's vision-centre — it is the brain that finally sees."),

    ("sense-organs", "medium",
     "कान का परदा (eardrum) क्या करता है?",
     "What does the eardrum do?",
     ["जल रोकता है", "ध्वनि-लहरों में कंपन करके उन्हें यांत्रिक थर-थराहट में बदलता है — आगे हड्डी-श्रृंखला को देता है", "संतुलन बनाता है", "हवा छानता है"],
     ["It blocks water", "Vibrates with the sound-waves, turning them into mechanical tremors — passing them to the bone-chain ahead", "It keeps balance", "It filters air"],
     1,
     "कान-परदा ढीला-तना चमड़ा-पटल है — हर आवाज़ की थाप इसी पर पहली बार गूँजती है।",
     "The eardrum is a slack-stretched skin-sheet — the beat of every sound echoes on it first."),

    ("sense-organs", "medium",
     "मध्य-कान की तीन छोटी हड्डियाँ (ossicles) का कार्य क्या है?",
     "What is the function of the three tiny bones (ossicles) of the middle ear?",
     ["जल बाहर निकालना", "परदे के कंपन को बढ़ाकर भीतरी कान तक पहुँचाना — ध्वनि-ऊर्जा का प्रवर्धक-सेतु", "रुधिर बनाना", "हवा बढ़ाना"],
     ["Draining water out", "Amplifying the drum's vibration and carrying it to the inner ear — an amplifier-bridge of sound-energy", "Making blood", "Increasing air"],
     1,
     "थैकी-रकाब-रेमिका तीन हड्डियाँ घुंघरू-श्रृंखला हैं — आवाज़ को तीव्र कर अंदर पहुँचाती हैं।",
     "The hammer-anvil-stirrup three bones are a bell-chain — they intensify the sound and deliver it inside."),

    ("sense-organs", "medium",
     "भीतरी कान का कुंडल (cochlea) किसका केंद्र है?",
     "The inner ear's coil (cochlea) is the centre of what?",
     ["संतुलन का", "श्रवण का — ध्वनि-कंपनों को तंत्रिका-संकेतों में बदलने वाले ग्राही यहीं बैठते हैं", "गंध का", "स्वाद का"],
     ["Of balance", "Of hearing — the receptors turning sound-vibrations into nerve-signals sit right here", "Of smell", "Of taste"],
     1,
     "घोंघा-कुंडल में सुनने की वास्तविक रसायन-विद्युत फैक्ट्री है।",
     "The snail-coil houses the actual electrochemical factory of hearing."),

    ("sense-organs", "medium",
     "सिर घुमाने पर हमें गिरने का अहसास और संतुलन — यह काम कान का कौन-सा भाग करता है?",
     "The feel of falling while turning the head, and balance — which part of the ear does this work?",
     ["कॉर्निया", "भीतरी कान के अर्धवृत्तीय नह्याएँ (semicircular canals)", "पुतली", "बाहरी कीप"],
     ["The cornea", "The semicircular canals of the inner ear", "The pupil", "The outer funnel"],
     1,
     "तीन तिरछी नहरें शरीर का जाइरोस्कोप हैं — सिर की हर झुकाव-घूमाव की खबर वहीं बनती है।",
     "The three slanted canals are the body's gyroscope — news of every head-tilt-turn forms right there."),

    ("sense-organs", "medium",
     "नाक बंद होने पर खाने का स्वाद फीका क्यों पड़ जाता है?",
     "Why does food taste flat when the nose is blocked?",
     ["जीभ सूख जाती है", "स्वाद-बोध का बड़ा हिस्सा गंध से आता है — गंध-मार्ग बंद तो जीभ केवल मीठा-खट्टा-नमकीन-कड़वा पाती है", "दाँत कमजोर हो जाते हैं", "लार बंद हो जाती है"],
     ["The tongue dries out", "A large share of taste-sense comes from smell — with the smell-route shut, the tongue gets only sweet-sour-salty-bitter", "The teeth weaken", "Saliva stops"],
     1,
     "भोजन का 'स्वाद' वास्तव में स्वाद+गंध का संयुक्त अनुभव है — ज़ुकाम में गंध-खंड गायब, स्वाद अधूरा।",
     "Food's 'taste' is actually a joint experience of taste+smell — in a cold the smell-chapter goes missing, the taste stays half."),

    ("sense-organs", "medium",
     "भोजन का स्वाद तभी ठीक लगता है जब वह किस अवस्था में हो?",
     "Food tastes right only when it is in what condition?",
     ["ठोस सूखी अवस्था में", "लार में घुलने की अवस्था में — घुला रसायन ही स्वाद-ग्राहियों तक पहुँच सकता है", "जमी हुई अवस्था में", "गरम ही गरम"],
     ["Solid and dry", "Dissolved in saliva — only a dissolved chemical can reach the taste-receptors", "Frozen", "Piping hot only"],
     1,
     "सूखी जीभ पर नमक भी फीका — पहले घुले, तब चखे जाएँ।",
     "Even salt tastes flat on a dry tongue — first dissolve, then taste."),

    ("sense-organs", "medium",
     "त्वचा के विभिन्न भागों में स्पर्श-संवेदनशीलता कैसी होती है?",
     "How is touch-sensitivity across different parts of the skin?",
     ["सब जगह समान", "अंगुली-अग्र, होंठ जैसे भाग अति-संवेदी; पीठ-बाहु जैसे भागों में कम — ग्राहियों का वितरण असमान", "केवल हाथ में होती है", "केवल तलवों में"],
     ["Equal everywhere", "Fingertips, lips and such parts are ultra-sensitive; back-forearm less — the receptor distribution is uneven", "Only in the hands", "Only in the soles"],
     1,
     "अंगुलियों पर ग्राहियों का घना जाल, पीठ पर बिखरा बिखरा — इसीलिए आँख बंद करके पहचान उंगलियों से होती है।",
     "A dense receptor-net on the fingers, a scattered one on the back — hence closed-eye recognition happens by the fingers."),

    ("sense-organs", "medium",
     "ग्राही (receptor) → तंत्रिका → मस्तिष्क — यह तीन-चरणी श्रृंखला किस कार्य की है?",
     "Receptor → nerve → brain — this three-step chain is of which function?",
     ["पाचन की", "संवेदन-बोध की — उद्दीपन पकड़ने से लेकर उसका अनुभव होने तक की यात्रा", "श्वास की", "उत्सर्जन की"],
     ["Of digestion", "Of sense-perception — the journey from catching the stimulus to experiencing it", "Of breathing", "Of excretion"],
     1,
     "पकड़ो (ग्राही) → भेजो (तंत्रिका) → पढ़ो (मस्तिष्क) — ज्ञानेंद्रियों की हर कहानी इसी तीन-अंक नाटक की।",
     "Catch (receptor) → send (nerve) → read (brain) — every sense-organ's story is this three-act play."),

    ("sense-organs", "medium",
     "ज्ञानेंद्रियाँ जीव के लिए अस्तित्व की दृष्टि से क्यों महत्वपूर्ण हैं?",
     "Why are sense organs vital for an organism's existence?",
     ["सुंदर दिखने के लिए", "पर्यावरण की घटनाओं की तुरंत सूचना देकर खतरे से बचने और अवसर पकड़ने में सक्षम बनाती हैं", "वजन बढ़ाने के लिए", "केवल नींद के लिए"],
     ["To look beautiful", "By instantly reporting environmental events, they enable dodging danger and seizing opportunity", "To gain weight", "Only for sleep"],
     1,
     "जानकारी ही बचाव है — साँप की सरसराहट सुनना ही भागने का पहला जतन है।",
     "Information is survival — just hearing a snake's rustle is the first act of fleeing."),

    ("sense-organs", "hard",
     "'अंधा बिंदु' (blind spot) क्या होता है?",
     "What is the 'blind spot'?",
     ["आँख का रंगीन भाग", "रेटिना का वह स्थान जहाँ दृष्टि-तंत्रिका निकलती है — वहाँ प्रकाश-ग्राही नहीं होते, इसलिए वहाँ का कोई प्रतिबिंब नहीं दिखता", "पुतली का काला रंग", "कॉर्निया का धब्बा"],
     ["The eye's coloured part", "The retinal spot where the optic nerve exits — no light-receptors there, so no image forming at that spot is seen", "The pupil's black colour", "A spot on the cornea"],
     1,
     "जहाँ तार बाहर निकलता है वहाँ फिल्म नहीं लगी होती — इसी खाली थाने को अंधा बिंदु कहते हैं।",
     "Where the wire exits, no film is laid — this empty station is called the blind spot."),
]
