# -*- coding: utf-8 -*-
"""B06 'Nutrition & Digestion' — Part 1 data (70 items).
Order: nutrients-balanced-diet (35), human-digestive-system (35).
Tuple: (topic, difficulty, q_hi, q_en, options_hi[4], options_en[4], correct_idx, exp_hi, exp_en)
DENY (never re-ask): B04 all nutrition-mode defs/examples (autotroph/heterotroph/saprophyte/parasite/
mushroom/pitcher/lichen/roundworm+Cuscuta); B07 pharynx air-food crossing & epiglottis; B08 iron-in-Hb
component framing & lacteal-fat-route; B02 intestine epithelium type, peristalsis-tissue,
digestive-organ-system framing; B03 tapeworm phylum, fungi/Plantae/Animalia mode-classification;
B09 food refrigeration/preservation.
"""

PART1 = [
    # ---------------- nutrients-balanced-diet (35: E12/M18/H5) ----------------
    ("nutrients-balanced-diet", "easy",
     "भोजन में मुख्य रूप से कौन-से पोषक तत्व (nutrients) पाए जाते हैं?",
     "Which nutrients are mainly found in food?",
     ["केवल प्रोटीन और वसा", "कार्बोहाइड्रेट, प्रोटीन, वसा, विटामिन, खनिज — साथ में जल और रेशा", "केवल विटामिन", "केवल खनिज लवण"],
     ["Only proteins and fats", "Carbohydrates, proteins, fats, vitamins, minerals — along with water and roughage", "Only vitamins", "Only mineral salts"],
     1,
     "संतुलित भोजन के घटक छह वर्ग हैं — तीन ऊर्जा-दाता (कार्बोहाइड्रेट, प्रोटीन, वसा) और तीन रक्षक (विटामिन, खनिज, जल) साथ में रेशा।",
     "A balanced food has six component classes — three energy-givers (carbohydrates, proteins, fats) and three protectors (vitamins, minerals, water) plus roughage."),

    ("nutrients-balanced-diet", "easy",
     "शरीर को तत्काल ऊर्जा मुख्य रूप से किस पोषक तत्व से मिलती है?",
     "From which nutrient does the body get instant energy mainly?",
     ["विटामिन से", "कार्बोहाइड्रेट से", "खनिज लवण से", "रेशे से"],
     ["From vitamins", "From carbohydrates", "From mineral salts", "From roughage"],
     1,
     "चावल-रोटी-आलू जैसे कार्बोहाइड्रेट सबसे जल्दी ग्लूकोस में टूटकर ऊर्जा देते हैं — इसीलिए मुख्य ऊर्जा-स्रोत कहलाते हैं।",
     "Carbohydrates like rice-roti-potato break into glucose fastest and give energy — hence called the main energy source."),

    ("nutrients-balanced-diet", "easy",
     "शरीर की वृद्धि और क्षतिग्रस्त ऊतकों की मरम्मत के लिए कौन-सा पोषक तत्व 'निर्माण-सामग्री' है?",
     "Which nutrient is the 'building material' for body growth and repair of worn-out tissues?",
     ["कार्बोहाइड्रेट", "प्रोटीन", "विटामिन", "रेशा"],
     ["Carbohydrates", "Proteins", "Vitamins", "Roughage"],
     1,
     "प्रोटीन से ही मांसपेशी, एंजाइम और शरीर-ऊतक बनते-टूटते रहते हैं — शरीर की ईंट-चूना प्रोटीन है।",
     "Muscles, enzymes and body tissues keep being built from proteins — protein is the body's brick-and-lime."),

    ("nutrients-balanced-diet", "easy",
     "दीर्घकालिक ऊर्जा-भंडार के रूप में शरीर में मुख्यतः कौन-सा पोषक तत्व जमा होता है?",
     "Which nutrient is stored in the body mainly as a long-term energy reserve?",
     ["विटामिन C", "वसा", "जल", "खनिज लवण"],
     ["Vitamin C", "Fat", "Water", "Mineral salts"],
     1,
     "अतिरिक्त वसा त्वचा के नीचे जमा होकर भविष्य का ऊर्जा-बैंक बनती है और शरीर को गर्म भी रखती है।",
     "Extra fat deposits under the skin as a future energy bank and also keeps the body warm."),

    ("nutrients-balanced-diet", "easy",
     "संतुलित आहार (balanced diet) से क्या तात्पर्य है?",
     "What is meant by a balanced diet?",
     ["केवल महँगा भोजन", "ऐसा भोजन जिसमें सभी पोषक तत्व सही मात्रा में शरीर की आवश्यकतानुसार सम्मिलित हों", "केवल दूध-फल का भोजन", "जितना हो सके खा लेना"],
     ["Only expensive food", "A diet that has all nutrients in right proportion as per the body's needs", "Only milk-and-fruit food", "Eating as much as one can"],
     1,
     "संतुलित आहार = ऊर्जा + वृद्धि + रक्षा — तीनों की पूर्ति एक ही थाली में सही अनुपात में।",
     "Balanced diet = energy + growth + protection — all three supplied on one plate in right proportion."),

    ("nutrients-balanced-diet", "easy",
     "विटामिन और खनिज लवण ऊर्जा तो नहीं देते, फिर भी आवश्यक क्यों हैं?",
     "Vitamins and minerals give no energy, so why are they essential?",
     ["वे स्वाद बढ़ाते हैं", "शरीर के विभिन्न जैविक कार्यों को सुचारु और रोग-रक्षा को सक्रिय रखते हैं", "वे वजन बढ़ाते हैं", "वे भूख बढ़ाते हैं"],
     ["They add taste", "They keep the body's various life-processes smooth and its disease-defence active", "They increase weight", "They increase hunger"],
     1,
     "ये सुरक्षा-पोषक हैं — मात्रा छोटी, कार्य निर्णायक; कमी पड़ते ही विशिष्ट रोग उभरते हैं।",
     "These are protective nutrients — small in amount, decisive in role; their lack brings specific diseases."),

    ("nutrients-balanced-diet", "easy",
     "मानव शरीर का लगभग कितना भाग जल है?",
     "About what fraction of the human body is water?",
     ["लगभग 10%", "लगभग 70%", "लगभग 30%", "लगभग 95%"],
     ["About 10%", "About 70%", "About 30%", "About 95%"],
     1,
     "शरीर का दो-तिहाई से थोड़ा कम (लगभग 70%) जल है — रुधिर से लेकर कोशिका-द्रव तक सब जलीय आधार पर चलता है।",
     "A little under two-thirds (about 70%) of the body is water — from blood to cell fluid, everything runs on a watery base."),

    ("nutrients-balanced-diet", "easy",
     "रिकेट्स (हड्डियों का मुड़ना) किस विटामिन की कमी से होता है?",
     "Deficiency of which vitamin causes rickets (bending of bones)?",
     ["विटामिन A", "विटामिन C", "विटामिन D", "विटामिन K"],
     ["Vitamin A", "Vitamin C", "Vitamin D", "Vitamin K"],
     2,
     "विटामिन D कैल्शियम के अवशोषण में सहायक है — इसकी कमी में हड्डियाँ कैल्शियम न पाकर नर्म पड़कर मुड़ जाती हैं।",
     "Vitamin D aids calcium absorption — without it bones go short of calcium, soften and bend."),

    ("nutrients-balanced-diet", "easy",
     "स्कर्वी (मसूढ़ों से रक्त स्राव) किस विटामिन की कमी से होता है?",
     "Deficiency of which vitamin causes scurvy (bleeding gums)?",
     ["विटामिन C", "विटामिन D", "विटामिन B1", "विटामिन A"],
     ["Vitamin C", "Vitamin D", "Vitamin B1", "Vitamin A"],
     0,
     "विटामिन C कोलेजन-निर्माण में काम आता है — कमी में मसूड़े-त्वचा से खून आने लगता है; नाविकों का अमरबेल-रोग।",
     "Vitamin C serves collagen-building — its lack makes gums and skin bleed; the sailors' disease."),

    ("nutrients-balanced-diet", "easy",
     "रतौंधी (night blindness) — रात में या मद्धम रोशनी में न दिखना — किस विटामिन की कमी का संकेत है?",
     "Night blindness — not seeing at night or in dim light — signals the deficiency of which vitamin?",
     ["विटामिन C", "विटामिन A", "विटामिन D", "विटामिन B1"],
     ["Vitamin C", "Vitamin A", "Vitamin D", "Vitamin B1"],
     1,
     "रेटिना का प्रकाश-ग्रहण विटामिन A पर निर्भर है — कमी में धुंधलके में दृष्टि गिरती है।",
     "The retina's light-catching depends on vitamin A — in its deficiency dim-light vision falls."),

    ("nutrients-balanced-diet", "easy",
     "संतुलित आहार में रेशा (roughage) क्यों ज़रूरी माना जाता है?",
     "Why is roughage considered necessary in a balanced diet?",
     ["वह ऊर्जा देता है", "वह पचता नहीं, पर मल को ठोस-चिकना बनाकर मल-त्याग को नियमित रखता है", "वह रुधिर बनाता है", "वह हड्डियाँ बनाता है"],
     ["It gives energy", "It is not digested, yet keeps the stool solid-smooth and bowel movement regular", "It makes blood", "It makes bones"],
     1,
     "सलाद-सब्ज़ी-फल का रेशा आँत की सफाई करता है — कब्ज और मल-त्याग की गड़बड़ी से बचाता है।",
     "The fibre of salad-vegetables-fruit scrubs the intestine clean — guarding constipation and bowel trouble."),

    ("nutrients-balanced-diet", "easy",
     "आयोडीन युक्त नमक क्यों खाने की सलाह दी जाती है?",
     "Why is iodised salt advised for eating?",
     ["नमक का स्वाद बढ़ाने को", "आयोडीन की कमी से बचने को — आयोडीन शरीर के लिए अनिवार्य सूक्ष्म-तत्व है", "नमक को सफेद बनाने को", "भूख बढ़ाने को"],
     ["To improve the salt's taste", "To avoid iodine deficiency — iodine is an essential trace element for the body", "To whiten the salt", "To increase appetite"],
     1,
     "मिट्टी-जल में आयोडीन कहीं-कहीं कम होता है — आयोडीनयुक्त नमक सस्ता और सरल रक्षण-उपाय है।",
     "Soil and water are iodine-poor in places — iodised salt is a cheap and simple protective measure."),

    ("nutrients-balanced-diet", "medium",
     "विटामिनों में से कौन-से वसा में घुलनशील (fat-soluble) हैं?",
     "Which among vitamins are fat-soluble?",
     ["B और C", "A, D, E और K", "केवल C", "सभी जल में घुलनशील"],
     ["B and C", "A, D, E and K", "Only C", "All are water-soluble"],
     1,
     "A, D, E, K वसा-घुलनशील — भोजन की वसा के साथ ही सोखे जाते हैं और शरीर में संग्रहित रह सकते हैं।",
     "A, D, E, K are fat-soluble — absorbed along with dietary fat and can stay stored in the body."),

    ("nutrients-balanced-diet", "medium",
     "कौन-से विटामिन जल में घुलनशील (water-soluble) हैं और शरीर में अधिक देर संग्रहित नहीं रहते?",
     "Which vitamins are water-soluble and do not stay stored in the body for long?",
     ["A और D", "B और C", "E और K", "A और K"],
     ["A and D", "B and C", "E and K", "A and K"],
     1,
     "B-समूह और C जल में घुलकर मूत्र के रास्ते बाहर निकल जाते हैं — रोज़ के आहार में इनकी आपूर्ति चाहिए।",
     "B-group and C dissolve in water and leave via urine — they must be supplied in the daily diet."),

    ("nutrients-balanced-diet", "medium",
     "धूप में खेलने वाले बच्चों को विटामिन D की कमी कम क्यों दिखती है?",
     "Why do children who play in sunlight show less vitamin D deficiency?",
     ["धूप से भूख लगती है", "त्वचा में सूर्य-प्रकाश विटामिन D बनाने में सहायक है", "धूप में हड्डियाँ गर्म होती हैं", "धूप से रुधिर लाल होता है"],
     ["Sunlight makes them hungry", "Sunlight on the skin helps the body make vitamin D", "The bones warm up in sun", "The blood turns red in sun"],
     1,
     "शरीर धूप की सहायता से स्वयं विटामिन D संश्लेषित कर लेता है — इसीलिए इसे 'धूप-विटामिन' कहते हैं।",
     "The body itself synthesises vitamin D with the help of sun — hence it is called the 'sunshine vitamin'."),

    ("nutrients-balanced-diet", "medium",
     "बेरी-बेरी (Beriberi) किस विटामिन की कमी से होता है?",
     "Beriberi is caused by the deficiency of which vitamin?",
     ["विटामिन B1 (थायमिन)", "विटामिन C", "विटामिन D", "विटामिन A"],
     ["Vitamin B1 (thiamine)", "Vitamin C", "Vitamin D", "Vitamin A"],
     0,
     "थायमिन की कमी में नसों की कमजोरी-सुन्नता और मांसपेशी शिथिलता होती है — पॉली-चावल खाने वालों का शास्त्रीय रोग।",
     "Thiamine deficiency weakens nerves (numbness) and flaccids muscles — the classic disease of polished-rice eaters."),

    ("nutrients-balanced-diet", "medium",
     "हड्डियों और दाँतों के निर्माण के लिए आवश्यक मुख्य खनिज कौन-सा है?",
     "Which is the chief mineral required for building bones and teeth?",
     ["लोहा", "कैल्शियम", "आयोडीन", "जिंक"],
     ["Iron", "Calcium", "Iodine", "Zinc"],
     1,
     "कैल्शियम और फॉस्फोरस मिलकर हड्डी-दाँत की कठोरता बनाते हैं; विटामिन D उस कैल्शियम को अवशोषित कराता है।",
     "Calcium with phosphorus builds bone-tooth hardness; vitamin D gets that calcium absorbed."),

    ("nutrients-balanced-diet", "medium",
     "आहार में लोहे की निरंतर कमी रहने पर क्या होता है?",
     "What happens if dietary iron remains deficient for long?",
     ["रिकेट्स होता है", "रुधिर में हीमोग्लोबिन घटता है — गंभीर रक्ताल्पता (anaemia) की स्थिति", "गलगंड हो जाता है", "रतौंधी हो जाती है"],
     ["Rickets occurs", "Haemoglobin in the blood falls — a state of serious anaemia", "Goitre occurs", "Night blindness occurs"],
     1,
     "नई रुधिर-कणिकाएँ लोहे के बिना हीमोग्लोबन नहीं बना पातीं — शरीर में ऑक्सीजन-क्षमता गिरती है, थकान-कमजोरी छाती है।",
     "Without iron, new red cells cannot build haemoglobin — the body's oxygen capacity drops, fatigue-weakness takes over."),

    ("nutrients-balanced-diet", "medium",
     "गलगंड (goitre) — गर्दन का फूलना — किस खनिज की कमी से होता है?",
     "Goitre — swelling of the neck — is caused by the deficiency of which mineral?",
     ["कैल्शियम", "लोहा", "आयोडीन", "पोटैशियम"],
     ["Calcium", "Iron", "Iodine", "Potassium"],
     2,
     "आयोडीन की कमी में गर्दन की ग्रंथि बढ़ जाती है और गला फूल उठता है — आयोडीनयुक्त नमक इसका बचाव है।",
     "In iodine deficiency the neck gland enlarges and the throat swells — iodised salt is the prevention."),

    ("nutrients-balanced-diet", "medium",
     "भोजन में प्रोटीन के लंबे अभाव में बच्चों में क्या दिखता है?",
     "What is seen in children after a long absence of protein in the diet?",
     ["बच्चा मोटा हो जाता है", "वृद्धि रुकती है, पेट फूलता है, बाल-त्वचा खराब — प्रोटीन-कमी के लक्षण", "दाँत चमकते हैं", "कोई असर नहीं"],
     ["The child becomes fat", "Growth stunts, belly swells, hair-skin spoil — signs of protein deficiency", "Teeth shine", "No effect"],
     1,
     "प्रोटीन ही वृद्धि की ईंट है — उसके अभाव में शरीर अपने ही ऊतक खा जाता है और गंभीर कुपोषण उभरता है।",
     "Protein is the brick of growth — without it the body consumes its own tissue and severe malnutrition emerges."),

    ("nutrients-balanced-diet", "medium",
     "निरंतर अधिक खाने और ऊर्जा-व्यय के अभाव से बनने वाली स्थिति क्या कहलाती है?",
     "What is the condition called that arises from continual overeating without matching energy spending?",
     ["रक्ताल्पता", "मोटापा (obesity)", "रिकेट्स", "गलगंड"],
     ["Anaemia", "Obesity", "Rickets", "Goitre"],
     1,
     "अतिरिक्त कैलोरी वसा बनकर जमा होती है — शरीर का वजन स्वस्थ सीमा से ऊपर चला जाता है।",
     "Extra calories pile up as stored fat — body weight crosses the healthy mark."),

    ("nutrients-balanced-diet", "medium",
     "एक बढ़ते बच्चे और एक वयस्क कार्यालय-कर्मी की पोषण-आवश्यकताएँ समान क्यों नहीं होतीं?",
     "Why are the nutrition needs of a growing child and an adult office-worker not the same?",
     ["दोनों की ऊँचाई भिन्न है", "आयु, शारीरिक श्रम और वृद्धि-चरण भिन्न हैं — आहार इन्हीं पर निर्भर करता है", "बच्चों को स्वाद ज्यादा चाहिए", "वयस्क को भूख कम लगती है"],
     ["Their heights differ", "Age, physical labour and growth-stage differ — the diet depends on these", "Children need more taste", "Adults feel less hungry"],
     1,
     "संतुलित आहार सापेक्ष धारणा है — धात्री-माँ, खिलाड़ी, बच्चा सबकी 'संतुलन-राशि' भिन्न है।",
     "A balanced diet is a relative idea — a nursing mother, an athlete, a child each has a different 'balance amount'."),

    ("nutrients-balanced-diet", "medium",
     "रेशा (roughage) पचता नहीं — फिर भी उपयोगी कैसे?",
     "Roughage is not digested — how is it still useful?",
     ["वह जल में घुलकर ऊर्जा देता है", "वह आँत की दीवार को भरती-खाली करते हुए मल को थोक देकर आगे धकेलता है — पाचन-मार्ग सक्रिय-साफ रहता है", "वह प्रोटीन बनाता है", "वह विटामिन का काम करता है"],
     ["It dissolves in water to give energy", "It gives the stool bulk and pushes it along, exercising the gut wall — the digestive tract stays active and clean", "It makes protein", "It works like a vitamin"],
     1,
     "रेशा आँत की 'झाड़ू' है — पचता नहीं, पर सफाई और नियमितता दोनों देता है।",
     "Roughage is the gut's 'broom' — undigested, yet it delivers both cleaning and regularity."),

    ("nutrients-balanced-diet", "medium",
     "जल को पोषक तत्व क्यों गिना जाता है?",
     "Why is water counted as a nutrient?",
     ["क्योंकि वह भोजन का स्वाद बनाता है", "क्योंकि वह भोजन के घटकों के परिवहन, पाचन-अभिक्रियाओं और ताप-नियमन का माध्यम है", "क्योंकि वह रंगीन होता है", "क्योंकि वह गर्म होता है"],
     ["Because it adds taste to food", "Because it is the medium for transporting food's components, digestion reactions and temperature control", "Because it is coloured", "Because it is warm"],
     1,
     "जल शरीर की हर अभिक्रिया का विलायक है — पोषक तत्वों की सवारी से लेकर मल-त्याग तक जल के बिना अधूरा।",
     "Water is the solvent of every body reaction — from the ride of nutrients to waste exit, nothing completes without it."),

    ("nutrients-balanced-diet", "medium",
     "'पोषक-तत्व-कमी रोग' (deficiency disease) की परिभाषा क्या है?",
     "What is the definition of a 'deficiency disease'?",
     ["संक्रमण से फैलने वाला रोग", "आहार में किसी विशिष्ट पोषक तत्व के दीर्घकालिक अभाव से उत्पन्न रोग", "वंशानुगत रोग", "दुर्घटना का रोग"],
     ["A disease spread by infection", "A disease produced by the long absence of a specific nutrient in the diet", "A hereditary disease", "An accidental disease"],
     1,
     "कमी-रोग संक्रमण से नहीं, थाली की कमी से आते हैं — स्कर्वी, रिकेट्स, गलगंड, रक्ताल्पता इसी की मिसालें।",
     "Deficiency diseases come not from infection but from the plate's shortfall — scurvy, rickets, goitre, anaemia are the examples."),

    ("nutrients-balanced-diet", "medium",
     "स्कर्वी से बचाने वाले विटामिन (C) के प्राकृतिक आहार-स्रोत कौन-से हैं?",
     "Which natural foods supply the vitamin (C) that protects against scurvy?",
     ["चावल और गेहूँ", "आँवला, नींबू, संतरा जैसे खट्टे फल और ताज़ी हरी सब्ज़ियाँ", "देसी घी", "चीनी"],
     ["Rice and wheat", "Amla, lemon, orange-type citrus fruits and fresh green vegetables", "Ghee", "Sugar"],
     1,
     "खट्टे फल-हरी सब्ज़ियाँ सी-विटामिन के भंडार हैं — इसीलिए स्कर्वी से बचने रोज़ चाहिए।",
     "Citrus fruits and greens are the storehouse of vitamin C — needed daily to keep scurvy away."),

    ("nutrients-balanced-diet", "medium",
     "विटामिन A के अच्छे स्रोत कौन-से हैं?",
     "Which are good sources of vitamin A?",
     ["गाजर, पपीता, हरी पत्तेदार सब्ज़ियाँ और दूध", "चीनी और नमक", "बेकिंग सोडा", "साधारण पानी"],
     ["Carrot, papaya, green leafy vegetables and milk", "Sugar and salt", "Baking soda", "Plain water"],
     0,
     "गाजर-पपीते का पीला-नारंगी रंग बीटा-कैरोटिन से है — शरीर उसी से विटामिन A बना लेता है।",
     "The yellow-orange of carrot-papaya is beta-carotene — the body makes vitamin A from it."),

    ("nutrients-balanced-diet", "medium",
     "लोहे के अच्छे आहार-स्रोत कौन-से हैं?",
     "Which are good dietary sources of iron?",
     ["पालक, गुड़, चना और कुछ अनाज", "केवल दूध", "केवल फल", "चीनी-गुड़ से कोई अंतर नहीं"],
     ["Spinach, jaggery, gram and some grains", "Only milk", "Only fruits", "No difference between sugar and jaggery"],
     0,
     "हरी पत्तेदार सब्ज़ियाँ-गुड़-दालें लोहे की थाली हैं — इनके अभाव में रक्ताल्पता दरवाज़े पर है।",
     "Green leaves, jaggery and pulses are the iron-plate — without them anaemia is at the door."),

    ("nutrients-balanced-diet", "medium",
     "कार्बोहाइड्रेट के प्रमुख आहार-स्रोत कौन-से हैं?",
     "Which are the chief dietary sources of carbohydrates?",
     ["चावल, गेहूँ, आलू, चीनी जैसे अनाज-कंद-मीठे", "केवल अंडे", "केवल घी", "केवल नमक"],
     ["Rice, wheat, potato, sugar — grains, tubers and sweets", "Only eggs", "Only ghee", "Only salt"],
     0,
     "अनाज-कंद-चीनी कार्बोहाइड्रेट का मुख्य आधार हैं — थाली का ऊर्जा-हिस्सा यही भरता है।",
     "Grains, tubers and sugar form the mainstay of carbohydrates — they fill the plate's energy share."),

    ("nutrients-balanced-diet", "medium",
     "प्रोटीन के अच्छे आहार-स्रोत कौन-से हैं?",
     "Which are good dietary sources of protein?",
     ["दालें, दूध-दही, अंडा, मछली, सोयाबीन", "चीनी और शहद", "नमक और मिर्च", "केवल पानी"],
     ["Pulses, milk-curd, egg, fish, soybean", "Sugar and honey", "Salt and chilli", "Only water"],
     0,
     "दाल-दूध-अंडा-मछली-सोया प्रोटीन-घन स्रोत हैं — शाकाहारी-मांसाहारी दोनों थालियों में विकल्प मौजूद।",
     "Pulse-milk-egg-fish-soya are protein-dense sources — both vegetarian and non-vegetarian plates have options."),

    ("nutrients-balanced-diet", "hard",
     "ग्राम-प्रति-ग्राम ऊर्जा की दृष्टि से वसा और कार्बोहाइड्रेट की तुलना क्या है?",
     "Gram for gram, how do fat and carbohydrate compare in energy?",
     ["दोनों बराबर", "वसा लगभग दुगुनी ऊर्जा देती है — इसीलिए संग्रह-रूप में वसा किफायती है", "कार्बोहाइड्रेट दुगुनी देता है", "वसा ऊर्जा देती ही नहीं"],
     ["Both equal", "Fat gives nearly double the energy — that is why fat is economical as the storage form", "Carbohydrate gives double", "Fat gives no energy"],
     1,
     "समान भार में वसा कैलोरी-घनत्व लगभग दोगुना रखती है — प्रकृति ने भंडार वसा में ही बनाया।",
     "Per equal weight fat holds nearly twice the calorie density — nature built the storehouse in fat."),

    ("nutrients-balanced-diet", "hard",
     "तत्काल ऊर्जा कार्बोहाइड्रेट से और संग्रह वसा में — यह व्यवस्था क्यों?",
     "Instant energy from carbohydrates but storage as fat — why this arrangement?",
     ["वसा स्वादिष्ट होती है", "ग्लूकोस घुलनशील-तुरंत-उपलब्ध है, पर उसे जमा करने में बहुत जल-भार लगता; वसा जल-रहित, सघन — संग्रह हेतु उपयुक्त", "कार्बोहाइड्रेट भारी होता है", "वसा हल्की रंग की होती है"],
     ["Fat is tasty", "Glucose is soluble and instantly available, but stocking it needs much water-weight; fat is water-free and compact — fit for storage", "Carbohydrate is heavy", "Fat is light-coloured"],
     1,
     "घुलनशील ग्लूकोस जल्दी खर्च हो जाता; अति-शेष वसा-रूप में सघन बंधकर रखा जाता है — दोनों अपनी जगह सही।",
     "Soluble glucose spends fast; the surplus is locked compactly as fat — each right in its place."),

    ("nutrients-balanced-diet", "hard",
     "क्वाशियोर्कर और मरास्मस दोनों गंभीर कुपोषण हैं — इनमें मूल अंतर क्या है?",
     "Kwashiorkor and marasmus are both severe malnutrition — what is the basic difference?",
     ["दोनों एक ही हैं", "क्वाशियोर्कर मुख्यतः प्रोटीन की कमी (कैलोरी कुछ-बहुत मिली) — पेट फूला, शरीर सूजन; मरास्मस में प्रोटीन-कैलोरी दोनों की भारी कमी — शरीर छलकर त्वचा-हड्डी रह जाता", "क्वाशियोर्कर वयस्कों का रोग है", "मरास्मस विटामिन-अधिकता है"],
     ["Both are the same", "Kwashiorkor is mainly protein deficiency (some calories still coming) — swollen belly, puffy body; marasmus is severe shortage of both protein and calories — the body shrinks to skin and bones", "Kwashiorkor is an adult disease", "Marasmus is vitamin excess"],
     1,
     "क्वाशियोर्कर = असंतुलित-थाली (प्रोटीन-विशेष अभाव); मरास्मस = लगभग खाली-थाली (सर्व-अभाव) — सूजन बनाम सूखना।",
     "Kwashiorkor = unbalanced plate (protein specially absent); marasmus = near-empty plate (total scarcity) — swelling versus shrinking."),

    ("nutrients-balanced-diet", "hard",
     "विटामिन B और C की 'अधिक मात्रा' शरीर के लिए चिंता का विषय कम क्यों होती है?",
     "Why is an 'excess' of vitamins B and C less of a worry for the body?",
     ["वे वसा में जमा हो जाते हैं", "वे जल में घुलनशील हैं — आवश्यकता से अधिक मात्रा मूत्र के साथ बाहर निकल जाती है", "वे कभी खाए नहीं जा सकते", "शरीर उन्हें पचा नहीं पाता"],
     ["They get stored in fat", "They are water-soluble — amounts beyond need pass out with urine", "They can never be eaten", "The body cannot digest them"],
     1,
     "जल-घुलनशील विटामिन का बहिर्मार्ग मूत्र है — संग्रह-विषाक्तता का खतरा न्यून।",
     "Water-soluble vitamins exit via urine — little risk of storage-toxicity."),

    ("nutrients-balanced-diet", "hard",
     "वसा-घुलनशील विटामिनों (A, D, E, K) का अति-सेवन जोखिम भरा क्यों माना जाता है?",
     "Why is over-intake of fat-soluble vitamins (A, D, E, K) considered risky?",
     ["वे तुरंत निकल जाते हैं", "वे शरीर की वसा-भंडारों में जमा होते हैं और बाहर का मार्ग नहीं मिलता — संचित मात्रा विषाक्तता पैदा कर सकती है", "वे भोजन में नहीं होते", "वे जल में घुल जाते हैं"],
     ["They pass out at once", "They deposit in the body's fat stores with no easy exit — the accumulated amount can turn toxic", "They are absent in food", "They dissolve in water"],
     1,
     "जमा होने वाले पोषक का अति शरीर में रुकता है — इसीलिए वसा-घुलनशील विटामिन-सप्लिमेंट सोच-समझकर।",
     "Excess of a storable nutrient lingers in the body — hence fat-soluble vitamin supplements demand caution."),

    # ---------------- human-digestive-system (35: E12/M18/H5) ----------------
    ("human-digestive-system", "easy",
     "मानव के पाचन-मार्ग (alimentary canal) के मुख्य भागों का सही क्रम कौन-सा है?",
     "Which is the correct order of the main parts of the human alimentary canal?",
     ["मुख → ग्रसनी → गुल्फा (oesophagus) → आमाशय → क्षुद्रांत → बृहदांत → मलाशय → मलद्वार", "मुख → आमाशय → ग्रसनी → बृहदांत → गुल्फा → क्षुद्रांत", "आमाशय → मुख → क्षुद्रांत → गुल्फा", "मलद्वार → मलाशय → आमाशय → मुख"],
     ["Mouth → pharynx → oesophagus → stomach → small intestine → large intestine → rectum → anus", "Mouth → stomach → pharynx → large intestine → oesophagus → small intestine", "Stomach → mouth → small intestine → oesophagus", "Anus → rectum → stomach → mouth"],
     0,
     "भोजन की यात्रा एक ही सीधी सुरंग में होती है — मुख से मलद्वार तक यही क्रम अटल है।",
     "The food's journey runs through one straight tunnel — mouth to anus, this order is fixed."),

    ("human-digestive-system", "easy",
     "पाचन की शुरुआत शरीर के किस भाग से होती है?",
     "Where does digestion begin in the body?",
     ["पेट से", "मुख (मुँह) से — दाँत चबाते हैं और लार मिलती है", "क्षुद्रांत से", "बृहदांत से"],
     ["In the stomach", "In the mouth — teeth chew and saliva mixes in", "In the small intestine", "In the large intestine"],
     1,
     "पहला चबाना ही पाचन का पहला चरण है — यांत्रिक और रासायनिक पाचन दोनों मुँह में ही शुरू होते हैं।",
     "The first chew is digestion's first step — both mechanical and chemical digestion start in the mouth."),

    ("human-digestive-system", "easy",
     "भोजन काटने का काम किन दाँतों का है?",
     "Which teeth do the job of cutting food?",
     ["अग्रचर्वणक (incisors)", "रदनक (canines)", "जवाला (molars)", "दाढ़ (premolars)"],
     ["Incisors", "Canines", "Molars", "Premolars"],
     0,
     "आगे की चौकोर-किनारेदार अग्रचर्वणक कैंची की तरह काटते हैं — 'काटने वाले दाँत'।",
     "The front squarish edged incisors cut like scissors — the 'cutting teeth'."),

    ("human-digestive-system", "easy",
     "मांस फाड़ने का कार्य किन दाँतों द्वारा होता है?",
     "Tearing of meat is done by which teeth?",
     ["अग्रचर्वणक", "नुकीले रदनक (canines)", "जवाला", "दाढ़"],
     ["Incisors", "The pointed canines", "Molars", "Premolars"],
     1,
     "रदनक नुकीले-टेढ़े होते हैं — फाड़ने-चीरने के लिए बने; मांसाहारियों में विशेष विकसित।",
     "Canines are pointed and curved — built for tearing; specially developed in carnivores."),

    ("human-digestive-system", "easy",
     "भोजन कूट-पीसकर चूर्ण बनाने का काम किन दाँतों का है?",
     "Which teeth grind and crush food into particles?",
     ["अग्रचर्वणक", "रदनक", "पीछे के चौड़े जवाला और दाढ़", "कोई नहीं"],
     ["Incisors", "Canines", "The broad molars and premolars at the back", "None"],
     2,
     "पीछे की चौड़ी-ऊबड़ चपटी सतहें चक्की की तरह पीसती हैं — चबाने का असली काम यहीं होता है।",
     "The broad bumpy surfaces at the back grind like a millstone — the real chewing happens there."),

    ("human-digestive-system", "easy",
     "जीभ (tongue) मुख-गुहा में क्या मुख्य कार्य करती है?",
     "What is the tongue's main job in the mouth?",
     ["भोजन पचाती है", "चबाए भोजन को लार से मिलाकर गोला (bolus) बनाती है और स्वाद का बोध कराती है", "भोजन निगलती है अकेले", "लार बनाती है"],
     ["It digests food", "Mixes chewed food with saliva into a ball (bolus) and gives the sense of taste", "Swallows food alone", "Makes saliva"],
     1,
     "जीभ मुँह की मिक्सर है — घुमा-घुमाकर सब मिलाती है और स्वाद-कलिकाएँ स्वाद पहचानती हैं।",
     "The tongue is the mouth's mixer — it turns and blends everything, while taste buds identify flavours."),

    ("human-digestive-system", "easy",
     "लार (saliva) मुँह में भोजन के लिए सबसे पहले क्या करती है?",
     "What does saliva first do to the food in the mouth?",
     ["उसे जमा देती है", "सूखे भोजन को गीला-चिकना बनाकर निगलने योग्य बनाती है", "उसे ठंडा करती है", "उसे मीठा बनाती है"],
     ["It solidifies it", "Wets the dry food into a slippery, swallowable paste", "It cools it", "It sweetens it"],
     1,
     "लार का जल भोजन को रुमाल-गीला बनाता है — चिकनापन निगलने की सवारी आसान करता है।",
     "Saliva's water makes the food moist — the slipperiness eases the swallow's ride."),

    ("human-digestive-system", "easy",
     "गुल्फा (oesophagus) का मुख्य कार्य क्या है?",
     "What is the main function of the oesophagus?",
     ["भोजन पचाना", "मुँह से आमाशय तक भोजन की नली-यात्रा कराना", "लार बनाना", "पित्त भेजना"],
     ["Digesting food", "Carrying the food through the tube from mouth to stomach", "Making saliva", "Sending bile"],
     1,
     "गुल्फा केवल मार्ग है — भोजन यहाँ रुकता नहीं, लहरों से नीचे खिसकता है।",
     "The oesophagus is only a passage — food doesn't halt here, it ripples downward."),

    ("human-digestive-system", "easy",
     "आमाशय (stomach) शरीर में क्या भूमिका निभाता है?",
     "What role does the stomach play in the body?",
     ["केवल भोजन भंडारित करता है", "भोजन को पेशी-भित्ति से मसलता है, अम्ल और पाचक-रस मिलाकर गाढ़ा मिश्रण बनाता है", "केवल पानी सोखता है", "मल बनाता है"],
     ["Only stores food", "Kneads the food with its muscular wall, adding acid and digestive juice into a thick mix", "Only absorbs water", "Forms faeces"],
     1,
     "पेट भोजन की गाड़ी-भट्टी है — मसलना + अम्ल + एंजाइम तीनों का मिला-जुला प्रहार।",
     "The stomach is the food's kneading-vat — the combined assault of churning + acid + enzyme."),

    ("human-digestive-system", "easy",
     "पाचन-तंत्र का सबसे लंबा भाग कौन-सा है और अवशोषण मुख्यतः कहाँ होती है?",
     "Which is the longest part of the digestive tract, and where does absorption mainly occur?",
     ["आमाशय — वहीं अवशोषण", "क्षुद्रांत (small intestine) — सबसे लंबा और अवशोषण का मुख्य स्थल", "गुल्फा — वहीं अवशोषण", "मलाशय — वहीं अवशोषण"],
     ["The stomach — absorption there", "The small intestine — the longest part and the main site of absorption", "The oesophagus — absorption there", "The rectum — absorption there"],
     1,
     "क्षुद्रांत लंबी, वलित नली है — पाचन की परिष्कर्ता और अवशोषण की मेज़ दोनों यही।",
     "The small intestine is a long folded tube — both digestion's finishing table and absorption's counter."),

    ("human-digestive-system", "easy",
     "बृहदांत (large intestine) का मुख्य कार्य क्या है?",
     "What is the main function of the large intestine?",
     ["प्रोटीन पचाना", "अपचे भोजन-अवशेष से जल और खनिज सोखकर मल को गाढ़ा करना", "वसा जमा करना", "लार बनाना"],
     ["Digesting proteins", "Absorbing water and minerals from the undigested residue, thickening it into faeces", "Storing fats", "Making saliva"],
     1,
     "बृहदांत जल-बचत की इकाई है — बचा-खुचा अंश सूखकर मल बनता है।",
     "The large intestine is the water-recovery unit — the leftover dries into faeces."),

    ("human-digestive-system", "easy",
     "मल-त्याग (egestion) शरीर से किस मार्ग से होता है?",
     "Through which route does egestion occur from the body?",
     ["मुँह से", "मलाशय से मलद्वार (anus) द्वारा", "त्वचा से", "मूत्र-मार्ग से"],
     ["Through the mouth", "From the rectum via the anus", "Through the skin", "Through the urinary tract"],
     1,
     "अपचा मल मलाशय में जमा होकर मलद्वार से बाहर निकलता है — पाचन-मार्ग का अंतिम द्वार।",
     "The undigested faeces collect in the rectum and exit via the anus — the canal's final gate."),

    ("human-digestive-system", "medium",
     "वयस्क मानव में स्थायी दाँतों की कुल संख्या कितनी होती है?",
     "What is the total number of permanent teeth in an adult human?",
     ["20", "28", "32", "16"],
     ["20", "28", "32", "16"],
     2,
     "32 दाँत — प्रत्येक धड़ में 4 अग्रचर्वणक, 2 रदनक, 4 दाढ़, 6 जवाला; दूध-दाँत केवल 20 होते हैं।",
     "32 teeth — per jaw 4 incisors, 2 canines, 4 premolars, 6 molars; milk teeth are only 20."),

    ("human-digestive-system", "medium",
     "बच्चों के दूध-दाँत और वयस्क स्थायी दाँतों में क्या संबंध है?",
     "What is the relation between children's milk teeth and adult permanent teeth?",
     ["दूध-दाँत जीवन भर रहते हैं", "दूध-दाँत (20) समय पर झड़कर स्थायी दाँतों (32) से बदल जाते हैं", "स्थायी दाँत पहले आते हैं", "दोनों एक साथ उगते हैं"],
     ["Milk teeth last lifelong", "Milk teeth (20) fall in time and are replaced by permanent teeth (32)", "Permanent teeth come first", "Both erupt together"],
     1,
     "छह-बारह वर्ष की उम्र में दूध-दाँत झड़ते हैं — नीचे स्थायी-सेट तैयार हो चुका होता है।",
     "Between ages six-twelve milk teeth drop — the permanent set waiting below is ready."),

    ("human-digestive-system", "medium",
     "चबाया हुआ भोजन + लार से बना गोला क्या कहलाता है?",
     "What is the ball of chewed food mixed with saliva called?",
     ["चाइम (chyme)", "बोलस (bolus)", "रस (chyle)", "मल"],
     ["Chyme", "Bolus", "Chyle", "Faeces"],
     1,
     "मुँह का तैयार निगलने-योग्य गोला = बोलस; पेट के अम्ल-मिश्रण को बाद में चाइम कहते हैं।",
     "The mouth-made swallowable ball = bolus; the stomach's acid mix is later called chyme."),

    ("human-digestive-system", "medium",
     "जीभ भोजन के स्वाद की पहचान किन संरचनाओं से करती है?",
     "By which structures does the tongue identify tastes?",
     ["रुधिर-नलिकाओं से", "स्वाद-कलिकाओं (taste buds) से", "बालों से", "दाँतों से"],
     ["Blood vessels", "Taste buds", "Hairs", "Teeth"],
     1,
     "जीभ की सतह पर बौने-किलों जैसी स्वाद-कलिकाएँ बैठी हैं — मीठा-खट्टा-कड़वा-नमकीन इन्हीं की पहचान।",
     "Bud-like taste spots sit on the tongue's surface — sweet-sour-bitter-salty are their reading."),

    ("human-digestive-system", "medium",
     "निगला गया बोलस गुल्फा से आमाशय तक कैसे पहुँचता है?",
     "How does the swallowed bolus reach the stomach through the oesophagus?",
     ["गुरुत्वाकर्षण से गिरता है", "गुल्फा-भित्ति की ऊपर-नीचे लहरेंदार पेशी-गति उसे धकेलती है — खड़े खाने पर भी", "लार उसे खींचती है", "वायु-दाब से चलता है"],
     ["It falls by gravity", "Wave-like muscular movement of the oesophagus wall pushes it — even when eating standing", "Saliva pulls it", "Air pressure moves it"],
     1,
     "गुल्फा की पेशी-लहर बोलस को मुट्ठी-सिकोड़ क्रम से नीचे धकेलती है — सिर के नीचे लटकने पर भी भोजन पेट पहुँचता है।",
     "The oesophagus's muscle-wave squeezes the bolus downward in sequence — food reaches the stomach even upside down."),

    ("human-digestive-system", "medium",
     "पेट की भीतरी दीवार पर म्यूकस (श्लेष्म) क्यों होता है?",
     "Why is there mucus on the stomach's inner wall?",
     ["स्वाद के लिए", "भित्ति को अपने ही प्रबल अम्ल और एंजाइम से बचाने के लिए पट्टीबंदी करता है", "भोजन को मीठा बनाने को", "लार बनाने को"],
     ["For taste", "It coats the wall, shielding it from its own strong acid and enzymes", "To sweeten the food", "To make saliva"],
     1,
     "पेट प्रबल अम्ल बनाता है — म्यूकस की परत उसी अम्ल से पेट-भित्ति की रक्षा करती है।",
     "The stomach makes strong acid — the mucus layer guards the stomach wall from that very acid."),

    ("human-digestive-system", "medium",
     "आमाशय से क्षुद्रांत में भोजन का द्वार नियंत्रित करने वाली संरचना क्या है?",
     "What is the structure controlling the gateway from stomach to small intestine?",
     ["एपिग्लॉटिस", "पाइलोरिक संकुची (pyloric sphincter)", "रदनक", "स्वाद-कलिका"],
     ["Epiglottis", "The pyloric sphincter", "Canines", "Taste buds"],
     1,
     "पाइलोरिक छल्ला-मांसपेशी द्वार खोलती-बंद करती है — थोड़ा-थोड़ा चाइम आगे जाता है।",
     "The pyloric ring-muscle opens and shuts the gate — chyme moves on little by little."),

    ("human-digestive-system", "medium",
     "क्षुद्रांत की भीतरी सतह पर उँगलियों जैसी उभार क्या कहलाते हैं?",
     "What are the finger-like projections on the small intestine's inner surface called?",
     ["रोम (villi)", "रदनक", "अलिंद", "पट"],
     ["Villi", "Canines", "Atria", "Septa"],
     0,
     "लाखों विलाई (villi) भीतरी सतह को मखमली-गुत्थी बनाते हैं — अवशोषण-क्षेत्र विराट।",
     "Millions of villi make the inner surface velvety — a giant absorption area."),

    ("human-digestive-system", "medium",
     "विलाई (villi) के भीतर घने रुधिर-वाहिकाएँ क्यों होती हैं?",
     "Why do villi contain dense blood vessels?",
     ["पेट को गर्म रखने को", "पचे हुए पोषक तत्वों को तुरंत रुधिर में उठाने के लिए — सोखे हुए का सीधा प्रवेश-द्वार", "भोजन जमा करने को", "लार भेजने को"],
     ["To keep the gut warm", "To lift the digested nutrients straight into the blood — a direct entry gate for whatever is absorbed", "To store food", "To send saliva"],
     1,
     "हर विलस के केंद्र में रुधिर-केशिका — सोखा पोषक तत्व पास की ही नली में उतर जाता है।",
     "A blood capillary at every villus core — absorbed nutrients drop into the nearby pipe at once."),

    ("human-digestive-system", "medium",
     "शरीर की सबसे बड़ी ग्रंथि कौन-सी है?",
     "Which is the largest gland of the body?",
     ["अग्नाशय (pancreas)", "यकृत (liver)", "लार-ग्रंथि", "थायरॉइड"],
     ["The pancreas", "The liver", "The salivary gland", "The thyroid"],
     1,
     "यकृत सबसे बड़ी ग्रंथि है — पित्त बनाना और शरीर के चयापचय की मुख्य रसोई दोनों उसके प्रभारे।",
     "The liver is the largest gland — making bile and running the body's metabolic kitchen."),

    ("human-digestive-system", "medium",
     "पित्त (bile) कहाँ बनता है और कहाँ संग्रहित रहता है?",
     "Where is bile made and where is it stored?",
     ["अग्नाशय में बनता — पित्ताशय में जमा", "यकृत में बनता — पित्ताशय (gall bladder) में जमा", "पेट में बनता — यकृत में जमा", "क्षुद्रांत में बनता — मलाशय में जमा"],
     ["Made in the pancreas — stored in the gall bladder", "Made in the liver — stored in the gall bladder", "Made in the stomach — stored in the liver", "Made in the small intestine — stored in the rectum"],
     1,
     "पित्त का निर्माण-स्थल यकृत, भंडार-थैली पित्ताशय — भोजन आते ही थैली खोलती है।",
     "Bile's factory is the liver, its storage bag the gall bladder — the bag opens as food arrives."),

    ("human-digestive-system", "medium",
     "पित्ताशय (gall bladder) का अपना कार्य क्या है?",
     "What is the gall bladder's own job?",
     ["पित्त बनाना", "यकृत-बना पित्त सांद्रित करके भंडारित करना और आवश्यकता पर क्षुद्रांत में छोड़ना", "इंसुलिन बनाना", "लार बनाना"],
     ["Making bile", "Storing and concentrating the liver-made bile, releasing it into the small intestine when needed", "Making insulin", "Making saliva"],
     1,
     "पित्ताशय केवल भंडार-थैली है — निर्माता यकृत है।",
     "The gall bladder is only the storage bag — the maker is the liver."),

    ("human-digestive-system", "medium",
     "अग्नाशय (pancreas) का पाचन में योगदान क्या है?",
     "What is the pancreas's contribution to digestion?",
     ["वह लार बनाता है", "वह पाचक-रस (अग्नाशय-रस) बनाकर क्षुद्रांत में छोड़ता है", "वह मल बनाता है", "वह केवल वसा जमा करता है"],
     ["It makes saliva", "It makes pancreatic juice and pours it into the small intestine", "It forms faeces", "It only stores fat"],
     1,
     "अग्नाशय-रस में कार्बोहाइड्रेट-प्रोटीन-वसा तीनों के पाचक होते हैं — त्रिमुखी पाचक-भेज।",
     "Pancreatic juice carries digestors of carbohydrate-protein-fat all three — a three-way digestive dispatch."),

    ("human-digestive-system", "medium",
     "अपेंडिक्स (appendix) मानव में अवशेष-अंग माना जाता है — इसका अर्थ क्या है?",
     "The appendix is considered a vestigial organ in humans — what does that mean?",
     ["वह सबसे महत्वपूर्ण अंग है", "विकास-क्रम में कभी कार्यकारी, अब पाचन में कोई आवश्यक भूमिका नहीं रह गई", "वह लार बनाता है", "वह मल बनाता है"],
     ["It is the most important organ", "Once functional in the course of evolution, it now plays no necessary role in digestion", "It makes saliva", "It forms faeces"],
     1,
     "शाकाहारी पूर्वजों में सेल्युलोस-पाचन में सहायक रहा अंग अब छोटा-निष्क्रिय अवशेष बना है।",
     "An organ that once aided cellulose-digestion in herbivorous ancestors now sits as a small inactive remnant."),

    ("human-digestive-system", "medium",
     "मुँह में होने वाले पाचन की प्रकृति क्या है?",
     "What is the nature of digestion that happens in the mouth?",
     ["केवल यांत्रिक (चबाना)", "केवल रासायनिक", "यांत्रिक (दाँतों से चबाना) + रासायनिक (लार का एंजाइम) — दोनों", "कोई पाचन नहीं होता"],
     ["Only mechanical (chewing)", "Only chemical", "Both mechanical (teeth chewing) + chemical (saliva's enzyme)", "No digestion occurs"],
     2,
     "दाँत भोजन का द्रव्यमान तोड़ते हैं, लार का एंजाइम स्टार्च पर रासायनिक हमला शुरू करता है।",
     "Teeth break the food's bulk while saliva's enzyme begins the chemical attack on starch."),

    ("human-digestive-system", "medium",
     "गुल्फा (oesophagus) में पाचन क्यों नहीं होता?",
     "Why does no digestion occur in the oesophagus?",
     ["वह बहुत छोटा है", "वहाँ कोई पाचक-ग्रंथि नहीं — वह केवल परिवहन-नली है", "वहाँ अम्ल नहीं होता ही", "वह बंद रहता है"],
     ["It is too short", "It has no digestive gland — it is only a transport pipe", "It has no acid at all", "It stays closed"],
     1,
     "गुल्फा से कोई रस नहीं निकलता — भोजन बस सरकता है; पाचन का काम आगे की ही रसोई में है।",
     "No juice secretes from the oesophagus — food merely slides; digestion's work belongs to the kitchens ahead."),

    ("human-digestive-system", "medium",
     "यकृत से निकलकर पित्त और अग्नाशय से निकलकर रस किस स्थान पर आकर मिलते हैं?",
     "Where do the bile from the liver and the juice from the pancreas meet after leaving their glands?",
     ["सीधे पेट में", "क्षुद्रांत (small intestine) के आरंभिक भाग में", "मलाशय में", "मुँह में"],
     ["Directly into the stomach", "Into the beginning part of the small intestine", "Into the rectum", "Into the mouth"],
     1,
     "दोनों नलियाँ क्षुद्रांत के प्रारंभ में खुलती हैं — भोजन के अम्ल-भरे चाइम पर यहीं पित्त-रस की बौछार पड़ती है।",
     "Both ducts open at the start of the small intestine — the bile-juice shower falls on the acid-laden chyme right there."),

    ("human-digestive-system", "medium",
     "मानव पाचन-नली की लंबाई मोटे तौर पर कितनी होती है?",
     "Roughly how long is the human digestive tube?",
     ["लगभग 1 मीटर", "लगभग 3 मीटर", "लगभग 9 मीटर", "लगभग 20 मीटर"],
     ["About 1 metre", "About 3 metres", "About 9 metres", "About 20 metres"],
     2,
     "मुँह से मलद्वार तक लगभग 9 मीटर की नली — शरीर की ऊँचाई से कई गुना लंबी।",
     "Mouth to anus the tube is about 9 metres — many times the body's height."),

    ("human-digestive-system", "hard",
     "क्षुद्रांत का इतना लंबा और मुड़ा-तुड़ा होना किस दृष्टि से लाभदायक है?",
     "In what way is the small intestine's being so long and coiled beneficial?",
     ["शरीर में जगह घटाता है", "भोजन धीरे-धीरे लंबी दूरी तय करे — पाचन और अवशोषण को धीमा-विस्तृत अवसर मिले", "वह सुंदर दिखता है", "वह वजन बढ़ाता है"],
     ["It saves space in the body", "Food travels a long slow distance — digestion and absorption get a slow, extended opportunity", "It looks beautiful", "It adds weight"],
     1,
     "लंबाई = समय और सतह — दोनों ही अवशोषण के मित्र; छोटी नली में पोषक बचकर निकल जाता।",
     "Length = time and surface — both friends of absorption; in a short tube nutrients would escape unused."),

    ("human-digestive-system", "hard",
     "यकृत पाचन-नली में सीधे नहीं जुड़ा, फिर भी पाचन-अंग क्यों गिना जाता है?",
     "The liver is not directly part of the digestive tube, so why is it counted a digestive organ?",
     ["क्योंकि वह पेट के भीतर है", "क्योंकि वह पित्त बनाकर नली द्वारा क्षुद्रांत तक पहुँचाता है — पाचन-रस का सहायक-स्रोत (accessory gland)", "क्योंकि वह भोजन जमा करता है", "क्योंकि वह हृदय से जुड़ा है"],
     ["Because it sits inside the stomach", "Because it makes bile and delivers it by a duct to the small intestine — an accessory source of digestive juice", "Because it stores food", "Because it joins the heart"],
     1,
     "पित्त-नली यकृत को पाचन-प्रक्रिया से जोड़ती है — नली के बाहर होकर भी नली की रसोई में सामग्री पहुँचाता है।",
     "The bile duct ties the liver into digestion — though outside the tube, it supplies goods to the tube's kitchen."),

    ("human-digestive-system", "hard",
     "क्षुद्रांत को 'क्षुद्र' (छोटा) क्यों कहा जाता है जबकि वही सबसे लंबा भाग है?",
     "Why is the small intestine called 'small' when it is the longest part?",
     ["नाम गलत पड़ा है", "यह बृहदांत की तुलना में पतली-छोटी व्यास की है — नाम व्यास का है, लंबाई का नहीं", "वह सबसे छोटा ही है", "वह छोटे जीव का होता है"],
     ["The name is a mistake", "It is narrower in diameter than the large intestine — the name refers to width, not length", "It really is the shortest", "It belongs to small creatures"],
     1,
     "क्षुद्रांत लंबी पर सँकरी; बृहदांत छोटी पर चौड़ी — 'क्षुद्र/बृहद' व्यास का विशेषण है।",
     "The small intestine is long but narrow; the large intestine short but wide — 'small/large' describes the bore."),

    ("human-digestive-system", "hard",
     "दंत-उत्क (enamel) की क्षति स्वयं ठीक क्यों नहीं हो पाती?",
     "Why does damage to tooth enamel not repair itself?",
     ["क्योंकि दाँत छोटे हैं", "एनामल में कोई जीवित कोशिका नहीं — बनाने वाली कोशिकाएँ उभरने के बाद मर जाती हैं, इसलिए नई भराई असंभव", "क्योंकि लार जहरीली है", "क्योंकि दाँत हड्डी नहीं है"],
     ["Because teeth are small", "Enamel has no living cells — the builder cells die after eruption, so fresh refilling is impossible", "Because saliva is toxic", "Because teeth are not bone"],
     1,
     "एनामल शरीर का सबसे कठोर पदार्थ है, पर निर्जीव — एक बार छिद्र बने तो भरने की शारीरिक व्यवस्था नहीं।",
     "Enamel is the body's hardest substance, yet lifeless — once a cavity forms, the body has no mechanism to refill it."),

    ("human-digestive-system", "hard",
     "पेट की दीवार में तीन परतों की मोटी मांसपेशी क्यों होती है?",
     "Why does the stomach wall have thick muscle in three layers?",
     ["पेट को ढकने के लिए", "भोजन को हर दिशा में निचोड़-मसलने की गति चाहिए — तिरछी, अनुदैर्ध्य और वृत्ताकार पेशियाँ मिलकर पूर्ण भट्टी-चक्की बनाती हैं", "भोजन जमा करने के लिए", "अम्ल बनाने के लिए"],
     ["To cover the stomach", "Food needs squeezing-kneading in every direction — oblique, longitudinal and circular muscles together form a complete kneading mill", "To store food", "To make acid"],
     1,
     "तीन दिशाओं की पेशी = त्रि-अक्ष मसलन — भोजन रस-अम्ल के साथ पूर्ण रूप से मिल जाता है।",
     "Muscles in three directions = tri-axial kneading — food blends fully with juice and acid."),
]
