# -*- coding: utf-8 -*-
"""B06 'Nutrition & Digestion' — Part 2 data (80 items).
Order: enzymes-digestion-steps (30), nutrition-modes (20), ingestion-other-animals (15),
digestive-wellness-disorders (15).
Tuple: (topic, difficulty, q_hi, q_en, options_hi[4], options_en[4], correct_idx, exp_hi, exp_en)
DENY reminders: B02 peristalsis-tissue framing; B04 all mode-definitions (use holozoic-specific/
animal-specific angles only); B07 epiglottis/pharynx-crossing, glucose+oxygen relations;
B08 iron-in-Hb framing, lacteal fat-route; B03 amoeba-kingdom, tapeworm-phylum; B09 amoeba-reproduction.
"""

PART2 = [
    # ---------------- enzymes-digestion-steps (30: E11/M16/H3) ----------------
    ("enzymes-digestion-steps", "easy",
     "एंजाइम (enzyme) क्या होता है?",
     "What is an enzyme?",
     ["ऊर्जा देने वाला पदार्थ", "जैव-उत्प्रेरक (biocatalyst) — पाचन-अभिक्रियाओं की गति बढ़ाने वाला प्रोटीन", "एक खनिज लवण", "एक विटामिन प्रकार"],
     ["An energy-giving substance", "A biocatalyst — a protein that speeds up digestion reactions", "A mineral salt", "A type of vitamin"],
     1,
     "एंजाइम पाचन-रसों के श्रमिक हैं — बिना खुद खर्च हुए भोजन-अणुओं के टूटने की रफ्तार कई गुना बढ़ा देते हैं।",
     "Enzymes are the digestive juices' workers — without being spent themselves they multiply the speed of food-molecule breakdown."),

    ("enzymes-digestion-steps", "easy",
     "मुँह की लार में पाया जाने वाला एंजाइम किस पदार्थ पर कार्य करता है?",
     "On which substance does the enzyme found in saliva act?",
     ["प्रोटीन पर", "स्टार्च (कार्बोहाइड्रेट) पर", "वसा पर", "विटामिन पर"],
     ["On proteins", "On starch (carbohydrate)", "On fats", "On vitamins"],
     1,
     "लारीय एमाइलेज़ (टायलिन) स्टार्च को छोटी शर्करा में बदलना शुरू करता है — पाचन की पहली रासायनिक चोट।",
     "Salivary amylase (ptyalin) begins turning starch into smaller sugars — digestion's first chemical strike."),

    ("enzymes-digestion-steps", "easy",
     "आमाशय का एंजाइम पेप्सिन किस पोषक पर कार्य करता है?",
     "On which nutrient does the stomach enzyme pepsin act?",
     ["वसा पर", "स्टार्च पर", "प्रोटीन पर", "जल पर"],
     ["On fats", "On starch", "On proteins", "On water"],
     2,
     "पेप्सिन प्रोटीन को छोटे टुकड़ों (पेप्टोन) में तोड़ता है — अम्ल-माध्यम में ही सक्रिय।",
     "Pepsin breaks proteins into smaller pieces (peptones) — active only in an acid medium."),

    ("enzymes-digestion-steps", "easy",
     "आमाशय में हाइड्रोक्लोरिक अम्ल (HCl) का स्राव क्यों होता है?",
     "Why is hydrochloric acid (HCl) secreted in the stomach?",
     ["भोजन को मीठा बनाने को", "पेप्सिन के कार्य के लिए अम्लीय-माध्यम बनाने और भोजन के साथ आए सूक्ष्मजीवों को निष्क्रिय करने को", "भोजन जमाने को", "लार बनाने को"],
     ["To sweeten the food", "To create the acidic medium pepsin needs and to inactivate microbes that come with food", "To clot the food", "To make saliva"],
     1,
     "पेप्सिन केवल तीखे अम्ल में चलता है; अम्ल भोजन-संगत सूक्ष्मजीवों पर भी अंकुश लगाता है।",
     "Pepsin runs only in strong acid; the acid also reins in food-borne microbes."),

    ("enzymes-digestion-steps", "easy",
     "पित्त (bile) वसा पर क्या करता है?",
     "What does bile do to fats?",
     ["वसा को पूरी तरह पचा देता है", "बड़ी वसा-बूँदों को अनगिनत सूक्ष्म बूँदों में तोड़ता है (इमल्सीकरण)", "वसा को जमा देता है", "वसा को मीठा बनाता है"],
     ["Fully digests the fat", "Breaks big fat globules into countless tiny droplets (emulsification)", "Solidifies the fat", "Sweetens the fat"],
     1,
     "पित्त डिटर्जेंट की तरह वसा फेंटकर महीन करता है — छोटी बूँदों पर एंजाइम का हमला आसान।",
     "Bile whips the fat fine like a detergent — enzyme attack becomes easy on tiny droplets."),

    ("enzymes-digestion-steps", "easy",
     "पाचन (digestion) से क्या तात्पर्य है?",
     "What is meant by digestion?",
     ["भोजन को निगलना", "जटिल, अघुलनशील भोजन-अणुओं को सरल, घुलनशील रूप में तोड़ने की प्रक्रिया", "भोजन को रुधिर में ले जाना", "अपचा मल निकालना"],
     ["Swallowing the food", "The process of breaking complex, insoluble food molecules into simple, soluble forms", "Carrying food into the blood", "Expelling undigested matter"],
     1,
     "पाचन = बड़े अणुओं की छोटे अणुओं में तुगलाई — जिसके बाद ही अवशोषण संभव है।",
     "Digestion = breaking big molecules into small ones — only after which absorption becomes possible."),

    ("enzymes-digestion-steps", "easy",
     "कार्बोहाइड्रेट के पाचन का अंतिम उत्पाद क्या है?",
     "What is the final product of carbohydrate digestion?",
     ["अमीनो अम्ल", "ग्लूकोस जैसी सरल शर्करा", "वसा-अम्ल", "जल"],
     ["Amino acids", "Simple sugars like glucose", "Fatty acids", "Water"],
     1,
     "स्टार्च की लंबी माला अंततः ग्लूकोस की मनकों तक टूटती है — यही रुधिर में उठता है।",
     "Starch's long chain finally snaps into glucose beads — these enter the blood."),

    ("enzymes-digestion-steps", "easy",
     "प्रोटीन के पाचन का अंतिम उत्पाद क्या है?",
     "What is the final product of protein digestion?",
     ["ग्लूकोस", "अमीनो अम्ल", "ग्लिसरॉल", "विटामिन"],
     ["Glucose", "Amino acids", "Glycerol", "Vitamins"],
     1,
     "प्रोटीन-माला अमीनो-अम्ल की इकाइयों तक टूटती है — इन्हीं से शरीर अपनी प्रोटीन फिर बनाता है।",
     "The protein chain breaks into amino-acid units — from these the body rebuilds its own proteins."),

    ("enzymes-digestion-steps", "easy",
     "वसा के पाचन के अंतिम उत्पाद कौन-से हैं?",
     "Which are the end products of fat digestion?",
     ["अमीनो अम्ल और ग्लूकोस", "वसा-अम्ल (fatty acids) और ग्लिसरॉल", "जल और लवण", "कार्बन डाइऑक्साइड"],
     ["Amino acids and glucose", "Fatty acids and glycerol", "Water and salts", "Carbon dioxide"],
     1,
     "वसा-त्रिक फैटी-एसिड + ग्लिसरॉल में बँटता है — यही अवशोषण-योग्य जोड़ी है।",
     "The fat triple splits into fatty acids + glycerol — that is the absorbable pair."),

    ("enzymes-digestion-steps", "easy",
     "अवशोषण (absorption) से क्या तात्पर्य है?",
     "What is meant by absorption?",
     ["भोजन को जोड़ना", "पचे हुए सरल पदार्थों को आँत की दीवार से रुधिर/लसीका में ले जाना", "भोजन को मल बनाना", "भोजन को ऊतकों में खर्च करना"],
     ["Joining up food", "Carrying the digested simple substances from the gut wall into blood/lymph", "Turning food into faeces", "Spending food in tissues"],
     1,
     "अवशोषण = रस की विलाई-दीवार से रुधिर-धारा में प्रवेश — क्षुद्रांत का मुख्य कार्य।",
     "Absorption = the juice's entry from the villus wall into the bloodstream — the small intestine's chief job."),

    ("enzymes-digestion-steps", "easy",
     "निर्गम (egestion) का अर्थ बताइए।",
     "State the meaning of egestion.",
     ["पचा भोजन रुधिर में लेना", "अपचे भोजन-अवशेष (मल) को मलद्वार से बाहर निकालना", "भोजन को कोशिकाओं में जोड़ना", "भोजन चबाना"],
     ["Taking digested food into blood", "Removing the undigested residue (faeces) through the anus", "Incorporating food into cells", "Chewing food"],
     1,
     "निर्गम अपशिष्ट-निकास है — जो पचा नहीं, वह शरीर में रुकता नहीं।",
     "Egestion is waste-exit — what cannot be digested does not linger in the body."),

    ("enzymes-digestion-steps", "medium",
     "मुँह में स्टार्च का पाचन कहाँ तक पहुँचता है?",
     "How far does starch digestion get in the mouth?",
     ["पूर्ण ग्लूकोस तक", "आंशिक — स्टार्च मैल्टोज़ जैसी मध्यवर्ती शर्करा तक; आगे क्षुद्रांत में पूरा होगा", "कुछ नहीं होता", "वसा बन जाता है"],
     ["Fully to glucose", "Partially — starch to intermediate sugars like maltose; completion awaits the small intestine", "Nothing happens", "It turns to fat"],
     1,
     "मुँह लार-एमाइलेज़ से केवल पहली तुगलाई करता है — मीठा स्वाद चबाते ही इसी से आता है।",
     "The mouth with salivary amylase does only the first split — the sweet taste while chewing comes from this."),

    ("enzymes-digestion-steps", "medium",
     "आमाशय के अम्ल-भोजन मिश्रण को क्या कहते हैं?",
     "What is the acid-food mixture of the stomach called?",
     ["बोलस", "चाइम (chyme)", "रस (chyle)", "विलाई"],
     ["Bolus", "Chyme", "Chyle", "Villi"],
     1,
     "पेट की मसलाई के बाद बना गाढ़ा-अर्धतरल अम्ल मिश्रण = चाइम; बोलस मुँह का शब्द है।",
     "The thick semi-fluid acid mix after the stomach's kneading = chyme; bolus is the mouth's word."),

    ("enzymes-digestion-steps", "medium",
     "लार-एमाइलेज़ का कार्य आमाशय में रुक जाता है — क्यों?",
     "Salivary amylase's action stops in the stomach — why?",
     ["पेट में लार नहीं पहुँचती", "पेट का प्रबल अम्ल अम्लीय-माध्यम बनाता है और पेप्सिन-क्षेत्र बन जाता है; स्टार्च-पाचन क्षुद्रांत में अग्नाशय-एमाइलेज़ पुनः शुरू करता है", "पेट में जल नहीं होता", "एमाइलेज़ घुल जाता है"],
     ["Saliva cannot reach the stomach", "The stomach's strong acid builds an acid medium and a pepsin-zone; starch digestion resumes in the small intestine via pancreatic amylase", "The stomach has no water", "Amylase dissolves away"],
     1,
     "पेट प्रोटीन-विशेषज्ञ कारखाना है — स्टार्च का काम वहाँ टाला जाता है, आगे फिर खुलता है।",
     "The stomach is the protein-specialist plant — starch's work is deferred there and reopened ahead."),

    ("enzymes-digestion-steps", "medium",
     "पित्त में कोई पाचक-एंजाइम नहीं होता, फिर भी वह पाचन का आवश्यक हिस्सा क्यों माना जाता है?",
     "Bile contains no digestive enzyme, so why is it counted an essential part of digestion?",
     ["वह भोजन को रंगता है", "उसका इमल्सीकरण वसा-बूँदों का क्षेत्र इतना बढ़ाता है कि लाइपेज़ का पाचन तेज़ हो जाता है; वह अम्लीय चाइम को अम्लरहित भी करता है", "वह मीठा बनाता है", "वह लार बनाता है"],
     ["It colours the food", "Its emulsification enlarges the fat-droplet field so much that lipase's digestion quickens; it also neutralises the acidic chyme", "It sweetens", "It makes saliva"],
     1,
     "बिना एंजाइम के भी पित्त सहायक-नायक है — वसा-पाचन की मंच-तैयारी वही करता है।",
     "Enzyme-less bile is still the supporting hero — it readies the stage for fat digestion."),

    ("enzymes-digestion-steps", "medium",
     "अग्नाशय-रस में किन तीनों वर्गों के पाचक एंजाइम आते हैं?",
     "Which three classes of digestive enzymes come in pancreatic juice?",
     ["केवल स्टार्च-पाचक", "कार्बोहाइड्रेट (एमाइलेज़), प्रोटीन (ट्रिप्सिन) और वसा (लाइपेज़) — तीनों", "केवल वसा-पाचक", "केवल जल-पाचक"],
     ["Only starch-digesting", "Carbohydrate (amylase), protein (trypsin) and fat (lipase) — all three", "Only fat-digesting", "Only water-digesting"],
     1,
     "अग्नाशय त्रिशूल-रस देता है — तीनों पोषकों पर एक साथ काम करने वाला एकमात्र बड़ा रस।",
     "The pancreas gives a trident juice — the only big juice working on all three nutrients at once."),

    ("enzymes-digestion-steps", "medium",
     "आहार-रस (intestinal juice) कहाँ से स्रावित होता है?",
     "Where is intestinal juice secreted from?",
     ["यकृत से", "क्षुद्रांत की भित्ति से", "अग्नाशय से", "लार-ग्रंथि से"],
     ["From the liver", "From the wall of the small intestine", "From the pancreas", "From the salivary gland"],
     1,
     "क्षुद्रांत की अपनी दीवार रस देती है — अंतिम चरण के पाचन-एंजाइम यहीं से।",
     "The small intestine's own wall supplies juice — the final-stage enzymes come from here."),

    ("enzymes-digestion-steps", "medium",
     "भोजन का संपूर्ण पाचन (तीनों पोषकों का अंतिम विघटन) कहाँ संपन्न होता है?",
     "Where does the complete digestion of food (final breakdown of all three nutrients) take place?",
     ["आमाशय में", "क्षुद्रांत (small intestine) में", "मुँह में", "बृहदांत में"],
     ["In the stomach", "In the small intestine", "In the mouth", "In the large intestine"],
     1,
     "मुँह-पेट केवल शुरुआत हैं — पित्त + अग्नाशय-रस + आंत्र-रस के संगम वाली क्षुद्रांत ही पाचन की समाप्ति-मंज़िल।",
     "Mouth-stomach are only beginnings — the small intestine, confluence of bile + pancreatic juice + intestinal juice, is digestion's finishing post."),

    ("enzymes-digestion-steps", "medium",
     "कलावर्त (peristalsis) क्या है?",
     "What is peristalsis?",
     ["रुधिर का बहना", "पाचन-नली की भित्ति में लहर की तरह दौड़ने वाली पेशी-संकुचन शृंखला जो भोजन को आगे धकेलती है", "लार का स्राव", "वसा का जमना"],
     ["The flowing of blood", "A wave-like chain of muscle contractions racing along the gut wall, pushing the food forward", "The secretion of saliva", "The solidifying of fat"],
     1,
     "नाली की दीवार ऊपर से नीचे क्रम से सिकुड़ती है — हर सिकुड़न भोजन की थैली नीचे मलती जाती है।",
     "The tube's wall contracts in top-to-bottom sequence — each squeeze milks the food parcel downward."),

    ("enzymes-digestion-steps", "medium",
     "कलावर्त-लहरें किस दिशा में चलती हैं?",
     "In which direction do peristaltic waves travel?",
     ["मलद्वार से मुँह की ओर", "मुँह से मलद्वार की ओर — एकदिशीय आगे की धकेलन", "दोनों दिशाओं में बराबर", "केवल पेट के भीतर गोलाकार"],
     ["From anus towards mouth", "From mouth towards anus — a one-way forward push", "Equally in both directions", "Only circular inside the stomach"],
     1,
     "पेशी-लहर का रुख नीचे की ओर ही होता है — इसीलिए खड़े या उलटे शरीर में भी भोजन आगे बढ़ता है।",
     "The muscle-wave faces only downward — hence food advances even in an upright or inverted body."),

    ("enzymes-digestion-steps", "medium",
     "स्वावशोषण (assimilation) से क्या तात्पर्य है?",
     "What is meant by assimilation?",
     ["भोजन का चबाना", "रुधिर से पहुँचे पोषक तत्वों को कोशिकाएँ अपनी संरचना-ऊर्जा में जोड़ना-उपयोग करना", "मल निकालना", "लार बनाना"],
     ["Chewing the food", "Cells taking up the nutrients delivered by blood and using them for structure-energy", "Expelling faeces", "Making saliva"],
     1,
     "अवशोषण रुधिर तक की कहानी है, स्वावशोषण कोशिका के भीतर की — पोषक का शरीर-बनना।",
     "Absorption is the story up to the blood; assimilation is inside the cell — nutrient becoming body."),

    ("enzymes-digestion-steps", "medium",
     "भोजन को भली-भाँति चबाना पाचन के लिए क्यों फायदेमंद है?",
     "Why is chewing food well beneficial for digestion?",
     ["मुँह का आकार बढ़ता है", "छोटे टुकड़ों का सतह-क्षेत्र बड़ा हो जाता है — एंजाइम हर ओर से हमला कर सकते हैं", "स्वाद बढ़ता है", "वजन घटता है"],
     ["The mouth's size grows", "Small pieces have a larger total surface area — enzymes can attack from all sides", "Taste improves", "Weight falls"],
     1,
     "चबाना यांत्रिक विभाजन है — सतह जितनी खुलेगी, रासायनिक पाचन उतना तेज़।",
     "Chewing is mechanical subdivision — the more the surface opens, the faster the chemical digestion."),

    ("enzymes-digestion-steps", "medium",
     "एंजाइम की क्रिया-विशिष्टता (specificity) का क्या कारण है?",
     "What is the reason for an enzyme's specificity?",
     ["हर एंजाइम एक जैसा होता है", "हर एंजाइम की आकृति उसके विशिष्ट सब्सट्रेट (कार्य-पदार्थ) से ताला-चाबी की तरह जुड़ती है — अन्य पदार्थों से नहीं", "एंजाइम सब कुछ खा जाते हैं", "एंजाइम रंग से काम पहचानते हैं"],
     ["Every enzyme is the same", "Each enzyme's shape fits its specific substrate like a lock and key — not other substances", "Enzymes eat everything", "Enzymes recognise by colour"],
     1,
     "ताला-चाबी मॉडल: एमाइलेज़ केवल स्टार्च, पेप्सिन केवल प्रोटीन — आकृति-मेल ही विशिष्टता।",
     "Lock-and-key model: amylase only starch, pepsin only protein — the shape-match is the specificity."),

    ("enzymes-digestion-steps", "medium",
     "ट्रिप्सिन किसका पाचक है और किस रस में होता है?",
     "Trypsin is a digestor of what and in which juice is it found?",
     ["वसा का — पित्त में", "प्रोटीन का — अग्नाशय-रस में", "स्टार्च का — लार में", "जल का — आँत्र-रस में"],
     ["Of fat — in bile", "Of protein — in pancreatic juice", "Of starch — in saliva", "Of water — in intestinal juice"],
     1,
     "ट्रिप्सिन अग्नाशय का प्रोटीन-पाचक है — पेप्सिन की क्षुद्रांत-कार्य की आगे की कड़ी।",
     "Trypsin is the pancreas's protein-digestor — the forward link of pepsin's work in the small intestine."),

    ("enzymes-digestion-steps", "medium",
     "लाइपेज़ किस पोषक पर कार्य करता है?",
     "On which nutrient does lipase act?",
     ["कार्बोहाइड्रेट", "प्रोटीन", "वसा", "विटामिन"],
     ["Carbohydrate", "Protein", "Fat", "Vitamin"],
     2,
     "लाइपेज़ वसा-त्रिक को वसा-अम्ल + ग्लिसरॉल तक खोलता है — पित्त ने मंच सजाया, लाइपेज़ खेलता है।",
     "Lipase unlocks the fat triple into fatty acids + glycerol — bile sets the stage, lipase plays."),

    ("enzymes-digestion-steps", "medium",
     "पाचन में मुँह और आमाशय का श्रम-विभाजन कैसा है?",
     "How is the division of labour between the mouth and the stomach in digestion?",
     ["दोनों एक ही पोषक पर काम करते हैं", "मुँह कार्बोहाइड्रेट-पाचन शुरू करता है, आमाशय प्रोटीन-पाचन का केंद्र है — वसा का मुख्य कार्य क्षुद्रांत में", "मुँह प्रोटीन पचाता है", "आमाशय स्टार्च पचाता है"],
     ["Both work on the same nutrient", "The mouth starts carbohydrate digestion, the stomach is the hub of protein digestion — fat's main work waits in the small intestine", "The mouth digests protein", "The stomach digests starch"],
     1,
     "हर चरण का अपना विशेषज्ञ-पोषक: मुँह-कार्बोहाइड्रेट, पेट-प्रोटीन, क्षुद्रांत-तीनों (विशेषतः वसा)।",
     "Each stage has its specialist nutrient: mouth-carbohydrate, stomach-protein, small intestine-all three (especially fat)."),

    ("enzymes-digestion-steps", "medium",
     "क्षुद्रांत की विलाइयों से सोखा गया ग्लूकोस और अमीनो अम्ल शरीर की कोशिकाओं तक कैसे पहुँचते हैं?",
     "How do the glucose and amino acids absorbed from the intestinal villi reach the body's cells?",
     ["लार के साथ", "रुधिर-प्रवाह (bloodstream) में उठकर — रुधिर ही उन्हें सभी कोशिकाओं तक पहुँचाता है", "नसों से", "लसीका से ही सब"],
     ["With saliva", "Lifted into the bloodstream — the blood alone carries them to every cell", "Through nerves", "Only through lymph"],
     1,
     "विलाई की केशिका में प्रवेश के बाद पोषक-यात्रा रुधिर की जिम्मेदारी — पाचन से संचरण की बागडोर यहीं बदलती है।",
     "After entering the villus capillary, the nutrient-journey becomes the blood's responsibility — the baton passes from digestion to circulation here."),

    ("enzymes-digestion-steps", "hard",
     "पेप्सिन क्षुद्रांत में निष्क्रिय क्यों हो जाता है?",
     "Why does pepsin become inactive in the small intestine?",
     ["वहाँ भोजन नहीं होता", "पेप्सिन केवल अम्लीय माध्यम का एंजाइम है — पित्त क्षुद्रांत के माध्यम को अम्लरहित करता है, और वहाँ ट्रिप्सिन प्रोटीन-कार्य संभालता है", "वह वहाँ जम जाता है", "उसे लार चाहिए"],
     ["There is no food there", "Pepsin is an enzyme of acidic medium only — bile makes the small intestine's medium non-acidic, and trypsin takes over the protein work there", "It clots there", "It needs saliva"],
     1,
     "एक एंजाइम एक माध्यम का नौकर — अम्ल-पेप्सिन अम्ल-पेट में; क्षुद्रांत ट्रिप्सिन का राज।",
     "One enzyme serves one medium — acid-pepsin in the acid-stomach; the small intestine is trypsin's reign."),

    ("enzymes-digestion-steps", "hard",
     "इमल्सीकरण (emulsification) वसा-पाचन को किस भौतिक सिद्धांत से तेज़ करता है?",
     "By which physical principle does emulsification speed up fat digestion?",
     ["भोजन को गर्म करके", "बूँदों के छोटे होने पर कुल सतह-क्षेत्र घनी हो जाता है — एंजाइम उसी खुली सतह पर चढ़ सकता है", "वसा को रंगने से", "वसा को जमाने से"],
     ["By heating the food", "As droplets shrink, the total surface area multiplies — the enzyme can climb onto that opened surface", "By colouring the fat", "By solidifying the fat"],
     1,
     "एक बड़ी बूँद के बदले हज़ारों सूक्ष्म बूँदें = हज़ार गुना मोर्चा — सतह-क्षेत्रफल की सीधी रणनीति।",
     "One big globule traded for thousands of tiny ones = a thousand-fold front — straight strategy of surface area."),

    ("enzymes-digestion-steps", "hard",
     "भोजन के बड़े अणुओं को छोटे-घुलनशील रूप में तोड़ना ही क्यों अनिवार्य है?",
     "Why is breaking food's big molecules into small soluble forms unavoidable?",
     ["स्वाद के लिए", "रुधिर-केशिका-दीवार और कोशिका-झिल्ली केवल छोटे घुलनशील अणुओं को आर-पार करने देती है — बड़े अणु भीतर नहीं घुस सकते", "रंग के लिए", "गंध के लिए"],
     ["For taste", "The blood-capillary wall and cell membrane allow only small soluble molecules to pass — big molecules cannot enter", "For colour", "For smell"],
     1,
     "शोषण-सीमा की बात: दीवार का दरवाज़ा छोटा है — सामान उसी के अनुसार तोड़ना पड़ेगा।",
     "A matter of absorption-limits: the wall's doorway is small — the luggage must be broken to match."),

    # ---------------- nutrition-modes (20: E7/M11/H2) ----------------
    ("nutrition-modes", "easy",
     "प्राणिमय (holozoic) पोषण किसे कहते हैं?",
     "What is called holozoic nutrition?",
     ["मृत पदार्थ सोखना", "पूर्ण जीव के रूप में भोजन निगलकर उसे शरीर के भीतर पचाना — जैसे अधिकांश प्राणी", "प्रकाश से भोजन बनाना", "पोषक से चूसना"],
     ["Absorbing dead matter", "Swallowing whole food and digesting it inside the body — as most animals do", "Making food from light", "Sucking from a host"],
     1,
     "होलोज़ोइक = संपूर्ण-प्राण भोजन: निगलना → पचाना → सोखना → जोड़ना → निकालना की पाँच-चरण पद्धति।",
     "Holozoic = whole-animal food: the five-step method of swallowing → digesting → absorbing → assimilating → egesting."),

    ("nutrition-modes", "easy",
     "प्राणिमय पोषण का पहला चरण कौन-सा है?",
     "Which is the first step of holozoic nutrition?",
     ["अवशोषण", "भोजन-ग्रहण (ingestion) — भोजन को शरीर के भीतर लेना", "निर्गम", "स्वावशोषण"],
     ["Absorption", "Ingestion — taking food into the body", "Egestion", "Assimilation"],
     1,
     "पहले भोजन भीतर आएगा, तब पाचन-शृंखला चलेगी — ग्रहण ही प्रवेश-द्वार है।",
     "Food must first come in for the digestive chain to run — ingestion is the entry gate."),

    ("nutrition-modes", "easy",
     "अमीबा भोजन कैसे ग्रहण करता है?",
     "How does Amoeba ingest food?",
     ["मुँह से चबाकर", "कूड़-पाँव (pseudopodia) फैलाकर भोजन-कण को घेरकर भीतर ले लेता है", "दाँतों से काटकर", "फिल्टर से छानकर"],
     ["By chewing with a mouth", "Spreads pseudopodia, encircles the food particle and takes it in", "By cutting with teeth", "By filtering through a sieve"],
     1,
     "अमीबा की कूड़-पाँव जीवित हाथों जैसी हैं — भोजन को गले लगाकर भीतर समा लेती हैं।",
     "Amoeba's pseudopodia work like living arms — they hug the food and tuck it inside."),

    ("nutrition-modes", "easy",
     "अमीबा में भोजन का पाचन कहाँ होता है?",
     "Where does digestion of food occur in Amoeba?",
     ["भोजन-रिक्तिका (food vacuole) में — कोशिका-द्रव्य के भीतर", "समर्पित आमाशय में", "मुँह में", "केंद्रक में"],
     ["In the food vacuole — inside the cytoplasm", "In a dedicated stomach", "In the mouth", "In the nucleus"],
     1,
     "भोजन-कण के चारों ओर बनी थैली में ही एंजाइम उड़ेले जाते हैं — थैली ही चलता-फिरता पेट।",
     "Enzymes pour into the sac formed around the food particle — the sac itself is a roving stomach."),

    ("nutrition-modes", "easy",
     "केवल पौधों पर भोजन करने वाले जीव क्या कहलाते हैं?",
     "What are organisms that feed only on plants called?",
     ["मांसाहारी", "शाकाहारी (herbivore)", "सर्वाहारी", "परजीवी"],
     ["Carnivores", "Herbivores", "Omnivores", "Parasites"],
     1,
     "गाय-हिरण-बकरी शाकाहारी हैं — ग्रास-फसल-पत्ते ही उनकी पूरी थाली।",
     "Cow-deer-goat are herbivores — grass-crop-leaves are their whole plate."),

    ("nutrition-modes", "easy",
     "केवल अन्य जीवों का मांस खाने वाले जीव क्या कहलाते हैं?",
     "What are organisms that eat only the flesh of other organisms called?",
     ["शाकाहारी", "मांसाहारी (carnivore)", "सर्वाहारी", "मृतजीवी"],
     ["Herbivores", "Carnivores", "Omnivores", "Saprophytes"],
     1,
     "शेर-बाघ-चील मांसाहारी हैं — शिकार का मांस ही उनका भोजन।",
     "Lion-tiger-kite are carnivores — the prey's flesh is their food."),

    ("nutrition-modes", "easy",
     "पौधा और मांस दोनों खाने वाले जीव क्या कहलाते हैं?",
     "What are organisms that eat both plants and meat called?",
     ["केवल शाकाहारी", "सर्वाहारी (omnivore) — जैसे मनुष्य, कौआ", "केवल मांसाहारी", "परजीवी"],
     ["Only herbivores", "Omnivores — like humans and crows", "Only carnivores", "Parasites"],
     1,
     "सर्वाहारी की थाली मिश्रित है — अन्न-सब्ज़ी भी, मांस भी।",
     "The omnivore's plate is mixed — grain-vegetable as well as meat."),

    ("nutrition-modes", "medium",
     "प्राणिमय पोषण के पाँच चरणों का सही क्रम कौन-सा है?",
     "Which is the correct order of the five steps of holozoic nutrition?",
     ["पाचन → ग्रहण → अवशोषण → स्वावशोषण → निर्गम", "ग्रहण (ingestion) → पाचन (digestion) → अवशोषण (absorption) → स्वावशोषण (assimilation) → निर्गम (egestion)", "निर्गम → ग्रहण → पाचन → अवशोषण → स्वावशोषण", "अवशोषण → स्वावशोषण → ग्रहण → पाचन → निर्गम"],
     ["Digestion → ingestion → absorption → assimilation → egestion", "Ingestion → digestion → absorption → assimilation → egestion", "Egestion → ingestion → digestion → absorption → assimilation", "Absorption → assimilation → ingestion → digestion → egestion"],
     1,
     "भीतर लो → तोड़ो → रुधिर में उठाओ → कोशिका में जोड़ो → बचा हुआ निकालो — यही अक्षर-क्रम।",
     "Take in → break down → lift into blood → build into cells → throw out the rest — that is the letter-order."),

    ("nutrition-modes", "medium",
     "अमीबा जैसे एककोशिकीय जीव को पाचन-अंगों की आवश्यकता क्यों नहीं पड़ती?",
     "Why does a unicellular organism like Amoeba not need digestive organs?",
     ["वह भोजन नहीं खाता", "उसकी एक ही कोशिका ही सब काम करती है — कोशिका-झिल्ली ग्रहण करती है, रिक्तिका पचाती है, झिल्ली निर्गम करती है", "उसका शरीर कठोर है", "वह पानी में नहीं रहता"],
     ["It eats no food", "Its single cell does every job — the membrane ingests, the vacuole digests, the membrane egests", "Its body is hard", "It does not live in water"],
     1,
     "एक कोशिका = एक पूरा कारखाना — विभाजन की जरूरत ही नहीं पड़ती।",
     "One cell = one whole factory — no need of departmentalisation."),

    ("nutrition-modes", "medium",
     "अमीबा अपचे भोजन-अंश को कैसे बाहर निकालता है?",
     "How does Amoeba throw out the undigested part of the food?",
     ["मलद्वार से", "कोशिका-झिल्ली किसी स्थान पर फटकर अपचा अंश बाहर छोड़ देती है", "मुँह से वापस", "त्वचा से पसीने में"],
     ["Through an anus", "The cell membrane ruptures at a spot and releases the undigested matter outside", "Back through the mouth", "Through skin sweat"],
     1,
     "निर्गम-स्थल कहीं भी बन सकता है — झिल्ली की खुली खिड़की ही निकास-द्वार।",
     "The exit-site can form anywhere — the membrane's ad hoc window itself is the discharge gate."),

    ("nutrition-modes", "medium",
     "पैरामीशियम भोजन-कणों को भीतर लाने में किन संरचनाओं का उपयोग करता है?",
     "Which structures does Paramecium use to bring food particles in?",
     ["कूड़-पाँव", "रोमक (cilia) — पूरे शरीर पर बालों जैसी झिल्लियाँ जल-धारा बनाकर भोजन मुँह-रेखा तक बहाती हैं", "चूसने वाली नली", "दाँत"],
     ["Pseudopodia", "Cilia — hair-like membranes all over the body create water-currents steering food to the mouth-line", "A sucking tube", "Teeth"],
     1,
     "हज़ारों पतले रोमक एक साथ चलकर जल में भोजन-प्रवाह की दिशा ही बदल देते हैं।",
     "Thousands of fine cilia beat together and literally redirect the food-flow in the water."),

    ("nutrition-modes", "medium",
     "शाकाहारी-प्राणी बनाम प्राणिमय-भोजी सूक्ष्मजीव — प्राणिमय (holozoic) पोषण उनमें से किसका वर्ग है जो पौधों का सेवन करता है?",
     "Herbivore versus holozoic — an animal eating plants still belongs to which nutrition category?",
     ["वह प्राणिमय-पोषी नहीं है", "हाँ, वह प्राणिमय पोषी ही है — ग्रहण-पाचन-अवशोषण की पूरी पाँच-चरण पद्धति अपनाता है; भोजन-स्रोत (पौधा/मांस) वर्ग का आधार नहीं", "वह मृतजीवी है", "वह स्वपोषी है"],
     ["It is not holozoic", "Yes, it is holozoic — it follows the full five-step ingestion-digestion-absorption method; the food source (plant/meat) is not the basis of the category", "It is saprophytic", "It is autotrophic"],
     1,
     "होलोज़ोइक पद्धति का प्रश्न 'कैसे' है, 'क्या' नहीं — शाकाहारी-मांसाहारी तो भोजन-वस्तु का वर्ग है।",
     "The holozoic question is 'how', not 'what' — herbivore-carnivore is the classification of food stuff."),

    ("nutrition-modes", "medium",
     "फीताकृमि (tapeworm) के पाचन-तंत्र नहीं होता — वह तो जीवन यापन कैसे करता है?",
     "A tapeworm has no digestive system — how does it survive at all?",
     ["वह उपवास करता है", "पोषक आँत में पहले से पचा-भोजन सीधे उसकी शरीर-सतह से सोख लेता है — पचाने की जरूरत ही नहीं", "वह प्रकाश-संश्लेषण करता है", "वह रुधिर पीता है"],
     ["It fasts", "It simply absorbs the host's pre-digested food through its body surface — no need to digest", "It photosynthesises", "It drinks blood"],
     1,
     "तैयार-भोजन की चोरी परजीवि-सफलता की कुंजी है — पोषक की रसोई में बिना रसोई खाना।",
     "Stealing ready-made food is the parasite's key to success — eating from the host's kitchen with no kitchen of one's own."),

    ("nutrition-modes", "medium",
     "मच्छर अपना भोजन कैसे लेता है?",
     "How does a mosquito take its food?",
     ["चबाकर", "सूई जैसी चूषक-सूँड से तरल भोजन (रस/रुधिर) चूसकर", "घूंट-घूंट निगलकर", "फिल्टर करके"],
     ["By chewing", "By sucking liquid food (juice/blood) through a needle-like proboscis", "By gulping mouthfuls", "By filtering"],
     1,
     "मच्छर की सूँड सर्वे-नली है — केवल तरल आहार ही उसकी पहुँच में।",
     "The mosquito's proboscis is a syringe-pipe — only liquid diet is within its reach."),

    ("nutrition-modes", "medium",
     "तितली अपना भोजन कैसे ग्रहण करती है?",
     "How does a butterfly ingest its food?",
     ["दाँतों से पीसकर", "नली जैसी घुंघराली सूँड (proboscis) खोलकर फूल के रस में डुबोकर चूसती है", "कीड़े पकड़कर", "बीज तोड़कर"],
     ["By grinding with teeth", "Uncoiling its tube-like proboscis and dipping it into the flower's nectar to suck", "By catching insects", "By cracking seeds"],
     1,
     "तितली की सूँड तिरछा-नली है — सुंदर कुंडली में मुड़ी रहती है, काम पर सीधी हो जाती है।",
     "The butterfly's proboscis is a straw-pipe — kept coiled prettily, straightened on the job."),

    ("nutrition-modes", "medium",
     "शाकाहारी जीवों का आँत-मार्ग मांसाहारियों से अपेक्षाकृत लंबा क्यों होता है?",
     "Why is the gut tract of herbivores relatively longer than that of carnivores?",
     ["शाकाहारी बड़े होते हैं", "पौधा-भोजन (सेल्युलोज-भरपूर) कठिन-धीमा पचता है — लंबी आँत उसे अधिक समय और सतह देती है; मांस पचना सरल है", "शाकाहारियों को जल ज्यादा चाहिए", "मांसाहारियों की आँत मोटी होती है"],
     ["Herbivores are bigger", "Plant food (cellulose-rich) digests slowly with difficulty — a long gut gives it more time and surface; meat digests easily", "Herbivores need more water", "Carnivores' guts are thicker"],
     1,
     "भोजन जितना खुरदुरा, मार्ग उतना लंबा — सेल्युलोस की बारीकी से निपटने की फीस।",
     "The rougher the food, the longer the route — the price of dealing with cellulose."),

    ("nutrition-modes", "medium",
     "मांसाहारियों के शरीर में शिकार-भोजन का संकेत सबसे स्पष्ट किन संरचनाओं में दिखता है?",
     "In which structures is the sign of a predatory diet most clearly seen in a carnivore's body?",
     ["पेट की लंबाई में", "तीखे नुकीले रदनक (canines) और फाड़ने-कूटने के दाँतों में", "कानों में", "पूँछ में"],
     ["In the stomach's length", "In the sharp pointed canines and the tearing-crushing teeth", "In the ears", "In the tail"],
     1,
     "दाँत ही आहार का विज़िटिंग-कार्ड — मांसाहारी के रदनक चाकू-काँटे हैं।",
     "Teeth are the diet's visiting card — a carnivore's canines are knives and forks."),

    ("nutrition-modes", "medium",
     "मक्खी ठोस चीनी-भोजन कैसे खाती है?",
     "How does a housefly eat solid sugary food?",
     ["निगलकर पेट में", "उगली गई लार में भोजन को घोलकर तरल बनाती है और चूस लेती है — बाहर ही आधा पाचन", "दाँतों से पीसकर", "केवल रस पीती है"],
     ["By swallowing into the stomach", "Regurgitated saliva dissolves the food into liquid outside and it sucks it in — half the digestion done outside", "By grinding with teeth", "It drinks only juice"],
     1,
     "मक्खी का भोजन-उपाय बाहरी-घोल पद्धति है — थूककर पिलाना और फिर चूसना।",
     "The housefly's way is the outside-solution method — spit-to-dissolve and then suck."),

    ("nutrition-modes", "hard",
     "अमीबा के भोजन-ग्रहण की प्रक्रिया का वैज्ञानिक नाम क्या है?",
     "What is the scientific name of Amoeba's food-engulfing process?",
     ["परासरण", "भक्षक-क्रिया / फैगोसाइटोसिस (phagocytosis)", "वाष्पोत्सर्जन", "निस्पंदन"],
     ["Osmosis", "Phagocytosis — the engulfing 'cell-eating' action", "Transpiration", "Filtration"],
     1,
     "कूड़-पाँवों से घेरकर भोजन-कण को भक्षण करना ही फैगोसाइटोसिस — कोशिका-भक्षण।",
     "Encircling the food particle with pseudopodia and devouring it is phagocytosis — cell-eating."),

    ("nutrition-modes", "hard",
     "अधिकांश गहरे-परजीवियों (endoparasites) में पाचन-तंत्र सरल होता या लुप्त — इसकी व्याख्या क्या है?",
     "The digestive system is simplified or lost in most deep parasites (endoparasites) — what explains this?",
     ["वे बड़े होते हैं", "पोषक के भीतर पहले से पचा भोजन सरलता से शोषणीय है — अपना पाचन-प्रबंधन खड़ा रखना ऊर्जा-बहुलाव हो जाता; अतः विकास ने उसे छोटा किया", "वे तेज़ तैरते हैं", "उनके पोषक छोटे होते हैं"],
     ["They are large", "Inside the host, pre-digested food is easily absorbable — maintaining one's own digestive apparatus becomes an energy extravagance; so evolution shrank it", "They swim fast", "Their hosts are small"],
     1,
     "जो सुविधा मुफ्त मिले, उसका उपकरण बनाए रखना व्यर्थ — परजीवि-विकास का 'उपकरण-क्षय' नियम।",
     "No point maintaining equipment for what comes free — the parasite-evolution rule of 'organ decay'."),

    # ---------------- ingestion-other-animals (15: E5/M9/H1) ----------------
    ("ingestion-other-animals", "easy",
     "जुगाली करने वाले प्राणियों (ruminants) के उदाहरण कौन-से हैं?",
     "Which are examples of ruminants (cud-chewing animals)?",
     ["गाय, भैंस, भेड़, बकरी", "कुत्ता, बिल्ली", "शेर, बाघ", "कौआ, कबूतर"],
     ["Cow, buffalo, sheep, goat", "Dog, cat", "Lion, tiger", "Crow, pigeon"],
     0,
     "घास चरकर जुगाली करने वाले चौपाये ही रूमिनेंट वर्ग हैं — गाय-भैंस उसके ध्वजवाहक।",
     "The grass-grazing cud-chewers form the ruminant class — cow-buffalo its flagbearers."),

    ("ingestion-other-animals", "easy",
     "रूमेन (rumen) क्या होता है?",
     "What is the rumen?",
     ["पेट की दीवार", "रूमिनेंट के बहुकक्षीय आमाशय का पहला-सबसे बड़ा कक्ष — घास भिगोकर किण्वन-संग्रह करने वाला", "क्षुद्रांत का हिस्सा", "मूत्र-थैली"],
     ["The stomach's wall", "The first and largest chamber of a ruminant's multi-chambered stomach — the soak-and-ferment store of grass", "A part of the small intestine", "The urinary bladder"],
     1,
     "रूमेन घास का पूर्व-प्रसंस्करण संयंत्र है — वहीं किण्वित होकर घास जुगाली के योग्य बनती है।",
     "The rumen is grass's pre-processing plant — fermented there, grass becomes fit for cud."),

    ("ingestion-other-animals", "easy",
     "जुगाली (cud) क्या कहलाती है?",
     "What is called cud?",
     ["पचा हुआ भोजन", "रूमेन से लौटाया गया आंशिक-चबा हरा भोजन जिसे प्राणी फिर से धीरे-धीरे चबता है", "पीने का पानी", "सूखा घास-भंडार"],
     ["Digested food", "The partly-chewed green food returned from the rumen, which the animal chews again slowly", "Drinking water", "A dry grass store"],
     1,
     "ग्रास का दूसरा चक्कर — भीगी-किण्वित घास मुँह में लौटकर महीन चबाई पाती है।",
     "Grass's second round — the soaked-fermented grass returns to the mouth for fine chewing."),

    ("ingestion-other-animals", "easy",
     "मेंढक अपना शिकार कैसे पकड़ता है?",
     "How does a frog catch its prey?",
     ["दाँतों से चबाकर", "चिपचिपी लंबी जीभ फेंककर कीट को चिपका लेता है", "पंजों से", "जाल बुनकर"],
     ["By chewing with teeth", "Flicks its sticky long tongue and glues the insect", "With claws", "By weaving a net"],
     1,
     "मेंढक की जीभ तानी हुई चिपचिपी फेंक-छड़ी है — कीड़ा चिपकते ही भीतर।",
     "The frog's tongue is a sticky throw-stick — the insect sticks and it's in."),

    ("ingestion-other-animals", "easy",
     "साँप अपने शिकार को कैसे खाता है?",
     "How does a snake eat its prey?",
     ["टुकड़े काटकर", "बिना चबाए पूरा निगल जाता है — ढीला निचला जबड़ा बड़े शिकार को समा लेता है", "पीसकर", "उबालकर"],
     ["By cutting pieces", "Swallows it whole without chewing — its loose lower jaw accommodates big prey", "By grinding", "By boiling"],
     1,
     "साँप का जबड़ा ताले नहीं बाँधे — फैलाव की हद से परे मुँह खुलता है और शिकार पूरा उतरता है।",
     "The snake's jaw has no fixed lock — the mouth opens beyond limits and the prey goes down whole."),

    ("ingestion-other-animals", "medium",
     "गाय आराम से बैठकर क्या चबाती रहती है — उसे दोबारा चबाने की आवश्यकता क्यों पड़ती है?",
     "What does a cow keep chewing at rest — why does it need to chew again?",
     ["वह रबड़ चबाती है", "घास का सेल्युलोज कठोर है — पहली बार जल्दी-जल्दी निगला भोजन रूमेन में भीग-किण्वित होकर सही चबाई के योग्य बनता है; दोबारा चबाने से महीन होकर पचने लगता है", "उसे ऊब जाती है", "उसके दाँत बढ़ते रहते हैं"],
     ["It chews rubber", "Grass cellulose is tough — the hastily swallowed first round soaks and ferments in the rumen, becoming fit for proper chewing; rechewing grinds it digestible", "It gets bored", "Its teeth keep growing"],
     1,
     "चरते समय शिकार-भय में जल्दी निगलना पड़ता है — आराम के समय की महीन जुगाली उसकी भरपाई।",
     "While grazing, fear of predators forces hasty swallowing — leisure-time fine cud-chewing makes up for it."),

    ("ingestion-other-animals", "medium",
     "रूमेन में रहने वाले सूक्ष्मजीव रूमिनेंट के लिए क्या करते हैं?",
     "What do the microbes living in the rumen do for the ruminant?",
     ["रुधिर बनाते हैं", "सेल्युलोज को तोड़कर पचाने योग्य पोषक में बदलते हैं — जो काम गाय का अपना एंजाइम नहीं कर सकता", "पित्त बनाते हैं", "शरीर को ठंडा करते हैं"],
     ["They make blood", "They break cellulose into digestible nutrients — the very job the cow's own enzymes cannot do", "They make bile", "They cool the body"],
     1,
     "घास का सेल्युलोज केवल रूमेन-जीवाणुओं की किण्वन-कुल्हाड़ी से टूटता है — सहजीवी भागीदारी।",
     "Grass cellulose yields only to the rumen microbes' fermentation-axe — a symbiotic partnership."),

    ("ingestion-other-animals", "medium",
     "रूमिनेंट के पेट के कक्ष कितने होते हैं?",
     "How many chambers does a ruminant's stomach have?",
     ["एक", "दो", "चार (rumen, reticulum, omasum, abomasum)", "तीन"],
     ["One", "Two", "Four (rumen, reticulum, omasum, abomasum)", "Three"],
     2,
     "चार कक्षों की शृंखला — भिगाना, छानना, निचोड़ना और असली पाचन (अबोमैसम = अम्ल-पेट)।",
     "A chain of four chambers — soaking, straining, squeezing and true digestion (abomasum = the acid stomach)."),

    ("ingestion-other-animals", "medium",
     "घास खाने की पूरी प्रक्रिया का सही क्रम चुनिए (रूमिनेंट)।",
     "Choose the correct order of the grass-eating process (ruminant).",
     ["घास चबाकर निगलना → रूमेन में भिगाना-किण्वन → जुगाली मुँह में लौटाना → दोबारा महीन चबाना → अगले कक्षों में पाचन", "घास निगलना → सीधे क्षुद्रांत में पाचन", "घास चबाना → जुगाली बनाना → रूमेन में पाचन खत्म", "घास → अबोमैसम → रूमेन → मुँह"],
     ["Chew-swallow grass → soak-ferment in rumen → return cud to mouth → rechew finely → digest in next chambers", "Swallow grass → digest directly in small intestine", "Chew grass → form cud → finish digestion in rumen", "Grass → abomasum → rumen → mouth"],
     0,
     "पहला निगलना भंडार-ग्रहण है, दूसरी चबाई वास्तविक तैयारी — दो-चरण ग्रहण रूमिनेंट की पहचान।",
     "The first swallow is storage-intake, the second chew the real preparation — two-stage intake is the ruminant's signature."),

    ("ingestion-other-animals", "medium",
     "गाय घास से जीवित रह लेती है पर मनुष्य घास खाकर नहीं — मूल कारण?",
     "A cow survives on grass but a human cannot — the root cause?",
     ["मनुष्य का पेट छोटा है", "मनुष्य में सेल्युलोज-पचाने वाला रूमेन-सूक्ष्मजीव संगठन नहीं — सेल्युलोज उसके लिए अपचा रेशा बन जाता है", "मनुष्य को घास स्वादहीन लगती है", "गाय के दाँत तेज़ होते हैं"],
     ["The human stomach is small", "Humans lack the rumen-microbe setup for cellulose — cellulose stays an undigested fibre for them", "Grass tastes bad to humans", "A cow's teeth are sharp"],
     1,
     "सेल्युलोज-कुंजी रूमेन-जीवाणुओं के पास है — वह चाबी केवल रूमिनेंट-पेट में बनती है।",
     "The cellulose-key lies with rumen microbes — that key is cut only in a ruminant stomach."),

    ("ingestion-other-animals", "medium",
     "मकड़ी अपने शिकार (कीड़ा) को कैसे 'खाती' है?",
     "How does a spider 'eat' its prey (an insect)?",
     ["चबाकर निगलती है", "जहर-एंजाइम उगलकर शिकार के भीतर डालती है और भीतर ही पचा हुआ तरल ऊपर चूस लेती है — बाहरी पाचन", "पूरा निगल जाती है", "केवल रक्त पीती है"],
     ["Chews and swallows it", "Spits venom-enzymes into the prey and sucks up the liquefied digested interior — extracellular digestion outside its own gut", "Swallows it whole", "Only drinks blood"],
     1,
     "मकड़ी का पेट शिकार के शरीर में ही बन जाता है — पाचन बाहर, भोजन भीतर।",
     "The prey's own body becomes the spider's digestion vat — digestion outside, dinner inside."),

    ("ingestion-other-animals", "medium",
     "पक्षियों में फसल (crop) और पेषणी (gizzard) का कार्य क्या है?",
     "What do the crop and the gizzard do in birds?",
     ["फसल — भोजन भिगोकर संग्रह; पेषणी — कंकर-जैसी स्थिति में द्रव्यमान कूट-पीस करती है (दाँत न होने की भरपाई)", "फसल — पाचन; पेषणी — श्वसन", "फसल — अंडे; पेषणी — उड़ान", "दोनों केवल जल-संग्रह"],
     ["Crop — soaks and stores food; gizzard — grinds the bulk pebble-like (making up for no teeth)", "Crop — digestion; gizzard — respiration", "Crop — eggs; gizzard — flight", "Both only water-storage"],
     0,
     "बिना दाँत वाले पक्षी की चूल्हा-चक्की: फसल भंडार-भिगोती है, पेषणी रेत-कंकर के साथ चक्की पीसती है।",
     "The toothless bird's stove-and-mill: the crop stores-soaks, the gizzard mills with sand-grit."),

    ("ingestion-other-animals", "medium",
     "व्हेल के मुँह की पट्टिकाएँ (baleen) किस काम आती हैं?",
     "What are the baleen plates in a whale's mouth used for?",
     ["भोजन चबाने", "जल से सूक्ष्म जीवों को छानकर फँसाना — फिल्टर-भोजन की प्रणाली", "श्वास लेने", "ध्वनि निकालने"],
     ["Chewing food", "Straining tiny organisms from the water — a filter-feeding apparatus", "Breathing", "Making sound"],
     1,
     "बाल्वीन-पट्टिकाएँ जाली-परदे हैं — विशाल जल-घूँट को छानकर क्रिल-प्लवक रोक लेती हैं।",
     "Baleen plates are mesh-curtains — sieving giant mouthfuls of water to trap krill-plankton."),

    ("ingestion-other-animals", "medium",
     "हमिंगबर्ड की लंबी पतली चोंच किस भोजन-ग्रहण से जुड़ी है?",
     "The long slender beak of a hummingbird is linked to which food habit?",
     ["बीज तोड़ने", "फूल की गहराई से मधु-रस चूसना — तरल-आहार की विशेषज्ञ चोंच", "मांस फाड़ने", "मछली पकड़ने"],
     ["Cracking seeds", "Sucking nectar from deep inside flowers — a beak specialised for liquid diet", "Tearing meat", "Catching fish"],
     1,
     "नली-चोंच और गहरा फूल एक-दूसरे के पूरक — मधु-जोड़ी का सहजीवी नमूना।",
     "The tube-beak and the deep flower complement each other — a classic specimen of the nectar pair."),

    ("ingestion-other-animals", "hard",
     "तारामीन (starfish) दो-खोलवाले मोलस्क को कैसे खाता है?",
     "How does a starfish eat a bivalve mollusc?",
     ["कवच तोड़कर निगलता है", "भुजाओं से कवच खोलकर अपना आमाशय मुँह से बाहर निकाल भीतर डालता है — शिकार को उसके घर में ही पचाकर सोख लेता है", "केवल रस चूसता है", "जहर डालकर घोल देता है"],
     ["Breaks the shell and swallows", "Pries the shell open with its arms, pushes its stomach out through its mouth into the shell — digests the prey inside its own home and absorbs it", "Only sucks juice", "Dissolves it with venom"],
     1,
     "पेट का उल्टा निकास — तारामीन का पाचन पेट बाहर लाकर करता है: कवच के भीतर ही रसोई।",
     "The stomach's outward deployment — the starfish digests by carrying its stomach out: the kitchen inside the shell itself."),

    # ---------------- digestive-wellness-disorders (15: E5/M7/H3) ----------------
    ("digestive-wellness-disorders", "easy",
     "अजीर्ण (indigestion) के सामान्य कारणों में क्या शामिल है?",
     "What is included among the common causes of indigestion?",
     ["संतुलित भोजन", "अधिक खाना, बहुत तेज़ खाना, बिना भली-भाँति चबाए निगलना", "रोज़ व्यायाम", "पर्याप्त जल"],
     ["Balanced food", "Overeating, eating too fast, swallowing without proper chewing", "Daily exercise", "Enough water"],
     1,
     "पेट की क्षमता से अधिक या तैयारी के बिना डाला भोजन — अजीर्ण का मूल सूत्र।",
     "Food pushed beyond the stomach's capacity or without preparation — indigestion's root formula."),

    ("digestive-wellness-disorders", "easy",
     "भोजन को धीरे-धीरे अच्छी तरह चबाना पाचन के लिए सीधा लाभ क्या देता है?",
     "What direct benefit does slow, thorough chewing give to digestion?",
     ["कम खाना पड़ता है", "भोजन लार से भली-भाँति मिल जाता है और छोटे टुकड़ों के रूप में पेट पहुँचता है — आगे का काम हल्का", "भूख बढ़ती है", "वजन तेज़ी से बढ़ता है"],
     ["One needs to eat less", "Food blends well with saliva and reaches the stomach in small pieces — the workload ahead stays light", "Hunger grows", "Weight rises fast"],
     1,
     "चबाई ही मुँह की आधी पाचन-तैयारी है — पेट-आँत का बोझ घटता है।",
     "Chewing itself is half the mouth's digestive prep — the stomach-gut's load shrinks."),

    ("digestive-wellness-disorders", "easy",
     "भोजन से पहले हाथ धोना किस आदत-वर्ग का स्वास्थ्य-नियम है?",
     "Washing hands before eating belongs to which habit-class of health rules?",
     ["खेल-नियम", "खाद्य-स्वच्छता (food hygiene) — पाचन-तंत्र को दूषित हाथों से होने वाले नुकसान से बचाने का नियम", "नींद-नियम", "अध्ययन-नियम"],
     ["A rule of play", "Food hygiene — the rule that shields the digestive system from harm by unclean hands", "A rule of sleep", "A rule of study"],
     1,
     "स्वच्छ हाथ-थाली की रेखा ही पाचन-स्वास्थ्य की पहली ढाल।",
     "The line of clean hands-plate is digestive health's first shield."),

    ("digestive-wellness-disorders", "easy",
     "बासी या अधपका भोजन पाचन के लिए क्यों हानिकारक माना जाता है?",
     "Why is stale or half-cooked food considered harmful for digestion?",
     ["वह महँगा होता है", "वह पाचन पर असामान्य बोझ डालता है और पेट-खराबी का सामान्य कारण बनता है — ताज़ा, सलामत पका भोजन ही सुरक्षित", "वह ठंडा होता है", "वह रंगीन होता है"],
     ["It is costly", "It puts abnormal strain on digestion and is a common cause of an upset stomach — fresh, properly cooked food alone is safe", "It is cold", "It is colourful"],
     1,
     "बासी-अधपका भोजन पेट की परीक्षा में उत्तीर्ण नहीं — ताज़ापन और पूर्ण पकाना ही मानक।",
     "Stale-half-cooked food fails the stomach's test — freshness and full cooking are the standard."),

    ("digestive-wellness-disorders", "easy",
     "दिन भर में पर्याप्त जल पीना पाचन में क्या सहायता करता है?",
     "How does drinking enough water through the day help digestion?",
     ["भोजन को जमाता है", "भोजन-रस को उचित तरलता देता है और मल को चिकना रखता है — नियमित मल-त्याग में सहायक", "भूख मारता है", "पेट फुलाता है"],
     ["It thickens the food", "Gives the food juice proper fluidity and keeps the stool smooth — aiding regular bowel movement", "It kills hunger", "It bloats the belly"],
     1,
     "जल पाचन-नली का चिकनाई-माध्यम है — कमी तुरंत कब्ज की ओर ले जाती है।",
     "Water is the gut's lubricating medium — its shortage leads straight to constipation."),

    ("digestive-wellness-disorders", "medium",
     "अति-तीखा या अति-तेल-मसाले वाला भोजन कुछ लोगों में क्या करता है?",
     "What does very spicy or oily food do in some people?",
     ["पाचन सुधारता है", "आमाशय के अम्ल-रस की असंतुलन-स्थिति और भारी बेचैनी (heartburn जैसी) पैदा कर सकता है", "भूख मारता है", "वजन घटाता है"],
     ["Improves digestion", "Can upset the stomach's acid-juice balance and produce heavy discomfort (heartburn-like)", "Kills appetite", "Reduces weight"],
     1,
     "क्षमता से अधिक तीखा-तैला भोजन पेट की अम्ल-व्यवस्था को डिस्टर्ब करता है — जलन-बेचैनी।",
     "Spice-oil beyond capacity disturbs the stomach's acid order — burning-uneasiness."),

    ("digestive-wellness-disorders", "medium",
     "एंटासिड (antacid) दवाएँ पाचन-असुविधा में क्या करती हैं?",
     "What do antacid medicines do in digestive discomfort?",
     ["भोजन पचाती हैं", "आमाशय के अतिरिक्त अम्ल को उदासीन कर (नमक-जल में बदलकर) जलन-भारीपन से राहत देती हैं", "लार बढ़ाती हैं", "मल कड़ा करती हैं"],
     ["They digest the food", "Neutralise the stomach's excess acid (turning it to salt-water), relieving burning-heaviness", "They increase saliva", "They harden the stool"],
     1,
     "एंटासिड क्षारीय-दूध-ऑफ-मैग्नीशिया श्रेणी की जलन-शांति है — अम्ल-जलन का रसायन-उत्तर।",
     "An antacid is the alkaline milk-of-magnesia class of burning-calmer — chemistry's answer to acid-heartburn."),

    ("digestive-wellness-disorders", "medium",
     "दस्त (diarrhoea) में शरीर को सबसे बड़ा खतरा किससे होता है?",
     "What is the biggest danger to the body in diarrhoea?",
     ["भूख से", "जल और लवणों की तीव्र हानि से — निर्जलीकरण (dehydration)", "नींद की कमी से", "वजन बढ़ने से"],
     ["From hunger", "From rapid loss of water and salts — dehydration", "From lack of sleep", "From weight gain"],
     1,
     "बार-बार मल-त्याग शरीर का जल-लवण खींच लेता है — दस्त की असली चेतावनी निर्जलीकरण है।",
     "Frequent stools drain the body's water-salts — diarrhoea's real alarm is dehydration."),

    ("digestive-wellness-disorders", "medium",
     "ORS (मुँह से पुनर्जलीकरण लवण) में मुख्यतः क्या होता है?",
     "What does ORS (oral rehydration salts) mainly contain?",
     ["केवल शुद्ध जल", "जल में घुला नमक और चीनी (ग्लूकोस) का निर्धारित अनुपात-मिश्रण", "केवल दूध", "फलों का रस"],
     ["Only pure water", "A set-proportion mix of salt and sugar (glucose) dissolved in water", "Only milk", "Fruit juice"],
     1,
     "नमक + चीनी + सुरक्षित जल — दस्त से छिने जल-लवण की सीधी वापसी का घरेलू-वैज्ञानिक नुस्खा।",
     "Salt + sugar + safe water — the home-scientific recipe for the direct return of water-salts looted by diarrhoea."),

    ("digestive-wellness-disorders", "medium",
     "आहारीय रेशा (dietary fibre) कब्ज से कैसे बचाता है?",
     "How does dietary fibre protect against constipation?",
     ["वह पचकर मल चिपकाता है", "वह अपचा रहकर मल को थोक और नरमी देता है — आँत की धकेलन-क्रिया नियमित चलती है", "वह जल सोख लेता है पूरा", "वह लार बढ़ाता है"],
     ["It digests and sticks the stool", "Staying undigested, it gives the stool bulk and softness — the bowel's push-action stays regular", "It absorbs all the water", "It increases saliva"],
     1,
     "रेशा मल की रीढ़ है — सलाद-फल-साबुत अनाज रोज़ रखें तो कब्ज दूर।",
     "Fibre is the stool's spine — daily salad-fruit-wholegrain keeps constipation away."),

    ("digestive-wellness-disorders", "medium",
     "समय पर और नियमित भोजन-दिनचर्या पाचन में क्यों सहायक है?",
     "Why is a regular meal timetable helpful for digestion?",
     ["घर सुंदर लगता है", "पाचन-रस भोजन-समय के अनुसार अभ्यस्त हो जाते हैं — नियमित रिदम में रस-स्राव और आँत-गति संतुलित रहती है", "कम खर्च होता है", "तेज़ भूख लगती है"],
     ["The house looks nice", "Digestive juices get accustomed to meal-times — in a set rhythm, juice secretion and gut movement stay balanced", "Cost falls", "Hunger rises fast"],
     1,
     "पेट घड़ी की तरह चलता है — अनियमित समय रस-स्राव का कार्यक्रम बिगाड़ देता है।",
     "The stomach runs like a clock — irregular hours wreck the juice-secretion programme."),

    ("digestive-wellness-disorders", "medium",
     "फास्ट-फूड/जंक-फूड को पाचन-दृष्टि से कमजोर आहार क्यों कहा जाता है?",
     "Why is fast/junk food called a weak diet from the digestive point of view?",
     ["वह जल्दी खत्म होता है", "उसमें प्रायः रेशा-विटामिन न्यून और वसा-नमक-चीनी अति — पाचन पर वसा-बोझ और रेशा-घाटा दोनों", "वह गरम होता है", "वह रंगीन थाली में आता है"],
     ["It finishes quickly", "It is usually low in fibre-vitamins and excess in fat-salt-sugar — both a fat-burden on digestion and a fibre-deficit", "It is hot", "It comes on a coloured plate"],
     1,
     "जंक-थाली का समीकरण: रेशा शून्य के पास, वसा-ऊंचाई पर — आँत के लिए दोहरा अभिशाप।",
     "The junk-plate equation: fibre near zero, fat at peak — a double curse for the gut."),

    ("digestive-wellness-disorders", "hard",
     "ORS में चीनी (ग्लूकोस) केवल स्वाद के लिए क्यों नहीं होती?",
     "Why is the sugar (glucose) in ORS not there just for taste?",
     ["चीनी दवा है", "आँत में जल-अवशोषण की यंत्रावली में ग्लूकोस और सोडियम साथ-साथ सोखे जाते हैं — ग्लूकोस के साथ जल-पुनर्जलीकरण भी तेज़ होता है", "चीनी रंग देती है", "चीनी मल जमाती है"],
     ["Sugar is a drug", "In the gut's absorption machinery, glucose and sodium are absorbed together — with glucose, water rehydration also speeds up", "Sugar adds colour", "Sugar hardens the stool"],
     1,
     "आँत की सह-परिवहन युक्ति: ग्लूकोस-सोडियम जोड़ी खींचती है, पानी उसी के पीछे — इसीलिए ORS में दोनों।",
     "The gut's co-transport trick: the glucose-sodium pair pulls, water follows — hence both in ORS."),

    ("digestive-wellness-disorders", "hard",
     "दस्त में शुद्ध जल पीना ORS पीने से कम प्रभावी क्यों हो सकता है?",
     "Why can drinking plain water during diarrhoea be less effective than drinking ORS?",
     ["जल में स्वाद नहीं", "जल खून के लवण-घनत्व को और घटा सकता है; लवण-नियंत्रित ORS जल-सोडियम संतुलन दोनों साथ बहाल करता है", "जल ठंडा होता है", "जल पेट में रुकता नहीं"],
     ["Water has no taste", "Plain water can further dilute the blood's salt concentration; the salt-controlled ORS restores both water and sodium balance together", "Water is cold", "Water does not stay in the stomach"],
     1,
     "सिर्फ जल भरपाई लवण-भरपाई नहीं — दस्त दोनों उड़ाता है, दोनों लौटाने पड़ेंगे।",
     "Water-only refilling is not salt-refilling — diarrhoea blows away both, both must return."),

    ("digestive-wellness-disorders", "hard",
     "दूध-ऑफ-मैग्नीशिया जैसी एंटासिड पेट की जलन में राहत किस अभिक्रिया से देती है?",
     "By which reaction does an antacid like milk of magnesia relieve stomach burning?",
     ["अम्ल-जोड़ (addition)", "क्षार का अम्ल पर उदासीनीकरण (neutralisation) — मैग्नीशिया-हाइड्रॉक्साइड अतिरिक्त HCl से प्रतिक्रिया कर क्लोराइड-लवण और जल बनाता है", "वाष्पीकरण", "किण्वन"],
     ["Acid addition", "Neutralisation of acid by the alkali — magnesium hydroxide reacts with excess HCl to form a chloride salt and water", "Vaporisation", "Fermentation"],
     1,
     "क्षार + अम्ल → लवण + जल — पेट की चूल्हे-पर छिड़की यही उदासीनीकरण-रसायन है।",
     "Alkali + acid → salt + water — this neutralisation chemistry is the sprinkler on the stomach's fire."),
]
