# -*- coding: utf-8 -*-
"""B07 'Respiration & Gas Exchange' — Part 2 data (80 items).
Order: gas-exchange-transport (30), respiration-other-organisms (30), respiration-vs-other-processes (20).
Tuple: (topic, difficulty, q_hi, q_en, options_hi[4], options_en[4], correct_idx, exp_hi, exp_en)
"""

PART2 = [
    # ---------------- gas-exchange-transport (30: E9/M18/H3) ----------------
    ("gas-exchange-transport", "easy",
     "वायुकोश से रुधिर में ऑक्सीजन किस दिशा में जाती है और क्यों?",
     "In which direction does oxygen move from the alveoli into the blood, and why?",
     ["रुधिर से वायुकोश की ओर — CO2 का खिंचाव", "वायुकोश से रुधिर की ओर — वायुकोश में O2 की सांद्रता अधिक होने से", "कोई गति नहीं होती", "दोनों दिशाओं में बराबर"],
     ["From blood to alveoli — pulled by CO2", "From alveoli to blood — because the O2 concentration in alveoli is higher", "No movement occurs", "Equally in both directions"],
     1,
     "गैसें सदा अधिक सांद्रता से कम सांद्रता की ओर फैलती हैं — वायुकोश की हवा में O2 ज्यादा, इसलिए वह रुधिर में उतरती है।",
     "Gases always diffuse from higher to lower concentration — alveolar air holds more O2, so it descends into the blood."),

    ("gas-exchange-transport", "easy",
     "मानव में श्वसन-वर्णक (respiratory pigment) का नाम क्या है?",
     "What is the name of the respiratory pigment in humans?",
     ["क्लोरोफिल", "हीमोग्लोबिन", "मेलेनिन", "कैरोटीन"],
     ["Chlorophyll", "Haemoglobin", "Melanin", "Carotene"],
     1,
     "हीमोग्लोबिन लोहे युक्त वर्णक है जो ऑक्सीजन से जुड़कर उसे शरीर भर में ले जाता है।",
     "Haemoglobin is the iron-rich pigment that binds oxygen and ferries it around the body."),

    ("gas-exchange-transport", "easy",
     "हीमोग्लोबिन रुधिर के किस घटक में रहता है?",
     "In which component of blood does haemoglobin reside?",
     ["प्लाज्मा में घुला", "लाल रुधिर कणिकाओं (RBC) के भीतर", "श्वेत कणिकाओं में", "पटिकाओं में"],
     ["Dissolved in plasma", "Inside red blood cells (RBCs)", "In white blood cells", "In platelets"],
     1,
     "हीमोग्लोबिन RBC के भीतर भरा रहता है — इसीलिए ऑक्सीजन-परिवहन का काम लाल कणिकाएँ करती हैं।",
     "Haemoglobin is packed inside RBCs — hence the red cells handle oxygen transport."),

    ("gas-exchange-transport", "easy",
     "रुधिर वायुकोशों पर पहुँचकर भीतर की हवा में कौन-सी गैस छोड़ता है?",
     "Which gas does the blood release into the air of the alveoli?",
     ["ऑक्सीजन", "नाइट्रोजन", "कार्बन डाइऑक्साइड", "हीलियम"],
     ["Oxygen", "Nitrogen", "Carbon dioxide", "Helium"],
     2,
     "ऊतकों से लाई गई CO2 वायुकोशों में छोड़ी जाती है और साँस के साथ बाहर निकलती है।",
     "The CO2 brought from tissues is dropped into the alveoli and leaves with the exhaled breath."),

    ("gas-exchange-transport", "easy",
     "वायुकोशों और केशिकाओं के बीच गैसों का आदान-प्रदान किस प्रक्रिया से होता है?",
     "By which process are gases exchanged between the alveoli and the capillaries?",
     ["सक्रिय परिवहन", "सरल विसरण (diffusion)", "परासरण", "निस्पंदन"],
     ["Active transport", "Simple diffusion", "Osmosis", "Filtration"],
     1,
     "गैस-विनिमय ऊर्जा खर्च किए बिना सांद्रता-अंतर से स्वतः होता है — यही सरल विसरण है।",
     "Gas exchange happens by itself along concentration gradients without energy — simple diffusion."),

    ("gas-exchange-transport", "easy",
     "वायुकोशों को बाहर से कौन-सी सूक्ष्म रुधिर वाहिकाएँ घेरे रहती हैं?",
     "Which tiny blood vessels surround the alveoli?",
     ["धमनियाँ", "नसें", "केशिकाएँ (capillaries)", "लसीका वाहिकाएँ"],
     ["Arteries", "Veins", "Capillaries", "Lymph vessels"],
     2,
     "वायुकोशों की दीवार से चिपकी केशिकाओं का जाल ही गैसों को रुधिर तक पहुँचाता है।",
     "A mesh of capillaries hugging the alveolar walls is what hands the gases to the blood."),

    ("gas-exchange-transport", "easy",
     "वायुकोश तथा उनकी केशिकाओं की दीवारें अत्यंत पतली क्यों होती हैं?",
     "Why are the walls of the alveoli and their capillaries extremely thin?",
     ["हवा को रोकने के लिए", "गैसों को तय करनी पड़ने वाली दूरी न्यूनतम रहे इसलिए", "दिखने में सुंदर लगे", "रुधिर को गाढ़ा करने के लिए"],
     ["To hold back the air", "So the distance the gases must travel stays minimal", "To look nice", "To thicken the blood"],
     1,
     "पतली दीवारें विसरण-दूरी घटाती हैं — O2 और CO2 तुरंत पार जाती हैं; मोटी दीवार विनिमय धीमा दे देती।",
     "Thin walls cut the diffusion distance — O2 and CO2 cross instantly; a thick wall would slow the exchange."),

    ("gas-exchange-transport", "easy",
     "ऑक्सीजन से भरपूर रुधिर का रंग कैसा होता है?",
     "What is the colour of oxygen-rich blood?",
     ["गहरा नीला", "चमकीला लाल (bright red)", "हरा", "पीला"],
     ["Deep blue", "Bright red", "Green", "Yellow"],
     1,
     "ऑक्सीहीमोग्लोबिन बनने से ऑक्सीजन-युक्त रुधिर चमकीला लाल दिखता है; CO2-प्रधान रुधिर गहरा-मटमैला होता है।",
     "Oxyhaemoglobin makes oxygen-loaded blood bright red; CO2-heavy blood looks darker and duller."),

    ("gas-exchange-transport", "easy",
     "फेफड़ों की केशिकाओं में हीमोग्लोबिन से ऑक्सीजन के जुड़ने पर बनने वाला यौगिक क्या कहलाता है?",
     "What is the compound formed when oxygen binds haemoglobin in the lung capillaries called?",
     ["कार्बोहीमोग्लोबिन", "ऑक्सीहीमोग्लोबिन", "ग्लूकोहीमोग्लोबिन", "मेथहीमोग्लोबिन"],
     ["Carbhaemoglobin", "Oxyhaemoglobin", "Glucohaemoglobin", "Methaemoglobin"],
     1,
     "O2 + Hb → ऑक्सीहीमोग्लोबिन — यही रूप ऑक्सीजन को शरीर की कोशिकाओं तक ढोता है।",
     "O2 + Hb → oxyhaemoglobin — this is the form that carries oxygen to the body's cells."),

    ("gas-exchange-transport", "medium",
     "गैस-विनिमय में 'सांद्रता-प्रवणता (concentration gradient)' से क्या तात्पर्य है?",
     "What is meant by 'concentration gradient' in gas exchange?",
     ["दोनों ओर समान मात्रा", "दो स्थानों के बीच गैस की सांद्रता का अंतर जो विसरण की दिशा तय करता है", "गैस का भार", "हवा की गति"],
     ["Equal amounts on both sides", "The difference in gas concentration between two places that sets the direction of diffusion", "The weight of the gas", "The speed of air"],
     1,
     "जहाँ गैस ज्यादा, वहाँ से कम वाली ओर बहना ही प्रवणता का काम है — विनिमय की दिशा यही तय करती है।",
     "Flowing from where the gas is plentiful to where it is scarce is what a gradient does — it fixes the direction of exchange."),

    ("gas-exchange-transport", "medium",
     "रुधिर में ऑक्सीजन किन दो रूपों में यात्रा करती है?",
     "In which two forms does oxygen travel in the blood?",
     ["प्लाज्मा में घुली और हीमोग्लोबिन से जुड़ी", "पटिकाओं में और WBC में", "केवल घुली हुई", "केवल लाल कणिकाओं के बाहर"],
     ["Dissolved in plasma and bound to haemoglobin", "In platelets and in WBCs", "Only dissolved", "Only outside the red cells"],
     0,
     "अधिकांश O2 हीमोग्लोबिन से जुड़ी रहती है, थोड़ी मात्रा प्लाज्मा में घुली — दोनों रूप मिलकर परिवहन पूरा करते हैं।",
     "Most O2 rides bound to haemoglobin and a small share dissolves in plasma — together the two forms complete the transport."),

    ("gas-exchange-transport", "medium",
     "CO2 का अधिकांश भाग रुधिर में किस रूप में ले जाया जाता है?",
     "In which form is most of the CO2 carried in the blood?",
     ["हीमोग्लोबिन से जुड़कर", "प्लाज्मा में घुलकर", "RBC के भीतर कैद होकर", "पटिकाओं में"],
     ["Bound to haemoglobin", "Dissolved in plasma", "Trapped inside RBCs", "In platelets"],
     1,
     "CO2 जल में अत्यंत घुलनशील है — इसीलिए उसका बड़ा हिस्सा प्लाज्मा में घुलकर फेफड़ों तक पहुँचता है।",
     "CO2 is highly soluble in water — so its larger share travels dissolved in plasma to the lungs."),

    ("gas-exchange-transport", "medium",
     "शरीर की कोशिकाओं के पास पहुँची केशिकाओं से गैसें किस दिशा में जाती हैं?",
     "In which directions do the gases move across capillaries reaching the body's cells?",
     ["O2 कोशिकाओं में, CO2 रुधिर में", "O2 रुधिर में वापस, CO2 कोशिकाओं में", "दोनों रुधिर में", "कोई गति नहीं"],
     ["O2 into the cells, CO2 into the blood", "O2 back into blood, CO2 into cells", "Both into the blood", "No movement"],
     0,
     "ऊतक-स्तर पर दिशा उलट जाती है — कोशिकाओं की O2 कम होती है और CO2 ज्यादा, इसलिए O2 भीतर और CO2 रुधिर में आती है।",
     "At tissue level the directions flip — cells are low in O2 and rich in CO2, so O2 exits and CO2 enters the blood."),

    ("gas-exchange-transport", "medium",
     "मानव शरीर में गैस-विनिमय के दो स्थल कौन-से हैं?",
     "Which are the two sites of gas exchange in the human body?",
     ["नाक और स्वरयंत्र", "वायुकोश (फेफड़े) और ऊतक-कोशिकाएँ", "श्वासनली और ब्रांकाई", "हृदय और यकृत"],
     ["Nose and larynx", "Alveoli (lungs) and tissue cells", "Trachea and bronchi", "Heart and liver"],
     1,
     "पहला विनिमय वायुकोशों पर (हवा से रुधिर) और दूसरा ऊतकों पर (रुधिर से कोशिकाएँ) — दो स्थल, एक ही विसरण-नियम।",
     "The first exchange occurs at the alveoli (air to blood) and the second at the tissues (blood to cells) — two sites, one diffusion rule."),

    ("gas-exchange-transport", "medium",
     "वायुकोशों की भीतरी सतह नम रहना क्यों जरूरी है?",
     "Why must the inner surface of the alveoli stay moist?",
     ["हवा को ठंडा करने के लिए", "गैसें घुलकर ही पतली दीवार पार कर सकती हैं", "धूल बाहर करने के लिए", "आवाज़ के लिए"],
     ["To cool the air", "Gases can cross the thin wall only after dissolving", "To expel dust", "For the voice"],
     1,
     "विसरण पहले द्रव में घुलने से शुरू होता है — सूखी सतह पर O2/CO2 का पारगमन ठप हो जाता।",
     "Diffusion begins with dissolving into a fluid — on a dry surface the passage of O2/CO2 would stall."),

    ("gas-exchange-transport", "medium",
     "'साँस लेना ही श्वसन है' — यह कथन किस कारण अधूरा है?",
     "Why is the statement 'breathing itself is respiration' incomplete?",
     ["साँस केवल हवा का बाहर-भीतर है; ऊर्जा-निर्माण तो कोशिकाओं के भीतर श्वसन से होता है", "साँस में भी ATP बनता है", "श्वसन फेफड़ों में होता है", "दोनों एक ही हैं, कथन सही है"],
     ["Breathing is only the in-and-out of air; energy is actually released by respiration inside the cells", "ATP is made during breathing too", "Respiration happens in the lungs", "Both are the same, the statement is right"],
     0,
     "श्वास-क्रिया भौतिक पहुँचाने का काम है, कोशिकीय श्वसन जैव-रासायनिक ऊर्जा-क्रिया — दोनों को मिलाकर गलतफहम बनती है।",
     "Breathing is the physical delivery job while cellular respiration is the biochemical energy event — conflating the two creates the confusion."),

    ("gas-exchange-transport", "medium",
     "भारी व्यायाम के दौरान गैस-विनिमय की दर क्यों बढ़ जाती है?",
     "Why does the rate of gas exchange rise during heavy exercise?",
     ["हवा में O2 बढ़ जाती है", "कोशिकाओं की O2-माँग और CO2-उत्पादन दोनों बढ़ जाते हैं — प्रवणताएँ तेज हो जाती हैं", "फेफड़े बड़े हो जाते हैं", "रुधिर कम हो जाता है"],
     ["O2 in the air increases", "The cells' O2 demand and CO2 output both rise — the gradients turn steeper", "The lungs enlarge", "The blood volume drops"],
     1,
     "तेज काम से ऊतकों की O2 खपत बढ़ती और CO2 जमा होती है — तीव्र प्रवणताएँ विनिमय की रफ्तार बढ़ा देती हैं।",
     "Hard work raises the tissues' O2 consumption and CO2 build-up — steeper gradients speed up the exchange."),

    ("gas-exchange-transport", "medium",
     "हीमोग्लोबिन फेफड़ों में ऑक्सीजन कैसे 'पकड़'कर ऊतकों में 'छोड़' देता है?",
     "How does haemoglobin 'grab' oxygen in the lungs and 'release' it in the tissues?",
     ["दोनों जगह समान रूप से पकड़ता है", "O2-प्रवणता के अनुसार — फेफड़ों की अधिक O2 में बंधता और ऊतकों की कम O2 में मुक्त होता है", "तापमान से ही नियंत्रित होता है", "प्रकाश से नियंत्रित होता है"],
     ["It binds equally at both places", "Along the O2 gradient — binding where O2 is high in lungs, letting go where O2 is low in tissues", "Only temperature controls it", "Light controls it"],
     1,
     "बंधन-मुक्ति O2 की उपलब्धता के अनुसार चलती है — यही हीमोग्लोबिन को ऑक्सीजन का स्मार्ट वाहक बनाती है।",
     "Binding-and-release follows O2 availability — this makes haemoglobin a smart oxygen carrier."),

    ("gas-exchange-transport", "medium",
     "अमीबा जैसे एककोशिकीय जीवों को श्वसन-वर्णक की जरूरत क्यों नहीं पड़ती?",
     "Why do unicellular organisms like Amoeba not need a respiratory pigment?",
     ["वे श्वसन नहीं करते", "उनकी समस्त कोशिका-सतह से विसरण प्रत्यक्ष और पर्याप्त है", "उनमें O2 का उपयोग नहीं होता", "वे प्रकाश-संश्लेषण करते हैं"],
     ["They do not respire", "Diffusion directly across their whole cell surface is sufficient", "They do not use O2", "They photosynthesise"],
     1,
     "जीव छोटा, दूरियां न्यूनतम — सतही विसरण से हर कोशिका-भाग तक O2 तुरंत पहुँच जाती है; वाहक की जरूरत ही नहीं रहती।",
     "The body is tiny and distances minimal — surface diffusion promptly delivers O2 to every part; no carrier is needed."),

    ("gas-exchange-transport", "medium",
     "RBC और प्लाज्मा का गैस-परिवहन में बँटवारा कैसा है?",
     "How is the gas-transport work divided between RBCs and plasma?",
     ["RBC सब कुछ ढोती हैं", "मुख्यतः O2 का भार RBC (हीमोग्लोबिन) का और घुली CO2 का भार प्लाज्मा का", "प्लाज्मा O2 ढोता है, RBC कुछ नहीं", "दोनों केवल CO2 ढोते हैं"],
     ["RBCs carry everything", "Chiefly O2 is carried by RBCs (haemoglobin) and dissolved CO2 by plasma", "Plasma carries O2, RBCs nothing", "Both carry only CO2"],
     1,
     "लाल कणिकाएँ हीमोग्लोबिन से O2 जोड़ती हैं जबकि CO2 का बड़ा अंश प्लाज्मा में घुला रहता है — काम बँटा हुआ है।",
     "Red cells hook O2 to haemoglobin while most CO2 stays dissolved in plasma — the work is shared."),

    ("gas-exchange-transport", "medium",
     "कोशिका-झिल्ली के पार ऑक्सीजन का प्रवेश किस शर्त में होगा?",
     "Under which condition will oxygen cross the cell membrane?",
     ["झिल्ली के भीतर O2 की सांद्रता बाहर से अधिक हो", "बाहर की सांद्रता भीतर से अधिक हो", "दोनों ओर सांद्रता समान हो", "O2 का प्रवेश कभी नहीं होता"],
     ["When O2 concentration inside the membrane is higher than outside", "When the outside concentration is higher than inside", "When concentrations are equal on both sides", "O2 never enters"],
     1,
     "विसरण का नियम — प्रवणता के अनुकूल ही बहता है; भीतर कम हो तो बाहर से O2 अंदर आएगी।",
     "The rule of diffusion — flow follows the gradient; if inside is lower, O2 will enter from outside."),

    ("gas-exchange-transport", "medium",
     "CO2 को 'श्वसन-अपशिष्ट' क्यों कहा जाता है?",
     "Why is CO2 called a 'respiratory waste'?",
     ["वह भोजन में मिलावट है", "कोशिकीय श्वसन के दौरान बनकर रुधिर में उठती और फेफड़ों से निकलती है", "वह प्रकाश-संश्लेषण का कचरा है", "वह जल का रूप है"],
     ["It is an adulterant in food", "It forms during cellular respiration, rides the blood and exits via the lungs", "It is photosynthetic rubbish", "It is a form of water"],
     1,
     "ग्लूकोज़ के विघटन में जो CO2 बचती है वह कोशिका के लिए बेकार है — रुधिर उसे उठाकर फेफड़ों से बाहर कर देता है।",
     "The CO2 left over from glucose breakdown is useless to the cell — blood carts it away and the lungs expel it."),

    ("gas-exchange-transport", "medium",
     "वायुकोशों और ऊतकों पर गैस-प्रवणताएँ लगातार कायम कैसे रहती हैं?",
     "How are the gas gradients at the alveoli and tissues kept alive continuously?",
     ["गैसें एक बार बनकर रुक जाती हैं", "साँस लगातार ताजी हवा लाती है और कोशिकाएं लगातार O2 खपत- CO2 निर्माण करती हैं", "हृदय गैसें बनाता है", "प्रवणताएँ स्थिर होती हैं कभी नहीं बदलतीं"],
     ["Gases form once and stop", "Breathing keeps bringing fresh air while cells keep consuming O2 and making CO2", "The heart manufactures gases", "Gradients stay fixed and never change"],
     1,
     "आगमन-निर्माण की निरंतरता ही प्रवणता को बनाए रखती है — साँस रुके तो विनिमय शीघ्र थम जाता।",
     "Continual supply and consumption maintain the gradient — stop breathing and the exchange soon halts."),

    ("gas-exchange-transport", "medium",
     "रुधिर-वाहिकाओं की दीवारें केशिकाओं पर सबसे पतली होना विनिमय के लिए क्यों उपयोगी है?",
     "Why is it useful for exchange that capillary walls are the thinnest of all blood vessels?",
     ["रुधिर तेज बहता है", "पदार्थों और गैसों का केशिका-भित्ति पार करना सरल हो जाता है", "दिल को कम मेहनत करनी पड़ती है", "रुधिर गाढ़ा हो जाता है"],
     ["Blood flows faster", "Substances and gases find it easy to cross the capillary wall", "The heart works less", "The blood thickens"],
     1,
     "केशिकाएँ वहीं बनती हैं जहाँ विनिमय हो — एक-कोशिका-मोटी दीवार गैसों के आने-जाने को पहुँच-योग्य बनाती है।",
     "Capillaries form right where exchange happens — a wall one cell thick makes gases' to-and-fro effortless."),

    ("gas-exchange-transport", "medium",
     "फेफड़ों से लौटती हवा में जल-वाष्प की मात्रा अधिक क्यों होती है?",
     "Why does the air returning from the lungs carry more water vapour?",
     ["फेफड़े जल छानते हैं", "वायुकोशों की नम सतह से हवा जल-वाष्प सोख लेती है", "हवा गर्म होने से जल बनता है", "नाक में जल भरा रहता है"],
     ["The lungs filter water", "The air picks up water vapour from the moist alveolar surfaces", "Heat converts air into water", "The nose stores water"],
     1,
     "वायुकोश भीतर से नम रहते हैं — संपर्क में आई हवा वहाँ की नमी उठा लेती है, इसीलिए छोड़ी साँस भरपूर जल-वाष्प लिए होती है।",
     "Alveoli are moist inside — the air in contact lifts that moisture, loading the exhaled breath with water vapour."),

    ("gas-exchange-transport", "medium",
     "एक विद्यार्थी का कथन: 'हम रुधिर में ऑक्सीजन भरकर उसे सीधे जला देते हैं।' इसमें क्या गलती है?",
     "A student says: 'We fill the blood with oxygen and simply burn it.' What is the error?",
     ["रुधिर में O2 नहीं जाती", "O2 जलती नहीं — वह कोशिकीय श्वसन की अभिक्रियाओं में ग्लूकोज़ के विघटन में उपयोग होती है, दहन नहीं होता", "दोनों सही हैं", "जलना फेफड़ों में होता है"],
     ["O2 does not enter blood", "O2 is not burnt — it is used in the reactions of cellular respiration to break down glucose; no combustion happens", "Both parts are correct", "Burning occurs in the lungs"],
     1,
     "शरीर में दहन नहीं होता — O2 ऑक्सीकरण की श्रृंखला में ग्लूकोज़ को चरणबद्ध तोड़ने का काम करती है, ऊर्जा ATP में बँधती है।",
     "No burning occurs in the body — O2 works in the oxidation chain that step-wise dismantles glucose, with energy banked in ATP."),

    ("gas-exchange-transport", "medium",
     "वायुकोशों में हवा और रुधिर के बीच कुल विनिमय-सतह का आकलन प्रयोगशाला में किया जाए तो वह मानव त्वचा की सतह से कैसी होगी?",
     "If the total exchange surface of the alveoli is estimated, how does it compare with the human skin surface?",
     ["त्वचा से कहीं छोटी", "लगभग बराबर", "त्वचा से कई गुना बड़ी", "मापी नहीं जा सकती"],
     ["Far smaller than the skin", "Nearly equal", "Many times larger than the skin", "It cannot be measured"],
     2,
     "करोड़ों वायुकोश मिलकर त्वचा से कई गुना (दर्जनों वर्ग मीटर) सतह बनाते हैं — यही विशाल क्षेत्र विनिमय की क्षमता देता है।",
     "Millions of alveoli add up to a surface many times (dozens of square metres) the skin — this vast area powers the exchange capacity."),

    ("gas-exchange-transport", "hard",
     "पर्वतारोहण पर ऊँचाई पर हवा में ऑक्सीजन का प्रतिशत वही ~21% है, फिर भी साँस फूलती है — कारण?",
     "At high altitude the air still holds the same ~21% oxygen, yet climbers feel breathless — why?",
     ["हवा का दबाव घटने से ऑक्सीजन का आंशिक दाब घट जाता है — रुधिर में O2 भराव कम हो जाता है", "O2 का प्रतिशत घट जाता है", "फेफड़े सिकुड़ जाते हैं", "हवा में CO2 बढ़ जाती है"],
     ["Lower air pressure reduces the partial pressure of oxygen — less O2 loads into the blood", "The percentage of O2 falls", "The lungs shrink", "CO2 in the air rises"],
     0,
     "घनी हवा में O2 के अणु प्रति श्वास कम मिलते हैं — प्रवणता कमजोर पड़ती है और हीमोग्लोबिन पूरा भर नहीं पाता; शरीर तेज़ साँस से भरपाई करता है।",
     "In thin air fewer O2 molecules arrive per breath — the gradient weakens, haemoglobin under-loads, and the body compensates by breathing harder."),

    ("gas-exchange-transport", "hard",
     "साँस लेने की तीव्र इच्छा (urge to breathe) मुख्यतः रुधिर में किस गैस के बढ़ने से जागृत होती है?",
     "A strong urge to breathe is triggered mainly by the rise of which gas in the blood?",
     ["ऑक्सीजन के घटने से", "कार्बन डाइऑक्साइड के बढ़ने से", "नाइट्रोजन से", "हीलियम से"],
     ["By a fall in oxygen", "By a rise in carbon dioxide", "By nitrogen", "By helium"],
     1,
     "मस्तिष्क का श्वसन-केंद्र मुख्यतः CO2-संवेदी है — रुधिर CO2 बढ़ते ही साँस की दर तेज कर देता है; O2 की गिरावट गौण उत्प्रेरक है।",
     "The brain's breathing centre is chiefly CO2-sensitive — rising blood CO2 instantly speeds up breathing; falling O2 is a secondary spur."),

    ("gas-exchange-transport", "hard",
     "यदि किसी कारण वायुकोश-दीवारें मोटी हो जाएँ तो क्या होगा?",
     "What happens if the alveolar walls become thickened for some reason?",
     ["विनिमय तेज हो जाता है", "विसरण-दूरी बढ़ने से गैस-विनिमय धीमा पड़ता है — साँस की कमी और थकान उत्पन्न होती है", "कोई प्रभाव नहीं पड़ता", "फेफड़े हवा रोक लेते हैं"],
     ["Exchange becomes faster", "The diffusion distance grows, slowing gas exchange — breathlessness and fatigue follow", "No effect occurs", "The lungs block the air"],
     1,
     "विनिमय-क्षमता दूरी पर टिकी है — मोटी दीवार वही रुकावट डालती है जो पहाड़ की दूर चोटी डालती है: पहुँच कठिन।",
     "Exchange capacity hinges on distance — a thickened wall is the barrier a far-off peak is: hard to reach."),

    # ---------------- respiration-other-organisms (30: E12/M13/H5) ----------------
    ("respiration-other-organisms", "easy",
     "पत्तियों की सतह पर गैसों के आदान-प्रदान के छिद्रों का नाम क्या है?",
     "What are the pores on the leaf surface for gas exchange called?",
     ["रंध्र (stomata)", "लेंटिसेल", "जड़-रोम", "जनन-रंध्र"],
     ["Stomata", "Lenticels", "Root hairs", "Reproductive pores"],
     0,
     "पत्तों की त्वचा पर स्थित सूक्ष्म रंध्र ही CO2-O2 के प्रवेश-निकास के द्वार हैं।",
     "The microscopic stomata on the leaf skin are the gates for CO2-O2 entry and exit."),

    ("respiration-other-organisms", "easy",
     "पौधों की जड़ें श्वसन के लिए ऑक्सीजन कहाँ से प्राप्त करती हैं?",
     "From where do plant roots obtain oxygen for respiration?",
     ["पत्तियों से नीचे नली द्वारा", "मिट्टी के कणों के बीच की हवा (मृदा-वायु) से", "जल से कभी नहीं", "सूर्य से"],
     ["Through a pipe from the leaves", "From the air between soil particles (soil air)", "Never from water", "From the sun"],
     1,
     "जड़ों के चारों ओर मिट्टी के छिद्रों में वायु भरी रहती है — जड़ें इसी मृदा-वायु से O2 ग्रहण करती हैं।",
     "Air fills the pore spaces of soil around roots — roots draw their O2 from this soil air."),

    ("respiration-other-organisms", "easy",
     "मछली पानी के बाहर रखने पर जल्दी मर जाती है — कारण?",
     "Why does a fish die soon when kept out of water?",
     ["उसे गर्मी लगती है", "गलफड़ों की पतली पत्तकियाँ बिना जल के सूखकर चिपक जाती हैं — घुली O2 ग्रहण नहीं कर पाते", "उसका हृदय रुक जाता है", "वह भूख से मरती है"],
     ["It feels hot", "The thin gill filaments dry and stick together without water — they cannot take up dissolved O2", "Its heart stops", "It dies of hunger"],
     1,
     "गलफड़े जल में खुलकर काम करते हैं; सूखी हवा में पत्तकियाँ आपस में चिपक जाने से सतह घट जाती है और श्वसन ठप हो जाता है।",
     "Gills work spread out in water; in dry air the filaments collapse and stick, the surface shrinks and respiration halts."),

    ("respiration-other-organisms", "easy",
     "कीट (insects) अपने शरीर में हवा किन छिद्रों से लेते हैं?",
     "Through which openings do insects take air into their bodies?",
     ["गलफड़े", "फेफड़े", "श्वास-छिद्र (spiracles)", "त्वचा"],
     ["Gills", "Lungs", "Spiracles", "Skin"],
     2,
     "कीट के धड़ पर पंक्तिबद्ध सूक्ष्म छिद्र — स्पिरेकल — हवा के प्रवेश-निकास के द्वार हैं।",
     "Rows of tiny holes on an insect's trunk — the spiracles — are the doors for air to enter and leave."),

    ("respiration-other-organisms", "easy",
     "कीटों के शरीर में हवा को गहराई तक पहुँचाने वाली नलिका-प्रणाली का नाम क्या है?",
     "What is the tube system called that carries air deep inside an insect's body?",
     ["केशिका-जाल", "ट्रैकियल तंत्र (श्वास-नलिकाएँ)", "रुधिर वाहिकाएँ", "लसीका नलिकाएँ"],
     ["Capillary network", "Tracheal system (air tubes)", "Blood vessels", "Lymph vessels"],
     1,
     "स्पिरेकल से शुरू होकर श्वास-नलिकाएँ (ट्रैकिया) शाखाओं से भर शरीर फैलती हैं और सीधे कोशिकाओं तक हवा पहुँचाती हैं।",
     "Starting at the spiracles, the tracheal tubes branch throughout the body, delivering air straight to the cells."),

    ("respiration-other-organisms", "easy",
     "केंचुआ (earthworm) श्वसन किस से करता है?",
     "Through what does an earthworm respire?",
     ["फेफड़ों से", "गलफड़ों से", "अपनी नम त्वचा (सतह) से", "ट्रैकिया से"],
     ["Through lungs", "Through gills", "Through its moist skin (surface)", "Through tracheae"],
     2,
     "केंचुए की नम-चिकनी त्वचा घुली हवा सीधे रुधिर से विसरित कर देती है — त्वचा ही उसका श्वसन-अंग है।",
     "The worm's damp skin directly diffuses dissolved air into its blood — the skin itself is its breathing organ."),

    ("respiration-other-organisms", "easy",
     "पौधों में श्वसन कहाँ-कहाँ होता है?",
     "In which parts of the plant does respiration occur?",
     ["केवल पत्तों में", "केवल जड़ों में", "जड़, तना, पत्ती — हर जीवित भाग में", "केवल फूलों में"],
     ["Only in leaves", "Only in roots", "In root, stem, leaf — every living part", "Only in flowers"],
     2,
     "पौधे की हर जीवित कोशिका ऊर्जा के लिए श्वसन करती है — यह क्रिया किसी एक अंग तक सीमित नहीं।",
     "Every living cell of the plant respires for energy — the process is not confined to any one organ."),

    ("respiration-other-organisms", "easy",
     "रात में पौधे मुख्यतः कौन-सी गैस छोड़ते हैं?",
     "Which gas do plants mainly release at night?",
     ["ऑक्सीजन", "कार्बन डाइऑक्साइड", "नाइट्रोजन", "हाइड्रोजन"],
     ["Oxygen", "Carbon dioxide", "Nitrogen", "Hydrogen"],
     1,
     "रात में प्रकाश-संश्लेषण रुकता है पर श्वसन चलता रहता है — इसलिए CO2 का शुद्ध निर्गम होता है।",
     "At night photosynthesis stops while respiration continues — so the net release is CO2."),

    ("respiration-other-organisms", "easy",
     "अमीबा जैसा एककोशिकीय जीव गैस-विनिमय कैसे करता है?",
     "How does a unicellular organism like Amoeba exchange gases?",
     ["फेफड़ों से", "कोशिका-झिल्ली के पार विसरण से", "गलफड़ों से", "रोमों से"],
     ["Through lungs", "By diffusion across the cell membrane", "Through gills", "Through hairs"],
     1,
     "पूरा जीव एक ही कोशिका है — सतही झिल्ली पर ही O2 भीतर और CO2 बाहर विसरित होती है।",
     "The whole animal is one cell — right at the surface membrane O2 diffuses in and CO2 diffuses out."),

    ("respiration-other-organisms", "easy",
     "हाइड्रा जैसे जीव गैस-विनिमय किससे करते हैं?",
     "Through what do animals like Hydra exchange gases?",
     ["फेफड़ों से", "विशेष अंगों से", "पूरे शरीर की सतह से", "पत्तियों से"],
     ["Through lungs", "Through special organs", "Through the whole body surface", "Through leaves"],
     2,
     "हाइड्रा की देह पतली-नम और कोशिकाएँ सतह के पास ही हैं — विनिमय केवल सतही विसरण से होता है।",
     "Hydra's body is thin and moist with cells sitting near the surface — surface diffusion alone meets its needs."),

    ("respiration-other-organisms", "easy",
     "मेंढक जैसा उभयचर श्वसन किन माध्यमों से करता है?",
     "Through which media does an amphibian like the frog respire?",
     ["केवल फेफड़ों से", "केवल त्वचा से", "फेफड़ों और नम त्वचा — दोनों से", "केवल गलफड़ों से"],
     ["Only through lungs", "Only through skin", "Through both lungs and moist skin", "Only through gills"],
     2,
     "मेंढक ज़मीन पर फेफड़ों से और जल/नमी में त्वचा से भी साँस लेता है — दोहरी व्यवस्था उसकी पहचान है।",
     "The frog breathes by lungs on land and through its moist skin in water — the double arrangement is its signature."),

    ("respiration-other-organisms", "easy",
     "कवक (fungi) जैसे जीव गैस-विनिमय किस स्तर पर करते हैं?",
     "At what level do organisms like fungi carry out gas exchange?",
     ["विशेष श्वसन-अंगों से", "अपनी समस्त सतह से विसरण द्वारा", "केवल बीजाणुओं से", "प्रकाश-संश्लेषण द्वारा"],
     ["Through special respiratory organs", "By diffusion across their entire surface", "Only through spores", "By photosynthesis"],
     1,
     "कवकों के सूक्ष्म तंतुओं की पतली दीवारें सीधे विसरण करती हैं — श्वसन-अंगों की जरूरत नहीं।",
     "The thin walls of microscopic fungal filaments diffuse gases directly — no respiratory organs are needed."),

    ("respiration-other-organisms", "medium",
     "गलफड़ों की सतह रुधिर वाहिकाओं से भरपूर होना उनकी कार्यक्षमता कैसे बढ़ाता है?",
     "How does the gill surface being richly loaded with blood vessels boost its efficiency?",
     ["रुधिर का रंग बदलता है", "घुली O2 तुरंत रुधिर में उतरती है और प्रवणता बनी रहती है", "गलफड़े मजबूत होते हैं", "जल का प्रवाह रुक जाता है"],
     ["The blood colour changes", "Dissolved O2 promptly enters the blood and the gradient stays alive", "The gills become strong", "The water flow stops"],
     1,
     "सतत रुधिर-प्रवाह ग्रहीत O2 को तुरंत दूर ले जाता है — गलफड़े की O2-सांद्रता कम बनी रहती है और विसरण लगातार चलता रहता है।",
     "A rich blood flow instantly carries away absorbed O2 — the gill's O2 level stays low and diffusion never stops."),

    ("respiration-other-organisms", "medium",
     "मछली को लगातार जल गलफड़ों पर बहाव रखना क्यों जरूरी है?",
     "Why must a fish keep water constantly flowing over its gills?",
     ["शरीर ठंडा रखने के लिए", "नया घुली-O2 युक्त जल ही लगातार विसरण संभव बनाता है; रुका जल अपनी O2 खो देता है", "भोजन ढूँढने के लिए", "तैरने में मदद के लिए"],
     ["To keep the body cool", "Only a continuous supply of fresh oxygenated water sustains diffusion; stalled water loses its O2", "To find food", "To help swimming"],
     1,
     "गलफड़ों के पास का जल अपनी घुली O2 दे देता है — मुँह-कलाई (operculum) की धारा ही ताजा जल बुलाती रहती है।",
     "The water near the gills gives up its dissolved O2 — the mouth-and-gill-cover current keeps summoning fresh water."),

    ("respiration-other-organisms", "medium",
     "कीटों की श्वास-नलिकाएँ (ट्रैकिया) रुधिर की मदद लिए बिना ही O2 कोशिकाओं तक कैसे पहुँचाती हैं?",
     "How do insect tracheae deliver O2 to cells without any help from blood?",
     ["नलिकाएँ सीधे शरीर-गहरे तक शाखाएँ फैलाती हैं और वायु बहकर कोशिकाओं तक पहुँचती है", "रुधिर O2 खा जाता है", "त्वचा सब ढोती है", "कीट प्रकाश-संश्लेषण करते हैं"],
     ["The tubes branch deep into the body and air flows right up to the cells", "The blood eats up the O2", "The skin carries everything", "Insects photosynthesise"],
     0,
     "ट्रैकियल तंत्र हवा की सीधी पाइपलाइन है — कोशिका-झिल्ली तक पहुँचकर विसरण स्थानीय स्तर पर ही पूरा हो जाता है।",
     "The tracheal system is a direct air pipeline — reaching the cell membranes, diffusion finishes the job locally."),

    ("respiration-other-organisms", "medium",
     "केंचुए की त्वचा का लगातार नम रहना उसके श्वसन के लिए अनिवार्य क्यों है?",
     "Why is a constantly moist skin indispensable for an earthworm's respiration?",
     ["विसरण द्रव-फिल्म के आर-पार ही होता है — सूखी त्वचा पर गैस-विनिमय रुक जाता है", "नमी से रंग गहरा होता है", "नम त्वचा शिकारी दूर रखती है", "नमी से वह तैरता है"],
     ["Diffusion occurs only across a fluid film — on dry skin the exchange stops", "Moisture darkens the colour", "Moist skin keeps predators away", "Moisture helps it float"],
     0,
     "हवा की O2 पहले त्वचा की जल-फिल्म में घुलती है, तभी भीतर जाती है — फिल्म सूखे तो मार्ग ही समाप्त।",
     "Atmospheric O2 must first dissolve in the skin's water film before entering — dry the film and the road ends."),

    ("respiration-other-organisms", "medium",
     "केंचुए का श्वसन-वर्णक रुधिर में किस रूप में रहता है?",
     "In what form does the earthworm's respiratory pigment exist in its blood?",
     ["कोशिकाओं में भरा (मानव की तरह)", "प्लाज्मा में घुला हुआ", "केवल त्वचा में", "केवल पाचन-तंत्र में"],
     ["Packed in cells (as in humans)", "Dissolved in the plasma", "Only in the skin", "Only in the gut"],
     1,
     "केंचुए का हीमोग्लोबिन रुधिर-द्रव में घुला रहता है — मानव के RBC-बंद हीमोग्लोबिन से यह भिन्न व्यवस्था है।",
     "The earthworm's haemoglobin stays dissolved in its blood fluid — an arrangement distinct from human RBC-packed haemoglobin."),

    ("respiration-other-organisms", "medium",
     "वर्षा में दिन के समय पौधा कौन-सी गैस शुद्ध रूप से छोड़ता है (मान लीजिए प्रकाश पर्याप्त है)?",
     "On a well-lit day, which gas does a plant release on net balance?",
     ["केवल CO2", "केवल O2 नहीं — निर्गम प्रकाश की तीव्रता पर निर्भर", "O2 और CO2 बराबर-बराबर", "कोई गैस नहीं"],
     ["Only CO2", "Not O2 alone — the net release depends on light intensity", "O2 and CO2 equally", "No gas"],
     1,
     "दिन में प्रकाश-संश्लेषण और श्वसन साथ चलते हैं — प्रकाश तेज हो तो O2 का निर्माण खपत से बढ़ जाता है और शुद्ध O2 निकलती है।",
     "By day photosynthesis and respiration run together — in strong light O2 production outpaces its use and net O2 is released."),

    ("respiration-other-organisms", "medium",
     "पेड़ के तने की मोटी छाल में गैस-विनिमय के लिए कौन-से छिद्र होते हैं?",
     "Which pores in the thick bark of a tree trunk serve gas exchange?",
     ["रंध्र", "लेंटिसेल (lenticels)", "श्वास-छिद्र", "जड़-रोम"],
     ["Stomata", "Lenticels", "Spiracles", "Root hairs"],
     1,
     "जहाँ छाल मोटी हो जाती है वहाँ छोटे-छोटे उभार वाले लेंटिसेल भीतरी जीवित ऊतकों तक हवा का रास्ता बनाते हैं।",
     "Where the bark turns thick, small raised lenticels keep an air route open to the living tissue inside."),

    ("respiration-other-organisms", "medium",
     "जड़ों में ऑक्सीजन ग्रहण का मुख्य क्षेत्र कौन-सा है?",
     "Which is the main region of oxygen uptake in roots?",
     ["मूल-ग्रीवा", "मूल-रोम (root hair) क्षेत्र", "मूल-छोटक", "जड़ का सिरा ढक्कन"],
     ["Root neck", "The root-hair zone", "Root cap", "The tip cover"],
     1,
     "मूल-रोमों की विशाल सतह मिट्टी-वायु से O2 लेने का मुख्य काम करती है — यही जड़ का विनिमय-क्षेत्र है।",
     "The enormous surface of root hairs does the chief work of taking O2 from soil air — the root's exchange zone."),

    ("respiration-other-organisms", "medium",
     "पक्षियों में वायु-कोश (air sacs) उड़ान के समय श्वसन में क्या लाभ देते हैं?",
     "What advantage do the air sacs of birds give their respiration during flight?",
     ["वे हवा संग्रहीत कर फेफड़ों में बार-बार भेजते हैं — उड़ान भर में निरंतर ऑक्सीजन-आपूर्ति बनी रहती है", "वे पंखों को फुलाते हैं", "वे भोजन पचाते हैं", "वे आवाज़ बनाते हैं"],
     ["They store air and pass it repeatedly through the lungs — oxygen supply stays continuous through the flight", "They inflate the wings", "They digest food", "They make voice"],
     0,
     "पक्षी-फेफड़े हवा को एक ही दिशा में झिझकते हैं; वायु-कोश आरक्षित हवा बार-बार इस प्रवाह में डालते हैं — थकान भरी उड़ान में भी O2 की घाटी नहीं पड़ती।",
     "Bird lungs stream air one-way; the sacs push reserve air through this stream again and again — even strenuous flight never starves the tissues of O2."),

    ("respiration-other-organisms", "medium",
     "डॉल्फिन और व्हेल जल में रहकर भी बार-बार सतह पर क्यों आते हैं?",
     "Why do dolphins and whales keep surfacing despite living in water?",
     ["खेलने के लिए", "उनके फेफड़े हवा से साँस लेते हैं — जल-स्तर से ऊपर वायुमंडलीय हवा लेना पड़ता है", "धूप सेंकने के लिए", "भोजन केवल सतह पर मिलता है"],
     ["To play", "Their lungs breathe air — they must take atmospheric air above the water line", "To bask in the sun", "Food is found only at the surface"],
     1,
     "ये स्तनधारी हैं — गलफड़े नहीं, फेफड़े हैं; घुली O2 काम नहीं आती, सीधी हवा चाहिए इसलिए सतह पर आकर साँस लेते हैं।",
     "They are mammals — lungs, not gills; dissolved O2 will not do, direct air is needed, so they surface to breathe."),

    ("respiration-other-organisms", "medium",
     "अंकुरित बीजों को काँच की बोतल में बंद कर रातभर रखा गया — सुबह बोतल में नीचे लटके चूने-जल को कोठरी का पानी दूधिया हो गया। यह प्रयोग क्या सिद्ध करता है?",
     "Germinating seeds are kept overnight in a sealed bottle with a vial of lime water; by morning the lime water turns milky. What does this prove?",
     ["बीजों में प्रकाश-संश्लेषण हुआ", "जीवित बीजों का श्वसन चलता रहा और CO2 निकली", "बीज सूख गए", "बोतल में O2 बनी"],
     ["Photosynthesis occurred in the seeds", "The living seeds kept respiring and released CO2", "The seeds dried up", "O2 formed in the bottle"],
     1,
     "दूधिया चूना-जल CO2 की उपस्थिति का पक्का प्रमाण है — अंकुरण के दौरान तेज श्वसन से बीज लगातार CO2 छोड़ते हैं।",
     "Milky lime water is firm proof of CO2 — germinating seeds respire briskly and release CO2 continuously."),

    ("respiration-other-organisms", "medium",
     "कीटों के रुधिर में श्वसन-वर्णक की उपस्थिति मामूली क्यों है?",
     "Why is the presence of a respiratory pigment minimal in insect blood?",
     ["कीट श्वसन नहीं करते", "ट्रैकियल नलिकाएँ हवा सीधे कोशिकाओं तक पहुँचाती हैं — रुधिर का गैस-परिवहन कार्य छोटा हो जाता है", "कीटों का रुधिर सफेद होता है", "कीट त्वचा से सब लेते हैं"],
     ["Insects do not respire", "Tracheal tubes deliver air straight to the cells — the blood's gas-transport role shrinks", "Insect blood is white", "Insects take everything through skin"],
     1,
     "हवा की सीधी पाइपलाइन होने से रुधिर को गैस-ढोना पड़ता नहीं — इसीलिए कीट-रुधिर वर्णक-निर्धन है।",
     "With a direct air pipeline, the blood need not ferry gases — hence insect blood is pigment-poor."),

    ("respiration-other-organisms", "medium",
     "पौधे की जड़ें अपने श्वसन से प्राप्त ऊर्जा का एक बड़ा उपयोग किसमें करती हैं?",
     "What major use do plant roots make of the energy obtained from their respiration?",
     ["पत्तियों को रंग देने में", "मिट्टी से खनिज लवणों का सक्रिय अवशोषण करने में", "फूल खिलाने में", "बीज बनाने में"],
     ["Colouring the leaves", "Actively absorbing mineral salts from the soil", "Opening the flowers", "Making seeds"],
     1,
     "खनिज-अवशोषण ऊर्जा-माँग का काम है — जड़-कोशिकाएँ अपने श्वसन की ATP से ही मिट्टी के लवणों को भीतर खींचती हैं।",
     "Mineral uptake is energy-hungry work — root cells use their respiratory ATP to pull soil salts inside."),

    ("respiration-other-organisms", "medium",
     "बरसात में मिट्टी पूरी तरह जल से संतृप्त होने पर बड़े वृक्षों की जड़ों के पास की मृदा-वायु का क्या होता है?",
     "What happens to the soil air near the roots of large trees when soil becomes fully water-saturated in rain?",
     ["वह बढ़ जाती है", "जल उसे हटा देता है — जड़ें ऑक्सीजन के लिए तंगी में आ जाती हैं", "मिट्टी वायु बनाती है", "कोई प्रभाव नहीं"],
     ["It increases", "Water displaces it — the roots face an oxygen crunch", "The soil makes air", "No effect"],
     1,
     "जल-भराव में मिट्टी के छिद्रों की हवा जल धकेल देता है — जड़-श्वसन दमन-छूट की स्थिति में आ जाता है।",
     "In waterlogging, water displaces the air from soil pores — root respiration lands in a choked state."),

    ("respiration-other-organisms", "hard",
     "गलफड़ों पर जल का प्रवाह और भीतर रुधिर का प्रवाह लगभग विपरीत दिशाओं में चलते हैं — इस व्यवस्था से मछली को क्या लाभ है?",
     "Water flows over the gills nearly opposite to the direction of blood flow inside — what benefit does this give the fish?",
     ["रुधिर जल में मिल जाता है", "पूरी सतह पर O2 का अंतर कायम रहता है — जल से अधिकतम ऑक्सीजन निकाली जाती है", "मछली तेज़ तैरती है", "गलफड़े ठंडे रहते हैं"],
     ["Blood mixes into the water", "An O2 difference persists over the whole surface — the maximum oxygen is extracted from water", "The fish swims faster", "The gills stay cool"],
     1,
     "विपरीत-प्रवाह व्यवस्था में थका हुआ रुधिर भी ताजा जल से ही मिलता है — विनिमय-प्रवणता अंत तक बनी रहती है और O2-ग्रहण लगभग पूर्ण होता है।",
     "In the counter-current arrangement even tired blood meets fresh water — the gradient survives to the very end and O2 uptake runs near-complete."),

    ("respiration-other-organisms", "hard",
     "भारी बारिश में केंचुए बार-बार ज़मीन की सतह पर क्यों उतर आते हैं?",
     "Why do earthworms keep coming up to the soil surface during heavy rain?",
     ["सूरज देखने के लिए", "बारिश के जल से बिल की वायु-छिद्र भर जाते हैं — ऑक्सीजन की कमी से बचने के लिए सतह पर आते हैं", "भोजन खोजने के लिए", "प्रजनन के लिए"],
     ["To see the sun", "Rain-water fills the air pockets of their burrows — they surface to escape the oxygen shortage", "To search food", "For reproduction"],
     1,
     "जल-भराव से बिलों की हवा जाती रहती है; त्वचा-श्वसन के लिए ज़मीन की गीली सतह की हवा ही उन्हें बचाती है।",
     "Waterlogging drives the air out of their burrows; the air at the wet ground surface is what saves their skin-breathing."),

    ("respiration-other-organisms", "hard",
     "जीवाश्म-काल की वायु में उच्च O2 थी — उस युग में भीमकाय कीट संभव थे, आज नहीं। श्वसन-दृष्टि से कारण क्या है?",
     "Giant insects were possible in the era of high atmospheric O2, not today. What is the respiratory reason?",
     ["आज हवा जहरीली है", "ट्रैकियल विसरण की पहुँच सीमित है — बड़ी देह में गहरे कोशिकाओं तक O2 पहुँचाना असंभव हो जाता है; अधिक O2 वाली हवा में ही विसरण-पहुँच बढ़ती थी", "कीट आलसी हो गए", "पक्षियों ने उन्हें खा लिया"],
     ["Today's air is toxic", "Tracheal diffusion has limited reach — in a big body deep cells cannot be supplied; oxygen-richer air once extended that reach", "Insects grew lazy", "Birds ate them up"],
     1,
     "विसरण दूरी के साथ तेजी से कमजोर पड़ता है — ट्रैकिया जितना लंबा, O2-आपूर्ति उतनी अनिश्चित; इसी सीमा ने कीटों का आकार बाँध दिया।",
     "Diffusion weakens rapidly with distance — the longer the trachea, the shakier the O2 supply; this limit has capped insect size."),

    ("respiration-other-organisms", "hard",
     "हाइड्रा जैसे जीव की देह-भित्ति केवल दो कोशिका-स्तरों की होना उसके गैस-विनिमय के लिए निर्णायक क्यों है?",
     "Why is Hydra's body wall being just two cell layers decisive for its gas exchange?",
     ["दो स्तर सुंदर लगते हैं", "हर कोशिका सतह के पास ही रहती है — विसरण-दूरी इतनी छोटी कि अंगों की जरूरत पड़ती ही नहीं", "दो स्तर मजबूती देते हैं", "दो स्तर प्रकाश रोकते हैं"],
     ["Two layers look nice", "Every cell stays next to the surface — the diffusion distance is so small that no organs are needed", "Two layers give strength", "Two layers block light"],
     1,
     "पतली देह = हर कोशिका की सतह से सीधी पहुँच — O2/CO2 का आदान-प्रदान झिल्ली पार सीधा हो जाता है।",
     "A thin body = every cell directly served from the surface — O2/CO2 exchange happens straight across membranes."),

    # ---------------- respiration-vs-other-processes (20: E7/M10/H3) ----------------
    ("respiration-vs-other-processes", "easy",
     "श्वास-क्रिया (breathing) और कोशिकीय श्वसन (respiration) का मूल अंतर क्या है?",
     "What is the basic difference between breathing and cellular respiration?",
     ["दोनों एक ही क्रिया हैं", "श्वास-क्रिया हवा का बाहर-भीतर है; श्वसन कोशिकाओं में भोजन तोड़कर ऊर्जा निकालना है", "श्वास में ऊर्जा बनती है, श्वसन में हवा", "श्वसन केवल पौधों में होता है"],
     ["Both are the same process", "Breathing is the in-and-out of air; respiration is the release of energy by breaking food in cells", "Breathing makes energy, respiration moves air", "Respiration occurs only in plants"],
     1,
     "श्वास-क्रिया यांत्रिक है, श्वसन जैव-रासायनिक — पहला दूसरे की हवा-आपूर्ति का बाहरी साधन मात्र।",
     "Breathing is mechanical, respiration biochemical — the former is merely the external supply line of the latter."),

    ("respiration-vs-other-processes", "easy",
     "दहन (combustion) और श्वसन दोनों ऑक्सीकरण हैं — इनकी प्रक्रिया में मुख्य भिन्नता क्या है?",
     "Both combustion and respiration are oxidations — what is the main difference in their manner?",
     ["दहन धीमा, श्वसन विस्फोटक", "दहन एकदम ताप-ज्वाला से, श्वसन एंजाइमों द्वारा नियंत्रित चरणों में", "दोनों में कोई भिन्नता नहीं", "श्वसन में ऑक्सीजन नहीं लगती"],
     ["Combustion is slow, respiration explosive", "Combustion is instant heat-flame; respiration runs in enzyme-controlled steps", "There is no difference", "Respiration needs no oxygen"],
     1,
     "लकड़ी जलती है एक ही झोंके में; ग्लूकोज़ टूटता है दर्जनों एंजाइम-चरणों में — रफ्तार और नियंत्रण ही भेद है।",
     "Wood burns in one blast; glucose breaks in dozens of enzyme steps — pace and control are the difference."),

    ("respiration-vs-other-processes", "easy",
     "श्वास-क्रिया मुख्यतः शरीर के किस भाग तक सीमित है?",
     "Breathing is mainly confined to which part of the body?",
     ["सभी कोशिकाएँ", "मस्तिष्क", "फेफड़े और श्वसन-मार्ग", "यकृत"],
     ["All cells", "The brain", "The lungs and respiratory tract", "The liver"],
     2,
     "श्वास-क्रिया का मंच छाती है; श्वसन का मंच शरीर की हर कोशिका — स्थल भी दोनों का भेद है।",
     "The stage of breathing is the chest; the stage of respiration is every cell — venue too distinguishes them."),

    ("respiration-vs-other-processes", "easy",
     "दहन में ईंधन की ऊर्जा मुख्यतः किस रूप में मुक्त होती है?",
     "In combustion, the fuel's energy is released mainly in which form?",
     ["ATP में", "ताप और प्रकाश में", "ग्लूकोज़ में", "प्रोटीन में"],
     ["As ATP", "As heat and light", "As glucose", "As protein"],
     1,
     "आग ताप-प्रकाश बिखेरती है; श्वसन उसी अंतर्निहित ऊर्जा को ATP के रूप में बाँधता है — यही रूप-भेद है।",
     "Fire scatters heat and light; respiration banks the same latent energy as ATP — the form is the divide."),

    ("respiration-vs-other-processes", "easy",
     "प्रकाश-संश्लेषण का समीकरण किस दिशा में चलता है?",
     "In which direction does the photosynthesis equation run?",
     ["CO2 + जल + प्रकाश → ग्लूकोज़ + O2", "ग्लूकोज़ + O2 → CO2 + जल + ऊर्जा", "ग्लूकोज़ → एथेनॉल + CO2", "प्रोटीन + O2 → ऊर्जा"],
     ["CO2 + water + light → glucose + O2", "glucose + O2 → CO2 + water + energy", "glucose → ethanol + CO2", "protein + O2 → energy"],
     0,
     "प्रकाश-संश्लेषण सरल पदार्थों से भोजन बनाता है; श्वसन उसी भोजन को वापस तोड़ता है — दिशाएँ आमने-सामने।",
     "Photosynthesis builds food from simple stuff; respiration breaks that food back — the directions face each other."),

    ("respiration-vs-other-processes", "easy",
     "केवल हरे पौधे प्रकाश-संश्लेषण कर सकते हैं — श्वसन करने वाले कौन हैं?",
     "Only green plants can photosynthesise — who can respire?",
     ["केवल प्राणी", "केवल मनुष्य", "सभी जीव — पौधे, प्राणी, कवक, सूक्ष्मजीव सब", "केवल स्तनधारी"],
     ["Only animals", "Only humans", "All living beings — plants, animals, fungi, microbes all", "Only mammals"],
     2,
     "प्रकाश-संश्लेषण हरितलवक का विशेषाधिकार है; श्वसन जीवन का सार्वभौमिक कार्य — जो जीवित है वह श्वसन करता है।",
     "Photosynthesis is the privilege of chloroplasts; respiration is life's universal act — whatever lives, respires."),

    ("respiration-vs-other-processes", "easy",
     "श्वास लेना (breathing) अपने आप में किस प्रकार की क्रिया है?",
     "What kind of process is breathing in itself?",
     ["रासायनिक ऊर्जा-क्रिया", "यांत्रिक (भौतिक) वायु-प्रवाह क्रिया", "प्रकाश-रासायनिक क्रिया", "उत्सर्जन क्रिया"],
     ["A chemical energy process", "A mechanical (physical) airflow process", "A photochemical process", "An excretory process"],
     1,
     "पसली-मध्यपट की हरकत से हवा का देना-लेना शुद्ध यांत्रिकी है — रासायनिक चरण तो कोशिकाओं में होते हैं।",
     "The giving and taking of air by rib-and-diaphragm motion is pure mechanics — the chemistry unfolds in the cells."),

    ("respiration-vs-other-processes", "medium",
     "श्वसन को 'नियंत्रित ऑक्सीकरण' कहा जाता है — नियंत्रण कौन करता है?",
     "Respiration is called 'controlled oxidation' — who exercises the control?",
     ["हवा की गति", "एंजाइम (enzyme)", "हृदय की धड़कन", "प्रकाश"],
     ["The speed of air", "Enzymes", "The heartbeat", "Light"],
     1,
     "हर चरण विशिष्ट एंजाइम की देखरेख में चलता है — एंजाइम ही गति, स्थान और मात्रा का नियंत्रण रखते हैं।",
     "Every step proceeds under the watch of a specific enzyme — enzymes hold the reins of pace, place and quantity."),

    ("respiration-vs-other-processes", "medium",
     "ग्लूकोज़ के जलने (दहन) और उसके श्वसन-विघटन के उत्पादों की तुलना में क्या समानता है?",
     "What is similar in the products of burning glucose and of its respiratory breakdown?",
     ["दोनों में एश (राख) बनती है", "दोनों में अंततः CO2 और H2O बनते हैं", "दोनों में एथेनॉल बनता है", "दोनों में प्रोटीन बनते हैं"],
     ["Both produce ash", "Both ultimately yield CO2 and H2O", "Both produce ethanol", "Both produce proteins"],
     1,
     "रसायन का गंतव्य एक है — CO2 और जल; फर्क रास्ते का है: आग में एक ही झटका, श्वसन में सीढ़ियाँ।",
     "The chemical destination is one — CO2 and water; the paths differ: a single blast in fire, a staircase in respiration."),

    ("respiration-vs-other-processes", "medium",
     "'श्वसन एक धीमा दहन है' — इस कथन की परीक्षा में सही व्याख्या क्या है?",
     "'Respiration is a slow combustion' — what is the correct interpretation of this statement for exams?",
     ["शरीर में सचमुच आग धीमे-धीमे जलती है", "ऑक्सीकरण की दृष्टि से दोनों समान हैं, पर श्वसन एंजाइम-नियंत्रित चरणों में ऊर्जा ATP में बाँधता है", "श्वसन दहन से भी तेज़ है", "कथन पूर्णतः गलत है"],
     ["A fire literally burns slowly in the body", "Both are alike as oxidations, but respiration binds energy into ATP through enzyme-controlled steps", "Respiration is even faster than combustion", "The statement is entirely wrong"],
     1,
     "समानता रासायनिक (ऑक्सीकरण), भिन्नता गति-नियंत्रण-ऊर्जा-रूप में — 'धीमा दहन' रूपक है, आग की वास्तविकता नहीं।",
     "The likeness is chemical (oxidation), the difference lies in pace, control and energy form — 'slow combustion' is a metaphor, not a literal fire."),

    ("respiration-vs-other-processes", "medium",
     "प्रकाश-संश्लेषण और श्वसन कच्चे माल (reactants) की दृष्टि से एक-दूसरे के कैसे हैं?",
     "How are photosynthesis and respiration related in terms of raw materials (reactants)?",
     ["दोनों के कच्चे माल समान हैं", "एक के उत्पाद दूसरे के कच्चे माल हैं", "दोनों का कोई संबंध नहीं", "दोनों एक ही दिशा में चलते हैं"],
     ["Their raw materials are identical", "The products of one are the raw materials of the other", "They are unrelated", "Both run in the same direction"],
     1,
     "प्रकाश-संश्लेषण का बना ग्लूकोज़-O2 श्वसन खाता है; श्वसन की CO2-जल प्रकाश-संश्लेषण उपयोग करता है — चक्र जुड़ा है।",
     "Respiration consumes the glucose-O2 that photosynthesis makes; photosynthesis uses the CO2-water that respiration yields — one linked cycle."),

    ("respiration-vs-other-processes", "medium",
     "दिन के समय हरे पौधे में कौन-सी दो क्रियाएँ साथ-साथ चल रही होती हैं?",
     "Which two processes run side by side in a green plant during the day?",
     ["केवल प्रकाश-संश्लेषण", "केवल श्वसन", "प्रकाश-संश्लेषण और श्वसन — दोनों साथ", "केवल वाष्पोत्सर्जन"],
     ["Only photosynthesis", "Only respiration", "Photosynthesis and respiration — both together", "Only transpiration"],
     2,
     "दिन में दोनों प्रक्रियाएँ समानांतर चलती हैं — केवल गति-प्रकाश-तीव्रता तय करती है कि शुद्ध गैस कौन-सी निकलेगी।",
     "By day both processes run in parallel — only the rate and light intensity decide which gas leaves on net."),

    ("respiration-vs-other-processes", "medium",
     "क्लोरोप्लास्ट और माइटोकॉन्ड्रिया का कार्य-विभाजन कैसा है?",
     "How is the work divided between chloroplasts and mitochondria?",
     ["दोनों ऊर्जा बनाते हैं", "क्लोरोप्लास्ट प्रकाश-ऊर्जा को भोजन में बाँधता है; माइटोकॉन्ड्रिया भोजन को तोड़कर ATP देता है", "दोनों प्रकाश बनाते हैं", "दोनों पाचन करते हैं"],
     ["Both make energy", "The chloroplast packs light energy into food; the mitochondrion breaks food to give ATP", "Both make light", "Both digest food"],
     1,
     "एक ऊर्जा का भंडारण-घर, दूसरा ऊर्जा का वितरण-घर — हरितलवक जमा करता है, माइटोकॉन्ड्रियन चलाता है।",
     "One is the energy storehouse, the other the energy supplier — the chloroplast saves, the mitochondrion spends."),

    ("respiration-vs-other-processes", "medium",
     "फेफड़ों में कोई ATP नहीं बनता — फिर भी वे श्वसन-तंत्र का हिस्सा क्यों हैं?",
     "No ATP is made in the lungs — why are they still part of the respiratory system?",
     ["वे हवा साफ करते हैं", "वे गैस-विनिमय कर कोशिकीय श्वसन का कच्चा माल (O2) पहुँचाते हैं", "वे रुधिर बनाते हैं", "वे भोजन पचाते हैं"],
     ["They clean the air", "They perform gas exchange and deliver the raw material (O2) of cellular respiration", "They make blood", "They digest food"],
     1,
     "फेफड़े आपूर्ति-विभाग हैं — O2 की डिलीवरी और CO2 का संग्रह; ऊर्जा-कारखाना कोशिकाओं में ही है।",
     "Lungs are the supply department — O2 delivery and CO2 collection; the energy factory lies within the cells."),

    ("respiration-vs-other-processes", "medium",
     "ऊर्जा-प्रवाह की दृष्टि से प्रकाश-संश्लेषण और श्वसन की दिशाएँ कैसी हैं?",
     "In terms of energy flow, what are the directions of photosynthesis and respiration?",
     ["दोनों ऊर्जा मुक्त करते हैं", "प्रकाश-संश्लेषण ऊर्जा को भोजन में संग्रहीत करता है, श्वसन उसे मुक्त करता है", "दोनों ऊर्जा संग्रहीत करते हैं", "किसी में ऊर्जा लेन-देन नहीं"],
     ["Both release energy", "Photosynthesis stores energy in food; respiration releases it", "Both store energy", "Neither involves energy exchange"],
     1,
     "सूर्य-प्रकाश → ग्लूकोज़ (जमा) → ATP (खर्च) — प्रकाश-संश्लेषण ऊर्जा का बैंक-जमा, श्वसन उसकी निकासी है।",
     "Sunlight → glucose (deposit) → ATP (spending) — photosynthesis is the energy deposit, respiration the withdrawal."),

    ("respiration-vs-other-processes", "medium",
     "व्यायाम के दौरान श्वास-क्रिया और कोशिकीय श्वसन की गतियों का आपसी संबंध कैसा रहता है?",
     "During exercise, how are the rates of breathing and cellular respiration related?",
     ["दोनों स्वतंत्र रहती हैं", "कोशिकीय श्वसन तेज होने पर O2-CO2 की माँग बढ़ती है और श्वास-क्रिया उसका अनुसरण करती है", "श्वास-क्रिया धीमी होती है", "कोशिकीय श्वसन रुक जाता है"],
     ["Both stay independent", "As cellular respiration speeds up, the O2-CO2 demand rises and breathing follows suit", "Breathing slows down", "Cellular respiration stops"],
     1,
     "माँग और आपूर्ति की यह कड़ी ही संबंध है — कोशिकाओं की खपत बढ़ती है, श्वास-तंत्र आपूर्ति बढ़ाकर साथ देता है।",
     "This demand-supply chain is the relationship — as cell consumption rises, the breathing apparatus raises supply to match."),

    ("respiration-vs-other-processes", "medium",
     "निम्न क्रिया-स्थल युग्मों में से गलत कौन-सा है?",
     "Which of the following process-site pairs is wrong?",
     ["प्रकाश-संश्लेषण — हरितलवक", "कोशिकीय श्वसन — माइटोकॉन्ड्रिया", "श्वास-क्रिया — फेफड़े", "दहन — माइटोकॉन्ड्रिया"],
     ["Photosynthesis — chloroplast", "Cellular respiration — mitochondria", "Breathing — lungs", "Combustion — mitochondria"],
     3,
     "दहन जीव-कोशिका में होता ही नहीं — वह अजैव प्रक्रिया है; माइटोकॉन्ड्रिया में तो नियंत्रित श्वसन होता है।",
     "Combustion never occurs in a living cell — it is a non-living process; mitochondria host controlled respiration."),

    ("respiration-vs-other-processes", "hard",
     "एक पूरे दिन-रात चक्र में स्वस्थ हरे पौधे की कुल गैस-हिसाब किस प्रक्रिया की ओर झुका रहता है और क्यों?",
     "Over a full day-night cycle, which way does the gas balance of a healthy green plant tilt, and why?",
     ["शुद्ध CO2 — क्योंकि रात का श्वसन दिन के संश्लेषण से बड़ा होता है", "शुद्ध O2 — क्योंकि बढ़ते पौधे में संश्लेषण का ग्लूकोज़-निर्माण श्वसन-खपत से अधिक रहता है", "पूर्णतः संतुलित — कभी नहीं झुकता", "निर्भर नहीं करता"],
     ["Net CO2 — because night respiration outweighs daytime photosynthesis", "Net O2 — because in a growing plant glucose made by photosynthesis exceeds respiratory consumption", "Perfectly balanced — never tilts", "It does not depend"],
     1,
     "वृद्धि के लिए पौधे को ग्लूकोज़ बचाना पड़ता है — बनाई गई मात्रा जलाई गई से अधिक; इसीलिए 24 घंटे का शुद्ध हिसाब O2 के पक्ष में रहता है।",
     "To grow, the plant must save glucose — made more than burnt; hence the 24-hour ledger stays in favour of O2."),

    ("respiration-vs-other-processes", "hard",
     "अंकुरित बीजों से भरे थर्मास-फ्लास्क में तापमान धीरे-धीरे ऊपर चला गया — यह किस तथ्य का प्रमाण है?",
     "The temperature in a thermos flask packed with germinating seeds slowly rose — proof of which fact?",
     ["बीजों में दहन हुआ", "श्वसन ऊर्जा का कुछ अंश ताप के रूप में भी मुक्त होता है", "बीज प्रकाश-संश्लेषण कर रहे थे", "थर्मास खराब था"],
     ["Combustion occurred in the seeds", "Part of the energy of respiration is also released as heat", "The seeds were photosynthesising", "The thermos was faulty"],
     1,
     "ATP में न बँधी ऊर्जा ताप बनकर निकलती है — बंद फ्लास्क में इसी श्वसन-ताप का संचय तापमान बढ़ाता है।",
     "Energy not trapped in ATP leaves as heat — the build-up of this respiratory heat in a sealed flask raises the temperature."),

    ("respiration-vs-other-processes", "hard",
     "एक विद्यार्थी दावा करता है: 'पौधे सदैव O2 छोड़ते हैं, इसलिए उनमें श्वसन नहीं होता।' इस तर्क की त्रुटि कहाँ है?",
     "A student claims: 'Plants always release O2, so they do not respire.' Where is the flaw in this reasoning?",
     ["पौधे वाकई O2 नहीं छोड़ते", "O2 का निर्गम प्रकाश-संश्लेषण का फल है; श्वसन तो चुपचाप हर कोशिका में चलता रहता है — दोनों साथ हो सकते हैं", "पौधों में कोशिकाएँ नहीं होतीं", "श्वसन केवल जड़ों में होता है"],
     ["Plants really do not release O2", "The O2 release is the product of photosynthesis; respiration silently continues in every cell — both can occur together", "Plants have no cells", "Respiration happens only in roots"],
     1,
     "दो प्रक्रियाएँ एक साथ चलना संभव है — दिन में संश्लेषण की O2 श्वसन की खपत से अधिक हो तो शुद्ध O2 दिखती है; यह श्वसन का अनुपस्थिति-प्रमाण नहीं।",
     "Two processes can coexist — when daytime photosynthetic O2 exceeds respiratory use, net O2 shows up; that is no proof of respiration's absence."),
]
