# -*- coding: utf-8 -*-
"""B07 'Respiration & Gas Exchange' — Part 1 data (70 items).
Order: human-respiratory-system (40), aerobic-anaerobic-respiration (30).
Tuple: (topic, difficulty, q_hi, q_en, options_hi[4], options_en[4], correct_idx, exp_hi, exp_en)
"""

PART1 = [
    # ---------------- human-respiratory-system (40: E14/M20/H6) ----------------
    ("human-respiratory-system", "easy",
     "नाक से दाखिल हुई हवा नासिका गुहा से गुजरते समय किन तीनों कार्यों के लिए तैयार हो जाती है?",
     "While passing through the nasal cavity, the inhaled air gets readied by which THREE treatments?",
     ["केवल छानना", "केवल गर्म करना", "केवल नम करना", "छानना, गर्म करना और नम करना — तीनों"],
     ["Only filtering", "Only warming", "Only moistening", "Filtering, warming and moistening — all three"],
     3,
     "नासिका गुहा के बाल धूल छानते हैं, रुधिर की गर्मी हवा को गर्म रखती है और श्लेष्मा उसे नम करता है — फेफड़ों के लिए हवा इसी से अनुकूल बनती है।",
     "Nasal hairs filter dust, blood warmth heats the air and mucus moistens it — this makes the air lung-friendly."),

    ("human-respiratory-system", "easy",
     "शरीर में हवा और भोजन दोनों का रास्ता किस भाग में आपस में मिलता है?",
     "In which part do the pathways of air and food meet inside the body?",
     ["स्वरयंत्र (larynx)", "ग्रसनी (pharynx)", "श्वासनली", "उरोस्थि"],
     ["Larynx", "Pharynx", "Trachea", "Sternum"],
     1,
     "ग्रसनी हवा और भोजन दोनों की साझी नली है; यहीं से हवा स्वरयंत्र की ओर और भोजन भोजन-नली की ओर मुड़ती है।",
     "The pharynx is the shared tube for both air and food; here air turns towards the larynx and food towards the food pipe."),

    ("human-respiratory-system", "easy",
     "श्वासनली (trachea) फेफड़ों में प्रवेश करते हुए किन दो शाखाओं में बँट जाती है?",
     "On entering the lungs, the trachea divides into which two branches?",
     ["वायुकोश (alveoli)", "ब्रोंकाइओल", "ब्रांकाई (bronchi)", "केशिकाएँ"],
     ["Alveoli", "Bronchioles", "Bronchi", "Capillaries"],
     2,
     "श्वासनली दो ब्रांकाइयों में बँटती है — प्रत्येक फेफड़े के लिए एक; आगे ये ब्रोंकाइओल में विभाजित होती हैं।",
     "The trachea splits into two bronchi — one for each lung; these further subdivide into bronchioles."),

    ("human-respiratory-system", "easy",
     "ब्रोंकाइओल के सिरों पर स्थित गुब्बारे जैसी छोटी संरचनाएँ क्या कहलाती हैं?",
     "What are the balloon-like tiny structures at the ends of bronchioles called?",
     ["गलफड़े", "वायुकोश (एल्वियोलाइ)", "वेष्टनी", "पटलिका"],
     ["Gills", "Alveoli", "Tentacles", "Ribs"],
     1,
     "ब्रोंकाइओल के अंत में वायुकोशों के गुच्छे होते हैं — यहीं रुधिर के साथ ऑक्सीजन-कार्बन डाइऑक्साइड का आदान-प्रदान होता है।",
     "Clusters of alveoli sit at the bronchiole ends — this is where oxygen and carbon dioxide are exchanged with blood."),

    ("human-respiratory-system", "easy",
     "फेफड़े शरीर की किस गुहा में स्थित होते हैं?",
     "In which cavity of the body are the lungs located?",
     ["उदर गुहा", "वक्ष (छाती) गुहा", "कपाल गुहा", "श्रोणि गुहा"],
     ["Abdominal cavity", "Thoracic (chest) cavity", "Cranial cavity", "Pelvic cavity"],
     1,
     "दोनों फेफड़े छाती की गुहा में हृदय के दोनों ओर पसलियों के पिंजरे के भीतर सुरक्षित रहते हैं।",
     "Both lungs lie in the chest cavity on either side of the heart, safeguarded inside the rib cage."),

    ("human-respiratory-system", "easy",
     "फेफड़ों के ठीक नीचे स्थित पेशीय (मांसपेशी वाली) झिल्ली कौन-सी है?",
     "Which is the muscular sheet located just below the lungs?",
     ["उरोस्थि", "मध्यपट (डायाफ्राम)", "क्षुद्रांत्र", "पर्दा"],
     ["Sternum", "Diaphragm", "Duodenum", "Peritoneum"],
     1,
     "मध्यपट छाती और पेट के बीच की गुंबदार पेशीय झिल्ली है जिसकी हरकत से साँस की यंत्रीक्रिया चलती है।",
     "The diaphragm is the domed muscular sheet between chest and belly whose movement drives the breathing mechanism."),

    ("human-respiratory-system", "easy",
     "साँस छोड़ते समय (exhalation) मध्यपट की क्या अवस्था होती है?",
     "What is the state of the diaphragm during exhalation?",
     ["वह सिकुड़कर नीचे चली जाती है", "वह शिथिल होकर ऊपर गुंबद की तरह हो जाती है", "वह पूरी तरह रुक जाती है", "वह बाईं ओर खिसक जाती है"],
     ["It contracts and moves down", "It relaxes into an upward dome", "It stops completely", "It shifts to the left"],
     1,
     "साँस छोड़ते समय मध्यपट शिथिल होकर ऊपर की ओर गुंबदाकार हो जाती है, छाती का आकार घटता है और हवा बाहर निकलती है।",
     "While exhaling, the diaphragm relaxes into an upward dome, the chest size shrinks and air flows out."),

    ("human-respiratory-system", "easy",
     "वयस्क स्वस्थ मनुष्य की विश्राम अवस्था में श्वसन दर (प्रति मिनट साँस) लगभग कितनी होती है?",
     "What is the approximate breathing rate of a healthy adult at rest (breaths per minute)?",
     ["5–8", "15–18", "30–35", "45–50"],
     ["5–8", "15–18", "30–35", "45–50"],
     1,
     "विश्राम अवस्था में सामान्य श्वसन दर 15–18 साँस प्रति मिनट होती है; दौड़-व्यायाम में यह कई गुना बढ़ जाती है।",
     "At rest the normal breathing rate is 15–18 breaths per minute; during running or exercise it multiplies several-fold."),

    ("human-respiratory-system", "easy",
     "नाक के भीतर के बाल (nasal hairs) मुख्यतः क्या करते हैं?",
     "What do the hairs inside the nose mainly do?",
     ["हवा को गर्म करते हैं", "धूल और जीवाणु जैसे कण छानकर रोकते हैं", "हवा को नम करते हैं", "गंध पहचानते हैं"],
     ["They warm the air", "They filter out particles like dust and germs", "They moisten the air", "They detect smell"],
     1,
     "नासिका-बाल हवा का पहला छलनी-द्वार है — बड़े कण यहीं अटक जाते हैं, जिससे फेफड़े साफ हवा पाते हैं।",
     "Nasal hairs are the first sieve of air — large particles get trapped here, keeping the incoming air clean for lungs."),

    ("human-respiratory-system", "easy",
     "शरीर में गैसों का वास्तविक आदान-प्रदान मुख्यतः कहाँ होता है?",
     "Where does the actual exchange of gases mainly occur in the body?",
     ["श्वासनली में", "ब्रांकाइ में", "वायुकोशों (एल्वियोलाइ) में", "नासिका गुहा में"],
     ["In the trachea", "In the bronchi", "In the alveoli", "In the nasal cavity"],
     2,
     "पतली दीवारों वाले वायुकोश और उन्हें लपेटे केशिकाएँ मिलकर विनिमय-सतह बनाते हैं; शेष मार्ग केवल हवा पहुँचाता है।",
     "Thin-walled alveoli wrapped in capillaries form the exchange surface; the rest of the pathway merely delivers air."),

    ("human-respiratory-system", "easy",
     "फेफड़ों की बनावट कैसी होती है?",
     "What is the texture of the lungs?",
     ["ठोस और पत्थर जैसी", "स्पंजी (रसीली) और लचीली", "तरल", "अस्थियुक्त कठोर"],
     ["Solid and stone-like", "Spongy and elastic", "Liquid", "Bony and hard"],
     1,
     "फेफड़े करोड़ों वायुकोशों के कारण स्पंज की तरह दिखते हैं और लचीली प्रकृति के कारण साँस के साथ फैलते-सिकुड़ते हैं।",
     "Lungs look spongy due to millions of alveoli, and their elastic nature lets them expand and recoil with each breath."),

    ("human-respiratory-system", "easy",
     "एक साँस-चक्र (breathing cycle) में कौन-सी दो क्रियाएँ होती हैं?",
     "Which two actions make up one breathing cycle?",
     ["पाचन और अवशोषण", "श्वसन-ग्रहण (inhalation) और श्वसन-त्याग (exhalation)", "परिसंचरण और उत्सर्जन", "संश्लेषण और विघटन"],
     ["Digestion and absorption", "Inhalation and exhalation", "Circulation and excretion", "Synthesis and breakdown"],
     1,
     "हवा अंदर लेना (श्वसन-ग्रहण) और बाहर छोड़ना (श्वसन-त्याग) — मिलकर एक श्वास-चक्र बनाते हैं।",
     "Taking air in (inhalation) and throwing it out (exhalation) — together they form one breathing cycle."),

    ("human-respiratory-system", "easy",
     "श्वसन-मार्ग की भित्ति में चिपचिपा श्लेष्मा (mucus) क्यों स्रावित होता है?",
     "Why is sticky mucus secreted in the walls of the respiratory passage?",
     ["हवा को ठंडा करने के लिए", "धूल-कण और रोगाणु चिपकाकर फँसाने के लिए", "हवा की गति बढ़ाने के लिए", "आवाज़ उत्पन्न करने के लिए"],
     ["To cool the air", "To trap dust particles and germs by sticking them", "To speed up the airflow", "To produce voice"],
     1,
     "श्लेष्मा एक चिपचिपा जाल है — हवा के साथ आए कण उसमें चिपककर फेफड़ों तक जाने से रुक जाते हैं।",
     "Mucus is a sticky trap — particles riding the air stick to it and never reach the lungs."),

    ("human-respiratory-system", "easy",
     "मुँह से नहीं, नाक से साँस लेना बेहतर क्यों माना जाता है?",
     "Why is breathing through the nose better than through the mouth?",
     ["नाक में हवा का भंडार रहता है", "नाक की राह हवा छनकर, गर्म होकर और नम होकर जाती है", "मुँह से हवा अंदर नहीं जा सकती", "नाक से साँस तेज़ होती है"],
     ["The nose stores a reserve of air", "Air via the nose gets filtered, warmed and moistened", "Air cannot enter through the mouth", "Nasal breathing is faster"],
     1,
     "नाक का मार्ग हवा को तीनों तरह से सुधारता है; मुँह का रास्ता सीधा और अछना होने से फेफड़ों के लिए कम अनुकूल है।",
     "The nasal route improves air in all three ways; the mouth route is direct and unfiltered, hence less ideal for lungs."),

    ("human-respiratory-system", "medium",
     "मनुष्य में हवा के प्रवाह का सही क्रम कौन-सा है?",
     "Which is the correct sequence of airflow in humans?",
     ["नाक → श्वासनली → स्वरयंत्र → ब्रांकाई → वायुकोश", "नाक → स्वरयंत्र → श्वासनली → ब्रांकाई → ब्रोंकाइओल → वायुकोश", "नाक → ब्रांकाई → श्वासनली → ब्रोंकाइओल → वायुकोश", "नाक → ब्रोंकाइओल → ब्रांकाई → श्वासनली → वायुकोश"],
     ["Nose → trachea → larynx → bronchi → alveoli", "Nose → larynx → trachea → bronchi → bronchioles → alveoli", "Nose → bronchi → trachea → bronchioles → alveoli", "Nose → bronchioles → bronchi → trachea → alveoli"],
     1,
     "क्रम याद रखें — नाक, ग्रसनी, स्वरयंत्र, श्वासनली, ब्रांकाई, ब्रोंकाइओल और अंत में वायुकोश।",
     "Remember the order — nose, pharynx, larynx, trachea, bronchi, bronchioles and finally the alveoli."),

    ("human-respiratory-system", "medium",
     "साँस लेते समय (inhalation) मध्यपट की क्रिया क्या होती है?",
     "What does the diaphragm do during inhalation?",
     ["शिथिल होकर ऊपर उठ जाती है", "संकुचित होकर नीचे की ओर सपट (flat) हो जाती है", "बाईं ओर मुड़ जाती है", "कोई हरकत नहीं करती"],
     ["It relaxes and moves up", "It contracts and flattens downward", "It bends to the left", "It does not move"],
     1,
     "साँस लेते समय मध्यपट सिकुड़कर नीचे सपट हो जाती है — छाती-गुहा लंबी होती है, आयतन बढ़ता है और हवा अंदर खिंचती है।",
     "During inhalation the diaphragm contracts and flattens down — the chest cavity lengthens, volume rises and air is drawn in."),

    ("human-respiratory-system", "medium",
     "साँस अंदर लेते समय पसलियाँ और छाती की दीवार की क्या हालत होती है?",
     "What happens to the ribs and chest wall while inhaling?",
     ["पसलियाँ नीचे-अंदर आती हैं", "पसलियाँ ऊपर और बाहर की ओर उठती हैं — छाती चौड़ी होती है", "पसलियाँ स्थिर रहती हैं", "पसलियाँ अंदर की ओर दबती हैं"],
     ["The ribs move down and inward", "The ribs lift up and outward — the chest broadens", "The ribs stay still", "The ribs press inward"],
     1,
     "पसलियों के बीच की बाह्य पेशियाँ सिकुड़ती हैं, पसलियाँ ऊपर-बाहर उठती हैं और छाती-गुहा का आयतन बढ़ जाता है।",
     "Muscles between the ribs contract, the ribs swing up and out, and the chest cavity volume increases."),

    ("human-respiratory-system", "medium",
     "साँस अंदर खिंचने का मूल कारण क्या है?",
     "What is the basic reason that air gets drawn into the lungs?",
     ["फेफड़े खुद हवा चूसते हैं", "छाती-गुहा के आयतन बढ़ने से भीतर का दबाव बाहर के वायुमंडलीय दबाव से कम हो जाता है", "नाक में हवा का खिंचाव होता है", "हृदय की धड़कन हवा खींचती है"],
     ["The lungs themselves suck air", "As the chest cavity expands, pressure inside falls below the outside atmospheric pressure", "A pull develops inside the nose", "The heartbeat draws air in"],
     1,
     "दबाव-अंतर का यही नियम है — छाती फैलती है, भीतरी दबाव घटता है, और वायुमंडल की हवा संतुलन के लिए अंदर दौड़ती है।",
     "It is pure pressure physics — the chest expands, inner pressure drops, and atmospheric air rushes in to balance."),

    ("human-respiratory-system", "medium",
     "साँस लेते समय छाती-गुहा में आयतन और दबाव में क्या बदलाव होता है?",
     "What changes occur in the volume and pressure of the chest cavity during inhalation?",
     ["आयतन घटता है, दबान बढ़ता है", "आयतन बढ़ता है, दबाव घटता है", "दोनों बढ़ते हैं", "दोनों घटते हैं"],
     ["Volume falls, pressure rises", "Volume rises, pressure falls", "Both increase", "Both decrease"],
     1,
     "मध्यपट-पसलियों के सिकुड़ने से आयतन बढ़ता और दबाव घटता है — घटा दबाव ही हवा को भीतर बुलाता है।",
     "Contraction of the diaphragm and ribs raises volume and lowers pressure — the lowered pressure is what calls the air in."),

    ("human-respiratory-system", "medium",
     "पसलियों के बीच स्थित पेशियाँ (intercostal muscles) साँस लेते समय क्या करती हैं?",
     "What do the intercostal muscles between the ribs do during inhalation?",
     ["शिथिल हो जाती हैं", "संकुचित होकर पसलियों को ऊपर उठाती हैं", "पसलियों को तोड़ती हैं", "केवल खांसते समय काम करती हैं"],
     ["They relax", "They contract and lift the ribs upward", "They break the ribs", "They work only while coughing"],
     1,
     "अंतर-पसली पेशियों का संकुचन पसलियों के पिंजरे को ऊपर-बाहर खोलता है — मध्यपट के साथ मिलकर साँस की यंत्रीक्रिया पूरी करता है।",
     "Contraction of intercostal muscles swings the rib cage up and out — together with the diaphragm this completes the breathing mechanism."),

    ("human-respiratory-system", "medium",
     "सामान्य विश्राम-साँस छोड़ने की क्रिया किस प्रकार की मानी जाती है?",
     "Normal exhalation at rest is considered which type of process?",
     ["सक्रिय — पेशियों के संकुचन से", "निष्क्रिय (passive) — पेशियों के शिथिल होने से, बिना अतिरिक्त मेहनत के", "कोई क्रिया नहीं होती", "रुधिर-दबाव से चलने वाली"],
     ["Active — driven by muscle contraction", "Passive — driven by muscle relaxation, without extra effort", "No process occurs", "Driven by blood pressure"],
     1,
     "विश्राम में साँस छोड़ना निष्क्रिय है — मध्यपट व पसली-पेशियाँ शिथिल होती हैं और फेफड़ों की प्रत्यास्थता हवा को बाहर धकेल देती है; जोर से छोड़ने पर पेशियाँ सक्रिय होती हैं।",
     "Resting exhalation is passive — diaphragm and rib muscles relax and the lungs' own elasticity pushes air out; forceful exhalation recruits muscles."),

    ("human-respiratory-system", "medium",
     "दौड़ते समय हमारी साँस तेज़ और गहरी क्यों हो जाती है?",
     "Why do our breaths become fast and deep while running?",
     ["फेफड़े गर्म हो जाते हैं", "मांसपेशियों को अधिक ऊर्जा चाहिए — अधिक ऑक्सीजन लेने और अधिक कार्बन डाइऑक्साइड निकालने के लिए", "हवा में ऑक्सीजन घट जाती है", "हृदय धीमा पड़ जाता है"],
     ["The lungs heat up", "Muscles need more energy — to take in more oxygen and expel more carbon dioxide", "Oxygen in the air decreases", "The heart slows down"],
     1,
     "तेज़ काम से कोशिकीय श्वसन बढ़ता है; O2 की माँग और CO2 का उत्पादन दोनों बढ़ते हैं, इसलिए श्वसन-तंत्र तेज़ चलता है।",
     "Hard work raises cellular respiration; both the O2 demand and CO2 output rise, so the breathing system speeds up."),

    ("human-respiratory-system", "medium",
     "श्वास-जल परीक्षण में हमारी छोड़ी हुई साँस चूने के पानी को दूधिया कर देती है — इससे क्या प्रमाणित होता है?",
     "Our exhaled breath turns lime water milky — what does this prove?",
     ["छोड़ी हवा में ऑक्सीजन बढ़ जाती है", "छोड़ी हवा में कार्बन डाइऑक्साइड होता है", "हमारे फेफड़े बीमार हैं", "चूने का पानी जहरीला है"],
     ["Exhaled air has more oxygen", "Exhaled air contains carbon dioxide", "Our lungs are diseased", "Lime water is toxic"],
     1,
     "चूने का पानी CO2 का परीक्षक है — दूधिया होना CO2 की उपस्थिति का पक्का संकेत है; श्वसन में CO2 निकलता है।",
     "Lime water is the CO2 tester — turning milky is firm proof of CO2, which respiration releases."),

    ("human-respiratory-system", "medium",
     "भीतर ली गई हवा और छोड़ी गई हवा की संरचना में मुख्य अंतर क्या है?",
     "What is the main difference between the composition of inhaled and exhaled air?",
     ["छोड़ी हवा में CO2 अधिक, O2 कम और जल-वाष्प अधिक होता है", "छोड़ी हवा में O2 अधिक होता है", "दोनों एकदम समान होती हैं", "छोड़ी हवा में नाइट्रोजन नहीं होती"],
     ["Exhaled air has more CO2, less O2 and more water vapour", "Exhaled air has more O2", "Both are exactly the same", "Exhaled air lacks nitrogen"],
     0,
     "विनिमय में रुधिर CO2 छोड़कर O2 लेता है — इसलिए निकली हवा CO2 और जल-वाष्प से भरपूर, O2 से थोड़ी खाली होती है।",
     "In exchange, blood drops CO2 and picks up O2 — so the outgoing air is rich in CO2 and vapour, slightly poorer in O2."),

    ("human-respiratory-system", "medium",
     "छोड़ी गई हवा में ऑक्सीजन बिल्कुल खत्म क्यों नहीं हो जाती?",
     "Why is the exhaled air not completely emptied of oxygen?",
     ["फेफड़े O2 छानना भूल जाते हैं", "वायुकोशों में रुधिर के संपर्क में आने वाली सारी हवा का विनिमय नहीं हो पाता — कुछ O2 बची रह जाती है", "हम जानबूझकर O2 रोकते हैं", "नाक O2 वापस ले लेता है"],
     ["The lungs forget to filter O2", "Not all air coming in contact with blood in the alveoli gets exchanged — some O2 is left over", "We deliberately hold back O2", "The nose takes the O2 back"],
     1,
     "विनिमय पूर्ण निष्कासन तक नहीं पहुँचता — मरा हुआ अंश (dead space) और अपूर्ण संतुलन हमेशा कुछ O2 हवा में छोड़ देता है; इसीलिए प्राण-वायु (CPR) संभव है।",
     "Exchange never runs to completion — dead-space air and incomplete equilibration always leave some O2 in the breath; that is why mouth-to-mouth resuscitation works."),

    ("human-respiratory-system", "medium",
     "श्वासनली के भीतर की सतह पर पाई जाने वाली ग्रंथियुक्त तथा पक्षमाभीय परत मिलकर क्या कार्य करती है?",
     "What combined function is served by the glandular and ciliated lining inside the trachea?",
     ["भोजन पचाना", "श्लेष्मा बनाकर कण चिपकाना और पक्षमों से उसे ऊपर की ओर बाहर झाड़ना", "रुधिर बनाना", "आवाज़ के तार कसना"],
     ["Digesting food", "Secreting mucus to trap particles and sweeping it upward and out with cilia", "Making blood", "Tightening the vocal cords"],
     1,
     "श्लेष्मा-जाल + पक्षमा-झाड़ू का यह जोड़ा श्वसन-मार्ग की सफाई-व्यवस्था है — प्रदूषण और संक्रमण से फेफड़ों की रक्षा की पहली पंक्ति।",
     "The mucus-net plus cilia-broom pair is the airway's cleaning system — the first line of defence guarding lungs from dust and infection."),

    ("human-respiratory-system", "medium",
     "स्वरयंत्र (larynx) का क्या कार्य है?",
     "What is the function of the larynx?",
     ["हवा छानना", "आवाज़ उत्पन्न करना — इसी में स्वर-तंतु कंपित होते हैं", "भोजन पचाना", "रुधिर शुद्ध करना"],
     ["Filtering air", "Producing voice — its vocal cords vibrate", "Digesting food", "Purifying blood"],
     1,
     "स्वरयंत्र के दो स्वर-तंतु हवा के दबाव में कंपन करके ध्वनि बनाते हैं; इसीलिए इसे आवाज़ का पेटी कहते हैं।",
     "Two vocal cords inside the larynx vibrate under air pressure to create sound — hence it is called the voice box."),

    ("human-respiratory-system", "medium",
     "भोजन निगलते समय भोजन श्वासनली में जाने से कौन-सी संरचना रोकती है?",
     "Which structure prevents food from entering the trachea while swallowing?",
     ["उरोस्थि", "कंठ-पट्टिका (epiglottis)", "मध्यपट", "श्लेष्मा"],
     ["Sternum", "Epiglottis", "Diaphragm", "Mucus"],
     1,
     "निगलते समय कंठ-पट्टिका श्वासनली का ढक्कन बनकर स्वरयंत्र का द्वार बंद कर देती है — इसी से खाना भोजन-नली में ही जाता है।",
     "While swallowing, the epiglottis acts as a lid, sealing the entrance of the airway so food goes only down the food pipe."),

    ("human-respiratory-system", "medium",
     "वायुकोशों (alveoli) की संख्या फेफड़ों में करोड़ों में होती है — इसका मुख्य परिणाम क्या है?",
     "The alveoli number in millions inside the lungs — what is the chief outcome of this?",
     ["फेफड़े भारी हो जाते हैं", "हवा के साथ रुधिर के संपर्क की सतह अत्यंत बड़ी हो जाती है", "हवा गर्म हो जाती है", "साँस की आवाज़ प्रबल होती है"],
     ["The lungs become heavy", "The surface of contact between air and blood becomes enormously large", "The air gets warmed", "The sound of breathing grows louder"],
     1,
     "करोड़ों छोटे-छोटे वायुकोश मिलकर विनिमय-सतह को इतना विस्तार देते हैं कि गैस-विनिमय तेज़ी और पर्याप्त मात्रा में हो सके।",
     "Millions of tiny alveoli stretch the exchange surface so wide that gas exchange happens fast and in adequate quantity."),

    ("human-respiratory-system", "medium",
     "व्यायाम के तुरंत बाद विद्यार्थी अपनी साँसों की गिनती करता है — प्रयोग से क्या निष्कर्ष निकलता है?",
     "A student counts breaths immediately after exercise — what conclusion does the experiment yield?",
     ["विश्राम की तुलना में श्वसन-दर बढ़ जाती है", "श्वसन-दर घट जाती है", "श्वसन-दर बिल्कुल बदलती नहीं", "साँस रुक जाती है"],
     ["The breathing rate rises compared with rest", "The breathing rate falls", "The breathing rate does not change at all", "Breathing stops"],
     0,
     "मांसपेशियों के काम से O2-खपत व CO2-निर्माण बढ़ता है; शरीर का प्रतिक्रिया-उत्तर है — तेज़ श्वसन-दर।",
     "Working muscles consume more O2 and release more CO2; the body's response is a faster breathing rate."),

    ("human-respiratory-system", "medium",
     "स्कूल-प्रयोग में श्वसन-मॉडल के काँच-जार में गुब्बारे (फेफड़े) और नीचे रबर की झिल्ली होती है — झिल्ली किसे दर्शाती है?",
     "In the bell-jar breathing model, balloons (lungs) sit above a rubber sheet — what does the sheet represent?",
     ["हृदय", "मध्यपट (डायाफ्राम)", "यकृत", "पसलियाँ"],
     ["The heart", "The diaphragm", "The liver", "The ribs"],
     1,
     "झिल्ली नीचे खींचने पर गुब्बारे फूलते हैं और छोड़ने पर सिकुड़ते हैं — ठीक वैसे ही जैसे मध्यपट की हरकत से फेफड़े हवा भरते-खाली करते हैं।",
     "Pulling the sheet down inflates the balloons and releasing it deflates them — exactly how diaphragm movement fills and empties the lungs."),

    ("human-respiratory-system", "medium",
     "श्वास-मार्ग का सबसे छोटा अंतिम विभाजन कौन-सा है जिससे वायुकोश जुड़ते हैं?",
     "Which is the smallest final division of the airway to which the alveoli attach?",
     ["ब्रांका", "ब्रोंकाइओल", "श्वासनली", "ग्रसनी"],
     ["Bronchus", "Bronchiole", "Trachea", "Pharynx"],
     1,
     "ब्रांकाइ से अनगिनत सूक्ष्म ब्रोंकाइओल निकलते हैं और हर ब्रोंकाइओल के सिरे पर वायुकोशों का गुच्छा लगा होता है।",
     "Countless fine bronchioles branch off the bronchi, and each bronchiole tip carries a cluster of alveoli."),

    ("human-respiratory-system", "medium",
     "क्या होगा यदि श्वासनली की दीवार में उपास्थि के सख्त छल्ले न हों?",
     "What would happen if the trachea lacked its stiff rings of cartilage?",
     ["कुछ नहीं होता", "नली दबाव पर बैठ जाती और हवा का रास्ता बंद हो जाता", "आवाज़ बंद हो जाती", "भोजन नली में जाने लगता"],
     ["Nothing would happen", "The tube would collapse under pressure and block the airflow", "The voice would stop", "Food would start entering it"],
     1,
     "छल्ले नली को हमेशा खुला रखते हैं; इनके बिना गले के बाहरी दबाव में हवा की नली दब जाती — साँस लेना संकट में पड़ जाता।",
     "The rings keep the tube permanently open; without them external pressure of the neck would flatten the airway and make breathing critical."),

    ("human-respiratory-system", "hard",
     "बायाँ फेफड़ा दाएँ से थोड़ा छोटा क्यों होता है?",
     "Why is the left lung slightly smaller than the right?",
     ["बाईं ओर हवा कम जाती है", "बाईं ओर हृदय को जगह देने के लिए", "बायाँ फेफड़ा निष्क्रिय होता है", "जन्मजात विकृति से"],
     ["Less air goes to the left side", "To make room for the heart on the left side", "The left lung is non-functional", "Due to a birth defect"],
     1,
     "हृदय छाती में थोड़ा बाईं ओर झुका होता है; बायाँ फेफड़ा उसे जगह देने के लिए दाएँ से छोटा और आकार में खांचेदार बना है।",
     "The heart tilts slightly to the left in the chest; the left lung is correspondingly smaller and notched to accommodate it."),

    ("human-respiratory-system", "hard",
     "क्या फेफड़े अपने आप फैल-सिकुड़ सकते हैं?",
     "Can the lungs expand and contract on their own?",
     ["हाँ, उनमें खिंचाव-पेशी होती है", "नहीं — उन्हें बाहर से मध्यपट और पसली-पेशियों की हरकत से फैलाया-सिकोड़ा जाता है", "हाँ, हवा के दबाव से खुद चलते हैं", "केवल नींद में खुद चलते हैं"],
     ["Yes, they contain stretch muscles", "No — they are inflated and deflated externally by the movements of the diaphragm and rib muscles", "Yes, air pressure runs them by itself", "Only during sleep do they run themselves"],
     1,
     "फेफड़ों में अपनी संकुचन-पेशी नहीं होती; वे मध्यपट व अंतर-पसली पेशियों द्वारा बदले गए छाती-दबाव के साथ निष्क्रिय रूप से फैलते-सिकुड़ते हैं।",
     "Lungs have no muscles of their own to drive breathing; they passively follow the chest-pressure changes created by the diaphragm and intercostal muscles."),

    ("human-respiratory-system", "hard",
     "खाँसते या छींकते समय शरीर में क्या होता है?",
     "What happens in the body during coughing or sneezing?",
     ["मध्यपट शिथिल हो जाता है", "पेट-पेशियों व मध्यपट के जोरदार संकुचन से हवा बड़ी रफ्तार से बाहर फेंकी जाती है — उकसावे वाले कण निकल जाते हैं", "फेफड़े बंद हो जाते हैं", "हवा पेट में चली जाती है"],
     ["The diaphragm relaxes", "Forceful contraction of abdominal muscles and the diaphragm throws air out at high speed — the irritating particles are expelled", "The lungs shut down", "The air diverts into the stomach"],
     1,
     "खाँसा-छींक श्वसन-मार्ग का सुरक्षा-प्रतिवर्त है — तीव्र दबाव की हवा के झोंके से गले-नाक का कचरा बाहर फेंका जाता है।",
     "Coughing and sneezing are protective reflexes of the airway — a high-pressure blast of air throws the irritant debris out."),

    ("human-respiratory-system", "hard",
     "गहरी नींद में भी हमारी साँस बिना रुके चलती रहती है — इसका नियंत्रण कौन करता है?",
     "Our breathing continues without pause even in deep sleep — which part controls this?",
     ["फेफड़े स्वयं", "मस्तिष्क का श्वसन-केंद्र (medulla)", "हृदय", "पसलियाँ"],
     ["The lungs themselves", "The respiratory centre of the brain (medulla)", "The heart", "The ribs"],
     1,
     "मस्तिष्क-तना (मेडुला) का श्वसन-केंद्र रुधिर की CO2-मात्रा पर नज़र रखकर स्वतः साँस की दर नियंत्रित करता है — इसीलिए नींद में भी श्वसन चलता रहता है।",
     "The respiratory centre in the brain stem (medulla) monitors blood CO2 and automatically sets the breathing rate — so breathing never stops in sleep."),

    ("human-respiratory-system", "hard",
     "डूबते व्यक्ति को खींचते समय बचावकर्ता उसका पानी निकालने के बाद मुँह-से-मुँह साँस (CPR-की तरह) देता है — यह कैसे काम करता है?",
     "How does mouth-to-mouth breathing given during rescue work?",
     ["बचावकर्ता अपनी छोड़ी हवा में मौजूद बची हुई ऑक्सीजन से डूबते व्यक्ति के फेफड़े फुलाता है", "वह शुद्ध ऑक्सीजन बनाता है", "उसकी हवा में CO2 ज्यादा होती है जो अच्छा है", "यह केवल मनोबल बढ़ाता है"],
     ["The rescuer's exhaled air still carries leftover oxygen, which inflates the victim's lungs", "The rescuer produces pure oxygen", "His air is rich in CO2, which is good", "It only boosts morale"],
     0,
     "छोड़ी हुई हवा में लगभग 16% ऑक्सीजन बची रहती है — यही अंश डूबते व्यक्ति के रुधिर तक पहुँचकर जान बचा सकता है।",
     "Exhaled air retains roughly 16% oxygen — this fraction can reach the victim's blood and save a life."),

    ("human-respiratory-system", "medium",
     "कक्षा-प्रयोग में विद्यार्थी साँस भरने और छोड़ने पर छाती की परिधि मापता है — साँस भरने पर परिधि बढ़ना किसे प्रदर्शित करता है?",
     "In a class experiment a student measures chest circumference while inhaling and exhaling — what does the increase on inhaling demonstrate?",
     ["फेफड़ों में रुधिर का भरना", "पसलियों का ऊपर-बाहर उठकर छाती-गुहा बड़ा करना — श्वसन-यंत्रीक्रिया का सीधा प्रमाण", "हृदय का फैलना", "मध्यपट का ऊपर उठना"],
     ["Blood filling the lungs", "The ribs rising up and outward enlarging the chest cavity — direct proof of the breathing mechanism", "The heart expanding", "The diaphragm moving up"],
     1,
     "साँस भरते समय पसली-पिंजरा ऊपर-बाहर खुलता है और मध्यपट नीचे जाता है — परिधि का बढ़ना इसी यंत्रीक्रिया का मापने-योग्य प्रमाण है।",
     "While inhaling, the rib cage swings up and out as the diaphragm descends — the growing circumference is measurable proof of this mechanism."),

    ("human-respiratory-system", "hard",
     "हिचकी (hiccup) आने का कारण क्या होता है?",
     "What causes hiccups?",
     ["फेफड़ों में वायु भर जाना", "मध्यपट की पेशी में अनैच्छिक झटकेदार संकुचन (spasm) होना", "हृदय की धड़कन बढ़ना", "भोजन-नली में वायु फँसना"],
     ["Air filling the lungs", "Sudden involuntary spasmodic contraction of the diaphragm muscle", "A rise in the heartbeat", "Air trapping in the food pipe"],
     1,
     "हिचकी मध्यपट की अचानक अनैच्छिक ऐंठन है — हर झटके से हवा तेजी से अंदर आती है और स्वरयंत्र का द्वार बंद होकर विशेष ध्वनि बनाता है।",
     "A hiccup is a sudden involuntary spasm of the diaphragm — each jerk pulls air in sharply and the voice-box snap shut makes the characteristic sound."),

    # ---------------- aerobic-anaerobic-respiration (30: E10/M16/H4) ----------------
    ("aerobic-anaerobic-respiration", "easy",
     "ऑक्सीजन की उपस्थिति में ग्लूकोज़ के विघटन को क्या कहते हैं?",
     "What is the breakdown of glucose in the presence of oxygen called?",
     ["अवायवीय श्वसन", "वायवीय (एरोबिक) श्वसन", "प्रकाश-संश्लेषण", "वाष्पोत्सर्जन"],
     ["Anaerobic respiration", "Aerobic respiration", "Photosynthesis", "Transpiration"],
     1,
     "ऑक्सीजन के साथ होने वाला श्वसन वायवीय श्वसन है — यह ग्लूकोज़ को पूर्णतः तोड़कर सर्वाधिक ऊर्जा देता है।",
     "Respiration that uses oxygen is aerobic respiration — it breaks glucose completely and yields the most energy."),

    ("aerobic-anaerobic-respiration", "easy",
     "वायवीय श्वसन के अंतिम उत्पाद कौन-से हैं?",
     "What are the end products of aerobic respiration?",
     ["एथेनॉल + CO2", "लैक्टिक अम्ल + ऊर्जा", "CO2 + जल + ऊर्जा", "ग्लूकोज़ + ऑक्सीजन"],
     ["Ethanol + CO2", "Lactic acid + energy", "CO2 + water + energy", "Glucose + oxygen"],
     2,
     "ऑक्सीजन में ग्लूकोज़ पूरा टूटकर कार्बन डाइऑक्साइड, जल और बड़ी मात्रा में ऊर्जा देता है।",
     "In oxygen, glucose breaks fully into carbon dioxide, water and a large amount of energy."),

    ("aerobic-anaerobic-respiration", "easy",
     "'अवायवीय (anaerobic)' शब्द का अर्थ क्या है?",
     "What does the word 'anaerobic' mean?",
     ["ऑक्सीजन की उपस्थिति में", "ऑक्सीजन की अनुपस्थिति में", "प्रकाश में", "जल में"],
     ["In the presence of oxygen", "In the absence of oxygen", "In light", "In water"],
     1,
     "एन = नहीं, एरोबिक = वायु-श्वसन — अर्थात् बिना ऑक्सीजन के होने वाला श्वसन।",
     "An = without, aerobic = air-using — respiration happening without oxygen."),

    ("aerobic-anaerobic-respiration", "easy",
     "ऑक्सीजन के बिना खमीर (yeast) ग्लूकोज़ को तोड़कर क्या बनाता है?",
     "Without oxygen, what does yeast produce by breaking glucose?",
     ["लैक्टिक अम्ल", "एथेनॉल (अल्कोहल) + CO2", "जल + ऊर्जा", "प्रोटीन"],
     ["Lactic acid", "Ethanol (alcohol) + CO2", "Water + energy", "Protein"],
     1,
     "खमीर का अवायवीय श्वसन ग्लूकोज़ से एथेनॉल और CO2 बनाता है — यही किण्वन (fermentation) है।",
     "Yeast's anaerobic respiration converts glucose into ethanol and CO2 — this is fermentation."),

    ("aerobic-anaerobic-respiration", "easy",
     "खमीर द्वारा अवायवीय श्वसन की प्रक्रिया का विशेष नाम क्या है?",
     "What is the special name of the anaerobic respiration carried out by yeast?",
     ["प्रकाश-संश्लेषण", "किण्वन (fermentation)", "वाष्पोत्सर्जन", "उत्सर्जन"],
     ["Photosynthesis", "Fermentation", "Transpiration", "Excretion"],
     1,
     "खमीर का शराब/CO2 उत्पादक अवायवीय श्वसन ही किण्वन कहलाता है — डोमेस्टिक उपयोग इसी से जुड़े हैं।",
     "Yeast's alcohol-and-CO2-producing anaerobic respiration is called fermentation — many household uses depend on it."),

    ("aerobic-anaerobic-respiration", "easy",
     "तेज़ दौड़ के बाद पैरों की मांसपेशियों में ऐंठन (cramps) क्यों पड़ती है?",
     "Why do leg muscles develop cramps after a fast run?",
     ["मांसपेशियाँ फट जाती हैं", "ऑक्सीजन की कमी में बना लैक्टिक अम्ल जमा हो जाता है", "हड्डियाँ घिस जाती हैं", "रुधिर की मात्रा घट जाती है"],
     ["The muscles tear", "Lactic acid formed due to oxygen shortage accumulates", "The bones wear out", "The blood volume falls"],
     1,
     "तेज़ काम में O2 पूरी नहीं पहुँचती — मांसपेशियाँ अवायवीय श्वसन से लैक्टिक अम्ल बनाती हैं और उसके जमा होने से ऐंठन-दर्द होता है।",
     "During intense work O2 runs short — muscles switch to anaerobic respiration, and the accumulated lactic acid causes cramping pain."),

    ("aerobic-anaerobic-respiration", "easy",
     "कोशिका के भीतर वायवीय श्वसन मुख्यतः कहाँ होता है?",
     "Where inside the cell does aerobic respiration mainly occur?",
     ["माइटोकॉन्ड्रिया", "राइबोसोम", "केंद्रक", "गॉल्जी उपकरण"],
     ["Mitochondria", "Ribosome", "Nucleus", "Golgi apparatus"],
     1,
     "माइटोकॉन्ड्रिया कोशिका की ऊर्जा-मशीन है — ग्लूकोज़ का ऑक्सीजन के साथ विघटन यहीं पूरा होता है।",
     "Mitochondria are the cell's power plants — the oxygen-based breakdown of glucose is completed here."),

    ("aerobic-anaerobic-respiration", "easy",
     "वायवीय और अवायवीय श्वसन में से किसमें ऊर्जा की प्राप्ति अधिक होती है?",
     "Between aerobic and anaerobic respiration, which yields more energy?",
     ["अवायवीय में", "वायवीय में", "दोनों में बराबर", "किसी में नहीं"],
     ["In anaerobic", "In aerobic", "Equal in both", "In neither"],
     1,
     "वायवीय श्वसन ग्लूकोज़ का पूर्ण विघटन करता है, इसलिए ऊर्जा बहुत अधिक मिलती है; अवायवीय में विघटन अधूरा रहता है।",
     "Aerobic respiration breaks glucose completely, releasing far more energy; anaerobic breakdown stays incomplete."),

    ("aerobic-anaerobic-respiration", "easy",
     "कोशिका में ऊर्जा किस रूप में संग्रहीत रहती है?",
     "In what form is energy stored in the cell?",
     ["वसा कणों में सदैव", "ATP (एडेनोसीन ट्राइफॉस्फेट) के रूप में", "विटामिनों में", "जल में"],
     ["Always in fat droplets", "As ATP (adenosine triphosphate)", "In vitamins", "In water"],
     1,
     "श्वसन से छूटी ऊर्जा ATP अणुओं में जमा होती है; कोशिका जब चाहे, ATP तोड़कर तुरंत ऊर्जा ले लेती है।",
     "Energy freed by respiration is packed into ATP molecules; the cell snaps an ATP whenever it needs instant energy."),

    ("aerobic-anaerobic-respiration", "easy",
     "हमारी मांसपेशियाँ कब अवायवीय श्वसन का सहारा लेती हैं?",
     "When do our muscles take recourse to anaerobic respiration?",
     ["जब ऑक्सीजन की आपूर्ति काम की माँग के बराबर नहीं पहुँच पाती", "सोते समय", "भोजन के समय", "विश्राम में सदैव"],
     ["When the oxygen supply cannot match the demand of the work", "While sleeping", "While eating", "Always at rest"],
     0,
     "भारी-तेज़ काम में रुधिर से O2 की आपूर्ति पीछे रह जाती है — तब मांसपेशियाँ बिना O2 वाले मार्ग से ऊर्जा बनाती हैं।",
     "During heavy exertion, blood cannot deliver O2 fast enough — muscles then extract energy through the oxygen-free route."),

    ("aerobic-anaerobic-respiration", "medium",
     "वायवीय श्वसन का शब्द-समीकरण पूरा कीजिए: ग्लूकोज़ + ऑक्सीजन → ?",
     "Complete the word equation of aerobic respiration: glucose + oxygen → ?",
     ["एथेनॉल + CO2 + ऊर्जा", "CO2 + जल + ऊर्जा", "लैक्टिक अम्ल + जल", "प्रोटीन + ऊर्जा"],
     ["Ethanol + CO2 + energy", "CO2 + water + energy", "Lactic acid + water", "Protein + energy"],
     1,
     "ग्लूकोज़ + O2 → CO2 + H2O + ऊर्जा — वायवीय श्वसन का यही संतुलित समीकरण है।",
     "Glucose + O2 → CO2 + H2O + energy — this is the balanced equation of aerobic respiration."),

    ("aerobic-anaerobic-respiration", "medium",
     "खमीर में अवायवीय श्वसन का समीकरण क्या है?",
     "What is the equation of anaerobic respiration in yeast?",
     ["ग्लूकोज़ → लैक्टिक अम्ल + ऊर्जा", "ग्लूकोज़ → एथेनॉल + CO2 + ऊर्जा", "ग्लूकोज़ + O2 → CO2 + H2O", "ग्लूकोज़ → ग्लाइकोजन + ऊर्जा"],
     ["Glucose → lactic acid + energy", "Glucose → ethanol + CO2 + energy", "Glucose + O2 → CO2 + H2O", "Glucose → glycogen + energy"],
     1,
     "खमीर ग्लूकोज़ को एथेनॉल और CO2 में तोड़ता है — इसी से शराब और बेकरी-उत्पाद जुड़े हैं।",
     "Yeast splits glucose into ethanol and CO2 — the basis of brewing and bakery products."),

    ("aerobic-anaerobic-respiration", "medium",
     "हमारी मांसपेशियों में अवायवीय श्वसन का समीकरण क्या है?",
     "What is the equation of anaerobic respiration in our muscles?",
     ["ग्लूकोज़ → एथेनॉल + CO2 + ऊर्जा", "ग्लूकोज़ → लैक्टिक अम्ल + ऊर्जा", "ग्लूकोज़ + O2 → CO2 + जल", "ग्लूकोज़ → स्टार्च + ऊर्जा"],
     ["Glucose → ethanol + CO2 + energy", "Glucose → lactic acid + energy", "Glucose + O2 → CO2 + water", "Glucose → starch + energy"],
     1,
     "ऑक्सीजन की कमी में मांसपेशियाँ ग्लूकोज़ को लैक्टिक अम्ल में तोड़ती हैं — ध्यान दें, यहाँ CO2 नहीं बनता।",
     "Short of oxygen, muscles break glucose into lactic acid — note, no CO2 forms here."),

    ("aerobic-anaerobic-respiration", "medium",
     "अवायवीय श्वसन में ऊर्जा कम क्यों मिलती है?",
     "Why does anaerobic respiration release less energy?",
     ["क्योंकि ग्लूकोज़ बिल्कुल टूटता नहीं — विघटन अधूरा रहता है और ऊर्जा अंतिम उत्पादों में बंद रह जाती है", "क्योंकि ऑक्सीजन ऊर्जा खा जाती है", "क्योंकि ग्लूकोज़ बनना बंद हो जाता है", "क्योंकि ATP काम नहीं करता"],
     ["Because glucose is not fully broken — the breakdown stays incomplete and energy remains locked in the end products", "Because oxygen eats up the energy", "Because glucose stops forming", "Because ATP stops working"],
     0,
     "अधूरे विघटन (एथेनॉल/लैक्टिक अम्ल) में ग्लूकोज़ की बची ऊर्जा उत्पादों के भीतर ही रह जाती है — इसीलिए ऊर्जा-लाभ कम होता है।",
     "In incomplete breakdown (ethanol/lactic acid), part of glucose's energy stays sealed inside the products — hence the smaller energy gain."),

    ("aerobic-anaerobic-respiration", "medium",
     "दौड़ समाप्त करने के बाद भी खिलाड़ी कुछ देर तेज़ साँस लेता रहता है — कारण?",
     "Even after finishing a race, an athlete keeps breathing hard for a while — why?",
     ["उसे डर लगता है", "जमा लैक्टिक अम्ल तोड़ने के लिए अतिरिक्त ऑक्सीजन चाहिए — 'ऑक्सीजन-ऋण' चुकाना पड़ता है", "उसके फेफड़े कमजोर हैं", "हवा में O2 घट गई थी"],
     ["He feels scared", "Breaking the accumulated lactic acid needs extra oxygen — the 'oxygen debt' must be repaid", "His lungs are weak", "The air had less O2"],
     1,
     "मांसपेशियों का लैक्टिक अम्ल तभी हटता है जब अतिरिक्त O2 ली जाए — इसी अतिरिक्त साँस को ऑक्सीजन-ऋण की भरपाई कहते हैं।",
     "Muscle lactic acid clears only with extra O2 intake — this after-race heavy breathing is called repaying the oxygen debt."),

    ("aerobic-anaerobic-respiration", "medium",
     "निम्न में से कौन-सा कथन वायवीय-अवायवीय श्वसन के बारे में सही है?",
     "Which statement about aerobic and anaerobic respiration is correct?",
     ["दोनों में उत्पाद समान होते हैं", "वायवीय में ग्लूकोज़ पूर्ण टूटता है, अवायवीय में आंशिक", "अवायवीय केवल मनुष्य में होता है", "वायवीय में ATP नहीं बनता"],
     ["Both have identical products", "In aerobic, glucose breaks completely; in anaerobic, partially", "Anaerobic occurs only in humans", "No ATP forms in aerobic"],
     1,
     "पूर्ण-विघटन (CO2+H2O) बनाम आंशिक-विघटन (एथेनॉल/लैक्टिक अम्ल) — यही दोनों का मूल अंतर है।",
     "Complete breakdown (CO2+H2O) versus partial breakdown (ethanol/lactic acid) — that is the core difference between the two."),

    ("aerobic-anaerobic-respiration", "medium",
     "श्वसन से मिली ATP की ऊर्जा कोशिका किन कार्यों में खर्च करती है?",
     "For which tasks does the cell spend the ATP energy obtained from respiration?",
     ["केवल भोजन चबाने में", "प्रोटीन-संश्लेषण, मांसपेशी-संकुचन और तंत्रिका-आवेग जैसे सभी जैविक कार्यों में", "केवल विचारने में", "केवल नींद में"],
     ["Only in chewing food", "In all biological work like protein synthesis, muscle contraction and nerve impulses", "Only in thinking", "Only in sleep"],
     1,
     "ATP कोशिका की सर्व-उपयोगी मुद्रा है — निर्माण से गति और संकेत तक हर काम इसी से चलता है।",
     "ATP is the cell's all-purpose currency — from building to moving to signalling, every job runs on it."),

    ("aerobic-anaerobic-respiration", "medium",
     "ग्लूकोज़ से पाइरूवेट बनने की पहली अभिक्रिया कोशिका के किस भाग में होती है?",
     "In which part of the cell does the first reaction, glucose to pyruvate, take place?",
     ["कोशिका-द्रव्य (cytoplasm)", "माइटोकॉन्ड्रिया", "केंद्रक", "कोशिका-भित्ति"],
     ["Cytoplasm", "Mitochondria", "Nucleus", "Cell wall"],
     0,
     "ग्लूकोज़ का पाइरूवेट में टूटना (ग्लाइकोलिसिस) कोशिका-द्रव्य में होता है; आगे का रास्ता O2 के होने-न होने पर तय होता है।",
     "The splitting of glucose into pyruvate (glycolysis) happens in the cytoplasm; the further route depends on whether O2 is available."),

    ("aerobic-anaerobic-respiration", "medium",
     "वर्षा में जलभराव (waterlogging) से पौधे की जड़ें क्यों क्षतिग्रस्त होती हैं?",
     "Why are plant roots damaged by waterlogging in the rainy season?",
     ["जड़ों को प्रकाश नहीं मिलता", "मिट्टी के छिद्रों में वायु की जगह जल भर जाता है — ऑक्सीजन न मिलने पर जड़-कोशिकाएँ अवायवीय श्वसन कर अपने ही ऊतकों को हानि पहुँचाती हैं", "जल में सभी खनिज घुल जाते हैं", "जड़ें तैरने लगती हैं"],
     ["Roots get no light", "Water fills the soil air-pores — starved of oxygen, root cells respire anaerobically and harm their own tissues", "All minerals dissolve away in water", "The roots start floating"],
     1,
     "जलभराव में जड़ों को O2 नहीं मिलती; लंबे अवायवीय श्वसन के विषैले उत्पाद जड़ों को मार डालते हैं — इसीलिए गमलों में निकास-छेद रखा जाता है।",
     "In waterlogged soil roots get no O2; prolonged anaerobic respiration and its toxic products kill the roots — hence drainage holes in pots."),

    ("aerobic-anaerobic-respiration", "medium",
     "शरीर में ग्लूकोज़ का ऑक्सीकरण एक साथ प्रज्वलित होने की बजाय छोटे-छोटे चरणों में क्यों होता है?",
     "Why does the oxidation of glucose in the body occur in small steps rather than bursting at once?",
     ["क्योंकि शरीर में आग लग सकती है", "चरणबद्ध-नियंत्रित ऑक्सीकरण से ऊर्जा धीरे-धीरे ATP में बाँधी जा सकती है — अचानक जलने से ऊर्जा नष्ट हो जाती", "क्योंकि ग्लूकोज़ जलता नहीं", "क्योंकि ऑक्सीजन कम होती है"],
     ["Because the body might catch fire", "Step-wise controlled oxidation lets energy be trapped gradually into ATP — a sudden burn would waste it", "Because glucose cannot burn", "Because oxygen is scarce"],
     1,
     "एक साथ जलने पर सारी ऊर्जा ताप के रूप में बिखर जाती; चरणबद्ध मार्ग उसे ATP के छोटे पैकेटों में सुरक्षित रखता है — यही जीव-विशेषता है।",
     "Burning all at once would scatter the energy as heat; the stepwise pathway banks it in small ATP packets — a hallmark of life."),

    ("aerobic-anaerobic-respiration", "medium",
     "वायवीय श्वसन और खमीर के अवायवीय श्वसन के उत्पादों का सही सुमेलन कौन-सा है?",
     "Which is the correct matching of products of aerobic respiration and yeast's anaerobic respiration?",
     ["वायवीय — CO2 व जल; खमीर — एथेनॉल व CO2", "वायवीय — एथेनॉल; खमीर — जल", "वायवीय — लैक्टिक अम्ल; खमीर — जल", "दोनों — केवल CO2"],
     ["Aerobic — CO2 and water; yeast — ethanol and CO2", "Aerobic — ethanol; yeast — water", "Aerobic — lactic acid; yeast — water", "Both — only CO2"],
     0,
     "दोनों प्रक्रियाओं में CO2 निकलता है, पर वायवीय का दूसरा उत्पाद जल और खमीर का दूसरा उत्पाद एथेनॉल होता है।",
     "Both release CO2, but the second product is water in aerobic respiration and ethanol in yeast."),

    ("aerobic-anaerobic-respiration", "medium",
     "मांसपेशी-कोशिकाओं में बना लैक्टिक अम्ल विश्राम के दौरान का क्या होता है?",
     "What happens to the lactic acid formed in muscle cells during rest?",
     ["वह मूत्र से सीधे बाहर चला जाता है", "यकृत में ले जाकर पुनः ग्लूकोज़ में बदला जाता है — इसी से ऐंठन धीरे-धीरे शांत होती है", "वह हड्डियों में जम जाता है", "वह वहीं रक्त में सदैव घूमता रहता है"],
     ["It passes out directly in urine", "It is carried to the liver and reconverted into glucose — that is why cramps ease gradually", "It deposits in bones", "It keeps circulating forever"],
     1,
     "विश्राम में O2 की पर्याप्त आपूर्ति से यकृत लैक्टिक अम्ल को पुनर्चक्रित करता है — ऑक्सीजन-ऋण की अदायगी इसी समय होती है।",
     "With ample O2 at rest, the liver recycles the lactic acid — this is exactly when the oxygen debt is settled."),

    ("aerobic-anaerobic-respiration", "medium",
     "हमारी मांसपेशियों के अवायवीय श्वसन में CO2 क्यों नहीं बनती, जबकि खमीर में बनती है?",
     "Why is no CO2 formed in the anaerobic respiration of our muscles, while yeast forms it?",
     ["मांसपेशियाँ CO2 पचा लेती हैं", "दोनों के अंतिम चरण के एंजाइम भिन्न हैं — पाइरूवेट पहले लैक्टिक अम्ल बनता है, दूसरे में एथेनॉल + CO2", "मांसपेशियों में ग्लूकोज़ नहीं होता", "CO2 केवल पौधों में बनती है"],
     ["Muscles digest the CO2", "Their final-step enzymes differ — pyruvate becomes lactic acid in one, ethanol + CO2 in the other", "Muscles lack glucose", "CO2 forms only in plants"],
     1,
     "ऑक्सीजन के अभाव में पाइरूवेट का भाग्य जीव-विशेष एंजाइमों पर निर्भर है — मांसपेशी में लैक्टिक अम्ल, खमीर में एथेनॉल व CO2।",
     "In the absence of oxygen, pyruvate's fate depends on organism-specific enzymes — lactic acid in muscle, ethanol and CO2 in yeast."),

    ("aerobic-anaerobic-respiration", "medium",
     "किण्वन (fermentation) के दौरान गुब्बारे में बंद खमीर-शक्कर मिश्रण में गुब्बारा फूलता है — गुब्बारे की गैस कौन-सी है?",
     "During fermentation, a balloon over a yeast-sugar mixture inflates — which gas fills the balloon?",
     ["ऑक्सीजन", "नाइट्रोजन", "कार्बन डाइऑक्साइड", "हाइड्रोजन"],
     ["Oxygen", "Nitrogen", "Carbon dioxide", "Hydrogen"],
     2,
     "खमीर शक्कर का अवायवीय विघटन करते हुए CO2 छोड़ता है — इसी गैस के दबाव से गुब्बारा फूलता जाता है।",
     "Yeast breaks down sugar anaerobically releasing CO2 — the pressure of this gas inflates the balloon."),

    ("aerobic-anaerobic-respiration", "medium",
     "दो विद्यार्थियों की बहस: A कहता है श्वसन दिन में होता है, B कहता है दिन-रात दोनों। निर्णय दीजिए।",
     "Two students argue: A says respiration happens by day, B says by day and night. Decide.",
     ["A सही — प्रकाश जरूरी है", "B सही — श्वसन प्रकाश से स्वतंत्र, हर कोशिका में सदैव चलता है", "दोनों गलत — श्वसन केवल रात में", "यह जीव पर निर्भर करता है"],
     ["A is right — light is necessary", "B is right — respiration is independent of light and runs in every cell round the clock", "Both wrong — respiration occurs only at night", "It depends on the organism"],
     1,
     "श्वसन जीवन-निर्वाह की निरंतर क्रिया है — प्रकाश-संश्लेषण के विपरीत यह प्रकाश माँगता नहीं; दिन-रात सभी कोशिकाओं में चलती रहती है।",
     "Respiration is a continuous life process — unlike photosynthesis it needs no light and keeps running in all cells day and night."),

    ("aerobic-anaerobic-respiration", "medium",
     "ओवन में आटा फूलकर रोटी/केक बनती है — आटे के भीतर कौन-सी कोशिकीय प्रक्रिया जिम्मेदार है?",
     "Dough rises in the oven to make bread or cake — which cellular process inside the dough is responsible?",
     ["खमीर का अवायवीय श्वसन (किण्वन) जिससे CO2 के बुलबुले बनते हैं", "आटे का प्रकाश-संश्लेषण", "गेहूँ की कोशिकाओं का वायवीय श्वसन", "पानी का वाष्पीकरण"],
     ["Anaerobic respiration (fermentation) of yeast producing CO2 bubbles", "Photosynthesis by the dough", "Aerobic respiration of wheat cells", "Evaporation of water"],
     0,
     "खमीर किण्वन में छोड़ी CO2 आटे में गैस-कोठरियाँ बनाती है — गर्मी में वे फैलकर आटा फुला देती हैं।",
     "CO2 released by yeast fermentation creates gas pockets in the dough — heat expands them and the dough rises."),

    ("aerobic-anaerobic-respiration", "hard",
     "पाइरूवेट का आगे का रास्ता किस शर्त पर तय होता है?",
     "On what condition does the further path of pyruvate get decided?",
     ["प्रकाश की उपस्थिति पर", "कोशिका में ऑक्सीजन की उपलब्धता पर", "जल की मात्रा पर", "तापमान पर कभी नहीं"],
     ["On the presence of light", "On the availability of oxygen in the cell", "On the amount of water", "Never on temperature"],
     1,
     "O2 मिले तो पाइरूवेट माइटोकॉन्ड्रिया में पूर्ण टूटता है (वायवीय); न मिले तो कोशिका-द्रव्य में एथेनॉल या लैक्टिक अम्ल बनता है (अवायवीय)।",
     "With O2, pyruvate breaks down fully in mitochondria (aerobic); without it, it turns into ethanol or lactic acid in the cytoplasm (anaerobic)."),

    ("aerobic-anaerobic-respiration", "hard",
     "निषेचन के बाद यदि मांसपेशी-कोशिका और खमीर-कोशिका दोनों ऑक्सीजन-रहित स्थिति में एक समान ग्लूकोज़ लें, तो परिणाम में मुख्य समानता और भिन्नता क्या होगी?",
     "If a muscle cell and a yeast cell take identical glucose under oxygen-free conditions, what is the main similarity and difference of the outcome?",
     ["समानता — दोनों में ऊर्जा बचती है; भिन्नता — मांसपेशी में लैक्टिक अम्ल, खमीर में एथेनॉल+CO2", "दोनों में सब कुछ समान होता है", "दोनों में कुछ नहीं होता", "खमीर में जल बनता है, मांसपेशी में CO2"],
     ["Similarity — both trap energy; difference — lactic acid in muscle, ethanol+CO2 in yeast", "Everything is identical in both", "Nothing happens in either", "Yeast makes water, muscle makes CO2"],
     0,
     "अवायवीय मार्ग का साझा सिद्धांत है — आंशिक विघटन से सीमित ऊर्जा; अंतिम उत्पाद जीव की एंजाइम-योजना से तय होता है।",
     "The shared principle of the anaerobic route is limited energy from partial breakdown; the end product is fixed by each organism's enzyme plan."),

    ("aerobic-anaerobic-respiration", "hard",
     "एक जीवाणु समूह पूर्णतः ऑक्सीजन-रहित गहरे कीचड़ में जीवित रहता है — उसकी ऊर्जा-प्राप्ति की व्यवस्था क्या बताती है?",
     "A bacterial colony survives in completely oxygen-free deep mud — what does its energy arrangement indicate?",
     ["वह प्रकाश-संश्लेषण करता है", "उसके पास ऑक्सीजन के बिना ऊर्जा निकालने की अवायवीय श्वसन-क्षमता है", "वह ऊर्जा बिना किसी प्रक्रिया के बनाता है", "वह ऊर्जा मिट्टी से सोखता है"],
     ["It photosynthesises", "It possesses anaerobic respiration — the ability to extract energy without oxygen", "It makes energy without any process", "It absorbs energy from the soil"],
     1,
     "ऑक्सीजनहीन आवास में जीवन अवायवीय श्वसन के बिना संभव नहीं — यह जीवाणु आंशिक विघटन से अपनी ऊर्जा जुटाता है।",
     "Life in an oxygen-free habitat is impossible without anaerobic respiration — this bacterium gathers energy from partial breakdown."),

    ("aerobic-anaerobic-respiration", "hard",
     "प्रयोग में खमीर + ग्लूकोज़ घोल को ऑक्सीजन-रहित बंद बोतल में रखा गया; कुछ देर बाद दबाव बढ़ा पर घोल का ताप कुछ ही बढ़ा — इससे क्या पता चलता है?",
     "Yeast + glucose solution is kept in a sealed oxygen-free bottle; pressure rises soon but temperature barely increases — what does this show?",
     ["खमीर प्रकाश-संश्लेषण कर रहा है", "अवायवीय श्वसन चल रहा है — CO2 गैस दबाव बढ़ाती है और ऊर्जा का बड़ा भाग रासायनिक बंधनों में बची रहता है, ताप में जाता ही नहीं", "ग्लूकोज़ उबाल के बिना जल रहा है", "बोतल में ऑक्सीजन बन रही है"],
     ["Yeast is photosynthesising", "Anaerobic respiration is running — CO2 raises the pressure, and most energy stays locked in chemical bonds instead of heating", "Glucose is burning without boiling", "Oxygen is forming in the bottle"],
     1,
     "बंद बोतल में दबाव-वृद्धि CO2 का प्रमाण है; ताप का न बढ़ना बताता है कि किण्वन की ऊर्जा-प्राप्ति कम है और उसका अंश उत्पादों में ही बंद रहता है।",
     "The pressure rise proves CO2; the negligible heating shows fermentation's small energy yield, most of it staying locked in the products."),
]
