# -*- coding: utf-8 -*-
"""B08 'Transportation & Circulation' — Part 2 data (50 items).
Order: blood-vessels-pressure (25), xylem-transport (25).
Tuple: (topic, difficulty, q_hi, q_en, options_hi[4], options_en[4], correct_idx, exp_hi, exp_en)
"""

PART2 = [
    # ---------------- blood-vessels-pressure (25: E8/M14/H3) ----------------
    ("blood-vessels-pressure", "easy",
     "धमनियों (arteries) रुधिर को किस दिशा में ले जाती हैं?",
     "In which direction do arteries carry blood?",
     ["हृदय की ओर", "हृदय से दूर, अंगों की ओर", "केवल नीचे की ओर", "केवल ऊपर की ओर"],
     ["Towards the heart", "Away from the heart, towards the organs", "Only downwards", "Only upwards"],
     1,
     "धमनी की परिभाषा ही यही है — हृदय से निकलने वाली वाहिकाएँ; शिराएँ हृदय की ओर लौटाती हैं।",
     "The very definition of an artery — vessels leaving the heart; veins return blood to it."),

    ("blood-vessels-pressure", "easy",
     "शिराओं (veins) का कार्य क्या है?",
     "What is the function of veins?",
     ["हृदय से रुधिर बाहर ले जाना", "रुधिर को हृदय की ओर वापस लाना", "रुधिर जमाना", "रुधिर छानना"],
     ["Taking blood out of the heart", "Bringing blood back towards the heart", "Clotting blood", "Filtering blood"],
     1,
     "शिराएँ वापसी-मार्ग हैं — अंगों से रुधिर उठाकर हृदय तक पहुँचाती हैं।",
     "Veins are the return route — they lift blood from the organs and deliver it to the heart."),

    ("blood-vessels-pressure", "easy",
     "धमनियों और शिराओं की दीवारों की तुलना में मुख्य भिन्नता क्या है?",
     "What is the main difference between the walls of arteries and veins?",
     ["धमनियों की दीवारें मोटी-प्रत्यास्थ, शिराओं की पतली", "धमनियों की दीवारें पतली, शिराओं की मोटी", "दोनों की दीवारें समान मोटी", "शिराओं में दीवार होती ही नहीं"],
     ["Artery walls are thick and elastic, vein walls thin", "Artery walls thin, vein walls thick", "Both equally thick", "Veins have no wall at all"],
     0,
     "धमनियाँ उच्च दबाव का सामना करती हैं इसलिए मोटी-लचीली बनी हैं; शिराओं में दबाव कम है, दीवार पतली।",
     "Arteries face high pressure, so they are thick and springy; veins carry low pressure and stay thin-walled."),

    ("blood-vessels-pressure", "easy",
     "शिराओं में कपाटिकाएँ (valves) किसलिए होती हैं?",
     "Why do veins contain valves?",
     ["रुधिर को तेज़ करने के लिए", "निम्न दबाव में रुधिर का उल्टा बहाव रोकने के लिए", "रुधिर छानने के लिए", "रुधिर जमाने के लिए"],
     ["To speed up the blood", "To prevent backflow of blood under low pressure", "To filter blood", "To clot blood"],
     1,
     "शिरा-रुधिर धीमा और दबाव-रहित बहता है — वाल्व उसे एकतरफा (हृदय की ओर) बनाए रखते हैं, विशेषकर पैरों में गुरुत्व के विरुद्ध।",
     "Venous blood drifts slowly with little pressure — valves keep it one-way (heartward), especially against gravity in the legs."),

    ("blood-vessels-pressure", "easy",
     "नाड़ी (pulse) सामान्यतः किस वाहिका में महसूस की जाती है?",
     "In which vessels is the pulse normally felt?",
     ["शिराओं में", "धमनियों में", "केशिकाओं में", "लसीका वाहिकाओं में"],
     ["In veins", "In arteries", "In capillaries", "In lymph vessels"],
     1,
     "हृदय के झटके से धमनी-भित्ति फैलती है — यही फैलाव कलाई/गले की उथली धमनियों पर नाड़ी बनता है।",
     "Each heart surge stretches the arterial wall — this stretch, felt in superficial arteries at wrist or neck, is the pulse."),

    ("blood-vessels-pressure", "easy",
     "शरीर की सबसे बड़ी धमनी कौन-सी है?",
     "Which is the largest artery of the body?",
     ["फुफ्फुसीय धमनी", "महाधमनी (aorta)", "कोरोनरी धमनी", "गुर्दे की धमनी"],
     ["Pulmonary artery", "The aorta", "Coronary artery", "Renal artery"],
     1,
     "बाएँ निलय से निकलने वाली महाधमनी सबसे बड़ी धमनी है — उसकी शाखाएँ संपूर्ण शरीर को रुधिर देती हैं।",
     "The aorta leaving the left ventricle is the largest artery — its branches supply the entire body."),

    ("blood-vessels-pressure", "easy",
     "शरीर की सबसे बड़ी शिरा कौन-सी है?",
     "Which is the largest vein of the body?",
     ["महाधमनी", "महाशिरा (vena cava)", "फुफ्फुसीय शिरा", "कोरोनरी शिरा"],
     ["The aorta", "The vena cava", "Pulmonary vein", "Coronary vein"],
     1,
     "महाशिरा शरीर भर से अशुद्ध रुधिर इकट्ठा करके हृदय के दाएँ अलिंद में उड़ेलती है।",
     "The vena cava collects deoxygenated blood from all over the body and pours it into the right atrium."),

    ("blood-vessels-pressure", "easy",
     "कोशिकाओं के चारों ओर जाली बुनकर रुधिर को कोशिकाओं तक पहुँचाने वाली सूक्ष्मतम वाहिकाएँ कौन-सी हैं?",
     "Which are the finest vessels that form a mesh around the cells and bring blood to them?",
     ["धमनियाँ", "शिराएँ", "केशिकाएँ (capillaries)", "महाधमनी"],
     ["Arteries", "Veins", "Capillaries", "The aorta"],
     2,
     "धमनियाँ केशिकाओं में, केशिकाएँ शिराओं में खुलती हैं — कोशिका-स्तर का सारा आदान-प्रदान केशिकाओं पर ही होता है।",
     "Arteries open into capillaries, capillaries into veins — all cell-level exchange happens at the capillaries."),

    ("blood-vessels-pressure", "medium",
     "फुफ्फुसीय धमनी (pulmonary artery) अन्य धमनियों से किस अर्थ में अपवाद है?",
     "In what sense is the pulmonary artery an exception among arteries?",
     ["वह शुद्ध रुधिर ले जाती है", "वह अशुद्ध (ऑक्सीजन-रहित) रुधिर ले जाती है — फेफड़ों की ओर", "उसमें वाल्व नहीं होता", "वह शिरा से निकलती है"],
     ["It carries oxygenated blood", "It carries deoxygenated blood — towards the lungs", "It has no valve", "It arises from a vein"],
     1,
     "धमनी होने का अर्थ 'हृदय से बाहर' है, 'शुद्ध रुधिर' नहीं — इसीलिए फुफ्फुसीय धमनी अशुद्ध रुधिर ढोते हुए भी धमनी ही है।",
     "Being an artery means 'leaving the heart', not 'oxygenated' — hence the pulmonary artery stays an artery while carrying deoxygenated blood."),

    ("blood-vessels-pressure", "medium",
     "फुफ्फुसीय शिरा (pulmonary vein) की विशेषता क्या है?",
     "What is special about the pulmonary vein?",
     ["वह अशुद्ध रुधिर लाती है", "वह शुद्ध (ऑक्सीजन-युक्त) रुधिर हृदय में लाती है — शिराओं में यह अपवाद है", "वह मस्तिष्क से निकलती है", "उसमें केवल प्लाज्मा होता है"],
     ["It brings deoxygenated blood", "It brings oxygenated blood to the heart — an exception among veins", "It leaves the brain", "It carries only plasma"],
     1,
     "शिरा होने का अर्थ 'हृदय की ओर' है — फुफ्फुसीय शिरा फेफड़ों से शुद्ध रुधिर लाती है, इसलिए शिराओं में अपवाद है।",
     "Being a vein means 'towards the heart' — the pulmonary vein brings oxygen-rich blood from lungs, the exception among veins."),

    ("blood-vessels-pressure", "medium",
     "दो धड़कनों के बीच भी धमनियों में रुधिर का प्रवाह क्यों रुकता नहीं?",
     "Why does blood flow in arteries not stop between two heartbeats?",
     ["हृदय लगातार खुला रहता है", "प्रत्यास्थ धमनी-भित्ति फैलकर सिकुड़ती है और भीतर का दबाब बनाए रखती है", "रुधिर में वाल्व होते हैं", "गुरुत्वाकर्षण खींचता है"],
     ["The heart stays open continuously", "The elastic arterial wall stretches and recoils, maintaining internal pressure", "Blood itself contains valves", "Gravity pulls it along"],
     1,
     "झटके पर भित्ति फैलती और झटके के बाद सिकुड़कर रुधिर को आगे धकेलती है — प्रत्यास्थता ही प्रवाह की सांतत्य रखती है।",
     "The wall stretches with each surge and recoils after it, pushing blood onward — elasticity keeps the flow continuous."),

    ("blood-vessels-pressure", "medium",
     "रुधिर-चाप (blood pressure) से क्या तात्पर्य है?",
     "What is meant by blood pressure?",
     ["हृदय की धड़कन की गति", "रुधिर द्वारा रुधिर-वाहिका की दीवार पर लगाया गया बल (दाब)", "रुधिर का रंग-गुण", "शिराओं की लंबाई"],
     ["The speed of the heartbeat", "The force (pressure) exerted by blood on the vessel wall", "The colour property of blood", "The length of veins"],
     1,
     "रुधिर-चाप वाहिका-भित्ति पर पड़ने वाला पार्श्व दबाव है — धमनियों में सबसे अधिक मापा जाता है।",
     "Blood pressure is the lateral push of blood on the vessel wall — measured at its highest in the arteries."),

    ("blood-vessels-pressure", "medium",
     "स्वस्थ वयस्क का सामान्य रुधिर-चाप कितना माना जाता है?",
     "What is considered the normal blood pressure of a healthy adult?",
     ["80/40 mmHg", "120/80 mmHg के आसपास", "160/100 mmHg", "200/150 mmHg"],
     ["80/40 mmHg", "About 120/80 mmHg", "160/100 mmHg", "200/150 mmHg"],
     1,
     "सिस्टोलिक ~120 और डायस्टोलिक ~80 mmHg — यही सामान्य मानक है।",
     "Systolic about 120 and diastolic about 80 mmHg — the normal standard."),

    ("blood-vessels-pressure", "medium",
     "रुधिर-चाप 120/80 में 120 और 80 क्रमशः क्या दर्शाते हैं?",
     "In a BP of 120/80, what do the 120 and the 80 respectively denote?",
     ["शिरा-दाब और धमनी-दाब", "संकुचन-चरण का दाब (systolic) और विश्राम-चरण का दाब (diastolic)", "हृदय की दर और श्वसन की दर", "RBC और WBC संख्या"],
     ["Vein pressure and artery pressure", "Pressure in the contraction phase (systolic) and in the relaxation phase (diastolic)", "Heart rate and breathing rate", "RBC and WBC counts"],
     1,
     "संकुचन में दाब चरम पर (~120) और विश्राम में निम्नतम (~80) पहुँचता है — यही दो अंक हैं।",
     "Pressure peaks (~120) during contraction and dips lowest (~80) during relaxation — those are the two numbers."),

    ("blood-vessels-pressure", "medium",
     "रुधिर-चाप मापने की युक्ति (instrument) क्या कहलाती है?",
     "What is the instrument for measuring blood pressure called?",
     ["स्फिग्मोमैनोमीटर", "थर्मामीटर", "बैरोमीटर", "स्पाइरोमीटर"],
     ["Sphygmomanometer", "Thermometer", "Barometer", "Spirometer"],
     0,
     "स्फिग्मोमैनोमीटर की पट्टी बाँह की धमनी को दबाकर संकुचन-विश्राम दाब पढ़ता है।",
     "The sphygmomanometer cuff compresses the arm's artery to read the contraction and relaxation pressures."),

    ("blood-vessels-pressure", "medium",
     "धमनियों, केशिकाओं और शिराओं में रुधिर-दाब का क्रम कैसा होता है?",
     "What is the order of blood pressure in arteries, capillaries and veins?",
     ["धमनी > केशिका > शिरा", "शिरा > केशिका > धमनी", "तीनों में समान", "केशिका > धमनी > शिरा"],
     ["Artery > capillary > vein", "Vein > capillary > artery", "Equal in all three", "Capillary > artery > vein"],
     0,
     "हृदय के पास दाब सर्वाधिक है और वाहिकाओं की शृंखला में आगे बढ़ते ही घटता जाता है — शिराओं तक लगभग शून्य।",
     "Pressure is highest near the heart and falls stepwise along the vessel chain — nearly zero by the veins."),

    ("blood-vessels-pressure", "medium",
     "धमनियों में वाल्व नहीं होते जबकि शिराओं में होते हैं — कारण?",
     "Arteries lack valves while veins have them — why?",
     ["धमनियाँ छोटी होती हैं", "धमनियों का उच्च दबावी रुधिर स्वयं एकदिश रहता है; शिराओं का निम्न-दाब रुधिर वापस झुकने का खतरा रखता है", "धमनियों में रुधिर जमता नहीं", "शिराएँ हृदय से निकलती हैं"],
     ["Arteries are short", "The high-pressure arterial flow stays one-way by itself; low-pressure venous blood risks slipping back", "Arterial blood never clots", "Veins leave the heart"],
     1,
     "दबान का ढाल बहाव की दिशा बनाए रखता है — धमनी में वाल्व की जरूरत नहीं; शिरा में गुरुत्व के विरुद्ध धकेलने के लिए वाल्व आवश्यक।",
     "A steep pressure gradient keeps arterial flow one-way — no valves needed; veins need valves to push against gravity."),

    ("blood-vessels-pressure", "medium",
     "धमनी और शिरा की दीवार तथा ल्यूमेन (lumen) के आधार पर सही सुमेलन कौन-सा है?",
     "Which is the correct matching of artery and vein by wall and lumen?",
     ["धमनी — मोटी दीवार, संकरा ल्यूमेन; शिरा — पतली दीवार, चौड़ा ल्यूमेन", "धमनी — पतली दीवार, चौड़ा ल्यूमेन; शिरा — मोटी दीवार, संकरा ल्यूमेन", "दोनों — मोटी दीवार, संकरा ल्यूमेन", "दोनों — पतली दीवार, चौड़ा ल्यूमेन"],
     ["Artery — thick wall, narrow lumen; vein — thin wall, wide lumen", "Artery — thin wall, wide lumen; vein — thick wall, narrow lumen", "Both — thick wall, narrow lumen", "Both — thin wall, wide lumen"],
     0,
     "उच्च दबाव सहने के लिए धमनी की मोटी दीवार और भीतर संकरा मार्ग; निम्न दाब की शिरा पतली दीवार और खुले ल्यूमेन वाली।",
     "The artery has a thick wall and narrow bore to bear high pressure; the low-pressure vein has a thin wall and an open lumen."),

    ("blood-vessels-pressure", "medium",
     "केशिकाओं में रुधिर का वेग सबसे धीमा क्यों होता है?",
     "Why is the velocity of blood slowest in the capillaries?",
     ["केशिकाएँ अवरोधक हैं", "विशाल केशिका-जाल में रुधिर फैल जाता है — धीमा प्रवाह ही आदान-प्रदान को संभव बनाता है", "हृदय वहाँ नहीं पहुँचता", "रुधिर वहाँ जम जाता है"],
     ["Capillaries are blockers", "Blood spreads across a vast capillary network — the slow flow is what makes exchange possible", "The heart does not reach there", "Blood clots there"],
     1,
     "कुल केशिका-छेद का क्षेत्रफल बहुत बड़ा है — वही रुधिर फैलने से गति गिरती है और कोशिकाओं के साथ समय-सापेक्ष विनिमय हो पाता है।",
     "The total capillary cross-section is huge — spreading out slows the flow, giving time for exchange with cells."),

    ("blood-vessels-pressure", "medium",
     "महाशिरा (vena cava) रुधिर को कहाँ उड़ेलती है?",
     "Where does the vena cava pour its blood?",
     ["बाएँ अलिंद में", "दाएँ अलिंद में", "बाएँ निलय में", "फेफड़ों में सीधे"],
     ["Into the left atrium", "Into the right atrium", "Into the left ventricle", "Directly into the lungs"],
     1,
     "शरीर भर का अशुद्ध रुधिर महाशिरा से दाएँ अलिंद में आता है — आगे का रास्ता फुफ्फुसीय धमनी का है।",
     "The body's deoxygenated blood arrives via the vena cava into the right atrium — the pulmonary artery lies ahead."),

    ("blood-vessels-pressure", "medium",
     "नाड़ी गिनती से हृदय-दर का अनुमान क्यों लग जाता है?",
     "Why can the heart rate be estimated by counting the pulse?",
     ["दोनों का कोई संबंध नहीं", "हृदय का प्रत्येक संकुचन धमनी-भित्ति में एक लहर भेजता है — एक धड़कन = एक नाड़ी-स्पंद", "नाड़ी शिराओं में चलती है", "नाड़ी दिमाग बनाता है"],
     ["The two are unrelated", "Each heart contraction sends one wave through the arterial wall — one beat = one pulse throb", "The pulse runs in veins", "The brain makes the pulse"],
     1,
     "धमनी-स्पंद हृदय-संकुचन की ही बाहरी प्रतिध्वनि है — इसी से कलाई पर बराबर संख्या मिलती है।",
     "The arterial throb is the outer echo of each contraction — the wrist count matches the heart count."),

    ("blood-vessels-pressure", "medium",
     "क्या सभी धमनियाँ शुद्ध और सभी शिराएँ अशुद्ध रुधिर ढोती हैं?",
     "Do all arteries carry oxygenated and all veins deoxygenated blood?",
     ["हाँ, सदैव", "नहीं — फुफ्फुसीय धमनी अशुद्ध और फुफ्फुसीय शिरा शुद्ध रुधिर ढोती है; दिशा ही वर्गीकरण का आधार है", "केवल मनुष्य में", "केवल पौधों में"],
     ["Yes, always", "No — the pulmonary artery carries deoxygenated and the pulmonary vein oxygenated blood; direction is the basis of classification", "Only in humans", "Only in plants"],
     1,
     "धमनी/शिरा का निर्धारण रुधिर की शुद्धता से नहीं, हृदय से बाहर/भीतर की दिशा से होता है।",
     "Artery versus vein is settled not by oxygen load but by direction — out of or into the heart."),

    ("blood-vessels-pressure", "hard",
     "धमनी शरीर में गहराई में (deep) रखते हुए बनी हैं — इसकी व्यावहारिक रक्षा-सार्थकता क्या है?",
     "Arteries mostly run deep in the body — what protective significance does this have?",
     ["गहराई में गर्मी मिलती है", "चोट-कट से उच्च-दाब वाली धमनियों की रक्षा होती है — उनका कटना भारी रुधिर-हानि का कारण होगा", "हड्डियाँ उन्हें सहारा देती हैं", "उनकी लंबाई घटती है"],
     ["They get warmth at depth", "High-pressure arteries stay safe from cuts — an arterial cut would cause heavy blood loss", "Bones support them", "Their length reduces"],
     1,
     "उच्च दबाव की धमनी कटने पर रुधिर फव्वारे जैसा बहता है — गहरी स्थिति प्रकृति की सुरक्षा-योजना है।",
     "A cut high-pressure artery spurts blood — the deep placement is nature's safety plan."),

    ("blood-vessels-pressure", "hard",
     "mmHg में मापी जाने वाली इकाई वास्तव में क्या दर्शाती है?",
     "What does the measuring unit mmHg actually represent?",
     ["पारे के मिलीमीटर स्तंभ की ऊँचाई जितना दाब", "रुधिर की मिलीमीटर मात्रा", "हृदय की मिलीमीटर गति", "मिनट में मिलीग्राम प्रवाह"],
     ["Pressure equal to the height of a millimetre column of mercury", "Millilitres of blood", "Millimetre speed of the heart", "Milligram flow per minute"],
     0,
     "दाब को पारे-स्तंभ की संतुलन-ऊँचाई से तुलना कर पढ़ा जाता है — 120 mmHg यानी पारे के 120 मिमी स्तंभ जितना बल।",
     "Pressure is read against a balancing mercury column — 120 mmHg means force equal to a 120 mm column of mercury."),

    ("blood-vessels-pressure", "hard",
     "यदि किसी की डायस्टोलिक दाब सामान्य से लगातार ऊँचा रहे तो हृदय-निलयों पर दीर्घकालिक प्रभाव क्या होगा?",
     "If the diastolic pressure stays persistently above normal, what is the long-term effect on the ventricles?",
     ["निलय सिकुड़ जाते हैं", "विश्राम-चरण कमजोर पड़ता है — दीवारों पर निरंतर अतिरिक्त बोझ पड़ता है और पेशी थकती है", "कोई प्रभाव नहीं", "निलयों की संख्या बदल जाती है"],
     ["The ventricles shrink", "The relaxation phase weakens — the walls bear a constant extra load and the muscle tires", "No effect", "The number of ventricles changes"],
     1,
     "डायस्टोल में हृदय को आराम मिलता है; बढ़ा हुआ आधार-दाब विश्राम कम करता है — पंप को स्थायी रूप से अधिक मेहनत करनी पड़ती है।",
     "Diastole is the heart's rest; a raised baseline pressure cuts that rest — the pump toils extra round the clock."),

    # ---------------- xylem-transport (25: E8/M14/H3) ----------------
    ("xylem-transport", "easy",
     "पौधे में जल और खनिज लवण ऊपर किस ऊतक द्वारा जाते हैं?",
     "Through which tissue do water and mineral salts move upward in a plant?",
     ["फ्लोएम", "जाइलम", "पर्वसंधि", "कॉर्क"],
     ["Phloem", "Xylem", "Node", "Cork"],
     1,
     "जाइलम जल-चालन ऊतक है — जड़ से ऊपर जल और घुले खनिज इसी की नलियों से चढ़ते हैं।",
     "Xylem is the water-conducting tissue — water and dissolved minerals climb through its tubes from the root."),

    ("xylem-transport", "easy",
     "वाष्पोत्सर्जन (transpiration) से क्या तात्पर्य है?",
     "What is meant by transpiration?",
     ["जड़ों द्वारा जल का अवशोषण", "पत्तियों से जल का वाष्प रूप में बाहर निकलना", "फ्लोएम में भोजन का बहना", "प्रकाश से भोजन बनना"],
     ["Absorption of water by roots", "Escape of water as vapour from the leaves", "Flow of food in phloem", "Making food with light"],
     1,
     "पत्तियों के रंध्रों से लगातार जल-वाष्प का हानि होना ही वाष्पोत्सर्जन है।",
     "The steady loss of water vapour through the leaf stomata is transpiration."),

    ("xylem-transport", "easy",
     "मृदा-जल को ऊपर धकेलने वाला हृदय-निर्मित दबाव किस भाग से विकसित होता है?",
     "The pressure that pushes soil water upward develops in which part?",
     ["पत्तियों में", "जड़ की कोशिकाओं में (मूल-दाब)", "तने की छाल में", "फूलों में"],
     ["In the leaves", "In the root's cells (root pressure)", "In the bark of the stem", "In the flowers"],
     1,
     "जड़-कोशिकाओं का लवण-संचय पानी को भीतर खींचकर जाइलम में धकेलता है — यही मूल-दाब है।",
     "The root cells' salt buildup draws water in and pushes it up the xylem — this is root pressure."),

    ("xylem-transport", "easy",
     "पत्तियों से वाष्पीकरण द्वारा उत्पन्न खिंचाव को क्या कहते हैं?",
     "What is the pull created by evaporation from the leaves called?",
     ["मूल-दाब", "वाष्पोत्सर्जन खिंचाव (transpiration pull)", "स्वादु-खिंचाव", "परासरण-दाब"],
     ["Root pressure", "Transpiration pull", "Sweet pull", "Osmotic pressure"],
     1,
     "पत्ती-कोशिकाओं से वाष्प बनने पर जाइलम-जल पर सोख-खिंचाव पड़ता है — यही बल ऊपर खींचता है।",
     "As vapour escapes leaf cells, a suction falls on the xylem water — this force pulls the column up."),

    ("xylem-transport", "easy",
     "रंध्र (stomata) खुलने पर वाष्पोत्सर्जन की दर का क्या होता है?",
     "What happens to the rate of transpiration when stomata open?",
     ["घटती है", "बढ़ जाती है", "रुक जाती है", "कोई प्रभाव नहीं"],
     ["It decreases", "It increases", "It stops", "No effect"],
     1,
     "खुले रंध्र जल-वाष्प को मुक्त निकास देते हैं — वाष्पोत्सर्जन तेज़ हो जाता है।",
     "Open stomata give water vapour a free exit — transpiration quickens."),

    ("xylem-transport", "easy",
     "पौधा जल मुख्यतः किन संरचनाओं द्वारा मृदा से सोखता है?",
     "Through which structures does a plant mainly absorb water from the soil?",
     ["पत्तियों द्वारा", "मूल-रोमों (root hairs) द्वारा", "तने की त्वचा द्वारा", "फूलों द्वारा"],
     ["Through leaves", "Through root hairs", "Through the stem's skin", "Through flowers"],
     1,
     "जड़ के निकले रोम मिट्टी के कणों से चिपककर जल की फिल्म सोख लेते हैं — जल-ग्रहण का मुख्य द्वार यही।",
     "Hairs jutting from the root hug soil particles and soak the water film — the main gateway of intake."),

    ("xylem-transport", "easy",
     "जाइलम में ऊपर उठने वाला 'रस' (sap) वास्तव में क्या होता है?",
     "What actually is the 'sap' that rises in the xylem?",
     ["शुद्ध जल", "जल में घुले खनिज लवणों का घोल", "ग्लूकोज़ का घोल", "वायु-कण"],
     ["Pure water", "A solution of mineral salts dissolved in water", "A glucose solution", "Air bubbles"],
     1,
     "जड़ से पत्ती तक जाइलम-रस = जल + घुले खनिज — दोनों साथ यात्रा करते हैं।",
     "From root to leaf the xylem sap = water + dissolved minerals — both travel together."),

    ("xylem-transport", "easy",
     "जाइलम-जल का प्रवाह किस दिशा में मुख्यतः होता है?",
     "In which direction does xylem water mainly flow?",
     ["नीचे की ओर", "ऊपर की ओर (ऊर्ध्वाधर)", "दोनों दिशाओं में समान", "क्षैतिज ही"],
     ["Downwards", "Upwards (vertical)", "Equally in both directions", "Only horizontal"],
     1,
     "जाइलम का परिवहन एकदिशीय — जड़ों से ऊपर की ओर; द्विदिश परिवहन फ्लोएम का गुण है।",
     "Xylem transport is one-way — upward from the roots; two-way transport is phloem's trait."),

    ("xylem-transport", "medium",
     "उच्च वृक्षों में जल चढ़ाने की मुख्य शक्ति कौन-सी है?",
     "Which is the main force lifting water in tall trees?",
     ["मूल-दाब", "वाष्पोत्सर्जन खिंचाव", "पत्तियों का वजन", "वायु-दाब"],
     ["Root pressure", "Transpiration pull", "The weight of leaves", "Air pressure"],
     1,
     "मूल-दाब की पहुँच सीमित है; ऊँचाई तक जल वाष्पोत्सर्जन-खिंचाव ही खींचकर ले जाता है।",
     "Root pressure has limited reach; transpiration pull is what hauls water to the top."),

    ("xylem-transport", "medium",
     "मूल-दाब अकेला ऊँचे वृक्षों तक जल क्यों नहीं पहुँचा पाता?",
     "Why can root pressure alone not deliver water to tall trees?",
     ["वह रात में ही बनता है", "उसका धकेलन-बल कमजोर है — कुछ मीटर की सीमित ऊँचाई तक ही जल को धकेल सकता है", "जड़ें छोटी होती हैं", "जाइलम रुका रहता है"],
     ["It develops only at night", "Its push is weak — it can shove water only up to a few metres", "The roots are short", "The xylem stays blocked"],
     1,
     "मूल-दाब असर्व-पर्याप्त बल है — गगनचुंबी वृक्षों के लिए खिंचाव-बल (वाष्पोत्सर्जन) ही पर्याप्त है।",
     "Root pressure is an all-insufficient push — for sky-high trees the pull of transpiration alone suffices."),

    ("xylem-transport", "medium",
     "मूल-दाब का प्रभाव कब सबसे स्पष्ट दिखता है?",
     "When is the effect of root pressure most visible?",
     ["दोपहर की तेज़ धूप में", "रात में या आर्द्र दिनों में जब वाष्पोत्सर्जन कम हो", "शुष्क गर्मी में", "पतझड़ में"],
     ["In strong afternoon sun", "At night or on humid days when transpiration is low", "In dry summer", "In autumn"],
     1,
     "वाष्पोत्सर्जन धीमा होने पर मूल-दाब का धक्का ही प्रमुख हो जाता है — जल-बूँदें निकलना (गटेशन) दिखता है।",
     "When transpiration slows, root pressure's push becomes dominant — droplets oozing out (guttation) can be seen."),

    ("xylem-transport", "medium",
     "जड़ से पत्ती तक जल-स्तंभ टूटा क्यों नहीं रहता?",
     "Why does the water column from root to leaf never break?",
     ["जल चिपचिपा होता है", "जल-अणु परस्पर आकर्षण (cohesion) से अखंड शृंखला बनाए रखते हैं और जाइलम-नलियाँ संकरी होती हैं", "वायु जाइलम में नहीं जाती", "पत्तियाँ खींचती नहीं"],
     ["Water is sticky", "Water molecules keep an unbroken chain by mutual attraction (cohesion) and xylem tubes are narrow", "Air never enters xylem", "Leaves do not pull"],
     1,
     "अणु-आकर्षण से जल तंतु की तरह जकड़ा रहता है — संकरी नलियों में यह अखंडता ही खिंचाव सह लेती है।",
     "Molecular attraction keeps water strung like a wire — in narrow tubes this intactness bears the pull."),

    ("xylem-transport", "medium",
     "पत्ती की मध्यपटल-कोशिकाओं (mesophyll) से वाष्प बनने पर जाइलम पर क्या प्रभाव पड़ता है?",
     "What happens to the xylem when vapour forms on the leaf's mesophyll cells?",
     ["जाइलम फैल जाता है", "कोशिकाओं का जल-घनत्व घटता है — जाइलम से जल खिंचकर सोखा जाता है, शृंखला ऊपर चढ़ती है", "जाइलम बंद हो जाता है", "कुछ नहीं होता"],
     ["The xylem expands", "The cells' water density falls — water is drawn from the xylem, and the chain climbs", "The xylem closes", "Nothing happens"],
     1,
     "वाष्पीकरण-सोख प्रभावी शृंखलीय प्रतिक्रिया है — पत्ती की कोशिका से तना, तने से जड़ तक खिंचाव चलता है।",
     "Evaporation-suction is a chain reaction — from leaf cell to stem to root, the pull travels down."),

    ("xylem-transport", "medium",
     "वाष्पोत्सर्जन का पौधे के लिए शीतलन-लाभ कैसे है?",
     "How does transpiration benefit the plant by cooling?",
     ["वाष्प बनते समय ऊष्मा अवशोषित होती है — पौधे की गर्मी बाहर निकलती है", "पानी ठंडा होता है", "पत्तियाँ काँपती हैं", "मिट्टी ठंडी होती है"],
     ["Heat is absorbed as vapour forms — the plant's warmth escapes", "The water cools down", "The leaves shiver", "The soil cools"],
     0,
     "वाष्पीकरण की गुप्त ऊष्मा पत्ती से ली जाती है — यही स्वेद-निष्कासन पौधे को धूप में भी ठंडा रखता है।",
     "Vapourisation's latent heat is drawn from the leaf — this sweating keeps the plant cool even in sun."),

    ("xylem-transport", "medium",
     "खनिज लवण जड़ से पत्तियों तक कैसे पहुँचते हैं?",
     "How do mineral salts reach the leaves from the roots?",
     ["फ्लोएम में भोजन के साथ", "जाइलम के जल-प्रवाह में घुलकर — जल-धारा के साथ सवार", "वायु में फैलकर", "लसीका द्वारा"],
     ["With food in the phloem", "Dissolved in the xylem water stream — riding the water current", "Diffusing through air", "By lymph"],
     1,
     "जड़ के अवशोषित लवण जाइलम-जल में घुल जाते हैं — वाष्पोत्सर्जन-खिंचाव जल के साथ उन्हें भी ऊपर ले जाता है।",
     "Salts absorbed by the root dissolve into the xylem stream — transpiration pull lifts them along with the water."),

    ("xylem-transport", "medium",
     "वायु में आर्द्रता (humidity) बढ़ने पर वाष्पोत्सर्जन की दर का क्या होगा?",
     "What happens to the rate of transpiration when atmospheric humidity rises?",
     ["बढ़ेगी", "घटेगी", "अपरिवर्तित रहेगी", "पहले बढ़ेगी फिर घटेगी"],
     ["It will rise", "It will fall", "It stays unchanged", "It rises then falls"],
     1,
     "बाहर की हवा जल-वाष्प से भरी होने पर भीतर-बाहर का अंतर घट जाता है — वाष्प निकलना कठिन हो जाता है।",
     "When outside air is already vapour-laden, the inside-outside gap narrows — the vapour struggles to leave."),

    ("xylem-transport", "medium",
     "तापमान बढ़ने पर वाष्पोत्सर्जन कैसा होगा?",
     "How does transpiration change with rising temperature?",
     ["घटेगा", "बढ़ेगा — वाष्पीकरण तेज़ हो जाता है", "रुक जाएगा", "उल्टा होगा"],
     ["It falls", "It rises — evaporation speeds up", "It stops", "It reverses"],
     1,
     "गर्मी जल-अणुओं की गति बढ़ाती है — वाष्प बनना और निकलना दोनों तेज़ हो जाते हैं।",
     "Heat quickens water molecules — both vapour formation and escape accelerate."),

    ("xylem-transport", "medium",
     "तेज़ हवा (wind) का वाष्पोत्सर्जन पर क्या प्रभाव है?",
     "What effect does strong wind have on transpiration?",
     ["घटाती है", "बढ़ाती है — पत्ती के आसपास की आर्द्र वायु-परत हटा देती है", "कोई प्रभाव नहीं", "रुकवा देती है"],
     ["It lowers it", "It raises it — sweeping away the humid air layer around the leaf", "No effect", "It stops it"],
     1,
     "हवा पत्ती के पास की संतृप्त वायु हटाकर ताजा शुष्क वायु लाती है — वाष्प-प्रवणता बढ़ जाती है।",
     "Wind replaces the saturated air near the leaf with fresh dry air — the vapour gradient steepens."),

    ("xylem-transport", "medium",
     "जब वाष्पोत्सर्जन की दर जल-अवशोषण की दर से अधिक हो जाए तो पौधे में क्या दिखता है?",
     "What is seen in a plant when the rate of transpiration exceeds the rate of water absorption?",
     ["पौधा तेज़ बढ़ता है", "पौधा मुरझाता (wilting) है — कोशिकाएँ जल खोकर शिथिल पड़ जाती हैं", "फूल खिलते हैं", "कुछ नहीं होता"],
     ["The plant grows fast", "The plant wilts — cells lose water and go limp", "Flowers bloom", "Nothing happens"],
     1,
     "घाटे का जल-हिसाब कोशिकाओं की तुरगिता (turgidity) गिरा देता है — पत्तियाँ-तना झुलने लगते हैं।",
     "A negative water balance drains cell turgidity — leaves and stem droop."),

    ("xylem-transport", "medium",
     "प्रकाश की उपस्थिति में वाष्पोत्सर्जन बढ़ने का माध्यम क्या है?",
     "By what medium does light increase transpiration?",
     ["प्रकाश जल खींचता है", "प्रकाश में रंध्र खुलते हैं — खुला द्वार अधिक वाष्प निकालता है", "प्रकाश से जल गर्म नहीं होता", "प्रकाश पत्ती मोटा करता है"],
     ["Light pulls water", "Stomata open in light — the open gate lets more vapour out", "Light does not warm water", "Light thickens the leaf"],
     1,
     "रंध्र प्रकाश-नियंत्रित द्वार हैं — दिन में खुलने से वाष्प-निकास और तद्द्वारा खिंचाव बढ़ता है।",
     "Stomata are light-governed gates — opening by day raises vapour exit and hence the pull."),

    ("xylem-transport", "medium",
     "जड़ों द्वारा सोखे गए जल का अधिकांश भाग पौधे में कहाँ जाता है?",
     "Where does most of the water absorbed by the roots go in the plant?",
     ["प्रकाश-संश्लेषण में सब समाहित", "अधिकांश (लगभग 90%+) वाष्पोत्सर्जन से वाष्प बनकर बाहर — प्रकाश-संश्लेषण में बहुत छोटा अंश", "फ्लोएम में संचित", "बीज में जमा"],
     ["All consumed in photosynthesis", "Most (over ~90%) leaves as vapour via transpiration — only a tiny share enters photosynthesis", "Stored in phloem", "Saved in seeds"],
     1,
     "जल-बजट का सच: सोखा जल लगभग पूरा वाष्पोत्सर्जन का माध्यम बनता है; भोजन-निर्माण में अल्प अंश ही प्रयुक्त होता है।",
     "The water budget's truth: almost all absorbed water serves as the vehicle of transpiration; a sliver feeds food-making."),

    ("xylem-transport", "hard",
     "जाइलम-नलिकाओं का संकरा होना अखंड जल-स्तंभ के लिए क्यों निर्णायक है?",
     "Why is the narrowness of xylem tubes decisive for the unbroken water column?",
     ["संकरी नली में जल जल्दी बहता है", "संकरे बोर में अणु-आकर्षण वाष्प के छोटे बुलबुले भी घोल देता है — स्तंभ टूटता नहीं", "संकरी नली में वायु नहीं जाती", "संकरी नली हल्की होती है"],
     ["Water flows faster in narrow tubes", "In a narrow bore, molecular attraction dissolves even tiny vapour bubbles — the column does not break", "Air cannot enter narrow tubes", "Narrow tubes are light"],
     1,
     "केशिकता-प्रभाव: संकरी नलियों में जल-आकर्षण इतना प्रबल होता है कि बुलबुले घुल जाते हैं और स्तंभ की सांतत्य बनी रहती है।",
     "Capillarity: in narrow tubes water attraction is so strong that bubbles dissolve and the column's continuity survives."),

    ("xylem-transport", "hard",
     "एक पौधे की शाखा पर पारदर्शी पॉलीथीन थैली बाँधी गई; कुछ घंटों में थैली के भीतर बूँदें जमा हो गईं। यह प्रयोग किसका प्रमाण है?",
     "A transparent polythene bag is tied on a branch; hours later droplets collect inside. What does this experiment prove?",
     ["पौधे का श्वसन", "जल-वाष्प निकलकर जमा हुआ — वाष्पोत्सर्जन का सीधा प्रमाण", "प्रकाश-संश्लेषण", "मूल-दाब"],
     ["The plant's respiration", "Water vapour escaped and condensed — direct proof of transpiration", "Photosynthesis", "Root pressure"],
     1,
     "थैली की ठंडी सतह पर निकली वाष्प संघनित होकर बूँदें बनती है — वाष्पोत्सर्जन का सरल प्रायोगिक प्रमाण।",
     "On the bag's cool surface the escaping vapour condenses into droplets — a simple experimental proof of transpiration."),

    ("xylem-transport", "hard",
     "निर्जल कोबाल्ट-क्लोराइड कागज पत्ती पर चिपकाने से गुलाबी हो जाता है — इससे क्या निष्कर्ष निकलता है?",
     "Anhydrous cobalt-chloride paper stuck on a leaf turns pink — what is concluded?",
     ["पत्ती ऑक्सीजन छोड़ती है", "पत्ती सतह से जल-वाष्प निकला — वाष्पोत्सर्जन हो रहा है", "पत्ती गर्म है", "पत्ती भोजन बना रही है"],
     ["The leaf releases oxygen", "Water vapour escaped the leaf surface — transpiration is occurring", "The leaf is warm", "The leaf is making food"],
     1,
     "निर्जल कोबाल्ट-क्लोराइड नीला होता है और जल मिलते ही गुलाबी — रंग-परिवर्तन जल-वाष्प का सुनिश्चित संकेतक है।",
     "Anhydrous cobalt chloride is blue and turns pink on meeting water — the colour change is a sure indicator of water vapour."),

    ("xylem-transport", "hard",
     "तीव्र दोपहर में पौधे अपने रंध्र आंशिक रूप से बंद कर लेते हैं — इसका परिवहन-परिणाम क्या होता है?",
     "At intense noon, plants partially close their stomata — what is the transport consequence?",
     ["जाइलम-प्रवाह पूर्णतः बंद", "जल-हानि का नियंत्रण — वाष्पोत्सर्जन-खिंचाव घटता है, जल-संतुलन बचाया जाता है", "मूल-दाब समाप्त हो जाता है", "फ्लोएम उल्टा चलता है"],
     ["Xylem flow stops fully", "Water loss is checked — the transpiration pull eases and the water balance is saved", "Root pressure vanishes", "Phloem reverses"],
     1,
     "रंध्र-आंशिक-बंदन पौधे का जल-संरक्षण उपाय है — अति-वाष्पोत्सर्जन से बचने के लिए द्वार थोड़ा मुंद जाता है।",
     "Partial stomatal closure is the plant's water-saving device — the gate narrows a bit to dodge excessive transpiration."),
]
