# -*- coding: utf-8 -*-
"""B08 'Transportation & Circulation' — Part 3 data (35 items).
Order: double-circulation-lymph (20), phloem-translocation (15).
Tuple: (topic, difficulty, q_hi, q_en, options_hi[4], options_en[4], correct_idx, exp_hi, exp_en)
"""

PART3 = [
    # ---------------- double-circulation-lymph (20: E7/M11/H2) ----------------
    ("double-circulation-lymph", "easy",
     "मानव में दोहरा परिसंचरण (double circulation) किसे कहते हैं?",
     "What is called double circulation in humans?",
     ["रुधिर का शरीर में दो बार फैलना", "रुधिर का पूर्ण चक्र में हृदय से दो बार गुजरना — एक बार फेफड़ों के लिए, एक बार शरीर के लिए", "हृदय के दो होना", "रुधिर का दो रंग का होना"],
     ["Blood spreading twice in the body", "Blood passing through the heart twice per complete circuit — once for the lungs, once for the body", "The heart being two in number", "Blood having two colours"],
     1,
     "फुफ्फुसीय चक्र + कायिक चक्र — एक ही चक्र में हृदय दो बार पंप करता है, इसीलिए दोहरा परिसंचरण।",
     "Pulmonary circuit + systemic circuit — the heart pumps twice in one round trip, hence double circulation."),

    ("double-circulation-lymph", "easy",
     "फुफ्फुसीय परिसंचरण (pulmonary circulation) में रुधिर कहाँ से कहाँ जाता है?",
     "In pulmonary circulation, blood travels from where to where?",
     ["शरीर से हृदय तक", "हृदय के दाएँ भाग से फेफड़ों तक और वापस हृदय के बाएँ भाग तक", "हृदय से सिर तक", "फेफड़ों से पेट तक"],
     ["From the body to the heart", "From the right side of the heart to the lungs and back to the left side of the heart", "From the heart to the head", "From the lungs to the stomach"],
     1,
     "दाएँ निलय → फुफ्फुसीय धमनी → फेफड़े → फुफ्फुसीय शिरा → बायाँ अलिंद — यही फुफ्फुसीय लूप है।",
     "Right ventricle → pulmonary artery → lungs → pulmonary vein → left atrium — that is the pulmonary loop."),

    ("double-circulation-lymph", "easy",
     "कायिक परिसंचरण (systemic circulation) का मार्ग क्या है?",
     "What is the route of systemic circulation?",
     ["हृदय के बाएँ भाग से शरीर भर में और वापस हृदय के दाएँ भाग तक", "फेफड़ों से फेफड़ों तक", "यकृत से यकृत तक", "गुर्दे से मूत्राशय तक"],
     ["From the left side of the heart to the whole body and back to the right side of the heart", "Lungs to lungs", "Liver to liver", "Kidney to bladder"],
     0,
     "बायाँ निलय → महाधमनी → शरीर → महाशिरा → दायाँ अलिंद — शरीर-सेवा वाला यह लूप कायिक परिसंचरण है।",
     "Left ventricle → aorta → body → vena cava → right atrium — this body-serving loop is systemic circulation."),

    ("double-circulation-lymph", "easy",
     "हृदय के दाएँ और बाएँ भागों के बीच पट (septum) का दोहरे परिसंचरण में क्या कार्य है?",
     "What is the septum's role in double circulation?",
     ["रुधिर को गर्म रखता है", "शुद्ध-अशुद्ध रुधिर के मिश्रण को रोकता है — दोनों पंप-प्रणालियाँ अलग-अलग शुद्धता बनाए रखती हैं", "धड़कन गिनता है", "रुधिर जमाता है"],
     ["It keeps blood warm", "It prevents mixing of oxygenated and deoxygenated blood — the two pump systems keep separate purity levels", "It counts beats", "It clots blood"],
     1,
     "पट दीवार के रूप में दोनों पक्षों को बाँटता है — न मिलने से ऑक्सीजन-स्तर बना रहता है।",
     "As a wall the septum splits the two sides — no mixing means oxygen levels stay put."),

    ("double-circulation-lymph", "easy",
     "लसीका (lymph) कैसा द्रव है?",
     "What kind of fluid is lymph?",
     ["लाल रंग का गाढ़ा", "रंगहीन (पीलापन-लेस) द्रव जो कोशिकाओं के बीच बहता है", "नीला", "हरा"],
     ["Red and thick", "A colourless (straw-tinted) fluid flowing between the cells", "Blue", "Green"],
     1,
     "लसीका = रुधिर का वह जल-भाग जो केशिकाओं से बाहर निकलकर कोशिकाओं के बीच घूमता है — रंगहीन, कणिका-रहित।",
     "Lymph = the watery part of blood that has left the capillaries to wander between cells — colourless, cell-free."),

    ("double-circulation-lymph", "easy",
     "लसीका का निर्माण कहाँ होता है?",
     "Where is lymph formed?",
     ["हृदय में", "केशिकाओं से रिसकर बने ऊतक-द्रव (tissue fluid) से", "फेफड़ों में", "यकृत में"],
     ["In the heart", "From the tissue fluid that seeps out of capillaries", "In the lungs", "In the liver"],
     1,
     "केशिका-दीवार से प्लाज्मा का छनना ही ऊतक-द्रव और फिर लसीका बनता है।",
     "The seeping of plasma through capillary walls becomes tissue fluid and then lymph."),

    ("double-circulation-lymph", "easy",
     "लसीका-तंत्र अपना द्रव अंततः कहाँ लौटाता है?",
     "Where does the lymphatic system finally return its fluid?",
     ["मूत्र में", "रुधिर-प्रवाह में (शिराओं के माध्यम से हृदय की ओर)", "त्वचा पर", "फेफड़ों में"],
     ["Into urine", "Into the bloodstream (via veins, towards the heart)", "Onto the skin", "Into the lungs"],
     1,
     "लसीका-वाहिकाएँ बड़ी शिराओं में खुलती हैं — द्रव रुधिर में लौटकर आयतन बनाए रखता है।",
     "Lymph vessels open into large veins — the fluid returns to the blood, keeping its volume intact."),

    ("double-circulation-lymph", "medium",
     "दोहरे परिसंचरण का शरीर को क्या लाभ है?",
     "What advantage does double circulation give the body?",
     ["हृदय को आराम मिलता है", "शुद्ध रुधिर पूरे दबाव से शरीर के प्रत्येक भाग में जाता है — ऑक्सीजन-आपूर्ति अधिकतम", "रुधिर का रंग सुंदर होता है", "रुधिर कम बनता है"],
     ["The heart gets rest", "Fully oxygenated blood reaches every body part at full pressure — oxygen delivery is maximised", "The blood's colour improves", "Less blood is made"],
     1,
     "मिश्रण न होने से ऊतकों को सदैव शुद्धतम रुधिर मिलता है; बायाँ निलय पूरे बल से उसे शरीर में ठेलता है।",
     "With no mixing, tissues always receive the purest blood; the left ventricle drives it into the body at full force."),

    ("double-circulation-lymph", "medium",
     "हृदय का बायाँ भाग शुद्ध रुधिर क्यों धारण करता है?",
     "Why does the left side of the heart hold oxygenated blood?",
     ["वह हवा में खुला रहता है", "फुफ्फुसीय चक्र से फेफड़ों का ऑक्सीजन-युक्त रुधिर बाएँ अलिंद में ही आता है — वहीं से कायिक चक्र शुरू होता है", "बायाँ भाग ऊपर होता है", "बाएँ भाग में फेफड़े लगे हैं"],
     ["It stays open to air", "The oxygen-rich blood from the lungs arrives in the left atrium via the pulmonary circuit — the systemic circuit starts right there", "The left side sits higher", "The lungs are attached to the left side"],
     1,
     "दो चक्रों की व्यवस्था ऐसी है — फेफड़ों से आया रुधिर बाएँ पक्ष में उतरता है और शरीर की ओर प्रेरित होता है।",
     "The two circuits are arranged so lung blood lands on the left side and is dispatched bodyward."),

    ("double-circulation-lymph", "medium",
     "मछली के परिसंचरण को एकल (single) क्यों कहा जाता है?",
     "Why is a fish's circulation called single?",
     ["उसका रुधिर एक बार बनता है", "रुधिर एक ही चक्र में हृदय से केवल एक बार गुजरता है — फेफड़ों जैसा अलग ऑक्सीजन-लूप नहीं", "उसका हृदय एक कोष्ठक का होता है ही नहीं", "उसके शरीर में रुधिर नहीं होता"],
     ["Its blood is made once", "Blood passes through the heart only once per circuit — no separate oxygen loop like lungs", "Its heart has no chamber at all", "Its body has no blood"],
     1,
     "गलफड़ों से ऑक्सीजन लेने के बाद रुधिर सीधे शरीर जाता है — हृदय में वापसी अगले चक्र में होती है।",
     "After picking oxygen at the gills the blood heads straight to the body — returning to the heart only next round."),

    ("double-circulation-lymph", "medium",
     "लसीका-गाँठों (lymph nodes) में WBC की उपस्थिति का कार्य क्या है?",
     "What is the role of WBCs present in lymph nodes?",
     ["रुधिर जमाना", "रोगाणुओं को छानकर पकड़ना और नष्ट करना — शरीर के रक्षा-चौकियों की तरह", "भोजन पचाना", "ऑक्सीजन बाँटना"],
     ["Clotting blood", "Trapping and destroying germs — like the body's defence checkpoints", "Digesting food", "Distributing oxygen"],
     1,
     "लसीका अपने प्रवाह में उठाए रोगाणु गाँठों में छनती है — वहीं WBC उन्हें कुचल देते हैं।",
     "Lymph filters the germs it carries at the nodes — there WBCs crush them."),

    ("double-circulation-lymph", "medium",
     "ऊतक-द्रव (tissue fluid) और प्लाज्मा में मुख्य अंतर क्या है?",
     "What is the main difference between tissue fluid and plasma?",
     ["कोई अंतर नहीं", "ऊतक-द्रव में बड़े प्लाज्मा-प्रोटीन बहुत कम होते हैं — केशिका-भित्ति से वे नहीं छन पाते", "ऊतक-द्रव में RBC अधिक होते हैं", "प्लाज्मा रंगहीन होता है"],
     ["No difference", "Tissue fluid has very few large plasma proteins — they cannot sieve through the capillary wall", "Tissue fluid has more RBCs", "Plasma is colourless"],
     1,
     "केशिका छलनी काम करती है — जल और छोटे विलेय बाहर, बड़े प्रोटीन भीतर रह जाते हैं।",
     "The capillary acts as a sieve — water and small solutes pass out, big proteins stay behind."),

    ("double-circulation-lymph", "medium",
     "यदि लसीका-निकासी (lymph drainage) ठीक से न हो तो शरीर की कोशिकाओं में क्या दिखेगा?",
     "If lymph drainage fails, what will be seen in the body's tissues?",
     ["कोशिकाएँ सूख जाएँगी", "द्रव जमा होकर सूजन (oedema) — ऊतक फूल जाएँगे", "कोशिकाएँ बढ़ जाएँगी", "कुछ नहीं होगा"],
     ["The cells dry out", "Fluid collects causing swelling (oedema) — the tissues puff up", "The cells multiply", "Nothing happens"],
     1,
     "केशिकाओं से निकला द्रव लौटने का रास्ता खो देता है — ऊतकों में जल-संग्रह सूजन बनता है।",
     "Fluid leaving the capillaries loses its return route — waterlogging of tissues becomes swelling."),

    ("double-circulation-lymph", "medium",
     "आँतों से सोखे गए वसा-अणु रुधिर तक मुख्यतः किस मार्ग से पहुँचते हैं?",
     "By which main route do fat molecules absorbed in the intestines reach the blood?",
     ["सीधे केशिकाओं से", "आँत की लसीका-वाहिकाओं (लैक्टियल) से — लसीका के माध्यम से", "श्वास द्वारा", "पसीने से"],
     ["Directly via capillaries", "Via the intestinal lymph vessels (lacteals) — through the lymph", "Through breath", "Through sweat"],
     1,
     "बड़े वसा-अणु केशिका-छलनी से नहीं गुजरते — वे लैक्टियल में उठकर लसीका द्वारा रुधिर तक जाते हैं।",
     "Large fat molecules do not pass the capillary sieve — they ride the lacteals into lymph and on to blood."),

    ("double-circulation-lymph", "medium",
     "तीन-कोष्ठक हृदय वाले जीव (जैसे मेढक) में रुधिर की शुद्धता की स्थिति कैसी रहती है?",
     "In animals with three-chambered hearts (like a frog), what is the state of blood purity?",
     ["पूर्णतः अमिश्रित", "कुछ मिश्रण संभव — शुद्ध-अशुद्ध रुधिर पूर्णतः अलग नहीं रहते", "रुधिर बिल्कुल शुद्ध होता है", "रुधिर ही नहीं होता"],
     ["Fully unmixed", "Some mixing is possible — oxygenated and deoxygenated blood do not stay fully separate", "The blood is fully pure", "There is no blood at all"],
     1,
     "एक निलय में दोनों रुधिर आमने-सामने आते हैं — पूर्ण पृथक्करण नहीं, इसलिए ऊर्जा-क्षमता सीमित।",
     "Both bloods meet in one ventricle — no complete separation, hence limited energy capacity."),

    ("double-circulation-lymph", "medium",
     "मानव हृदय में रुधिर का पूर्ण मार्ग क्रम में कौन-सा सही है?",
     "Which is the correct full pathway of blood through the human heart, in order?",
     ["महाशिरा → दायाँ अलिंद → दायाँ निलय → फुफ्फुसीय धमनी → फेफड़े → फुफ्फुसीय शिरा → बायाँ अलिंद → बायाँ निलय → महाधमनी", "महाधमनी → बायाँ अलिंद → फेफड़े → दायाँ निलय → महाशिरा", "फेफड़े → दायाँ अलिंद → महाधमनी → बायाँ निलय", "दायाँ अलिंद → बायाँ अलिंद → फेफड़े → महाशिरा"],
     ["Vena cava → right atrium → right ventricle → pulmonary artery → lungs → pulmonary vein → left atrium → left ventricle → aorta", "Aorta → left atrium → lungs → right ventricle → vena cava", "Lungs → right atrium → aorta → left ventricle", "Right atrium → left atrium → lungs → vena cava"],
     0,
     "यही दोहरे परिसंचरण की धारा है — दाएँ पक्ष से फेफड़े, फेफड़ों से बायाँ पक्ष, बाएँ पक्ष से शरीर।",
     "This is the stream of double circulation — right side to lungs, lungs to left side, left side to body."),

    ("double-circulation-lymph", "medium",
     "दोहरे परिसंचरण में फुफ्फुसीय चक्र का दबाव कायिक चक्र से कम रखा गया है — इसकी व्यवस्था कैसे है?",
     "In double circulation the pulmonary circuit runs at lower pressure than the systemic — how is this arranged?",
     ["दोनों निलयों की दीवारें समान हैं", "दायाँ निलय पतली दीवार वाला है — वह रुधिर को केवल निकट फेफड़ों तक धकेलता है; बायाँ निलय मोटी दीवार से पूरे शरीर के लिए उच्च दाब बनाता है", "फेफड़ों में वाल्व होते हैं", "शिराएँ धकेलती हैं"],
     ["Both ventricles have equal walls", "The right ventricle is thin-walled — it pushes blood only to the nearby lungs; the thick-walled left ventricle builds high pressure for the whole body", "The lungs contain valves", "The veins push"],
     1,
     "दाएँ निलय का छोटा काम छोटी दीवार से, बाएँ निलय का बड़ा काम मोटी दीवार से — प्रकृति का आनुपातिक इंजीनियरिंग।",
     "The right ventricle's small job gets a thin wall, the left ventricle's big job a thick one — nature's proportional engineering."),

    ("double-circulation-lymph", "medium",
     "लसीका और रुधिर में गति की दृष्टि से अंतर क्यों है?",
     "Why do lymph and blood differ in speed of flow?",
     ["लसीका मोटी होती है", "लसीका का कोई पंप नहीं — वह दाब-पार्थक्य और पेशी-दबाव से धीमे-धीमे बहती है, रुधिर हृदय से तेज़ दौड़ता है", "लसीका ऊपर जाती है", "रुधिर में वाल्व नहीं होते"],
     ["Lymph is thick", "Lymph has no pump — it drifts slowly by pressure difference and muscle squeeze, while blood races from the heart", "Lymph goes upward", "Blood has no valves"],
     1,
     "हृदय-पंप रुधिर को चलाता है; लसीका निष्क्रिय प्रवाह है — शरीर-चालन से ही उसकी गति बनती है।",
     "The heart-pump drives blood; lymph is a passive flow — body movement alone stirs it."),

    ("double-circulation-lymph", "hard",
     "केशिकाओं में द्रव का बाहर रिसना और वापसी दोनों होते हैं — ऊतक-द्रव का बनना किस ओर झुका होता है?",
     "Capillaries both leak fluid out and take it back — which way does the balance tilt for tissue fluid formation?",
     ["केवल वापसी होती है", "केशिका के धमनी-सिरे पर दबाव अधिक — बहिर्स्राव वहीं प्रबल; शिरा-सिरे पर वापसी — कुल बाहर निकला द्रव लसीका से लौटता है", "दोनों सिरों पर समान", "कहीं भी निष्कासन नहीं"],
     ["Only return happens", "At the artery-end the pressure is higher — outward seepage dominates there; return occurs at the vein-end; the net leftover fluid comes back via lymph", "Both ends equal", "No leakage anywhere"],
     1,
     "धमनी-सिरे का उच्च दबाव द्रव बाहर धकेलता है, शिरा-सिरे का घटा दबाव खींचता है — शेष बचे द्रव की वापसी लसीका-तंत्र संभालता है।",
     "The artery-end's high pressure pushes fluid out, the vein-end's lower pressure draws it back — the lymphatic system handles the leftover."),

    ("double-circulation-lymph", "hard",
     "लसीका-वाहिकाओं में भी वाल्व क्यों होते हैं?",
     "Why do lymph vessels also contain valves?",
     ["लसीका जमती है", "पंप-रहित धीमे प्रवाह को शरीर-चालन के झोलों से ही आगे धकेलना पड़ता है — बिना वाल्व वह वापस नीचे बह जाएगी", "लसीका गाढ़ी होती है", "वाल्व लसीका बनाते हैं"],
     ["Lymph clots", "The pumpless slow flow is nudged along only by jolts of body movement — without valves it would slip back down", "Lymph is thick", "Valves make lymph"],
     1,
     "निम्न-दाब प्रवाह में गुरुत्व हावी हो सकता है — वाल्व प्रत्येक धक्के को एकदिशीय बनाकर काम पूरा कराते हैं।",
     "In a low-pressure flow gravity can win — valves make every nudge one-way and get the job done."),

    # ---------------- phloem-translocation (15: E5/M9/H1) ----------------
    ("phloem-translocation", "easy",
     "पौधे में भोजन (शर्करा) का परिवहन किस ऊतक द्वारा होता है?",
     "Through which tissue is food (sugar) transported in a plant?",
     ["जाइलम", "फ्लोएम", "कॉर्क", "एपिडर्मिस"],
     ["Xylem", "Phloem", "Cork", "Epidermis"],
     1,
     "फ्लोएम भोजन-चालन ऊतक है — पत्तियों से बना भोजन इसी से शरीर के सभी भागों को जाता है।",
     "Phloem is the food-conducting tissue — food made in the leaves travels through it to all plant parts."),

    ("phloem-translocation", "easy",
     "भोजन-परिवहन की प्रक्रिया को क्या कहते हैं?",
     "What is the process of food transport called?",
     ["वाष्पोत्सर्जन", "स्थानांतरण (translocation)", "विसरण", "परासरण"],
     ["Transpiration", "Translocation", "Diffusion", "Osmosis"],
     1,
     "फ्लोएम में भोजन-वहन का नाम स्थानांतरण (translocation) है।",
     "The carriage of food in the phloem is named translocation."),

    ("phloem-translocation", "easy",
     "पौधे में 'स्रोत' (source) किसे कहते हैं?",
     "What is called the 'source' in a plant?",
     ["जहाँ भोजन खर्च होता है", "जहाँ भोजन बनता है — जैसे हरी पत्तियाँ", "जड़ की मिट्टी", "तने की छाल"],
     ["Where food is consumed", "Where food is made — e.g. the green leaves", "The root's soil", "The stem's bark"],
     1,
     "भोजन-निर्माण स्थल = स्रोत; वहाँ से भोजन निकलकर पौधे में बँटता है।",
     "The food-making site = source; food leaves it to be distributed round the plant."),

    ("phloem-translocation", "easy",
     "'शंकु' या 'ग्राही' (sink) किन भागों को कहा जाता है?",
     "Which parts are called 'sinks'?",
     ["पत्तियाँ", "जहाँ भोजन उपयोग या संग्रह होता है — जड़ें, फल, बीज, कंद", "तने की ऊपरी कली", "केवल फूल"],
     ["The leaves", "Where food is used or stored — roots, fruits, seeds, tubers", "The stem's top bud", "Only the flower"],
     1,
     "ग्राही = उपभोक्ता-भंडार; वहाँ भोजन पहुँचाना ही स्थानांतरण का उद्देश्य है।",
     "Sinks = consumers-and-stores; delivering food there is translocation's whole purpose."),

    ("phloem-translocation", "easy",
     "फ्लोएम में भोजन-प्रवाह किस दिशा(ओं) में हो सकता है?",
     "In which direction(s) can food flow in the phloem?",
     ["केवल नीचे", "केवल ऊपर", "दोनों दिशाओं में — ऊपर और नीचे (द्विदिश)", "क्षैतिज ही"],
     ["Only downward", "Only upward", "Both ways — up and down (bidirectional)", "Only horizontal"],
     2,
     "ग्राही पौधे में ऊपर (कली) और नीचे (जड़) दोनों ओर होते हैं — इसलिए फ्लोएम-प्रवाह द्विदिशीय है।",
     "Sinks lie both above (buds) and below (roots) — hence phloem flow is bidirectional."),

    ("phloem-translocation", "medium",
     "फ्लोएम द्वारा परिवहनीय पदार्थ मुख्यतः कौन-से हैं?",
     "Which substances are mainly transported by the phloem?",
     ["जल और खनिज", "सुक्रोज़ और अमीनो अम्ल", "ऑक्सीजन", "कार्बन डाइऑक्साइड"],
     ["Water and minerals", "Sucrose and amino acids", "Oxygen", "Carbon dioxide"],
     1,
     "फ्लोएम-रस में मुख्यतः घुली शर्करा (सुक्रोज़) और अमीनो अम्ल होते हैं।",
     "Phloem sap mainly carries dissolved sugar (sucrose) and amino acids."),

    ("phloem-translocation", "medium",
     "स्थानांतरण (translocation) में ऊर्जा (ATP) की आवश्यकता क्यों पड़ती है?",
     "Why does translocation require energy (ATP)?",
     ["फ्लोएम की नलिकाएँ बंद होती हैं", "भोजन को चालन-नलिकाओं में सक्रिय रूप से लोड करना पड़ता है — यह ऊर्जा-व्ययी प्रक्रिया है", "पौधा चलता है", "भोजन ठंडा होता है"],
     ["The phloem tubes are closed", "Food must be actively loaded into the conducting tubes — an energy-spending step", "The plant moves", "The food is cold"],
     1,
     "सक्रिय लोडिंग से नलिका-सिरे पर शर्करा-सांद्रता बढ़ती है — जल प्रवेश कर प्रवाह चलाता है; ATP इसी चरण में खर्च होता है।",
     "Active loading raises sugar concentration at the tube end — water enters and drives the flow; ATP is spent at this step."),

    ("phloem-translocation", "medium",
     "चालन-ऊतक में भोजन लोड करने में कौन-सी कोशिकाएँ सहायक हैं?",
     "Which cells assist in loading food into the conducting tissue?",
     ["वाहिकाएँ", "साथी कोशिकाएँ (companion cells)", "रोम-कोशिकाएँ", "गार्ड सेल"],
     ["Vessels", "Companion cells", "Hair cells", "Guard cells"],
     1,
     "जीवित साथी कोशिकाएँ चालन-पोतों के साथ लगी होती हैं और उन्हें ऊर्जा-प्रबंधन व लोडिंग में मदद करती हैं।",
     "Living companion cells sit beside the conducting tubes and aid their energy management and loading."),

    ("phloem-translocation", "medium",
     "वसंत में पेड़ की कलियाँ फूटते समय जड़ों में संग्रहित भोजन का प्रवाह कैसा होता है?",
     "When buds sprout in spring, how does the stored food in the roots flow?",
     ["रुक जाता है", "ऊपर की ओर बहता है — जड़ तब ग्राही से स्रोत बन जाती है", "नीचे की ओर", "नष्ट हो जाता है"],
     ["It stops", "It flows upward — the root then turns from sink into source", "Downward", "It is destroyed"],
     1,
     "स्रोत-ग्राही की भूमिकाएँ ऋतु-सापेक्ष बदलती हैं — संग्रहित भोजन जब खर्च होता है तो भंडार ही स्रोत बन जाता है।",
     "Source-sink roles shift with the season — when stored food is spent, the store itself becomes the source."),

    ("phloem-translocation", "medium",
     "फल बढ़ते समय उसकी 'ग्राही-शक्ति' का क्या अर्थ है?",
     "What is meant by a growing fruit's 'sink strength'?",
     ["फल का गिरना", "फल की भोजन माँग की प्रबलता — प्रबल ग्राही फ्लोएम से अधिक भोजन खींच लेता है", "फल का रंग", "फल की गंध"],
     ["The fruit dropping", "The vigour of the fruit's food demand — a strong sink draws more food from the phloem", "The fruit's colour", "The fruit's smell"],
     1,
     "जो अंग जितनी तेज़ी से बढ़ता या संग्रह करता है, उतना ही प्रबल खिंचाव वह भोजन-धारा पर डालता है।",
     "The faster an organ grows or stores, the harder it pulls on the food stream."),

    ("phloem-translocation", "medium",
     "जाइलम और फ्लोएम का परिवहन-वस्तु संबंध में सही युग्म कौन-सा है?",
     "Which is the correct pairing of xylem and phloem by what they transport?",
     ["जाइलम — भोजन; फ्लोएम — जल", "जाइलम — जल व खनिज; फ्लोएम — भोजन (सुक्रोज़, अमीनो अम्ल)", "दोनों — जल", "दोनों — भोजन"],
     ["Xylem — food; phloem — water", "Xylem — water & minerals; phloem — food (sucrose, amino acids)", "Both — water", "Both — food"],
     1,
     "जाइलम ऊर्ध्व जल-खनिज मार्ग, फ्लोएम द्विदिश भोजन-मार्ग — कार्य आधार पर अलग।",
     "Xylem: the upward water-mineral route; phloem: the bidirectional food route — separate by function."),

    ("phloem-translocation", "medium",
     "तने के चारों ओर छल्ला (ring) काटकर छाल हटा देने पर छल्ले के ठीक ऊपर सूजन दिखती है — क्यों?",
     "When a ring of bark is removed round the stem, swelling appears just above the ring — why?",
     ["जाइलम बंद हो गया", "फ्लोएम कट गया — ऊपर से आ रहा भोजन वहीं जमा हो जाता है", "जड़ मर गई", "पानी रुक गया"],
     ["The xylem closed", "The phloem is cut — food coming from above collects right there", "The root died", "The water stopped"],
     1,
     "छाल-छल्ले में फ्लोएम होता है; नीचे जाता भोजन रास्ता-कट होकर ऊपर ही इकट्ठा हो जाता है।",
     "The bark ring contains the phloem; downward food, road-blocked, piles up above the cut."),

    ("phloem-translocation", "medium",
     "किसी शाखा का छाल-छल्ला (girdling) अनेक सप्ताह बाद उस शाखा की जड़ों को क्यों मार देता है?",
     "Why does girdling a branch kill its roots after many weeks?",
     ["जड़ों को जल नहीं मिला", "जड़ों को भोजन नहीं मिला — जाइलम नीचे जल ले जाता रहा, पर ऊपर से फ्लोएम-भोजन आना छल्ले से रुका", "जड़ें ऊपर चढ़ गईं", "पत्तियाँ सूख गईं"],
     ["The roots got no water", "The roots got no food — the xylem kept sending water down, but phloem food from above was stopped by the ring", "The roots climbed up", "The leaves dried"],
     1,
     "जड़ें ग्राही हैं — भोजन-रुकावट से भूखी मरती हैं जबकि जल-परिवहन (जाइलम) कुछ समय चलता रहता है।",
     "Roots are sinks — starved by the food blockade they die, while xylem water flow continues a while."),

    ("phloem-translocation", "medium",
     "आलू के पौधे में कंद (tuber) मोटा होने के लिए भोजन कैसे पहुँचता है?",
     "How does food reach the swelling tuber in a potato plant?",
     ["जाइलम भोजन भेजता है", "पत्तों में बनी सुक्रोज़ फ्लोएम द्वारा नीचे कंद-ग्राही तक आती है और वहाँ स्टार्च बनकर संचित होती है", "कंद स्वयं भोजन बनाता है", "मिट्टी से भोजन सोखा जाता है"],
     ["The xylem sends food", "Sucrose made in the leaves travels down via the phloem to the tuber-sink and is stored there as starch", "The tuber makes its own food", "Food is absorbed from the soil"],
     1,
     "कंद प्रबल ग्राही है — फ्लोएम-धारा उसमें शर्करा उतारती है; भंडारण-रूप में स्टार्च में बदल जाती है।",
     "The tuber is a mighty sink — the phloem stream unloads sugar into it, which converts to starch for storage."),

    ("phloem-translocation", "hard",
     "फ्लोएम में द्रव्यमान-प्रवाह (mass flow) का सोच क्या है — स्रोत से ग्राही तक चालन कैसे चलता है?",
     "What is the mass-flow idea in phloem — how does conduction run from source to sink?",
     ["भोजन कोशिका-दर-कोशिका फेंका जाता है", "स्रोत पर सक्रिय शर्करा-लोडिंग से जल प्रवेश कर दाब बढ़ता है; ग्राही पर शर्करा उतरने से दाब घटता है — दाबांतर ही रस को स्रोत से ग्राही धकेलता है", "वाष्पोत्सर्जन खींचता है", "मूल-दाब धकेलता है"],
     ["Food is flung cell to cell", "Active sugar loading at the source draws water in and raises pressure; at the sink sugar unloading lowers it — this pressure difference pushes sap from source to sink", "Transpiration pulls it", "Root pressure pushes it"],
     1,
     "दाब-प्रवाह परिकल्पना: स्रोत-सिरा उच्च-दाब, ग्राही-सिरा निम्न-दाब — अंतर ही बहाव का इंजन है।",
     "The pressure-flow hypothesis: source end high-pressure, sink end low-pressure — the difference is the flow's engine."),
]
