# -*- coding: utf-8 -*-
"""B08 'Transportation & Circulation' — Part 1 data (65 items).
Order: heart (35), blood-components (30).
Tuple: (topic, difficulty, q_hi, q_en, options_hi[4], options_en[4], correct_idx, exp_hi, exp_en)
"""

PART1 = [
    # ---------------- heart (35: E12/M20/H3) ----------------
    ("heart", "easy",
     "मानव हृदय की चार कक्षों के ऊपरी जोड़े को क्या कहा जाता है?",
     "What is the upper pair of the four chambers of the human heart called?",
     ["निलय (ventricles)", "अलिंद (atria)", "महाधमनी", "शिराएँ"],
     ["Ventricles", "Atria", "Aorta", "Veins"],
     1,
     "हृदय के ऊपरी दो कक्ष अलिंद हैं जो रुधिर ग्रहण करते हैं; निचले दो कक्ष निलय हैं जो रुधिर को बाहर पंप करते हैं।",
     "The upper two chambers are atria, which receive blood; the lower two are ventricles, which pump blood out."),

    ("heart", "easy",
     "हृदय के निचले दो कक्षों का कार्य क्या है?",
     "What is the role of the lower two chambers of the heart?",
     ["रुधिर को केवल जमा करना", "रुधिर को संकुचन द्वारा बाहर धकेलना (पंप करना)", "रुधिर छानना", "रुधिर जमाना"],
     ["Only storing blood", "Pumping blood out by contraction", "Filtering blood", "Clotting blood"],
     1,
     "निलय हृदय के मोटी-दीवार वाले पंप-कक्ष हैं — उनका संकुचन ही रुधिर को फेफड़ों और शरीर तक भेजता है।",
     "Ventricles are the thick-walled pumping chambers — their contraction sends blood to the lungs and the body."),

    ("heart", "easy",
     "हृदय के बाएँ और दाएँ भाग को अलग रखने वाली भित्ति को क्या कहते हैं?",
     "What is the wall separating the left and right sides of the heart called?",
     ["वाल्व (कपाटिका)", "पट्टिका", "पट (septum)", "झिल्ली"],
     ["Valve", "Platelet", "Septum", "Membrane"],
     2,
     "पट (सेप्टम) दाएँ और बाएँ अर्ध के बीच की विभाजक भित्ति है जो शुद्ध और अशुद्ध रुधिर के मिश्रण को रोकती है।",
     "The septum is the dividing wall between the right and left halves that stops oxygenated and deoxygenated blood from mixing."),

    ("heart", "easy",
     "हृदय में कपाटिकाओं (valves) का मुख्य कार्य क्या है?",
     "What is the main function of the valves in the heart?",
     ["रुधिर को तेज़ बहाना", "रुधिर का उल्टा बहाव (backflow) रोकना", "रुधिर बनाना", "हृदय को ठंडा रखना"],
     ["Making the blood flow faster", "Preventing the backflow of blood", "Producing blood", "Cooling the heart"],
     1,
     "कपाटिकाएँ एकतरफा द्वार हैं — संकुचन के बाद रुधिर वापस न लौट सके, यही उनका काम है।",
     "Valves are one-way gates — their job is to stop blood from returning after each contraction."),

    ("heart", "easy",
     "हृदय के दाएँ अलिंद और दाएँ निलय के बीच का वाल्व क्या कहलाता है?",
     "What is the valve between the right atrium and the right ventricle called?",
     ["द्विकपर्दी (बाइकस्पिड)", "त्रिकपर्दी (ट्राइकस्पिड)", "अर्धचंद्र वाल्व", "माइट्रल वाल्व"],
     ["Bicuspid valve", "Tricuspid valve", "Semilunar valve", "Mitral valve"],
     1,
     "दाएँ अलिंद-निलय के बीच त्रिकपर्दी वाल्व है; बाएँ ओर द्विकपर्दी (माइट्रल) वाल्व है।",
     "The tricuspid valve sits between the right atrium and ventricle; on the left side is the bicuspid (mitral) valve."),

    ("heart", "easy",
     "बाएँ अलिंद और बाएँ निलय के बीच का कपाटिका किस नाम से जानी जाती है?",
     "By what name is the valve between the left atrium and the left ventricle known?",
     ["त्रिकपर्दी", "द्विकपर्दी (बाइकस्पिड/माइट्रल)", "साइनस वाल्व", "कोरोनरी वाल्व"],
     ["Tricuspid", "Bicuspid (mitral)", "Sinus valve", "Coronary valve"],
     1,
     "बाईं ओर का अलिंद-निलय द्वार द्विकपर्दी कहलाता है — इसे माइट्रल वाल्व भी कहते हैं।",
     "The left atrium-ventricle door is called bicuspid — also known as the mitral valve."),

    ("heart", "easy",
     "वयस्क मनुष्य का हृदय एक मिनट में औसतन कितनी बार धड़कता है?",
     "On average, how many times does an adult human heart beat per minute?",
     ["लगभग 12–15", "लगभग 30–35", "लगभग 70–72", "लगभग 150–160"],
     ["About 12–15", "About 30–35", "About 70–72", "About 150–160"],
     2,
     "विश्रामावस्था में हृदय की धड़कन लगभग 70–72 प्रति मिनट होती है; शारीरिक मेहनत में यह बढ़ जाती है।",
     "At rest the heart beats about 70–72 times a minute; physical exertion raises this."),

    ("heart", "easy",
     "हृदय के किस भाग से शुद्ध (ऑक्सीजन-युक्त) रुधिर पूरे शरीर में जाता है?",
     "From which part of the heart does oxygenated blood go out to the whole body?",
     ["दायाँ अलिंद", "दायाँ निलय", "बायाँ निलय", "बायाँ अलिंद"],
     ["Right atrium", "Right ventricle", "Left ventricle", "Left atrium"],
     2,
     "बायाँ निलय शुद्ध रुधिर को महाधमनी (aorta) में धकेलता है — इसीलिए उसकी दीवार सबसे मोटी है।",
     "The left ventricle pushes oxygenated blood into the aorta — that is why its wall is the thickest."),

    ("heart", "easy",
     "हृदय के दाएँ पक्ष में कौन-सा रुधिर बहता है?",
     "Which blood flows through the right side of the heart?",
     ["शुद्ध रुधिर", "अशुद्ध (ऑक्सीजन-रहित) रुधिर", "केवल प्लाज्मा", "लसीका"],
     ["Oxygenated blood", "Deoxygenated blood", "Only plasma", "Lymph"],
     1,
     "दायाँ अर्ध अशुद्ध रुधिर का पंप-घर है — शरीर से लौटा रुधिर यहीं से फेफड़ों को भेजा जाता है।",
     "The right half is the pump-house of deoxygenated blood — returning blood is sent from here to the lungs."),

    ("heart", "easy",
     "'धड़-धड़' (lub-dub) हृदय-ध्वनि किन संरचनाओं के बंद होने से उत्पन्न होती है?",
     "The 'lub-dub' heart sounds are produced by the closing of which structures?",
     ["पट (septum)", "हृदय की कपाटिकाएँ (valves)", "महाधमनी की दीवार", "फेफड़ों की झिल्ली"],
     ["The septum", "The valves of the heart", "The wall of the aorta", "The lung membrane"],
     1,
     "कपाटिकाओं के तेज़ी से बंद होने का कंपन ही lub-dub ध्वनि बनाता है — पहली ध्वनि त्रिकपर्दी/द्विकपर्दी की, दूसरी अर्धचंद्राकार वाल्व की।",
     "The snap-shut vibration of the valves makes the lub-dub — the first sound from the tricuspid/bicuspid, the second from the semilunar valves."),

    ("heart", "easy",
     "हृदय को किस उपाधि से पहचाना जाता है?",
     "By what title is the heart identified?",
     ["शरीर की छननी", "शरीर का पंप", "शरीर की भट्ठी", "शरीर का भंडार"],
     ["The filter of the body", "The pump of the body", "The furnace of the body", "The storehouse of the body"],
     1,
     "हृदय एक मांसपेशीय पंप है जो जीवन भर निरंतर संकुचित-शिथिल होकर रुधिर को शरीर भर में धकेलता रहता है।",
     "The heart is a muscular pump that contracts and relaxes lifelong, pushing blood through the body."),

    ("heart", "easy",
     "हृदय की मांसपेशी (हृदय पेशी) किस प्रकार की होती है?",
     "What type of tissue is the heart muscle?",
     ["ऐच्छिक रेखिक पेशी", "हृदय पेशी (कार्डिएक) — अनैच्छिक और लयबद्ध", "अरेखित ऐच्छिक पेशी", "उपकला ऊतक"],
     ["Voluntary striated muscle", "Cardiac muscle — involuntary and rhythmic", "Involuntary voluntary smooth muscle", "Epithelial tissue"],
     1,
     "हृदय की पेशी अनैच्छिक और अपने-आप लय में संकुचित होने वाली विशेष कार्डिएक पेशी है।",
     "The heart's muscle is special cardiac muscle — involuntary and self-rhythmic in contraction."),

    ("heart", "medium",
     "शरीर से लौटता अशुद्ध रुधिर हृदय में किस क्रम से गुजरता है?",
     "In which sequence does deoxygenated blood returning from the body pass through the heart?",
     ["दायाँ निलय → दायाँ अलिंद → फेफड़े", "दायाँ अलिंद → दायाँ निलय → फुफ्फुसीय धमनी", "बायाँ अलिंद → बायाँ निलय → महाधमनी", "दायाँ अलिंद → बायाँ निलय → फेफड़े"],
     ["Right ventricle → right atrium → lungs", "Right atrium → right ventricle → pulmonary artery", "Left atrium → left ventricle → aorta", "Right atrium → left ventricle → lungs"],
     1,
     "ऊपर/नीचे महाशिरा से रुधिर दाएँ अलिंद में गिरता है → त्रिकपर्दी से दाएँ निलय में → संकुचन से फुफ्फुसीय धमनी द्वारा फेफड़ों को।",
     "From the venae cavae blood drops into the right atrium → through the tricuspid into the right ventricle → contraction sends it via the pulmonary artery to the lungs."),

    ("heart", "medium",
     "फेफड़ों से लौटी शुद्ध रुधिर का हृदय के भीतर पथ क्या है?",
     "What is the path of oxygenated blood returning from the lungs, inside the heart?",
     ["बायाँ अलिंद → बायाँ निलय → महाधमनी", "बायाँ निलय → बायाँ अलिंद → शरीर", "दायाँ अलिंद → बायाँ निलय → शरीर", "बायाँ अलिंद → दायाँ निलय → फेफड़े"],
     ["Left atrium → left ventricle → aorta", "Left ventricle → left atrium → body", "Right atrium → left ventricle → body", "Left atrium → right ventricle → lungs"],
     0,
     "फुफ्फुसीय शिराएँ रुधिर बाएँ अलिंद में लाती हैं → द्विकपर्दी से बाएँ निलय में → महाधमनी से संपूर्ण शरीर में।",
     "Pulmonary veins bring blood to the left atrium → through the bicuspid into the left ventricle → out through the aorta to the whole body."),

    ("heart", "medium",
     "बाएँ निलय की दीवार बाकी कक्षों से मोटी क्यों होती है?",
     "Why is the wall of the left ventricle thicker than that of the other chambers?",
     ["उसमें रुधिर सबसे अधिक रहता है", "उसे रुधिर को संपूर्ण शरीर तक उच्च दबाव से धकेलना होता है", "वह सबसे ऊपर स्थित है", "उसकी दीवार में वसा जमा होती है"],
     ["It holds the most blood", "It must push blood to the entire body at high pressure", "It sits at the top", "Fat deposits in its wall"],
     1,
     "दाएँ निलय को केवल नज़दीकी फेफड़ों तक रुधिर भेजना है; बाएँ निलय को सिर से पैर तक — इसी लंबी दूरी के दबाव के लिए उसकी पेशी मोटी है।",
     "The right ventricle sends blood only to the nearby lungs; the left must drive it from head to toe — its muscle is thick for that long-distance pressure."),

    ("heart", "medium",
     "एक हृदय-चक्र (cardiac cycle) में क्या-क्या शामिल है?",
     "What does one cardiac cycle include?",
     ["केवल हृदय का संकुचन", "केवल हृदय का विश्राम", "संकुचन (systole) और विश्राम (diastole) — दोनों", "श्वास-ग्रहण और श्वास-त्याग"],
     ["Only contraction of the heart", "Only relaxation of the heart", "Both contraction (systole) and relaxation (diastole)", "Inhalation and exhalation"],
     2,
     "एक चक्र = अलिंदों-निलयों का क्रमिक संकुचन फिर विश्राम; 70–72 चक्र प्रति मिनट में हृदय पूरा करता है।",
     "One cycle = sequential contraction then relaxation of atria and ventricles; the heart completes 70–72 cycles a minute."),

    ("heart", "medium",
     "सिस्टोल (systole) से क्या तात्पर्य है?",
     "What is meant by systole?",
     ["हृदय-कक्षों का विश्राम-चरण", "हृदय-कक्षों का संकुचन-चरण", "रुधिर का थक्का जमना", "रुधिर का छनना"],
     ["The relaxation phase of heart chambers", "The contraction phase of heart chambers", "Clotting of blood", "Filtering of blood"],
     1,
     "सिस्टोल = संकुचन, जिसमें कक्षों का रुधिर बाहर निकलता है; डायस्टोल = विश्राम, जिसमें कक्ष रुधिर से भरते हैं।",
     "Systole = contraction, when chambers eject blood; diastole = relaxation, when chambers fill with blood."),

    ("heart", "medium",
     "डायस्टोल (diastole) के दौरान हृदय के कक्ष क्या करते हैं?",
     "What do the heart chambers do during diastole?",
     ["रुधिर बाहर धकेलते हैं", "रुधिर से भर जाते हैं (विश्राम)", "पूर्णतः रिक्त रहते हैं", "रुधिर जमाते हैं"],
     ["They push blood out", "They fill with blood (relax)", "They stay completely empty", "They clot the blood"],
     1,
     "विश्राम-चरण में अलिंद शिराओं से और निलय अलिंदों से रुधिर भरकर अगले संकुचन के लिए तैयार हो जाते हैं।",
     "In the relaxation phase the atria fill from veins and the ventricles from the atria, readying for the next beat."),

    ("heart", "medium",
     "मानव हृदय वक्ष-गुहा में कहाँ और किस आकार-स्थिति में पाया जाता है?",
     "Where and in what position-shape does the human heart lie in the chest cavity?",
     ["पसलियों के बाहर, मुट्ठी से दुगुना", "दोनों फेफड़ों के बीच, छाती के मध्य में थोड़ा बाईं ओर झुका, अपनी मुट्ठी के आकार का", "पेट की गुहा में, गोल", "गर्दन में, चपटा"],
     ["Outside the ribs, twice the fist", "Between the two lungs, mid-chest tilted slightly left, about the size of one's own fist", "In the belly cavity, round", "In the neck, flat"],
     1,
     "हृदय दो फेफड़ों के बीच आड़ी पर्दे के पास बाईं ओर झुका बैठा है; अपने स्वयं की बंद मुट्ठी जितना आकार है।",
     "The heart sits between the lungs near the mid-partition, tilted slightly left; its size matches one's own clenched fist."),

    ("heart", "medium",
     "सार्विक परिसंचरण (systemic circulation) का कार्य क्या है?",
     "What is the work of systemic circulation?",
     ["रुधिर को फेफड़ों तक ले जाना", "हृदय के बाएँ पक्ष से शुद्ध रुधिर को संपूर्ण शरीर की कोशिकाओं तक पहुँचाना और अशुद्ध रुधिर वापस लाना", "रुधिर जमाना", "लसीका बनाना"],
     ["Taking blood to the lungs", "Delivering oxygenated blood from the left side to all body cells and bringing deoxygenated blood back", "Clotting blood", "Forming lymph"],
     1,
     "सार्विक लूप शरीर की हर कोशिका तक O2-पोषक तत्व पहुँचाता और CO2-अपशिष्ट उठाकर हृदय लौटता है।",
     "The systemic loop delivers O2 and nutrients to every cell and returns carrying CO2 and wastes to the heart."),

    ("heart", "medium",
     "हृदय की अलिंदों और निलयों के आकार की तुलना में निलय बड़े क्यों होते हैं?",
     "Why are the ventricles larger-chambered than the atria?",
     ["अलिंद छोटे जन्म से होते हैं", "अलिंद को केवल आसपास से रुधिर ग्रहण कर नीचे देना है; निलयों को दूर तक पंप करने हेतु बड़ी क्षमता-शक्ति चाहिए", "निलयों में वायु भरती है", "अलिंद में केवल लसीका आती है"],
     ["Atria are small from birth", "Atria only receive nearby blood and pass it down; ventricles need large capacity-power to pump far", "Ventricles hold air", "Only lymph enters the atria"],
     1,
     "अलिंद संग्रह-कक्ष हैं; निलय प्रणोदक-कक्ष — फेफड़ों/शरीर की दूरी तक धकेलने के लिए बड़ी मांसपेशी और आकार चाहिए।",
     "Atria are collection chambers; ventricles are propellers — pushing as far as the lungs or body demands bigger size and muscle."),

    ("heart", "medium",
     "दाएँ निलय से रुधिर किस वाहिका द्वारा बाहर जाता है?",
     "Through which vessel does blood leave the right ventricle?",
     ["महाधमनी (aorta)", "फुफ्फुसीय धमनी (pulmonary artery)", "फुफ्फुसीय शिरा", "कोरोनरी शिरा"],
     ["The aorta", "The pulmonary artery", "The pulmonary vein", "The coronary vein"],
     1,
     "दायाँ निलय अशुद्ध रुधिर फुफ्फुसीय धमनी से फेफड़ों को भेजता है — यही उसका एकमात्र कार्य है।",
     "The right ventricle sends deoxygenated blood to the lungs via the pulmonary artery — its sole assignment."),

    ("heart", "medium",
     "बाएँ निलय का संकुचन रुधिर को किस मुख्य वाहिका में प्रवेश कराता है?",
     "The contraction of the left ventricle pushes blood into which main vessel?",
     ["फुफ्फुसीय धमनी", "महाधमनी (aorta)", "ऊपरी महाशिरा", "यकृत-शिरा"],
     ["Pulmonary artery", "The aorta", "Superior vena cava", "Hepatic vein"],
     1,
     "महाधमनी शरीर की सबसे बड़ी धमनी है — बाएँ निलय से निकलकर उसकी शाखाएँ पूरे शरीर में फैलती हैं।",
     "The aorta is the body's largest artery — leaving the left ventricle, its branches spread through the whole body."),

    ("heart", "medium",
     "हृदय की धड़कन रुके बिना अलिंद-निलय का संकुचन किस क्रम में होता है?",
     "In which order do the atria and ventricles contract during a normal heartbeat?",
     ["दोनों साथ एक ही क्षण", "पहले दोनों अलिंद, फिर दोनों निलय", "पहले निलय, फिर अलिंद", "केवल निलय संकुचित होते हैं"],
     ["Both at the same instant", "First both atria, then both ventricles", "First ventricles, then atria", "Only ventricles contract"],
     1,
     "लयबद्ध क्रम — अलिंदों का संकुचन रुधिर नीचे धकेलता है, तत्पश्चात निलयों का संकुचन उसे शरीर/फेफड़ों तक।",
     "A set rhythm — atrial contraction pushes blood down, then ventricular contraction drives it to body and lungs."),

    ("heart", "medium",
     "हृदय में रुधिर का मिश्रण न होना किस दृष्टि से लाभदायक है?",
     "Why is the absence of blood mixing in the heart advantageous?",
     ["हृदय हल्का रहता है", "कोशिकाओं को पूर्ण-ऑक्सीजन युक्त रुधिर मिलता है — ऊर्जा-प्राप्ति अधिकतम होती है", "रुधिर का रंग सुंदर दिखता है", "रुधिर जल्दी जमता है"],
     ["The heart stays light", "Cells receive fully oxygenated blood — energy yield is maximised", "The blood colour looks nice", "Blood clots quickly"],
     1,
     "चार-कक्षीय पृथक्करण से ऊतकों तक हमेशा शुद्धतम रुधिर पहुँचता है — यही सक्रिय जीवन और स्थिर ताप का आधार है।",
     "Four-chambered separation delivers the purest blood to tissues — the basis of active life and stable body temperature."),

    ("heart", "medium",
     "हृदय-पेशी को लगातार कार्य के लिए ऊर्जा-ऑक्सीजन कैसे मिलती रहती है?",
     "How does the heart muscle itself keep receiving energy and oxygen for nonstop work?",
     ["हृदय-गुहा के भीतर के रुधिर से सीधे", "हृदय की अपनी रुधिर-आपूर्ति (कोरोनरी वाहिकाएँ) द्वारा", "फेफड़ों से प्रत्यक्ष विसरण से", "लसीका से"],
     ["Directly from the blood inside its chambers", "Through the heart's own blood supply (coronary vessels)", "By direct diffusion from the lungs", "From lymph"],
     1,
     "हृदय-भित्ति की मोटी पेशी गुहा-रुधिर से पोषण नहीं ले सकती; कोरोनरी धमनियाँ उसे अपना रुधिर पहुँचाती हैं।",
     "The thick heart wall cannot feed from chamber blood; coronary arteries deliver its own blood supply."),

    ("heart", "medium",
     "हृदय और रुधिर-वाहिकाओं को मिलाकर किस नाम से जाना जाता है?",
     "What is the heart together with the blood vessels known as?",
     ["श्वसन-तंत्र", "परिसंचरण तंत्र (cardiovascular)", "पाचन-तंत्र", "उत्सर्जन-तंत्र"],
     ["Respiratory system", "Circulatory system (cardiovascular)", "Digestive system", "Excretory system"],
     1,
     "हृदय (पंप) + रुधिर + वाहिकाओं का नेटवर्क = परिसंचरण तंत्र — शरीर का परिवहन-मार्ग।",
     "Heart (pump) + blood + vessel network = circulatory system — the transport highway of the body."),

    ("heart", "medium",
     "यदि हृदय की त्रिकपर्दी वाल्व ठीक से बंद न होता तो क्या समस्या उत्पन्न होगी?",
     "What problem arises if the tricuspid valve fails to close properly?",
     ["रुधिर दाएँ अलिंद में वापस लौटेगा — पंप-क्षमता घटेगी", "रुधिर तुरंत जम जाएगा", "महाधमनी फट जाएगी", "कुछ नहीं होगा"],
     ["Blood will leak back into the right atrium — pumping efficiency falls", "Blood will clot instantly", "The aorta will burst", "Nothing will happen"],
     0,
     "बंद न होने पर संकुचन का रुधिर वापस अलिंद में रिसता है — आगे का प्रवाह कमजोर पड़ता है; यही वाल्व-निष्फलता का सिद्धांत है।",
     "If the valve leaks, contraction blood regurgitates into the atrium — the forward flow weakens; this is the principle of valve failure."),

    ("heart", "medium",
     "हृदय की धड़कन और नाड़ी (pulse) का संबंध क्या है?",
     "What is the relation between the heartbeat and the pulse?",
     ["दोनों अलग-अलग गति से चलते हैं", "प्रति मिनट दोनों की संख्या समान होती है — नाड़ी हृदय-संकुचन की ही प्रतिध्वनि है", "नाड़ी धड़कन से दुगुनी होती है", "कोई संबंध नहीं"],
     ["They run at different rates", "Their counts per minute are equal — the pulse is the echo of each heart contraction", "Pulse is double the heartbeat", "No relation"],
     1,
     "हर संकुचन धमनी-भित्ति में एक लहर भेजता है — वही लहर कलाई पर नाड़ी के रूप में महसूस होती है; संख्या एक ही।",
     "Every contraction sends a wave through the arterial wall — that wave is felt as the pulse; the counts match one-to-one."),

    ("heart", "medium",
     "व्यायाम के समय हृदय की धड़कन और प्रत्येक धड़कन में पंप किया रुधिर — दोनों में क्या बदलाव आता है?",
     "During exercise, what happens to the heart rate and the blood pumped per beat?",
     ["दर बढ़ती है, प्रति धड़कन आयतन घटता है", "दर घटती है, आयतन बढ़ता है", "दोनों बढ़ते हैं — कोशिकाओं की O2-माँग पूरी करने हेतु", "दोनों घटते हैं"],
     ["Rate rises, volume per beat falls", "Rate falls, volume rises", "Both increase — to meet the cells' O2 demand", "Both decrease"],
     2,
     "तेज़ काम में हृदय तेज़ और गहरा पंप करता है — प्रति मिनट रुधिर-निर्गम काफ़ी बढ़ जाता है।",
     "During hard work the heart pumps faster and stronger — the blood output per minute rises sharply."),

    ("heart", "medium",
     "महाधमनी (aorta) की भित्ति अत्यंत प्रत्यास्थ (elastic) क्यों होती है?",
     "Why is the wall of the aorta highly elastic?",
     ["रुधिर को रोकने के लिए", "संकुचन के झटके को सोखकर निरंतर प्रवाह में बदलने के लिए", "रुधिर छानने के लिए", "वायु रखने के लिए"],
     ["To block the blood", "To absorb the contraction's surge and convert it into a steady flow", "To filter blood", "To hold air"],
     1,
     "प्रत्यास्थ महाधमनी प्रत्येक झटके को थामकर दो धड़कनों के बीच भी रुधिर को आगे धकेलती रहती है — प्रवाह सतत बना रहता है।",
     "The elastic aorta buffers each surge and keeps pushing blood even between beats — the flow stays continuous."),

    ("heart", "hard",
     "मछली के रुधिर-प्रवाह की तुलना में मानव-हृदय की दोहरी व्यवस्था का शुद्ध परिणाम क्या है?",
     "Compared with blood flow in fish, what is the net outcome of the human heart's double arrangement?",
     ["मनुष्य में रुधिर धीमा बहता है", "मछली में रुधिर हृदय से एक बार निकलकर सीधे ऊतकों में जाता है; मनुष्य में फेफड़ों से शुद्ध होकर ऊतकों तक पूर्ण-ऑक्सीजन रुधिर पहुँचता है", "मछली में ऑक्सीजन नहीं जाती", "मनुष्य में हृदय छोटा होता है"],
     ["Blood flows slower in humans", "In fish, blood leaves the heart once and goes straight to tissues; in humans it is oxygenated in lungs before reaching tissues with full oxygen load", "No oxygen travels in fish", "The human heart is smaller"],
     1,
     "मछली का एकल परिसंचरण क्षमता में सीमित है; मानव का दोहरा परिसंचरण ऊतकों तक ऑक्सीजन-संतृप्त रुधिर की आपूर्ति करता है।",
     "The fish's single circulation limits delivery; the human double circulation supplies tissues with oxygen-saturated blood."),

    ("heart", "hard",
     "हृदय-गुहा की तुलना में हृदय-पेशी (myocardium) को अपनी कोरोनरी आपूर्ति क्यों चाहिए — गुहा में तो लगातार रुधिर भरा रहता है?",
     "Why does the heart muscle (myocardium) need its coronary supply when the chambers are constantly full of blood?",
     ["गुहा का रुधिर दूषित होता है", "मोटी पेशी-दीवार की भीतरी कोशिकाओं तक गुहा-रुधिर विसरित नहीं हो पाता — पृथक आपूर्ति आवश्यक है", "पेशी रुधिर से घबराती है", "कोरोनरी रुधिर अधिक ठंडा होता है"],
     ["Chamber blood is impure", "The inner cells of the thick muscular wall cannot be reached by diffusion from chamber blood — a separate supply is essential", "The muscle fears blood", "Coronary blood is cooler"],
     1,
     "पोषण-विसरण की सीमा कुछ सेल-मोटाई तक ही है; मायोकार्डियम की गहरी कोशिकाओं के लिए विशेष धमनियाँ ही काम करती हैं।",
     "Diffusive nourishment reaches only a few cell-lengths; deep myocardium cells depend on dedicated arteries."),

    ("heart", "hard",
     "यदि कोई व्यक्ति केवल शिराओं (veins) से रुधिर देने के बजाय हृदय की कोरोनरी धमनी में रुकावट का सामना करे, तो सबसे पहले कौन-सा ऊतक क्षतिग्रस्त होगा?",
     "If a coronary artery becomes blocked, which tissue is damaged first?",
     ["मस्तिष्क की तंत्रिकाएँ", "हृदय की अपनी पेशी", "यकृत", "त्वचा"],
     ["Nerves of the brain", "The heart's own muscle", "The liver", "The skin"],
     1,
     "कोरोनरी धमनी केवल हृदय-पेशी को रुधिर देती है — उसके अवरोधन से सबसे पहले मायोकार्डियम ही ऑक्सीजन-भुखमरी में पड़ता है।",
     "A coronary artery serves only the heart muscle — its blockage starves the myocardium of oxygen first."),

    ("heart", "hard",
     "उद्घाटन-निरीक्षण: एक हृदय में बाएँ निलय की दीवार की मोटाई दाएँ निलय से लगभग तीन गुनी मिली। यह अवलोकन किस तथ्य की पुष्टि करता है?",
     "A dissection shows the left ventricle wall about three times thicker than the right. Which fact does this observation confirm?",
     ["बायाँ निलय अधिक रुधिर रखता है", "बाएँ निलय को पूरे शरीर की दूरी तक उच्च दबाव बनाना होता है — कार्य के अनुरूप पेशी-विकास", "दायाँ निलय निष्क्रिय है", "हृदय में वसा जमा है"],
     ["The left ventricle holds more blood", "The left ventricle must build high pressure for the whole body's distance — muscle grown to match the work", "The right ventricle is idle", "Fat is deposited in the heart"],
     1,
     "दीवार-मोटाई पंप-भार का जीवित रिकॉर्ड है — दूर-दराज सार्विक परिसंचरण के लिए बाएँ निलय की पेशी अनुपात में विकसित होती है।",
     "Wall thickness is a living record of pump load — the left ventricle's muscle grows in proportion to systemic circulation's long haul."),

    # ---------------- blood-components (30: E10/M17/H3) ----------------
    ("blood-components", "easy",
     "रुधिर का तरल भाग जिसमें कोशिकाएँ तैरती हैं, क्या कहलाता है?",
     "What is the fluid part of blood in which the cells float called?",
     ["प्लाज्मा", "लसीका", "सीरम", "साइनोवियल द्रव"],
     ["Plasma", "Lymph", "Serum", "Synovial fluid"],
     0,
     "प्लाज्मा रुधिर का पीलापन लिए तरल मैट्रिक्स है — इसी में RBC, WBC और पटलिकाएँ निलंबित रहती हैं।",
     "Plasma is the yellowish fluid matrix of blood — RBCs, WBCs and platelets stay suspended in it."),

    ("blood-components", "easy",
     "प्लाज्मा का प्रमुख घटक (प्रतिशत) क्या है?",
     "What is the major component (by percentage) of plasma?",
     ["प्रोटीन — 90%", "जल — लगभग 90%", "लवण — 50%", "ग्लूकोज़ — 70%"],
     ["Proteins — 90%", "Water — about 90%", "Salts — 50%", "Glucose — 70%"],
     1,
     "प्लाज्मा का लगभग 90% जल है; शेष में प्रोटीन, लवण, ग्लूकोज़, गैसें और अपशिष्ट घुले रहते हैं।",
     "About 90% of plasma is water; the rest carries dissolved proteins, salts, glucose, gases and wastes."),

    ("blood-components", "easy",
     "श्वेत रुधिर कणिकाओं (WBC) का मुख्य कार्य क्या है?",
     "What is the chief function of white blood cells (WBCs)?",
     ["गैस-परिवहन", "शरीर की रक्षा — रोगाणुओं से लड़ना", "रुधिर जमाना", "भोजन पचाना"],
     ["Gas transport", "Body defence — fighting germs", "Clotting blood", "Digesting food"],
     1,
     "WBC शरीर के सैनिक हैं — अपनी अमीबीय गति से रोगाणुओं तक पहुँचकर उन्हें निगल जाते हैं।",
     "WBCs are the body's soldiers — moving amoeboid-ly to engulf germs."),

    ("blood-components", "easy",
     "रुधिर का थक्का जमाने में सहायक कोशिका-खंड कौन-सा है?",
     "Which cell fragment helps in clotting of blood?",
     ["RBC", "WBC", "पटलिकाएँ (platelets)", "प्लाज्मा प्रोटीन ही पर्याप्त"],
     ["RBC", "WBC", "Platelets", "Plasma proteins alone suffice"],
     2,
     "पटलिकाएँ (थ्रोम्बोसाइट) घाव के संपर्क में आते ही टूटकर थक्का-निर्माण की श्रृंखला शुरू करती हैं।",
     "Platelets (thrombocytes) rupture on contact with a wound and kick off the clotting cascade."),

    ("blood-components", "easy",
     "प्लाज्मा में घुले रुधिर-प्रोटीन का नाम क्या है जो थक्के की जाली बनाता है?",
     "What is the dissolved blood protein called that forms the mesh of a clot?",
     ["हीमोग्लोबिन", "फाइब्रिन", "एल्बुमिन", "पेप्सिन"],
     ["Haemoglobin", "Fibrin", "Albumin", "Pepsin"],
     1,
     "घायल होने पर घुलनशील फाइब्रिनोजेन अघुलनशील फाइब्रिन के जाल में बदल जाता है — इसी जाल में कोशिकाएँ फँसकर थक्का बनता है।",
     "On injury, soluble fibrinogen turns into an insoluble fibrin mesh — cells trapped in this mesh form the clot."),

    ("blood-components", "easy",
     "रक्त समूहों का ABO वर्गीकरण किस आधार पर होता है?",
     "On what basis is the ABO classification of blood groups done?",
     ["RBC की संख्या पर", "RBC की सतह पर प्रतिजन (antigen) A/B की उपस्थिति पर", "प्लाज्मा के रंग पर", "WBC के आकार पर"],
     ["On the number of RBCs", "On the presence of antigen A/B on the RBC surface", "On the colour of plasma", "On the shape of WBCs"],
     1,
     "RBC पर कौन-सा प्रतिजन लगा है — A, B, दोनों या कोई नहीं — उसी से समूह A, B, AB या O तय होता है।",
     "Which antigen an RBC carries — A, B, both or none — decides the group A, B, AB or O."),

    ("blood-components", "easy",
     "सर्वव्यापी दाता (universal donor) किस रक्त-समूह को कहा जाता है?",
     "Which blood group is called the universal donor?",
     ["A", "B", "AB", "O"],
     ["A", "B", "AB", "O"],
     3,
     "O-समूह की RBC पर कोई प्रतिजन (A/B) नहीं होता — इसलिए किसी भी समूह के रुधिर में उसका जमाव (clumping) नहीं होता।",
     "Group-O red cells carry no A/B antigen — so they trigger no clumping in any recipient's blood."),

    ("blood-components", "easy",
     "सर्वग्राही (universal recipient) किस रक्त-समूह को कहा जाता है?",
     "Which blood group is called the universal recipient?",
     ["O", "A", "B", "AB"],
     ["O", "A", "B", "AB"],
     3,
     "AB-समूह के प्लाज्मा में कोई प्रतिरोधी (anti-A/anti-B) नहीं होता — किसी भी समूह का रुधिर चल सकता है।",
     "Group-AB plasma holds no anti-A/anti-B antibodies — blood of any group can be given."),

    ("blood-components", "easy",
     "रुधिर की मुख्य तीन कोशिकीय इकाइयाँ कौन-सी हैं?",
     "What are the three main cellular elements of blood?",
     ["RBC, WBC, पटलिकाएँ", "RBC, WBC, न्यूरॉन", "WBC, पटलिकाएँ, कोलेजन", "RBC, कोण्ड्रोसाइट, पटलिकाएँ"],
     ["RBCs, WBCs, platelets", "RBCs, WBCs, neurons", "WBCs, platelets, collagen", "RBCs, chondrocytes, platelets"],
     0,
     "लाल कणिकाएँ, श्वेत कणिकाएँ और पटलिकाएँ — तीनों प्लाज्मा में तैरती रुधिर-इकाइयाँ हैं।",
     "Red cells, white cells and platelets — the three blood elements floating in plasma."),

    ("blood-components", "easy",
     "प्लाज्मा के सफेद रंग का नहीं — रुधिर का लाल रंग किसके कारण होता है?",
     "The red colour of blood is due to what?",
     ["प्लाज्मा के वर्णक", "RBC का हीमोग्लोबिन", "पटलिकाओं का रंग", "WBC के केंद्रक"],
     ["Pigments of plasma", "Haemoglobin of RBCs", "The colour of platelets", "Nuclei of WBCs"],
     1,
     "हीमोग्लोबिन का लोहा-युक्त वर्णक ही रुधिर को लाल रंग देता है।",
     "The iron-bearing pigment haemoglobin gives blood its red colour."),

    ("blood-components", "medium",
     "प्लाज्मा के कौन-से कार्य इसे रुधिर का 'परिवहन-माध्यम' बनाते हैं?",
     "Which functions of plasma make it the 'transport medium' of blood?",
     ["केवल जल संतुलन", "पोषक तत्वों, गैसों, अपशिष्टों और हार्मोनों का घुलकर यात्रा करना", "केवल थक्का बनाना", "केवल रंग देना"],
     ["Only water balance", "Carrying dissolved nutrients, gases, wastes and hormones on their journeys", "Only clotting", "Only giving colour"],
     1,
     "प्लाज्मा एक बहुउपयोगी माल-गाड़ी है — ग्लूकोज़, अमीनो अम्ल, CO2, यूरिया, हार्मोन सब इसी में घुलकर गंतव्य तक जाते हैं।",
     "Plasma is a multipurpose freight car — glucose, amino acids, CO2, urea and hormones all ride dissolved to their destinations."),

    ("blood-components", "medium",
     "लाल रुधिर कणिकाओं के परिपक्व रूप में केंद्रक नहीं होता — इसका फायदा क्या है?",
     "Mature red blood cells lack a nucleus — what is the advantage of this?",
     ["कोशिका हल्की होकर अधिक हीमोग्लोबिन ढो सकती है", "कोशिका तेज़ बढ़ती है", "कोशिका जल्दी मरती है", "कोई विशेष लाभ नहीं"],
     ["The cell becomes lighter and can carry more haemoglobin", "The cell grows faster", "The cell dies quickly", "No special benefit"],
     0,
     "केंद्रक की जगह अतिरिक्त हीमोग्लोबिन भर जाता है — गैस-वहन क्षमता अधिकतम होती है; अवतल (biconcave) आकार सतह भी बढ़ाता है।",
     "The nucleus's space packs in extra haemoglobin — gas-carrying capacity is maximised; the biconcave shape adds surface too."),

    ("blood-components", "medium",
     "WBC किस विशेषता से रुधिर-वाहिका की दीवार से बाहर ऊतकों में पहुँच जाते हैं?",
     "By which special ability do WBCs move out of the vessel wall into the tissues?",
     ["वे दीवार तोड़ देते हैं", "उनकी अमीबीय गति — दीवार की कोशिकाओं के बीच रेंगकर निकल जाते हैं", "वे उड़ जाते हैं", "वे प्लाज्मा में घुल जाते हैं"],
     ["They break the wall", "Their amoeboid movement — squeezing between the wall's cells", "They fly out", "They dissolve into plasma"],
     1,
     "अमीबीय गति से WBC संक्रमण-स्थल पर वाहिका छोड़कर पहुँचते हैं — इसी क्रिया को डायापेडेसिस कहते हैं।",
     "By amoeboid motion WBCs leave the vessel and reach infection sites — an action called diapedesis."),

    ("blood-components", "medium",
     "घाव पर थक्का बनने की सही घटना-श्रृंखला क्या है?",
     "What is the correct chain of events in clot formation at a wound?",
     ["पटलिकाएँ टूटती हैं → फाइब्रिनोजेन फाइब्रिन में बदलता है → जाल में कोशिकाएँ फँसती हैं → थक्का", "फाइब्रिन फाइब्रिनोजेन बनता है → RBC टूटते हैं", "WBC फाइब्रिन खाते हैं → रुधिर सूखता है", "प्लाज्मा वाष्पित होता है → अंश बचता है"],
     ["Platelets rupture → fibrinogen converts to fibrin → cells get trapped in the mesh → clot", "Fibrin becomes fibrinogen → RBCs burst", "WBCs eat fibrin → blood dries", "Plasma evaporates → residue remains"],
     0,
     "पटलिका-स्राव से शुरू होकर फाइब्रिन-जाल तक की यही क्रमबद्ध श्रृंखला रुधिर-हानि रोकती है।",
     "This ordered chain — from platelet release to the fibrin mesh — is what stops blood loss."),

    ("blood-components", "medium",
     "सीरम (serum) और प्लाज्मा में क्या अंतर है?",
     "What is the difference between serum and plasma?",
     ["दोनों समान हैं", "सीरम = प्लाज्मा जिसमें से फाइब्रिनोजेन हट चुका हो (थक्का बनने के बाद बचा तरल)", "प्लाज्मा में कोशिकाएँ होती हैं, सीरम में नहीं — यही एकमात्र अंतर है", "सीरम लाल होता है"],
     ["Both are identical", "Serum = plasma from which fibrinogen has been removed (the fluid left after clotting)", "Plasma has cells and serum does not — that is the only difference", "Serum is red"],
     1,
     "रुधिर जमने दें तो थक्के में फाइब्रिनोजेन खर्च हो जाता है; ऊपर जो साफ तरल बचता है वही सीरम है।",
     "Let blood clot and fibrinogen is spent in the clot; the clear fluid left above is serum."),

    ("blood-components", "medium",
     "रुधिर-आधान (transfusion) में असंगत समूह देने पर खतरा क्या होता है?",
     "What is the danger of transfusing an incompatible blood group?",
     ["रुधिर पतला हो जाता है", "प्राप्तकर्ता के प्रतिरोधियों से दाता की RBC चिपककर जमाव (agglutination) बनाती हैं — वाहिकाएँ बंद हो सकती हैं", "रुधिर नीला पड़ जाता है", "कोई खतरा नहीं"],
     ["The blood thins out", "The recipient's antibodies clump the donor RBCs (agglutination) — vessels may get blocked", "The blood turns blue", "No danger"],
     1,
     "प्रतिजन-प्रतिरोधी मेल से RBC का जमाव घातक हो सकता है — इसीलिए आधान पूर्व संगतता-परीक्षण अनिवार्य है।",
     "Antigen-antibody clash clumps RBCs, which can be fatal — hence compatibility testing before every transfusion."),

    ("blood-components", "medium",
     "AB रुधिर-समूह के व्यक्ति के प्लाज्मा में कौन-से प्रतिरोधी होते हैं?",
     "Which antibodies are present in the plasma of a person with blood group AB?",
     ["anti-A", "anti-B", "anti-A और anti-B दोनों", "कोई नहीं"],
     ["anti-A", "anti-B", "Both anti-A and anti-B", "None"],
     3,
     "AB व्यक्ति की RBC पर दोनों प्रतिजन होते हैं — प्लाज्मा में दोनों के प्रतिरोधी अनुपस्थित रहते हैं, इसीलिए वह सर्वग्राही है।",
     "An AB person's red cells bear both antigens — the plasma keeps neither antibody, making them the universal recipient."),

    ("blood-components", "medium",
     "O रुधिर-समूह के व्यक्ति की RBC पर कौन-से प्रतिजन पाए जाते हैं?",
     "Which antigens are found on the RBCs of a person with blood group O?",
     ["केवल A", "केवल B", "A और B दोनों", "न A, न B"],
     ["Only A", "Only B", "Both A and B", "Neither A nor B"],
     3,
     "O-समूह की RBC प्रतिजन-रहित होती हैं — दूसरे के प्रतिरोधियों को चिपने को कुछ नहीं मिलता।",
     "Group-O red cells are antigen-free — the recipient's antibodies find nothing to clasp."),

    ("blood-components", "medium",
     "प्लाज्मा-प्रोटीन का एक महत्वपूर्ण योगदान रुधिर के किस गुण में है?",
     "Plasma proteins contribute importantly to which property of blood?",
     ["रुधिर का रंग", "रुधिर का विसरण-दाब (osmotic balance) — जल को वाहिका के भीतर खींचे रखना", "रुधिर की गंध", "रुधिर का pH ही तय करना"],
     ["The colour of blood", "The osmotic balance of blood — keeping water drawn inside the vessels", "The smell of blood", "Solely fixing blood pH"],
     1,
     "प्लाज्मा-प्रोटीन वाहिका-भीतर खिंचाव बनाए रखते हैं जिससे तरल भाग छनकर बाहर नहीं रिसता।",
     "Plasma proteins maintain an inward pull so the fluid fraction does not leak out of the vessels."),

    ("blood-components", "medium",
     "हीमोग्लोबिन में कौन-सा खनिज होता है जो ऑक्सीजन से जुड़ने का केंद्र है?",
     "Which mineral in haemoglobin is the hub of oxygen binding?",
     ["कैल्शियम", "लोहा (iron)", "सोडियम", "आयोडीन"],
     ["Calcium", "Iron", "Sodium", "Iodine"],
     1,
     "हीमोग्लोबिन के हीम-भाग का लोहा ही O2 से जुड़ता है — आहार में लोहे की कमी से हीमोग्लोबिन घटता है।",
     "The iron of haem's part is what bonds O2 — dietary iron shortage lowers haemoglobin."),

    ("blood-components", "medium",
     "रुधिर शरीर का ताप कैसे नियंत्रित करने में सहायक है?",
     "How does blood help regulate body temperature?",
     ["रुधिर गर्मी पैदा करता है", "गर्म-ठंडे क्षेत्रों के बीच लगातार परिसंचरण से ताप का वितरण-संतुलन होता है", "रुधिर पसीना बनाता है", "रुधिर त्वचा मोटी करता है"],
     ["Blood generates heat", "Continuous circulation between warmer and cooler regions distributes and balances heat", "Blood makes sweat", "Blood thickens the skin"],
     1,
     "रुधिर शरीर का ताप-वाहक है — अंगों की गर्मी उठाकर त्वचा तक पहुँचाता और वितरित करता रहता है।",
     "Blood is the body's heat carrier — it lifts warmth from organs, delivers it to the skin and keeps it distributed."),

    ("blood-components", "medium",
     "हार्मोन जो ग्रंथियों से निकलते हैं, लक्ष्य-अंग तक किस माध्यम से पहुँचते हैं?",
     "By what medium do hormones secreted by glands reach their target organs?",
     ["लसीका से ही", "रुधिर (प्लाज्मा) द्वारा", "नाड़ियों से", "श्वास द्वारा"],
     ["Only by lymph", "By blood (plasma)", "By nerves", "By breath"],
     1,
     "अंतःस्रावी ग्रंथियाँ अपने स्राव रुधिर-धारा में छोड़ती हैं — प्लाज्मा उन्हें संपूर्ण शरीर के लक्ष्यों तक ले जाता है।",
     "Endocrine glands pour their secretions into the bloodstream — plasma ferries them to targets across the body."),

    ("blood-components", "medium",
     "CO2 का रुधिर में परिवहन-हिस्सा यहाँ नहीं पूछा जा रहा — बताइए कि रुधिर के किस घटक में 'जल में घुलनशीलता' का गुण CO2 के लिए सबसे उपयोगी है?",
     "Which blood component's water-rich nature is most useful for carrying dissolved CO2?",
     ["RBC की झिल्ली", "प्लाज्मा (जल-प्रधान तरल)", "पटलिकाएँ", "WBC का केंद्रक"],
     ["The RBC membrane", "Plasma (the water-rich fluid)", "Platelets", "The WBC nucleus"],
     1,
     "CO2 जल में उत्तम घुलनशील है — प्लाज्मा का 90% जल उसकी सवारी का मुख्य स्थान है।",
     "CO2 dissolves well in water — plasma's 90% water is its chief ride."),

    ("blood-components", "hard",
     "RBC की सामान्य आयु लगभग कितनी होती है?",
     "What is the average lifespan of a red blood cell?",
     ["लगभग 5–7 दिन", "लगभग 120 दिन (4 माह)", "लगभग 5 वर्ष", "जीवन भर"],
     ["About 5–7 days", "About 120 days (4 months)", "About 5 years", "Lifelong"],
     1,
     "लगभग 120 दिन कार्य करने के बाद पुरानी RBC यकृत-प्लीहा में तोड़ी जाती हैं और अस्थिमज्जा नई बनाती रहती है।",
     "After about 120 days of service, old RBCs are broken down in liver and spleen while marrow keeps making new ones."),

    ("blood-components", "hard",
     "प्रतिजन A और B दोनों वाले व्यक्ति का समूह AB है — उसके प्लाज्मा में anti-A/anti-B क्यों नहीं होते?",
     "A person with both A and B antigens is group AB — why does the plasma lack anti-A/anti-B?",
     ["प्लाज्मा प्रोटीन बनाना भूल जाता है", "शरीर कभी भी अपने ही RBC-प्रतिजनों के विरुद्ध प्रतिरोधी नहीं बनाता — अपने विरुद्ध हमला आत्म-घाता होता", "प्रतिरोधी RBC में चले जाते हैं", "AB में प्लाज्मा होता ही नहीं"],
     ["The plasma forgets to make proteins", "The body never makes antibodies against its own RBC antigens — self-attack would be self-destructive", "The antibodies move into RBCs", "AB has no plasma"],
     1,
     "प्रतिरोधी-निर्माण स्व-प्रतिजन के प्रति सहनशीलता से रोका जाता है — अपने प्रतिजन पहचानने वाला प्रतिरोधी बनता ही नहीं।",
     "Antibody production is checked by self-tolerance — an antibody recognising one's own antigen is never made."),

    ("blood-components", "hard",
     "Rh-कारक की दृष्टि से 'Rh+' और 'Rh−' का अर्थ क्या है?",
     "In terms of the Rh factor, what do 'Rh+' and 'Rh−' mean?",
     ["Rh+ में ऑक्सीजन अधिक, Rh− में कम", "RBC पर Rh-प्रतिजन की उपस्थिति (Rh+) या अनुपस्थिति (Rh−)", "प्लाज्मा के दो रंग", "पटलिकाओं की दो श्रेणियाँ"],
     ["Rh+ has more oxygen, Rh− less", "Presence (Rh+) or absence (Rh−) of the Rh antigen on RBCs", "Two colours of plasma", "Two classes of platelets"],
     1,
     "Rhesus-प्रतिजन RBC पर हो तो Rh+, न हो तो Rh− — यह ABO से पृथक, स्वतंत्र वंशानुगत वर्गीकरण है।",
     "Rhesus antigen present on RBCs makes Rh+, absent makes Rh− — an independent inheritance layer over ABO."),

    ("blood-components", "hard",
     "समूह-O का रुधिर किसी भी समूह को देने योग्य है — पर O-व्यक्ति को O ही क्यों चाहिए?",
     "Group-O blood can be given to anyone — but why can an O-person receive only O?",
     ["उसका प्लाज्मा पर्याप्त नहीं", "उसके प्लाज्मा में anti-A और anti-B दोनों होते हैं — A/B/AB की RBC तुरंत जमाव कर देंगे", "O-रुधिर सबसे पुराना होता है", "O में प्रतिरोधी नहीं बनते"],
     ["His plasma is insufficient", "His plasma carries both anti-A and anti-B — A, B or AB cells would clump at once", "O blood is the oldest", "No antibodies form in O"],
     1,
     "सर्वव्यापी दाता का दूसरा पहलू — O-प्राप्तकर्ता का प्लाज्मा दोनों प्रतिरोधियों से भरा होता है; केवल प्रतिजन-रहित O-कोशिकाएँ ही सुरक्षित हैं।",
     "The flip side of universal donorship — an O recipient's plasma brims with both antibodies; only antigen-free O cells are safe."),
    ("blood-components", "easy",
     "रुधिर की तीनों कोशिकीय इकाइयों में सबसे अधिक संख्या किसकी होती है?",
     "Which of the three cellular elements of blood is the most numerous?",
     ["WBC", "पटलिकाएँ", "RBC (लाल कणिकाएँ)", "तीनों बराबर"],
     ["WBCs", "Platelets", "RBCs (red cells)", "All three equal"],
     2,
     "एक घन मिलीलीटर रुधिर में लाखों RBC होती हैं — WBC और पटलिकाओं से अनेक गुना अधिक।",
     "A cubic millimetre of blood holds millions of RBCs — many times more than WBCs or platelets."),

    ("blood-components", "medium",
     "यदि किसी व्यक्ति की RBC संख्या असामान्य रूप से घट जाए, तो ऊतकों पर सबसे पहला प्रभाव क्या पड़ेगा?",
     "If a person's RBC count abnormally falls, what is the first effect on the tissues?",
     ["भोजन पचाना रुक जाएगा", "ऑक्सीजन की आपूर्ति घटेगी — थकान और कमजोरी जल्दी महसूस होगी", "रुधिर जमना बंद हो जाएगा", "शरीर ठंडा हो जाएगा"],
     ["Digestion will stop", "Oxygen supply drops — fatigue and weakness are felt early", "Clotting will stop", "The body turns cold"],
     1,
     "RBC ही ऑक्सीजन-वाहन हैं — उनकी घटी संख्या का सीधा अर्थ है ऊतकों तक O2 की घटी डिलीवरी।",
     "RBCs are the oxygen vehicles — fewer of them directly means less O2 delivered to tissues."),

    ("blood-components", "hard",
     "AB-समूह वाला व्यक्ति (सर्वग्राही) दाता के रूप में अन्य समूहों को रुधिर क्यों नहीं दे सकता?",
     "Why can an AB-group person (universal recipient) not donate blood to the other groups?",
     ["उसके रुधिर में प्रतिरोधी होते हैं जो सबको चोट पहुँचाते हैं", "उसकी RBC पर A और B दोनों प्रतिजन होते हैं — A, B या O के प्लाज्मा में उनमें से एक के विरुद्ध प्रतिरोधी पाया जाता है जो कोशिकाओं को जमा देता है", "AB रुधिर बहुत गाढ़ा होता है", "AB रुधिर में ऑक्सीजन नहीं होती"],
     ["His blood carries antibodies that harm everyone", "His RBCs bear both A and B antigens — plasma of A, B or O groups contains an antibody against one of them, clumping the cells", "AB blood is too thick", "AB blood has no oxygen"],
     1,
     "A-प्राप्तकर्ता में anti-B, B में anti-A, O में दोनों — AB की दोनों-प्रतिजन वाली कोशिकाएँ हर ओर जमाव का निमंत्रण हैं; केवल AB ही उन्हें सह लेता है।",
     "An A recipient has anti-B, a B recipient anti-A, an O both — the dual-antigen AB cells invite clumping everywhere; only AB accepts them."),
]
