# -*- coding: utf-8 -*-
"""B10 Part-1 — Growth, Development & Adolescence (chapter-10).
90 items: endocrine-system 40 (E13/M23/H4) + puberty-adolescence 30 (E10/M17/H3)
          + secondary-sexual-characteristics 20 (E7/M11/H2).
Tuple: (topic, difficulty, question_hi, question_en, options_hi[4], options_en[4], correct_idx, expl_hi, expl_en)

DENY-AWARENESS (verified by pre-generation scan of all 9 locked banks):
- B09/ch-02 owns: ovulation day-14 (q326), menstruation 3-7d (q330), cycle 21-35d (q331),
  menopause AGE ~50 (q332), boys-puberty common change voice+shoulders (q340),
  pad change 4-6h (q348), implantation (q329, menarche only as distractor).
- B06/ch-07 owns: goitre-iodine MINERAL angle (q719), iodised-salt advice (q712),
  largest gland= liver (q757), balanced-diet DEFINITION (q705), protein building-material (q703),
  calcium bones/teeth (q717), iron-deficiency consequence (q718), child-vs-adult needs (q722).
- B08/ch-09 owns: hormone transport MEDIUM= blood (q957).
- B05/ch-06 owns: nerve-message SPEED specialty (q631).
- B07/ch-08 owns: larynx FUNCTION (q827).
- B02/ch-03 owns: glandular epithelium tissue (q361).
=> B10 frames: ductless-duct concept (not medium), goitre as thyroid-gland swelling, largest
   ENDOCRINE gland, Adam's apple as puberty change, hormone-duration not speed, age-range of
   adolescence (11-17), menarche name, menopause WITHOUT age number.
"""

PART1 = [
    # ================= ENDOCRINE SYSTEM & HORMONES — 40 (E13/M23/H4) =================
    ("endocrine-system", "easy",
     "अंतःस्रावी तंत्र मुख्यतः किन संरचनाओं से मिलकर बना है?",
     "What structures mainly make up the endocrine system?",
     ["अंतःस्रावी ग्रंथियों से", "केवल हड्डियों से", "केवल नसों से", "केवल रुधिर वाहिकाओं से"],
     ["Endocrine glands", "Only bones", "Only nerves", "Only blood vessels"],
     0,
     "पिट्यूटरी, थायरॉइड, अधिवृक्क जैसी ग्रंथियाँ मिलकर शरीर की रासायनिक दूत-प्रणाली बनाती हैं।",
     "Glands like the pituitary, thyroid and adrenal together form the body's chemical courier system."),

    ("endocrine-system", "easy",
     "हार्मोन किसे कहते हैं?",
     "What are hormones?",
     ["ग्रंथियों द्वारा स्रावित रासायनिक संदेशवाहक", "रुधिर की लाल कोशिकाएँ", "नसों की बिजली", "पाचक रस"],
     ["Chemical messengers secreted by glands", "Red cells of blood", "The nerves' electricity", "Digestive juices"],
     0,
     "हार्मोन ग्रंथियों से निकलकर रक्त के सहारे लक्ष्य-अंगों तक आदेश पहुँचाने वाले रसायन हैं।",
     "Hormones are chemicals released by glands that carry orders to target organs riding the bloodstream."),

    ("endocrine-system", "easy",
     "'मास्टर ग्रंथि' किस अंतःस्रावी ग्रंथि को कहा जाता है?",
     "Which endocrine gland is called the 'master gland'?",
     ["पिट्यूटरी", "थायरॉइड", "अधिवृक्क", "अग्न्याशय"],
     ["Pituitary", "Thyroid", "Adrenal", "Pancreas"],
     0,
     "पिट्यूटरी कई अन्य ग्रंथियों की सक्रियता तय करती है — इसीलिए उसे मास्टर ग्रंथि कहते हैं।",
     "The pituitary decides the activity of several other glands — hence the title master gland."),

    ("endocrine-system", "easy",
     "थायरॉक्सिन हार्मोन किस ग्रंथि द्वारा स्रावित होता है?",
     "Which gland secretes the hormone thyroxine?",
     ["थायरॉइड ग्रंथि", "यकृत", "गुर्दा", "प्लीहा"],
     ["The thyroid gland", "Liver", "Kidney", "Spleen"],
     0,
     "गले में स्थित थायरॉइड ग्रंथि थायरॉक्सिन बनाती है।",
     "The thyroid gland, seated in the neck, makes thyroxine."),

    ("endocrine-system", "easy",
     "एड्रेनालिन हार्मोन किस ग्रंथि से निकलता है?",
     "From which gland does the hormone adrenaline come?",
     ["अधिवृक्क ग्रंथि से", "पिट्यूटरी से", "थायरॉइड से", "अग्न्याशय से"],
     ["The adrenal gland", "The pituitary", "The thyroid", "The pancreas"],
     0,
     "गुर्दों के ऊपर बैठी अधिवृक्क ग्रंथि आपात-क्षणों में एड्रेनालिन उड़ेलती है।",
     "The adrenal gland, perched atop the kidneys, pours out adrenaline in moments of emergency."),

    ("endocrine-system", "easy",
     "इंसुलिन हार्मोन का निर्माण कहाँ होता है?",
     "Where is the hormone insulin produced?",
     ["अग्न्याशय में", "आँख में", "फेफड़ों में", "हृदय में"],
     ["In the pancreas", "In the eye", "In the lungs", "In the heart"],
     0,
     "अग्न्याशय की अंतःस्रावी कोशिकाएँ इंसुलिन बनाकर रक्त में छोड़ती हैं।",
     "The endocrine cells of the pancreas make insulin and release it into blood."),

    ("endocrine-system", "easy",
     "टेस्टोस्टेरोन हार्मोन मुख्यतः किससे स्रावित होता है?",
     "The hormone testosterone is secreted mainly by what?",
     ["वृषणों से", "अंडाशयों से", "गुर्दों से", "आमाशय से"],
     ["The testes", "The ovaries", "The kidneys", "The stomach"],
     0,
     "लड़कों में वृषण टेस्टोस्टेरोन बनाते हैं — यौवन के परिवर्तन इसी की छत्रछाया में आते हैं।",
     "In boys the testes make testosterone — the changes of puberty arrive under its umbrella."),

    ("endocrine-system", "easy",
     "एस्ट्रोजन हार्मोन मुख्यतः किस ग्रंथि से मिलता है?",
     "Which gland mainly supplies the hormone oestrogen?",
     ["अंडाशय से", "वृषण से", "थायरॉइड से", "अधिवृक्क से"],
     ["The ovary", "The testes", "The thyroid", "The adrenal"],
     0,
     "लड़कियों में अंडाशय एस्ट्रोजन स्रावित करते हैं — स्त्री-यौवन के सूत्रधार।",
     "In girls the ovaries secrete oestrogen — the helmsman of female puberty."),

    ("endocrine-system", "easy",
     "अंतःस्रावी ग्रंथियों के परिवार में थायरॉइड का दर्जा क्या है?",
     "What rank does the thyroid hold in the family of endocrine glands?",
     ["सबसे बड़ी अंतःस्रावी ग्रंथि", "सबसे छोटी ग्रंथि", "अंतिम दर्जे की ग्रंथि", "बिल्कुल अनुपस्थित ग्रंथि"],
     ["The largest endocrine gland", "The smallest gland", "A last-rank gland", "An altogether absent gland"],
     0,
     "थायरॉइड अंतःस्रावी श्रेणी की सबसे बड़ी ग्रंथि है — स्मरण रहे, शरीर की सबसे बड़ी ग्रंथि (यकृत) इसी सूची में नहीं, क्योंकि वह बाह्यस्रावी भी है।",
     "The thyroid is the largest gland of the endocrine class — remember, the body's largest gland (liver) is not on this list since it is exocrine too."),

    ("endocrine-system", "easy",
     "'नलीहीन ग्रंथि' (ductless gland) का क्या अर्थ है?",
     "What does a 'ductless gland' mean?",
     ["जो स्राव सीधे रक्त में छोड़ती है", "जिसमें स्राव की नली होती है", "जो कभी स्राव नहीं करती", "जो केवल पाचन में काम आती है"],
     ["One that pours its secretion straight into blood", "One that has a duct for its secretion", "One that never secretes", "One used only in digestion"],
     0,
     "अंतःस्रावी ग्रंथियाँ नली नहीं रखतीं — उनका हार्मोन सीधा रक्त-प्रवाह में उतरता है।",
     "Endocrine glands keep no duct — their hormone drops straight into the bloodstream."),

    ("endocrine-system", "easy",
     "पिट्यूटरी ग्रंथि शरीर में कहाँ स्थित है?",
     "Where is the pituitary gland located in the body?",
     ["मस्तिष्क के ठीक नीचे", "हृदय के ऊपर", "पेट के बीच में", "घुटनों के पास"],
     ["Just below the brain", "Above the heart", "In the middle of the abdomen", "Near the knees"],
     0,
     "मस्तिष्क के नीचे लटकती छोटी-सी पिट्यूटरी पूरे अंतःस्रावी जगत की केंद्र-कुर्सी है।",
     "A tiny pituitary hangs below the brain — the centrestage chair of the whole endocrine world."),

    ("endocrine-system", "easy",
     "अधिवृक्क (एड्रेनल) ग्रंथियाँ कहाँ पाई जाती हैं?",
     "Where are the adrenal glands found?",
     ["प्रत्येक गुर्दे के ऊपर", "फेफड़ों के अंदर", "आँखों के पीछे", "जीभ के नीचे"],
     ["Atop each kidney", "Inside the lungs", "Behind the eyes", "Under the tongue"],
     0,
     "नाम ही कह देता है — अधि + वृक्क, यानी गुर्दे की टोपी जैसे ऊपर बैठी ग्रंथियाँ।",
     "The name itself tells — ad + renal, glands sitting cap-like above the kidneys."),

    ("endocrine-system", "easy",
     "इंसुलिन का मुख्य कार्य क्या है?",
     "What is the chief function of insulin?",
     ["रक्त में शर्करा के स्तर को नियंत्रित रखना", "भोजन पचाना", "शरीर का रंग बदलना", "हड्डियाँ जोड़ना"],
     ["Keeping the blood sugar level controlled", "Digesting food", "Changing the body's colour", "Joining bones"],
     0,
     "इंसुलिन रक्त की अतिरिक्त शर्करा को कम करता है — शर्करा-थर्मोस्टैट की तरह।",
     "Insulin reins in excess blood sugar — like a sugar-thermostat of the blood."),

    ("endocrine-system", "medium",
     "पिट्यूटरी को मास्टर ग्रंथि क्यों कहा जाता है?",
     "Why is the pituitary called the master gland?",
     ["क्योंकि वह अनेक अन्य ग्रंथियों की सक्रियता नियंत्रित करती है", "क्योंकि वह सबसे भारी अंग है", "क्योंकि वह रुधिर बनाती है", "क्योंकि वह पाचन करती है"],
     ["Because it controls the activity of many other glands", "Because it is the heaviest organ", "Because it makes blood", "Because it digests food"],
     0,
     "थायरॉइड, अधिवृक्क और योनि-ग्रंथियों की धुन पिट्यूटरी के इशारों पर चलती है।",
     "The thyroid, adrenals and sex glands dance to the pituitary's signals."),

    ("endocrine-system", "medium",
     "थायरॉक्सिन का प्रमुख कार्य क्या है?",
     "What is the principal work of thyroxine?",
     ["शरीर के चयापचय की गति नियंत्रित करना", "रुधिर जमाना", "भोजन भंडारित करना", "नाखून बढ़ाना"],
     ["Controlling the pace of the body's metabolism", "Clotting blood", "Storing food", "Growing nails"],
     0,
     "थायरॉक्सिन कोशिकाओं के जलने-खपने की रफ़्तार तय करता है — धीमा तो ऊर्जा-ग्राम कम, तेज़ तो ज़्यादा।",
     "Thyroxine fixes the burn-rate of cells — slow means less energy spent, fast means more."),

    ("endocrine-system", "medium",
     "एड्रेनालिन को 'आपातकालीन हार्मोन' क्यों कहते हैं?",
     "Why is adrenaline called the 'emergency hormone'?",
     ["खतरे के क्षण में वह शरीर को तुरंत सतर्क-तैयार बना देता है", "क्योंकि वह केवल नींद में बनता है", "क्योंकि वह भोजन पचाता है", "क्योंकि वह हड्डियाँ गलाता है"],
     ["In moments of danger it instantly readies the body for alert action", "Because it is made only in sleep", "Because it digests food", "Because it melts bones"],
     0,
     "साँप दिखा और धड़कन तेज़, साँस गहरी, मांसपेशियाँ तनी — यही एड्रेनालिन की तत्परता-फेरी है।",
     "A snake appears and the heart races, breath deepens, muscles tense — adrenaline's readiness-drill."),

    ("endocrine-system", "medium",
     "घेघा (गले की सूजन) में शरीर की कौन-सी ग्रंथि सूज जाती है?",
     "In goitre (swelling of the neck), which gland of the body swells up?",
     ["थायरॉइड", "पिट्यूटरी", "अधिवृक्क", "अग्न्याशय"],
     ["The thyroid", "The pituitary", "The adrenal", "The pancreas"],
     0,
     "गले की अग्र-भित्ति पर बैठी थायरॉइड बढ़ जाने से घेघा बनता है — थायरॉक्सिन-संतुलन बिगड़ने का संकेत।",
     "The thyroid sitting on the front of the neck enlarges to form goitre — a sign of disturbed thyroxine balance."),

    ("endocrine-system", "medium",
     "अग्न्याशय को 'मिश्रित ग्रंथि' क्यों कहा जाता है?",
     "Why is the pancreas called a 'mixed gland'?",
     ["क्योंकि वह पाचक रस (नली द्वारा) और हार्मोन (रक्त में) दोनों बनाता है", "क्योंकि वह दो अंगों में बँटा है", "क्योंकि वह केवल बच्चों में होता है", "क्योंकि वह रुधिर छानता है"],
     ["Because it makes both digestive juice (via a duct) and hormones (into blood)", "Because it is split into two organs", "Because it occurs only in children", "Because it filters blood"],
     0,
     "एक ही अग्न्याशय में दो विभाग — पाचन-नली वाला बाह्यस्रावी और इंसुलिन वाला अंतःस्रावी।",
     "One pancreas, two departments — the exocrine with a digestive duct and the endocrine with insulin."),

    ("endocrine-system", "medium",
     "निम्न में से कौन-सा हार्मोन-ग्रंथि युग्म सुमेलित नहीं है?",
     "Which hormone-gland pair is NOT correctly matched?",
     ["एड्रेनालिन — यकृत", "थायरॉक्सिन — थायरॉइड", "इंसुलिन — अग्न्याशय", "वृद्धि हार्मोन — पिट्यूटरी"],
     ["Adrenaline — liver", "Thyroxine — thyroid", "Insulin — pancreas", "Growth hormone — pituitary"],
     0,
     "एड्रेनालिन यकृत का नहीं, अधिवृक्क ग्रंथि का उत्पाद है — बाकी तीनों जोड़े सही हैं।",
     "Adrenaline belongs not to the liver but to the adrenal gland — the other three pairs are right."),

    ("endocrine-system", "medium",
     "हार्मोन-संदेश तंत्रिका-संदेश से अपनी किस विशेषता से भिन्न है?",
     "By which special quality does a hormone message differ from a nerve message?",
     ["इसका प्रभाव धीमा पर दीर्घकालिक और व्यापक होता है", "यह केवल एक सेकंड चलता है", "यह केवल एक कोशिका तक जाता है", "इसमें कोई रसायन नहीं होता"],
     ["Its effect is slow but long-lasting and widespread", "It lasts only a second", "It reaches only one cell", "It contains no chemical"],
     0,
     "नसें बिजली-सी तुरंत पहुँचाती हैं; हार्मोन धीरे-धीरे, पर वृद्धि जैसे दीर्ग कामों में टिकाऊ नियंत्रण रखते हैं।",
     "Nerves deliver lightning-quick; hormones work slowly yet hold durable control in long jobs like growth."),

    ("endocrine-system", "medium",
     "वृषणों और अंडाशयों की अंतःस्रावी भूमिका क्या है?",
     "What is the endocrine role of the testes and ovaries?",
     ["वे अपने हार्मोन (टेस्टोस्टेरोन/एस्ट्रोजन) रक्त में छोड़ते हैं", "वे केवल पाचक रस बनाते हैं", "वे रुधिर छानते हैं", "वे वायु छानते हैं"],
     ["They release their hormones (testosterone/oestrogen) into blood", "They only make digestive juice", "They filter blood", "They filter air"],
     0,
     "प्रजनन कोशिकाओं के साथ-साथ ये ग्रंथियाँ यौवन-हार्मोन भी देती हैं — दोहरी ज़िम्मेदारी।",
     "Besides reproductive cells these glands also yield the puberty hormones — a double duty."),

    ("endocrine-system", "medium",
     "किसी हार्मोन का 'लक्ष्य अंग' (target organ) किसे कहते हैं?",
     "What is called the 'target organ' of a hormone?",
     ["वह विशिष्ट अंग जिस पर वह हार्मोन अपना प्रभाव डालता है", "वह अंग जो हार्मोन खा जाता है", "वह अंग जो हार्मोन बनाता है", "वह अंग जो हार्मोन को बर्फ में रखता है"],
     ["The specific organ on which that hormone casts its effect", "The organ that eats the hormone", "The organ that makes the hormone", "The organ that stores hormone in ice"],
     0,
     "हर हार्मोन का अपना पता-लिखा दरवाज़ा होता है — इंसुलिन की चिट्ठी शर्करा-कोशिकाओं के नाम।",
     "Every hormone has an addressed door — insulin's letter is written in the name of sugar-cells."),

    ("endocrine-system", "medium",
     "थायरॉइड ग्रंथि शरीर में कहाँ स्थित है?",
     "Where is the thyroid gland situated in the body?",
     ["गले के आगे, वायु-नली के दोनों ओर", "पीठ के निचले भाग में", "मस्तिष्क के भीतर गहरे", "पैरों की एड़ियों में"],
     ["In front of the neck, flanking the windpipe", "In the lower back", "Deep inside the brain", "In the heels of the feet"],
     0,
     "गले की आगे-भित्ति पर तितली-आकार थायरॉइड श्वास-नली को गले करती बैठी है।",
     "On the front wall of the neck a butterfly-shaped thyroid hugs the windpipe."),

    ("endocrine-system", "medium",
     "इंसुलिन की कमी होने पर रक्त में क्या होता है?",
     "What happens to blood when insulin falls short?",
     ["शर्करा का स्तर बढ़ जाता है", "शर्करा पूरी तरह समाप्त हो जाती है", "रुधिर नीला पड़ जाता है", "रुधिर जम जाता है"],
     ["The sugar level rises", "Sugar vanishes completely", "Blood turns blue", "Blood clots"],
     0,
     "इंसुलिन के बिना कोशिकाएँ शर्करा भली-भाँति ग्रहण नहीं कर पातीं — शर्करा रक्त में ही जमा होती जाती है।",
     "Without insulin cells cannot properly take up sugar — it keeps piling up in the blood."),

    ("endocrine-system", "medium",
     "शरीर में हार्मोन की मात्रा संतुलित रहना क्यों आवश्यक है?",
     "Why must the amount of hormones stay balanced in the body?",
     ["कमी या अधिकता — दोनों ही शरीर की क्रियाओं को बिगाड़ सकती हैं", "क्योंकि हार्मोन बासी हो जाते हैं", "क्योंकि हार्मोन बहुत महँगे होते हैं", "क्योंकि इनसे रंग बदलता है"],
     ["Deficiency or excess — both can derange body functions", "Because hormones go stale", "Because hormones are costly", "Because they change colour"],
     0,
     "हार्मोन दवा नहीं, अनुपात हैं — ग्रंथि से निकलने वाली हर बूँद शरीर के पैमाने पर तौली जाती है।",
     "Hormones are not medicine but proportion — every drop from a gland is weighed on the body's scale."),

    ("endocrine-system", "medium",
     "शरीर का समग्र समन्वय किन दो प्रणालियों के सहयोग से चलता है?",
     "By the teamwork of which two systems does the body's overall coordination run?",
     ["तंत्रिका तंत्र और अंतःस्रावी तंत्र", "पाचन तंत्र और त्वचा", "अस्थि तंत्र और रुधिर", "मांसपेशियाँ और बाल"],
     ["The nervous system and the endocrine system", "The digestive system and skin", "The skeletal system and blood", "Muscles and hair"],
     0,
     "बिजली-दौड़ नसें और रसायन-बहार हार्मोन — दोनों मिलकर शरीर का संचालन-मंडल बनाते हैं।",
     "Lightning-running nerves and chemical-flowing hormones — together they form the body's steering circle."),

    ("endocrine-system", "medium",
     "मेंढक के लार्वा (टैडपोल) का वयस्क मेंढक में रूपांतरण किस हार्मोन पर निर्भर करता है?",
     "The transformation of a tadpole into an adult frog depends on which hormone?",
     ["थायरॉक्सिन", "इंसुलिन", "एड्रेनालिन", "वृद्धि हार्मोन"],
     ["Thyroxine", "Insulin", "Adrenaline", "Growth hormone"],
     0,
     "थायरॉक्सिन की उपस्थिति में ही पूँछ जाती है, पैर आते हैं — रूपांतरण की घड़ी इसी से चलती है।",
     "Only in thyroxine's presence does the tail go and legs come — the clock of metamorphosis runs on it."),

    ("endocrine-system", "medium",
     "एड्रेनालिन का स्रावण किन क्षणों में बढ़ जाता है?",
     "At which moments does adrenaline secretion shoot up?",
     ["भय, क्रोध या खतरे के क्षणों में", "गहरी नींद में", "भोजन पचाते समय", "पढ़ते-लिखते समय"],
     ["In moments of fear, anger or danger", "In deep sleep", "While digesting food", "While reading and writing"],
     0,
     "डर-गुस्सा-खतरा तीनों घंटियाँ अधिवृक्क पर एक साथ बजती हैं — एड्रेनालिन की बाढ़ आ जाती है।",
     "Fear-anger-danger ring three bells on the adrenal at once — a flood of adrenaline arrives."),

    ("endocrine-system", "medium",
     "पिट्यूटरी ग्रंथि के नियंत्रण-वृत्त में मुख्यतः कौन-सी ग्रंथियाँ आती हैं?",
     "Which glands mainly fall inside the pituitary's circle of control?",
     ["थायरॉइड, अधिवृक्क और योनि-ग्रंथियाँ", "केवल स्वेद-ग्रंथियाँ", "केवल लार-ग्रंथियाँ", "केवल यकृत"],
     ["The thyroid, adrenals and sex glands", "Only sweat glands", "Only salivary glands", "Only the liver"],
     0,
     "मास्टर की मुट्ठी में बड़े खिलाड़ी — थायरॉइड से लेकर योनि-ग्रंथियों तक सबके पत्र उसी के डाकखाने से।",
     "Big players in the master's fist — from thyroid to sex glands, all their mail goes through its post office."),

    ("endocrine-system", "medium",
     "बच्चों में थायरॉक्सिन की लंबी कमी रहने पर क्या प्रभाव दिख सकता है?",
     "What effect can a long thyroxine shortage show in children?",
     ["शारीरिक और मानसिक वृद्धि धीमी पड़ सकती है", "बाल काले हो जाते हैं", "आँखें नीली हो जाती हैं", "कद रातोंरात दुगना"],
     ["Physical and mental growth can slow down", "Hair turns black", "Eyes turn blue", "Height doubles overnight"],
     0,
     "थायरॉक्सिन वृद्धि की रेल का इंजन है — कम पड़ा तो गाड़ी धीमी, बच्चे का विकास भी धीमा।",
     "Thyroxine is the engine of the growth-train — short supply slows the train and the child's development."),

    ("endocrine-system", "medium",
     "निम्न हार्मोन-कार्य युग्मों में से कौन-सा सही नहीं है?",
     "Which of these hormone-function pairs is INCORRECT?",
     ["एड्रेनालिन — शरीर को सुस्त बनाना", "इंसुलिन — रक्त-शर्करा घटाना", "थायरॉक्सिन — चयापचय नियंत्रण", "वृद्धि हार्मोन — शरीर की वृद्धि"],
     ["Adrenaline — making the body sluggish", "Insulin — lowering blood sugar", "Thyroxine — controlling metabolism", "Growth hormone — growth of the body"],
     0,
     "एड्रेनालिन सुस्त नहीं, सतर्क बनाता है — बाकी तीन जोड़े सही हैं।",
     "Adrenaline makes the body alert, not sluggish — the other three pairs are correct."),

    ("endocrine-system", "medium",
     "स्वेद-ग्रंथि और थायरॉइड के बीच का मूल अंतर क्या है?",
     "What is the basic difference between a sweat gland and the thyroid?",
     ["स्वेद-ग्रंथि नलीदार (बाह्यस्रावी) है, थायरॉइड नलीहीन (अंतःस्रावी)", "स्वेद-ग्रंथि रक्त में स्राव छोड़ती है", "थायरॉइड त्वचा पर स्राव छोड़ता है", "दोनों में कोई अंतर नहीं"],
     ["A sweat gland is ducted (exocrine), the thyroid is ductless (endocrine)", "A sweat gland pours secretion into blood", "The thyroid pours secretion onto skin", "There is no difference"],
     0,
     "स्वेद त्वचा की सतह पर नली से बहता है; थायरॉक्सिन रक्त की धारा में घुलता है — रास्ते ही अलग।",
     "Sweat flows through a duct onto skin; thyroxine dissolves into the bloodstream — different roads altogether."),

    ("endocrine-system", "medium",
     "हार्मोनी नियंत्रण किस प्रकार के शारीरिक कार्यों के लिए सर्वाधिक उपयुक्त माना जाता है?",
     "Hormonal control is considered most suited for which kind of body-jobs?",
     ["धीमे, दीर्घकालिक परिवर्तन जैसे वृद्धि और यौवन", "पलक झपकाने जैसे तत्काल कार्य", "घुटने मोड़ने जैसे झटके", "आँख की पुतली फैलाना"],
     ["Slow, long-term changes like growth and puberty", "Instant jobs like blinking", "Jerks like bending the knee", "Dilating the pupil"],
     0,
     "जो काम वर्षों में बनते हैं — लंबाई, रूप, परिपक्वता — उनकी बागडोर हार्मोन के हाथ में रहती है।",
     "Works built over years — height, form, maturity — remain in hormones' charge."),

    ("endocrine-system", "medium",
     "भोजन के तुरंत बाद रक्त-शर्करा बढ़ती है — शरीर उसे संतुलित करने हेतु क्या करता है?",
     "Right after a meal blood sugar rises — what does the body do to balance it?",
     ["अग्न्याशय से इंसुलिन का स्रावण बढ़ा देता है", "इंसुलिन रोक देता है", "थायरॉइड निकाल देता है", "रुधिर को बाहर निकाल देता है"],
     ["It increases insulin secretion from the pancreas", "It stops insulin", "It removes the thyroid", "It drains the blood out"],
     0,
     "मीठा बढ़ा → इंसुलिन बहा → शर्करा कोशिकाओं में उतरी → स्तर फिर संतुलित — स्वतः-नियमन का जीता-जागता नमूना।",
     "Sweet rises → insulin flows → sugar enters cells → level rebalances — a living specimen of self-regulation."),

    ("endocrine-system", "medium",
     "अंतःस्रावी ग्रंथियों में रुधिर वाहिकाओं का जाल विशेष सघन क्यों होता है?",
     "Why is the network of blood vessels specially dense in endocrine glands?",
     ["क्योंकि उनका हार्मोन सीधे रक्त में जाना होता है", "क्योंकि वे हवा भंडारित करती हैं", "क्योंकि वे रुधिर बनाती हैं", "क्योंकि वे पाचन करती हैं"],
     ["Because their hormone has to pass straight into blood", "Because they store air", "Because they make blood", "Because they digest"],
     0,
     "जिस ग्रंथि का माल रक्त के डाक-तार से जाएगा, उसके घर डाकघर की गली में होना ही होगा — सघन वाहिका-जाल वही डाक-गली है।",
     "The gland whose goods travel by blood's postal wire must live by the post-office lane — the dense vessel-net is that very lane."),

    ("endocrine-system", "medium",
     "शरीर में किसी हार्मोन की मात्रा आवश्यकता से अधिक हो जाए, तो शरीर की प्रवृत्ति क्या होती है?",
     "If a hormone's amount exceeds the need, what is the body's tendency?",
     ["उसके स्रावण को घटाकर संतुलन बनाना", "और अधिक स्रावित करना", "ग्रंथि को बाहर निकाल देना", "रुधिर को जमने देना"],
     ["To cut its secretion and restore balance", "To secrete even more", "To eject the gland", "To let the blood clot"],
     0,
     "शरीर रसोई की तरह चलता है — नमक ज्यादा गिरा तो अगली चुटकी छोटी; हार्मोन-स्राव भी माँग-देख कर घटता-बढ़ता है।",
     "The body runs like a kitchen — extra salt dropped, the next pinch smaller; hormone secretion too shrinks and swells watching demand."),

    ("endocrine-system", "hard",
     "निम्न ग्रंथि-स्थान युग्मों में से कौन-सा गलत है?",
     "Which gland-location pair is WRONG?",
     ["पिट्यूटरी — गुर्दे के ऊपर", "थायरॉइड — गले में", "अधिवृक्क — गुर्दे के ऊपर", "अग्न्याशय — पेट में"],
     ["Pituitary — atop the kidney", "Thyroid — in the neck", "Adrenal — atop the kidney", "Pancreas — in the abdomen"],
     0,
     "पिट्यूटरी मस्तिष्क के नीचे बैठती है, गुर्दे के ऊपर नहीं — गुर्दे की टोपी अधिवृक्क की है।",
     "The pituitary sits below the brain, not atop the kidney — the kidney's cap belongs to the adrenal."),

    ("endocrine-system", "hard",
     "टैडपोल में थायरॉक्सिन का निर्माण रुक जाए, तो क्या होगा?",
     "If thyroxine production stops in a tadpole, what will happen?",
     ["रूपांतरण रुक जाएगा — वयस्क मेंढक नहीं बन पाएगा", "टैडपोल तुरंत मेंढक बन जाएगा", "टैडपोल का आकार दुगना हो जाएगा", "कुछ नहीं बदलेगा"],
     ["Metamorphosis halts — it cannot become an adult frog", "It instantly becomes a frog", "Its size doubles", "Nothing changes"],
     0,
     "रूपांतरण की सारी कला थायरॉक्सिन के कैनवास पर बनती है — रंग ही न मिले तो चित्र कैसा!",
     "The whole art of metamorphosis is drawn on thyroxine's canvas — no paint, no picture!"),

    ("endocrine-system", "hard",
     "पिट्यूटरी की विशेषता बताइए — उसका दायरा कितना व्यापक है?",
     "State the pituitary's speciality — how wide is its domain?",
     ["वृद्धि से लेकर अन्य ग्रंथियों के नियंत्रण तक — सर्वाधिक व्यापक अंतःस्रावी अधिकार", "केवल एक अंग तक सीमित", "केवल पाचन तक सीमित", "केवल नींद तक सीमित"],
     ["From growth to controlling other glands — the widest endocrine authority", "Limited to a single organ", "Limited to digestion", "Limited to sleep"],
     0,
     "छोटे-से दाने में इतना अधिकार — शरीर की वृद्धि भी उसकी, ग्रंथियों की सलाह भी उसकी।",
     "Such authority in a tiny seed — the body's growth is its brief, and the glands' counsel too."),

    ("endocrine-system", "hard",
     "एक ही ग्रंथि ऐसी है जो 'दूत' भी है और 'मास्टर' भी — सोचकर बताइए यह कौन है और क्यों?",
     "One gland is both a 'messenger' and a 'master' — think and tell, which one and why?",
     ["पिट्यूटरी — स्वयं हार्मोन बनाती है और दूसरी ग्रंथियों को भी नियंत्रित करती है", "स्वेद-ग्रंथि — दोनों काम करती है", "लार-ग्रंथि — दोनों काम करती है", "ऐसी कोई ग्रंथि नहीं"],
     ["The pituitary — it makes its own hormones AND controls other glands", "The sweat gland — does both", "The salivary gland — does both", "No such gland exists"],
     0,
     "पिट्यूटरी दोहरी पहचान रखती है — अपने हार्मोन की फौज भी उसकी, ग्रंथि-जगत की कमान भी उसकी।",
     "The pituitary holds a twin identity — an army of its own hormones and the command of the gland-world."),

    # ================= PUBERTY & ADOLESCENCE — 30 (E10/M17/H3) =================
    ("puberty-adolescence", "easy",
     "किशोरावस्था (adolescence) प्रायः किस आयु-सीमा में मानी जाती है?",
     "In which age range is adolescence usually placed?",
     ["लगभग 11 से 17 वर्ष", "1 से 5 वर्ष", "30 से 40 वर्ष", "60 से 70 वर्ष"],
     ["About 11 to 17 years", "1 to 5 years", "30 to 40 years", "60 to 70 years"],
     0,
     "ग्यारह से सत्रह के बीच का दौर किशोरावस्था कहलाता है — बचपन और वयस्कता का पुल।",
     "The span between eleven and seventeen is called adolescence — the bridge of childhood and adulthood."),

    ("puberty-adolescence", "easy",
     "यौवनारंभ (puberty) कब कहा जाता है?",
     "When is the stage called puberty?",
     ["जब शरीर यौवन-परिवर्तनों के साथ प्रजनन की ओर परिपक्व होने लगता है", "जब बच्चा चलना सीखता है", "जब पहला दाँत आता है", "जब बाल सफेद होते हैं"],
     ["When the body begins maturing towards reproduction with the changes of puberty", "When a child learns to walk", "When the first tooth comes", "When hair turns grey"],
     0,
     "यौवनारंभ वह द्वार-क्षण है जब शरीर 'बच्चा' छोड़कर 'किशोर' की गली में कदम रखता है।",
     "Puberty is the doorway-moment when the body steps out of 'child' street into 'adolescent' lane."),

    ("puberty-adolescence", "easy",
     "किशोरावस्था मुख्यतः किस संक्रमण का काल है?",
     "Adolescence is mainly the period of transition between what?",
     ["बाल्यावस्था और वयस्कता के बीच", "वयस्कता और वृद्धावस्था के बीच", "शैशवावस्था और बाल्यावस्था के बीच", "जन्म और शैशवावस्था के बीच"],
     ["Between childhood and adulthood", "Between adulthood and old age", "Between infancy and childhood", "Between birth and infancy"],
     0,
     "न बच्चा, न बड़ा — बीच का यह तटबंध ही किशोरावस्था है, जहाँ दोनों किनारों से लहरें आती हैं।",
     "Neither child nor grown — this in-between embankment is adolescence, waves arriving from both shores."),

    ("puberty-adolescence", "easy",
     "किशोरावस्था के शारीरिक परिवर्तन मुख्यतः किसके नियंत्रण में होते हैं?",
     "The bodily changes of adolescence are controlled mainly by what?",
     ["हार्मोनों के", "केवल आदतों के", "केवल मौसम के", "केवल विद्यालय के"],
     ["Hormones", "Only habits", "Only the weather", "Only the school"],
     0,
     "इस उम्र की हर धड़कन-बदलाव के पीछे हार्मोन का हाथ है — टेस्टोस्टेरोन और एस्ट्रोजन आगे बढ़े सूत्रधार।",
     "Behind every changed beat of this age is the hand of hormones — testosterone and oestrogen lead as directors."),

    ("puberty-adolescence", "easy",
     "लड़की में पहली बार मासिक धर्म के आरंभ को क्या कहते हैं?",
     "What is the onset of the first menstruation in a girl called?",
     ["मेनार्क", "रजोनिवृत्ति", "ओव्यूलेशन", "गर्भाधान"],
     ["Menarche", "Menopause", "Ovulation", "Conception"],
     0,
     "पहली बार आया मासिक धर्म मेनार्क है — किशोरी के प्रजनन-जीवन का पहला घंटाघर।",
     "The first-ever menstruation is menarche — the first milestone of an adolescent girl's reproductive life."),

    ("puberty-adolescence", "easy",
     "लड़कों में यौवन-परिवर्तन लाने वाला मुख्य हार्मोन कौन-सा है?",
     "Which is the chief hormone bringing puberty changes in boys?",
     ["टेस्टोस्टेरोन", "एस्ट्रोजन", "इंसुलिन", "थायरॉक्सिन"],
     ["Testosterone", "Oestrogen", "Insulin", "Thyroxine"],
     0,
     "लड़कों के यौवन का ड्रम-बीट टेस्टोस्टेरोन की छड़ी से बजता है।",
     "The drumbeat of boys' puberty plays from testosterone's baton."),

    ("puberty-adolescence", "easy",
     "लड़कियों में यौवन-परिवर्तन मुख्यतः किस हार्मोन के प्रभाव से आते हैं?",
     "Puberty changes in girls come mainly under the influence of which hormone?",
     ["एस्ट्रोजन", "टेस्टोस्टेरोन", "एड्रेनालिन", "इंसुलिन"],
     ["Oestrogen", "Testosterone", "Adrenaline", "Insulin"],
     0,
     "एस्ट्रोजन लड़कियों के शरीर में यौवन की बुनाई करता है — स्तन, कूल्हे, मासिक चक्र सब उसी की कताई।",
     "Oestrogen weaves puberty in a girl's body — breasts, hips, the menstrual cycle, all its spinning."),

    ("puberty-adolescence", "easy",
     "जन्म के बाद शरीर की सबसे तेज़ ऊँचाई-वृद्धि (growth spurt) प्रायः किस अवस्था में दिखती है?",
     "The fastest spurt of height after birth usually appears in which stage?",
     ["किशोरावस्था में", "पहले महीने में", "वृद्धावस्था में", "भ्रूणावस्था के बाद तुरंत"],
     ["In adolescence", "In the first month", "In old age", "Right after the embryonic stage"],
     0,
     "किशोरावस्था दूसरी तेज़ बढ़वार का मौसम है — कुछ महीनों में पतलून छोटे पड़ने लगते हैं।",
     "Adolescence is the season of the second growth-surge — trousers start falling short within months."),

    ("puberty-adolescence", "easy",
     "औसतन यौवनारंभ लड़कियों में लड़कों की तुलना में कब होता है?",
     "On average, does puberty begin in girls compared to boys?",
     ["जल्दी (कुछ वर्ष पहले)", "बहुत देर से", "ठीक उसी आयु में", "कभी नहीं"],
     ["Earlier (by a couple of years)", "Much later", "At exactly the same age", "Never"],
     0,
     "लड़कियों में यौवन की घंटी प्रायः दो-एक वर्ष पहले बजती है — इसीलिए उस उम्र में लड़कियाँ लंबी दिखती हैं।",
     "The puberty bell rings in girls a year or two earlier — that is why girls look taller at that age."),

    ("puberty-adolescence", "easy",
     "क्या यौवनारंभ की आयु सब लड़कों-लड़कियों में एक ही होती है?",
     "Is the age of puberty onset identical in all boys and girls?",
     ["नहीं — व्यक्ति से व्यक्ति भिन्नता सामान्य है", "हाँ, सबमें एक ही दिन", "हाँ, सबमें एक ही महीना", "यह केवल लड़कों में भिन्न होता है"],
     ["No — variation from person to person is normal", "Yes, the same day for all", "Yes, the same month for all", "It varies only in boys"],
     0,
     "किसी का यौवन 11 में, किसी का 14 में — दोनों सामान्य; शरीर अपनी घड़ी अपनी गति से चलाता है।",
     "Someone's puberty at 11, another's at 14 — both normal; the body runs its clock at its own pace."),

    ("puberty-adolescence", "medium",
     "मानव-जीवन की अवस्थाओं का सही क्रम कौन-सा है?",
     "Which is the correct order of the stages of human life?",
     ["शैशवावस्था → बाल्यावस्था → किशोरावस्था → वयस्कता", "किशोरावस्था → शैशवावस्था → बाल्यावस्था → वयस्कता", "वयस्कता → किशोरावस्था → बाल्यावस्था → शैशवावस्था", "बाल्यावस्था → शैशवावस्था → वयस्कता → किशोरावस्था"],
     ["Infancy → childhood → adolescence → adulthood", "Adolescence → infancy → childhood → adulthood", "Adulthood → adolescence → childhood → infancy", "Childhood → infancy → adulthood → adolescence"],
     0,
     "जीवन की सीढ़ियाँ क्रम में चढ़ती हैं — शिशु, बालक, किशोर, फिर वयस्क।",
     "Life's stairs are climbed in order — infant, child, adolescent, then adult."),

    ("puberty-adolescence", "medium",
     "यौवनारंभ की आयु में व्यक्तिगत भिन्नता के प्रमुख कारण क्या हैं?",
     "What are the chief reasons for individual variation in the age of puberty onset?",
     ["पोषण, आनुवंशिकता और सामान्य स्वास्थ्य", "पड़ोस का रंग", "जूते का नंबर", "स्कूल की इमारत"],
     ["Nutrition, heredity and general health", "The colour of the neighbourhood", "The shoe size", "The school building"],
     0,
     "अच्छा भोजन और वंशानुक्रम — दोनों मिलकर यौवन की घड़ी पहले-बाद चलाते हैं।",
     "Good food and heredity — together they run the puberty clock early or late."),

    ("puberty-adolescence", "medium",
     "किशोरावस्था के growth spurt में शरीर में मुख्यतः क्या-क्या बढ़ता है?",
     "What mainly increases in the body during the adolescent growth spurt?",
     ["ऊँचाई, भार और मांसपेशियाँ तीनों", "केवल बाल", "केवल आँखें", "केवल आवाज़"],
     ["Height, weight and muscles — all three", "Only hair", "Only the eyes", "Only the voice"],
     0,
     "लंबाई खिंचती है, वज़न बैठता है, मांसपेशियाँ जुड़ती हैं — त्रिवेणी वृद्धि एक साथ बहती है।",
     "Length stretches, weight settles, muscles join — a triveni of growth flows together."),

    ("puberty-adolescence", "medium",
     "किशोरों में मूड में उतार-चढ़ाव (mood swings) आने का मुख्य शारीरिक कारण क्या है?",
     "What is the main bodily cause of mood swings in adolescents?",
     ["बदलते हार्मोन-स्तर का मस्तिष्क पर प्रभाव", "पानी की कमी", "जूतों की गंध", "दीवार का रंग"],
     ["The effect of shifting hormone levels on the brain", "Lack of water", "Smell of shoes", "Colour of the wall"],
     0,
     "हार्मोन का ज्वार-भाटा मस्तिष्क के समुद्र तक लहरें भेजता है — भावनाएँ उसी से थिरकती हैं।",
     "The tide of hormones sends waves up to the brain's sea — emotions sway with it."),

    ("puberty-adolescence", "medium",
     "किशोरावस्था में मानसिक परिवर्तनों में कौन-सा सम्मिलित है?",
     "Which of these is included among the mental changes of adolescence?",
     ["सोचने और निर्णय लेने की क्षमता में वृद्धि", "आँखों का रंग बदलना", "कद घटना", "दाँत झड़ना"],
     ["Growth in the capacity to think and decide", "Change of eye colour", "Height decreasing", "Teeth falling"],
     0,
     "इस उम्र में दिमाग का दर्पण तेज़ होता है — प्रश्न बढ़ते हैं, तर्क गहरे होते हैं, निर्णय अपने बनते हैं।",
     "In this age the brain's mirror sharpens — questions multiply, reasoning deepens, decisions become one's own."),

    ("puberty-adolescence", "medium",
     "किशोरावस्था के सामाजिक परिवर्तनों में प्रमुखतः क्या दिखता है?",
     "What is prominently seen among the social changes of adolescence?",
     ["मित्रों के साथ लगाव और उत्तरदायित्व की भावना में वृद्धि", "केवल खिलौनों में रुचि", "केवल नींद में वृद्धि", "केवल रुलाई"],
     ["Attachment to friends and a growing sense of responsibility", "Interest only in toys", "Only an increase in sleep", "Only crying"],
     0,
     "दुनिया घर से फैलती है — संगी मिलते हैं, जिम्मेदारियों के धागे हाथ में आते हैं।",
     "The world spreads beyond home — companions arrive, threads of responsibility come to hand."),

    ("puberty-adolescence", "medium",
     "किशोर का चिड़चिड़ापन या भावनात्मक उतार-चढ़ाव देखकर उसे समझना क्यों जरूरी है?",
     "Why is it important to understand an adolescent's irritability or emotional ups and downs?",
     ["यह हार्मोन-प्रभावित सामान्य प्रक्रिया है — डाँट से नहीं, सहयोग से सधती है", "यह बीमारी है जिसका ऑपरेशन होता है", "यह स्थायी स्वभाव बन जाता है", "यह केवल लड़कों में होता है"],
     ["It is a normal hormone-influenced process — it settles with support, not scolding", "It is a disease needing surgery", "It becomes permanent nature", "It occurs only in boys"],
     0,
     "बदलते हार्मोन की ऋतु में मौसम ऐसा बदलता है — समझदारी से छत देना जरूरी है, तूफान का दोष नहीं।",
     "In the season of shifting hormones the weather changes so — a roof of understanding is needed, not blame for the storm."),

    ("puberty-adolescence", "medium",
     "किशोरावस्था के परिवर्तन एक बार में रातोंरात आ जाते हैं — यह कथन कैसा है?",
     "Adolescent changes arrive overnight all at once — how is this statement?",
     ["गलत — ये परिवर्तन कई वर्षों में क्रमशः आते हैं", "बिल्कुल सही", "आधा सही आधा गलत", "केवल लड़कियों के लिए सही"],
     ["Wrong — these changes come gradually over several years", "Absolutely right", "Half right, half wrong", "Right only for girls"],
     0,
     "यौवन कोई स्विच नहीं, ऋतु है — कई बरसों की धूप-छाँव में रूप बनता है।",
     "Puberty is not a switch but a season — the form is built over years of sun and shade."),

    ("puberty-adolescence", "medium",
     "किशोरावस्था में जिज्ञासा और नए प्रयोग करने की प्रवृत्ति को सही दिशा कैसे दी जाती है?",
     "How is the adolescent tendency of curiosity and experimentation channelled rightly?",
     ["खेल, कला, विज्ञान जैसे रचनात्मक क्षेत्रों में सक्रिय भागीदारी से", "सब प्रयोग रोककर", "टीवी देखकर ही", "खाना-सोकर"],
     ["Through active participation in creative fields like sports, arts and science", "By banning all experiments", "Only by watching TV", "Only by eating and sleeping"],
     0,
     "जिज्ञासा की नदी को बाँधना नहीं, मोड़ना चाहिए — मैदान, मंच और प्रयोगशाला उसके सही ग्राह्य-खाते हैं।",
     "The river of curiosity should be turned, not dammed — field, stage and lab are its right channels."),

    ("puberty-adolescence", "medium",
     "किशोरावस्था के शारीरिक-मानसिक परिवर्तनों को समझना किशोर के लिए क्यों उपयोगी है?",
     "Why is understanding the bodily-mental changes useful for an adolescent?",
     ["आत्मविश्वास बनता है और भ्रम-मिथकों से बचा जा सकता है", "इससे आयु बढ़ती है", "इससे कद घटता है", "इससे परीक्षा टल जाती है"],
     ["It builds self-confidence and keeps confusion-myths away", "It increases lifespan", "It reduces height", "It cancels exams"],
     0,
     "जाना-समझा बदलाव डराता नहीं — शरीर की बात जानने वाला किशोर मिथकों की गली में नहीं भटकता।",
     "A known change does not frighten — an adolescent who knows his body's story does not stray into myths' lane."),

    ("puberty-adolescence", "medium",
     "किशोरावस्था में मस्तिष्क की परिपक्वता शारीरिक वृद्धि की तुलना में कैसी चलती है?",
     "How does the brain's maturation in adolescence proceed compared to physical growth?",
     ["मस्तिष्क की परिपक्वता धीरे-धीरे और शरीर से पीछे चलती रहती है", "दोनों एक ही दिन पूरे हो जाते हैं", "मस्तिष्क पहले पूर्ण परिपक्व हो जाता है", "मस्तिष्क परिपक्व ही नहीं होता"],
     ["The brain matures slowly, lagging behind the body", "Both finish on the same day", "The brain matures fully first", "The brain never matures"],
     0,
     "शरीर जल्दी बड़ा, समझ धीरे-धीरे — इसी अंतराल में मार्गदर्शन सहारा बनता है।",
     "Body grows fast, judgement slowly — guidance becomes the support inside this very gap."),

    ("puberty-adolescence", "medium",
     "किशोरावस्था में भूख क्यों बढ़ जाती है?",
     "Why does appetite increase in adolescence?",
     ["तेज़ वृद्धि और ऊर्जा-खर्च की माँग बढ़ जाती है", "पाचन रुक जाता है", "नींद समाप्त हो जाती है", "आँखें कमजोर हो जाती हैं"],
     ["The demand of rapid growth and energy expenditure rises", "Digestion stops", "Sleep ends", "Eyes weaken"],
     0,
     "बढ़ते शरीर की ईंट-गारे की जरूरत खाने से ही मिलती है — भूख वृद्धि की मजदूरी है।",
     "The bricks-mortar of a growing body come only from food — appetite is growth's wage."),

    ("puberty-adolescence", "medium",
     "किशोर के अपने शरीर के प्रति सकारात्मक दृष्टिकोण (self-image) क्यों जरूरी है?",
     "Why is a positive self-image about one's own body important for an adolescent?",
     ["हर शरीर अपनी गति से बदलता है — तुलना से नहीं, स्वीकार से आत्मविश्वास बनता है", "इससे कद बढ़ता है", "इससे यौवन रुक जाता है", "इससे भूख खत्म हो जाती है"],
     ["Every body changes at its own pace — confidence comes from acceptance, not comparison", "It increases height", "It stops puberty", "It ends appetite"],
     0,
     "दूसरों से तौला हुआ किशोर हमेशा घटता है — अपनी तराज़ू पर तौलने से ही संतुलन बनता है।",
     "An adolescent weighed against others always falls short — balance comes only from being weighed on one's own scale."),

    ("puberty-adolescence", "medium",
     "किशोरावस्था के प्रश्नों पर माता-पिता अथवा शिक्षकों से खुलकर बात करना क्यों सहायक है?",
     "Why is it helpful to talk openly with parents or teachers about adolescent questions?",
     ["विश्वसनीय जानकारी मिलती है और अनावश्यक चिंता दूर होती है", "इससे स्कूल छूट जाता है", "इससे यौवन जल्दी आता है", "इससे भोजन मुफ्त मिलता है"],
     ["One gets trustworthy information and needless worry goes away", "It gets school cancelled", "It brings puberty earlier", "It gets free food"],
     0,
     "घर-विद्यालय का दरवाज़ा खुला रखने वाला किशोर अफवाहों के बाजार में नहीं खरीदारी करता।",
     "An adolescent who keeps the home-school door open does not shop in the bazaar of rumours."),

    ("puberty-adolescence", "medium",
     "किशोरावस्था में नई क्षमताओं (संगीत, खेल, लेखन) का विकास किस श्रेणी का उदाहरण है?",
     "The development of new capacities (music, sports, writing) in adolescence is an example of which category?",
     ["विकास (development) — कार्य-कौशल की परिपक्वता", "केवल वृद्धि (growth)", "केवल आयु-गणना", "केवल त्वचा-परिवर्तन"],
     ["Development — the maturation of functional skill", "Only growth", "Only counting of age", "Only a change of skin"],
     0,
     "लंबाई वृद्धि है, कौशल विकास — दोनों अलग डिब्बे हैं, दोनों जरूरी हैं।",
     "Height is growth, skill is development — two separate boxes, both necessary."),

    ("puberty-adolescence", "medium",
     "किशोर अब भी पूर्ण वयस्क नहीं होता — इस अवस्था में उसे क्या सीखना चाहिए?",
     "An adolescent is not yet a full adult — what should be learnt at this stage?",
     ["संयम और जिम्मेदार निर्णय लेने का अभ्यास", "सब काम इच्छा से करना", "वयस्कों की अनदेखी करना", "रात भर जागना"],
     ["The practice of restraint and responsible decision-making", "Doing everything on impulse", "Ignoring adults", "Staying awake all night"],
     0,
     "आज़ादी के पहाड़ पर चढ़ने वाले को रस्सी-संयम भी पकड़ना होता है — किशोरावस्था वही अभ्यास-मैदान है।",
     "The climber of freedom's hill must also grip the rope of restraint — adolescence is that practice-ground."),

    ("puberty-adolescence", "medium",
     "लड़के-लड़कियों दोनों में किशोरावस्था के सामान्य शारीरिक परिवर्तनों में कौन-सा सम्मिलित है?",
     "Which is included among the ordinary bodily changes of adolescence in BOTH boys and girls?",
     ["ऊँचाई-वृद्धि, शरीर पर बाल और त्वचा में बदलाव", "केवल दाढ़ी आना", "केवल स्तन-विकास", "केवल आवाज़ भारी होना"],
     ["Increase in height, body hair and changes in skin", "Only the appearance of a beard", "Only breast development", "Only deepening of voice"],
     0,
     "कुछ बदलाव दोनों के साझे हैं — लंबाई, केश, त्वचा; कुछ अलग — दाढ़ी या स्तन।",
     "Some changes are shared by both — height, hair, skin; some are distinct — beard or breast."),

    ("puberty-adolescence", "hard",
     "किशोरावस्था और यौवनारंभ में मूल अंतर क्या है?",
     "What is the basic difference between adolescence and puberty?",
     ["किशोरावस्था पूरी अवधि है, यौवनारंभ उसकी शुरुआत का द्वार-क्षण", "दोनों एक ही का दो नाम हैं", "यौवनारंभ लंबी अवधि है, किशोरावस्था क्षण", "दोनों में कोई संबंध नहीं"],
     ["Adolescence is the whole period; puberty is the doorway-moment of its beginning", "Both are two names of the same thing", "Puberty is the long period, adolescence a moment", "The two are unrelated"],
     0,
     "किशोरावस्था पूरी सड़क है; यौवनारंभ उस पर पहला मोड़ — जहाँ से शरीर नया मोड़ लेता है।",
     "Adolescence is the whole road; puberty its first turning — where the body takes a new bend."),

    ("puberty-adolescence", "hard",
     "12 वर्ष की एक लड़की में यौवन-परिवर्तन दिख रहे हैं — उसके शरीर में प्रधानतः कौन-सा हार्मोन काम कर रहा होगा?",
     "Puberty changes are appearing in a 12-year-old girl — which hormone is predominantly at work in her body?",
     ["अंडाशय से स्रावित एस्ट्रोजन", "वृषण से स्रावित टेस्टोस्टेरोन", "अधिवृक्क से स्रावित एड्रेनालिन", "थायरॉइड से स्रावित थायरॉक्सिन"],
     ["Oestrogen secreted by the ovaries", "Testosterone secreted by the testes", "Adrenaline secreted by the adrenal", "Thyroxine secreted by the thyroid"],
     0,
     "लड़की का यौवन-मंच एस्ट्रोजन संचालित करता है — स्रोत उसके अंडाशय।",
     "A girl's puberty-stage is run by oestrogen — the source being her ovaries."),

    ("puberty-adolescence", "hard",
     "किशोरावस्था संबंधी निम्न में से कौन-सा कथन गलत है?",
     "Which statement about adolescence is WRONG?",
     ["किशोरावस्था के सारे परिवर्तन एक निश्चित उम्र के दिन ही सब पर आते हैं", "इस दौरान भावनात्मक उतार-चढ़ाव सामान्य है", "हार्मोन इन परिवर्तनों के सूत्रधार हैं", "यह बाल्यावस्था से वयस्कता का संक्रमण है"],
     ["All adolescent changes arrive on one fixed age-day for everyone", "Emotional ups and downs are normal in this phase", "Hormones direct these changes", "It is the transition from childhood to adulthood"],
     0,
     "परिवर्तनों की आयु-घड़ी सबकी भिन्न — पहले कथन ही गलत; बाकी तीनों सही।",
     "Everyone's age-clock of changes differs — the first statement itself is wrong; the other three stand correct."),

    # ================= SECONDARY SEXUAL CHARACTERISTICS — 20 (E7/M11/H2) =================
    ("secondary-sexual-characteristics", "easy",
     "लड़कों में ठुड्डी और मूँछ पर बाल आना किस श्रेणी का परिवर्तन माना जाता है?",
     "The appearance of hair on the chin and upper lip of boys is counted as which kind of change?",
     ["द्वितीयक लैंगिक लक्षण", "प्राथमिक लैंगिक लक्षण", "रोग", "आहार-परिवर्तन"],
     ["A secondary sexual characteristic", "A primary sexual characteristic", "A disease", "A dietary change"],
     0,
     "यौवन में उभरे लक्षण जो प्रजनन-अंग से अलग शरीर पर दिखते हैं — द्वितीयक लैंगिक लक्षण कहलाते हैं।",
     "Features emerging at puberty visible on the body apart from reproductive organs — called secondary sexual characteristics."),

    ("secondary-sexual-characteristics", "easy",
     "लड़कियों में स्तनों का विकास किस प्रकार का लक्षण है?",
     "Breast development in girls is which type of characteristic?",
     ["द्वितीयक लैंगिक लक्षण", "प्राथमिक लैंगिक लक्षण", "अल्पकालिक बीमारी", "जन्मजात दोष"],
     ["A secondary sexual characteristic", "A primary sexual characteristic", "A short illness", "A birth defect"],
     0,
     "यौवन-हार्मोन से उभरा, प्रजनन-अंग से भिन्न लक्षण — इसलिए द्वितीयक।",
     "Emerging from puberty-hormone, a feature apart from reproductive organs — hence secondary."),

    ("secondary-sexual-characteristics", "easy",
     "लड़कों के स्वर (आवाज़) का भारी होना किस वर्ग में गिना जाता है?",
     "Deepening of voice in boys is counted in which class?",
     ["द्वितीयक लैंगिक लक्षण", "प्राथमिक लैंगिक लक्षण", "संवेदन-लक्षण", "पाचन-लक्षण"],
     ["Secondary sexual characteristic", "Primary sexual characteristic", "A sensory feature", "A digestive feature"],
     0,
     "आवाज़ का रूप-बदलाव यौवन की देन है — श्रेणी द्वितीयक।",
     "The voice's change of grain is puberty's gift — class secondary."),

    ("secondary-sexual-characteristics", "easy",
     "बगलों और शरीर पर बाल आना लड़कों और लड़कियों — दोनों में किस श्रेणी का परिवर्तन है?",
     "Hair appearing in the armpits and on the body — in BOTH boys and girls — is a change of which category?",
     ["द्वितीयक लैंगिक लक्षण", "प्राथमिक लैंगिक लक्षण", "केवल त्वचा-रोग", "केवल आयु-चिह्न"],
     ["Secondary sexual characteristic", "Primary sexual characteristic", "Only a skin disease", "Only an age-mark"],
     0,
     "शरीर-केश दोनों लिंगों में यौवन के साझे द्वितीयक लक्षण हैं।",
     "Body hair is puberty's shared secondary feature in both sexes."),

    ("secondary-sexual-characteristics", "easy",
     "'प्राथमिक लैंगिक लक्षण' से क्या तात्पर्य है?",
     "What is meant by 'primary sexual characteristics'?",
     ["जन्म से उपस्थित प्रजनन अंग", "यौवन में आई दाढ़ी", "यौवन में बदली आवाज़", "किशोरावस्था के मुँहासे"],
     ["The reproductive organs present from birth", "The beard that comes at puberty", "The voice that changes at puberty", "Adolescent pimples"],
     0,
     "जन्मजात प्रजनन-अंग प्राथमिक; यौवन की प्रसूनि में खिले लक्षण द्वितीयक।",
     "Birth-given reproductive organs are primary; features blooming in puberty's spring are secondary."),

    ("secondary-sexual-characteristics", "easy",
     "मुँहासे (pimples) प्रायः किस आयु-दौर में सामान्य रूप से दिखते हैं?",
     "In which age-phase do pimples commonly appear as a normal happening?",
     ["किशोरावस्था में", "पहले वर्ष में", "वृद्धावस्था में", "भ्रूणावस्था में"],
     ["In adolescence", "In the first year", "In old age", "In the embryonic stage"],
     0,
     "हार्मोन-मौसम में त्वचा की तेल-ग्रंथियाँ जागती हैं — मुँहासे उसी ऋतु की ओस हैं, रोग नहीं।",
     "In the hormone-season the skin's oil glands awaken — pimples are that season's dew, not a disease."),

    ("secondary-sexual-characteristics", "easy",
     "लड़कियों में कूल्हों (हिप्स) का चौड़ा होना किस श्रेणी का लक्षण है?",
     "Broadening of hips in girls is a characteristic of which category?",
     ["द्वितीयक लैंगिक लक्षण", "प्राथमिक लैंगिक लक्षण", "अस्थि-रोग", "मांसपेशी-रोग"],
     ["A secondary sexual characteristic", "A primary sexual characteristic", "A bone disease", "A muscle disease"],
     0,
     "यौवन-हार्मोन की छाँव में शरीर की बनावट स्त्री-रूप की ओर घूमती है — कूल्हों की चौड़ाई उसी का अंग।",
     "Under puberty-hormone's shade the build turns towards the feminine form — hip-breadth is part of it."),

    ("secondary-sexual-characteristics", "medium",
     "लड़कों में द्वितीयक लैंगिक लक्षणों को कौन-सा हार्मोन सामने लाता है?",
     "Which hormone brings forth the secondary sexual characteristics in boys?",
     ["टेस्टोस्टेरोन", "एस्ट्रोजन", "इंसुलिन", "एड्रेनालिन"],
     ["Testosterone", "Oestrogen", "Insulin", "Adrenaline"],
     0,
     "टेस्टोस्टेरोन के इशारे पर दाढ़ी, आवाज़, कंधे — सब रंगमंच पर आते हैं।",
     "At testosterone's cue the beard, voice, shoulders — all enter the stage."),

    ("secondary-sexual-characteristics", "medium",
     "लड़कियों के द्वितीयक लैंगिक लक्षणों के विकास का मुख्य स्रोत-हार्मोन कौन-सा है?",
     "Which is the main source-hormone for the development of secondary sexual characteristics in girls?",
     ["एस्ट्रोजन", "टेस्टोस्टेरोन", "थायरॉक्सिन", "वृद्धि हार्मोन"],
     ["Oestrogen", "Testosterone", "Thyroxine", "Growth hormone"],
     0,
     "एस्ट्रोजन लड़की के शरीर का यौवन-वास्तुकार है।",
     "Oestrogen is the puberty-architect of a girl's body."),

    ("secondary-sexual-characteristics", "medium",
     "प्राथमिक और द्वितीयक लैंगिक लक्षणों का मूल अंतर क्या है?",
     "What is the basic difference between primary and secondary sexual characteristics?",
     ["प्राथमिक जन्म से होते हैं; द्वितीयक यौवन में विकसित होते हैं", "दोनों जन्म से होते हैं", "दोनों यौवन में आते हैं", "प्राथमिक यौवन में, द्वितीयक जन्म से"],
     ["Primary exist from birth; secondary develop at puberty", "Both exist from birth", "Both come at puberty", "Primary at puberty, secondary from birth"],
     0,
     "जन्म की थाती में प्राथमिक; यौवन की कली में द्वितीयक — समय ही विभाजक रेखा।",
     "In birth's store lie the primary; in puberty's bud the secondary — time itself is the dividing line."),

    ("secondary-sexual-characteristics", "medium",
     "लड़कों के गले में उभरने वाला 'एडम्स एप्पल' वास्तव में क्या है?",
     "What actually is the 'Adam's apple' that protrudes in boys' throats?",
     ["बढ़े हुए स्वरयंत्र (voice box) का उभार", "अतिरिक्त हड्डी", "गले की गाँठ", "कोई मांसपेशी का खिंचाव"],
     ["The bulge of the grown voice box (larynx)", "An extra bone", "A knot of the throat", "A pull of some muscle"],
     0,
     "यौवन में स्वरयंत्र आगे की ओर बढ़ जाता है — वही उभार एडम्स एप्पल, और बड़े स्वरयंत्र से आवाज़ भारी।",
     "At puberty the voice box grows forward — that bulge is Adam's apple, and the larger box deepens the voice."),

    ("secondary-sexual-characteristics", "medium",
     "निम्न में से कौन-सा लड़कों या लड़कियों का द्वितीयक लैंगिक लक्षण नहीं है?",
     "Which of the following is NOT a secondary sexual characteristic of boys or girls?",
     ["आँखों का रंग", "दाढ़ी-मूँछ का आना", "स्तनों का विकास", "आवाज़ का भारी होना"],
     ["Colour of the eyes", "Appearance of facial hair", "Development of breasts", "Deepening of voice"],
     0,
     "आँखों का रंग जन्मजात लक्षण है, यौवन की देन नहीं — बाकी तीनों द्वितीयक।",
     "Eye colour is a birth-given trait, not puberty's gift — the other three are secondary."),

    ("secondary-sexual-characteristics", "medium",
     "किशोरावस्था में मुँहासे क्यों निकलते हैं?",
     "Why do pimples break out in adolescence?",
     ["हार्मोन के प्रभाव से त्वचा की तेल-ग्रंथियाँ अधिक सक्रिय हो जाती हैं", "पानी पीने से", "पढ़ने से", "जूते पहनने से"],
     ["Under hormone influence the skin's oil glands become overactive", "From drinking water", "From studying", "From wearing shoes"],
     0,
     "हार्मोन की गर्मी में तेल-ग्रंथियाँ धम-धम बहती हैं — रोमछिद्र बंद होते हैं, मुँहासे जन्म लेते हैं।",
     "In hormone's heat the oil glands flow thick — pores clog and pimples are born."),

    ("secondary-sexual-characteristics", "medium",
     "आवाज़ का परिवर्तन लड़कों में लड़कियों की तुलना में अधिक स्पष्ट क्यों होता है?",
     "Why is the change of voice more distinct in boys than in girls?",
     ["लड़कों का स्वरयंत्र अधिक बढ़ जाता है", "लड़के अधिक बोलते हैं", "लड़कों की जीभ लंबी होती है", "लड़के अधिक गाते हैं"],
     ["The voice box grows more in boys", "Boys talk more", "Boys' tongues are longer", "Boys sing more"],
     0,
     "टेस्टोस्टेरोन स्वरयंत्र को बड़ा-भारी बनाता है — तार लंबे, सुर गहरा; लड़कियों में वृद्धि हल्की।",
     "Testosterone makes the voice box big-heavy — longer cords, deeper tone; in girls the growth is mild."),

    ("secondary-sexual-characteristics", "medium",
     "यौवन में लड़कों के कंधे चौड़े और लड़कियों के कूल्हे चौड़े — यह भिन्नता किसका प्रतीक है?",
     "In puberty boys' shoulders broaden and girls' hips widen — this difference is a mark of what?",
     ["लैंगिक भिन्नता के द्वितीयक लक्षणों की", "पोशाक की", "आहार की", "मौसम की"],
     ["The secondary characteristics of sexual difference", "Of clothing", "Of diet", "Of weather"],
     0,
     "शरीर की बनावट ही यौवन में लिंग-रूप ग्रहण करती है — कंधा-कूल्हा उसी नक्शे की रेखाएँ।",
     "The body's very build takes a sex-form at puberty — shoulder and hip are lines of the same map."),

    ("secondary-sexual-characteristics", "medium",
     "यौवन में मांसपेशियों का विकास प्रायः किसमें अधिक प्रखर होता है?",
     "The development of muscles at puberty is usually more pronounced in whom?",
     ["लड़कों में — टेस्टोस्टेरोन के प्रभाव से", "लड़कियों में — एस्ट्रोजन के प्रभाव से", "दोनों में समान", "किसी में नहीं"],
     ["In boys — under testosterone's influence", "In girls — under oestrogen's influence", "Equally in both", "In neither"],
     0,
     "टेस्टोस्टेरोन मांसपेशी का पुश्तैनी है — इसीलिए लड़कों का ढाँचा भरसक बनता है।",
     "Testosterone is the patron of muscle — hence a boy's frame fills out amply."),

    ("secondary-sexual-characteristics", "medium",
     "निम्न में से कौन-सा समूह पूर्णतः लड़कियों के द्वितीयक लैंगिक लक्षणों का है?",
     "Which group consists ENTIRELY of secondary sexual characteristics of girls?",
     ["स्तन-विकास, कूल्हों का चौड़ा होना, शरीर-केश", "दाढ़ी, मूँछ, भारी आवाज़", "कंधे चौड़े, एडम्स एप्पल", "मूँछें और स्तन-विकास"],
     ["Breast development, broadening of hips, body hair", "Beard, moustache, heavy voice", "Broad shoulders, Adam's apple", "Moustache and breast development"],
     0,
     "पहला समूह लड़कियों का; दूसरा-तीसरा लड़कों का; चौथा मिलाजुला — शुद्ध लड़कियों वाला केवल पहला।",
     "The first group is girls'; second-third are boys'; the fourth is mixed — purely girls' is only the first."),

    ("secondary-sexual-characteristics", "medium",
     "प्राथमिक लैंगिक लक्षण और द्वितीयक लैंगिक लक्षण — सुमेलन परीक्षण: कौन-सा युग्म सही है?",
     "Primary and secondary sexual characteristics — matching test: which pair is correct?",
     ["प्राथमिक — जन्मजात प्रजनन अंग; द्वितीयक — यौवन में विकसित बाह्य लक्षण", "प्राथमिक — दाढ़ी; द्वितीयक — प्रजनन अंग", "प्राथमिक — आवाज़; द्वितीयक — प्रजनन अंग", "दोनों — केवल आँतरिक भावनाएँ"],
     ["Primary — birth-given reproductive organs; secondary — external features developed at puberty", "Primary — beard; secondary — reproductive organs", "Primary — voice; secondary — reproductive organs", "Both — only inner feelings"],
     0,
     "जन्म की संरचना प्राथमिक, यौवन की प्रसूनि द्वितीयक — सुमेलन केवल पहले युग्म में सही बैठता है।",
     "Birth's structure is primary, puberty's bloom secondary — the matching sits right only in the first pair."),

    ("secondary-sexual-characteristics", "hard",
     "मानव में स्तन-ग्रंथियों (मैमरी ग्लैंड्स) का यौवन में विकसित होना किस श्रेणी में आता है — यह प्रश्न अक्सर भ्रमित करता है?",
     "In humans, the development of mammary glands at puberty falls in which category — a question that often confuses?",
     ["द्वितीयक लैंगिक लक्षण", "प्राथमिक लैंगिक लक्षण", "अंतःस्रावी रोग", "पाचन लक्षण"],
     ["A secondary sexual characteristic", "A primary sexual characteristic", "An endocrine disease", "A digestive feature"],
     0,
     "ग्रंथि जन्म से है, पर उसका विकास-विस्तार यौवन में होता है — इसलिए मानव-शास्त्र में इसे द्वितीयक लक्षण की श्रेणी में रखा जाता है।",
     "The gland exists from birth, but its growth-expansion happens at puberty — hence in human science it is placed among secondary characteristics."),

    ("secondary-sexual-characteristics", "hard",
     "निम्न लिंग-लक्षण युग्मों में से कौन-सा गलत है?",
     "Which of these sex-characteristic pairs is WRONG?",
     ["लड़के — एस्ट्रोजन का प्रभावी स्रोत", "लड़कियाँ — एस्ट्रोजन का प्रभावी स्रोत", "लड़के — दाढ़ी-मूँछ का विकास", "लड़कियाँ — स्तनों का विकास"],
     ["Boys — the effective source of oestrogen", "Girls — the effective source of oestrogen", "Boys — development of facial hair", "Girls — development of breasts"],
     0,
     "एस्ट्रोजन की मुख्य कुर्सी अंडाशय है, वृषण नहीं — पहला युग्म ही गलत; बाकी तीन सही।",
     "Oestrogen's main seat is the ovary, not the testes — the first pair is wrong; the rest three stand right."),
]
