# -*- coding: utf-8 -*-
"""B10 Part-2 — Growth, Development & Adolescence (chapter-10).
60 items: growth-hormone 20 (E7/M11/H2) + reproductive-phase 20 (E7/M11/H2)
          + adolescent-health 20 (E7/M11/H2).
Tuple: (topic, difficulty, question_hi, question_en, options_hi[4], options_en[4], correct_idx, expl_hi, expl_en)

DENY-AWARENESS carried from Part-1 header, Part-2 specifics:
- B09/ch-02 owns ovulation-day, menstruation/cycle DURATIONS, menopause AGE, pad-frequency.
  => Reproductive-phase items use: definition of flow, purpose of cycle, menarche-vs-menopause
     contrast, menopause WITHOUT age, irregular-start normalcy, hormonal control by ovaries.
- B06/ch-07 owns protein/calcium/iron building-block definitions, balanced-diet definition,
  child-vs-adult needs, junk-food-as-weak-diet, iodised-salt advice.
  => Adolescent-health items use the ADOLESCENT-NEED angle only (growth demand, menstrual
     blood loss, bone spurt), breakfast habit, routine, exercise-habit, SAY-NO.
- No advanced endocrine pathology (no acromegaly/cretinism naming), no reproductive anatomy,
  no disease/microorganism content (B11), no environment content (B12).
"""

PART2 = [
    # ================= GROWTH HORMONE & GROWTH DISORDERS — 20 (E7/M11/H2) =================
    ("growth-hormone", "easy",
     "वृद्धि हार्मोन (growth hormone) किस ग्रंथि से स्रावित होता है?",
     "From which gland is the growth hormone secreted?",
     ["पिट्यूटरी से", "थायरॉइड से", "अधिवृक्क से", "अग्न्याशय से"],
     ["The pituitary", "The thyroid", "The adrenal", "The pancreas"],
     0,
     "मस्तिष्क-तल पर बैठी पिट्यूटरी ही शरीर की वृद्धि की मुख्य बागडोर रखती है।",
     "The pituitary, seated at the brain's floor, holds the main charge of the body's growth."),

    ("growth-hormone", "easy",
     "वृद्धि हार्मोन का मुख्य कार्य क्या है?",
     "What is the main function of the growth hormone?",
     ["शरीर की समग्र वृद्धि को नियंत्रित और बढ़ावा देना", "भोजन पचाना", "रुधिर जमाना", "बालों का रंग बदलना"],
     ["Controlling and promoting the body's overall growth", "Digesting food", "Clotting blood", "Changing hair colour"],
     0,
     "हड्डियों, मांसपेशियों, अंगों — समूचे शरीर के निर्माण-कार्य की मेजबानी वृद्धि हार्मोन करता है।",
     "Bones, muscles, organs — the growth hormone hosts the construction-work of the whole body."),

    ("growth-hormone", "easy",
     "बचपन में वृद्धि हार्मोन की कमी से क्या हो सकता है?",
     "What can happen from a deficiency of growth hormone in childhood?",
     ["बौनापन (कद बहुत कम रह जाना)", "विशालकायता", "रात में लंबा होना", "बाल सफेद होना"],
     ["Dwarfism (height staying very short)", "Gigantism", "Growing tall at night", "Hair turning grey"],
     0,
     "ईंट-सीमेंट की आपूर्ति घटी तो दीवार अधूरी — बचपन की कमी बौनेपन का रूप ले लेती है।",
     "Less brick-cement supply, unfinished wall — childhood shortage takes the form of dwarfism."),

    ("growth-hormone", "easy",
     "बचपन में ही वृद्धि हार्मोन का स्रावण बहुत अधिक होने पर क्या स्थिति उत्पन्न हो सकती है?",
     "What condition can arise if growth hormone secretion is far too much in childhood itself?",
     ["विशालकायता (असामान्य लंबाई)", "बौनापन", "कद स्थिर रहना", "मोटापा घटना"],
     ["Gigantism (abnormal tallness)", "Dwarfism", "Height staying static", "Obesity decreasing"],
     0,
     "सीमा से बढ़ी आपूर्ति तो दीवार आसमान छूए — बचपन की अधिकता विशालकायता बनती है।",
     "Supply beyond limit and the wall touches the sky — childhood excess becomes gigantism."),

    ("growth-hormone", "easy",
     "'वृद्धि' और 'विकास' में मूल अंतर क्या है?",
     "What is the basic difference between 'growth' and 'development'?",
     ["वृद्धि आकार में वृद्धि है; विकास कार्य-क्षमता की परिपक्वता", "दोनों एक ही हैं", "वृद्धि केवल बच्चों में, विकास केवल वृद्धों में", "विकास आकार है, वृद्धि परिपक्वता"],
     ["Growth is increase in size; development is maturation of function", "Both are the same", "Growth only in children, development only in the old", "Development is size, growth is maturity"],
     0,
     "लंबाई-वजन बढ़ना वृद्धि; समझ-कौशल-जिम्मेदारी का पकना विकास — दोनों पहिए मिलकर जीवन-गाड़ी चलाते हैं।",
     "Rise of height-weight is growth; the ripening of sense-skill-responsibility is development — both wheels roll life's cart."),

    ("growth-hormone", "easy",
     "शरीर की लंबाई में वृद्धि मुख्यतः किस हार्मोन से जुड़ी मानी जाती है?",
     "Increase in the body's height is linked mainly with which hormone?",
     ["वृद्धि हार्मोन", "एड्रेनालिन", "इंसुलिन", "एस्ट्रोजन"],
     ["The growth hormone", "Adrenaline", "Insulin", "Oestrogen"],
     0,
     "कद की कुंजी पिट्यूटरी की इसी चाबी में रहती है।",
     "The key of height stays with this very key of the pituitary."),

    ("growth-hormone", "easy",
     "गहरी नींद के दौरान वृद्धि हार्मोन का स्रावण कैसा रहता है?",
     "How is the secretion of growth hormone during deep sleep?",
     ["अपेक्षाकृत अधिक", "पूरी तरह बंद", "आधा-अधूरा", "केवल दिन में होता है"],
     ["Relatively more", "Fully stopped", "Half-done", "It occurs only in the day"],
     0,
     "सोते शरीर में वृद्धि की रात-पाली चलती है — इसीलिए बच्चों-किशोरों की भरपूर नींद जरूरी।",
     "In the sleeping body runs the night-shift of growth — hence full sleep matters for children and adolescents."),

    ("growth-hormone", "medium",
     "'वृद्धि हार्मोन केवल लंबाई बढ़ाता है' — यह कथन क्यों अधूरा है?",
     "Why is the statement 'growth hormone only increases height' incomplete?",
     ["वह लंबाई के साथ मांसपेशियों और अंगों की समग्र वृद्धि भी नियंत्रित करता है", "क्योंकि वह केवल बाल बढ़ाता है", "क्योंकि वह कुछ नहीं करता", "क्योंकि वह केवल दाँत बढ़ाता है"],
     ["Along with height it governs the overall growth of muscles and organs", "Because it only grows hair", "Because it does nothing", "Because it only grows teeth"],
     0,
     "केवल फूल नहीं — पूरा बगीचा; वृद्धि हार्मोन का अधिकार शरीर के समग्र नक्शे पर है।",
     "Not just one flower — the whole garden; growth hormone's writ runs over the body's whole map."),

    ("growth-hormone", "medium",
     "बौनेपन का हार्मोन-संबंधी कारण क्या हो सकता है?",
     "What can be the hormone-related cause of dwarfism?",
     ["बचपन में वृद्धि हार्मोन की कमी", "वयस्कता में एड्रेनालिन की अधिकता", "इंसुलिन की अधिकता", "एस्ट्रोजन की कमी"],
     ["Deficiency of growth hormone in childhood", "Excess of adrenaline in adulthood", "Excess of insulin", "Deficiency of oestrogen"],
     0,
     "जिस उम्र में नींव गढ़ी जाती है, उसी में सामग्री कम पड़ी — तो कद की इमारत नीची रह गई।",
     "The age when the foundation is cast, right there the material fell short — so the tower of height stayed low."),

    ("growth-hormone", "medium",
     "विशालकायता विकसित होने की शर्त क्या है?",
     "What is the condition for gigantism to develop?",
     ["हड्डियों की वृद्धि चालू होने की अवस्था में ही हार्मोन की अधिकता", "हड्डियों की वृद्धि रुकने के बाद कमी", "केवल वृद्धावस्था में अधिकता", "केवल नवजात में कमी"],
     ["Hormone excess while the bones' growth is still running", "Deficiency after bones' growth stops", "Excess only in old age", "Deficiency only in the newborn"],
     0,
     "बढ़ती ईंटों पर ही अतिरिक्त गारा चढ़ेगा — नक्शा जम चुका हो तो लंबाई का दरवाजा बंद।",
     "Extra mortar sticks only on rising bricks — once the design is set, the door of height closes."),

    ("growth-hormone", "medium",
     "पिट्यूटरी → वृद्धि हार्मोन → परिणाम — श्रृंखला का सही सुमेलन कौन-सा है?",
     "Pituitary → growth hormone → outcome — which is the correct matching of the chain?",
     ["पिट्यूटरी से वृद्धि हार्मोन → शरीर की समग्र वृद्धि", "पिट्यूटरी से इंसुलिन → शर्करा नियंत्रण", "थायरॉइड से वृद्धि हार्मोन → आपात तत्परता", "अधिवृक्क से वृद्धि हार्मोन → चयापचय"],
     ["Pituitary gives growth hormone → overall growth of body", "Pituitary gives insulin → sugar control", "Thyroid gives growth hormone → emergency alertness", "Adrenal gives growth hormone → metabolism"],
     0,
     "ग्रंथि-हार्मोन-फल तीनों की तारतम्य पहले युग्म में ही शुद्ध बैठती है।",
     "The tuning of gland-hormone-fruit sits true only in the first pair."),

    ("growth-hormone", "medium",
     "वृद्धि में थायरॉक्सिन की भूमिका क्या है?",
     "What is thyroxine's role in growth?",
     ["वह वृद्धि हार्मोन का सहयोगी है — चयापचय चुस्त रखकर वृद्धि को गति देता है", "वह वृद्धि रोकता है", "वह केवल आवाज़ बदलता है", "उसका वृद्धि से कोई लेना-देना नहीं"],
     ["It is the growth hormone's ally — keeping metabolism brisk, it speeds growth", "It stops growth", "It only changes the voice", "It has nothing to do with growth"],
     0,
     "टैडपोल का रूपांतरण हो या बच्चे की लंबाई — थायरॉक्सिन घास-फूस का काम नहीं करता, इंजन का।",
     "Be it a tadpole's transformation or a child's height — thyroxine works not as the hay but as the engine."),

    ("growth-hormone", "medium",
     "निम्न में से कौन-सा 'विकास' (development) का सही उदाहरण है?",
     "Which of these is a correct example of 'development'?",
     ["निर्णय लेने की क्षमता का पकना", "केवल वजन बढ़ना", "केवल कद बढ़ना", "केवल बाल लंबे होना"],
     ["The ripening of decision-making capacity", "Only weight gain", "Only height gain", "Only hair getting longer"],
     0,
     "आकार की बढ़त वृद्धि है; क्षमता की बढ़त विकास — तर्क-क्षमता बाद वाली श्रेणी की सधी हुई मिसाल।",
     "Size's increase is growth; capacity's increase is development — reasoning-power is a seasoned specimen of the latter."),

    ("growth-hormone", "medium",
     "किशोरावस्था में ऊँचाई की तीव्र बढ़त (growth spurt) के पीछे कौन-सी हार्मोन-स्थिति होती है?",
     "Which hormone-situation lies behind the sharp rise of height (growth spurt) in adolescence?",
     ["वृद्धि हार्मोन के साथ यौवन-हार्मोनों का भी स्रावण ऊँचा हो जाना", "सभी हार्मोन बंद हो जाना", "केवल एड्रेनालिन बढ़ना", "इंसुलिन शून्य होना"],
     ["Growth hormone's secretion rising high together with the puberty hormones", "All hormones shutting off", "Only adrenaline rising", "Insulin falling to zero"],
     0,
     "दो नदियों का संगम-मौसम — वृद्धि हार्मोन और यौवन-हार्मोन एक साथ बहते हैं, कद झटपट खिंचता है।",
     "The confluence-season of two rivers — growth hormone and puberty hormones flow together, height pulls up swiftly."),

    ("growth-hormone", "medium",
     "बच्चे की वृद्धि उम्र के अनुसार असामान्य रूप से धीमी दिखे तो सबसे उचित कदम क्या है?",
     "If a child's growth looks abnormally slow for age, what is the most proper step?",
     ["चिकित्सक से जाँच-परामर्श कराना", "घर पर रहकर इंतज़ार करना", "अफवाहों पर भरोसा करना", "खाना बंद कर देना"],
     ["Getting a check-up and counselling from a doctor", "Waiting at home", "Trusting rumours", "Stopping food"],
     0,
     "धीमी वृद्धि के पीछे हार्मोन भी हो सकते हैं, पोषण भी — जाँच ही असली कारण खोलती है।",
     "Behind slow growth may lie hormones or nutrition — only a check-up opens the real cause."),

    ("growth-hormone", "medium",
     "हड्डियों की लंबी-वृद्धि वाली अवस्था समाप्त होने के बाद कद में वृद्धि कैसी रह जाती है?",
     "After the stage of bones' length-growth ends, what happens to height?",
     ["प्रायः लगभग स्थिर रह जाती है", "दोगुनी बढ़ने लगती है", "आधी घट जाती है", "रोज़ बदलती रहती है"],
     ["It usually stays nearly fixed", "It starts doubling", "It halves", "It changes daily"],
     0,
     "लंबाई की दुकान जब शटर डाल देती है, तो कद अपने अंतिम आँकड़े पर टिक जाता है।",
     "When the shop of lengthiness pulls its shutter down, height settles at its final figure."),

    ("growth-hormone", "medium",
     "किशोर की ऊँचाई के पीछे काम करने वाले तीन प्रमुख कारक कौन-से हैं?",
     "Which three chief factors work behind an adolescent's height?",
     ["आनुवंशिकता, हार्मोन और पोषण", "जूते, कपड़े और टोपी", "मौसम, पते और नाम", "स्कूल, बस और बैग"],
     ["Heredity, hormones and nutrition", "Shoes, clothes and cap", "Weather, address and name", "School, bus and bag"],
     0,
     "मिलानटैंक में तीनों की भरपाई जरूरी — वंश नक्शा देता है, हार्मोन गति, पोषण ईंटें।",
     "All three must be filled in the balance-tank — heredity gives the map, hormones the speed, nutrition the bricks."),

    ("growth-hormone", "medium",
     "सही 'विकास' की पहचान वाला कथन चुनिए — विकास में गिनती किस चीज़ की जाती है?",
     "Pick the statement identifying true 'development' — in development, what gets counted?",
     ["समझ, कौशल और व्यवहार की परिपक्वता", "केवल शरीर का भार", "केवल बालों की लंबाई", "केवल आँखों की संख्या"],
     ["The maturity of understanding, skill and behaviour", "Only the body's weight", "Only the length of hair", "Only the number of eyes"],
     0,
     "विकास का मापदंड तराजू से नहीं, व्यवहार से — समझदारी जितनी गहरी, विकास उतना ऊँचा।",
     "Development's measure is not the scale but conduct — the deeper the judgement, the taller the development."),

    ("growth-hormone", "hard",
     "एक व्यक्ति का कद बचपन से ही असामान्य रूप से कम रहा — प्रायः कौन-सी ग्रंथि की कम-सक्रियता संभावित कारण हो सकती है?",
     "A person's height stayed abnormally short since childhood — which gland's under-activity is the likely cause?",
     ["पिट्यूटरी", "अधिवृक्क", "अग्न्याशय", "थायरॉइड नहीं, अपितु यकृत"],
     ["The pituitary", "The adrenal", "The pancreas", "Not the thyroid but the liver"],
     0,
     "वृद्धि-हार्मोन की फैक्ट्री पिट्यूटरी है — बचपन से ठप पड़ी फैक्ट्री का नतीजा बौना कद।",
     "The growth-hormone factory is the pituitary — a factory stalled since childhood yields a short stature."),

    ("growth-hormone", "hard",
     "वृद्धि हार्मोन संबंधी निम्न में से कौन-सा कथन गलत है?",
     "Which statement about growth hormone is WRONG?",
     ["वृद्धि हार्मोन की अधिकता से हमेशा बौनापन होता है", "यह पिट्यूटरी से स्रावित होता है", "इसकी बचपन की कमी बौनापन का कारण बन सकती है", "यह समग्र शारीरिक वृद्धि नियंत्रित करता है"],
     ["Excess of growth hormone always causes dwarfism", "It is secreted by the pituitary", "Its childhood deficiency can cause dwarfism", "It controls overall bodily growth"],
     0,
     "अधिकता बौनापन नहीं — विशालकायता की ओर ले जाती है; कमी से बौनापन — पहला कथन ही उल्टा पड़ा है।",
     "Excess leads not to dwarfism but towards gigantism; deficiency gives dwarfism — the first statement stands inverted."),

    # ================= REPRODUCTIVE PHASE — 20 (E7/M11/H2) =================
    ("reproductive-phase", "easy",
     "मासिक धर्म (menstruation) के दौरान शरीर से वास्तव में क्या निकलता है?",
     "What actually flows out of the body during menstruation?",
     ["गर्भाशय की अंतर-परत का टूटा ऊतक और रक्त", "केवल शुद्ध पानी", "पाचक रस", "लसीका वाहिकाओं का दूध"],
     ["The broken tissue of the uterus's inner lining and blood", "Only pure water", "Digestive juice", "The lymph's milk"],
     0,
     "गर्भाशय की बिछाई गद्दी जब काम न आए, तो शरीर उसे तोड़कर बाहर भेजता है — यही मासिक धर्म है।",
     "When the uterus's spread mattress serves no use, the body breaks and sends it out — that is menstruation."),

    ("reproductive-phase", "easy",
     "स्त्रियों में प्रजनन अवस्था की समाप्ति को क्या कहते हैं?",
     "What is the end of the reproductive phase in women called?",
     ["रजोनिवृत्ति (मेनोपॉज)", "मेनार्क", "यौवनारंभ", "ओव्यूलेशन"],
     ["Menopause", "Menarche", "Puberty onset", "Ovulation"],
     0,
     "मासिक चक्र की स्थायी विदाई — रजोनिवृत्ति; इसके बाद प्रजनन क्षमता समाप्त मानी जाती है।",
     "The permanent farewell of the monthly cycle — menopause; after it reproductive capacity is taken as ended."),

    ("reproductive-phase", "easy",
     "रजोनिवृत्ति (मेनोपॉज) के बाद स्त्री में क्या स्थिति हो जाती है?",
     "After menopause, what becomes the state of a woman?",
     ["मासिक धर्म और प्रजनन क्षमता समाप्त हो जाती है", "मासिक धर्म दोगुना हो जाता है", "प्रजनन क्षमता बढ़ जाती है", "कुछ नहीं बदलता"],
     ["Menstruation and reproductive capacity come to an end", "Menstruation doubles", "Reproductive capacity increases", "Nothing changes"],
     0,
     "जो घड़ी वर्षों टिकती रही, वह रजोनिवृत्ति पर स्थिर हो जाती है — यह सामान्य जैविक घटना है, बीमारी नहीं।",
     "The clock that ticked for years stands still at menopause — a normal biological event, not an illness."),

    ("reproductive-phase", "easy",
     "पुरुषों में शुक्राणुओं का उत्पादन प्रायः कब आरंभ होता है?",
     "When does sperm production in males usually begin?",
     ["यौवनारंभ के साथ — लगभग 11–14 वर्ष पर", "जन्म के समय", "पाँच वर्ष की आयु में", "रजोनिवृत्ति के बाद"],
     ["With the onset of puberty — around 11–14 years", "At the time of birth", "At age five", "After menopause"],
     0,
     "यौवन की घंटी के साथ ही वृषण सक्रिय हो उठते हैं — शुक्राणु-उत्पादन का कारखाना चालू।",
     "With puberty's bell the testes wake — the sperm factory switches on."),

    ("reproductive-phase", "easy",
     "मासिक धर्म-चक्र का दोहराव प्रायः कितने समय के अंतराल पर होता है?",
     "At roughly what interval does the menstrual cycle repeat?",
     ["लगभग एक माह (मासिक) पर", "प्रतिदिन", "हर घंटे", "साल में एक बार"],
     ["About one month (monthly)", "Every day", "Every hour", "Once a year"],
     0,
     "चंद्र-चक्र की कद-काठी के बराबर अंतराल — इसीलिए नाम 'मासिक' धर्म पड़ा।",
     "An interval of about the moon-cycle's span — hence the name 'monthly' flow."),

    ("reproductive-phase", "easy",
     "लड़कियों में प्रजनन अवस्था का आरंभ प्रायः किस आयु-दौर में होता है?",
     "In girls, the reproductive phase usually begins in which age-bracket?",
     ["लगभग 10–12 वर्ष के आसपास", "2–3 वर्ष में", "20–22 वर्ष में", "60–62 वर्ष में"],
     ["Around 10–12 years", "At 2–3 years", "At 20–22 years", "At 60–62 years"],
     0,
     "दस से बारह के बीच मेनार्क की घंटी प्रायः बज जाती है — किसी की जल्दी, किसी की देर।",
     "Between ten and twelve the bell of menarche usually rings — early for some, late for others."),

    ("reproductive-phase", "easy",
     "मासिक धर्म का पहली बार आरंभ होना किसका संकेत है?",
     "The first-ever beginning of menstruation signals what?",
     ["किशोरी में प्रजनन परिपक्वता की ओर बढ़ने का", "किसी गंभीर रोग का", "कद घटने का", "आँखें कमजोर होने का"],
     ["The adolescent's move towards reproductive maturity", "Some serious disease", "Height shrinking", "Eyes weakening"],
     0,
     "मेनार्क रोग नहीं, परिपक्वता का पहला पत्र है — शरीर यह घोषणा करता है कि वह बड़ा हो रहा है।",
     "Menarche is not disease but maturity's first letter — the body declares it is growing up."),

    ("reproductive-phase", "medium",
     "मासिक चक्र में गर्भाशय की भीतरी परत हर बार क्यों मोटी-तैयार होती है?",
     "Why does the uterus's inner lining thicken in readiness every cycle?",
     ["संभावित गर्भाधान की स्थिति में भ्रूण को सहारा देने की तैयारी में", "पाचन में सहायता हेतु", "शरीर को गर्म रखने हेतु", "श्वास में सहायता हेतु"],
     ["In preparation to support an embryo in case a pregnancy begins", "To help digestion", "To keep the body warm", "To help breathing"],
     0,
     "गर्भाशय हर माह एक पलंग बिछाता है — अतिथि आए तो ठीक, न आए तो गद्दी समेट ली जाती है।",
     "The uterus spreads a bed each month — if the guest arrives, well; if not, the mattress is folded away."),

    ("reproductive-phase", "medium",
     "जब गर्भाधान नहीं होता, तो गर्भाशय की तैयार परत का क्या होता है?",
     "When pregnancy does not happen, what becomes of the uterus's prepared lining?",
     ["वह टूटकर मासिक धर्म के रूप में बाहर निकल जाती है", "वह स्थायी रह जाती है", "वह पथरी बन जाती है", "वह फेफड़ों तक चली जाती है"],
     ["It breaks down and flows out as menstruation", "It stays permanently", "It turns to stone", "It walks off to the lungs"],
     0,
     "अनुपयुक्त बिसातर समेटना शरीर का पुराना नियम — अगले चक्र में नई परत फिर तैयार।",
     "Folding the unused bedding is the body's old rule — the next cycle readies a fresh lining again."),

    ("reproductive-phase", "medium",
     "मेनार्क के बाद प्रारंभिक कुछ महीनों-वर्षों में मासिक धर्म अनियमित होना कैसा माना जाता है?",
     "Menstruation being irregular in the first months-years after menarche is considered how?",
     ["सामान्य — हार्मोन-तंत्र धीरे-धीरे सधता है", "गंभीर रोग का चिह्न", "स्थायी समस्या", "उपचार असंभव"],
     ["Normal — the hormone-system settles gradually", "A sign of grave disease", "A permanent problem", "Untreatable"],
     0,
     "नई घड़ी पहले दिनों में थोड़ी आगे-पीछे चलती है — फिर क्रम में बैठ जाती है।",
     "A new clock runs a little off in early days — then settles into order."),

    ("reproductive-phase", "medium",
     "मेनार्क और रजोनिवृत्ति में मूल अंतर क्या है?",
     "What is the basic difference between menarche and menopause?",
     ["मेनार्क प्रजनन अवस्था का आरंभ है, रजोनिवृत्ति उसकी समाप्ति", "दोनों एक ही घटना हैं", "मेनार्क समाप्ति है, रजोनिवृत्ति आरंभ", "दोनों पुरुषों में होती हैं"],
     ["Menarche is the START of the reproductive phase, menopause its END", "Both are the same event", "Menarche is the end, menopause the start", "Both occur in males"],
     0,
     "एक द्वार-दालन, दूसरा द्वार-विदाई — बीच की पूरी दालान ही प्रजनन अवस्था है।",
     "One is the doorway-welcome, the other the doorway-farewell — the whole hall between is the reproductive phase."),

    ("reproductive-phase", "medium",
     "मासिक चक्र का हार्मोन-संचालन मुख्यतः कौन-सी ग्रंथि करती है?",
     "Which gland mainly conducts the hormonal running of the menstrual cycle?",
     ["अंडाशय — एस्ट्रोजन और प्रोजेस्टेरोन के द्वारा", "यकृत — पित्त के द्वारा", "गुर्दा — मूत्र के द्वारा", "आमाशय — अम्ल के द्वारा"],
     ["The ovaries — by means of oestrogen and progesterone", "The liver — by bile", "The kidney — by urine", "The stomach — by acid"],
     0,
     "अंडाशय के दो हार्मोन चक्र के स्वर-लय तय करते हैं — एक परत बनाता है, दूसरा उसे सँभालता है।",
     "The ovary's two hormones set the cycle's note-rhythm — one builds the lining, the other maintains it."),

    ("reproductive-phase", "medium",
     "मासिक धर्म को लेकर सही दृष्टिकोण कौन-सा है?",
     "Which is the right attitude towards menstruation?",
     ["यह एक सामान्य, स्वस्थ शारीरिक प्रक्रिया है — शर्म या अछूतपन की नहीं", "यह बीमारी है जिसमें घर से बाहर निकलना मना", "यह केवल वयस्कों की समस्या है", "इसमें स्कूल जाना हानिकारक है"],
     ["A normal, healthy bodily process — not one of shame or untouchability", "A disease barring leaving the house", "Only an adults' problem", "Going to school in it is harmful"],
     0,
     "शरीर की ऋतु को शर्म की चादर में नहीं, समझ के दिन-चंद्रा में देखना चाहिए — सामान्य व स्वाभाविक।",
     "The body's season should be seen in the daylight of understanding, not a sheet of shame — normal and natural."),

    ("reproductive-phase", "medium",
     "मासिक धर्म के दिनों में आयरन-युक्त आहार लड़कियों को विशेष क्यों सुझाया जाता है?",
     "Why is iron-rich food specially advised to girls during menstrual days?",
     ["रक्त की हानि की पूर्ति में आयरन सहायक है", "आयरन से आवाज़ भारी होती है", "आयरन कद घटाता है", "आयरन नींद लाता है"],
     ["Iron helps make up the loss of blood", "Iron deepens the voice", "Iron reduces height", "Iron brings sleep"],
     0,
     "जो धातु रुधिर की स्याही है, वही मासिक-दिनों की भरपाई का पुल है — हरी सब्जियाँ, फल, गुड़।",
     "The metal that is blood's ink is the very bridge of replenishment in menstrual days — greens, fruits, jaggery."),

    ("reproductive-phase", "medium",
     "प्रजनन अवस्था की समाप्ति के संदर्भ में स्त्री और पुरुष में प्रायः क्या अंतर देखा जाता है?",
     "Regarding the end of the reproductive phase, what difference is usually seen between women and men?",
     ["स्त्रियों में रजोनिवृत्ति जैसी निश्चित समाप्ति आती है; पुरुषों में ऐसी तीक्ष्ण समाप्ति नहीं", "दोनों में एक साथ रजोनिवृत्ति आती है", "पुरुषों में पहले रजोनिवृत्ति आती है", "किसी में कभी समाप्ति नहीं होती"],
     ["Women get a definite end like menopause; men do not have such a sharp end", "Both get menopause together", "Men get menopause first", "No one's phase ever ends"],
     0,
     "स्त्री की प्रजनन-घड़ी एक दिन विराम लेती है; पुरुष की चाल धीमी अवश्य पड़ती है, पर ठप नहीं होती।",
     "A woman's reproductive clock pauses one day; a man's pace slows but does not halt."),

    ("reproductive-phase", "medium",
     "प्रत्येक नए चक्र में गर्भाशय की परत के साथ क्या होता है?",
     "What happens to the uterine lining with every new cycle?",
     ["पुरानी परत निकलने के बाद नई परत फिर से बनती है", "परतें जमा होती जाती हैं", "परत कभी नहीं बदलती", "परत हृदय तक चली जाती है"],
     ["After the old lining flows out, a fresh lining builds again", "Linings keep stacking up", "The lining never changes", "The lining walks to the heart"],
     0,
     "झाड़ू लगा दुकान, फिर नई व्यवस्था — गर्भाशय हर चक्र में ताज़ा कवर बिछाता है।",
     "Shop swept, then a new arrangement — the uterus spreads a fresh cover every cycle."),

    ("reproductive-phase", "medium",
     "मासिक धर्म के दिनों में सामान्य देखभाल के अंतर्गत क्या सम्मिलित है?",
     "What is included under ordinary care during menstrual days?",
     ["विश्राम, स्वच्छता का ध्यान और संतुलित आहार", "पूरा बिस्तर छोड़ देना", "खाना-पीना बंद करना", "स्कूल से स्थायी छुट्टी"],
     ["Rest, attention to cleanliness and a balanced diet", "Leaving the bed entirely", "Stopping all food", "Permanent leave from school"],
     0,
     "सामान्य-सा ध्यान ही काफी है — स्वच्छता, विश्राम और पौष्टिक भोजन; जीवन वैसा ही चलता रहता है।",
     "Ordinary care suffices — cleanliness, rest and nourishing food; life runs on as usual."),

    ("reproductive-phase", "medium",
     "'प्रजनन अवस्था' किस काल-खंड को कहते हैं?",
     "Which span of time is called the 'reproductive phase'?",
     ["मेनार्क से रजोनिवृत्ति तक की अवधि", "जन्म से मेनार्क तक", "रजोनिवृत्ति के बाद का काल", "पूरा जीवन-काल"],
     ["The period from menarche to menopause", "Birth to menarche", "The time after menopause", "The whole lifespan"],
     0,
     "जिस दौर में शरीर प्रजनन में सक्षम रहता है — उसकी दो मील के पत्थर मेनार्क और रजोनिवृत्ति हैं।",
     "The span in which the body remains capable of reproduction — its two milestones are menarche and menopause."),

    ("reproductive-phase", "hard",
     "चक्र की उद्देश्य-श्रृंखला पर विचार कीजिए — गर्भाशय परत तैयार → गर्भाधान नहीं → परत झड़ती है। इसमें मासिक धर्म किस चरण का नाम है?",
     "Consider the purpose-chain of the cycle — uterine lining prepares → no pregnancy → lining sheds. Menstruation is the name of which step?",
     ["तीसरा चरण — तैयार परत का टूटकर बाहर आना", "पहला चरण — परत का बनना", "दूसरा चरण — गर्भाधान", "कोई चरण नहीं"],
     ["The third step — the prepared lining breaking and flowing out", "The first step — the lining's formation", "The second step — pregnancy", "No step at all"],
     0,
     "तैयारी → अवसर न मिलना → समेटना: मासिक धर्म तीसरे मोड़ का नाम है, अंत का नहीं — चक्र फिर शुरू होता है।",
     "Preparation → occasion not arriving → folding up: menstruation names the third turn, not the end — the cycle starts afresh."),

    ("reproductive-phase", "hard",
     "प्रजनन अवस्था संबंधी निम्न में से कौन-सा कथन सही नहीं है?",
     "Which statement about the reproductive phase is NOT correct?",
     ["रजोनिवृत्ति के बाद भी मासिक धर्म चलता रहता है", "मेनार्क प्रजनन अवस्था का आरंभ है", "यह अवस्था हार्मोनों द्वारा संचालित है", "अंडाशय इस अवस्था में सक्रिय रहते हैं"],
     ["Even after menopause menstruation keeps running", "Menarche is the start of the reproductive phase", "This phase is run by hormones", "The ovaries stay active in this phase"],
     0,
     "रजोनिवृत्ति का अर्थ ही चक्र की स्थायी विराम-घंटी — पहला कथन संबंध-हीन; बाकी तीन सही।",
     "Menopause itself means the cycle's permanent pause-bell — the first statement is off; the other three stand."),

    # ================= ADOLESCENT HEALTH — 20 (E7/M11/H2) =================
    ("adolescent-health", "easy",
     "किशोरावस्था में संतुलित आहार की माँग सामान्य से अधिक क्यों हो जाती है?",
     "Why does the demand for a balanced diet rise above normal in adolescence?",
     ["इस दौर में शरीर की वृद्धि सबसे तेज़ चलती है — ईंट-गारे की जरूरत चरम पर", "क्योंकि किशोर केवल खेलते हैं", "क्योंकि पाचन बंद हो जाता है", "क्योंकि नींद दोगुनी होती है"],
     ["In this phase the body's growth runs fastest — brick-and-mortar need at its peak", "Because adolescents only play", "Because digestion stops", "Because sleep doubles"],
     0,
     "बढ़ती इमारत को चूना-ईंट सबसे ज्यादा उसी मौसम में चाहिए जब रफ्तार तेज़ हो — किशोरावस्था वही निर्माण-मौसम है।",
     "A rising building needs lime-brick most in the season of fast pace — adolescence is that construction-season."),

    ("adolescent-health", "easy",
     "किशोरावस्था में मांसपेशियों और शरीर-निर्माण की दृष्टि से कौन-सा आहार-घटक विशेष उपयोगी है?",
     "Which dietary component is specially useful for muscles and body-building in adolescence?",
     ["प्रोटीन — दालें, दूध, अंडा, पनीर", "केवल चीनी", "केवल नमक", "केवल बर्फ"],
     ["Protein — pulses, milk, egg, cottage cheese", "Only sugar", "Only salt", "Only ice"],
     0,
     "बढ़ती मांसपेशी का गारा प्रोटीन है — किशोर की थाली में दाल-दूध का दरवाजा खुला रहना चाहिए।",
     "The mortar of growing muscle is protein — the door of pulses-milk must stay open in an adolescent's plate."),

    ("adolescent-health", "easy",
     "लड़कियों को किशोरावस्था में आयरन-युक्त आहार (हरी सब्जियाँ, गुड़) की अतिरिक्त सलाह क्यों दी जाती है?",
     "Why are girls additionally advised iron-rich food (green vegetables, jaggery) in adolescence?",
     ["मासिक धर्म में रक्त-हानि की भरपाई के लिए", "आवाज़ भारी करने के लिए", "कद घटाने के लिए", "बाल सीधे करने के लिए"],
     ["To make up the blood loss in menstruation", "To deepen the voice", "To reduce height", "To straighten hair"],
     0,
     "जिस मौसम में रक्त की बहावत होती है, उसी मौसम में आयरन की आपूर्ति भी बढ़ानी होती है।",
     "In the season of blood's flow, the iron supply must be raised in the same season."),

    ("adolescent-health", "easy",
     "किशोरावस्था में हड्डियों की तेज़ वृद्धि के लिए कौन-सा खनिज आहार में पर्याप्त चाहिए?",
     "Which mineral must be ample in the diet for the rapid bone-growth of adolescence?",
     ["कैल्शियम — दूध, दही, पनीर से", "लोहा — केवल पानी से", "सोडियम — केवल नमक से", "सीसा — पेंट से"],
     ["Calcium — from milk, curd, cottage cheese", "Iron — only from water", "Sodium — only from salt", "Lead — from paint"],
     0,
     "कद की तीखी उड़ान वाले मौसम में हड्डियों का सीमेंट कैल्शियम है — दूध-दही उसके सीधे भंडार।",
     "In the season of height's sharp flight, bones' cement is calcium — milk and curd its direct storehouse."),

    ("adolescent-health", "easy",
     "नशे की लत से बचने का सबसे सरल मंत्र क्या है?",
     "What is the simplest formula to stay safe from addiction?",
     ["पहली पेशकश पर ही दृढ़ता से 'नहीं' कह देना", "थोड़ा-थोड़ा चलते रहना", "दोस्तों के आगे झुक जाना", "बाद में छोड़ने की योजना बनाना"],
     ["Saying a firm 'NO' at the very first offer", "Continuing little by little", "Bowing before friends", "Planning to quit later"],
     0,
     "पहली सीढ़ी ही न चढ़े तो गिरने का सवाल ही नहीं — SAY NO यही एकमात्र मजबूत दरवाज़ा है।",
     "If the first stair is never climbed, there is no question of falling — SAY NO is the only strong door."),

    ("adolescent-health", "easy",
     "किशोर के लिए प्रतिरात्रि पर्याप्त नींद लगभग कितनी मानी जाती है?",
     "About how much sleep per night is considered enough for an adolescent?",
     ["लगभग 8–9 घंटे", "2–3 घंटे", "लगभग 1 घंटा", "20–22 घंटे"],
     ["About 8–9 hours", "2–3 hours", "About 1 hour", "20–22 hours"],
     0,
     "वृद्धि की रात-पाली पूरी नींद में ही चलती है — आठ-नौ घंटे किशोर शरीर-मस्तिष्क की साझा आवश्यकता।",
     "Growth's night-shift runs only in full sleep — eight-nine hours are the shared need of adolescent body and brain."),

    ("adolescent-health", "easy",
     "किशोरावस्था में प्रतिदिन स्नान और स्वच्छ रहना विशेष क्यों जरूरी हो जाता है?",
     "Why do daily bathing and cleanliness become specially necessary in adolescence?",
     ["इस उम्र में स्वेद-ग्रंथियाँ अधिक सक्रिय हो जाती हैं", "क्योंकि बारिश अधिक होती है", "क्योंकि स्कूल बंद रहता है", "क्योंकि कपड़े नहीं मिलते"],
     ["The sweat glands become more active at this age", "Because it rains more", "Because school stays closed", "Because clothes are unavailable"],
     0,
     "हार्मोन की गर्मी में पसीने की फैक्ट्री तेज़ चलती है — रोज़ स्नान, साफ कपड़े उसी की साथ-चलने वाली जरूरत।",
     "In hormone's heat the sweat-factory runs fast — daily bath and clean clothes are its fellow-travellers."),

    ("adolescent-health", "medium",
     "मादक पदार्थ (नशा) किशोर के लिए विशेष रूप से हानिकारक क्यों हैं?",
     "Why are intoxicants specially harmful for an adolescent?",
     ["विकासशील शरीर-मस्तिष्क को हानि पहुँचाकर लत बना देते हैं", "वे केवल वयस्कों के लिए अच्छे हैं", "वे कद बढ़ाते हैं", "वे भूख बढ़ाते हैं"],
     ["They harm the developing body-brain and turn into addiction", "They are good only for adults", "They increase height", "They increase appetite"],
     0,
     "कच्चे घर की नींव पर हथौड़ा — नशा विकासशील मस्तिष्क को वही करता है; साथ ही लत का फंदा भी।",
     "A hammer on a raw house's foundation — that is what intoxicants do to a developing brain; plus the noose of dependence."),

    ("adolescent-health", "medium",
     "धूम्रपान सहित नशीले पदार्थ किशोर के समग्र विकास पर कैसा प्रभाव डालते हैं?",
     "How do smoky and narcotic substances affect an adolescent's overall development?",
     ["शारीरिक वृद्धि, मानसिक एकाग्रता और सीखने की क्षमता — तीनों को धीमा-क्षतिग्रस्त करते हैं", "केवल बाल बढ़ाते हैं", "कोई प्रभाव नहीं", "विकास दोगुना करते हैं"],
     ["They slow and damage bodily growth, mental focus and the capacity to learn — all three", "They only grow hair", "No effect", "They double development"],
     0,
     "जहर-मिला ईंधन इंजन को दौड़ा नहीं सकता — नशे की गाड़ी में विकास की रफ्तार गिरती है।",
     "Poison-mixed fuel cannot race an engine — in addiction's vehicle the speed of development falls."),

    ("adolescent-health", "medium",
     "किशोर के लिए तनाव (stress) के स्वस्थ नियंत्रण का तरीका क्या है?",
     "What is a healthy way of stress-control for an adolescent?",
     ["शौक, खेल या किसी विश्वसनीय अपने से बातचीत", "झगड़ा करना", "कमरे में बंद रहना", "नशे का सहारा"],
     ["A hobby, sport or talk with a trusted one", "Picking fights", "Staying locked in a room", "Taking refuge in intoxicants"],
     0,
     "भाप को सीटी से निकलना चाहिए, बर्तन नहीं फटना चाहिए — खेल, शौक और संवाद वे सीटियाँ हैं।",
     "Steam must leave by the whistle, not burst the vessel — sport, hobby and conversation are those whistles."),

    ("adolescent-health", "medium",
     "किशोरावस्था के शारीरिक परिवर्तनों को लेकर फैले मिथकों से कैसे निपटा जाता है?",
     "How does one deal with the myths spread about adolescent bodily changes?",
     ["विज्ञान-आधारित सही जानकारी से — जाँचकर, पूछकर", "मिथक को ही सच मान लेकर", "दोस्तों की बात पर बिना जाँच भरोसा करके", "विषय से पीछे हटकर"],
     ["With correct science-based information — checking and asking", "Accepting the myth as truth", "Trusting friends' word unchecked", "Backing away from the subject"],
     0,
     "मिथक अंधेरे की दीवार है, जानकारी उसमें खिड़की — प्रमाणित ज्ञान ही किशोर का असली दीवार-तोड़ है।",
     "A myth is a wall of darkness, information its window — verified knowledge alone is the adolescent's true wall-breaker."),

    ("adolescent-health", "medium",
     "सहपाठियों के दबाव (peer pressure) में गलत काम करने से बचने की सशक्त रणनीति क्या है?",
     "What is an empowered strategy to avoid wrong deeds under peer pressure?",
     ["अपना स्पष्ट 'नहीं' बनाए रखना और सही संग चुनना", "सब दोस्त छोड़ देना", "हर बात मान लेना", "झूठ बोलना"],
     ["Holding one's clear 'no' and choosing right company", "Leaving all friends", "Agreeing every time", "Telling lies"],
     0,
     "डगर बदलना पड़े तो बदलो, लेकिन मंज़िल के आगे नहीं — साफ इनकार और अच्छी संगति दोनों ढाल हैं।",
     "Change the lane if needed, but not ahead of the goal — clear refusal and good company are both shields."),

    ("adolescent-health", "medium",
     "किशोर के लिए सुबह का नाश्ता न छोड़ना क्यों कहा जाता है?",
     "Why is an adolescent told never to skip breakfast?",
     ["दिन भर की ऊर्जा और स्कूल में एकाग्रता की नींव वही रखती है", "इससे नींद आती है", "इससे कद घटता है", "इससे आवाज़ बदलती है"],
     ["It lays the base of the whole day's energy and focus at school", "It brings sleep", "It reduces height", "It changes the voice"],
     0,
     "खाली टैंक से सुबह की रेस नहीं — नाश्ता दिन की पहली ईंधन-भराई है, मन और शरीर दोनों की।",
     "No morning race on an empty tank — breakfast is the day's first fuelling, of both mind and body."),

    ("adolescent-health", "medium",
     "किशोर की दैनिक दिनचर्या में खेल-व्यायाम का स्थान क्यों निर्धारित होना चाहिए?",
     "Why must a fixed place for play-exercise be there in an adolescent's daily routine?",
     ["इससे मांसपेशियाँ मजबूत, मन हल्का और नींद गहरी होती है", "इससे भूख मर जाती है", "इससे पढ़ाई रुक जाती है", "इससे हड्डियाँ घुल जाती हैं"],
     ["Muscles grow strong, the mind light and sleep deep", "It kills appetite", "It stops study", "It dissolves bones"],
     0,
     "चलती धारा ही साफ रहती है — चलता शरीर ही स्वस्थ; व्यायाम किशोर की डाली को लचीला-मजबूत बनाता है।",
     "Only a flowing stream stays clean — only a moving body stays healthy; exercise keeps the adolescent branch supple-strong."),

    ("adolescent-health", "medium",
     "मुँहासों के दौर में त्वचा की सामान्य देखभाल-पद्धति क्या है?",
     "What is the ordinary care routine for skin in the pimple-phase?",
     ["मुँह को दिन में दो बार हल्के साबुन-पानी से धोना और दाबना-कुतरना नहीं", "मुँहासों को नाखून से दबाते रहना", "मोटी क्रीम की मालिश", "त्वचा को पूरी तरह छेड़छाड़"],
     ["Washing the face twice a day with mild soap-water and not squeezing or picking", "Pressing the pimples with nails", "Massaging thick cream", "Tampering with the skin fully"],
     0,
     "हल्की सफाई और धैर्य — यही मुँहासों की सामान्य चिकित्सा; दबाने से जलन और दाग बढ़ते हैं।",
     "Gentle cleaning and patience — that is the ordinary treatment of pimples; squeezing raises irritation and marks."),

    ("adolescent-health", "medium",
     "किशोर-स्वास्थ्य का सूत्र-समूह कौन-सा है?",
     "Which is the formula-set of adolescent health?",
     ["संतुलित आहार + नियमित व्यायाम + पर्याप्त नींद + सकारात्मक दृष्टिकोण", "भरपूर मिठाई + देर रात जागना", "अधूरा भोजन + दिन भर बैठना", "नशा + तनाव"],
     ["Balanced diet + regular exercise + adequate sleep + positive attitude", "Plenty of sweets + late-night waking", "Half meals + sitting all day", "Intoxicants + stress"],
     0,
     "चार पहिए — आहार, व्यायाम, नींद, सोच — इन्हीं पर किशोर-स्वास्थ्य की गाड़ी सधी चलती है।",
     "Four wheels — diet, exercise, sleep, outlook — on these very wheels runs the cart of adolescent health."),

    ("adolescent-health", "medium",
     "किशोरावस्था के भावनात्मक उतार-चढ़ावों में वयस्कों का मार्गदर्शन कैसा सहारा सिद्ध होता है?",
     "In the emotional swings of adolescence, how does adult guidance prove supportive?",
     ["अनुभव की रोशनी में सही-गलत की राह दिखाता है और अकेलापन मिटाता है", "यह स्वतंत्रता छीन लेता है", "यह समस्याएँ बढ़ाता है", "इसका कोई प्रभाव नहीं"],
     ["In the light of experience it shows the right-wrong road and removes loneliness", "It snatches independence", "It multiplies problems", "It has no effect"],
     0,
     "कोहरे में चलते मुसाफ़िर को दूर का दीया काम आता है — वयस्क-मार्गदर्शन किशोर का वही दूर-दीया है।",
     "To a traveller in fog, a distant lamp helps — adult guidance is that far lamp for the adolescent."),

    ("adolescent-health", "medium",
     "किशोर के लिए नियमित दिनचर्या (routine) का महत्व क्यों बताया जाता है?",
     "Why is a regular routine emphasised for an adolescent?",
     ["खाने-सोने-पढ़ने का संतुलित क्रम शरीर-घड़ी को सधाता है", "इससे छुट्टियाँ बढ़ती हैं", "इससे स्कूल भूल जाता है", "इससे भूख खत्म होती है"],
     ["A balanced order of eating-sleeping-studying tunes the body-clock", "It increases holidays", "It makes one forget school", "It ends appetite"],
     0,
     "घड़ी की सुइयाँ जब नियम से चलें, तभी समय का सदुपयोग होता है — दिनचर्या वही नियम-सुई है।",
     "Only when the clock's hands run by rule is time well-used — routine is that rule-hand."),

    ("adolescent-health", "hard",
     "एक किशोर रोज़ नाश्ता छोड़ता है, देर रात जागता है और बाहर का भोजन खाता है — इस शैली का दीर्घकालिक प्रभाव क्या रहेगा?",
     "An adolescent skips breakfast daily, wakes late nights and eats out — what will be the long-term effect of this style?",
     ["वृद्धि-ऊर्जा-एकाग्रता तीनों पर धीरे-धीरे विपरीत असर", "कोई प्रभाव नहीं", "तीनों दोगुने हो जाएँगे", "केवल बाल अच्छे होंगे"],
     ["Gradual adverse effect on growth, energy and concentration — all three", "No effect", "All three will double", "Only hair will improve"],
     0,
     "तीन कमजोर थंब खड़ी दीवार नहीं खींचते — कमजोर आदतें मिलकर किशोर की वृद्धि-इमारत को धीमा करती हैं।",
     "Three weak pegs cannot hold a standing wall — weak habits together slow the adolescent's growth-edifice."),

    ("adolescent-health", "hard",
     "किशोर-स्वास्थ्य संबंधी निम्न में से कौन-सा कथन गलत है?",
     "Which statement about adolescent health is WRONG?",
     ["मादक पदार्थों का कभी-कभार सेवन हानिरहित होता है", "पर्याप्त नींद वृद्धि के अनुकूल है", "संतुलित आहार में सभी पोषक तत्व होते हैं", "व्यायाम मानसिक स्वास्थ्य को भी सहायक है"],
     ["Occasional use of intoxicants is harmless", "Adequate sleep favours growth", "A balanced diet contains all nutrients", "Exercise helps mental health too"],
     0,
     "पहला कदम ही पुल नहीं बनने दो — 'कभी-कभार' वाला कथन जाल है; नशे की कोई हानिरहित मात्रा नहीं।",
     "Do not let the first step itself become a bridge — the 'occasional' claim is a snare; no dose of intoxicant is harmless."),
]
