# -*- coding: utf-8 -*-
"""B11 Part-2 — Health, Disease & Microorganisms (chapter-11).
70 items: disease-dynamics 25 (E8/M14/H3) + immunity-prevention 25 (E8/M14/H3)
          + health-hygiene 20 (E6/M13/H1).
Tuple: (topic, difficulty, question_hi, question_en, options_hi[4], options_en[4], correct_idx, expl_hi, expl_en)

DENY-AWARENESS carried from Part-1 header, Part-2 specifics:
- B06/ch-07 owns deficiency-disease DEFINITION (q725) => 'non-communicable' examples
  name deficiency only as an option-word, never as a definition question.
- B10/ch-10 owns adolescent diet/sleep/exercise/skin-pimple items => hygiene items here
  use community/food/water/vector-control angles, not adolescent-lifestyle repeats.
- B08/ch-09 owns blood-group antibodies (q952) => antibodies defined only as germ-defence
  proteins in blood, no blood-grouping.
- No advanced immunology (no T-cell/B-cell nomenclature, no serology), no clinical
  pathology, no ecosystem-level decomposition (B12) — only transmission-break logic.
"""

PART2 = [
    # ================= DISEASE DYNAMICS — 25 (E8/M14/H3) =================
    ("disease-dynamics", "easy",
     "संचारी रोग (communicable disease) किसे कहते हैं?",
     "What is called a communicable disease?",
     ["जो एक व्यक्ति से दूसरे व्यक्ति तक फैल सकता है", "जो केवल पहाड़ों पर होता है", "जो केवल पौधों को होता है", "जो चंद्रमा से आता है"],
     ["One that can spread from one person to another", "One that occurs only on mountains", "One that afflicts only plants", "One that comes from the moon"],
     0,
     "खांसते-छींकते, छूते-छाते या दूषित जल-भोजन से जो रोग साझा हो जाए — वही संचारी।",
     "A disease that gets shared through cough-sneeze, touch or tainted water-food — that is communicable."),

    ("disease-dynamics", "easy",
     "निम्न में से कौन-सा असंचारी (non-communicable) रोग है?",
     "Which of the following is a non-communicable disease?",
     ["मधुमेह", "हैजा", "खसरा", "मलेरिया"],
     ["Diabetes", "Cholera", "Measles", "Malaria"],
     0,
     "मधुमेह किसी के छूने या पास बैठने से नहीं फैलता — हैजा, खसरा, मलेरिया तीनों का फैलने का रास्ता है।",
     "Diabetes does not spread by touch or sitting near — cholera, measles, malaria all have a spreading route."),

    ("disease-dynamics", "easy",
     "रोगी के नाक-मुँह से निकली बूंदें हवा में कैसे रोग फैलाती हैं?",
     "How do droplets from a patient's nose-mouth spread disease in air?",
     ["साँस के साथ दूसरे व्यक्ति के शरीर में पहुँचकर", "दीवारों को रंगकर", "फर्श को ठंडा करके", "पंखे को तेज़ करके"],
     ["By entering another person's body with the breath", "By painting the walls", "By cooling the floor", "By speeding the fan"],
     0,
     "छींक की बूंदें हवा में रोगाणु-बम बनकर तैरती हैं — साँस लेते ही वे नए शरीर में उतर जाती हैं।",
     "Sneeze-droplets float in air as germ-bombs — the moment someone breathes, they descend into a new body."),

    ("disease-dynamics", "easy",
     "रोग के 'वाहक' का सामान्य उदाहरण कौन-सा है?",
     "Which is the common example of a disease 'vector'?",
     ["मच्छर", "गाय", "नीम का पेड़", "नदी का पत्थर"],
     ["The mosquito", "The cow", "The neem tree", "The river stone"],
     0,
     "मलेरिया-डेंगू जैसे रोगों में मच्छर ही वाहक का जीता-जागता उदाहरण है।",
     "In diseases like malaria-dengue the mosquito is the living-breathing example of a vector."),

    ("disease-dynamics", "easy",
     "संक्रमित जल पीने से होने वाले रोग किस श्रेणी में आते हैं?",
     "Diseases caused by drinking infected water fall in which category?",
     ["जल-वाहित (water-borne) रोग", "वायु-वाहित रोग", "संपर्क-रोग", "वंशानुगत रोग"],
     ["Water-borne diseases", "Air-borne diseases", "Contact diseases", "Hereditary diseases"],
     0,
     "हैजा-टाइफॉइड जैसे रोग जल की सवारी में आते हैं — इसीलिए जल-वाहित कहलाते हैं।",
     "Diseases like cholera-typhoid ride in water — hence called water-borne."),

    ("disease-dynamics", "easy",
     "किसी रोग के 'लक्षण' (symptoms) से क्या तात्पर्य है?",
     "What is meant by the 'symptoms' of a disease?",
     ["शरीर में दिखने वाले असामान्य संकेत जैसे बुखार, खांसी", "शरीर का सामान्य रहना", "दवा की कीमत", "डॉक्टर की फीस"],
     ["Abnormal signs appearing in the body like fever, cough", "The body staying normal", "The price of medicine", "The doctor's fee"],
     0,
     "बुखार-खांसी-दर्द जैसे संकेत शरीर के घंटी-नाद हैं — भीतर कुछ गड़बड़ है, यही बताते हैं।",
     "Signs like fever-cough-pain are the body's bell-notes — they announce something is wrong inside."),

    ("disease-dynamics", "easy",
     "मलेरिया-मच्छर गंदे जल में नहीं — अपनी प्रजाति के अनुकूल जल में पलता है। रोग-रोकथाम की दृष्टि से सबसे सरल उपाय क्या है?",
     "The malaria mosquito breeds not in dirty water but in water suited to its species. What is the simplest step for disease-control?",
     ["घर-आसपास जल जमा न होने देना", "घर में पानी भरकर रखना", "टंकी खुली रखना", "गमलों में पानी छोड़ना"],
     ["Not letting water collect around the house", "Keeping the house stocked with water", "Leaving the tank open", "Leaving water in flowerpots"],
     0,
     "मच्छर का घर ही न बनने दो — ठहराव जल हटा दो तो वाहक की पूरी पीढ़ी वहीं रुक जाती है।",
     "Do not let the mosquito's house be built — remove standing water and the vector's whole generation halts there."),

    ("disease-dynamics", "easy",
     "स्वस्थ व्यक्ति को रोगी के संपर्क में रहने से कौन-से रोग फैलने का खतरा रहता है?",
     "Which diseases risk spreading when a healthy person stays in contact with a patient?",
     ["खसरा और चेचक जैसे वायु-संपर्क रोग", "मधुमेह", "रक्ताल्पता", "दृष्टि-दोष"],
     ["Air-contact diseases like measles and smallpox", "Diabetes", "Anaemia", "Defect of vision"],
     0,
     "छींक-खांसी से फैलने वाले रोग संपर्ग में रहकर आसानी से साझा हो जाते हैं।",
     "Diseases spread by sneeze-cough get shared easily by staying in proximity."),

    ("disease-dynamics", "medium",
     "रोगाणु शरीर में प्रवेश करने और रोग के लक्षण दिखने के बीच का समय-अंतराल क्या कहलाता है?",
     "What is the time-gap between the pathogen's entry into the body and the appearance of disease symptoms called?",
     ["सुप्तावधि (incubation period)", "परास", "तरंगदैर्ध्य", "आवर्तकाल"],
     ["Incubation period", "Range", "Wavelength", "Time period"],
     0,
     "रोगाणु घुसता है, फिर चुपचाप बढ़ता है — बुखार दिखने तक की यह चुप्पी ही सुप्तावधि है।",
     "The germ enters, then quietly multiplies — this silence till the fever shows is the incubation period."),

    ("disease-dynamics", "medium",
     "संचारी रोग की श्रृंखला तोड़ने का अर्थ है —",
     "Breaking the chain of a communicable disease means —",
     ["रोगाणु के फैलने के मार्ग को काटना", "रोगी से दोस्ती करना", "रोगाणुओं को भोजन देना", "श्रृंखला को लंबा करना"],
     ["Cutting the route by which the pathogen spreads", "Befriending the patient", "Feeding the pathogens", "Lengthening the chain"],
     0,
     "जल-उबालना, हाथ-धोना, मच्छर-भगाना — हर उपाय श्रृंखला की एक कड़ी तोड़ता है, रोग वहीं रुक जाता है।",
     "Boiling water, washing hands, chasing mosquitoes — every step breaks one link of the chain, and the disease stops right there."),

    ("disease-dynamics", "medium",
     "महामारी (epidemic) किसे कहते हैं?",
     "What is called an epidemic?",
     ["जब कोई रोग किसी क्षेत्र में बहुत अधिक लोगों को एक साथ प्रभावित करे", "जब एक आदमी जुकाम से छींके", "जब फसल अच्छी हो", "जब बारिश न हो"],
     ["When a disease affects very many people of an area at once", "When one man sneezes with a cold", "When the crop is good", "When there is no rain"],
     0,
     "जब रोग की आग पूरे इलाके में फैल जाए — कई सौ-हज़ार लोग एक साथ बीमार — तो उसे महामारी कहते हैं।",
     "When the disease's fire spreads across a whole area — hundreds-thousands ill together — it is called an epidemic."),

    ("disease-dynamics", "medium",
     "रोगी को अलग रखना (isolation) किस उद्देश्य से किया जाता है?",
     "With what aim is a patient kept separate (isolation)?",
     ["ताकि रोगाणु दूसरों तक न फैले", "ताकि रोगी अकेला महसूस करे", "ताकि घर साफ दिखे", "ताकि पड़ोसी जल जाएँ"],
     ["So that the pathogen does not reach others", "So that the patient feels lonely", "So that the house looks clean", "So that the neighbours burn"],
     0,
     "संक्रामक रोगी को अलग कमरे में रखना श्रृंखला की पहली कड़ी पर ही जाल बिछाना है।",
     "Keeping an infectious patient in a separate room is spreading the net on the very first link of the chain."),

    ("disease-dynamics", "medium",
     "हैजा से बचने का सबसे प्रभावी घरेलू उपाय क्या है?",
     "What is the most effective household protection against cholera?",
     ["उबला-शुद्ध जल पीना और स्वच्छ भोजन", "नहर का जल सीधा पीना", "कच्चा भोजन खुले में रखना", "गंदे हाथों से खाना"],
     ["Drinking boiled-pure water and eating clean food", "Drinking canal water straight", "Keeping raw food in the open", "Eating with dirty hands"],
     0,
     "हैजा जल-भोजन की सवारी से आता है — सवारी ही बंद कर दो, रोग दरवाज़े पर ही लौट जाएगा।",
     "Cholera arrives by the water-food ride — stop the ride itself and the disease returns from the doorstep."),

    ("disease-dynamics", "medium",
     "'वाहक नियंत्रण' (vector control) से क्या तात्पर्य है?",
     "What is meant by 'vector control'?",
     ["रोग-वहन करने वाले जीवों की संख्या घटाना-रोकना", "रोगियों को बाँध देना", "वाहनों की रेस", "रोग का नाम बदलना"],
     ["Reducing-stopping the population of disease-carrying organisms", "Tying up the patients", "A race of vehicles", "Renaming the disease"],
     0,
     "मच्छर-मक्खी की प्रजाति रोकना वाहक-नियंत्रण है — सवार गिरे नहीं, तो रोग भी नहीं गिरेगा।",
     "Checking the mosquito-fly breed is vector control — if the rider does not rise, the disease will not rise either."),

    ("disease-dynamics", "medium",
     "भोजन को खुला और लंबे समय तक रखना खतरनाक क्यों है?",
     "Why is keeping food open and for long hours dangerous?",
     ["हवा के जीवाणु-बीज उस पर बैठकर बढ़ने लगते हैं", "भोजन का रंग सुंदर हो जाता है", "भोजन भारी हो जाता है", "भोजन मीठा हो जाता है"],
     ["Airborne germ-seeds sit on it and begin to multiply", "The food's colour turns beautiful", "The food becomes heavy", "The food becomes sweet"],
     0,
     "खुला भोजन हवा के रोगाणुओं का मुफ्त-ढाबा बन जाता है — ढकना और जल्दी खा जाना ही समझदारी।",
     "Open food becomes a free diner for airborne germs — covering it and eating soon is the wisdom."),

    ("disease-dynamics", "medium",
     "एक ही रोगाणु से एक इलाके में कई लोग एक साथ बीमार हो गए — इसकी सबसे संभावित व्याख्या क्या है?",
     "Several people of an area fell ill together from the same pathogen — what is the most likely explanation?",
     ["सभी का एक ही स्रोत (जल/भोजन) से संपर्क हुआ", "सभी ने एक साथ नाच किया", "सभी को इनाम मिला", "सभी एक साथ बूढ़े हो गए"],
     ["All of them contacted one common source (water/food)", "All danced together", "All got a prize", "All grew old together"],
     0,
     "एक ही कुएँ-टंकी का दूषित जल जब कई घर पीते हैं, तो बीमारी झुंड में आती है — स्रोत एक, रोगी अनेक।",
     "When many homes drink one contaminated well-tank's water, disease arrives in a herd — source one, patients many."),

    ("disease-dynamics", "medium",
     "छींकते समय नाक-मुँह ढकना किस सिद्धांत का पालन है?",
     "Covering nose-mouth while sneezing is following which principle?",
     ["संचरण-मार्ग काटने का", "वायु बेचने का", "ध्वनि-प्रदूषण का", "तापमान बढ़ाने का"],
     ["Cutting the route of transmission", "Selling air", "Of noise pollution", "Of raising temperature"],
     0,
     "रुमाल-कोहनी से छींक रोकना रोगाणु-बम को हवा में ही निष्क्रिय कर देता है — श्रृंखला की कड़ी वहीं टूटती है।",
     "Stopping the sneeze with a hanky-elbow defuses the germ-bomb in the air itself — the chain's link breaks right there."),

    ("disease-dynamics", "medium",
     "रोग फैलने की 'सीधी सवारियाँ' कौन-सी हैं?",
     "Which are the 'direct rides' of disease spread?",
     ["वायु, जल, भोजन, स्पर्श और वाहक", "केवल सोशल मीडिया", "केवल रेडियो", "केवल तार"],
     ["Air, water, food, touch and vector", "Only social media", "Only radio", "Only wires"],
     0,
     "हवा, पानी, खाना, छूना और मच्छर-मक्खी — रोगाणु की पाँच चलती-फिरती सवारियाँ; सबका टिकट अलग-अलग तरीके से काटा जाता है।",
     "Air, water, food, touch and mosquito-fly — the five ever-moving rides of pathogens; each ticket is cut by a different method."),

    ("disease-dynamics", "medium",
     "अशुद्ध जल से होने वाले दो रोगों का सुमेलन कौन-सा सही है?",
     "Which matching of two diseases from impure water is correct?",
     ["हैजा + टाइफॉइड", "पोलियो + दाद", "मलेरिया + चेचक", "खसरा + रतुआ"],
     ["Cholera + Typhoid", "Polio + Ringworm", "Malaria + Smallpox", "Measles + Rust"],
     0,
     "हैजा और टाइफॉइड दोनों दूषित जल-भोजन के जीवाणु-रोग हैं — एक ही सवारी के दो सवार।",
     "Cholera and typhoid are both bacterial diseases of tainted water-food — two riders of the same ride."),

    ("disease-dynamics", "medium",
     "रोग-प्रसार में 'जन-संख्या घनत्व' का प्रभाव क्यों देखा जाता है?",
     "Why is 'population density' seen to affect disease spread?",
     ["भीड़ में निकट-संपर्क बढ़ता है, रोगाणु को सवारी मिलना आसान हो जाता है", "भीड़ में हवा ज्यादा होती है", "भीड़ में पानी गायब होता है", "घनत्व से रोग डरता है"],
     ["In crowds close contact rises, making it easy for the pathogen to find a ride", "Crowds have more air", "Crowds lack water", "Disease fears density"],
     0,
     "एक छींक भीड़ में दस लोगों तक पहुँचती है, सुनसान में किसी को नहीं — संपर्क जितना, संचरण उतना।",
     "One sneeze reaches ten people in a crowd, none in a desert — as the contact, so the transmission."),

    ("disease-dynamics", "medium",
     "संक्रमित व्यक्ति के बर्तन-वस्त्र को अलग रखने का कारण क्या है?",
     "Why are an infected person's utensils-clothes kept separate?",
     ["उन पर लगे रोगाणु स्वस्थ सदस्यों तक न पहुँचें", "बर्तन नए दिखें", "कपड़े रंगीन हों", "घर बड़ा लगे"],
     ["So that germs on them do not reach healthy members", "So the utensils look new", "So the clothes are coloured", "So the house looks big"],
     0,
     "रोगी का गिलास भी रोग का गवाह हो सकता है — अलग रखना ही उसकी गवाही बंद करना है।",
     "Even the patient's glass can be a witness of disease — keeping it separate is shutting that testimony."),

    ("disease-dynamics", "medium",
     "खाने के कुछ घंटे बाद उल्टी-दस्त से हुई 'भोजन-विषाक्तता' का सूक्ष्म कारण क्या होता है?",
     "What is the micro-cause of 'food poisoning' that struck with vomiting-loose motions some hours after eating?",
     ["भोजन में पले जीवाणुओं के बनाए विष", "भोजन का रंग", "भोजन का भार", "भोजन की थाली"],
     ["Toxins made by bacteria that grew in the food", "The food's colour", "The food's weight", "The food's plate"],
     0,
     "गर्मी में खुला रखा भोजन जीवाणुओं का विष-कारखाना बन जाता है — विष पेट में उतरते ही उबाल आता है।",
     "Food left open in the heat becomes a germ-toxin factory — the moment the toxin descends into the stomach, the churn begins."),

    ("disease-dynamics", "hard",
     "एक रोग जल से फैलता है, दूसरा वायु से, तीसरा वाहक से। तीनों के लिए क्रमशः उपाय-त्रयी का सही सुमेलन कौन-सा है?",
     "One disease spreads by water, another by air, a third by vector. Which is the correct matching of the remedy-triad respectively?",
     ["जल-उबालना, छींक-ढकना, मच्छर-नियंत्रण", "जल-गिराना, छींक-फैलाना, मच्छर-पालना", "जल-जमाना, वायु-बेचना, वाहक-बढ़ाना", "तीनों का एक ही उपाय — घुड़साल"],
     ["Boiling water, covering sneeze, mosquito-control", "Dropping water, spreading sneeze, rearing mosquitoes", "Storing water, selling air, raising vectors", "Same remedy for all three — a stable"],
     0,
     "हर सवारी का टिकट उसी के हिसाब से कटता है — जल का उबाल से, वायु का ढकने से, वाहक का नियंत्रण से।",
     "Each ride's ticket is cut per its own account — water's by boiling, air's by covering, vector's by control."),

    ("disease-dynamics", "hard",
     "'रोगाणु शरीर में घुसा, बढ़ा, विष फैलाया, लक्षण दिखे' — इस क्रम में सुप्तावधि कौन-से चरण के बीच की अवधि है?",
     "'The pathogen entered, multiplied, spread toxin, symptoms showed' — between which stages of this sequence lies the incubation period?",
     ["प्रवेश और लक्षण-प्रकट होने के बीच", "लक्षण और दवा के बीच", "दवा और डिस्चार्ज के बीच", "किसी चरण के बीच नहीं"],
     ["Between entry and the appearance of symptoms", "Between symptoms and medicine", "Between medicine and discharge", "Between no stages"],
     0,
     "प्रवेश से लक्षण तक का चुप-मौन अंतराल ही सुप्तावधि है — रोगाणु इसी दौरान चुपके से अपनी सेना बढ़ाता है।",
     "The silent interval from entry to symptom is the incubation period — in this very span the germ quietly raises its army."),

    ("disease-dynamics", "hard",
     "किसी रोग के 'वाहक' और 'रोगाणु' की भूमिकाओं पर विचार कीजिए — कौन-सा कथन सही है?",
     "Consider the roles of a disease's 'vector' and 'pathogen' — which statement is correct?",
     ["वाहक केवल पहुँचाता है, बीमारी रोगाणु करता है", "वाहक ही बीमारी करता है, रोगाणु सवार है", "दोनों एक ही जीव हैं", "दोनों की भूमिका उल्टी-सी है पर सही"],
     ["The vector only delivers; the pathogen causes the illness", "The vector causes illness; the pathogen is the rider", "Both are the same organism", "Both roles are inverted yet correct"],
     0,
     "मच्छर डाकिया है, प्लाज्मोडियम पत्र — बीमारी पत्र से लगती है, डाकिया से नहीं।",
     "The mosquito is the postman, Plasmodium the letter — illness comes from the letter, not the postman."),

    # ================= IMMUNITY & PREVENTION — 25 (E8/M14/H3) =================
    ("immunity-prevention", "easy",
     "प्रतिरक्षा (immunity) किसे कहते हैं?",
     "What is called immunity?",
     ["शरीर की रोग से लड़ने की क्षमता", "शरीर का रंग", "बालों की चमक", "नाखूनों की लंबाई"],
     ["The body's capacity to fight disease", "The body's colour", "The shine of hair", "The length of nails"],
     0,
     "जिस शरीर में रोगाणुओं से लड़ने की सेना जागी रहती है, उसे प्रतिरक्षा कहते हैं।",
     "The body in which the army to fight germs stays awake is said to have immunity."),

    ("immunity-prevention", "easy",
     "टीकाकरण (vaccination) से क्या प्राप्त होता है?",
     "What is gained from vaccination?",
     ["रोग के विरुद्ध सुरक्षा-क्षमता", "केवल भूख", "केवल नींद", "केवल बाल"],
     ["Protective capacity against a disease", "Only hunger", "Only sleep", "Only hair"],
     0,
     "टीका शरीर को रोग से पहले ही रोग का परिचय करा देता है — असली हमले पर शरीर तैयार मिलता है।",
     "A vaccine introduces the body to the disease before it arrives — at the real attack the body is found ready."),

    ("immunity-prevention", "easy",
     "एंटीबॉडी क्या होती हैं?",
     "What are antibodies?",
     ["रक्त में बनने वाले विशेष प्रोटीन जो रोगाणुओं को निष्क्रिय करते हैं", "हड्डी के टुकड़े", "त्वचा के रोम", "बाल की जड़ें"],
     ["Special proteins formed in blood that deactivate pathogens", "Pieces of bone", "Pores of skin", "Roots of hair"],
     0,
     "एंटीबॉडी शरीर के ताले-चाबी वाले प्रहरी हैं — रोगाणु को पहचानकर उसकी चाल बंद कर देते हैं।",
     "Antibodies are the body's lock-and-key sentries — recognising the germ, they stop its move."),

    ("immunity-prevention", "easy",
     "पोलियो की बूँदें देने का उद्देश्य क्या है?",
     "What is the aim of giving polio drops?",
     ["पोलियो वायरस के विरुद्ध शरीर की रक्षा-स्मृति जगाना", "बच्चे को नहलाना", "बच्चे को तौलना", "बच्चे का नाम रखना"],
     ["To awaken the body's defence-memory against the polio virus", "To bathe the child", "To weigh the child", "To name the child"],
     0,
     "दो बूँदों में छुपा संदेश — 'इस वायरस को पहचान लो' — आने वाले वर्षों तक शरीर यही याद रखता है।",
     "The message hidden in two drops — 'know this virus' — the body remembers it for years to come."),

    ("immunity-prevention", "easy",
     "त्वचा और श्लेष्म-झिल्ली शरीर की किस पंक्ति की रक्षा हैं?",
     "The skin and mucous membranes are the defence of which line of the body?",
     ["पहली रक्षा-पंक्ति (प्रवेश-रोध)", "अंतिम पंक्ति", "कोई पंक्ति नहीं", "बाहरी सजावट"],
     ["The first line of defence (entry-blocking)", "The last line", "No line at all", "External decoration"],
     0,
     "त्वचा की दीवार, नाक के बाल, गले की झिल्ली — ये सब रोगाणु को अंदर घुसने से पहले ही रोकते हैं।",
     "The skin's wall, the nose-hairs, the throat's membrane — all stop the germ before it enters."),

    ("immunity-prevention", "easy",
     "श्वेत रुधिर-कणिकाएँ (WBC) शरीर की रक्षा में क्या भूमिका निभाती हैं?",
     "What role do white blood cells (WBC) play in the body's defence?",
     ["वे रोगाणुओं को निगलकर नष्ट करती हैं", "वे शरीर को ठंडा करती हैं", "वे बाल बढ़ाती हैं", "वे भोजन पचाती हैं"],
     ["They swallow and destroy germs", "They cool the body", "They grow hair", "They digest food"],
     0,
     "WBC शरीर के संतरी-सैनिक हैं — रक्त-गली में गश्त लगाते हुए घुसैयियों को वहीं दबा देते हैं।",
     "WBC are the body's sentry-soldiers — patrolling the blood-lane they crush intruders on the spot."),

    ("immunity-prevention", "easy",
     "घाव पर दवा-पट्टी करना रोग-रोकथाम का कौन-सा तर्क है?",
     "What is the disease-prevention logic of dressing a wound?",
     ["खुला घाव रोगाणुओं का प्रवेश-द्वार है — ढकना द्वार बंद करना है", "घाव को हवा देना", "घाव को रंगना", "घाव को बढ़ना"],
     ["An open wound is the pathogens' entry-door — dressing it shuts the door", "Giving air to the wound", "Colouring the wound", "Growing the wound"],
     0,
     "त्वचा की टूटी दीवार पट्टी से फिर खड़ी हो जाती है — रोगाणु का रास्ता वहीं बंद।",
     "The skin's broken wall stands up again with the dressing — the pathogen's road closes right there."),

    ("immunity-prevention", "easy",
     "किसी रोग का टीका लगवाने के बाद वही रोग फिर नहीं होता — कारण?",
     "After getting vaccinated against a disease, the same disease does not recur — why?",
     ["शरीर की रक्षा-स्मृति उस रोगाणु को याद रखती है", "टीका शरीर में बर्फ जमा देता है", "रोगाणु डरकर भाग जाता है", "शरीर का रंग बदल जाता है"],
     ["The body's defence-memory remembers that pathogen", "The vaccine freezes the body", "The pathogen flees in fear", "The body's colour changes"],
     0,
     "एक बार पहचाना हुआ रोगाणु दोबारा आए तो स्मृति-प्रहरी फौरन एंटीबॉडी-फौज खड़ी कर देते हैं।",
     "If a once-recognised pathogen comes again, the memory-sentries raise the antibody-army at once."),

    ("immunity-prevention", "medium",
     "टीके में रोगाणु का कमज़ोर रूप क्यों रखा जाता है, पूरी ताकत वाला नहीं?",
     "Why is a weakened form of the pathogen kept in a vaccine, not a fully potent one?",
     ["शरीर पहचान तो बना ले, बीमार न हो", "शरीर बीमार ही न होने पाए, पहचान भी न बने", "टीका सस्ता पड़े", "टीका रंगीन दिखे"],
     ["So the body builds recognition without falling ill", "So the body neither falls ill nor builds recognition", "So the vaccine is cheap", "So the vaccine looks colourful"],
     0,
     "कमज़ोर रोगाणु एक मैक-डांस है — शरीर ताल सीख लेता है, पर थकता नहीं।",
     "A weakened germ is a mock-dance — the body learns the rhythm without getting tired."),

    ("immunity-prevention", "medium",
     "एडवर्ड जेनर की खोज की कहानी का मूल सुराग क्या था?",
     "What was the original clue in the story of Edward Jenner's discovery?",
     ["गाय-मट्ठे वाले दुग्धपालक चेचक से बचे रहते थे", "मच्छरों को गाय खा जाती थी", "भेड़ें चेचक फैलाती थीं", "घोड़े टीके बनाते थे"],
     ["Milkmaids having cowpox stayed safe from smallpox", "Cows ate up the mosquitoes", "Sheep spread smallpox", "Horses made vaccines"],
     0,
     "गायों के हल्के मट्ठे-रोग से बचे लोग भारी चेचक से भी बच निकलते थे — इसी गाँव-खुशबू से टीका-विज्ञान जन्मा।",
     "People spared by the cows' mild pox also escaped the heavy smallpox — from this village-scent was vaccine-science born."),

    ("immunity-prevention", "medium",
     "प्रतिरक्षा और टीकाकरण का संबंध क्या है?",
     "What is the relation between immunity and vaccination?",
     ["टीकाकरण प्रतिरक्षा जगाने का साधन है", "दोनों एक-दूसरे से असंबंधित हैं", "प्रतिरक्षा टीकाकरण का विपरीत है", "टीकाकरण रोग का इलाज है"],
     ["Vaccination is the means of awakening immunity", "The two are unrelated", "Immunity is the opposite of vaccination", "Vaccination is the cure of disease"],
     0,
     "टीका बीज है, प्रतिरक्षा फसल — टीका लगवाना प्रतिरक्षा की खेती बोना है।",
     "The vaccine is the seed, immunity the crop — getting vaccinated is sowing the field of defence."),

    ("immunity-prevention", "medium",
     "वायरल रोगों में एंटीबायोटिक काम नहीं करते — क्यों?",
     "Why do antibiotics not work in viral diseases?",
     ["एंटीबायोटिक जीवाणु-भित्ति जैसे लक्ष्यों पर बने हैं, जो वायरस में नहीं होते", "वायरस एंटीबायोटिक को खा जाते हैं", "एंटीबायोटिक डर जाते हैं", "वायरस बहुत मिलनसार हैं"],
     ["Antibiotics are built for targets like bacterial walls, which viruses do not have", "Viruses eat the antibiotics", "Antibiotics get scared", "Viruses are very friendly"],
     0,
     "जिस दीवार पर हथौड़ा बना है, वह दीवार वायरस के घर में है ही नहीं — इसीलिए जुकाम-बुखार जैसे वायरल रोगों में एंटीबायोटिक व्यर्थ हैं।",
     "The wall the hammer was made for does not exist in the virus's house — hence antibiotics are useless in viral colds-fevers."),

    ("immunity-prevention", "medium",
     "एंटीबायोटिक का बिना डॉक्टरी सलाह अधिक प्रयोग करना हानिकारक क्यों?",
     "Why is overusing antibiotics without medical advice harmful?",
     ["रोगाणु धीरे-धीरे दवा के विरुद्ध सख्त (प्रतिरोधी) हो जाते हैं", "दवा महँगी हो जाती है", "दवा का रंग उड़ जाता है", "दवा की बोतल टूट जाती है"],
     ["Germs gradually turn tough (resistant) against the medicine", "The medicine becomes costly", "The medicine's colour flies away", "The medicine's bottle breaks"],
     0,
     "हर अधूरी लड़ाई दुश्मन को तराशती है — बिना जरूरत दी गई दवा जीवाणु को उसी दवा के लिए पहलवान बना देती है।",
     "Every half-fought battle whets the foe — medicine given needlessly turns the bacterium into a wrestler against that very drug."),

    ("immunity-prevention", "medium",
     "भारत में पोलियो-मुक्ति की सफलता का आधार क्या रणनीति रही?",
     "What strategy underpinned India's success towards a polio-free status?",
     ["घर-घर जाकर बूँदें देना (पल्स-पोलियो अभियान)", "सबको अस्पताल बंद करना", "मच्छर पालना", "नहरें खोलना"],
     ["Door-to-door drop-giving (Pulse Polio campaign)", "Closing all hospitals", "Rearing mosquitoes", "Opening canals"],
     0,
     "पल्स-पोलियो अभियान ने एक ही दिन करोड़ों बच्चों को ढक लिया — वायरस को घर ही नहीं मिला।",
     "The Pulse Polio campaign covered crores of children on a single day — the virus found no home."),

    ("immunity-prevention", "medium",
     "जल-जनित रोगों से बचाव की तीन-स्तरीय रेखा कौन-सी है?",
     "Which is the three-layered line of protection against water-borne diseases?",
     ["उबालना/छानना, स्रोत की सुरक्षा, जल-शुद्धि-प्रणाली", "पानी इकट्ठा करना, उल्टा गिराना, भूल जाना", "कुएँ में मल डालना, टंकी खोलना, पाइप काटना", "पानी रंगना, बेचना, उड़ाना"],
     ["Boiling/filtering, protecting the source, water-purification systems", "Collecting water, dropping it, forgetting it", "Putting waste in wells, opening tanks, cutting pipes", "Colouring water, selling it, flying it"],
     0,
     "स्रोत से गिलास तक — हर मोड़ पर जल की सुरक्षा ही जल-जनित रोगों की दीवार है।",
     "From source to glass — water's security at every turn is the wall against water-borne diseases."),

    ("immunity-prevention", "medium",
     "मलेरिया-रोकथाम के लिए व्यक्तिगत स्तर के उपायों में क्या शामिल है?",
     "What is included in personal-level measures against malaria?",
     ["मच्छरदानी, पूरे कपड़े, रिपेलेंट का प्रयोग", "रात में नंगे रहना", "खुली खिड़कियों पर सोना", "पानी में खड़े होना"],
     ["Mosquito nets, full clothes, use of repellents", "Staying bare at night", "Sleeping by open windows", "Standing in water"],
     0,
     "वाहक के काटने से बचना ही मलेरिया में व्यक्तिगत दीवार है — जाल, कपड़ा और रिपेलेंट तीन परतें।",
     "Saving oneself from the vector's bite is the personal wall in malaria — net, cloth and repellent its three layers."),

    ("immunity-prevention", "medium",
     "बच्चों के लिए टीकाकरण-समय-सारणी (जैसे BCG, DPT) का पालन क्यों जरूरी माना जाता है?",
     "Why is following the immunisation schedule (like BCG, DPT) for children considered necessary?",
     ["हर टीका निश्चित आयु-खिड़की में सबसे असरदार सुरक्षा देता है", "टीके केवल बड़ों के लिए हैं", "समय-सारणी मनोरंजन के लिए है", "टीके रंग बदलने के लिए हैं"],
     ["Each vaccine gives the most effective protection in a fixed age-window", "Vaccines are only for adults", "The schedule is for entertainment", "Vaccines are for changing colours"],
     0,
     "बचपन की डोज़-घड़ी समय पर चढ़ाई जाए तो रक्षा-दीवार पूरी खड़ी होती है — छूटी खिड़की दीवार में गड्ढा छोड़ती है।",
     "Wound the childhood dose-clock on time and the defence-wall stands complete — a missed window leaves a pit in the wall."),

    ("immunity-prevention", "medium",
     "प्रतिरक्षा के दो स्रोत — जन्मजात और टीके/रोग से अर्जित। 'अर्जित प्रतिरक्षा' की पहचान क्या है?",
     "Two sources of immunity — inborn and acquired via vaccine/disease. What is the mark of 'acquired immunity'?",
     ["विशिष्ट रोगाणु से मिलने के बाद उसी के विरुद्ध विकसित स्मृति-रक्षा", "जन्म से हर रोग के विरुद्ध पूरी तैयारी", "केवल त्वचा की मोटाई", "केवल बालों की संख्या"],
     ["Memory-defence developed against a specific pathogen after encountering it", "Full readiness against every disease from birth", "Only the thickness of skin", "Only the number of hairs"],
     0,
     "जन्मजात रक्षा सामान्य चौकी है; अर्जित रक्षा नाम-अंकित वारंट — एक बार मिला रोगाणु, उसका दस्तावेज उम्र भर।",
     "Inborn defence is a general checkpoint; acquired defence is a named warrant — a germ met once, its dossier lifelong."),

    ("immunity-prevention", "medium",
     "सुरक्षित पेयजल के लिए घरेलू 'तीन-छलनी' विधि क्या है?",
     "What is the household 'three-strainer' method for safe drinking water?",
     ["छानना + उबालना + ढककर रखना", "मिलाना + रंगना + बेचना", "गर्म करना + जमाना + उड़ाना", "इकट्ठा करना + छलाना + भूलना"],
     ["Filtering + boiling + keeping covered", "Mixing + colouring + selling", "Heating + freezing + flying", "Collecting + straining + forgetting"],
     0,
     "छानलो बड़े कण, उबालो रोगाणु, ढको दोबारा गिरने से — तीन कदम, एक सुरक्षित गिलास।",
     "Strain the big particles, boil the germs, cover from falling again — three steps, one safe glass."),

    ("immunity-prevention", "medium",
     "रोग-प्रतिरोध में पौष्टिक आहार की भूमिका क्या है?",
     "What is the role of nourishing food in disease resistance?",
     ["अच्छा पोषण रक्षा-सेना (WBC-एंटीबॉडी) की ताकत बनाए रखता है", "पोषण रोगाणुओं को खिलाता है", "पोषण से रक्षा-सेना भाग जाती है", "पोषण का रोग से कोई संबंध नहीं"],
     ["Good nutrition keeps the defence army (WBC-antibodies) strong", "Nutrition feeds the germs", "The defence army flees from nutrition", "Nutrition has no relation with disease"],
     0,
     "सेना भूखी लड़ नहीं सकती — पोषण ही रक्षा-तंत्र का राशन-भंडार है।",
     "An army hungry cannot fight — nutrition is the ration-store of the defence system."),

    ("immunity-prevention", "medium",
     "हैजा में ORS (नमक-चीनी का घोल) क्यों दिया जाता है?",
     "Why is ORS (salt-sugar solution) given in cholera?",
     ["दस्तों से खोया जल-लवण तुरंत पूरा करने के लिए", "रोगाणु को मीठा खिलाने के लिए", "बुखार बढ़ाने के लिए", "नींद लाने के लिए"],
     ["To quickly restore the water-salts lost through loose motions", "To feed sweets to the germ", "To raise the fever", "To bring sleep"],
     0,
     "हैजा का असली खतरा शरीर का सूख जाना है — ORS जल-लवण की टपक-सिंचाई है।",
     "Cholera's real danger is the body drying out — ORS is the drip-irrigation of water-salts."),

    ("immunity-prevention", "medium",
     "'वाहक नियंत्रण' में मच्छरदानी और जल-स्रोत-प्रबंधन — दोनों की अपेक्षा क्या है?",
     "In 'vector control', what is expected of both mosquito nets and water-source management?",
     ["जाल काटने की दो कड़ियाँ — काटना और प्रजनन-रोकना", "दोनों से मच्छर मोटे होते हैं", "दोनों मच्छरों को आमंत्रण हैं", "दोनों का आपस में मेल नहीं"],
     ["Two links of chain-cutting — biting and breeding-stop", "Both fatten mosquitoes", "Both invite mosquitoes", "The two are unrelated"],
     0,
     "जाल रात की काट से बचाता है, जल-प्रबंधन कल की पीढ़ी से — दोनों मिलकर वाहक का वृत्त ही बंद करते हैं।",
     "The net saves from tonight's bite, water-management from tomorrow's generation — together they shut the vector's circle."),

    ("immunity-prevention", "hard",
     "एक व्यक्ति को चेचक हो चुका है और ठीक हो गया है — दोबारा चेचक का खतरा प्रायः क्यों नहीं रहता?",
     "A person has had smallpox and recovered — why does the risk of smallpox again usually not remain?",
     ["उस रोग के विरुद्ध शरीर की स्मृति-प्रतिरक्षा बन चुकी है", "रोगाणु उसका प्रशंसक बन गया", "शरीर में चेचक की जगह खत्म हो गई", "चेचक ने उसे विदा कर दिया"],
     ["The body's memory-immunity against that disease has formed", "The germ became his fan", "The place for smallpox in his body finished", "Smallpox bade him farewell"],
     0,
     "प्राकृतिक संक्रमण भी टीके जैसा ही पाठ पढ़ा देता है — एंटीबॉडी-स्मृति उम्रों तक कायम।",
     "A natural infection too teaches the same lesson as a vaccine — the antibody-memory lasts for ages."),

    ("immunity-prevention", "hard",
     "टीका, एंटीबॉडी, स्मृति-प्रतिरक्षा — तीनों की श्रृंखला में सही क्रम क्या है?",
     "What is the correct order in the chain of vaccine, antibody, memory-immunity?",
     ["टीका → एंटीबॉडी निर्माण → स्मृति-प्रतिरक्षा", "एंटीबॉडी → टीका → स्मृति", "स्मृति → एंटीबॉडी → टीका", "कोई क्रम नहीं"],
     ["Vaccine → antibody formation → memory-immunity", "Antibody → vaccine → memory", "Memory → antibody → vaccine", "No order"],
     0,
     "टीका पहला पत्र है, एंटीबॉडी उत्तर, स्मृति अभिलेखागार — क्रम यही तो है।",
     "The vaccine is the first letter, the antibody the reply, memory the archive — this indeed is the order."),

    ("immunity-prevention", "hard",
     "'जन्मजात रक्षा सामान्य है, अर्जित रक्षा विशिष्ट है' — इस कथन की पुष्टि करने वाला उदाहरण कौन-सा है?",
     "'Inborn defence is general, acquired defence is specific' — which example confirms this statement?",
     ["त्वचा हर रोगाणु को रोकती है; चेचक-रोगी की स्मृति केवल चेचक वायरस को मारती है", "त्वचा कुछ नहीं रोकती; स्मृति सब कुछ मारती है", "दोनों एक जैसे काम करते हैं", "न त्वचा रोकती है न स्मृति मारती है"],
     ["Skin blocks every germ; a smallpox-patient's memory kills only the smallpox virus", "Skin blocks nothing; memory kills everything", "Both do identical work", "Neither skin blocks nor memory kills"],
     0,
     "त्वचा चौकीदार है — सबको रोके; अर्जित स्मृति निशाना-बर्दार है — केवल अपने वारंट वाले को पहचाने।",
     "The skin is the watchman — stops all; acquired memory is the marksman — recognises only those on its warrant."),

    # ================= HEALTH & HYGIENE — 20 (E6/M13/H1) =================
    ("health-hygiene", "easy",
     "'स्वास्थ्य' केवल 'बीमारी न होना' नहीं है — इसकी पूरी परिभाषा क्या है?",
     "Health is not merely 'absence of disease' — what is its complete definition?",
     ["शारीरिक, मानसिक और सामाजिक रूप से अच्छी स्थिति", "केवल तगड़ा शरीर", "केवल मोटा शरीर", "केवल सुंदर चेहरा"],
     ["A good state physically, mentally and socially", "Only a strong body", "Only a fat body", "Only a beautiful face"],
     0,
     "स्वस्थ वह जो शरीर से चुस्त, मन से शांत और समाज में सहज हो — तीनों आँगन रौशन हों।",
     "Healthy is one who is nimble in body, calm in mind and easy in society — all three couryards lit."),

    ("health-hygiene", "easy",
     "शौच के बाद और भोजन से पहले हाथ धोना किन रोगों के खतरे को काटता है?",
     "Washing hands after defecation and before eating cuts the risk of which diseases?",
     ["हैजा-टाइफॉइड जैसे जल-भोजन जनित रोग", "केवल बाल-झड़ना", "केवल आँखों का चितवना", "केवल जूतों का घिसना"],
     ["Water-food borne diseases like cholera-typhoid", "Only hair fall", "Only blinking of eyes", "Only wearing of shoes"],
     0,
     "हाथ रोगाणु की सबसे व्यस्त सवारी है — साबुन से धोल तो भाड़ा ही बंद।",
     "Hands are the germ's busiest ride — wash with soap and the fare stops."),

    ("health-hygiene", "easy",
     "घर के आस-पास कचरा जमा रहने से कौन-सा स्वास्थ्य-खतरा बनता है?",
     "What health hazard builds up from garbage lying around the house?",
     ["मक्खी-मच्छर का प्रजनन-स्थल और रोग-वाहकों की बाढ़", "ताजी हवा की बाढ़", "फलों की बाढ़", "दूध की बाढ़"],
     ["A breeding ground for flies-mosquitoes and a flood of disease-vectors", "A flood of fresh air", "A flood of fruits", "A flood of milk"],
     0,
     "कचरा वाहकों का गोदाम है — उठाओ तो गोदाम ही बंद।",
     "Garbage is the vectors' warehouse — remove it and the warehouse shuts."),

    ("health-hygiene", "easy",
     "खाना पकाकर गर्म-गर्म खाना बनाम घंटों पहले पका खुला रखा — कौन-सा सुरक्षित और क्यों?",
     "Hot freshly-cooked food versus food cooked hours ago and kept open — which is safe and why?",
     ["गर्म-ताजा भोजन, क्योंकि पकाने की गर्मी रोगाणु मारती है और कम समय का खुला-प्रसार", "दोनों बराबर", "खुला पुराना सुरक्षित", "पका हुआ खतरनाक"],
     ["Hot-fresh food, because cooking heat kills germs and exposure time stays short", "Both equal", "Old open food is safe", "Cooked food is dangerous"],
     0,
     "गर्मी की छतरी और थोड़ी हवा-छुअन — भोजन की सुरक्षा का दोहरा ताला।",
     "The umbrella of heat and little exposure — a double lock of food safety."),

    ("health-hygiene", "easy",
     "खुले में शौच (open defecation) रोग-श्रृंखला में कौन-सी कड़ी बनता है?",
     "Which link in the disease-chain does open defecation become?",
     ["जल-भोजन के माध्यम से रोगाणु फैलाने वाली मुख्य कड़ी", "रोग रोकने वाली कड़ी", "व्यायाम बढ़ाने वाली कड़ी", "कोई कड़ी नहीं"],
     ["The main link that spreads pathogens through water-food", "A disease-preventing link", "An exercise-boosting link", "No link at all"],
     0,
     "खुला मल बरसात-जल से कुओं-टंकियों तक रोगाणु पहुँचाता है — शौचालय इसी कड़ी की कैंची।",
     "Open waste sends pathogens to wells-tanks with rain-water — the toilet is the scissor on this very link."),

    ("health-hygiene", "easy",
     "नाखून समय-समय पर काटना क्यों सलाहा जाता है?",
     "Why is cutting nails from time to time advised?",
     ["लंबे नाखूनों में गंदगी-रोगाणु जमा होकर भोजन-मुँह तक पहुँचते हैं", "नाखून काटने से कद बढ़ता है", "नाखून काटने से आँखें नीली होती हैं", "नाखून काटने से बाल घुंघराले होते हैं"],
     ["Dirt-germs collect in long nails and reach food-mouth", "Cutting nails raises height", "Cutting nails turns eyes blue", "Cutting nails curls the hair"],
     0,
     "नाखून की डेरी रोगाणुओं की सुरंग है — छोटे नाखून, बंद सुरंग।",
     "The nail's burrow is a germ-tunnel — short nails, shut tunnel."),

    ("health-hygiene", "medium",
     "सार्वजनिक स्वास्थ्य (public health) की जिम्मेदारी में स्थानीय निकाय क्या-क्या करते हैं?",
     "What do local bodies do within the responsibility of public health?",
     ["सुरक्षित जल-आपूर्ति, मल-निपटान, टीकाकरण-अभियान", "केवल सड़कों पर रंग भरना", "केवल जन्मदिन मनाना", "केवल साइनबोर्ड लगाना"],
     ["Safe water supply, waste disposal, vaccination campaigns", "Only painting the roads", "Only celebrating birthdays", "Only putting up signboards"],
     0,
     "साफ पानी, साफ मोहल्ला, टीकों की छतरी — सार्वजनिक स्वास्थ्य की तीन दीवारें।",
     "Clean water, clean neighbourhood, the umbrella of vaccines — three walls of public health."),

    ("health-hygiene", "medium",
     "भोजन को ढककर रखना किस प्रकार का स्वच्छता-उपाय है?",
     "What kind of hygiene measure is keeping food covered?",
     ["रोगाणु-प्रवेश रोकने वाला (निवारक) उपाय", "रोग बढ़ाने वाला उपाय", "उपचारात्मक उपाय", "कोई उपाय नहीं"],
     ["A preventive measure that blocks pathogen entry", "A disease-raising measure", "A curative measure", "No measure at all"],
     0,
     "ढकना = द्वार बंद — वायु-बैठे जीवाणु भोजन तक पहुँच ही नहीं पाते।",
     "Covering = closing the door — air-seated germs cannot even reach the food."),

    ("health-hygiene", "medium",
     "फल-सब्जियों को खाने से पहले धोना किस खतरे की रोक है?",
     "Washing fruits-vegetables before eating is a guard against which danger?",
     ["उन पर लगे जीवाणु-कीटनाशक के अवशेष", "उनके रंग का उड़ना", "उनका मीठा होना", "उनका बड़ा होना"],
     ["Germs and pesticide residues sitting on them", "Their colour flying off", "Their turning sweet", "Their turning big"],
     0,
     "खेत से थाली तक फल-सब्जी कई हाथ छूती है — पानी की धार उन हाथों की गंदगी उतार देती है।",
     "From field to plate the fruit-vegetable passes many hands — the stream of water carries that touch's dirt away."),

    ("health-hygiene", "medium",
     "दूषित जल की पहचान का सामान्य संकेत क्या हो सकता है?",
     "What can be a common sign of contaminated water?",
     ["उसमें गंदी गंध, स्वाद या दिखने में अशुद्धि", "वह बिल्कुल साफ और रोगाणु-रहित", "वह डिस्टिल्ड जैसी शुद्ध", "वह स्वादिष्ट और मीठी"],
     ["A foul smell, taste or visible impurity in it", "It is absolutely clean and germ-free", "It is pure like distilled", "It is tasty and sweet"],
     0,
     "गंध-स्वाद-रंग की चेतावनी पर पीना बंद करो — पर खतरा यह है कि घातक रोगाणु अक्सर बिना संकेत रहते हैं, इसलिए उबालना ही सुरक्षा है।",
     "Stop drinking on the warning of smell-taste-colour — yet the danger is that deadly germs often give no sign, so boiling is the safety."),

    ("health-hygiene", "medium",
     "घर की सफाई में 'सूखी सफाई' (जल-ठहराव रहित) पर बल क्यों दिया जाता है?",
     "Why is emphasis laid on 'dry cleanliness' (no water-logging) in house-cleaning?",
     ["ठहरा जल डेंगू-मलेरिया वाहकों का प्रजनन-घर है", "सूखा घर गीले से सस्ता है", "जल ठहरने से दीवारें लंबी होती हैं", "सूखी सफाई से छत उड़ती है"],
     ["Standing water is the breeding-home of dengue-malaria vectors", "A dry house is cheaper than a wet one", "Walls grow tall when water stands", "Dry cleaning flies the roof away"],
     0,
     "सूखा मोहल्ला = बंद प्रजनन-घर — कूलर-टंकी-गमले का जल हर हफ्ते बदलो।",
     "A dry neighbourhood = a shut breeding-home — change cooler-tank-pot water every week."),

    ("health-hygiene", "medium",
     "व्यक्तिगत स्वच्छता और सार्वजनिक स्वच्छता में मूल अंतर क्या है?",
     "What is the basic difference between personal hygiene and public hygiene?",
     ["व्यक्तिगत अपने शरीर-आसपास की सफाई; सार्वजनिक पूरे समुदाय-परिवेश की सफाई", "दोनों एक ही हैं", "व्यक्तिगत सार्वजनिक से बड़ी है", "सार्वजनिक केवल सरकार का काम है"],
     ["Personal is cleanliness of one's own body-surroundings; public is of the whole community-environment", "Both are the same", "Personal is bigger than public", "Public is only the government's job"],
     0,
     "नहाना-धोना व्यक्तिगत दीवार है, नाली-कचरा-जल प्रबंधन सामूहिक दुर्ग — दोनों के बिना रोग-चौकी अधूरी।",
     "Bathing-washing is the personal wall, drain-waste-water management the collective fort — without both the disease-post stays incomplete."),

    ("health-hygiene", "medium",
     "बासी/खराब भोजन की पहचान से बचने का सामान्य नियम क्या है?",
     "What is the common rule to avoid stale/spoiled food?",
     ["गंध-स्वाद-रंग बदला लगे तो न खाएँ", "गर्म कर लें तो हमेशा खाएँ", "जो मिले वही खा लें", "बासी भोजन मीठा होता है"],
     ["If smell-taste-colour seems changed, do not eat", "If reheated, always eat", "Eat whatever is found", "Stale food is sweet"],
     0,
     "बदली गंध जीवाणुओं का बिगुल है — गर्म करने से कुछ विष टूटते नहीं, इसलिए बिगुल सुनते ही थाली छोड़ दो।",
     "A changed smell is the germs' bugle — some toxins do not break on reheating, so leave the plate the moment you hear the bugle."),

    ("health-hygiene", "medium",
     "सामुदायिक स्तर पर टीकाकरण-अभियान की सफलता किस बात पर निर्भर करती है?",
     "What does the success of a community vaccination campaign depend on?",
     ["जन-भागीदारी और पूर्ण कवरेज — जितने लोग उतनी मजबूत दीवार", "केवल विज्ञापन पर", "केवल एक व्यक्ति के टीके पर", "मौसम पर"],
     ["People's participation and full coverage — as many people, so strong the wall", "Only on advertising", "Only on one person's vaccine", "On the weather"],
     0,
     "झुंड-प्रतिरक्षा की दीवार हर ईंट से बनती है — कोई ईंट छूटी तो दीवार में छेद।",
     "The herd-immunity wall is built of every brick — one brick missed and the wall has a hole."),

    ("health-hygiene", "medium",
     "खाने-पीने की दुकान पर स्वच्छता-निरीक्षण का सार्वजनिक स्वास्थ्य-तर्क क्या है?",
     "What is the public-health logic of hygiene inspection of food shops?",
     ["एक दूषित स्रोत सैकड़ों उपभोक्ताओं तक रोग पहुँचा सकता है", "दुकानें सजावट के लिए हैं", "निरीक्षक को खाना मिलता है", "दुकानदार की छुट्टी होती है"],
     ["One contaminated source can deliver disease to hundreds of consumers", "Shops are for decoration", "The inspector gets food", "The shopkeeper gets a holiday"],
     0,
     "सार्वजनिक रसोई की एक गलती पूरे मोहल्ले की थाली में उतरती है — निरीक्षण वही रोकता है।",
     "One mistake of a public kitchen descends into the whole neighbourhood's plate — inspection stops exactly that."),

    ("health-hygiene", "medium",
     "बरसात में रोग बढ़ने का सूक्ष्म-कारण क्या है?",
     "What is the subtle reason for diseases rising in the rainy season?",
     ["नमी-तापमान से जीवाणु-वाहक दोनों जल्दी पलते हैं", "बारिश का पानी मीठा होता है", "बादल दवा गिराते हैं", "छतें उड़ जाती हैं"],
     ["With moisture-temperature both germs and vectors breed fast", "Rainwater is sweet", "Clouds drop medicine", "Roofs fly away"],
     0,
     "बरसात रोगाणु-वाहक दोनों की दोहत्ती ऋतु है — इसीलिए इस मौसम में जल-स्वच्छता का पहरा दोगुना।",
     "Rain is the twin season of germs and vectors — hence the guard of water-hygiene doubles this season."),

    ("health-hygiene", "medium",
     "स्वच्छ शौचालय के प्रयोग से कौन-सा परिपथ टूटता है?",
     "Which circuit is broken by the use of a clean toilet?",
     ["मल → जल/भोजन → मुँह का रोगाणु-परिपथ", "पानी → बादल → बारिश का परिपथ", "भोजन → रक्त → मांसपेशी का परिपथ", "हवा → पत्ता → डाली का परिपथ"],
     ["The germ-circuit of faeces → water/food → mouth", "The circuit of water → cloud → rain", "The circuit of food → blood → muscle", "The circuit of air → leaf → twig"],
     0,
     "मल-जल-मुँह की यही चक्कर जल-जनित रोगों की धुरी है — शौचालय चक्कर की कील है।",
     "This very circle of faeces-water-mouth is the axis of water-borne diseases — the toilet is the nail on the circle."),

    ("health-hygiene", "medium",
     "स्वस्थ रहने की आदतों में कौन-सा समूह पूर्णतः सही है?",
     "Which group is ENTIRELY correct among habits of staying healthy?",
     ["स्वच्छ जल, ताजा भोजन, नियमित सफाई, टीकाकरण", "कच्चा जल, बासी भोजन, कचरा, टीके से भागना", "अधूरा सोना, खुला खाना, गंदे हाथ", "तीनों समूह सही"],
     ["Clean water, fresh food, regular cleanliness, vaccination", "Raw water, stale food, garbage, fleeing vaccines", "Half sleep, open food, dirty hands", "All three groups correct"],
     0,
     "चार थंभे — जल, भोजन, सफाई, टीका — इन्हीं पर स्वास्थ्य की क्यारी खड़ी रहती है।",
     "Four pillars — water, food, cleanliness, vaccine — on these alone stands the bed of health."),

    ("health-hygiene", "medium",
     "रोग से बचाव में 'जागरूकता' की भूमिका क्यों निर्णायक मानी जाती है?",
     "Why is 'awareness' counted decisive in disease prevention?",
     ["सही जानकारी ही सही आदत और समय पर उपाय कराती है", "जागरूकता से बुखार आता है", "जागरूकता रोगाणुओं को बुलाती है", "जागरूकता से नींद आती है"],
     ["Right information alone brings right habit and timely step", "Awareness brings fever", "Awareness calls the germs", "Awareness brings sleep"],
     0,
     "अफवाह से लड़ने वाला ज्ञान ही असली प्रतिरक्षा-दीवार की नींव है — जाना हुआ खतरा आधा टला खतरा।",
     "The knowledge that fights rumour is the true foundation of the immunity-wall — a known danger is a half-averted danger."),

    ("health-hygiene", "hard",
     "'रोग का इलाज बाद में, रोकथाम पहले' — इस सिद्धांत का व्यावहारिक कारण क्या है?",
     "'Cure of disease later, prevention first' — what is the practical reason for this principle?",
     ["रोकथाम घर-स्तर पर संभव और सस्ती है; इलाज दुर्लभ-महँगा और देर से दिखने वाला", "इलाज संभव नहीं होता", "रोकथाम से बीमारी आती है", "दोनों एक साथ असंभव"],
     ["Prevention is possible and cheap at home level; cure is rare-costly and late-showing", "Cure is impossible", "Prevention brings illness", "Both together impossible"],
     0,
     "जाल पहले बुनना सस्ता है, मछली हाथ से निकलने के बाद महँगा — उबला पानी निःशुल्क, अस्पताल का बिल भारी।",
     "Weaving the net first is cheap; pulling the fish out by hand after it slips is costly — boiled water is free, the hospital bill heavy."),

]
