# -*- coding: utf-8 -*-
"""B11 Part-1 — Health, Disease & Microorganisms (chapter-11).
80 items: harmful-microbes 30 (E10/M17/H3) + microbial-world 25 (E8/M14/H3)
          + useful-microorganisms 25 (E8/M14/H3).
Tuple: (topic, difficulty, question_hi, question_en, options_hi[4], options_en[4], correct_idx, expl_hi, expl_en)

DENY-AWARENESS (verified by pre-generation scan of all 10 locked banks):
- B09/ch-02 owns: bacteria-reproduce-by-division (q260/276), yeast='unicellular fungus'
  classification (q267), medicine-from-fungi framing (q273), STI (q341).
- B03/ch-04 owns: kingdom placements Monera/fungi/protozoa-into-Protista (q461-479),
  fungi nutrition/cell-wall (q465/467).
- B04/ch-05 owns: Rhizobium root-nodule home (q545), what-it-gives (q549),
  what-it-gets (q550), lichen (q552), Rhizopus-nutrition (q553).
- B07/ch-08 owns: yeast-anaerobic PRODUCTS/equation (q844/852), fermentation-as-
  respiration-name (q845), gas-in-balloon (q864).
- B06/ch-07 owns: deficiency-disease definition (q725), mosquito-feeding (q814).
- B08/ch-09 owns: blood-group antibodies (q952).
- B10/ch-10 owns: adolescent diet/sleep/exercise/intoxicants items.
=> B11 frames: penicillin via FLEMING-DISCOVERY angle; Rhizobium only inside
   'soil-fertility microbes' list angle + blue-green algae as separate fact; yeast
   via USE angle (bread/idli/alcohol industry), not products/equation; antibodies via
   germ-defence angle, not blood-grouping; immunity distinct from B10 lifestyle items.
"""

PART1 = [
    # ================= HARMFUL MICROBES & DISEASES — 30 (E10/M17/H3) =================
    ("harmful-microbes", "easy",
     "रोग उत्पन्न करने वाले सूक्ष्मजीवों को क्या कहा जाता है?",
     "What are disease-causing microorganisms called?",
     ["रोगाणु (पैथोजन)", "प्रकाश-संश्लेषक", "वाष्पक", "खनिज"],
     ["Pathogens", "Photosynthesisers", "Vaporisers", "Minerals"],
     0,
     "जो सूक्ष्मजीव शरीर में घुसकर बीमारी पैदा करते हैं, वे रोगाणु कहलाते हैं।",
     "Microbes that enter the body and produce illness are called pathogens."),

    ("harmful-microbes", "easy",
     "मलेरिया किस प्रकार के सूक्ष्मजीव से होता है?",
     "Malaria is caused by which kind of microorganism?",
     ["प्रोटोज़ोआ से", "वायरस से", "फफूंद से", "शैवाल से"],
     ["A protozoan", "A virus", "A fungus", "An alga"],
     0,
     "मलेरिया प्रोटोज़ोआ (प्लाज्मोडियम) से होता है, जो मादा एनोफेलीज़ मच्छर के काटने से फैलता है।",
     "Malaria comes from a protozoan (Plasmodium), spread by the bite of the female Anopheles mosquito."),

    ("harmful-microbes", "easy",
     "चेचक (smallpox) किस प्रकार के रोगाणु से होता है?",
     "Smallpox is caused by which kind of pathogen?",
     ["वायरस से", "बैक्टीरिया से", "प्रोटोज़ोआ से", "फफूंद से"],
     ["A virus", "A bacterium", "A protozoan", "A fungus"],
     0,
     "चेचक एक वायरल रोग है — टीके की शक्ति से ही इसे दुनिया से लगभग मिटाया जा सका।",
     "Smallpox is a viral disease — it could be erased from the world only by the power of vaccination."),

    ("harmful-microbes", "easy",
     "हैजा मुख्यतः किस प्रकार के रोगाणु से होता है?",
     "Cholera is caused mainly by which kind of pathogen?",
     ["बैक्टीरिया से", "वायरस से", "फफूंद से", "कीट से"],
     ["A bacterium", "A virus", "A fungus", "An insect"],
     0,
     "हैजा जीवाणु (विब्रियो) का रोग है — दूषित जल और भोजन इसकी मुख्य सवारी है।",
     "Cholera is a bacterial (Vibrio) disease — contaminated water and food are its main carriers."),

    ("harmful-microbes", "easy",
     "तपेदिक (टीबी) किस प्रकार के रोगाणु से होता है?",
     "Tuberculosis is caused by which kind of pathogen?",
     ["बैक्टीरिया से", "वायरस से", "प्रोटोज़ोआ से", "फफूंद से"],
     ["A bacterium", "A virus", "A protozoan", "A fungus"],
     0,
     "टीबी का जीवाणु वायु में फैली छींक-बूंदों से स्वस्थ व्यक्ति तक पहुँचता है।",
     "TB's bacterium reaches a healthy person through sneeze-droplets spread in the air."),

    ("harmful-microbes", "easy",
     "पोलियो किस प्रकार के रोगाणु से होता है?",
     "Polio is caused by which kind of pathogen?",
     ["वायरस से", "बैक्टीरिया से", "प्रोटोज़ोआ से", "फफूंद से"],
     ["A virus", "A bacterium", "A protozoan", "A fungus"],
     0,
     "पोलियो वायरस तंत्रिका तंत्र पर हमला करता है — पल्स-पोलियो बूँदों ने भारत में इसे हराया।",
     "The polio virus attacks the nervous system — pulse-polio drops defeated it in India."),

    ("harmful-microbes", "easy",
     "डेंगू किस कीट द्वारा फैलाया जाता है?",
     "Dengue is spread by which insect?",
     ["एडीज मच्छर द्वारा", "मक्खी द्वारा", "तितली द्वारा", "चींटी द्वारा"],
     ["The Aedes mosquito", "The housefly", "The butterfly", "The ant"],
     0,
     "डेंगू एडीज मच्छर के काटने से फैलता है — दिन में काटने वाला यह मच्छर साफ-ठहरा जल में पलता है।",
     "Dengue spreads by the Aedes mosquito's bite — this day-biter breeds in clean standing water."),

    ("harmful-microbes", "easy",
     "मलेरिया फैलाने वाला मच्छर कौन-सा है?",
     "Which mosquito spreads malaria?",
     ["मादा एनोफेलीज़", "नर एनोफेलीज़", "घर की मक्खी", "मधुमक्खी"],
     ["The female Anopheles", "The male Anopheles", "The housefly", "The honeybee"],
     0,
     "मलेरिया का प्लाज्मोडियम मादा एनोफेलीज़ के काटने से ही शरीर में उतरता है।",
     "Malaria's Plasmodium enters the body only through the bite of the female Anopheles."),

    ("harmful-microbes", "easy",
     "खुजली वाली त्वचा-रोग 'दाद' (ringworm) किस सूक्ष्मजीव से होता है?",
     "The itchy skin disease 'ringworm' is caused by which microorganism?",
     ["फफूंद से", "बैक्टीरिया से", "वायरस से", "प्रोटोज़ोआ से"],
     ["A fungus", "A bacterium", "A virus", "A protozoan"],
     0,
     "दाद एक फंगल रोग है — संक्रमित व्यक्ति के सीधे संपर्क या उसके तौलिये-कपड़ों से फैलता है।",
     "Ringworm is a fungal disease — spreading by direct contact with an infected person or their towel-clothes."),

    ("harmful-microbes", "easy",
     "जलांतक (रेबीज़) का वायरस सामान्यतः किससे मनुष्य को संक्रमित करता है?",
     "The rabies virus usually infects humans through what?",
     ["पागल कुत्ते के काटने से", "मक्खी की भिनभिनाहट से", "ठंडे पानी से", "धूप से"],
     ["The bite of a rabid dog", "A fly's buzzing", "Cold water", "Sunshine"],
     0,
     "रेबीज़ वायरस संक्रमित जानवर की लार के साथ काट के घाव से शरीर में घुसता है — बुखार-डायरिया नहीं, मस्तिष्क पर हमला।",
     "The rabies virus enters through the bite wound along with an infected animal's saliva — attacking not fever-diarrhoea but the brain."),

    ("harmful-microbes", "medium",
     "हैजा और टाइफॉइड मुख्य रूप से किस माध्यम से फैलते हैं?",
     "Cholera and typhoid spread mainly through which medium?",
     ["दूषित जल एवं भोजन से", "वायु की लहरों से", "मिट्टी की खुशबू से", "सूर्य-प्रकाश से"],
     ["Contaminated water and food", "Air waves", "The smell of soil", "Sunlight"],
     0,
     "मल-मिश्रित जल और दूषित भोजन जीवाणु-रोगों की असली सड़क हैं — उबला पानी यह सड़क तोड़ देता है।",
     "Faeces-mixed water and contaminated food are the true highway of bacterial diseases — boiled water cuts this road."),

    ("harmful-microbes", "medium",
     "खसरा (measles) और चेचक किस मार्ग से एक व्यक्ति से दूसरे तक पहुँचते हैं?",
     "By which route do measles and smallpox pass from one person to another?",
     ["रोगी की छींक-खांसी की बूंदों से (वायु)", "किताबों के पन्नों से", "पेड़ की छाल से", "चट्टानों से"],
     ["Through the droplets of the patient's sneeze-cough (air)", "Through book pages", "Through tree bark", "Through rocks"],
     0,
     "वायु-जनित रोगों के रोगाणु छींक के साथ हवा में उड़ते हैं और साँस के साथ दूसरे शरीर में उतरते हैं।",
     "Airborne germs fly with the sneeze into the air and descend into another body with the breath."),

    ("harmful-microbes", "medium",
     "निम्न में से कौन-सा रोग मादा एनोफेलीज़ मच्छर से नहीं फैलता?",
     "Which of these diseases is NOT spread by the female Anopheles mosquito?",
     ["डेंगू", "मलेरिया", "दोनों फैलते हैं", "कोई नहीं"],
     ["Dengue", "Malaria", "Both are spread", "None"],
     0,
     "एनोफेलीज़ की सवारी पर केवल मलेरिया का प्लाज्मोडियम चढ़ता है; डेंगू का वाहक एडीज है।",
     "Only malaria's Plasmodium rides the Anopheles; dengue's carrier is the Aedes."),

    ("harmful-microbes", "medium",
     "'वाहक' (vector) किसे कहते हैं?",
     "What is called a 'vector'?",
     ["वह जीव जो रोगाणु को एक व्यक्ति से दूसरे तक पहुँचाता है", "वह जीव जो खुद बीमार होता है", "वह पौधा जो भोजन बनाता है", "वह पत्थर जो लुढ़कता है"],
     ["An organism that carries the pathogen from one person to another", "An organism that itself falls ill", "A plant that makes food", "A stone that rolls"],
     0,
     "मच्छर स्वयं मलेरिया से बीमार नहीं होता, पर वह प्लाज्मोडियम की सवारी करता है — यही वाहकता है।",
     "The mosquito does not itself fall sick of malaria, yet it gives Plasmodium a ride — that is vectorhood."),

    ("harmful-microbes", "medium",
     "भोजन पर बैठी मक्खी किस प्रकार रोग फैलाती है?",
     "How does a fly sitting on food spread disease?",
     ["वह गंदे स्थानों से रोगाणु शरीर पर लाकर भोजन पर उतारती है", "वह भोजन को गर्म कर देती है", "वह भोजन को जमा देती है", "वह भोजन को रंग देती है"],
     ["It brings germs on its body from dirty places and deposits them on food", "It warms the food", "It freezes the food", "It colours the food"],
     0,
     "मक्खी का शरीर गंदगी की टैक्सी है — कूड़े से रोगाणु उठाकर वह खाने की थाली तक पहुँचा देती है।",
     "The fly's body is a taxi of filth — it lifts germs from garbage and delivers them up to the plate."),

    ("harmful-microbes", "medium",
     "हैपेटाइटिस-A (पीलिया) रोगाणु मुख्यतः शरीर में किस मार्ग से प्रवेश करता है?",
     "The hepatitis-A (jaundice) germ mainly enters the body by which route?",
     ["दूषित जल-भोजन के साथ मुँह से", "कान के रास्ते", "बालों के रास्ते", "नाखूनों के रास्ते"],
     ["Through the mouth with contaminated water-food", "Through the ears", "Through the hair", "Through the nails"],
     0,
     "पीलिया का वायरस मल-संदूषित जल से यात्रा करता है — इसीलिए उबला-छना पानी इसकी पहली रोक है।",
     "Jaundice's virus travels in faeces-tainted water — boiled-filtered water is its first barrier."),

    ("harmful-microbes", "medium",
     "निम्न रोग-रोगाणु युग्मों में से कौन-सा सुमेलित नहीं है?",
     "Which disease-pathogen pair is NOT correctly matched?",
     ["हैजा — वायरस", "मलेरिया — प्रोटोज़ोआ", "चेचक — वायरस", "दाद — फफूंद"],
     ["Cholera — virus", "Malaria — protozoan", "Smallpox — virus", "Ringworm — fungus"],
     0,
     "हैजा जीवाणु का रोग है, वायरस का नहीं — बाकी तीनों जोड़े सही बैठते हैं।",
     "Cholera is a bacterial disease, not viral — the other three pairs sit right."),

    ("harmful-microbes", "medium",
     "तपेदिक का जीवाणु मुख्यतः शरीर के किस अंग को क्षति पहुँचाता है?",
     "TB bacteria mainly damage which organ of the body?",
     ["फेफड़ों को", "आँखों को", "नाखूनों को", "बालों को"],
     ["The lungs", "The eyes", "The nails", "The hair"],
     0,
     "टीबी का जीवाणु वायु की सवारी से फेफड़ों तक पहुँचता है — वहीं अपनी कॉलोनी बसाता है।",
     "TB's bacterium rides the air up to the lungs — and pitches its colony right there."),

    ("harmful-microbes", "medium",
     "कोरोना-वायरस जैसे रोगाणु एक-दूसरे तक मुख्यतः कैसे पहुँचते हैं?",
     "How do germs like the coronavirus mainly reach one person from another?",
     ["साँस और छींक-बूंदों के संपर्क से", "जूतों के फिते से", "दीवार के रंग से", "किताब के कवर से"],
     ["Through breath and sneeze-droplet contact", "Through shoelaces", "Through wall paint", "Through book covers"],
     0,
     "संक्रमित व्यक्ति की बोली-छींक की बूंदें हवा में रोगाणु बिखेरती हैं — मास्क और दूरी इसी बिखराव को रोकते हैं।",
     "An infected person's speech-sneeze droplets scatter germs in air — masks and distance stop this very scatter."),

    ("harmful-microbes", "medium",
     "टाइफॉइड का जीवाणु शरीर में प्रवेश का मुख्य द्वार कौन-सा है?",
     "Which is the main door of entry for the typhoid bacterium?",
     ["दूषित जल-भोजन के साथ मुँह", "त्वचा के छिद्र", "कान का पर्दा", "आँख की पुतली"],
     ["The mouth, with contaminated water-food", "Pores of the skin", "The eardrum", "The pupil of the eye"],
     0,
     "टाइफॉइड जीवाणु का प्रवेश-द्वार मुँह है — अशुद्ध जल पीकर ही यह यात्रा शुरू होती है।",
     "The typhoid bacterium's entry-gate is the mouth — the journey begins only by drinking impure water."),

    ("harmful-microbes", "medium",
     "रोगाणु शरीर में घुसने के लिए सामान्यतः कौन-से द्वार अपनाते हैं?",
     "Which doors do pathogens generally use to enter the body?",
     ["श्वास, भोजन-जल, घाव और संपर्क", "केवल बाल", "केवल नाखून", "केवल दाँत"],
     ["Breath, food-water, wounds and contact", "Only hair", "Only nails", "Only teeth"],
     0,
     "नाक-मुँह, भोजन-जल, खुले घाव और सीधा संपर्क — रोगाणु के चार चलते-फिरते दरवाज़े।",
     "Nose-mouth, food-water, open wounds and direct contact — the four ever-open doors of pathogens."),

    ("harmful-microbes", "medium",
     "फंगल त्वचा-रोग किन संपर्कों से बचाव माँगते हैं?",
     "Fungal skin diseases demand protection from which contacts?",
     ["रोगी के तौलिए, कपड़ों और सीधे स्पर्श से", "साफ हवा से", "उबले पानी से", "धूप की किरण से"],
     ["The patient's towel, clothes and direct touch", "Clean air", "Boiled water", "Sunray"],
     0,
     "फंगल बीज गीले-गर्म साझा सामानों में पलते हैं — व्यक्तिगत तौलिया-चप्पल ही रोक है।",
     "Fungal seeds breed in shared damp-warm articles — a personal towel-slipper is the barrier."),

    ("harmful-microbes", "medium",
     "गेहूँ की फसल पर लगने वाला 'रतुआ' (rust) रोग किस सूक्ष्मजीव से होता है?",
     "The 'rust' disease of wheat crop is caused by which microorganism?",
     ["फफूंद से", "वायरस से", "प्रोटोज़ोआ से", "शैवाल से"],
     ["A fungus", "A virus", "A protozoan", "An alga"],
     0,
     "रतुआ एक फंगल फसल-रोग है — नाम 'फफूंदी' से ही लिए बिना फसल को जंग लगा देता है।",
     "Rust is a fungal crop disease — true to its name it corrodes the crop like iron-rust."),

    ("harmful-microbes", "medium",
     "निम्न में से कौन-सा वायरल रोग नहीं है?",
     "Which of the following is NOT a viral disease?",
     ["मलेरिया", "पोलियो", "खसरा", "चेचक"],
     ["Malaria", "Polio", "Measles", "Smallpox"],
     0,
     "मलेरिया प्रोटोज़ोआ का रोग है — पोलियो, खसरा और चेचक तीनों वायरल हैं।",
     "Malaria is a protozoan disease — polio, measles and smallpox are all viral."),

    ("harmful-microbes", "medium",
     "अमीबा-पेचिश (अमीबियासिस) किस सूक्ष्म-समूह का रोग है?",
     "Amoebic dysentery is a disease of which micro-group?",
     ["प्रोटोज़ोआ", "वायरस", "फफूंद", "बैक्टीरिया"],
     ["Protozoa", "Virus", "Fungus", "Bacteria"],
     0,
     "अमीबा एक प्रोटोज़ोआ है — दूषित जल-भोजन से आँत तक पहुँचकर पेचिश कराता है।",
     "Amoeba is a protozoan — reaching the gut via contaminated water-food it causes dysentery."),

    ("harmful-microbes", "medium",
     "रोगाणु शरीर के भीतर आकर मुख्यतः क्या करते हैं?",
     "What do pathogens mainly do after entering the body?",
     ["वे शरीर की कोशिकाओं/ऊतकों को क्षति पहुँचाकर विषाक्त पदार्थ बनाते हैं", "वे शरीर साफ करते हैं", "वे रक्त में ठंडक लाते हैं", "वे हड्डियाँ मजबूत करते हैं"],
     ["They damage the body's cells/tissues and produce toxic substances", "They clean the body", "They cool the blood", "They strengthen bones"],
     0,
     "रोगाणु अपने विष और कोशिका-तोड़ से शरीर की सामान्य क्रिया बिगाड़ देते हैं — बीमारी के लक्षण उसी की आवाज़ हैं।",
     "With their toxins and cell-breaking, pathogens derange the body's normal working — the symptoms of disease are its voice."),

    ("harmful-microbes", "medium",
     "मलेरिया के प्लाज्मोडियम मच्छर के शरीर से मनुष्य तक किस रूप में यात्रा करता है?",
     "How does malaria's Plasmodium travel from the mosquito's body to the human?",
     ["मच्छर के काटने पर उसकी लार के साथ", "मच्छर की भिनभिनाहट के साथ", "मच्छर के पंखों के रंग के साथ", "मच्छर के अंडों के साथ"],
     ["With its saliva when the mosquito bites", "With the mosquito's buzzing", "With the colour of its wings", "With the mosquito's eggs"],
     0,
     "काटते समय मच्छर लार में घुले प्लाज्मोडियम को रक्त-धारा में उतार देता है।",
     "While biting, the mosquito drops Plasmodium dissolved in saliva into the bloodstream."),

    ("harmful-microbes", "hard",
     "एक वायरल और एक बैक्टीयल रोग का सुमेलन-युग्म चुनिए —",
     "Pick the correctly matched pair of one viral and one bacterial disease —",
     ["पोलियो (वायरल) + टाइफॉइड (बैक्टीयल)", "हैजा (वायरल) + खसरा (बैक्टीयल)", "दाद (वायरल) + पोलियो (बैक्टीयल)", "मलेरिया (वायरल) + चेचक (बैक्टीयल)"],
     ["Polio (viral) + Typhoid (bacterial)", "Cholera (viral) + Measles (bacterial)", "Ringworm (viral) + Polio (bacterial)", "Malaria (viral) + Smallpox (bacterial)"],
     0,
     "पोलियो वायरस का और टाइफॉइड जीवाणु का रोग है — केवल पहला युग्म दोनों तटों पर सही।",
     "Polio is a virus's disease and typhoid a bacterium's — only the first pair stands right on both banks."),

    ("harmful-microbes", "hard",
     "एडीज़ और एनोफेलीज़ — दोनों मच्छरों के रोग-सवारों पर विचार कीजिए। कौन-सा कथन सही है?",
     "Consider the disease-riders of both Aedes and Anopheles mosquitoes. Which statement is correct?",
     ["एनोफेलीज़-मलेरिया और एडीज़-डेंगू युग्म सही हैं", "एनोफेलीज़-डेंगू और एडीज़-मलेरिया युग्म सही हैं", "दोनों मच्छर केवल चेचक फैलाते हैं", "दोनों मच्छर केवल दाद फैलाते हैं"],
     ["The pairs Anopheles-malaria and Aedes-dengue are correct", "The pairs Anopheles-dengue and Aedes-malaria are correct", "Both mosquitoes spread only smallpox", "Both mosquitoes spread only ringworm"],
     0,
     "मलेरिया की सवारी एनोफेलीज़ करता है, डेंगू की एडीज़ — दोनों युग्म अपनी-अपनी जगह सही।",
     "Malaria rides the Anopheles, dengue the Aedes — both pairs correct in their own places."),

    ("harmful-microbes", "hard",
     "रोगाणुओं की तीन अलग-अलग सवारियाँ — जल, वायु और मच्छर। इन तीनों से फैलने वाले रोगों का सही क्रम कौन-सा है?",
     "Three different rides of pathogens — water, air and mosquito. Which is the correct order of diseases spread by them?",
     ["जल-हैजा, वायु-तपेदिक, मच्छर-मलेरिया", "जल-चेचक, वायु-हैजा, मच्छर-पोलियो", "जल-दाद, वायु-मलेरिया, मच्छर-टीबी", "जल-खसरा, वायु-डेंगू, मच्छर-टाइफॉइड"],
     ["Water-cholera, air-TB, mosquito-malaria", "Water-smallpox, air-cholera, mosquito-polio", "Water-ringworm, air-malaria, mosquito-TB", "Water-measles, air-dengue, mosquito-typhoid"],
     0,
     "हैजा जल की सवारी पर, तपेदिक हवा की, मलेरिया मच्छर की — पहला क्रम तीनों यात्राओं को सही बैठाता है।",
     "Cholera rides water, TB rides air, malaria rides the mosquito — the first order seats all three journeys rightly."),

    # ================= MICROBIAL WORLD — 25 (E8/M14/H3) =================
    ("microbial-world", "easy",
     "सूक्ष्मजीवों को देखने के लिए किस यंत्र की आवश्यकता होती है?",
     "Which instrument is needed to see microorganisms?",
     ["सूक्ष्मदर्शी (माइक्रोस्कोप)", "दूरबीन", "थर्मामीटर", "बैरोमीटर"],
     ["A microscope", "A telescope", "A thermometer", "A barometer"],
     0,
     "नेत्र से अदृश्य इस सूक्ष्म जगत का दरवाज़ा सूक्ष्मदर्शी की लेंस खोलती है।",
     "The lens of a microscope opens the door to this invisible miniature world."),

    ("microbial-world", "easy",
     "सूक्ष्मजीवों के चार प्रमुख समूह कौन-से हैं?",
     "Which are the four major groups of microorganisms?",
     ["बैक्टीरिया, वायरस, फफूंद, प्रोटोज़ोआ", "गाय, बकरी, भेल, ऊन", "कुत्ता, बिल्ली, घोड़ा, गधा", "कबूतर, कौआ, मोर, तोता"],
     ["Bacteria, viruses, fungi, protozoa", "Cow, goat, sheep, wool", "Dog, cat, horse, donkey", "Pigeon, crow, peacock, parrot"],
     0,
     "जीवाणु, विषाणु, फफूंद और प्रोटोज़ोआ — यही चार गुट सूक्ष्म-जगत के मुख्य खंभे हैं।",
     "Bacteria, viruses, fungi and protozoa — these four clans are the main pillars of the micro-world."),

    ("microbial-world", "easy",
     "बैक्टीरिया किस प्रकार के जीव हैं — आकार की दृष्टि से?",
     "What kind of beings are bacteria — in terms of size?",
     ["अति-सूक्ष्म एकल-कोशिका जीव", "विशाल बहु-कोशिका जीव", "मानव-आकार जीव", "पर्वत-आकार जीव"],
     ["Extremely tiny single-celled beings", "Giant multicellular beings", "Human-sized beings", "Mountain-sized beings"],
     0,
     "एक बूँद जल में लाखों बैक्टीरिया समा सकते हैं — इतने छोटे और एकल-कोशिका।",
     "Millions of bacteria can fit in one drop of water — so tiny and single-celled."),

    ("microbial-world", "easy",
     "सूक्ष्मजीव कहाँ-कहाँ पाए जाते हैं?",
     "Where are microorganisms found?",
     ["मिट्टी, जल, वायु — लगभग हर जगह", "केवल रेगिस्तान में", "केवल बर्फ में", "केवल चंद्रमा पर"],
     ["Soil, water, air — almost everywhere", "Only in deserts", "Only in ice", "Only on the moon"],
     0,
     "ध्रुवीय बर्फ से गर्म झरनों तक, गहरी मिट्टी से वायु की ऊँचाइयों तक — सूक्ष्मजीव हर मौसम में घर बना लेते हैं।",
     "From polar ice to hot springs, from deep soil to the heights of air — microbes make home in every weather."),

    ("microbial-world", "easy",
     "वायरस को 'जीव और निर्जीव की सीमा' किस विशेषता से कहा जाता है?",
     "Why is the virus called 'the border of living and non-living'?",
     ["जीवित कोशिका के बाहर निष्क्रिय, भीतर प्रजननशील", "क्योंकि वह हर जगह दौड़ता है", "क्योंकि वह गाना गाता है", "क्योंकि वह रंग बदलता है"],
     ["Outside a living cell it is inert, inside it multiplies", "Because it runs everywhere", "Because it sings", "Because it changes colour"],
     0,
     "मेज़ पर रखा वायरस निर्जीव कण-मात्र; कोशिका में घुसते ही जीवतंत्र — दोनों दुनिया की नागरिकता रखता है।",
     "On the table a virus is but a lifeless particle; entering a cell it becomes lifeware — a citizen of both worlds."),

    ("microbial-world", "easy",
     "रोटी पर लगी हरी-काली 'फफूंद' किस सूक्ष्म-समूह का उदाहरण है?",
     "The green-black 'mould' on bread is an example of which micro-group?",
     ["फफूंद (fungi)", "प्रोटोज़ोआ", "वायरस", "शैवाल"],
     ["Fungi", "Protozoa", "Virus", "Algae"],
     0,
     "गीली रोटी की सतह पर फैलता यह रंगीन दलदल फंगल वृद्धि है — सूक्ष्मजगत का सबसे दृश्य चेहरा।",
     "This coloured spread on wet bread is fungal growth — the micro-world's most visible face."),

    ("microbial-world", "easy",
     "कीचड़ की बूंद में घूमता अमीबा और फानुस-जैसा पैरामीशियम — सूक्ष्म-जगत की इस टोली का नाम क्या है?",
     "The roaming Amoeba in a drop of mud and the balloon-like Paramecium — what is this squad of the micro-world called?",
     ["प्रोटोज़ोआ", "वायरस", "फफूंद", "बैक्टीरिया"],
     ["Protozoa", "Virus", "Fungi", "Bacteria"],
     0,
     "जल में घुमंतू इन एकल-कोशिका जीवों की टोली प्रोटोज़ोआ कहलाती है — मलेरिया का प्लाज्मोडियम भी इसी कुनबे का।",
     "The squad of these wandering single-celled beings in water is called protozoa — malaria-causing Plasmodium too belongs to this clan."),

    ("microbial-world", "easy",
     "सूक्ष्मजीवों की खोज का श्रेय किसे दिया जाता है?",
     "Who is credited with the discovery of microorganisms?",
     ["ल्यूवेनहॉक को", "न्यूटन को", "ईडिसन को", "राइट बंधुओं को"],
     ["Leeuwenhoek", "Newton", "Edison", "The Wright brothers"],
     0,
     "एंटनी वैन ल्यूवेनहॉक ने अपने आत्म-निर्मित लेंस से सर्वप्रथम इस सूक्ष्म-जगत को देखा — 'ऐनिमलक्यूल्स' कहा।",
     "Antonie van Leeuwenhoek first saw this micro-world through his self-made lenses — calling them 'animalcules'."),

    ("microbial-world", "medium",
     "जीवाणुओं और वायरसों के बीच आधारभूत अंतर क्या है?",
     "What is the fundamental difference between bacteria and viruses?",
     ["जीवाणु स्वतंत्र रूप से बढ़ सकते हैं; वायरस केवल जीवित कोशिका में", "जीवाणु छोटे नहीं होते", "वायरस प्रकाश-संश्लेषण करते हैं", "जीवाणु पानी में तैरते नहीं"],
     ["Bacteria can grow independently; viruses only inside a living cell", "Bacteria are never small", "Viruses photosynthesise", "Bacteria cannot float in water"],
     0,
     "जीवाणु पूरी कोशिका हैं और अपना गुणन खुद करते हैं; वायरस कोशिका तक नहीं — किराए की छापाखाने में ही अपनी प्रतियाँ छपवाते हैं।",
     "Bacteria are full cells and multiply on their own; viruses are not even cells — they get their copies printed in a rented press."),

    ("microbial-world", "medium",
     "प्रोटोज़ोआ की प्रमुख पहचान क्या है?",
     "What is the chief identity of protozoa?",
     ["एकल-कोशिका वाले सूक्ष्म 'प्राणी-जैसे' जीव", "बहु-कोशिका वाले विशाल पौधे", "कोशिका-रहित कण", "पत्थर के टुकड़े"],
     ["Single-celled microscopic 'animal-like' beings", "Giant multicellular plants", "Cell-less particles", "Pieces of stone"],
     0,
     "अमीबा-पैरामीशियम जैसे प्रोटोज़ोआ एकल-कोशिका होकर भी चलते-फिरते, खाते-पचाते मिलते हैं — प्राणी-स्वभाव सूक्ष्म शरीर में।",
     "Protozoa like Amoeba-Paramecium, though single-celled, move about and feed — animal-nature in a tiny body."),

    ("microbial-world", "medium",
     "वर्षा के दिनों में नम कपड़ों-चीज़ों पर फफूंद जल्दी क्यों लगती है?",
     "Why does mould catch damp clothes-things quickly in rainy days?",
     ["नमी और गर्मी फफूंद के बीजों के अंकुरण की सबसे अनुकूल ऋतु है", "क्योंकि फफूंद को धूप चाहिए", "क्योंकि फफूंद बर्फ में बढ़ती है", "क्योंकि वर्षा में सब कुछ सूखता है"],
     ["Moisture and warmth are the most favourable season for mould spores to germinate", "Because mould needs sunshine", "Because mould grows in ice", "Because everything dries in rain"],
     0,
     "फफूंद के बीज हवा में भरे रहते हैं — नम-गर्म मौसम मिलते ही मौका पाकर उग जाते हैं।",
     "Mould spores fill the air — the moment damp-warm weather arrives they sprout at the chance."),

    ("microbial-world", "medium",
     "वायु में उड़ते सूक्ष्मजीव-बीज किस नाम से जाने जाते हैं?",
     "By what name are the microbe-seeds flying in the air known?",
     ["बीजाणु (स्पोर)", "पराग-कण", "धूल-कण", "जल-बूँद"],
     ["Spores", "Pollen grains", "Dust particles", "Water droplets"],
     0,
     "स्पोर हल्के और सख्त आवरण वाले बीज हैं — हवा की सवारी में दूर तक उड़कर नए ठिकानों पर जमते हैं।",
     "Spores are light, hard-coated seeds — riding the wind they settle on new stations far away."),

    ("microbial-world", "medium",
     "गर्म जल-धाराओं (hot springs) में भी कुछ सूक्ष्मजीव जीवित रहते हैं — यह किसका प्रमाण है?",
     "Some microorganisms survive even in hot springs — proof of what?",
     ["सूक्ष्मजीवों की अति-विविध रहन-क्षमता", "जल का कभी गर्म न होना", "जीवन की नदी में अंडे न होना", "सूक्ष्मदर्शी का टूट जाना"],
     ["The extreme diversity of microbial habitats", "That water never heats", "That rivers hold no eggs", "That the microscope broke"],
     0,
     "बर्फ से उबलते झरने तक — सूक्ष्मजीवों ने हर कठिन मौसम में शाखा खोल रखी है।",
     "From ice to boiling springs — microbes have opened branches in every harsh season."),

    ("microbial-world", "medium",
     "हमारी आँतों में भी अनेक सूक्ष्मजीव निवास करते हैं — उनका सामान्य प्रभाव क्या है?",
     "Many microorganisms dwell in our intestines too — what is their usual effect?",
     ["प्रायः अनुकूल — पाचन में सहायक", "प्रायः घातक — तुरंत बीमारी", "प्रायः निरर्थक", "प्रायः भारी",
     ],
     ["Usually favourable — helpful in digestion", "Usually deadly — instant disease", "Usually useless", "Usually heavy"],
     0,
     "आँत के इन मेहमानों में कई अच्छे साथी हैं जो पाचन-मंडली में हाथ बँटाते हैं — सभी सूक्ष्मजीव शत्रु नहीं।",
     "Among the gut's guests are good companions who lend a hand in digestion — not all microbes are foes."),

    ("microbial-world", "medium",
     "बैक्टीरिया की तुलना में वायरस का आकार कैसा है?",
     "How is the size of a virus compared to a bacterium?",
     ["वायरस सामान्यतः बैक्टीरिया से भी छोटे होते हैं", "वायरस बैक्टीरिया से बहुत बड़े होते हैं", "दोनों बराबर-आकार होते हैं", "वायरस आकार ही नहीं रखते"],
     ["Viruses are usually even smaller than bacteria", "Viruses are much bigger than bacteria", "Both are equal in size", "Viruses have no size at all"],
     0,
     "जिस फिल्टर से बैक्टीरिया रुक जाते हैं, उसमें से वायरस निकल जाते हैं — आकार का यही अंतर उनकी पहचान का आधार रहा।",
     "From a filter that stops bacteria, viruses slip through — this size-gap remained the basis of their identity."),

    ("microbial-world", "medium",
     "सूक्ष्मजीवों की गिनती सूक्ष्मदर्शी के आविष्कार के बाद ही क्यों संभव हुई?",
     "Why was the counting of microorganisms possible only after the invention of the microscope?",
     ["क्योंकि वे नंगी आँख से दिखाई नहीं देते", "क्योंकि वे रात में ही मिलते हैं", "क्योंकि वे भाग जाते हैं", "क्योंकि वे रंगीन नहीं होते"],
     ["Because they are not visible to the naked eye", "Because they appear only at night", "Because they run away", "Because they are not coloured"],
     0,
     "लेंस ने नेत्र की सीमा को काट दिया — जो आँख से परे था, वह विज्ञान के सामने आ गया।",
     "The lens cut the limit of the eye — what lay beyond sight came before science."),

    ("microbial-world", "medium",
     "सूक्ष्मदर्शी के नीचे जीवाणुओं के मुख्य आकार-रूप कौन-से दिखते हैं?",
     "What main shape-forms of bacteria are seen under the microscope?",
     ["गोल (कॉकस), छड़ी-रूप (बैसिलस), सर्पिल-कुंडली", "चौकोर, गोल-चौकोर, तिकोना-चौकोर", "पतंग, जहाज़, रेलगाड़ी", "पर्वत, नदी, मैदान"],
     ["Round (coccus), rod (bacillus), spiral-coil", "Square, round-square, triangle-square", "Kite, ship, train", "Mountain, river, plain"],
     0,
     "जीवाणुओं की पहचान का पहला सीढ़ी-पत्थर उनका आकार है — गोल, छड़ी और सर्पिल; विज्ञान ने इन्हीं रूपों पर नाम टँके।",
     "The first stepping-stone of bacterial identity is their shape — round, rod and spiral; science pinned names on these very forms."),

    ("microbial-world", "medium",
     "निम्न में से कौन-सा सूक्ष्म-समूह है जिसके सदस्य स्वयं भोजन बना सकते हैं (शैवाल को छोड़कर सूक्ष्म-जगत में)?",
     "Which micro-group's members (apart from algae in the micro-world) can make their own food?",
     ["नीली-हरी शैवाल (सायनोबैक्टीरिया) जैसे जीवाणु-रूपी प्रकाश-संश्लेषक", "वायरस", "सभी फफूंद", "सभी प्रोटोज़ोआ"],
     ["Beings like blue-green algae (cyanobacteria) — bacterial photosynthesisers", "Viruses", "All fungi", "All protozoa"],
     0,
     "नीली-हरी शैवाल जैसे कुछ सूक्ष्मजीव स्वयं भोजन जुटा लेते हैं — सूक्ष्म-जगत के बाकी गुट मुख्यतः तैयार भोजन पर निर्भर।",
     "Some microbes like blue-green algae gather their own food — the rest of the micro-world depends mostly on ready food."),

    ("microbial-world", "medium",
     "मिट्टी में सूक्ष्मजीवों की संख्या विशेष रूप से क्यों भरपूर रहती है?",
     "Why does soil remain especially rich in the number of microorganisms?",
     ["मिट्टी में आर्द्रता, खनिज और कार्बनिक पदार्थ की निरंतर आपूर्ति रहती है", "क्योंकि मिट्टी सबसे साफ होती है", "क्योंकि मिट्टी में हवा नहीं होती", "क्योंकि मिट्टी खाली होती है"],
     ["Soil keeps a constant supply of moisture, minerals and organic matter", "Because soil is the cleanest", "Because soil has no air", "Because soil is empty"],
     0,
     "मिट्टी सूक्ष्म-जगत का भंडार-घर है — खाना-पीना और आशियाना दोनों यहीं मिलते हैं।",
     "Soil is the storehouse-home of the micro-world — food-drink and dwelling all are found here."),

    ("microbial-world", "medium",
     "वायरस की बाह्य पहचान क्या है?",
     "What is the outer identity of a virus?",
     ["प्रोटीन-आवरण में बंद आनुवंशिक पदार्थ", "सेल्युलोज की दीवार", "काइटिन का कवच", "चूने का खोल"],
     ["Genetic material wrapped in a protein coat", "A cellulose wall", "A chitin armour", "A lime shell"],
     0,
     "केंद्र में आनुवंशिक सामग्री, बाहर प्रोटीन की परत — वायरस का पूरा सामान इतना ही सूक्ष्म है।",
     "Genetic material at the core, a protein layer outside — the virus's entire luggage is this miniature."),

    ("microbial-world", "medium",
     "प्रोटोज़ोआ और बैक्टीरिया दोनों एकल-कोशिका हैं — दोनों में मुख्य विभाजक क्या है?",
     "Protozoa and bacteria are both single-celled — what is the main divider between them?",
     ["प्रोटोज़ोआ प्राणी-जैसा जीवन-ढंग रखते हैं; बैक्टीरिया जीवाणु-गुट के सूक्ष्मतम-सरल ढाँचे वाले", "दोनों में कोई अंतर नहीं", "प्रोटोज़ोआ पौधे हैं", "बैक्टीरिया सबसे बड़े जीव हैं"],
     ["Protozoa keep an animal-like way of life; bacteria are the tiniest-simplest framed of the bacterial clan", "No difference between the two", "Protozoa are plants", "Bacteria are the largest beings"],
     0,
     "दोनों एकल-कोशिका होकर भी अलग गुट हैं — प्रोटोज़ोआ का स्वभाव प्राणी-जैसा, जीवाणुओं का ढाँचा अपने ही दर्जे का सरल।",
     "Though both single-celled they are separate clans — protozoa's nature animal-like, bacteria's frame simple in its own rank."),

    ("microbial-world", "medium",
     "रेफ्रिजरेटर में रखा भोजन बाहर की तुलना में अधिक दिन क्यों टिकता है?",
     "Why does food kept in a refrigerator last more days than outside?",
     ["ठंडे तापमान पर सूक्ष्मजीवों की वृद्धि बहुत धीमी हो जाती है", "ठंड में सूक्ष्मजीव मर जाते हैं", "रेफ्रिजरेटर भोजन खा जाता है", "ठंड में रोगाणु भाग जाते हैं"],
     ["At cold temperature the growth of microorganisms becomes very slow", "Microbes die in the cold", "The refrigerator eats the food", "Germs run away in the cold"],
     0,
     "ठंड जीवाणु-गुणन की गाड़ी की ब्रेक लगाती है — गाड़ी रुकती नहीं, धीमी जरूर हो जाती है; इसीलिए फ्रिज में भोजन देर तक, पर सदा नहीं टिकता।",
     "Cold applies the brake to the bacterial-multiplication train — the train does not stop, only slows; hence food in the fridge lasts longer, but not forever."),

    ("microbial-world", "hard",
     "निम्न सूक्ष्मजीव-समूह युग्मों में से कौन-सा पूर्णतः सही है?",
     "Which microorganism-group pair is ENTIRELY correct?",
     ["मलेरिया-प्रोटोज़ोआ, रोटी-फफूंद, पोलियो-वायरस", "मलेरिया-वायरस, रोटी-बैक्टीरिया, पोलियो-फफूंद", "मलेरिया-फफूंद, रोटी-प्रोटोज़ोआ, पोलियो-बैक्टीरिया", "मलेरिया-बैक्टीरिया, रोटी-वायरस, पोलियो-प्रोटोज़ोआ"],
     ["Malaria-protozoan, bread-mould-fungus, polio-virus", "Malaria-virus, bread-bacterium, polio-fungus", "Malaria-fungus, bread-protozoan, polio-bacterium", "Malaria-bacterium, bread-virus, polio-protozoan"],
     0,
     "तीनों युग्म पहले विकल्प में ही सही बैठते हैं — रोग, रोटी और पोलियो अपने-अपने गुटों के सही निवासी।",
     "All three pairs sit right only in the first option — disease, bread and polio rightly housed in their clans."),

    ("microbial-world", "hard",
     "जीवाणु वर्ग की कोशिकाओं की वह विशेषता जो उन्हें ऊँचे-संगठित जीवों से अलग करती है, क्या है?",
     "What is that feature of bacterial cells which separates them from higher-organised beings?",
     ["उनका आनुवंशिक पदार्थ झिल्ली-बद्ध केंद्रक में संगठित नहीं होता", "उनमें कोशिका-भित्ति नहीं होती", "उनमें झिल्ली नहीं होती", "उनमें जीवद्रव्य नहीं होता"],
     ["Their genetic material is not organised in a membrane-bound nucleus", "They have no cell wall", "They have no membrane", "They have no cytoplasm"],
     0,
     "जीवाणुओं में केंद्रक-झिल्ली नहीं — आनुवंशिक सामग्री सीधे कोशिका-द्रव्य में रहती है; यही उनकी सूक्ष्म-पहचान है।",
     "Bacteria keep no nuclear membrane — genetic material lies free in the cell-sap; this is their micro-signature."),

    ("microbial-world", "hard",
     "चार सूक्ष्म-गुटों को उनकी 'स्वतंत्र जीवन-क्षमता' के आधार पर सोचिए — कौन-सा कथन सही है?",
     "Think of the four micro-clans on the basis of their 'capacity for independent life' — which statement is correct?",
     ["जीवाणु और प्रोटोज़ोआ स्वतंत्र जीवन जी सकते हैं; वायरस नहीं", "वायरस स्वतंत्र जीवन जी सकते हैं; जीवाणु नहीं", "चारों गुट स्वतंत्र जीवन से बाहर हैं", "चारों गुट वायरस-जैसे परजीवी हैं"],
     ["Bacteria and protozoa can live independent life; viruses cannot", "Viruses can live independent life; bacteria cannot", "All four clans are outside independent life", "All four clans are virus-like parasites"],
     0,
     "जीवाणु-प्रोटोज़ोआ अपनी कोशिका-भर की दुकान चलाते हैं; वायरस केवल किराए की कोशिका में अपनी प्रतिलिपि छापते हैं।",
     "Bacteria-protozoa run their own full-cell shop; viruses only print their copy in a rented cell."),

    # ================= USEFUL MICROORGANISMS — 25 (E8/M14/H3) =================
    ("useful-microorganisms", "easy",
     "दही जमाने में कौन-सा सूक्ष्मजीव काम करता है?",
     "Which microorganism works in setting curd?",
     ["लैक्टोबैसिलस (दूध-जमाने वाला जीवाणु)", "वायरस", "अमीबा", "मच्छर"],
     ["Lactobacillus (the milk-setting bacterium)", "A virus", "Amoeba", "A mosquito"],
     0,
     "लैक्टोबैसिलस दूध की शर्करा को दही में बदल देता है — पुरानी दही का चम्मच नई दही का बीज है।",
     "Lactobacillus turns milk's sugar into curd — a spoon of old curd is the seed of the new."),

    ("useful-microorganisms", "easy",
     "इडली-डोसा का बैटर फूलकर खमीरी क्यों हो जाता है?",
     "Why does the idli-dosa batter rise and turn frothy?",
     ["उसमें पल रहे सूक्ष्मजीव गैस उत्पन्न करते हैं", "बैटर गर्मी से पिघल जाता है", "चावल पानी पी लेते हैं", "डोसा खुद उछलता है"],
     ["The microbes growing in it produce gas", "The batter melts with heat", "The rice drinks up the water", "The dosa jumps by itself"],
     0,
     "रात भर बैटर में सूक्ष्मजीव अपना काम करते हैं — उनकी गैस के गुब्बारों से ही इडली नरम-फूली बनती है।",
     "All night the microbes work in the batter — their gas-bubbles alone make the idli soft and risen."),

    ("useful-microorganisms", "easy",
     "डबलरोटी (ब्रेड) का आटा फूलने में कौन सहायक है?",
     "What helps the bread dough rise?",
     ["खमीर (यीस्ट)", "चींटियाँ", "बालू", "लोहा"],
     ["Yeast", "Ants", "Sand", "Iron"],
     0,
     "खमीर आटे में गैस के छोटे-छोटे गुब्बारे छोड़ता है — बनते समय वही गुब्बारे ब्रेड के छेद बन जाते हैं।",
     "Yeast releases tiny gas-balloons in the dough — the same balloons become the bread's holes when baked."),

    ("useful-microorganisms", "easy",
     "पेनिसिलिन की खोज किसने की थी?",
     "Who discovered penicillin?",
     ["अलेक्जेंडर फ्लेमिंग ने", "न्यूटन ने", "गैलीलियो ने", "कोलंबस ने"],
     ["Alexander Fleming", "Newton", "Galileo", "Columbus"],
     0,
     "फ्लेमिंग ने यह देखा कि एक फफूंद ने अपने आस-पास के जीवाणु मार दिए — इसी नज़रे से पेनिसिलिन का युग आया।",
     "Fleming saw a fungus had killed the bacteria around it — from this sight dawned the era of penicillin."),

    ("useful-microorganisms", "easy",
     "प्रतिजैविक (एंटीबायोटिक) क्या होते हैं?",
     "What are antibiotics?",
     ["ऐसी दवाइयाँ जो जीवाणुओं की वृद्धि रोकती या उन्हें मारती हैं", "भोजन पचाने वाले रस", "विटामिन की गोलियाँ", "उर्वरक की थैलियाँ"],
     ["Medicines that stop or kill bacteria", "Digestive juices", "Vitamin pills", "Fertiliser bags"],
     0,
     "एंटीबायोटिक जीवाणु-रोगों के विरुद्ध शरीर की सेना के साथ लड़ने वाले हथियार हैं।",
     "Antibiotics are weapons that fight alongside the body's army against bacterial diseases."),

    ("useful-microorganisms", "easy",
     "मिट्टी की उर्वरता बनाए रखने में सहायक सूक्ष्मजीवों में कौन-से गिने जाते हैं?",
     "Which are counted among the microorganisms helpful in maintaining soil fertility?",
     ["राइजोबियम और नीली-हरी शैवाल", "मच्छर और मक्खी", "कोरोना और पोलियो", "दाद और रतुआ"],
     ["Rhizobium and blue-green algae", "Mosquito and housefly", "Corona and polio", "Ringworm and rust"],
     0,
     "ये सूक्ष्म मित्र वायु की नाइट्रोजन को पौधों के लिए उपयोगी रूप में बदलते हैं — मिट्टी का प्राकृतिक उर्वरक-कारखाना।",
     "These micro-friends convert air's nitrogen into a form useful for plants — the soil's natural fertiliser factory."),

    ("useful-microorganisms", "easy",
     "मृत पौधों-प्राणियों के शरीर को सड़ाकर सरल पदार्थों में बदलने वाले सूक्ष्मजीव क्या कहलाते हैं?",
     "What are the microorganisms that decompose dead plant-animal bodies into simple substances called?",
     ["अपघटक (डिकंपोज़र)", "उत्पादक", "शिकारी", "परागक"],
     ["Decomposers", "Producers", "Predators", "Pollinators"],
     0,
     "अपघटक सूक्ष्मजीव प्रकृति की सफाई-दास्तान हैं — मृत को गुनगुना कर मिट्टी में लौटा देते हैं।",
     "Decomposer microbes are nature's cleaning crew — they warm the dead and return it to the soil."),

    ("useful-microorganisms", "easy",
     "गोबर-गैस (गैसीय ईंधन) का निर्माण किन सूक्ष्मजीवों से होता है?",
     "The production of gobargas (gobar-gas fuel) is done by which microorganisms?",
     ["मीथेन बनाने वाले जीवाणुओं से", "वायरस से", "अमीबा से", "फफूंद से"],
     ["Methane-making bacteria", "Viruses", "Amoeba", "Fungi"],
     0,
     "गोबर में पलने वाले जीवाणु बिना हवा के मीथेन गैस बनाते हैं — खेत का कचरा चूल्हे की आग बन जाता है।",
     "Bacteria breeding in dung make methane gas without air — the farm's waste becomes the stove's flame."),

    ("useful-microorganisms", "easy",
     "शराब उद्योग में किस सूक्ष्मजीव का उपयोग होता है?",
     "Which microorganism is used in the alcohol industry?",
     ["खमीर (यीस्ट)", "लैक्टोबैसिलस", "प्लाज्मोडियम", "एनोफेलीज़"],
     ["Yeast", "Lactobacillus", "Plasmodium", "Anopheles"],
     0,
     "खमीर चीनी-घोल का किण्वन करके एल्कोहॉल बनाता है — इसी कला पर शराब-कारखानों की नींव है।",
     "Yeast ferments sugar-solution into alcohol — the whole foundation of distilleries rests on this art."),

    ("useful-microorganisms", "medium",
     "दूध को लंबे समय तक सुरक्षित रखने के लिए उसे गर्म करके झटपट ठंडा किया जाता है — यह प्रक्रिया क्या कहलाती है?",
     "The process of heating milk and quickly cooling it to keep it safe long — what is it called?",
     ["पाश्चुरीकरण", "आसवन", "वाष्पीकरण", "निस्पंदन"],
     ["Pasteurisation", "Distillation", "Vaporisation", "Filtration"],
     0,
     "पाश्चुरीकरण दूध के हानिकारक जीवाणुओं को मार-घटा देता है — स्वाद वैसा, सुरक्षा बढ़ी।",
     "Pasteurisation kills-reduces milk's harmful bacteria — taste the same, safety raised."),

    ("useful-microorganisms", "medium",
     "किण्वन (फर्मेंटेशन) किसे कहते हैं?",
     "What is called fermentation?",
     ["खमीर द्वारा शर्करा का एल्कोहॉल में बदलना", "पानी का बर्फ बनना", "लोहे का जंग लगना", "दूध का मक्खन बनना"],
     ["The conversion of sugar into alcohol by yeast", "Water turning to ice", "Iron catching rust", "Milk turning to butter"],
     0,
     "शर्करा → एल्कोहॉल + कार्बन डाइऑक्साइड — खमीर की इसी धुन पर ब्रेड से शराब तक का उद्योग टिका है।",
     "Sugar → alcohol + carbon dioxide — on this very tune of yeast rest the industries from bread to brew."),

    ("useful-microorganisms", "medium",
     "टीका (वैक्सीन) में सामान्यतः क्या होता है?",
     "What does a vaccine usually contain?",
     ["रोगाणु का कमज़ोर या मृत रूप", "रोगाणु का पूरी ताकत वाला जीवित रूप", "केवल चीनी", "केवल नमक"],
     ["A weakened or dead form of the pathogen", "A fully potent living form of the pathogen", "Only sugar", "Only salt"],
     0,
     "टीके में रोगाणु की ताकत तोड़ी जा चुकी होती है — शरीर उसे देखकर बिना बीमार हुए रक्षा-पहरा सीख लेता है।",
     "In a vaccine the pathogen's strength is broken — the body sees it and learns the defence-drill without falling ill."),

    ("useful-microorganisms", "medium",
     "टीकाकरण का मूल सिद्धांत क्या है?",
     "What is the basic principle of vaccination?",
     ["हल्के/मृत रोगाणु से शरीर एंटीबॉडी बनाकर स्मृति-रक्षा विकसित करता है", "शरीर को बहुत बीमार करके डराना", "रोगाणुओं को भोजन देना", "रक्त निकाल देना"],
     ["From mild/dead germs the body builds antibodies and develops memory-defence", "Scaring the body by making it very ill", "Feeding the germs", "Draining out the blood"],
     0,
     "टीका एक मैक-परीक्षा है — हल्के रोगाणु से तैयारी कर ली, तो असली परीक्षा में शरीर पहले से जागा मिलता है।",
     "A vaccine is a mock-test — prepare with a mild germ, and in the real exam the body is found already awake."),

    ("useful-microorganisms", "medium",
     "पेनिसिलिन का स्रोत कौन-सा सूक्ष्मजीव है?",
     "Which microorganism is the source of penicillin?",
     ["एक फफूंद (पेनिसिलियम)", "एक जीवाणु", "एक वायरस", "एक प्रोटोज़ोआ"],
     ["A fungus (Penicillium)", "A bacterium", "A virus", "A protozoan"],
     0,
     "पेनिसिलियम फफूंद का बनाया पेनिसिलिन जीवाणुओं के लिए संहारक सिद्ध हुआ — फफूंद वाले फ्लेमिंग की खिड़की वाली खोज।",
     "Penicillin, made by the Penicillium fungus, proved fatal to bacteria — the fungus-man Fleming's window-seat discovery."),

    ("useful-microorganisms", "medium",
     "राइजोबियम जीवाणु नाइट्रोजन-स्थिरीकरण करके किसकी फसलों को लाभ पहुँचाते हैं?",
     "Rhizobium bacteria, by fixing nitrogen, benefit the crops of what?",
     ["दलहनी फसलों (चना, मटर, सोयाबीन) को", "आम के पेड़ों को", "गेहूँ की हर बाली को", "केले के पौधों को"],
     ["Leguminous crops (gram, pea, soybean)", "Mango trees", "Every ear of wheat", "Banana plants"],
     0,
     "राइजोबियम दलहनी जड़ों के गाँठों में रहकर वायु-नाइट्रोजन स्थिर करते हैं — खेत का हरा उर्वरक-ठेका।",
     "Rhizobium, living in legume-root nodules, fixes air-nitrogen — the field's green fertiliser contract."),

    ("useful-microorganisms", "medium",
     "वायुमंडल की नाइट्रोजन को पौधों के लिए उपयोगी बनाने वाली प्रक्रिया का नाम क्या है?",
     "What is the name of the process that makes the atmosphere's nitrogen useful for plants?",
     ["नाइट्रोजन-स्थिरीकरण", "प्रकाश-संश्लेषण", "वाष्पोत्सर्जन", "संघनन"],
     ["Nitrogen fixation", "Photosynthesis", "Transpiration", "Condensation"],
     0,
     "वायु की नाइट्रोजन सीधे पौधे नहीं ले सकते — सूक्ष्मजीव उसे स्थिर करके उपयोगी खुराक बनाते हैं।",
     "Plants cannot take air's nitrogen directly — microbes fix it into a usable dose."),

    ("useful-microorganisms", "medium",
     "नीली-हरी शैवाल (सायनोबैक्टीरिया) खेती में किस रूप में उपयोगी हैं?",
     "In what form are blue-green algae (cyanobacteria) useful in farming?",
     ["वे नाइट्रोजन स्थिर करके मिट्टी की उर्वरता बढ़ाते हैं", "वे फसल काट देते हैं", "वे खेत सुखा देते हैं", "वे मिट्टी उखाड़ देते हैं"],
     ["They fix nitrogen and raise soil fertility", "They cut the crop", "They dry the field", "They uproot the soil"],
     0,
     "चावल के दलदल-खेतों में नीली-हरी शैवाल मुफ्त का नाइट्रोजन-घर चलाती हैं।",
     "In rice's marsh-fields blue-green algae run a free nitrogen-house."),

    ("useful-microorganisms", "medium",
     "अपघटक सूक्ष्मजीव पर्यावरण की सफाई में कैसे सहायक हैं?",
     "How are decomposer microbes helpful in nature's cleaning?",
     ["वे मृत पदार्थों को सरल तत्वों में बदलकर मिट्टी में लौटा देते हैं", "वे कचरा इकट्ठा करके बेच देते हैं", "वे कचरा जला देते हैं", "वे कचरा नदी में बहा देते हैं"],
     ["They convert dead matter into simple elements and return it to the soil", "They collect and sell the waste", "They burn the waste", "They dump waste into the river"],
     0,
     "सूक्ष्म-अपघटक प्रकृति की रीसायकल-मशीन हैं — मृत का कचरा, जीवन का कच्चा माल।",
     "Micro-decomposers are nature's recycling machine — the dead's waste, life's raw material."),

    ("useful-microorganisms", "medium",
     "सिरका (एसिटिक अम्ल) के निर्माण में कौन-सा सूक्ष्मजीव सहायक है?",
     "Which microorganism helps in the making of vinegar (acetic acid)?",
     ["एसिटिक अम्ल बनाने वाले जीवाणु", "खमीर", "प्लाज्मोडियम", "नीली-हरी शैवाल"],
     ["Acetic-acid-making bacteria", "Yeast", "Plasmodium", "Blue-green algae"],
     0,
     "अल्कोहॉल को आगे ऑक्सीकृत कर एसिटिक जीवाणु उसे सिरके में बदल देते हैं — इसीलिए खुली शराब खट्टी हो जाती है।",
     "Oxidising alcohol further, acetic bacteria turn it into vinegar — that is why open liquor turns sour."),

    ("useful-microorganisms", "medium",
     "व्यर्थ जल (सीवेज) के शोधन में सूक्ष्मजीव क्या करते हैं?",
     "What do microorganisms do in the treatment of waste water (sewage)?",
     ["वे जल में घुले कार्बनिक अपशिष्ट को तोड़कर जल साफ करते हैं", "वे जल में रंग भरते हैं", "वे जल को जमा देते हैं", "वे नालियाँ तोड़ देते हैं"],
     ["They break down the organic waste dissolved in water and clean it", "They colour the water", "They freeze the water", "They break the drains"],
     0,
     "शोधन-टैंकों में सूक्ष्मजीवों की दास्ता कार्बनिक बोझ खा-खाकर हल्का कर देती है — जल वापस धारा में लौटता है।",
     "In treatment tanks the microbe crew eats the organic load light — the water returns to the stream."),

    ("useful-microorganisms", "medium",
     "एंटीबायोटिक का स्रोत मुख्यतः कौन-से सूक्ष्मजीव हैं?",
     "Which microorganisms are the main source of antibiotics?",
     ["जीवाणु और फफूंद", "वायरस और प्रोटोज़ोआ", "मच्छर और मक्खी", "शैवाल और मॉस"],
     ["Bacteria and fungi", "Viruses and protozoa", "Mosquito and housefly", "Algae and moss"],
     0,
     "अपनी लड़ाई के हथियार के रूप में जीवाणु-फफूंद जो रसायन बनाते हैं, मनुष्य ने उन्हीं की दवा बना ली।",
     "The chemicals bacteria-fungi make as their combat weapons, humans turned into medicines."),

    ("useful-microorganisms", "medium",
     "टीके की खोज की दिशा में अग्रणी योगदान किसका माना जाता है — चेचक के टीके के रूप में?",
     "Whose contribution is counted pioneering in the discovery of vaccines — in the form of the smallpox vaccine?",
     ["एडवर्ड जेनर का", "थॉमस एडिसन का", "आइंस्टीन का", "मैगलन का"],
     ["Edward Jenner's", "Thomas Edison's", "Einstein's", "Magellan's"],
     0,
     "जेनर ने देखा कि गाय-मट्ठे वाले दुग्धपालक चेचक से बचे रहते हैं — इसी सुराग से टीके का द्वार खुला।",
     "Jenner saw that milkmaids who had cowpox stayed safe from smallpox — from this clue the door of vaccines opened."),

    ("useful-microorganisms", "hard",
     "बिना ऑक्सीजन के गोबर में जीवाणु क्या बनाते हैं — और वह किस काम आता है?",
     "Without oxygen, what do bacteria in dung make — and what is it used for?",
     ["मीथेन — ईंधन के रूप में चूल्हे-लालटेन में", "ऑक्सीजन — गुब्बारे में", "हीलियम — जहाज़ों में", "क्लोरीन — पूल में"],
     ["Methane — used as fuel in stoves-lanterns", "Oxygen — in balloons", "Helium — in airships", "Chlorine — in pools"],
     0,
     "अवायवीय जीवाणु गोबर से मीथेन बनाते हैं — गोबर-गैस प्लांट गाँव का सस्ता ऊर्जा-सौदा।",
     "Anaerobic bacteria make methane from dung — the gobargas plant is the village's cheap energy deal."),

    ("useful-microorganisms", "hard",
     "पौधे वायु की नाइट्रोजन सीधे क्यों नहीं ले पाते — और यह कमी कौन पूरा करता है?",
     "Why can plants not take the air's nitrogen directly — and who fills this lack?",
     ["नाइट्रोजन का अणु बहुत स्थिर है; राइजोबियम जैसे सूक्ष्मजीव उसे स्थिरीकृत कर पौधों तक पहुँचाते हैं", "नाइट्रोजन जहरीली है; मच्छर उसे बदलते हैं", "पौधे नाइट्रोजन से डरते हैं; चींटियाँ रखवाली करती हैं", "नाइट्रोजन भारी है; हाथी उसे ढोते हैं"],
     ["The nitrogen molecule is too stable; microbes like Rhizobium fix it and deliver it to plants", "Nitrogen is poisonous; mosquitoes change it", "Plants fear nitrogen; ants guard it", "Nitrogen is heavy; elephants carry it"],
     0,
     "वायु की नाइट्रोजन की मजबूत बंधी को सूक्ष्मजीव ही तोड़ पाते हैं — फिर पौधे उसे नुक्तचीनी कर लेते हैं।",
     "Only microbes can break the strong bond of air's nitrogen — then plants nit-pick it up."),

    ("useful-microorganisms", "hard",
     "उपयोगी सूक्ष्मजीवों के चार अलग-अलग युद्धक्षेत्र — दही, ब्रेड, पेनिसिलिन, गोबर-गैस। सही सूक्ष्मजीव-युद्धक्षेत्र सुमेलन कौन-सा है?",
     "Four different battlefields of useful microbes — curd, bread, penicillin, gobargas. Which microbe-battlefield matching is correct?",
     ["लैक्टोबैसिलस-दही, खमीर-ब्रेड, पेनिसिलियम-पेनिसिलिन, मीथेन-जीवाणु-गोबरगैस", "खमीर-दही, लैक्टोबैसिलस-ब्रेड, मीथेन-पेनिसिलिन, पेनिसिलियम-गोबरगैस", "पेनिसिलियम-दही, मीथेन-ब्रेड, लैक्टोबैसिलस-पेनिसिलिन, खमीर-गोबरगैस", "सभी काम एक ही जीवाणु करता है"],
     ["Lactobacillus-curd, yeast-bread, Penicillium-penicillin, methane-bacteria-gobargas", "Yeast-curd, Lactobacillus-bread, methane-penicillin, Penicillium-gobargas", "Penicillium-curd, methane-bread, Lactobacillus-penicillin, yeast-gobargas", "All jobs done by one bacterium"],
     0,
     "चारों काम चार विशेषज्ञों के — दही का लैक्टोबैसिलस, ब्रेड का खमीर, दवा का पेनिसिलियम, गैस का मीथेन-जीवाणु।",
     "Four jobs, four specialists — curd's Lactobacillus, bread's yeast, medicine's Penicillium, gas's methane-bacteria."),
]
