# -*- coding: utf-8 -*-
"""B12 Part-2 — Environment, Ecosystems & Natural Resources (chapter-12).
80 items: energy-flow 20 (E7/M11/H2) + natural-resources-conservation 25 (E8/M14/H3)
          + pollution-waste-sustainability 35 (E12/M20/H3).
Tuple: (topic, difficulty, question_hi, question_en, options_hi[4], options_en[4], correct_idx, expl_hi, expl_en)

DENY-AWARENESS (Part-2): B07/ch-08 q945 owns photosynthesis-vs-respiration energy
directions; B04 q522 greenhouse-CO2 farming; B04 q558 lightning nitrogen route;
B04 q586 tree-roots erosion; B04 q627 manure-vs-fertiliser; B11 q1171 sewage-microbe
treatment. => energy items use 10%-law/unidirectional/pyramid angles; greenhouse =
heat-trap/global-warming (not farm CO2); nitrogen = cycle ORDER; soil = deforestation
consequence/afforestation; sewage = why-treat-before-release policy angle.
"""

PART2 = [
    # ================= ENERGY FLOW & ECOLOGICAL RELATIONS — 20 (E7/M11/H2) =================
    ("energy-flow-relations", "easy",
     "पारितंत्र की समस्त ऊर्जा का मूल स्रोत कौन-सा है?",
     "What is the root source of all the energy of an ecosystem?",
     ["सूर्य", "चंद्रमा", "तारे", "ज्वालामुखी"],
     ["The sun", "The moon", "The stars", "Volcanoes"],
     0,
     "धूप से पौधा, पौधे से श्रृंखला — पारितंत्र की हर ऊर्जा-बूँद की जन्मभूमि सूर्य ही है।",
     "From sunshine to plant, from plant to chain — the sun alone is the birthplace of every drop of the ecosystem's energy."),

    ("energy-flow-relations", "easy",
     "सूर्य की ऊर्जा खाद्य-श्रृंखला में सबसे पहले किसके द्वारा भोजन में बाँधी जाती है?",
     "By whom is the sun's energy first bound into food in a food chain?",
     ["हरे पौधों (निर्माताओं) द्वारा", "शिकारियों द्वारा", "अपघटकों द्वारा", "मृतभक्षियों द्वारा"],
     ["By green plants (producers)", "By predators", "By decomposers", "By scavengers"],
     0,
     "धूप को रोटी में बदलने का एकमात्र कारखाना हरा पौधा है — श्रृंखला की ऊर्जा-प्रवेश-द्वार यही।",
     "The only factory that turns sunshine into bread is the green plant — the energy-entry-door of the chain."),

    ("energy-flow-relations", "easy",
     "खाद्य-श्रृंखला में ऊर्जा किस दिशा में चलती है?",
     "In which direction does energy travel in a food chain?",
     ["निर्माता से उपभोक्ताओं की ओर — नीचे से ऊपर", "शिकारी से शिकार की ओर", "उपभोक्ता से निर्माता की ओर", "किसी दिशा में नहीं"],
     ["From producers towards consumers — bottom to top", "From predator towards prey", "From consumers towards producers", "In no direction"],
     0,
     "घास से हिरण, हिरण से शेर — ऊर्जा का रास्ता हमेशा खाने से खाने वाले की ओर ऊपर की मंजिलों में चढ़ता है।",
     "From grass to deer, deer to lion — energy's path always climbs the floors from the eaten to the eater."),

    ("energy-flow-relations", "easy",
     "खाद्य-श्रृंखला में 'भोजन' मूल रूप से किसका वाहक है?",
     "In a food chain, 'food' is basically the carrier of what?",
     ["ऊर्जा का", "रंग का", "ध्वनि का", "सुगंध का"],
     ["Of energy", "Of colour", "Of sound", "Of fragrance"],
     0,
     "जो भोजन ऊपर जाता है, उसमें ऊर्जा बैठी होती है — श्रृंखला ऊर्जा की आपूर्ति-लाइन है।",
     "The food that goes up carries energy seated within — the chain is energy's supply-line."),

    ("energy-flow-relations", "easy",
     "पारितंत्र में ऊर्जा का अंतिम रूप क्या बनता है — जो वापस काम में नहीं आता?",
     "What final form does energy take in an ecosystem — which does not come back into use?",
     ["गर्मी (ऊष्मा)", "प्रकाश", "भोजन", "खनिज"],
     ["Heat", "Light", "Food", "Minerals"],
     0,
     "हर स्तर पर बड़ा हिस्सा गर्मी बनकर हवा में बिखर जाता है — वह गर्मी फिर श्रृंखला में नहीं लौटती।",
     "At every level a large part scatters into air as heat — that heat does not return to the chain."),

    ("energy-flow-relations", "easy",
     "एक पोषण-स्तर से अगले स्तर तक पहुँचते समय ऊर्जा की मात्रा का सामान्य रुझान कैसा होता है?",
     "What is the usual trend of the amount of energy as it passes from one trophic level to the next?",
     ["कम हो जाती है", "बढ़ जाती है", "दोगुनी हो जाती है", "अपरिवर्तित रहती है"],
     ["It decreases", "It increases", "It doubles", "It remains unchanged"],
     0,
     "हर मंजिल पर खर्च और बिखराव — ऊपर पहुँचते-पहुँचते बटुआ हल्का होता जाता है।",
     "Spending and scattering at every floor — the purse keeps getting lighter on the way up."),

    ("energy-flow-relations", "easy",
     "क्या ऊर्जा श्रृंखला में शेर से घास की ओर लौट सकती है?",
     "Can energy in a chain return from the lion towards the grass?",
     ["नहीं — प्रवाह एकमुखी है", "हाँ, रोज़ लौटती है", "हाँ, सर्दियों में", "हाँ, अपघटक वापस भेजते हैं"],
     ["No — the flow is one-way", "Yes, it returns daily", "Yes, in winters", "Yes, decomposers send it back"],
     0,
     "ऊर्जा का प्रवाह नल की तरह नहीं, नदी की तरह है — बहती है आगे, लौटती नहीं।",
     "Energy's flow is not like a tap but like a river — it flows ahead, never back."),

    ("energy-flow-relations", "medium",
     "ऊर्जा-स्थानांतरण का 10 प्रतिशत नियम क्या कहता है?",
     "What does the ten percent law of energy transfer say?",
     ["एक स्तर की ऊर्जा का लगभग 10% ही अगले स्तर तक पहुँचता है", "10% ऊर्जा मिट्टी में चली जाती है", "10% ऊर्जा शिकारी छोड़ देता है", "10% ऊर्जा हर स्तर पर बनती है"],
     ["Only about 10% of a level's energy reaches the next level", "10% of energy goes into the soil", "The predator leaves 10% energy", "10% energy is created at every level"],
     0,
     "घास की सौ इकाइयों में से हिरण तक दस, हिरण की दस में से शेर तक एक — हर मंजिल पर 90% खर्च-बिखर जाता है।",
     "Of a hundred units of grass, ten reach the deer; of the deer's ten, one reaches the lion — at every floor 90% is spent-scattered."),

    ("energy-flow-relations", "medium",
     "1000 किलो घास से चलने वाली श्रृंखला में 10% नियम से शेर-स्तर तक पहुँचने वाली ऊर्जा-मात्रा लगभग कितनी होगी?",
     "In a chain starting from 1000 kg of grass, by the 10% law roughly what amount of energy reaches the lion level?",
     ["लगभग 10 किलो-तुल्य", "लगभग 500 किलो-तुल्य", "लगभग 1000 किलो-तुल्य", "लगभग 100 किलो-तुल्य"],
     ["About 10 kg-equivalent", "About 500 kg-equivalent", "About 1000 kg-equivalent", "About 100 kg-equivalent"],
     0,
     "1000 → हिरण पर 100 → शेर पर 10 — दो मंजिलों की चढ़ाई में सौगुना घटाव।",
     "1000 → 100 at the deer → 10 at the lion — a hundredfold cut in the climb of two floors."),

    ("energy-flow-relations", "medium",
     "खाद्य-श्रृंखलाएँ प्रायः 4–5 स्तरों से अधिक लंबी क्यों नहीं होतीं?",
     "Why are food chains usually not longer than 4–5 levels?",
     ["हर स्तर पर ऊर्जा घटती जाती है — अंतिम स्तरों तक जीवित रहने लायक बचती ही नहीं", "क्योंकि जीव थक जाते हैं", "क्योंकि श्रृंखला टूट जाती है", "क्योंकि सूर्य रात में नहीं निकलता"],
     ["Energy keeps falling at every level — nothing survival-worthy remains for the last levels", "Because organisms get tired", "Because the chain breaks", "Because the sun does not rise at night"],
     0,
     "जिस मंजिल पर भोजन की कमाई खर्च से कम पड़े, वहाँ कोई किरायेदार टिक नहीं पाता — ऊर्जा-घाटा ही श्रृंखला की लंबाई की सीमा है।",
     "On the floor where food's earning falls below the expense, no tenant can stay — the energy-deficit is the very limit of the chain's length."),

    ("energy-flow-relations", "medium",
     "श्रृंखला में सर्वाधिक ऊर्जा किस स्तर पर उपलब्ध रहती है?",
     "At which level does the maximum energy remain available in the chain?",
     ["निर्माताओं के स्तर पर", "शीर्ष शिकारी पर", "दूसरे उपभोक्ता पर", "अपघटकों पर"],
     ["At the producers' level", "At the top predator", "At the second consumer", "At the decomposers"],
     0,
     "सबसे नीचे की मंजिल पर भंडार भरा — जितनी ऊँची मंजिल, उतना छोटा बटुआ।",
     "The store is full on the lowest floor — the higher the floor, the smaller the purse."),

    ("energy-flow-relations", "medium",
     "एक स्तर से दूसरे स्तर पर ऊर्जा का बड़ा हिस्सा कहाँ खर्च-बिखर जाता है?",
     "Where does the major share of energy get spent-scattered in passing from one level to another?",
     ["जीव की जीवन-क्रियाओं में और गर्मी के रूप में वातावरण में", "मिट्टी में दफन होने में", "अंडों में संचित होने में", "हवा में रंग बनने में"],
     ["In the organism's life-processes and as heat into the surroundings", "In getting buried in the soil", "In being stored in eggs", "In turning into colour in the air"],
     0,
     "दौड़ना, पचाना, साँस लेना — हर काम का बिल ऊर्जा से चुकता होता है; बची ऊर्जा गर्मी बनकर हवा हो जाती है।",
     "Running, digesting, breathing — every task's bill is paid in energy; the leftover turns to heat and becomes air."),

    ("energy-flow-relations", "medium",
     "'ऊर्जा-पिरामिड' का आकार नीचे चौड़ा और ऊपर संकरा क्यों होता है?",
     "Why is the shape of the 'energy pyramid' broad at the base and narrow at the top?",
     ["हर ऊपरी स्तर को कम ऊर्जा मिलती है — ढेर नीचे से ऊपर छोटा होता जाता है", "क्योंकि नीचे के जीव मोटे होते हैं", "क्योंकि ऊपर हवा तेज़ होती है", "क्योंकि पिरामिड सुंदर लगता है"],
     ["Every upper level receives less energy — the pile keeps shrinking from bottom to top", "Because the lower organisms are fat", "Because the wind is strong above", "Because a pyramid looks beautiful"],
     0,
     "सौ की नींव पर दस की मंजिल, दस पर एक का कमरा — ऊर्जा-क्षरण की गिनती पिरामिड की बनावट में सही झलकती है।",
     "A floor of ten on a base of hundred, a room of one on ten — the count of energy-loss reflects truly in the pyramid's build."),

    ("energy-flow-relations", "medium",
     "ऊपर के पोषण-स्तरों पर जैव-द्रव्य (biomass) की मात्रा का रुझान कैसा रहता है?",
     "What is the trend of the amount of biomass at the upper trophic levels?",
     ["क्रमशः घटता रहता है", "क्रमशः बढ़ता रहता है", "समान रहता है", "पहले बढ़ता फिर घटता है"],
     ["It keeps decreasing progressively", "It keeps increasing", "It stays equal", "It first rises then falls"],
     0,
     "ऊर्जा जिधर घटे, वजन उधर घटे — कम ऊर्जा वाली मंजिल पर कम माल ढुलता है।",
     "Wherever energy falls, weight falls — less goods get unloaded on a low-energy floor."),

    ("energy-flow-relations", "medium",
     "ऊर्जा पारितंत्र में 'प्रवाहित' होती है जबकि पोषक तत्व 'चक्रित' — दोनों की तुलना का सार क्या है?",
     "Energy 'flows' in an ecosystem while nutrients 'cycle' — what is the essence of the comparison?",
     ["ऊर्जा एक बार गुजरकर गर्मी बन जाती है; पोषक बार-बार घूमते रहते हैं", "दोनों बार-बार घूमते हैं", "दोनों एक ही बार गुजरते हैं", "ऊर्जा घूमती है, पोषक गुजरते हैं"],
     ["Energy passes once and turns into heat; nutrients go round and round again", "Both circle repeatedly", "Both pass only once", "Energy circles, nutrients pass"],
     0,
     "ऊर्जा टिकट-यात्री है — एक सफर, फिर गर्मी में विलय; पोषक स्थायी नागरिक — जन्म-मृत्यु के चक्र में सदा घर-घर।",
     "Energy is a ticketed passenger — one journey, then a merger into heat; nutrients are permanent citizens — ever circulating house to house in the cycle of birth-death."),

    ("energy-flow-relations", "medium",
     "अपघटकों की ऊर्जा-प्राप्ति का स्रोत क्या है?",
     "What is the source of decomposers' energy gain?",
     ["हर पोषण-स्तर के मृत-अवशेष और अपशिष्ट", "केवल शीर्ष शिकारी का शिकार", "सूर्य का सीधा प्रकाश", "जीवित शाकाहारी"],
     ["The dead-remains and waste of every trophic level", "Only the top predator's hunt", "The sun's direct light", "Living herbivores"],
     0,
     "अपघटक ऊर्जा-बही के बाहरी पन्नों से नहीं, हर पंने के मार्जिन से खाते हैं — हर स्तर का बचा-खुचा उन्हीं की रोटी।",
     "Decomposers feed not from outside pages of the energy-ledger but from the margin of every page — every level's leftovers are their bread."),

    ("energy-flow-relations", "medium",
     "मनुष्य शाकाहार से अधिक लोगों का पेट क्यों पाल सकता है — मांसाहार की तुलना में?",
     "Why can man feed more stomachs from vegetarian food — compared to non-vegetarian?",
     ["निम्न स्तर से भोजन लेने पर ऊर्जा-हानि की मंजिलें कम लगती हैं", "शाकाहार में स्वाद कम होता है", "मांस में ऊर्जा होती ही नहीं", "शाकाहार से बीमारी नहीं होती"],
     ["Taking food from a lower level, fewer floors of energy-loss are paid", "Vegetarian food has less taste", "Meat has no energy", "Vegetarian food causes no disease"],
     0,
     "अनाज सीधे निर्माता से — एक मंजिल का टोल; अनाज→गाय→इंसान — दो मंजिल का टोल; जितनी कम मंजिलें, उतनी ज्यादा थालियाँ।",
     "Grain straight from the producer — one floor's toll; grain→cow→man — two floors' toll; the fewer the floors, the more the plates."),

    ("energy-flow-relations", "medium",
     "ऊर्जा का गर्मी में बिखर जाना किस स्तर पर होता है?",
     "At which level does energy's scattering into heat occur?",
     ["हर पोषण-स्तर पर — जीवन-क्रियाओं के दौरान", "केवल निर्माताओं पर", "केवल शीर्ष शिकारी पर", "कहीं नहीं होता"],
     ["At every trophic level — during life-processes", "Only at the producers", "Only at the top predator", "It happens nowhere"],
     0,
     "हर जीव हर पल ऊर्जा जलाता है — गर्मी का रास्ता हर मंजिल की खिड़की से खुला है।",
     "Every being burns energy every moment — the path of heat stays open through every floor's window."),

    ("energy-flow-relations", "hard",
     "ऊर्जा को 'पुनर्चक्रित' क्यों नहीं किया जा सकता — पोषकों की तरह?",
     "Why can energy not be 'recycled' — like nutrients?",
     ["ऊर्जा हर उपयोग में अंततः गर्मी बनकर बिखर जाती है — पारितंत्र उसे फिर भोजन में नहीं बाँध सकता", "क्योंकि ऊर्जा हल्की होती है", "क्योंकि अपघटक आलसी होते हैं", "क्योंकि सूर्य रात में ऊर्जा ले जाता है"],
     ["Energy in every use finally scatters as heat — the ecosystem cannot bind it back into food", "Because energy is light", "Because decomposers are lazy", "Because the sun takes energy away at night"],
     0,
     "पोषक ईंट हैं — गिरें तो फिर इमारत में चढ़ती हैं; ऊर्जा बालू-घड़ी का बीच है — गिरा तो गिरा, बाँधा नहीं जाता।",
     "Nutrients are bricks — fallen, they climb back into the building; energy is the sand of the hourglass — once fallen, it cannot be bound again."),

    ("energy-flow-relations", "hard",
     "संख्या-पिरामिड कभी-कभी उल्टा दिखता है (एक पेड़ पर हजार कीट), पर ऊर्जा-पिरामिड कभी उल्टा क्यों नहीं होता?",
     "The pyramid of numbers sometimes looks inverted (a thousand insects on one tree), but why is the energy pyramid never inverted?",
     ["ऊर्जा हर स्तर पर अनिवार्य रूप से घटती है — संख्या छल सकती है, ऊर्जा नहीं", "क्योंकि ऊर्जा गिनी नहीं जा सकती", "क्योंकि कीट ऊर्जा खाते ही नहीं", "क्योंकि पेड़ छोटे जीवों से ऊर्जा लेते हैं"],
     ["Energy necessarily falls at every level — numbers can deceive, energy cannot", "Because energy cannot be counted", "Because insects do not eat energy", "Because trees take energy from small beings"],
     0,
     "एक बड़े पेड़ की एक ही देह पर हजार छोटे मुँह — संख्या उल्टी दिखे; पर पेड़ की कुल ऊर्जा-पकड़ हजार कीटों से कई गुना बड़ी — ऊर्जा की तुला कभी झूठ नहीं बोलती।",
     "A thousand tiny mouths on the single body of one big tree — numbers may look inverted; but the tree's total energy-hold is many times the thousand insects — the scale of energy never lies."),

    # ================= NATURAL RESOURCES & CONSERVATION — 25 (E8/M14/H3) =================
    ("natural-resources-conservation", "easy",
     "'प्राकृतिक संसाधन' किसे कहते हैं?",
     "What are called 'natural resources'?",
     ["प्रकृति से बिना मानव-प्रयास के प्राप्त उपयोगी चीजें — जल, वायु, मिट्टी, वन, खनिज", "मनुष्य की बनाई मशीनें", "बाजार से खरीदा माल", "केवल सोने के गहने"],
     ["Useful things obtained from nature without human effort — water, air, soil, forests, minerals", "Machines made by man", "Goods bought from the market", "Only gold ornaments"],
     0,
     "हवा से लेकर कोयले तक — जो प्रकृति ने अपनी मर्ज़ी से दिया, वही प्राकृतिक संसाधन।",
     "From air to coal — whatever nature gave by its own will, that is a natural resource."),

    ("natural-resources-conservation", "easy",
     "'नवीकरणीय संसाधन' का अर्थ क्या है?",
     "What is the meaning of 'renewable resources'?",
     ["जो प्रकृति में लगातार फिर बनते रहते हैं", "जो कभी दोबारा नहीं बनते", "जो केवल रात में बनते हैं", "जो केवल शहरों में मिलते हैं"],
     ["Those that keep forming again continuously in nature", "Those that never form again", "Those that form only at night", "Those found only in cities"],
     0,
     "लकीर की दीवार नहीं — बहता झरना; जो खर्च हो और फिर भरे, वही नवीकरणीय।",
     "Not a line drawn on stone but a flowing spring — what gets spent and refills is renewable."),

    ("natural-resources-conservation", "easy",
     "'अनवीकरणीय संसाधन' से क्या समझते हैं?",
     "What is understood by 'non-renewable resources'?",
     ["जिनके बनने में लाखों वर्ष लगते हैं और दोबारा मानव-समय में नहीं बनते", "जो एक हफ्ते में बनते हैं", "जो अनंत हैं", "जो सिर्फ बरसात में मिलते हैं"],
     ["Those that take millions of years to form and do not reform within human time", "Those that form in a week", "Those that are infinite", "Those found only in the rains"],
     0,
     "कोयला-पेट्रोल पृथ्वी की गहरी बचत है — एक बार उठाई तो दोबारा जमा होने में युग लगेंगे।",
     "Coal-petrol are the earth's deep savings — once withdrawn, ages will pass before the deposit refills."),

    ("natural-resources-conservation", "easy",
     "कोयला और पेट्रोलियम किस श्रेणी के संसाधन हैं?",
     "Coal and petroleum are resources of which category?",
     ["अनवीकरणीय — जीवाश्म ईंधन", "नवीकरणीय", "असीमित", "मानव-निर्मित"],
     ["Non-renewable — fossil fuels", "Renewable", "Unlimited", "Man-made"],
     0,
     "करोड़ों वर्ष पुराने जीव-वनों की देह से बने ये ईंधन — इतिहास की जमा-पूँजी, ब्याज नहीं।",
     "These fuels formed from the bodies of organism-forests crores of years old — history's fixed deposit, not interest."),

    ("natural-resources-conservation", "easy",
     "सौर-ऊर्जा और पवन-ऊर्जा किस वर्ग में रखी जाती हैं?",
     "In which class are solar energy and wind energy placed?",
     ["नवीकरणीय/अक्षय ऊर्जा", "अनवीकरणीय", "जीवाश्म", "कृत्रिम"],
     ["Renewable/inexhaustible energy", "Non-renewable", "Fossil", "Artificial"],
     0,
     "सूर्य रोज़ उदय होता है, हवा रोज़ बहती है — इनका खजाना खर्च से घटता नहीं।",
     "The sun rises daily, the wind blows daily — their treasure does not shrink by spending."),

        ("natural-resources-conservation", "easy",
     "मिठास वाला उपयोगी जल — नदियों-झीलों का जल — कुल जल की तुलना में कैसा है?",
     "Useful sweet water — the water of rivers-lakes — compared to total water is how?",
     ["बहुत छोटा अंश", "आधा भाग", "लगभग पूरा", "एक तिहाई"],
     ["A very small fraction", "Half", "Almost all", "One third"],
     0,
     "धरती का ज्यादातर जल खारा सागरीय — पीने-सिंचने लायक मीठे जल का हिस्सा बूँद-भर ही है, इसीलिए बचत जरूरी।",
     "Most of the earth's water is salty sea — the share of sweet water fit for drinking-irrigation is but a drop, hence saving is a must."),

    ("natural-resources-conservation", "easy",
     "जल-चक्र पृथ्वी पर जल को किस रूप में रखता है?",
     "The water cycle keeps the earth's water in what state?",
     ["निरंतर नवीनीकरण की स्थिति में", "एक ही जगह जमा", "केवल बर्फ में", "केवल बादलों में"],
     ["In a state of continuous renewal", "Frozen in one place", "Only in ice", "Only in clouds"],
     0,
     "समुद्र से भाप, भाप से बादल, बादल से बरसात, बरसात से नदी — जल बदलते-बदलते हमेशा ताज़ा रहता है।",
     "Vapour from the sea, cloud from vapour, rain from cloud, river from rain — changing and changing, water stays ever fresh."),

    ("natural-resources-conservation", "easy",
     "वर्षा का जल जमीन में रिसकर कहाँ पहुँचता है?",
     "Where does rainwater reach after seeping into the ground?",
     ["भूजल (भूमिगत जल-भंडार) में", "सीधे सूर्य में", "केवल पत्तों पर", "कहीं नहीं"],
     ["Into groundwater (the underground water-store)", "Straight into the sun", "Only on leaves", "Nowhere"],
     0,
     "रिसा हुआ जल धरती के नीचे की नम-तह में जमा होता है — कुएँ-नलकूप उसी की पाइपलाइन हैं।",
     "The seeped water collects in the moist layer beneath the earth — wells and tubewells are its pipeline."),

    ("natural-resources-conservation", "medium",
     "जल-चक्र के अंदर आने वाली प्रक्रियाओं का सही क्रम कौन-सा है?",
     "Which is the correct order of the processes that occur within the water cycle?",
     ["वाष्पीकरण → संघनन → वर्षा → प्रवाह/रिसाव", "वर्षा → वाष्पीकरण → संघनन", "संघनन → वाष्पीकरण → वर्षा", "प्रवाह → बादल → गर्मी"],
     ["Evaporation → condensation → rainfall → flow/seepage", "Rainfall → evaporation → condensation", "Condensation → evaporation → rainfall", "Flow → cloud → heat"],
     0,
     "सूरज ने खींचा, ऊपर ठंड ने भींचा, बादल फटे, जल नीचे उतरा — चक्र की सीढ़ियाँ इसी क्रम में चढ़ती-उतरती हैं।",
     "The sun drew it up, the cold above squeezed it, the clouds burst, the water descended — the cycle's stairs rise-fall in this very order."),

    ("natural-resources-conservation", "medium",
     "वर्षा-जल संचयन (rainwater harvesting) का मुख्य उद्देश्य क्या है?",
     "What is the main aim of rainwater harvesting?",
     ["बहते वर्षा-जल को रोककर भूजल का पुनर्भरण/संग्रह करना", "बारिश रोकना", "नदियाँ सुखाना", "छतों पर खेती करना"],
     ["Stopping the flowing rainwater to recharge/store groundwater", "To stop the rain", "To dry the rivers", "To farm on rooftops"],
     0,
     "जो बूँद नाली से बहकर समुद्र जाती, उसे घर के नीचे खाते में जमा करना — यही संचयन की कला।",
     "The drop that would flow down the drain to the sea — depositing it in the account beneath the home is the art of harvesting."),

    ("natural-resources-conservation", "medium",
     "किसी क्षेत्र में भूजल का अति-दोहन (overuse) होने पर सबसे पहला दृश्य परिणाम क्या दिखता है?",
     "What is the first visible result when groundwater is over-drawn in an area?",
     ["कुएँ-बोरिंग का जल-स्तर गिर जाना", "बाढ़ आना", "वर्षा दोगुनी होना", "नदियाँ फैल जाना"],
     ["The water level of wells-borings falls", "Floods arrive", "Rainfall doubles", "Rivers spread out"],
     0,
     "खाते से निकासी जमा से तेज़ — पहले ब्याज गिरता है, फिर मूल; गिरता जल-स्तर ही चेतावनी का पहला घंटा।",
     "Withdrawal from the account faster than deposit — first the interest falls, then the principal; the sinking water-level is the alarm's first bell."),

    ("natural-resources-conservation", "medium",
     "बाँध बनाने के लाभ और मूल्य — दोनों की सही पहचान वाला कथन कौन-सा है?",
     "Which statement rightly identifies both the benefit and the cost of building dams?",
     ["जल-भंडारण-सिंचाई-विद्युत का लाभ, पर विस्थापन-पारिस्थितिक-क्षति का मूल्य भी", "केवल लाभ, कोई मूल्य नहीं", "केवल मूल्य, कोई लाभ नहीं", "न लाभ न मूल्य"],
     ["The benefit of water-storage-irrigation-power, but also the cost of displacement-ecological damage", "Only benefit, no cost", "Only cost, no benefit", "Neither benefit nor cost"],
     0,
     "बाँध दोधारी औज़ार है — एक धार में फसल-बिजली, दूसरी में उजड़े गाँव-डूबे वन; सोच-समझकर चलाना ही समझदारी।",
     "A dam is a double-edged tool — one edge bears crop-electricity, the other uprooted villages-drowned forests; running it thoughtfully is the wisdom."),

    ("natural-resources-conservation", "medium",
     "वनों की अति-कटाई (deforestation) के बहुपक्षीय परिणामों में कौन-सा समूह सही है?",
     "Which group is correct among the many-sided results of deforestation?",
     ["मिट्टी-क्षरण, बाढ़-सूखा की बढ़ती आवृत्ति, वर्षा-पैटर्न का बिगड़ना, वन्य-जीव आवास का विनाश", "केवल सुंदरता में कमी", "केवल लकड़ी की कीमत बढ़ना", "कोई परिणाम नहीं"],
     ["Soil erosion, rising frequency of floods-droughts, disturbed rainfall pattern, destruction of wildlife habitat", "Only a decline in beauty", "Only a rise in timber price", "No results"],
     0,
     "पेड़ जाते हैं तो जड़ें भी जाती हैं, छाया भी, आर्द्रता भी, घर भी — कटाई का बिल कई मोर्चों पर भरता है।",
     "When trees go, the roots too go, the shade too, the moisture too, the homes too — the bill of felling is paid on many fronts."),

    ("natural-resources-conservation", "medium",
     "'वनरोपण' (afforestation) से क्या तात्पर्य है?",
     "What is meant by 'afforestation'?",
     ["कटे/बियाबान क्षेत्रों में नए पेड़ रोपकर वन फिर से खड़े करना", "पुराने जंगल काटना", "जंगल में घर बनाना", "जंगल को बेचना"],
     ["Raising forests anew by planting new trees in cut/waste areas", "Cutting old forests", "Building houses in forests", "Selling forests"],
     0,
     "जो मंज़िर गिरी, उसी जगह नई ईंट — वनरोपण ऋण चुकाने की किश्त है, प्रकृति के खाते में जमा।",
     "A new brick where the old one fell — afforestation is an instalment of debt-repayment, a deposit in nature's account."),

    ("natural-resources-conservation", "medium",
     "वन प्राकृतिक संसाधनों की सूची में 'बहु-कार्य' क्यों कहलाते हैं?",
     "Why are forests called 'multi-function' in the list of natural resources?",
     ["वर्षा-अनुकूल जलवायु, जल-रिसाव-रोक, मिट्टी-संरक्षण, वन्य-आवास, लकड़ी-ईंधन — सब एक साथ", "वे केवल लकड़ी देते हैं", "वे केवल छाया देते हैं", "वे कोई काम नहीं करते"],
     ["Rain-friendly climate, checking water-runoff, soil conservation, wildlife habitat, timber-fuel — all together", "They only give timber", "They only give shade", "They do no work"],
     0,
     "एक ही पेड़ सौ दफ़्तरों का कर्मचारी — जल, मिट्टी, जलवायु, जीव, अर्थ — हर विभाग में उसकी ड्यूटी।",
     "A single tree is the employee of a hundred offices — water, soil, climate, beings, economy — its duty lies in every department."),

    ("natural-resources-conservation", "medium",
     "मिट्टी-क्षरण (soil erosion) के प्रमुख कारणों में कौन-से गिने जाते हैं?",
     "Which are counted among the chief causes of soil erosion?",
     ["वन-निर्माण और अतिचारण", "केवल बारिश होना", "केवल हवा चलना", "केवल सर्दी पड़ना"],
     ["Deforestation and overgrazing", "Only the falling of rain", "Only the blowing of wind", "Only the onset of winter"],
     0,
     "ढकने वाली हरियाली हटी, तो बारिश-हवा ने उधेड़ना शुरू कर दिया — खुली मिट्टी ही बहती है।",
     "Once the covering greenery left, rain-wind began plucking — only uncovered soil flows away."),

    ("natural-resources-conservation", "medium",
     "मिट्टी की उर्वरता की रक्षा का सबसे स्वाभाविक तरीका क्या है?",
     "What is the most natural way of protecting soil fertility?",
     ["भूमि पर वनस्पति-आवरण बनाए रखना और अतिचारण रोकना", "मिट्टी को बोरों में भरना", "खेत कंक्रीट कर देना", "मिट्टी जलाना"],
     ["Keeping a vegetal cover on the land and stopping overgrazing", "Filling the soil in bags", "Concreting the field", "Burning the soil"],
     0,
     "जड़ें जाल बुनती हैं, पत्तियाँ चादर ओढ़ाती हैं — ढकी मिट्टी ही तैयार मिट्टी रहती है।",
     "Roots weave the net, leaves spread the sheet — only covered soil stays composed."),

    ("natural-resources-conservation", "medium",
     "जीवाश्म-ईंधन (कोयला, पेट्रोल) सीमित होने के साथ-साथ और किस दोष के साथ जुड़े हैं?",
     "Along with being limited, with what other fault are fossil fuels (coal, petrol) linked?",
     ["जलने पर वायु-प्रदूषण", "जलने पर बारिश", "जलने पर फसल", "जलने पर छाया"],
     ["Air pollution on burning", "Rain on burning", "Crop on burning", "Shade on burning"],
     0,
     "एक ही थैली में दो काँटे — भंडार खत्म होगा और जलते हुए धुआँ आज भी फेफड़ों पर चढ़ रहा है।",
     "Two thorns in one pouch — the store will end, and the burning smoke is even now climbing onto lungs."),

    ("natural-resources-conservation", "medium",
     "सौर-ऊर्जा और पवन-ऊर्जा को 'विकल्प' क्यों कहा जाता है?",
     "Why are solar energy and wind energy called 'alternatives'?",
     ["जीवाश्म-ईंधन के प्रदूषण-रहित, अखर्चनीय विकल्प के रूप में", "क्योंकि वे महँगी हैं", "क्योंकि वे रात में काम नहीं करतीं", "क्योंकि वे नई नहीं हैं"],
     ["As pollution-free, inexhaustible alternatives to fossil fuels", "Because they are costly", "Because they do not work at night", "Because they are not new"],
     0,
     "धुएँ वाली सवारी की जगह हवा-धूप की सवारी — टिकट नहीं चाहिए, सफर अनंत।",
     "In place of the smoky ride, the ride of wind-sunshine — no ticket needed, the journey endless."),

    ("natural-resources-conservation", "medium",
     "नाइट्रोजन-चक्र में वायु की नाइट्रोजन पौधों तक किस क्रम से पहुँचती है?",
     "In the nitrogen cycle, in what order does the air's nitrogen reach the plants?",
     ["वायु → स्थिरीकरण (मिट्टी/जड़ों में) → पौधे → जंतु → मृत्यु-अपघटन → वापस वायु", "वायु → सीधे जंतु → पौधे", "पौधे → वायु → मिट्टी", "मिट्टी → वायु → बादल"],
     ["Air → fixation (in soil/roots) → plants → animals → death-decay → back to air", "Air → directly animals → plants", "Plants → air → soil", "Soil → air → clouds"],
     0,
     "वायु की कड़ी नाइट्रोजन को जड़ें-मिट्टी पकड़ती हैं, पौधा भोजन बनाता है, जंतु खाते हैं, मृत शरीर गलते हैं और जीवाणु उसे फिर हवा में छोड़ देते हैं।",
     "The roots-soil catch the air's linked nitrogen, the plant makes food, animals eat, dead bodies decay and bacteria release it back to the air."),

    ("natural-resources-conservation", "medium",
     "कार्बन-चक्र में 'दहन' की भूमिका क्या है?",
     "What is the role of 'burning' in the carbon cycle?",
     ["जीवाश्म/वनों के जलने से जमा कार्बन CO₂ बनकर वायु में लौटता है", "जलने से कार्बन खत्म हो जाता है", "जलने से कार्बन बढ़ता है", "जलने का कोई संबंध नहीं"],
     ["On the burning of fossils/forests the stored carbon returns to air as CO₂", "Burning finishes carbon", "Burning increases carbon", "Burning has no relation"],
     0,
     "करोड़ों वर्ष की तिजोरी एक सदी में खोल दी — दहन कार्बन-चक्र का वह मोड़ है जहाँ जमा अचानक खर्च हो जाती है।",
     "The treasury of crores of years opened within a century — burning is that turn of the carbon cycle where the deposit is suddenly spent."),

    ("natural-resources-conservation", "medium",
     "आज जल की माँग बढ़ती ही जा रही है — इसके प्रमुख कारणों का सही समूह कौन-सा है?",
     "Today the demand for water keeps rising — which is the correct group of its chief causes?",
     ["बढ़ती जनसंख्या, औद्योगिकीकरण, फैलती कृषि", "घटती जनसंख्या", "बंद पड़े कारखाने", "कम होती खेती"],
     ["Rising population, industrialisation, spreading agriculture", "Falling population", "Closed factories", "Shrinking farming"],
     0,
     "एक-एक नागरिक, एक-एक कारखाना, एक-एक बीघा — तीनों गिनती में बढ़ते हैं और बाल्टी में से पानी घटता है।",
     "Each citizen, each factory, each acre — all three grow in count and the water falls from the bucket."),

    ("natural-resources-conservation", "hard",
     "'नवीकरणीय संसाधन अक्षय हैं, जितना चाहो खर्चो' — यह कथन कहाँ गलत है?",
     "Where is the statement 'renewable resources are inexhaustible, spend as you wish' wrong?",
     ["प्रकृति की पुनर्भरण-दर से तेज़ दोहन पर नवीकरणीय भी क्षय हो जाते हैं", "यह कथन पूरी तरह सही है", "केवल रेगिस्तान में गलत है", "केवल समुद्र में गलत है"],
     ["When drawn faster than nature's refill-rate, even renewables deplete", "The statement is fully right", "Wrong only in deserts", "Wrong only in the sea"],
     0,
     "भंडार भरता बाल्टी से, खाली होता बाल्टी से — पानी अनंत, बाल्टी नहीं; दोहन की रफ्तार ही अक्षयता तय करती है।",
     "The store refills bucket by bucket and empties bucket by bucket — the water may be endless, the bucket is not; the pace of draw alone decides inexhaustibility."),

    ("natural-resources-conservation", "hard",
     "ऊपरी मिट्टी की परत को 'सदियों की देन' क्यों कहा जाता है?",
     "Why is the topsoil layer called 'the gift of centuries'?",
     ["चट्टान-जीव-जड़ों के मिलन से यह पतली उपजाऊ परत बनने में बहुत लंबा समय लगता है, पर बहने में कुछ वर्ष", "क्योंकि वह रात में बनती है", "क्योंकि वह केवल पहाड़ों पर होती है", "क्योंकि उसमें सोना होता है"],
     ["This thin fertile layer takes very long to form from the meeting of rock-beings-roots, but washes away in a few years", "Because it forms at night", "Because it occurs only on mountains", "Because it contains gold"],
     0,
     "एक मुट्ठी उपजाऊ मिट्टी के पीछे सैकड़ों बरसों की भूमिका — और एक बाढ़ में सारा लेखा मिट जाना; इसीलिए इसे 'दुर्लभ पूँजी' कहना अत्युक्ति नहीं।",
     "Behind one fistful of fertile soil lie hundreds of years of groundwork — and one flood can wipe the whole account; calling it 'rare capital' is no exaggeration."),

    ("natural-resources-conservation", "hard",
     "'सतत विकास' (sustainable development) की मूल शर्त पीढ़ियों के बीच क्या तय करती है?",
     "What does the basic condition of 'sustainable development' decide between generations?",
     ["आज का उपयोग ऐसा हो कि आने वाली पीढ़ियों का हक भी बचा रहे", "आज सब खपा लेना, कल देखा जाएगा", "कल की पीढ़ी अपना इंतज़ाम करे", "संसाधन सिर्फ अमीरों के लिए"],
     ["Today's use should be such that the right of coming generations too remains saved", "Consume all today, tomorrow will be seen", "Let tomorrow's generation arrange its own", "Resources only for the rich"],
     0,
     "संसाधन पीढ़ी-दर-पीढ़ी चलने वाली विरासत है — सततता का अर्थ है बंटवारे में आने वाले मेहमानों की थाली भी पहले से रख देना।",
     "Resources are a heritage passing generation to generation — sustainability means setting the plate of the guests-to-come in the division beforehand."),

    # ================= POLLUTION / WASTE / SUSTAINABILITY — 35 (E12/M20/H3) =================
    ("pollution-waste-sustainability", "easy",
     "'प्रदूषण' किसे कहते हैं?",
     "What is called 'pollution'?",
     ["पर्यावरण में अवांछित पदार्थों का मिलकर उसे जीवों के लिए हानिकारक बना देना", "पर्यावरण की सफाई", "पेड़ लगाना", "जल इकट्ठा करना"],
     ["The mixing of unwanted substances into the environment making it harmful for beings", "The cleaning of the environment", "Planting trees", "Collecting water"],
     0,
     "जो अपनी जगह नहीं और जितनी मात्रा में नहीं होना चाहिए — पर्यावरण में घुसा वही प्रदूषक।",
     "What is not in its place and not in the amount it should be — that intruder in the environment is the pollutant."),

    ("pollution-waste-sustainability", "easy",
     "जल-प्रदूषण के सामान्य स्रोतों में कौन-से गिने जाते हैं?",
     "Which are counted among the common sources of water pollution?",
     ["घरेलू सीवेज, उद्योग-अपशिष्ट, खाद-कीटनाशक की बहाव", "केवल बारिश", "केवल नदी की गति", "केवल सूरज की रोशनी"],
     ["Domestic sewage, industrial waste, the runoff of fertiliser-pesticide", "Only rain", "Only the river's flow", "Only the sun's light"],
     0,
     "शहर का गंदा जल, कारखाने का जहरीला बहाव और खेतों का रासायनिक बहाव — तीनों मिलकर जल-शरीर बिगाड़ते हैं।",
     "The city's dirty water, the factory's poisonous discharge and the fields' chemical runoff — all three together spoil the water-body."),

    ("pollution-waste-sustainability", "easy",
     "शोर से होने वाले प्रदूषण का नाम क्या है?",
     "What is the name of the pollution caused by loud sound?",
     ["ध्वनि-प्रदूषण", "जल-प्रदूषण", "मृदा-प्रदूषण", "तापीय-प्रदूषण"],
     ["Noise pollution", "Water pollution", "Soil pollution", "Thermal pollution"],
     0,
     "कान की सीमा से ऊपर का शोर भी एक प्रदूषक है — नींद, सुनना और मन तीनों पर भारी।",
     "Sound above the ear's limit too is a pollutant — heavy on sleep, hearing and mind alike."),

    ("pollution-waste-sustainability", "easy",
     "'ग्रीनहाउस गैसों' में कौन-सी गैस प्रमुखतः गिनी जाती है?",
     "Which gas is chiefly counted among the 'greenhouse gases'?",
     ["कार्बन डाइऑक्साइड", "ऑक्सीजन", "नाइट्रोजन", "हीलियम"],
     ["Carbon dioxide", "Oxygen", "Nitrogen", "Helium"],
     0,
     "जले ईंधन की CO₂ और दूसरी गैसें वायु में गर्मी-जकड़ा चादर बुनती हैं — यही ग्रीनहाउस-परत।",
     "The burnt fuel's CO₂ and other gases weave a heat-trapping sheet in the air — this very greenhouse-layer."),

    ("pollution-waste-sustainability", "easy",
     "वैश्विक तापन (global warming) से जुड़ा मुख्य कारण क्या माना जाता है?",
     "What is considered the main cause linked with global warming?",
     ["वायुमंडल में ग्रीनहाउस गैसों (जैसे CO₂) का बढ़ना", "ऑक्सीजन का बढ़ना", "वर्षा का घटना", "हवा का तेज़ चलना"],
     ["The rise of greenhouse gases (like CO₂) in the atmosphere", "The rise of oxygen", "The fall of rainfall", "The blowing of fast wind"],
     0,
     "जितनी मोटी गर्म-चादर, उतना ज्यादा भीतर की गर्मी — CO₂ का ढेर धरती की बुखार की चादर है।",
     "The thicker the warm sheet, the more the heat inside — the pile of CO₂ is the sheet of the earth's fever."),

    ("pollution-waste-sustainability", "easy",
     "ओजोन-परत का प्राकृतिक कार्य क्या है?",
     "What is the natural function of the ozone layer?",
     ["सूर्य की हानिकारक पराबैंगनी किरणों को रोकना", "वर्षा बरसाना", "हवा चलाना", "भूकंप रोकना"],
     ["To block the sun's harmful ultraviolet rays", "To cause rainfall", "To blow the wind", "To stop earthquakes"],
     0,
     "सांस के लिए ओजोन नहीं चाहिए, पर सूरज की तेज़-किरण की छाता वही परत तानती है — आसमान का सनस्क्रीन।",
     "Ozone is not needed for breath, yet that very layer spreads the umbrella against the sun's fierce rays — the sky's sunscreen."),

    ("pollution-waste-sustainability", "easy",
     "ओजोन-परत को नुकसान पहुँचाने वाले रसायन किस नाम से जाने जाते हैं?",
     "By what name are the chemicals that damage the ozone layer known?",
     ["CFC (क्लोरोफ्लोरोकार्बन)", "ऑक्सीजन", "नाइट्रोजन", "जलवाष्प"],
     ["CFCs (chlorofluorocarbons)", "Oxygen", "Nitrogen", "Water vapour"],
     0,
     "रेफ्रिजरेटर-एसी-स्प्रे में छुपे CFC ऊपर चढ़कर ओजोन की ढाल पर छेद करते हैं।",
     "CFCs hidden in refrigerators-ACs-sprays climb up and bore holes in the ozone shield."),

    ("pollution-waste-sustainability", "easy",
     "'जैव-अपघटनीय' (biodegradable) पदार्थ किसे कहते हैं?",
     "What are called 'biodegradable' materials?",
     ["जिन्हें सूक्ष्मजीव गलाकर सरल पदार्थों में बदल सकते हैं", "जो कभी नहीं गलते", "जो केवल पिघलते हैं", "जो केवल जलते हैं"],
     ["Those that microbes can decay and convert into simple substances", "Those that never decay", "Those that only melt", "Those that only burn"],
     0,
     "सब्जी-छिलका, कागज, कपड़ा — प्रकृति की रसोई में पच जाने वाली चीज़ें।",
     "Vegetable-peel, paper, cloth — things that digest in nature's kitchen."),

    ("pollution-waste-sustainability", "easy",
     "'अजैव-अपघटनीय' (non-biodegradable) किसे कहते हैं?",
     "What are called 'non-biodegradable'?",
     ["जिन्हें सूक्ष्मजीव नहीं गला सकते — जैसे प्लास्टिक", "जो एक दिन में गल जाते हैं", "जो खाने योग्य हैं", "जो पानी में घुल जाते हैं"],
     ["Those that microbes cannot decay — like plastic", "Those that decay in a day", "Those that are edible", "Those that dissolve in water"],
     0,
     "प्रकृति के पाचक-रस से अछूते ये पदार्थ सदियों जमे रहते हैं — मिट्टी-जल की बेडी पर।",
     "Untouched by nature's digestive juices, these materials lie piled for ages — on the bed of soil-water."),

    ("pollution-waste-sustainability", "easy",
     "प्लास्टिक की थैली किस श्रेणी में आती है?",
     "In which category does the plastic bag fall?",
     ["अजैव-अपघटनीय", "जैव-अपघटनीय", "उर्वरक", "जैव-ईंधन"],
     ["Non-biodegradable", "Biodegradable", "A fertiliser", "A biofuel"],
     0,
     "प्लास्टिक को गलाने वाला जीवाणु प्रकृति में नहीं — थैली सड़ती नहीं, सदियों जमा रहती है।",
     "No plastic-decaying bacterium exists in nature — the bag does not rot, it stays piled for ages."),

    ("pollution-waste-sustainability", "easy",
     "सब्जी के छिलके और गीले कचरे को किस श्रेणी में रखा जाता है?",
     "In which category are vegetable peels and wet waste placed?",
     ["जैव-अपघटनीय", "अजैव-अपघटनीय", "रेडियोधर्मी", "इलेक्ट्रॉनिक कचरा"],
     ["Biodegradable", "Non-biodegradable", "Radioactive", "Electronic waste"],
     0,
     "गीला-जैविक कचरा शीघ्र गलकर खाद का कच्चा माल बनता है — प्रकृति की रसोई का राशन।",
     "Wet-organic waste soon decays into raw material of compost — the ration of nature's kitchen."),

    ("pollution-waste-sustainability", "easy",
     "धुएँ और कोहरे के मिले रूप को क्या कहते हैं?",
     "What is the combined form of smoke and fog called?",
     ["धुंध (स्मॉग)", "ओजोन", "अम्ल-वर्षा", "साइक्लोन"],
     ["Smog", "Ozone", "Acid rain", "A cyclone"],
     0,
     "smoke + fog = smog — सर्दियों के शहर में जहरीली धुंध की दीवार यही बनती है।",
     "smoke + fog = smog — the wall of poisonous haze in the winter city is formed of this very thing."),

    ("pollution-waste-sustainability", "medium",
     "वाहनों और कारखानों की गैसों से बनी 'अम्ल-वर्षा' का कारण-युग्म क्या है?",
     "What is the cause-pair of 'acid rain' formed from the gases of vehicles and factories?",
     ["सल्फर और नाइट्रोजन के ऑक्साइड हवा में घुलकर बारिश के पानी को अम्लीय बनाना", "ऑक्सीजन और हीलियम", "नाइट्रोजन और आर्गन", "जलवाष्प और धूल"],
     ["Oxides of sulphur and nitrogen dissolving in air and turning rainwater acidic", "Oxygen and helium", "Nitrogen and argon", "Water vapour and dust"],
     0,
     "चिमनी-नली की गैसें बादल के पानी में घुलकर उसे खट्टा कर देती हैं — वही अम्लीय बूँदें फसल-इमारत-जल को खाती हैं।",
     "The chimney-pipe gases dissolve into the cloud's water and sour it — those very acidic drops eat into crop-building-water."),

    ("pollution-waste-sustainability", "medium",
     "कार्बन मोनोऑक्साइड (CO) घातक क्यों है?",
     "Why is carbon monoxide (CO) deadly?",
     ["वह रुधिर में ऑक्सीजन की जगह जकड़ लेता है — शरीर को ऑक्सीजन नहीं मिल पाता", "वह दिखता ही नहीं", "वह बहुत भारी है", "वह आवाज़ निकालता है"],
     ["It grips oxygen's place in the blood — the body cannot get oxygen", "It is invisible", "It is very heavy", "It makes noise"],
     0,
     "CO रुधिर की ऑक्सीजन-कुर्सी पर चुपचाप बैठ जाता है — कमरे भर ऑक्सीजन हो, फिर भी शरीर भूखा।",
     "CO silently occupies the oxygen-chair of the blood — the room may be full of oxygen, yet the body starves."),

    ("pollution-waste-sustainability", "medium",
     "खेतों की अतिरिक्त खाद नदी-तालाब में बहने पर जल-जीवन पर क्या आफत आती है?",
     "What calamity befalls aquatic life when excess fertiliser from fields flows into a river-pond?",
     ["शैवाल की तेज बाढ़ जल की घुली ऑक्सीजन खा जाती है — मछलियाँ दम तोड़ती हैं", "जल मीठा हो जाता है", "मछलियाँ दोगुनी हो जाती हैं", "कुछ नहीं होता"],
     ["A fast bloom of algae eats the water's dissolved oxygen — fish suffocate", "The water turns sweet", "The fish double", "Nothing happens"],
     0,
     "खाद की दावत पाकर शैवाल दबोच लेते हैं पूरा जल-घर — ऑक्सीजन की मोहलत खत्म, जल-जीव ठिठक जाते हैं।",
     "Feasting on the fertiliser, the algae seize the whole water-house — oxygen's lease ends, the aquatic beings fall still."),

    ("pollution-waste-sustainability", "medium",
     "ग्रीनहाउस-प्रभाव की कार्यप्रणाली क्या है?",
     "What is the working mechanism of the greenhouse effect?",
     ["गैसें वायुमंडल में ऐसा आवरण बनाती हैं जो धरती की गर्मी को बाहर जाने से रोक देता है", "गैसें धूप को रोकती हैं", "गैसें बारिश बंद करती हैं", "गैसें हवा खा जाती हैं"],
     ["The gases form a cover in the atmosphere that stops the earth's heat from going out", "The gases stop the sunshine", "The gases stop the rain", "The gases eat the air"],
     0,
     "शीशे के ग्रीनहाउस की तरह — धूप भीतर, गर्मी भीतर ही जकड़ी; गैस-चादर जितनी मोटी, भीतर उतना तपा।",
     "Like a glass greenhouse — sunshine within, the heat held within; the thicker the gas-sheet, the hotter inside."),

    ("pollution-waste-sustainability", "medium",
     "वैश्विक तापन के चलते हिम-ढलानों के पिघलने का सीधा परिणाम क्या देखा जाता है?",
     "What direct result of the melting of glaciers under global warming is seen?",
     ["समुद्र-स्तर का धीरे-धीरे बढ़ना — तटीय बस्तियों पर खतरा", "समुद्र का सूखना", "नदियों का खारा होना", "वर्षा का पूरी तरह बंद होना"],
     ["The slow rise of sea level — danger to coastal settlements", "The drying of the sea", "The turning of rivers salty", "The total stop of rain"],
     0,
     "पहाड़ों की बर्फ-बचत पिघलकर सागर में गिरती है — सागर की धारा चढ़ती है और किनारों की साँस ऊपर।",
     "The snow-savings of mountains melt and drop into the sea — the sea's level climbs and the coasts' breath rises."),

    ("pollution-waste-sustainability", "medium",
     "ओजोन-छिद्र से बढ़ती पराबैंगनी किरणें मनुष्य के लिए खतरा क्यों?",
     "Why are the rising ultraviolet rays from the ozone hole a danger for humans?",
     ["अधिक UV त्वचा-आँखों के लिए हानिकारक", "UV से भूख लगती है", "UV से बाल काले होते हैं", "UV से नींद आती है"],
     ["Excess UV is harmful for the skin-eyes", "UV brings hunger", "UV turns hair black", "UV brings sleep"],
     0,
     "आसमान की छाता पतली पड़ी तो तेज़ किरण सीधे त्वचा पर — सुरक्षा-परत का छेद स्वास्थ्य का जोखिम।",
     "As the sky's umbrella thins, the fierce rays fall straight on the skin — a hole in the shield is a risk to health."),

    ("pollution-waste-sustainability", "medium",
     "घरेलू कचरे को 'गीले' और 'सूखे' में अलग करने (segregation) का लाभ क्या है?",
     "What is the benefit of separating household waste into 'wet' and 'dry' (segregation)?",
     ["गीला खाद बनाने, सूखा रीसाइकिल करने के लिए सीधा चला जाता है", "कचरा दोगुना हो जाता है", "गंध बढ़ती है", "कोई लाभ नहीं"],
     ["The wet goes straight to composting, the dry to recycling", "The waste doubles", "The smell rises", "No benefit"],
     0,
     "स्रोत पर अलग की हुई कचरा ही कारखाने के काम की — मिलीजुली कचरा न खाद बनती है न रीसाइकिल।",
     "Only waste separated at the source is fit for the factory's work — mixed waste becomes neither compost nor recycle."),

    ("pollution-waste-sustainability", "medium",
     "पुनर्चक्रण (recycling) के लिए सर्वाधिक उपयुक्त सामान्य पदार्थ कौन-से हैं?",
     "Which common materials are most suitable for recycling?",
     ["काँच, कागज, धातु (जैसे एल्युमिनियम)", "प्रयुक्त टीके की शीशियाँ", "जला हुआ प्लास्टिक", "गीला कचरा"],
     ["Glass, paper, metals (like aluminium)", "Used vaccine vials", "Burnt plastic", "Wet waste"],
     0,
     "काँच-धातु पिघलकर बार-बार नए बर्तन बनते हैं, कागज़ गूँथकर नया कागज़ — यही रीसाइकिल के सिपाही।",
     "Glass-metal melt into new vessels again and again, paper is kneaded into new paper — these are the soldiers of recycling."),

    ("pollution-waste-sustainability", "medium",
     "जैविक कचरे से 'कंपोस्ट' बनाने की प्रक्रिया में मुख्य कर्ता कौन है?",
     "Who is the main agent in the process of making 'compost' from organic waste?",
     ["अपघटक सूक्ष्मजीव जो गीले कचरे को गलाकर खाद बनाते हैं", "धूप", "हवा ही पर्याप्त", "प्लास्टिक की थैली"],
     ["Decomposer microbes that decay the wet waste into manure", "Sunshine", "Air alone suffices", "A plastic bag"],
     0,
     "कूड़े के ढेर में अपघटकों की मेहनत — कच्चा गीला कचरा पक जाता है काली-भूरी उर्वर खाद।",
     "The labour of decomposers in the waste-heap — the raw wet waste ripens into black-brown fertile manure."),

    ("pollution-waste-sustainability", "medium",
     "कचरा-भराव (landfill) स्थलों की प्रमुख समस्या क्या होती है?",
     "What remains the major problem of landfill sites?",
     ["जमीन-जल का रिसाव-दूषण और मिथेन-गैस-दुर्गंध जैसे दीर्घकालिक दोष", "वहाँ खेल का मैदान बनता है", "वहाँ फसल उगती है", "वहाँ कोई दोष नहीं"],
     ["Long-term faults like seepage-pollution of ground-water and methane-gas-odour", "A playground forms there", "A crop grows there", "No fault there"],
     0,
     "ढेर के नीचे से रिसता जहरीला रस और उठती गैस — भराव का बिल आस-पास की धरती-जल सालों तक चुकाती है।",
     "The poisonous juice seeping from under the heap and the rising gas — the surrounding soil-water pays the landfill's bill for years."),

    ("pollution-waste-sustainability", "medium",
     "3R का सही अर्थ-क्रम क्या है?",
     "What is the correct meaning-order of the 3Rs?",
     ["Reduce (घटाओ) → Reuse (दोबारा इस्तेमाल) → Recycle (पुनर्चक्रित करो)", "Recycle → Reject → Reply", "Repair → Rent → Repeat", "तीनों एक ही बात हैं"],
     ["Reduce → Reuse → Recycle", "Recycle → Reject → Reply", "Repair → Rent → Repeat", "All three mean the same"],
     0,
     "पहले कचरा होने से बचो, फिर जो हुआ उसे दोबारा चलाओ, तब बचे तो रीसाइकिल — क्रम भी वैज्ञानिक है।",
     "First avoid the waste, then run what happened once more, only if still left recycle — the order too is scientific."),

    ("pollution-waste-sustainability", "medium",
     "'Reduce' का व्यावहारिक उदाहरण कौन-सा है?",
     "Which is a practical example of 'Reduce'?",
     ["खरीदारी पर थैली लेने से मना करना", "थैली जला देना", "थैली नदी में बहा देना", "थैलियाँ इकट्ठी करना"],
     ["Refusing to take a bag on shopping", "Burning the bag", "Flowing the bag into a river", "Hoarding bags"],
     0,
     "जो पैदा ही नहीं हुआ, उसका निपटान सवाल ही नहीं — इनकार सबसे पहली और सबसे सस्ती सीढ़ी।",
     "What was never produced has no disposal question — refusal is the first and cheapest stair."),

    ("pollution-waste-sustainability", "medium",
     "'Reuse' और 'Recycle' का अंतर स्पष्ट करने वाला युग्म कौन-सा है?",
     "Which pair makes the difference between 'Reuse' and 'Recycle' clear?",
     ["काँच की बोतल दोबारा भरकर इस्तेमाल = reuse; वही बोतल तोड़कर पिघलाना = recycle", "दोनों एक ही हैं", "reuse = जलाना", "recycle = फेंकना"],
     ["Refilling and using a glass bottle again = reuse; breaking and melting the same bottle = recycle", "Both are the same", "Reuse = burning", "Recycle = throwing"],
     0,
     "दोबारा इस्तेमाल वस्तु को वैसे ही चलाना है; रीसाइकिल उसे तोड़कर नए रूप में ढालना — एक मरम्मत, दूसरा पुनर्जन्म।",
     "Reuse runs the object as it is; recycle breaks and recasts it into a new form — one is repair, the other rebirth."),

    ("pollution-waste-sustainability", "medium",
     "प्लास्टिक पर्यावरण के लिए विशेष सिरदर्द क्यों बना है?",
     "Why has plastic become a special headache for the environment?",
     ["वह सदियों तक नहीं गलता, जल-निकास जाम करता है, जल-जीवों को घेरता है और जलने पर जहर छोड़ता है", "वह बहुत सस्ता है", "वह बहुत हल्का है", "वह रंगीन होता है"],
     ["It does not decay for ages, chokes drains, entraps aquatic life and releases poison on burning", "It is very cheap", "It is very light", "It is colourful"],
     0,
     "न गलने वाली चीज़ जितनी उपयोगी, उतनी ही हठी — इस्तेमाल की सुविधा निपटान के सिरदर्द में बदल जाती है।",
     "A thing that will not decay is as stubborn as it is useful — the convenience of use turns into the headache of disposal."),

    ("pollution-waste-sustainability", "medium",
     "घरों-नगरों का सीवेज नदी में बिना उपचार सीधा नहीं छोड़ा जाना चाहिए — मुख्य कारण?",
     "Why should the sewage of homes-cities not be released straight into a river without treatment?",
     ["उसमें घुले हानिकारक पदार्थ-रोगाणु जल-जीवन और नदी-तट आबादी दोनों बिगाड़ते हैं", "नदी को जल नहीं चाहिए", "सीवेज में सोना होता है", "नदियाँ गंदगी पसंद करती हैं"],
     ["The harmful matter-germs dissolved in it spoil both aquatic life and the river-bank population", "The river needs no water", "Sewage contains gold", "Rivers like dirt"],
     0,
     "एक नगर का गंदा जल पूरी नदी की धारा बदल देता है — उपचार-द्वार पार करके ही उसे नदी तक जाना चाहिए।",
     "One city's dirty water can change a whole river's current — it must pass the treatment-gate before reaching the river."),

        ("pollution-waste-sustainability", "medium",
     "पराली (फसल-अवशेष) जलाने से होने वाली समस्या किस प्रकार की है?",
     "The problem from burning stubble (crop-residue) is of which type?",
     ["वायु-प्रदूषण — धुएँ की चादर क्षेत्र से आगे शहरों तक फैलती है", "जल-प्रदूषण", "शोर-प्रदूषण", "कोई समस्या नहीं"],
     ["Air pollution — the sheet of smoke spreads from the region to the cities beyond", "Water pollution", "Noise pollution", "No problem"],
     0,
     "खेत की सफाई का आग का रास्ता शहर की साँस पर भारी — जलाना नहीं, वापस मिट्टी में मिलाना ही उपाय।",
     "Fire's road of field-cleaning weighs heavy on the city's breath — not burning but mixing back into the soil is the remedy."),

        ("pollution-waste-sustainability", "medium",
     "जल-प्रदूषण का सीधा प्रभाव जलीय-जीवों पर क्यों गहरा पड़ता है?",
     "Why does water pollution's direct impact fall deep on aquatic organisms?",
     ["उनका पूरा घर-श्वास-भोजन उसी जल में डूबा है — बचने का कोई दूसरा घर नहीं", "वे जमीन पर रह सकते हैं", "उन्हें प्रदूषण पसंद है", "वे उड़ जाते हैं"],
     ["Their whole home-breath-food is sunk in that very water — no second house to escape to", "They can live on land", "They like pollution", "They fly away"],
     0,
     "मछली का घर जल ही है — घर ही जहर हो जाए तो प्रवास नहीं, मृत्यु बचती है।",
     "The fish's home is the water itself — when the home turns poison, no migration remains, only death."),

    ("pollution-waste-sustainability", "medium",
     "मृदा-प्रदूषण के सामान्य कारणों में कौन-सा समूह सही है?",
     "Which group is correct among the common causes of soil pollution?",
     ["प्लास्टिक-कचरा, कीटनाशियों-खादों का अत्यधिक प्रयोग, ठोस अपशिष्ट का ढेर", "केवल वर्षा", "केवल हवा", "केवल धूप"],
     ["Plastic-waste, excessive use of pesticides-fertilisers, heaps of solid waste", "Only rainfall", "Only wind", "Only sunshine"],
     0,
     "जो जमीन पर गिरा वह जमीन में उतरा — मिट्टी का शरीर भी अपनी सीमा से ज्यादा जहर नहीं झेलता।",
     "What fell on the ground sank into it — even the soil's body cannot bear poison beyond its limit."),

    ("pollution-waste-sustainability", "medium",
     "'पर्यावरण-मित्र' जीवन-शैली का पहचान-चिह्न क्या है?",
     "What is the identifying mark of an 'eco-friendly' lifestyle?",
     ["कम खर्च, दोबारा उपयोग, जैविक पसंद, कचरे का अलग-अलग निपटान", "ज्यादा खर्च, ज्यादा फेंकना", "एक बार उपयोग की हर चीज़", "जलाना-बहाना ही उपाय"],
     ["Less spending, reuse, organic choice, separate disposal of waste", "More spending, more throwing", "Single-use everything", "Burning-flowing as the only remedy"],
     0,
     "हल्का पदचाप — पृथ्वी पर जितना कम बोझ, जीवन-शैली उतनी पर्यावरण-मित्र।",
     "A light footfall — the less the load on the earth, the more eco-friendly the lifestyle."),

    ("pollution-waste-sustainability", "medium",
     "गाँव-शहर के 'हरित-पट्टी' (green belt) बनाने का प्रदूषण-लाभ क्या है?",
     "What is the pollution-benefit of creating 'green belts' in villages-cities?",
     ["पेड़ धूल-धुएँ-शोर तीनों को छानने-सोखने-काटने में सहायक", "पेड़ प्रदूषण बढ़ाते हैं", "पेड़ केवल लकड़ी देते हैं", "कोई लाभ नहीं"],
     ["Trees help filter-absorb-cut dust, smoke and noise — all three", "Trees raise pollution", "Trees only give timber", "No benefit"],
     0,
     "पेड़ों की दीवार शहर की साँस की छलनी — हरियाली की पट्टी सस्ती और सुंदर शुद्धि-मशीन।",
     "The wall of trees is the sieve of the city's breath — a belt of green is a cheap and beautiful purification-machine."),

    ("pollution-waste-sustainability", "hard",
     "यदि ओजोन-परत पूरी गायब हो जाए, तो धरती पर जीवन की स्थिति की सोच-परीक्षा क्या बताती है?",
     "If the ozone layer vanished entirely, what does the thought-experiment of life's condition on earth tell?",
     ["तीव्र UV बौछार जीवों की त्वचा-आँख-डीएनए पर सीधा प्रहार — जमीनी जीव के लिए अस्तित्व कठिन", "कुछ भी नहीं बदलता", "रातें ठंडी हो जाती हैं", "वर्षा दोगुनी हो जाती है"],
     ["A fierce UV shower strikes the skin-eyes-DNA of beings straight — existence turns difficult for ground-life", "Nothing changes", "Nights turn cold", "Rainfall doubles"],
     0,
     "आसमान की सनस्क्रीन उतर जाए तो तेज़ किरणों का सीधा दौर — इसीलिए परत की एक-एक बूँद की रक्षा जरूरी।",
     "If the sky's sunscreen descends, a direct barrage of fierce rays — hence the defence of every drop of the layer matters."),

    ("pollution-waste-sustainability", "hard",
     "'ग्रीनहाउस-प्रभाव बुरा है' — इस कथन में क्या भूल छिपी है?",
     "What mistake lies hidden in the statement 'the greenhouse effect is bad'?",
     ["प्राकृतिक मात्रा में यह प्रभाव धरती को रहने योग्य गर्म रखता है — बुरा है उसका अति-बढ़ना", "कथन पूरी तरह सही है", "ग्रीनहाउस-प्रभाव होता ही नहीं", "यह केवल शुक्र ग्रह पर होता है"],
     ["In natural measure this effect keeps the earth livably warm — what is bad is its excess rise", "The statement is fully right", "The greenhouse effect does not occur", "It occurs only on Venus"],
     0,
     "बुखार बुरा है, पर शरीर का स्वाभाविक ताप जीवन की शर्त है — गर्म-चादर चाहिए भी, बस नाप में।",
     "Fever is bad, but the body's natural warmth is life's condition — the warm sheet is needed too, only in measure."),

    ("pollution-waste-sustainability", "hard",
     "पुराने मोबाइल-कंप्यूटर का 'ई-कचरा' साधारण कचरे से अधिक खतरनाक क्यों गिना जाता है?",
     "Why is the 'e-waste' of old mobiles-computers counted as more dangerous than ordinary waste?",
     ["उसमें सीसा-पारा जैसी भारी विषधातुएँ जड़े हैं जो रिसकर मिट्टी-जल में बैठ जाती हैं", "वह बहुत बड़ा होता है", "वह रंगीन होता है", "वह जल्दी गल जाता है"],
     ["Heavy toxic metals like lead-mercury are seated in it, which seep and settle into soil-water", "It is very big", "It is colourful", "It decays quickly"],
     0,
     "साधारण कूड़ा गलता है पर ई-कचरा टपकता है — धातु-जहर की बूँदें सालों तक जमीन की नसों में उतरती रहती हैं; इसीलिए उसका पृथक्-निपटान विशेष जरूरी।",
     "Ordinary waste rots but e-waste drips — drops of metal-venom keep descending into the ground's veins for years; hence its separate disposal is specially necessary."),
]
