# -*- coding: utf-8 -*-
"""C01 part 2 — Matter & Its States (chemistry chapter-01).
T3 changes-of-state (E20/M21/H9) + T4 evaporation-and-cooling (E20/M22/H8).
Tuple: (topic, difficulty, q_hi, q_en, opts_hi[4], opts_en[4], correct_idx=0, expl_hi, expl_en)
All authored with correct_idx 0; answer-position rotation happens in gen script.
State-change names/directions and sublimation examples (naphthalene, camphor) are
straight from chapter-01 meta. Framings avoid P06's heat-side stems — C01 reasons
from the matter/particle side.
"""

PART2 = [
    # ================= CHANGES OF STATE (50) =================
    # ---- easy (20) ----
    ("changes-of-state", "easy",
     "एक ही पदार्थ का ठोस से द्रव या द्रव से गैस बनने जैसा परिवर्तन क्या कहलाता है?",
     "What is a change like the same substance turning from solid to liquid or liquid to gas called?",
     ["अवस्था परिवर्तन", "विसरण", "संपीडन", "वायु दाब"],
     ["A change of state", "Diffusion", "Compression", "Air pressure"],
     0,
     "पदार्थ वही रहता है, केवल उसकी अवस्था बदलती है — यही अवस्था परिवर्तन है।",
     "The substance remains the same; only its state changes — that is a change of state."),

    ("changes-of-state", "easy",
     "ठोस के द्रव में बदलने की प्रक्रिया का नाम क्या है?",
     "What is the name of the process of a solid turning into a liquid?",
     ["पिघलन", "जमन", "संघनन", "उर्ध्वपातन"],
     ["Melting", "Freezing", "Condensation", "Sublimation"],
     0,
     "बर्फ का पानी बनना — पिघलन का जीवंत उदाहरण।",
     "Ice becoming water — a living example of melting."),

    ("changes-of-state", "easy",
     "द्रव के ठोस में बदलने की क्रिया क्या कहलाती है?",
     "What is the process of a liquid turning into a solid called?",
     ["जमन (हिमायन)", "पिघलन", "क्वथन", "वाष्पीकरण"],
     ["Freezing", "Melting", "Boiling", "Evaporation"],
     0,
     "पानी का बर्फ बनना — जमन।",
     "Water becoming ice — freezing."),

    ("changes-of-state", "easy",
     "गैस के द्रव में बदलने की प्रक्रिया का नाम बताइए:",
     "State the name of the process of a gas turning into a liquid:",
     ["संघनन", "पिघलन", "उर्ध्वपातन", "क्वथन"],
     ["Condensation", "Melting", "Sublimation", "Boiling"],
     0,
     "भाप का पानी बनना — संघनन।",
     "Steam becoming water — condensation."),

    ("changes-of-state", "easy",
     "द्रव के गैस (भाप) में बदलने की तीव्र प्रक्रिया जो पूरे द्रव में होती है, क्या कहलाती है?",
     "What is the vigorous process of a liquid turning into gas (vapour) throughout the whole liquid called?",
     ["क्वथन", "जमन", "संघनन", "पिघलन"],
     ["Boiling", "Freezing", "Condensation", "Melting"],
     0,
     "पूरे पानी में बुलबुलों के साथ भाप बनना — क्वथन।",
     "Vapour forming with bubbles throughout the water — boiling."),

    ("changes-of-state", "easy",
     "उर्ध्वपातन में ठोस किस अवस्था में बदलता है?",
     "In sublimation, into what does a solid change?",
     ["सीधे गैस में", "पहले द्रव, फिर गैस में", "केवल द्रव में", "किसी अवस्था में नहीं"],
     ["Directly into gas", "First into liquid, then gas", "Only into liquid", "Into no state"],
     0,
     "उर्ध्वपातन = ठोस → गैस, बिना द्रव बने।",
     "Sublimation = solid → gas without becoming liquid."),

    ("changes-of-state", "easy",
     "उर्ध्वपातन का सामान्य घरेलू उदाहरण कौन-सा है?",
     "Which is a common household example of sublimation?",
     ["नैफ्थलीन की गोलियाँ", "पानी की बर्फ", "लोहे की कील", "नमक का घोल"],
     ["Naphthalene balls", "Ice of water", "An iron nail", "A salt solution"],
     0,
     "नैफ्थलीन द्रव बने बिना सीधे गैस बनती है — धीरे-धीरे गोली गायब।",
     "Naphthalene turns straight into gas without liquefying — the ball slowly vanishes."),

    ("changes-of-state", "easy",
     "कपूर की गोली छोड़ने पर महीनों में बिना गीली हुए गायब हो जाती है। यह कौन-सी प्रक्रिया है?",
     "A camphor tablet left aside disappears in months without getting wet. Which process is this?",
     ["उर्ध्वपातन", "पिघलन", "संघनन", "जमन"],
     ["Sublimation", "Melting", "Condensation", "Freezing"],
     0,
     "ठोस कपूर सीधे गैस बनती है — उर्ध्वपातन।",
     "Solid camphor turns directly into gas — sublimation."),

    ("changes-of-state", "easy",
     "बर्फ का पानी बनना और पानी का भाप बनना — इन क्रमशः परिवर्तनों के नाम हैं:",
     "Ice turning into water and water turning into steam — the names of these changes respectively are:",
     ["पिघलन और क्वथन", "जमन और संघनन", "संघनन और पिघलन", "उर्ध्वपातन और जमन"],
     ["Melting and boiling", "Freezing and condensation", "Condensation and melting", "Sublimation and freezing"],
     0,
     "बर्फ → पानी = पिघलन; पानी → भाप = क्वथन।",
     "Ice → water = melting; water → steam = boiling."),

    ("changes-of-state", "easy",
     "भाप का पानी और पानी का बर्फ बनना — दोनों क्रियाओं के नाम क्रमशः हैं:",
     "Steam becoming water and water becoming ice — the names of the two processes respectively are:",
     ["संघनन और जमन", "पिघलन और क्वथन", "क्वथन और संघनन", "उर्ध्वपातन और पिघलन"],
     ["Condensation and freezing", "Melting and boiling", "Boiling and condensation", "Sublimation and melting"],
     0,
     "गैस → द्रव संघनन; द्रव → ठोस जमन।",
     "Gas → liquid condensation; liquid → solid freezing."),

    ("changes-of-state", "easy",
     "गर्मी में घी की डिब्बी में रखा घी द्रव बन जाता है और सर्दी में फिर ठोस। ये दोनों क्रमशः क्या हैं?",
     "In summer the ghee in a tin becomes liquid and in winter it turns solid again. What are these two respectively?",
     ["पिघलन और जमन", "जमन और पिघलन", "क्वथन और संघनन", "उर्ध्वपातन और क्वथन"],
     ["Melting and freezing", "Freezing and melting", "Boiling and condensation", "Sublimation and boiling"],
     0,
     "मौसम के साथ घी पिघलता-जमता है — अवस्था परिवर्तन का रोज़ का नमूना।",
     "Ghee melts and freezes with the season — an everyday sample of change of state."),

    ("changes-of-state", "easy",
     "मोमबत्ती का जलता मोम गर्म होकर द्रव बन जाता है। यह कौन-सा परिवर्तन है?",
     "The burning candle's wax heats up and becomes liquid. Which change is this?",
     ["पिघलन", "संघनन", "जमन", "उर्ध्वपातन"],
     ["Melting", "Condensation", "Freezing", "Sublimation"],
     0,
     "गर्मी से ठोस मोम द्रव बना — पिघलन।",
     "Heat turned the solid wax liquid — melting."),

    ("changes-of-state", "easy",
     "ढँकी हुई कढ़ाई के ढक्कन के भीतर की ओर पानी की छोटी बूँदें जमा हो जाती हैं। यह किस प्रक्रिया का परिणाम है?",
     "Small water drops collect on the inside of a covered pan's lid. This is the result of which process?",
     ["संघनन", "पिघलन", "उर्ध्वपातन", "जमन"],
     ["Condensation", "Melting", "Sublimation", "Freezing"],
     0,
     "बनने वाली भाप ठंडे ढक्कन से छूकर फिर द्रव बनती है — संघनन।",
     "The forming vapour touches the cool lid and turns liquid again — condensation."),

    ("changes-of-state", "easy",
     "रेफ्रिजरेटर में रखा पानी की छौनी का पानी ठोस बर्फ बन जाता है। क्रिया का नाम क्या है?",
     "The water in an ice tray kept in the refrigerator turns into solid ice. What is the process called?",
     ["जमन", "क्वथन", "वाष्पीकरण", "उर्ध्वपातन"],
     ["Freezing", "Boiling", "Evaporation", "Sublimation"],
     0,
     "ठंड से द्रव जल ठोस बर्फ बना — जमन।",
     "Cold turned the liquid water into solid ice — freezing."),

    ("changes-of-state", "easy",
     "सर्दी की रात पानी की टंकी का पानी बर्फ जम जाता है। पानी की अवस्था कैसे बदली?",
     "On a winter night the water in a tank freezes. How did the water's state change?",
     ["द्रव से ठोस (जमन)", "ठोस से द्रव (पिघलन)", "द्रव से गैस (क्वथन)", "गैस से द्रव (संघनन)"],
     ["Liquid to solid (freezing)", "Solid to liquid (melting)", "Liquid to gas (boiling)", "Gas to liquid (condensation)"],
     0,
     "द्रव → ठोस की दिशा जमन की पहचान है।",
     "The liquid → solid direction is the very identity of freezing."),

    ("changes-of-state", "easy",
     "पिघलन में पदार्थ की अवस्था किस दिशा में बदलती है?",
     "In melting, in which direction does the substance's state change?",
     ["ठोस → द्रव", "द्रव → ठोस", "गैस → द्रव", "ठोस → गैस"],
     ["Solid → liquid", "Liquid → solid", "Gas → liquid", "Solid → gas"],
     0,
     "पिघलन का एकमात्र रास्ता — ठोस से द्रव।",
     "Melting's only route — solid to liquid."),

    ("changes-of-state", "easy",
     "संघनन में अवस्था की दिशा क्या होती है?",
     "What is the direction of the state in condensation?",
     ["गैस → द्रव", "द्रव → गैस", "ठोस → द्रव", "द्रव → ठोस"],
     ["Gas → liquid", "Liquid → gas", "Solid → liquid", "Liquid → solid"],
     0,
     "भाप का पानी बनना — गैस से द्रव की ओर।",
     "Steam becoming water — from gas toward liquid."),

    ("changes-of-state", "easy",
     "नैफ्थलीन की गोली कपड़ों में रखने पर धीरे-धीरे छोटी होती जाती है बिना गीली हुए। कारण-प्रक्रिया चुनिए:",
     "A naphthalene ball kept among clothes keeps getting smaller without becoming wet. Choose the cause-process:",
     ["वह द्रव बने बिना सीधे गैस में बदलती है (उर्ध्वपातन)", "वह पानी में घुल जाती है", "वह पिघलकर बह जाती है", "कपड़े उसे खा जाते हैं"],
     ["It changes straight into gas without becoming liquid (sublimation)", "It dissolves in water", "It melts and flows away", "The clothes eat it up"],
     0,
     "आकार घटना = कण-दर-कण गैस बनकर उड़ना।",
     "Shrinking size = turning into gas particle by particle and escaping."),

    ("changes-of-state", "easy",
     "भाप, पानी और बर्फ — तीनों में पदार्थ का वास्तविक अंतर क्या है?",
     "Steam, water and ice — what is the actual difference in the substance among the three?",
     ["केवल अवस्था अलग है, पदार्थ (जल) वही है", "तीनों अलग-अलग पदार्थ हैं", "तीनों में कण अलग हैं", "तीनों में द्रव्यमान अलग है"],
     ["Only the state differs; the substance (water) is the same", "All three are different substances", "The particles differ in all three", "The masses differ in all three"],
     0,
     "एक ही जल की तीन अवस्थाएँ — गैस, द्रव, ठोस।",
     "Three states of the same water — gas, liquid, solid."),

    ("changes-of-state", "easy",
     "पानी को लगातार गर्म करने पर वह उबलकर किस अवस्था में बदलता है?",
     "On being heated continuously, into which state does water change by boiling?",
     ["गैस (भाप)", "ठोस (बर्फ)", "प्लाज़्मा", "वही द्रव रहता है"],
     ["Gas (steam)", "Solid (ice)", "Plasma", "It remains the same liquid"],
     0,
     "उबलते पानी से भाप बनती है — द्रव से गैस।",
     "Boiling water gives steam — liquid to gas."),

    # ---- medium (21) ----
    ("changes-of-state", "medium",
     "अवस्था-परिवर्तनों और उनकी दिशाओं का गलत मिलान कौन-सा है?",
     "Which is the WRONG matching of the changes of state with their directions?",
     ["संघनन — ठोस से गैस", "पिघलन — ठोस से द्रव", "जमन — द्रव से ठोस", "क्वथन — द्रव से गैस"],
     ["Condensation — solid to gas", "Melting — solid to liquid", "Freezing — liquid to solid", "Boiling — liquid to gas"],
     0,
     "संघनन गैस को द्रव बनाता है, ठोस को नहीं।",
     "Condensation turns a gas into a liquid, not a solid."),

    ("changes-of-state", "medium",
     "पिघलन और जमन एक दूसरे के क्या हैं?",
     "What are melting and freezing to each other?",
     ["विपरीत दिशा वाली क्रियाएँ", "एक ही क्रिया के दो नाम", "असंबंधित क्रियाएँ", "दोनों गैस बनाती हैं"],
     ["Opposite-direction processes", "Two names of one process", "Unrelated processes", "Both turn matter into gas"],
     0,
     "पिघलन ठोस को द्रव बनाता है, जमन उसी द्रव को ठोस — उलटी दिशाएँ।",
     "Melting takes solid to liquid; freezing takes that liquid back to solid — reverse directions."),

    ("changes-of-state", "medium",
     "क्वथन और संघनन के बीच का संबंध क्या है?",
     "What is the relation between boiling and condensation?",
     ["एक दूसरे के विपरीत — क्वथन द्रव से गैस, संघनन गैस से द्रव", "दोनों एक ही दिशा में होते हैं", "दोनों ठोस बनाते हैं", "दोनों में कोई संबंध नहीं"],
     ["Opposites of each other — boiling liquid to gas, condensation gas to liquid", "Both occur in the same direction", "Both make solids", "The two are unrelated"],
     0,
     "एक बनाता है भाप, दूसरा उसे वापस पानी।",
     "One makes steam; the other brings it back to water."),

    ("changes-of-state", "medium",
     "जल की यात्रा: बर्फ → जल → भाप। इस श्रृंखला में कौन-से दो परिवर्तन हुए?",
     "Water's journey: ice → water → steam. Which two changes occurred in this chain?",
     ["पिघलन, फिर क्वथन", "जमन, फिर संघनन", "संघनन, फिर पिघलन", "उर्ध्वपातन, फिर जमन"],
     ["Melting, then boiling", "Freezing, then condensation", "Condensation, then melting", "Sublimation, then freezing"],
     0,
     "ठोस→द्रव पिघलन; द्रव→गैस क्वथन।",
     "Solid→liquid melting; liquid→gas boiling."),

    ("changes-of-state", "medium",
     "जल की वापसी: भाप → जल → बर्फ। इस श्रृंखला में क्रियाओं का क्रम क्या है?",
     "Water's return: steam → water → ice. What is the order of the processes in this chain?",
     ["संघनन, फिर जमन", "क्वथन, फिर पिघलन", "पिघलन, फिर संघनन", "जमन, फिर उर्ध्वपातन"],
     ["Condensation, then freezing", "Boiling, then melting", "Melting, then condensation", "Freezing, then sublimation"],
     0,
     "गैस→द्रव संघनन; द्रव→ठोस जमन।",
     "Gas→liquid condensation; liquid→solid freezing."),

    ("changes-of-state", "medium",
     "बर्फ के गिलास को वापस फ्रीजर में रखने पर उसका जल फिर बर्फ बन गया। पूरे चक्र में जल ने कौन-से रूप ओर क्रम से अपनाए?",
     "Putting the ice-glass back in the freezer, its water became ice again. In the full cycle, which forms did the water take, in order?",
     ["ठोस → द्रव → ठोस", "द्रव → गैस → द्रव", "ठोस → गैस → ठोस", "गैस → ठोस → गैस"],
     ["Solid → liquid → solid", "Liquid → gas → liquid", "Solid → gas → solid", "Gas → solid → gas"],
     0,
     "पिघलन के बाद जमन — जल का आ-जा चक्र।",
     "Melting followed by freezing — water's to-and-fro cycle."),

    ("changes-of-state", "medium",
     "ठंडी खिड़की के शीशे पर कमरे की भाप छोटी बूँदों में जमा दिखती है। यहाँ कौन-सा परिवर्तन हुआ?",
     "On a cold window pane the room's vapour is seen gathered as tiny drops. Which change occurred here?",
     ["गैस से द्रव — संघनन", "द्रव से गैस — क्वथन", "ठोस से द्रव — पिघलन", "ठोस से गैस — उर्ध्वपातन"],
     ["Gas to liquid — condensation", "Liquid to gas — boiling", "Solid to liquid — melting", "Solid to gas — sublimation"],
     0,
     "ठंडे शीशे ने भाप को द्रव में बदल दिया।",
     "The cold pane converted the vapour into liquid."),

    ("changes-of-state", "medium",
     "चाय की भाप ऊपर चली जाती है और ऊपर ठंडी हवा मिलते ही छोटे जल-कण बन जाती है। यह कौन-सी क्रिया है?",
     "Tea's steam rises and, meeting cooler air, turns into tiny water particles. Which process is this?",
     ["संघनन", "पिघलन", "जमन", "उर्ध्वपातन"],
     ["Condensation", "Melting", "Freezing", "Sublimation"],
     0,
     "गर्म भाप + ठंडी हवा = वापस द्रव कण।",
     "Hot vapour + cool air = back to liquid particles."),

    ("changes-of-state", "medium",
     "क्वथन के समय पूरे द्रव में बुलबुले कहाँ-कहाँ बनते हैं?",
     "During boiling, where all do the bubbles form in the liquid?",
     ["पूरे द्रव में — भीतर भी, तल में भी", "केवल सतह पर", "केवल बर्तन के किनारों पर", "कहीं नहीं बनते"],
     ["Throughout the whole liquid — inside it and at the bottom too", "Only at the surface", "Only at the vessel's edges", "They do not form anywhere"],
     0,
     "क्वथन पूरे द्रव की घटना है — इसीलिए हर ओर बुलबुले।",
     "Boiling is a whole-liquid event — hence bubbles everywhere."),

    ("changes-of-state", "medium",
     "गर्म किए जा रहे एक शुद्ध पदार्थ के सामने तापमापी का रुककर स्थिर हो जाना बताता है कि —",
     "For a pure substance being heated, the thermometer pausing and holding steady indicates that —",
     ["पदार्थ उस समय अवस्था-परिवर्तन (पिघलन या क्वथन) में है", "गर्म करना बंद हो गया है", "तापमापी खराब हो गया है", "पदार्थ ठंडा होने लगा है"],
     ["The substance is at that moment in a change of state (melting or boiling)", "The heating has stopped", "The thermometer has broken", "The substance has begun to cool"],
     0,
     "पिघलन-क्वथन के समय ताप स्थिर रहता है — यही स्थिरता उस प्रक्रिया की पहचान है।",
     "During melting and boiling the temperature stays steady — that steadiness is the signature of the process."),

    ("changes-of-state", "medium",
     "दो कथन: (i) उर्ध्वपातन में द्रव अवस्था की भूमिका नहीं होती। (ii) नैफ्थलीन और कपूर उर्ध्वपातन करने वाले ठोस हैं। सही विकल्प:",
     "Two statements: (i) In sublimation the liquid state plays no role. (ii) Naphthalene and camphor are solids that sublime. The correct option:",
     ["दोनों सही हैं", "केवल (i) सही", "केवल (ii) सही", "दोनों गलत"],
     ["Both are correct", "Only (i)", "Only (ii)", "Both wrong"],
     0,
     "ठोस से सीधे गैस — बीच में द्रव नहीं।",
     "Solid straight to gas — no liquid in between."),

    ("changes-of-state", "medium",
     "आँगन में गिरी बर्फ दोपहर तक जल बन गई और शाम तक गीलापन सूख गया। जल ने कौन-सा क्रम दिखाया?",
     "Ice fallen in the courtyard turned into water by noon, and by evening the wetness dried up. What sequence did the water show?",
     ["ठोस → द्रव → गैस", "गैस → द्रव → ठोस", "द्रव → ठोस → गैस", "ठोस → गैस → द्रव"],
     ["Solid → liquid → gas", "Gas → liquid → solid", "Liquid → solid → gas", "Solid → gas → liquid"],
     0,
     "पिघलन के बाद वाष्पीकरण — जल का ऊपर की ओर चक्र।",
     "Melting followed by evaporation — water's upward journey."),

    ("changes-of-state", "medium",
     "सुबह घास पर ओस की बूँदें दोपहर तक गायब रहती हैं। बूँदों के गायब होने का अवस्था-परिवर्तन क्या है?",
     "Dew drops on the morning grass are gone by noon. What is the state change of the drops' disappearance?",
     ["द्रव से गैस (वाष्पीकरण)", "गैस से द्रव (संघनन)", "द्रव से ठोस (जमन)", "ठोस से द्रव (पिघलन)"],
     ["Liquid to gas (evaporation)", "Gas to liquid (condensation)", "Liquid to solid (freezing)", "Solid to liquid (melting)"],
     0,
     "बूँदें अदृश्य जल-कण बनकर उड़ीं।",
     "The drops flew off as invisible water particles."),

    ("changes-of-state", "medium",
     "नैफ्थलीन गोली के ऊपर कपड़े लंबे समय बंद रखने पर कपड़ों में उसकी गंध बस जाती है। इसके पीछे कौन-से दो तथ्य साथ चलते हैं?",
     "On keeping clothes over a naphthalene ball for long, its smell settles into the clothes. Which two facts work together behind this?",
     ["उर्ध्वपातन (ठोस→गैस) और विसरण (गैस के कणों का फैलाव)", "पिघलन और जमन", "क्वथन और संघनन", "संपीडन और प्रसार"],
     ["Sublimation (solid→gas) and diffusion (the spreading of the gas's particles)", "Melting and freezing", "Boiling and condensation", "Compression and expansion"],
     0,
     "पहले ठोस गैस बनी, फिर उसके कण कपड़ों तक विसरित हुए।",
     "First the solid became gas; then its particles diffused into the clothes."),

    ("changes-of-state", "medium",
     "गर्म चाय के गिलास से उठने वाली 'धुंध' वास्तव में क्या है?",
     "What really is the 'haze' rising from a glass of hot tea?",
     ["छोटे द्रव जल-कण — भाप के ठंडी हवा से संघनित होने का रूप", "शुद्ध गैस", "धुआँ जला हुआ", "धूल के कण"],
     ["Tiny liquid water particles — the form of vapour condensed by cooler air", "A pure gas", "Burnt smoke", "Dust particles"],
     0,
     "दिखने वाली धुंध संघनन की बनी है; अदृश्य भाप शुद्ध गैस है।",
     "The visible haze is made by condensation; the invisible vapour is the true gas."),

    ("changes-of-state", "medium",
     "तीन कथन: (i) पिघलन ठोस से द्रव की क्रिया है। (ii) संघनन गैस से द्रव की क्रिया है। (iii) जमन द्रव से गैस की क्रिया है। गलत कथन:",
     "Three statements: (i) Melting is solid to liquid. (ii) Condensation is gas to liquid. (iii) Freezing is liquid to gas. The wrong statement:",
     ["कथन (iii)", "कथन (i)", "कथन (ii)", "तीनों सही"],
     ["Statement (iii)", "Statement (i)", "Statement (ii)", "All three correct"],
     0,
     "जमन द्रव को ठोस बनाता है, गैस नहीं।",
     "Freezing makes a liquid solid, not gas."),

    ("changes-of-state", "medium",
     "एक बर्फ की टिकिया ट्रे में पिघली और फिर वही जल फ्रीजर में जमा। दोनों क्रियाओं में जल के कणों के बीच क्या बदला?",
     "An ice cube melted in a tray and the same water froze again in the freezer. In both processes, what changed between the water's particles?",
     ["कणों का आपसी बंधन — पिघलन में ढीला, जमन में कसा", "कणों की संख्या", "कणों का रंग", "कणों का आकार"],
     ["The particles' mutual binding — loosened in melting, tightened in freezing", "The number of particles", "The colour of the particles", "The size of the particles"],
     0,
     "अवस्था-बदलाव का इंजन कणों का बंधन है।",
     "The engine of state change is the particles' binding."),

    ("changes-of-state", "medium",
     "'नैफ्थलीन की गोली पिघलकर बहती है' — इस कथन की गलती क्या है?",
     "What is the error in the statement 'a naphthalene ball melts and flows away'?",
     ["नैफ्थलीन पिघलती नहीं — वह सीधे गैस बनती है (उर्ध्वपातन)", "नैफ्थलीन गैस नहीं बनती", "नैफ्थलीन जल जाती है", "कथन पूर्णतः सही है"],
     ["Naphthalene does not melt — it turns directly into gas (sublimation)", "Naphthalene does not become gas", "Naphthalene burns away", "The statement is fully correct"],
     0,
     "गीला न बनना ही उर्ध्वपातन की पहचान है।",
     "Never turning wet is the very mark of sublimation."),

    ("changes-of-state", "medium",
     "उबलते दूध को उबाल के ठीक बाद गिलास में ढँककर रखा गया। ठंडा होने पर ढक्कन हटाने पर भीतर बूँदें दिखीं। इन बूँदों का स्रोत क्या था?",
     "Boiling milk was poured into a glass and covered just after. When cooled and uncovered, drops were seen inside. What was the source of these drops?",
     ["दूध की भाप जो ढक्कन पर संघनित हुई", "बाहर की हवा", "काँच का पिघलना", "दूध का जमना"],
     ["The milk's vapour that condensed on the lid", "The outside air", "Melting of the glass", "Freezing of the milk"],
     0,
     "वाष्प → ठंडा ढक्कन → बूँदें — संघनन की छोटी घटना।",
     "Vapour → cool lid → drops — a small event of condensation."),

    ("changes-of-state", "medium",
     "किसी ठोस पदार्थ को लगातार गर्म किया जा रहा है। उसके बदलते रूप का सही ताप-क्रम आधारित विवरण चुनिए (सामान्य ठोस, जो उर्ध्वपातन नहीं करता):",
     "A solid substance is being heated continuously. Choose the correct description of its changing form (an ordinary solid that does not sublime):",
     ["ठोस → (पिघलकर) द्रव → (उबलकर) गैस", "ठोस → सीधे गैस", "ठोस → गैस → द्रव", "ठोस ठोस ही रहता है"],
     ["Solid → (melts into) liquid → (boils into) gas", "Solid → directly gas", "Solid → gas → liquid", "The solid remains solid"],
     0,
     "साधारण ठोस का रास्ता द्रव से होकर ही गैस तक जाता है।",
     "An ordinary solid reaches gas only via the liquid."),

    ("changes-of-state", "medium",
     "दो कथन: (i) बर्फ और भाप दोनों जल के ही रूप हैं। (ii) अवस्था बदलने पर जल के कण बदल जाते हैं। सही विकल्प:",
     "Two statements: (i) Ice and steam are both forms of water. (ii) On changing state, water's particles themselves change. The correct option:",
     ["(i) सही, (ii) गलत — कण वही रहते हैं, केवल बंधन बदलता है", "दोनों सही", "दोनों गलत", "(i) गलत, (ii) सही"],
     ["(i) correct, (ii) wrong — the particles remain the same; only the bonding changes", "Both correct", "Both wrong", "(i) wrong, (ii) correct"],
     0,
     "अवस्था-परिवर्तन कणों का नहीं, कणों के बंधन का खेल है।",
     "A change of state is a play of the particles' bonding, not of the particles."),

    # ---- hard (9) ----
    ("changes-of-state", "hard",
     "किसी ठोस को गर्म करने पर वह द्रव बने बिना सीधे वाष्प बनने लगा। विद्यार्थी ने इसे पिघलन कहा। उसकी गलती स्पष्ट कीजिए:",
     "On heating, a solid began turning directly into vapour without becoming liquid. A student called it melting. Clarify his error:",
     ["द्रव बने बिना गैस बनना उर्ध्वपातन है, पिघलन नहीं", "वह क्वथन था", "वह संघनन था", "विद्यार्थी सही था"],
     ["Becoming gas without becoming liquid is sublimation, not melting", "It was boiling", "It was condensation", "The student was right"],
     0,
     "पिघलन के लिए द्रव-रूप अनिवार्य है; छलांग सीधी गैस में उर्ध्वपातन है।",
     "Melting requires the liquid form; a leap straight into gas is sublimation."),

    ("changes-of-state", "hard",
     "पाँच परिवर्तन — पिघलन, जमन, क्वथन, संघनन, उर्ध्वपातन — में से 'ठोस से जुड़ा' असामान्य निकल कौन-सा है और क्यों?",
     "Among the five changes — melting, freezing, boiling, condensation, sublimation — which is the unusual one linked to solids and why?",
     ["उर्ध्वपातन — क्योंकि यह द्रव को छोड़कर सीधे ठोस से गैस बनाता है", "पिघलन — क्योंकि यह ठोस बनाता है", "जमन — क्योंकि यह गैस बनाता है", "संघनन — क्योंकि यह ठोस बनाता है"],
     ["Sublimation — because it makes gas straight from solid, skipping the liquid", "Melting — because it makes a solid", "Freezing — because it makes a gas", "Condensation — because it makes a solid"],
     0,
     "चार परिवर्तन द्रव को स्पर्श करते हैं; उर्ध्वपातन द्रव को छलांग मारता है।",
     "Four changes touch the liquid; sublimation leaps over it."),

    ("changes-of-state", "hard",
     "तीन कथन: (i) जमन में कणों का बंधन कसता है। (ii) पिघलन में कणों का बंधन ढीला होता है। (iii) किसी अवस्था-परिवर्तन में कण नष्ट नहीं होते। सही समूह:",
     "Three statements: (i) In freezing the particles' binding tightens. (ii) In melting the binding loosens. (iii) In no change of state are particles destroyed. The correct set:",
     ["तीनों सही", "केवल (i) और (ii)", "केवल (iii)", "केवल (ii)"],
     ["All three correct", "Only (i) and (ii)", "Only (iii)", "Only (ii)"],
     0,
     "बंधन का कस-ढीला होना ही परिवर्तन है; कण सदा सुरक्षित।",
     "The tightening or loosening of binding is the change; the particles stay safe."),

    ("changes-of-state", "hard",
     "सोच-परीक्षण: यदि कोई पदार्थ उर्ध्वपातन न करता और उसका द्रव रूप भी न बनता, तो उसके गैस बनने का कोई मार्ग बचता है?",
     "Thought experiment: if a substance neither sublimed nor ever formed a liquid, would any path remain for it to become a gas?",
     ["नहीं — गैस बनने के दोनों रास्ते (द्रव से क्वथन, ठोस से उर्ध्वपातन) बंद हो जाते", "हाँ, जमकर", "हाँ, संघनित होकर", "हाँ, विसरण से"],
     ["No — both routes to gas (boiling from liquid, subliming from solid) would be closed", "Yes, by freezing", "Yes, by condensing", "Yes, by diffusing"],
     0,
     "गैस के दो द्वार हैं — द्रव और सीधा ठोस; दोनों बंद तो द्वार नहीं।",
     "A gas has two doors — via liquid and straight from solid; close both and there is no door."),

    ("changes-of-state", "hard",
     "एक ही बर्तन में बर्फ-जल मिश्रण लंबे समय तक रखा है। मिश्रण में बर्फ भी है और जल भी। इस स्थिति की कण-व्याख्या क्या है?",
     "An ice-water mixture has been kept in the same vessel for long. The mix holds both ice and water. What is the particle explanation of this state?",
     ["पिघलन-बिंदु पर ठोस और द्रव दोनों साथ रह सकते हैं — कणों का एक भाग जकड़ा, दूसरा ढीला", "बर्फ और जल अलग पदार्थ हैं", "कण आधे गायब हो गए", "यह उर्ध्वपातन की स्थिति है"],
     ["At the melting point the solid and the liquid can coexist — one part of the particles locked, the other loose", "Ice and water are different substances", "Half the particles vanished", "This is a sublimation situation"],
     0,
     "जहाँ ठोस द्रव में बदल रहा हो, वहाँ दोनों रूप साथ दिखते हैं।",
     "Where a solid is passing into liquid, both forms show up together."),

    ("changes-of-state", "hard",
     "'हर अवस्था-परिवर्तन उलटा भी संभव है' — इस कथन के अनुसार क्वथन का उलटा और पिघलन का उलटा क्रमशः हैं:",
     "'Every change of state is reversible too' — per this statement, the reverse of boiling and the reverse of melting respectively are:",
     ["संघनन और जमन", "जमन और संघनन", "उर्ध्वपातन और क्वथन", "क्वथन और पिघलन"],
     ["Condensation and freezing", "Freezing and condensation", "Sublimation and boiling", "Boiling and melting"],
     0,
     "गैस→द्रव संघनन (क्वथन का उलटा); द्रव→ठोस जमन (पिघलन का उलटा)।",
     "Gas→liquid condensation (boiling's reverse); liquid→solid freezing (melting's reverse)."),

    ("changes-of-state", "hard",
     "उर्ध्वपातन करते ठोस के कण 'गायब' कहाँ जाते हैं? सही निष्कर्ष चुनिए:",
     "Where do the particles of a subliming solid 'disappear' to? Choose the correct conclusion:",
     ["वे वायु में गैस-कणों के रूप में मिल जाते हैं — नष्ट नहीं होते", "वे नष्ट हो जाते हैं", "वे बर्तन में रह जाते हैं", "वे ठोस में ही सिकुड़ जाते हैं"],
     ["They join the air as gas particles — they are not destroyed", "They are destroyed", "They remain in the vessel", "They shrink back into the solid"],
     0,
     "अदृश्य होना गायब होना नहीं — कण वायु में विलीन।",
     "Becoming invisible is not becoming nothing — the particles merge into the air."),

    ("changes-of-state", "hard",
     "एक बंद जार में नैफ्थलीन की कुछ गोलियाँ रखी हैं। महीनों बाद गोलियाँ छोटी हो गईं और जार खोलने पर भीतर गंध थी। इससे निकलने वाले दो निष्कर्ष क्या हैं?",
     "Some naphthalene balls are kept in a sealed jar. Months later the balls shrank and the jar smelled of naphthalene on opening. What two conclusions follow?",
     ["(1) गोलियों ने उर्ध्वपातन किया; (2) बनी गैस बंद जार में फैलकर रह गई", "(1) गोलियाँ पिघलीं; (2) जार में पानी आ गया", "(1) गोलियाँ जमीं; (2) जार ठंडा था", "(1) गोलियाँ घुलीं; (2) जार में घोल बना"],
     ["(1) The balls sublimed; (2) the gas formed stayed spread inside the sealed jar", "(1) The balls melted; (2) water entered the jar", "(1) The balls froze; (2) the jar was cold", "(1) The balls dissolved; (2) a solution formed in the jar"],
     0,
     "छोटी गोलियाँ + बंद जार की गंध = उर्ध्वपातन और गैस का बंद स्थान घेरना।",
     "Shrunken balls + smell in a sealed jar = sublimation and the gas occupying the closed space."),

    ("changes-of-state", "hard",
     "अवस्था-परिवर्तन की दिशाओं का नक्शा बनाएँ: ठोस-द्रव-गैस तीन स्टेशन हैं। इस नक्शे पर 'गैस से ठोस सीधे' जाने वाला कोई मार्ग बताइए (जैसा ऊपर पाँचों में नहीं गिनाया गया) —",
     "Let us map the directions of change of state: solid-liquid-gas are three stations. On this map, state whether any direct 'gas to solid' route was counted among the five named above —",
     ["नहीं — पाँचों में गैस से ठोस सीधा रास्ता सूचीबद्ध नहीं है; गैस पहले द्रव बनती है", "हाँ — जमन वही है", "हाँ — पिघलन वही है", "हाँ — उर्ध्वपातन वही है"],
     ["No — among the five, no direct gas-to-solid route is listed; a gas becomes liquid first", "Yes — freezing is that route", "Yes — melting is that route", "Yes — sublimation is that route"],
     0,
     "हमारी सूची के पाँच दरवाज़े हैं; गैस→ठोस सीधा दरवाज़ा उसमें नहीं है।",
     "Our list has five doors; a direct gas→solid door is not among them."),

    # ================= EVAPORATION AND COOLING (50) =================
    # ---- easy (20) ----
    ("evaporation-and-cooling", "easy",
     "वाष्पीकरण किस सतह से होता है?",
     "From which surface does evaporation take place?",
     ["केवल द्रव की खुली सतह से", "द्रव के भीतर से", "बर्तन की तली से ही", "कहीं से नहीं"],
     ["Only from the liquid's open surface", "From inside the liquid", "Only from the vessel's bottom", "From nowhere"],
     0,
     "वाष्पीकरण सतही घटना है — ऊपरी कण ही उड़ते हैं।",
     "Evaporation is a surface event — only the top particles escape."),

    ("evaporation-and-cooling", "easy",
     "गर्मी में आँगन में पानी के छींटे लगाने से ठंडक क्यों मिलती है?",
     "Why does sprinkling water in the courtyard bring coolness in summer?",
     ["पानी वाष्पीकरण होते हुए ठंडक देता है", "पानी आँगन को ढक लेता है", "पानी गर्म हो जाता है", "पानी बर्फ बन जाता है"],
     ["The water, evaporating, gives coolness", "The water covers the courtyard", "The water heats up", "The water turns to ice"],
     0,
     "छींटों का वाष्पीकरण ही ठंडक का कारण है।",
     "The evaporation of the sprinkled droplets is the cause of the coolness."),

    ("evaporation-and-cooling", "easy",
     "वाष्पीकरण के चार कारकों में से एक कौन-सा है?",
     "Which one of these is among the four factors of evaporation?",
     ["ताप (गर्मी)", "बर्तन का रंग", "द्रव की गंध", "कमरे की ऊँचाई"],
     ["Temperature (heat)", "The vessel's colour", "The liquid's smell", "The room's height"],
     0,
     "चार कारक — ताप, सतही क्षेत्रफल, वायु गति, आर्द्रता।",
     "The four factors — temperature, surface area, wind speed, humidity."),

    ("evaporation-and-cooling", "easy",
     "वाष्पीकरण के कारकों में 'सतही क्षेत्रफल' का अर्थ है —",
     "Among the factors of evaporation, 'surface area' means —",
     ["द्रव की खुली सतह का फैलाव", "द्रव की गहराई", "बर्तन की ऊँचाई", "द्रव का रंग"],
     ["The spread of the liquid's open surface", "The liquid's depth", "The vessel's height", "The liquid's colour"],
     0,
     "सतह जितनी फैली, उतने ज्यादा कण उड़ने के मौके पर।",
     "The wider the surface, the more particles get the chance to escape."),

    ("evaporation-and-cooling", "easy",
     "वाष्पीकरण के कारकों में 'वायु गति' का अर्थ है —",
     "Among the factors of evaporation, 'wind speed' means —",
     ["हवा के बहने की चाल", "हवा की दिशा", "हवा का रंग", "हवा की गंध"],
     ["The pace at which the air blows", "The direction of the air", "The colour of the air", "The smell of the air"],
     0,
     "बहती हवा की चाल ही वायु-गति कारक है।",
     "The pace of the blowing air is the wind-speed factor."),

    ("evaporation-and-cooling", "easy",
     "आर्द्रता का अर्थ है —",
     "Humidity means —",
     ["हवा में जल-कणों (भाप) की मात्रा", "हवा की गति", "हवा का रंग", "हवा का ताप"],
     ["The amount of water particles (vapour) in the air", "The speed of the wind", "The colour of the air", "The temperature of the air"],
     0,
     "जितनी अधिक आर्द्रता, हवा में उतने ज्यादा जल-कण।",
     "The more the humidity, the more water particles in the air."),

    ("evaporation-and-cooling", "easy",
     "निम्न में से कौन-सा वाष्पीकरण का कारक नहीं है?",
     "Which of the following is NOT a factor of evaporation?",
     ["बर्तन का रंग", "ताप", "वायु गति", "आर्द्रता"],
     ["The vessel's colour", "Temperature", "Wind speed", "Humidity"],
     0,
     "चार कारक — ताप, सतही क्षेत्रफल, वायु गति, आर्द्रता; रंग इनमें नहीं।",
     "Four factors — temperature, surface area, wind speed, humidity; colour is not among them."),

    ("evaporation-and-cooling", "easy",
     "वाष्पीकरण में द्रव का कौन-सा कण सबसे पहले उड़ता है?",
     "In evaporation, which particles of the liquid escape first?",
     ["सतह पर पहुँचे और पर्याप्त तेज कण", "सबसे ठंडे कण", "सबसे बड़े कण", "तल में दबे कण"],
     ["Those on the surface and sufficiently fast", "The coldest particles", "The largest particles", "Those pressed at the bottom"],
     0,
     "तेज गति वाले ऊपरी कण ही बंधन तोड़कर भाग पाते हैं।",
     "Only the fast-moving upper particles break the binding and escape."),

    ("evaporation-and-cooling", "easy",
     "खुले गिलास का पानी बिना उबाले धीरे-धीरे घटता जाता है। यह किस प्रक्रिया से होता है?",
     "Water in an open glass slowly reduces without boiling. By which process does this happen?",
     ["वाष्पीकरण (सतह से कणों का उड़ना)", "क्वथन", "जमन", "उर्ध्वपातन"],
     ["Evaporation (particles escaping from the surface)", "Boiling", "Freezing", "Sublimation"],
     0,
     "बिना उबाल भी सतह के कण उड़ते रहते हैं।",
     "Even without boiling, the surface particles keep escaping."),

    ("evaporation-and-cooling", "easy",
     "वाष्पीकरण केवल गर्मियों में ही होता है — यह कथन सही है?",
     "Evaporation occurs only in summers — is this statement correct?",
     ["नहीं, यह किसी भी ताप पर हो सकता है, गर्मी में तेज होता है", "हाँ, केवल गर्मी में", "हाँ, केवल दोपहर में", "हाँ, केवल रेगिस्तान में"],
     ["No, it can occur at any temperature; it is faster in summer", "Yes, only in summer", "Yes, only at noon", "Yes, only in deserts"],
     0,
     "वाष्पीकरण किसी भी ताप पर चलता है — ताप बढ़ने से केवल गति बढ़ती है।",
     "Evaporation runs at any temperature — heat only raises its pace."),

    ("evaporation-and-cooling", "easy",
     "ताप बढ़ने पर वाष्पीकरण की गति का क्या होता है?",
     "What happens to the rate of evaporation when temperature rises?",
     ["बढ़ जाती है", "घट जाती है", "शून्य हो जाती है", "उलट जाती है"],
     ["It increases", "It decreases", "It becomes zero", "It reverses"],
     0,
     "गर्मी में कण तेज दौड़ते हैं — उड़ने वाले बढ़ जाते हैं।",
     "In heat the particles race faster — more of them escape."),

    ("evaporation-and-cooling", "easy",
     "बरसात के दिन (अधिक आर्द्रता) वाष्पीकरण की गति कैसी रहती है?",
     "On a rainy day (high humidity), how does the rate of evaporation remain?",
     ["धीमी रहती है", "बहुत तेज", "शून्य नहीं, पर अधिकतम", "बढ़ जाती है"],
     ["It remains slow", "Very fast", "Not zero, but maximum", "It increases"],
     0,
     "हवा में पहले से भाप भरी हो तो नए कणों की जगह कम।",
     "With the air already full of vapour, there is less room for new particles."),

    ("evaporation-and-cooling", "easy",
     "वाष्पीकरण होते समय द्रव की अवस्था किसमें बदल रही होती है?",
     "During evaporation, into what is the liquid's state changing?",
     ["द्रव से गैस", "गैस से द्रव", "द्रव से ठोस", "ठोस से गैस"],
     ["Liquid to gas", "Gas to liquid", "Liquid to solid", "Solid to gas"],
     0,
     "जल के कण भाप के कण बनते हैं।",
     "The water particles become vapour particles."),

    ("evaporation-and-cooling", "easy",
     "गर्मी की दोपहर छत पर पानी डालने से नीचे कमरे को राहत मिलती है। मुख्य कारण क्या है?",
     "Pouring water on the roof in a hot afternoon gives relief to the room below. What is the main reason?",
     ["छत के पानी का वाष्पीकरण करते हुए ठंडक देना", "पानी का छत में सोख लिया जाना", "पानी का बर्फ बनना", "बादलों का आ जाना"],
     ["The roof's water, while evaporating, gives coolness", "The water getting absorbed into the roof", "The water turning to ice", "The clouds arriving"],
     0,
     "वाष्पीकरण की ठंडक ही छत-वाले कमरे की राहत है।",
     "Evaporation's coolness is the relief for the room under the roof."),

    ("evaporation-and-cooling", "easy",
     "आर्द्रता मुख्यतः किस अवस्था में मौजूद जल-कणों से बनती है?",
     "Humidity is formed mainly from water particles present in which state?",
     ["गैस (भाप)", "ठोस (बर्फ)", "द्रव की बड़ी बूँदें", "किसी अवस्था में नहीं"],
     ["Gas (vapour)", "Solid (ice)", "Big drops of liquid", "In no state"],
     0,
     "हवा में घुली भाप के जल-कण ही आर्द्रता हैं।",
     "The water particles of vapour mixed in the air are the humidity."),

    ("evaporation-and-cooling", "easy",
     "पानी के छींटों से मिली ठंडक तभी तक बनी रहती है, जब तक —",
     "The coolness from water sprinkles stays only as long as —",
     ["छिड़के जल का वाष्पीकरण होता रहता है", "जल जमा रहता है", "जल उबलता रहता है", "फर्श गीला नहीं होता"],
     ["The sprinkled water keeps evaporating", "The water stays frozen", "The water keeps boiling", "The floor is not wet"],
     0,
     "ठंडक वाष्पीकरण के साथ आती है और वाष्पीकरण के साथ ही टिकती है।",
     "The coolness comes with evaporation and lasts only as long as evaporation does."),

    ("evaporation-and-cooling", "easy",
     "गर्मी के दिनों में तालाब का जल-स्तर अपने आप नीचे चला जाता है। जल का क्या हुआ?",
     "In summer days a pond's water level goes down on its own. What happened to the water?",
     ["वाष्पीकरण से जल-कण वायु में गैस बनकर उड़ गए", "जल तली में बर्फ बन गया", "पूरा जल मिट्टी में रिस गया", "जल ने रंग बदल दिया"],
     ["By evaporation the water particles flew off into the air as gas", "The water turned to ice at the bottom", "The whole water seeped into the soil", "The water changed colour"],
     0,
     "खुली बड़ी सतह से जल-कण लगातार भाप बनते रहते हैं।",
     "From the big open surface the water particles keep turning into vapour."),

    ("evaporation-and-cooling", "easy",
     "वाष्पीकरण हो जाने के बाद जल के कण कहाँ रहते हैं?",
     "After evaporation has happened, where do the water's particles remain?",
     ["वायु में भाप (गैस) के रूप में", "बर्तन में ही ठोस बनकर", "जल में वापस आ जाते हैं", "नष्ट हो जाते हैं"],
     ["In the air as vapour (gas)", "In the vessel itself, turned solid", "They come back into the water", "They are destroyed"],
     0,
     "उड़े कण गायब नहीं होते — वे वायु में मिल जाते हैं।",
     "The escaped particles are not lost — they join the air."),

    ("evaporation-and-cooling", "easy",
     "धुले कपड़े सूख रहे हैं; उनके बगल में खड़ा व्यक्ति हल्की ठंडक महसूस करता है। कारण?",
     "Washed clothes are drying; a person standing right beside them feels a slight coolness. Why?",
     ["कपड़ों के जल-कण वाष्पीकरण होकर उड़ रहे हैं", "कपड़े पंखे की तरह हवा कर रहे हैं", "कपड़े गर्म हो गए हैं", "कपड़ों में बर्फ भरी है"],
     ["The clothes' water particles are evaporating away", "The clothes are fanning the air", "The clothes have become hot", "The clothes are packed with ice"],
     0,
     "वाष्पीकरण की ठंडक समीप भी महसूस होती है।",
     "Evaporation's coolness is felt close by as well."),

    ("evaporation-and-cooling", "easy",
     "छिड़काव के बाद तेज हवा चलने लगी और फर्श का जल जल्दी सूख गया। कौन-सा कारक काम आया?",
     "After sprinkling, a strong wind began and the floor's water dried quickly. Which factor helped?",
     ["वायु गति", "आर्द्रता", "जल का रंग", "बर्तन की ऊँचाई"],
     ["Wind speed", "Humidity", "The water's colour", "The vessel's height"],
     0,
     "बहती हवा ने भाप के कणों को उड़ाया — वाष्पीकरण तेज हुआ।",
     "The blowing air swept off the vapour particles — evaporation quickened."),

    # ---- medium (22) ----
    ("evaporation-and-cooling", "medium",
     "माँ ने धोकर गीली चादर को सिकोड़ने के बजाय पूरी फैला दी। वाष्पीकरण के किस कारक का उपयोग हुआ?",
     "Mother spread the washed wet sheet fully instead of bunching it up. Which factor of evaporation was used?",
     ["सतही क्षेत्रफल — फैली सतह से ज्यादा वाष्पीकरण", "ताप", "आर्द्रता", "वायु दाब"],
     ["Surface area — a spread-out surface evaporates more", "Temperature", "Humidity", "Air pressure"],
     0,
     "फैली चादर की सतह बड़ी — उड़ने वाले जल-कण ज्यादा।",
     "The spread sheet's surface is larger — more water particles escape."),

    ("evaporation-and-cooling", "medium",
     "गर्मी में घर के आगे गूँज (बोरी) पर पानी छिड़कने से हवा ठंडी लगती है। इस युक्ति का वैज्ञानिक आधार चुनिए:",
     "In summer, sprinkling water on the jute sacks before the house makes the breeze feel cool. Choose the scientific basis of this trick:",
     ["गूँज के पानी का वाष्पीकरण — बहती हवा के साथ ठंडक घर तक", "गूँज का बर्फ बनना", "गूँज का पिघलना", "पानी का घर में जाना"],
     ["Evaporation of the sacks' water — the coolness travels home with the breeze", "The sacks turning to ice", "Melting of the sacks", "The water entering the house"],
     0,
     "छिड़काव + हवा = वाष्पीकरण + ठंडक का प्रवाह।",
     "Sprinkling + breeze = evaporation + a flow of coolness."),

    ("evaporation-and-cooling", "medium",
     "दो कथन: (i) वायु गति बढ़ने से वाष्पीकरण तेज होता है। (ii) आर्द्रता बढ़ने से वाष्पीकरण तेज होता है। सही विकल्प:",
     "Two statements: (i) Greater wind speed quickens evaporation. (ii) Greater humidity quickens evaporation. The correct option:",
     ["(i) सही, (ii) गलत", "दोनों सही", "दोनों गलत", "(i) गलत, (ii) सही"],
     ["(i) correct, (ii) wrong", "Both correct", "Both wrong", "(i) wrong, (ii) correct"],
     0,
     "हवा तेज करती है, आर्द्रता धीमी — दोनों उलट दिशा में।",
     "Wind speeds it up; humidity slows it — the two act oppositely."),

    ("evaporation-and-cooling", "medium",
     "एक ही मात्रा का पानी चाय की प्लेट (थाली) में और काँच के गिलास में रखा। किसमें वाष्पीकरण तेज चलेगा और क्यों?",
     "The same quantity of water is kept in a saucer and in a glass. In which will evaporation run faster and why?",
     ["थाली में — खुली सतह बड़ी, सतही क्षेत्रफल का लाभ", "गिलास में — गहराई का लाभ", "दोनों में समान", "निर्भर नहीं करता"],
     ["The saucer — its open surface is larger, the benefit of surface area", "The glass — the benefit of depth", "The same in both", "It does not depend"],
     0,
     "थाली की फैली सतह ज्यादा कणों को उड़ने देती है।",
     "The saucer's spread surface lets more particles escape."),

    ("evaporation-and-cooling", "medium",
     "आर्द्र (नम) हवा में वाष्पीकरण धीमा क्यों हो जाता है? कण-दृष्टि से कारण चुनिए:",
     "Why does evaporation slow down in humid (moist) air? Choose the reason from the particle viewpoint:",
     ["हवा के कणों के बीच पहले से भाप के कण भरे होते हैं — नए जल-कणों के लिए अंतराल कम", "हवा के कण सो जाते हैं", "जल-कण बड़े हो जाते हैं", "हवा जहरीली हो जाती है"],
     ["The air's particles are already crowded with vapour particles — little room for new water particles", "The air's particles fall asleep", "The water particles grow large", "The air becomes poisonous"],
     0,
     "भरी सब्जी-मंडी में नई सब्जी कहाँ रखें — आर्द्र हवा वैसी ही है।",
     "Where would new vegetables fit in an already-full mandi — humid air is just like that."),

    ("evaporation-and-cooling", "medium",
     "गर्म दिन में ठंडी रात की तुलना में खुले पानी की सतह से कण ज्यादा तेजी से उड़ते हैं। कारण-श्रृंखला चुनिए:",
     "On a hot day, particles escape from an open water surface faster than on a cold night. Choose the cause-chain:",
     ["अधिक ताप → कणों की गति तेज → अधिक कण बंधन तोड़कर उड़ते हैं", "अधिक ताप → कण भारी → कम उड़ते हैं", "अधिक ताप → सतह छोटी", "अधिक ताप → आर्द्रता बढ़ती"],
     ["Higher temperature → faster particle motion → more particles break the binding and escape", "Higher temperature → heavier particles → fewer escape", "Higher temperature → smaller surface", "Higher temperature → humidity rises"],
     0,
     "ताप-गति-पलायन की यही कड़ी वाष्पीकरण का तर्क है।",
     "This chain of temperature-motion-escape is the logic of evaporation."),

    ("evaporation-and-cooling", "medium",
     "कुछ लोग मानते हैं कि छींटों से ठंडक इसलिए मिलती है क्योंकि पाइप का जल 'पहले से ठंडा' होता है। इस धारणा की गलती क्या है?",
     "Some people believe sprinkles give coolness because the pipe's water is 'already cold'. What is the error in this belief?",
     ["ठंडक जल के पहले से ठंडे होने से नहीं, बल्कि जल के वाष्पीकरण की प्रक्रिया से आती है", "पाइप का जल वास्तव में गर्म होता है", "छींटे गर्मी बढ़ाते हैं", "यह धारणा पूर्णतः सही है"],
     ["The coolness comes not from the water being cold beforehand, but from the process of the water's evaporation", "The pipe's water is actually hot", "Sprinkles raise the heat", "The belief is fully correct"],
     0,
     "साधारण ताप का जल भी वाष्पीकरण होते ही ठंडक देता है — स्रोत प्रक्रिया है, जल का ताप नहीं।",
     "Even ordinary-temperature water gives coolness upon evaporating — the source is the process, not the water's temperature."),

    ("evaporation-and-cooling", "medium",
     "वाष्पीकरण के चारों कारक — ताप, सतही क्षेत्रफल, वायु गति, आर्द्रता — में से कौन-सा कारक वाष्पीकरण को 'घटा' देता है (बढ़ाने के बजाय)?",
     "Of the four factors of evaporation — temperature, surface area, wind speed, humidity — which one reduces evaporation (instead of raising it)?",
     ["आर्द्रता (बढ़ने पर)", "ताप (बढ़ने पर)", "सतही क्षेत्रफल (बढ़ने पर)", "वायु गति (बढ़ने पर)"],
     ["Humidity (when it rises)", "Temperature (when it rises)", "Surface area (when it grows)", "Wind speed (when it rises)"],
     0,
     "तीन कारक बढ़ाते हैं, एक (आर्द्रता) बढ़ने पर घटाता है।",
     "Three factors raise it; one (humidity) lowers it as it grows."),

    ("evaporation-and-cooling", "medium",
     "गर्मी में मिट्टी के फर्श पर पानी छिड़ककर झाड़ू लगाया जाता है। इसका दोहरा वैज्ञानिक हेतु क्या है?",
     "In summer, water is sprinkled on the earthen floor before sweeping. What is the twin scientific purpose?",
     ["धूल बंधना + वाष्पीकरण से ठंडक", "फर्श गलाना + गर्मी", "फर्श रंगना + चमक", "पानी बचाना + भट्ठी"],
     ["Settling the dust + coolness from evaporation", "Melting the floor + heat", "Colouring the floor + shine", "Saving water + a furnace"],
     0,
     "छिड़काव एक तीर से दो निशाने — धूल और गर्मी।",
     "One sprinkling, two targets — dust and heat."),

    ("evaporation-and-cooling", "medium",
     "गर्मियों में दरवाज़ों पर खस-खस की तट्टियाँ गीली करके लटकाई जाती हैं; उनसे आती हवा ठंडी लगती है। वैज्ञानिक आधार चुनिए:",
     "In summers, vetiver screens are hung wet on doorways; the breeze coming through them feels cool. Choose the scientific basis:",
     ["तट्टी के जल का वाष्पीकरण — ठंडक हवा के साथ भीतर आती है", "तट्टी का बर्फ बन जाना", "खस की गंध से ठंडक", "तट्टी हवा को रोक देती है"],
     ["Evaporation of the screen's water — the coolness enters with the breeze", "The screen turning to ice", "Coolness from vetiver's fragrance", "The screen blocks the air"],
     0,
     "गीली तट्टी वाष्पीकरण की सतह बनती है; हवा ठंडक को भीतर लाती है।",
     "The wet screen becomes a surface for evaporation; the wind brings the coolness inside."),

    ("evaporation-and-cooling", "medium",
     "एक ही द्रव की दो प्लेटें — एक धूप में, एक छाया में। किसमें वाष्पीकरण तेज और किस कारक से?",
     "Two plates of the same liquid — one in sunlight, one in shade. In which is evaporation faster, and by which factor?",
     ["धूप वाली में — ताप कारक से", "छाया वाली में — आर्द्रता से", "दोनों समान", "छाया वाली में — वायु गति से"],
     ["The one in sunlight — by the temperature factor", "The one in shade — by humidity", "Both equal", "The one in shade — by wind speed"],
     0,
     "धूप का ताप कण-गति बढ़ाता है — वाष्पीकरण तेज।",
     "The sun's heat raises particle motion — faster evaporation."),

    ("evaporation-and-cooling", "medium",
     "तीन कथन: (i) वाष्पीकरण किसी भी ताप पर हो सकता है। (ii) खुली सतह जितनी बड़ी होगी, वाष्पीकरण उतना तेज होगा। (iii) आर्द्रता बढ़ने से वाष्पीकरण घटता है। सही समूह:",
     "Three statements: (i) Evaporation can occur at any temperature. (ii) The bigger the open surface, the faster the evaporation. (iii) With rising humidity, evaporation falls. The correct set:",
     ["तीनों सही", "केवल (i) और (iii)", "केवल (ii)", "केवल (iii)"],
     ["All three correct", "Only (i) and (iii)", "Only (ii)", "Only (iii)"],
     0,
     "तीनों कथन ताप, सतही क्षेत्रफल और आर्द्रता — तीन कारकों के शुद्ध विवरण हैं।",
     "All three statements are accurate descriptions of three factors — temperature, surface area and humidity."),

    ("evaporation-and-cooling", "medium",
     "पानी भरी टंकी को ढँक देने पर जल कब तक बचा रहता है? अर्थात ढकने से वाष्पीकरण पर क्या असर पड़ता है?",
     "Covering a water tank keeps the water lasting longer. That is, what effect does covering have on evaporation?",
     ["ढकने से खुली सतह समाप्त — वाष्पीकरण लगभग रुक जाता है", "ढकने से वाष्पीकरण तेज होता है", "ढकने से जल जमता है", "कोई असर नहीं"],
     ["Covering ends the open surface — evaporation nearly stops", "Covering quickens evaporation", "Covering freezes the water", "No effect"],
     0,
     "जहाँ सतह नहीं, वहाँ सतही प्रक्रिया नहीं।",
     "No open surface, no surface process."),

    ("evaporation-and-cooling", "medium",
     "गर्मी में पशुओं को पानी के छींटे पड़ते रहने से उन्हें राहत मिलती है। वाष्पीकरण-तर्क चुनिए:",
     "In summer, animals get relief when water sprinkles keep falling on them. Choose the evaporation logic:",
     ["शरीर पर जल की परत का वाष्पीकरण होता रहता है और ठंडक बनी रहती है", "जल पशुओं का रंग बदलता है", "जल उनमें उर्ध्वपातन करता है", "जल द्रव्यमान बढ़ाता है"],
     ["The layer of water on the body keeps evaporating and the coolness persists", "The water changes their colour", "The water sublimes on them", "The water increases their mass"],
     0,
     "छींटे = लगातार वाष्पीकरण = लगातार ठंडक।",
     "Sprinkles = continuous evaporation = continuous coolness."),

    ("evaporation-and-cooling", "medium",
     "खुली छत पर फैली गिली दरी किन दो कारकों का एक साथ लाभ उठाती है?",
     "A wet mat spread on an open roof exploits which two factors together?",
     ["बड़ा सतही क्षेत्रफल + खुली हवा की गति", "आर्द्रता + दाब", "रंग + गंध", "गहराई + घनत्व"],
     ["A large surface area + the speed of open air", "Humidity + pressure", "Colour + smell", "Depth + density"],
     0,
     "फैलाव सतह देता है, खुली छत वायु-गति — दोनों कारक साथ।",
     "Spreading gives surface; the open roof gives wind — both factors together."),

    ("evaporation-and-cooling", "medium",
     "एक ही गीला तौलिया दो रूपों में — (क) धूप में पूरा फैला, (ख) छाया में सिकुड़ा। वाष्पीकरण किसमें तेज और किन दो कारकों से?",
     "The same wet towel in two arrangements — (a) fully spread in sun, (b) crumpled in shade. In which is evaporation faster, and by which two factors?",
     ["(क) में — ताप और सतही क्षेत्रफल दोनों का लाभ", "(ख) में — आर्द्रता का लाभ", "दोनों में समान", "(ख) में — छाया ठंडक देती है"],
     ["In (a) — the benefit of both temperature and surface area", "In (b) — the benefit of humidity", "The same in both", "In (b) — shade gives coolness"],
     0,
     "धूप ताप बढ़ाती है और फैलाव सतह बढ़ाता है — दोनों ही कारक (क) के पक्ष में।",
     "Sun raises the temperature and spreading raises the surface — both factors favour (a)."),

    ("evaporation-and-cooling", "medium",
     "गर्म रेगिस्तान में पानी को मिट्टी के सूखे बर्तन (सूराही जैसा) में रखा जाता है। बर्तन की सतह से पानी का धीमा रिसाव क्या देता है?",
     "In a hot desert, water is kept in an unglazed earthen vessel (like a surahi). What does the slow seepage of water from the vessel's surface provide?",
     ["लगातार वाष्पीकरण और ठंडा पानी", "पानी का जमना", "पानी का उबलना", "पानी का गलना"],
     ["Continuous evaporation and cool water", "Freezing of the water", "Boiling of the water", "Melting of the water"],
     0,
     "रिसे पानी की सतह बनती है — वाष्पीकरण — ठंडक।",
     "The seeped water makes a surface — evaporation — coolness."),

    ("evaporation-and-cooling", "medium",
     "गर्मी में हाथ-मुँह धोकर बिना पोंछे छोड़ देने पर त्वचा ठंडी महसूस होती है। कारण-क्रम चुनिए:",
     "In summer, washing hands and face and leaving them unwiped makes the skin feel cool. Choose the cause-order:",
     ["त्वचा के जल-कण वाष्पीकरण होकर उड़ते हैं → ठंडक", "जल त्वचा में रुक जाता है → गर्मी", "जल उबल जाता है", "जल जम जाता है"],
     ["The skin's water particles evaporate away → coolness", "The water stays in the skin → heat", "The water boils", "The water freezes"],
     0,
     "धोना + न छूना = वाष्पीकरण का जीता जाना।",
     "Washing + not wiping = letting evaporation win."),

    ("evaporation-and-cooling", "medium",
     "एक बाल्टी पानी को दो दिन तक छोड़ दिया गया। जल थोड़ा घटा, पर बाल्टी का तल गीला ही रहा। यहाँ कौन-सा कारक वाष्पीकरण को सीमित रख रहा था?",
     "A bucket of water was left for two days. The water lessened a little, yet the bucket's base stayed wet. Which factor kept the evaporation limited here?",
     ["छोटा सतही क्षेत्रफल — बाल्टी का मुँह ही एकमात्र खुली सतह", "ताप बहुत अधिक था", "वायु गति शून्य थी और ताप भी — यह असंभव है", "जल गायब हो गया"],
     ["The small surface area — the bucket's mouth is the only open surface", "The temperature was too high", "Both wind and temperature were zero — impossible", "The water vanished"],
     0,
     "गहरे बर्तन की सतह छोटी — वाष्पीकरण भी सीमित।",
     "A deep vessel's surface is small — so is its evaporation."),

    ("evaporation-and-cooling", "medium",
     "कथन: 'वाष्पीकरण केवल तब होता है जब द्रव उबलने लगे।' इस कथन का सही निर्णय कीजिए:",
     "Statement: 'Evaporation happens only when the liquid begins to boil.' Judge this statement correctly:",
     ["गलत — वाष्पीकरण उबाल से पहले भी, बिना उबाले भी होता रहता है", "सही — उबाल जरूरी है", "आंशिक सही — केवल गर्मियों में", "सही — केवल द्रवों में"],
     ["Wrong — evaporation goes on before boiling and without boiling", "Correct — boiling is necessary", "Partly right — only in summers", "Correct — only in liquids"],
     0,
     "खुला जल बिना उबाले घटता है — यही प्रतिदिन का प्रमाण है।",
     "Open water reduces without boiling — everyday proof."),

    ("evaporation-and-cooling", "medium",
     "वाष्पीकरण के चार कारक वाले समूह का सही चयन कीजिए:",
     "Choose the correct selection of the group of the four factors of evaporation:",
     ["ताप, सतही क्षेत्रफल, वायु गति, आर्द्रता", "रंग, गंध, स्वाद, चमक", "द्रव्यमान, आयतन, घनत्व, दाब", "लंबाई, चौड़ाई, ऊँचाई, गहराई"],
     ["Temperature, surface area, wind speed, humidity", "Colour, smell, taste, shine", "Mass, volume, density, pressure", "Length, breadth, height, depth"],
     0,
     "यही चौकड़ी वाष्पीकरण की दर तय करती है।",
     "This quartet alone decides the rate of evaporation."),

    ("evaporation-and-cooling", "medium",
     "गर्मी के दिन सड़क पर पानी छिड़कने वाली गाड़ी गुजरती है। छिड़काव के तुरंत बाद के कुछ मिनटों में हवा में क्या बदलाव महसूस होता है और क्यों?",
     "A water-sprinkling truck passes on a summer road. What change is felt in the air during the few minutes right after, and why?",
     ["हल्की ठंडक — छिड़के जल के वाष्पीकरण के कारण", "गर्मी — जल के गर्म होने से", "बदबू — जल के गंध लेने से", "अंधेरा — भाप के बादल से"],
     ["A slight coolness — due to the evaporation of the sprinkled water", "Heat — from the water warming up", "Stench — from the water picking up smells", "Darkness — from clouds of vapour"],
     0,
     "सड़क का छिड़काव भी वही पुराना नियम — वाष्पीकरण से ठंडक।",
     "Road sprinkling follows the same old rule — coolness by evaporation."),

    # ---- hard (8) ----
    ("evaporation-and-cooling", "hard",
     "तीन कथन: (i) वाष्पीकरण की प्रक्रिया ठंडक देती है। (ii) वाष्पीकरण की दर चार कारकों पर निर्भर करती है। (iii) वाष्पीकरण केवल बरसात के दिनों में होता है। गलत कथन:",
     "Three statements: (i) The process of evaporation gives coolness. (ii) The rate of evaporation depends on four factors. (iii) Evaporation occurs only on rainy days. The wrong statement:",
     ["कथन (iii) — गर्मी में तो वाष्पीकरण और तेज होता है", "कथन (i)", "कथन (ii)", "तीनों सही"],
     ["Statement (iii) — in heat evaporation actually becomes faster", "Statement (i)", "Statement (ii)", "All three correct"],
     0,
     "बरसात की आर्द्रता तो वाष्पीकरण को धीमा करती है; यह कभी 'केवल-बरसात' क्रिया नहीं।",
     "Rainy-day humidity actually slows evaporation; it is never a rainy-days-only process."),

    ("evaporation-and-cooling", "hard",
     "सोच-परीक्षण: वायु गति नाम का कारक हटा दिया जाए (हवा पूर्णतः रुक जाए), तो खुले पानी के वाष्पीकरण पर सबसे तार्किक असर क्या होगा?",
     "Thought experiment: if the factor called wind speed is removed (the air becomes perfectly still), what is the most logical effect on the evaporation of open water?",
     ["वाष्पीकरण धीमा पड़ जाएगा — सतह के ऊपर जमा भाप के कण वापस द्रव में आने की संभावना बढ़ जाएगी", "वाष्पीकरण पूरी तरह बंद हो जाएगा", "वाष्पीकरण तेज हो जाएगा", "कोई असर नहीं"],
     ["Evaporation would slow — the vapour particles gathered above the surface would stand more chance of returning to the liquid", "Evaporation would stop entirely", "Evaporation would quicken", "No effect"],
     0,
     "बहती हवा भाप को हटाती है; रुकी हवा में भाप सिर पर बैठती है।",
     "Moving air carries vapour off; in still air the vapour sits overhead."),

    ("evaporation-and-cooling", "hard",
     "दो कथन: (i) वाष्पीकरण में उड़ने वाले कण औसत कणों से अधिक गतिमान होते हैं। (ii) इसीलिए बचे द्रव की दशा में ठंडक आती है। सही विकल्प:",
     "Two statements: (i) The particles escaping in evaporation are more mobile than the average particles. (ii) That is why the remaining liquid's state brings coolness. The correct option:",
     ["दोनों सही हैं", "केवल (i) सही", "केवल (ii) सही", "दोनों गलत"],
     ["Both are correct", "Only (i)", "Only (ii)", "Both wrong"],
     0,
     "तेज कण निकले, धीमे बचे — बचे हुए का समूह ठंडा।",
     "The fast ones left, the slow stayed — the leftover crowd is cooler."),

    ("evaporation-and-cooling", "hard",
     "एक व्यापारी गर्म दिन में सब्ज़ियों पर बराबर पानी छिड़कता रहता है। इस अर्थव्यवस्था में वाष्पीकरण के दो लाभ एक साथ काम कर रहे हैं — चुनिए:",
     "A vendor keeps sprinkling water on vegetables on a hot day. In this economy, two benefits of evaporation work together — choose them:",
     ["ठंडक बनाए रखना + मुरझाने से बचाव (सतह गीली रहती है)", "सब्जियाँ उबालना + जमाना", "रंग बदलना + गंध लगाना", "वजन घटाना + सुखाना"],
     ["Keeping coolness + protection from wilting (the surface stays moist)", "Boiling and freezing the vegetables", "Changing colour and adding smell", "Reducing weight and drying"],
     0,
     "छिड़काव की ठंडक और नमी — दोनों वाष्पीकरण की मित्रता से।",
     "The sprinkle's coolness and moisture — both from the friendship of evaporation."),

    ("evaporation-and-cooling", "hard",
     "गर्मी में घर के अंदरूनी आँगन में छिड़काव से ठंडक बाहर की तुलना में ज्यादा देर टिकती है। वाष्पीकरण के कारकों में से किसकी मौजूदगी यहाँ निर्णायक है?",
     "In summer, the coolness from sprinkling inside the courtyard lasts longer than outside. Which of the evaporation factors is decisive in its presence here?",
     ["भीतर वायु गति कम — भाप धीरे-धीरे बनती है और ठंडक देर तक", "भीतर ताप अधिक", "भीतर सतही क्षेत्रफल अधिक", "भीतर आर्द्रता शून्य"],
     ["Inside, the wind speed is low — the vapour forms slowly and the coolness lasts", "Inside, the temperature is higher", "Inside, the surface area is larger", "Inside, the humidity is zero"],
     0,
     "धीमी वायु = धीमा, लंबा वाष्पीकरण = देर तक ठंडक।",
     "Slower wind = slower, longer evaporation = coolness that lasts."),

    ("evaporation-and-cooling", "hard",
     "चार परिस्थितियाँ: (क) धूप + हवा (ख) धूप + रुकी हवा (ग) छाया + हवा (घ) छाया + रुकी हवा। वाष्पीकरण सबसे तेज किसमें होगा?",
     "Four situations: (a) sun + wind (b) sun + still air (c) shade + wind (d) shade + still air. In which will evaporation be fastest?",
     ["(क) धूप + हवा — ताप और वायु गति दोनों कारक साथ", "(ख)", "(ग)", "(घ)"],
     ["(a) sun + wind — the two factors of temperature and wind speed together", "(b)", "(c)", "(d)"],
     0,
     "दो तेज़ कारकों का मिलन ही सबसे तेज़ वाष्पीकरण देता है।",
     "The union of two strong factors gives the fastest evaporation."),

    ("evaporation-and-cooling", "hard",
     "'छींटों से ठंडक' और 'छाया से ठंडक' — दोनों में वैज्ञानिक आधार की दृष्टि से अंतर स्पष्ट कीजिए:",
     "'Coolness from sprinkles' vs 'coolness from shade' — clarify the difference from the viewpoint of the scientific basis:",
     ["छींटों की ठंडक वाष्पीकरण से (जल की प्रक्रिया), छाया की ठंडक सूर्य-ताप से बचने से (गर्मी का न आना)", "दोनों वाष्पीकरण से", "दोनों बर्फ से", "दोनों हवा से"],
     ["The sprinkles' coolness is from evaporation (a process of water); the shade's coolness is from avoiding the sun's heat (heat not arriving)", "Both from evaporation", "Both from ice", "Both from air"],
     0,
     "एक ठंडक प्रक्रिया से आती है, दूसरी गर्मी के अनुपस्थित रहने से।",
     "One coolness comes from a process; the other from heat's absence."),

    ("evaporation-and-cooling", "hard",
     "वाष्पीकरण की दर बढ़ाने वाले तीन कारक और उसे घटाने वाले एक कारक का संतुलित विवरण कौन-सा है?",
     "Which is the balanced description of the three factors that raise the rate of evaporation and the one factor that lowers it?",
     ["बढ़ाते हैं — ताप, सतही क्षेत्रफल, वायु गति; घटाता है — आर्द्रता (बढ़ने पर)", "बढ़ाते हैं — आर्द्रता, दाब, रंग; घटाता है — ताप", "बढ़ाते हैं — चारों कारक", "घटाते हैं — चारों कारक"],
     ["Raisers — temperature, surface area, wind speed; reducer — humidity (when it rises)", "Raisers — humidity, pressure, colour; reducer — temperature", "All four factors raise it", "All four factors lower it"],
     0,
     "तीन तेज़ करते हैं, एक धीमा — यही संतुलन याद रखने योग्य है।",
     "Three quicken it, one slows — this balance is worth remembering."),
]
