# -*- coding: utf-8 -*-
"""C01 part 1 — Matter & Its States (chemistry chapter-01).
T1 matter-and-particles (E20/M21/H9) + T2 states-of-matter (E20/M21/H9).
Tuple: (topic, difficulty, q_hi, q_en, opts_hi[4], opts_en[4], correct_idx=0, expl_hi, expl_en)
All authored with correct_idx 0; answer-position rotation happens in gen script.
Only chapter-01 meta facts — particle nature (tiny, gaps, motion, diffusion),
matter = mass + volume, attraction order solid > liquid > gas.
"""

PART1 = [
    # ================= MATTER AND PARTICLES (50) =================
    # ---- easy (20) ----
    ("matter-and-particles", "easy",
     "पदार्थ की परिभाषा द्रव्यमान और आयतन को जोड़ते हुए चुनिए — पदार्थ वह है जो…",
     "Choose the definition of matter linking its mass and volume — matter is that which…",
     ["जिसमें द्रव्यमान हो और जो स्थान घेरे, उसे पदार्थ कहते हैं", "केवल दिखने वाली चमकदार वस्तुओं को", "केवल गैसों को", "केवल प्रकाश को"],
     ["Anything that has mass and occupies space is called matter", "Only shiny visible objects", "Only gases", "Only light"],
     0,
     "द्रव्यमान + आयतन — यही पदार्थ की पहचान है।",
     "Mass + volume — that is the identity of matter."),

    ("matter-and-particles", "easy",
     "पदार्थ किन दो राशियों से बनता है?",
     "Matter is characterised by which two quantities?",
     ["द्रव्यमान और आयतन", "लंबाई और चौड़ाई", "रंग और गंध", "चाल और वेग"],
     ["Mass and volume", "Length and breadth", "Colour and smell", "Speed and velocity"],
     0,
     "प्रत्येक पदार्थ का द्रव्यमान होता है और वह कुछ स्थान घेरता है।",
     "Every matter has mass and occupies some space."),

    ("matter-and-particles", "easy",
     "पदार्थ किन अत्यंत छोटे कणों से बना होता है?",
     "Matter is made up of what kind of extremely small particles?",
     ["अत्यंत छोटे कणों से जो नंगी आँख से नहीं दिखते", "बड़े टुकड़ों से जो साफ दिखते हैं", "प्रकाश किरणों से", "ध्वनि तरंगों से"],
     ["Extremely small particles invisible to the naked eye", "Large pieces clearly visible", "Light rays", "Sound waves"],
     0,
     "पदार्थ के कण इतने छोटे हैं कि बिना सूक्ष्मदर्शी नहीं देखे जा सकते।",
     "The particles of matter are so small that they cannot be seen without a microscope."),

    ("matter-and-particles", "easy",
     "पदार्थ के कणों के बीच क्या होता है?",
     "What is there between the particles of matter?",
     ["रिक्त स्थान (खाली जगह)", "ठोस पदार्थ", "पानी", "हवा ही हवा"],
     ["Empty space (gaps)", "Solid material", "Water", "Nothing but air"],
     0,
     "कणों के बीच रिक्त स्थान होता है — यही उनकी गति को संभव बनाता है।",
     "There are gaps between particles — this very fact makes their movement possible."),

    ("matter-and-particles", "easy",
     "पदार्थ के कण कैसे रहते हैं?",
     "How do the particles of matter remain?",
     ["निरंतर गतिमान", "पूर्णतः स्थिर", "केवल रात में चलते", "केवल गर्मी में चलते"],
     ["Constantly moving", "Perfectly still", "Moving only at night", "Moving only in summer"],
     0,
     "कण निरंतर गति में रहते हैं — यह पदार्थ की मूल प्रकृति है।",
     "Particles remain in constant motion — that is the basic nature of matter."),

    ("matter-and-particles", "easy",
     "खुले इत्र की शीशी से सुगंध पूरे कमरे में क्यों फैल जाती है?",
     "Why does the fragrance from an open perfume bottle spread through the whole room?",
     ["इत्र के कण गति करते हुए वायु के कणों के बीच घुल-मिल जाते हैं (विसरण)", "शीशी शोर मचाती है", "हवा शीशी को पी जाती है", "सुगंध रंग बदलती है"],
     ["The perfume's particles, moving about, mix into the air's particles (diffusion)", "The bottle makes noise", "The air swallows the bottle", "The fragrance changes colour"],
     0,
     "गतिमान कणों का फैलना ही विसरण है — यह कण-गति का प्रमाण है।",
     "The spreading of moving particles is diffusion — proof of particle motion."),

    ("matter-and-particles", "easy",
     "विसरण किस बात का प्रमाण है?",
     "Diffusion is the proof of what?",
     ["पदार्थ के कण निरंतर गतिमान रहते हैं", "पदार्थ भारी होता है", "पदार्थ ठंडा होता है", "पदार्थ रंगीन होता है"],
     ["The particles of matter are in constant motion", "Matter is heavy", "Matter is cold", "Matter is coloured"],
     0,
     "बिना गति के विसरण संभव नहीं — इसीलिए यह कण-गति का प्रमाण है।",
     "Without motion diffusion is impossible — hence it proves particle motion."),

    ("matter-and-particles", "easy",
     "रसोई में तड़का लगाते ही खुशबू दूर कमरे तक पहुँच जाती है। यह किसका उदाहरण है?",
     "The aroma of tempering spices reaches a far room as soon as food is cooked. This is an example of what?",
     ["विसरण का", "संघनन का", "जमने का", "उर्ध्वपातन का"],
     ["Diffusion", "Condensation", "Freezing", "Sublimation"],
     0,
     "गंध के कण हवा में घुलकर फैलते हैं — विसरण।",
     "The aroma's particles spread by mixing into air — diffusion."),

    ("matter-and-particles", "easy",
     "पदार्थ के कणों के बीच आकर्षण किस क्रम में होता है?",
     "In what order is the attraction between the particles of matter found?",
     ["ठोस > द्रव > गैस", "गैस > द्रव > ठोस", "द्रव > ठोस > गैस", "तीनों में बराबर"],
     ["Solid > liquid > gas", "Gas > liquid > solid", "Liquid > solid > gas", "Equal in all three"],
     0,
     "ठोस में आकर्षण सर्वाधिक, गैस में सबसे कम — क्रम ठोस > द्रव > गैस।",
     "Attraction is greatest in solids, least in gases — order solid > liquid > gas."),

    ("matter-and-particles", "easy",
     "निम्न में से क्या पदार्थ नहीं है?",
     "Which of the following is NOT matter?",
     ["प्रकाश", "पानी", "हवा", "लोहा"],
     ["Light", "Water", "Air", "Iron"],
     0,
     "प्रकाश का न द्रव्यमान होता है, न वह स्थान घेरता है — इसलिए वह पदार्थ नहीं।",
     "Light has neither mass nor does it occupy space — so it is not matter."),

    ("matter-and-particles", "easy",
     "हवा पदार्थ है — इसका आधार क्या है?",
     "Air is matter — what is the basis for this?",
     ["हवा का द्रव्यमान होता है और वह स्थान घेरती है", "हवा नीली दिखती है", "हवा चलती है इसलिए", "हवा ठंडी होती है"],
     ["Air has mass and it occupies space", "Air looks blue", "Because air moves", "Air is cold"],
     0,
     "द्रव्यमान + आयतन का होना ही हवा को पदार्थ सिद्ध करता है।",
     "Having mass and volume is what proves air to be matter."),

    ("matter-and-particles", "easy",
     "एक गिलास पानी में चुटकी भर शक्कर घुल जाती है और पानी का स्तर नहीं बढ़ता। इससे क्या पता चलता है?",
     "A pinch of sugar dissolves in a glass of water and the water level does not rise. What does this show?",
     ["पानी के कणों के बीच रिक्त स्थान है जिसमें शक्कर के कण समा गए", "पानी गायब हो गया", "शक्कर प्रकाश है", "पानी ठोस है"],
     ["There are gaps between water's particles where the sugar's particles fitted in", "The water vanished", "Sugar is light", "Water is a solid"],
     0,
     "कणों के बीच का रिक्त स्थान ही घुलने की जगह देता है।",
     "The gaps between particles provide the room for dissolving."),

    ("matter-and-particles", "easy",
     "कणों की निरंतर गति के कारण गैसें क्या करती हैं?",
     "Because of the constant motion of their particles, what do gases do?",
     ["अपने आप चारों ओर फैल जाती हैं", "एक कोने में जम जाती हैं", "ठोस बन जाती हैं", "शून्य हो जाती हैं"],
     ["They spread out in all directions by themselves", "They settle in one corner", "They become solid", "They vanish"],
     0,
     "स्वतंत्र व गतिमान कण स्वभाव से हर ओर दौड़ते हैं।",
     "Free, moving particles naturally rush in every direction."),

    ("matter-and-particles", "easy",
     "धुआँ बिना पंखे के भी कमरे में फैल जाता है। कारण?",
     "Smoke spreads in a room even without a fan. Why?",
     ["धुएँ के कण गतिमान होकर वायु में विसरित होते हैं", "धुआँ भारी होता है", "दीवारें धुएँ को खींचती हैं", "धुआँ ठंडा होता है"],
     ["Smoke's particles, being in motion, diffuse into the air", "Smoke is heavy", "The walls pull the smoke", "Smoke is cold"],
     0,
     "कण-गति + रिक्त स्थान = प्राकृतिक विसरण।",
     "Particle motion + gaps = natural diffusion."),

    ("matter-and-particles", "easy",
     "पदार्थ के कणों का आकार कैसा होता है?",
     "How small are the particles of matter?",
     ["अत्यंत छोटे — नंगी आँख से अदृश्य", "मटर के दाने जितने", "अंगूठे जितने", "कितने भी बड़े हो सकते हैं"],
     ["Extremely small — invisible to the naked eye", "Pea-sized", "Thumb-sized", "They can be of any big size"],
     0,
     "कण अत्यंत सूक्ष्म होते हैं — इसीलिए पदार्थ एक संतत चीज़ जैसा दिखता है।",
     "Particles are extremely tiny — that is why matter looks continuous."),

    ("matter-and-particles", "easy",
     "कमरे के एक कोने में आगबूझी खोलने पर दूसरे कोने तक गंध पहुँचना दर्शाता है —",
     "Opening an incense stick in one corner of a room, the smell reaching the other corner shows —",
     ["कण गतिमान हैं और उनके बीच रिक्त स्थान है", "कण ठोस हैं", "कण रंगीन हैं", "कमरा ठंडा है"],
     ["The particles are moving and there is space between them", "The particles are solid", "The particles are coloured", "The room is cold"],
     0,
     "गति और रिक्त स्थान दोनों का होना विसरण की शर्त है।",
     "Both motion and gaps are the conditions for diffusion."),

    ("matter-and-particles", "easy",
     "पदार्थ के कण निरंतर गति में रहते हैं — यह गति रुकती कब है?",
     "The particles of matter stay in constant motion — when does this motion stop?",
     ["कभी पूरी तरह नहीं रुकती", "रात में रुक जाती है", "बारिश में रुक जाती है", "कमरे में रुक जाती है"],
     ["It never stops completely", "It stops at night", "It stops in rain", "It stops indoors"],
     0,
     "कण-गति पदार्थ का स्थायी स्वभाव है।",
     "Particle motion is the permanent habit of matter."),

    ("matter-and-particles", "easy",
     "नमक का घोल चखने पर पूरे घोल का स्वाद नमकीन लगता है। कारण?",
     "A salt solution tastes salty throughout. Why?",
     ["नमक के कण जल के कणों के बीच फैलकर घुल गए", "नमक ऊपर तैरता है", "जल नमक खा गया", "गिलास नमकीन है"],
     ["Salt's particles spread and mixed between water's particles", "The salt floats on top", "The water ate the salt", "The glass is salty"],
     0,
     "घुले कणों का समान रूप से फैलना ही हर घूँट को नमकीन बनाता है।",
     "The even spread of dissolved particles makes every sip salty."),

    ("matter-and-particles", "easy",
     "गैसों के कण ठोस के कणों की तुलना में कैसे होते हैं?",
     "How are the particles of gases compared with those of solids?",
     ["अधिक स्वतंत्र और दूर-दूर", "अधिक बंधे और पास-पास", "बिल्कुल एक जैसे बंधे", "बड़े आकार के"],
     ["More free and far apart", "More bound and close together", "Exactly as bound", "Bigger in size"],
     0,
     "गैस में आकर्षण सबसे कम — कण सर्वाधिक स्वतंत्र।",
     "In gases the attraction is least — the particles are most free."),

    ("matter-and-particles", "easy",
     "किसी वस्तु को पदार्थ कहने के लिए उसका क्या होना जरूरी है?",
     "For calling something matter, what is essential?",
     ["द्रव्यमान होना और स्थान घेरना — दोनों", "केवल सुंदर दिखना", "केवल टिकना", "केवल चलना"],
     ["Having mass and occupying space — both", "Only looking beautiful", "Only being durable", "Only moving"],
     0,
     "द्रव्यमान और आयतन — दोनों विद्यमान हों तभी पदार्थ।",
     "Mass and volume — only when both exist is it matter."),

    # ---- medium (21) ----
    ("matter-and-particles", "medium",
     "खुले पानी के गिलास में शीशी की दवा (सिरप) डालने पर रंग धीरे-धीरे पूरे पानी में फैल जाता है बिना चलाए। कौन-सा तथ्य सामने आता है?",
     "When syrup is dropped into a glass of plain water, its colour slowly spreads through the whole water without stirring. Which fact comes forward?",
     ["जल के कण स्वयं गतिमान हैं — विसरण स्वतः होता है", "जल के कण बिल्कुल स्थिर हैं", "रंग जल से ऊपरी रूप से चिपकता है", "गिलास रंग खींचता है"],
     ["Water's particles are themselves moving — diffusion happens on its own", "Water's particles are perfectly still", "The colour just sticks on the water", "The glass pulls the colour"],
     0,
     "बिना हिलाए फैलाव केवल गतिमान कणों के कारण ही संभव है।",
     "Spreading without stirring is possible only because of moving particles."),

    ("matter-and-particles", "medium",
     "गर्म पानी में शक्कर ठंडे पानी की तुलना में जल्दी घुलती है। कणों की दृष्टि से कारण बताइए:",
     "Sugar dissolves faster in hot water than in cold. State the reason from the particles' viewpoint:",
     ["गर्म जल में कणों की गति तेज होती है, इसलिए विसरण शीघ्र होता है", "गर्म जल भारी होता है", "शक्कर गर्मी में पिघल जाती है पहले", "ठंडे जल में रिक्त स्थान नहीं होता"],
     ["In hot water the particles move faster, so diffusion happens sooner", "Hot water is heavier", "The sugar melts first in heat", "Cold water has no gaps"],
     0,
     "ताप बढ़ने से कण-गति तेज — विसरण भी तेज।",
     "Higher temperature speeds up particle motion — and diffusion too."),

    ("matter-and-particles", "medium",
     "दो कथन: (i) कणों के बीच रिक्त स्थान होता है। (ii) कण निरंतर गतिमान रहते हैं। सही विकल्प:",
     "Two statements: (i) There are gaps between particles. (ii) Particles remain in constant motion. The correct option:",
     ["दोनों सही हैं", "केवल (i) सही", "केवल (ii) सही", "दोनों गलत"],
     ["Both are correct", "Only (i)", "Only (ii)", "Both wrong"],
     0,
     "रिक्त स्थान और गति — दोनों कण-प्रकृति के तथ्य हैं।",
     "Gaps and motion — both are facts of particle nature."),

    ("matter-and-particles", "medium",
     "ठोस में कण अधिक बंधे क्यों होते हैं?",
     "Why are the particles more tightly bound in a solid?",
     ["कणों के बीच आकर्षण बल सबसे प्रबल होता है", "कणों के बीच नज़र आती है", "कण बड़े होते हैं", "कण गीले होते हैं"],
     ["The attraction between the particles is strongest", "The particles can see each other", "The particles are large", "The particles are wet"],
     0,
     "प्रबल आकर्षण ही ठोस के निश्चित आकार का आधार है।",
     "Strong attraction is the basis of a solid's fixed shape."),

    ("matter-and-particles", "medium",
     "गैस में कण लगभग स्वतंत्र क्यों घूमते हैं?",
     "Why do the particles of a gas roam almost freely?",
     ["कणों के बीच आकर्षण बहुत कम होता है", "कण बहुत बड़े होते हैं", "कणों में पंख होते हैं", "कण चुंबकित होते हैं"],
     ["The attraction between the particles is very small", "The particles are very large", "The particles have wings", "The particles are magnetised"],
     0,
     "कम आकर्षण = अधिक स्वतंत्रता — गैस का स्वभाव।",
     "Less attraction = more freedom — the gas's nature."),

    ("matter-and-particles", "medium",
     "विसरण गैसों में सबसे तेज क्यों होता है?",
     "Why is diffusion fastest in gases?",
     ["गैसों के कण सर्वाधिक स्वतंत्र और गतिमान होते हैं", "गैसें रंगीन होती हैं", "गैसें भारी होती हैं", "गैसों में कण नहीं होते"],
     ["The particles of gases are the most free and mobile", "Gases are coloured", "Gases are heavy", "Gases have no particles"],
     0,
     "स्वतंत्र व तेज गति वाले कण तुरंत घुल-मिल जाते हैं।",
     "Free, fast particles mix in no time."),

    ("matter-and-particles", "medium",
     "एक ही गंध वाला पदार्थ गर्म कमरे में जल्दी और ठंडे कमरे में देर से महसूस होता है। कारण?",
     "The same smelly substance is noticed sooner in a warm room and later in a cold one. Why?",
     ["ताप अधिक होने पर कणों की गति और विसरण दर बढ़ जाती है", "ठंडे कमरे में नाक बंद हो जाती है", "गर्म कमरे में दीवारें गंध बनाती हैं", "ठंड में गंध गिर जाती है"],
     ["At higher temperature the particles' motion and diffusion rate increase", "The nose closes in a cold room", "Warm walls create the smell", "The smell falls down in cold"],
     0,
     "ताप-वृद्धि कण-गति तेज करती है — विसरण भी।",
     "A rise in temperature quickens particle motion — and diffusion."),

    ("matter-and-particles", "medium",
     "वायु को पदार्थ मानने का प्रयोग: कसी हुई गेंद में हवा भरने पर गेंद का वजन बढ़ता है। यह किसे सिद्ध करता है?",
     "Experiment proving air is matter: pumping air into a tight ball increases the ball's weight. What does this prove?",
     ["हवा का द्रव्यमान होता है", "हवा का रंग नीला है", "हवा गंधहीन है", "गेंद रबर की है"],
     ["Air has mass", "Air's colour is blue", "Air is odourless", "The ball is of rubber"],
     0,
     "वजन बढ़ना = भरी गई हवा का द्रव्यमान जुड़ना।",
     "The weight gain = the mass of the air added."),

    ("matter-and-particles", "medium",
     "पदार्थ के कणों के बीच का रिक्त स्थान किसका प्रत्यक्ष सबूत है?",
     "The empty space between the particles of matter is direct evidence of what?",
     ["कणों के बीच दूरी होने का — जैसे घुलने में स्तर न बढ़ना", "कणों के रंग का", "कणों की गति का — यह अलग तथ्य है", "कणों के आकार का"],
     ["That there is distance between particles — as when dissolving raises no level", "Of the particles' colour", "Of the particles' motion — a separate fact", "Of the particles' size"],
     0,
     "स्तर न बढ़ना बताता है कि नए कण पुराने कणों के बीच के अंतराल में समा गए।",
     "The level not rising shows the new particles slipped into the old particles' gaps."),

    ("matter-and-particles", "medium",
     "कथन: 'पदार्थ के कण इतने पास-पास हैं कि बीच में कुछ नहीं होता।' इस कथन का सही निर्णय कीजिए:",
     "Statement: 'The particles of matter are so close that there is nothing between them.' Judge this statement correctly:",
     ["गलत — कणों के बीच रिक्त स्थान होता है", "सही — बीच पूरी तरह भरा रहता है", "आंशिक सही — केवल गैसों में खाली है", "सही — केवल द्रवों में खाली है"],
     ["Wrong — there is empty space between the particles", "Correct — the space is fully packed", "Partly right — only gases have gaps", "Correct — only liquids have gaps"],
     0,
     "तीनों अवस्थाओं में कणों के बीच अंतराल है — फर्क केवल मात्रा का है।",
     "In all three states there are gaps between particles — only the amount differs."),

    ("matter-and-particles", "medium",
     "अगरबत्ती का धुआँ किसी ओर झुके बिना सीधा ऊपर उठता है और फिर फैलता है। कण-सिद्धांत से इसकी व्याख्या क्या है?",
     "Incense smoke rises straight up without tilting and then spreads. What is its explanation from the particle theory?",
     ["धुएँ के गतिमान कण वायु के गतिमान कणों में मिलकर विसरित हो जाते हैं", "धुआँ दीवार से टकराता है", "धुएँ के कण नीचे गिरते हैं", "वायु कणों को खा जाता है"],
     ["The moving smoke particles mix into the moving air particles and diffuse", "The smoke hits the walls", "The smoke particles fall down", "It eats up the air particles"],
     0,
     "दोनों कण-परिवार गतिमान हैं — मिलना स्वाभाविक है।",
     "Both particle families are moving — mixing is natural."),

    ("matter-and-particles", "medium",
     "गीले कपड़ों को बासी हवा वाले बंद कमरे में टाँगने पर कमरे में नमी क्यों बढ़ जाती है? (कण-दृष्टि से)",
     "Why does hanging wet clothes in a stuffy closed room raise the room's dampness? (from the particle viewpoint)",
     ["कपड़ों के जल-कण वायु में विसरित होकर फैल जाते हैं", "कपड़े कमरे को ढक देते हैं", "दीवारें पानी पीती हैं", "कमरा गर्म हो जाता है"],
     ["The water particles from the clothes diffuse and spread into the air", "The clothes cover the room", "The walls drink the water", "The room warms up"],
     0,
     "जल-कणों का वायु में विसरण ही नमी का कारण है।",
     "The diffusion of water particles into air is the cause of dampness."),

    ("matter-and-particles", "medium",
     "तीन कथन: (i) कण अत्यंत छोटे हैं। (ii) कणों के बीच आकर्षण होता है। (iii) कण अचल रहते हैं। गलत कथन कौन-सा है?",
     "Three statements: (i) Particles are extremely small. (ii) There is attraction between particles. (iii) Particles stay motionless. Which is wrong?",
     ["कथन (iii)", "कथन (i)", "कथन (ii)", "तीनों सही"],
     ["Statement (iii)", "Statement (i)", "Statement (ii)", "All three correct"],
     0,
     "कण अचल नहीं — निरंतर गतिमान रहते हैं।",
     "Particles are not motionless — they stay in constant motion."),

    ("matter-and-particles", "medium",
     "एक बंद टीन में अमोनिया खोलने पर पास बैठा विद्यार्थी गंध पहले और दूर बैठा बाद में महसूस करता है। यह अंतर किस तथ्य का परिणाम है?",
     "When an ammonia tin is opened, a nearby student smells it first and a far-off one later. This difference results from which fact?",
     ["विसरण में समय लगता है — गंध के कण धीरे-धीरे दूर तक पहुँचते हैं", "दूर के विद्यार्थी की नाक तेज है", "अमोनिया पीछे की ओर जाता है", "गंध केवल ऊपर रहती है"],
     ["Diffusion takes time — the smell's particles reach far off gradually", "The far student's nose is sharper", "Ammonia moves backwards", "The smell stays only up high"],
     0,
     "विसरण तुरंत दूर तक नहीं पहुँचता — कण-गति को समय चाहिए।",
     "Diffusion does not reach afar instantly — particle motion needs time."),

    ("matter-and-particles", "medium",
     "पदार्थ के गुण (आकार, अवस्था, प्रवाह) का मूल कारण कणों की क्या विशेषताएँ हैं?",
     "What features of the particles are the root cause of matter's properties (shape, state, flow)?",
     ["कणों के बीच का अंतराल, आकर्षण और गति", "कणों का रंग और स्वाद", "कणों की गंध", "कणों की चमक"],
     ["The gaps, attraction and motion of the particles", "The colour and taste of the particles", "The smell of the particles", "The shine of the particles"],
     0,
     "अंतराल + आकर्षण + गति — यही तीन अवस्थाओं का भेद खोलते हैं।",
     "Gaps + attraction + motion — these three unlock the difference of states."),

    ("matter-and-particles", "medium",
     "किसी ठोस में रिक्त स्थान कम और गैस में बहुत अधिक होता है। इसका सीधा परिणाम क्या है?",
     "A solid has little empty space and a gas has a great deal. What is the direct consequence?",
     ["ठोस संपीड्य नहीं, गैस अत्यधिक संपीड्य होती है", "ठोस बहता है, गैस नहीं", "ठोस हल्का, गैस भारी", "दोनों समान व्यवहार करते हैं"],
     ["A solid is not compressible, a gas is highly compressible", "A solid flows, a gas does not", "A solid is light, a gas heavy", "Both behave alike"],
     0,
     "अधिक रिक्त स्थान = कणों को दबाने की जगह = संपीड्यता।",
     "More empty space = room to press the particles = compressibility."),

    ("matter-and-particles", "medium",
     "विसरण की क्रिया में कण एक दिशा में नहीं, बल्कि हर दिशा में फैलते हैं। इससे कण-गति की प्रकृति के बारे में क्या पता चलता है?",
     "In diffusion the particles spread not in one direction but in every direction. What does this tell about the nature of particle motion?",
     ["कणों की गति अव्यवस्थित (यादृच्छिक) होती है, निश्चित पथ पर नहीं", "कण एक पंक्ति में चलते हैं", "कण वापस लौटते नहीं", "कण केवल नीचे जाते हैं"],
     ["The particles' motion is random, not on a fixed path", "The particles march in a line", "The particles never return", "The particles only go downward"],
     0,
     "सब ओर फैलाव यादृच्छिक गति का संकेत है।",
     "Spreading everywhere signals random motion."),

    ("matter-and-particles", "medium",
     "दो कथन: (i) विसरण ठोस, द्रव, गैस तीनों में होता है, पर गैस में सर्वाधिक तेज। (ii) विसरण के लिए कणों का गतिमान होना ही पर्याप्त है, रिक्त स्थान की जरूरत नहीं। सही विकल्प:",
     "Two statements: (i) Diffusion occurs in solids, liquids and gases, but is fastest in gases. (ii) For diffusion, particles being in motion is enough; no empty space is needed. The correct option:",
     ["(i) सही, (ii) गलत", "दोनों सही", "दोनों गलत", "(i) गलत, (ii) सही"],
     ["(i) correct, (ii) wrong", "Both correct", "Both wrong", "(i) wrong, (ii) correct"],
     0,
     "घुलने-मिलने के लिए अंतराल भी जरूरी है — केवल गति पर्याप्त नहीं।",
     "Gaps too are needed for mixing — motion alone is not enough."),

    ("matter-and-particles", "medium",
     "एक ही द्रव (जल) की बूँद गर्म प्लेट पर फैलकर जल्दी गायब होती है, जबकि ठंडी प्लेट पर टिकी रहती है। कण-गति की दृष्टि से अंतर चुनिए:",
     "The same drop of water spreads and vanishes quickly on a hot plate but stays on a cold one. Choose the difference from the particle-motion viewpoint:",
     ["गर्मी में जल-कणों की गति बहुत तेज हो जाती है", "ठंडी प्लेट बूँद को पकड़ लेती है", "गर्म प्लेट बूँद को खा जाती है", "बूँद का आकार बदल जाता है"],
     ["In heat the water particles' motion becomes very fast", "The cold plate grips the drop", "The hot plate eats the drop", "The drop's shape changes"],
     0,
     "ताप-वृद्धि कण-गति बढ़ाती है — बूँद के कण जल्दी उड़ते हैं।",
     "Rising temperature speeds particle motion — the drop's particles escape sooner."),

    ("matter-and-particles", "medium",
     "पदार्थ की 'संतत दिखने वाली' सतह के बावजूद उसके भीतर क्या चल रहा है?",
     "Despite a matter's 'continuous-looking' surface, what is going on inside it?",
     ["अदृश्य कणों का खेल — उनका अंतराल, आकर्षण और निरंतर गति", "पूर्ण शांति और ठोस भराव", "केवल रंग के कण", "केवल प्रकाश का भ्रम"],
     ["The play of invisible particles — their gaps, attraction and ceaseless motion", "Total stillness and solid packing", "Only colour particles", "Only an illusion of light"],
     0,
     "दिखना संतत, भीतर कण-कण — यही पदार्थ का वास्तविक चेहरा है।",
     "Continuous to the eye, particulate within — that is matter's true face."),

    # ---- hard (9) ----
    ("matter-and-particles", "medium",
     "एक चम्मच नमक पानी में घुलकर पूरी तरह अदृश्य हो गया, फिर भी घोल का हर घूँट नमकीन है। नमक के कणों के विषय में इसका निष्कर्ष क्या है?",
     "A spoonful of salt dissolved in water and became completely invisible, yet every sip of the solution tastes salty. What does this conclude about the salt's particles?",
     ["कण इतने सूक्ष्म हैं कि आँख से नहीं दिखते और जल-कणों के बीच समा जाते हैं — नष्ट नहीं होते",
      "नमक के कण नष्ट हो गए",
      "नमक ने पानी के कणों को नमकीन बना दिया",
      "नमक पानी की सतह पर तैरता रहता है"],
     ["The particles are so minute that they cannot be seen and they fit among the water particles — they are not destroyed",
      "The salt's particles were destroyed",
      "The salt made the water's particles salty",
      "The salt keeps floating on the water's surface"],
     0,
     "अदृश्य होना गायब होना नहीं — सूक्ष्म कण जल-कणों के बीच फैल गए।",
     "Becoming invisible is not becoming nothing — the minute particles spread among the water particles."),

    ("matter-and-particles", "hard",
     "कथन-विश्लेषण: (i) विसरण स्वतः होता है। (ii) विसरण में कणों को बाहरी मिलाने की जरूरत नहीं। (iii) विसरण केवल गैसों तक सीमित है। सही कथनों का समूह:",
     "Statement analysis: (i) Diffusion happens on its own. (ii) In diffusion the particles need no external stirring. (iii) Diffusion is limited to gases only. The group of correct statements:",
     ["(i) और (ii) सही, (iii) गलत", "तीनों सही", "केवल (iii) सही", "(i) गलत, (ii) सही, (iii) सही"],
     ["(i) and (ii) correct, (iii) wrong", "All three correct", "Only (iii) correct", "(i) wrong, (ii) correct, (iii) correct"],
     0,
     "विसरण तीनों अवस्थाओं का सहज गुण है — गैस में सबसे तेज।",
     "Diffusion is a spontaneous property of all three states — fastest in gases."),

    ("matter-and-particles", "hard",
     "यदि किसी काल्पनिक पदार्थ के कणों के बीच रिक्त स्थान बिल्कुल शून्य हो जाए, तो सबसे पहले कौन-सा गुण असंभव हो जाएगा?",
     "If the empty space between the particles of an imaginary matter became exactly zero, which property would become impossible first?",
     ["संपीड्यता — दबाने के लिए जगह ही नहीं बचेगी", "रंग", "द्रव्यमान", "आयतन"],
     ["Compressibility — no room would remain to press", "Colour", "Mass", "Volume"],
     0,
     "संपीड़न का अर्थ ही है अंतराल घटाना — अंतराल शून्य तो संपीडन अर्थहीन।",
     "Compression means reducing the gaps — zero gaps make compression meaningless."),

    ("matter-and-particles", "hard",
     "गैस भरे गुब्बारे के कण निरंतर दीवारों से टकराते रहते हैं। इस गति का कारण-श्रृंखला क्या है?",
     "The particles of an inflated balloon keep striking the walls constantly. What is the cause-chain of this motion?",
     ["कण स्वभाव से गतिमान + बीच आकर्षण न्यून + अंतराल विपुल = निरंतर टक्कर", "दीवारें कणों को बुलाती हैं", "गुब्बारे का रंग टक्कर देता है", "हवा बाहर से धक्का देती रहती है"],
     ["Particles are inherently mobile + little attraction between them + ample gaps = ceaseless collisions", "The walls call the particles", "The balloon's colour causes collisions", "Outside air keeps pushing"],
     0,
     "गैस-कणों की तीन विशेषताएँ मिलकर निरंतर टकराव देती हैं।",
     "Three traits of gas particles together produce ceaseless collisions."),

    ("matter-and-particles", "hard",
     "एक बंद कमरे में ऊपरी कोने में छोड़ी गई सुगंध धीरे-धीरे नीचे तक आती है — यहाँ तक कि गुरुत्व के विपरीत भी। इसका सर्वाधिक तर्कसंगत कारण क्या है?",
     "In a closed room a fragrance released in an upper corner slowly reaches even the bottom — against gravity too. What is the most logical reason?",
     ["कणों की यादृच्छिक गति हर दिशा में विसरण करा देती है", "सुगंध हल्की होती है इसलिए गिरती नहीं", "फर्श सुगंध को खींचता है", "पंखा चुपचाप चलता है"],
     ["The particles' random motion drives diffusion in every direction", "The fragrance is light, so it does not fall", "The floor pulls the fragrance", "A fan runs secretly"],
     0,
     "यादृच्छिक गति दिशा नहीं चुनती — इसलिए गुरुत्व के विरुद्ध भी विसरण होता है।",
     "Random motion picks no direction — hence diffusion occurs even against gravity."),

    ("matter-and-particles", "hard",
     "कणों के बीच आकर्षण: ठोस > द्रव > गैस। इस क्रम का तार्किक परिणाम चुनिए:",
     "Attraction between particles: solid > liquid > gas. Choose the logical consequence of this order:",
     ["ठोस का आकार स्थिर, द्रव बहता, गैस फैलती है", "तीनों का आकार स्थिर", "तीनों बहते हैं", "ठोस बहता, गैस स्थिर"],
     ["A solid keeps its shape, a liquid flows, a gas spreads", "All three keep fixed shape", "All three flow", "A solid flows, a gas is fixed"],
     0,
     "आकर्षण जितना कम, कण उतने स्वतंत्र — व्यवहार उतना ढीला।",
     "The weaker the attraction, the freer the particles — the looser the behaviour."),

    ("matter-and-particles", "hard",
     "तीन कथन: (i) वायु पदार्थ है। (ii) प्रकाश पदार्थ नहीं है। (iii) ध्वनि पदार्थ है। सही कथनों का समूह चुनिए:",
     "Three statements: (i) Air is matter. (ii) Light is not matter. (iii) Sound is matter. Choose the group of correct statements:",
     ["(i) और (ii) सही, (iii) गलत", "तीनों सही", "केवल (iii) सही", "(i) गलत, (ii) गलत, (iii) सही"],
     ["(i) and (ii) correct, (iii) wrong", "All three correct", "Only (iii) correct", "(i) wrong, (ii) wrong, (iii) correct"],
     0,
     "ध्वनि में द्रव्यमान-आयतन नहीं — वह तरंग है, पदार्थ नहीं।",
     "Sound has no mass or volume — it is a wave, not matter."),

    ("matter-and-particles", "hard",
     "दो गैसें एक बर्तन में छोड़ने पर कुछ ही देर में पूरे बर्तन में समान रूप से मिल जाती हैं। सोच-परीक्षण: यदि गैस के कण बिल्कुल स्थिर होते, तो क्या होता?",
     "Two gases released in a vessel mix uniformly throughout it within a while. Thought experiment: if the gas particles were perfectly still, what would happen?",
     ["मिश्रण नहीं बनता — दोनों गैसें अलग परतों में रहतीं", "मिश्रण और तेज़ होता", "कोई अंतर नहीं पड़ता", "बर्तन फट जाता"],
     ["No mixture would form — both gases would stay as separate layers", "Mixing would be even faster", "No difference would occur", "The vessel would burst"],
     0,
     "मिश्रण का इंजन कण-गति है — गति रुकी तो विसरण रुका।",
     "Particle motion is the engine of mixing — stop the motion, stop the diffusion."),

    ("matter-and-particles", "hard",
     "चाय में चीनी घुलने के बाद चाय का स्वाद हर घूँट में समान मीठा लगता है। इसकी कण-स्तरीय व्याख्या क्या है?",
     "After sugar dissolves in tea, the tea tastes equally sweet in every sip. What is the particle-level explanation?",
     ["घुले शक्कर-कण जल-कणों के बीच समान रूप से विसरित हो जाते हैं", "शक्कर तल में इकट्ठी रहती है", "हर घूँट में नई शक्कर डाली जाती है", "चाय शक्कर को याद रखती है"],
     ["The dissolved sugar particles diffuse uniformly between the water particles", "The sugar gathers at the bottom", "Fresh sugar is added to every sip", "The tea remembers the sugar"],
     0,
     "समान विसरण = समान मिठास।",
     "Uniform diffusion = uniform sweetness."),

    ("matter-and-particles", "hard",
     "'पदार्थ के कणों के बीच केवल खाली जगह ही नहीं, बल्कि एक खिंचाव (आकर्षण) भी है' — इस तथ्य का सबसे स्पष्ट समर्थन कौन-सा प्रेक्षण देता है?",
     "'Between the particles of matter there is not just empty space but also a pull (attraction)' — which observation gives the clearest support to this fact?",
     ["ठोस कण अपनी जगह सरकते नहीं — प्रबल खिंचाव उन्हें बाँधे रखता है", "गैस फैलती है", "पानी गीला है", "रंग फैलता है"],
     ["A solid's particles do not drift from their places — a strong pull keeps them bound", "A gas spreads", "Water is wet", "A colour spreads"],
     0,
     "आकर्षण का सबसे सीधा प्रमाण ठोस की स्थिरता है।",
     "A solid's fixity is the most direct proof of attraction."),

    # ================= STATES OF MATTER (50) =================
    # ---- easy (20) ----
    ("states-of-matter", "easy",
     "पदार्थ की मुख्य अवस्थाएँ कौन-सी हैं?",
     "What are the main states of matter?",
     ["ठोस, द्रव और गैस", "केवल ठोस और गैस", "केवल द्रव और गैस", "ठोस, द्रव और प्रकाश"],
     ["Solid, liquid and gas", "Only solid and gas", "Only liquid and gas", "Solid, liquid and light"],
     0,
     "हमारे अध्ययन की तीन मुख्य अवस्थाएँ — ठोस, द्रव, गैस।",
     "The three main states of our study — solid, liquid, gas."),

    ("states-of-matter", "easy",
     "ठोस में कण कैसे स्थित होते हैं?",
     "How are the particles arranged in a solid?",
     ["सबसे संघन (पास-पास) और स्थिर", "दूर-दूर और मुक्त", "बिखरे हुए और उड़ते हुए", "केवल सतह पर"],
     ["Most compact (close together) and fixed", "Far apart and free", "Scattered and flying", "Only on the surface"],
     0,
     "ठोस के कण सबसे ज्यादा संकुचित और अपनी जगह जमे रहते हैं।",
     "A solid's particles are the most packed and stay fixed in their places."),

    ("states-of-matter", "easy",
     "द्रव का प्रमुख गुण क्या है?",
     "What is the chief property of a liquid?",
     ["प्रवाह — बहने की क्षमता", "निश्चित आकार", "संपीड्यता सबसे अधिक", "कणों का स्थिर रहना"],
     ["Fluidity — the ability to flow", "A fixed shape", "Highest compressibility", "Particles staying fixed"],
     0,
     "द्रव की पहचान ही उसका बहना है।",
     "A liquid's very identity is its flowing."),

    ("states-of-matter", "easy",
     "गैस के कण कैसे होते हैं?",
     "How are the particles of a gas?",
     ["सर्वाधिक स्वतंत्र और दूर-दूर", "सबसे संघन और बंधे", "आपस में जकड़े", "निश्चित स्थान पर जड़"],
     ["The most free and far apart", "The most compact and bound", "Locked with each other", "Rooted at fixed spots"],
     0,
     "गैस में कण लगभग बिना बंधन घूमते हैं।",
     "In a gas the particles roam nearly unbound."),

    ("states-of-matter", "easy",
     "किस अवस्था में कण सर्वाधिक संघन होते हैं?",
     "In which state are the particles most compact?",
     ["ठोस में", "द्रव में", "गैस में", "तीनों में समान"],
     ["In a solid", "In a liquid", "In a gas", "The same in all three"],
     0,
     "ठोस के कण सबसे पास-पास रहते हैं।",
     "A solid's particles stay closest together."),

    ("states-of-matter", "easy",
     "कौन-सी अवस्था संपीड्य होती है?",
     "Which state is compressible?",
     ["गैस", "ठोस", "द्रव", "कोई नहीं"],
     ["Gas", "Solid", "Liquid", "None"],
     0,
     "गैस के कणों के बीच बड़े अंतराल — दबाने पर सिकुड़ जाती है।",
     "Large gaps between gas particles — it shrinks when pressed."),

    ("states-of-matter", "easy",
     "ठोस का आकार और आयतन कैसा होता है?",
     "How are the shape and volume of a solid?",
     ["दोनों निश्चित", "दोनों परिवर्तनशील", "आकार परिवर्तनशील, आयतन निश्चित", "आकार निश्चित, आयतन परिवर्तनशील"],
     ["Both fixed", "Both variable", "Shape variable, volume fixed", "Shape fixed, volume variable"],
     0,
     "प्रबल आकर्षण ठोस को निश्चित आकार-आयतन देता है।",
     "Strong attraction gives a solid its fixed shape and volume."),

    ("states-of-matter", "easy",
     "द्रव का आकार और आयतन कैसा होता है?",
     "How are the shape and volume of a liquid?",
     ["आकार बर्तन के अनुसार बदलता है, आयतन निश्चित रहता है", "दोनों निश्चित", "दोनों बदलते हैं", "आकार निश्चित, आयतन बदलता"],
     ["Shape changes with the container, volume stays fixed", "Both fixed", "Both change", "Shape fixed, volume changes"],
     0,
     "द्रव बहता है पर उसकी मात्रा (आयतन) वही रहती है।",
     "A liquid flows, but its quantity (volume) stays the same."),

    ("states-of-matter", "easy",
     "गैस का आकार और आयतन कैसा होता है?",
     "How are the shape and volume of a gas?",
     ["दोनों बर्तन के अनुसार — गैस पूरे बर्तन को भर देती है", "दोनों निश्चित", "केवल आकार निश्चित", "केवल आयतन निश्चित"],
     ["Both as per the container — a gas fills the whole vessel", "Both fixed", "Only shape fixed", "Only volume fixed"],
     0,
     "मुक्त कण कहीं भी जाते हैं — गैस उपलब्ध पूरा स्थान घेर लेती है।",
     "Free particles go anywhere — a gas occupies all the space available."),

    ("states-of-matter", "easy",
     "पानी किस अवस्था का पदार्थ है?",
     "Water is matter of which state?",
     ["द्रव", "ठोस", "गैस", "इनमें से कोई नहीं"],
     ["Liquid", "Solid", "Gas", "None of these"],
     0,
     "पानी बहता है और बर्तन का आकार ले लेता है — द्रव।",
     "Water flows and takes its container's shape — a liquid."),

    ("states-of-matter", "easy",
     "बर्फ किस अवस्था का उदाहरण है?",
     "Ice is an example of which state?",
     ["ठोस", "द्रव", "गैस", "उर्ध्वपातन"],
     ["Solid", "Liquid", "Gas", "Sublimation"],
     0,
     "बर्फ का आकार निश्चित — ठोस अवस्था।",
     "Ice has a fixed shape — the solid state."),

    ("states-of-matter", "easy",
     "ऑक्सीजन सामान्यतः किस अवस्था में होती है?",
     "In which state does oxygen normally exist?",
     ["गैस", "ठोस", "द्रव", "प्लाज़्मा"],
     ["Gas", "Solid", "Liquid", "Plasma"],
     0,
     "ऑक्सीजन के मुक्त कण हवा में घूमते हैं — गैस।",
     "Oxygen's free particles roam the air — a gas."),

    ("states-of-matter", "easy",
     "पत्थर, दूध और हवा — तीनों की अवस्थाओं का सही क्रम है:",
     "Stone, milk and air — the correct order of their states is:",
     ["ठोस, द्रव, गैस", "द्रव, ठोस, गैस", "गैस, द्रव, ठोस", "ठोस, गैस, द्रव"],
     ["Solid, liquid, gas", "Liquid, solid, gas", "Gas, liquid, solid", "Solid, gas, liquid"],
     0,
     "पत्थर ठोस, दूध द्रव, हवा गैस — तीनों अवस्थाओं के जीते-जागते उदाहरण।",
     "Stone solid, milk liquid, air gas — living examples of all three states."),

    ("states-of-matter", "easy",
     "किस अवस्था में कण सर्वाधिक स्वतंत्र रूप से गति करते हैं?",
     "In which state do the particles move most freely?",
     ["गैस में", "ठोस में", "द्रव में", "तीनों में समान"],
     ["In a gas", "In a solid", "In a liquid", "The same in all three"],
     0,
     "गैस में बंधन सबसे कम — स्वतंत्रता सबसे अधिक।",
     "Least binding in a gas — the most freedom."),

    ("states-of-matter", "easy",
     "ठोस अपना आकार क्यों नहीं बदलता?",
     "Why does a solid not change its shape?",
     ["कण प्रबल आकर्षण से अपनी स्थान पर जकड़े रहते हैं", "कण बहुत बड़े होते हैं", "कण गीले होते हैं", "कण नींद में होते हैं"],
     ["Its particles stay locked in place by strong attraction", "Its particles are very large", "Its particles are wet", "Its particles are asleep"],
     0,
     "प्रबल आकर्षण = स्थिर कण = स्थिर आकार।",
     "Strong attraction = fixed particles = fixed shape."),

    ("states-of-matter", "easy",
     "द्रव क्यों बहता है?",
     "Why does a liquid flow?",
     ["उसके कण आकर्षण में ढील होने से सरक सकते हैं", "उसके कण उड़ते हैं", "उसके कण जड़ हैं", "उसका आकार निश्चित है"],
     ["Its particles, loosely held, can slide past one another", "Its particles fly away", "Its particles are inert", "Its shape is fixed"],
     0,
     "ठोस से कम आकर्षण द्रव के कणों को सरकने देता है।",
     "Attraction weaker than in solids lets a liquid's particles slide."),

    ("states-of-matter", "easy",
     "गैस हमेशा बर्तन का पूरा आकार क्यों ले लेती है?",
     "Why does a gas always take the full shape of its container?",
     ["उसके मुक्त कण हर ओर दौड़कर पूरा स्थान भर देते हैं", "वह बर्तन से डरती है", "बर्तन उसे खींचता है", "वह भारी होती है"],
     ["Its free particles race everywhere and fill all the space", "It fears the container", "The container pulls it", "It is heavy"],
     0,
     "मुक्त कण + निरंतर गति = पूरा बर्तन भर जाना।",
     "Free particles + constant motion = the whole vessel gets filled."),

    ("states-of-matter", "easy",
     "तीनों अवस्थाओं में विसरण दर सबसे अधिक किसमें होती है?",
     "Among the three states, in which is the diffusion rate the highest?",
     ["गैस में", "ठोस में", "द्रव में", "तीनों में बराबर"],
     ["In gases", "In solids", "In liquids", "Equal in all three"],
     0,
     "सर्वाधिक स्वतंत्र कण — सर्वाधिक तेज विसरण।",
     "The most free particles — the fastest diffusion."),

    ("states-of-matter", "easy",
     "किसी चीज़ को 'संपीड्य' कहने का अर्थ है —",
     "To call something 'compressible' means —",
     ["दबाने पर उसका आयतन घट सकता है", "दबाने पर वह रंग बदलती है", "वह बहती है", "वह पिघलती है"],
     ["Its volume can be reduced by pressing", "It changes colour under pressure", "It flows", "It melts"],
     0,
     "संपीड्यता = दबाव पर आयतन घटने की क्षमता।",
     "Compressibility = the capacity to shrink in volume under pressure."),

    ("states-of-matter", "easy",
     "नाइट्रोजन और ऑक्सीजन जैसी हवा की गैसें किस अवस्था में होने से बर्तन का पूरा आकार लेती हैं?",
     "Gases of the air like nitrogen and oxygen take the full shape of the vessel because of being in which state?",
     ["गैस अवस्था में — कण मुक्त व गतिमान", "ठोस अवस्था में", "द्रव अवस्था में", "किसी अवस्था में नहीं"],
     ["The gaseous state — particles free and moving", "The solid state", "The liquid state", "In no state"],
     0,
     "गैस-अवस्था के मुक्त कण ही उपलब्ध स्थान भर देते हैं।",
     "The free particles of the gaseous state fill the available space."),

    # ---- medium (21) ----
    ("states-of-matter", "medium",
     "ठोस, द्रव, गैस में कणों के बीच आकर्षण का तुलनात्मक क्रम दिया है — सही क्रम चुनिए:",
     "A comparative order of the attraction between particles in solid, liquid, gas is given — choose the correct one:",
     ["ठोस (सर्वाधिक) → द्रव → गैस (न्यूनतम)", "गैस (सर्वाधिक) → द्रव → ठोस", "द्रव (सर्वाधिक) → ठोस → गैस", "तीनों में एक समान"],
     ["Solid (highest) → liquid → gas (lowest)", "Gas (highest) → liquid → solid", "Liquid (highest) → solid → gas", "Identical in all three"],
     0,
     "आकर्षण घटता क्रम — ठोस, द्रव, गैस।",
     "Attraction in decreasing order — solid, liquid, gas."),

    ("states-of-matter", "medium",
     "एक ही पदार्थ की तीन अवस्थाओं में कणों के बीच की दूरी का शुद्ध क्रम क्या है?",
     "What is the exact order of the inter-particle distance in the three states of the same substance?",
     ["गैस > द्रव > ठोस", "ठोस > द्रव > गैस", "द्रव > ठोस > गैस", "तीनों में बराबर"],
     ["Gas > liquid > solid", "Solid > liquid > gas", "Liquid > solid > gas", "Equal in all three"],
     0,
     "दूरी बढ़ती क्रम में — ठोस से द्रव से गैस।",
     "Distance in increasing order — solid to liquid to gas."),

    ("states-of-matter", "medium",
     "गैस को सिलेंडर में क्यों भरा जा सकता है?",
     "Why can a gas be filled into a cylinder?",
     ["गैस संपीड्य है — कणों के बीच के बड़े अंतराल में दबाव से कण पास आ जाते हैं", "गैस ठोस है", "गैस भारी है", "सिलेंडर गैस खींचता है"],
     ["A gas is compressible — under pressure the particles close into the large gaps between them", "A gas is solid", "A gas is heavy", "The cylinder sucks the gas"],
     0,
     "अंतराल की बहुलता ही गैस के दबकर सिमटने की अनुमति देती है।",
     "The abundance of gaps lets a gas shrink under pressure."),

    ("states-of-matter", "medium",
     "रेत ठोस है, पर उसका आकार बर्तन के साथ बदल जाता है। क्या यह ठोस की परिभाषा तोड़ता है?",
     "Sand is a solid, yet its shape changes with the container. Does this break the definition of a solid?",
     ["नहीं — हर रेत कण अलग ठोस है; पूरा ढेर कणों का समूह है, एक ठोस पिंड नहीं", "हाँ, रेत द्रव है", "हाँ, रेत गैस है", "रेत कोई अवस्था नहीं है"],
     ["No — each grain of sand is a separate solid; the heap is a collection of particles, not one solid block", "Yes, sand is a liquid", "Yes, sand is a gas", "Sand has no state"],
     0,
     "आकार-बदलाव ढेर का है, दाने का नहीं — दाना ठोस बना रहता है।",
     "The change of shape belongs to the heap, not the grain — the grain stays solid."),

    ("states-of-matter", "medium",
     "दो कथन: (i) द्रव का आयतन निश्चित होता है। (ii) द्रव का आकार निश्चित नहीं होता। सही विकल्प:",
     "Two statements: (i) A liquid's volume is fixed. (ii) A liquid's shape is not fixed. The correct option:",
     ["दोनों सही हैं", "केवल (i) सही", "केवल (ii) सही", "दोनों गलत"],
     ["Both are correct", "Only (i)", "Only (ii)", "Both wrong"],
     0,
     "द्रव की मात्रा स्थिर, आकार बर्तन पर निर्भर।",
     "A liquid's quantity stays, its shape depends on the vessel."),

    ("states-of-matter", "medium",
     "स्प्रे कैन की गैस दबाकर भरी जाती है। दबी हुई अवस्था में कणों के बीच क्या बदला है?",
     "The gas in a spray can is filled under pressure. What has changed between the particles in the pressed state?",
     ["उनके बीच की दूरी घट गई है", "उनका रंग बदल गया", "उनका आकार बढ़ गया", "वे ठोस बन गए"],
     ["The distance between them has decreased", "Their colour has changed", "Their size has grown", "They have become solid"],
     0,
     "संपीड़न केवल अंतराल घटाता है, कण को नहीं।",
     "Compression only reduces the gaps, not the particles."),

    ("states-of-matter", "medium",
     "तीन बर्तनों में एक-एक लीटर तेल, पानी और हवा भरी है। कणों की संख्या एक समान मानें तो किस बर्तन में कण सबसे पास-पास होंगे?",
     "One litre each of oil, water and air is taken in three vessels. Assuming equal numbers of particles, in which vessel are the particles closest?",
     ["तेल और पानी (द्रव) में — हवा की तुलना में", "हवा में", "तीनों में समान", "कह नहीं सकते"],
     ["In the oil and water (liquids) — compared with the air", "In the air", "The same in all three", "Cannot be said"],
     0,
     "द्रवों के कण गैस की तुलना में घने बंधे रहते हैं।",
     "The particles of liquids stay packed closer than a gas's."),

    ("states-of-matter", "medium",
     "किसी ठोस को तोड़ने पर वह अपने टुकड़ों में भी ठोस ही रहता है। कारण चुनिए:",
     "When a solid is broken, each piece remains a solid too. Choose the reason:",
     ["टुकड़ों में भी कणों का प्रबल आकर्षण और संघन व्यवस्था बनी रहती है", "टुकड़े गैस बन जाते हैं", "आकर्षण तुरंत समाप्त हो जाता है", "कण उड़ जाते हैं"],
     ["Even in the pieces, the strong attraction and compact arrangement of particles persist", "The pieces turn into gas", "The attraction vanishes at once", "The particles fly away"],
     0,
     "भंग होने से आकार बदलता है, कण-प्रकृति नहीं।",
     "Breaking changes the shape, not the particle nature."),

    ("states-of-matter", "medium",
     "गैसों की तुलना में द्रवों का विसरण धीमा क्यों होता है?",
     "Why is diffusion in liquids slower than in gases?",
     ["द्रवों के कण अधिक बंधे होने से कम स्वतंत्र रूप से घूम पाते हैं", "द्रवों के कण बड़े होते हैं", "द्रवों में रिक्त स्थान नहीं होता", "गैसों के कण सो जाते हैं"],
     ["Being more tightly bound, a liquid's particles cannot roam as freely", "A liquid's particles are larger", "Liquids have no empty space", "A gas's particles fall asleep"],
     0,
     "बंधन जितना, गति उतनी — विसरण भी उतना।",
     "The more the binding, the less the motion — and the diffusion."),

    ("states-of-matter", "medium",
     "किस अवस्था में कण अपनी स्थिति छोड़कर आस-पास के कणों के ऊपर से सरकते रहते हैं (ढलान)?",
     "In which state do the particles keep sliding over their neighbours, leaving their positions?",
     ["द्रव में", "ठोस में", "गैस में", "किसी में नहीं"],
     ["In a liquid", "In a solid", "In a gas", "In none"],
     0,
     "द्रव का बहना ही कणों की यह ढलान-गति है।",
     "A liquid's flowing is precisely this sliding motion of particles."),

    ("states-of-matter", "medium",
     "तीन कथन: (i) ठोस संपीड्य नहीं होते। (ii) द्रव अल्प संपीड्य होते हैं। (iii) गैसें अत्यधिक संपीड्य होती हैं। सही समूह:",
     "Three statements: (i) Solids are not compressible. (ii) Liquids are slightly compressible. (iii) Gases are highly compressible. The correct set:",
     ["तीनों सही", "केवल (i) और (iii)", "केवल (ii)", "केवल (iii)"],
     ["All three correct", "Only (i) and (iii)", "Only (ii)", "Only (iii)"],
     0,
     "अंतराल की मात्रा के अनुसार संपीड्यता — ठोस नहीं, द्रव थोड़ा, गैस बहुत।",
     "Compressibility follows the gaps — solids none, liquids slight, gases much."),

    ("states-of-matter", "medium",
     "एक स्पंज दबाने पर सिकुड़ जाता है। क्या स्पंज गैस जैसा संपीड्य ठोस है?",
     "A sponge shrinks when pressed. Is a sponge a compressible solid like a gas?",
     ["स्पंज ठोस है — दबने पर कण नहीं, उसके छिद्रों में बंद हवा सिकुड़ती है", "हाँ, स्पंज गैस है", "स्पंज द्रव है", "स्पंज पदार्थ नहीं"],
     ["A sponge is a solid — when pressed, the air trapped in its pores shrinks, not its particles", "Yes, a sponge is a gas", "A sponge is a liquid", "A sponge is not matter"],
     0,
     "संपीडन छिद्रों की हवा का है — स्पंज के कण अपनी जगह जमे रहते हैं।",
     "The compression belongs to the air in the pores — the sponge's own particles stay put."),

    ("states-of-matter", "medium",
     "द्रव और गैस दोनों 'द्रव' (fluids) कहलाते हैं। इनके बहने का साझा आधार क्या है?",
     "Both liquids and gases are called 'fluids'. What is the shared basis of their flowing?",
     ["दोनों के कण आकर्षण में इतनी ढील है कि वे सरक-फिसल सकते हैं", "दोनों रंगीन होते हैं", "दोनों ठंडे होते हैं", "दोनों भारी होते हैं"],
     ["In both, the particles are loosely enough held to slide and slip", "Both are coloured", "Both are cold", "Both are heavy"],
     0,
     "बहने की क्षमता = कणों की सरकने की क्षमता।",
     "The ability to flow = the particles' ability to slide."),

    ("states-of-matter", "medium",
     "गैस को बर्तन के एक कोने में रखा जाए तो वह कुछ ही क्षण में क्या करती है?",
     "If a gas is kept in one corner of a vessel, what does it do within moments?",
     ["पूरे बर्तन में फैल जाती है", "उसी कोने में रहती है", "नीचे बैठ जाती है", "जम जाती है"],
     ["It spreads through the whole vessel", "It stays in that corner", "It settles to the bottom", "It freezes"],
     0,
     "मुक्त गतिमान कण उपलब्ध सारा स्थान घेर लेते हैं।",
     "Free moving particles occupy all the space available."),

    ("states-of-matter", "medium",
     "ठोस और द्रव की तुलना में गैस का घनत्व (प्रति इकाई आयतन द्रव्यमान) सामान्यतः कम होने का कारण क्या है?",
     "Compared with solids and liquids, why is a gas's density (mass per unit volume) normally low?",
     ["कणों के बीच विशाल रिक्त स्थान के कारण उसी आयतन में कण बहुत कम होते हैं", "गैस के कण वजनहीन होते हैं", "गैस के कण छोटे होते हैं", "गैस रंगहीन होती है"],
     ["Due to the huge empty spaces, very few particles fit in the same volume", "A gas's particles are weightless", "A gas's particles are tiny", "A gas is colourless"],
     0,
     "खाली जगह अधिक = उसी थाल में कम कण = कम घनत्व।",
     "More empty space = fewer particles in the same plate = lower density."),

    ("states-of-matter", "medium",
     "किसी ठोस को गर्म करने पर वह पिघलकर द्रव बनता है। इस परिवर्तन में कणों के बीच क्या हुआ?",
     "On heating, a solid melts into a liquid. In this change, what happened between the particles?",
     ["आकर्षण की पकड़ ढीली पड़ी और कण सरकने लगे", "कण गायब हो गए", "नए कण बन गए", "कण आकार बदलकर बड़े हो गए"],
     ["The grip of attraction loosened and the particles began to slide", "The particles vanished", "New particles formed", "The particles grew bigger"],
     0,
     "पिघलन = आकर्षण में ढील = कणों को गति।",
     "Melting = loosened attraction = mobility for particles."),

    ("states-of-matter", "medium",
     "लकड़ी का तख्ता और उतनी ही जगह घेरती हवा — किसमें कणों का आपसी खिंचाव ज्यादा है?",
     "A wooden plank and air occupying the same space — in which is the mutual pull of particles greater?",
     ["तख्ते में — ठोस के कण प्रबल आकर्षण में बंधे हैं", "हवा में", "दोनों में बराबर", "निर्भर नहीं करता"],
     ["In the plank — a solid's particles are bound by strong attraction", "In the air", "Equal in both", "It does not depend"],
     0,
     "ठोस की जकड़न ही उसके आकार की जकड़न है।",
     "A solid's grip on its particles is the grip on its shape."),

    ("states-of-matter", "medium",
     "दो कथन: (i) गैस का आयतन बर्तन के आयतन के बराबर हो जाता है। (ii) द्रव का आयतन बर्तन से स्वतंत्र रहता है। सही विकल्प:",
     "Two statements: (i) A gas's volume becomes equal to the vessel's volume. (ii) A liquid's volume remains independent of the vessel. The correct option:",
     ["दोनों सही हैं", "केवल (i) सही", "केवल (ii) सही", "दोनों गलत"],
     ["Both are correct", "Only (i)", "Only (ii)", "Both wrong"],
     0,
     "गैस बर्तन जितना, द्रव अपनी मात्रा जितना।",
     "A gas as big as the vessel, a liquid as big as its own quantity."),

    ("states-of-matter", "medium",
     "अवस्था-पहचान: मैं बहता हूँ, मेरा आयतन स्थिर है, मेरे कण पास हैं पर जकड़े नहीं। मैं क्या हूँ?",
     "State identification: I flow, my volume is steady, my particles are close yet not locked. What am I?",
     ["द्रव", "ठोस", "गैस", "उर्ध्वपातित पदार्थ"],
     ["A liquid", "A solid", "A gas", "A sublimated substance"],
     0,
     "बहना + स्थिर आयतन = द्रव की दो स्पष्ट पहचान।",
     "Flowing + steady volume = the two clear marks of a liquid."),

    # ---- hard (9) ----
    ("states-of-matter", "medium",
     "कणों की गति की स्वतंत्रता का सही क्रम कौन-सा है?",
     "Which is the correct order of the freedom of the particles' motion?",
     ["गैस > द्रव > ठोस", "ठोस > द्रव > गैस", "द्रव > गैस > ठोस", "तीनों अवस्थाओं में समान"],
     ["Gas > liquid > solid", "Solid > liquid > gas", "Liquid > gas > solid", "The same in all three states"],
     0,
     "जितना ढीला बंधन, उतनी बड़ी छलांग — गैस सबसे आगे।",
     "The looser the binding, the bigger the leap — gas is far ahead."),

    ("states-of-matter", "medium",
     "प्लास्टिक की सीरिंज में हवा भरकर मुँह बंद कर दबाया जा सकता है, पर सीरिंज पानी से भरी हो तो दबाना लगभग असंभव। कारण चुनिए:",
     "A plastic syringe filled with air can be pressed with its nozzle closed, but if it is filled with water, pressing is nearly impossible. Choose the reason:",
     ["गैस के कणों के बीच बड़े अंतराल हैं जो सिकुड़ सकते हैं; द्रव के कण पास-पास हैं",
      "हवा हल्की और पानी भारी होता है",
      "पानी सीरिंज की दीवार से चिपक जाता है",
      "हवा में रंग नहीं होता"],
     ["The gas's particles have large gaps that can shrink; the liquid's particles are close together",
      "Air is light and water is heavy",
      "Water sticks to the syringe's wall",
      "Air has no colour"],
     0,
     "संपीड्यता का अंतर अंतरालों के अंतर से आता है, भार से नहीं।",
     "The difference in compressibility comes from the difference in the gaps, not from weight."),

    ("states-of-matter", "hard",
     "तीन कथन: (i) ठोस के कण गतिहीन होते हैं। (ii) द्रव के कण केवल कंपन करते हैं, सरकते नहीं। (iii) गैस के कण निरंतर गतिमान रहते हैं। इनमें से सही कथन एक ही है — कौन-सा?",
     "Three statements: (i) A solid's particles are motionless. (ii) A liquid's particles only vibrate and never slide. (iii) A gas's particles stay in constant motion. Only one of these is correct — which one?",
     ["कथन (iii)", "कथन (i)", "कथन (ii)", "तीनों सही"],
     ["Statement (iii)", "Statement (i)", "Statement (ii)", "All three correct"],
     0,
     "तीनों अवस्थाओं के कण गतिमान हैं — फर्क गति की मात्रा का है, होने-न होने का नहीं।",
     "Particles in all three states move — the difference is of degree, not of existence."),

    ("states-of-matter", "hard",
     "सोच-परीक्षण: यदि द्रव के कणों का आपसी आकर्षण ठोस जितना प्रबल हो जाए, तो द्रव का व्यवहार कैसा हो जाएगा?",
     "Thought experiment: if a liquid's inter-particle attraction became as strong as a solid's, how would the liquid behave?",
     ["बहना बंद कर ठोस जैसा आकार पकड़ लेगा", "गैस बन जाएगा", "उड़ जाएगा", "कोई अंतर नहीं पड़ेगा"],
     ["It would stop flowing and hold a solid-like shape", "It would become a gas", "It would fly away", "No difference would occur"],
     0,
     "बहाव ढीले बंधन की देन है — बंधन कसा तो बहाव रुका।",
     "Flow is the gift of loose binding — tighten the binding, the flow stops."),

    ("states-of-matter", "hard",
     "सोच-परीक्षण: यदि गैस के कणों के बीच रिक्त स्थान द्रव जितना रह जाए, तो गैस की संपीड्यता का क्या होगा?",
     "Thought experiment: if the empty spaces in a gas became as few as a liquid's, what would happen to the gas's compressibility?",
     ["वह द्रव जैसी लगभग असंपीड्य हो जाएगी", "वह और अधिक संपीड्य होगी", "कोई बदलाव नहीं", "वह ठोस बन जाएगी"],
     ["It would become nearly incompressible like a liquid", "It would become more compressible", "No change", "It would turn solid"],
     0,
     "संपीड्यता अंतराल की छाया है — अंतराल गया तो संपीड्यता गई।",
     "Compressibility is the shadow of the gaps — no gaps, no compressibility."),

    ("states-of-matter", "hard",
     "कण-व्यवस्था के आधार पर तीन अवस्थाओं का सही वर्णन-मिलान कौन-सा है?",
     "Which is the correct description-matching of the three states based on particle arrangement?",
     ["ठोस — संघन व सुव्यवस्थित; द्रव — मध्यम बंधन व सरकते; गैस — सर्वाधिक बिखरे व मुक्त", "ठोस — बिखरे; द्रव — संघन; गैस — सुव्यवस्थित", "तीनों — समान व्यवस्था", "ठोस — मुक्त; गैस — जकड़े"],
     ["Solid — compact and orderly; liquid — moderately held and sliding; gas — most scattered and free", "Solid — scattered; liquid — compact; gas — orderly", "All three — same arrangement", "Solid — free; gas — locked"],
     0,
     "व्यवस्था का यही स्पेक्ट्रम तीन अवस्थाओं का मानचित्र है।",
     "This spectrum of arrangement is the map of the three states."),

    ("states-of-matter", "hard",
     "एक बंद सीधी नली में नीचे पानी, उस पर तेल और ऊपर हवा है। इन तीनों की कण-संरचना के आधार पर सही कथन चुनिए:",
     "In a sealed upright tube there is water at the bottom, oil above it and air on top. Based on the particle structure of these three, choose the correct statement:",
     ["पानी-तेल द्रव हैं — कण पास पर सरकते; हवा गैस है — कण सर्वाधिक मुक्त", "तीनों गैस हैं", "तीनों ठोस हैं", "हवा द्रव है"],
     ["Water and oil are liquids — particles close yet sliding; air is a gas — its particles the most free", "All three are gases", "All three are solids", "Air is a liquid"],
     0,
     "एक नली, तीन अवस्थाएँ — भिन्न कण-व्यवहार।",
     "One tube, three states — different particle behaviours."),

    ("states-of-matter", "hard",
     "दो कथन: (i) ठोस और द्रव का विसरण हो सकता है, पर बहुत धीमा। (ii) विसरण की गति कण-स्वतंत्रता की माप है। सही विकल्प:",
     "Two statements: (i) Solids and liquids can diffuse, though very slowly. (ii) The speed of diffusion is a measure of the particles' freedom. The correct option:",
     ["दोनों सही हैं", "केवल (i) सही", "केवल (ii) सही", "दोनों गलत"],
     ["Both are correct", "Only (i)", "Only (ii)", "Both wrong"],
     0,
     "विसरण-दर स्वतंत्रता का थर्मामीटर है।",
     "The diffusion rate is the thermometer of freedom."),

    ("states-of-matter", "hard",
     "एक गेंद-बॉल को हथेली में दबाकर छोड़ने पर वह फिर फूल जाती है, पर पत्थर नहीं। कण-सिद्धांत से अंतर समझाइए:",
     "A rubber ball squeezed in the palm regains its size on release, but a stone does not change. Explain the difference from the particle theory:",
     ["गेंद के ठोस कण अपनी जगह पर लौट आते हैं — पत्थर के कण पहले से ही सबसे संघन हैं; दोनों ही ठोस हैं, गेंद का उछाल उसकी लोचदार संरचना से है", "गेंद गैस है", "पत्थर द्रव है", "दोनों में कोई अंतर नहीं"],
     ["The ball's solid particles return to their places — a stone's particles are already most compact; both are solids, the ball's bounce comes from its elastic structure", "The ball is a gas", "The stone is a liquid", "There is no difference"],
     0,
     "दोनों ठोस हैं — अंतर संरचना की लोच का है, अवस्था का नहीं।",
     "Both are solids — the difference is of structural elasticity, not of state."),

    ("states-of-matter", "hard",
     "अवस्था-पहेली: मेरे कण इतने मुक्त हैं कि मैं किसी भी बर्तन का पूरा आकार-आयतन ले लेता हूँ और मुझे दबाया भी जा सकता है। मैं क्या हूँ?",
     "State riddle: my particles are so free that I take the full shape and volume of any vessel, and I can also be compressed. What am I?",
     ["गैस", "ठोस", "द्रव", "द्रव और गैस दोनों"],
     ["A gas", "A solid", "A liquid", "Both liquid and gas"],
     0,
     "पूरा बर्तन भरना + संपीड्य होना = गैस की अनूठी पहचान।",
     "Filling the vessel + being compressible = the gas's unique identity."),

    ("states-of-matter", "hard",
     "तीनों अवस्थाओं के गुणों की तुलना-तालिका में सबसे सुसंगत पंक्ति कौन-सी है?",
     "In the comparison table of the properties of the three states, which is the most consistent row?",
     ["ठोस: आकार-आयतन निश्चित; द्रव: आयतन निश्चित, आकार बदलता; गैस: दोनों बदलते", "ठोस: आकार बदलता; द्रव: दोनों निश्चित; गैस: आयतन निश्चित", "ठोस: दोनों बदलते; द्रव: आकार निश्चित; गैस: आयतन बदलता", "तीनों: दोनों गुण समान"],
     ["Solid: shape and volume fixed; liquid: volume fixed, shape varies; gas: both vary", "Solid: shape varies; liquid: both fixed; gas: volume fixed", "Solid: both vary; liquid: shape fixed; gas: volume varies", "All three: both properties identical"],
     0,
     "यही पंक्ति तीनों अवस्थाओं का सार है।",
     "This row is the essence of the three states."),
]
