# -*- coding: utf-8 -*-
"""C02 part 1 — Physical & Chemical Changes (chemistry chapter-02).
T1 physical-change (E20/M21/H9) + T2 chemical-change (E20/M21/H9).
Tuple: (topic, difficulty, q_hi, q_en, opts_hi[4], opts_en[4], correct_idx=0, expl_hi, expl_en)
All authored with correct_idx 0; answer-position rotation happens in gen script.
Content authority: chapter-02 meta ONLY (no invented products, conditions or numbers).
Mg burning product = magnesium oxide (per English meta note; the Hindi meta line's
"गंधक डाइऑक्साइड" is a known meta typo, not used).
"""

PART1 = [
    # ================= PHYSICAL CHANGE (50) =================
    # ---- easy (20) ----
    ("physical-change", "easy",
     "भौतिक परिवर्तन में क्या नहीं बनता?",
     "What is NOT formed in a physical change?",
     ["नया पदार्थ", "आकार में बदलाव", "अवस्था में बदलाव", "आकृति में बदलाव"],
     ["A new substance", "A change in shape", "A change of state", "A change in form"],
     0,
     "भौतिक परिवर्तन में केवल भौतिक गुण बदलते हैं — नया पदार्थ नहीं बनता।",
     "In a physical change only physical properties change — no new substance forms."),

    ("physical-change", "easy",
     "भौतिक परिवर्तन में मूल पदार्थ का क्या होता है?",
     "What happens to the original substance in a physical change?",
     ["वह वही बना रहता है", "वह नए पदार्थ में बदल जाता है", "वह नष्ट हो जाता है", "उसके गुण पूरी तरह बदल जाते हैं"],
     ["It remains the same", "It turns into a new substance", "It is destroyed", "Its properties change completely"],
     0,
     "मूल पदार्थ वही रहता है — यही भौतिक परिवर्तन की पहचान है।",
     "The original substance remains — that is the identity of a physical change."),

    ("physical-change", "easy",
     "मोम का गर्म होकर पिघल जाना किस प्रकार का परिवर्तन है?",
     "Wax getting hot and melting is which type of change?",
     ["भौतिक परिवर्तन", "रासायनिक परिवर्तन", "कोई परिवर्तन नहीं", "दोनों प्रकार का परिवर्तन"],
     ["A physical change", "A chemical change", "No change", "Both types of change"],
     0,
     "अवस्था बदली, पदार्थ वही — भौतिक परिवर्तन।",
     "The state changed, the substance stayed — a physical change."),

    ("physical-change", "easy",
     "काँच के गिलास का टूट जाना (भंगन) कैसा परिवर्तन है?",
     "The breaking of a glass tumbler is what kind of change?",
     ["भौतिक परिवर्तन — आकार बदला, पदार्थ नहीं", "रासायनिक परिवर्तन — नया पदार्थ बना", "कोई परिवर्तन नहीं", "अवक्षेपण परिवर्तन"],
     ["A physical change — shape changed, not the substance", "A chemical change — a new substance formed", "No change", "A precipitation change"],
     0,
     "टुकड़े भी काँच ही हैं — मूल पदार्थ वही, इसलिए भौतिक।",
     "The pieces are still glass — the substance is the same, hence physical."),

    ("physical-change", "easy",
     "चीनी के पानी में घुलने पर क्या बनता है?",
     "What forms when sugar dissolves in water?",
     ["कोई नया पदार्थ नहीं — चीनी और जल वही रहते हैं", "नया अम्ल", "नई गैस", "नया लवण"],
     ["No new substance — sugar and water remain as they were", "A new acid", "A new gas", "A new salt"],
     0,
     "घुलने से केवल मिश्र रूप बना — नया पदार्थ नहीं।",
     "Dissolving only made a mixed form — no new substance."),

    ("physical-change", "easy",
     "भौतिक परिवर्तन प्रायः कैसे होते हैं?",
     "Physical changes are usually —",
     ["उत्क्रमणीय (वापस लौटने योग्य)", "अनुक्रमणीय", "सदैव अनुक्रमणीय", "कभी उत्क्रमणीय नहीं"],
     ["Reversible (capable of returning)", "Irreversible", "Always irreversible", "Never reversible"],
     0,
     "मूल पदार्थ बना रहता है, इसलिए प्रायः पूर्ववत् होना संभव है।",
     "Since the original substance remains, returning to the previous form is usually possible."),

    ("physical-change", "easy",
     "'उत्क्रमणीय परिवर्तन' का अर्थ है —",
     "'Reversible change' means —",
     ["जिसे पुनः मूल रूप में लाया जा सके", "जिसमें गैस निकले", "जिसमें रंग बदले", "जिसमें अवक्षेप पड़े"],
     ["One that can be brought back to its original form", "One in which a gas escapes", "One in which the colour changes", "One in which a precipitate settles"],
     0,
     "उत्क्रमणीय = मूल रूप में वापसी संभव।",
     "Reversible = a return to the original form is possible."),

    ("physical-change", "easy",
     "पिघला हुआ बर्फ-जल दोबारा जमकर बर्फ बन गया। यह भौतिक परिवर्तन का उत्क्रमणीय होना दर्शाता है — आधार चुनिए:",
     "Melted ice-water froze back into ice. This shows the reversibility of a physical change — choose the basis:",
     ["जल पहले भी जल था और बाद में भी जल रहा", "बर्फ एक नया पदार्थ है", "जल में रंग बदल गया", "जल से गैस निकली"],
     ["Water was water before and stayed water after", "Ice is a new substance", "The water's colour changed", "A gas escaped from the water"],
     0,
     "अवस्था आगे-पीछे हुई, पदार्थ जल ही रहा — इसलिए उत्क्रमणीय।",
     "The state went back and forth but the substance stayed water — hence reversible."),

    ("physical-change", "easy",
     "कागज़ को कैंची से काटना कैसा परिवर्तन है?",
     "Cutting paper with scissors is what kind of change?",
     ["भौतिक — केवल आकार बदला", "रासायनिक — नया पदार्थ बना", "कोई परिवर्तन नहीं", "संघनन"],
     ["Physical — only the shape changed", "Chemical — a new substance formed", "No change", "Condensation"],
     0,
     "कागज़ के टुकड़े भी कागज़ ही हैं — भौतिक परिवर्तन।",
     "The pieces of paper are still paper — a physical change."),

    ("physical-change", "easy",
     "निम्न में से कौन-सा भौतिक परिवर्तन नहीं है?",
     "Which of the following is NOT a physical change?",
     ["लोहे में जंग लगना", "मोम का पिघलना", "काँच का टूटना", "चीनी का घुलना"],
     ["Rusting of iron", "Melting of wax", "Breaking of glass", "Dissolving of sugar"],
     0,
     "जंग लगने में नया पदार्थ बनता है — रासायनिक परिवर्तन।",
     "Rusting forms a new substance — a chemical change."),

    ("physical-change", "easy",
     "अवस्था का बदलना (ठोस ↔ द्रव) किस वर्ग का परिवर्तन है?",
     "A change of state (solid ↔ liquid) belongs to which class of change?",
     ["भौतिक — पदार्थ वही रहता है", "रासायनिक — पदार्थ बदल जाता है", "कोई परिवर्तन नहीं", "विद्युत परिवर्तन"],
     ["Physical — the substance stays the same", "Chemical — the substance changes", "No change", "An electrical change"],
     0,
     "बर्फ, जल — दोनों जल ही है; केवल अवस्था बदली।",
     "Ice and water are both water; only the state changed."),

    ("physical-change", "easy",
     "भौतिक परिवर्तन के उदाहरणों का सही समूह कौन-सा है?",
     "Which is the correct group of examples of physical change?",
     ["पिघलना, भंगन, घुलना", "दहन, जंग, दही जमना", "पाचन, श्वसन, दहन", "जंग, विद्युत लेपन, पिघलना"],
     ["Melting, breaking, dissolving", "Burning, rusting, curd setting", "Digestion, respiration, burning", "Rusting, electroplating, melting"],
     0,
     "यही तीन भौतिक परिवर्तन के आधारभूत उदाहरण हैं।",
     "These three are the basic examples of physical change."),

    ("physical-change", "easy",
     "गेंद के दबकर चपटी हो जाने में क्या बदला?",
     "What changed when a ball got pressed flat?",
     ["केवल उसकी आकृति", "उसका पदार्थ", "उसका रासायनिक गुण", "उसका द्रव्यमान बढ़ा"],
     ["Only its shape", "Its substance", "Its chemical property", "Its mass increased"],
     0,
     "आकृति भौतिक गुण है — उसका बदलना भौतिक परिवर्तन है।",
     "Shape is a physical property — its change is a physical change."),

    ("physical-change", "easy",
     "चीनी घोल की चाय मीठी लगती है। इससे क्या पता चलता है?",
     "The sugar solution tastes sweet in tea. What does this show?",
     ["चीनी अब भी उसी पदार्थ के रूप में घोल में है", "चीनी नया पदार्थ बन गई", "चाय में अवक्षेप गिरा", "चीनी नष्ट हो गई"],
     ["The sugar is still present in the solution as the same substance", "The sugar became a new substance", "A precipitate fell in the tea", "The sugar was destroyed"],
     0,
     "मीठापन चीनी के गुण का बना रहना दिखाता है — पदार्थ वही।",
     "The sweetness shows the sugar's property remains — the substance is unchanged."),

    ("physical-change", "easy",
     "लकड़ी की छड़ी को छीलकर छोटा किया गया। परिवर्तन का प्रकार और कारण चुनिए:",
     "A wooden stick was peeled and shortened. Choose the type of change and the reason:",
     ["भौतिक — आकार बदला, लकड़ी वही रही", "रासायनिक — नया पदार्थ बना", "भौतिक — लकड़ी नई धातु बन गई", "कोई परिवर्तन नहीं हुआ"],
     ["Physical — shape changed, the wood stayed", "Chemical — a new substance formed", "Physical — the wood became a new metal", "No change occurred"],
     0,
     "छिलने से आकार घटा, पदार्थ लकड़ी ही रहा।",
     "Peeling reduced the size; the substance remained wood."),

    ("physical-change", "easy",
     "भौतिक परिवर्तन में कौन-से गुण बदल सकते हैं?",
     "Which properties may change in a physical change?",
     ["अवस्था, आकार या आकृति", "पदार्थ की संरचना वाले गुण", "नया पदार्थ बनने वाले गुण", "कोई गुण नहीं बदलता"],
     ["State, shape or form", "The substance's compositional properties", "New-substance-forming properties", "No property changes"],
     0,
     "भौतिक गुण = अवस्था, आकार, आकृति — यही बदलते हैं।",
     "Physical properties = state, shape, form — these are what change."),

    ("physical-change", "easy",
     "फलों को छीलकर टुकड़े करना कैसा परिवर्तन है?",
     "Peeling and cutting fruits into pieces is what kind of change?",
     ["भौतिक परिवर्तन", "रासायनिक परिवर्तन", "दहन", "विद्युत लेपन"],
     ["A physical change", "A chemical change", "Combustion", "Electroplating"],
     0,
     "आकार-आकृति बदली, फल का पदार्थ वही रहा।",
     "Shape and form changed; the fruit's substance stayed the same."),

    ("physical-change", "easy",
     "तैयार आइसक्रीम को गर्मी में द्रव बहने लगी और फ्रीजर में रखने पर फिर जम गई। पूरी घटना किसका उदाहरण है?",
     "Ready ice-cream began flowing liquid in the heat and froze again when kept in the freezer. The whole event is an example of what?",
     ["उत्क्रमणीय भौतिक परिवर्तन", "अनुक्रमणीय रासायनिक परिवर्तन", "अवक्षेपण", "विद्युत लेपन"],
     ["A reversible physical change", "An irreversible chemical change", "Precipitation", "Electroplating"],
     0,
     "पदार्थ वही, अवस्था आगे-पीछे — उत्क्रमणीय भौतिक परिवर्तन।",
     "Same substance, state back and forth — a reversible physical change."),

    ("physical-change", "easy",
     "डोरी को काटकर छोटे टुकड़े किए गए। इसमें बनने वाला 'नया' केवल क्या है?",
     "A rope was cut into small pieces. What is the only 'new' thing made here?",
     ["टुकड़ों का नया आकार", "नया पदार्थ", "नई गैस", "नया लवण"],
     ["A new arrangement of the pieces", "A new substance", "A new gas", "A new salt"],
     0,
     "आकार नया, पदार्थ पुराना ही — इसलिए भौतिक परिवर्तन।",
     "New shape, same old substance — hence a physical change."),

    ("physical-change", "easy",
     "दो कथन: (i) भौतिक परिवर्तन में मूल पदार्थ बना रहता है। (ii) भौतिक परिवर्तन में सदैव गैस निकलती है। सही विकल्प:",
     "Two statements: (i) In a physical change the original substance remains. (ii) In a physical change a gas always escapes. The correct option:",
     ["(i) सही, (ii) गलत", "दोनों सही", "दोनों गलत", "(i) गलत, (ii) सही"],
     ["(i) correct, (ii) wrong", "Both correct", "Both wrong", "(i) wrong, (ii) correct"],
     0,
     "गैस निकलना रासायनिक परिवर्तन का संकेत है, भौतिक का नहीं।",
     "Gas evolution is a sign of chemical change, not physical."),

    # ---- medium (21) ----
    ("physical-change", "medium",
     "काँच टूटने पर भी उसे भौतिक परिवर्तन क्यों कहा जाता है? कारण-चुनाव कीजिए:",
     "Why is even the breaking of glass called a physical change? Choose the reason:",
     ["टूटे टुकड़ों में भी मूल पदार्थ (काँच) वही रहता है — नया पदार्थ नहीं बनता", "काँच टूटकर नई धातु बन जाता है", "टूटने पर रंग बदल जाता है", "टूटने पर गैस निकलती है"],
     ["Even in the broken pieces the original substance (glass) remains — no new substance forms", "Broken glass becomes a new metal", "Breaking changes its colour", "Breaking releases a gas"],
     0,
     "परिवर्तन की कसौटी 'नया पदार्थ' है, 'नया आकार' नहीं।",
     "The test of a change is 'a new substance', not 'a new shape'."),

    ("physical-change", "medium",
     "कथन: 'सभी भौतिक परिवर्तन उत्क्रमणीय होते हैं।' इसका सही निर्णय कीजिए:",
     "Statement: 'All physical changes are reversible.' Judge it correctly:",
     ["गलत — भौतिक परिवर्तन प्रायः उत्क्रमणीय होते हैं, सभी नहीं", "सही — सभी सदैव उत्क्रमणीय", "सही — केवल अनुक्रमणीय", "गलत — भौतिक परिवर्तन कभी उत्क्रमणीय नहीं"],
     ["Wrong — physical changes are usually reversible, not all", "Correct — all are always reversible", "Correct — only irreversible", "Wrong — physical changes are never reversible"],
     0,
     "'प्रायः' शब्द ही बताता है — अधिकांश, सर्व नहीं।",
     "The word 'usually' itself says — most, not all."),

    ("physical-change", "medium",
     "चीनी घोल में चीनी का पदार्थत्व बना रहता है — इसका सबसे सीधा प्रमाण क्या है?",
     "The sugar in a solution keeps its identity as sugar — what is the most direct proof of this?",
     ["घोल का स्वाद पहले जैसा ही मीठा रहता है", "घोल का रंग बदल जाता है", "घोल से गैस निकलती है", "घोल में अवक्षेप गिरता है"],
     ["The solution tastes exactly as sweet as before", "The solution's colour changes", "A gas escapes from the solution", "A precipitate settles in the solution"],
     0,
     "गुण बने रहना = पदार्थ बना रहना।",
     "A property persisting means the substance persists."),

    ("physical-change", "medium",
     "चार घटनाएँ: मोम पिघलना, कागज़ कतरना, गेंद चपटी होना, लोहे में जंग लगना। इनमें से अलग कौन-सी है और क्यों?",
     "Four events: wax melting, paper being cut, a ball getting flattened, iron rusting. Which one is the odd one out and why?",
     ["जंग लगना — यह नया पदार्थ बनाता है", "मोम पिघलना — यह अवस्था बदलता है", "कागज़ कतरना — यह आकार बदलता है", "गेंद चपटी होना — यह आकृति बदलता है"],
     ["Rusting — it forms a new substance", "Wax melting — it changes state", "Paper cutting — it changes shape", "Ball flattening — it changes form"],
     0,
     "तीन घटनाओं में पदार्थ वही रहा; जंग में नया पदार्थ बना।",
     "In three events the substance stayed; in rusting a new substance formed."),

    ("physical-change", "medium",
     "प्रेक्षण: एक पदार्थ की अवस्था बदली, फिर पुनः पहले जैसी हो गई; पदार्थ की पहचान कहीं नहीं बदली। निष्कर्ष क्या है?",
     "Observation: a substance's state changed and then returned to the earlier one; the substance's identity never changed. What is the conclusion?",
     ["भौतिक परिवर्तन हुआ — नया पदार्थ नहीं बना", "रासायनिक परिवर्तन हुआ", "अवक्षेप बना", "दहन हुआ"],
     ["A physical change occurred — no new substance formed", "A chemical change occurred", "A precipitate formed", "Combustion occurred"],
     0,
     "पहचान अचली रही — यही भौतिक परिवर्तन की परिभाषा है।",
     "The identity stayed fixed — that is the very definition of a physical change."),

    ("physical-change", "medium",
     "गीले तौलिये को मरोड़ा गया — पानी बाहर निकला, तौलिया वैसा का वैसा रहा। इस घटना का वर्गीकरण और आधार चुनिए:",
     "A wet towel was wrung — water came out, the towel remained as it was. Choose the classification and basis of this event:",
     ["भौतिक परिवर्तन — केवल जल अलग हुआ, दोनों पदार्थ वही रहे", "रासायनिक परिवर्तन — तौलिया बदल गया", "रासायनिक परिवर्तन — जल नया पदार्थ बना", "दहन — जल जल गया"],
     ["Physical change — only water separated, both substances stayed the same", "Chemical change — the towel changed", "Chemical change — the water became a new substance", "Combustion — the water burnt"],
     0,
     "मरोड़ने से केवल जल की स्थिति बदली, पदार्थ नहीं।",
     "Wringing changed only the water's situation, not any substance."),

    ("physical-change", "medium",
     "जले हुए कागज़ और कतरे हुए कागज़ में मूल अंतर किस बात में है?",
     "In what basic respect do burnt paper and cut paper differ?",
     ["जले कागज़ में नया पदार्थ बना, कतरे में केवल आकार बदला", "दोनों में नया पदार्थ बना", "दोनों में केवल आकार बदला", "कतरे कागज़ में गैस निकली"],
     ["In burnt paper a new substance formed; in cut paper only the shape changed", "A new substance formed in both", "Only the shape changed in both", "A gas escaped from the cut paper"],
     0,
     "जलना = रासायनिक; कतरना = भौतिक — कसौटी नया पदार्थ है।",
     "Burning = chemical; cutting = physical — the test is a new substance."),

    ("physical-change", "medium",
     "चाकू की धार करना (घिसाव से तेज़ बनाना) कैसा परिवर्तन है और क्यों?",
     "Sharpening a knife (grinding it sharp) is what kind of change and why?",
     ["भौतिक — धातु का आकार बदलता है, धातु वही रहती है", "रासायनिक — धातु नए पदार्थ में बदलती है", "भौतिक — चाकू में नया तत्व भर जाता है", "दहन — धातु जलती है"],
     ["Physical — the metal's shape changes, the metal remains the same", "Chemical — the metal turns into a new substance", "Physical — a new element fills into the knife", "Combustion — the metal burns"],
     0,
     "घिसाव आकार बदलता है, पदार्थ नहीं।",
     "Grinding changes shape, not substance."),

    ("physical-change", "medium",
     "सोचिए: यदि कोई परिवर्तन 'भौतिक' होने के बावजूद मूल पदार्थ को नए गुणों वाले पदार्थ में बदल दे, तो वह वास्तव में किस श्रेणी में आएगा?",
     "Think: if a change, despite being called 'physical', converts the original substance into a substance with new properties, which category does it actually fall in?",
     ["रासायनिक — क्योंकि नया पदार्थ बन गया", "भौतिक — क्योंकि नाम भौतिक है", "दोनों श्रेणियों में", "किसी श्रेणी में नहीं"],
     ["Chemical — because a new substance has formed", "Physical — because the name says physical", "In both categories", "In no category"],
     0,
     "वर्गीकरण की कसौटी नाम नहीं, नए पदार्थ का बनना है।",
     "The test of classification is not the name but the formation of a new substance."),

    ("physical-change", "medium",
     "किसी परिवर्तन को पहचानने का सबसे पहला प्रश्न क्या होना चाहिए?",
     "What should be the very first question to ask when identifying a change?",
     ["क्या नया पदार्थ बन रहा है?", "रंग क्या है?", "ताप कितना है?", "आकार कितना बड़ा है?"],
     ["Is a new substance forming?", "What is the colour?", "What is the temperature?", "How big is the size?"],
     0,
     "नया पदार्थ बनता है या नहीं — यही पहला प्रश्न है।",
     "Whether a new substance forms — that is the first question."),

    ("physical-change", "medium",
     "नींबू के रस में चीनी घोलकर शरबत बनाया गया। शरबत की मिठास किसकी है और चीनी का क्या हुआ?",
     "Sugar was dissolved in lemon juice to make sherbet. Whose is the sweetness of the sherbet and what happened to the sugar?",
     ["मिठास चीनी की ही है — चीनी नए पदार्थ में नहीं बदली, वही रही", "चीनी नई अम्लीय चीज़ बन गई", "चीनी नष्ट हो गई", "चीनी की जगह नमक बना"],
     ["The sweetness is the sugar's own — it did not turn into a new substance, it remained the same", "The sugar became a new acidic thing", "The sugar was destroyed", "The sugar turned into salt"],
     0,
     "घोलना यहाँ भौतिक रहा — स्वाद ही गवाह है।",
     "Dissolving stayed physical here — the taste itself is the witness."),

    ("physical-change", "medium",
     "तीन कथन: (i) भौतिक परिवर्तन में नया पदार्थ नहीं बनता। (ii) भौतिक परिवर्तन में अवस्था, आकार या आकृति बदल सकती है। (iii) भौतिक परिवर्तन के बाद मूल पदार्थ की पहचान बदल जाती है। सही समूह:",
     "Three statements: (i) No new substance forms in a physical change. (ii) In a physical change, state, shape or form may change. (iii) After a physical change the original substance's identity changes. The correct set:",
     ["(i) और (ii) सही, (iii) गलत", "तीनों सही", "केवल (iii) सही", "केवल (ii) सही"],
     ["(i) and (ii) correct, (iii) wrong", "All three correct", "Only (iii) correct", "Only (ii) correct"],
     0,
     "पहचान बनी रहती है — यही तो भौतिक परिवर्तन है।",
     "The identity remains — that is precisely what makes it physical."),

    ("physical-change", "medium",
     "पिघलना और जलना — दोनों में गर्मी लगती है, फिर भी दोनों अलग वर्ग के हैं। वर्ग-अंतर का एकमात्र आधार चुनिए:",
     "Melting and burning — both involve heat, yet they belong to different classes. Choose the sole basis of the class difference:",
     ["पिघलने में नया पदार्थ नहीं बनता, जलने में बनता है", "पिघलने में गर्मी नहीं लगती", "जलने में आकार नहीं बदलता", "दोनों में कोई अंतर नहीं"],
     ["In melting no new substance forms; in burning one does", "Melting needs no heat", "Burning does not change shape", "There is no difference between the two"],
     0,
     "गर्मी का होना नहीं, नए पदार्थ का बनना कसौटी है।",
     "The test is not the presence of heat but the formation of a new substance."),

    ("physical-change", "medium",
     "वर्गीकरण-तालिका में सही पंक्ति चुनिए:",
     "Choose the correct row in the classification table:",
     ["मोम पिघलना — भौतिक; कागज़ कतरना — भौतिक; दही जमना — रासायनिक", "मोम पिघलना — रासायनिक; कागज़ कतरना — भौतिक; दही जमना — भौतिक", "मोम पिघलना — भौतिक; कागज़ कतरना — रासायनिक; दही जमना — भौतिक", "तीनों — भौतिक"],
     ["Wax melting — physical; paper cutting — physical; curd setting — chemical", "Wax melting — chemical; paper cutting — physical; curd setting — physical", "Wax melting — physical; paper cutting — chemical; curd setting — physical", "All three — physical"],
     0,
     "पिघलना-कतरना में पदार्थ वही; दही में दूध नए पदार्थ में बदला।",
     "In melting and cutting the substance stays; in curd the milk changes to a new substance."),

    ("physical-change", "medium",
     "एक घटना के बाद विद्यार्थी ने मूल पदार्थ को पुनः प्राप्त कर लिया। इससे परिवर्तन के बारे में सबसे संभावित निष्कर्ष क्या है?",
     "After an event a student recovered the original substance again. What is the most likely conclusion about the change?",
     ["परिवर्तन प्रायः भौतिक रहा होगा — उत्क्रमणीय", "परिवर्तन अवश्य रासायनिक था", "परिवर्तन दहन था", "परिवर्तन अवक्षेपण था"],
     ["The change was most likely physical — reversible", "The change must have been chemical", "The change was combustion", "The change was precipitation"],
     0,
     "मूल पदार्थ की वापसी उत्क्रमणीयता का, और उत्क्रमणीयता प्रायः भौतिक परिवर्तन का लक्षण है।",
     "Recovery of the original substance means reversibility, and reversibility usually marks a physical change."),

    ("physical-change", "medium",
     "रबड़ के गुब्बारे को दबाया गया — वह सिकुड़ा और छोड़ने पर फूल गया। कथन बनाइए:",
     "A rubber balloon was pressed — it shrank and inflated again on release. Frame the correct statement:",
     ["आकृति बदली और लौट आई — उत्क्रमणीय भौतिक परिवर्तन", "पदार्थ बदल गया — रासायनिक परिवर्तन", "गुब्बारे से गैस का निर्माण — रासायनिक", "यह कोई परिवर्तन नहीं था"],
     ["The shape changed and returned — a reversible physical change", "The substance changed — a chemical change", "A gas was created in the balloon — chemical", "This was no change at all"],
     0,
     "दबाव आकृति बदलता है; पदार्थ को नहीं छूता।",
     "Pressure changes shape; it does not touch the substance."),

    ("physical-change", "medium",
     "'घुलना सदैव भौतिक परिवर्तन नहीं होता' — इस कथन के पक्ष में अध्याय का उदाहरण कौन-सा है?",
     "'Dissolving is not always a physical change' — which example from the chapter supports this statement?",
     ["चूने का जल में घुलना — ऊष्मा और नया पदार्थ बनता है", "चीनी का जल में घुलना", "नमक का जल में घुलना", "मोम का पिघलना"],
     ["Lime dissolving in water — heat and a new substance form", "Sugar dissolving in water", "Salt dissolving in water", "Wax melting"],
     0,
     "चूना-जल घुलने की क्रिया को रासायनिक बना देता है — यही परीक्षा-जाल है।",
     "Lime-water dissolving turns the act chemical — this is the exam trap."),

    ("physical-change", "medium",
     "बर्फीली सड़क का बर्फ दोपहर को जल बन गया और रात में फिर जम गया। इस पूरे चक्र में 'पदार्थ' के साथ क्या हुआ?",
     "The ice on a frozen road became water by noon and froze again at night. In this whole cycle, what happened to the 'substance'?",
     ["पदार्थ (जल) हर दशा में वही रहा — केवल अवस्था बदली", "पदार्थ पहले नया बना, फिर पुराना", "पदार्थ नष्ट हो गया", "पदार्थ नई गैस बन गया"],
     ["The substance (water) remained the same throughout — only the state changed", "The substance first became new, then old again", "The substance was destroyed", "The substance became a new gas"],
     0,
     "जल → बर्फ → जल: अवस्था-चक्र, पदार्थ-चक्र नहीं।",
     "Water → ice → water: a cycle of state, not of substance."),

    ("physical-change", "medium",
     "दो कथन: (i) भौतिक परिवर्तन प्रायः उत्क्रमणीय होते हैं। (ii) रासायनिक परिवर्तन प्रायः अनुक्रमणीय होते हैं। सही विकल्प:",
     "Two statements: (i) Physical changes are usually reversible. (ii) Chemical changes are usually irreversible. The correct option:",
     ["दोनों सही हैं", "दोनों गलत हैं", "केवल (i) सही", "केवल (ii) सही"],
     ["Both are correct", "Both are wrong", "Only (i) correct", "Only (ii) correct"],
     0,
     "दोनों 'प्रायः' के साथ सही — यही अध्याय का नियम है।",
     "Both are correct with 'usually' — that is the chapter's rule."),

    ("physical-change", "medium",
     "आटे की रोटी पर बेलन (रोलिंग पिन) से की गई क्रिया का परिवर्तन-वर्ग क्या है?",
     "What is the class of change in the action of a rolling pin on a dough roti?",
     ["भौतिक — आकृति बदलती है", "रासायनिक — नया पदार्थ बनता है", "दहन", "अवक्षेपण"],
     ["Physical — the shape changes", "Chemical — a new substance forms", "Combustion", "Precipitation"],
     0,
     "बेलने से आकार बदला — पदार्थ वही रहा।",
     "Rolling changed the shape — the substance stayed."),

    ("physical-change", "medium",
     "कोई घटना बार-बार आगे-पीछे हो सकती है और उसमें कभी कोई नया पदार्थ नहीं बनता। ऐसी घटनाओं का सामान्य नाम क्या है?",
     "An event can go back and forth repeatedly and never forms any new substance. What is such an event generally called?",
     ["भौतिक परिवर्तन", "रासायनिक परिवर्तन", "दहन", "विद्युत लेपन"],
     ["A physical change", "A chemical change", "Combustion", "Electroplating"],
     0,
     "नया पदार्थ नहीं = भौतिक — सीधी कसौटी।",
     "No new substance = physical — the direct test."),

    # ---- hard (9) ----
    ("physical-change", "hard",
     "तीन कथन: (i) भौतिक परिवर्तन में नया पदार्थ नहीं बनता। (ii) सभी भौतिक परिवर्तन सदैव उत्क्रमणीय होते हैं। (iii) भौतिक परिवर्तन में मूल पदार्थ बना रहता है। गलत कथन:",
     "Three statements: (i) No new substance forms in a physical change. (ii) All physical changes are always reversible. (iii) In a physical change the original substance remains. The wrong statement:",
     ["कथन (ii) — भौतिक परिवर्तन प्रायः उत्क्रमणीय होते हैं, सभी नहीं", "कथन (i)", "कथन (iii)", "तीनों सही"],
     ["Statement (ii) — physical changes are usually reversible, not all", "Statement (i)", "Statement (iii)", "All three correct"],
     0,
     "'सदैव' शब्द ने कथन को गलत बना दिया — सही शब्द 'प्रायः' है।",
     "The word 'always' made the statement wrong — the right word is 'usually'."),

    ("physical-change", "hard",
     "सोच-परीक्षण: कोई परिवर्तन पूर्णतः उत्क्रमणीय है और उसमें कभी कोई नया पदार्थ नहीं बनता। वह किस वर्ग में सुरक्षित रूप से गिना जाएगा?",
     "Thought experiment: a change is fully reversible and never forms any new substance. In which class will it safely be counted?",
     ["भौतिक परिवर्तन", "रासायनिक परिवर्तन", "दोनों वर्गों में", "किसी वर्ग में नहीं"],
     ["A physical change", "A chemical change", "In both classes", "In neither class"],
     0,
     "दोनों लक्षण भौतिक परिवर्तन की परिभाषा पूरी करते हैं।",
     "Both traits fulfil the definition of a physical change."),

    ("physical-change", "hard",
     "चीनी और चूना — दोनों जल में घुलते हैं। क्या दोनों घटनाएँ एक ही वर्ग की हैं? सही निष्कर्ष चुनिए:",
     "Sugar and lime — both dissolve in water. Are the two events of the same class? Choose the correct conclusion:",
     ["नहीं — चीनी का घुलना भौतिक (नया पदार्थ नहीं), चूने का घुलना रासायनिक (ऊष्मा और नया पदार्थ)", "हाँ — दोनों भौतिक", "हाँ — दोनों रासायनिक", "घुलने वाली हर चीज़ रासायनिक"],
     ["No — sugar's dissolving is physical (no new substance); lime's dissolving is chemical (heat and a new substance)", "Yes — both physical", "Yes — both chemical", "Everything that dissolves is chemical"],
     0,
     "बाहरी क्रिया (घुलना) एक जैसी, परिणाम भिन्न — कसौटी नया पदार्थ है।",
     "The outward act (dissolving) looks alike, the outcomes differ — the test is the new substance."),

    ("physical-change", "hard",
     "चार युग्मों में से कौन-सा युग्म 'दोनों भौतिक' है?",
     "Which of the four pairs is 'both physical'?",
     ["पिघलना और भंगन", "पिघलना और दहन", "भंगन और दही जमना", "जंग लगना और कतरना"],
     ["Melting and breaking", "Melting and burning", "Breaking and curd setting", "Rusting and cutting"],
     0,
     "पिघलना-भंगन दोनों में पदार्थ वही रहता है।",
     "In both melting and breaking the substance remains."),

    ("physical-change", "hard",
     "भ्रांति: 'आकार बदल गया तो पदार्थ भी नया बन गया।' इस भ्रांति का खंडन किस तर्क से होगा?",
     "Misconception: 'If the shape changed, the substance too became new.' Which argument refutes this misconception?",
     ["आकार भौतिक गुण है — उसके बदलने से पदार्थ की पहचान नहीं बदलती; कटे कागज़ के टुकड़े भी कागज़ ही हैं", "आकार बदलने से गैस निकलती है", "हर आकार-परिवर्तन में रंग बदलता है", "भ्रांति सही है"],
     ["Shape is a physical property — changing it does not change the substance's identity; the cut pieces of paper are still paper", "Changing shape releases a gas", "Every shape-change alters the colour", "The misconception is correct"],
     0,
     "पहचान और आकार अलग-अलग बातें हैं।",
     "Identity and shape are two different things."),

    ("physical-change", "hard",
     "तुलना-तालिका में भौतिक बनाम रासायनिक की सबसे सुसंगत पंक्ति चुनिए:",
     "Choose the most consistent row for physical versus chemical in the comparison table:",
     ["भौतिक: नया पदार्थ नहीं, प्रायः उत्क्रमणीय; रासायनिक: नया पदार्थ, प्रायः अनुक्रमणीय", "भौतिक: नया पदार्थ, प्रायः अनुक्रमणीय; रासायनिक: नया पदार्थ नहीं", "भौतिक: प्रायः अनुक्रमणीय; रासायनिक: नया पदार्थ नहीं", "दोनों: नया पदार्थ बनता है"],
     ["Physical: no new substance, usually reversible; chemical: new substance, usually irreversible", "Physical: new substance, usually irreversible; chemical: no new substance", "Physical: usually irreversible; chemical: no new substance", "Both: a new substance forms"],
     0,
     "यही दो कॉलम अध्याय की रीढ़ हैं।",
     "These two columns are the backbone of the chapter."),

    ("physical-change", "hard",
     "'भौतिक परिवर्तन केवल ठोस वस्तुओं में होते हैं' — इस कथन का निर्णय और कारण चुनिए:",
     "'Physical changes occur only in solid objects' — judge this statement and choose the reason:",
     ["गलत — चीनी जैसे पदार्थ का द्रव जल में घुलना भी भौतिक परिवर्तन है", "सही — द्रवों में कभी परिवर्तन नहीं होता", "सही — केवल ठोस टूटता है", "गलत — भौतिक परिवर्तन केवल गैसों में होता है"],
     ["Wrong — a substance like sugar dissolving in liquid water is also a physical change", "Correct — liquids never change", "Correct — only solids break", "Wrong — physical changes occur only in gases"],
     0,
     "घुलना (द्रव में) भौतिक परिवर्तन का घरेलू उदाहरण है।",
     "Dissolving (in a liquid) is a household example of physical change."),

    ("physical-change", "hard",
     "एक घटना में आकार बदला और वापस भी आ गया; दूसरी में आकार बदला पर वापस नहीं आया — दोनों में नया पदार्थ नहीं बना। दोनों घटनाओं का सही वर्गीकरण:",
     "In one event the shape changed and returned; in another the shape changed and did not return — in both, no new substance formed. The correct classification of the two events:",
     ["दोनों भौतिक — उत्क्रमणीयता भिन्न होने पर भी वर्ग एक है", "पहली भौतिक, दूसरी रासायनिक", "दोनों रासायनिक", "पहली रासायनिक, दूसरी भौतिक"],
     ["Both physical — despite differing reversibility, the class is one", "First physical, second chemical", "Both chemical", "First chemical, second physical"],
     0,
     "वर्ग की कसौटी नया पदार्थ है, उत्क्रमणीयता नहीं।",
     "The class is decided by a new substance, not by reversibility."),

    ("physical-change", "hard",
     "कक्षा में चार घटनाएँ हुईं — (क) चाकू से रबड़ कटा (ख) पिन से गुब्बारा फूटा (ग) पैंसिल छीली गई (घ) रबड़ जलाया गया। 'अलग' घटना और उसका वर्ग चुनिए:",
     "Four events occurred in class — (a) rubber cut with a knife (b) balloon burst with a pin (c) pencil sharpened (d) rubber burnt. Choose the 'odd' event and its class:",
     ["(घ) — रासायनिक (नया पदार्थ बना)", "(क) — रासायनिक", "(ख) — कोई परिवर्तन नहीं", "(ग) — रासायनिक"],
     ["(d) — chemical (a new substance formed)", "(a) — chemical", "(b) — no change", "(c) — chemical"],
     0,
     "तीन घटनाओं में आकार-आकृति बदली; जलने में पदार्थ बदला।",
     "In three events shape or form changed; in burning the substance changed."),

    # ================= CHEMICAL CHANGE (50) =================
    # ---- easy (20) ----
    ("chemical-change", "easy",
     "रासायनिक परिवर्तन की मूल पहचान क्या है?",
     "What is the basic identity of a chemical change?",
     ["नए गुणों वाला नया पदार्थ बनना", "केवल आकार बदलना", "केवल अवस्था बदलना", "केवल ताप बदलना"],
     ["Formation of a new substance with new properties", "Only a change of shape", "Only a change of state", "Only a change of temperature"],
     0,
     "नया पदार्थ — रासायनिक परिवर्तन की मूल कसौटी।",
     "A new substance — the core test of a chemical change."),

    ("chemical-change", "easy",
     "रासायनिक परिवर्तन में बने नए पदार्थ के गुण कैसे होते हैं?",
     "How are the properties of the new substance formed in a chemical change?",
     ["मूल पदार्थ से भिन्न", "मूल पदार्थ जैसे ही", "केवल रंग में भिन्न, बाकी सब समान", "गुण बदलते ही नहीं"],
     ["Different from the original substance", "Just like the original", "Different only in colour, rest same", "The properties do not change at all"],
     0,
     "नए पदार्थ के गुण भिन्न होते हैं — यही उसकी पहचान।",
     "The new substance's properties are different — that is its identity."),

    ("chemical-change", "easy",
     "चाकमाक (मैग्नीशियम) जलने पर क्या बनता है?",
     "What forms when magnesium burns?",
     ["मैग्नीशियम ऑक्साइड", "मैग्नीशियम कार्बनेट", "गंधक डाइऑक्साइड गैस ही बनती है", "कुछ नहीं बनता"],
     ["Magnesium oxide", "Magnesium carbonate", "Only sulfur dioxide gas forms", "Nothing forms"],
     0,
     "जलते मैग्नीशियम से नया पदार्थ मैग्नीशियम ऑक्साइड बनता है।",
     "Burning magnesium gives the new substance magnesium oxide."),

    ("chemical-change", "easy",
     "रासायनिक परिवर्तन का संकेत नहीं है —",
     "Which is NOT a sign of a chemical change?",
     ["आकार का बदलना", "रंग का बदलना", "गैस का निकलना", "अवक्षेप का बनना"],
     ["A change of shape", "A change of colour", "Evolution of gas", "Formation of a precipitate"],
     0,
     "रंग, गैस, ताप, अवक्षेप — चार संकेत; आकार इनमें नहीं।",
     "Colour, gas, temperature, precipitate — the four signs; shape is not one."),

    ("chemical-change", "easy",
     "रासायनिक परिवर्तन प्रायः कैसे होते हैं?",
     "Chemical changes are usually —",
     ["अनुक्रमणीय", "उत्क्रमणीय", "सदैव उत्क्रमणीय", "कभी अनुक्रमणीय नहीं"],
     ["Irreversible", "Reversible", "Always reversible", "Never irreversible"],
     0,
     "नया पदार्थ बन जाने पर पुराना रूप प्रायः वापस नहीं आता।",
     "Once a new substance forms, the old form usually does not return."),

    ("chemical-change", "easy",
     "रासायनिक परिवर्तन में ऊर्जा का क्या होता है?",
     "What happens to energy in a chemical change?",
     ["उसका अवशोषण या उत्सर्जन होता है", "कुछ नहीं होता", "ऊर्जा सदैव बनी रहती है", "ऊर्जा सदैव नष्ट हो जाती है"],
     ["It is absorbed or released", "Nothing happens to it", "Energy always stays put", "Energy is always destroyed"],
     0,
     "कुछ रासायनिक परिवर्तन ऊर्जा लेते हैं, कुछ देते हैं।",
     "Some chemical changes take in energy, some give it out."),

    ("chemical-change", "easy",
     "किसी मिश्रण से गैस के बुलबुले निकलना किस परिवर्तन का संकेत है?",
     "Bubbles of gas escaping from a mixture are a sign of which change?",
     ["रासायनिक परिवर्तन", "भौतिक परिवर्तन", "कोई परिवर्तन नहीं", "केवल उबाल"],
     ["A chemical change", "A physical change", "No change", "Only boiling"],
     0,
     "गैस निकलना चारों संकेतों में एक है।",
     "Gas evolution is one of the four signs."),

    ("chemical-change", "easy",
     "दही जमना किस प्रकार का परिवर्तन है?",
     "Setting of curd is which type of change?",
     ["रासायनिक", "भौतिक", "कोई परिवर्तन नहीं", "केवल अवस्था-परिवर्तन"],
     ["Chemical", "Physical", "No change", "Only a change of state"],
     0,
     "दूध से भिन्न गुणों वाला दही बनता है — नया पदार्थ।",
     "Curd with properties different from milk forms — a new substance."),

    ("chemical-change", "easy",
     "किसी परिवर्तन के दौरान मिश्रण का रंग बदल गया। यह किसका संकेत है?",
     "During a change the mixture's colour changed. What is this a sign of?",
     ["रासायनिक परिवर्तन का", "भौतिक परिवर्तन का", "किसी परिवर्तन का नहीं", "केवल आकार-परिवर्तन का"],
     ["Of a chemical change", "Of a physical change", "Of no change", "Only of a shape change"],
     0,
     "रंग-परिवर्तन रासायनिक परिवर्तन का सूचक संकेत है।",
     "A colour change is an indicative sign of a chemical change."),

    ("chemical-change", "easy",
     "चीनी का घुलना और चाकमाक का जलना — इनमें रासायनिक परिवर्तन कौन-सा है?",
     "Dissolving of sugar and burning of magnesium — which of these is a chemical change?",
     ["चाकमाक का जलना", "चीनी का घुलना", "दोनों", "कोई नहीं"],
     ["Burning of magnesium", "Dissolving of sugar", "Both", "Neither"],
     0,
     "जलने पर नया पदार्थ बनता है; घुलने पर नहीं।",
     "Burning forms a new substance; dissolving does not."),

    ("chemical-change", "easy",
     "रासायनिक परिवर्तन के बाद मूल पदार्थ का क्या होता है?",
     "What happens to the original substance after a chemical change?",
     ["वह नए पदार्थ में बदल जाता है", "वह वैसा ही बना रहता है", "वह केवल आकार बदलता है", "वह केवल अवस्था बदलता है"],
     ["It changes into a new substance", "It remains as it was", "It only changes shape", "It only changes state"],
     0,
     "रासायनिक परिवर्तन मूल पदार्थ को ही नए में बदल देता है।",
     "A chemical change converts the original substance itself into something new."),

    ("chemical-change", "easy",
     "प्रयोग के दौरान नली को छूने पर नली गर्म या ठंडी महसूस हुई (ताप बदला)। यह किसका संभावित संकेत है?",
     "During an experiment the tube felt warm or cool to touch (the temperature changed). What is this a probable sign of?",
     ["रासायनिक परिवर्तन का", "केवल आकार-परिवर्तन का", "किसी परिवर्तन का नहीं", "केवल रंग-परिवर्तन का"],
     ["Of a chemical change", "Only of a shape change", "Of no change", "Only of a colour change"],
     0,
     "ताप-परिवर्तन ऊर्जा के आने-जाने का, और रासायनिक परिवर्तन का संकेत है।",
     "A temperature change signals energy going in or out — and a chemical change."),

    ("chemical-change", "easy",
     "निम्न में से कौन-सा रासायनिक परिवर्तन नहीं है?",
     "Which of the following is NOT a chemical change?",
     ["बर्फ का पिघलना", "दही का जमना", "लकड़ी का जलना", "लोहे का जंगना"],
     ["Melting of ice", "Setting of curd", "Burning of wood", "Rusting of iron"],
     0,
     "पिघलने में जल वही रहता है — भौतिक परिवर्तन।",
     "In melting the water remains the same — a physical change."),

    ("chemical-change", "easy",
     "'P = Same substance, C = Completely new' — इस सूत्र के अनुसार 'C' किसे कहते हैं?",
     "As per the formula 'P = Same substance, C = Completely new', what does 'C' stand for?",
     ["रासायनिक परिवर्तन", "भौतिक परिवर्तन", "उत्क्रमणीय परिवर्तन", "अवस्था-परिवर्तन"],
     ["A chemical change", "A physical change", "A reversible change", "A change of state"],
     0,
     "C = Completely new — पूरी तरह नया पदार्थ = रासायनिक।",
     "C = Completely new — a wholly new substance = chemical."),

    ("chemical-change", "easy",
     "रासायनिक परिवर्तन के चारों संकेतों का सही समूह कौन-सा है?",
     "Which is the correct group of the four signs of a chemical change?",
     ["रंग परिवर्तन, गैस निकलना, ताप परिवर्तन, अवक्षेप बनना", "आकार, आकृति, अवस्था, रंग", "कटना, टूटना, पिघलना, घुलना", "रंग, गंध, चमक, आकार"],
     ["Colour change, gas evolution, temperature change, precipitate formation", "Shape, form, state, colour", "Cutting, breaking, melting, dissolving", "Colour, smell, shine, shape"],
     0,
     "यही चौकड़ी रासायनिक परिवर्तन के संकेत है।",
     "This quartet is the signs of a chemical change."),

    ("chemical-change", "easy",
     "माचिस की तीली जलाना (दहन) कैसा परिवर्तन है?",
     "Lighting a matchstick (combustion) is what kind of change?",
     ["रासायनिक परिवर्तन", "भौतिक परिवर्तन", "उत्क्रमणीय भौतिक परिवर्तन", "कोई परिवर्तन नहीं"],
     ["A chemical change", "A physical change", "A reversible physical change", "No change"],
     0,
     "दहन में नए पदार्थ बनते हैं — रासायनिक।",
     "Combustion forms new substances — chemical."),

    ("chemical-change", "easy",
     "जलने के बाद बने पदार्थ की मैग्नीशियम से तुलना में क्या कहा जा सकता है?",
     "What can be said about the substance formed after burning, compared with magnesium?",
     ["उसके गुण मैग्नीशियम से भिन्न हैं", "उसके गुण मैग्नीशियम जैसे ही हैं", "वह मैग्नीशियम ही है", "वह कोई पदार्थ है ही नहीं"],
     ["Its properties are different from magnesium", "Its properties are just like magnesium's", "It is magnesium itself", "It is not a substance at all"],
     0,
     "रासायनिक परिवर्तन का नया पदार्थ भिन्न गुण लिए होता है।",
     "A chemical change's new substance carries different properties."),

    ("chemical-change", "easy",
     "अवक्षेप का बनना किस परिवर्तन का संकेत है?",
     "Formation of a precipitate is a sign of which change?",
     ["रासायनिक परिवर्तन", "भौतिक परिवर्तन", "अवस्था-परिवर्तन", "कोई परिवर्तन नहीं"],
     ["A chemical change", "A physical change", "A change of state", "No change"],
     0,
     "घोल में ठोस अवक्षेप का जमना रासायनिक संकेत है।",
     "A solid precipitate settling in a solution is a chemical sign."),

    ("chemical-change", "easy",
     "दो कथन: (i) रासायनिक परिवर्तन में नया पदार्थ बनता है। (ii) रासायनिक परिवर्तन में ऊर्जा का अवशोषण या उत्सर्जन हो सकता है। सही विकल्प:",
     "Two statements: (i) A new substance forms in a chemical change. (ii) In a chemical change energy may be absorbed or released. The correct option:",
     ["दोनों सही", "दोनों गलत", "केवल (i) सही", "केवल (ii) सही"],
     ["Both correct", "Both wrong", "Only (i) correct", "Only (ii) correct"],
     0,
     "दोनों कथन रासायनिक परिवर्तन की परिभाषा के अंग हैं।",
     "Both statements are part of the definition of a chemical change."),

    ("chemical-change", "easy",
     "किसी घटना में मूल पदार्थ नए गुणों वाले पदार्थ में बदल गया। घटना का नाम बताइए:",
     "In an event the original substance changed into a substance with new properties. Name the event:",
     ["रासायनिक परिवर्तन", "भौतिक परिवर्तन", "उत्क्रमणीय परिवर्तन", "आकृति-परिवर्तन"],
     ["A chemical change", "A physical change", "A reversible change", "A change of form"],
     0,
     "नए गुण वाला नया पदार्थ = रासायनिक परिवर्तन।",
     "A new substance with new properties = a chemical change."),

    # ---- medium (21) ----
    ("chemical-change", "medium",
     "प्रयोग: एक पट्टी जलाई गई; जलने के बाद बचा पदार्थ जलने से पहले वाली पट्टी से पूर्णतः भिन्न था। परिवर्तन का वर्ग और आधार चुनिए:",
     "Experiment: a strip was burnt; the substance left after burning was completely different from the strip before burning. Choose the class of change and its basis:",
     ["रासायनिक — नए गुणों वाला नया पदार्थ बना", "भौतिक — केवल आकार बदला", "भौतिक — केवल अवस्था बदली", "कोई परिवर्तन नहीं हुआ"],
     ["Chemical — a new substance with new properties formed", "Physical — only the shape changed", "Physical — only the state changed", "No change occurred"],
     0,
     "जलने के आगे-पीछे के पदार्थ भिन्न — यही रासायनिक परिवर्तन है।",
     "The substances before and after burning differ — that is a chemical change."),

    ("chemical-change", "medium",
     "प्रेक्षण: दो घोल मिलाने पर मिश्रण से गैस के बुलबुले उठे और नली गर्म हो गई। निष्कर्ष क्या है?",
     "Observation: on mixing two solutions, bubbles of gas rose from the mixture and the tube became warm. What is the conclusion?",
     ["रासायनिक परिवर्तन हुआ — गैस और ताप दोनों संकेत मिले", "भौतिक परिवर्तन हुआ", "केवल आकार बदला", "कुछ नहीं हुआ"],
     ["A chemical change occurred — both gas and temperature signs appeared", "A physical change occurred", "Only the shape changed", "Nothing happened"],
     0,
     "दो संकेत एक साथ — निष्कर्ष निश्चित।",
     "Two signs together — the conclusion is firm."),

    ("chemical-change", "medium",
     "दो कथन: (i) रासायनिक परिवर्तन में सदैव नया पदार्थ बनता है। (ii) रासायनिक परिवर्तन सदैव अनुक्रमणीय होते हैं। सही विकल्प:",
     "Two statements: (i) A new substance always forms in a chemical change. (ii) Chemical changes are always irreversible. The correct option:",
     ["(i) सही; (ii) गलत — वे प्रायः अनुक्रमणीय होते हैं, सदैव नहीं", "दोनों सही", "दोनों गलत", "(i) गलत, (ii) सही"],
     ["(i) correct; (ii) wrong — they are usually irreversible, not always", "Both correct", "Both wrong", "(i) wrong, (ii) correct"],
     0,
     "नया पदार्थ आवश्यक; अनुक्रमणीयता के आगे 'प्रायः' लगा है।",
     "A new substance is essential; irreversibility carries the word 'usually'."),

    ("chemical-change", "medium",
     "क्या 'ताप बदलना' अकेला पर्याप्त प्रमाण है? सोचिए — ठंडा जल रखने पर भी ताप बदलता है पर पदार्थ वही रहता है। सही तर्क चुनिए:",
     "Is 'a temperature change' alone sufficient proof? Think — even cold water kept aside changes temperature yet the substance stays the same. Choose the correct reasoning:",
     ["ताप-परिवर्तन संकेत है, पर निर्णय की अंतिम कसौटी नया पदार्थ बनना है", "ताप बदलने पर हमेशा रासायनिक परिवर्तन होता है", "ताप कभी नहीं बदलता", "ताप-परिवर्तन भौतिक परिवर्तन का संकेत है"],
     ["A temperature change is a sign, but the final test of the verdict is the formation of a new substance", "Whenever temperature changes, a chemical change occurs", "Temperature never changes", "A temperature change is a sign of a physical change"],
     0,
     "संकेत इशारा देते हैं; फैसला 'नया पदार्थ' से होता है।",
     "Signs point the way; the verdict comes from 'a new substance'."),

    ("chemical-change", "medium",
     "प्रेक्षण: दो साफ घोल मिलाने पर नीचे ठोस पदार्थ जमा हो गया। यह किसे कहते हैं और यह किसका संकेत है?",
     "Observation: on mixing two clear solutions a solid substance settled at the bottom. What is this called and a sign of what?",
     ["अवक्षेप — रासायनिक परिवर्तन का संकेत", "बुलबुले — भौतिक परिवर्तन का", "रंग — किसी परिवर्तन का नहीं", "आकार — भौतिक परिवर्तन का"],
     ["A precipitate — a sign of a chemical change", "Bubbles — of a physical change", "Colour — of no change", "Shape — of a physical change"],
     0,
     "अवक्षेप बनना चारों रासायनिक संकेतों में गिना जाता है।",
     "Precipitate formation is counted among the four chemical signs."),

    ("chemical-change", "medium",
     "पहेली: मुझमें मूल पदार्थ नए पदार्थ में बदल जाता है, नए पदार्थ के गुण भिन्न होते हैं और मैं प्रायः लौटने नहीं देता। मैं कौन हूँ?",
     "Riddle: in me the original substance turns into a new one, the new one's properties differ, and I usually do not allow a return. Who am I?",
     ["रासायनिक परिवर्तन", "भौतिक परिवर्तन", "उत्क्रमणीय परिवर्तन", "आकृति-परिवर्तन"],
     ["A chemical change", "A physical change", "A reversible change", "A change of form"],
     0,
     "नया पदार्थ + भिन्न गुण + प्रायः अनुक्रमणीय — रासायनिक।",
     "New substance + different properties + usually irreversible — chemical."),

    ("chemical-change", "medium",
     "कुछ रासायनिक परिवर्तन ऊर्जा अवशोषित करते हैं और कुछ उत्सर्जित करते हैं। इस कथन के अनुसार सही निष्कर्ष चुनिए:",
     "Some chemical changes absorb energy and some release it. Per this statement, choose the correct conclusion:",
     ["ऊर्जा का आदान-प्रदान रासायनिक परिवर्तन की सामान्य विशेषता है", "केवल उत्सर्जन होता है", "केवल अवशोषण होता है", "रासायनिक परिवर्तन में ऊर्जा वर्जित है"],
     ["An exchange of energy is a general feature of chemical changes", "Only release occurs", "Only absorption occurs", "Energy is forbidden in chemical changes"],
     0,
     "अवशोषण या उत्सर्जन — दोनों दिशाएँ संभव।",
     "Absorption or release — both directions are possible."),

    ("chemical-change", "medium",
     "जला चाकमाक और घोल में चीनी — इन दोनों घटनाओं की तुलना का एकमात्र निर्णायक आधार चुनिए:",
     "Burnt magnesium and sugar in a solution — choose the sole decisive basis for comparing these two events:",
     ["पहली में नया पदार्थ बना, दूसरी में नहीं", "पहली में आकार बदला, दूसरी में नहीं", "दोनों में नया पदार्थ बना", "दोनों में कुछ नहीं बदला"],
     ["In the first a new substance formed; in the second it did not", "In the first the shape changed; in the second it did not", "A new substance formed in both", "Nothing changed in either"],
     0,
     "चाकमाक जलकर ऑक्साइड बना; चीनी घुलकर चीनी ही रही।",
     "The magnesium burnt to an oxide; the sugar dissolved and stayed sugar."),

    ("chemical-change", "medium",
     "उलटा-प्रश्न: निम्न में से किस घटना में नया पदार्थ नहीं बनता?",
     "Reverse question: in which of these events is no new substance formed?",
     ["चीनी का जल में घुलना", "लकड़ी का जलना", "दही का जमना", "लोहे का जंगना"],
     ["Sugar dissolving in water", "Wood burning", "Curd setting", "Iron rusting"],
     0,
     "तीन घटनाओं में नए पदार्थ बने; घुलने में चीनी वही रही।",
     "In three events new substances formed; in dissolving the sugar stayed."),

    ("chemical-change", "medium",
     "तीन कथन: (i) गैस निकलना रासायनिक संकेत है। (ii) रंग बदलना रासायनिक संकेत है। (iii) आकार बदलना रासायनिक संकेत है। गलत कथन:",
     "Three statements: (i) Gas evolution is a chemical sign. (ii) Colour change is a chemical sign. (iii) Shape change is a chemical sign. The wrong statement:",
     ["कथन (iii) — आकार-परिवर्तन भौतिक गुण का बदलाव है", "कथन (i)", "कथन (ii)", "तीनों सही"],
     ["Statement (iii) — a shape change is a change of a physical property", "Statement (i)", "Statement (ii)", "All three correct"],
     0,
     "आकार संकेत-सूची में नहीं है।",
     "Shape is not on the sign list."),

    ("chemical-change", "medium",
     "चूने को जल में घोला गया — घोल गर्म हो गया और नया पदार्थ बना। वर्ग-निर्णय कीजिए:",
     "Lime was dissolved in water — the solution became hot and a new substance formed. Make the class verdict:",
     ["रासायनिक परिवर्तन — 'घुलना' होते हुए भी", "भौतिक परिवर्तन — घुलना तो है", "कोई परिवर्तन नहीं", "केवल अवस्था-परिवर्तन"],
     ["A chemical change — despite it being a 'dissolving'", "A physical change — after all it is dissolving", "No change", "Only a change of state"],
     0,
     "ऊष्मा + नया पदार्थ = रासायनिक; बाहरी क्रिया से मत भटकिए।",
     "Heat + a new substance = chemical; do not be misled by the outward act."),

    ("chemical-change", "medium",
     "कारण-श्रृंखला पूरी कीजिए: रंग बदला + गैस निकली → ______ → रासायनिक परिवर्तन",
     "Complete the cause-chain: colour changed + gas evolved → ______ → chemical change",
     ["नया पदार्थ बना", "आकार बदला", "आकृति बदली", "पदार्थ वही रहा"],
     ["A new substance formed", "The shape changed", "The form changed", "The substance stayed the same"],
     0,
     "संकेतों के पीछे की वास्तविकता नए पदार्थ का बनना है।",
     "The reality behind the signs is the formation of a new substance."),

    ("chemical-change", "medium",
     "भौतिक और रासायनिक परिवर्तन की उत्क्रमणीयता की सही जोड़ी चुनिए:",
     "Choose the correct pairing of the reversibility of physical and chemical changes:",
     ["भौतिक — प्रायः उत्क्रमणीय; रासायनिक — प्रायः अनुक्रमणीय", "भौतिक — प्रायः अनुक्रमणीय; रासायनिक — प्रायः उत्क्रमणीय", "दोनों — प्रायः उत्क्रमणीय", "दोनों — प्रायः अनुक्रमणीय"],
     ["Physical — usually reversible; chemical — usually irreversible", "Physical — usually irreversible; chemical — usually reversible", "Both — usually reversible", "Both — usually irreversible"],
     0,
     "यही जोड़ी परीक्षा में बार-बार पूछी जाती है।",
     "This exact pairing is asked again and again in exams."),

    ("chemical-change", "medium",
     "प्रेक्षण-अनुमान: एक बंद बोतल में रखे पदार्थ में समय के साथ रंग बदल गया और मूल पदार्थ वापस नहीं लाया जा सका। सबसे उचित निष्कर्ष:",
     "Observation-inference: in a substance kept in a sealed bottle the colour changed over time and the original substance could not be brought back. The most reasonable conclusion:",
     ["रासायनिक परिवर्तन हुआ — नया पदार्थ बन गया", "भौतिक परिवर्तन हुआ", "केवल आकार बदला", "बोतल का रंग बदला"],
     ["A chemical change occurred — a new substance formed", "A physical change occurred", "Only the shape changed", "The bottle's colour changed"],
     0,
     "रंग-परिवर्तन + अनुक्रमणीयता — रासायनिक परिवर्तन का चित्र।",
     "Colour change + irreversibility — the picture of a chemical change."),

    ("chemical-change", "medium",
     "कथन: 'हर वह घटना जिसमें गर्मी या ठंडक महसूस होती है, रासायनिक परिवर्तन है।' इसका निर्णय:",
     "Statement: 'Every event in which heat or coolness is felt is a chemical change.' Judge it:",
     ["गलत — ताप-परिवर्तन संकेत है, पर निर्णय नए पदार्थ से होगा", "सही — गर्मी महसूस हो तो रासायनिक", "सही — ठंडक महसूस हो तो भौतिक", "कथन का निर्णय संभव नहीं"],
     ["Wrong — a temperature change is a sign, but the verdict will come from a new substance", "Correct — if heat is felt it is chemical", "Correct — if coolness is felt it is physical", "The statement cannot be judged"],
     0,
     "संकेत और निर्णय को मिलाना भ्रांति है।",
     "Confusing a sign with the verdict is a misconception."),

    ("chemical-change", "medium",
     "दही जमने के बाद उसी दही से आसानी से पहले जैसा दूध नहीं बनाया जा सकता। यह किस गुण का उदाहरण है?",
     "After curd has set, the same curd cannot easily be turned back into the earlier milk. This is an example of which feature?",
     ["रासायनिक परिवर्तन की प्रायः अनुक्रमणीयता", "भौतिक परिवर्तन की उत्क्रमणीयता", "अवस्था-परिवर्तन", "आकृति-परिवर्तन"],
     ["The usual irreversibility of a chemical change", "The reversibility of a physical change", "A change of state", "A change of form"],
     0,
     "नया पदार्थ बनने के बाद वापसी प्रायः नहीं।",
     "After a new substance forms, a return is usually not possible."),

    ("chemical-change", "medium",
     "जलते लकड़ी के टुकड़े से धुआँ उठा और आसपास गर्मी महसूस हुई। इन प्रेक्षणों का वर्गीकरण कीजिए:",
     "Smoke rose from a burning piece of wood and warmth was felt around. Classify these observations:",
     ["गैस और ताप — रासायनिक परिवर्तन (दहन) के संकेत", "आकार और आकृति — भौतिक संकेत", "रंग और आकार — कोई संकेत नहीं", "केवल अवस्था-परिवर्तन"],
     ["Gas and temperature — signs of a chemical change (combustion)", "Shape and form — physical signs", "Colour and shape — no signs", "Only a change of state"],
     0,
     "दहन के दो संकेत एक साथ दिखे।",
     "Two signs of combustion appeared together."),

    ("chemical-change", "medium",
     "रिक्त-तर्क: रासायनिक परिवर्तन के संकेत (रंग, गैस, ताप, अवक्षेप) वास्तव में किस एक होने के बाहरी प्रमाण हैं?",
     "Fill in the logic: the signs of a chemical change (colour, gas, temperature, precipitate) are actually the outward proofs of what single happening?",
     ["नए पदार्थ का बनना", "आकार का बदलना", "अवस्था का बदलना", "पदार्थ का वही रहना"],
     ["The formation of a new substance", "A change of shape", "A change of state", "The substance staying the same"],
     0,
     "संकेत छाया हैं; नया पदार्थ वस्तु है।",
     "The signs are the shadow; the new substance is the object."),

    ("chemical-change", "medium",
     "वर्गीकरण: पिघलना, जंग लगना, कागज़ मोड़ना, दही जमना — इनमें रासायनिक युग्म कौन-सा है?",
     "Classify: melting, rusting, folding paper, curd setting — which is the chemical pair?",
     ["जंग लगना और दही जमना", "पिघलना और जंग लगना", "कागज़ मोड़ना और पिघलना", "पिघलना और दही जमना"],
     ["Rusting and curd setting", "Melting and rusting", "Folding paper and melting", "Melting and curd setting"],
     0,
     "दोनों में नया पदार्थ बनता है।",
     "In both, a new substance forms."),

    ("chemical-change", "medium",
     "किसी रासायनिक परिवर्तन की ऊर्जा-दशा के बारे में पहले से क्या कहा जा सकता है?",
     "What can be said in advance about the energy situation of a chemical change?",
     ["केवल इतना — ऊर्जा का अवशोषण या उत्सर्जन होगा", "हमेशा ऊर्जा उत्सर्जित होगी", "हमेशा ऊर्जा अवशोषित होगी", "ऊर्जा का कोई लेन-देन नहीं होगा"],
     ["Only this — energy will be absorbed or released", "Energy will always be released", "Energy will always be absorbed", "No exchange of energy will occur"],
     0,
     "दिशा नहीं, द्वैत पक्का — अवशोषण या उत्सर्जन।",
     "Not the direction, but the duality is certain — absorption or release."),

    ("chemical-change", "medium",
     "जली हुई वस्तु को पुनः मूल रूप में लाना प्रायः संभव नहीं होता। इसका कारण-चुनाव कीजिए:",
     "Bringing a burnt thing back to its original form is usually not possible. Choose the reason:",
     ["जलने में नया पदार्थ बन चुका है — रासायनिक परिवर्तन प्रायः अनुक्रमणीय है", "जलने में केवल आकार बदलता है", "जलना भौतिक परिवर्तन है", "जलने में पदार्थ नहीं बदलता"],
     ["In burning a new substance has already formed — a chemical change is usually irreversible", "In burning only the shape changes", "Burning is a physical change", "In burning the substance does not change"],
     0,
     "नए पदार्थ की वापसी प्रायः नहीं होती।",
     "A new substance usually does not return."),

    # ---- hard (9) ----
    ("chemical-change", "hard",
     "तीन कथन: (i) नया पदार्थ बनना रासायनिक परिवर्तन की आवश्यक शर्त है। (ii) रंग-गैस-ताप-अवक्षेप किसी रासायनिक परिवर्तन के संकेत हैं। (iii) रासायनिक परिवर्तन सदैव अनुक्रमणीय होते हैं। सही समूह:",
     "Three statements: (i) Formation of a new substance is the necessary condition of a chemical change. (ii) Colour-gas-temperature-precipitate are signs of a chemical change. (iii) Chemical changes are always irreversible. The correct set:",
     ["(i) और (ii) सही, (iii) गलत — वे प्रायः अनुक्रमणीय हैं", "तीनों सही", "केवल (iii) सही", "केवल (i) सही"],
     ["(i) and (ii) correct, (iii) wrong — they are usually irreversible", "All three correct", "Only (iii) correct", "Only (i) correct"],
     0,
     "'सदैव' कहीं नहीं — 'प्रायः' ही सही शब्द है।",
     "'Always' appears nowhere — 'usually' is the correct word."),

    ("chemical-change", "hard",
     "सोच-परीक्षण: जिस परिवर्तन को सरलता से पूर्ववत् किया जा सके और जिसमें पदार्थ की पहचान अचली रही हो — वह प्रायः किस वर्ग का होगा?",
     "Thought experiment: a change that can be simply undone and in which the substance's identity stayed fixed — which class will it usually belong to?",
     ["भौतिक — यह दोनों लक्षण उसी की परिभाषा हैं", "रासायनिक", "दोनों वर्गों का", "किसी वर्ग का नहीं"],
     ["Physical — both traits are its definition", "Chemical", "Of both classes", "Of neither class"],
     0,
     "पहचान + सरल वापसी = भौतिक।",
     "Identity + easy return = physical."),

    ("chemical-change", "hard",
     "भ्रांति: 'घोल से बिना गर्म किए बुलबुले उठ रहे हैं — पानी उबल रहा है, यह भौतिक परिवर्तन है।' भ्रांति कहाँ है?",
     "Misconception: 'Bubbles are rising from the solution without heating — the water is boiling, a physical change.' Where is the error?",
     ["बिना गर्म किए गैस के बुलबुले गैस-निकलने का रासायनिक संकेत हैं, उबाल का नहीं", "बुलबुले कभी नहीं उठते", "उबाल रासायनिक परिवर्तन है", "गैस-निकलना भौतिक संकेत है"],
     ["Gas bubbles rising without heating are the chemical sign of gas evolution, not boiling", "Bubbles never rise", "Boiling is a chemical change", "Gas evolution is a physical sign"],
     0,
     "उबाल को गर्मी चाहिए; बिना गर्मी के बुलबुले नए पदार्थ का इशारा हैं।",
     "Boiling needs heat; bubbles without heat point to a new substance."),

    ("chemical-change", "hard",
     "चार घटनाओं की वर्ग-तालिका में सही पंक्ति चुनिए:",
     "Choose the correct row in the class table of four events:",
     ["दही जमना — रासायनिक; कागज़ मोड़ना — भौतिक; जंग लगना — रासायनिक; मोम पिघलना — भौतिक", "दही जमना — भौतिक; कागज़ मोड़ना — रासायनिक; जंग लगना — भौतिक; मोम पिघलना — रासायनिक", "चारों — भौतिक", "चारों — रासायनिक"],
     ["Curd setting — chemical; folding paper — physical; rusting — chemical; wax melting — physical", "Curd setting — physical; folding paper — chemical; rusting — physical; wax melting — chemical", "All four — physical", "All four — chemical"],
     0,
     "कसौटी हर घटना पर एक जैसी लगाइए — नया पदार्थ बना या नहीं।",
     "Apply the same test to every event — did a new substance form or not."),

    ("chemical-change", "hard",
     "कथन: 'सभी रासायनिक परिवर्तन ऊष्मा छोड़ते हैं।' इसका निर्णय और सही रूप चुनिए:",
     "Statement: 'All chemical changes release heat.' Judge it and choose the correct form:",
     ["गलत — कुछ ऊर्जा अवशोषित करते हैं, कुछ उत्सर्जित", "सही — सभी ऊष्मा छोड़ते हैं", "सही — सभी ऊष्मा लेते हैं", "गलत — कोई ऊर्जा नहीं देता"],
     ["Wrong — some absorb energy, some release it", "Correct — all release heat", "Correct — all absorb heat", "Wrong — none gives out energy"],
     0,
     "अवशोषण और उत्सर्जन — दोनों दिशाएँ मान्य हैं।",
     "Absorption and release — both directions are valid."),

    ("chemical-change", "hard",
     "चूना-जल प्रयोग से दो निष्कर्ष निकले: (1) घोल गर्म हुआ (2) नया पदार्थ बना। इनसे 'घुलने' की क्रिया के बारे में सामान्य सबक क्या है?",
     "Two conclusions emerged from the lime-water experiment: (1) the solution became hot (2) a new substance formed. What general lesson about the act of 'dissolving' follows?",
     ["घुलने की बाहरी क्रिया वर्ग तय नहीं करती — निर्णय संकेतों और नए पदार्थ से होता है", "घुलना सदैव रासायनिक है", "घुलना सदैव भौतिक है", "गर्मी वर्ग से कोई संबंध नहीं"],
     ["The outward act of dissolving does not decide the class — the verdict comes from signs and a new substance", "Dissolving is always chemical", "Dissolving is always physical", "Heat has no relation to the class"],
     0,
     "एक ही क्रिया, दो वर्ग — कसौटी परिणाम है, क्रिया नहीं।",
     "One act, two classes — the test is the outcome, not the act."),

    ("chemical-change", "hard",
     "तीन प्रेक्षण: रंग बदला, अवक्षेप गिरा, मूल अवस्था वापस नहीं आई। निष्कर्ष-चयन:",
     "Three observations: the colour changed, a precipitate settled, the original condition did not return. Choose the conclusion:",
     ["तीनों संकेत रासायनिक परिवर्तन की ओर इशारा करते हैं", "तीनों भौतिक परिवर्तन के", "कोई निष्कर्ष नहीं", "केवल अवस्था-परिवर्तन हुआ"],
     ["All three signs point to a chemical change", "All three to a physical change", "No conclusion", "Only a change of state occurred"],
     0,
     "तीन में से तीन संकेत — निर्णय निश्चित।",
     "Three signs out of three — the verdict is certain."),

    ("chemical-change", "hard",
     "कौन-सा युग्म 'दोनों रासायनिक' है?",
     "Which pair is 'both chemical'?",
     ["दही जमना और जंग लगना", "दही जमना और मोम पिघलना", "जंग लगना और कागज़ कतरना", "मोम पिघलना और चीनी घुलना"],
     ["Curd setting and rusting", "Curd setting and wax melting", "Rusting and paper cutting", "Wax melting and sugar dissolving"],
     0,
     "दही और जंग — दोनों में नए पदार्थ बनते हैं।",
     "Curd and rust — in both, new substances form."),

    ("chemical-change", "hard",
     "जले हुए मैग्नीशियम की पट्टी पुनः चमकदार मैग्नीशियम नहीं बनती। इससे रासायनिक परिवर्तन की किस सामान्य विशेषता की पुष्टि होती है?",
     "A burnt magnesium strip does not become shiny magnesium again. Which general feature of chemical changes does this confirm?",
     ["प्रायः अनुक्रमणीयता — नया पदार्थ बनने के बाद वापसी कठिन", "प्रायः उत्क्रमणीयता", "आकार-परिवर्तन", "अवस्था-परिवर्तन"],
     ["The usual irreversibility — after a new substance forms, a return is difficult", "The usual reversibility", "A change of shape", "A change of state"],
     0,
     "ऑक्साइड बनने के बाद पट्टी वही नहीं रहती।",
     "After the oxide forms, the strip is never quite the same."),
]
