# -*- coding: utf-8 -*-
"""C02 part 2 — Physical & Chemical Changes (chemistry chapter-02).
T3 rusting-and-prevention (E20/M21/H9) + T4 chemical-changes-in-daily-life (E20/M22/H8).
Tuple: (topic, difficulty, q_hi, q_en, opts_hi[4], opts_en[4], correct_idx=0, expl_hi, expl_en)
Content authority: chapter-02 meta ONLY — rusting needs oxygen AND water;
prevention = painting, galvanising (zinc layer), oiling, alloying.
Daily-life chemical changes = digestion, respiration, photosynthesis, burning,
curd setting, electroplating (classification level only; no process mechanics).
"""

PART2 = [
    # ================= RUSTING AND PREVENTION (50) =================
    # ---- easy (20) ----
    ("rusting-and-prevention", "easy",
     "जंग किस धातु को लगता है?",
     "Which metal does rust attack?",
     ["लोहे को", "ताँबे को", "लकड़ी को", "काँच को"],
     ["Iron", "Copper", "Wood", "Glass"],
     0,
     "जंग लगना लोहे की समस्या है।",
     "Rusting is iron's problem."),

    ("rusting-and-prevention", "easy",
     "जंग लगने के लिए लोहे को किन दो की आवश्यकता होती है?",
     "Which two things does iron need for rusting?",
     ["ऑक्सीजन और जल — दोनों", "केवल ऑक्सीजन", "केवल जल", "केवल प्रकाश"],
     ["Oxygen and water — both", "Only oxygen", "Only water", "Only light"],
     0,
     "दोनों के संपर्क से मिलकर जंग लगता है।",
     "Contact with both together causes rusting."),

    ("rusting-and-prevention", "easy",
     "जंग लगना किस प्रकार का परिवर्तन है?",
     "Rusting is which type of change?",
     ["रासायनिक परिवर्तन", "भौतिक परिवर्तन", "कोई परिवर्तन नहीं", "केवल आकार-परिवर्तन"],
     ["A chemical change", "A physical change", "No change", "Only a shape change"],
     0,
     "जंग एक नया पदार्थ है — इसलिए रासायनिक।",
     "Rust is a new substance — hence chemical."),

    ("rusting-and-prevention", "easy",
     "जंग लगना लोहे का क्या कहलाता है?",
     "Rusting is called what of iron?",
     ["ऑक्सीकरण", "पिघलना", "भंगन", "विद्युत लेपन"],
     ["Oxidation", "Melting", "Breaking", "Electroplating"],
     0,
     "जंग लगना लोहे का ऑक्सीकरण है।",
     "Rusting is the oxidation of iron."),

    ("rusting-and-prevention", "easy",
     "गैल्वनाइज़िंग में लोहे पर किसकी परत चढ़ाई जाती है?",
     "In galvanising, a layer of which metal is coated on iron?",
     ["जस्ते (जिंक) की", "ताँबे की", "सोने की", "लोहे ही की"],
     ["Zinc", "Copper", "Gold", "Iron itself"],
     0,
     "जस्ते की परत — यही गैल्वनाइज़िंग (जस्तीकरण) है।",
     "A layer of zinc — that is galvanising."),

    ("rusting-and-prevention", "easy",
     "'जस्तीकरण' शब्द का अर्थ है —",
     "The word 'galvanising' means —",
     ["जस्ते की परत चढ़ाना", "रंग पोतना", "तेल लगाना", "लोहा पिघलाना"],
     ["Coating with a layer of zinc", "Applying paint", "Applying oil", "Melting the iron"],
     0,
     "जस्ता + परत = जस्तीकरण।",
     "Zinc + coating = galvanising."),

    ("rusting-and-prevention", "easy",
     "लोहे की वस्तुओं पर रंग पोतना (painting) किसे रोकता है?",
     "Painting iron objects prevents what?",
     ["जंग लगने को", "पिघलने को", "टूटने को", "गीला होने को"],
     ["Rusting", "Melting", "Breaking", "Getting wet"],
     0,
     "रंगना जंग-रोकथाम का सरल उपाय है।",
     "Painting is a simple remedy of rust prevention."),

    ("rusting-and-prevention", "easy",
     "लोहे के औजारों पर तेल लगाना किसके लिए है?",
     "Applying oil to iron tools is for what?",
     ["जंग से बचाव के लिए", "सुगंध के लिए", "रंग बदलने के लिए", "वजन बढ़ाने के लिए"],
     ["Protection from rust", "Fragrance", "Changing colour", "Increasing weight"],
     0,
     "तेल की परत जंग से बचाती है।",
     "A film of oil protects from rust."),

    ("rusting-and-prevention", "easy",
     "मिश्र धातु (alloy) बनाना किसके उपायों में गिना जाता है?",
     "Making an alloy is counted among the remedies of what?",
     ["जंग रोकथाम के", "जल शुद्धिकरण के", "विद्युत बचत के", "प्रकाश संश्लेषण के"],
     ["Rust prevention", "Water purification", "Saving electricity", "Photosynthesis"],
     0,
     "मिश्र धातु बनाना भी जंग रोकने का उपाय है।",
     "Alloying too is a way to prevent rust."),

    ("rusting-and-prevention", "easy",
     "जंग से बचाव के लिए लोहे को किसके संपर्क से बचाना होता है?",
     "To guard against rust, iron must be kept away from contact with what?",
     ["ऑक्सीजन और जल से", "केवल धूल से", "केवल प्रकाश से", "केवल ध्वनि से"],
     ["Oxygen and water", "Only dust", "Only light", "Only sound"],
     0,
     "संपर्क टूटा, तो जंग रुका।",
     "Break the contact, and rust stops."),

    ("rusting-and-prevention", "easy",
     "गीली लोहे की छड़ हवा में रखी गई। उसे जंग क्यों लगी?",
     "A wet iron rod was left in the air. Why did it rust?",
     ["जल भी था और हवा की ऑक्सीजन भी — दोनों शर्तें पूरी हुईं", "केवल गर्मी के कारण", "केवल प्रकाश के कारण", "छड़ पुरानी थी"],
     ["Water was there and the air's oxygen too — both conditions were met", "Only because of heat", "Only because of light", "The rod was old"],
     0,
     "जंग की दोनों शर्तें एक साथ मिल गईं।",
     "Both conditions of rust came together."),

    ("rusting-and-prevention", "easy",
     "जंग रोकथाम के उपायों में से कौन-सा नहीं है?",
     "Which of these is NOT a method of rust prevention?",
     ["लोहे को पानी में डूबा रखना", "रंगना", "गैल्वनाइज़िंग", "तेल लगाना"],
     ["Keeping iron immersed in water", "Painting", "Galvanising", "Oiling"],
     0,
     "पानी तो जंग की शर्त है, रोकथाम का उपाय नहीं।",
     "Water is a condition for rust, not a remedy."),

    ("rusting-and-prevention", "easy",
     "जंग लगना 'भौतिक क्षरण' नहीं है — सही कथन चुनिए:",
     "Rusting is not 'physical erosion' — choose the correct statement:",
     ["जंग लगना रासायनिक परिवर्तन है", "जंग लगना भौतिक परिवर्तन है", "जंग लगना कोई परिवर्तन नहीं", "जंग केवल रंग है"],
     ["Rusting is a chemical change", "Rusting is a physical change", "Rusting is no change", "Rust is only a colour"],
     0,
     "परीक्षा-जाल: जंग को भौतिक क्षरण समझना — यह रासायनिक है।",
     "Exam trap: thinking rust is physical erosion — it is chemical."),

    ("rusting-and-prevention", "easy",
     "लोहे की छत को रंग रोज़/साल में पोता जाता है — मुख्य कारण:",
     "The iron roof is painted regularly — the main reason:",
     ["जंग लगने से बचाव", "छत को ठंडा करना", "छत को हल्का करना", "धूल इकट्ठा करना"],
     ["Protection from rusting", "Cooling the roof", "Making the roof lighter", "Collecting dust"],
     0,
     "रंग की परत जंग की शर्तें पूरी नहीं होने देती।",
     "The paint layer does not let rust's conditions be met."),

    ("rusting-and-prevention", "easy",
     "जस्ते की परत लोहे के लिए क्या करती है?",
     "What does the zinc layer do for iron?",
     ["लोहे को जंग की दशा से बचाती है", "लोहे को पिघला देती है", "लोहे को नरम करती है", "लोहे का रंग बदलती है"],
     ["It shields the iron from the conditions of rust", "It melts the iron", "It softens the iron", "It changes the iron's colour"],
     0,
     "जस्ते की परत ढाल का काम करती है।",
     "The zinc layer works as a shield."),

    ("rusting-and-prevention", "easy",
     "जंग लगने में लोहा किसमें बदल जाता है?",
     "In rusting, what does the iron turn into?",
     ["ऑक्सीकरण से बने नए पदार्थ (जंग) में", "नई धातु में", "लकड़ी में", "काँच में"],
     ["Into a new substance formed by oxidation (rust)", "Into a new metal", "Into wood", "Into glass"],
     0,
     "जंग स्वयं नया पदार्थ है।",
     "Rust itself is the new substance."),

    ("rusting-and-prevention", "easy",
     "'जंग-जस्ता' की जोड़ी किस उपाय से जुड़ी है?",
     "The pair 'rust-zinc' is linked with which remedy?",
     ["गैल्वनाइज़िंग", "रंगना", "तेल लगाना", "मिश्र धातु"],
     ["Galvanising", "Painting", "Oiling", "Alloying"],
     0,
     "जंग रोकने के लिए जस्ता — यही जोड़ी याद रखनी है।",
     "Zinc against rust — that is the pair to remember."),

    ("rusting-and-prevention", "easy",
     "पूरी तरह सूखी हवा में रखे शुद्ध लोहे की चादर को जल उपलब्ध नहीं है। जंग लगेगा या नहीं?",
     "A pure iron sheet kept in completely dry air has no water available. Will it rust or not?",
     ["नहीं — जल की शर्त पूरी नहीं हुई", "हाँ — हवा है तो जंग लगेगा", "हाँ — जंग हवा से अपने आप लगता है", "जंग केवल धूप से लगता है"],
     ["No — the water condition is unfulfilled", "Yes — with air present it will rust", "Yes — rust occurs from air by itself", "Rust comes only from sunshine"],
     0,
     "दोनों शर्तें चाहिए; एक की कमी से जंग नहीं।",
     "Both conditions are needed; lacking one, no rust."),

    ("rusting-and-prevention", "easy",
     "ऑक्सीजन नहीं है, केवल जल में डूबा लोहा — जंग की स्थिति क्या होगी?",
     "Iron immersed in water with no oxygen present — what will be the situation for rust?",
     ["जंग नहीं लगेगा — ऑक्सीजन की शर्त पूरी नहीं", "जंग जल से ही लग जाएगा", "जंग दोगुना लगेगा", "लोहा घुल जाएगा"],
     ["No rust — the oxygen condition is unfulfilled", "Water alone will rust it", "Rust will be doubled", "The iron will dissolve"],
     0,
     "जल अकेला पर्याप्त नहीं — ऑक्सीजन भी जरूरी।",
     "Water alone is not enough — oxygen is essential too."),

    ("rusting-and-prevention", "easy",
     "जंग लगे लोहे की वस्तु के लिए कौन-सा कथन सही है?",
     "Which statement is correct for a rusted iron object?",
     ["उसमें नया पदार्थ (जंग) बन चुका है", "उसका लोहा और चमकदार हो गया", "उसमें केवल आकार बदला", "उसमें कोई परिवर्तन नहीं हुआ"],
     ["A new substance (rust) has formed in it", "Its iron has become shinier", "Only its shape changed", "No change occurred in it"],
     0,
     "जंग = नया पदार्थ = रासायनिक परिवर्तन।",
     "Rust = a new substance = a chemical change."),

    # ---- medium (21) ----
    ("rusting-and-prevention", "medium",
     "दो कथन: (i) जंग लगने में ऑक्सीजन और जल दोनों आवश्यक हैं। (ii) केवल ऑक्सीजन पर्याप्त है। सही विकल्प:",
     "Two statements: (i) Rusting requires both oxygen and water. (ii) Oxygen alone is sufficient. The correct option:",
     ["(i) सही, (ii) गलत", "दोनों सही", "दोनों गलत", "(i) गलत, (ii) सही"],
     ["(i) correct, (ii) wrong", "Both correct", "Both wrong", "(i) wrong, (ii) correct"],
     0,
     "एक भी शर्त छूटे तो जंग नहीं।",
     "If even one condition drops, no rust."),

    ("rusting-and-prevention", "medium",
     "प्रेक्षण: दरवाजे के नंगे कब्ज़ों पर जंग दिखा, पर रंग वाले पट पर नहीं। निष्कर्ष क्या है?",
     "Observation: rust appeared on the bare hinges of a door, but not on the painted panel. What is the conclusion?",
     ["रंग की परत ने लोहे को ऑक्सीजन-जल के संपर्क से बचाए रखा", "कब्ज़े सस्ते थे", "रंग वाला लोहा नहीं था", "जंग रंग को पसंद नहीं आती"],
     ["The paint layer kept the iron cut off from contact with oxygen and water", "The hinges were cheap", "The painted part was not iron", "Rust does not like paint"],
     0,
     "ढका लोहा जंग से बचा — रोकथाम का सिद्धांत दिखा।",
     "The covered iron stayed safe — the principle of prevention showed up."),

    ("rusting-and-prevention", "medium",
     "गैल्वनाइज़िंग की परत जंग से कैसे बचाती है? तर्क चुनिए:",
     "How does a galvanised layer protect from rust? Choose the logic:",
     ["जस्ते की परत लोहे और ऑक्सीजन-जल के बीच घेरा बना देती है", "जस्ता लोहे को खा जाता है", "जस्ता जंग को रंग देता है", "जस्ता लोहे को पिघलाता है"],
     ["The zinc layer forms a ring between the iron and oxygen-water", "Zinc eats up the iron", "Zinc colours the rust", "Zinc melts the iron"],
     0,
     "ढाल का काम — संपर्क अलग।",
     "The work of a shield — contact severed."),

    ("rusting-and-prevention", "medium",
     "परिदृश्य: बारिश में भीगी साइकिल की नंगी धातु की भागों को जंग लग गया, पर तेल चढ़ी चेन बची रही। कारण-चुनाव:",
     "Scenario: the bare metal parts of a rain-soaked bicycle rusted, but the oiled chain survived. Choose the reason:",
     ["तेल की परत ने चेन पर जल-ऑक्सीजन का संपर्क नहीं होने दिया", "चेन प्लास्टिक की थी", "चेन में लोहा नहीं था", "तेल ने चेन को सुखा दिया"],
     ["The oil film did not let water-oxygen contact the chain", "The chain was plastic", "The chain had no iron", "The oil dried the chain"],
     0,
     "तेल = संपर्क-अवरोध = जंग-रोकथाम।",
     "Oil = contact barrier = rust prevention."),

    ("rusting-and-prevention", "medium",
     "तीन कथन: (i) जंग लगना रासायनिक परिवर्तन है। (ii) जंग लगना ऑक्सीकरण है। (iii) जंग लगना भौतिक क्षरण है। गलत कथन:",
     "Three statements: (i) Rusting is a chemical change. (ii) Rusting is oxidation. (iii) Rusting is physical erosion. The wrong statement:",
     ["कथन (iii)", "कथन (i)", "कथन (ii)", "तीनों सही"],
     ["Statement (iii)", "Statement (i)", "Statement (ii)", "All three correct"],
     0,
     "भौतिक क्षरण वाली उंगली यहीं उठाना गलत है।",
     "Pointing at physical erosion is exactly the wrong move here."),

    ("rusting-and-prevention", "medium",
     "जंग-रोकथाम के चार उपायों का सही समूह कौन-सा है?",
     "Which is the correct group of the four methods of rust prevention?",
     ["रंगना, गैल्वनाइज़िंग, तेल लगाना, मिश्र धातु बनाना", "रंगना, धोना, सुखाना, तोड़ना", "गैल्वनाइज़िंग, पिघलाना, भंगन, घुलना", "तेल, नमक, चीनी, अम्ल"],
     ["Painting, galvanising, oiling, alloying", "Painting, washing, drying, breaking", "Galvanising, melting, breaking, dissolving", "Oil, salt, sugar, acid"],
     0,
     "यही चार अध्याय की रोकथाम-सूची हैं।",
     "These four are the chapter's prevention list."),

    ("rusting-and-prevention", "medium",
     "कारण-श्रृंखला पूरी कीजिए: गीला लोहा + हवा की ऑक्सीजन → ______ → जंग",
     "Complete the cause-chain: wet iron + oxygen of the air → ______ → rust",
     ["लोहे का ऑक्सीकरण", "लोहे का पिघलना", "लोहे का कतरना", "लोहे का रंगना"],
     ["Oxidation of the iron", "Melting of the iron", "Cutting of the iron", "Painting of the iron"],
     0,
     "ऑक्सीकरण की कड़ी हटे तो श्रृंखला अधूरी।",
     "Remove the oxidation link and the chain breaks."),

    ("rusting-and-prevention", "medium",
     "खेत से लौटके किसान ने फावड़ा धोकर मिट्टी साफ किया और सूखे कपड़े से पोंछकर तेल लगा दिया। वह वास्तव में क्या तोड़ रहा है?",
     "Returning from the field, a farmer washed his spade clean, wiped it with a dry cloth and applied oil. What is he actually breaking?",
     ["जल और ऑक्सीजन के लोहे तक पहुँचने का संपर्क", "फावड़े का आकार", "लोहे की मिश्र धातु", "मिट्टी का रंग"],
     ["The contact of water and oxygen reaching the iron", "The spade's shape", "The iron's alloy", "The soil's colour"],
     0,
     "पोंछना जल हटाता है, तेल बाकी संपर्क बंद करता है।",
     "Wiping removes water; oil shuts the remaining contact."),

    ("rusting-and-prevention", "medium",
     "रंगना और गैल्वनाइज़िंग — दोनों का साझा उद्देश्य एक है। वह उद्देश्य और दोनों में भिन्नता चुनिए:",
     "Painting and galvanising — both share one purpose. Choose that purpose and the difference between them:",
     ["उद्देश्य: जंग-रोकथाम; भिन्नता: एक में रंग की परत, दूसरे में जस्ते की", "उद्देश्य: सजावट; भिन्नता: रंग", "उद्देश्य: पिघलना; भिन्नता: ताप", "उद्देश्य: वजन बढ़ाना; भिन्नता: धातु"],
     ["Purpose: rust prevention; difference: a paint layer in one, a zinc layer in the other", "Purpose: decoration; difference: colour", "Purpose: melting; difference: temperature", "Purpose: adding weight; difference: metal"],
     0,
     "रास्ता अलग, मंज़िल एक — जंग रोकना।",
     "Different routes, one destination — stopping rust."),

    ("rusting-and-prevention", "medium",
     "वर्षा ऋतु में लोहे की खिड़कियों पर जंग के धब्बे दिखने लगे। इस मौसम में जंग की कौन-सी शर्त जुड़ गई थी?",
     "In the rainy season rust spots began appearing on iron windows. Which condition of rust got added in this season?",
     ["जल की उपस्थिति — ऑक्सीजन तो हवा में पहले से थी", "ऑक्सीजन पहली बार आई", "प्रकाश कम हुआ", "लोहा बढ़ गया"],
     ["The presence of water — oxygen was already in the air", "Oxygen arrived for the first time", "Light decreased", "The iron increased"],
     0,
     "बारिश ने जल-शर्त पूरी की; दूसरी शर्त हमेशा से थी।",
     "The rain fulfilled the water condition; the other was always there."),

    ("rusting-and-prevention", "medium",
     "लोहे के एक टुकड़े को गर्म करके तेल में डुबोया गया (तेल-तड़का विधि) — यह पुराना घरेलू उपाय किस सिद्धांत पर है?",
     "A piece of iron was heated and dipped in oil (the oil-tempering way) — on which principle is this old household remedy based?",
     ["तेल की परत जल-ऑक्सीजन का संपर्क काट देती है", "तेल लोहे को नरम करता है", "तेल जंग को रंगता है", "गर्मी जंग को जला देती है"],
     ["The oil film cuts off contact with water-oxygen", "Oil softens the iron", "Oil colours the rust", "Heat burns the rust away"],
     0,
     "लोहे की तेल-परत = संपर्क-रोध।",
     "An oil film on iron = a contact barrier."),

    ("rusting-and-prevention", "medium",
     "दो कथन: (i) गैल्वनाइज़िंग में जस्ते की परत चढ़ती है। (ii) जंग लगना लोहे का ऑक्सीकरण है। सही विकल्प:",
     "Two statements: (i) In galvanising a layer of zinc is applied. (ii) Rusting is the oxidation of iron. The correct option:",
     ["दोनों सही", "दोनों गलत", "केवल (i) सही", "केवल (ii) सही"],
     ["Both correct", "Both wrong", "Only (i) correct", "Only (ii) correct"],
     0,
     "एक उपाय-तथ्य, एक परिवर्तन-तथ्य — दोनों अध्याय के हैं।",
     "One remedy-fact, one change-fact — both belong to the chapter."),

    ("rusting-and-prevention", "medium",
     "मिश्र धातु बनाना अन्य उपायों (रंग/तेल/जस्ता) से किस मायने में भिन्न है?",
     "In what sense is alloying different from the other methods (paint/oil/zinc)?",
     ["अन्य बाहरी परत चढ़ाते हैं; मिश्र धातु में धातु में ही दूसरी धातु मिलाई जाती है", "मिश्र धातु में कुछ नहीं किया जाता", "मिश्र धातु जंग बढ़ाती है", "कोई भिन्नता नहीं"],
     ["The others apply an outer layer; in alloying another metal is mixed into the metal itself", "Nothing is done in alloying", "An alloy increases rust", "There is no difference"],
     0,
     "परत बाहरी बनाम मिलावट भीतरी — यही भेद है।",
     "An outer coat versus an inner mix — that is the difference."),

    ("rusting-and-prevention", "medium",
     "नमी भरे इलाके की लोहे की रेलिंग पर जंग लग गई। नमी की भूमिका क्या है?",
     "The iron railing of a damp area got rusted. What role did the dampness play?",
     ["नमी जल उपलब्ध कराती है — जंग की एक शर्त", "नमी ऑक्सीजन है", "नमी रंग है", "नमी से लोहा पिघलता है"],
     ["Dampness supplies water — one condition of rust", "Dampness is oxygen", "Dampness is a colour", "Dampness melts iron"],
     0,
     "नमी = जल की उपस्थिति।",
     "Dampness = the presence of water."),

    ("rusting-and-prevention", "medium",
     "जंग लगी कील से जंग हटा लिया गया, फिर भी वह पहले जैसी नई कील नहीं रही। यह किस बात का प्रमाण है?",
     "Rust was removed from a rusted nail, yet it did not remain like a new nail. What is this proof of?",
     ["जंग लगना रासायनिक परिवर्तन था — प्रायः अनुक्रमणीय", "जंग लगना भौतिक परिवर्तन था", "जंग केवल रंग था", "कील बदली नहीं थी"],
     ["Rusting was a chemical change — usually irreversible", "Rusting was a physical change", "Rust was only a colour", "The nail had not changed"],
     0,
     "जंग उतरने से पदार्थ की वापसी नहीं होती।",
     "Scraping off rust does not bring the substance back."),

    ("rusting-and-prevention", "medium",
     "पेंट उतर गए लोहे के दरवाजे के उसी स्थान पर जंग दिखने लगी। क्रम-तर्क चुनिए:",
     "Rust began to appear at the very spot of an iron door where the paint had peeled. Choose the chain of reasoning:",
     ["परत गई → लोहा खुला → ऑक्सीजन-जल का संपर्क → जंग", "परत गई → लोहा पिघला → जंग", "रंग ने जंग बनाई", "दरवाजा बूढ़ा हो गया"],
     ["Layer gone → iron exposed → contact with oxygen-water → rust", "Layer gone → iron melted → rust", "The paint made the rust", "The door grew old"],
     0,
     "जहाँ ढाल गई, वहीं जंग आई।",
     "Where the shield went, rust came."),

    ("rusting-and-prevention", "medium",
     "कक्षा-प्रयोग: तीन लोहे की कीलें — (क) सूखी हवा में (ख) उबला-ठंडा किया गया जल जिसमें ऑक्सीजन नहीं (ग) खुला जल। जंग किसमें लगेगी?",
     "Class experiment: three iron nails — (a) in dry air (b) in boiled-and-cooled water with no oxygen (c) in open water. In which will rust form?",
     ["केवल (ग) में — जल और ऑक्सीजन दोनों वहीं हैं", "तीनों में", "केवल (क) में", "केवल (ख) में"],
     ["Only in (c) — water and oxygen are both there", "In all three", "Only in (a)", "Only in (b)"],
     0,
     "(क) में जल नहीं, (ख) में ऑक्सीजन नहीं — केवल (ग) पूर्ण।",
     "(a) lacks water, (b) lacks oxygen — only (c) is complete."),

    ("rusting-and-prevention", "medium",
     "जंग लगना और मोम पिघलना — दोनों लोहे/मोम पर 'होते' हैं, पर वर्ग भिन्न है। भिन्नता का एक-शब्द आधार:",
     "Rusting and wax melting — both 'happen' to iron/wax, yet the classes differ. The one-word basis of the difference:",
     ["नया पदार्थ", "आकार", "रंग", "ताप"],
     ["A new substance", "Shape", "Colour", "Temperature"],
     0,
     "जंग में नया पदार्थ बना; पिघले मोम में नहीं।",
     "In rust a new substance formed; in melted wax, none."),

    ("rusting-and-prevention", "medium",
     "गैल्वनाइज़िड बाल्टी और साधारण रंगी बाल्टी — दोनों जंग से बचती हैं। गैल्वनाइज़िड वाली की पहचान क्या है?",
     "A galvanised bucket and an ordinarily painted bucket — both stay safe from rust. What is the identification of the galvanised one?",
     ["उस पर जस्ते की परत चढ़ी होती है", "उस पर सोने की परत होती है", "वह मिश्र धातु नहीं होती", "वह लोहे की नहीं होती"],
     ["It carries a coating of zinc", "It carries a coating of gold", "It is not an alloy", "It is not made of iron"],
     0,
     "जस्ते की परत ही गैल्वनाइज़िड की पहचान है।",
     "A zinc coating is the very identity of galvanised."),

    ("rusting-and-prevention", "medium",
     "तेल-ग्रीस लगे बेयरिंग वाले पुर्ज़ों को जंग कम लगता है। निष्कर्ष और कारण चुनिए:",
     "Parts with oil-grease applied get less rust. Choose the conclusion and reason:",
     ["जंग की शर्तों का संपर्क टूटा रहता है — रोकथाम सिद्ध", "जंग तेल से डरती है", "तेल लोहा बनाता है", "पुर्ज़े नहीं बदलते"],
     ["The contact of rust's conditions stays broken — prevention proven", "Rust fears oil", "Oil makes iron", "The parts do not change"],
     0,
     "ग्रीस भी वही ढाल-सिद्धांत है।",
     "Grease follows the same shield principle."),

    # ---- hard (9) ----
    ("rusting-and-prevention", "hard",
     "तीन कथन: (i) जंग के लिए ऑक्सीजन और जल दोनों आवश्यक हैं। (ii) सभी रोकथाम उपाय लोहे की सतह को इन दोनों से अलग रखते हैं। (iii) जंग लगना उत्क्रमणीय परिवर्तन है। सही समूह:",
     "Three statements: (i) Both oxygen and water are necessary for rust. (ii) All prevention methods keep the iron's surface cut off from these two. (iii) Rusting is a reversible change. The correct set:",
     ["(i) और (ii) सही, (iii) गलत — जंग लगना रासायनिक और प्रायः अनुक्रमणीय है", "तीनों सही", "केवल (iii) सही", "केवल (i) सही"],
     ["(i) and (ii) correct, (iii) wrong — rusting is chemical and usually irreversible", "All three correct", "Only (iii) correct", "Only (i) correct"],
     0,
     "रोकथाम का पूरा खेल संपर्क-तोड़ने का है।",
     "The whole game of prevention is breaking contact."),

    ("rusting-and-prevention", "hard",
     "सोच-परीक्षण: ऐसी काल्पनिक दुनिया जहाँ वायुमंडल में ऑक्सीजन नहीं है — वहाँ खुले भीगे लोहे की क्या दशा होगी?",
     "Thought experiment: in an imaginary world whose atmosphere has no oxygen — what will be the condition of openly wet iron there?",
     ["जंग नहीं लगेगी — एक आवश्यक शर्त ही नहीं है", "जंग दोगुनी लगेगी", "जंग जल से लग जाएगी", "लोहा उड़ जाएगा"],
     ["No rust — one necessary condition itself is absent", "Double rust", "Water alone will rust it", "The iron will fly away"],
     0,
     "शर्त हटी तो परिणाम हटा।",
     "Remove the condition, and the result goes too."),

    ("rusting-and-prevention", "hard",
     "जंग की शर्त/प्रकृति/रोकथाम की सही पंक्ति चुनिए:",
     "Choose the correct row for rust's condition/nature/prevention:",
     ["शर्त: ऑक्सीजन + जल; प्रकृति: रासायनिक (ऑक्सीकरण); रोकथाम: परत/मिश्रण से संपर्क-विच्छेद", "शर्त: केवल जल; प्रकृति: भौतिक; रोकथाम: पानी डालना", "शर्त: केवल ऑक्सीजन; प्रकृति: भौतिक; रोकथाम: गर्म करना", "शर्त: प्रकाश; प्रकृति: कोई नहीं; रोकथाम: अंधेरा"],
     ["Condition: oxygen + water; nature: chemical (oxidation); prevention: cutting contact by coating/mixing", "Condition: only water; nature: physical; prevention: adding water", "Condition: only oxygen; nature: physical; prevention: heating", "Condition: light; nature: none; prevention: darkness"],
     0,
     "एक पंक्ति में पूरा जंग-अध्याय।",
     "The whole rust story in one row."),

    ("rusting-and-prevention", "hard",
     "चार स्थितियाँ: (क) सूखी हवा में लोहा (ख) ऑक्सीजन-रहित जल में लोहा (ग) खुली गीली हवा में लोहा (घ) तेल में डूबा लोहा। जंग किसमें लगेगी?",
     "Four situations: (a) iron in dry air (b) iron in oxygen-free water (c) iron in open moist air (d) iron immersed in oil. In which will rust form?",
     ["केवल (ग) में", "(क) और (ग) में", "(ख) और (घ) में", "चारों में"],
     ["Only in (c)", "In (a) and (c)", "In (b) and (d)", "In all four"],
     0,
     "केवल (ग) में दोनों शर्तें और संपर्क साथ हैं।",
     "Only in (c) are both conditions and contact present together."),

    ("rusting-and-prevention", "hard",
     "भ्रांति: 'जंग लगना केवल दिखने की समस्या है — रंग थोड़ा उड़ गया।' भ्रांति का खंडन किस तथ्य से होता है?",
     "Misconception: 'Rusting is only a problem of appearance — just a bit of colour flying off.' Which fact refutes the misconception?",
     ["जंग लगने में लोहे का पदार्थ ही ऑक्सीकरण से नए पदार्थ में बदल जाता है — यह रासायनिक परिवर्तन है", "जंग सुंदर नहीं लगती", "जंग दाग नहीं है", "भ्रांति सही है"],
     ["In rusting the iron's substance itself changes by oxidation into a new substance — it is a chemical change", "Rust does not look nice", "Rust is not a stain", "The misconception is correct"],
     0,
     "जंग सतह का मेकअप नहीं, पदार्थ का बदलाव है।",
     "Rust is not surface makeup; it is a change of substance."),

    ("rusting-and-prevention", "hard",
     "रंग, तेल और जस्ता — तीनों परतों का साझा सिद्धांत एक है और मिश्र धातु इससे भिन्न है। साझा सिद्धांत और भिन्नता चुनिए:",
     "Paint, oil and zinc — all three layers share one principle, and alloying differs from it. Choose the shared principle and the difference:",
     ["साझा: सतह पर परत कर ऑक्सीजन-जल संपर्क तोड़ना; भिन्नता: मिश्र धातु में परत नहीं, धातु में दूसरी धातु की मिलावट", "साझा: लोहे को गर्म करना; भिन्नता: ठंडा करना", "साझा: जंग को रंगना; भिन्नता: धोना", "साझा: कुछ नहीं; भिन्नता: कुछ नहीं"],
     ["Shared: breaking oxygen-water contact by a surface layer; difference: alloying uses no layer but a mix of another metal into the metal", "Shared: heating the iron; difference: cooling", "Shared: painting the rust; difference: washing", "Shared: nothing; difference: nothing"],
     0,
     "तीन ढालें बाहरी, एक ढाल भीतरी।",
     "Three shields outside, one shield inside."),

    ("rusting-and-prevention", "hard",
     "निष्कर्ष-तर्क: जंग-रोकथाम के चारों उपायों (रंगना, गैल्वनाइज़िंग, तेल, मिश्र धातु) में साझी कड़ी क्या है?",
     "Concluding logic: what is the common link among all four methods of rust prevention (painting, galvanising, oiling, alloying)?",
     ["सभी लोहे को जंग की आवश्यक दशाओं से बचाने का ही काम करते हैं", "सभी लोहे को पिघलाते हैं", "सभी जंग को रंगते हैं", "सभी लोहे का वजन बढ़ाते हैं"],
     ["All of them merely work to save the iron from the conditions necessary for rust", "All of them melt the iron", "All of them colour the rust", "All of them add weight to the iron"],
     0,
     "मकसद एक — दशाएँ पूरी न होने देना।",
     "One aim — not letting the conditions be fulfilled."),

    ("rusting-and-prevention", "hard",
     "'जंग लगना ऑक्सीकरण है' — इस कथन से निकलने वाला सही निष्कर्ष चुनिए:",
     "'Rusting is oxidation' — choose the correct conclusion drawn from this statement:",
     ["जंग बनने में ऑक्सीजन की भागीदारी अनिवार्य है और बना पदार्थ मूल लोहे से भिन्न है", "जंग में ऑक्सीजन निकलती है", "जंग में जल नहीं चाहिए", "जंग लोहे का रंग है"],
     ["Oxygen's participation is essential in rust forming, and the product differs from the original iron", "Oxygen escapes in rusting", "Rusting needs no water", "Rust is iron's colour"],
     0,
     "ऑक्सीकरण-शब्द ऑक्सीजन की भूमिका बता देता है।",
     "The word oxidation itself reveals oxygen's role."),

    ("rusting-and-prevention", "hard",
     "जंग-प्रबंधन का परीक्षा-ढाँचा: सही मिलान कौन-सा है?",
     "The exam frame of rust management: which is the correct matching?",
     ["शर्तें — ऑक्सीजन व जल; वर्ग — रासायनिक; उपाय — रंगना, जस्तीकरण, तेल, मिश्र धातु", "शर्तें — केवल जल; वर्ग — भौतिक; उपाय — धोना", "शर्तें — केवल ऑक्सीजन; वर्ग — भौतिक; उपाय — सुखाना", "शर्तें — प्रकाश; वर्ग — कोई नहीं; उपाय — रंगना"],
     ["Conditions — oxygen and water; class — chemical; methods — painting, galvanising, oiling, alloying", "Conditions — only water; class — physical; methods — washing", "Conditions — only oxygen; class — physical; methods — drying", "Conditions — light; class — none; methods — painting"],
     0,
     "ढाँचा याद = पूरा अंक।",
     "Remember the frame = full marks."),

    # ================= CHEMICAL CHANGES IN DAILY LIFE (50) =================
    # ---- easy (20) ----
    ("chemical-changes-in-daily-life", "easy",
     "पाचन किस प्रकार का परिवर्तन है?",
     "Digestion is which type of change?",
     ["रासायनिक", "भौतिक", "कोई परिवर्तन नहीं", "केवल आकार-परिवर्तन"],
     ["Chemical", "Physical", "No change", "Only a shape change"],
     0,
     "भोजन पाचन में नए पदार्थों में बदलता है।",
     "Food changes into new substances in digestion."),

    ("chemical-changes-in-daily-life", "easy",
     "श्वसन (साँस लेना) कैसा परिवर्तन है?",
     "Respiration (breathing) is what kind of change?",
     ["रासायनिक परिवर्तन", "भौतिक परिवर्तन", "अवस्था-परिवर्तन", "आकृति-परिवर्तन"],
     ["A chemical change", "A physical change", "A change of state", "A change of form"],
     0,
     "श्वसन रासायनिक परिवर्तन है।",
     "Respiration is a chemical change."),

    ("chemical-changes-in-daily-life", "easy",
     "प्रकाश संश्लेषण किस वर्ग का परिवर्तन है?",
     "Photosynthesis is a change of which class?",
     ["रासायनिक", "भौतिक", "कोई परिवर्तन नहीं", "विद्युत"],
     ["Chemical", "Physical", "No change", "Electrical"],
     0,
     "प्रकाश संश्लेषण रासायनिक परिवर्तन है।",
     "Photosynthesis is a chemical change."),

    ("chemical-changes-in-daily-life", "easy",
     "दहन (जलना) कैसा परिवर्तन है?",
     "Combustion (burning) is what kind of change?",
     ["रासायनिक", "भौतिक", "उत्क्रमणीय भौतिक", "कोई नहीं"],
     ["Chemical", "Physical", "Reversible physical", "None"],
     0,
     "दहन में नए पदार्थ बनते हैं।",
     "New substances form in combustion."),

    ("chemical-changes-in-daily-life", "easy",
     "रोज़ सुबह दूध को दही में बदला जाता है — घर का यह रोज़ का बदलाव किस वर्ग का है?",
     "Every morning milk is turned into curd — this daily household transformation belongs to which class?",
     ["रासायनिक", "भौतिक", "अवस्था-परिवर्तन", "आकार-परिवर्तन"],
     ["Chemical", "Physical", "A change of state", "A change of shape"],
     0,
     "दही दूध से भिन्न गुणों वाला नया पदार्थ है।",
     "Curd is a new substance with properties different from milk."),

    ("chemical-changes-in-daily-life", "easy",
     "विद्युत लेपन किस प्रकार का परिवर्तन माना जाता है?",
     "Electroplating is considered which type of change?",
     ["रासायनिक", "भौतिक", "कोई परिवर्तन नहीं", "केवल रंग-परिवर्तन"],
     ["Chemical", "Physical", "No change", "Only a colour change"],
     0,
     "विद्युत लेपन रासायनिक परिवर्तनों की सूची में है।",
     "Electroplating is on the list of chemical changes."),

    ("chemical-changes-in-daily-life", "easy",
     "रसोई की इन क्रियाओं में से कौन-सी रासायनिक परिवर्तन नहीं है?",
     "Which of these kitchen acts is NOT a chemical change?",
     ["सब्ज़ी का काटना", "दही का जमना", "चूल्हे का जलना", "खाने का पचना"],
     ["Cutting vegetables", "Setting of curd", "Burning of the stove", "Digestion of food"],
     0,
     "काटने में केवल आकार बदला — भौतिक।",
     "Cutting changed only the shape — physical."),

    ("chemical-changes-in-daily-life", "easy",
     "सभी रासायनिक परिवर्तनों का सही समूह कौन-सा है?",
     "Which is the correct all-chemical group?",
     ["पाचन, श्वसन, प्रकाश संश्लेषण, दहन", "काटना, पिघलना, भंगन, घुलना", "पिघलना, दहन, कतरना, मोड़ना", "दही, जंग, मोड़ना, घुलना"],
     ["Digestion, respiration, photosynthesis, combustion", "Cutting, melting, breaking, dissolving", "Melting, burning, cutting, folding", "Curd, rust, folding, dissolving"],
     0,
     "पहला समूह ही पूर्णतः रासायनिक है।",
     "Only the first group is wholly chemical."),

    ("chemical-changes-in-daily-life", "easy",
     "दही जमने में दूध के साथ मूलतः क्या होता है?",
     "What fundamentally happens to milk when curd sets?",
     ["वह भिन्न गुणों वाले नए पदार्थ (दही) में बदल जाता है", "केवल उसका आकार बदलता है", "केवल उसकी अवस्था बदलती है", "उसका कुछ नहीं होता"],
     ["It changes into a new substance (curd) with different properties", "Only its shape changes", "Only its state changes", "Nothing happens to it"],
     0,
     "दूध → दही = नया पदार्थ।",
     "Milk → curd = a new substance."),

    ("chemical-changes-in-daily-life", "easy",
     "विद्युत लेपन के दौरान वस्तु की सतह पर क्या होता है?",
     "What happens to the surface of an object during electroplating?",
     ["उस पर धातु की परत जमती है", "वह कट जाती है", "वह पिघल जाती है", "उसका रंग उड़ जाता है"],
     ["A layer of metal deposits on it", "It gets cut", "It melts", "Its colour flies off"],
     0,
     "सतह पर धातु-परत का चढ़ना इस परिवर्तन की बाहरी पहचान है।",
     "A metal layer depositing on the surface is the outward identity of this change."),

    ("chemical-changes-in-daily-life", "easy",
     "पाचन क्रिया में भोजन का क्या होता है?",
     "What happens to food in digestion?",
     ["वह नए पदार्थों में बदल जाता है", "केवल उसके टुकड़े होते हैं", "केवल वह गर्म होता है", "कुछ नहीं होता"],
     ["It changes into new substances", "It only gets broken into pieces", "It only gets warm", "Nothing happens"],
     0,
     "पाचन = भोजन का नए पदार्थों में रूपांतरण।",
     "Digestion = the conversion of food into new substances."),

    ("chemical-changes-in-daily-life", "easy",
     "जलती मोमबत्ती का दहन किस वर्ग में आता है?",
     "The combustion of a burning candle falls in which class?",
     ["रासायनिक परिवर्तन", "भौतिक परिवर्तन", "उत्क्रमणीय परिवर्तन", "कोई परिवर्तन नहीं"],
     ["A chemical change", "A physical change", "A reversible change", "No change"],
     0,
     "जलना = दहन = रासायनिक।",
     "Burning = combustion = chemical."),

    ("chemical-changes-in-daily-life", "easy",
     "रासायनिक परिवर्तनों की ऊर्जा-विशेषता के अनुसार दैनिक जीवन के रासायनिक परिवर्तनों में ऊर्जा का क्या होता है?",
     "Per the energy feature of chemical changes, what happens to energy in the chemical changes of daily life?",
     ["उसका अवशोषण या उत्सर्जन होता है", "कुछ नहीं होता", "ऊर्जा सदैव बनी रहती है", "ऊर्जा सदैव नष्ट होती है"],
     ["It is absorbed or released", "Nothing happens", "Energy always remains", "Energy is always destroyed"],
     0,
     "ऊर्जा का लेन-देन रासायनिक परिवर्तन की सामान्य बात है।",
     "An exchange of energy is the normal affair of a chemical change."),

    ("chemical-changes-in-daily-life", "easy",
     "दहन का एक सामान्य उदाहरण चुनिए:",
     "Choose a common example of combustion:",
     ["लकड़ी का जलाना", "जल का पिघलना", "कागज़ का मोड़ना", "चीनी का घोलना"],
     ["Burning of wood", "Melting of ice", "Folding of paper", "Dissolving of sugar"],
     0,
     "जलाना = दहन का रोज़ का रूप।",
     "Burning = the everyday face of combustion."),

    ("chemical-changes-in-daily-life", "easy",
     "पाचन, कागज़-कतरना और दही जमना — इनमें रासायनिक परिवर्तनों की संख्या कितनी है?",
     "Digestion, paper-cutting and curd setting — how many chemical changes are among these?",
     ["दो — पाचन और दही जमना", "तीन", "एक — केवल कागज़ कतरना", "शून्य"],
     ["Two — digestion and curd setting", "Three", "One — only paper cutting", "Zero"],
     0,
     "कतरना भौतिक रहा; बाकी दोनों रासायनिक।",
     "Cutting stayed physical; the other two are chemical."),

    ("chemical-changes-in-daily-life", "easy",
     "दही एक बार जम गया, तो उसी से पहले जैसा दूध प्रायः —",
     "Once curd has set, from the same curd the earlier milk usually —",
     ["आसानी से वापस नहीं आता", "तुरंत आ जाता है", "रात में आ जाता है", "गर्म करते ही आ जाता है"],
     ["does not come back easily", "comes back at once", "comes back at night", "comes back on heating"],
     0,
     "रासायनिक परिवर्तन प्रायः अनुक्रमणीय — दही उदाहरण।",
     "A chemical change is usually irreversible — curd is the example."),

    ("chemical-changes-in-daily-life", "easy",
     "श्वसन और प्रकाश संश्लेषण दोनों का साझा वर्ग क्या है?",
     "What is the shared class of respiration and photosynthesis?",
     ["दोनों रासायनिक परिवर्तन हैं", "दोनों भौतिक परिवर्तन हैं", "एक रासायनिक, एक भौतिक", "दोनों अवस्था-परिवर्तन हैं"],
     ["Both are chemical changes", "Both are physical changes", "One chemical, one physical", "Both are changes of state"],
     0,
     "दोनों अध्याय की रासायनिक-सूची में साथ हैं।",
     "Both sit together on the chapter's chemical list."),

    ("chemical-changes-in-daily-life", "easy",
     "'दही जमना — रासायनिक; चीनी घोलना — भौतिक' — यह युग्म-मिलान सही है या गलत?",
     "'Curd setting — chemical; sugar dissolving — physical' — is this pair-matching right or wrong?",
     ["सही", "गलत — दोनों रासायनिक", "गलत — दोनों भौतिक", "गलत — दोनों उत्क्रमणीय"],
     ["Right", "Wrong — both chemical", "Wrong — both physical", "Wrong — both reversible"],
     0,
     "नया पदार्थ बना (दही), नहीं बना (घोल) — मिलान सही।",
     "A new substance formed (curd), did not (solution) — the matching is right."),

    ("chemical-changes-in-daily-life", "easy",
     "दैनिक जीवन में साँस लेते हुए हम कौन-सा परिवर्तन हर क्षण कर रहे होते हैं?",
     "While breathing in daily life, which change do we keep carrying out every moment?",
     ["रासायनिक परिवर्तन — श्वसन", "भौतिक परिवर्तन — केवल हवा का आना-जाना", "अवस्था-परिवर्तन", "आकृति-परिवर्तन"],
     ["A chemical change — respiration", "A physical change — merely air moving in and out", "A change of state", "A change of form"],
     0,
     "श्वसन सिर्फ हवा की आवाज-वाला काम नहीं — रासायनिक परिवर्तन है।",
     "Respiration is not merely an air-moving affair — it is a chemical change."),

    ("chemical-changes-in-daily-life", "easy",
     "जंग लगना, दही जमना, पाचन — तीनों की साझी कसौटी क्या है?",
     "Rusting, curd setting, digestion — what is the shared test of all three?",
     ["तीनों में नया पदार्थ बनता है", "तीनों में केवल आकार बदलता है", "तीनों में केवल रंग बदलता है", "तीनों में कुछ नहीं बदलता"],
     ["In all three a new substance forms", "In all three only shape changes", "In all three only colour changes", "In all three nothing changes"],
     0,
     "नया पदार्थ — तीनों की एक ही कसौटी।",
     "A new substance — the single test of all three."),

    # ---- medium (22) ----
    ("chemical-changes-in-daily-life", "medium",
     "दही का स्वाद दूध जैसा नहीं होता। इस प्रेक्षण से क्या निष्कर्ष निकलता है?",
     "Curd does not taste like milk. What conclusion follows from this observation?",
     ["दही दूध से भिन्न गुणों वाला नया पदार्थ है — परिवर्तन रासायनिक", "दही केवल जमा हुआ दूध है — भौतिक", "दूध खराब था", "स्वाद से कोई निष्कर्ष नहीं"],
     ["Curd is a new substance with properties different from milk — the change is chemical", "Curd is merely set milk — physical", "The milk was spoiled", "No conclusion comes from taste"],
     0,
     "गुण बदल गए = पदार्थ बदल गया।",
     "Properties changed = the substance changed."),

    ("chemical-changes-in-daily-life", "medium",
     "पाचन को रासायनिक कहने का मुख्य आधार क्या है?",
     "What is the main basis for calling digestion chemical?",
     ["भोजन भिन्न गुणों वाले पदार्थों में बदल जाता है", "भोजन केवल छोटे टुकड़ों में टूटता है", "भोजन केवल गर्म होता है", "भोजन का आकार बदलता है"],
     ["Food changes into substances with different properties", "Food merely breaks into smaller pieces", "Food merely gets warm", "Food's shape changes"],
     0,
     "आकार नहीं, पदार्थ का बदलना पाचन की पहचान है।",
     "Not shape but the change of substance is digestion's identity."),

    ("chemical-changes-in-daily-life", "medium",
     "रसोई की एक सुबह: सब्ज़ी काटी गई और चूल्हे पर लकड़ी जलाई गई। दोनों घटनाओं का वर्ग-क्रम चुनिए:",
     "A kitchen morning: vegetables were cut and wood was burnt on the stove. Choose the class order of the two events:",
     ["काटना — भौतिक; जलना — रासायनिक", "काटना — रासायनिक; जलना — भौतिक", "दोनों — भौतिक", "दोनों — रासायनिक"],
     ["Cutting — physical; burning — chemical", "Cutting — chemical; burning — physical", "Both — physical", "Both — chemical"],
     0,
     "एक ही रसोई में दोनों वर्ग दिख गए।",
     "One kitchen showed both classes."),

    ("chemical-changes-in-daily-life", "medium",
     "तीन कथन: (i) पाचन रासायनिक परिवर्तन है। (ii) प्रकाश संश्लेषण रासायनिक परिवर्तन है। (iii) जल का उबालना रासायनिक परिवर्तन है। सही समूह:",
     "Three statements: (i) Digestion is a chemical change. (ii) Photosynthesis is a chemical change. (iii) Boiling of water is a chemical change. The correct set:",
     ["(i) और (ii) सही, (iii) गलत — उबालना अवस्था-परिवर्तन है", "तीनों सही", "केवल (iii) सही", "केवल (i) सही"],
     ["(i) and (ii) correct, (iii) wrong — boiling is a change of state", "All three correct", "Only (iii) correct", "Only (i) correct"],
     0,
     "उबलते जल में जल ही रहता है — भौतिक।",
     "In boiling water the water remains — physical."),

    ("chemical-changes-in-daily-life", "medium",
     "विद्युत लेपन में वस्तु की सतह पर धातु की परत जमती है। इसे रासायनिक परिवर्तनों में क्यों गिना जाता है?",
     "In electroplating a layer of metal deposits on an object's surface. Why is it counted among chemical changes?",
     ["इसमें वस्तु की सतह पर नए पदार्थ (धातु-परत) का निर्माण होता है", "इसमें केवल आकार बदलता है", "इसमें केवल रंग उड़ता है", "इसमें कुछ नहीं होता"],
     ["A new substance (the metal layer) is built on the object's surface", "Only the shape changes", "Only the colour flies off", "Nothing happens"],
     0,
     "धातु-परत का बनना ही इसकी रासायनिक पहचान है।",
     "The forming of the metal layer is its chemical identity."),

    ("chemical-changes-in-daily-life", "medium",
     "भोजन की एक ही यात्रा में चबाना और पाचन — दोनों अलग वर्ग के हैं। भेद स्पष्ट कीजिए:",
     "In one and the same journey of food, chewing and digestion belong to different classes. Clarify the difference:",
     ["चबाना भौतिक है (आकार छोटा होता है); पाचन रासायनिक है (नए पदार्थ बनते हैं)", "दोनों रासायनिक हैं", "दोनों भौतिक हैं", "चबाना रासायनिक, पाचन भौतिक"],
     ["Chewing is physical (the size reduces); digestion is chemical (new substances form)", "Both are chemical", "Both are physical", "Chewing chemical, digestion physical"],
     0,
     "मुँह में आकार बदला; भीतर पदार्थ बदले।",
     "In the mouth the size changed; inside, the substance changed."),

    ("chemical-changes-in-daily-life", "medium",
     "दो कथन: (i) श्वसन रासायनिक परिवर्तन है। (ii) प्रकाश संश्लेषण भौतिक परिवर्तन है। सही विकल्प:",
     "Two statements: (i) Respiration is a chemical change. (ii) Photosynthesis is a physical change. The correct option:",
     ["(i) सही, (ii) गलत", "दोनों सही", "दोनों गलत", "(i) गलत, (ii) सही"],
     ["(i) correct, (ii) wrong", "Both correct", "Both wrong", "(i) wrong, (ii) correct"],
     0,
     "दोनों जीव-प्रक्रियाएँ रासायनिक सूची में हैं।",
     "Both life processes are on the chemical list."),

    ("chemical-changes-in-daily-life", "medium",
     "रात भर में दूध जमकर दही हो गया। परिवर्तन का वर्ग और इसका अर्थ चुनिए:",
     "Over the night the milk set into curd. Choose the class of the change and its meaning:",
     ["रासायनिक — दूध भिन्न गुणों वाले नए पदार्थ में बदल गया", "भौतिक — केवल दूध गाढ़ा हुआ", "भौतिक — केवल अवस्था बदली", "कोई परिवर्तन नहीं हुआ"],
     ["Chemical — the milk changed into a new substance with different properties", "Physical — the milk merely thickened", "Physical — only the state changed", "No change occurred"],
     0,
     "दही का जमना दूध का रूपांतरण है, सिकुड़न नहीं।",
     "Curd setting is a transformation of milk, not a shrinkage."),

    ("chemical-changes-in-daily-life", "medium",
     "जलते लकड़े के चूल्हे से धुआँ और गर्मी — दोनों प्रेक्षण किस वर्ग के पक्ष में गवाही देते हैं?",
     "Smoke and heat from a burning wood stove — both observations testify in favour of which class?",
     ["रासायनिक परिवर्तन (दहन) के पक्ष में — गैस और ताप संकेत", "भौतिक परिवर्तन के पक्ष में", "किसी परिवर्तन के विरुद्ध", "केवल आकार-परिवर्तन के पक्ष में"],
     ["In favour of a chemical change (combustion) — gas and temperature signs", "In favour of a physical change", "Against any change", "In favour of only a shape change"],
     0,
     "चूल्हे की गवाही भी संकेतों से देनी है।",
     "Even the stove's testimony is given through signs."),

    ("chemical-changes-in-daily-life", "medium",
     "दैनिक जीवन की छह क्रियाओं में से भौतिक परिवर्तन कौन-सा है — पाचन, श्वसन, दहन, दही जमना, विद्युत लेपन, चादर की तह?",
     "Among the six acts of daily life, which is the physical change — digestion, respiration, combustion, curd setting, electroplating, folding a sheet?",
     ["चादर की तह", "पाचन", "दही जमना", "विद्युत लेपन"],
     ["Folding a sheet", "Digestion", "Curd setting", "Electroplating"],
     0,
     "पाँच रासायनिक सूची में; तह मात्र आकृति-बदलाव।",
     "Five sit on the chemical list; the fold is a mere change of form."),

    ("chemical-changes-in-daily-life", "medium",
     "कारण-चुनाव: प्रकाश संश्लेषण को रासायनिक परिवर्तन कहने के पीछे क्या है?",
     "Choose the cause: what lies behind calling photosynthesis a chemical change?",
     ["इसमें नए पदार्थों का निर्माण होता है", "इसमें केवल पत्तियाँ हिलती हैं", "इसमें केवल प्रकाश गर्म करता है", "इसमें कुछ नहीं बनता"],
     ["New substances are formed in it", "Only the leaves shake in it", "Only light warms in it", "Nothing forms in it"],
     0,
     "निर्माण-क्रिया ही रासायनिक कहलाने का आधार है।",
     "The act of formation is the basis of being called chemical."),

    ("rusting-and-prevention", "medium",
     "परिदृश्य: गीले लोहे की कढ़ाई रात भर बाहर रह गई; सुबह उस पर भूरे धब्बे आ गए। धब्बों की पहचान और वर्ग चुनिए:",
     "Scenario: a wet iron pan stayed out all night; by morning brown spots appeared on it. Choose the identification of the spots and the class:",
     ["जंग — रासायनिक परिवर्तन", "रंग के छींटे — भौतिक", "मिट्टी — कोई परिवर्तन नहीं", "पानी की बूँदें — अवस्था-परिवर्तन"],
     ["Rust — a chemical change", "Specks of paint — physical", "Soil — no change", "Drops of water — a change of state"],
     0,
     "गीला लोहा + हवा की ऑक्सीजन = जंग।",
     "Wet iron + the air's oxygen = rust."),

    ("chemical-changes-in-daily-life", "medium",
     "दैनिक जीवन की क्रियाओं की तालिका में सही वर्गीकृत पंक्ति चुनिए:",
     "From the acts of daily life, choose the correctly classified row:",
     ["पाचन — रासायनिक; चादर तह — भौतिक; दही — रासायनिक", "पाचन — भौतिक; चादर तह — रासायनिक; दही — भौतिक", "तीनों — रासायनिक", "तीनों — भौतिक"],
     ["Digestion — chemical; folding a sheet — physical; curd — chemical", "Digestion — physical; folding — chemical; curd — physical", "All three — chemical", "All three — physical"],
     0,
     "एक-एक करके कसौटी लगाइए।",
     "Apply the test one by one."),

    ("chemical-changes-in-daily-life", "medium",
     "श्वसन को 'केवल हवा का अंदर-बाहर आना' (भौतिक क्रिया) कहना क्यों अधूरा है?",
     "Why is calling respiration 'merely air moving in and out' (a physical act) incomplete?",
     ["श्वसन में भीतर नए पदार्थ बनते हैं — यह रासायनिक परिवर्तन है", "हवा कभी अंदर-बाहर नहीं आती", "श्वसन में कुछ नहीं होता", "हवा का आना रासायनिक है"],
     ["In respiration new substances form inside — it is a chemical change", "Air never moves in and out", "Nothing happens in respiration", "The coming of air is chemical"],
     0,
     "साँस की बाहरी घटना भीतर रासायनिक क्रिया का आवरण है।",
     "The outward affair of breath is the covering of an inner chemical action."),

    ("chemical-changes-in-daily-life", "medium",
     "भ्रांति-निर्णय: 'दही से दूध आसानी से वापस आ जाता है — यह उत्क्रमणीय परिवर्तन है।'",
     "Misconception judgement: 'Milk returns easily from curd — this is a reversible change.'",
     ["गलत — दही जमना रासायनिक परिवर्तन है और प्रायः अनुक्रमणीय", "सही — यह भौतिक परिवर्तन है", "सही — गर्म करते ही दूध आता है", "निर्णय संभव नहीं"],
     ["Wrong — curd setting is a chemical change and usually irreversible", "Correct — it is a physical change", "Correct — milk comes on heating", "No judgement possible"],
     0,
     "घर का अनुभव ही गवाह है — वापसी नहीं होती।",
     "The household experience itself is the witness — no return occurs."),

    ("chemical-changes-in-daily-life", "medium",
     "दहन और श्वसन — दोनों को एक ही वर्ग (रासायनिक) में रखने का आधार क्या है?",
     "On what basis are combustion and respiration placed in the same (chemical) class?",
     ["दोनों में नए पदार्थों का निर्माण होता है", "दोनों में केवल आकार बदलता है", "दोनों में केवल रंग बदलता है", "दोनों में कुछ नहीं बदलता"],
     ["In both, new substances are formed", "In both only shape changes", "In both only colour changes", "In both nothing changes"],
     0,
     "वर्ग की ईंट निर्माण-क्रिया से बनती है।",
     "The class's brick is the act of formation."),

    ("chemical-changes-in-daily-life", "medium",
     "किसी गाँव की सुबह: चूल्हा जला, दूध दही के लिए रखा, औजारों पर तेल लगाया। इनमें से रासायनिक परिवर्तनों की संख्या कितनी?",
     "A village morning: the stove was lit, milk was set for curd, oil was applied to tools. How many chemical changes are among these?",
     ["दो — चूल्हा जलना और दूध का दही बनना", "तीन", "एक — केवल चूल्हा", "शून्य"],
     ["Two — the stove burning and the milk turning to curd", "Three", "One — only the stove", "Zero"],
     0,
     "तेल लगाना जंग की रोकथाम है, स्वयं रासायनिक परिवर्तन नहीं।",
     "Applying oil is rust prevention, not itself a chemical change."),

    ("chemical-changes-in-daily-life", "medium",
     "प्रेक्षण-अनुमान: गर्म दूध को रखा था; कुछ घंटों में उसका स्वाद और बनावट दोनों बदल गए और वह वापस नहीं लौटा। यह किसका चित्र है?",
     "Observation-inference: hot milk was kept aside; within hours both its taste and texture changed and it did not return. This is the picture of what?",
     ["रासायनिक परिवर्तन का — नया पदार्थ बन गया", "भौतिक परिवर्तन का", "अवस्था-परिवर्तन का", "किसी परिवर्तन का नहीं"],
     ["Of a chemical change — a new substance formed", "Of a physical change", "Of a change of state", "Of no change"],
     0,
     "स्वाद-बनावट का बदलना गुण-बदलाव का संकेत है।",
     "A change of taste and texture signals a change of properties."),

    ("chemical-changes-in-daily-life", "medium",
     "छह क्रियाओं — पाचन, श्वसन, प्रकाश संश्लेषण, दहन, दही जमना, विद्युत लेपन — के बारे में सही कथन चुनिए:",
     "About the six acts — digestion, respiration, photosynthesis, combustion, curd setting, electroplating — choose the correct statement:",
     ["ये सभी रासायनिक परिवर्तन हैं", "इनमें से केवल दो रासायनिक हैं", "ये सभी भौतिक परिवर्तन हैं", "इनमें से कोई परिवर्तन नहीं है"],
     ["All of these are chemical changes", "Only two of them are chemical", "All of these are physical changes", "None of these is a change"],
     0,
     "अध्याय की दैनिक-जीवन सूची पूरी की पूरी रासायनिक है।",
     "The chapter's daily-life list is chemical through and through."),

    ("chemical-changes-in-daily-life", "medium",
     "उलटा-वर्गीकरण: निम्न में से कौन-सी क्रिया शेष तीन से भिन्न वर्ग की है — दही जमना, लकड़ी जलाना, चीनी घोलना, जंग लगना?",
     "Reverse classification: which of these acts belongs to a class different from the remaining three — curd setting, wood burning, sugar dissolving, rusting?",
     ["चीनी घोलना — भौतिक (शेष रासायनिक)", "दही जमना", "लकड़ी जलाना", "जंग लगना"],
     ["Sugar dissolving — physical (the rest chemical)", "Curd setting", "Wood burning", "Rusting"],
     0,
     "तीन में नया पदार्थ बना; घोल में नहीं।",
     "In three a new substance formed; in the solution, none."),

    ("chemical-changes-in-daily-life", "medium",
     "दो कथन: (i) दहन रासायनिक परिवर्तन है। (ii) दहन के बाद जलाई वस्तु प्रायः पूर्ववत् नहीं होती। सही विकल्प:",
     "Two statements: (i) Combustion is a chemical change. (ii) After combustion the burnt object usually does not return to its earlier form. The correct option:",
     ["दोनों सही", "दोनों गलत", "केवल (i) सही", "केवल (ii) सही"],
     ["Both correct", "Both wrong", "Only (i) correct", "Only (ii) correct"],
     0,
     "रासायनिक होना और प्रायः अनुक्रमणीय होना साथ चलते हैं।",
     "Being chemical and being usually irreversible go together."),

    ("chemical-changes-in-daily-life", "medium",
     "विद्युत लेपन और चादर की तह — दोनों में वस्तु की 'सतह/आकृति' बदलती दिखती है। फिर भी वर्ग भिन्न है — एक-पंक्ति कारण:",
     "Electroplating and folding a sheet — in both the object's 'surface/shape' appears to change. Yet the classes differ — a one-line reason:",
     ["लेपन में नया पदार्थ (धातु-परत) जुड़ता है; तह में केवल आकृति बदलती है", "दोनों में नया पदार्थ बनता है", "दोनों में केवल आकृति बदलती है", "दोनों में रंग बदलता है"],
     ["In plating a new substance (the metal layer) is added; in folding only the form changes", "A new substance forms in both", "Only the form changes in both", "The colour changes in both"],
     0,
     "दिखने में समान, कसौटी पर भिन्न।",
     "Alike in appearance, different on the test."),

    
    ("chemical-changes-in-daily-life", "medium",
     "आँगन में दो घटनाएँ एक साथ चलीं — कपड़े सुखाने की रस्सी पर तौलिया सूखा और कोने में गीले लोहे की टोकरी पर जंग चढ़ी। कपड़े-तौलिये की घटना का वर्ग जंग से भिन्न क्यों है?",
     "Two events ran together in the courtyard — the towel dried on the clothesline and rust climbed the wet iron basket in the corner. Why is the towel event's class different from rust's?",
     ["तौलिये में केवल जल का जाना हुआ (नया पदार्थ नहीं); जंग में लोहे का नया पदार्थ बना", "दोनों में नया पदार्थ बना", "दोनों भौतिक परिवर्तन हैं", "दोनों रासायनिक परिवर्तन हैं"],
     ["In the towel only the water left (no new substance); in rust a new substance of iron formed", "A new substance formed in both", "Both are physical changes", "Both are chemical changes"],
     0,
     "सूखना और जंग — दिखने में साथ, कसौटी पर अलग।",
     "Drying and rust — together in appearance, apart on the test."),

    # ---- hard (8) ----
    ("chemical-changes-in-daily-life", "hard",
     "तीन कथन: (i) पाचन रासायनिक परिवर्तन है। (ii) दही जमना रासायनिक परिवर्तन है। (iii) विद्युत लेपन भौतिक परिवर्तन है। गलत कथन:",
     "Three statements: (i) Digestion is a chemical change. (ii) Curd setting is a chemical change. (iii) Electroplating is a physical change. The wrong statement:",
     ["कथन (iii) — विद्युत लेपन रासायनिक परिवर्तन है", "कथन (i)", "कथन (ii)", "तीनों सही"],
     ["Statement (iii) — electroplating is a chemical change", "Statement (i)", "Statement (ii)", "All three correct"],
     0,
     "लेपन सूची में रासायनिक के साथ है।",
     "Plating stands with the chemical ones on the list."),

    ("chemical-changes-in-daily-life", "hard",
     "सोच-परीक्षण: यदि पाचन केवल भौतिक परिवर्तन होता, तो भोजन के साथ क्या नहीं होता?",
     "Thought experiment: if digestion were only a physical change, what would NOT happen to the food?",
     ["भोजन के गुणों वाले नए पदार्थों का निर्माण — केवल आकार बदलता", "भोजन का टुकड़ों में बँटना", "भोजन का गर्म होना", "भोजन का मुँह में आना"],
     ["The formation of new substances with new properties — only the shape would change", "The food breaking into pieces", "The food getting warm", "The food entering the mouth"],
     0,
     "भौतिक होने का अर्थ होता — पदार्थ वही, आकार भिन्न।",
     "Being physical would have meant — same substance, different shape."),

    ("chemical-changes-in-daily-life", "hard",
     "चार क्रियाओं का वर्ग-क्रम (रासायनिक/भौतिक) सही चुनिए — प्रकाश संश्लेषण, कागज़ मोड़ना, श्वसन, जंग लगाना:",
     "Choose the correct class order (chemical/physical) of the four acts — photosynthesis, folding paper, respiration, rusting:",
     ["रासायनिक, भौतिक, रासायनिक, रासायनिक", "भौतिक, रासायनिक, भौतिक, रासायनिक", "सभी रासायनिक", "सभी भौतिक"],
     ["Chemical, physical, chemical, chemical", "Physical, chemical, physical, chemical", "All chemical", "All physical"],
     0,
     "केवल मोड़ना भौतिक निकला।",
     "Only folding turned out physical."),

    ("chemical-changes-in-daily-life", "hard",
     "भ्रांति: 'दही जमना तो दूध का बस जमना है — जैसे पानी जमकर बर्फ बनता है; दोनों एक जैसे (भौतिक) हैं।' खंडन का मुख्य तर्क:",
     "Misconception: 'Curd setting is just milk freezing — like water freezing into ice; both are alike (physical).' The main refuting argument:",
     ["बर्फ जमने में जल वही रहता है; दही बनने में दूध भिन्न गुणों वाले नए पदार्थ में बदलता है", "दही कभी नहीं जमता", "बर्फ रासायनिक परिवर्तन है", "दोनों में गैस निकलती है"],
     ["In ice forming the water stays the same; in curd forming the milk changes into a new substance with different properties", "Curd never sets", "Ice forming is a chemical change", "A gas escapes in both"],
     0,
     "दिखने में 'जमना' समान, होने में पदार्थ-बदल भिन्न।",
     "In appearance both 'set'; in reality the substance-change differs."),

    ("chemical-changes-in-daily-life", "hard",
     "जंग, दही और पाचन — तीनों अलग-अलग क्षेत्रों (धातु, रसोई, शरीर) की घटनाएँ हैं, फिर भी एक परीक्षा-प्रश्न में साथ आ जाते हैं। वह साझा सूत्र क्या है?",
     "Rust, curd and digestion — events of three different arenas (metal, kitchen, body), yet they come together in one exam question. What is their shared formula?",
     ["तीनों में नए गुणों वाला नया पदार्थ बनता है — रासायनिक परिवर्तन", "तीनों भौतिक परिवर्तन हैं", "तीनों में केवल रंग बदलता है", "तीनों उत्क्रमणीय हैं"],
     ["In all three a new substance with new properties forms — a chemical change", "All three are physical changes", "In all three only the colour changes", "All three are reversible"],
     0,
     "क्षेत्र भिन्न, कसौटी एक।",
     "Different arenas, one test."),

    ("chemical-changes-in-daily-life", "hard",
     "कथन-सेट: (i) दहन ऊर्जा के आदान-प्रदान के साथ चलता है। (ii) रासायनिक परिवर्तनों में ऊर्जा का अवशोषण या उत्सर्जन दोनों संभव है। (iii) ऊर्जा का लेन-देन केवल भौतिक परिवर्तनों की विशेषता है। सही समूह:",
     "Statement set: (i) Combustion runs with an exchange of energy. (ii) In chemical changes both absorption and release of energy are possible. (iii) An exchange of energy is the exclusive feature of physical changes. The correct set:",
     ["(i) और (ii) सही, (iii) गलत", "तीनों सही", "केवल (iii) सही", "केवल (i) सही"],
     ["(i) and (ii) correct, (iii) wrong", "All three correct", "Only (iii) correct", "Only (i) correct"],
     0,
     "ऊर्जा-लेन-देन रासायनिक परिवर्तन की पहचान है।",
     "An energy exchange is a mark of chemical change."),

    ("chemical-changes-in-daily-life", "hard",
     "एक दिन की गिनती: घी जला (अनजाने में), दूध फटा, बर्फ पिघली, साइकिल की चेन पर जंग, और रोटी बेली। रासायनिक घटनाओं की संख्या और उनका चयन:",
     "A day's count: ghee burnt (by mistake), milk curdled, ice melted, rust on the bicycle chain, and a roti was rolled. The number of chemical events and their selection:",
     ["तीन — घी जलना (दहन), दूध फटना (दही जैसा नया पदार्थ), जंग लगना", "दो", "चार", "पाँचों"],
     ["Three — ghee burning (combustion), milk curdling (a new substance like curd), rusting", "Two", "Four", "All five"],
     0,
     "पिघलना और बेलना भौतिक रहे; बाकी तीन रासायनिक।",
     "Melting and rolling stayed physical; the remaining three are chemical."),

    ("chemical-changes-in-daily-life", "hard",
     "सार-प्रश्न: 'नया पदार्थ' की कसौटी दैनिक जीवन के कितने क्षेत्रों में एक जैसी लगती है — रसोई (दही), शरीर (पाचन), धातु (जंग), अनुष्ठान (दहन)?",
     "Summing up: the test of 'a new substance' applies identically across how many arenas of daily life — kitchen (curd), body (digestion), metal (rust), ritual (combustion)?",
     ["चारों क्षेत्रों में — कसौटी सर्वव्यापी है", "केवल रसोई में", "केवल शरीर में", "केवल धातु में"],
     ["Across all four arenas — the test is universal", "Only in the kitchen", "Only in the body", "Only in metals"],
     0,
     "कसौटी एक, क्षेत्र अनंत — यही अध्याय की सार-सीख।",
     "One test, endless arenas — that is the chapter's summing lesson."),
]
