#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generates the 12 NEW Physics chapter folders (roadmap P01-P12)."""
import json, os

OUT = "data/science/physics"
SUBJECT = {"subject": "physics", "subjectName": {"hi": "भौतिक विज्ञान", "en": "Physics"}, "classRange": "6-10"}

def N(concept, example, sections, kp, ef, et, tb, mt, pq, mr, qr):
    return {"concept": concept, "example": example,
            "sections": [{"heading": h, "content": c} for h, c in sections],
            "keyPoints": kp, "examFocus": ef, "examTraps": et,
            "thinkBeforeAnswer": tb, "memoryTricks": mt, "pyqSignals": pq,
            "mustRemember": mr, "quickRevision": qr}

CH = []

CH.append(("chapter-01", "P01", 1, "मापन, मात्रक एवं वैज्ञानिक अन्वेषण", "Measurement, Units & Scientific Investigation",
"मापन, मात्रक और प्रयोग की विधियाँ।", "Measurement, units and the method of experiments.",
{"hi": N(
 "विज्ञान में हर भौतिक राशि को मापना आवश्यक है और मापन के लिए मानक मात्रक चाहिए। SI प्रणाली में सात मूल मात्रक हैं — मीटर, किलोग्राम, सेकंड, एम्पियर, केल्विन, मोल और कैंडेला। सही उपकरण, सही विधि और त्रुटि का ध्यान मिलकर विश्वसनीय मापन बनाते हैं।",
 "कमरे की लंबाई मीटर स्केल से और धागे की मोटाई पेंचमापी (स्क्रू गेज) जैसे उपकरण से मापी जाती है — राशि के अनुसार उपकरण बदलता है।",
 [("मापन की आवश्यकता", "बिना मापन के तुलना अधूरी है; मापन = संख्यात्मक मान + मात्रक।"),
  ("SI मात्रक प्रणाली", "लंबाई-मीटर, द्रव्यमान-किलोग्राम, समय-सेकंड, विद्युत धारा-एम्पियर, ताप-केल्विन, पदार्थ की मात्रा-मोल, ज्योति तीव्रता-कैंडेला।"),
  ("लंबाई, द्रव्यमान एवं समय का मापन", "मीटर स्केल, वर्नियर कैलिपर्स और स्क्रू गेज लंबाई के; तुला द्रव्यमान का; घड़ी-स्टॉपवॉच समय के मापन में प्रयुक्त होते हैं।"),
  ("त्रुटि एवं परिशुद्धता", "सभी मापनों में कुछ त्रुटि होती है; सही पढ़ने की दृष्टि और अनेक बार मापकर औसत लेने से परिशुद्धता बढ़ती है।")],
 ["मापन में मात्रक अनिवार्य है — केवल संख्या अर्थहीन है",
  "SI के सात मूल मात्रक — मीटर, किलोग्राम, सेकंड, एम्पियर, केल्विन, मोल, कैंडेला",
  "1 किलोमीटर = 1000 मीटर; 1 मीटर = 100 सेंटीमीटर",
  "क्षेत्रफल का मात्रक वर्ग मीटर और आयतन का घन मीटर है",
  "द्रव्यमान और भार भिन्न राशियाँ हैं — द्रव्यमान का मात्रक किलोग्राम है",
  "प्रयोग में अनेक पाठ्यांकों का औसत त्रुटि घटाता है"],
 ["सात मूल मात्रक और उनकी राशियाँ जोड़कर रटें",
  "द्रव्यमान-भार अंतर पर विशेष ध्यान दें",
  "लघु-बृहद उपसर्ग (सेंटी, मिली, किलो, मेगा) के मान याद रखें"],
 ["द्रव्यमान और भार को समान न मानें — भार बल है जिसका मात्रक न्यूटन है",
  "किलोग्राम द्रव्यमान का मात्रक है, भार का नहीं"],
 ["मात्रक पूछा जाए तो पहले राशि पहचानें — लंबाई, द्रव्यमान या समय",
  "परिवर्तन (जैसे किमी→मी) में उपसर्ग का मान लगाकर गुणा करें"],
 ["'M-K-S-A-K-M-C' — मीटर, किलोग्राम, सेकंड, एम्पियर, केल्विन, मोल, कैंडेला क्रम से दोहराएँ",
  "किलो=1000, सेंटी=1/100, मिली=1/1000 — सीढ़ी बनाकर याद करें"],
 ["SI मूल मात्रक और उनकी राशियाँ सीधे पूछी जाती हैं",
  "मात्रक-परिवर्तन के प्रश्न आम हैं"],
 ["मापन = संख्या + मात्रक",
  "SI के सात मूल मात्रक",
  "लंबाई-द्रव्यमान-समय के मापक उपकरण",
  "द्रव्यमान और भार में अंतर"],
 "मापन के लिए संख्या और मात्रक दोनों आवश्यक हैं। SI प्रणाली के सात मूल मात्रक हैं। लंबाई, द्रव्यमान और समय के निश्चित उपकरण हैं और प्रत्येक मापन में कुछ त्रुटि संभव है, जिसे औसत लेकर घटाया जा सकता है। द्रव्यमान (किग्रा) और भार (न्यूटन) भिन्न राशियाँ हैं।"),
 "en": N(
 "In science every physical quantity must be measured, and measurement needs standard units. The SI system has seven base units — metre, kilogram, second, ampere, kelvin, mole and candela. Right instrument, right method and awareness of error together make a measurement reliable.",
 "A room's length is measured with a metre scale and a wire's thickness with a screw gauge — the instrument changes with the quantity.",
 [("Need for Measurement", "Comparison is incomplete without measurement; measurement = numerical value + unit."),
  ("SI Unit System", "Length-metre, mass-kilogram, time-second, current-ampere, temperature-kelvin, amount of substance-mole, luminous intensity-candela."),
  ("Measuring Length, Mass and Time", "Metre scale, vernier callipers and screw gauge for length; balance for mass; clock-stopwatch for time."),
  ("Error and Accuracy", "Every measurement has some error; correct viewing and averaging several readings improve accuracy.")],
 ["A unit is essential in measurement — a number alone is meaningless",
  "The seven SI base units — metre, kilogram, second, ampere, kelvin, mole, candela",
  "1 kilometre = 1000 metres; 1 metre = 100 centimetres",
  "Area is in square metres and volume in cubic metres",
  "Mass and weight are different — the unit of mass is kilogram",
  "Averaging several readings reduces error"],
 ["Learn the seven base units with their quantities",
  "Note the difference between mass and weight carefully",
  "Memorise values of prefixes (centi, milli, kilo, mega)"],
 ["Do not treat mass and weight as same — weight is a force measured in newtons",
  "Kilogram is the unit of mass, not of weight"],
 ["When a unit is asked, first identify the quantity — length, mass or time",
  "In conversions, multiply by the prefix value (km→m)"],
 ["Repeat 'M-K-S-A-K-M-C' — metre, kilogram, second, ampere, kelvin, mole, candela",
  "kilo=1000, centi=1/100, milli=1/1000 — remember as a ladder"],
 ["SI base units and their quantities are asked directly",
  "Unit-conversion questions are common"],
 ["Measurement = number + unit",
  "The seven SI base units",
  "Instruments for length-mass-time",
  "Difference between mass and weight"],
 "Measurement needs both a number and a unit. The SI system has seven base units. Length, mass and time have dedicated instruments, and every measurement carries some error, reduced by averaging. Mass (kg) and weight (newton) are different quantities.")}))

CH.append(("chapter-02", "P02", 2, "गति एवं समय", "Motion & Time",
"गति के प्रकार, चाल-वेग और ग्राफ।", "Types of motion, speed-velocity and graphs.",
{"hi": N(
 "जब किसी वस्तु की स्थिति समय के साथ बदलती है तो वह गति में कहलाती है। दूरी और विस्थापन, चाल और वेग, तथा त्वरण गति का वर्णन करते हैं। दूरी-समय और वेग-समय ग्राफ से गति की प्रकृति सरलता से समझी जाती है।",
 "सीधी सड़क पर चलती कार का ओडोमीटर दूरी दर्शाता है जबकि उसका विस्थापन उद्गम से सीधी रेखा में होता है।",
 [("दूरी एवं विस्थापन", "दूरी पथ की कुल लंबाई है (अदिश); विस्थापन न्यूनतम दूरी है जिसमें दिशा होती है (सदिश)।"),
  ("चाल एवं वेग", "चाल = दूरी/समय; वेग = विस्थापन/समय। एकसमान चाल का अर्थ है समान समय में समान दूरी।"),
  ("त्वरण", "वेग में परिवर्तन की दर त्वरण है; मुक्त पिंड का त्वरण गुरुत्वीय त्वरण g ≈ 9.8 m/s² होता है।"),
  ("ग्राफ", "दूरी-समय ग्राफ की ढाल चाल देती है; वेग-समय ग्राफ की ढाल त्वरण और क्षेत्रफल विस्थापन देता है।")],
 ["दूरी अदिश है विस्थापन सदिश",
  "विस्थापन का मान दूरी के बराबर या उससे कम हो सकता है",
  "चाल = दूरी/समय; वेग = विस्थापन/समय",
  "SI में चाल-वेग का मात्रक मीटर/सेकंड है",
  "त्वरण = वेग-परिवर्तन/समय, मात्रक m/s²",
  "एक चक्कर पूरा करने पर विस्थापन शून्य होता है"],
 ["दूरी-विस्थापन और चाल-वेग के युग्म अंतर रटें",
  "ग्राफ की ढाल का अर्थ (चाल/त्वरण) याद रखें",
  "सरल संख्यात्मक प्रश्नों का अभ्यास करें — v = d/t"],
 ["चाल और वेग को एक न मानें — दिशा बदलने पर वेग बदल जाता है",
  "वृत्ताकार पथ में एकसमान चाल होने पर भी वेग बदलता रहता है"],
 ["प्रश्न में 'कुल पथ' हो तो दूरी, 'सीधी दूरी + दिशा' हो तो विस्थापन चुनें",
  "ग्राफ क्षैतिज रेखा हो तो वस्तु विरामावस्था में है"],
 ["'D-दूरी-अदिश, V-विस्थापन-वेक्टर' जोड़ी याद रखें",
  "V-T ग्राफ: ढाल = त्वरण, क्षेत्रफल = विस्थापन"],
 ["दूरी-विस्थापन अंतर परीक्षा में बार-बार पूछा जाता है",
  "ग्राफ पढ़ने के प्रश्न आम हैं"],
 ["गति की परिभाषा",
  "दूरी बनाम विस्थापन",
  "चाल, वेग और त्वरण के सूत्र",
  "ग्राफ से चाल और त्वरण ज्ञात करना"],
 "स्थिति के समय के साथ परिवर्तन को गति कहते हैं। दूरी अदिश और विस्थापन सदिश राशि है। चाल दूरी/समय तथा वेग विस्थापन/समय होता है और वेग-परिवर्तन की दर त्वरण है। ग्राफ की ढाल और क्षेत्रफल से चाल, त्वरण और विस्थापन ज्ञात होते हैं।"),
 "en": N(
 "When an object's position changes with time it is said to be in motion. Distance and displacement, speed and velocity, and acceleration describe motion. Distance-time and velocity-time graphs make the nature of motion easy to understand.",
 "A car's odometer shows distance, while its displacement is the straight line from the origin.",
 [("Distance and Displacement", "Distance is total path length (scalar); displacement is minimum distance with direction (vector)."),
  ("Speed and Velocity", "Speed = distance/time; velocity = displacement/time. Uniform speed means equal distances in equal times."),
  ("Acceleration", "Rate of change of velocity is acceleration; a freely falling body has acceleration g ≈ 9.8 m/s²."),
  ("Graphs", "Slope of a distance-time graph gives speed; slope of a velocity-time graph gives acceleration and its area gives displacement.")],
 ["Distance is scalar, displacement is vector",
  "Displacement is less than or equal to distance",
  "Speed = distance/time; velocity = displacement/time",
  "The SI unit of speed/velocity is metre/second",
  "Acceleration = change of velocity/time, unit m/s²",
  "Displacement after one full circle is zero"],
 ["Learn the paired differences — distance-displacement and speed-velocity",
  "Remember what the slope of each graph means (speed/acceleration)",
  "Practise simple numericals — v = d/t"],
 ["Do not treat speed and velocity as identical — changing direction changes velocity",
  "In circular motion with uniform speed, velocity keeps changing"],
 ["'Total path' means distance; 'straight distance with direction' means displacement",
  "A horizontal graph line means the object is at rest"],
 ["'D-distance-scalar, V-vector' — remember the pair",
  "V-T graph: slope = acceleration, area = displacement"],
 ["The distance-displacement difference is asked repeatedly",
  "Reading graphs is a common question type"],
 ["Definition of motion",
  "Distance vs displacement",
  "Formulas of speed, velocity and acceleration",
  "Finding speed and acceleration from graphs"],
 "Change of position with time is motion. Distance is scalar and displacement is vector. Speed is distance/time and velocity is displacement/time; rate of change of velocity is acceleration. Slopes and areas of graphs give speed, acceleration and displacement.")}))

CH.append(("chapter-03", "P03", 3, "बल एवं गति के नियम", "Force & Laws of Motion",
"बल के प्रभाव और न्यूटन के तीन गति-नियम।", "Effects of force and Newton's three laws of motion.",
{"hi": N(
 "बल वह प्रभाव है जो वस्तु की गति बदल सकता है, उसे विरामावस्था से चला सकता है या आकार बदल सकता है। न्यूटन के तीन नियम गति का पूरा वर्णन करते हैं — जड़त्व का नियम, संवेग-परिवर्तन का नियम और क्रिया-प्रतिक्रिया का नियम। घर्षण एक ऐसा बल है जो गति का विरोध करता है।",
 "बस के अचानक चलने पर यात्री पीछे झुक जाता है — यह जड़त्व का उदाहरण है।",
 [("बल एवं उसके प्रभाव", "बल गति बदल सकता है, दिशा बदल सकता है और आकार बदल सकता है; संतुलित बलों में परिणामी बल शून्य होता है।"),
  ("प्रथम नियम — जड़त्व", "वस्तु अपनी अवस्था में बनी रहती है जब तक बाह्य बल न लगे; द्रव्यमान जड़त्व का माप है।"),
  ("द्वितीय नियम — संवेग", "F = ma; संवेग p = mv और बल संवेग-परिवर्तन की दर है।"),
  ("तृतीय नियम एवं घर्षण", "प्रत्येक क्रिया के बराबर व विपरीत प्रतिक्रिया होती है; घर्षण गति का विरोध करता है और उपयोगी-हानिकारक दोनों होता है।")],
 ["बल गति, दिशा या आकार बदल सकता है",
  "न्यूटन का प्रथम नियम जड़त्व का नियम है",
  "द्रव्यमान अधिक = जड़त्व अधिक",
  "द्वितीय नियम: F = ma; संवेग p = mv",
  "क्रिया-प्रतिक्रिया बराबर परंतु विपरीत दिशाओं में और भिन्न वस्तुओं पर",
  "घर्षण घटाने के उपाय — स्नेहन (lubricant), रोलर, धारावाहिक आकार"],
 ["F = ma से सरल संख्यात्मक प्रश्नों का अभ्यास करें",
  "जड़त्व के दैनिक जीवन के उदाहरण याद रखें",
  "क्रिया-प्रतिक्रिया जोड़ी के उदाहरण (रॉकेट, तैराक) जानें"],
 ["क्रिया-प्रतिक्रिया एक ही वस्तु पर नहीं लगतीं — इसलिए वे कभी संतुलित नहीं होतीं",
  "घर्षण सदा हानिकारक नहीं है — चलने में यह आवश्यक है"],
 ["'अवस्था में परिवर्तन क्यों नहीं' पूछा जाए तो जड़त्व उत्तर है",
  "रॉकेट की गति का कारण पूछा जाए तो तृतीय नियम चुनें"],
 ["पहला नियम = 'आराम का नियम', दूसरा = 'F=ma', तीसरा = 'क्रिया-प्रतिक्रिया' — तीन टैग याद रखें",
  "p = mv — 'momentum = mass × velocity' जोड़ी दोहराएँ"],
 ["न्यूटन के नियमों पर सीधे प्रश्न बार-बार आते हैं",
  "F = ma के संख्यात्मक प्रश्न परीक्षा में सामान्य हैं"],
 ["बल के प्रभाव",
  "न्यूटन के तीनों नियम",
  "संवेग और F = ma",
  "घर्षण के लाभ-हानि"],
 "बल वस्तु की गति, दिशा या आकार बदल सकता है। न्यूटन का प्रथम नियम जड़त्व बताता है, द्वितीय नियम F = ma से बल-संवेग संबंध देता है और तृतीय नियम क्रिया-प्रतिक्रिया का नियम है। घर्षण गति का विरोधी बल है जो उपयोगी और हानिकारक दोनों रूपों में होता है।"),
 "en": N(
 "Force is the influence that can change the motion, start motion from rest, or change the shape of an object. Newton's three laws describe motion fully — the law of inertia, the law of momentum change and the law of action-reaction. Friction is a force that opposes motion.",
 "When a bus starts suddenly, passengers lean backward — an example of inertia.",
 [("Force and its Effects", "Force can change motion, direction or shape; balanced forces have zero resultant."),
  ("First Law — Inertia", "A body stays in its state unless an external force acts; mass is the measure of inertia."),
  ("Second Law — Momentum", "F = ma; momentum p = mv and force is the rate of change of momentum."),
  ("Third Law and Friction", "Every action has an equal and opposite reaction; friction opposes motion and is both useful and harmful.")],
 ["Force can change motion, direction or shape",
  "Newton's first law is the law of inertia",
  "More mass = more inertia",
  "Second law: F = ma; momentum p = mv",
  "Action-reaction are equal, opposite and on different bodies",
  "Friction is reduced by lubricants, rollers and streamlined shapes"],
 ["Practise simple numericals using F = ma",
  "Remember daily-life examples of inertia",
  "Know action-reaction pairs (rocket, swimmer)"],
 ["Action and reaction do not act on the same body — hence they never balance",
  "Friction is not always harmful — it is necessary for walking"],
 ["'Why no change of state' points to inertia",
  "For a rocket's motion, choose the third law"],
 ["First law = 'law of rest', second = 'F=ma', third = 'action-reaction' — three tags",
  "p = mv — repeat 'momentum = mass × velocity'"],
 ["Direct questions on Newton's laws appear repeatedly",
  "Numericals on F = ma are common in exams"],
 ["Effects of force",
  "All three Newton's laws",
  "Momentum and F = ma",
  "Advantages and harms of friction"],
 "Force can change the motion, direction or shape of a body. Newton's first law gives inertia, the second gives F = ma and momentum, and the third gives action-reaction. Friction opposes motion and is both useful and harmful.")}))

CH.append(("chapter-04", "P04", 4, "गुरुत्वाकर्षण, भार एवं दाब", "Gravitation, Weight & Pressure",
"गुरुत्वाकर्षण, भार-द्रव्यमान अंतर और दाब।", "Gravitation, weight-mass difference and pressure.",
{"hi": N(
 "हर वस्तु हर दूसरी वस्तु को गुरुत्वाकर्षण बल से आकर्षित करती है। पृथ्वी के कारण यह बल वस्तुओं को नीचे खींचता है जिसे भार कहते हैं। दाब इकाई क्षेत्रफल पर लगने वाला बल है और द्रवों में गहराई के साथ बढ़ता है, जिससे उत्प्लावकता का नियम बनता है।",
 "नुकीली कील आसानी से दीवार में घुस जाती है क्योंकि उसका क्षेत्रफल कम होने से दाब अधिक होता है।",
 [("गुरुत्वाकर्षण का नियम", "दो वस्तुओं के बीच आकर्षण बल द्रव्यमानों के गुणनफल के समानुपाती और दूरी के वर्ग के व्युत्क्रमानुपाती होता है।"),
  ("गुरुत्वीय त्वरण एवं भार", "पृथ्वी पर g ≈ 9.8 m/s²; भार W = mg, जो स्थान के साथ बदलता है जबकि द्रव्यमान स्थिर रहता है।"),
  ("दाब", "दाब = बल/क्षेत्रफल, मात्रक पास्कल; द्रवों में दाब गहराई के साथ बढ़ता है और सभी दिशाओं में समान रूप से कार्य करता है।"),
  ("उत्प्लावकता", "आर्किमिडीज के अनुसार पिंड पर उठाव बल विस्थापित द्रव के भार के बराबर होता है; इसी से प्लवनशीलता का नियम बनता है।")],
 ["गुरुत्वाकर्षण सार्वत्रिक बल है",
  "g का मान पृथ्वी पर लगभग 9.8 m/s² है",
  "भार W = mg — यह बल है, मात्रक न्यूटन",
  "चंद्रमा पर भार पृथ्वी का लगभग 1/6 होता है",
  "दाब = बल/क्षेत्रफल, मात्रक पास्कल (N/m²)",
  "वायुमंडलीय दाब सभी दिशाओं में कार्य करता है"],
 ["द्रव्यमान-भार अंतर की तुलना तालिका याद रखें",
  "आर्किमिडीज सिद्धांत और प्लवन का नियम के उदाहरण जानें",
  "दाब-क्षेत्रफल संबंधी संख्यात्मक प्रश्नों का अभ्यास करें"],
 ["द्रव्यमान और भार को समान न लें — द्रव्यमान स्थान बदलने पर स्थिर रहता है",
  "गुरुत्वीय त्वरण सदा नीचे की ओर होता है, वस्तु की गति की दिशा से स्वतंत्र"],
 ["चंद्रमा पर भार का प्रश्न हो तो 1/6 का उपयोग करें",
  "प्लवन/डूबने का प्रश्न हो तो घनत्व की तुलना करें"],
 ["'W = mg — Weight has g' वाक्य दोहराएँ",
  "छोटा क्षेत्रफल = अधिक दाब — कील और नुकीले जूते उदाहरण हैं"],
 ["द्रव्यमान-भार अंतर परीक्षा का प्रिय प्रश्न है",
  "आर्किमिडीज सिद्धांत पर प्रश्न बार-बार आते हैं"],
 ["गुरुत्वाकर्षण का सार्वत्रिक नियम",
  "भार और द्रव्यमान में अंतर",
  "दाब की परिभाषा और मात्रक",
  "आर्किमिडीज सिद्धांत और प्लवन का नियम"],
 "प्रत्येक वस्तु गुरुत्वाकर्षण बल से दूसरी को आकर्षित करती है। पृथ्वी पर g ≈ 9.8 m/s² तथा भार W = mg होता है जो द्रव्यमान से भिन्न है। दाब बल प्रति इकाई क्षेत्रफल है और द्रव में गहराई के साथ बढ़ता है। आर्किमिडीज के सिद्धांत से उत्प्लावकता और प्लवन का नियम निकलता है।"),
 "en": N(
 "Every object attracts every other object by gravitational force. Earth's pull gives objects weight. Pressure is force per unit area and increases with depth in fluids, leading to the law of buoyancy.",
 "A pointed nail enters a wall easily because its small area gives high pressure.",
 [("Law of Gravitation", "The attraction between two bodies is proportional to the product of masses and inversely proportional to the square of distance."),
  ("Gravitational Acceleration and Weight", "On Earth g ≈ 9.8 m/s²; weight W = mg changes with place while mass stays constant."),
  ("Pressure", "Pressure = force/area, unit pascal; in fluids it increases with depth and acts equally in all directions."),
  ("Buoyancy", "By Archimedes' principle, the upward force on a body equals the weight of fluid displaced; this gives the law of floatation.")],
 ["Gravitation is a universal force",
  "g is about 9.8 m/s² on Earth",
  "Weight W = mg — it is a force in newtons",
  "On the Moon the weight is about 1/6 of that on Earth",
  "Pressure = force/area, unit pascal (N/m²)",
  "Atmospheric pressure acts in all directions"],
 ["Keep a comparison table of mass vs weight",
  "Know examples of Archimedes' principle and the law of floatation",
  "Practise numericals on pressure and area"],
 ["Do not confuse mass and weight — mass stays constant everywhere",
  "Gravitational acceleration always points downward, independent of the object's motion"],
 ["For weight on the Moon, use the 1/6 factor",
  "For floating/sinking, compare densities"],
 ["Repeat 'W = mg — Weight has g'",
  "Small area = high pressure — nail and pointed shoes are examples"],
 ["The mass-weight difference is an exam favourite",
  "Questions on Archimedes' principle appear repeatedly"],
 ["Universal law of gravitation",
  "Difference between weight and mass",
  "Definition and unit of pressure",
  "Archimedes' principle and the law of floatation"],
 "Every body attracts another gravitationally. On Earth g ≈ 9.8 m/s² and weight W = mg differs from mass. Pressure is force per unit area and grows with depth in fluids. Archimedes' principle gives buoyancy and the law of floatation.")}))

CH.append(("chapter-05", "P05", 5, "कार्य, ऊर्जा एवं शक्ति", "Work, Energy & Power",
"कार्य, ऊर्जा के रूप और शक्ति की अवधारणा।", "Work, forms of energy and the concept of power.",
{"hi": N(
 "जब बल लगाने पर वस्तु बल की दिशा में विस्थापित होती है तो कार्य होता है। ऊर्जा कार्य करने की क्षमता है और उसके मुख्य रूप गतिज तथा स्थितिज ऊर्जा हैं। शक्ति इकाई समय में किया गया कार्य है।",
 "ऊपर उठाई गई ईंट में स्थितिज ऊर्जा और गिरते समय गतिज ऊर्जा आती है — ऊर्जा संरक्षण का सरल उदाहरण।",
 [("कार्य", "W = F × s; जब विस्थापन शून्य हो या बल के लंबवत हो तो कार्य शून्य होता है। मात्रक जूल।"),
  ("ऊर्जा के रूप", "गतिज ऊर्जा KE = ½mv²; स्थितिज ऊर्जा PE = mgh; ऊर्जा रूपांतरित हो सकती है परंतु नष्ट नहीं होती।"),
  ("ऊर्जा संरक्षण", "ऊर्जा न तो उत्पन्न होती है न नष्ट — केवल रूप बदलती है; मुक्त पतन में PE और KE आपस में बदलती रहती हैं।"),
  ("शक्ति", "P = कार्य/समय, मात्रक वाट; 1 अश्वशक्ति ≈ 746 वाट और विद्युत खपत की इकाई किलोवाट-घंटा है।")],
 ["कार्य = बल × विस्थापन (बल की दिशा में)",
  "बल लगाने पर भी विस्थापन शून्य हो तो कार्य शून्य",
  "KE = ½mv² और PE = mgh",
  "ऊर्जा संरक्षण का नियम रूपांतरण बताता है",
  "शक्ति = कार्य/समय, मात्रक वाट",
  "1 kWh विद्युत ऊर्जा की व्यावसायिक इकाई है"],
 ["KE और PE के सूत्रों से सरल संख्यात्मक प्रश्न हल करें",
  "ऊर्जा-रूपांतरण की दैनिक उदाहरण-श्रृंखलाएँ लिखें",
  "वाट और किलोवाट-घंटा में अंतर समझें"],
 ["बल लगाना ही कार्य नहीं — विस्थापन आवश्यक है",
  "शक्ति और ऊर्जा भिन्न हैं — शक्ति ऊर्जा की दर है"],
 ["'कार्य शून्य' के प्रश्न में विस्थापन की दिशा जाँचें",
  "ऊर्जा की इकाई पूछी जाए तो जूल उत्तर है"],
 ["'W = Fs' और 'P = W/t' दोनों सूत्र जोड़ी में याद करें",
  "KE में v का वर्ग है — वेग दोगुना तो KE चार गुना"],
 ["KE-PE रूपांतरण और संरक्षण पर प्रश्न आम हैं",
  "कार्य और शक्ति के सूत्रों से संख्यात्मक प्रश्न आते हैं"],
 ["कार्य की परिभाषा और शर्त",
  "KE तथा PE के सूत्र",
  "ऊर्जा संरक्षण का नियम",
  "शक्ति की परिभाषा और मात्रक"],
 "बल की दिशा में विस्थापन होने पर कार्य W = Fs होता है। ऊर्जा कार्य करने की क्षमता है जिसके प्रमुख रूप गतिज (½mv²) और स्थितिज (mgh) हैं। ऊर्जा संरक्षण के नियम अनुसार ऊर्जा केवल रूप बदलती है। शक्ति कार्य की दर है जिसका मात्रक वाट है।"),
 "en": N(
 "Work is done when a force displaces an object in the direction of the force. Energy is the capacity to do work, its chief forms being kinetic and potential energy. Power is work done per unit time.",
 "A raised brick has potential energy and gains kinetic energy while falling — a simple example of energy conservation.",
 [("Work", "W = F × s; work is zero when displacement is zero or perpendicular to the force. Unit: joule."),
  ("Forms of Energy", "Kinetic energy KE = ½mv²; potential energy PE = mgh; energy changes form but is never destroyed."),
  ("Conservation of Energy", "Energy can neither be created nor destroyed, only transformed; in free fall PE and KE keep interconverting."),
  ("Power", "P = work/time, unit watt; 1 horsepower ≈ 746 watts and kilowatt-hour is the commercial unit of electricity.")],
 ["Work = force × displacement (in the direction of force)",
  "Force with zero displacement means zero work",
  "KE = ½mv² and PE = mgh",
  "The law of conservation of energy describes transformation",
  "Power = work/time, unit watt",
  "1 kWh is the commercial unit of electrical energy"],
 ["Solve simple numericals with KE and PE formulas",
  "Write daily-life chains of energy transformation",
  "Understand the difference between watt and kilowatt-hour"],
 ["Applying force is not work — displacement is necessary",
  "Power and energy differ — power is the rate of energy"],
 ["For zero-work questions, check the direction of displacement",
  "For the unit of energy, the answer is joule"],
 ["Learn 'W = Fs' and 'P = W/t' as a pair",
  "KE has v squared — double the velocity gives four times KE"],
 ["Questions on KE-PE conversion and conservation are common",
  "Numericals on work and power formulas appear in exams"],
 ["Definition and condition of work",
  "Formulas of KE and PE",
  "Law of conservation of energy",
  "Definition and unit of power"],
 "Work is W = Fs when displacement is along the force. Energy is the capacity to do work, chiefly kinetic (½mv²) and potential (mgh). By conservation of energy only the form changes. Power is the rate of work, measured in watts.")}))

CH.append(("chapter-06", "P06", 6, "ऊष्मा एवं ताप", "Heat & Temperature",
"ताप और ऊष्मा में अंतर, ऊष्मा संचरण एवं अवस्था परिवर्तन।", "Difference between heat and temperature, heat transfer and change of state.",
{"hi": N(
 "ऊष्मा ऊर्जा का रूप है जो गर्म पिंड से ठंडे पिंड की ओर प्रवाहित होती है, जबकि ताप वस्तु की गर्मी की डिग्री बताता है। ऊष्मा चालन, संवहन और विकिरण तीन विधियों से संचरित होती है। अवस्था परिवर्तन में ताप स्थिर रहता है और गुप्त ऊष्मा अवशोषित होती है।",
 "बर्फ पिघलते समय तापमान 0°C पर स्थिर रहता है — यह गुप्त ऊष्मा का प्रभाव है।",
 [("ताप एवं ऊष्मा", "ताप को थर्मामीटर से मापा जाता है; ऊष्मा का मात्रक जूल या कैलोरी है और यह कुल ऊर्जा है।"),
  ("ऊष्मा संचरण", "चालन में कण अपने स्थान पर रहकर ऊष्मा देते हैं (धातुएँ), संवहन में कण स्वयं चलते हैं (द्रव-गैस) और विकिरण में बिना माध्यम ऊष्मा मिलती है (सूर्य की गर्मी)।"),
  ("अवस्था परिवर्तन एवं गुप्त ऊष्मा", "पिघलने और क्वथन बिंदु पर ताप स्थिर रहता है; बर्फ का पिघलने का गुप्त ऊष्मा 80 cal/g और जल का क्वथन का 540 cal/g होता है।"),
  ("दैनिक जीवन में ऊष्मा", "समुद्री-स्थलीय समीरण, ठंडे पदार्थ का गर्म पानी से उबलना, गर्म वस्त्र पहनना आदि ऊष्मा संचरण के उदाहरण हैं।")],
 ["ऊष्मा ऊर्जा है, ताप उसकी तीव्रता का माप है",
  "ताप का SI मात्रक केल्विन; सामान्य पैमाना डिग्री सेल्सियस",
  "संचरण की तीन विधियाँ — चालन, संवहन, विकिरण",
  "विकिरण को कोई माध्यम नहीं चाहिए",
  "अवस्था परिवर्तन के समय ताप स्थिर रहता है",
  "धातुएँ ऊष्मा की सुचालक और लकड़ी-प्लास्टिक कुचालक हैं"],
 ["चालन-संवहन-विकिरण के दो-दो उदाहरण याद रखें",
  "समुद्री-स्थलीय समीरण की दिशा (दिन/रात) समझें",
  "गुप्त ऊष्मा की अवधारणा स्पष्ट करें"],
 ["गर्म पिंड में 'अधिक ऊष्मा' और 'अधिक ताप' को एक न मानें — द्रव्यमान भी मायने रखता है",
  "सभी विधियों को माध्यम नहीं चाहिए ऐसा नहीं — केवल विकिरण को"],
 ["ऊष्मा प्रवाह की दिशा पूछी जाए तो गर्म से ठंडे की ओर उत्तर दें",
  "ताप स्थिर क्यों — प्रश्न पर गुप्त ऊष्मा याद करें"],
 ["'C-C-R' — Conduction, Convection, Radiation क्रम से दोहराएँ",
  "बर्फ-80, जल-540 — गुप्त ऊष्मा के आंकिक मान जोड़कर याद करें"],
 ["चालन-संवहन-विकिरण अंतर परीक्षा में बार-बार पूछा जाता है",
  "गुप्त ऊष्मा पर सीधे प्रश्न आते हैं"],
 ["ताप और ऊष्मा में अंतर",
  "संचरण की तीन विधियाँ और उदाहरण",
  "अवस्था परिवर्तन में ताप का स्थिर रहना",
  "सुचालक और कुचालक पदार्थ"],
 "ऊष्मा गर्म से ठंडे पिंड की ओर बहने वाली ऊर्जा है और ताप गर्मी की डिग्री है। ऊष्मा चालन, संवहन और विकिरण से संचरित होती है। पिघलने-क्वथन बिंदु पर ताप स्थिर रहता है क्योंकि गुप्त ऊष्मा अवशोषित होती है। धातुएँ सुचालक और अधातुएँ कुचालक होती हैं।"),
 "en": N(
 "Heat is a form of energy that flows from a hot body to a cold one, while temperature tells the degree of hotness. Heat is transferred by conduction, convection and radiation. During change of state the temperature stays constant as latent heat is absorbed.",
 "While ice melts, the temperature stays at 0°C — the effect of latent heat.",
 [("Temperature and Heat", "Temperature is measured by a thermometer; heat is total energy with unit joule or calorie."),
  ("Transfer of Heat", "In conduction particles pass heat without moving (metals), in convection particles themselves move (liquids-gases), and radiation needs no medium (sunlight)."),
  ("Change of State and Latent Heat", "At melting and boiling points temperature remains constant; latent heat of ice is 80 cal/g and of boiling water 540 cal/g."),
  ("Heat in Daily Life", "Sea-land breezes, cold things warming in hot water, and wearing warm clothes are examples of heat transfer.")],
 ["Heat is energy; temperature is the measure of its intensity",
  "The SI unit of temperature is kelvin; the common scale is degree Celsius",
  "Three modes of transfer — conduction, convection, radiation",
  "Radiation needs no medium",
  "Temperature stays constant during change of state",
  "Metals are good conductors; wood-plastic are insulators"],
 ["Remember two examples each of conduction-convection-radiation",
  "Understand the direction of sea-land breezes (day/night)",
  "Clarify the concept of latent heat"],
 ["Do not equate 'more heat' with 'more temperature' — mass also matters",
  "Not all modes need a medium — only radiation does not"],
 ["For heat-flow direction, answer: hot to cold",
  "For 'why constant temperature', recall latent heat"],
 ["Repeat 'C-C-R' — Conduction, Convection, Radiation",
  "Ice-80, water-540 — remember latent heat values in pairs"],
 ["The conduction-convection-radiation difference is asked repeatedly",
  "Direct questions on latent heat appear often"],
 ["Difference between heat and temperature",
  "Three modes of transfer with examples",
  "Constant temperature during change of state",
  "Conductors and insulators"],
 "Heat flows from hot to cold bodies and temperature measures hotness. Heat transfers by conduction, convection and radiation. At melting-boiling points temperature stays constant because latent heat is absorbed. Metals conduct well while non-metals insulate.")}))

CH.append(("chapter-07", "P07", 7, "ध्वनि एवं उसके अनुप्रयोग", "Sound & Its Applications",
"ध्वनि का संचरण, तरंग गुण और प्रतिध्वनि।", "Propagation of sound, wave properties and echo.",
{"hi": N(
 "ध्वनि कंपन से उत्पन्न होती है और माध्यम (ठोस, द्रव, गैस) में दाब-तरंगों के रूप में चलती है; निर्वात में ध्वनि नहीं चलती। आवृत्ति से पिच (सुर) और आयाम से तीव्रता (प्रबलता) निर्धारित होती है। परावर्तन से प्रतिध्वनि बनती है जिसकी सहायता से दूरी मापी जाती है।",
 "पहाड़ों में चिल्लाने पर आई गूंज परावर्तित ध्वनि — प्रतिध्वनि — है।",
 [("ध्वनि का उत्पन्न एवं संचरण", "कंपन करता पिंड ध्वनि उत्पन्न करता है; ध्वनि माध्यम के कणों को कंपन कराकर आगे बढ़ती है और निर्वात में नहीं चल सकती।"),
  ("तरंग गुण", "आवृत्ति (हर्ट्ज़) से पिच, आयाम से प्रबलता और तरंगदैर्घ्य से ध्वनि का स्वरूप निर्धारित होता है; वेग = आवृत्ति × तरंगदैर्घ्य।"),
  ("प्रतिध्वनि", "परावर्तित ध्वनि सुनने योग्य हो तो प्रतिध्वनि कहलाती है; मनुष्य को दो ध्वनियाँ 0.1 सेकंड से अधिक अंतराल पर सुनाई देती हैं, इसलिए प्रतिध्वनि के लिए न्यूनतम दूरी लगभग 17.2 मीटर चाहिए।"),
  ("श्रव्यता सीमा एवं अनुप्रयोग", "मनुष्य 20 Hz–20,000 Hz सुनता है; 20 Hz से कम अवश्रव्य और 20,000 Hz से अधिक पराश्रव्य कहलाते हैं — पराश्रव्य सोनार, चिकित्सा और सफाई में उपयोगी है।")],
 ["ध्वनि यांत्रिक तरंग है — माध्यम आवश्यक है",
  "निर्वात में ध्वनि नहीं चलती",
  "पिच आवृत्ति पर और प्रबलता आयाम पर निर्भर करती है",
  "वायु में ध्वनि की चाल ≈ 344 m/s (कक्ष ताप पर)",
  "प्रतिध्वनि के लिए परावर्तक से न्यूनतम ≈ 17.2 m दूरी चाहिए",
  "मनुष्य की श्रव्यता सीमा 20–20,000 Hz है"],
 ["v = f × λ के सरल प्रश्न हल करें",
  "अवश्रव्य-पराश्रव्य-श्रव्य सीमाएँ रटें",
  "SONAR और अल्ट्रासाउंड के उपयोग याद रखें"],
 ["सभी तरंगों को माध्यम नहीं चाहिए ऐसा नहीं — प्रकाश को नहीं चाहिए, ध्वनि को चाहिए",
  "प्रतिध्वनि और गूंज (reverberation) एक नहीं हैं — बार-बार परावर्तन से गूंज बनती है"],
 ["पिच या सूक्ष्मता की बात हो तो आवृत्ति देखें",
  "दूरी मापने का प्रश्न हो तो प्रतिध्वनि सूत्र d = vt/2 लगाएँ"],
 ["'L-T-U' — 20 Hz से कम infrasound (Low), 20-20k audible (T), अधिक ultrasound (U)",
  "343-344 m/s को 'ध्वनि की हवाई चाल' के रूप में याद करें"],
 ["प्रतिध्वनि की न्यूनतम दूरी परीक्षा में बार-बार पूछी जाती है",
  "श्रव्यता सीमा और पराश्रव्य उपयोग सामान्य प्रश्न हैं"],
 ["ध्वनि को माध्यम की आवश्यकता",
  "पिच और प्रबलता के कारक",
  "प्रतिध्वनि की शर्त और न्यूनतम दूरी",
  "श्रव्यता सीमा तथा पराश्रव्य के उपयोग"],
 "ध्वनि कंपन से बनती और माध्यम में दाब तरंग से चलती है; निर्वात में नहीं। आवृत्ति से पिच और आयाम से प्रबलता तय होती है। परावर्तित ध्वनि प्रतिध्वनि बनाती है जिससे दूरी मापी जाती है। मनुष्य 20–20,000 Hz सुनता है और पराश्रव्य चिकित्सा-सोनार में उपयोगी है।"),
 "en": N(
 "Sound is produced by vibration and travels in a medium (solid, liquid, gas) as pressure waves; it cannot travel in vacuum. Frequency decides pitch and amplitude decides loudness. Reflection produces echo, which is used to measure distance.",
 "The roll of a shout in the hills is reflected sound — an echo.",
 [("Production and Propagation", "A vibrating body produces sound; sound travels by vibrating medium particles and cannot pass through vacuum."),
  ("Wave Properties", "Frequency (hertz) gives pitch, amplitude gives loudness, and wavelength shapes the sound; velocity = frequency × wavelength."),
  ("Echo", "Reflected sound heard distinctly is an echo; humans need a gap over 0.1 s between sounds, so the minimum distance for an echo is about 17.2 m."),
  ("Hearing Range and Uses", "Humans hear 20 Hz–20,000 Hz; below 20 Hz is infrasound and above 20,000 Hz is ultrasound — ultrasound is useful in sonar, medicine and cleaning.")],
 ["Sound is a mechanical wave — a medium is required",
  "Sound cannot travel through vacuum",
  "Pitch depends on frequency, loudness on amplitude",
  "Speed of sound in air ≈ 344 m/s at room temperature",
  "An echo needs a minimum reflector distance of about 17.2 m",
  "The human hearing range is 20–20,000 Hz"],
 ["Solve simple problems with v = f × λ",
  "Learn the infrasound-audible-ultrasound boundaries",
  "Remember uses of SONAR and ultrasound"],
 ["Not all waves need a medium — light does not, sound does",
  "Echo and reverberation are different — repeated reflections cause reverberation"],
 ["Pitch questions point to frequency",
  "For distance measurement, apply the echo formula d = vt/2"],
 ["'L-A-U' — below 20 Hz infrasound (Low), 20-20k Audible, above it Ultrasound",
  "Remember 343-344 m/s as the speed of sound in air"],
 ["The minimum echo distance is asked repeatedly",
  "Hearing range and ultrasound uses are common questions"],
 ["Sound needs a medium",
  "Factors of pitch and loudness",
  "Condition and minimum distance of echo",
  "Hearing range and uses of ultrasound"],
 "Sound is produced by vibration and travels as pressure waves in a medium, not in vacuum. Frequency gives pitch and amplitude gives loudness. Reflected sound forms echo, used for distance measurement. Humans hear 20–20,000 Hz and ultrasound serves medicine and sonar.")}))

CH.append(("chapter-08", "P08", 8, "प्रकाश, परावर्तन एवं अपवर्तन", "Light, Reflection & Refraction",
"दर्पण, लेंस और प्रकाश के व्यवहार की मूल बातें।", "Basics of mirrors, lenses and the behaviour of light.",
{"hi": N(
 "प्रकाश सीधी रेखा में चलती है और दर्पण से परावर्तित, लेंस-प्रिज्म से अपवर्तित होकर विभिन्न प्रतिबिंब बनाती है। परावर्तन के नियम समतल व गोलीय दर्पण के प्रतिबिंब निर्धारित करते हैं, जबकि अपवर्तन से लेंस की क्षमता और विक्षेपण की व्याख्या होती है।",
 "पानी में डूबी पेंसिल मुड़ी दिखती है — यह अपवर्तन का प्रभाव है।",
 [("प्रकाश का सीधा व वर्तन", "प्रकाश एकसमान माध्यम में सीधी रेखा में चलती है; छाया और ग्रहण इसी का प्रमाण हैं।"),
  ("परावर्तन एवं दर्पण", "आपतन कोण = परावर्तन कोण; समतल दर्पण का प्रतिबिंब आभासी, समान और पीछे बनता है; अवतल दर्पण अभिसारी तथा उत्तल दर्पण अपसारी होता है।"),
  ("अपवर्तन एवं लेंस", "प्रकाश माध्यम बदलने पर दिशा बदलती है; उत्तल लेंस अभिसारी और अवतल लेंस अपसारी होता है; लेंस की क्षमता P = 1/f (डाइऑप्टर)।"),
  ("विक्षेपण एवं मानव नेत्र", "प्रिज्म प्रकाश को सात रंगों में बाँटता है; निकट-दृष्टि दोष अवतल लेंस और दीर्घ-दृष्टि दोष उत्तल लेंस से सुधारा जाता है।")],
 ["प्रकाश सीधी रेखा में चलती है",
  "परावर्तन का नियम — आपतन कोण = परावर्तन कोण",
  "समतल दर्पण का प्रतिबिंब आभासी और समान आकार का होता है",
  "अवतल दर्पण और उत्तल लेंस अभिसारी होते हैं",
  "अपवर्तन माध्यम बदलने पर प्रकाश की दिशा परिवर्तन है",
  "श्वेत प्रकाश सात रंगों का मिश्रण है"],
 ["दर्पण और लेंस के प्रतिबिंब-बिंदु आरेख बनाकर समझें",
  "अभिसारी-अपसारी युग्म (अवतल दर्पण/उत्तल दर्पण; उत्तल लेंस/अवतल लेंस) रटें",
  "नेत्र-दोषों और उनके सुधार के जोड़े याद रखें"],
 ["अवतल-उत्तल को उलटना सामान्य त्रुटि है — दर्पण और लेंस के लिए अलग याद रखें",
  "समतल दर्पण का प्रतिबिंब वास्तविक नहीं होता"],
 ["लेंस की क्षमता पूछी जाए तो P = 1/f लगाएँ",
  "इंद्रधनुष/सात रंग का प्रश्न हो तो विक्षेपण चुनें"],
 ["'कैवी-कोन्वेक्स कन्वर्ज' — उत्तल (convex) लेंस जोड़ता (converge) है",
  "VIBGYOR क्रम — बैंगनी से लाल तक तरंगदैर्घ्य क्रम याद रखें"],
 ["दर्पण/लेंस के प्रतिबिंब गठन के प्रश्न बार-बार आते हैं",
  "नेत्र-दोष सुधार के जोड़े परीक्षा में सामान्य हैं"],
 ["परावर्तन के नियम",
  "समतल व गोलीय दर्पण के प्रतिबिंब",
  "अपवर्तन और लेंस की क्षमता",
  "विक्षेपण और नेत्र-दोष"],
 "प्रकाश सीधी रेखा में चलती है और दर्पणों से परावर्तन के नियमों पर प्रतिबिंब बनाती है। माध्यम बदलने पर अपवर्तन होता है जिससे लेंस कार्य करते हैं। प्रिज्म प्रकाश का विक्षेपण कर सात रंग दिखाता है और नेत्र-दोष लेंस से सुधारे जाते हैं।"),
 "en": N(
 "Light travels in straight lines and, on reflection from mirrors and refraction through lenses and prisms, forms various images. Laws of reflection decide images formed by plane and spherical mirrors, while refraction explains lens power and dispersion.",
 "A pencil dipped in water appears bent — an effect of refraction.",
 [("Rectilinear Propagation", "Light travels in a straight line in a uniform medium; shadows and eclipses prove it."),
  ("Reflection and Mirrors", "Angle of incidence = angle of reflection; a plane mirror forms a virtual, same-size image behind it; concave mirrors converge and convex mirrors diverge."),
  ("Refraction and Lenses", "Light changes direction when the medium changes; a convex lens converges and a concave lens diverges; lens power P = 1/f (dioptre)."),
  ("Dispersion and the Eye", "A prism splits light into seven colours; short-sightedness is corrected by a concave lens and long-sightedness by a convex lens.")],
 ["Light travels in a straight line",
  "Law of reflection — angle of incidence = angle of reflection",
  "A plane mirror image is virtual and of the same size",
  "Concave mirrors and convex lenses converge",
  "Refraction is the change of direction when the medium changes",
  "White light is a mixture of seven colours"],
 ["Understand image formation by ray diagrams of mirrors and lenses",
  "Learn converging-diverging pairs (concave/convex mirror; convex/concave lens)",
  "Remember pairs of eye defects and their corrections"],
 ["Swapping concave-convex is a common mistake — learn them separately for mirrors and lenses",
  "The image of a plane mirror is never real"],
 ["For lens power, apply P = 1/f",
  "For rainbow/seven colours, choose dispersion"],
 ["'Convex Converges' — a convex lens brings rays together",
  "VIBGYOR — remember the colour order from violet to red"],
 ["Image formation questions of mirrors/lenses come repeatedly",
  "Eye-defect correction pairs are common in exams"],
 ["Laws of reflection",
  "Images of plane and spherical mirrors",
  "Refraction and lens power",
  "Dispersion and eye defects"],
 "Light travels straight and forms images by the laws of reflection at mirrors. Refraction on changing media makes lenses work. A prism disperses light into seven colours, and eye defects are corrected with suitable lenses.")}))

CH.append(("chapter-09", "P09", 9, "विद्युत एवं विद्युत परिपथ", "Electricity & Electric Circuits",
"विद्युत धारा, ओम का नियम और परिपथ।", "Electric current, Ohm's law and circuits.",
{"hi": N(
 "विद्युत धारा आवेश का प्रवाह है जिसका मात्रक एम्पियर है। विभवांतर, प्रतिरोध और धारा का संबंध ओम का नियम V = IR देता है। प्रतिरोधों को श्रेणी और समांतर क्रम में जोड़ा जाता है और विद्युत शक्ति P = VI से निकलती है।",
 "घरेलू MCB और फ्यूज अत्यधिक धारा पर परिपथ काटकर उपकरणों को बचाते हैं।",
 [("आवेश एवं धारा", "आवेश का मात्रक कूलॉम; धारा I = Q/t का मात्रक एम्पियर — इसे अमीटर से मापा जाता है।"),
  ("विभवांतर एवं ओम का नियम", "विभवांतर का मात्रक वोल्ट, मापक वोल्टमीटर; V = IR — नियत ताप पर प्रतिरोध स्थिर रहता है।"),
  ("प्रतिरोध एवं संयोजन", "प्रतिरोध R = ρl/A — लंबाई बढ़ने पर बढ़ता और मोटाई बढ़ने पर घटता है; श्रेणी में R = R₁+R₂, समांतर में 1/R = 1/R₁+1/R₂।"),
  ("विद्युत शक्ति एवं सुरक्षा", "P = VI = I²R; इकाई वाट; फ्यूज-अर्थिंग और MCB अति-धारा से सुरक्षा देते हैं।")],
 ["धारा का मात्रक एम्पियर, आवेश का कूलॉम, विभवांतर का वोल्ट",
  "ओम का नियम V = IR",
  "प्रतिरोध लंबाई के समानुपाती और अनुप्रस्थ काट के व्युत्क्रमानुपाती है",
  "श्रेणी क्रम में प्रतिरोध जुड़ता है, समांतर में घटता है",
  "विद्युत शक्ति P = VI, मात्रक वाट",
  "अमीटर श्रेणी में और वोल्टमीटर समांतर में जोड़ा जाता है"],
 ["V = IR और P = VI से सरल संख्यात्मक प्रश्न हल करें",
  "श्रेणी-समांतर संयोजन के गुण और उदाहरण याद रखें",
  "फ्यूज और अर्थिंग का कार्य समझें"],
 ["अमीटर और वोल्टमीटर के जोड़ने का क्रम उलटना सामान्य त्रुटि है",
  "समांतर क्रम कुल प्रतिरोध सबसे छोटे प्रतिरोध से भी कम होता है — इसे ध्यान रखें"],
 ["धारा पूछी जाए तो I = V/R लगाएँ",
  "बिजली बिल की गणना kWh में होती है — P × t उपयोग करें"],
 ["'V-R-I त्रिकोण' बनाकर V=IR, I=V/R, R=V/I तीनों याद करें",
  "श्रेणी = जोड़ (Add), समांतर = भाग (divide by reciprocals)"],
 ["ओम के नियम के संख्यात्मक प्रश्न बार-बार आते हैं",
  "श्रेणी-समांतर कुल प्रतिरोध की तुलना सामान्य प्रश्न है"],
 ["धारा, आवेश और विभवांतर के मात्रक",
  "ओम का नियम",
  "प्रतिरोध के कारक और संयोजन",
  "विद्युत शक्ति और सुरक्षा उपकरण"],
 "विद्युत धारा आवेश का प्रवाह है जिसका मात्रक एम्पियर है। ओम के नियम V = IR अनुसार नियत ताप प्रतिरोध स्थिर रहता है। प्रतिरोध लंबाई और अनुप्रस्थ काट पर निर्भर करता है; श्रेणी में जुड़ता और समांतर में घटता है। विद्युत शक्ति P = VI है और फ्यूज-अर्थिंग सुरक्षा देते हैं।"),
 "en": N(
 "Electric current is the flow of charge, measured in amperes. Potential difference, resistance and current are related by Ohm's law V = IR. Resistances are combined in series and parallel, and electric power comes from P = VI.",
 "Household MCBs and fuses break the circuit on excess current and protect appliances.",
 [("Charge and Current", "The unit of charge is the coulomb; current I = Q/t in amperes, measured by an ammeter."),
  ("Potential Difference and Ohm's Law", "Potential difference is in volts, measured by a voltmeter; V = IR — resistance stays constant at fixed temperature."),
  ("Resistance and Combinations", "Resistance R = ρl/A — increases with length, decreases with thickness; in series R = R₁+R₂, in parallel 1/R = 1/R₁+1/R₂."),
  ("Electric Power and Safety", "P = VI = I²R; unit watt; fuse, earthing and MCB protect from excess current.")],
 ["Unit of current ampere, charge coulomb, potential difference volt",
  "Ohm's law V = IR",
  "Resistance is proportional to length and inversely to cross-section",
  "Series combination adds resistance; parallel reduces it",
  "Electric power P = VI, unit watt",
  "An ammeter connects in series and a voltmeter in parallel"],
 ["Solve simple numericals with V = IR and P = VI",
  "Remember properties and examples of series-parallel combinations",
  "Understand the working of fuse and earthing"],
 ["Swapping the connections of ammeter and voltmeter is a common error",
  "Note that total parallel resistance is less than the smallest resistance"],
 ["For current, apply I = V/R",
  "Electricity bills are calculated in kWh — use P × t"],
 ["Draw the 'V-R-I triangle' to remember V=IR, I=V/R, R=V/I",
  "Series = Add; parallel = reciprocals"],
 ["Numericals on Ohm's law appear repeatedly",
  "Comparing total resistance of series-parallel is common"],
 ["Units of current, charge and potential difference",
  "Ohm's law",
  "Factors of resistance and combinations",
  "Electric power and safety devices"],
 "Electric current is the flow of charge in amperes. Ohm's law V = IR holds at constant temperature. Resistance depends on length and cross-section; it adds in series and reduces in parallel. Power is P = VI and fuses with earthing give protection.")}))

CH.append(("chapter-10", "P10", 10, "चुंबकत्व एवं विद्युत-चुंबकीय प्रभाव", "Magnetism & Electromagnetic Effects",
"चुंबण, चुंबकीय क्षेत्र और विद्युत-चुंबकीय प्रभाव।", "Magnetism, magnetic fields and electromagnetic effects.",
{"hi": N(
 "चुंबक ऐसे पदार्थ हैं जो लोहे जैसी धातुओं को आकर्षित करते हैं और उनके चारों ओर चुंबकीय क्षेत्र होता है जिसे लोहे की छीलन से देखा जा सकता है। धारावाही तार के चारों ओर चुंबकीय क्षेत्र बनता है — यही विद्युत-चुंबकीय प्रभाव है जिससे विद्युत-चुंबक, मोटर और जनित्र काम करते हैं।",
 "कंपास की सुई सदा उत्तर-दक्षिण दिशा में रहती है क्योंकि पृथ्वी स्वयं एक विशाल चुंबक की तरह व्यवहार करती है।",
 [("चुंबण एवं चुंबकीय क्षेत्र", "समान ध्रुव एक-दूसरे को प्रतिकर्षित और विपरीत ध्रुव आकर्षित करते हैं; चुंबकीय बल रेखाएँ उत्तर से दक्षिण (बाहर) की ओर जाती हैं।"),
  ("पृथ्वी का चुंबकत्व", "पृथ्वी एक विशाल चुंबक की तरह है; कंपास सुई इसी के कारण दिशा बताती है।"),
  ("विद्युत-चुंबक", "धारावाही कुंडली में लोहे की छड़ डालने से मजबूत अस्थायी चुंबक बनता है; क्रेन, विद्युत घंटी और रिले में उपयोगी।"),
  ("मोटर-जनित्र प्रभाव", "चुंबकीय क्षेत्र में धारावाही चालक पर बल लगता है (मोटर) और चालक को घुमाने पर धारा प्रेरित होती है (जनित्र)।")],
 ["समान ध्रुव प्रतिकर्षित, विपरीत ध्रुव आकर्षित करते हैं",
  "चुंबकीय बल रेखाएँ चुंबक के बाहर N से S की ओर जाती हैं",
  "एक टुकड़े में टूटे चुंबक के दोनों टुकड़ों में दो ध्रुव बनते हैं",
  "धारावाही तार के चारों ओर चुंबकीय क्षेत्र बनता है",
  "विद्युत-चुंबक अस्थायी चुंबक है — धारा बंद तो चुंबकत्व समाप्त",
  "मोटर विद्युत ऊर्जा को गतिज में, जनित्र गतिज को विद्युत में बदलता है"],
 ["ध्रुव-नियम (आकर्षण-प्रतिकर्षण) और बल-रेखा दिशा रटें",
  "विद्युत-चुंबक के उपयोग (क्रेन, घंटी) याद रखें",
  "मोटर-जनित्र में ऊर्जा-रूपांतरण की दिशा समझें"],
 ["चुंबक के टुकड़े करने पर एक ध्रुवीय चुंबक नहीं बनता — हर टुकड़ा द्विध्रुवीय होता है",
  "सभी धातुएँ चुंबकीय नहीं हैं — लोहा, निकल, कोबाल्ट प्रमुख चुंबकीय धातुएँ हैं"],
 ["कंपास/दिशा का प्रश्न हो तो पृथ्वी का चुंबकत्व जोड़ें",
  "ऊर्जा-रूपांतरण की दिशा पूछी जाए तो मोटर-जनित्र का कार्य देखें"],
 ["'Like repels, Unlike attracts' — दोहराकर याद करें",
  "मोटर = मोशन (motion), जनित्र = जनरेट (generate) — नाम से कार्य याद रखें"],
 ["ध्रुवीय नियम पर सीधे प्रश्न आते हैं",
  "विद्युत-चुंबक के उपयोग पूछे जाते हैं"],
 ["चुंबकीय ध्रुवों का नियम",
  "चुंबकीय बल रेखाओं की दिशा",
  "विद्युत-चुंबक की संरचना और उपयोग",
  "मोटर और जनित्र का सिद्धांत"],
 "चुंबक विपरीत ध्रुवों में आकर्षण और समान ध्रुवों में प्रतिकर्षण दर्शाते हैं तथा चारों ओर चुंबकीय क्षेत्र बनाते हैं। पृथ्वी स्वयं चुंबत्वीय चुंबक है जिससे कंपास काम करता है। धारावाही कुंडली विद्युत-चुंबक बनाती है और इसी सिद्धांत से मोटर तथा जनित्र कार्य करते हैं।"),
 "en": N(
 "Magnets attract metals like iron and have a magnetic field around them, visible with iron filings. A current-carrying wire produces a magnetic field — the electromagnetic effect behind electromagnets, motors and generators.",
 "A compass needle always points north-south because the Earth itself behaves like a giant magnet.",
 [("Magnetism and Magnetic Field", "Like poles repel and unlike poles attract; field lines run from north to south outside the magnet."),
  ("Earth's Magnetism", "The Earth acts like a huge magnet; because of it a compass shows direction."),
  ("Electromagnet", "An iron rod inside a current-carrying coil becomes a strong temporary magnet; used in cranes, electric bells and relays."),
  ("Motor-Generator Effect", "A current-carrying conductor in a magnetic field experiences force (motor), and moving a conductor in a field induces current (generator).")],
 ["Like poles repel, unlike poles attract",
  "Outside a magnet, field lines go from N to S",
  "Breaking a magnet gives two pieces each with two poles",
  "A current-carrying wire has a magnetic field around it",
  "An electromagnet is temporary — switching off current ends the magnetism",
  "A motor converts electrical to kinetic energy; a generator the reverse"],
 ["Learn the pole rule (attraction-repulsion) and field-line direction",
  "Remember uses of electromagnets (crane, bell)",
  "Understand the direction of energy conversion in motor-generator"],
 ["Breaking a magnet never gives a single pole — every piece is dipolar",
  "Not all metals are magnetic — iron, nickel and cobalt are the main ones"],
 ["For compass/direction questions, link Earth's magnetism",
  "For energy-conversion direction, check motor vs generator"],
 ["'Like repels, Unlike attracts' — repeat to remember",
  "Motor = Motion, Generator = Generate — remember functions by name"],
 ["Direct questions on pole rules appear often",
  "Uses of electromagnets are commonly asked"],
 ["Rule of magnetic poles",
  "Direction of magnetic field lines",
  "Construction and uses of the electromagnet",
  "Principles of motor and generator"],
 "Magnets show attraction between unlike poles and repulsion between like poles, with a field around them. The Earth is itself magnetic, making compasses work. A current-carrying coil forms an electromagnet, and the same principles run motors and generators.")}))

CH.append(("chapter-11", "P11", 11, "विद्युत धारा के प्रभाव एवं ऊर्जा", "Effects of Electric Current & Energy",
"धारा के तापीय-रासायनिक-चुंबकीय प्रभाव और ऊर्जा स्रोत।", "Heating, chemical and magnetic effects of current, and energy sources.",
{"hi": N(
 "विद्युत धारा के तीन मुख्य प्रभाव हैं — तापीय (हीटर, बल्ब), रासायनिक (विद्युत अपघटन, विद्युतलेपन) और चुंबकीय (विद्युत-चुंबक, मोटर)। इन्हीं प्रभावों पर घरेलू उपकरण और औद्योगिक प्रक्रियाएँ चलती हैं। विद्युत ऊर्जा प्राप्त करने के पारंपरिक और गैर-पारंपरिक स्रोतों का ज्ञान परीक्षा के लिए आवश्यक है।",
 "पानी में डूबे दो इलेक्ट्रोड से गुजरने वाली धारा हाइड्रोजन-ऑक्सीजन गैसें देती है — विद्युत अपघटन का उदाहरण।",
 [("तापीय प्रभाव", "J = I²Rt (जूल का नियम) अनुसार धारा प्रतिरोध में ऊष्मा देती है; हीटर, इस्त्री, फ्यूज और इलेक्ट्रिक बल्ब इसी पर आधारित हैं।"),
  ("रासायनिक प्रभाव", "अम्ल-क्षार-लवण के विलयन में धारा प्रवाहित करने पर विद्युत अपघटन होता है; विद्युतलेपन (electroplating) से वस्तुओं पर धातु-परत चढ़ती है।"),
  ("चुंबकीय प्रभाव", "धारावाही चालक के चारों ओर चुंबकीय क्षेत्र बनता है — इसी से विद्युत-चुंबक, मोटर, घंटी और रिले कार्य करते हैं।"),
  ("ऊर्जा स्रोत", "पारंपरिक — जीवाश्म ईंधन (कोयला, पेट्रोल), जल-ऊर्जा; गैर-पारंपरिक — सौर, पवन, ज्वारीय, भूतापीय, बायोगैस; नवीनीकरणीय स्रोत भविष्य की आवश्यकता हैं।")],
 ["धारा के तीन प्रभाव — तापीय, रासायनिक, चुंबकीय",
  "जूल का तापीय नियम H = I²Rt",
  "विद्युतलेपन सजावटी और सुरक्षात्मक धातु-कलई करता है",
  "फ्यूस तापीय प्रभाव पर आधारित सुरक्षा उपकरण है",
  "सौर-पवन-ज्वारीय-भूतापीय नवीनीकरणीय स्रोत हैं",
  "कोयला-पेट्रोल अनवीनीकरणीय जीवाश्म ईंधन हैं"],
 ["तीनों प्रभावों के दो-दो उदाहरण जोड़कर याद करें",
  "नवीनीकरणीय बनाम अनवीनीकरणीय स्रोतों की सूची बनाएँ",
  "H = I²Rt से सरल संख्यात्मक प्रश्न हल करें"],
 ["बल्ब का प्रकाश केवल तापीय प्रभाव नहीं — तंतु गर्म होकर चमकता है, यह समझें",
  "विद्युतलेपन और विद्युत अपघटन को एक न मानें — लेपन अपघटन का अनुप्रयोग है"],
 ["उपकरण देखकर प्रभाव पहचानें — हीटर (तापीय), विद्युत-चुंबक (चुंबकीय), कलई (रासायनिक)",
  "ऊर्जा स्रोत के प्रश्न में पहले नवीनीकरणीय/अनवीनीकरणीय वर्ग तय करें"],
 ["'H-C-M' क्रम से तीन प्रभाप याद करें — Heating, Chemical, Magnetic",
  "'SPIT-G' — सौर, पवन, ज्वारीय (Tidal), भूतापीय (Geothermal) नवीनीकरणीय चार"],
 ["धारा के प्रभाव पर सीधे प्रश्न परीक्षा में आते हैं",
  "विद्युतलेपन के उपयोग पूछा जाता है"],
 ["धारा के तीन प्रभाव और उदाहरण",
  "जूल का तापीय नियम",
  "विद्युतलेपन की प्रक्रिया",
  "नवीनीकरणीय और अनवीनीकरणीय स्रोत"],
 "विद्युत धारा के तापीय (H = I²Rt), रासायनिक (विद्युत अपघटन-लेपन) और चुंबकीय (विद्युत-चुंबक) प्रभावों पर अनेक उपकरण चलते हैं। ऊर्जा के पारंपरिक स्रोत जीवाश्म ईंधन और जल हैं, जबकि सौर, पवन, ज्वारीय और भूतापीय नवीनीकरणीय विकल्प हैं।"),
 "en": N(
 "Electric current has three main effects — heating (heater, bulb), chemical (electrolysis, electroplating) and magnetic (electromagnet, motor). Household devices and industrial processes run on these effects. Knowledge of conventional and non-conventional sources of electrical energy is essential for exams.",
 "Passing current through two electrodes in water gives hydrogen and oxygen — an example of electrolysis.",
 [("Heating Effect", "By Joule's law H = I²Rt, current heats resistance; heaters, irons, fuses and bulbs work on this."),
  ("Chemical Effect", "Current through solutions of acids, bases or salts causes electrolysis; electroplating deposits a metal layer on objects."),
  ("Magnetic Effect", "A current-carrying conductor has a magnetic field around it — the basis of electromagnets, motors, bells and relays."),
  ("Sources of Energy", "Conventional — fossil fuels (coal, petrol), hydropower; non-conventional — solar, wind, tidal, geothermal, biogas; renewable sources are the future need.")],
 ["Three effects of current — heating, chemical, magnetic",
  "Joule's law of heating H = I²Rt",
  "Electroplating gives decorative and protective metal coating",
  "The fuse is a safety device based on the heating effect",
  "Solar, wind, tidal and geothermal are renewable sources",
  "Coal and petrol are non-renewable fossil fuels"],
 ["Learn two examples each of the three effects",
  "Make lists of renewable vs non-renewable sources",
  "Solve simple numericals with H = I²Rt"],
 ["A bulb's light is not only a 'heating effect' label — the filament glows because it becomes hot; understand this",
  "Do not equate electroplating with electrolysis — plating is an application of electrolysis"],
 ["Identify the effect from the device — heater (heating), electromagnet (magnetic), plating (chemical)",
  "For energy-source questions, first fix the renewable/non-renewable class"],
 ["Remember the three effects in order — Heating, Chemical, Magnetic",
  "'SWTG' — Solar, Wind, Tidal, Geothermal are the four renewables"],
 ["Direct questions on effects of current appear in exams",
  "Uses of electroplating are commonly asked"],
 ["Three effects of current with examples",
  "Joule's law of heating",
  "Process of electroplating",
  "Renewable and non-renewable sources"],
 "Many devices run on the heating (H = I²Rt), chemical (electrolysis-electroplating) and magnetic (electromagnet) effects of current. Conventional energy sources are fossil fuels and water, while solar, wind, tidal and geothermal are renewable alternatives.")}))

CH.append(("chapter-12", "P12", 12, "अंतरिक्ष, पृथ्वी एवं मूल भौतिक परिघटनाएँ", "Space, Earth & Basic Physical Phenomena",
"सौर परिवार, ग्रहण और खगोलीय परिघटनाएँ।", "The solar system, eclipses and astronomical phenomena.",
{"hi": N(
 "हमारा सौर परिवार सूर्य और उसके चारों ओर घूमते आठ ग्रहों, उपग्रहों, क्षुद्रग्रहों और धूमकेतुओं से बना है। पृथ्वी की घूर्णन और परिक्रमा से दिन-रात और ऋतु परिवर्तन होते हैं, जबकि चंद्रमा की स्थिति से कलाएँ और ग्रहण बनते हैं। भारत के अंतरिक्ष अभियान और कृत्रिम उपग्रह भी परीक्षा का भाग हैं।",
 "बड़े डब्बे में छेद कर घुसने वाली धूप की किरण सीधी रेखा में चलने का सबूत है — इसी से ग्रहण की व्याख्या होती है।",
 [("सौर परिवार", "सूर्य तारा है; आठ ग्रह — बुध, शुक्र, पृथ्वी, मंगल, बृहस्पति, शनि, अरुण, वरुण; बृहस्पति सबसे बड़ा और बुध सबसे छोटा ग्रह; शुक्र सबसे गर्म और सबसे चमकीला ग्रह है।"),
  ("दिन-रात एवं ऋतुएँ", "पृथ्वी के घूर्णन से दिन-रात और तिर्यक अक्ष पर परिक्रमा से ऋतु परिवर्तन होता है।"),
  ("चंद्रमा की कलाएँ एवं ग्रहण", "चंद्रमा पृथ्वी का उपग्रह है; सूर्य-पृथ्वी-चंद्रमा की स्थिति से कलाएँ बदलती हैं; जब चंद्रमा पृथ्वी की छाया में आता है तो चंद्र ग्रहण और जब चंद्रमा सूर्य को ढक देता है तो सूर्य ग्रहण होता है।"),
  ("भारतीय अंतरिक्ष अभियान", "ISRO द्वारा आर्यभट्ट (प्रथम भारतीय उपग्रह), चंद्रयान और मंगलयान जैसे अभियान; कृत्रिम उपग्रह संचार-मौसम-दूरसंचार में उपयोगी हैं।")],
 ["सौर परिवार में सूर्य सहित आठ ग्रह हैं",
  "पृथ्वी से दिखने वाला सबसे चमकीला पिंड शुक्र ग्रह है",
  "बृहस्पति सबसे बड़ा ग्रह; बुध सूर्य के सबसे निकट",
  "दिन-रात पृथ्वी के घूर्णन से और ऋतुएँ तिर्यक अक्ष के कारण होती हैं",
  "चंद्र ग्रहण पृथ्वी की छाया में चंद्रमा आने से होता है",
  "आर्यभट्ट प्रथम भारतीय कृत्रिम उपग्रह था"],
 ["ग्रहों का क्रम सूर्य से दूरी के अनुसार रटें",
  "सौर-चंद्र ग्रहण की स्थिति चित्र बनाकर समझें",
  "ISRO के प्रमुख अभियानों के नाम याद रखें"],
 ["शुक्र सबसे गर्म ग्रह है, बुध नहीं — यद्यपि बुध सूर्य के सबसे निकट है",
  "तारा और ग्रह भिन्न हैं — ग्रह स्वयं प्रकाशमान नहीं होते"],
 ["ग्रहण के प्रश्न में सूर्य-पृथ्वी-चंद्रमा की क्रम-स्थिति बनाकर देखें",
  "सबसे चमकीला/गर्म/बड़ा ग्रह पूछा जाए तो सावधानी से उत्तर चुनें"],
 ["'बुध-शुक्र-पृथ्वी-मंगल-बृहस्पति-शनि-अरुण-वरुण' क्रम दोहराएँ",
  "चंद्र ग्रहण = छाया में चंद्रमा; सूर्य ग्रहण = ढका सूर्य"],
 ["ग्रहों का क्रम और विशेषताएँ परीक्षा में बार-बार पूछी जाती हैं",
  "ग्रहणों का कारण सामान्य प्रश्न है"],
 ["सौर परिवार के सदस्य और ग्रहों का क्रम",
  "दिन-रात और ऋतुओं का कारण",
  "ग्रहणों का निर्माण",
  "ISRO के प्रमुख अभियान"],
 "सौर परिवार में सूर्य, आठ ग्रह, उपग्रह, क्षुद्रग्रह और धूमकेतु हैं। पृथ्वी के घूर्णन से दिन-रात और तिर्यक अक्ष पर परिक्रमा से ऋतुएँ बनती हैं। चंद्रमा की कलाएँ और ग्रहण सूर्य-पृथ्वी-चंद्रमा की स्थिति से निर्धारित होते हैं। ISRO के अभियान भारत की अंतरिक्ष प्रगति दर्शाते हैं।"),
 "en": N(
 "Our solar system consists of the Sun, eight planets revolving around it, satellites, asteroids and comets. Earth's rotation and revolution cause day-night and seasons, while the Moon's position gives phases and eclipses. Indian space missions and artificial satellites are also part of the exam syllabus.",
 "Sunlight entering through a hole in a big box travels in a straight line — this explains eclipses.",
 [("Solar System", "The Sun is a star; eight planets — Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, Neptune; Jupiter is the largest and Mercury the smallest; Venus is the hottest and brightest planet."),
  ("Day-Night and Seasons", "Earth's rotation causes day and night, and revolution on a tilted axis causes seasons."),
  ("Moon Phases and Eclipses", "The Moon is Earth's satellite; phases change with the Sun-Earth-Moon arrangement; a lunar eclipse occurs when the Moon enters Earth's shadow, and a solar eclipse when the Moon covers the Sun."),
  ("Indian Space Missions", "ISRO's missions like Aryabhata (first Indian satellite), Chandrayaan and Mangalyaan; artificial satellites serve communication, weather and broadcasting.")],
 ["The solar system has the Sun and eight planets",
  "Venus is the brightest body seen from Earth",
  "Jupiter is the largest planet; Mercury is closest to the Sun",
  "Day-night is due to rotation; seasons to the tilted axis",
  "A lunar eclipse happens when the Moon enters Earth's shadow",
  "Aryabhata was the first Indian artificial satellite"],
 ["Learn the order of planets by distance from the Sun",
  "Understand solar-lunar eclipse positions with diagrams",
  "Remember names of major ISRO missions"],
 ["Venus, not Mercury, is the hottest planet — although Mercury is nearest the Sun",
  "Stars and planets differ — planets do not shine by themselves"],
 ["For eclipse questions, draw the Sun-Earth-Moon order first",
  "Be careful when asked the brightest/hottest/largest planet"],
 ["Repeat the order — Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, Neptune",
  "Lunar eclipse = Moon in shadow; solar eclipse = Sun covered"],
 ["Planetary order and special facts are asked repeatedly",
  "Causes of eclipses are common questions"],
 ["Members of the solar system and order of planets",
  "Causes of day-night and seasons",
  "Formation of eclipses",
  "Major ISRO missions"],
 "The solar system has the Sun, eight planets, satellites, asteroids and comets. Rotation gives day-night and the tilted revolution gives seasons. Moon phases and eclipses depend on the Sun-Earth-Moon arrangement. ISRO's missions mark India's space progress.")}))

def build(ch):
    (d, code, num, nhi, nen, dhi, den, notes) = ch
    meta = dict(SUBJECT)
    meta.update({
        "chapter": d,
        "chapterNumber": num,
        "code": code,
        "chapterName": {"hi": nhi, "en": nen},
        "mockQuestionCount": 30,
        "practiceQuestionTarget": 150,
        "mockTestTarget": 5,
        "topics": [],
        "notes": notes,
    })
    return d, meta

if __name__ == "__main__":
    for ch in CH:
        d, meta = build(ch)
        p = os.path.join(OUT, d)
        os.makedirs(p, exist_ok=True)
        with open(os.path.join(p, "meta.json"), "w", encoding="utf-8") as f:
            json.dump(meta, f, ensure_ascii=False, indent=2); f.write("\n")
        with open(os.path.join(p, "questions.json"), "w", encoding="utf-8") as f:
            json.dump({"questions": []}, f, ensure_ascii=False, indent=2); f.write("\n")
        print("wrote", os.path.join(OUT, d))
    print("physics chapters:", len(CH))
