#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generates the 12 NEW Chemistry chapter folders (roadmap C01-C12)."""
import json, os

OUT = "data/science/chemistry"
SUBJECT = {"subject": "chemistry", "subjectName": {"hi": "रसायन विज्ञान", "en": "Chemistry"}, "classRange": "6-10"}

def N(concept, example, sections, kp, ef, et, tb, mt, pq, mr, qr):
    return {"concept": concept, "example": example,
            "sections": [{"heading": h, "content": c} for h, c in sections],
            "keyPoints": kp, "examFocus": ef, "examTraps": et,
            "thinkBeforeAnswer": tb, "memoryTricks": mt, "pyqSignals": pq,
            "mustRemember": mr, "quickRevision": qr}

CH = []

CH.append(("chapter-01", "C01", 1, "पदार्थ एवं उसकी अवस्थाएँ", "Matter & Its States",
"पदार्थ की तीन अवस्थाएँ और उनका अंतर-परिवर्तन।", "The three states of matter and their interconversion.",
{"hi": N(
 "पदार्थ वह है जो द्रव्यमान रखता है और स्थान घेरता है। ठोस, द्रव और गैस पदार्थ की तीन अवस्थाएँ हैं जो कणों के बीच आकर्षण और गतिज ऊर्जा के अंतर से निर्धारित होती हैं। ताप बढ़ाने-घटाने से पदार्थ एक अवस्था से दूसरी में बदलता है।",
 "बर्फ पिघलकर जल और जल उबलकर भाप बनता है — अवस्था परिवर्तन का सामान्य उदाहरण।",
 [("पदार्थ कणों से बना है", "कण अत्यंत छोटे होते हैं, उनके बीच रिक्त स्थान होता है और वे निरंतर गतिमान रहते हैं; विसरण इसका प्रमाण है।"),
  ("ठोस, द्रव, गैस", "ठोस में कण सबसे संघन और स्थिर; द्रव में प्रवाह गुण; गैस में कण सर्वाधिक स्वतंत्र और संपीड्य।"),
  ("अवस्था परिवर्तन", "पिघलन (ठोस→द्रव), क्वथन (द्रव→गैस), संघनन (गैस→द्रव), जमन (द्रव→ठोस) और उर्ध्वपातन (ठोस→गैस) मुख्य परिवर्तन हैं।"),
  ("वाष्पीकरण एवं शीतलन", "वाष्पीकरण के कारक — ताप, सतही क्षेत्रफल, वायु गति, आर्द्रता; पानी के छींटे लगाने से ठंडक वाष्पीकरण के कारण होती है।")],
 ["पदार्थ = द्रव्यमान + आयतन",
  "कणों के बीच आकर्षण: ठोस > द्रव > गैस",
  "गैसें संपीड्य और विसरण दर में सर्वाधिक होती हैं",
  "पिघलन-क्वथन बिंदु पर ताप स्थिर रहता है",
  "उर्ध्वपातन में ठोस सीधे गैस बनता है (नैफ्थलीन, कपूर)",
  "वाष्पीकरण से शीतलन होता है"],
 ["तीनों अवस्थाओं के गुणों की तुलना तालिका रटें",
  "अवस्था-परिवर्तन के नाम और दिशा जोड़कर याद करें",
  "वाष्पीकरण के चार कारक दोहराएँ"],
 ["वाष्पीकरण और क्वथन एक नहीं — क्वथन पूरे द्रव में, वाष्पीकरण केवल सतह पर होता है",
  "सभी ठोस पिघलकर द्रव बनते हैं ऐसा नहीं — नैफ्थलीन सीधे गैस बनती है"],
 ["'संपीड्य' शब्द देखकर गैस पहचानें",
  "ठंडा करने का कारण पूछा जाए तो वाष्पीकरण उत्तर है"],
 ["'S-L-G' क्रम में आकर्षण घटता है — Solid, Liquid, Gas",
  "पिघलन-जमन जोड़ी और क्वथन-संघनन जोड़ी को साथ याद करें"],
 ["तीन अवस्थाओं की तुलना परीक्षा में बार-बार आती है",
  "वाष्पीकरण के कारक सीधे पूछे जाते हैं"],
 ["पदार्थ की परिभाषा",
  "तीन अवस्थाओं के गुण",
  "अवस्था परिवर्तनों के नाम",
  "वाष्पीकरण के कारक और शीतलन प्रभाव"],
 "पदार्थ द्रव्यमान और आयतन रखता है और छोटे कणों से बना है। ठोस, द्रव, गैस अवस्थाएँ कणों के आकर्षण व गति के अंतर से बनती हैं। ताप परिवर्तन से पिघलन, क्वथन, संघनन, जमन और उर्ध्वपातन होते हैं; वाष्पीकरण से शीतलन होता है।"),
 "en": N(
 "Matter is anything that has mass and occupies space. Solid, liquid and gas are the three states of matter, decided by the attraction between particles and their kinetic energy. Changing temperature converts matter from one state to another.",
 "Ice melts into water and water boils into vapour — a common example of change of state.",
 [("Matter is Made of Particles", "Particles are extremely small, have spaces between them and are constantly moving; diffusion proves this."),
  ("Solid, Liquid, Gas", "In solids particles are most packed and fixed; liquids flow; in gases particles are freest and compressible."),
  ("Change of State", "Melting (solid→liquid), boiling (liquid→gas), condensation (gas→liquid), freezing (liquid→solid) and sublimation (solid→gas) are the main changes."),
  ("Evaporation and Cooling", "Factors of evaporation — temperature, surface area, wind speed, humidity; sprinkled water cools due to evaporation.")],
 ["Matter = mass + volume",
  "Attraction between particles: solid > liquid > gas",
  "Gases are compressible and diffuse fastest",
  "Temperature stays constant at melting-boiling points",
  "In sublimation a solid turns directly into gas (naphthalene, camphor)",
  "Evaporation causes cooling"],
 ["Learn the comparison table of the three states",
  "Memorise names of state changes with their directions",
  "Repeat the four factors of evaporation"],
 ["Evaporation and boiling are different — boiling occurs throughout the liquid, evaporation only at the surface",
  "Not every solid melts first — naphthalene turns directly into gas"],
 ["The word 'compressible' points to a gas",
  "For cooling, the answer is evaporation"],
 ["Attraction decreases in order Solid-Liquid-Gas",
  "Remember melting-freezing and boiling-condensation as pairs"],
 ["Comparison of three states is asked repeatedly",
  "Factors of evaporation are asked directly"],
 ["Definition of matter",
  "Properties of the three states",
  "Names of changes of state",
  "Factors of evaporation and the cooling effect"],
 "Matter has mass and volume and is made of tiny particles. Solid, liquid and gas states arise from differences in particle attraction and motion. Temperature changes cause melting, boiling, condensation, freezing and sublimation; evaporation produces cooling.")}))

CH.append(("chapter-02", "C02", 2, "भौतिक एवं रासायनिक परिवर्तन", "Physical & Chemical Changes",
"परिवर्तनों के दो प्रकार और उनकी पहचान।", "Two types of changes and how to identify them.",
{"hi": N(
 "परिवर्तन दो प्रकार के होते हैं — भौतिक, जिसमें केवल भौतिक गुण बदलते हैं और नया पदार्थ नहीं बनता, और रासायनिक, जिसमें नया पदार्थ बनता है। रासायनिक परिवर्तन प्रायः अनुक्रमणीय होते हैं और इनमें ऊर्जा का अवशोषण या उत्सर्जन होता है।",
 "जले हुए चाकमाक से नया गंधक डाइऑक्साइड बनता है — रासायनिक परिवर्तन; जबकि चीनी के घुलने पर कोई नया पदार्थ नहीं बनता — भौतिक परिवर्तन।",
 [("भौतिक परिवर्तन", "अवस्था, आकार या आकृति बदलती है पर मूल पदार्थ वही रहता है; जैसे पिघलना, भंगन, घुलना — प्रायः उत्क्रमणीय।"),
  ("रासायनिक परिवर्तन", "नया पदार्थ बनता है जिसके गुण भिन्न होते हैं; संकेत — रंग परिवर्तन, गैस निकलना, ताप परिवर्तन, अवक्षेप बनना।"),
  ("मोचन (जंग) एवं उसकी रोकथाम", "लोहे में ऑक्सीजन-जल के संपर्क से जंग लगता है; रंगना, गैल्वनाइज़िंग (जस्तीकरण), तेल लगाना और मिश्र धातु बनाना रोकथाम के उपाय हैं।"),
  ("दैनिक जीवन के रासायनिक परिवर्तन", "पाचन, श्वसन, प्रकाश संश्लेषण, दहन, दही जमना और विद्युत लेपन — सभी रासायनिक परिवर्तन हैं।")],
 ["भौतिक परिवर्तन में नया पदार्थ नहीं बनता",
  "रासायनिक परिवर्तन में नया पदार्थ बनता है",
  "रासायनिक परिवर्तन के संकेत — रंग, गैस, ताप, अवक्षेप",
  "जंग लगना लोहे का ऑक्सीकरण है",
  "गैल्वनाइज़िंग में जस्ते की परत चढ़ाई जाती है",
  "पाचन और श्वसन रासायनिक परिवर्तन हैं"],
 ["दोनों परिवर्तनों के उदाहरण अलग-अलग सूचीबद्ध करके रटें",
  "जंग रोकथाम के उपाय याद रखें",
  "परिवर्तन देखकर उसका प्रकार पहचानने का अभ्यास करें"],
 ["घुलना सदैव भौतिक परिवर्तन नहीं — चूने का जल में घुलने पर ऊष्मा और नया पदार्थ बनता है",
  "जंग लगना भौतिक क्षरण नहीं, रासायनिक परिवर्तन है"],
 ["नया पदार्थ बनता है या नहीं — यही पहला प्रश्न पूछें",
  "गैस/रंग/ताप का संकेत मिले तो रासायनिक परिवर्तन चुनें"],
 ["'P = Same substance, C = Completely new' — भौतिक बनाम रासायनिक",
  "जंग-जस्ता (Zn) जोड़ी याद रखें — गैल्वनाइज़िंग में जस्ता"],
 ["भौतिक-रासायनिक अंतर परीक्षा का सामान्य प्रश्न है",
  "जंग और उसकी रोकथाम पूछी जाती है"],
 ["दोनों परिवर्तनों की परिभाषा",
  "रासायनिक परिवर्तन के संकेत",
  "जंग लगने की शर्तें और रोकथाम",
  "दैनिक जीवन के उदाहरण"],
 "भौतिक परिवर्तन में केवल भौतिक गुण बदलते हैं और मूल पदार्थ बना रहता है, जबकि रासायनिक परिवर्तन में नया पदार्थ बनता है। रंग, गैस, ताप व अवक्षेप रासायनिक परिवर्तन के संकेत हैं। जंग लगना रासायनिक परिवर्तन है जिसे रंगना व जस्तीकरण से रोका जाता है।"),
 "en": N(
 "Changes are of two types — physical, where only physical properties change and no new substance forms, and chemical, where a new substance is produced. Chemical changes are mostly irreversible and involve absorption or release of energy.",
 "Burning magnesium gives new magnesium oxide — a chemical change; dissolving sugar forms no new substance — a physical change.",
 [("Physical Change", "State, shape or form changes but the original substance remains, e.g. melting, breaking, dissolving — usually reversible."),
  ("Chemical Change", "A new substance with different properties forms; signs — colour change, gas evolution, temperature change, precipitate formation."),
  ("Rusting and its Prevention", "Iron rusts on contact with oxygen and water; painting, galvanising, oiling and alloying prevent it."),
  ("Chemical Changes in Daily Life", "Digestion, respiration, photosynthesis, burning, curd formation and electroplating are all chemical changes.")],
 ["No new substance forms in a physical change",
  "A new substance forms in a chemical change",
  "Signs of chemical change — colour, gas, heat, precipitate",
  "Rusting is oxidation of iron",
  "Galvanising coats iron with a layer of zinc",
  "Digestion and respiration are chemical changes"],
 ["List examples of both types separately and learn them",
  "Remember methods of preventing rusting",
  "Practise identifying the type from a described change"],
 ["Dissolving is not always physical — dissolving lime in water gives heat and a new substance",
  "Rusting is not physical erosion but a chemical change"],
 ["First ask whether a new substance forms",
  "Gas/colour/heat signs point to a chemical change"],
 ["'P = Same substance, C = Completely new' — physical vs chemical",
  "Remember the rust-zinc pair — zinc in galvanising"],
 ["The physical-chemical difference is a common exam question",
  "Rusting and its prevention are frequently asked"],
 ["Definitions of both changes",
  "Signs of chemical change",
  "Conditions and prevention of rusting",
  "Daily-life examples"],
 "In a physical change only physical properties change and the substance remains; in a chemical change a new substance forms. Colour, gas, heat and precipitate signal chemical changes. Rusting is a chemical change prevented by painting and galvanising.")}))

CH.append(("chapter-03", "C03", 3, "पदार्थों का पृथक्करण एवं मिश्रण", "Separation of Substances & Mixtures",
"मिश्रण और पृथक्करण की विधियाँ।", "Mixtures and methods of separation.",
{"hi": N(
 "दो या अधिक पदार्थों के मिश्रण के घटकों को उनके गुणों के अंतर के आधार पर पृथक किया जाता है। अनाज से कंकड़ निकालने से लेकर पेट्रोल शोधन तक हर स्थान पर पृथक्करण विधियाँ प्रयुक्त होती हैं। विधि का चुनाव घटकों के आकार, घनत्व, विलेयता और वाष्पशीलता पर निर्भर करता है।",
 "समुद्र के जल से नमक वाष्पीकरण द्वारा और रेत से नमक छानकर-घोलकर प्राप्त किया जाता है।",
 [("मिश्रण क्या है", "मिश्रण में घटक अपने गुण बनाए रखते हैं और साधारण विधियों से पृथक हो सकते हैं; विलयन, स्लरी और निलंबन मिश्रण के रूप हैं।"),
  ("शुष्क विधियाँ", "हाथ से बीनना, थreshाई (winnowing), छलनी (sieving), चुंबकीय पृथक्करण और उर्ध्वपातन — आकार/घनत्व/चुंबकत्व के अंतर पर आधारित।"),
  ("आर्द्र विधियाँ", "अवसादन (sedimentation), निस्तारण (decantation), निस्पंदन (filtration), वाष्पीकरण, संघनन और आसवन (distillation) — विलेयता और वाष्पशीलता के अंतर पर आधारित।"),
  ("विशिष्ट विधियाँ", "प्रभाजी निस्पंदन (तेल-जल), क्रोमेटोग्राफी (रंगों का पृथक्करण), केंद्रापसारण (क्रीम-दूध) और जल अवशोषण द्वारा संतृप्त विलयन से क्रिस्टलीकरण।")],
 ["मिश्रण के घटक अपने गुण रखते हैं",
  "छलनी आकार के अंतर पर, थreshाई भार के अंतर पर काम करती है",
  "निस्पंदन अघुलनशील ठोस-द्रव मिश्रण के लिए",
  "वाष्पीकरण से घुला ठोस प्राप्त होता है",
  "आसवन विलायक के उबलाव बिंदु के अंतर पर आधारित है",
  "प्रभाजी कीप अमिश्रणीय द्रवों (तेल-जल) को पृथक करता है"],
 ["प्रत्येक विधि का एक स्मरणीय उदाहरण जोड़कर रटें",
  "निस्पंदन-निस्तारण-अवसादन का क्रम समझें",
  "क्रिस्टलीकरण और आसवन में अंतर स्पष्ट करें"],
 ["निस्पंदन और निस्तारण को एक न मानें — निस्तारण बिना फिल्टर तरल उंडेलना है",
  "वाष्पीकरण और आसवन भिन्न हैं — आसवन में वाष्प को संघनित कर एकत्र किया जाता है"],
 ["तेल-जल जैसा अमिश्रणीय युग्म देखें तो प्रभाजी कीप चुनें",
  "घुले ठोस को प्राप्त करना हो तो वाष्पीकरण/क्रिस्टलीकरण सोचें"],
 ["'छलनी = छानना (size)', 'कीप = अमिश्रणीय (immiscible)' जोड़ी याद रखें",
  "SED-FIL-EVA-CON क्रम — अवसादन, निस्पंदन, वाष्पीकरण, संघनन"],
 ["विधि और उदाहरण के मिलान के प्रश्न बार-बार आते हैं",
  "नमक-रेत और तेल-जल प्रिय उदाहरण हैं"],
 ["मिश्रण की परिभाषा",
  "शुष्क और आर्द्र पृथक्करण विधियाँ",
  "आसवन और प्रभाजी निस्पंदन का उपयोग",
  "क्रिस्टलीकरण की प्रक्रिया"],
 "मिश्रण के घटक गुणों के अंतर के आधार पर पृथक किए जाते हैं — आकार (छलनी), भार (थreshाई), चुंबकत्व, विलेयता (निस्पंदन, वाष्पीकरण), वाष्पशीलता (आसवन) और अमिश्रणीयता (प्रभाजी कीप)। उद्देश्य के अनुसार उपयुक्त विधि चुनी जाती है।"),
 "en": N(
 "Components of a mixture of two or more substances are separated based on differences in their properties. Separation methods are used everywhere from cleaning grain to refining petrol. The choice of method depends on size, density, solubility and volatility of the components.",
 "Salt is obtained from sea water by evaporation and from sand by filtering, dissolving and evaporating.",
 [("What is a Mixture", "In a mixture components retain their properties and can be separated by simple methods; solutions and suspensions are forms of mixtures."),
  ("Dry Methods", "Handpicking, winnowing, sieving, magnetic separation and sublimation — based on differences of size, weight or magnetism."),
  ("Wet Methods", "Sedimentation, decantation, filtration, evaporation, condensation and distillation — based on solubility and volatility differences."),
  ("Special Methods", "Separating funnel (oil-water), chromatography (separating colours), centrifugation (cream from milk) and crystallisation from saturated solutions.")],
 ["Components of a mixture keep their properties",
  "Sieving works on size difference; winnowing on weight difference",
  "Filtration suits an insoluble solid-liquid mixture",
  "Evaporation recovers a dissolved solid",
  "Distillation is based on boiling point difference of solvents",
  "A separating funnel separates immiscible liquids (oil-water)"],
 ["Learn each method with one memorable example",
  "Understand the order sedimentation-decantation-filtration",
  "Clarify the difference between crystallisation and distillation"],
 ["Do not equate filtration with decantation — decantation pours off the liquid without a filter",
  "Evaporation and distillation differ — in distillation the vapour is condensed and collected"],
 ["For an immiscible pair like oil-water, choose the separating funnel",
  "To recover a dissolved solid, think evaporation or crystallisation"],
 ["'Sieve = size', 'Funnel = immiscible' — remember the pairs",
  "SED-FIL-EVA-CON order — sedimentation, filtration, evaporation, condensation"],
 ["Matching methods with examples is asked repeatedly",
  "Salt-sand and oil-water are favourite examples"],
 ["Definition of a mixture",
  "Dry and wet separation methods",
  "Uses of distillation and the separating funnel",
  "Process of crystallisation"],
 "Components of mixtures are separated by property differences — size (sieving), weight (winnowing), magnetism, solubility (filtration, evaporation), volatility (distillation) and immiscibility (separating funnel). A suitable method is chosen according to the purpose.")}))

CH.append(("chapter-04", "C04", 4, "तत्व, यौगिक एवं शुद्ध पदार्थ", "Elements, Compounds & Pure Substances",
"तत्व, यौगिक और मिश्रण का स्पष्ट वर्गीकरण।", "Clear classification of elements, compounds and mixtures.",
{"hi": N(
 "शुद्ध पदार्थ दो प्रकार के होते हैं — तत्व और यौगिक। तत्व वह शुद्ध पदार्थ है जो एक ही प्रकार के परमाणुओं से बना हो, जबकि यौगिक दो या अधिक तत्वों के निश्चित अनुपात में रासायनिक संयोग से बनता है। मिश्रण में घटक किसी भी अनुपात में भौतिक रूप से मिले रहते हैं।",
 "जल (H₂O) एक यौगिक है जिसमें हाइड्रोजन-ऑक्सीजन 1:8 द्रव्यमान अनुपात में स्थिर रहते हैं, जबकि वायु एक मिश्रण है जिसकी संरचना स्थान बदलने पर बदल सकती है।",
 [("तत्व", "अब तक 118 तत्व ज्ञात हैं; धातु, अधातु और उपधातु वर्ग हैं; प्रतीक अंतरराष्ट्रीय सहमति से निश्चित होते हैं।"),
  ("यौगिक", "निश्चित द्रव्यमान अनुपात, समरूप संरचना और स्वयं से भिन्न गुण; जैसे जल, नमक, चीनी।"),
  ("मिश्रण", "घटक किसी भी अनुपात में, अपने गुणों के साथ; सममिश्रण (विलयन) और विषममिश्रण प्रकार।"),
  ("पदार्थ वर्गीकरण का चार्ट", "पदार्थ → शुद्ध (तत्व/यौगिक) + मिश्रण; यही चार्ट परीक्षा में पूछा जाता है।")],
 ["तत्व एक ही प्रकार के परमाणुओं से बना शुद्ध पदार्थ है",
  "यौगिक में तत्व निश्चित अनुपात में रासायनिक रूप से जुड़े होते हैं",
  "मिश्रण में घटक भौतिक रूप से मिलते हैं और किसी भी अनुपात में रह सकते हैं",
  "यौगिक के गुण उसके घटकों से भिन्न होते हैं",
  "मिश्रण के गुण घटकों के गुणों पर निर्भर रहते हैं",
  "धातुएँ चमकदार-संवाहक, अधातुएँ भंगुर-असंवाहक होती हैं"],
 ["पदार्थ वर्गीकरण चार्ट बनाकर रटें",
  "यौगिक बनाम मिश्रण की तुलना तालिका याद करें",
  "प्रमुख तत्वों के प्रतीक और धातु-अधातु वर्ग याद रखें"],
 ["वायु यौगिक नहीं, मिश्रण है — इसकी संरचना स्थिर नहीं होती",
  "मिश्रण और यौगिक दोनों में एक से अधिक तत्व हो सकते हैं — अंतर संयोग के प्रकार में है"],
 ["'निश्चित अनुपात' मिले तो यौगिक, 'कोई भी अनुपात' मिले तो मिश्रण चुनें",
  "पृथक्करण की कठिनाई देखें — यौगिक केवल रासायनिक विधि से टूटता है"],
 ["'E = one Element, C = Combination fixed' — तत्व और यौगिक",
  "वायु = मिश्रण, जल = यौगिक — इस जोड़ी को स्मरण-चिह्न बनाएँ"],
 ["यौगिक-मिश्रण अंतर परीक्षा में बार-बार पूछा जाता है",
  "पदार्थ वर्गीकरण चार्ट पूछा जाता है"],
 ["तत्व और यौगिक की परिभाषा",
  "यौगिक-मिश्रण अंतर",
  "धातु-अधातु-उपधातु वर्ग",
  "पदार्थ वर्गीकरण चार्ट"],
 "शुद्ध पदार्थ तत्व (एक ही प्रकार के परमाणु) और यौगिक (निश्चित अनुपात में रासायनिक संयोग) होते हैं। मिश्रण में घटक भौतिक रूप से किसी भी अनुपात में रहते हैं और सरल विधियों से पृथक होते हैं। तत्वों को धातु, अधातु और उपधातु में बाँटा जाता है।"),
 "en": N(
 "Pure substances are of two types — elements and compounds. An element is a pure substance made of one kind of atom, while a compound forms by chemical combination of two or more elements in a fixed ratio. In a mixture, components remain physically mixed in any ratio.",
 "Water (H₂O) is a compound where hydrogen and oxygen stay in a fixed 1:8 mass ratio, while air is a mixture whose composition can change from place to place.",
 [("Element", "118 elements are known so far; metals, non-metals and metalloids are the classes; symbols are internationally agreed."),
  ("Compound", "Fixed mass ratio, uniform composition and properties different from its components, e.g. water, salt, sugar."),
  ("Mixture", "Components in any ratio, keeping their properties; homogeneous (solutions) and heterogeneous types."),
  ("Classification Chart of Matter", "Matter → pure (element/compound) + mixture; this chart is asked in exams.")],
 ["An element is a pure substance of one kind of atom",
  "In a compound elements combine chemically in a fixed ratio",
  "In a mixture components mix physically in any ratio",
  "Properties of a compound differ from its components",
  "Properties of a mixture depend on its components",
  "Metals are lustrous conductors; non-metals are brittle insulators"],
 ["Draw and learn the classification chart of matter",
  "Memorise the compound vs mixture comparison table",
  "Remember symbols of common elements and their classes"],
 ["Air is not a compound but a mixture — its composition is not fixed",
  "Both mixtures and compounds can contain many elements — the difference lies in the type of combination"],
 ["'Fixed ratio' means compound; 'any ratio' means mixture",
  "Note the difficulty of separation — a compound breaks only chemically"],
 ["'E = one Element, C = Combination fixed'",
  "Air = mixture, water = compound — use the pair as a memory tag"],
 ["The compound-mixture difference is asked repeatedly",
  "The classification chart of matter is frequently asked"],
 ["Definitions of element and compound",
  "Compound vs mixture difference",
  "Classes of metals, non-metals, metalloids",
  "Classification chart of matter"],
 "Pure substances are elements (one kind of atom) and compounds (chemical combination in fixed ratio). In mixtures, components stay physically mixed in any ratio and separate by simple methods. Elements are classified as metals, non-metals and metalloids.")}))

CH.append(("chapter-05", "C05", 5, "परमाणु, अणु एवं रासायनिक सूत्र", "Atoms, Molecules & Chemical Formulae",
"परमाणु सिद्धांत, संयोजकता और सूत्र लेखन।", "Atomic theory, valency and writing formulae.",
{"hi": N(
 "परमाणु द्रव्य की सबसे छोटी क्रियाशील इकाई है और अणु दो या अधिक परमाणुओं का समूह है। डाल्टन के परमाणु सिद्धांत ने रासायनिक संयोग के नियमों को व्याख्या दी। संयोजकता (वैलेंसी) जानकर हम किसी भी यौगिक का रासायनिक सूत्र लिख सकते हैं।",
 "जल का सूत्र H₂O है क्योंकि हाइड्रोजन की संयोजकता 1 और ऑक्सीजन की 2 है — क्रॉस-विधि से सूत्र बनता है।",
 [("परमाणु एवं अणु", "परमाणु तत्व की मूल इकाई है; अणु एक ही या भिन्न तत्वों के परमाणुओं से बन सकता है (O₂, H₂O)।"),
  ("डाल्टन का सिद्धांत", "परमाणु अविभाज्य, असृजित और अविनाशी हैं; रासायनिक अभिक्रिया में परमाणु केवल पुनर्व्यवस्थित होते हैं।"),
  ("संयोजकता एवं आयन", "संयोजकता संयोग क्षमता है — H=1, O=2, N=3, C=4; धनायन इलेक्ट्रॉन देते और ऋणायन लेते हैं।"),
  ("सूत्र लेखन एवं स्थिर अनुपात", "क्रॉस-विधि से सूत्र लिखें; शुद्ध यौगिक में तत्वों का द्रव्यमान अनुपात सदा स्थिर रहता है (नियत अनुपात का नियम); आण्विक द्रव्यमान = परमाणु द्रव्यमानों का योग।")],
 ["परमाणु तत्व की सबसे छोटी क्रियाशील इकाई है",
  "अणु समान परमाणुओं (O₂) या भिन्न परमाणुओं (H₂O) से बनता है",
  "प्रमुख संयोजकताएँ — H(1), O(2), N(3), C(4)",
  "धनायन धनावेशित, ऋणायन ऋणावेशित होते हैं",
  "नियत अनुपात का नियम शुद्ध यौगिक पर लागू होता है",
  "जल का आण्विक द्रव्यमान 18 u है"],
 ["क्रॉस-विधि से सामान्य यौगिकों के सूत्र लिखने का अभ्यास करें",
  "प्रमुख तत्वों के प्रतीक और संयोजकता जोड़े रटें",
  "आण्विक द्रव्यमान की सरल गणनाएँ करें"],
 ["परमाणु और अणु को एक न मानें — अणु परमाणुओं से बना होता है",
  "सभी परमाणु आज भी अविभाज्य नहीं माने जाते — इलेक्ट्रॉन-प्रोटॉन-न्यूट्रॉन की खोज हुई है"],
 ["सूत्र लिखते समय धनायन पहले और ऋणायन बाद में रखें",
  "आण्विक द्रव्यमान के प्रश्न में परमाणु द्रव्यमान गुणा संख्या से जोड़ें"],
 ["'HONC-1234' — H=1, O=2, N=3, C=4 संयोजकता क्रम",
  "क्रॉस-विधि को तीर चिह्न से बनाकर याद रखें"],
 ["सूत्र लेखन और आण्विक द्रव्यमान के प्रश्न बार-बार आते हैं",
  "नियत अनुपात के नियम पर सीधे प्रश्न पूछे जाते हैं"],
 ["परमाणु और अणु में अंतर",
  "डाल्टन के सिद्धांत के बिंदु",
  "क्रॉस-विधि से सूत्र लेखन",
  "नियत अनुपात का नियम"],
 "परमाणु तत्व की मूल इकाई और अणु परमाणुओं का समूह है। डाल्टन के सिद्धांत अनुसार अभिक्रिया में परमाणु पुनर्व्यवस्थित होते हैं। संयोजकता से क्रॉस-विधि द्वारा सूत्र लिखे जाते हैं और शुद्ध यौगिक में तत्वों का द्रव्यमान अनुपात स्थिर रहता है।"),
 "en": N(
 "An atom is the smallest reactive unit of matter and a molecule is a group of two or more atoms. Dalton's atomic theory explained the laws of chemical combination. Knowing valency, we can write the chemical formula of any compound.",
 "Water's formula is H₂O because hydrogen has valency 1 and oxygen 2 — the criss-cross method gives the formula.",
 [("Atoms and Molecules", "An atom is the basic unit of an element; a molecule may form from atoms of the same or different elements (O₂, H₂O)."),
  ("Dalton's Theory", "Atoms are indivisible, neither created nor destroyed; in a reaction atoms only rearrange."),
  ("Valency and Ions", "Valency is combining capacity — H=1, O=2, N=3, C=4; cations lose electrons and anions gain them."),
  ("Formula Writing and Fixed Ratio", "Write formulae by the criss-cross method; a pure compound always has a fixed mass ratio of elements (law of constant proportion); molecular mass = sum of atomic masses.")],
 ["An atom is the smallest reactive unit of an element",
  "A molecule forms from same (O₂) or different atoms (H₂O)",
  "Main valencies — H(1), O(2), N(3), C(4)",
  "Cations are positive and anons are negative",
  "The law of constant proportion applies to pure compounds",
  "The molecular mass of water is 18 u"],
 ["Practise writing formulae of common compounds by the criss-cross method",
  "Learn symbol-valency pairs of common elements",
  "Do simple calculations of molecular mass"],
 ["Do not equate atoms with molecules — molecules are made of atoms",
  "Atoms are no longer considered indivisible today — electrons, protons and neutrons have been discovered"],
 ["While writing formulae, place the cation first and the anion later",
  "In molecular mass questions, add atomic masses multiplied by counts"],
 ["'HONC-1234' — the valency order of H, O, N, C",
  "Remember the criss-cross method with arrow marks"],
 ["Questions on formula writing and molecular mass come repeatedly",
  "The law of constant proportion is asked directly"],
 ["Difference between atom and molecule",
  "Points of Dalton's theory",
  "Formula writing by the criss-cross method",
  "Law of constant proportion"],
 "Atoms are the basic units of elements and molecules are groups of atoms. In reactions atoms rearrange per Dalton's theory. Formulae are written by the criss-cross method using valency, and pure compounds keep a fixed mass ratio of elements.")}))

CH.append(("chapter-06", "C06", 6, "परमाणु की संरचना", "Structure of the Atom",
"परमाणु के उपकण और परमाणु मॉडल।", "Subatomic particles and atomic models.",
{"hi": N(
 "परमाणु इलेक्ट्रॉन, प्रोटॉन और न्यूट्रॉन से बना है। थॉमसन, रदरफोर्ड और बोर के मॉडल ने क्रमशः परमाणु की संरचना की व्याख्या विकसित की। इलेक्ट्रॉन निश्चित कक्षाओं (शैलों) में रहते हैं और सबसे बाहरी कक्षा के इलेक्ट्रॉन (संयोजकता इलेक्ट्रॉन) रासायनिक गुण निर्धारित करते हैं।",
 "कार्बन (Z=6) की K शैल में 2 और L शैल में 4 इलेक्ट्रॉन होते हैं — इसी से उसकी संयोजकता 4 है।",
 [("उपपरमाणविक कण", "इलेक्ट्रॉन (−1, नगण्य द्रव्यमान), प्रोटॉन (+1, 1 u), न्यूट्रॉन (0, 1 u); परमाणु उदासीन होता है क्योंकि प्रोटॉन = इलेक्ट्रॉन।"),
  ("परमाणु मॉडल", "थॉमसन — पुडिंग मॉडल; रदरफोर्ड — नाभिक प्रतिरोधी प्रयोग से केंद्र में नाभिक; बोर — निश्चित कक्षाएँ।"),
  ("परमाणु संख्या एवं द्रव्यमान संख्या", "परमाणु संख्या Z = प्रोटॉन संख्या; द्रव्यमान संख्या A = प्रोटॉन + न्यूट्रॉन; संकेतन A/z X।"),
  ("समस्थानिक (आइसोटोप)", "समान Z भिन्न A — जैसे H-1, H-2, H-3; C-12, C-14; U-235 का उपयोग नाभिकीय ईंधन में और C-14 आयु-निर्धारण में होता है।")],
 ["परमाणु तीन उपकणों — इलेक्ट्रॉन, प्रोटॉन, न्यूट्रॉन से बना है",
  "परमाणु संख्या = प्रोटॉन संख्या = इलेक्ट्रॉन संख्या (उदासीन परमाणु)",
  "द्रव्यमान संख्या = प्रोटॉन + न्यूट्रॉन",
  "K शैल अधिकतम 2, L शैल 8 इलेक्ट्रॉन रख सकती है",
  "संयोजकता इलेक्ट्रॉन रासायनिक गुण तय करते हैं",
  "समस्थानिकों के रासायनिक गुण समान, भौतिक गुण भिन्न होते हैं"],
 ["परमाणु संख्या से इलेक्ट्रॉन विन्यास लिखने का अभ्यास करें",
  "मॉडलों की विशेषताएँ और उनकी कमियाँ जोड़कर याद करें",
  "समस्थानिकों के उपयोग रटें"],
 ["परमाणु वास्तव में अविभाज्य नहीं — यह डाल्टन की सीमा थी",
  "समान द्रव्यमान संख्या वाले परमाणु समान तत्व के नहीं होते — Z देखें"],
 ["विन्यास लिखते समय 2n² नियम (K=2, L=8, M=18) क्रम से भरें",
  "समस्थानिक पहचानने के लिए Z समान और A भिन्न देखें"],
 ["'EPN' — इलेक्ट्रॉन ऋण, प्रोटॉन धन, न्यूट्रॉन उदासीन",
  "K-2, L-8 को 'ट्रेन की दो डिब्बे' की तरह याद करें"],
 ["इलेक्ट्रॉन विन्यास और समस्थानिक पर प्रश्न बार-बार आते हैं",
  "रदरफोर्ड प्रयोग की निष्कर्ष पूछे जाते हैं"],
 ["तीन उपकणों के गुण",
  "परमाणु संख्या और द्रव्यमान संख्या",
  "इलेक्ट्रॉन विन्यास",
  "समस्थानिक और उनके उपयोग"],
 "परमाणु में नाभिक (प्रोटॉन-न्यूट्रॉन) और कक्षाओं में इलेक्ट्रॉन होते हैं। परमाणु संख्या प्रोटॉनों की संख्या और द्रव्यमान संख्या न्यूक्लियॉनों की संख्या है। बोर मॉडल की निश्चित कक्षाओं में इलेक्ट्रॉन व्यवस्थित रहते हैं और संयोजकता इलेक्ट्रॉन रासायनिक गुण निर्धारित करते हैं। समान परमाणु संख्या वाले समस्थानिक चिकित्सा, ऊर्जा औि आयु-निर्धारण में उपयोगी हैं।"),
 "en": N(
 "An atom is made of electrons, protons and neutrons. The models of Thomson, Rutherford and Bohr progressively explained atomic structure. Electrons occupy definite shells, and the outermost (valence) electrons decide chemical properties.",
 "Carbon (Z=6) has 2 electrons in the K shell and 4 in the L shell — hence its valency is 4.",
 [("Subatomic Particles", "Electron (−1, negligible mass), proton (+1, 1 u), neutron (0, 1 u); an atom is neutral because protons = electrons."),
  ("Atomic Models", "Thomson — pudding model; Rutherford — nucleus from the scattering experiment; Bohr — fixed orbits."),
  ("Atomic Number and Mass Number", "Atomic number Z = number of protons; mass number A = protons + neutrons; notation A/Z X."),
  ("Isotopes", "Same Z, different A — e.g. H-1, H-2, H-3; C-12, C-14; U-235 is used as nuclear fuel and C-14 in age determination.")],
 ["An atom has three particles — electron, proton, neutron",
  "Atomic number = protons = electrons (neutral atom)",
  "Mass number = protons + neutrons",
  "The K shell holds at most 2 electrons, the L shell 8",
  "Valence electrons decide chemical properties",
  "Isotopes have similar chemical but different physical properties"],
 ["Practise writing electron configurations from atomic number",
  "Learn features and drawbacks of each model together",
  "Memorise uses of isotopes"],
 ["Atoms are not truly indivisible — that was Dalton's limitation",
  "Atoms with the same mass number need not belong to the same element — check Z"],
 ["Fill shells in the 2n² order (K=2, L=8, M=18) while writing configurations",
  "To identify isotopes, look for same Z with different A"],
 ["'EPN' — Electron negative, Proton positive, Neutron neutral",
  "Remember K-2, L-8 like 'two coaches of a train'"],
 ["Questions on electron configuration and isotopes come repeatedly",
  "Conclusions of Rutherford's experiment are asked"],
 ["Properties of the three particles",
  "Atomic number and mass number",
  "Electron configuration",
  "Isotopes and their uses"],
 "An atom has a nucleus (protons-neutrons) with electrons in shells. Atomic number counts protons and mass number counts nucleons. Bohr's fixed orbits arrange electrons, and valence electrons decide chemical behaviour. Isotopes with the same atomic number serve medicine, energy and age-dating.")}))

CH.append(("chapter-07", "C07", 7, "रासायनिक अभिक्रियाएँ एवं समीकरण", "Chemical Reactions & Equations",
"समीकरण लेखन, संतुलन और अभिक्रिया प्रकार।", "Writing and balancing equations, and types of reactions.",
{"hi": N(
 "रासायनिक अभिक्रिया में अभिकारक नए उत्पाद में बदलते हैं और इसे संतुलित रासायनिक समीकरण से दर्शाया जाता है जिसमें दोनों ओर प्रत्येक तत्व के परमाणु समान होते हैं। अभिक्रियाएँ संयोजन, अपघटन, विस्थापन और द्विविस्थापन प्रकारों में बाँटी जाती हैं।",
 "चूने के पानी में CO₂ डालने पर दूधिया होना (CaCO₃) अभिक्रिया होने का संकेत है।",
 [("समीकरण लेखन एवं संतुलन", "अभिकारक → उत्पाद; द्रव्यमान संरक्षण के अनुसार दोनों पक्षों के परमाणु बराबर रखना आवश्यक है।"),
  ("संयोजन एवं अपघटन", "संयोजन में दो पदार्थ मिलकर एक बनते हैं (CaO + H₂O → Ca(OH)₂); अपघटन में एक पदार्थ टूटता है (CaCO₃ → CaO + CO₂)।"),
  ("विस्थापन एवं द्विविस्थापन", "अधिक क्रियाशील तत्व कम क्रियाशील को हटाता है (Fe + CuSO₄); द्विविस्थापन में आयनों का आदान-प्रदान होता है (AgNO₃ + NaCl → AgCl)।"),
  ("उष्माक्षेपी-उष्माशोषी, ऑक्सीकरण-अपचयन", "ऊर्जा उत्सर्जन/अवशोषण; ऑक्सीजन प्राप्ति = ऑक्सीकरण, हानि = अपचयन; जंग और मोचन इसी के उदाहरण हैं।")],
 ["संतुलित समीकरण में दोनों ओर परमाणु संख्या समान होती है",
  "अभिक्रिया के संकेत — रंग परिवर्तन, गैस, अवक्षेप, ताप परिवर्तन",
  "संयोजन: A + B → AB; अपघटन: AB → A + B",
  "विस्थापन में क्रियाशीलता क्रम महत्वपूर्ण है",
  "द्विविस्थापन में अवक्षेप प्रायः बनता है",
  "जीवन-प्रक्रियाएँ जैसे पाचन भी रासायनिक अभिक्रियाएँ हैं"],
 ["द्रव्यमान संरक्षण के अनुसार सरल समीकरण संतुलित करने का अभ्यास करें",
  "चारों प्रकारों के एक-एक उदाहरण रटें",
  "ऑक्सीकरण-अपचयन की परिभाषा स्पष्ट रखें"],
 ["तीर (→) के स्थान पर बराबर (=) न लिखें",
  "सभी अभिक्रियाएँ उष्माक्षेपी नहीं होतीं — कुछ उष्माशोषी होती हैं"],
 ["कोई पदार्थ ऑक्सीजन/हाइड्रोजन का आदान-प्रदान दिखाए तो रेडॉक्स सोचें",
  "दो विलयन मिलकर अवक्षेप दें तो द्विविस्थापन चुनें"],
 ["संयोजन = 'जोड़ा' (join), अपघटन = 'टुकड़े' (break) — नाम से अर्थ याद रखें",
  "'OIL RIG' — Oxidation Is Loss, Reduction Is Gain (इलेक्ट्रॉन)"],
 ["अभिक्रिया प्रकार पहचानने के प्रश्न बार-बार आते हैं",
  "समीकरण संतुलन परीक्षा का सामान्य प्रश्न है"],
 ["संतुलित समीकरण की शर्त",
  "अभिक्रिया के चार प्रकार और उदाहरण",
  "ऑक्सीकरण-अपचयन की परिभाषा",
  "अभिक्रिया के संकेत"],
 "रासायनिक अभिक्रिया में अभिकारक उत्पाद में बदलते हैं और द्रव्यमान संरक्षण के अनुसार समीकरण संतुलित किया जाता है। अभिक्रियाएँ संयोजन, अपघटन, विस्थापन और द्विविस्थापन श्रेणियों में होती हैं। ऑक्सीकरण-अपचयन और उष्मा परिवर्तन भी अभिक्रिया के महत्वपूर्ण पहलू हैं।"),
 "en": N(
 "In a chemical reaction reactants change into new products, shown by a balanced chemical equation where atoms of every element are equal on both sides. Reactions are classified as combination, decomposition, displacement and double displacement.",
 "Lime water turning milky (CaCO₃) on passing CO₂ is a sign of a reaction.",
 [("Writing and Balancing", "Reactants → products; by conservation of mass, atoms on both sides must be equal."),
  ("Combination and Decomposition", "In combination two substances form one (CaO + H₂O → Ca(OH)₂); in decomposition one breaks (CaCO₃ → CaO + CO₂)."),
  ("Displacement and Double Displacement", "A more reactive element displaces a less reactive one (Fe + CuSO₄); in double displacement ions exchange (AgNO₃ + NaCl → AgCl)."),
  ("Exothermic-Endothermic, Oxidation-Reduction", "Energy release or absorption; gain of oxygen = oxidation, loss = reduction; rusting and corrosion are examples.")],
 ["In a balanced equation atom counts are equal on both sides",
  "Signs of reaction — colour change, gas, precipitate, temperature change",
  "Combination: A + B → AB; decomposition: AB → A + B",
  "Reactivity order matters in displacement",
  "Double displacement usually forms a precipitate",
  "Life processes like digestion are also chemical reactions"],
 ["Practise balancing simple equations by conservation of mass",
  "Learn one example each of the four types",
  "Keep the definitions of oxidation-reduction clear"],
 ["Do not use '=' in place of the arrow (→)",
  "Not all reactions are exothermic — some absorb heat"],
 ["Oxygen/hydrogen transfer points to redox",
  "Two solutions giving a precipitate point to double displacement"],
 ["Combination = join, decomposition = break — remember by name",
  "'OIL RIG' — Oxidation Is Loss, Reduction Is Gain of electrons"],
 ["Identifying reaction types is asked repeatedly",
  "Balancing equations is a common exam task"],
 ["Condition of a balanced equation",
  "Four reaction types with examples",
  "Definition of oxidation-reduction",
  "Signs of a reaction"],
 "In chemical reactions reactants become products and equations are balanced by conservation of mass. Reactions are of combination, decomposition, displacement and double displacement types. Oxidation-reduction and heat changes are also key aspects.")}))

CH.append(("chapter-08", "C08", 8, "अम्ल, क्षार, लवण एवं सूचक", "Acids, Bases, Salts & Indicators",
"अम्ल-क्षार की पहचान, उदासीनीकरण और pH।", "Identifying acids-bases, neutralisation and pH.",
{"hi": N(
 "अम्ल खट्टे स्वाद वाले पदार्थ हैं जो जल में घुलकर H⁺ आयन देते हैं, जबकि क्षार कड़वे होते हैं और OH⁻ आयन देते हैं। सूचक (लिटमस, टर्मेरिक, फिनॉल्फथैलीन) अम्ल-क्षार की पहचान कराते हैं। अम्ल और क्षार की अभिक्रिया से लवण और जल बनता है — उदासीनीकरण।",
 "चींटी के काटने पर नमीन (फार्मिक अम्ल) के प्रभाव को बेकिंग सोडा लगाकर उदासीन किया जाता है।",
 [("अम्ल एवं क्षार", "अम्ल — नींबू (साइट्रिक), विनegar (एसीटिक), HCl; क्षार — साबुन, चूना, NaOH; दोनों जलीय विलयन में आयन देते हैं।"),
  ("सूचक", "प्राकृतिक — लिटमस, टर्मेरिक, चुकंदर का रस; संश्लिष्ट — मेथिल ऑरेंज, फिनॉल्फथैलीन; गंधहीन वाष्पीकरण से लिटमस कागज बनता है।"),
  ("उदासीनीकरण एवं pH", "अम्ल + क्षार → लवण + जल; pH पैमाना 0–14 — 7 उदासीन, 7 से कम अम्लीय, अधिक क्षारीय; पाचन में HCl और एंटासिड का सिद्धांत इसी पर है।"),
  ("दैनिक जीवन के लवण", "सोडियम बाइकार्बोनेट (बेकिंग सोडा), सोडियम कार्बोनेट (धोने का सोडा), कैल्शियम सल्फेट (प्लास्टर ऑफ पेरिस), अमोनियम हाइड्रॉक्साइड-सोडा वोटर शीतल पेय।")],
 ["अम्ल H⁺ और क्षार OH⁻ आयन देते हैं",
  "अम्ल नीले लिटमस को लाल, क्षार लाल को नीला करते हैं",
  "उदासीनीकरण: अम्ल + क्षार → लवण + जल",
  "pH 7 उदासीन, <7 अम्लीय, >7 क्षारीय",
  "सूचक प्राकृतिक और संश्लिष्ट दोनों प्रकार के होते हैं",
  "बेकिंग सोडा NaHCO₃ और धोने का सोडा Na₂CO₃ है"],
 ["pH पैमाने की दिशा और उदाहरण याद रखें",
  "प्राकृतिक सूचकों के नाम और रंग परिवर्तन रटें",
  "दैनिक लवणों के रासायनिक नाम और उपयोग जोड़कर याद करें"],
 ["सभी खट्टे पदार्थ खतरनाक अम्ल नहीं — नींबू का साइट्रिक अम्ल कमजोर अम्ल है",
  "क्षार और क्षारीय विलयन में अंतर है — प्रत्येक क्षार विलेय नहीं होता"],
 ["रंग परिवर्तन का प्रश्न हो तो पहले अम्ल/क्षार पहचानें",
  "pH का प्रश्न हो तो 7 की तुलना करें"],
 ["'BLUE-BASE' — क्षार नीला करता है लाल लिटमस को",
  "pH पैमाने को 0-7-14 सीढ़ी बनाकर याद करें"],
 ["लिटमस परिवर्तन और pH पर सीधे प्रश्न आते हैं",
  "बेकिंग सोडा और धोने का सोडा अक्सर पूछे जाते हैं"],
 ["अम्ल-क्षार की परिभाषा",
  "सूचक और रंग परिवर्तन",
  "उदासीनीकरण अभिक्रिया",
  "pH पैमाना और दैनिक लवण"],
 "अम्ल H⁺ तथा क्षार OH⁻ आयन देते हैं और सूचक इनकी पहचान कराते हैं। अम्ल-क्षार की अभिक्रिया से लवण और जल बनता है। pH पैमाना 0–14 पर अम्लीयता-क्षारीयता बताता है। बेकिंग सोडा, धोने का सोडा और प्लास्टर ऑफ पेरिस दैनिक जीवन के महत्वपूर्ण लवण हैं।"),
 "en": N(
 "Acids are sour substances that give H⁺ ions in water, while bases are bitter and give OH⁻ ions. Indicators (litmus, turmeric, phenolphthalein) identify acids and bases. Acid-base reaction gives salt and water — neutralisation.",
 "The effect of formic acid from an ant bite is neutralised by applying baking soda.",
 [("Acids and Bases", "Acids — lemon (citric), vinegar (acetic), HCl; bases — soap, lime, NaOH; both give ions in aqueous solution."),
  ("Indicators", "Natural — litmus, turmeric, beetroot juice; synthetic — methyl orange, phenolphthalein."),
  ("Neutralisation and pH", "Acid + base → salt + water; the pH scale is 0–14 — 7 neutral, below 7 acidic, above 7 basic; antacids work on this principle."),
  ("Salts in Daily Life", "Sodium bicarbonate (baking soda), sodium carbonate (washing soda), calcium sulphate (plaster of Paris), soda water cool drinks.")],
 ["Acids give H⁺ and bases give OH⁻ ions",
  "Acids turn blue litmus red; bases turn red litmus blue",
  "Neutralisation: acid + base → salt + water",
  "pH 7 neutral, <7 acidic, >7 basic",
  "Indicators are of natural and synthetic types",
  "Baking soda is NaHCO₃ and washing soda is Na₂CO₃"],
 ["Remember the pH scale direction with examples",
  "Learn names of natural indicators and their colour changes",
  "Memorise chemical names and uses of daily salts"],
 ["Not all sour substances are dangerous acids — citric acid in lemon is weak",
  "Base and alkaline solution differ — not every base is soluble"],
 ["For colour-change questions, first identify acid or base",
  "For pH questions, compare with 7"],
 ["'BLUE-BASE' — a base turns red litmus blue",
  "Remember the pH scale as a 0-7-14 ladder"],
 ["Direct questions on litmus change and pH are common",
  "Baking soda and washing soda are frequently asked"],
 ["Definitions of acid and base",
  "Indicators and colour changes",
  "Neutralisation reaction",
  "pH scale and daily salts"],
 "Acids give H⁺ and bases give OH⁻ ions; indicators identify them. Acid-base reaction gives salt and water. The 0–14 pH scale shows acidity-alkalinity. Baking soda, washing soda and plaster of Paris are important daily-life salts.")}))

CH.append(("chapter-09", "C09", 9, "धातुएँ एवं अधातुएँ", "Metals & Non-metals",
"धातु-अधातु गुण, क्रियाशीलता श्रेणी और मिश्र धातु।", "Properties of metals-non-metals, reactivity series and alloys.",
{"hi": N(
 "धातुएँ चमकदार, तन्य, आघातवर्धनीय और ऊष्मा-विद्युत की सुचालक होती हैं, जबकि अधातुएँ भंगुर और असंवाहक होती हैं। क्रियाशीलता श्रेणी बताती है कि कौन-सी धातु किसको विलयन से विस्थापित कर सकती है। धातुओं से अयस्क निष्कर्षण और मिश्र धातु निर्माण महत्वपूर्ण औद्योगिक प्रक्रियाएँ हैं।",
 "लोहे की कील ताँबे के सल्फेट विलयन में डालने पर नीला रंग हल्का हरा हो जाता है — विस्थापन अभिक्रिया।",
 [("धातुओं एवं अधातुओं के गुण", "धातुएँ — चमक, तन्यता, आघातवर्धनीयता, संवाहकता; अधातुएँ — भंगुरता, अचालकता, बिना चमक (ग्रेफाइट अपवाद)।"),
  ("क्रियाशीलता श्रेणी", "K > Na > Ca > Mg > Al > Zn > Fe > Pb > Cu > Ag > Au; उच्च श्रेणी की धातु निम्न को विस्थापित करती है।"),
  ("धातुओं का निष्कर्षण", "अयस्क से अपचयन द्वारा; भर्जन (रोस्टिंग) और निक्षालन (कैल्सीनेशन) पूर्व-प्रक्रियाएँ; उदाहरण — हेमेटाइट से लोहा।"),
  ("मिश्र धातुएँ एवं जंग", "पीतल (Cu+Zn), स्टील (Fe+C), स्टेनलेस स्टील (Fe+Cr+Ni); मिश्र धातुएँ कठोरता-संक्षारण प्रतिरोध बढ़ाती हैं; जंग ऑक्सीकरण से बचाव — रंगना, गैल्वनाइज़िंग।")],
 ["धातुएँ चमकदार, तन्य और सुचालक होती हैं",
  "अधातुएँ भंगुर और असंवाहक होती हैं",
  "क्रियाशीलता श्रेणी में सोना सबसे निष्क्रिय धातुओं में है",
  "विस्थापन अभिक्रिया क्रियाशीलता श्रेणी पर आधारित है",
  "पीतल = ताँबा + जस्ता; स्टेनलेस स्टील = लोहा + क्रोमियम + निकल",
  "जंग लोहे का ऑक्सीकरण है"],
 ["क्रियाशीलता श्रेणी का क्रम रटें",
  "प्रमुख मिश्र धातुओं के घटक और उपयोग याद रखें",
  "विस्थापन अभिक्रिया के उदाहरण समझें"],
 ["सभी चमकदार पदार्थ धातु नहीं — आईसीन (iodine) चमकदार अधातु है",
  "ग्रेफाइट अधातु होकर भी विद्युत सुचालक है"],
 ["विस्थापन का प्रश्न हो तो श्रेणी में ऊपर की धातु को चुनें",
  "मिश्र धातु के घटक पूछे जाएँ तो नाम-जोड़े याद करें"],
 ["'KNa-Ca-Mg-Al-Zn-Fe-Pb-Cu-Ag-Au' क्रम को गाने की तरह दोहराएँ",
  "'पीतल में पीतल नहीं — ताँबा-जस्ता' वाक्य से भ्रम दूर करें"],
 ["मिश्र धातुओं के घटक और विस्थापन अभिक्रिया परीक्षा में बार-बार आते हैं",
  "धातु-अधातु गुणों की तुलना सामान्य प्रश्न है"],
 ["धातु-अधातु गुण",
  "क्रियाशीलता श्रेणी और विस्थापन",
  "अयस्क से धातु निष्कर्षण की रूपरेखा",
  "प्रमुख मिश्र धातुएँ और जंग से बचाव"],
 "धातुएँ चमकदार, तन्य, सुचालक होती हैं और अधातुएँ भंगुर असंवाहक। क्रियाशीलता श्रेणी विस्थापन अभिक्रिया का आधार है। अयस्कों से अपचयन द्वारा धातुएँ निकाली जाती हैं। पीतल, स्टील जैसी मिश्र धातुएँ गुण सुधारती हैं और गैल्वनाइज़िंग-रंगने से जंग से बचा जाता है।"),
 "en": N(
 "Metals are lustrous, ductile, malleable and good conductors of heat and electricity, while non-metals are brittle and non-conductors. The reactivity series tells which metal can displace another from its solution. Extraction of metals from ores and alloy making are important industrial processes.",
 "An iron nail dropped in copper sulphate solution turns the blue colour light green — a displacement reaction.",
 [("Properties of Metals and Non-metals", "Metals — lustre, ductility, malleability, conductivity; non-metals — brittleness, non-conductivity, no lustre (graphite an exception)."),
  ("Reactivity Series", "K > Na > Ca > Mg > Al > Zn > Fe > Pb > Cu > Ag > Au; a higher metal displaces a lower one."),
  ("Extraction of Metals", "Reduction of ores; roasting and calcination are preliminary steps; example — iron from haematite."),
  ("Alloys and Rusting", "Brass (Cu+Zn), steel (Fe+C), stainless steel (Fe+Cr+Ni); alloys improve hardness and corrosion resistance; rusting is prevented by painting and galvanising.")],
 ["Metals are lustrous, ductile and conductors",
  "Non-metals are brittle and non-conductors",
  "Gold is among the least reactive metals in the series",
  "Displacement reactions follow the reactivity series",
  "Brass = copper + zinc; stainless steel = iron + chromium + nickel",
  "Rusting is oxidation of iron"],
 ["Learn the order of the reactivity series",
  "Remember components and uses of common alloys",
  "Understand examples of displacement reactions"],
 ["Not every lustrous substance is a metal — iodine is a lustrous non-metal",
  "Graphite is a non-metal yet conducts electricity"],
 ["For displacement questions, choose the metal higher in the series",
  "For alloy components, recall the name-pairs"],
 ["Repeat the series K-Na-Ca-Mg-Al-Zn-Fe-Pb-Cu-Ag-Au like a rhyme",
  "'Brass has no brass — it is copper-zinc' clears the confusion"],
 ["Alloy components and displacement reactions are asked repeatedly",
  "Comparing metal-non-metal properties is a common question"],
 ["Properties of metals and non-metals",
  "Reactivity series and displacement",
  "Outline of metal extraction from ores",
  "Common alloys and rust prevention"],
 "Metals are lustrous, ductile conductors; non-metals are brittle insulators. The reactivity series governs displacement. Metals are extracted from ores by reduction. Alloys like brass and steel improve properties, and painting or galvanising prevents rusting.")}))

CH.append(("chapter-10", "C10", 10, "कार्बन एवं उसके यौगिक", "Carbon & Its Compounds",
"कार्बन की बंधन क्षमता, समपरमाणुकता और उपयोगी यौगिक।", "Bonding capacity of carbon, allotropy and useful compounds.",
{"hi": N(
 "कार्बन चतुष्कोणीय (टेट्रावैलेंट) तत्व है जो शृंखल और जाल बनाकर असंख्य यौगिक रचता है — यही उसकी श्रेष्ठता का कारण है। हीरा, ग्रेफाइट और फुलरीन उसके समपरमाणुक (एलोट्रोप) रूप हैं। इथेनॉल और इथेनोइक अम्ल जैसे यौगिक तथा साबुन-डिटर्जेंट की क्रिया दैनिक जीवन से जुड़े हैं।",
 "हीरा और ग्रेफाइट दोनों कार्बन के ही रूप हैं पर हीरा सबसे कठोर और ग्रेफाइट मुलायम पदार्थ है — संरचना का अंतर।",
 [("कार्बन की बंधन क्षमता", "टेट्रावैलेंसी और शृंखलन (catenation) से लंबी शृंखलाएँ, शाखाएँ और वलय बनते हैं; सहसंयोजी बंधन।"),
  ("कार्बन के समपरमाणुक रूप", "हीरा — त्रिविम जाल, सबसे कठोर; ग्रेफाइट — परतदार, विद्युत चालक, मुलायम; फुलरीन — गोलाकार अणु।"),
  ("कार्बन यौगिकों के वर्ग", "हाइड्रोकार्बन (संतृप्त-असंतृप्त), कार्यात्मक समूह (एल्कोहॉल -OH, अम्ल -COOH), समजातीय श्रेणी की अवधारणा।"),
  ("इथेनॉल, इथेनोइक अम्ल एवं साबुन", "इथेनॉल C₂H₅OH — विलायक; इथेनोइक अम्ल CH₃COOH — सिरका; साबुन जल कपट पर लंबे शृंखला अणुओं से मैल हटाते हैं।")],
 ["कार्बन की संयोजकता 4 है",
  "कार्बन सहसंयोजी बंधन बनाता है",
  "हीरा और ग्रेफाइट कार्बन के समपरमाणुक रूप हैं",
  "संतृप्त हाइड्रोकार्बन एकल और असंतृप्त द्वि/त्रि-बंध रखते हैं",
  "-OH कार्यात्मक समूह एल्कोहॉल और -COOH अम्ल दर्शाता है",
  "साबुन की सफाई क्रिया माइसील बनाने पर आधारित है"],
 ["समपरमाणुक रूपों के गुण तुलनात्मक रूप से याद करें",
  "कार्यात्मक समूहों के सूत्र और उदाहरण जोड़ें",
  "साबुन-डिटर्जेंट की क्रिया की मूल बात समझें"],
 ["हीरा और ग्रेफाइट को अलग तत्व न मानें — दोनों कार्बन के रूप हैं",
  "सभी कार्बन यौगिक संवाहक नहीं — अधिकांश असंवाहक होते हैं (ग्रेफाइट अपवाद)"],
 ["बंधों की संख्या पूछी जाए तो संतृप्त/असंतृप्त पहचानें",
  "काठोरता/चालकता का प्रश्न हो तो संरचना (जाल बनाम परत) देखें"],
 ["'C की 4 बांह' — चार बंधन बनाने की क्षमता याद रखें",
  "हीरा = जाल (network), ग्रेफाइट = परत (layers) — जोड़ी दोहराएँ"],
 ["समपरमाणुक रूपों की तुलना और कार्यात्मक समूह परीक्षा में आते हैं",
  "साबुन की क्रिया पर प्रश्न पूछा जाता है"],
 ["कार्बन की टेट्रावैलेंसी और शृंखलन",
  "हीरा-ग्रेफाइट के गुण",
  "कार्यात्मक समूह",
  "साबुन की सफाई क्रिया"],
 "कार्बन की चार संयोजकता और शृंखलन क्षमता उसे असंख्य यौगिक बनाने देती है। हीरा, ग्रेफाइट और फुलरीन उसके समपरमाणुक रूप हैं। कार्यात्मक समूहों से यौगिकों का वर्गीकरण होता है और इथेनॉल-इथेनोइक अम्ल तथा साबुन दैनिक जीवन के महत्वपूर्ण कार्बन यौगिक हैं।"),
 "en": N(
 "Carbon is a tetravalent element that forms chains and networks to create countless compounds — the reason for its versatility. Diamond, graphite and fullerene are its allotropes. Compounds like ethanol and ethanoic acid, and the action of soaps and detergents, connect to daily life.",
 "Diamond and graphite are both forms of carbon, yet diamond is the hardest and graphite soft — a difference of structure.",
 [("Bonding Capacity of Carbon", "Tetravalency and catenation create long chains, branches and rings; bonds are covalent."),
  ("Allotropes of Carbon", "Diamond — 3-D network, hardest; graphite — layered, electric conductor, soft; fullerene — spherical molecules."),
  ("Classes of Carbon Compounds", "Hydrocarbons (saturated-unsaturated), functional groups (alcohol -OH, acid -COOH), the idea of homologous series."),
  ("Ethanol, Ethanoic Acid and Soap", "Ethanol C₂H₅OH — solvent; ethanoic acid CH₃COOH — vinegar; soap cleans by forming micelles in water.")],
 ["Carbon has valency 4",
  "Carbon forms covalent bonds",
  "Diamond and graphite are allotropes of carbon",
  "Saturated hydrocarbons have single bonds; unsaturated have double/triple",
  "The -OH group marks alcohols and -COOH marks acids",
  "Soap cleans by forming micelles"],
 ["Learn the properties of allotropes comparatively",
  "Link functional group formulae with examples",
  "Understand the basics of soap-detergent action"],
 ["Do not treat diamond and graphite as different elements — both are carbon",
  "Most carbon compounds are non-conductors (graphite is the exception)"],
 ["For bond-count questions, identify saturated vs unsaturated",
  "For hardness/conductivity, look at the structure (network vs layers)"],
 ["'C has 4 hands' — remember the four-bond capacity",
  "Diamond = network, graphite = layers — repeat the pair"],
 ["Comparing allotropes and functional groups appears in exams",
  "The action of soap is a common question"],
 ["Tetravalency and catenation of carbon",
  "Properties of diamond-graphite",
  "Functional groups",
  "Cleansing action of soap"],
 "Carbon's four-valency and catenation let it form countless compounds. Diamond, graphite and fullerene are its allotropes. Functional groups classify compounds, while ethanol, ethanoic acid and soap are important carbon compounds of daily life.")}))

CH.append(("chapter-11", "C11", 11, "वायु, जल एवं पर्यावरणीय रसायन", "Air, Water & Environmental Chemistry",
"वायु-जल की संरचना, प्रदूषण और शुद्धिकरण।", "Composition of air-water, pollution and purification.",
{"hi": N(
 "वायु गैसों का मिश्रण है — नाइट्रोजन लगभग 78%, ऑक्सीजन 21% और शेष CO₂, आर्गन आदि। जल विलायक के रूप में अद्वितीय है पर प्राकृतिक जल में अशुद्धियाँ होती हैं जिन्हें विभिन्न विधियों से दूर किया जाता है। वायु-जल प्रदूषण और ग्रीनहाउस प्रभाव आधुनिक पर्यावरणीय चिंताएँ हैं।",
 "चूने के पानी पर फूँक मारने पर दूधिया सफेद होना CO₂ की उपस्थिति का परीक्षण है।",
 [("वायु की संरचना", "N₂ 78%, O₂ 21%, Ar 0.9%, CO₂ 0.03% और जलवाष्प; ऑक्सीजन दहन के लिए आवश्यक है।"),
  ("जल एवं उसकी शुद्धि", "जल सार्वत्रिक विलायक है; निस्पंदन, क्लोरीनीकरण, उबालना और आसवन से शुद्धिकरण; खनिज-जल vs मृदु जल।"),
  ("जल प्रदूषण", "गृह-औद्योगिक अपशिष्ट और उर्वरक जल को प्रदूषित करते हैं; जलजनित रोगों से बचाव शुद्ध जल से होता है।"),
  ("वायु प्रदूषण एवं ग्रीनहाउस प्रभाव", "CO, SO₂, NOₓ और पार्टिकुलेट द्वारा वायु प्रदूषण; CO₂-मेथेन ग्रीनहाउस प्रभाव और वैश्विक तापन बढ़ाते हैं; ओजोन क्षय CFC से होता है।")],
 ["वायु में N₂ सर्वाधिक (78%) और O₂ दूसरे स्थान पर (21%) है",
  "ऑक्सीजन दहन में सहायक, CO₂ दहन में सहायक नहीं",
  "जल 'सार्वत्रिक विलायक' कहलाता है",
  "क्लोरीनीकरण जीवाणुनाशक शुद्धिकरण विधि है",
  "ग्रीनहाउस गैसें — CO₂, मेथेन, जलवाष्प",
  "CFC ओजोस्फीयर को हानि पहुँचाते हैं"],
 ["वायु के प्रतिशत घटक रटें",
  "जल शुद्धिकरण विधियों के उदाहरण जोड़ें",
  "ग्रीनहाउस गैसों और ओजोन क्षय के कारण याद रखें"],
 ["वायु में ऑक्सीजन सर्वाधिक है ऐसा नहीं — नाइट्रोजन सर्वाधिक है",
  "भारी जल और कठोर जल भिन्न अवधारणाएँ हैं"],
 ["दहन का प्रश्न हो तो ऑक्सीजन की भूमिका देखें",
  "वैश्विक तापन का कारण पूछा जाए तो ग्रीनहाउस गैसें चुनें"],
 ["'78-21-1' नियम — N₂, O₂, शेष गैसें",
  "'GGC' — Greenhouse gases: CO₂, CH₄, H₂O वाष्प"],
 ["वायु की संरचना के प्रतिशत सीधे पूछे जाते हैं",
  "ओजोन क्षय और ग्रीनहाउस प्रभाव पर प्रश्न आम हैं"],
 ["वायु के प्रमुख घटक और प्रतिशत",
  "जल शुद्धिकरण की विधियाँ",
  "जल प्रदूषण के स्रोत",
  "ग्रीनहाउस प्रभाव और ओजोन क्षय"],
 "वायु मुख्यतः नाइट्रोजन (78%) और ऑक्सीजन (21%) का मिश्रण है। जल सार्वत्रिक विलायक है जिसे निस्पंदन-क्लोरीनीकरण-आसवन से शुद्ध किया जाता है। अपशिष्ट से जल प्रदूषण और CO, SO₂ से वायु प्रदूषण होता है। ग्रीनहाउस गैसें वैश्विक तापन और CFC ओजोन क्षय करते हैं।"),
 "en": N(
 "Air is a mixture of gases — about 78% nitrogen, 21% oxygen and the rest CO₂, argon etc. Water is a unique solvent but natural water carries impurities removed by various methods. Air-water pollution and the greenhouse effect are modern environmental concerns.",
 "Blowing air through lime water turns it milky white — the test for CO₂.",
 [("Composition of Air", "N₂ 78%, O₂ 21%, Ar 0.9%, CO₂ 0.03% and water vapour; oxygen supports combustion."),
  ("Water and its Purification", "Water is the universal solvent; purification by filtration, chlorination, boiling and distillation; mineral vs soft water."),
  ("Water Pollution", "Household-industrial waste and fertilisers pollute water; protection from water-borne diseases needs pure water."),
  ("Air Pollution and Greenhouse Effect", "CO, SO₂, NOₓ and particulates pollute air; CO₂-methane raise the greenhouse effect and global warming; CFCs deplete ozone.")],
 ["Air has the most N₂ (78%) and O₂ second (21%)",
  "Oxygen supports combustion; CO₂ does not",
  "Water is called the 'universal solvent'",
  "Chlorination is a germicidal purification method",
  "Greenhouse gases — CO₂, methane, water vapour",
  "CFCs harm the ozone layer"],
 ["Learn the percentage composition of air",
  "Link water-purification methods with examples",
  "Remember causes of the greenhouse effect and ozone depletion"],
 ["Nitrogen, not oxygen, is the most abundant gas in air",
  "Heavy water and hard water are different concepts"],
 ["For combustion questions, note oxygen's role",
  "For global warming, choose greenhouse gases"],
 ["The '78-21-1' rule — N₂, O₂, remaining gases",
  "'GGC' — greenhouse gases: CO₂, CH₄, water vapour"],
 ["Percentage composition of air is asked directly",
  "Ozone depletion and the greenhouse effect are common questions"],
 ["Main components and percentages of air",
  "Methods of water purification",
  "Sources of water pollution",
  "Greenhouse effect and ozone depletion"],
 "Air is mainly a mixture of nitrogen (78%) and oxygen (21%). Water, the universal solvent, is purified by filtration, chlorination and distillation. Waste pollutes water while CO and SO₂ pollute air. Greenhouse gases cause global warming and CFCs deplete ozone.")}))

CH.append(("chapter-12", "C12", 12, "ईंधन, दहन एवं दैनिक जीवन का रसायन", "Fuels, Combustion & Everyday Chemistry",
"दहन के प्रकार, ईंधन की कैलोरीफिक मान और स्वच्छ ऊर्जा।", "Types of combustion, calorific value of fuels and clean energy.",
{"hi": N(
 "दहन एक रासायनिक प्रक्रिया है जिसमें पदार्थ ऑक्सीजन में जलकर ऊष्मा-प्रकाश देते हैं। ईंधन की गुणवत्ता उसके कैलोरीफिक मान (kJ/kg) से मापी जाती है। ईंधन जलने से उत्पन्न प्रदूषक और उनके स्वच्छ विकल्प परीक्षा का महत्वपूर्ण भाग हैं।",
 "मोमबत्ती की लौ में नीला क्षेत्र अपूर्ण दहन और चमकीला पीला क्षेत्र अपूर्ण दहन से बने कार्बन कणों से जलता है।",
 [("दहन एवं उसके प्रकार", "दहन के लिए ऑक्सीजन आवश्यक; तीव्र (ज्वाला), अपूर्ण (कालिख), स्वतः दहन (फास्फोरस)।"),
  ("लौ की संरचना", "मोमबत्ती की लौ के क्षेत्र — सबसे गर्म नीला भाग तल के पास; पीला चमकीला भाग अपूर्ण दहन का।"),
  ("ईंधन एवं कैलोरीफिक मान", "ईष्टम ईंधन के गुण — उच्च कैलोरीफिक मान, कम धुआँ, सस्ता, सुरक्षित; हाइड्रोजन का कैलोरीफिक मान उच्च पर भंडारण कठिन।"),
  ("प्रदूषण एवं स्वच्छ विकल्प", "कोयला-पेट्रोल जलने से SO₂, CO, CO₂ और राख; CNG-LPG स्वच्छ; ऊर्जा संरक्षण और नवीकरणीय विकल्प आवश्यक।")],
 ["दहन के लिए तीन आवश्यकताएँ — ज्वनशील पदार्थ, ऑक्सीजन, ज्वलन ताप",
  "अपूर्ण दहन से CO और कालिख बनती है",
  "कैलोरीफिक मान = प्रति किग्रा ईंधन से प्राप्त ऊष्मा (kJ/kg)",
  "हाइड्रोजन का कैलोरीफिक मान लगभग 150 kJ/g है",
  "CNG और LPG पेट्रोल-कोयले से स्वच्छ ईंधन हैं",
  "जीवाश्म ईंधन अनवीनीकरणीय हैं"],
 ["लौ के क्षेत्रों का ताप-क्रम याद रखें",
  "आदर्श ईंधन के गुण गिनकर लिखें",
  "प्रदूषक गैसों और उनके स्रोत के जोड़े बनाएँ"],
 ["सभी जलना दहन नहीं — जंग लगना धीमा ऑक्सीकरण है",
  "CO₂ विषैली नहीं है पर CO घातक है — दोनों को न मिलाएँ"],
 ["'धुआँ/कालिख' का उल्लेख मिले तो अपूर्ण दहन चुनें",
  "स्वच्छ ईंधन का प्रश्न हो तो CNG/LPG/हाइड्रोजन सोचें"],
 ["'F-O-H' — Fuel, Oxygen, Heat — आग की त्रिभुज",
  "150 kJ/g — हाइड्रोजन का कैलोरीफिक मान अलग से याद रखें"],
 ["लौ के क्षेत्र और दहन प्रकार पूछे जाते हैं",
  "कैलोरीफिक मान पर संख्यात्मक प्रश्न आते हैं"],
 ["दहन की शर्तें",
  "दहन के प्रकार",
  "आदर्श ईंधन के गुण",
  "ईंधन प्रदूषण और स्वच्छ विकल्प"],
 "दहन में पदार्थ ऑक्सीजन के साथ जलकर ऊष्मा-प्रकाश देते हैं; अपूर्ण दहन से CO और कालिख बनती है। ईंधन की गुणवत्ता कैलोरीफिक मान से मापी जाती है। आदर्श ईंधन उच्च कैलोरीफिक मान और कम प्रदूषण वाला होता है; CNG-LPG स्वच्छ विकल्प और जीवाश्म ईंधन अनवीनीकरणीय हैं।"),
 "en": N(
 "Combustion is a chemical process in which substances burn in oxygen giving heat and light. Fuel quality is measured by its calorific value (kJ/kg). Pollutants from burning fuels and their cleaner alternatives form an important exam topic.",
 "In a candle flame the blue zone indicates complete combustion while the glowing yellow zone burns carbon particles from incomplete combustion.",
 [("Combustion and its Types", "Oxygen is necessary; rapid (flame), incomplete (soot), and spontaneous combustion (phosphorus)."),
  ("Structure of a Flame", "Zones of a candle flame — the hottest blue part near the base; the luminous yellow part shows incomplete combustion."),
  ("Fuels and Calorific Value", "Qualities of an ideal fuel — high calorific value, low smoke, cheap, safe; hydrogen has high calorific value but is hard to store."),
  ("Pollution and Clean Alternatives", "Burning coal-petrol gives SO₂, CO, CO₂ and ash; CNG-LPG are cleaner; energy conservation and renewables are essential.")],
 ["Three needs of combustion — combustible substance, oxygen, ignition temperature",
  "Incomplete combustion gives CO and soot",
  "Calorific value = heat per kg of fuel (kJ/kg)",
  "Hydrogen's calorific value is about 150 kJ/g",
  "CNG and LPG are cleaner than petrol-coal",
  "Fossil fuels are non-renewable"],
 ["Remember the temperature order of flame zones",
  "List the qualities of an ideal fuel on your fingers",
  "Make pairs of pollutant gases and their sources"],
 ["Not all burning is combustion — rusting is slow oxidation",
  "CO₂ is not poisonous but CO is deadly — do not mix them"],
 ["Smoke/soot in a question points to incomplete combustion",
  "For clean fuels think CNG/LPG/hydrogen"],
 ["'F-O-H' — Fuel, Oxygen, Heat — the fire triangle",
  "Remember 150 kJ/g as hydrogen's calorific value"],
 ["Flame zones and combustion types are asked",
  "Numericals on calorific value appear in exams"],
 ["Conditions of combustion",
  "Types of combustion",
  "Qualities of an ideal fuel",
  "Fuel pollution and clean alternatives"],
 "In combustion substances burn in oxygen giving heat and light; incomplete combustion gives CO and soot. Fuel quality is measured by calorific value. An ideal fuel has high calorific value with low pollution; CNG-LPG are clean options and fossil fuels are non-renewable.")}))

def build(ch):
    (d, code, num, nhi, nen, dhi, den, notes) = ch
    meta = dict(SUBJECT)
    meta.update({
        "chapter": d,
        "chapterNumber": num,
        "code": code,
        "chapterName": {"hi": nhi, "en": nen},
        "mockQuestionCount": 30,
        "practiceQuestionTarget": 150,
        "mockTestTarget": 5,
        "topics": [],
        "notes": notes,
    })
    return d, meta

if __name__ == "__main__":
    for ch in CH:
        d, meta = build(ch)
        p = os.path.join(OUT, d)
        os.makedirs(p, exist_ok=True)
        with open(os.path.join(p, "meta.json"), "w", encoding="utf-8") as f:
            json.dump(meta, f, ensure_ascii=False, indent=2); f.write("\n")
        with open(os.path.join(p, "questions.json"), "w", encoding="utf-8") as f:
            json.dump({"questions": []}, f, ensure_ascii=False, indent=2); f.write("\n")
        print("wrote", os.path.join(OUT, d))
    print("chemistry chapters:", len(CH))
