#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generates the 10 NEW Biology chapter folders (roadmap B02-B08, B10-B12).
Existing chapter-01 (B01) and chapter-02 (B09) are NOT touched here."""
import json, os

OUT = "data/science/biology"

SUBJECT = {
    "subject": "biology",
    "subjectName": {"hi": "जीव विज्ञान", "en": "Biology"},
    "classRange": "6-10",
}

# Each chapter: (dir, code, num, nameHi, nameEn, descHi, descEn, notes)
def N(concept, example, sections, kp, ef, et, tb, mt, pq, mr, qr):
    return {"concept": concept, "example": example,
            "sections": [{"heading": h, "content": c} for h, c in sections],
            "keyPoints": kp, "examFocus": ef, "examTraps": et,
            "thinkBeforeAnswer": tb, "memoryTricks": mt, "pyqSignals": pq,
            "mustRemember": mr, "quickRevision": qr}

CH = []

CH.append(("chapter-03", "B02", 2, "ऊतक एवं शरीर की संरचना", "Tissues & Body Structure",
"शरीर की संरचना को समझने के लिए ऊतकों का अध्ययन आवश्यक है।",
"Study of tissues is essential to understand how the body is built.",
{"hi": N(
 "समान उत्पत्ति, संरचना और कार्य वाली कोशिकाओं का समूह ऊतक कहलाता है। पादप ऊतक विभज्योतक और स्थायी ऊतक में बँटते हैं, जबकि जंतु ऊतक चार प्रकार के होते हैं — उपकला, संयोजी, पेशीय और तंत्रिका। हड्डियों का ढाँचा शरीर को आकार और गति देता है।",
 "त्वचा की बाहरी परत उपकला ऊतक का, रक्त संयोजी ऊतक का और जंघा की मांसपेशी पेशीय ऊतक का उदाहरण है।",
 [("पादप ऊतक", "विभज्योतक निरंतर विभाजित होकर वृद्धि करता है; स्थायी ऊतक (सरल व जटिल) विभाजन क्षमता खो चुके होते हैं।"),
  ("जंतु ऊतक", "उपकला ढकने का कार्य करती है, संयोजी ऊतक जोड़ता और सहारा देता है, पेशीय ऊतक गति उत्पन्न करता है और तंत्रिका ऊतक संकेत संचालित करता है।"),
  ("अस्थि-पंजर", "मनुष्य के कंकाल में 206 अस्थियाँ होती हैं; पसलियाँ हृदय और फेफड़ों की रक्षा करती हैं और रीढ़ में 33 कशेरुकाएँ होती हैं।"),
  ("जोड़ एवं गति", "संधियों (जोड़ों) पर अस्थियाँ आपस में जुड़ती हैं; गोलाकार जोड़ कंधे में और कबंध जोड़ कोहनी में पाया जाता है।")],
 ["ऊतक समान कोशिकाओं का समूह है जो एक विशिष्ट कार्य करता है",
  "विभज्योतक वृद्धि करता है, स्थायी ऊतक नहीं",
  "जंतु ऊतक चार प्रकार के हैं — उपकला, संयोजी, पेशीय, तंत्रिका",
  "रक्त एक तरल संयोजी ऊतक है",
  "जाइलम और फ्लोएम जटिल स्थायी ऊतक हैं",
  "कंकाल शरीर को आकार, सहारा और गति देता है"],
 ["पादप और जंतु ऊतकों के नाम व उदाहरण जोड़कर याद रखें",
  "उपकला, संयोजी, पेशीय, तंत्रिका — क्रम और कार्य साथ में याद करें",
  "जोड़ों के प्रकार और उनका स्थान पूछा जाता है"],
 ["सभी संयोजी ऊतक ठोस नहीं होते — रक्त तरल संयोजी ऊतक है",
  "विभज्योतक और स्थायी ऊतक के कार्य आपस में उलटकर न लिखें"],
 ["प्रश्न में 'ढकने वाला ऊतक' हो तो उपकला, 'जोड़ने वाला' हो तो संयोजी ऊतक चुनें",
  "गति या संकुचन की बात आए तो पेशीय ऊतक के प्रकार (रेखित, अरेखित, हृदयक) याद करें"],
 ["जंतु ऊतक — 'उ-सं-प-त' (उपकला, संयोजी, पेशीय, तंत्रिका) क्रम से याद करें",
  "जाइलम = जल ऊपर, फ्लोएम = भोजन नीचे-ऊपर दोनों दिशाओं में — 'जा-फ्लो' याद रखें"],
 ["ऊतकों के प्रकार और उनके एक-एक उदाहरण पर सीधे प्रश्न आम हैं",
  "रक्त को ऊतक कहना और उसके घटक पूछना परीक्षा में बार-बार आता है"],
 ["ऊतक की परिभाषा और पादप-जंतु ऊतकों का वर्गीकरण",
  "चार जंतु ऊतकों के नाम और कार्य",
  "विभज्योतक बनाम स्थायी ऊतक",
  "कंकाल के मुख्य भाग और जोड़ों के प्रकार"],
 "ऊतक समान कोशिकाओं का समूह है। पादपों में विभज्योतक वृद्धि करता है और स्थायी ऊतक (जाइलम, फ्लोएम सहित) संरचना व परिवहन का कार्य करते हैं। जंतुओं में उपकला, संयोजी, पेशीय और तंत्रिका ऊतक मिलते हैं। अस्थि-पंजर 206 अस्थियों का बना है और जोड़ों की सहायता से गति संभव होती है।"),
 "en": N(
 "A tissue is a group of cells with similar origin, structure and function. Plant tissues divide into meristematic and permanent tissues, while animal tissues are of four types — epithelial, connective, muscular and nervous. The skeletal framework gives the body shape, support and movement.",
 "The outer layer of skin is epithelial tissue, blood is connective tissue, and the thigh muscle is muscular tissue.",
 [("Plant Tissues", "Meristematic tissue divides continuously for growth; permanent tissues (simple and complex) have lost the ability to divide."),
  ("Animal Tissues", "Epithelial tissue covers, connective tissue binds and supports, muscular tissue produces movement, and nervous tissue carries signals."),
  ("Skeletal System", "The human skeleton has 206 bones; the ribs protect the heart and lungs, and the backbone has 33 vertebrae."),
  ("Joints and Movement", "Bones meet at joints; the ball-and-socket joint is in the shoulder and the hinge joint is in the elbow.")],
 ["A tissue is a group of similar cells performing one specific function",
  "Meristematic tissue grows; permanent tissue does not divide",
  "Animal tissues are of four types — epithelial, connective, muscular, nervous",
  "Blood is a liquid connective tissue",
  "Xylem and phloem are complex permanent tissues",
  "The skeleton gives shape, support and movement to the body"],
 ["Memorise plant and animal tissue names with one example each",
  "Learn the order and functions of epithelial, connective, muscular and nervous tissues",
  "Types of joints and their locations are commonly asked"],
 ["Not all connective tissues are solid — blood is a liquid connective tissue",
  "Do not swap the functions of meristematic and permanent tissues"],
 ["If a question says 'covering tissue', pick epithelial; 'binding tissue' means connective",
  "For movement or contraction, recall the types of muscular tissue (striated, unstriated, cardiac)"],
 ["Remember animal tissues as E-C-M-N — epithelial, connective, muscular, nervous",
  "Xylem carries water upward; phloem carries food both ways — 'X-up, phlo-both'"],
 ["Direct one-line questions on tissue types and examples are common",
  "Calling blood a tissue and naming its components is repeatedly asked"],
 ["Definition of tissue and classification of plant/animal tissues",
  "Names and functions of the four animal tissues",
  "Meristematic vs permanent tissue",
  "Main parts of the skeleton and types of joints"],
 "A tissue is a group of similar cells. In plants, meristematic tissue grows and permanent tissues (including xylem and phloem) provide structure and transport. Animals have epithelial, connective, muscular and nervous tissues. The skeleton of 206 bones, with the help of joints, makes movement possible.")}))

CH.append(("chapter-04", "B03", 3, "जीवों में विविधता एवं वर्गीकरण", "Diversity & Classification of Living Organisms",
"जीवों की विविधता को वर्गीकरण द्वारा व्यवस्थित किया जाता है।",
"Classification brings order to the diversity of living organisms.",
{"hi": N(
 "पृथ्वी पर लाखों प्रकार के जीव पाए जाते हैं, इसलिए उन्हें समान लक्षणों के आधार पर समूहों में बाँटा जाता है। वर्गीकरण की मुख्य श्रेणियाँ हैं — साम्राज्य, संघ, वर्ग, गण, कुल, वंश और जाति। इसी आधार पर जीवों को पाँच जगतों में और पौधों-जंतुओं को आगे उपविभागों में बाँटा गया है।",
 "आलू और टमाटर एक ही कुल में आते हैं क्योंकि दोनों की पत्तियों और फूलों की संरचना समान है।",
 [("वर्गीकरण का आधार", "जीवों को कोशिका-संरचना, शरीर-योजना, पोषण-विधि और प्रजनन-विधि जैसे लक्षणों के आधार पर वर्गीकृत किया जाता है।"),
  ("वर्गीकरण की श्रेणियाँ", "साम्राज्य → संघ → वर्ग → गण → कुल → वंश → जाति — जाति सबसे छोटी मूल श्रेणी है।"),
  ("पाँच जगत", "मोनेरा, प्रोटिस्टा, फंजाई, प्लांटी और एनिमेलिया — यही व्हिटेकर का पाँच-जगत वर्गीकरण है।"),
  ("पौधे एवं जंतु समूह", "पौधे शैवाल-काष्ठ शरीर व बीज न होने/होने के आधार पर बँटते हैं; जंतु कशेरुकी और अकशेरुकी में बाँटे जाते हैं और कशेरुकी अगण के पाँच वर्ग हैं — मछली, उभयचर, सरीसृप, पक्षी, स्तनधारी।")],
 ["वर्गीकरण समान लक्षणों के आधार पर जीवों को समूहों में बाँटना है",
  "जाति वर्गीकरण की सबसे छोटी मूल श्रेणी है",
  "पाँच जगत हैं — मोनेरा, प्रोटिस्टा, फंजाई, प्लांटी, एनिमेलिया",
  "कशेरुकी जंतुओं के पाँच वर्ग हैं — मछली, उभयचर, सरीसृप, पक्षी, स्तनधारी",
  "नामांकन में जीव का वैज्ञानिक नाम वंश + जाति से बनता है",
  "अकशेरुकी जीव रीढ़ की हड्डी नहीं रखते, जैसे कीट और केंचुआ"],
 ["श्रेणियों का क्रम साम्राज्य से जाति तक रटें",
  "पाँच जगतों के नाम और उनके एक-एक उदाहरण याद रखें",
  "कशेरुकी वर्गों के विशेष लक्षण (जैसे उभयचर की ग्रंथियुक्त त्वचा) पर ध्यान दें"],
 ["मोनेरा में सभी जीव सूक्ष्म होते हैं ऐसा नहीं — प्रोटिस्टा भी सूक्ष्म हो सकते हैं",
  "सभी सरीसृप जल में नहीं रहते; कछुआ जल-थल दोनों में रहता है पर सरीसृप है"],
 ["प्रश्न में 'सबसे छोटी श्रेणी' हो तो जाति उत्तर है",
  "'रीढ़ की हड्डी नहीं' पाए तो जीव अकशेरुकी समूह में रखें"],
 ["श्रेणी-क्रम याद करने के लिए 'सा-सं-व-ग-कु-वं-जा' क्रम दोहराएँ",
  "कशेरुकी वर्ग — म-उ-स-प-स्त (मछली, उभयचर, सरीसृप, पक्षी, स्तनधारी)"],
 ["पाँच जगतों के नाम और उदाहरण पर सीधे प्रश्न पूछे जाते हैं",
  "मानव का वैज्ञानिक नाम (होमो सेपियन्स) और उसकी स्थिति अक्सर पूछी जाती है"],
 ["वर्गीकरण की श्रेणियाँ और उनका क्रम",
  "पाँच जगतों के नाम व उदाहरण",
  "कशेरुकी और अकशेरुकी में अंतर",
  "वैज्ञानिक नामांकन का नियम — वंश + जाति"],
 "जीवों की विविधता को समान लक्षणों के आधार पर वर्गीकरण द्वारा व्यवस्थित किया जाता है। श्रेणियाँ साम्राज्य से जाति तक होती हैं। व्हिटेकर का पाँच-जगत वर्गीकरण जीवों को मोनेरा, प्रोटिस्टा, फंजाई, प्लांटी और एनिमेलिया में बाँटता है। कशेरुकी जंतु पाँच वर्गों में और पौधे बीज व शरीर-योजना के आधार पर आगे बाँटे जाते हैं।"),
 "en": N(
 "Millions of organisms live on Earth, so they are grouped by shared characteristics. The main ranks are kingdom, phylum, class, order, family, genus and species. On this basis organisms are placed in five kingdoms, and plants and animals are further subdivided.",
 "Potato and tomato belong to the same family because their leaf and flower structure is similar.",
 [("Basis of Classification", "Organisms are classified by cell structure, body design, mode of nutrition and reproduction."),
  ("Ranks of Classification", "Kingdom → Phylum → Class → Order → Family → Genus → Species — species is the smallest basic rank."),
  ("Five Kingdoms", "Monera, Protista, Fungi, Plantae and Animalia — Whittaker's five-kingdom classification."),
  ("Plant and Animal Groups", "Plants are grouped by thallus/woody body and absence/presence of seeds; animals are invertebrate or vertebrate, and vertebrates have five classes — fish, amphibians, reptiles, birds, mammals.")],
 ["Classification is grouping organisms by shared characteristics",
  "Species is the smallest basic rank of classification",
  "The five kingdoms are Monera, Protista, Fungi, Plantae, Animalia",
  "Vertebrates have five classes — fish, amphibians, reptiles, birds, mammals",
  "In binomial nomenclature the scientific name = genus + species",
  "Invertebrates, such as insects and earthworms, lack a backbone"],
 ["Learn the rank order from kingdom to species by heart",
  "Memorise the five kingdoms with one example each",
  "Note class-specific traits (e.g. moist skin of amphibians)"],
 ["Not all microscopic organisms are Monera — Protists can also be microscopic",
  "Not all reptiles stay on land; the turtle lives in water and on land yet is a reptile"],
 ["If a question asks the 'smallest rank', the answer is species",
  "No backbone means the animal belongs to the invertebrate group"],
 ["Revise the rank order as K-P-C-O-F-G-S",
  "Vertebrate classes — Fish, Amphibians, Reptiles, Birds, Mammals (FARBM)"],
 ["Direct questions on the five kingdoms and their examples are common",
  "The scientific name of humans (Homo sapiens) and its parts are often asked"],
 ["Ranks of classification and their order",
  "Names and examples of the five kingdoms",
  "Differences between vertebrates and invertebrates",
  "Rule of binomial nomenclature — genus + species"],
 "Classification organises the diversity of life by shared characteristics, with ranks from kingdom down to species. Whittaker's five-kingdom system places organisms in Monera, Protista, Fungi, Plantae and Animalia. Vertebrates are divided into five classes and plants are subdivided by body design and seeds. Binomial nomenclature gives each organism a two-part scientific name.")}))

CH.append(("chapter-05", "B04", 4, "पादप जीवन एवं पादप क्रियाएँ", "Plant Life & Plant Functions",
"पादपों की संरचना और उनकी मुख्य क्रियाएँ — प्रकाश संश्लेषण, वाष्पोत्सर्जन आदि।",
"Plant structure and key functions — photosynthesis, transpiration and more.",
{"hi": N(
 "पौधे जड़, तना, पत्ती, फूल और फल से बने होते हैं और हर भाग एक विशेष कार्य करता है। हरे पत्ते क्लोरोफिल की सहायता से प्रकाश संश्लेषण द्वारा भोजन बनाते हैं, जड़ें जल व खनिज ग्रहण करती हैं और वाष्पोत्सर्जन द्वारा पौधे में खिंचाव बना रहता है।",
 "मुंबई में गाजर जड़ में भोजन संचित होता है और सरसों के बीज से तेल मिलता है — दोनों पौधे के विभिन्न भागों के उपयोग हैं।",
 [("पौधे के भाग एवं कार्य", "जड़ अवशोषण व टिकाऊता, तना संचालन व सहारा, पत्ती भोजन निर्माण, फूल प्रजनन करते हैं।"),
  ("प्रकाश संश्लेषण", "हरे पत्तों में क्लोरोफिल, CO₂ और जल सूर्य-प्रकाश की उपस्थिति में मिलकर ग्लूकोज व ऑक्सीजन बनाते हैं।"),
  ("वाष्पोत्सर्जन", "पत्तियों की रंध्रों से जलवाष्प का निकलना वाष्पोत्सर्जन कहलाता है; यह खिंचाव बनाए रखता है और पौधे को ठंडा रखता है।"),
  ("फूल, फल एवं बीज", "परागण के बाद निषेचन से बीज बनता है, अंडाशय फल बनता है और बीज से नया पौधा उगता है।")],
 ["पौधे का शरीर जड़-तना-पत्ती रूप में विभाजित होता है",
  "प्रकाश संश्लेषण में कच्चा माल — CO₂, जल, सूर्य-प्रकाश, क्लोरोफिल",
  "प्रकाश संश्लेषण के उत्पाद — ग्लूकोज और ऑक्सीजन",
  "रंध्र पत्तियों में गैसों का आदान-प्रदान करते हैं",
  "वाष्पोत्सर्जन जल का उपयोगी व्यय और पौधे की शीतलन-विधि है",
  "अंडाशय फल और बीजांड बीज बनाता है"],
 ["प्रकाश संश्लेषण का संतुलित समीकरण और आवश्यक कारक याद रखें",
  "रंध्रों की संरचना और कार्क पर प्रश्न आम हैं",
  "जड़ के प्रकार (मूसला, रेशेदार) और उनके उदाहरण रटें"],
 ["प्रकाश संश्लेषण केवल रात में नहीं होता — प्रकाश आवश्यक है",
  "सभी जड़ें भोजन संचित नहीं करतीं — गाजर, मूली जैसी विशेष जड़ें ही करती हैं"],
 ["प्रश्न में ऑक्सीजन का उत्सर्जन हो तो प्रकाश संश्लेषण की ओर सोचें",
  "जलवाष्प के निकलने की बात आए तो रंध्र और वाष्पोत्सर्जन याद करें"],
 ["कच्चे माल को 'COW' याद रखें — CO₂, जल (Water), प्रकाश (light) के लिए O नहीं बल्कि क्रम बनाए रखें",
  "अंडाशय = फल, बीजांड = बीज — 'ओ-फ, ओव-सी' जोड़ी याद रखें"],
 ["प्रकाश संश्लेषण के उत्पाद और कारक पर सीधे प्रश्न बार-बार आते हैं",
  "रंध्र का स्थान और कार्य पूछा जाता है"],
 ["प्रकाश संश्लेषण की परिभाषा, कच्चा माल और उत्पाद",
  "वाष्पोत्सर्जन का कार्य",
  "पौधे के भागों के कार्य",
  "फूल से फल और बीज बनने का क्रम"],
 "पौधों में हर भाग का विशेष कार्य है — जड़ अवशोषण, तना संचालन, पत्ती भोजन निर्माण और फूल प्रजनन करते हैं। प्रकाश संश्लेषण में CO₂ और जल से ग्लूकोज व ऑक्सीजन बनते हैं। रंध्रों से होने वाला वाष्पोत्सर्जन पौधे में खिंचाव और शीतलन बनाए रखता है। निषेचन के बाद अंडाशय फल और बीजांड बीज बन जाता है।"),
 "en": N(
 "A plant is made of root, stem, leaf, flower and fruit, and each part has a special job. Green leaves prepare food by photosynthesis using chlorophyll, roots absorb water and minerals, and transpiration maintains the pull inside the plant.",
 "Carrot stores food in its root and mustard seeds give oil — both are uses of different plant parts.",
 [("Plant Parts and Functions", "Roots absorb and anchor, the stem conducts and supports, leaves make food, and flowers reproduce."),
  ("Photosynthesis", "In green leaves, chlorophyll, CO₂ and water use sunlight to form glucose and oxygen."),
  ("Transpiration", "Loss of water vapour through stomata of leaves; it maintains suction pull and cools the plant."),
  ("Flower, Fruit and Seed", "After pollination and fertilisation the seed forms, the ovary becomes the fruit, and a new plant grows from the seed.")],
 ["The plant body is divided into root, stem and leaf systems",
  "Raw materials of photosynthesis — CO₂, water, sunlight, chlorophyll",
  "Products of photosynthesis — glucose and oxygen",
  "Stomata in leaves exchange gases",
  "Transpiration is useful water loss and cools the plant",
  "The ovary becomes the fruit and the ovule becomes the seed"],
 ["Memorise the balanced equation and requirements of photosynthesis",
  "Structure and role of stomata are commonly asked",
  "Learn root types (tap, fibrous) with examples"],
 ["Photosynthesis does not occur at night — light is essential",
  "Not all roots store food — only special roots like carrot and radish do"],
 ["If oxygen is released in a question, think of photosynthesis",
  "Water vapour leaving the plant points to stomata and transpiration"],
 ["Link raw materials as CO₂-Water-Light-Chlorophyll",
  "Ovary → Fruit, Ovule → Seed — remember the O-pairs"],
 ["Direct questions on photosynthesis products and factors appear repeatedly",
  "Location and function of stomata are frequently asked"],
 ["Definition, raw materials and products of photosynthesis",
  "Function of transpiration",
  "Functions of plant parts",
  "Sequence from flower to fruit and seed"],
 "Every plant part has a role — roots absorb, the stem conducts, leaves make food and flowers reproduce. In photosynthesis, CO₂ and water form glucose and oxygen. Transpiration through stomata maintains pull and cools the plant. After fertilisation the ovary becomes the fruit and the ovule becomes the seed.")}))

CH.append(("chapter-06", "B05", 5, "जंतु जीवन एवं शरीर क्रियाएँ", "Animal Life & Body Functions",
"जंतुओं के अंग-तंत्र, समन्वय एवं उत्सर्जन की मूल बातें।",
"Basics of organ systems, coordination and excretion in animals.",
{"hi": N(
 "जंतुओं का शरीर अनेक अंग-तंत्रों से मिलकर बना है — पाचन, श्वसन, परिवहन, उत्सर्जन, नियंत्रण एवं समन्वय और प्रजनन। तंत्रिका तंत्र और हार्मोन मिलकर शरीर के सभी अंगों का समन्वय करते हैं, जबकि वृक्क अपशिष्ट पदार्थों को रक्त से हटाकर मूत्र बनाते हैं।",
 "हाथ गर्म वस्तु को छूते ही पीछे खिंच जाता है — यह तंत्रिका तंत्र की त्वरित क्रिया है; भोजन के बाद रक्त में शर्करा बढ़ने पर इंसुलिन का स्राव हार्मोन-नियंत्रण का उदाहरण है।",
 [("अंग-तंत्रों का सिंहावलोकन", "पाचन भोजन को सरल करता है, श्वसन ऊर्जा देता है, परिवहन रक्त द्वारा वितरण करता है और प्रजनन जाति को आगे बढ़ाता है।"),
  ("तंत्रिका तंत्र", "मस्तिष्क, मेरुरज्जु और तंत्रिकाएँ मिलकर उद्दीपन का तुरंत उत्तर देती हैं; यह नियंत्रण तीव्र लेकिन अल्पकालिक होता है।"),
  ("हार्मोनल नियंत्रण", "अंतःस्रावी ग्रंथियों के हार्मोन (जैसे इंसुलिन, थायरॉक्सिन) रक्त द्वारा पहुँचकर धीमा लेकिन दीर्घकालिक नियंत्रण रखते हैं।"),
  ("वृक्क एवं उत्सर्जन", "मानव में दो वृक्क रक्त छानकर यूरिया युक्त मूत्र बनाते हैं; यह शरीर से नाइट्रोजनी अपशिष्ट हटाता है।")],
 ["जंतु शरीर अनेक सहयोगी अंग-तंत्रों से बना है",
  "तंत्रिका नियंत्रण तीव्र और संक्षिप्त, हार्मोनल नियंत्रण धीमा और दीर्घ होता है",
  "मस्तिष्क और मेरुरज्जु केंद्रीय तंत्रिका तंत्र बनाते हैं",
  "इंसुलिन रक्त-शर्करा घटाता है, थायरॉक्सिन चयापचय नियंत्रित करता है",
  "वृक्क मूलभूत उत्सर्जन अंग हैं और यूरिया को मूत्र में निकालते हैं",
  "संतुलन (होमियोस्टेसिस) के लिए उत्सर्जन आवश्यक है"],
 ["तंत्रिका बनाम हार्मोनल नियंत्रण का अंतर तालिका रूप में याद रखें",
  "वृक्क की संरचना की मूल इकाई नेफ्रॉन है — नाम याद रखें",
  "इंद्रियों (आँख, कान, त्वचा, जीभ, नाक) के उद्दीपन और अंग जोड़कर याद करें"],
 ["सभी नियंत्रण तंत्रिका तंत्र से नहीं होते — वृद्धि और चयापचय हार्मोन से नियंत्रित होते हैं",
  "वृक्क केवल मूत्र नहीं बनाते — वे रक्त छानने और जल-संतुलन का भी कार्य करते हैं"],
 ["तुरंत प्रतिक्रिया की बात आए तो तंत्रिका तंत्र, धीमे दीर्घ परिवर्तन की बात आए तो हार्मोन चुनें",
  "रक्त में शर्करा घटाने वाला हार्मोन पूछा जाए तो इंसुलिन उत्तर है"],
 ["N-for-nerves = तुरंत (immediate), H-for-hormones = धीरे-धीरे (slow)",
  "इंसुलिन—इंजेक्शन—मधुमेह त्रिक को एक साथ याद करें"],
 ["तंत्रिका और हार्मोनल नियंत्रण में अंतर परीक्षा में बार-बार पूछा जाता है",
  "वृक्क का कार्य और यूरिया सीधे प्रश्नों में आते हैं"],
 ["अंग-तंत्रों के नाम और उनके मुख्य अंग",
  "तंत्रिका और हार्मोनल नियंत्रण में अंतर",
  "वृक्क का कार्य",
  "मुख्य हार्मोन और उनके एक-एक कार्य"],
 "जंतु शरीर पाचन, श्वसन, परिवहन, उत्सर्जन और नियंत्रण अंग-तंत्रों से बना है। तंत्रिका तंत्र तीव्र व अल्पकालिक नियंत्रण करता है जबकि हार्मोन धीमे व दीर्घकालिक नियंत्रण रखते हैं। वृक्क रक्त से यूरिया हटाकर मूत्र बनाते हैं और शरीर का जल-संतुलन बनाए रखते हैं।"),
 "en": N(
 "The animal body is built of many organ systems — digestion, respiration, transport, excretion, control-coordination and reproduction. The nervous system and hormones coordinate all organs, while kidneys filter wastes from blood to form urine.",
 "The hand withdraws instantly on touching something hot — a fast nervous action; insulin released after a meal controls blood sugar — an example of hormonal control.",
 [("Organ Systems Overview", "Digestion simplifies food, respiration provides energy, transport distributes materials by blood, and reproduction continues the species."),
  ("Nervous System", "Brain, spinal cord and nerves respond to stimuli immediately; this control is fast but short-lived."),
  ("Hormonal Control", "Hormones of endocrine glands (e.g. insulin, thyroxine) travel through blood for slow but long-lasting control."),
  ("Kidneys and Excretion", "Two kidneys filter blood to form urea-containing urine, removing nitrogenous waste from the body.")],
 ["The animal body is made of many cooperating organ systems",
  "Nervous control is fast and brief; hormonal control is slow and long-lasting",
  "Brain and spinal cord form the central nervous system",
  "Insulin lowers blood sugar; thyroxine controls metabolism",
  "Kidneys are the main excretory organs and remove urea as urine",
  "Excretion is essential for homeostasis"],
 ["Learn the differences between nervous and hormonal control as a table",
  "Remember that the nephron is the basic unit of the kidney",
  "Pair each sense organ (eye, ear, skin, tongue, nose) with its stimulus"],
 ["Not all control is nervous — growth and metabolism are controlled by hormones",
  "Kidneys do not just make urine — they also filter blood and balance water"],
 ["Immediate reaction points to the nervous system; slow long-term change points to hormones",
  "For a hormone that lowers blood sugar, the answer is insulin"],
 ["N-for-nerves = now; H-for-hormones = gradually",
  "Remember the trio insulin–injection–diabetes together"],
 ["Differences between nervous and hormonal control are asked repeatedly",
  "Functions of the kidney and urea appear in direct questions"],
 ["Names of organ systems and their main organs",
  "Difference between nervous and hormonal control",
  "Function of the kidney",
  "Key hormones and one function of each"],
 "The animal body consists of digestion, respiration, transport, excretion and control systems. The nervous system gives fast, short-term control while hormones give slow, long-term control. Kidneys filter urea from blood to make urine and maintain the body's water balance.")}))

CH.append(("chapter-07", "B06", 6, "पोषण एवं पाचन", "Nutrition & Digestion",
"पोषक तत्व, पोषण के प्रकार और मानव का पाचन तंत्र।",
"Nutrients, modes of nutrition and the human digestive system.",
{"hi": N(
 "भोजन से मिलने वाले पोषक तत्व — कार्बोहाइड्रेट, प्रोटीन, वसा, विटामिन और खनिज — शरीर के विकास, ऊर्जा और रक्षा के लिए आवश्यक हैं। पौधे स्वपोषी होते हैं जबकि जंतु परपोषी; कुछ जीव मृतोपजीवी या परजीवी होते हैं। मनुष्य के पाचन तंत्र में भोजन मुँह से मलाशय तक क्रमबद्ध रूप से पचता है।",
 "आमाशय में हाइड्रोक्लोरिक अम्ल भोजन को अम्लीय बनाता है और पेप्सिन प्रोटीन का पाचन करता है — अम्ल का यह कार्य रक्षा भी करता है।",
 [("पोषक तत्व एवं संतुलित आहार", "ऊर्जा के लिए कार्बोहाइड्रेट और वसा, शरीर-निर्माण के लिए प्रोटीन तथा रक्षा-नियंत्रण के लिए विटामिन-खनिज आवश्यक हैं।"),
  ("पोषण के प्रकार", "स्वपोषी (पौधे), परपोषी (जंतु), मृतोपजीवी (फंजस) और परजीवी (फीताकृमि) — पोषण की विधि से जीवों का वर्गीकरण।"),
  ("मानव पाचन तंत्र", "मुँह (लार में एमाइलेज) → आमाशय (HCl + पेप्सिन) → छोटी आँत (पित्त + एंजाइम) → अवशोषण → बड़ी आँत।"),
  ("विटामिन एवं उनकी कमी", "विटामिन A की कमी से रतौंधी, C से स्कर्वी, D से रिकेट्स, B1 से बेरी-बेरी और आयोडीन की कमी से घेघा होता है।")],
 ["पोषक तत्व पाँच प्रकार के होते हैं — कार्बोहाइड्रेट, प्रोटीन, वसा, विटामिन, खनिज (और जल)",
  "पौधे स्वपोषी, जंतु परपोषी होते हैं",
  "लार में स्टार्च पचाने वाला एमाइलेज होता है",
  "आमाशय का अम्ल पेप्सिन को सक्रिय करता है और कीटाणु मारता है",
  "छोटी आँत भोजन का अवशोषण करती है",
  "विटामिन-खनिज जल में घुलनशील और वसा में घुलनशील दो वर्गों में बाँटे जाते हैं"],
 ["किस विटामिन की कमी से कौन-सा रोग — यह जोड़ा रटें",
  "पाचन तंत्र के अंगों का क्रम और उनके एंजाइम याद रखें",
  "स्वपोषी/परपोषी/मृतोपजीवी/परजीवी के उदाहरण एक-एक करके याद करें"],
 ["सभी एंजाइम एक ही स्थान पर नहीं कार्य करते — लार, आमाशय और आँत के एंजाइम अलग हैं",
  "लार केवल आर्द्र करने के लिए नहीं है — उसमें एमाइलेज होता है"],
 ["प्रश्न में प्रोटीन का पाचन हो तो पेप्सिन और आमाशय याद करें",
  "कमी-रोग का प्रश्न आए तो जोड़े (विटामिन-रोग) दोहराएँ"],
 ["A-रतौंधी, C-स्कर्वी, D-रिकेट्स, B1-बेरीबेरी — अक्षर-जोड़ से याद करें",
  "भोजन का मार्ग 'मुँ-आ-छो-बड़ा-मल' क्रम से याद करें"],
 ["पाचन तंत्र के भाग और एंजाइम पर सीधे प्रश्न आम हैं",
  "विटामिन कमी से होने वाले रोग बार-बार पूछे जाते हैं"],
 ["पोषक तत्व और उनके कार्य",
  "पोषण के प्रकार और उदाहरण",
  "पाचन तंत्र के मुख्य अंग और एंजाइम",
  "विटामिन कमी के रोग"],
 "भोजन के पोषक तत्व ऊर्जा, वृद्धि और रक्षा के लिए आवश्यक हैं। पोषण स्वपोषी, परपोषी, मृतोपजीवी और परजीवी प्रकार का होता है। मानव के पाचन तंत्र में मुँह, आमाशय और छोटी आँत के एंजाइम भोजन को सरल अणुओं में बदलते हैं और छोटी आँत उसे अवशोषित करती है। विटामिनों की कमी से विशिष्ट रोग होते हैं।"),
 "en": N(
 "Nutrients from food — carbohydrates, proteins, fats, vitamins and minerals — are needed for growth, energy and protection. Plants are autotrophic while animals are heterotrophic; some organisms are saprophytic or parasitic. In the human digestive system food is digested step by step from mouth to rectum.",
 "Hydrochloric acid in the stomach makes food acidic and activates pepsin to digest protein; the acid also kills germs.",
 [("Nutrients and Balanced Diet", "Carbohydrates and fats give energy, proteins build the body, and vitamins-minerals protect and regulate."),
  ("Modes of Nutrition", "Autotrophic (plants), heterotrophic (animals), saprophytic (fungi) and parasitic (tapeworm) — classification by mode of nutrition."),
  ("Human Digestive System", "Mouth (salivary amylase) → stomach (HCl + pepsin) → small intestine (bile + enzymes) → absorption → large intestine."),
  ("Vitamins and Deficiency", "Lack of vitamin A causes night-blindness, C scurvy, D rickets, B1 beri-beri, and iodine deficiency causes goitre.")],
 ["There are five nutrients — carbohydrates, proteins, fats, vitamins, minerals (plus water)",
  "Plants are autotrophic; animals are heterotrophic",
  "Saliva contains amylase which digests starch",
  "Stomach acid activates pepsin and kills germs",
  "The small intestine absorbs digested food",
  "Vitamins are classified as water-soluble and fat-soluble"],
 ["Memorise which vitamin deficiency causes which disease",
  "Learn the order of digestive organs and their enzymes",
  "Remember one example each of autotrophic/heterotrophic/saprophytic/parasitic nutrition"],
 ["Not all enzymes work in one place — saliva, stomach and intestine have different enzymes",
  "Saliva is not just for moistening — it contains amylase"],
 ["Protein digestion points to pepsin and the stomach",
  "For deficiency-disease questions, recall the vitamin-disease pairs"],
 ["Remember A-night-blindness, C-scurvy, D-rickets, B1-beri-beri by letter pairs",
  "Learn the food path as Mouth-Stomach-Small-Large-Rectum in order"],
 ["Direct questions on digestive parts and enzymes are common",
  "Diseases caused by vitamin deficiency are asked repeatedly"],
 ["Nutrients and their functions",
  "Modes of nutrition with examples",
  "Main organs and enzymes of the digestive system",
  "Deficiency diseases of vitamins"],
 "Nutrients are essential for energy, growth and protection. Nutrition may be autotrophic, heterotrophic, saprophytic or parasitic. In humans, enzymes of the mouth, stomach and small intestine simplify food, and the small intestine absorbs it. Vitamin deficiencies cause specific diseases.")}))

CH.append(("chapter-08", "B07", 7, "श्वसन एवं गैसों का आदान-प्रदान", "Respiration & Gas Exchange",
"श्वसन की प्रक्रिया, वायुीय/अवायुीय श्वसन और श्वसन तंत्र।",
"Respiration process, aerobic/anaerobic types and the respiratory system.",
{"hi": N(
 "श्वसन में भोजन के ऑक्सीकरण द्वारा ऊर्जा मुक्त होती है; यह कोशिकाओं में होने वाली जैविक प्रक्रिया है। ऑक्सीजन की उपस्थिति में होने वाला श्वसन वायुीय और अनुपस्थिति में होने वाला अवायुीय कहलाता है। मनुष्य में नासिका छिद्रों से फेफड़ों तक का मार्ग और उसमें गैसों का आदान-प्रदान वायुकोशों (एल्वियोलाई) में होता है।",
 "दौड़ के बाद मांसपेशियों में जलन अवायुीय श्वसन से बने लैक्टिक अम्ल के कारण होती है।",
 [("श्वसन बनाम श्वास", "श्वसन कोशिकाओं में ऊर्जा-उत्पादन है, जबकि श्वास केवल वायु का अंदर-बाहर आना है — दोनों को मिलाकर न लिखें।"),
  ("वायुीय एवं अवायुीय श्वसन", "वायुीय श्वसन में ग्लूकोज + ऑक्सीजन → CO₂ + जल + अधिक ऊर्जा; अवायुीय में यीस्ट अल्कोहल और मांसपेशियाँ लैक्टिक अम्ल बनाती हैं।"),
  ("मानव श्वसन तंत्र", "वायु नासिका → श्वासनली → श्वसनी → फेफड़ों के वायुकोशों तक जाती है; डायाफ्राम और पसलियाँ साँस लेने में सहायक हैं।"),
  ("पौधों एवं अन्य जीवों में श्वसन", "पौधों में रंध्र और जड़ों में वायु अंतराल से, मछली में क्लोम से और कीटों में श्वासनलिकाओं से गैसों का आदान-प्रदान होता है।")],
 ["श्वसन भोजन के ऑक्सीकरण से ऊर्जा मुक्त करने की कोशिकीय प्रक्रिया है",
  "वायुीय श्वसन के उत्पाद — CO₂, जल और 38 ATP के आसपास ऊर्जा",
  "अवायुीय श्वसन में यीस्ट अल्कोहल + CO₂ देता है (किण्वन)",
  "मांसपेशियों में अवायुीय श्वसन से लैक्टिक अम्ल बनता है",
  "गैसों का आदान-प्रदान वायुकोशों (एल्वियोलाई) में होता है",
  "श्वसन और प्रकाश संश्लेषण की दिशा एक-दूसरे के विपरीत है"],
 ["श्वसन और श्वास में अंतर स्पष्ट रूप से याद रखें",
  "वायुीय और अवायुीय श्वसन के उत्पादों की तुलना करें",
  "विभिन्न जीवों के श्वसन अंग (क्लोम, श्वासनलिका, त्वचा) जोड़कर याद करें"],
 ["श्वास लेना ही श्वसन नहीं है — ऊर्जा-उत्पादन कोशिकाओं में होता है",
  "सभी जीव फेफड़ों से श्वास नहीं लेते — मछली क्लोम से, केंचुआ त्वचा से साँस लेता है"],
 ["अल्कोहल/किण्वन का उल्लेख मिले तो यीस्ट का अवायुीय श्वसन याद करें",
  "मांसपेशियों में जलन का कारण पूछा जाए तो लैक्टिक अम्ल उत्तर है"],
 ["Aerobic = A for Air (हवा के साथ), Anaerobic = An = नहीं (हवा के बिना)",
  "यीस्ट-अल्कोहल-मदिरा त्रिक को एक साथ याद करें"],
 ["वायुीय बनाम अवायुीय श्वसन की तुलना परीक्षा में बार-बार आती है",
  "विभिन्न जीवों के श्वसन अंग पूछे जाते हैं"],
 ["श्वसन की परिभाषा और उद्देश्य",
  "वायुीय-अवायुीय श्वसन के उत्पाद",
  "मानव श्वसन तंत्र का मार्ग",
  "विभिन्न जीवों के श्वसन अंग"],
 "श्वसन कोशिकाओं में भोजन के ऑक्सीकरण द्वारा ऊर्जा मुक्त करने की प्रक्रिया है। वायुीय श्वसन में ऑक्सीजन लेकर CO₂, जल और अधिक ऊर्जा मिलती है; अवायुीय श्वसन में यीस्ट अल्कोहल और मांसपेशियाँ लैक्टिक अम्ल बनाती हैं। मनुष्य में गैसों का आदान-प्रदान फेफड़ों के वायुकोशों में होता है और अन्य जीवों में श्वसन अंग भिन्न होते हैं।"),
 "en": N(
 "In respiration, energy is released by oxidation of food; it is a cellular process. Respiration with oxygen is aerobic and without oxygen is anaerobic. In humans, air travels from nostrils to the lungs and gases exchange in the alveoli.",
 "Muscle cramps after running are due to lactic acid formed by anaerobic respiration.",
 [("Respiration vs Breathing", "Respiration is energy production inside cells, while breathing is only the inward-outward movement of air — do not mix them."),
  ("Aerobic and Anaerobic Respiration", "Aerobic: glucose + oxygen → CO₂ + water + more energy; anaerobic: yeast gives alcohol and muscles give lactic acid."),
  ("Human Respiratory System", "Air passes nostrils → trachea → bronchi → alveoli of lungs; the diaphragm and ribs help in breathing."),
  ("Respiration in Plants and Other Organisms", "Plants exchange gases through stomata and root air spaces, fish through gills, and insects through tracheae.")],
 ["Respiration is the cellular process of releasing energy by oxidising food",
  "Aerobic products — CO₂, water and energy (about 38 ATP)",
  "In anaerobic respiration yeast gives alcohol + CO₂ (fermentation)",
  "Muscles form lactic acid in anaerobic respiration",
  "Gas exchange occurs in the alveoli",
  "Respiration and photosynthesis run in opposite directions"],
 ["Keep the difference between respiration and breathing clear",
  "Compare the products of aerobic and anaerobic respiration",
  "Pair respiratory organs of different organisms (gills, tracheae, skin)"],
 ["Breathing is not respiration — energy production happens in cells",
  "Not all organisms breathe with lungs — fish use gills and earthworms use their skin"],
 ["Mention of alcohol/fermentation points to anaerobic respiration in yeast",
  "For muscle cramps, the answer is lactic acid"],
 ["Aerobic = A for Air; Anaerobic = An = without air",
  "Remember the trio yeast-alcohol-brewing together"],
 ["Comparison of aerobic vs anaerobic respiration is asked repeatedly",
  "Respiratory organs of different organisms are common questions"],
 ["Definition and purpose of respiration",
  "Products of aerobic-anaerobic respiration",
  "Path of the human respiratory system",
  "Respiratory organs of various organisms"],
 "Respiration releases energy by oxidising food inside cells. Aerobic respiration uses oxygen to give CO₂, water and more energy; anaerobic respiration makes alcohol in yeast and lactic acid in muscles. In humans gas exchange occurs in the alveoli, and different organisms use different respiratory organs.")}))

CH.append(("chapter-09", "B08", 8, "परिवहन एवं रक्त संचार", "Transportation & Circulation",
"रक्त, हृदय और पौधों में परिवहन की प्रणाली।",
"Blood, the heart and transport in plants.",
{"hi": N(
 "शरीर की कोशिकाओं तक भोजन, ऑक्सीजन और अपशिष्ट पदार्थों का परिवहन रक्त द्वारा होता है। हृदय चार कक्षों का पेशीय अंग है जो रक्त को शरीर में लगातार पंप करता है और मनुष्य में द्विरक्त संचार पाया जाता है। पौधों में जाइलम जल व खनिज ऊपर और फ्लोएम भोजन सभी दिशाओं में ले जाता है।",
 "गाजर में पानी नीले रंग से ऊपर चढ़ना जाइलम के जल-परिवहन का सरल प्रयोग है।",
 [("रक्त एवं उसके घटक", "रक्त में प्लाज्मा, लाल रुधिर कणिकाएँ (ऑक्सीजन वहन), श्वेत रुधिर कणिकाएँ (रक्षा) और प्लेटलेट्स (थक्का) होते हैं।"),
  ("हृदय एवं रक्तवाहिकाएँ", "हृदय के दो अलिंद और दो निलय हैं; धमनियाँ रक्त हृदय से दूर और शिराएँ हृदय की ओर लाती हैं।"),
  ("द्विरक्त संचार", "रक्त एक चक्र में दो बार हृदय से गुजरता है — फुफ्फुसीय चक्र (फेफड़े) और दैहिक चक्र (शरीर); इससे ऊर्जा-आपूर्ति कुशल बनती है।"),
  ("पौधों में परिवहन", "जाइलम मूल-दाब और वाष्पोत्सर्जन-खिंचाव से जल ऊपर चढ़ता है; फ्लोएम सक्रिय परिवहन से भोजन पत्तियों से भंडारण अंगों तक ले जाता है।")],
 ["रक्त = प्लाज्मा + RBC + WBC + प्लेटलेट्स",
  "हीमोग्लोबिन ऑक्सीजन का वहन करता है और इसमें लोहा होता है",
  "धमनियाँ हृदय से बाहर, शिराएँ हृदय की ओर",
  "मनुष्य में चार-कक्षीय हृदय और द्विरक्त संचार होता है",
  "लसीका तंत्र वसा अवशोषित करता है और रक्षा में सहायक होता है",
  "जाइलम-जल व खनिज, फ्लोएम-भोजन परिवहन करता है"],
 ["हृदय के कक्षों का नाम और क्रम याद रखें",
  "धमनी-शिरा के अंतर की तुलना तालिका बनाएँ",
  "वाष्पोत्सर्जन-खिंचाव और मूल दाब को जाइलम परिवहन से जोड़कर याद करें"],
 ["सभी धमनियों में शुद्ध रक्त नहीं होता — फुफ्फुसीय धमनी अशुद्ध रक्त ले जाती है",
  "जाइलम और फ्लोएम के कार्य उलटकर न लिखें"],
 ["फुफ्फुसीय धमनी का प्रश्न आए तो सावधान हों — यह अपवाद है",
  "पौधे में भोजन के परिवहन का प्रश्न हो तो फ्लोएम चुनें"],
 ["A-for-Away — धमनी (Artery) हृदय से दूर ले जाती है",
  "'जा-जल, फ्लो-फल' — जाइलम जल, फ्लोएम भोजन (फल) के लिए"],
 ["रक्त के घटक और उनके कार्य सीधे पूछे जाते हैं",
  "जाइलम-फ्लोएम का कार्य बार-बार पूछा जाता है"],
 ["रक्त के चार घटक और कार्य",
  "हृदय के चार कक्ष",
  "धमनी और शिरा में अंतर",
  "पौधों में जाइलम-फ्लोएम का कार्य"],
 "रक्त प्लाज्मा, RBC, WBC और प्लेटलेट्स से मिलकर बना है और हृदय चार कक्षों द्वारा इसे शरीर में पंप करता है; मनुष्य में द्विरक्त संचार पाया जाता है। धमनियाँ रक्त हृदय से दूर और शिराएँ हृदय की ओर लाती हैं। पौधों में जाइलम जल-खनिज ऊपर ले जाता है और फ्लोएम भोजन का परिवहन करता है।"),
 "en": N(
 "Blood transports food, oxygen and wastes to and from the cells of the body. The heart is a four-chambered muscular organ that pumps blood continuously, and humans show double circulation. In plants, xylem carries water and minerals upward and phloem carries food in all directions.",
 "Blue-coloured water rising in a carrot is a simple experiment of water transport in xylem.",
 [("Blood and its Components", "Blood has plasma, red cells (oxygen transport), white cells (defence) and platelets (clotting)."),
  ("Heart and Blood Vessels", "The heart has two atria and two ventricles; arteries carry blood away from the heart and veins bring it back."),
  ("Double Circulation", "Blood passes through the heart twice in one cycle — pulmonary (lungs) and systemic (body) circuits — making energy supply efficient."),
  ("Transport in Plants", "Xylem raises water by root pressure and transpiration pull; phloem actively transports food from leaves to storage organs.")],
 ["Blood = plasma + RBC + WBC + platelets",
  "Haemoglobin carries oxygen and contains iron",
  "Arteries go away from the heart; veins come toward it",
  "Humans have a four-chambered heart and double circulation",
  "The lymphatic system absorbs fats and helps in defence",
  "Xylem transports water and minerals; phloem transports food"],
 ["Learn the names and order of the heart's chambers",
  "Make a comparison table of arteries vs veins",
  "Link transpiration pull and root pressure with xylem transport"],
 ["Not all arteries carry pure blood — the pulmonary artery carries impure blood",
  "Do not swap the functions of xylem and phloem"],
 ["Be careful with questions on the pulmonary artery — it is the exception",
  "For food transport in plants, choose phloem"],
 ["A-for-Away — Arteries carry blood Away from the heart",
  "'Xy-water, Phlo-food' — xylem for water, phloem for food"],
 ["Components of blood and their functions are asked directly",
  "Functions of xylem and phloem are asked repeatedly"],
 ["Four components of blood and their functions",
  "Four chambers of the heart",
  "Difference between arteries and veins",
  "Roles of xylem and phloem in plants"],
 "Blood consists of plasma, RBCs, WBCs and platelets, and the four-chambered heart pumps it around the body with double circulation. Arteries carry blood away from the heart and veins bring it back. In plants, xylem moves water and minerals upward while phloem transports food.")}))

CH.append(("chapter-10", "B10", 10, "वृद्धि, विकास एवं किशोरावस्था", "Growth, Development & Adolescence",
"वृद्धि, किशोरावस्था के परिवर्तन और हार्मोन की भूमिका।",
"Growth, changes of adolescence and the role of hormones.",
{"hi": N(
 "जन्म से वयस्क होने तक शरीर में लगातार वृद्धि और विकास होता है। किशोरावस्था (लगभग 11–17 वर्ष) में हार्मोनों के प्रभाव से शारीरिक और मानसिक परिवर्तन आते हैं, जिसे यौवनारंभ कहा जाता है। यही अवधि में लिंग-अंगों की परिपक्वता और ग्रंथियों की सक्रियता बढ़ती है।",
 "लड़कों में स्वर भारी होना (एडम्स एप्पल) और लड़कियों में स्तनों का विकास किशोरावस्था के स्पष्ट परिवर्तन हैं।",
 [("वृद्धि एवं विकास", "वृद्धि आकार में वृद्धि है जबकि विकास क्रमबद्ध परिवर्तनों से जटिलता और परिपक्वता की ओर बढ़ना है।"),
  ("किशोरावस्था एवं यौवनारंभ", "किशोरावस्था में लड़कों में टेस्टोस्टेरोन और लड़कियों में एस्ट्रोजन के प्रभाव से द्वितीयक लैंगिक लक्षण विकसित होते हैं।"),
  ("मुख्य हार्मोन", "वृद्धि हार्मोन (पिट्यूटरी), थायरॉक्सिन (थायरॉइड), इंसुलिन (अग्न्याशय), एड्रेनालिन (अधिवृक्क) — प्रत्येक का एक निश्चित कार्य है।"),
  ("स्वस्थ किशोरावस्था", "संतुलित आहार, व्यायाम, पर्याप्त नींद और मादक पदार्थों से बचाव इस आयु के लिए आवश्यक हैं।")],
 ["वृद्धि आकार में वृद्धि है, विकास कार्य-क्षमता की परिपक्वता है",
  "किशोरावस्था लगभग 11–17 वर्ष की आयु है",
  "टेस्टोस्टेरोन लड़कों में और एस्ट्रोजन लड़कियों में यौवन परिवर्तन लाते हैं",
  "वृद्धि हार्मोन की कमी से बौनापन, अधिकता से विशालकायता",
  "थायरॉक्सिन में आयोडीन होता है; इसकी कमी से घेघा",
  "मादक पदार्थ किशोर मस्तिष्क के विकास को हानि पहुँचाते हैं"],
 ["हार्मोन-ग्रंथि-कार्य का त्रिक जोड़कर याद रखें",
  "प्राथमिक और द्वितीयक लैंगिक लक्षणों में अंतर समझें",
  "आयोडीन-नमक-घेघा संबंध पर प्रश्न आम हैं"],
 ["सभी परिवर्तन रातोंरात नहीं होते — किशोरावस्था कई वर्षों की अवधि है",
  "वृद्धि हार्मोन केवल लंबाई नहीं बढ़ाता — यह समग्र वृद्धि नियंत्रित करता है"],
 ["बौनापन/विशालकायता का प्रश्न हो तो पिट्यूटरी का वृद्धि हार्मोन याद करें",
  "घेघे का कारण पूछा जाए तो आयोडीन की कमी और थायरॉक्सिन जोड़ें"],
 ["T-for-Testosterone = लड़के, E-for-Estrogen = लड़कियाँ",
  "'ग्रोथ-गला' — वृद्धि हार्मोन की ग्रंथि पिट्यूटरी याद रखें"],
 ["हार्मोन और उनके कार्य सीधे पूछे जाते हैं",
  "किशोरावस्था की आयु सीमा पर प्रश्न आते हैं"],
 ["वृद्धि और विकास में अंतर",
  "किशोरावस्था के मुख्य परिवर्तन",
  "मुख्य हार्मोन और उनकी ग्रंथियाँ",
  "आयोडीन की कमी के परिणाम"],
 "जन्म से वयस्कता तक शरीर में वृद्धि और विकास चलता रहता है। किशोरावस्था में टेस्टोस्टेरोन और एस्ट्रोजन के प्रभाव से यौवन परिवर्तन आते हैं। वृद्धि हार्मोन, थायरॉक्सिन, इंसुलिन और एड्रेनालिन जैसे हार्मोन शरीर के विकास और नियंत्रण में निर्णायक भूमिका रखते हैं। संतुलित आहार और स्वस्थ आदतें इस अवस्था को सुरक्षित रखती हैं।"),
 "en": N(
 "From birth to adulthood the body grows and develops continuously. In adolescence (about 11–17 years) hormones cause physical and mental changes called puberty, during which reproductive organs mature and glands become more active.",
 "Deepening of voice (Adam's apple) in boys and breast development in girls are clear changes of adolescence.",
 [("Growth and Development", "Growth is increase in size, while development is the ordered progress towards complexity and maturity."),
  ("Adolescence and Puberty", "In adolescence, testosterone in boys and oestrogen in girls develop secondary sexual characters."),
  ("Main Hormones", "Growth hormone (pituitary), thyroxine (thyroid), insulin (pancreas), adrenaline (adrenal) — each has a defined role."),
  ("Healthy Adolescence", "Balanced diet, exercise, adequate sleep and avoiding intoxicants are essential at this age.")],
 ["Growth is increase in size; development is maturation of function",
  "Adolescence is roughly 11–17 years of age",
  "Testosterone (boys) and oestrogen (girls) bring puberty changes",
  "Deficiency of growth hormone causes dwarfism; excess causes gigantism",
  "Thyroxine contains iodine; its deficiency causes goitre",
  "Intoxicants harm the developing adolescent brain"],
 ["Learn hormone-gland-function triplets",
  "Understand the difference between primary and secondary sexual characters",
  "Questions on iodised salt and goitre are common"],
 ["Changes do not happen overnight — adolescence spans several years",
  "Growth hormone does not only increase height — it controls overall growth"],
 ["For dwarfism/gigantism questions, recall the growth hormone of the pituitary",
  "For goitre, link iodine deficiency with thyroxine"],
 ["T-for-Testosterone = boys; E-for-Estrogen = girls",
  "'Growth-gland' — remember the pituitary for growth hormone"],
 ["Hormones and their functions are asked directly",
  "The age range of adolescence appears in questions"],
 ["Difference between growth and development",
  "Main changes of adolescence",
  "Key hormones and their glands",
  "Effects of iodine deficiency"],
 "The body grows and develops from birth to adulthood. In adolescence, testosterone and oestrogen bring the changes of puberty. Hormones like growth hormone, thyroxine, insulin and adrenaline play decisive roles in development and control. Balanced diet and healthy habits keep this stage safe.")}))

CH.append(("chapter-11", "B11", 11, "स्वास्थ्य, रोग एवं सूक्ष्मजीव", "Health, Disease & Microorganisms",
"स्वास्थ्य, रोगों के प्रकार और सूक्ष्मजीवों के लाभ-हानि।",
"Health, types of diseases and the benefits/harms of microorganisms.",
{"hi": N(
 "स्वास्थ्य केवल रोग का अभाव नहीं बल्कि शारीरिक, मानसिक और सामाजिक कल्याण की अवस्था है। रोग संक्रामक (एक व्यक्ति से दूसरे को फैलने वाले) और असंक्रामक (जैसे मधुमेह) होते हैं। जीवाणु, विषाणु, कवक और प्रोटोजोआ जैसे सूक्ष्मजीव कभी उपयोगी (दही, एंटीबायोटिक) और कभी हानिकारक (टाइफाइड, कोविड) होते हैं।",
 "टीकाकरण में मृत या क्षीण रोगाणु देकर शरीर को रोग से लड़ने की क्षमता विकसित कर ली जाती है।",
 [("स्वास्थ्य एवं रोग", "संतुलित आहार, स्वच्छता, व्यायाम और टीकाकरण से स्वास्थ्य बना रहता है; रोग शरीर की सामान्य क्रिया को बिगाड़ता है।"),
  ("संक्रामक बनाम असंक्रामक रोग", "संक्रामक रोग जीवाणु/विषाणु आदि से फैलते हैं (कोलेरा, खसरा); असंक्रामक रोग जीवनशैली या कमी से होते हैं (मधुमेह, रक्ताल्पता)।"),
  ("रोगाणुओं से रक्षा", "टीकाकरण (जैसे BCG, पोलियो), एंटीबायोटिक (जीवाणुरोधी) और स्वच्छ आदतें रोगों से बचाती हैं।"),
  ("उपयोगी सूक्ष्मजीव", "यीस्ट (डबल रोटी, मदिरा), लैक्टोबैसिलस (दही), एंटीबायोटिक निर्माण और जैव-उर्वरक में सूक्ष्मजीव उपयोगी हैं।")],
 ["स्वास्थ्य शारीरिक-मानसिक-सामाजिक कल्याण की अवस्था है",
  "संक्रामक रोग रोगाणुओं से, असंक्रामक जीवनशैली/कमी से होते हैं",
  "जीवाणुजनित रोग — टाइफाइड, कोलेरा; विषाणुजनित — खसरा, पोलियो",
  "एंटीबायोटिक केवल जीवाणु रोगों में कारगर हैं",
  "टीका पूर्व-रक्षा देता है, एंटीबायोटिक उपचार करता है",
  "मलेरिया प्रोटोजोआ (प्लाज्मोडियम) से और मच्छर-जनित रोगों में गिना जाता है"],
 ["रोग और उसके रोगाणु के जोड़े (कोलेरा-जीवाणु, मलेरिया-प्रोटोजोआ) रटें",
  "संक्रामक रोगों के फैलने के मार्ग — वायु, जल, संपर्क, वाहक",
  "टीकाकरण का सिद्धांत और सामान्य टीकों के नाम याद रखें"],
 ["सभी रोग संक्रामक नहीं होते — मधुमेह और रक्ताल्पता असंक्रामक हैं",
  "एंटीबायोटिक विषाणु रोगों (जैसे सर्दी) में कारगर नहीं हैं"],
 ["रोग का नाम देखकर पहले उसका रोगाणु-वर्ग पहचानें — जीवाणु, विषाणु, प्रोटोजोआ या कवक",
  "फैलने का माध्यम पूछा जाए तो वाहक (मच्छर, मक्खी) और जल/वायु दोनों विकल्प जाँचें"],
 ["कोलेरा-जीवाणु, मलेरिया-मच्छर जैसे जोड़े कहानी-शैली में याद करें",
  "'V-for-Virus, V-for-Vaccine' — टीका प्रायः विषाणु रोगों के लिए प्रसिद्ध है"],
 ["रोग-रोगाणु के जोड़े परीक्षा में बार-बार पूछे जाते हैं",
  "टीका और एंटीबायोटिक के अंतर पर प्रश्न आम है"],
 ["स्वास्थ्य की परिभाषा",
  "संक्रामक-असंक्रामक रोगों में अंतर",
  "प्रमुख रोग और उनके रोगाणु",
  "टीकाकरण और एंटीबायोटिक की भूमिका"],
 "स्वास्थ्य शारीरिक, मानसिक और सामाजिक कल्याण की अवस्था है। रोग संक्रामक और असंक्रामक प्रकार के होते हैं और संक्रामक रोग जीवाणु, विषाणु, कवक या प्रोटोजोआ से फैलते हैं। टीकाकरण और एंटीबायोटिक रोगों से बचाव व उपचार करते हैं, जबकि अनेक सूक्ष्मजीव दही, डबल रोटी और एंटीबायोटिक निर्माण में उपयोगी हैं।"),
 "en": N(
 "Health is not merely absence of disease but a state of physical, mental and social well-being. Diseases are infectious (spreading person to person) or non-infectious (like diabetes). Microorganisms such as bacteria, viruses, fungi and protozoa may be useful (curd, antibiotics) or harmful (typhoid, COVID).",
 "Vaccination gives the body the ability to fight a disease by introducing dead or weakened germs.",
 [("Health and Disease", "Balanced diet, cleanliness, exercise and vaccination maintain health; disease disturbs normal body function."),
  ("Infectious vs Non-infectious Diseases", "Infectious diseases spread by germs (cholera, measles); non-infectious ones arise from lifestyle or deficiency (diabetes, anaemia)."),
  ("Protection from Germs", "Vaccination (e.g. BCG, polio), antibiotics (against bacteria) and hygienic habits prevent disease."),
  ("Useful Microorganisms", "Yeast (bread, alcohol), Lactobacillus (curd), antibiotic production and biofertilisers use microorganisms.")],
 ["Health is a state of physical, mental and social well-being",
  "Infectious diseases come from germs; non-infectious from lifestyle or deficiency",
  "Bacterial diseases — typhoid, cholera; viral — measles, polio",
  "Antibiotics work only against bacterial diseases",
  "Vaccines protect beforehand; antibiotics treat infection",
  "Malaria is caused by a protozoan (Plasmodium) and is mosquito-borne"],
 ["Memorise disease-germ pairs (cholera-bacteria, malaria-protozoa)",
  "Learn the modes of spread — air, water, contact, vectors",
  "Remember the principle of vaccination and common vaccines"],
 ["Not all diseases are infectious — diabetes and anaemia are non-infectious",
  "Antibiotics do not work on viral diseases like the common cold"],
 ["Identify the germ class first from the disease name — bacteria, virus, protozoan or fungus",
  "When asked how a disease spreads, check both vectors and water/air routes"],
 ["Remember pairs like cholera-bacteria and malaria-mosquito as mini stories",
  "'V-for-Virus, V-for-Vaccine' — vaccines are famous for viral diseases"],
 ["Disease-germ pairs are asked repeatedly",
  "The difference between vaccine and antibiotic is a common question"],
 ["Definition of health",
  "Difference between infectious and non-infectious diseases",
  "Major diseases and their germs",
  "Role of vaccination and antibiotics"],
 "Health is a state of complete well-being. Diseases are infectious or non-infectious, and infectious ones spread by bacteria, viruses, fungi or protozoa. Vaccination and antibiotics protect and treat, while many microorganisms are useful in curd, bread and antibiotic production.")}))

CH.append(("chapter-12", "B12", 12, "पर्यावरण, पारितंत्र एवं प्राकृतिक संसाधन", "Environment, Ecosystems & Natural Resources",
"पारितंत्र, खाद्य श्रृंखला और संसाधन संरक्षण।",
"Ecosystems, food chains and conservation of resources.",
{"hi": N(
 "सभी जीव और उनका भौतिक पर्यावरण मिलकर पारितंत्र बनाते हैं, जिसमें ऊर्जा सूर्य से निर्माताओं (पौधों) द्वारा ग्रहण कर खाद्य श्रृंखला से आगे बहती है। मानव गतिविधियों से अपशिष्ट, प्रदूषण और संसाधनों का क्षरण हो रहा है, इसलिए जल, वन और वन्यजीव संरक्षण आवश्यक है।",
 "एक खेत में फसल → टिड्डा → गिरगिट → साँप → ईगल की श्रृंखला खाद्य श्रृंखला का सरल उदाहरण है।",
 [("पारितंत्र एवं इसके घटक", "निर्जीव (जल, मिट्टी, वायु) और जीवीय (निर्माता, उपभोक्ता, अपघटक) घटक मिलकर पारितंत्र बनाते हैं।"),
  ("खाद्य श्रृंखला एवं खाद्य जाल", "ऊर्जा सूर्य → पौधा → शाकाहारी → मांसाहारी क्रम में बहती है; अनेक श्रृंखलाएँ मिलकर खाद्य जाल बनाती हैं और हर स्तर पर ऊर्जा घटती है।"),
  ("अपघटक एवं पदार्थ चक्र", "अपघटक मृत कार्बनिक पदार्थ को सरल रूप में तोड़कर पोषक तत्वों को पुनः मिट्टी में लौटाते हैं।"),
  ("संसाधन संरक्षण", "जल-बचत, वनीकरण, वन्यजीव अभयारण्य, 5R (Refuse, Reduce, Reuse, Repurpose, Recycle) और सतत उपयोग संसाधनों को भविष्य के लिए बचाते हैं।")],
 ["पारितंत्र = जीवीय + निर्जीव घटकों का अंतःक्रिया तंत्र",
  "सूर्य सभी पारितंत्रों का अंतिम ऊर्जा स्रोत है",
  "खाद्य श्रृंखला में ऊर्जा हर स्तर पर लगभग 10% ही आगे जाती है",
  "हरित पौधे निर्माता, जंतु उपभोक्ता और जीवाणु-कवक अपघटक हैं",
  "जैव-अपघटनीय अपशिष्ट (प्लास्टिक) पर्यावरण के लिए गंभीर समस्या है",
  "ओजोन परत सूर्य की पराबैंगनी किरणों से रक्षा करती है"],
 ["खाद्य श्रृंखला में पोषण स्तरों का क्रम और ऊर्जा-प्रवाह की दिशा याद रखें",
  "जैव-अपघटनीय बनाम अनैव-अपघटनीय अपशिष्ट के उदाहरण जोड़ें",
  "5R के नाम क्रम से दोहराएँ"],
 ["खाद्य श्रृंखला में ऊर्जा चक्रीय नहीं बहती — वह एक ही दिशा में बहती है",
  "सभी अपशिष्ट जैव-अपघटनीय नहीं होते — प्लास्टिक अनैव-अपघटनीय है"],
 ["ऊर्जा-प्रवाह का प्रश्न हो तो दिशा (सूर्य→निर्माता→उपभोक्ता) देखें",
  "अपघटक की बात आए तो जीवाणु और कवक चुनें"],
 ["ऊर्जा-प्रवाह को 'सू-पौ-शा-मा' (सूर्य, पौधा, शाकाहारी, मांसाहारी) क्रम से याद करें",
  "5R को 'R-R-R-R-R' गिनकर दोहराएँ"],
 ["खाद्य श्रृंखला और पोषण स्तर पर प्रश्न बार-बार पूछे जाते हैं",
  "ओजोस्फीयर और CFC का संबंध परीक्षा में आता है"],
 ["पारितंत्र के घटक",
  "खाद्य श्रृंखला और ऊर्जा प्रवाह",
  "अपघटकों की भूमिका",
  "प्राकृतिक संसाधनों के संरक्षण के उपाय"],
 "जीव और उनका पर्यावरण मिलकर पारितंत्र बनाते हैं जिसमें सूर्य से आई ऊर्जा निर्माताओं से खाद्य श्रृंखला द्वारा उपभोक्ताओं तक बहती है और अपघटक पोषक तत्व पुनः मिट्टी में लौटाते हैं। मानव अपशिष्ट और अति-दोहन से संतुलन बिगड़ रहा है; जल, वन और वन्यजीव संरक्षण तथा 5R अपनाकर सतत विकास संभव है।"),
 "en": N(
 "All organisms and their physical environment together form an ecosystem, where energy from the sun is captured by producers (plants) and flows through food chains. Human activities create waste, pollution and resource depletion, making conservation of water, forests and wildlife essential.",
 "In a field, crop → grasshopper → garden lizard → snake → eagle is a simple food chain.",
 [("Ecosystem and its Components", "Abiotic (water, soil, air) and biotic (producers, consumers, decomposers) components together form an ecosystem."),
  ("Food Chain and Food Web", "Energy flows sun → plant → herbivore → carnivore; many chains interlink into a food web and energy decreases at every level."),
  ("Decomposers and Material Cycles", "Decomposers break dead organic matter into simpler substances and return nutrients to the soil."),
  ("Conservation of Resources", "Water saving, afforestation, wildlife sanctuaries, the 5Rs (Refuse, Reduce, Reuse, Repurpose, Recycle) and sustainable use preserve resources for the future.")],
 ["An ecosystem = interacting biotic and abiotic components",
  "The sun is the ultimate energy source of every ecosystem",
  "Only about 10% of energy passes to each next level in a food chain",
  "Green plants are producers, animals are consumers, bacteria-fungi are decomposers",
  "Non-biodegradable waste (plastic) is a serious environmental problem",
  "The ozone layer protects from the Sun's ultraviolet rays"],
 ["Learn the order of trophic levels and the one-way direction of energy flow",
  "Pair examples of biodegradable vs non-biodegradable waste",
  "Repeat the names of the 5Rs in order"],
 ["Energy in a food chain is not cyclical — it flows in one direction only",
  "Not all waste is biodegradable — plastic is non-biodegradable"],
 ["For energy-flow questions, check the direction (sun→producer→consumer)",
  "When decomposers are mentioned, choose bacteria and fungi"],
 ["Remember energy flow as Sun-Plant-Herbivore-Carnivore in order",
  "Count the 5Rs on five fingers"],
 ["Food chains and trophic levels are asked repeatedly",
  "The ozone layer and CFC link appears in exams"],
 ["Components of an ecosystem",
  "Food chain and energy flow",
  "Role of decomposers",
  "Measures to conserve natural resources"],
 "Organisms and their environment form ecosystems where solar energy flows from producers through food chains, and decomposers return nutrients to the soil. Human waste and overuse disturb this balance; conservation of water, forests and wildlife along with the 5Rs makes sustainable development possible.")}))

def build(ch):
    (d, code, num, nhi, nen, dhi, den, notes) = ch
    meta = dict(SUBJECT)
    meta.update({
        "chapter": d,
        "chapterNumber": num,
        "code": code,
        "chapterName": {"hi": nhi, "en": nen},
        "mockQuestionCount": 30,
        "practiceQuestionTarget": 150,
        "mockTestTarget": 5,
        "topics": [],
        "notes": notes,
    })
    return d, meta

if __name__ == "__main__":
    for ch in CH:
        d, meta = build(ch)
        p = os.path.join(OUT, d)
        os.makedirs(p, exist_ok=True)
        with open(os.path.join(p, "meta.json"), "w", encoding="utf-8") as f:
            json.dump(meta, f, ensure_ascii=False, indent=2)
            f.write("\n")
        with open(os.path.join(p, "questions.json"), "w", encoding="utf-8") as f:
            json.dump({"questions": []}, f, ensure_ascii=False, indent=2)
            f.write("\n")
        print("wrote", os.path.join(OUT, d))
    print("biology new chapters:", len(CH))
