# -*- coding: utf-8 -*-
"""P01 Part-2 — Measurement, Units & Scientific Investigation (physics/chapter-01).
74 items: length-mass-time-measurement 37 (E15/M16/H6) + error-precision 37 (E14/M17/H6).
Tuple: (topic, difficulty, question_hi, question_en, options_hi[4], options_en[4], correct_idx, expl_hi, expl_hi)
Scope: instruments (metre scale / vernier callipers / screw gauge / balance / clock-stopwatch), mass-vs-weight trap
(mass kg invariant; weight = force in newton), error/averaging/parallax, accuracy vs precision.
"""

PART2 = [
    # ================= LENGTH, MASS & TIME MEASUREMENT — 37 (E15/M16/H6) =================
    ("length-mass-time", "easy",
     "लंबाई मापने का सामान्य उपकरण कौन-सा है?",
     "Which is the common instrument for measuring length?",
     ["मीटर स्केल", "तुला", "स्टॉपवॉच", "थर्मामीटर"],
     ["Metre scale", "Balance", "Stopwatch", "Thermometer"],
     0,
     "लंबाई की सामान्य माप मीटर स्केल से होती है।",
     "Ordinary length measurement is done with a metre scale."),

    ("length-mass-time", "easy",
     "द्रव्यमान (mass) मापने का उपकरण कौन-सा है?",
     "Which instrument is used to measure mass?",
     ["तुला (balance)", "मीटर स्केल", "स्टॉपवॉच", "पेंचमापी"],
     ["Balance", "Metre scale", "Stopwatch", "Screw gauge"],
     0,
     "द्रव्यमान तुला से मापा जाता है — सेकंडों में नहीं, किलोग्राम में।",
     "Mass is measured with a balance — in kilograms, not seconds."),

    ("length-mass-time", "easy",
     "समय मापने के लिए कौन-से उपकरण प्रयुक्त होते हैं?",
     "Which instruments are used to measure time?",
     ["घड़ी और स्टॉपवॉच", "तुला और स्केल", "स्क्रू गेज और घड़ी", "थर्मामीटर और तुला"],
     ["Clock and stopwatch", "Balance and scale", "Screw gauge and clock", "Thermometer and balance"],
     0,
     "घड़ी सामान्य समय के लिए, स्टॉपवॉच दौड़-प्रयोग जैसे छोटे अंतराल के लिए।",
     "The clock for ordinary time, the stopwatch for short intervals like races and experiments."),

    ("length-mass-time", "easy",
     "कमरे की लंबाई मापने के लिए सबसे उपयुक्त उपकरण क्या है?",
     "What is the most suitable instrument for measuring a room's length?",
     ["मीटर की फीता/स्केल", "पेंचमापी (स्क्रू गेज)", "वर्नियर कैलिपर्स", "स्टॉपवॉच"],
     ["A metre tape/scale", "Screw gauge", "Vernier callipers", "Stopwatch"],
     0,
     "राशि के आकार के अनुसार उपकरण — कमरे जैसी बड़ी लंबाई मीटर फीते से।",
     "The instrument follows the size of the job — room-sized lengths need a metre tape."),

    ("length-mass-time", "easy",
     "तार की मोटाई जैसी बहुत छोटी लंबाई कौन-सा उपकरण मापता है?",
     "Which instrument measures very small lengths like a wire's thickness?",
     ["पेंचमापी (स्क्रू गेज)", "मीटर स्केल", "घड़ी", "तुला"],
     ["Screw gauge", "Metre scale", "Clock", "Balance"],
     0,
     "जितना बारीक काम, उतना बारीक औज़ार — तार की मोटाई स्क्रू गेज का काम।",
     "The finer the job, the finer the tool — wire thickness is the screw gauge's work."),

    ("length-mass-time", "easy",
     "वर्नियर कैलिपर्स किस राशि के मापन में प्रयुक्त होते हैं?",
     "Vernier callipers are used to measure which quantity?",
     ["लंबाई", "द्रव्यमान", "समय", "ताप"],
     ["Length", "Mass", "Time", "Temperature"],
     0,
     "वर्नियर कैलिपर्स लंबाई के सूक्ष्म मापन का उपकरण है।",
     "Vernier callipers are an instrument for fine length measurement."),

    ("length-mass-time", "easy",
     "द्रव्यमान का SI मात्रक क्या है?",
     "What is the SI unit of mass?",
     ["किलोग्राम", "न्यूटन", "सेकंड", "मीटर"],
     ["Kilogram", "Newton", "Second", "Metre"],
     0,
     "द्रव्यमान — किलोग्राम; न्यूटन भार की इकाई है।",
     "Mass — kilogram; the newton is the unit of weight."),

    ("length-mass-time", "easy",
     "भार (weight) किस प्रकार की भौतिक राशि है?",
     "What kind of physical quantity is weight?",
     ["बल", "लंबाई", "समय", "पदार्थ की मात्रा"],
     ["A force", "A length", "A time", "An amount of substance"],
     0,
     "भार वह बल है जिससे पृथ्वी पिंड को खींचती है — इसलिए उसकी इकाई न्यूटन।",
     "Weight is the force with which the earth pulls a body — hence its unit is the newton."),

    ("length-mass-time", "easy",
     "तुला (balance) वास्तव में क्या मापती है?",
     "What does a balance actually measure?",
     ["द्रव्यमान", "भार", "आयतन", "लंबाई"],
     ["Mass", "Weight", "Volume", "Length"],
     0,
     "तुला दोनों पहलुओं के द्रव्यमान की तुलना करती है — भार नहीं।",
     "A balance compares the masses on its two pans — not their weights."),

    ("length-mass-time", "easy",
     "किताब की लंबाई मापते समय आँख कहाँ रखनी चाहिए?",
     "Where should the eye be placed while measuring the length of a book?",
     ["पाठ्यांक (mark) के ठीक ऊपर, लंबवत दिशा में", "तिरछी दिशा में", "बाईं ओर से", "दाईं ओर से"],
     ["Directly above the mark, perpendicular", "At a slant", "From the left side", "From the right side"],
     0,
     "लंबवत दृष्टि ही वह देखती है जो स्केल पर है — तिरछी नज़र पाठ्यांक बदल देती है।",
     "Only a perpendicular gaze sees what the scale shows — a slanted view shifts the reading."),

    ("length-mass-time", "easy",
     "स्कूल की दौड़ में समय कौन-सा उपकरण रिकॉर्ड करता है?",
     "Which instrument records time in a school race?",
     ["स्टॉपवॉच", "तुला", "मीटर स्केल", "वर्नियर कैलिपर्स"],
     ["Stopwatch", "Balance", "Metre scale", "Vernier callipers"],
     0,
     "स्टॉपवॉच के बटन से सेकंडों का हिसाब — दौड़ का साथी।",
     "The stopwatch's button counts the seconds — the runner's companion."),

    ("length-mass-time", "easy",
     "कपड़े की दुकान पर कपड़ा किस उपकरण से मापा जाता है?",
     "In a cloth shop, cloth is measured with which instrument?",
     ["मीटर की पैमाइश/फीता", "स्क्रू गेज", "तुला", "स्टॉपवॉच"],
     ["A metre scale/tape", "Screw gauge", "Balance", "Stopwatch"],
     0,
     "कपड़े की लंबाई मीटर में — मीटर की छड़ी/फीता से।",
     "Cloth length in metres — measured by the metre stick or tape."),

    ("length-mass-time", "easy",
     "भार की SI इकाई क्या है?",
     "What is the SI unit of weight?",
     ["न्यूटन", "किलोग्राम", "जूल", "वाट"],
     ["Newton", "Kilogram", "Joule", "Watt"],
     0,
     "भार बल है → न्यूटन; किलोग्राम द्रव्यमान की इकाई है।",
     "Weight is a force → newton; the kilogram belongs to mass."),

    ("length-mass-time", "easy",
     "निम्न में से त्रुटिपूर्ण कथन कौन-सा है?",
     "Which statement is INCORRECT?",
     ["द्रव्यमान और भार एक ही राशि हैं", "द्रव्यमान की इकाई किलोग्राम है", "भार एक बल है", "भार की इकाई न्यूटन है"],
     ["Mass and weight are the same quantity", "The unit of mass is kilogram", "Weight is a force", "The unit of weight is newton"],
     0,
     "पहला कथन ही जाल है — द्रव्यमान पदार्थ की मात्रा, भार खिंचाव का बल।",
     "The first statement is the trap — mass is the amount of matter, weight the pull of gravity."),

    ("length-mass-time", "easy",
     "किराना दुकान पर तौलने के लिए कौन-सा उपकरण उपयुक्त है?",
     "Which instrument is appropriate for weighing goods at a grocery shop?",
     ["तुला", "स्टॉपवॉच", "वर्नियर कैलिपर्स", "मीटर स्केल"],
     ["Balance", "Stopwatch", "Vernier callipers", "Metre scale"],
     0,
     "तौल = द्रव्यमान की माप = तुला का काम।",
     "Weighing = measuring mass = the balance's job."),

    ("length-mass-time", "medium",
     "डोरी की मोटाई और कमरे की लंबाई मापने के लिए क्रमशः कौन-से उपकरण उपयुक्त हैं?",
     "Which instruments suit measuring a rope's thickness and a room's length, respectively?",
     ["पेंचमापी और मीटर फीता", "मीटर फीता और पेंचमापी", "तुला और स्टॉपवॉच", "दोनों के लिए स्टॉपवॉच"],
     ["Screw gauge and metre tape", "Metre tape and screw gauge", "Balance and stopwatch", "Stopwatch for both"],
     0,
     "बारीक काम को बारीक औज़ार, बड़े काम को लंबा औज़ार — राशि के आकार से उपकरण बदलता है।",
     "Fine job, fine tool; large job, long tool — the instrument changes with the size of the quantity."),

    ("length-mass-time", "medium",
     "किताब की मोटाई नापने के लिए मीटर स्केल की तुलना में वर्नियर कैलिपर्स क्यों बेहतर हैं?",
     "Why are vernier callipers better than a metre scale for measuring a book's thickness?",
     ["कैलिपर्स में लघुत्तम माप (अंतराल) बहुत छोटा होता है — सूक्ष्म अंतर भी पकड़ में आता है", "कैलिपर्स में रंग अच्छा होता है", "स्केल टूट जाता है", "कैलिपर्स हल्के होते हैं"],
     ["The callipers' least interval is very small — even tiny differences are caught", "The callipers have a nicer colour", "The scale breaks", "The callipers are lighter"],
     0,
     "जिस उपकरण की न्यूनतम पहचान जितनी बारीक, मापन उतना सूक्ष्म।",
     "The finer an instrument's smallest readable step, the finer its measurement."),

    ("length-mass-time", "medium",
     "चाँद पर जाने पर किसी व्यक्ति का द्रव्यमान क्या होगा?",
     "What happens to a person's mass on going to the moon?",
     ["वह अपरिवर्तित रहती है", "शून्य हो जाती है", "छह गुना बढ़ जाती है", "आधी हो जाती है"],
     ["It remains unchanged", "It becomes zero", "It becomes six times", "It halves"],
     0,
     "द्रव्यमान पदार्थ की अपनी संपत्ति है — जगह बदलने से नहीं बदलती।",
     "Mass is the matter's own property — changing place does not change it."),

    ("length-mass-time", "medium",
     "चाँद पर व्यक्ति का भार क्यों कम हो जाता है?",
     "Why does a person's weight decrease on the moon?",
     ["चाँद का गुरुत्वीय खिंचाव पृथ्वी से कम है, और भार वही बल है", "द्रव्यमान कम हो जाता है", "चाँद पर कोई बल नहीं होता", "वहाँ तुला नहीं होती"],
     ["The moon's gravitational pull is less than the earth's, and weight is exactly that force", "The mass decreases", "No force exists on the moon", "There is no balance there"],
     0,
     "भार खिंचाव पर टिका है — खिंचाव घटा तो भार घटा; द्रव्यमान ज्यों का त्यों।",
     "Weight rides on pull — less pull, less weight; the mass stays put."),

    ("length-mass-time", "medium",
     "दुकान की मशीन '5 किलो' बताती है — यह तकनीकी रूप से क्या है?",
     "A shop machine shows '5 kilos' — what is this technically?",
     ["वस्तु का द्रव्यमान (किलोग्राम में)", "वस्तु का भार (न्यूटन में)", "वस्तु का आयतन", "वस्तु की लंबाई"],
     ["The goods' mass (in kilograms)", "The goods' weight (in newtons)", "The goods' volume", "The goods' length"],
     0,
     "दैनिक भाषा का 'वज़न' विज्ञान का द्रव्यमान है — किग्रा में; न्यूटन वाला भार अलग राशि।",
     "Daily-life 'weight' is science's mass — in kg; the newton-weight is a different quantity."),

    ("length-mass-time", "medium",
     "दो-पलड़ी तुला में एक पलड़े पर वस्तु और दूसरे पर मानक बाट — तुला संतुलन पर क्या सिद्ध होता है?",
     "On a two-pan balance, goods on one pan and standard weights on the other — what does balance prove?",
     ["दोनों पलड़ों के द्रव्यमान बराबर हैं", "दोनों के भार अलग हैं", "आयतन बराबर है", "लंबाई बराबर है"],
     ["The masses on both pans are equal", "Their weights differ", "Their volumes are equal", "Their lengths are equal"],
     0,
     "संतुलन = द्रव्यमानों की बराबरी की जाँच — इसी से बाट काम करते हैं।",
     "Balance = a test of equal masses — that is how standard weights work."),

    ("length-mass-time", "medium",
     "पैमाइश करते समय आँख तिरछी रखने से पाठ्यांक कैसा हो जाता है?",
     "What happens to the reading if the eye is kept at a slant while measuring?",
     ["पाठ्यांक गलत (त्रुटिपूर्ण) हो जाता है", "पाठ्यांक बिल्कुल सही रहता है", "पाठ्यांक दोगुना हो जाता है", "कोई प्रभाव नहीं"],
     ["The reading becomes wrong (erroneous)", "The reading stays perfectly correct", "The reading doubles", "No effect"],
     0,
     "तिरछी दृष्टि स्केल के चिह्नों को खिसका देखती है — यही दृष्टि-त्रुटि (parallax) है।",
     "A slanted gaze sees the marks shifted — this is the parallax error."),

    ("length-mass-time", "medium",
     "स्केल का शून्य-छोर घिस जाने पर उस स्केल से मापने पर क्या संभावना है?",
     "If the zero end of a scale is worn out, what is likely when measuring with it?",
     ["पाठ्यांक में त्रुटि आ सकती है", "मापन ज्यादा सही हो जाता है", "स्केल लंबा हो जाता है", "कोई फर्क नहीं पड़ता"],
     ["An error can creep into the reading", "The measurement becomes more correct", "The scale becomes longer", "It makes no difference"],
     0,
     "घिसा शून्य आरंभ ही गलत कर देता है — ऐसी स्थिति में किसी पूर्ण चिह्न से मापना बेहतर।",
     "A worn zero corrupts the very start — better to measure from a fully intact mark."),

    ("length-mass-time", "medium",
     "कथन A: द्रव्यमान हर जगह समान रहता है। कथन B: भार हर जगह समान रहता है। कौन-सा सही है?",
     "Statement A: mass stays the same everywhere. Statement B: weight stays the same everywhere. Which is correct?",
     ["केवल A सही", "केवल B सही", "A और B दोनों सही", "दोनों गलत"],
     ["Only A is correct", "Only B is correct", "Both A and B", "Both wrong"],
     0,
     "द्रव्यमान यात्री के साथ नहीं बदलता; भार ग्रह के खिंचाव के साथ बदलता है।",
     "Mass does not change with travel; weight changes with each body's pull."),

    ("length-mass-time", "medium",
     "एयरपोर्ट पर सामान की जाँच 'किलोग्राम' में होती है — यह किस राशि की जाँच है?",
     "Airport baggage is checked in 'kilograms' — which quantity is being checked?",
     ["द्रव्यमान", "भार (बल)", "क्षेत्रफल", "समय"],
     ["Mass", "Weight (force)", "Area", "Time"],
     0,
     "किलोग्राम बोलते ही राशि द्रव्यमान — भार होता तो न्यूटन बोलते।",
     "Say kilogram and the quantity is mass — were it weight, newtons would be spoken."),

    ("length-mass-time", "medium",
     "पेंचमापी (स्क्रू गेज) 'पेंच' के घूमने पर छोटी दूरी कैसे पकड़ता है?",
     "How does a screw gauge catch tiny distances through the turning of its screw?",
     ["पेंच का एक पूरा चक्र बहुत छोटी सीधी गति से जुड़ता है — बड़ा घुमाव, बारीक विस्थापन", "पेंच तार को खा जाता है", "पेंच से तार लंबा हो जाता है", "पेंच को गर्म किया जाता है"],
     ["One full turn of the screw advances only a very small straight step — a big rotation, a fine displacement", "The screw eats the wire", "The screw lengthens the wire", "The screw is heated"],
     0,
     "घूमने-चढ़ने वाले पेंच की सूक्ष्म चाल ही स्क्रू गेज की सूक्ष्म पकड़ का रहस्य है।",
     "The fine travel of the turning screw is the very secret of the screw gauge's fine grip."),

    ("length-mass-time", "medium",
     "स्टॉपवॉच की तुलना में साधारण दीवार-घड़ी दौड़ के समय के लिए अनुपयुक्त क्यों है?",
     "Why is an ordinary wall clock unsuitable for timing a race compared to a stopwatch?",
     ["स्टॉपवॉच सेकंड-वाले छोटे अंतरालों को तुरंत शुरू-रोक कर पकड़ती है; दीवार घड़ी नहीं", "दीवार घड़ी में बिजली नहीं होती", "स्टॉपवॉच सस्ती होती है", "दीवार घड़ी चलती ही नहीं"],
     ["A stopwatch starts-stops instantly to catch small second-intervals; a wall clock cannot", "A wall clock has no electricity", "A stopwatch is cheaper", "A wall clock does not run"],
     0,
     "दौड़ का समय क्षण-क्षण का खेल है — तत्काल रोकने-चलाने वाला घड़ा चाहिए।",
     "A race is a game of instants — it needs a clock that stops and starts on command."),

    ("length-mass-time", "medium",
     "किसी वस्तु का द्रव्यमान 2 किलोग्राम है — इस कथन से भार के बारे में क्या कहा जा सकता है?",
     "An object's mass is 2 kilograms — what can be said about its weight from this statement?",
     ["सीधे कुछ नहीं — भार बल है जिसकी इकाई न्यूटन है और वह अलग से व्यक्त होता है", "भार भी 2 न्यूटन है", "भार भी 2 किलोग्राम है", "भार शून्य है"],
     ["Nothing directly — weight is a force in newtons, expressed separately", "Weight is also 2 newtons", "Weight is also 2 kilograms", "Weight is zero"],
     0,
     "द्रव्यमान-कथन भार-कथन नहीं — दोनों राशियों की डोरियाँ अलग।",
     "A statement of mass is not a statement of weight — the two quantities hang from separate ropes."),

    ("length-mass-time", "medium",
     "तीन वस्तुएँ — (i) टेबल की लंबाई, (ii) रुई का गुच्छा, (iii) 100 मीटर दौड़। इनके लिए सही उपकरण-क्रम है —",
     "Three jobs — (i) a table's length, (ii) a lump of cotton, (iii) a 100 m race. The correct instrument order is —",
     ["मीटर स्केल, तुला, स्टॉपवॉच", "तुला, स्टॉपवॉच, मीटर स्केल", "स्टॉपवॉच, मीटर स्केल, तुला", "स्क्रू गेज, तुला, घड़ी की कैलाई"],
     ["Metre scale, balance, stopwatch", "Balance, stopwatch, metre scale", "Stopwatch, metre scale, balance", "Screw gauge, balance, a wristwatch"],
     0,
     "राशि पहचानो — लंबाई→स्केल, द्रव्यमान→तुला, समय→स्टॉपवॉच।",
     "Identify the quantity — length→scale, mass→balance, time→stopwatch."),

    ("length-mass-time", "medium",
     "एक ही तराजू पर ग्राम-बाट और किलोग्राम-बाट मिले हों — मापन में यह विविधता किस सूत्र से सटीक रहती है?",
     "A balance set has gram and kilogram weights — by what principle does measurement stay accurate with this mix?",
     ["सभी बाट मानक इकाइयों के दशमलव गुणज हैं — परस्पर निश्चित अनुपात में", "बाटों का रंग एक जैसा है", "बाट किसी भी वज़न के बराबर माने जाते हैं", "तुला को गोल घुमाया जाता है"],
     ["All weights are decimal multiples of the standard unit — in fixed ratios to one another", "The weights share a colour", "Weights are taken equal to any value", "The balance is spun around"],
     0,
     "1 किग्रा = 1000 ग्राम का निश्चित संबंध ही बाटों की मिलीजुली टोकरी को सटीक रखता है।",
     "The fixed relation 1 kg = 1000 g keeps the mixed basket of weights accurate."),

    ("length-mass-time", "medium",
     "यात्रा करते समय द्रव्यमान और भार में से कौन-सी राशि व्यक्ति के साथ 'स्थिर' रहती है?",
     "While travelling, which of the two — mass or weight — stays 'fixed' with the person?",
     ["द्रव्यमान", "भार", "दोनों", "कोई नहीं"],
     ["Mass", "Weight", "Both", "Neither"],
     0,
     "पदार्थ की मात्रा जहाँ वह वहीं; खिंचाव जितना, भार उतना।",
     "The amount of matter travels as it is; the weight answers to each pull."),

    ("length-mass-time", "hard",
     "दो-पलड़ी तुला से कोई अज्ञात वस्तु 200 ग्राम + 50 ग्राम + 10 ग्राम के बाटों से संतुलित होती है — वस्तु का द्रव्यमान कितना है?",
     "On a two-pan balance an unknown object balances with 200 g + 50 g + 10 g weights — what is the object's mass?",
     ["260 ग्राम", "250 ग्राम", "200 ग्राम", "310 ग्राम"],
     ["260 grams", "250 grams", "200 grams", "310 grams"],
     0,
     "200 + 50 + 10 = 260 ग्राम — संतुलन क्षण में दोनों पलड़ों का द्रव्यमान समान।",
     "200 + 50 + 10 = 260 g — at balance the two pans carry equal mass."),

    ("length-mass-time", "hard",
     "किराने की दुकान की भाषा में 'वज़न 5 किलो' और भौतिकी की भाषा में 'भार' — दोनों के बीच का संबंध स्पष्ट कीजिए।",
     "Clarify the relation between the grocery phrase 'weight 5 kilos' and the physics term 'weight'.",
     ["दुकान का 'वज़न' वास्तव में द्रव्यमान है; भौतिकी का भार न्यूटन में मापा जाने वाला बल है", "दोनों एक ही हैं", "दुकान का वज़न भार है और भौतिकी का भार द्रव्यमान", "दोनों आयतन हैं"],
     ["The grocer's 'weight' is actually mass; physics' weight is the force measured in newtons", "Both are the same", "The grocer's weight is force and physics' weight is mass", "Both are volume"],
     0,
     "दैनिक भाषा का 'वज़न' विज्ञान की कसौटी पर द्रव्यमान निकलता है — यही अनुवाद-जाल है।",
     "On science's touchstone, daily 'weight' turns out to be mass — the classic translation trap."),

    ("length-mass-time", "hard",
     "चाँद पर तुला से वस्तु का मापन करने पर परिणाम पृथ्वी जैसा ही क्यों मिलेगा?",
     "Why would measuring an object with a balance on the moon give the same result as on the earth?",
     ["तुला द्रव्यमान तुलना करती है, और द्रव्यमान गुरुत्व से नहीं बदलता", "चाँद पर तुला नहीं चलती", "चाँद का गुरुत्व पृथ्वी जैसा ही है", "वस्तु चाँद पर हल्की हो जाती है"],
     ["A balance compares masses, and mass does not change with gravity", "A balance does not work on the moon", "The moon's gravity equals the earth's", "The object becomes lighter on the moon"],
     0,
     "दोनों पलड़ों पर खिंचाव साथ घटता-बढ़ता है — तुलना वही, द्रव्यमान वही।",
     "The pull on both pans rises and falls together — the comparison, and the mass, stay unchanged."),

    ("length-mass-time", "hard",
     "यदि भार और द्रव्यमान में से किसी एक को 'पिंड का गुण' और दूसरे को 'पिंड पर पड़ने वाला प्रभाव' कहना हो, तो सही मिलान है —",
     "If one of mass/weight is to be called 'the body's own property' and the other 'an effect on the body', the correct matching is —",
     ["द्रव्यमान = पिंड का गुण; भार = पिंड पर पड़ने वाला प्रभाव (गुरुत्वीय बल)", "भार = पिंड का गुण; द्रव्यमान = प्रभाव", "दोनों पिंड के गुण हैं", "दोनों बाहरी प्रभाव हैं"],
     ["Mass = the body's own property; weight = an effect on the body (the gravitational force)", "Weight = the body's property; mass = the effect", "Both are the body's properties", "Both are external effects"],
     0,
     "द्रव्यमान पदार्थ के साथ पैदा होता है; भार वहाँ के खिंचाव से जन्म लेता है।",
     "Mass is born with the matter; weight is born of the pull wherever the matter stands."),

    ("length-mass-time", "hard",
     "स्क्रू गेज बनाम मीटर स्केल — दोनों लंबाई मापते हैं, फिर भी उन्हें अलग-अलग कामों के लिए रखा जाता है। इसका गहरा कारण है —",
     "Screw gauge vs metre scale — both measure length, yet they are reserved for different jobs. The deeper reason is —",
     ["दोनों की न्यूनतम पहचान-क्षमता (बारीकी) भिन्न है — उसी के अनुसार सूक्ष्म/स्थूल काम बँटते हैं", "एक लोहे का और दूसरा लकड़ी का होता है", "एक नई और दूसरा पुरानी होती है", "दोनों में कोई भेद नहीं"],
     ["Their smallest readable fineness differs — fine and coarse jobs are divided accordingly", "One is of iron and the other of wood", "One is new and the other old", "There is no difference"],
     0,
     "औज़ार की बारीकी ही योग्यता है — सूक्ष्म माप सूक्ष्म उपकरण से ही।",
     "An instrument's fineness is its qualification — fine measurements need fine instruments."),

    ("length-mass-time", "hard",
     "एक प्रयोग में गेंद गिराने का समय स्टॉपवॉच से नापा जाता है और गेंद की मात्रा तुला से — रिपोर्ट में 'समय' और 'द्रव्यमान' के साथ क्या अनिवार्य है?",
     "An experiment times a falling ball with a stopwatch and measures its mass with a balance — what must accompany 'time' and 'mass' in the report?",
     ["संख्या के साथ सही मात्रक (सेकंड, किलोग्राम) — अन्यथा रिपोर्ट अर्थहीन", "केवल रंगीन चार्ट", "केवल फोटो", "कुछ भी जरूरी नहीं"],
     ["Correct units with the numbers (seconds, kilograms) — otherwise the report is meaningless", "Only colourful charts", "Only photographs", "Nothing is necessary"],
     0,
     "मापन की रिपोर्ट संख्या-मात्रक की जोड़ी से विधिवत बनती है।",
     "A measurement report is made proper only by the pair of number and unit."),

    # ================= ERROR & PRECISION — 37 (E14/M17/H6) =================
    ("error-precision", "easy",
     "क्या कोई भी मापन बिल्कुल शुद्ध (error-free) हो सकता है?",
     "Can any measurement be absolutely error-free?",
     ["नहीं — हर मापन में कुछ त्रुटि संभव है", "हाँ, हमेशा", "केवल महँगे यंत्रों में", "केवल वैज्ञानिकों के लिए"],
     ["No — some error is possible in every measurement", "Yes, always", "Only in costly instruments", "Only for scientists"],
     0,
     "त्रुटि मापन की छाया है — कम की जा सकती है, मिटाई नहीं।",
     "Error is measurement's shadow — it can be reduced, never erased."),

    ("error-precision", "easy",
     "मापन की त्रुटि कम करने का सरल उपाय क्या है?",
     "What is the simple way to reduce error in measurement?",
     ["कई बार मापकर औसत लेना", "एक ही बार मापना", "अंदाज़ा लगाना", "मापन छोड़ देना"],
     ["Measuring several times and taking the average", "Measuring just once", "Making a guess", "Giving up measuring"],
     0,
     "बार-बार मापने से उतार-चढ़ाव औसत में संतुलित हो जाता है।",
     "Repeated measurements let the ups and downs balance out in the average."),

    ("error-precision", "easy",
     "स्केल से पढ़ते समय सही दृष्टि (eye position) क्यों जरूरी है?",
     "Why is the correct eye position necessary while reading a scale?",
     ["तिरछी दृष्टि पाठ्यांक बदल देती है — त्रुटि आती है", "आँख सुंदर लगती है", "स्केल चमकता है", "इससे समय बचता है"],
     ["A slanted view changes the reading — error creeps in", "The eye looks nice", "The scale shines", "It saves time"],
     0,
     "सीधी दृष्टि = सही पाठ्यांक की पहली शर्त।",
     "A straight gaze = the first condition of a true reading."),

    ("error-precision", "easy",
     "किसी राशि का एक ही मान बार-बार मापा गया — सबसे भरोसेमंद प्रतिनिधि मान कौन-सा माना जाता है?",
     "The same quantity was measured repeatedly — which value is taken as the most trustworthy representative?",
     ["सभी पाठ्यांकों का औसत", "सबसे बड़ा पाठ्यांक", "सबसे छोटा पाठ्यांक", "पहला पाठ्यांक"],
     ["The average of all the readings", "The largest reading", "The smallest reading", "The first reading"],
     0,
     "औसत उतार-चढ़ाव को समेटकर सबसे निकट का अनुमान देता है।",
     "The average gathers the swings and gives the closest estimate."),

    ("error-precision", "easy",
     "'त्रुटि' (error) और 'गलती' (mistake) — दैनिक भाषा में एक जैसे लगते हैं। विज्ञान में त्रुटि का अर्थ है —",
     "'Error' and 'mistake' sound alike in daily language. In science, error means —",
     ["मापन और वास्तविक मान के बीच का स्वाभाविक अंतर", "जान-बूझकर की गई भूल", "नैतिक कमी", "यंत्र चोरी"],
     ["The natural difference between the measured and the true value", "A deliberate slip", "A moral flaw", "Stealing an instrument"],
     0,
     "त्रुटि सही विधि में भी रहती है; गलती लापरवाही से आती है।",
     "Error remains even in a careful method; a mistake comes from carelessness."),

    ("error-precision", "easy",
     "एक ही पेंसिल को चार बार मापा गया — 15.1 सेमी, 15.3 सेमी, 15.2 सेमी, 15.2 सेमी। रिपोर्ट के लिए सर्वोत्तम मान क्या होगा?",
     "One pencil was measured four times — 15.1 cm, 15.3 cm, 15.2 cm, 15.2 cm. What is the best value to report?",
     ["औसत ≈ 15.2 सेमी", "15.1 सेमी", "15.3 सेमी", "15 सेमी"],
     ["The average ≈ 15.2 cm", "15.1 cm", "15.3 cm", "15 cm"],
     0,
     "(15.1 + 15.3 + 15.2 + 15.2) ÷ 4 = 60.8 ÷ 4 = 15.2 सेमी।",
     "(15.1 + 15.3 + 15.2 + 15.2) ÷ 4 = 60.8 ÷ 4 = 15.2 cm."),

    ("error-precision", "easy",
     "पाठ्यांक लेते समय आँख स्केल के चिह्न के ठीक ऊपर हो — इस नियम का कारण है —",
     "The rule 'keep the eye directly above the mark' exists because —",
     ["तिरछी दृष्टि चिह्न को खिसका दिखाती है", "इससे रोशनी बढ़ती है", "इससे स्केल गर्म होता है", "यह केवल शिष्टाचार है"],
     ["A slanted view shows the mark shifted", "It increases light", "It warms the scale", "It is mere etiquette"],
     0,
     "सीधा देखना ही चिह्न को उसकी जगह दिखाता है।",
     "Only a straight look shows the mark in its own place."),

    ("error-precision", "easy",
     "अधिक बार मापने से परिणाम कैसा होता है?",
     "What does measuring more number of times do to the result?",
     ["परिणाम अधिक विश्वसनीय (औसत के रूप में) हो जाता है", "परिणाम बिगड़ जाता है", "परिणाम दोगुना हो जाता है", "कोई असर नहीं"],
     ["The result becomes more reliable (as an average)", "The result worsens", "The result doubles", "No effect"],
     0,
     "अधिक पाठ्यांक = अधिक संतुलन = अधिक विश्वास।",
     "More readings = more balancing = more confidence."),

    ("error-precision", "easy",
     "किसी स्केल का लघुत्तम अंश (smallest division) जितना छोटा हो, मापन उतना —",
     "The smaller the smallest division of a scale, the more —— the measurement.",
     ["सूक्ष्म/बारीक (precise)", "लंबा", "भारी", "तेज़"],
     ["Fine/precise", "Long", "Heavy", "Fast"],
     0,
     "बारीक बँटवारा बारीक माप देती है।",
     "A finer division yields a finer measurement."),

    ("error-precision", "easy",
     "एक विद्यार्थी ने केवल एक बार मापकर परिणाम लिख दिया — उसकी विधि की कमी क्या है?",
     "A student measured only once and wrote the result — what is the weakness of the method?",
     ["एक पाठ्यांक की संयोग-त्रुटि पकड़ में नहीं आती; औसत का मौका ही नहीं", "मापन बहुत सही है", "पेंसिल खराब होगी", "स्केल गायब होगा"],
     ["A single reading can hide a chance error; there is no chance to average", "The measurement is very correct", "The pencil must be faulty", "The scale must be lost"],
     0,
     "एक गवाह पर भरोसा कम — पाठ्यांकों की भीड़ जाँच बनाती है।",
     "One witness earns little trust — a crowd of readings builds the check."),

    ("error-precision", "easy",
     "प्रयोग के परिणाम में त्रुटि की उपस्थिति उसे 'बेकार' नहीं बनाती — शर्त क्या है?",
     "The presence of some error does not make a result useless — what is the condition?",
     ["त्रुटि को मापन-विधि के साथ ईमानदारी से बताया गया हो और उसे कम करने का प्रयास हो", "त्रुटि को छिपाया गया हो", "त्रुटि को दोगुना किया गया हो", "परिणाम रंग-बिरंगा हो"],
     ["The error is honestly stated with the method and efforts are made to reduce it", "The error is hidden", "The error is doubled", "The result is colourful"],
     0,
     "त्रुटि की स्वीकृति विज्ञान की ईमानदारी है — छिपाना बेईमानी।",
     "Admitting error is science's honesty — hiding it is the opposite."),

    ("error-precision", "easy",
     "दोहराया मापन (repeated measurement) मुख्यतः किसे कम करता है?",
     "Repeated measurement mainly reduces —",
     ["पाठ्यांकों के उतार-चढ़ाव (संयोग-भिन्नता) का प्रभाव", "यंत्र की कीमत", "प्रयोग का समय", "कमरे की रोशनी"],
     ["The effect of ups and downs (chance variation) among readings", "The instrument's cost", "The experiment's duration", "The room's lighting"],
     0,
     "औसत संयोग-उतार-चढ़ाव को दबाता है।",
     "Averaging damps the chance swings."),

    ("error-precision", "easy",
     "मापन-पुस्तिका (record book) में पाठ्यांक के साथ क्या सदा लिखा जाना चाहिए?",
     "What should always be written along with the reading in a record book?",
     ["मात्रक", "मौसम", "जूते का नंबर", "मनपसंद गाना"],
     ["The unit", "The weather", "The shoe size", "A favourite song"],
     0,
     "बिना मात्रक पाठ्यांक अधूरा — रिकॉर्ड अर्थहीन।",
     "A unitless reading is incomplete — a meaningless record."),

    ("error-precision", "easy",
     "एक पाठ्यांक दूसरों से बहुत अलग (जैसे 15.2, 15.3, 15.2, 19.9) आए तो पहला कदम क्या होना चाहिए?",
     "If one reading is far apart from the others (like 15.2, 15.3, 15.2, 19.9), what should be the first step?",
     ["उस असामान्य पाठ्यांक की जाँच करना/दोबारा मापना", "उसे चुपचाप सबसे बड़ा मान लेना", "सभी पाठ्यांक फेंक देना", "कुछ न करना"],
     ["Re-check/re-measure that unusual reading", "Silently accept it as the largest", "Throw away all readings", "Do nothing"],
     0,
     "झूलता हुआ मान पहले जाँचो — गलती हो सकती है, त्रुटि नहीं।",
     "First examine the outlier — it may be a mistake, not an error."),

    ("error-precision", "medium",
     "किसी छड़ की लंबाई के चार पाठ्यांक: 2.0 सेमी, 2.2 सेमी, 1.8 सेमी, 2.0 सेमी — औसत पाठ्यांक कितना है?",
     "Four readings of a rod's length: 2.0 cm, 2.2 cm, 1.8 cm, 2.0 cm — what is the average reading?",
     ["2.0 सेमी", "2.2 सेमी", "1.8 सेमी", "8.0 सेमी"],
     ["2.0 cm", "2.2 cm", "1.8 cm", "8.0 cm"],
     0,
     "(2.0 + 2.2 + 1.8 + 2.0) ÷ 4 = 8.0 ÷ 4 = 2.0 सेमी।",
     "(2.0 + 2.2 + 1.8 + 2.0) ÷ 4 = 8.0 ÷ 4 = 2.0 cm."),

    ("error-precision", "medium",
     "तापमान पाठ्यांक: 10.0, 10.2, 9.8, 10.0 (सेल्सियस में) — रिपोर्ट का औसत मान क्या होगा?",
     "Temperature readings: 10.0, 10.2, 9.8, 10.0 (in Celsius) — what is the average value for the report?",
     ["10.0 °C", "10.2 °C", "9.8 °C", "40.0 °C"],
     ["10.0 °C", "10.2 °C", "9.8 °C", "40.0 °C"],
     0,
     "योग 40.0 ÷ 4 = 10.0 °C — ऊपर-नीचे के झोले औसत में संतुलित।",
     "Sum 40.0 ÷ 4 = 10.0 °C — the swings above and below balance in the mean."),

    ("error-precision", "medium",
     "'शुद्धता' (accuracy) का अर्थ क्या है?",
     "What does 'accuracy' mean?",
     ["मापा मान वास्तविक (सही) मान के कितने निकट है", "पाठ्यांकों का आपस में निकट होना", "यंत्र का महँगा होना", "जल्दी नापना"],
     ["How close the measured value is to the true value", "How close the readings are to each other", "How costly the instrument is", "Measuring quickly"],
     0,
     "शुद्धता लक्ष्य से निकटता की बात है — निशाने पर लगाना।",
     "Accuracy is closeness to the target — hitting the mark."),

    ("error-precision", "medium",
     "'परिशुद्धता' (precision) का अर्थ क्या है?",
     "What does 'precision' mean?",
     ["बार-बार किए पाठ्यांक आपस में कितने निकट/संगत हैं", "वास्तविक मान के निकट पहुँचना", "केवल कीमत", "केवल रंग"],
     ["How close/consistent repeated readings are with each other", "Approaching the true value", "Only the cost", "Only the colour"],
     0,
     "परिशुद्धता बाणों का गुच्छा बनाना है — कहीं भी हो, पर साथ-साथ।",
     "Precision is clustering the arrows — anywhere, but together."),

    ("error-precision", "medium",
     "निशानेबाज़ी में बाण एक जगह गुच्छे में लगे, पर वह जगह केंद्र (लक्ष्य) से दूर है — यह स्थिति किसका उदाहरण है?",
     "In archery, arrows land clustered at one spot away from the centre — which concept does this illustrate?",
     ["परिशुद्ध लेकिन अशुद्ध (precise but not accurate)", "शुद्ध लेकिन अपरिशुद्ध", "शुद्ध और परिशुद्ध दोनों", "न शुद्ध न परिशुद्ध"],
     ["Precise but not accurate", "Accurate but not precise", "Both accurate and precise", "Neither"],
     0,
     "गुच्छा = परिशुद्धता; गुच्छा लक्ष्य से दूर = अशुद्धता — दोनों अलग गुण हैं।",
     "The cluster = precision; the cluster off-target = inaccuracy — two separate virtues."),

    ("error-precision", "medium",
     "निशानेबाज़ी में बाण केंद्र के चारों ओर बिखरे, पर उनका औसत केंद्र पर है — यह कैसी स्थिति है?",
     "Arrows scatter around the centre whose average lies on it — what kind of situation is this?",
     ["औसतन शुद्ध, पर अपरिशुद्ध", "परिशुद्ध और शुद्ध", "दोनों नहीं", "केवल परिशुद्ध"],
     ["Accurate on average, but not precise", "Precise and accurate", "Neither", "Only precise"],
     0,
     "बिखराव बताता है — पाठ्यांक संगत नहीं; फिर भी औसत लक्ष्य के पास।",
     "The scatter tells — readings not consistent; and yet their average lies near the aim."),

    ("error-precision", "medium",
     "एक स्केल के चिह्न 1 मिमी अंतराल पर हैं और दूसरे के 1 सेमी पर — सूक्ष्म मापन के लिए कौन-सा उपयुक्त और क्यों?",
     "One scale has marks 1 mm apart, another 1 cm apart — which suits fine measurement and why?",
     ["1 मिमी वाला — उसकी न्यूनतम पहचान बारीक है", "1 सेमी वाला — वह लंबा है", "दोनों समान", "कोई नहीं"],
     ["The 1 mm one — its smallest readable step is finer", "The 1 cm one — it is longer", "Both equal", "Neither"],
     0,
     "जितने बारीक चिह्न, उतना बारीक निर्णय।",
     "The finer the marks, the finer the verdict."),

    ("error-precision", "medium",
     "पाठ्यांक लेते समय सिर बाएँ-दाएँ हिलाने से पाठ्यांक बदल दिखता है — इस प्रभाव का नाम क्या है?",
     "While taking a reading, moving the head left-right makes the reading appear to shift — what is this effect called?",
     ["दृष्टि-त्रुटि (पैरालैक्स)", "शून्य-त्रुटि का रोग", "घर्षण", "चुंबकत्व"],
     ["Parallax error", "Zero-error disease", "Friction", "Magnetism"],
     0,
     "दृष्टि की दिशा बदली तो चिह्न खिसका दिखा — यही पैरालैक्स।",
     "Change the gaze direction and the mark seems to slide — that is parallax."),

    ("error-precision", "medium",
     "पैरालैक्स-त्रुटि से बचने का उपाय क्या है?",
     "What is the way to avoid parallax error?",
     ["आँख को चिह्न के ठीक ऊपर (लंबवत) रखना", "आँख बंद कर नापना", "स्केल को पानी में डुबोना", "दो बार गहरी साँस लेना"],
     ["Keeping the eye directly above the mark (perpendicular)", "Measuring with eyes closed", "Dipping the scale in water", "Taking two deep breaths"],
     0,
     "लंबवत दृष्टि ही शुद्ध दृष्टि।",
     "The perpendicular gaze alone is the true gaze."),

    ("error-precision", "medium",
     "एक विद्यार्थी के चार पाठ्यांक: 12.1, 12.0, 12.2, 12.1 सेमी — ये परिणाम किस गुण दिखाते हैं?",
     "A student's four readings: 12.1, 12.0, 12.2, 12.1 cm — which quality do these results show?",
     ["अच्छी परिशुद्धता (पाठ्यांक संगत हैं)", "अशुद्धता", "कोई गुण नहीं", "मापन-मात्रा में वृद्धि"],
     ["Good precision (the readings are consistent)", "Inaccuracy", "No quality", "An increase in the quantity measured"],
     0,
     "पाठ्यांकों का साथ-साथ रहना ही परिशुद्धता की पहचान।",
     "Readings staying together is the very signature of precision."),

    ("error-precision", "medium",
     "उसी छड़ के दूसरे विद्यार्थी के पाठ्यांक: 11.5, 12.8, 12.1, 11.9 सेमी — इस सेट की कमजोरी क्या है?",
     "Another student's readings of the same rod: 11.5, 12.8, 12.1, 11.9 cm — what is this set's weakness?",
     ["पाठ्यांक बिखरे हुए — परिशुद्धता कम", "पाठ्यांक बहुत संगत हैं", "सभी पाठ्यांक गलत इकाई में", "कोई कमजोरी नहीं"],
     ["The readings are scattered — low precision", "The readings are highly consistent", "All readings are in wrong units", "No weakness"],
     0,
     "फैलाव जितना, संगति उतनी कम।",
     "The wider the spread, the weaker the consistency."),

    ("error-precision", "medium",
     "औसत लेने से पहले सभी पाठ्यांकों को किसी एक मात्रक में क्यों बदलना चाहिए?",
     "Why should all readings be converted to one unit before averaging?",
     ["अलग मात्रकों का औसत अर्थहीन होता है", "इससे कागज बचता है", "मात्रक रंगीन दिखते हैं", "ऐसा कोई नियम नहीं"],
     ["An average of mixed units is meaningless", "It saves paper", "Units look colourful", "No such rule exists"],
     0,
     "सेबों और संतरों का औसत नहीं होता — पहले एक जैसा फल बनाओ।",
     "You cannot average apples and oranges — first make the fruit uniform."),

    ("error-precision", "medium",
     "किसी मापन को 'विश्वसनीय' कहने के लिए विधि-वर्णन में क्या शामिल होना चाहिए?",
     "For a measurement to be called reliable, what should the method description include?",
     ["उपकरण, इकाई, पाठ्यांकों की संख्या और औसत", "केवल अंतिम संख्या", "केवल उपकरण की तस्वीर", "कुछ भी नहीं"],
     ["Instrument, unit, number of readings and the average", "Only the final number", "Only a photo of the instrument", "Nothing"],
     0,
     "पारदर्शी विधि ही परीक्षक की नज़र में विश्वास जीतती है।",
     "A transparent method alone wins the examiner's trust."),

    ("error-precision", "medium",
     "एक पाठ्यांक में 4.5 सेमी लिखने की जगह 45 सेमी लिख गया — यह क्या है?",
     "A reading of 4.5 cm was written as 45 cm — what is this?",
     ["गलती (mistake), त्रुटि (error) नहीं", "शुद्ध त्रुटि", "परिशुद्धता", "इकाई-परिवर्तन"],
     ["A mistake, not an error", "A pure error", "Precision", "Unit conversion"],
     0,
     "लिपि-चूक विधि की त्रुटि नहीं — सावधानी से टलने वाली गलती।",
     "A slip of the pen is not the method's error — a carelessness that care removes."),

    ("error-precision", "medium",
     "एक ही विद्यार्थी एक ही स्केल से पाँच बार मापता है और हर बार लगभग वही मान आता है — फिर भी वास्तविक मान से थोड़ा अंतर रह सकता है। क्यों?",
     "The same student measures five times with the same scale and gets nearly the same value — yet a gap from the true value can remain. Why?",
     ["स्केल की अपनी (नियत) त्रुटि दोहराव से नहीं बदलती — संगति शुद्धता की गारंटी नहीं", "विद्यार्थी ने धोखा दिया", "स्केल रोज़ बदल जाता है", "वास्तविक मान हर दिन बदलता है"],
     ["The scale's own fixed error does not change with repetition — consistency is no guarantee of accuracy", "The student cheated", "The scale changes daily", "The true value changes daily"],
     0,
     "एक ही औज़ार की सारी बातें एक ही तराज़ू पर — दोहराव उस तराज़ू को नहीं बदलता।",
     "Every word of one instrument sits on one scale — repetition does not change that scale."),

    ("error-precision", "medium",
     "कक्षा में दो छात्रों ने एक ही मेज़ मापी — अंतिम रिपोर्ट में अंतर आया। सबसे वैज्ञानिक कदम क्या है?",
     "Two students measured the same table — a difference appeared in the final reports. What is the most scientific step?",
     ["दोनों अपने-अपने सभी पाठ्यांक औसतों सहित साझा करें और विधि की जाँच करें", "अपना ही परिणाम सही मान लें", "तीसरे से न मिलने दें", "मेज़ को छोटा कर दें"],
     ["Share all readings with averages and examine each other's method", "Assume one's own result correct", "Hide it from a third student", "Cut the table shorter"],
     0,
     "मतभेद जाँच का न्योता है — विधि खुले तो सत्य खुलेगा।",
     "A difference is an invitation to examine — open the method and the truth opens too."),

    ("error-precision", "medium",
     "किसी पाठ्यांक-समूह का सबसे बड़ा मान 20.4 सेमी और सबसे छोटा 20.0 सेमी है — यह 0.4 सेमी का अंतर किसका संकेत देता है?",
     "In a set of readings the largest is 20.4 cm and the smallest 20.0 cm — what does this 0.4 cm gap indicate?",
     ["पाठ्यांकों के बिखराव (परिशुद्धता की सीमा) का", "मापी गई वस्तु की लंबाई का", "मात्रक की गलती का", "किसी नियम का उल्लंघन"],
     ["The spread of the readings (the limit of precision)", "The length of the object measured", "A unit mistake", "A violation of law"],
     0,
     "सबसे ऊँचा-नीचे पाठ्यांक का फासला बिखराव की नाप है।",
     "The gap between highest and lowest readings measures the scatter."),

    ("error-precision", "hard",
     "छात्र A के पाठ्यांक वास्तविक मान 20.0 सेमी के बहुत निकट हैं पर आपस में बिखरे; छात्र B के पाठ्यांक परस्पर बहुत निकट हैं पर 19.0 सेमी के आसपास हैं। सही वर्णन है —",
     "Student A's readings lie very near the true value 20.0 cm but scatter among themselves; student B's readings are mutually very close but hover around 19.0 cm. The correct description is —",
     ["A अधिक शुद्ध, B अधिक परिशुद्ध", "A अधिक परिशुद्ध, B अधिक शुद्ध", "दोनों समान", "दोनों में कोई अंतर नहीं"],
     ["A is more accurate, B is more precise", "A is more precise, B is more accurate", "Both are equal", "No difference between them"],
     0,
     "लक्ष्य के पास = शुद्ध; आपस में पास = परिशुद्ध — दो अलग समीक्षाएँ।",
     "Near the target = accurate; near each other = precise — two separate verdicts."),

    ("error-precision", "hard",
     "यदि किसी स्केल का शून्य चिह्न हर पाठ्यांक में ही एक निश्चित खिसकाव देता हो, तो केवल बार-बार मापकर औसत लेने से यह खिसकाव —",
     "If a scale's zero mark imparts a fixed shift to every reading, then merely repeating and averaging will make this shift —",
     ["नहीं हटेगा, क्योंकि वह हर पाठ्यांक में एक जैसा है — औसत में भी वही रहेगा", "तुरंत हट जाएगा", "दोगुना हो जाएगा", "अपने आप उलट जाएगा"],
     ["Not go away, because it sits identically in every reading — the average keeps it", "Disappear at once", "Double itself", "Reverse by itself"],
     0,
     "साझा खिसकाव औसत की छलाँग में भी सवार रहता है — विधि की समीक्षा चाहिए, केवल दोहराव नहीं।",
     "A shared shift rides along even in the average's leap — it needs a review of method, not mere repetition."),

    ("error-precision", "hard",
     "कथन A: औसत लेने से पाठ्यांकों का बिखराव कम प्रभावी होता है। कथन B: औसत लेने से यंत्र की बारीकी (लघुत्तम माप) बदल जाती है। सही विकल्प —",
     "Statement A: averaging weakens the effect of the readings' scatter. Statement B: averaging changes the instrument's fineness (least count). The correct option —",
     ["A सही, B गलत", "A गलत, B सही", "दोनों सही", "दोनों गलत"],
     ["A right, B wrong", "A wrong, B right", "Both right", "Both wrong"],
     0,
     "औसत सांख्यिकी का उपाय है, यंत्र की सीमा का नहीं — बारीकी औज़ार की अपनी धरोहर।",
     "Averaging is a statistical remedy, not the instrument's — fineness stays the tool's own inheritance."),

    ("error-precision", "hard",
     "एक टीम चाहती है कि परिणाम शुद्ध और परिशुद्ध दोनों बनें। सबसे उपयुक्त रणनीति कौन-सी है?",
     "A team wants results to be both accurate and precise. Which is the most suitable strategy?",
     ["बारीक-पहचान वाला शुद्ध (मानक) उपकरण + शुद्ध विधि (लंबवत दृष्टि) + बार-बार मापकर औसत", "केवल एक बार मापना", "महँगा उपकरण खरीदना ही पर्याप्त", "केवल तेज़ गति से मापना"],
     ["A fine, correctly-calibrated instrument + correct method (perpendicular view) + repeated averaging", "Measuring only once", "Buying a costly instrument alone suffices", "Measuring very fast alone"],
     0,
     "शुद्धता औज़ार-विधि से, परिशुद्धता दोहराव से — दोनों की संधि ही आदर्श।",
     "Accuracy from tool-and-method, precision from repetition — their union is the ideal."),

    ("error-precision", "hard",
     "दो स्केल — P की बारीकी 1 मिमी, Q की बारीकी 1 सेमी। एक छोटा अंतर (जैसे किताब की मोटाई में बढ़ोतरी) जाँचना है। कौन-सा चुनें और इस चुनाव का औचित्य क्या है?",
     "Two scales — P's fineness 1 mm, Q's 1 cm. A small difference (like a change in a book's thickness) must be detected. Which to choose and why?",
     ["P — क्योंकि जो अंतर 1 सेमी की बारीकी में छुपा रहेगा, वह 1 मिमी में पकड़ा जाएगा", "Q — वह लंबी है", "कोई भी — दोनों एक जैसे", "दोनों नहीं — तुला चाहिए"],
     ["P — a change hidden at 1 cm fineness becomes visible at 1 mm", "Q — it is longer", "Either — both alike", "Neither — a balance is needed"],
     0,
     "बारीक जाँच के लिए बारीक पैमाना — मिमी की नज़र से ही मिमी का फर्क दिखता है।",
     "A fine test needs a fine yardstick — only a mm-scale eye can see a mm-scale change."),

    ("error-precision", "hard",
     "एक ही छड़ के दो पाठ्यांक: 1.5 मीटर और 100 सेंटीमीटर। सही औसत निकालने की प्रक्रिया और परिणाम क्या है?",
     "Two readings of the same rod: 1.5 metres and 100 centimetres. What is the correct averaging procedure and result?",
     ["पहले एक इकाई में बदलो (150 सेमी, 100 सेमी) → औसत 125 सेमी = 1.25 मीटर", "सीधे (1.5 + 100) ÷ 2 = 50.75 मीटर", "औसत 1.5 मीटर ही रहेगा", "औसत 100 सेमी ही रहेगा"],
     ["First convert to one unit (150 cm, 100 cm) → average 125 cm = 1.25 metres", "Directly (1.5 + 100) ÷ 2 = 50.75 metres", "The average stays 1.5 metres", "The average stays 100 cm"],
     0,
     "(150 + 100) ÷ 2 = 125 सेमी — मिश्रित इकाइयों का औसत पहले एकरूप करना जरूरी; अन्यथा 50.75 मीटर जैसी बेतुकी संख्या आती है।",
     "(150 + 100) ÷ 2 = 125 cm — mixed units must first be unified; otherwise an absurdity like 50.75 metres appears."),
]
