# -*- coding: utf-8 -*-
"""P01 Part-1 — Measurement, Units & Scientific Investigation (physics/chapter-01).
76 items: need-for-measurement 38 (E16/M16/H6) + si-unit-system 38 (E15/M16/H7).
Tuple: (topic, difficulty, question_hi, question_en, options_hi[4], options_en[4], correct_idx, expl_hi, expl_en)
Content scope = P01 meta.json notes ONLY. Traps honoured: mass(kg) vs weight(N); °C vs K (K = °C + 273);
accuracy (true-value closeness) vs precision (repeat-closeness). Prefixes: kilo=1000, centi=1/100, milli=1/1000, mega=10^6.
"""

PART1 = [
    # ================= NEED FOR MEASUREMENT — 38 (E16/M16/H6) =================
    ("need-for-measurement", "easy",
     "विज्ञान में मापन (measurement) किन दो चीज़ों से मिलकर बनता है?",
     "In science, what two things together make a measurement?",
     ["संख्यात्मक मान और मात्रक", "संख्या और रंग", "आकार और भार", "समय और दिशा"],
     ["A numerical value and a unit", "A number and a colour", "Shape and weight", "Time and direction"],
     0,
     "मापन = संख्या + मात्रक — दोनों साथ हों तभी मापन पूरा होता है।",
     "Measurement = number + unit — only together do they make a complete measurement."),

    ("need-for-measurement", "easy",
     "केवल संख्या लिखना (जैसे 'लंबाई 5') विज्ञान में अर्थहीन क्यों है?",
     "Why is writing only a number (like 'length 5') meaningless in science?",
     ["क्योंकि बिना मात्रक के यह ज्ञात नहीं होता कि 5 किस राशि में और कितना है", "क्योंकि संख्याएँ गलत होती हैं", "क्योंकि विज्ञान में संख्या नहीं लिखते", "क्योंकि 5 छोटी संख्या है"],
     ["Because without a unit it is not known what the 5 is a quantity of, or how much", "Because numbers are wrong", "Because numbers are not written in science", "Because 5 is a small number"],
     0,
     "5 मीटर, 5 किग्रा या 5 सेकंड — बिना मात्रक सब अधूरा; संख्या अकेली कुछ नहीं बताती।",
     "5 metres, 5 kilograms or 5 seconds — without a unit all is incomplete; a number alone says nothing."),

    ("need-for-measurement", "easy",
     "मात्रक (unit) किसे कहते हैं?",
     "What is a unit?",
     ["किसी भौतिक राशि को मापने के लिए चुना गया निश्चित, मानक संदर्भ", "कोई भी बड़ी संख्या", "गणित का एक नियम", "विज्ञान का एक यंत्र"],
     ["A fixed, standard reference chosen to measure a physical quantity", "Any large number", "A rule of mathematics", "A scientific machine"],
     0,
     "मात्रक वह तय किया गया मानक है जिससे तुलना करके राशि की संख्या निकलती है।",
     "A unit is the fixed standard against which a quantity is compared to get its number."),

    ("need-for-measurement", "easy",
     "तुलना करने के लिए किसका होना आवश्यक है?",
     "What is necessary for making a proper comparison?",
     ["मानक मात्रक में मापन", "केवल अनुमान", "केवल आँख का अंदाज़ा", "केवल वर्णन"],
     ["Measurement in standard units", "Only guesswork", "Only a visual estimate", "Only a description"],
     0,
     "बिना मापन के तुलना अधूरी है — मानक मात्रक ही तुलना को निष्पक्ष बनाता है।",
     "Comparison is incomplete without measurement — standard units make it fair."),

    ("need-for-measurement", "easy",
     "निम्न में से कौन-सा मापन पूर्ण (complete) है?",
     "Which of the following is a complete measurement?",
     ["किताब की लंबाई 25 सेंटीमीटर", "किताब की लंबाई 25", "किताब काफी लंबी है", "किताब बहुत अच्छी है"],
     ["The length of the book is 25 centimetres", "The length of the book is 25", "The book is quite long", "The book is very good"],
     0,
     "25 सेंटीमीटर में संख्या (25) और मात्रक (सेंटीमीटर) दोनों हैं — बाकी कथन अनुमान या राय हैं।",
     "'25 centimetres' has both the number (25) and the unit (centimetre) — the rest are estimates or opinions."),

    ("need-for-measurement", "easy",
     "मापन के बिना विज्ञान का प्रयोग क्यों अधूरा माना जाता है?",
     "Why is a scientific experiment considered incomplete without measurement?",
     ["क्योंकि परिणाम की तुलना और जाँच संख्या + मात्रक के बिना संभव नहीं", "क्योंकि प्रयोग बिना मापन के खतरनाक हैं", "क्योंकि विज्ञान में केवल संख्याएँ देखी जाती हैं", "क्योंकि मापन से प्रयोग सुंदर दिखता है"],
     ["Because results cannot be compared or checked without number + unit", "Because experiments are dangerous without measurement", "Because only numbers are watched in science", "Because measurement makes experiments beautiful"],
     0,
     "प्रयोग की पुष्टि तभी होती है जब परिणाम मापा और तुलना किया जा सके।",
     "An experiment is verified only when its results can be measured and compared."),

    ("need-for-measurement", "easy",
     "'SI' प्रणाली का पूरा रूप क्या है?",
     "What is the full form of the 'SI' system?",
     ["International System of Units", "Scientific Instruments", "Standard India", "Simple Instruments"],
     ["International System of Units", "Scientific Instruments", "Standard India", "Simple Instruments"],
     0,
     "SI = International System of Units — दुनिया भर के वैज्ञानिकों की सहमति वाली मात्रक-प्रणाली।",
     "SI = International System of Units — the unit system agreed upon by scientists worldwide."),

    ("need-for-measurement", "easy",
     "किसी राशि का मान '7 सेकंड' है — यहाँ मापी गई राशि कौन-सी है?",
     "A quantity's value is '7 seconds' — which quantity is measured here?",
     ["समय", "लंबाई", "द्रव्यमान", "ताप"],
     ["Time", "Length", "Mass", "Temperature"],
     0,
     "मात्रक पहचानो तो राशि मिलती है — सेकंड समय का मात्रक है।",
     "Identify the unit and you find the quantity — the second is the unit of time."),

    ("need-for-measurement", "easy",
     "'15 किलोग्राम' में मापी गई राशि कौन-सी है?",
     "Which quantity is measured in '15 kilograms'?",
     ["द्रव्यमान", "भार", "लंबाई", "विद्युत धारा"],
     ["Mass", "Weight", "Length", "Electric current"],
     0,
     "किलोग्राम द्रव्यमान का SI मात्रक है।",
     "The kilogram is the SI unit of mass."),

    ("need-for-measurement", "easy",
     "दुकानदार कपड़ा मापते समय कौन-सी राशि माप रहा है?",
     "While measuring cloth, which quantity is the shopkeeper measuring?",
     ["लंबाई", "द्रव्यमान", "समय", "ताप"],
     ["Length", "Mass", "Time", "Temperature"],
     0,
     "कपड़ा मीटर में मापा जाता है — यह लंबाई की माप है।",
     "Cloth is measured in metres — a measurement of length."),

    ("need-for-measurement", "easy",
     "मानक मात्रक (standard unit) की सबसे जरूरी शर्त क्या है?",
     "What is the most essential condition for a standard unit?",
     ["वह सबके लिए एक जैसा और स्थिर (न बदलने वाला) हो", "वह बहुत बड़ा हो", "वह केवल एक देश में मान्य हो", "वह बार-बार बदलता रहे"],
     ["It must be the same and fixed (unchanging) for everyone", "It must be very large", "It must be valid in only one country", "It must keep changing"],
     0,
     "मानक का अर्थ ही है — हर जगह, हर समय, हर व्यक्ति के लिए समान।",
     "The very meaning of a standard is — same for every place, time and person."),

    ("need-for-measurement", "easy",
     "एक व्यक्ति की 'बित्ती' (अंगुली की चौड़ाई) से मापने पर समस्या क्यों होती है?",
     "Why is measuring with a person's 'finger width' (anguli) problematic?",
     ["अलग-अलग व्यक्तियों की अंगुलियाँ अलग-अलग मोटी होती हैं — मापन सबके लिए समान नहीं रहता", "अंगुली से मापना मना है", "अंगुली में मात्रक नहीं होता", "अंगुली टूट जाती है"],
     ["Different people's fingers differ in width — the measurement is not the same for all", "Measuring by finger is forbidden", "A finger has no unit inside", "The finger breaks"],
     0,
     "शरीर-आधारित मापन व्यक्ति-दर-व्यक्ति बदलता है, इसलिए मानक नहीं कहलाता।",
     "Body-based measures vary person to person, hence they are not standard."),

    ("need-for-measurement", "easy",
     "पुराने समय की 'हाथ की फैलाव' (बित्त/हस्त) जैसी इकाइयाँ अवैज्ञानिक क्यों मानी गईं?",
     "Why were old units like the 'hand span' (hasta) considered unscientific?",
     ["क्योंकि ये व्यक्ति के शरीर के अनुसार बदलती थीं — निश्चित मानक नहीं थीं", "क्योंकि ये बहुत पुरानी थीं", "क्योंकि इनका उच्चारण कठिन था", "क्योंकि ये केवल बच्चों के लिए थीं"],
     ["Because they changed from person to person — no fixed standard", "Because they were very old", "Because they were hard to pronounce", "Because they were only for children"],
     0,
     "मापन की निर्भरता व्यक्ति पर नहीं, मानक पर होनी चाहिए।",
     "Measurement must depend on a standard, not on the person measuring."),

    ("need-for-measurement", "easy",
     "मेज की लंबाई नापने के लिए उपयुक्त इकाई कौन-सी है?",
     "Which unit is appropriate for measuring the length of a table?",
     ["सेंटीमीटर/मीटर", "किलोमीटर", "मिलीमीटर ही एकमात्र विकल्प", "किलोग्राम"],
     ["Centimetre/metre", "Kilometre", "Millimetre as the only option", "Kilogram"],
     0,
     "वस्तु के आकार के अनुसार इकाई चुनते हैं — मेज के लिए सेंटीमीटर/मीटर उपयुक्त।",
     "The unit is chosen to suit the object's size — cm/m suit a table."),

    ("need-for-measurement", "easy",
     "दो शहरों के बीच की दूरी बताने के लिए कौन-सी इकाई सर्वाधिक उपयुक्त है?",
     "Which unit is most appropriate for the distance between two cities?",
     ["किलोमीटर", "सेंटीमीटर", "मिलीमीटर", "ग्राम"],
     ["Kilometre", "Centimetre", "Millimetre", "Gram"],
     0,
     "बड़ी दूरियों के लिए बड़ी इकाई — किलोमीटर — सुविधाजनक और सार्थक है।",
     "Large distances call for a large unit — the kilometre is convenient and meaningful."),

    ("need-for-measurement", "easy",
     "विज्ञान में मापन को 'भाषा' क्यों कहा जाता है?",
     "Why is measurement called the 'language' of science?",
     ["क्योंकि यह वैज्ञानिकों को संख्या + मात्रक के माध्यम से निर्द्वंद्व रूप से संवाद करने देता है", "क्योंकि इसमें व्याकरण होता है", "क्योंकि यह केवल पुस्तकों में होता है", "क्योंकि यह अनुवाद करता है"],
     ["Because it lets scientists communicate unambiguously through number + unit", "Because it has grammar", "Because it happens only in books", "Because it translates"],
     0,
     "दो वैज्ञानिक — दो देश, एक मात्रक, एक ही मत: यही मापन की साझा भाषा है।",
     "Two scientists — two countries, one unit, one conclusion: that is measurement's shared language."),

    ("need-for-measurement", "medium",
     "दो छात्र एक ही डंडी मापते हैं — एक 'हाथ' (हस्त) में, दूसरा मीटर स्केल से। किसका परिणाम सभी के लिए उपयोगी है और क्यों?",
     "Two students measure the same stick — one in hand spans, one with a metre scale. Whose result is useful to all, and why?",
     ["मीटर स्केल वाला — क्योंकि मीटर सबके लिए एक जैसा मानक है", "हाथ वाला — क्योंकि हाथ सदा उपलब्ध है", "दोनों समान रूप से", "कोई नहीं"],
     ["The metre-scale one — because the metre is the same standard for everyone", "The hand-span one — because the hand is always available", "Both equally", "Neither"],
     0,
     "उपयोगिता का आधार पुनरावृत्ति (reproducibility) है — मानक मात्रक ही सबके परिणाम मेलाता है।",
     "Usefulness rests on reproducibility — only a standard unit aligns everyone's results."),

    ("need-for-measurement", "medium",
     "5 मीटर + 100 सेंटीमीटर का योग कितना होगा?",
     "What is the sum of 5 metres + 100 centimetres?",
     ["6 मीटर", "5.1 मीटर", "105 मीटर", "600 मीटर"],
     ["6 metres", "5.1 metres", "105 metres", "600 metres"],
     0,
     "100 सेंटीमीटर = 1 मीटर; इसलिए 5 + 1 = 6 मीटर — योग से पहले इकाई समान करनी जरूरी है।",
     "100 cm = 1 m; hence 5 + 1 = 6 m — units must be matched before adding."),

    ("need-for-measurement", "medium",
     "5 मीटर और 5 किलोग्राम को जोड़ा नहीं जा सकता — क्यों?",
     "5 metres and 5 kilograms cannot be added — why?",
     ["क्योंकि दोनों भिन्न राशियाँ हैं — लंबाई और द्रव्यमान का योग भौतिक रूप से अर्थहीन है", "क्योंकि 5 विषम संख्या है", "क्योंकि मात्रक जुड़ते नहीं", "क्योंकि किलोग्राम बड़ा होता है"],
     ["Because they are different quantities — adding length and mass is physically meaningless", "Because 5 is an odd number", "Because units do not join", "Because the kilogram is bigger"],
     0,
     "योग एक ही राशि के मानों में ही होता है — सेब और आम की गिनती एक टोकरी में वैज्ञानिक नहीं।",
     "Addition works only within one quantity — counting apples and mangoes into one basket is not science."),

    ("need-for-measurement", "medium",
     "250 सेंटीमीटर और 2.5 मीटर में से कौन लंबा है?",
     "Between 250 centimetres and 2.5 metres, which is longer?",
     ["दोनों बराबर लंबे हैं", "250 सेंटीमीटर लंबा", "2.5 मीटर लंबा", "तुलना संभव नहीं"],
     ["Both are equally long", "250 centimetres is longer", "2.5 metres is longer", "Comparison is impossible"],
     0,
     "250 सेंटीमीटर = 2.5 मीटर — इकाई बदलने पर मान बदलता है, लंबाई नहीं।",
     "250 cm = 2.5 m — converting the unit changes the number, not the length."),

    ("need-for-measurement", "medium",
     "एक दर्जी (tailor) के लिए मापन क्यों आवश्यक है?",
     "Why is measurement necessary for a tailor?",
     ["कपड़ा काटने से पहले शरीर की लंबाइयों का सही मान चाहिए, वरना कपड़ा फिट नहीं होगा", "क्योंकि दर्जी को गणित आता है", "क्योंकि कानून ऐसा कहता है", "क्योंकि कपड़ा बिकता नहीं"],
     ["Correct body measurements are needed before cutting cloth, else the garment will not fit", "Because the tailor knows mathematics", "Because the law says so", "Because cloth does not sell"],
     0,
     "मापन केवल प्रयोगशाला नहीं, दैनिक काम की सटीकता की कुंजी है।",
     "Measurement is the key to accuracy in daily work, not just in laboratories."),

    ("need-for-measurement", "medium",
     "अलग-अलग देशों के वैज्ञानिकों के परिणाम आपस में तुलनीय बनाने के लिए क्या सर्वाधिक आवश्यक है?",
     "What is most needed to make results of scientists from different countries comparable?",
     ["सबके द्वारा समान मानक मात्रक (SI) का प्रयोग", "सबका एक ही देश में रहना", "एक ही भाषा बोलना", "एक ही यंत्र खरीदना"],
     ["Use of the same standard units (SI) by all", "Living in the same country", "Speaking the same language", "Buying the same instrument"],
     0,
     "SI एक विश्व-भाषा की तरह काम करती है — इकाई साझी तो तुलना साझी।",
     "SI works like a world language — shared units make shared comparison."),

    ("need-for-measurement", "medium",
     "कथन A: मापन में संख्या आवश्यक है। कथन B: मापन में मात्रक आवश्यक है। कौन-सा सही है?",
     "Statement A: a measurement needs a number. Statement B: a measurement needs a unit. Which is correct?",
     ["A और B दोनों सही", "केवल A सही", "केवल B सही", "दोनों गलत"],
     ["Both A and B are correct", "Only A is correct", "Only B is correct", "Both are wrong"],
     0,
     "मापन संख्या और मात्रक की जोड़ी है — एक भी अधूरा तो मापन अधूरा।",
     "Measurement is the pair of number and unit — missing either leaves it incomplete."),

    ("need-for-measurement", "medium",
     "एक बच्चा कहता है 'मेरा बस्ता भारी है'। वैज्ञानिक दृष्टि से इस कथन में क्या कमी है?",
     "A child says 'my bag is heavy'. What does this statement lack from a scientific viewpoint?",
     ["मापा हुआ मान और मात्रक — 'भारी' केवल अनुभव है, मापन नहीं", "वर्तनी की गलती", "व्याकरण", "कोई कमी नहीं"],
     ["A measured value with a unit — 'heavy' is only a feeling, not a measurement", "A spelling mistake", "Grammar", "Nothing is lacking"],
     0,
     "विज्ञान अनुभव को संख्या + मात्रक में बदलता है — जैसे 'बस्ता का द्रव्यमान 4 किलोग्राम'।",
     "Science converts experience into number + unit — e.g. 'the bag's mass is 4 kilograms'."),

    ("need-for-measurement", "medium",
     "यदि सब्जी बेचने वाला प्रत्येक ग्राहक को अपनी 'मुट्ठी' से तौल दे, तो समस्या क्या होगी?",
     "If a vegetable seller weighs out using his own 'fistful' for every customer, what problem arises?",
     ["मुट्ठी का आकार निश्चित नहीं — हर बार मात्रा अलग, कोई निष्पक्ष मापन नहीं", "ग्राहक खुश होंगे", "सब्जी खराब होगी", "कोई समस्या नहीं"],
     ["A fistful is not a fixed size — the amount differs every time, no fair measurement", "Customers will be happy", "Vegetables will spoil", "No problem"],
     0,
     "मापन का आधार निश्चितता है; शरीर के अंग निश्चित मानक नहीं दे सकते।",
     "Measurement rests on fixity; body parts cannot provide a fixed standard."),

    ("need-for-measurement", "medium",
     "राशि (quantity) और मात्रक (unit) में सही युग्म चुनिए —",
     "Pick the correct quantity–unit pair —",
     ["ताप — केल्विन", "ताप — मीटर", "द्रव्यमान — सेकंड", "समय — किलोग्राम"],
     ["Temperature — kelvin", "Temperature — metre", "Mass — second", "Time — kilogram"],
     0,
     "पहले राशि पहचानो, फिर उसका SI मात्रक लगाओ — ताप का मात्रक केल्विन है।",
     "First identify the quantity, then attach its SI unit — kelvin belongs to temperature."),

        ("need-for-measurement", "medium",
     "चीनी में '2 किलो' और नमक में '2 किलो' — दोनों की तुलना वैज्ञानिक रूप से किस आधार पर होती है?",
     "Sugar '2 kg' and salt '2 kg' — on what basis is the comparison scientifically made?",
     ["दोनों का द्रव्यमान समान मानक इकाई (किलोग्राम) में समान है", "दोनों सफेद हैं", "दोनों खाने के काम आते हैं", "दोनों बाजार से आए"],
     ["Both have equal mass in the same standard unit (kilogram)", "Both are white", "Both are edible", "Both came from the market"],
     0,
     "पदार्थ भिन्न, राशि एक — द्रव्यमान; इकाई एक — किग्रा; तुलना सही।",
     "Different substances, same quantity — mass; same unit — kg; the comparison stands."),

    ("need-for-measurement", "medium",
     "किसी प्रयोग की रिपोर्ट में केवल 'लंबाई = 3' लिखा है। यह रिपोर्ट किस कारण अस्वीकार्य है?",
     "A report states only 'length = 3'. Why is this report unacceptable?",
     ["मात्रक अनुपस्थित — सूचना अधूरी, दोहराया (verify) नहीं जा सकती", "संख्या बहुत छोटी है", "अंग्रेजी में नहीं लिखा", "हस्तलेखन खराब है"],
     ["The unit is missing — the information is incomplete and cannot be verified", "The number is too small", "It is not written in English", "The handwriting is poor"],
     0,
     "बिना मात्रक का मान दोहराया नहीं जा सकता — विज्ञान में पुनरीक्षण ही सबूत है।",
     "A unitless value cannot be reproduced — and reproducibility is proof in science."),

    ("need-for-measurement", "medium",
     "मापन का मान '40' है और मात्रक 'सेंटीमीटर' — पूरी सूचना से हमें क्या-क्या पता चलता है?",
     "The value is '40' and the unit is 'centimetre' — what all does the complete information tell us?",
     ["राशि का प्रकार (लंबाई) और उसका संख्यात्मक मान दोनों", "केवल संख्या", "केवल राशि", "कुछ नहीं"],
     ["Both the type of quantity (length) and its numerical value", "Only the number", "Only the quantity", "Nothing"],
     0,
     "इकाई राशि बताती है, संख्या परिमाण — साथ में मापन संपूर्ण।",
     "The unit names the quantity, the number gives the size — together the measurement is complete."),

    ("need-for-measurement", "medium",
     "पग/कदम (footstep) से दूरी मापने पर एक ही सड़क की दूरी अलग-अलग क्यों आती है?",
     "Why does the same road give different distances when measured by footsteps?",
     ["हर व्यक्ति के कदम की लंबाई भिन्न होती है — इकाई अमानक है", "सड़क बदल जाती है", "कदम गिनने में गलती होती है", "मौसम का प्रभाव"],
     ["Each person's step length differs — the unit is non-standard", "The road changes", "Mistakes in counting steps", "Effect of weather"],
     0,
     "इकाई ही अस्थिर तो मापन अस्थिर — इसीलिए निश्चिक मानक जरूरी हैं।",
     "An unstable unit makes unstable measurement — hence fixed standards are needed."),

    ("need-for-measurement", "medium",
     "किस मापन-श्रेणी में 'समय' राशि आती है — वर्णन करें कि 100 मीटर दौड़ का परिणाम किस राशि में मिलता है?",
     "In what quantity is the result of a 100-metre race expressed?",
     ["समय (जैसे सेकंड में)", "लंबाई", "द्रव्यमान", "ताप"],
     ["Time (e.g. in seconds)", "Length", "Mass", "Temperature"],
     0,
     "दौड़ की रिपोर्ट घड़ी से आती है — विजेता समय-मापन से तय होता है।",
     "The race report comes from the clock — timing decides the winner."),

    ("need-for-measurement", "medium",
     "यदि कोई राशि 'मात्रक-रहित संख्या' में रिकॉर्ड की जाती रही हो, तो सबसे गंभीर परिणाम क्या होगा?",
     "If quantities keep being recorded as unit-less numbers, what is the gravest consequence?",
     ["आगे की तुलना, सत्यापन और गणना — तीनों असंभव", "फाइलें भारी होंगी", "संख्याएँ खराब हो जाएँगी", "कलम खत्म हो जाएगी"],
     ["All later comparison, verification and calculation become impossible", "Files become heavy", "Numbers get spoilt", "Pens run out"],
     0,
     "इकाई-हीन रिकॉर्ड विज्ञान की स्मृति भ्रष्ट कर देता है — तुलना की जड़ कट जाती है।",
     "Unit-less records corrupt science's memory — the root of comparison is severed."),

    ("need-for-measurement", "hard",
     "कोई लेखा 'ताप = 25' लिखकर छोड़ देता है। इस अधूरे कथन से कौन-सी जानकारी अनिश्चित रह जाती है?",
     "A record reads 'temperature = 25' and stops. What information stays uncertain from this incomplete statement?",
     ["यह केल्विन है या डिग्री सेल्सियस — दोनों में 25 का अर्थ भिन्न है", "केवल यह कि संख्या दशमलव में है", "केवल यह कि ताप गर्मी है", "कोई अनिश्चितता नहीं"],
     ["Whether it is kelvin or degree Celsius — 25 means different things in each", "Only that the number is decimal", "Only that it is warm", "No uncertainty at all"],
     0,
     "25 K = −248 °C और 25 °C सामान्य गर्मी — मात्रक के बिना ताप की व्याख्या ही उलझ जाती है।",
     "25 K is −248 °C while 25 °C is ordinary warmth — without a unit even the interpretation flips."),

    ("need-for-measurement", "hard",
     "किसी अनुसंधान-पत्र (research paper) में सभी मान SI मात्रकों में होने चाहिए — इस पद्धति का तर्क क्या है?",
     "Research papers should state all values in SI units — what is the reasoning behind this practice?",
     ["किसी भी देश का पाठक मानक मात्रकों में ही परिणाम दोहरा सकता है", "SI लिखने में छोटा होता है", "SI केवल सुंदर दिखता है", "अन्य इकाइयाँ प्रतिबंधित हैं"],
     ["A reader in any country can reproduce the results only in standard units", "SI is shorter to write", "SI just looks nicer", "Other units are banned"],
     0,
     "साझा मानक = साझा विश्वास; पुनरुत्पादन विज्ञान की कसौटी है।",
     "Shared standard = shared trust; reproducibility is science's touchstone."),

    ("need-for-measurement", "hard",
     "सोचिए — दो कारखानों के पुर्ज़ों को जोड़ा जाना है। एक 'इंच' में और दूसरा 'मिलीमीटर' में माप रहा है और किसी ने मात्रक नहीं लिखा। सबसे संभावित परिणाम क्या होगा?",
     "Two factories must fit parts together. One measures in inches, the other in millimetres, and neither writes the unit. What is the most likely outcome?",
     ["पुर्ज़े फिट नहीं होंगे — मात्रक-भ्रम से आकार बेमेल", "सब कुछ सही जुड़ेगा", "पुर्ज़े मजबूत बनेंगे", "कोई प्रभाव नहीं"],
     ["The parts will not fit — unit confusion mismatches sizes", "Everything will fit perfectly", "The parts become stronger", "No effect"],
     0,
     "इतिहास में इकाई-भ्रम से महँगी विफलताएँ हुई हैं — मात्रक लिखना विवेक है, औपचारिकता नहीं।",
     "History holds costly failures from unit confusion — writing the unit is wisdom, not formality."),

    ("need-for-measurement", "hard",
     "'संख्या मात्रक के बिना अर्थहीन है' — इस कथन का सबसे गहरा कारण क्या है?",
     "What is the deepest reason behind 'a number without a unit is meaningless'?",
     ["संख्या केवल अनुपात है — मात्रक ही उसे भौतिक वास्तविकता से जोड़ता है", "क्योंकि संख्याएँ बनाई गई हैं", "क्योंकि मात्रक सुंदर हैं", "क्योंकि शिक्षक ऐसा कहते हैं"],
     ["A number is only a ratio — the unit alone ties it to physical reality", "Because numbers are invented", "Because units are beautiful", "Because teachers say so"],
     0,
     "5 क्या है — कुछ नहीं; 5 किग्रा — अब यह पदार्थ की सूचना है: मात्रक संख्या को देह देता है।",
     "What is 5 — nothing; 5 kg — now it is information about matter: the unit gives the number a body."),

    ("need-for-measurement", "hard",
     "मापन-पद्धति के विकास क्रम में सही क्रम कौन-सा है?",
     "Which is the correct order in the evolution of measurement methods?",
     ["शरीर-आधारित इकाइाँ → स्थानीय मानक → अंतरराष्ट्रीय मानक (SI)", "SI → शरीर-आधारित इकाइयाँ → स्थानीय मानक", "स्थानीय मानक → शरीर-आधारित → SI", "तीनों एक साथ बने"],
     ["Body-based units → local standards → international standards (SI)", "SI → body-based units → local standards", "Local standards → body-based → SI", "All three arose together"],
     0,
     "मापन की यात्रा व्यक्तिगत अनुमान से विश्व-मानक तक — समस्या वही: सबके लिए एक जैसा मान।",
     "Measurement's journey runs from personal guess to world standard — the quest unchanged: one value for all."),

    ("need-for-measurement", "hard",
     "कोई वैज्ञानिक दावा करता है: 'मेरी विधि इतनी सटीक है कि मात्रक की जरूरत नहीं।' इस दावे की सबसे बड़ी त्रुटि क्या है?",
     "A scientist claims: 'My method is so precise that units are unnecessary.' What is the biggest flaw in this claim?",
     ["मात्रक के बिना परिणाम की तुलना करने वाला दूसरा वैज्ञानिक उसे समझ ही नहीं सकता — सटीकता व्यर्थ", "सटीक विधियाँ नहीं होतीं", "वैज्ञानिक झूठ बोलते हैं", "कोई त्रुटि नहीं"],
     ["Without a unit, no other scientist can even interpret the result for comparison — the precision is wasted", "Precise methods do not exist", "Scientists lie", "No flaw"],
     0,
     "जिसे पढ़ा नहीं जा सके, उसे जाँचा नहीं जा सकता — मात्रक संवाद की शर्त है, सजावट नहीं।",
     "What cannot be read cannot be checked — the unit is a condition of communication, not decoration."),

    ("si-unit-system", "medium",
     "3 मिनट 20 सेकंड में कुल कितने सेकंड होंगे?",
     "How many total seconds are there in 3 minutes 20 seconds?",
     ["200 सेकंड", "320 सेकंड", "180 सेकंड", "100 सेकंड"],
     ["200 seconds", "320 seconds", "180 seconds", "100 seconds"],
     0,
     "3 × 60 + 20 = 180 + 20 = 200 सेकंड — मिश्र इकाई को पहले एक इकाई में खोलें।",
     "3 × 60 + 20 = 180 + 20 = 200 s — first unfold the mixed unit into one."),

    ("si-unit-system", "hard",
     "'0 K' (शून्य केल्विन) की भौतिक सार्थकता क्या है?",
     "What is the physical significance of '0 K' (zero kelvin)?",
     ["यह परम शून्य है — सैद्धांतिक रूप से सबसे निम्न संभव ताप, जो −273°C के बराबर है", "यह पानी का हिमांक है", "यह कमरे का ताप है", "यह ताप का ऊपरी छोर है"],
     ["It is absolute zero — theoretically the lowest possible temperature, equal to −273°C", "It is water's freezing point", "It is room temperature", "It is the upper limit of temperature"],
     0,
     "केल्विन पैमाने का शून्य सार्थक है — वही परम ठंड की सैद्धांतिक सीमा; सेल्सियस में वह −273°C।",
     "Zero on the kelvin scale is meaningful — the theoretical limit of ultimate cold; in Celsius that is −273°C."),

    ("si-unit-system", "hard",
     "कथन: 'हर भौतिक राशि का अपना एक अलग SI मूल मात्रक होता है।' इस कथन की गलती क्या है?",
     "Statement: 'Every physical quantity has its own separate SI base unit.' What is wrong with it?",
     ["बहुत सी राशियाँ (जैसे क्षेत्रफल, आयतन, बल) मूल मात्रकों से बनी व्युत्पन्न मात्रकों में मापी जाती हैं", "कथन पूरी तरह सही है", "मूल मात्रक केवल दो हैं", "व्युत्पन्न मात्रक होते ही नहीं"],
     ["Many quantities (like area, volume, force) are measured in derived units built from base units", "The statement is fully correct", "There are only two base units", "Derived units do not exist"],
     0,
     "मूल मात्रक सात ही हैं; बाकी राशियाँ इन्हीं के संयोजन से बनी इकाइयों में व्यक्त होती हैं।",
     "Base units are only seven; the rest of the quantities speak in units combined from these."),

    # ================= SI UNIT SYSTEM — 38 (E15/M16/H7) =================
    ("si-unit-system", "easy",
     "SI प्रणाली में लंबाई का मूल मात्रक (base unit) क्या है?",
     "What is the SI base unit of length?",
     ["मीटर (m)", "सेंटीमीटर", "किलोमीटर", "किलोग्राम"],
     ["Metre (m)", "Centimetre", "Kilometre", "Kilogram"],
     0,
     "लंबाई का SI मूल मात्रक मीटर है; सेंटीमीटर-किलोमीटर उपसर्गों से बनी इकाइयाँ हैं।",
     "The SI base unit of length is the metre; cm and km are prefix-derived units."),

    ("si-unit-system", "easy",
     "द्रव्यमान (mass) का SI मूल मात्रक कौन-सा है?",
     "Which is the SI base unit of mass?",
     ["किलोग्राम (kg)", "ग्राम", "न्यूटन", "पाउंड"],
     ["Kilogram (kg)", "Gram", "Newton", "Pound"],
     0,
     "द्रव्यमान का मूल मात्रक किलोग्राम — ग्राम नहीं; यही परीक्षा का प्रिय जाल है।",
     "The base unit of mass is the kilogram — not the gram; a favourite exam trap."),

    ("si-unit-system", "easy",
     "समय का SI मात्रक क्या है?",
     "What is the SI unit of time?",
     ["सेकंड (s)", "मिनट", "घंटा", "दिन"],
     ["Second (s)", "Minute", "Hour", "Day"],
     0,
     "सेकंड ही समय का मूल मात्रक है; मिनट-घंटा उसके गुणज हैं।",
     "The second alone is the base unit of time; minutes and hours are its multiples."),

    ("si-unit-system", "easy",
     "विद्युत धारा (electric current) का SI मूल मात्रक कौन-सा है?",
     "Which is the SI base unit of electric current?",
     ["एम्पियर (A)", "वोल्ट", "ओम", "वाट"],
     ["Ampere (A)", "Volt", "Ohm", "Watt"],
     0,
     "एम्पियर विद्युत धारा का मूल मात्रक; वोल्ट-ओम-वाट अन्य राशियों की इकाइयाँ हैं।",
     "The ampere is the base unit of current; volt-ohm-watt belong to other quantities."),

    ("si-unit-system", "easy",
     "ताप (temperature) का SI मूल मात्रक क्या है?",
     "What is the SI base unit of temperature?",
     ["केल्विन (K)", "डिग्री सेल्सियस", "फैरेनहाइट", "जूल"],
     ["Kelvin (K)", "Degree Celsius", "Fahrenheit", "Joule"],
     0,
     "SI में ताप का मूल मात्रक केल्विन है; सेल्सियस-फैरेनहाइट व्यावहारिक पैमाने हैं।",
     "In SI the base unit of temperature is the kelvin; Celsius and Fahrenheit are practical scales."),

    ("si-unit-system", "easy",
     "पदार्थ की मात्रा (amount of substance) का SI मात्रक कौन-सा है?",
     "Which is the SI unit of amount of substance?",
     ["मोल (mol)", "किलोग्राम", "लीटर", "मीटर"],
     ["Mole (mol)", "Kilogram", "Litre", "Metre"],
     0,
     "मोल पदार्थ की मात्रा (कणों की संख्या-आधारित) की इकाई है — द्रव्यमान से भिन्न राशि।",
     "The mole measures amount of substance (particle-count based) — a quantity distinct from mass."),

    ("si-unit-system", "easy",
     "ज्योति तीव्रता (luminous intensity) का SI मूल मात्रक क्या है?",
     "What is the SI base unit of luminous intensity?",
     ["कैंडेला (cd)", "ल्यूमेन", "वाट", "डेसिबल"],
     ["Candela (cd)", "Lumen", "Watt", "Decibel"],
     0,
     "कैंडेला ज्योति तीव्रता का मूल मात्रक है — सात मूल मात्रकों की सूची का सातवाँ सदस्य।",
     "The candela is the base unit of luminous intensity — seventh member of the base-unit list."),

    ("si-unit-system", "easy",
     "SI प्रणाली में मूल (base) मात्रक कुल कितने हैं?",
     "How many base units does the SI system have in total?",
     ["7", "5", "10", "12"],
     ["7", "5", "10", "12"],
     0,
     "सात — मीटर, किलोग्राम, सेकंड, एम्पियर, केल्विन, मोल, कैंडेला।",
     "Seven — metre, kilogram, second, ampere, kelvin, mole, candela."),

    ("si-unit-system", "easy",
     "क्षेत्रफल (area) का SI मात्रक क्या है?",
     "What is the SI unit of area?",
     ["वर्ग मीटर (m²)", "घन मीटर", "मीटर", "वर्ग किलोग्राम"],
     ["Square metre (m²)", "Cubic metre", "Metre", "Square kilogram"],
     0,
     "लंबाई × लंबाई = वर्ग मीटर — क्षेत्रफल दो-विमीय है।",
     "Length × length = square metre — area is two-dimensional."),

    ("si-unit-system", "easy",
     "आयतन (volume) का SI मात्रक क्या है?",
     "What is the SI unit of volume?",
     ["घन मीटर (m³)", "वर्ग मीटर", "मीटर", "लीटर"],
     ["Cubic metre (m³)", "Square metre", "Metre", "Litre"],
     0,
     "लंबाई × चौड़ाई × ऊँचाई = घन मीटर; लीटर व्यावहारिक इकाई है।",
     "Length × breadth × height = cubic metre; the litre is a practical unit."),

    ("si-unit-system", "easy",
     "किलोग्राम का सही प्रतीक (symbol) कौन-सा है?",
     "Which is the correct symbol for kilogram?",
     ["kg", "KG", "Kg", "kG"],
     ["kg", "KG", "Kg", "kG"],
     0,
     "SI प्रतीक निश्चित लिखित रूप के साथ आते हैं — kg छोटे अक्षरों में।",
     "SI symbols come in fixed written forms — kg in lowercase."),

    ("si-unit-system", "easy",
     "केल्विन का सही प्रतीक कौन-सा है?",
     "Which is the correct symbol for kelvin?",
     ["K", "k", "°K", "Ke"],
     ["K", "k", "°K", "Ke"],
     0,
     "केल्विन का प्रतीक बड़ा K है और इसके साथ डिग्री (°) का चिह्न नहीं लगता।",
     "Kelvin's symbol is capital K, and it never carries the degree (°) sign."),

    ("si-unit-system", "easy",
     "'सेकंड' राशि किस भौतिक राशि से संबंधित है?",
     "The unit 'second' belongs to which physical quantity?",
     ["समय", "लंबाई", "द्रव्यमान", "ताप"],
     ["Time", "Length", "Mass", "Temperature"],
     0,
     "सेकंड समय की इकाई — सात मूल मात्रकों में तीसरा।",
     "The second is the unit of time — third of the seven base units."),

    ("si-unit-system", "easy",
     "निम्न में से कौन-सा मूल मात्रक नहीं है?",
     "Which of the following is NOT a base unit?",
     ["लीटर", "मीटर", "सेकंड", "मोल"],
     ["Litre", "Metre", "Second", "Mole"],
     0,
     "लीटर आयतन की सामान्य इकाई है, SI मूल मात्रक नहीं — आयतन का SI मात्रक घन मीटर है।",
     "The litre is a common unit of volume, not an SI base unit — volume's SI unit is the cubic metre."),

    ("si-unit-system", "easy",
     "'कैंडेला' मात्रक किस राशि के लिए है?",
     "The unit 'candela' is for which quantity?",
     ["ज्योति तीव्रता", "ध्वनि तीव्रता", "विद्युत धारा", "द्रव्यमान"],
     ["Luminous intensity", "Sound intensity", "Electric current", "Mass"],
     0,
     "मोमबत्ती (candle) शब्द से बना कैंडेला — प्रकाश की तीव्रता की इकाई।",
     "From 'candle' comes candela — the unit of light intensity."),

            ("si-unit-system", "medium",
     "उपसर्ग 'मिली' (milli) का मान क्या है?",
     "What is the value of the prefix 'milli'?",
     ["1/1000", "1/100", "1000", "100"],
     ["1/1000", "1/100", "1000", "100"],
     0,
     "मिली = हज़ारवाँ भाग — 1 मीटर = 1000 मिलीमीटर।",
     "milli = one-thousandth — 1 m = 1000 mm."),

    ("si-unit-system", "medium",
     "उपसर्ग 'मेगा' (mega) का मान क्या होता है?",
     "What is the value of the prefix 'mega'?",
     ["10 लाख (10⁶)", "1000", "100", "1/1000"],
     ["One million (10⁶)", "1000", "100", "1/1000"],
     0,
     "मेगा = 10⁶ — किलो (10³) से एक सीढ़ी ऊपर।",
     "mega = 10⁶ — one ladder step above kilo (10³)."),

    ("si-unit-system", "medium",
     "2.5 किलोमीटर में कितने मीटर होते हैं?",
     "How many metres are there in 2.5 kilometres?",
     ["2500 मीटर", "250 मीटर", "25 मीटर", "25000 मीटर"],
     ["2500 metres", "250 metres", "25 metres", "25000 metres"],
     0,
     "2.5 × 1000 = 2500 मीटर — किलो लगाने पर 1000 से गुणा।",
     "2.5 × 1000 = 2500 m — applying kilo multiplies by 1000."),

    ("si-unit-system", "medium",
     "300 सेंटीमीटर को मीटर में बदलने पर क्या मिलेगा?",
     "Converting 300 centimetres into metres gives —",
     ["3 मीटर", "30 मीटर", "0.3 मीटर", "3000 मीटर"],
     ["3 metres", "30 metres", "0.3 metres", "3000 metres"],
     0,
     "300 ÷ 100 = 3 मीटर — सेंटी हटाने पर 100 से भाग।",
     "300 ÷ 100 = 3 m — removing centi divides by 100."),

    ("si-unit-system", "medium",
     "0.5 किलोग्राम में कितने ग्राम होंगे?",
     "How many grams are there in 0.5 kilograms?",
     ["500 ग्राम", "50 ग्राम", "5 ग्राम", "5000 ग्राम"],
     ["500 grams", "50 grams", "5 grams", "5000 grams"],
     0,
     "0.5 × 1000 = 500 ग्राम।",
     "0.5 × 1000 = 500 g."),

    ("si-unit-system", "medium",
     "2 घंटे में कितने सेकंड होते हैं?",
     "How many seconds are there in 2 hours?",
     ["7200 सेकंड", "3600 सेकंड", "1200 सेकंड", "720 सेकंड"],
     ["7200 seconds", "3600 seconds", "1200 seconds", "720 seconds"],
     0,
     "2 × 60 × 60 = 7200 सेकंड — घंटा → मिनट → सेकंड की सीढ़ी।",
     "2 × 60 × 60 = 7200 s — the hour → minute → second ladder."),

        ("si-unit-system", "medium",
     "250 मिलीमीटर कितने सेंटीमीटर बनते हैं?",
     "250 millimetres equal how many centimetres?",
     ["25 सेंटीमीटर", "2.5 सेंटीमीटर", "2500 सेंटीमीटर", "25000 सेंटीमीटर"],
     ["25 centimetres", "2.5 centimetres", "2500 centimetres", "25000 centimetres"],
     0,
     "250 × (1/1000) मीटर = 0.25 मीटर = 25 सेंटीमीटर; या 250 ÷ 10 = 25 सेमी।",
     "250 × (1/1000) m = 0.25 m = 25 cm; or 250 ÷ 10 = 25 cm."),

    ("si-unit-system", "medium",
     "0°C को केल्विन में व्यक्त करने पर क्या मिलता है?",
     "Expressing 0°C in kelvin gives —",
     ["273 K", "0 K", "100 K", "−273 K"],
     ["273 K", "0 K", "100 K", "−273 K"],
     0,
     "K = °C + 273 → 0 + 273 = 273 K — पानी का हिमांक 273 K।",
     "K = °C + 273 → 0 + 273 = 273 K — water's freezing point."),

    ("si-unit-system", "medium",
     "27°C को केल्विन पैमाने में कितना होगा?",
     "What is 27°C on the kelvin scale?",
     ["300 K", "273 K", "300°K", "54 K"],
     ["300 K", "273 K", "300°K", "54 K"],
     0,
     "27 + 273 = 300 K; K के साथ डिग्री चिह्न नहीं लिखते।",
     "27 + 273 = 300 K; no degree sign with K."),

    ("si-unit-system", "medium",
     "सामान्य दाब पर पानी का क्वथनांक 100°C है — केल्विन में यह कितना होगा?",
     "Water boils at 100°C at normal pressure — what is this in kelvin?",
     ["373 K", "273 K", "173 K", "100 K"],
     ["373 K", "273 K", "173 K", "100 K"],
     0,
     "100 + 273 = 373 K — केल्विन पैमाने पर उबलने का आंकिक मान हमेशा बड़ा।",
     "100 + 273 = 373 K — boiling reads numerically larger on the kelvin scale."),

    ("si-unit-system", "medium",
     "2 मीटर × 3 मीटर की दीवार का क्षेत्रफल किस इकाई और कितना होगा?",
     "A wall 2 m × 3 m has an area of what size and unit?",
     ["6 वर्ग मीटर (m²)", "6 घन मीटर", "5 मीटर", "6 मीटर"],
     ["6 square metres (m²)", "6 cubic metres", "5 metres", "6 metres"],
     0,
     "क्षेत्रफल = 2 × 3 = 6 m² — मीटर × मीटर वर्ग मीटर देता है।",
     "Area = 2 × 3 = 6 m² — metre × metre yields square metres."),

    ("si-unit-system", "medium",
     "10 सेंटीमीटर भुजा वाले घन (cube) का आयतन कितना होगा?",
     "What is the volume of a cube of side 10 centimetres?",
     ["1000 घन सेंटीमीटर", "100 घन सेंटीमीटर", "30 घन सेंटीमीटर", "10 घन सेंटीमीटर"],
     ["1000 cubic centimetres", "100 cubic centimetres", "30 cubic centimetres", "10 cubic centimetres"],
     0,
     "आयतन = 10 × 10 × 10 = 1000 सेमी³ — तीन विमाओं का गुणन।",
     "Volume = 10 × 10 × 10 = 1000 cm³ — a product of three dimensions."),

    ("si-unit-system", "medium",
     "निम्न में से कौन-सी इकाई SI मूल मात्रक नहीं है — न्यूटन, सेकंड, मोल, कैंडेला?",
     "Which of these is NOT an SI base unit — newton, second, mole, candela?",
     ["न्यूटन", "सेकंड", "मोल", "कैंडेला"],
     ["Newton", "Second", "Mole", "Candela"],
     0,
     "न्यूटन बल का (व्युत्पन्न) मात्रक है — भार की इकाई; मूल सूची में नहीं।",
     "The newton is a (derived) unit of force — the unit of weight; not in the base list."),

    ("si-unit-system", "medium",
     "राशि→मात्रक का गलत युग्म कौन-सा है?",
     "Which quantity→unit pair is WRONG?",
     ["भार — किलोग्राम", "लंबाई — मीटर", "समय — सेकंड", "ताप — केल्विन"],
     ["Weight — kilogram", "Length — metre", "Time — second", "Temperature — kelvin"],
     0,
     "भार बल है, उसकी इकाई न्यूटन; किलोग्राम द्रव्यमान की इकाई — यही परीक्षा-जाल है।",
     "Weight is a force measured in newtons; the kilogram measures mass — the classic exam trap."),

    ("si-unit-system", "medium",
     "'मोल' और 'किलोग्राम' दोनों पदार्थ से जुड़ी इकाइयाँ हैं — दोनों की मापी राशि भिन्न क्यों है?",
     "Both 'mole' and 'kilogram' relate to substances — why are the quantities they measure different?",
     ["मोल कणों की संख्या-आधारित मात्रा है, किलोग्राम द्रव्यमान — दो अलग भौतिक राशियाँ", "दोनों एक ही हैं", "मोल ग्राम का पर्याय है", "किलोग्राम संख्या गिनता है"],
     ["The mole counts particle-amount, the kilogram measures mass — two distinct physical quantities", "Both are the same", "Mole is a synonym of gram", "Kilogram counts numbers"],
     0,
     "एक ही थैली चीनी: द्रव्यमान 1 किग्रा, पर मोल उसमें छुपे कणों की गिनती बताता है।",
     "One bag of sugar: mass 1 kg, but the mole counts the particles hidden within."),

        ("si-unit-system", "hard",
     "केल्विन और डिग्री सेल्सियस — दोनों के 'एक अंश' (degree size) का आकार समान होता है, फिर भी दोनों भिन्न क्यों गिने जाते हैं?",
     "Kelvin and degree Celsius have the same step size — why are they still counted as different?",
     ["दोनों के शून्य-बिंदु भिन्न हैं: 0 K परम शून्य है, 0°C पानी का हिमांक", "केल्विन छोटा होता है", "सेल्सियस वैज्ञानिक नहीं है", "कोई भेद नहीं"],
     ["Their zero points differ: 0 K is absolute zero, 0°C is water's freezing point", "Kelvin is smaller", "Celsius is unscientific", "No difference"],
     0,
     "सीढ़ियों की चौड़ाई बराबर, पर फर्श से पहली सीढ़ी की ऊँचाई अलग — शून्य का फर्क ही दोनों को अलग करता है।",
     "Equal step widths, but the first step sits at a different height — the zero offset is what separates them."),

    ("si-unit-system", "hard",
     "कथन जाँचिए — A: ताप का SI मात्रक सेल्सियस है। B: 0°C = 273 K। कौन-सा सही/गलत है?",
     "Evaluate — A: the SI unit of temperature is Celsius. B: 0°C = 273 K. Which is right/wrong?",
     ["A गलत, B सही", "A सही, B गलत", "दोनों सही", "दोनों गलत"],
     ["A wrong, B right", "A right, B wrong", "Both right", "Both wrong"],
     0,
     "SI में केल्विन; और 0°C + 273 = 273 K — पहला कथन मात्रक-जाल, दूसरा परिवर्तन-सूत्र।",
     "In SI it is kelvin; and 0°C + 273 = 273 K — the first is a unit trap, the second the conversion."),

    ("si-unit-system", "hard",
     "एक विद्यार्थी 2 मेगामीटर को '2000 मीटर' लिखता है। गलती कहाँ है?",
     "A student writes 2 megametres as '2000 metres'. Where is the mistake?",
     ["मेगा = 10⁶ है, अतः 2 मेगामीटर = 2,000,000 मीटर — उसने मेगा को किलो मान लिया", "कोई गलती नहीं", "उसने गुणा की जगह भाग किया", "मेगामीटर मात्रक ही नहीं होता"],
     ["Mega = 10⁶, so 2 Mm = 2,000,000 m — the student treated mega as kilo", "No mistake", "The student divided instead of multiplying", "Megametre is not a unit"],
     0,
     "किलो की सीढ़ी 10³, मेगा की 10⁶ — एक सीढ़ी की भूल दस गुना फर्क देती है।",
     "Kilo's ladder is 10³, mega's is 10⁶ — a one-step slip makes a tenfold error."),

    ("si-unit-system", "hard",
     "किलोग्राम और वर्ग मीटर क्रमशः किस प्रकार की इकाइयाँ हैं?",
     "What kinds of units are the kilogram and the square metre, respectively?",
     ["मूल मात्रक और व्युत्पन्न (derived) मात्रक", "दोनों मूल", "दोनों व्युत्पन्न", "दोनों गैर-SI"],
     ["A base unit and a derived unit", "Both base", "Both derived", "Both non-SI"],
     0,
     "किग्रा सात मूल में से एक; वर्ग मीटर मीटर से निकला व्युत्पन्न मात्रक।",
     "kg is one of the seven base units; m² is derived from the metre."),

    ("si-unit-system", "hard",
     "यदि कोई राशि 'कैंडेला में' दी गई हो, तो वह राशि किस आयाम (dimension) से संबंधित है?",
     "If a quantity is given 'in candela', which aspect of the world does it relate to?",
     ["प्रकाश की तीव्रता (दीप्ति)", "ध्वनि का स्तर", "ऊष्मा की मात्रा", "बल का प्रभाव"],
     ["Intensity of light (luminosity)", "Level of sound", "Amount of heat", "Effect of force"],
     0,
     "कैंडेला केवल प्रकाश-तीव्रता की दुनिया में बोलता है — सात मूल मात्रकों में सबसे कम जाना-पहचाना।",
     "Candela speaks only in the world of light intensity — the least familiar of the seven base units."),
]
