# -*- coding: utf-8 -*-
"""P02 Part-1 — Motion & Time (physics/chapter-02).
76 items: distance-displacement 38 (E16/M16/H6) + speed-velocity 38 (E15/M16/H7).
Tuple: (topic, difficulty, question_hi, question_en, options_hi[4], options_en[4], correct_idx, expl_hi, expl_en)
Scope: P02 meta notes ONLY. Traps: distance(scalar) vs displacement(vector); displacement <= distance;
uniform circular motion — constant speed yet changing velocity; average speed != mean of speeds.
DENY (P01 owns): measuring instruments/units questions. No Newton's laws (P03), no gravitation (P04).
"""

PART1 = [
    # ================= DISTANCE & DISPLACEMENT — 38 (E16/M16/H6) =================
    ("distance-displacement", "easy",
     "दूरी (distance) किसे कहते हैं?",
     "What is meant by distance?",
     ["पथ की कुल लंबाई जो वस्तु तय करती है", "प्रारंभ व अंत बिंदु के बीच सीधी न्यूनतम दूरी", "केवल दिशा", "केवल समय"],
     ["The total length of the path travelled by the object", "The straight minimum gap between start and end points", "Only direction", "Only time"],
     0,
     "दूरी पथभर की गिनती है — चाहे रास्ता कितना भी घुमावदार हो।",
     "Distance is the whole path's count — however winding the road."),

    ("distance-displacement", "easy",
     "विस्थापन (displacement) किसे कहते हैं?",
     "What is meant by displacement?",
     ["प्रारंभ और अंत बिंदुओं के बीच की न्यूनतम सीधी दूरी (निश्चित दिशा सहित)", "तय किए गए पथ की कुल लंबाई", "वस्तु का वज़न", "वस्तु की चाल"],
     ["The minimum straight distance between the initial and final points (with definite direction)", "The total length of the path travelled", "The object's weight", "The object's speed"],
     0,
     "विस्थापन सीधी रस्सी है — शुरुआत से मंज़िल तक, दिशा समेत।",
     "Displacement is the taut rope — start to finish, direction included."),

    ("distance-displacement", "easy",
     "दूरी किस प्रकार की राशि है?",
     "What kind of quantity is distance?",
     ["अदिश (scalar)", "सदिश (vector)", "कभी अदिश कभी सदिश", "न अदिश न सदिश"],
     ["Scalar", "Vector", "Sometimes scalar, sometimes vector", "Neither scalar nor vector"],
     0,
     "दूरी में केवल परिमाण होता है, दिशा नहीं — इसलिए अदिश।",
     "Distance has only magnitude, no direction — hence a scalar."),

    ("distance-displacement", "easy",
     "विस्थापन किस प्रकार की राशि है?",
     "What kind of quantity is displacement?",
     ["सदिश (vector)", "अदिश (scalar)", "इकाई", "मात्रक-रहित"],
     ["Vector", "Scalar", "A unit", "Unitless"],
     0,
     "विस्थापन में परिमाण और दिशा दोनों होते हैं — सदिश राशि।",
     "Displacement carries both magnitude and direction — a vector."),

    ("distance-displacement", "easy",
     "दूरी और विस्थापन में से किसकी दिशा बताई जाती है?",
     "Which of distance and displacement carries a direction?",
     ["विस्थापन", "दूरी", "दोनों", "कोई नहीं"],
     ["Displacement", "Distance", "Both", "Neither"],
     0,
     "विस्थापन 'कितनी और किधर' — दोनों बताता है।",
     "Displacement tells 'how much and which way' — both."),

    ("distance-displacement", "easy",
     "यदि वस्तु सीधी रेखा में बिना मुड़े चले, तो दूरी और विस्थापन का संबंध क्या होगा?",
     "If an object moves in a straight line without turning, what is the relation between distance and displacement?",
     ["दोनों बराबर", "दूरी विस्थापन से हमेशा बड़ी", "विस्थापन हमेशा बड़ा", "दोनों शून्य"],
     ["Both are equal", "Distance is always greater", "Displacement is always greater", "Both are zero"],
     0,
     "सीधा रास्ता = रस्सी ही रास्ता — तब दूरी = विस्थापन।",
     "A straight road = the rope itself — then distance equals displacement."),

    ("distance-displacement", "easy",
     "विस्थापन का मान दूरी की तुलना में कैसा हो सकता है?",
     "How can the value of displacement compare with distance?",
     ["दूरी के बराबर या उससे कम", "हमेशा अधिक", "हमेशा दोगुना", "हमेशा ऋणात्मक"],
     ["Equal to or less than distance", "Always more", "Always double", "Always negative"],
     0,
     "घुमावदार रास्ते में पथ लंबा, रस्सी छोटी — विस्थापन ≤ दूरी।",
     "On a winding path the road is long, the rope short — displacement ≤ distance."),

    ("distance-displacement", "easy",
     "SI मात्रकों में दूरी और विस्थापन दोनों किस इकाई में मापे जाते हैं?",
     "In SI units, both distance and displacement are measured in which unit?",
     ["मीटर", "मीटर/सेकंड", "सेकंड", "वर्ग मीटर"],
     ["Metre", "Metre/second", "Second", "Square metre"],
     0,
     "दोनों लंबाई की राशियाँ हैं — इसलिए दोनों मीटर में।",
     "Both are quantities of length — hence both in metres."),

    ("distance-displacement", "easy",
     "घर से 100 मीटर चलकर उसी रास्ते से वापस घर आ गए — तय दूरी कितनी है?",
     "You walk 100 metres from home and return by the same path — what is the distance travelled?",
     ["200 मीटर", "100 मीटर", "0 मीटर", "50 मीटर"],
     ["200 metres", "100 metres", "0 metres", "50 metres"],
     0,
     "100 + 100 = 200 मीटर — दूरी पथ का कुल योग है।",
     "100 + 100 = 200 m — distance is the path's total sum."),

    ("distance-displacement", "easy",
     "उसी यात्रा (100 मीटर जाकर वापस) में विस्थापन कितना हुआ?",
     "In that same trip (100 metres out and back), what is the displacement?",
     ["शून्य", "100 मीटर", "200 मीटर", "50 मीटर"],
     ["Zero", "100 metres", "200 metres", "50 metres"],
     0,
     "शुरुआत और मंज़िल एक ही जगह — रस्सी की लंबाई शून्य।",
     "Start and finish are the same spot — the rope's length is zero."),

    ("distance-displacement", "easy",
     "वृत्ताकार पथ का एक पूरा चक्कर लगाने पर विस्थापन कितना होता है?",
     "What is the displacement after completing one full round of a circular path?",
     ["शून्य", "परिधि के बराबर", "त्रिज्या के बराबर", "व्यास के बराबर"],
     ["Zero", "Equal to the circumference", "Equal to the radius", "Equal to the diameter"],
     0,
     "चक्कर के अंत में शुरुआती बिंदु पर ही वापसी — विस्थापन शून्य।",
     "At the lap's end you stand at the starting point — displacement zero."),

    ("distance-displacement", "easy",
     "क्या विस्थापन शून्य होते हुए भी दूरी शून्य-न-हो सकती है?",
     "Can distance be non-zero while displacement is zero?",
     ["हाँ — जैसे पूरा चक्कर लगाने पर", "नहीं, कभी नहीं", "केवल सीधी रेखा में", "केवल तेज़ चलने पर"],
     ["Yes — as on completing a full round", "No, never", "Only in a straight line", "Only while walking fast"],
     0,
     "पथभर चलते रहो और वहीं लौट आओ — दूरी भरी, विस्थापन खाली।",
     "Keep walking the path and land back home — distance full, displacement empty."),

    ("distance-displacement", "easy",
     "दूरी का मान कब ऋणात्मक हो सकता है?",
     "When can the value of distance be negative?",
     ["कभी नहीं", "वापस चलने पर", "पश्चिम चलने पर", "गति रुकने पर"],
     ["Never", "While walking back", "While walking west", "When motion stops"],
     0,
     "पथ की लंबाई में जोड़ा ही जाता है, घटाया नहीं — दूरी सदा धनात्मक या शून्य।",
     "Path length only accumulates, never subtracts — distance is always positive or zero."),

    ("distance-displacement", "easy",
     "एक विद्यार्थी पूर्व 3 मीटर चला — उसके विस्थापन में दिशा क्यों लिखी जाती है?",
     "A student walks 3 metres east — why is a direction stated in the displacement?",
     ["क्योंकि विस्थापन सदिश है — परिमाण से बिना दिशा के अर्थ पूरा नहीं", "क्योंकि दूरी भी सदिश है", "क्योंकि 3 बड़ी संख्या है", "क्योंकि पूर्व शुभ है"],
     ["Because displacement is a vector — without direction magnitude alone is incomplete", "Because distance is also a vector", "Because 3 is a big number", "Because east is auspicious"],
     0,
     "सदिश की पहचान ही दिशा है — '3 मीटर' अधूरा, '3 मीटर पूर्व' पूरा।",
     "A vector's identity is its direction — '3 m' incomplete, '3 m east' complete."),

    ("distance-displacement", "easy",
     "सीधी सड़क पर आगे और पीछे समान दूरी चलने पर कौन-सी राशि शून्य हो जाती है?",
     "Walking equal distances forward and backward on a straight road makes which quantity zero?",
     ["विस्थापन", "दूरी", "समय", "चाल भी और दूरी भी"],
     ["Displacement", "Distance", "Time", "Both speed and distance"],
     0,
     "आगे-पीछे की बराबर लंबाई एक-दूसरे को काट देती है — विस्थापन शून्य।",
     "Equal forward and backward lengths cancel each other — displacement zero."),

    ("distance-displacement", "easy",
     "किसी वस्तु की गति का वर्णन करते समय 'प्रारंभिक बिंदु' और 'अंतिम बिंदु' किस राशि की गणना के लिए जरूरी हैं?",
     "While describing motion, 'initial point' and 'final point' are needed to compute which quantity?",
     ["विस्थापन", "द्रव्यमान", "आयतन", "घनत्व"],
     ["Displacement", "Mass", "Volume", "Density"],
     0,
     "विस्थापन दो बिंदुओं की रस्सी है — दोनों सिरों का पता होना जरूरी।",
     "Displacement is the rope between two points — both ends must be known."),

    ("distance-displacement", "medium",
     "पूर्व 4 मीटर और फिर उत्तर 3 मीटर चलने पर विस्थापन का परिमाण कितना होगा?",
     "Walking 4 metres east and then 3 metres north, what is the magnitude of displacement?",
     ["5 मीटर", "7 मीटर", "1 मीटर", "12 मीटर"],
     ["5 metres", "7 metres", "1 metre", "12 metres"],
     0,
     "सीधे कोने पर पाइथागोरस: √(4² + 3²) = √25 = 5 मीटर।",
     "Right-angle Pythagoras: √(4² + 3²) = √25 = 5 m."),

    ("distance-displacement", "medium",
     "उसी स्थिति (4 मीटर पूर्व, 3 मीटर उत्तर) में तय कुल दूरी कितनी है?",
     "In the same case (4 m east, 3 m north), what is the total distance travelled?",
     ["7 मीटर", "5 मीटर", "1 मीटर", "25 मीटर"],
     ["7 metres", "5 metres", "1 metre", "25 metres"],
     0,
     "दूरी पथ का योग है: 4 + 3 = 7 मीटर (विस्थापन 5 मीटर रहा)।",
     "Distance is the path's sum: 4 + 3 = 7 m (displacement was 5 m)."),

    ("distance-displacement", "medium",
     "एक वृत्ताकार मैदान की परिधि 400 मीटर है। आधा चक्कर लगाने पर दूरी और विस्थापन क्रमशः क्या होंगे? (त्रिज्या ≈ 63.7 मीटर मानकर व्यास ≈ 127 मीटर)",
     "A circular track has a 400-metre circumference. After half a round, distance and displacement respectively are — (take diameter ≈ 127 m)",
     ["दूरी 200 मीटर, विस्थापन 127 मीटर", "दोनों 200 मीटर", "दूरी 127 मीटर, विस्थापन 200 मीटर", "दोनों शून्य"],
     ["Distance 200 m, displacement 127 m", "Both 200 m", "Distance 127 m, displacement 200 m", "Both zero"],
     0,
     "आधा पथ = 200 मीटर; आधे चक्कर की रस्सी = व्यास ≈ 127 मीटर — दूरी बड़ी, विस्थापन छोटा।",
     "Half the path = 200 m; half-lap rope = diameter ≈ 127 m — distance larger, displacement smaller."),

    ("distance-displacement", "medium",
     "एक वस्तु पहले 5 मीटर पूर्व, फिर 5 मीटर पश्चिम चली — दूरी और विस्थापन क्रमशः हैं —",
     "An object moves 5 m east, then 5 m west — distance and displacement respectively are —",
     ["10 मीटर, शून्य", "शून्य, 10 मीटर", "5 मीटर, 5 मीटर", "10 मीटर, 10 मीटर"],
     ["10 m, zero", "Zero, 10 m", "5 m, 5 m", "10 m, 10 m"],
     0,
     "पथ 5 + 5 = 10 मीटर; सिरा वहीं जहाँ से चली — विस्थापन शून्य।",
     "Path 5 + 5 = 10 m; ends where it began — displacement zero."),

    ("distance-displacement", "medium",
     "यदि किसी गति में विस्थापन का परिमाण तय दूरी के बराबर है, तो गति के बारे में क्या कहा जा सकता है?",
     "If in a motion the displacement's magnitude equals the distance travelled, what can be said about the motion?",
     ["गति एक ही दिशा में सीधी रेखा में हुई", "गति वृत्ताकार थी", "गति में दिशा बदलती रही", "वस्तु स्थिर रही"],
     ["The motion was in a straight line in one direction", "The motion was circular", "The direction kept changing", "The object stayed at rest"],
     0,
     "रस्सी ही रास्ता तभी जब कोई मोड़ न हो — सीधी, एक-दिशा गति।",
     "The rope equals the road only when there are no turns — straight, one-way motion."),

    ("distance-displacement", "medium",
     "ट्रेन स्टेशन A से घुमावदार पटरी से C होते हुए B पहुँचती है। कौन-सा कथन सही है?",
     "A train goes from station A to B via a curved track through C. Which statement is correct?",
     ["A से B तक दूरी, A से B विस्थापन से अधिक या बराबर होगी", "विस्थापन सदा अधिक होगा", "दोनों बराबर ही होंगे", "दूरी शून्य होगी"],
     ["Distance A to B will be greater than or equal to displacement A to B", "Displacement will always be greater", "Both will always be equal", "Distance will be zero"],
     0,
     "घुमाव पथ को लंबा करता है, रस्सी को नहीं।",
     "Curves lengthen the path, never the rope."),

    ("distance-displacement", "medium",
     "कथन A: दूरी और विस्थापन के मात्रक समान होते हैं। कथन B: दोनों राशियाँ सदैव समान मान रखती हैं। सही विकल्प —",
     "Statement A: distance and displacement have the same unit. Statement B: the two always have the same value. The correct option —",
     ["A सही, B गलत", "A गलत, B सही", "दोनों सही", "दोनों गलत"],
     ["A right, B wrong", "A wrong, B right", "Both right", "Both wrong"],
     0,
     "मात्रक दोनों का मीटर; मान सीधी-रेखा गति को छोड़कर भिन्न हो सकता है।",
     "Both share the metre; values can differ except in straight-line motion."),

    ("distance-displacement", "medium",
     "एक व्यक्ति 8 मीटर पूर्व और 6 मीटर उत्तर चलता है — उसकी दूरी और विस्थापन का अंतर कितना है?",
     "A person walks 8 m east and 6 m north — what is the difference between distance and displacement?",
     ["4 मीटर", "2 मीटर", "14 मीटर", "0 मीटर"],
     ["4 metres", "2 metres", "14 metres", "0 metres"],
     0,
     "दूरी 8 + 6 = 14; विस्थापन √(64+36) = 10; अंतर = 14 − 10 = 4 मीटर।",
     "Distance 8 + 6 = 14; displacement √(64+36) = 10; difference = 14 − 10 = 4 m."),

    ("distance-displacement", "medium",
     "विस्थापन शून्य होने के लिए आवश्यक शर्त क्या है?",
     "What is the necessary condition for displacement to be zero?",
     ["अंतिम बिंदु प्रारंभिक बिंदु पर ही हो", "तय दूरी शून्य हो", "गति सीधी रेखा में हो", "चाल नियत हो"],
     ["The final point coincides with the initial point", "The distance travelled is zero", "The motion is in a straight line", "The speed is constant"],
     0,
     "शुरुआत ही मंज़िल — तब रस्सी की लंबाई शून्य, चाहे पथ कितना भी लंबा।",
     "The start itself is the destination — then the rope's length is zero, however long the path."),

    ("distance-displacement", "medium",
     "समान अंतराल में समान दूरी तय करने वाली गति को क्या कहते हैं?",
     "Motion covering equal distances in equal intervals of time is called —",
     ["एकसमान गति (uniform motion)", "अनियमित गति", "वृत्ताकार गति", "दोलन गति"],
     ["Uniform motion", "Non-uniform motion", "Circular motion", "Oscillatory motion"],
     0,
     "बराबर समय-बराबर फासला — यही एकसमान गति की पहचान।",
     "Equal time, equal gap — that is the signature of uniform motion."),

    ("distance-displacement", "medium",
     "असमान अंतरालों में असमान दूरियाँ तय होने पर गति कहलाती है —",
     "When unequal distances are covered in equal intervals, the motion is called —",
     ["अनियमित (non-uniform)", "एकसमान", "स्थिर", "समय-निरपेक्ष"],
     ["Non-uniform", "Uniform", "At rest", "Time-independent"],
     0,
     "कदमों की लंबाई बदलती रहे तो गति अनियमित।",
     "If the stride keeps changing, the motion is non-uniform."),

    ("distance-displacement", "medium",
     "एक कार 2 किलोमीटर पूर्व जाकर रुकती है और फिर 2 किलोमीटर पश्चिम लौटती है। पूरी यात्रा में दूरी : विस्थापन का अनुपात है —",
     "A car goes 2 km east, stops, and returns 2 km west. In the whole trip the ratio distance : displacement is —",
     ["परिमाण में 4 : 0", "2 : 2", "1 : 1", "0 : 4"],
     ["In magnitude 4 : 0", "2 : 2", "1 : 1", "0 : 4"],
     0,
     "दूरी 4 किमी, विस्थापन 0 — अनुपात 4:0; शून्य से विभाजन सावधानी से देखें, यहाँ केवल तुलना है।",
     "Distance 4 km, displacement 0 — the comparison stands at 4 vs 0."),

    ("distance-displacement", "medium",
     "यात्रा का विवरण: 3 मीटर उत्तर → 4 मीटर पूर्व। विस्थापन की दिशा और परिमाण का युग्म सही चुनें —",
     "Journey: 3 m north → 4 m east. Pick the correct pair of displacement direction and magnitude —",
     ["उत्तर-पूर्व, 5 मीटर", "दक्षिण, 7 मीटर", "पूर्व, 4 मीटर", "उत्तर, 3 मीटर"],
     ["North-east, 5 metres", "South, 7 metres", "East, 4 metres", "North, 3 metres"],
     0,
     "√(3² + 4²) = 5 मीटर, दिशा उत्तर-पूर्व — रस्सी दोनों कदमों के विकर्ण पर।",
     "√(3² + 4²) = 5 m toward north-east — the rope lies on the diagonal of both steps."),

    ("distance-displacement", "medium",
     "दूरी-मापक (odometer) गाड़ी में क्या दर्शाता है — दूरी या विस्थापन?",
     "What does a vehicle's odometer show — distance or displacement?",
     ["दूरी (पथ का कुल योग)", "विस्थापन", "दोनों", "कोई नहीं"],
     ["Distance (the path's total)", "Displacement", "Both", "Neither"],
     0,
     "मीटर जोड़ता जाता है, घटाता नहीं — उधर लौटने पर भी बढ़ता है: यह दूरी है।",
     "The meter only adds, never subtracts — it grows even on the return: that is distance."),

    ("distance-displacement", "hard",
     "एक घड़ी की सुई 15 मिनट में 12 से 3 पर पहुँचती है। सुई के सिरे द्वारा दूरी और विस्थापन (त्रिज्या r) —",
     "A clock's hand goes from 12 to 3 in 15 minutes. For the hand's tip, distance and displacement (radius r) are —",
     ["दूरी = (परिधि)/4, विस्थापन = √2·r", "दोनों बराबर", "दूरी = √2·r, विस्थापन = परिधि/4", "दोनों शून्य"],
     ["Distance = circumference/4, displacement = √2·r", "Both equal", "Distance = √2·r, displacement = circumference/4", "Both zero"],
     0,
     "12 से 3 तक चौथाई वृत्त-चाप = 2πr/4; सीधी रस्सी = √(r²+r²) = √2·r — चाप लंबा, जीवा छोटी।",
     "12-to-3 is a quarter arc = 2πr/4; the straight rope = √(r²+r²) = √2·r — arc long, chord short."),

    ("distance-displacement", "hard",
     "कथन A: दूरी कभी घटती नहीं। कथन B: विस्थापन का परिमाण घट भी सकता है और शून्य भी हो सकता है। सही विकल्प —",
     "Statement A: distance never decreases. Statement B: displacement's magnitude can decrease and even become zero. The correct option —",
     ["दोनों सही", "केवल A सही", "केवल B सही", "दोनों गलत"],
     ["Both are correct", "Only A is correct", "Only B is correct", "Both wrong"],
     0,
     "पथ का काउंटर सिर्फ बढ़ता है; रस्सी गति की दिशा से छोटी-बड़ी होती रहती है।",
     "The path counter only rises; the rope shrinks and stretches with the direction of motion."),

    ("distance-displacement", "hard",
     "व्यक्ति A सीधे 10 मीटर चलता है; व्यक्ति B इसी बिंदु तक वक्र पथ से पहुँचता है। कौन-सा निष्कर्ष निश्चित है?",
     "Person A walks 10 m straight; person B reaches the same point by a curved path. Which conclusion is certain?",
     ["दोनों का विस्थापन समान है, B की दूरी अधिक है", "दोनों की दूरी समान है", "A का विस्थापन अधिक", "B का विस्थापन अधिक"],
     ["Both have the same displacement; B's distance is greater", "Both have the same distance", "A's displacement is greater", "B's displacement is greater"],
     0,
     "मंज़िल एक — रस्सी एक; वक्र रास्ता लंबा — B की दूरी बड़ी।",
     "One destination — one rope; the curved road is longer — B's distance bigger."),

    ("distance-displacement", "hard",
     "यदि किसी यात्रा में दूरी और विस्थापन दोनों शून्य हों, तो वस्तु की अवस्था क्या थी?",
     "If in a journey both distance and displacement are zero, what was the object's state?",
     ["वस्तु विरामावस्था में थी (कोई गति नहीं)", "वस्तु चक्कर लगाती रही", "वस्तु ने आगे-पीछे चलना किया", "वस्तु तेज़ दौड़ी"],
     ["The object was at rest (no motion)", "The object kept circling", "The object moved to and fro", "The object ran fast"],
     0,
     "पथ शून्य का अर्थ — कदम ही नहीं उठा; चक्कर या आगे-पीछे में दूरी बनती।",
     "Zero path means not a step taken; circling or to-and-fro would build distance."),

    ("distance-displacement", "hard",
     "आधे चक्कर (अर्धवृत्त) की यात्रा में दूरी और विस्थापन का अनुपात (त्रिज्या r) होगा —",
     "For a half-round (semi-circular) trip, the ratio distance : displacement (radius r) will be —",
     ["π : 2", "2 : π", "1 : 1", "π : 1"],
     ["π : 2", "2 : π", "1 : 1", "π : 1"],
     0,
     "अर्धपरिधि πr, विस्थापन = व्यास 2r → अनुपात πr : 2r = π : 2।",
     "Semi-arc πr, displacement = diameter 2r → ratio πr : 2r = π : 2."),

    ("distance-displacement", "hard",
     "एक विमान 300 किमी उत्तर, फिर 400 किमी पूर्व उड़ता है। प्रारंभ-बिंदु से विस्थापन कितना?",
     "A plane flies 300 km north, then 400 km east. What is its displacement from the start?",
     ["500 किलोमीटर (उत्तर-पूर्व दिशा में)", "700 किलोमीटर", "100 किलोमीटर", "शून्य"],
     ["500 km (toward north-east)", "700 km", "100 km", "Zero"],
     0,
     "√(300² + 400²) = √250000 = 500 किमी — 3-4-5 त्रिभुज की हवाई रस्सी।",
     "√(300² + 400²) = √250000 = 500 km — the aerial rope of a 3-4-5 triangle."),

    ("distance-displacement", "medium",
     "एक वस्तु 5 मीटर पश्चिम और फिर 12 मीटर उत्तर चलती है — विस्थापन का परिमाण कितना?",
     "An object moves 5 m west and then 12 m north — what is the magnitude of displacement?",
     ["13 मीटर", "17 मीटर", "7 मीटर", "60 मीटर"],
     ["13 metres", "17 metres", "7 metres", "60 metres"],
     0,
     "समकोण पर √(5² + 12²) = √169 = 13 मीटर — 5-12-13 त्रिक।",
     "At right angles √(5² + 12²) = √169 = 13 m — the 5-12-13 triple."),

    ("distance-displacement", "medium",
     "क्या ऐसा संभव है कि तय दूरी बढ़ती रहे पर विस्थापन का परिमान घटता रहे?",
     "Is it possible that the distance travelled keeps growing while the displacement's magnitude keeps shrinking?",
     ["हाँ — जैसे शुरुआत से दूर जाकर वापस आधे रास्ते पर लौटने पर", "नहीं, कभी नहीं", "केवल वृत्त में", "केवल विराम में"],
     ["Yes — as when going far from the start and then returning part of the way", "No, never", "Only in a circle", "Only at rest"],
     0,
     "लौटते कदम दूरी में जुड़ते हैं पर रस्सी छोटी करते हैं।",
     "Returning steps add to the path yet shorten the rope."),

    # ================= SPEED & VELOCITY — 38 (E15/M16/H7) =================
    ("speed-velocity", "easy",
     "चाल (speed) का सूत्र क्या है?",
     "What is the formula for speed?",
     ["चाल = दूरी / समय", "चाल = समय / दूरी", "चाल = दूरी × समय", "चाल = विस्थापन × समय"],
     ["Speed = distance / time", "Speed = time / distance", "Speed = distance × time", "Speed = displacement × time"],
     0,
     "एक सेकंड में कितना रास्ता — यही चाल की परिभाषा।",
     "How much road per second — that is speed's definition."),

    ("speed-velocity", "easy",
     "वेग (velocity) का सूत्र क्या है?",
     "What is the formula for velocity?",
     ["वेग = विस्थापन / समय", "वेग = दूरी / समय", "वेग = समय / विस्थापन", "वेग = दूरी × समय"],
     ["Velocity = displacement / time", "Velocity = distance / time", "Velocity = time / displacement", "Velocity = distance × time"],
     0,
     "वेग रस्सी की रफ्तार है — विस्थापन प्रति सेकंड।",
     "Velocity is the rope's pace — displacement per second."),

    ("speed-velocity", "easy",
     "चाल और वेग का SI मात्रक क्या है?",
     "What is the SI unit of both speed and velocity?",
     ["मीटर/सेकंड (m/s)", "मीटर-सेकंड", "किलोमीटर", "सेकंड/मीटर"],
     ["Metre/second (m/s)", "Metre-second", "Kilometre", "Second/metre"],
     0,
     "लंबाई विभाजित समय से — मीटर प्रति सेकंड।",
     "Length divided by time — metre per second."),

    ("speed-velocity", "easy",
     "चाल किस प्रकार की राशि है?",
     "What kind of quantity is speed?",
     ["अदिश (केवल परिमाण)", "सदिश (परिमाण + दिशा)", "मात्रक-रहित", "कभी अदिश कभी सदिश"],
     ["Scalar (magnitude only)", "Vector (magnitude + direction)", "Unitless", "Sometimes scalar, sometimes vector"],
     0,
     "चाल सिर्फ 'कितनी तेज़' — दिशा नहीं पूछती।",
     "Speed asks only 'how fast' — never which way."),

    ("speed-velocity", "easy",
     "वेग किस प्रकार की राशि है?",
     "What kind of quantity is velocity?",
     ["सदिश (परिमाण + दिशा)", "अदिश", "मिश्रित", "मात्रक-रहित"],
     ["Vector (magnitude + direction)", "Scalar", "Mixed", "Unitless"],
     0,
     "वेग 'कितनी तेज़ और किधर' — दोनों बताता है।",
     "Velocity tells 'how fast and which way' — both."),

    ("speed-velocity", "easy",
     "एक कार 100 मीटर की दूरी 20 सेकंड में तय करती है — उसकी चाल कितनी है?",
     "A car covers 100 metres in 20 seconds — what is its speed?",
     ["5 मीटर/सेकंड", "20 मीटर/सेकंड", "2000 मीटर/सेकंड", "0.2 मीटर/सेकंड"],
     ["5 m/s", "20 m/s", "2000 m/s", "0.2 m/s"],
     0,
     "100 ÷ 20 = 5 मीटर/सेकंड।",
     "100 ÷ 20 = 5 m/s."),

    ("speed-velocity", "easy",
     "एकसमान चाल (uniform speed) से चलती बस 10 मिनट में 3 किलोमीटर चलती है — चाल मीटर/सेकंड में कितनी? (1 किमी = 1000 मीटर)",
     "A bus moving at uniform speed covers 3 km in 10 minutes — the speed in m/s is — (1 km = 1000 m)",
     ["5 मीटर/सेकंड", "30 मीटर/सेकंड", "300 मीटर/सेकंड", "0.5 मीटर/सेकंड"],
     ["5 m/s", "30 m/s", "300 m/s", "0.5 m/s"],
     0,
     "3000 मीटर ÷ 600 सेकंड = 5 मीटर/सेकंड।",
     "3000 m ÷ 600 s = 5 m/s."),

    ("speed-velocity", "easy",
     "s = v × t सूत्र में s क्या दर्शाता है?",
     "In the formula s = v × t, what does s stand for?",
     ["तय की गई दूरी", "चाल", "समय", "विस्थापन की दिशा"],
     ["Distance travelled", "Speed", "Time", "Direction of displacement"],
     0,
     "s = दूरी; v = चाल; t = समय — दूरी चाल और समय का गुणनफल।",
     "s = distance; v = speed; t = time — distance is speed times time."),

    ("speed-velocity", "easy",
     "5 मीटर/सेकंड की चाल से 20 सेकंड चलने पर तय दूरी कितनी होगी?",
     "Walking at 5 m/s for 20 seconds, what distance is covered?",
     ["100 मीटर", "25 मीटर", "4 मीटर", "500 मीटर"],
     ["100 metres", "25 metres", "4 metres", "500 metres"],
     0,
     "s = 5 × 20 = 100 मीटर।",
     "s = 5 × 20 = 100 m."),

    ("speed-velocity", "easy",
     "औसत चाल (average speed) निकालने का सूत्र क्या है?",
     "What is the formula for average speed?",
     ["कुल दूरी / कुल समय", "कुल समय / कुल दूरी", "प्रारंभिक चाल + अंतिम चाल", "सबसे बड़ी चाल"],
     ["Total distance / total time", "Total time / total distance", "Initial speed + final speed", "The maximum speed"],
     0,
     "औसत पूरी यात्रा का हिसाब है — कुल दूरी पर कुल समय।",
     "The average belongs to the whole journey — total distance over total time."),

    ("speed-velocity", "easy",
     "क्या किसी वस्तु की चाल नियत हो और वेग बदलता रहे?",
     "Can an object have constant speed while its velocity keeps changing?",
     ["हाँ — जैसे वृत्ताकार पथ में एकसमान चाल से दौड़ते हुए", "नहीं, असंभव", "केवल सीधी रेखा में", "केवल विरामावस्था में"],
     ["Yes — as while running at steady speed on a circular track", "No, impossible", "Only in a straight line", "Only at rest"],
     0,
     "दिशा बदलती रहे तो वेग बदलता रहता है — चाल शुद्ध परिमाण है।",
     "If direction keeps turning, velocity keeps changing — speed is pure magnitude."),

    ("speed-velocity", "easy",
     "साइकिल सवार 15 मिनट में 4.5 किलोमीटर चलता है — औसत चाल कितनी?",
     "A cyclist covers 4.5 km in 15 minutes — what is the average speed?",
     ["18 किमी/घंटा", "4.5 किमी/घंटा", "45 किमी/घंटा", "30 किमी/घंटा"],
     ["18 km/h", "4.5 km/h", "45 km/h", "30 km/h"],
     0,
     "15 मिनट = 0.25 घंटा; 4.5 ÷ 0.25 = 18 किमी/घंटा।",
     "15 min = 0.25 h; 4.5 ÷ 0.25 = 18 km/h."),

    ("speed-velocity", "easy",
     "वेग का मान ऋणात्मक कब लिखा जा सकता है?",
     "When can velocity be written with a negative sign?",
     ["चुनी गई धनात्मक दिशा के विपरीत गति होने पर", "चाल घटने पर", "दूरी शून्य होने पर", "कभी नहीं"],
     ["When the motion is opposite to the chosen positive direction", "When speed decreases", "When distance is zero", "Never"],
     0,
     "चिह्न दिशा बताता है — धनात्मक दिशा से उलट चलने पर ऋणात्मक वेग।",
     "The sign speaks of direction — motion opposite to the positive sense is negative velocity."),

    ("speed-velocity", "easy",
     "एक धावक 200 मीटर दौड़ 25 सेकंड में पूरी करता है — उसकी औसत चाल?",
     "A runner finishes a 200-metre race in 25 seconds — average speed?",
     ["8 मीटर/सेकंड", "5 मीटर/सेकंड", "25 मीटर/सेकंड", "0.125 मीटर/सेकंड"],
     ["8 m/s", "5 m/s", "25 m/s", "0.125 m/s"],
     0,
     "200 ÷ 25 = 8 मीटर/सेकंड।",
     "200 ÷ 25 = 8 m/s."),

    ("speed-velocity", "easy",
     "चाल और वेग के मान कब बराबर होते हैं?",
     "When are the values of speed and velocity equal?",
     ["सीधी रेखा में एक ही दिशा की गति में", "वृत्ताकार गति में हमेशा", "दिशा बदलते समय", "कभी नहीं"],
     ["In straight-line motion in one direction", "Always in circular motion", "While direction changes", "Never"],
     0,
     "जब पथ ही रस्सी हो — सीधी, एक-दिशा गति — तब दोनों बराबर।",
     "When the path itself is the rope — straight, one-way motion — the two are equal."),

    ("speed-velocity", "medium",
     "72 किमी/घंटा को मीटर/सेकंड में बदलो —",
     "Convert 72 km/h into m/s —",
     ["20 मीटर/सेकंड", "7.2 मीटर/सेकंड", "36 मीटर/सेकंड", "200 मीटर/सेकंड"],
     ["20 m/s", "7.2 m/s", "36 m/s", "200 m/s"],
     0,
     "72 × 1000/3600 = 72 × 5/18 = 20 मीटर/सेकंड।",
     "72 × 1000/3600 = 72 × 5/18 = 20 m/s."),

    ("speed-velocity", "medium",
     "36 किमी/घंटा कितने मीटर/सेकंड होता है?",
     "How many m/s is 36 km/h?",
     ["10 मीटर/सेकंड", "6 मीटर/सेकंड", "360 मीटर/सेकंड", "3.6 मीटर/सेकंड"],
     ["10 m/s", "6 m/s", "360 m/s", "3.6 m/s"],
     0,
     "36 × 5/18 = 10 मीटर/सेकंड।",
     "36 × 5/18 = 10 m/s."),

    ("speed-velocity", "medium",
     "90 किमी/घंटा की कार की चाल मीटर/सेकंड में?",
     "A car at 90 km/h — speed in m/s?",
     ["25 मीटर/सेकंड", "9 मीटर/सेकंड", "900 मीटर/सेकंड", "18 मीटर/सेकंड"],
     ["25 m/s", "9 m/s", "900 m/s", "18 m/s"],
     0,
     "90 × 5/18 = 25 मीटर/सेकंड।",
     "90 × 5/18 = 25 m/s."),

    ("speed-velocity", "medium",
     "एक कार पहले 30 किमी/घंटा की चाल से 2 घंटे, फिर 60 किमी/घंटा की चाल से 1 घंटा चलती है — औसत चाल?",
     "A car travels 2 hours at 30 km/h, then 1 hour at 60 km/h — average speed?",
     ["40 किमी/घंटा", "45 किमी/घंटा", "30 किमी/घंटा", "90 किमी/घंटा"],
     ["40 km/h", "45 km/h", "30 km/h", "90 km/h"],
     0,
     "दूरी 60 + 60 = 120 किमी; समय 3 घंटे; औसत = 120/3 = 40 किमी/घंटा (45 नहीं — यही जाल है)।",
     "Distance 60 + 60 = 120 km; time 3 h; average = 120/3 = 40 km/h (not 45 — the classic trap)."),

    ("speed-velocity", "medium",
     "पहाड़ी पर जाते समय 20 किमी/घंटा और लौटते समय उसी दूरी 30 किमी/घंटा — पूरी यात्रा की औसत चाल?",
     "Up a hill at 20 km/h and back the same distance at 30 km/h — average speed for the whole trip?",
     ["24 किमी/घंटा", "25 किमी/घंटा", "26 किमी/घंटा", "50 किमी/घंटा"],
     ["24 km/h", "25 km/h", "26 km/h", "50 km/h"],
     0,
     "मान लो एक तरफ 60 किमी: जाना 3 घंटे, लौटना 2 घंटे; औसत = 120/5 = 24 किमी/घंटा — साधारण औसत (25) गलत।",
     "Take 60 km each way: up 3 h, down 2 h; average = 120/5 = 24 km/h — the simple mean (25) is wrong."),

    ("speed-velocity", "medium",
     "एक वाहन पहले 60 मीटर 10 सेकंड में, फिर 40 मीटर 30 सेकंड में चलता है — कुल यात्रा की औसत चाल?",
     "A vehicle covers 60 m in 10 s, then 40 m in 30 s — average speed of the whole journey?",
     ["2.5 मीटर/सेकंड", "5 मीटर/सेकंड", "1.33 मीटर/सेकंड", "10 मीटर/सेकंड"],
     ["2.5 m/s", "5 m/s", "1.33 m/s", "10 m/s"],
     0,
     "कुल दूरी 100 मीटर, कुल समय 40 सेकंड → 100/40 = 2.5 मीटर/सेकंड।",
     "Total 100 m in 40 s → 100/40 = 2.5 m/s."),

    ("speed-velocity", "medium",
     "60 किमी/घंटा से 2 घंटे चलकर ट्रेन ने कितना रास्ता तय किया?",
     "At 60 km/h for 2 hours, how far does the train go?",
     ["120 किलोमीटर", "30 किलोमीटर", "62 किलोमीटर", "600 किलोमीटर"],
     ["120 kilometres", "30 kilometres", "62 kilometres", "600 kilometres"],
     0,
     "s = 60 × 2 = 120 किलोमीटर।",
     "s = 60 × 2 = 120 km."),

    ("speed-velocity", "medium",
     "15 मीटर/सेकंड की चाल से चलती रेल 600 मीटर का पुल कितने समय में पार करेगी?",
     "At 15 m/s, in what time does a rail cross a 600-metre bridge?",
     ["40 सेकंड", "4 सेकंड", "90 सेकंड", "9000 सेकंड"],
     ["40 seconds", "4 seconds", "90 seconds", "9000 seconds"],
     0,
     "t = 600/15 = 40 सेकंड।",
     "t = 600/15 = 40 s."),

    ("speed-velocity", "medium",
     "औरत चाल और वेग में से कौन-सी राशि 'दिशा बदलने पर' बदलती है?",
     "Which of speed and velocity changes when direction changes?",
     ["वेग", "चाल", "दोनों", "कोई नहीं"],
     ["Velocity", "Speed", "Both", "Neither"],
     0,
     "चाल को दिशा से कोई मतलब नहीं; वेग सदिश है — मोड़ पर बदल जाता है।",
     "Speed cares nothing for direction; velocity is a vector — it changes at the turn."),

    ("speed-velocity", "medium",
     "कथन A: चाल कभी ऋणात्मक नहीं होती। कथन B: वेग ऋणात्मक हो सकता है। सही विकल्प —",
     "Statement A: speed is never negative. Statement B: velocity can be negative. The correct option —",
     ["दोनों सही", "केवल A सही", "केवल B सही", "दोनों गलत"],
     ["Both are correct", "Only A is correct", "Only B is correct", "Both wrong"],
     0,
     "पथ-लंबाई सदा धनात्मक; वेग का चिह्न दिशा की सूचना देता है।",
     "Path length is always positive; velocity's sign informs the direction."),

    ("speed-velocity", "medium",
     "एक तीरंदाज गोल मैदान में स्थिर तेज़ रफ्तार से दौड़ता है। उसकी चाल 8 मीटर/सेकंड स्थिर है — वेग?",
     "An athlete runs on a circular ground at a steady fast pace. Speed constant at 8 m/s — the velocity?",
     ["परिमाण 8 रहते हुए भी दिशा बदलने से वेग बदलता रहता है", "वेग भी पूरी तरह स्थिर रहता है", "वेग शून्य हो जाता है", "वेग बढ़ता रहता है"],
     ["Velocity keeps changing as direction turns, magnitude 8 staying put", "Velocity also stays fully constant", "Velocity becomes zero", "Velocity keeps increasing"],
     0,
     "नियत चाल + बदलती दिशा = बदलता वेग — वृत्ताकार गति की पहचान।",
     "Steady speed + turning direction = changing velocity — the mark of circular motion."),

    ("speed-velocity", "medium",
     "वेग 10 मीटर/सेकंड से चलती वस्तु 30 सेकंड में कितना विस्थापन करेगी (सीधी रेखा में)?",
     "An object moving at 10 m/s in a straight line — displacement in 30 seconds?",
     ["300 मीटर", "3 मीटर", "30 मीटर", "0.33 मीटर"],
     ["300 metres", "3 metres", "30 metres", "0.33 metres"],
     0,
     "विस्थापन = 10 × 30 = 300 मीटर (सीधी रेखा में दूरी भी यही)।",
     "Displacement = 10 × 30 = 300 m (in a straight line, distance equals it)."),

    ("speed-velocity", "medium",
     "आधे घंटे में 9 किलोमीटर चलने वाली बस की चाल मीटर/सेकंड में लगभग कितनी?",
     "A bus covers 9 km in half an hour — its speed in m/s is about?",
     ["5 मीटर/सेकंड", "18 मीटर/सेकंड", "9 मीटर/सेकंड", "50 मीटर/सेकंड"],
     ["5 m/s", "18 m/s", "9 m/s", "50 m/s"],
     0,
     "9000 मीटर / 1800 सेकंड = 5 मीटर/सेकंड।",
     "9000 m / 1800 s = 5 m/s."),

    ("speed-velocity", "medium",
     "दो बसें: A 40 किमी/घंटा, B 10 मीटर/सेकंड — कौन तेज़ है?",
     "Two buses: A at 40 km/h, B at 10 m/s — which is faster?",
     ["बस A (क्योंकि 10 मीटर/सेकंड = 36 किमी/घंटा, जो 40 से कम है)", "बस B स्पष्ट रूप से", "दोनों बराबर", "तुलना संभव नहीं"],
     ["Bus A (since 10 m/s equals 36 km/h, which is less than 40)", "Clearly bus B", "Both equal", "Comparison impossible"],
     0,
     "इकाई समान करो: 10 मीटर/सेकंड = 36 किमी/घंटा → A (40) तेज़ है।",
     "Unify units: 10 m/s = 36 km/h → A (40) is faster."),

    ("speed-velocity", "medium",
     "एक कार की स्पीडोमीटर 60 किमी/घंटा दिखाती है — यह कौन-सी राशि है?",
     "A car's speedometer reads 60 km/h — which quantity is this?",
     ["तात्क्षणिक चाल (उस क्षण की)", "औसत चाल", "औसत वेग", "त्वरण"],
     ["Instantaneous speed (of that moment)", "Average speed", "Average velocity", "Acceleration"],
     0,
     "स्पीडोमीटर उस पल की चाल बताता है — दिशा नहीं, इसलिए चाल।",
     "The speedometer shows that instant's pace — no direction, hence speed."),

    ("speed-velocity", "medium",
     "54 किमी/घंटा को मीटर/सेकंड में बदलने पर क्या मिलता है?",
     "Converting 54 km/h into m/s gives —",
     ["15 मीटर/सेकंड", "5.4 मीटर/सेकंड", "54 मीटर/सेकंड", "150 मीटर/सेकंड"],
     ["15 m/s", "5.4 m/s", "54 m/s", "150 m/s"],
     0,
     "54 × 5/18 = 3 × 5 = 15 मीटर/सेकंड।",
     "54 × 5/18 = 3 × 5 = 15 m/s."),

    ("speed-velocity", "hard",
     "एक कार ने एक वृत्ताकार 500 मीटर परिधि वाले मैदान के डेढ़ चक्कर 100 सेकंड में पूरे किए — दूरी और औसत चाल?",
     "A car completes one and a half rounds of a 500 m-circumference circular ground in 100 s — distance and average speed?",
     ["दूरी 750 मीटर, औसत चाल 7.5 मीटर/सेकंड", "दूरी 500 मीटर, चाल 5 मीटर/सेकंड", "दूरी 1000 मीटर, चाल 10 मीटर/सेकंड", "दूरी 250 मीटर, चाल 2.5 मीटर/सेकंड"],
     ["Distance 750 m, average speed 7.5 m/s", "Distance 500 m, speed 5 m/s", "Distance 1000 m, speed 10 m/s", "Distance 250 m, speed 2.5 m/s"],
     0,
     "1.5 × 500 = 750 मीटर; 750/100 = 7.5 मीटर/सेकंड।",
     "1.5 × 500 = 750 m; 750/100 = 7.5 m/s."),

    ("speed-velocity", "hard",
     "उसी कार (500 मीटर परिधि, डेढ़ चक्कर) का विस्थापन और औसत वेग का परिमाण क्या होगा?",
     "For the same car (500 m circumference, one and a half rounds), what are the displacement and average velocity's magnitude?",
     ["विस्थापन = व्यास (≈159 मीटर), औसत वेग ≈ 1.59 मीटर/सेकंड", "विस्थापन 750 मीटर, वेग 7.5 मीटर/सेकंड", "विस्थापन शून्य, वेग शून्य", "विस्थापन 500 मीटर, वेग 5 मीटर/सेकंड"],
     ["Displacement = diameter (≈159 m), average velocity ≈ 1.59 m/s", "Displacement 750 m, velocity 7.5 m/s", "Displacement zero, velocity zero", "Displacement 500 m, velocity 5 m/s"],
     0,
     "डेढ़ चक्कर = एक चक्कर + आधा: आधे चक्कर की रस्सी व्यास ≈ 500/π ≈ 159 मीटर; वेग = 159/100 ≈ 1.59 मीटर/सेकंड।",
     "1.5 rounds = one full + half: the half's rope is the diameter ≈ 500/π ≈ 159 m; velocity = 159/100 ≈ 1.59 m/s."),

    ("speed-velocity", "hard",
     "राम ने गंगा किनारे 3 किमी/घंटा से नाव चलाई और वापसी में नदी के साथ-साथ उतनी ही दूरी 6 किमी/घंटा से — औसत चाल क्या होगी?",
     "Ram rows 3 km/h along a river stretch and returns the same distance at 6 km/h — what is the average speed?",
     ["4 किमी/घंटा", "4.5 किमी/घंटा", "5 किमी/घंटा", "9 किमी/घंटा"],
     ["4 km/h", "4.5 km/h", "5 km/h", "9 km/h"],
     0,
     "मान लो 6 किमी एक तरफ: जाना 2 घंटे, लौटना 1 घंटा → 12/3 = 4 किमी/घंटा।",
     "Take 6 km each way: out 2 h, back 1 h → 12/3 = 4 km/h."),

    ("speed-velocity", "hard",
     "ध्वनि 340 मीटर/सेकंड से चलती है। बिजली चमकी और 3 सेकंड बाद गड़गड़ाहट सुनाई दी — बादल की दूरी लगभग कितनी?",
     "Sound travels at 340 m/s. Lightning flashed and thunder was heard 3 seconds later — the cloud's distance is about?",
     ["1020 मीटर", "113 मीटर", "340 मीटर", "343 मीटर"],
     ["1020 metres", "113 metres", "340 metres", "343 metres"],
     0,
     "s = 340 × 3 = 1020 मीटर — चाल-समय सूत्र का वास्तविक उपयोग।",
     "s = 340 × 3 = 1020 m — the speed-time formula at real work."),

    ("speed-velocity", "hard",
     "कथन A: औसत चाल = (v1+v2)/2 केवल तभी जब दोनों चालों में समय समान हो। कथन B: समान दूरी की दो चालों का औसत समय-भारित होता है। सही विकल्प —",
     "Statement A: average speed = (v1+v2)/2 only when the times spent at the two speeds are equal. Statement B: for equal distances at two speeds, the average is time-weighted. The correct option —",
     ["दोनों सही", "केवल A सही", "केवल B सही", "दोनों गलत"],
     ["Both are correct", "Only A is correct", "Only B is correct", "Both wrong"],
     0,
     "औसत का उत्तर समय-तापमान पर निर्भर है — समान समय पर सरल औसत, समान दूरी पर कुल-दूरी/कुल-समय।",
     "The average's answer depends on time — equal times allow the simple mean; equal distances demand total/total."),

    ("speed-velocity", "hard",
     "एक धावक 100 मीटर 10 सेकंड में और दूसरा 200 मीटर 25 सेकंड में दौड़ता है — किसकी औसत चाल अधिक?",
     "One sprinter runs 100 m in 10 s and another 200 m in 25 s — whose average speed is higher?",
     ["पहला (10 मीटर/सेकंड बनाम 8 मीटर/सेकंड)", "दूसरा", "दोनों बराबर", "तुलना के लिए दिशा चाहिए"],
     ["The first (10 m/s versus 8 m/s)", "The second", "Both equal", "Direction is needed to compare"],
     0,
     "100/10 = 10; 200/25 = 8 — पहले की औसत चाल बड़ी।",
     "100/10 = 10; 200/25 = 8 — the first sprinter's average is higher."),

    ("speed-velocity", "hard",
     "एक वस्तु 4 सेकंड में 48 मीटर जाकर उसी 48 मीटर वापस आती है, कुल 12 सेकंड में — औसत चाल और औसत वेग?",
     "An object goes 48 m out and returns the same 48 m, taking 12 s in all — average speed and average velocity?",
     ["चाल 8 मीटर/सेकंड, वेग शून्य", "दोनों 8 मीटर/सेकंड", "चाल शून्य, वेग 8 मीटर/सेकंड", "दोनों शून्य"],
     ["Speed 8 m/s, velocity zero", "Both 8 m/s", "Speed zero, velocity 8 m/s", "Both zero"],
     0,
     "दूरी 96/12 = 8 मीटर/सेकंड; विस्थापन शून्य → औसत वेग शून्य।",
     "Distance 96/12 = 8 m/s; displacement zero → average velocity zero."),
]
