# -*- coding: utf-8 -*-
"""P02 Part-2 — Motion & Time (physics/chapter-02).
74 items: acceleration 37 (E15/M16/H6) + motion-graphs 37 (E14/M17/H6).
Tuple: (topic, difficulty, question_hi, question_en, options_hi[4], options_en[4], correct_idx, expl_hi, expl_en)
Scope: acceleration = rate of change of velocity, a=(v−u)/t, unit m/s², retardation;
graphs described VERBALLY: distance-time slope = speed; velocity-time slope = acceleration,
area under v-t = distance. No Newton's laws (P03), no gravitation values (P04).
"""

PART2 = [
    # ================= ACCELERATION — 37 (E15/M16/H6) =================
    ("acceleration", "easy",
     "त्वरण (acceleration) किसे कहते हैं?",
     "What is meant by acceleration?",
     ["एकांक समय में वेग में परिवर्तन की दर", "एकांक समय में दूरी की दर", "तय की गई कुल दूरी", "वेग की दिशा"],
     ["The rate of change of velocity per unit time", "The rate of distance per unit time", "The total distance covered", "The direction of velocity"],
     0,
     "वेग बदले तो बदलाव की रफ्तार ही त्वरण है।",
     "When velocity changes, the pace of that change is acceleration."),

    ("acceleration", "easy",
     "त्वरण का सूत्र क्या है?",
     "What is the formula for acceleration?",
     ["a = (v − u) / t", "a = v × t", "a = u + v", "a = t / (v − u)"],
     ["a = (v − u) / t", "a = v × t", "a = u + v", "a = t / (v − u)"],
     0,
     "अंतिम वेग v में से प्रारंभिक वेग u घटाकर समय से भाग।",
     "Subtract initial velocity u from final velocity v, divide by time."),

    ("acceleration", "easy",
     "त्वरण का SI मात्रक क्या है?",
     "What is the SI unit of acceleration?",
     ["मीटर/सेकंड² (m/s²)", "मीटर/सेकंड", "सेकंड/मीटर", "मीटर×सेकंड"],
     ["Metre/second² (m/s²)", "Metre/second", "Second/metre", "Metre×second"],
     0,
     "(मीटर/सेकंड) प्रति सेकंड = मीटर/सेकंड²।",
     "(m/s) per second = m/s²."),

    ("acceleration", "easy",
     "एकसमान वेग (uniform velocity) से चलती वस्तु का त्वरण कितना होता है?",
     "What is the acceleration of an object moving with uniform velocity?",
     ["शून्य", "धनात्मक", "ऋणात्मक", "अनंत"],
     ["Zero", "Positive", "Negative", "Infinite"],
     0,
     "वेग बदल ही नहीं रहा — परिवर्तन की दर शून्य।",
     "Velocity is not changing at all — the rate of change is zero."),

    ("acceleration", "easy",
     "वेग बढ़ने पर त्वरण की दिशा गति की दिशा के —",
     "When velocity increases, acceleration points —— to the direction of motion.",
     ["अनुकूल (समान) होती है", "विपरीत होती है", "लंबवत होती है", "कोई संबंध नहीं"],
     ["Along (the same way)", "Opposite", "Perpendicular", "Unrelated"],
     0,
     "बढ़ती रफ्तार का त्वरण गति के साथ चलता है।",
     "The acceleration of rising speed travels with the motion."),

    ("acceleration", "easy",
     "वेग घटने पर त्वरण को क्या कहते हैं?",
     "What is acceleration called when velocity decreases?",
     ["मंदन / ऋणात्मक त्वरण (retardation)", "धनात्मक त्वरण", "शून्य त्वरण", "अपकेंद्री त्वरण"],
     ["Retardation / negative acceleration", "Positive acceleration", "Zero acceleration", "Centrifugal acceleration"],
     0,
     "गति के विरुद्ध दिशा में त्वरण = मंदन।",
     "Acceleration opposite to the motion = retardation."),

    ("acceleration", "easy",
     "वेग-समय ग्राफ की ढाल (slope) क्या बताती है?",
     "What does the slope of a velocity-time graph give?",
     ["त्वरण", "दूरी", "चाल", "समय"],
     ["Acceleration", "Distance", "Speed", "Time"],
     0,
     "वेग-समय की ढाल = वेग-परिवर्तन/समय = त्वरण।",
     "v-t slope = velocity-change/time = acceleration."),

    ("acceleration", "easy",
     "किसी मोटरसाइकिल का वेग 5 सेकंड में 10 मीटर/सेकंड से 20 मीटर/सेकंड हुआ — त्वरण कितना?",
     "A motorcycle's velocity goes from 10 m/s to 20 m/s in 5 s — the acceleration is?",
     ["2 मीटर/सेकंड²", "10 मीटर/सेकंड²", "0.5 मीटर/सेकंड²", "4 मीटर/सेकंड²"],
     ["2 m/s²", "10 m/s²", "0.5 m/s²", "4 m/s²"],
     0,
     "(20 − 10)/5 = 2 मीटर/सेकंड²।",
     "(20 − 10)/5 = 2 m/s²."),

    ("acceleration", "easy",
     "विरामावस्था से चलना शुरू करने वाली वस्तु का प्रारंभिक वेग (u) कितना माना जाता है?",
     "For an object starting from rest, what is the initial velocity (u) taken as?",
     ["शून्य", "1 मीटर/सेकंड", "9.8 मीटर/सेकंड", "अनंत"],
     ["Zero", "1 m/s", "9.8 m/s", "Infinite"],
     0,
     "विराम का अर्थ — शुरुआती वेग शून्य।",
     "Rest means the starting velocity is zero."),

    ("acceleration", "easy",
     "त्वरण किस प्रकार की राशि है?",
     "What kind of quantity is acceleration?",
     ["सदिश", "अदिश", "मात्रक-रहित", "कभी सदिश कभी अदिश"],
     ["Vector", "Scalar", "Unitless", "Sometimes vector, sometimes scalar"],
     0,
     "त्वरण में परिमाण और दिशा दोनों (वेग-परिवर्तन की दिशा) होते हैं।",
     "Acceleration has both magnitude and direction (of the velocity change)."),

    ("acceleration", "easy",
     "ब्रेक लगाते समय गाड़ी का त्वरण कैसा होता है?",
     "While braking, a vehicle's acceleration is —",
     ["ऋणात्मक (मंदन)", "धनात्मक", "शून्य", "पहले शून्य फिर धनात्मक"],
     ["Negative (retardation)", "Positive", "Zero", "First zero then positive"],
     0,
     "ब्रेक वेग घटाता है — परिवर्तन गति के विपरीत।",
     "Brakes cut the velocity — the change is opposite to motion."),

    ("acceleration", "easy",
     "एक कार का वेग 8 सेकंड में 0 से 16 मीटर/सेकंड होता है — त्वरण?",
     "A car's velocity rises from 0 to 16 m/s in 8 s — acceleration?",
     ["2 मीटर/सेकंड²", "16 मीटर/सेकंड²", "4 मीटर/सेकंड²", "0.5 मीटर/सेकंड²"],
     ["2 m/s²", "16 m/s²", "4 m/s²", "0.5 m/s²"],
     0,
     "(16 − 0)/8 = 2 मीटर/सेकंड²।",
     "(16 − 0)/8 = 2 m/s²."),

    ("acceleration", "easy",
     "'मंदन' (retardation) का मान गणना में किस चिह्न के साथ आता है?",
     "What sign does 'retardation' carry in calculation?",
     ["ऋणात्मक", "धनात्मक", "चिह्न-रहित", "संख्या-रहित"],
     ["Negative", "Positive", "Unsigned", "Numberless"],
     0,
     "मंदन = गति के विपरीत त्वरण → ऋणात्मक चिह्न।",
     "Retardation = acceleration against the motion → negative sign."),

    ("acceleration", "easy",
     "सीधी सड़क पर एकसमान त्वरण से चलती वस्तु का वेग —",
     "For an object moving with uniform acceleration on a straight road, the velocity —",
     ["समान समय-अंतराल में समान मात्रा में बदलता है", "बिल्कुल नहीं बदलता", "अनियमित बदलता है", "शून्य रहता है"],
     ["Changes by equal amounts in equal intervals of time", "Does not change at all", "Changes irregularly", "Stays zero"],
     0,
     "एकसमान त्वरण = वेग-वृद्धि की समान रफ्तार।",
     "Uniform acceleration = an even pace of velocity growth."),

    ("acceleration", "easy",
     "वेग 30 मीटर/सेकंड से घटकर 10 मीटर/सेकंड हुआ, समय 5 सेकंड — त्वरण का मान?",
     "Velocity falls from 30 m/s to 10 m/s in 5 s — the value of acceleration?",
     ["−4 मीटर/सेकंड² (मंदन)", "4 मीटर/सेकंड²", "−8 मीटर/सेकंड²", "40 मीटर/सेकंड²"],
     ["−4 m/s² (retardation)", "4 m/s²", "−8 m/s²", "40 m/s²"],
     0,
     "(10 − 30)/5 = −20/5 = −4 मीटर/सेकंड²।",
     "(10 − 30)/5 = −20/5 = −4 m/s²."),

    ("acceleration", "medium",
     "वेग 25 मीटर/सेकंड से 15 मीटर/सेकंड 5 सेकंड में बदला — त्वरण और उसका प्रकार?",
     "Velocity changes from 25 m/s to 15 m/s in 5 s — acceleration and its type?",
     ["−2 मीटर/सेकंड², मंदन", "+2 मीटर/सेकंड², त्वरण", "−10 मीटर/सेकंड², मंदन", "शून्य"],
     ["−2 m/s², retardation", "+2 m/s², acceleration", "−10 m/s², retardation", "Zero"],
     0,
     "(15 − 25)/5 = −2 — ऋणात्मक, अर्थात् मंदन।",
     "(15 − 25)/5 = −2 — negative, hence retardation."),

    ("acceleration", "medium",
     "विराम से चालू होकर साइकिल 5 सेकंड में 10 मीटर/सेकंड वेग पकड़ती है — त्वरण?",
     "Starting from rest, a bicycle reaches 10 m/s in 5 s — acceleration?",
     ["2 मीटर/सेकंड²", "10 मीटर/सेकंड²", "0.5 मीटर/सेकंड²", "50 मीटर/सेकंड²"],
     ["2 m/s²", "10 m/s²", "0.5 m/s²", "50 m/s²"],
     0,
     "(10 − 0)/5 = 2 मीटर/सेकंड²।",
     "(10 − 0)/5 = 2 m/s²."),

    ("acceleration", "medium",
     "एक बस 18 किमी/घंटा से विराम पर आती है — यदि प्रारंभिक वेग को मीटर/सेकंड में बदलें तो?",
     "A bus comes to rest from 18 km/h — what is the initial velocity in m/s?",
     ["5 मीटर/सेकंड", "18 मीटर/सेकंड", "0.5 मीटर/सेकंड", "50 मीटर/सेकंड"],
     ["5 m/s", "18 m/s", "0.5 m/s", "50 m/s"],
     0,
     "18 × 5/18 = 5 मीटर/सेकंड — इकाई बदलकर ही त्वरण गणना सही होगी।",
     "18 × 5/18 = 5 m/s — only after unit conversion does the acceleration come out right."),

    ("acceleration", "medium",
     "विराम से चली वस्तु 5 सेकंड में 5 मीटर/सेकंड वेग प्राप्त करती है — त्वरण कितना?",
     "From rest, an object gains 5 m/s of velocity in 5 s — acceleration?",
     ["1 मीटर/सेकंड²", "5 मीटर/सेकंड²", "25 मीटर/सेकंड²", "0.2 मीटर/सेकंड²"],
     ["1 m/s²", "5 m/s²", "25 m/s²", "0.2 m/s²"],
     0,
     "(5 − 0)/5 = 1 मीटर/सेकंड²।",
     "(5 − 0)/5 = 1 m/s²."),

    ("acceleration", "medium",
     "किसी वस्तु का त्वरण 2 मीटर/सेकंड² है — इस कथन का अर्थ है —",
     "An object's acceleration is 2 m/s² — this statement means —",
     ["प्रत्येक सेकंड वेग 2 मीटर/सेकंड बढ़ता है", "प्रत्येक सेकंड दूरी 2 मीटर बढ़ती है", "वेग 2 मीटर/सेकंड स्थिर है", "समय 2 सेकंड स्थिर है"],
     ["Every second the velocity grows by 2 m/s", "Every second the distance grows by 2 m", "Velocity is fixed at 2 m/s", "Time is fixed at 2 s"],
     0,
     "त्वरण वेग में जोड़ की दर है — प्रति सेकंड 2 मीटर/सेकंड।",
     "Acceleration is the rate of addition to velocity — 2 m/s each second."),

    ("acceleration", "medium",
     "कथन A: वेग शून्य होते हुए भी त्वरण हो सकता है। कथन B: त्वरण शून्य होते हुए भी वेग हो सकता है। सही विकल्प —",
     "Statement A: acceleration can exist even when velocity is zero. Statement B: velocity can exist even when acceleration is zero. The correct option —",
     ["दोनों सही", "केवल A सही", "केवल B सही", "दोनों गलत"],
     ["Both are correct", "Only A is correct", "Only B is correct", "Both wrong"],
     0,
     "क्षण विशेष पर वेग शून्य पर त्वरण बना रह सकता है (जैसे विराम से चलने के क्षण); नियत वेग पर त्वरण शून्य।",
     "At an instant velocity can be zero while acceleration persists (as at the moment of starting from rest); at constant velocity acceleration is zero."),

    ("acceleration", "medium",
     "एक गेंद ऊपर फेंकी जाती है (सीधी रेखा में)। चढ़ते समय उसका त्वरण —",
     "A ball is thrown straight up. While rising, its acceleration is —",
     ["गति के विपरीत (मंदन रूप में कार्य करता है)", "गति के अनुकूल", "शून्य", "पहले शून्य फिर अनुकूल"],
     ["Opposite to the motion (acting as retardation)", "Along the motion", "Zero", "First zero then along"],
     0,
     "चढ़ाई में वेग घटता है — परिवर्तन गति के विपरीत दिशा में।",
     "While rising the velocity falls — the change points against the motion."),

    ("acceleration", "medium",
     "कार का वेग 3 सेकंड में 36 किमी/घंटा से 54 किमी/घंटा होता है — त्वरण मीटर/सेकंड² में?",
     "A car's velocity goes from 36 km/h to 54 km/h in 3 s — acceleration in m/s²?",
     ["≈1.67 मीटर/सेकंड²", "6 मीटर/सेकंड²", "18 मीटर/सेकंड²", "0.6 मीटर/सेकंड²"],
     ["≈1.67 m/s²", "6 m/s²", "18 m/s²", "0.6 m/s²"],
     0,
     "36→10, 54→15 मीटर/सेकंड; (15−10)/3 = 5/3 ≈ 1.67 मीटर/सेकंड²।",
     "36→10 and 54→15 m/s; (15−10)/3 = 5/3 ≈ 1.67 m/s²."),

    ("acceleration", "medium",
     "वेग-समय ग्राफ की ढाल शून्य (क्षैतिज रेखा) हो तो वस्तु की अवस्था क्या है?",
     "If the slope of a velocity-time graph is zero (horizontal line), what is the object's state?",
     ["नियत वेग (त्वरण रहित)", "विरामावस्था", "नियत त्वरण", "अनियमित गति"],
     ["Constant velocity (no acceleration)", "At rest", "Constant acceleration", "Non-uniform motion"],
     0,
     "समतल वेग-रेखा = वेग बदल नहीं रहा = त्वरण शून्य।",
     "A flat velocity line = velocity not changing = zero acceleration."),

    ("acceleration", "medium",
     "ऋणात्मक त्वरण का अर्थ हमेशा 'वेग घटना' ही होता है या केवल 'चिह्न-संबंधी' बात है?",
     "Is negative acceleration always 'velocity decreasing', or only a matter of sign convention?",
     ["चुनी गई धनात्मक दिशा के अनुसार — वेग उस दिशा में घट रहा है या विपरीत दिशा में बढ़ रहा है", "हमेशा केवल वेग-घटना", "हमेशा केवल विपरीत दिशा में गति", "यह केवल गणितीय शोभा है"],
     ["It depends on the chosen positive direction — velocity falling along it, or growing opposite to it", "Always merely velocity falling", "Always motion in the reverse direction", "It is mere mathematical decoration"],
     0,
     "चिह्न दिशा-संधि की भाषा है — धनात्मक दिशा तय करने के बाद ही ऋण का अर्थ खुलता है।",
     "The sign speaks the language of direction-agreement — the negative's meaning opens only after fixing the positive sense."),

    ("acceleration", "medium",
     "त्वरण 4 मीटर/सेकंड² से चलती (विराम से आरंभ) वस्तु 3 सेकंड में कितना वेग पकड़ेगी?",
     "Starting from rest with acceleration 4 m/s², what velocity does the object gain in 3 s?",
     ["12 मीटर/सेकंड", "7 मीटर/सेकंड", "4 मीटर/सेकंड", "1.33 मीटर/सेकंड"],
     ["12 m/s", "7 m/s", "4 m/s", "1.33 m/s"],
     0,
     "v = u + at की भावना से: 0 + 4×3 = 12 मीटर/सेकंड (प्रति सेकंड 4 का जोड़)।",
     "In the spirit of v = u + at: 0 + 4×3 = 12 m/s (an addition of 4 each second)."),

    ("acceleration", "medium",
     "वेग 0 से 20 मीटर/सेकंड 10 सेकंड में — प्रति सेकंड वेग-वृद्धि कितनी?",
     "Velocity 0 → 20 m/s in 10 s — what is the velocity gain per second?",
     ["2 मीटर/सेकंड प्रति सेकंड", "20 मीटर/सेकंड प्रति सेकंड", "200 मीटर/सेकंड प्रति सेकंड", "0.5 मीटर/सेकंड प्रति सेकंड"],
     ["2 m/s per second", "20 m/s per second", "200 m/s per second", "0.5 m/s per second"],
     0,
     "20/10 = 2 मीटर/सेकंड प्रति सेकंड — यही त्वरण 2 m/s² है।",
     "20/10 = 2 m/s per second — this very thing is acceleration 2 m/s²."),

    ("acceleration", "medium",
     "एक ट्रेन 4 सेकंड तक 2 मीटर/सेकंड² के त्वरण से चली (विराम से) — 4 सेकंड के अंत में वेग?",
     "A train accelerates from rest at 2 m/s² for 4 s — velocity at the end of 4 s?",
     ["8 मीटर/सेकंड", "6 मीटर/सेकंड", "16 मीटर/सेकंड", "2 मीटर/सेकंड"],
     ["8 m/s", "6 m/s", "16 m/s", "2 m/s"],
     0,
     "प्रति सेकंड 2 का जोड़, 4 सेकंड = 8 मीटर/सेकंड।",
     "An addition of 2 each second, 4 seconds = 8 m/s."),

    ("acceleration", "medium",
     "कथन जाँच: 'त्वरण केवल वेग के मान में वृद्धि का नाम है।' इस कथन की त्रुटि क्या है?",
     "Evaluate: 'acceleration is only the name for an increase in the magnitude of velocity.' What is wrong here?",
     ["त्वरण वेग में किसी भी भांति परिवर्तन (घटाव या दिशा-परिवर्तन सहित) की दर है", "कथन पूरी तरह सही है", "त्वरण केवल दिशा का नाम है", "त्वरण केवल समय का नाम है"],
     ["Acceleration is the rate of any change of velocity (decrease or direction-change included)", "The statement is fully correct", "Acceleration is only about direction", "Acceleration is only about time"],
     0,
     "वेग घटे या दिशा बदले — दोनों में त्वरण जन्मता है।",
     "Velocity falling or direction turning — both give birth to acceleration."),

    ("acceleration", "medium",
     "वृत्ताकार पथ में नियत चाल से दौड़ते धावक का त्वरण —",
     "For a runner at constant speed on a circular track, the acceleration —",
     ["शून्य नहीं है, क्योंकि दिशा बदलती रहती है", "शून्य है, क्योंकि चाल नियत है", "अनंत है", "मापी नहीं जा सकती"],
     ["Is not zero, because the direction keeps changing", "Is zero, because the speed is constant", "Is infinite", "Cannot be measured"],
     0,
     "वेग = चाल + दिशा; दिशा घूमती है तो वेग बदलता है — त्वरण बना रहता है।",
     "Velocity = speed + direction; with direction turning, velocity changes — acceleration persists."),

    ("acceleration", "hard",
     "वेग 60 किमी/घंटा से विराम तक 5 सेकंड में — मंदन मीटर/सेकंड² में कितना?",
     "From 60 km/h to rest in 5 s — retardation in m/s²?",
     ["≈3.33 मीटर/सेकंड²", "12 मीटर/सेकंड²", "60 मीटर/सेकंड²", "0.3 मीटर/सेकंड²"],
     ["≈3.33 m/s²", "12 m/s²", "60 m/s²", "0.3 m/s²"],
     0,
     "60 किमी/घंटा = 16.67 मीटर/सेकंड; (0−16.67)/5 ≈ −3.33 → मंदन ≈ 3.33 मीटर/सेकंड²।",
     "60 km/h = 16.67 m/s; (0−16.67)/5 ≈ −3.33 → retardation ≈ 3.33 m/s²."),

    ("acceleration", "hard",
     "विराम से आरंभ कर वस्तु पहले सेकंड में 2 मीटर/सेकंड, दूसरे सेकंड में 4 मीटर/सेकंड, तीसरे सेकंड में 6 मीटर/सेकंड वेग अंत तक पकड़ती है — त्वरण कितना और कैसा?",
     "Starting from rest, an object ends the 1st second at 2 m/s, the 2nd at 4 m/s, the 3rd at 6 m/s — what is the acceleration and of what kind?",
     ["2 मीटर/सेकंड², एकसमान", "बढ़ता हुआ त्वरण", "घटता हुआ त्वरण", "शून्य"],
     ["2 m/s², uniform", "Increasing acceleration", "Decreasing acceleration", "Zero"],
     0,
     "हर सेकंड वेग में समान +2 — एकसमान त्वरण 2 मीटर/सेकंड²।",
     "An equal +2 to velocity every second — uniform acceleration 2 m/s²."),

    ("acceleration", "hard",
     "कथन A: वेग-समय ग्राफ की ढाल जितनी तीखी, त्वरण उतना अधिक। कथन B: दूरी-समय ग्राफ की ढाल त्वरण देती है। सही विकल्प —",
     "Statement A: the steeper the v-t slope, the greater the acceleration. Statement B: the d-t slope gives acceleration. The correct option —",
     ["A सही, B गलत", "A गलत, B सही", "दोनों सही", "दोनों गलत"],
     ["A right, B wrong", "A wrong, B right", "Both right", "Both wrong"],
     0,
     "दूरी-समय की ढाल चाल देती है; वेग-समय की ढाल ही त्वरण।",
     "The d-t slope gives speed; only the v-t slope gives acceleration."),

    ("acceleration", "hard",
     "एक कार पहले 2 सेकंड में 0 से 6 मीटर/सेकंड, अगले 2 सेकंड में 6 से 12 मीटर/सेकंड — पूरी अवधि का त्वरण?",
     "A car goes 0→6 m/s in the first 2 s, then 6→12 m/s in the next 2 s — acceleration over the whole period?",
     ["3 मीटर/सेकंड² एकसमान", "छह मीटर/सेकंड²", "बदलता हुआ", "शून्य"],
     ["3 m/s² uniform", "6 m/s²", "Changing", "Zero"],
     0,
     "पहला चरण 6/2=3, दूसरा 6/2=3 — समान रफ्तार का वेग-जोड़ = एकसमान 3 मीटर/सेकंड²।",
     "First leg 6/2=3, second 6/2=3 — an even pace of velocity gain = uniform 3 m/s²."),

    ("acceleration", "hard",
     "यदि वेग-समय ग्राफ नीचे की ओर झुकी (ऋणात्मक ढाल) सरल रेखा हो, तो वस्तु की गति का वर्णन है —",
     "If a velocity-time graph is a straight line sloping downward (negative slope), the motion is described as —",
     ["एकसमान मंदन", "एकसमान त्वरण", "विराम", "नियत वेग"],
     ["Uniform retardation", "Uniform acceleration", "Rest", "Constant velocity"],
     0,
     "सीधी रेखा = ढाल नियत; ऋण ढाल = वेग-घटाव — एकसमान मंदन।",
     "Straight line = constant slope; negative slope = velocity falling — uniform retardation."),

    ("acceleration", "hard",
     "सोचिए — बस स्टॉप से चली और 10 सेकंड में 20 मीटर/सेकंड पकड़ा; फिर 20 सेकंड उसी वेग पर चली। पूरी यात्रा के दो चरणों में त्वरण का योग्य वर्णन है —",
     "Think — a bus leaves a stop and reaches 20 m/s in 10 s, then holds that velocity for 20 s. Across the two phases, the acceleration is rightly described as —",
     ["पहले चरण में 2 मीटर/सेकंड², दूसरे में शून्य", "दोनों चरणों में 2 मीटर/सेकंड²", "पहले शून्य, फिर 2 मीटर/सेकंड²", "दोनों में शून्य"],
     ["2 m/s² in the first phase, zero in the second", "2 m/s² in both phases", "Zero first, then 2 m/s²", "Zero in both"],
     0,
     "चरण 1: 20/10 = 2 मीटर/सेकंड²; चरण 2: नियत वेग → त्वरण शून्य।",
     "Phase 1: 20/10 = 2 m/s²; phase 2: constant velocity → zero acceleration."),

    ("acceleration", "medium",
     "बस-यात्रा के तीन चरण: (i) स्टॉप से चलना, (ii) सीधी सड़क पर नियत वेग, (iii) अगले स्टॉप पर ब्रेक — किस चरण में वेग-परिवर्तन की दर ऋणात्मक है?",
     "Three phases of a bus ride: (i) pulling away from the stop, (ii) steady velocity on a straight road, (iii) braking at the next stop — in which phase is the rate of change of velocity negative?",
     ["केवल (iii)", "केवल (i)", "(i) और (iii) दोनों", "(ii)"],
     ["Only (iii)", "Only (i)", "Both (i) and (iii)", "(ii)"],
     0,
     "चलना = धनात्मक दर; नियत वेग = शून्य दर; ब्रेक = ऋणात्मक दर।",
     "Pulling away = positive rate; steady velocity = zero rate; braking = negative rate."),

    # ================= MOTION GRAPHS — 37 (E14/M17/H6) =================
    ("motion-graphs", "medium",
     "दूरी-समय ग्राफ में दो रेखाएँ किसी बिंदु पर मिलती हैं — उस बिंदु का अर्थ है —",
     "In a distance-time graph two lines meet at a point — that point means —",
     ["उस क्षण दोनों एक ही स्थान पर हैं (मिलन-बिंदु)", "दोनों की चाल समान हो गई", "दोनों रुक गए", "ग्राफ गलत है"],
     ["At that instant both are at the same place (meeting point)", "Their speeds became equal", "Both stopped", "The graph is wrong"],
     0,
     "रेखाओं का कटाव = उसी समय उसी दूरी का भेंट-बिंदु।",
     "The lines' crossing = a rendezvous of the same instant and same distance."),

    ("motion-graphs", "medium",
     "वेग-समय ग्राफ: 20 मीटर/सेकंड से सीधी रेखा 5 सेकंड में शून्य तक — इस मंदन-चरण में तय दूरी (क्षेत्रफल)?",
     "Velocity-time graph: a straight line from 20 m/s down to zero in 5 s — distance covered in this retardation phase (area)?",
     ["50 मीटर", "100 मीटर", "20 मीटर", "4 मीटर"],
     ["50 metres", "100 metres", "20 metres", "4 metres"],
     0,
     "त्रिभुज क्षेत्रफल = ½ × 5 × 20 = 50 मीटर।",
     "Triangle area = ½ × 5 × 20 = 50 m."),

    ("motion-graphs", "hard",
     "दूरी-समय ग्राफ की रेखा बिंदु (0 सेकंड, 0 मीटर) से (10 सेकंड, 50 मीटर) तक सरल है — चाल कितनी?",
     "A distance-time line runs straight from (0 s, 0 m) to (10 s, 50 m) — the speed is?",
     ["5 मीटर/सेकंड", "50 मीटर/सेकंड", "0.2 मीटर/सेकंड", "500 मीटर/सेकंड"],
     ["5 m/s", "50 m/s", "0.2 m/s", "500 m/s"],
     0,
     "ढाल = (50 − 0)/(10 − 0) = 5 मीटर/सेकंड।",
     "Slope = (50 − 0)/(10 − 0) = 5 m/s."),

    ("motion-graphs", "hard",
     "वेग-समय ग्राफ: 2 सेकंड में 0 से 10 मीटर/सेकंड, फिर 3 सेकंड तक 10 मीटर/सेकंड समतल — कुल दूरी?",
     "Velocity-time graph: 0→10 m/s in 2 s, then flat at 10 m/s for 3 s — total distance?",
     ["40 मीटर", "50 मीटर", "20 मीटर", "30 मीटर"],
     ["40 metres", "50 metres", "20 metres", "30 metres"],
     0,
     "त्रिभुज ½×2×10 = 10 + आयत 10×3 = 30 → 40 मीटर।",
     "Triangle ½×2×10 = 10 plus rectangle 10×3 = 30 → 40 m."),

    ("motion-graphs", "hard",
     "कथन A: दूरी-समय ग्राफ का वक्र बदलती चाल बताता है। कथन B: वेग-समय ग्राफ की समतल रेखा बदलती चाल बताती है। सही विकल्प —",
     "Statement A: a curve in the distance-time graph indicates changing speed. Statement B: a flat line in the velocity-time graph indicates changing speed. The correct option —",
     ["A सही, B गलत", "A गलत, B सही", "दोनों सही", "दोनों गलत"],
     ["A right, B wrong", "A wrong, B right", "Both right", "Both wrong"],
     0,
     "वक्र = बदलती ढाल = बदलती चाल; वेग-ग्राफ की समतल रेखा = नियत वेग।",
     "A curve = changing slope = changing speed; a flat velocity line = constant velocity."),

    ("motion-graphs", "easy",
     "दूरी-समय ग्राफ में समय अक्ष के समांतर (क्षैतिज) रेखा का क्या अर्थ है?",
     "In a distance-time graph, what does a line parallel to the time axis mean?",
     ["वस्तु विरामावस्था में है", "वस्तु तेज़ चल रही है", "वस्तु त्वरित हो रही है", "वस्तु वापस आ रही है"],
     ["The object is at rest", "The object is moving fast", "The object is accelerating", "The object is returning"],
     0,
     "समय बढ़ा पर दूरी नहीं — ठहराव की सीधी रेखा।",
     "Time grows but distance does not — the flat line of a halt."),

    ("motion-graphs", "easy",
     "दूरी-समय ग्राफ की ढाल (slope) क्या बताती है?",
     "What does the slope of a distance-time graph give?",
     ["चाल", "त्वरण", "समय", "विस्थापन की दिशा"],
     ["Speed", "Acceleration", "Time", "Direction of displacement"],
     0,
     "ढाल = दूरी-परिवर्तन/समय = चाल।",
     "Slope = distance-change/time = speed."),

    ("motion-graphs", "easy",
     "दूरी-समय ग्राफ में तीखी (steep) रेखा किसे दर्शाती है?",
     "In a distance-time graph, a steep line indicates what?",
     ["अधिक चाल", "कम चाल", "विराम", "ऋणात्मक चाल"],
     ["Higher speed", "Lower speed", "Rest", "Negative speed"],
     0,
     "जितनी खड़ी चढ़ाई, उतनी तेज़ रफ्तार।",
     "The steeper the climb, the faster the pace."),

    ("motion-graphs", "easy",
     "दूरी-समय ग्राफ का मूल बिंदु (origin) से शुरू होना क्या दर्शाता है?",
     "A distance-time graph starting from the origin indicates what?",
     ["यात्रा शुरुआती क्षण और स्थान से चली", "वस्तु विराम पर थी", "दूरी ऋणात्मक थी", "समय उलट चला"],
     ["The journey began at the initial moment and place", "The object was at rest", "Distance was negative", "Time ran backwards"],
     0,
     "मूल बिंदु = शून्य समय, शून्य दूरी — यात्रा का पहला कदम।",
     "Origin = zero time, zero distance — the journey's first step."),

    ("motion-graphs", "easy",
     "दूरी-समय ग्राफ में सरल रेखा (straight line) किस गति का चिह्न है?",
     "In a distance-time graph, a straight line is the sign of which motion?",
     ["एकसमान चाल", "अनियमित चाल", "नियत त्वरण", "विराम"],
     ["Uniform speed", "Non-uniform speed", "Constant acceleration", "Rest"],
     0,
     "सीधी रेखा = ढाल स्थिर = चाल स्थिर।",
     "Straight line = steady slope = steady speed."),

    ("motion-graphs", "easy",
     "दूरी-समय ग्राफ में वक्र (curved) रेखा क्या बताती है?",
     "What does a curved line in a distance-time graph tell?",
     ["चाल बदल रही है (अनियमित गति)", "वस्तु खड़ी है", "चाल शून्य है", "समय रुका है"],
     ["The speed is changing (non-uniform motion)", "The object is standing", "Speed is zero", "Time has stopped"],
     0,
     "मुड़ती ढाल = बदलती चाल।",
     "A bending slope = a changing speed."),

    ("motion-graphs", "easy",
     "वेग-समय ग्राफ में समय अक्ष के समांतर रेखा का अर्थ है —",
     "In a velocity-time graph, a line parallel to the time axis means —",
     ["नियत वेग (शून्य त्वरण)", "विराम", "नियत त्वरण", "मंदन"],
     ["Constant velocity (zero acceleration)", "Rest", "Constant acceleration", "Retardation"],
     0,
     "समतल वेग-रेखा: वेग स्थिर, त्वरण शून्य।",
     "A flat velocity line: velocity fixed, acceleration zero."),

    ("motion-graphs", "easy",
     "वेग-समय ग्राफ में झुकी हुई सरल रेखा क्या दर्शाती है?",
     "In a velocity-time graph, an inclined straight line indicates —",
     ["नियत त्वरण", "नियत चाल", "विराम", "अनंत वेग"],
     ["Constant acceleration", "Constant speed", "Rest", "Infinite velocity"],
     0,
     "सीधी झुकी रेखा = ढाल नियत = त्वरण नियत।",
     "A straight inclined line = constant slope = constant acceleration."),

    ("motion-graphs", "easy",
     "दूरी-समय ग्राफ में दो वस्तुओं की रेखाओं में जिसकी ढाल अधिक —",
     "Between two objects' lines in a distance-time graph, the one with the greater slope —",
     ["अधिक तेज़ है", "धीमी है", "विराम पर है", "पीछे है"],
     ["Is faster", "Is slower", "Is at rest", "Is behind"],
     0,
     "ढाल = चाल; बड़ी ढाल = तेज़ वस्तु।",
     "Slope = speed; bigger slope = faster object."),

    ("motion-graphs", "easy",
     "वेग-समय ग्राफ के नीचे का क्षेत्रफल (area) क्या देता है?",
     "What does the area under a velocity-time graph give?",
     ["तय दूरी", "त्वरण", "समय", "चाल"],
     ["Distance travelled", "Acceleration", "Time", "Speed"],
     0,
     "वेग × समय = दूरी — ग्राफ के नीचे का रकबा वही बताता है।",
     "Velocity × time = distance — the area beneath the graph tells the same."),

    ("motion-graphs", "easy",
     "स्थिर वस्तु का दूरी-समय ग्राफ कैसा होगा?",
     "What does the distance-time graph of a stationary object look like?",
     ["समय अक्ष के समांतर सरल रेखा", "तीखी चढ़ती रेखा", "वक्र", "नीचे उतरती रेखा"],
     ["A straight line parallel to the time axis", "A steep rising line", "A curve", "A falling line"],
     0,
     "दूरी जमी जगह पर — रेखा समतल।",
     "Distance stays put — the line stays flat."),

    ("motion-graphs", "easy",
     "ग्राफ पढ़ने में क्षैतिज अक्ष (x-axis) प्रायः क्या दर्शाता है?",
     "In these graphs, what does the horizontal (x) axis usually represent?",
     ["समय", "दूरी", "वेग", "त्वरण"],
     ["Time", "Distance", "Velocity", "Acceleration"],
     0,
     "समय अक्ष आगे बढ़ता है, दूरी/वेग ऊपर नापे जाते हैं।",
     "The time axis runs ahead; distance/velocity are measured up."),

    ("motion-graphs", "easy",
     "एकसमान चाल की दूरी-समय रेखा और त्वरित गति की दूरी-समय रेखा में अंतर क्या होता है?",
     "What is the difference between the distance-time line of uniform speed and of accelerated motion?",
     ["पहली सरल रेखा, दूसरी वक्र (ऊपर की ओर मुड़ी)", "दोनों सरल रेखाएँ", "दोनों वक्र", "पहली वक्र, दूसरी सरल"],
     ["The first is a straight line, the second a curve (bending upward)", "Both straight lines", "Both curves", "The first a curve, the second straight"],
     0,
     "स्थिर चाल सीधी रेखा; बढ़ती चाल ऊपर उठता वक्र बनाती है।",
     "Steady speed draws a straight line; growing speed draws an upward bend."),

    ("motion-graphs", "easy",
     "वेग-समय ग्राफ में ऋणात्मक ढाल किसका संकेत है?",
     "In a velocity-time graph, a negative slope signals what?",
     ["मंदन (वेग घट रहा है)", "त्वरण बढ़ रहा है", "विराम", "नियत वेग"],
     ["Retardation (velocity is falling)", "Acceleration rising", "Rest", "Constant velocity"],
     0,
     "नीचे ढलान = वेग की गिरावट।",
     "A downhill slant = velocity falling."),

    ("motion-graphs", "medium",
     "दूरी-समय ग्राफ की रेखा पहले तीखी, बाद में समतल हो जाती है — गति का वर्णन है —",
     "A distance-time line is first steep, then flattens — the motion is described as —",
     ["पहले तेज़, फिर धीमी/रुकी", "पहले धीमी, फिर तेज़", "पूरा विराम", "नियत चाल पूरे समय"],
     ["First fast, then slowing/stopping", "First slow, then fast", "At rest throughout", "Constant speed throughout"],
     0,
     "ढाल घटना = चाल घटना; समतल होना = ठहराव की ओर।",
     "Falling slope = falling speed; flattening = heading to a stop."),

    ("motion-graphs", "medium",
     "एक कार का दूरी-समय ग्राफ मूल बिंदु से 30° का कोण बनाती सरल रेखा है; दूसरी कार की रेखा 60° का — कौन तेज़?",
     "One car's distance-time line makes a 30° angle from the origin; another's makes 60° — which is faster?",
     ["60° वाली", "30° वाली", "दोनों समान", "कोण से पता नहीं चलता"],
     ["The 60° one", "The 30° one", "Both equal", "Angles tell nothing"],
     0,
     "बड़ा कोण = बड़ी ढाल = बड़ी चाल।",
     "Bigger angle = bigger slope = bigger speed."),

    ("motion-graphs", "medium",
     "दूरी-समय ग्राफ में समय-अक्ष के साथ रेखा की ऊँचाई समय के साथ घट रही है — यह असंभव क्यों है (शुद्ध दूरी के लिए)?",
     "In a distance-time graph the line's height falls with time — why is this impossible (for pure distance)?",
     ["क्योंकि तय दूरी कभी घटती नहीं — वह केवल बढ़ती या स्थिर रहती है", "क्योंकि समय नहीं बदलता", "क्योंकि दूरी शून्य है", "क्योंकि ग्राफ गलत रंग का है"],
     ["Because travelled distance never decreases — it only grows or stays", "Because time does not change", "Because distance is zero", "Because the graph has the wrong colour"],
     0,
     "दूरी का हिसाब केवल जुड़ता है — उतरती रेखा विस्थापन-ग्राफ की पहचान हो सकती है, दूरी की नहीं।",
     "Distance's ledger only accumulates — a falling line may belong to a displacement graph, never pure distance."),

    ("motion-graphs", "medium",
     "वेग-समय ग्राफ: पहले 5 सेकंड समतल रेखा 10 मीटर/सेकंड पर, फिर समय-अक्ष तक नीचे — पहले चरण में तय दूरी?",
     "Velocity-time graph: flat at 10 m/s for the first 5 s, then down to the time axis — distance covered in the first phase?",
     ["50 मीटर", "10 मीटर", "5 मीटर", "2 मीटर"],
     ["50 metres", "10 metres", "5 metres", "2 metres"],
     0,
     "क्षेत्रफल = 10 × 5 = 50 मीटर।",
     "Area = 10 × 5 = 50 m."),

    ("motion-graphs", "medium",
     "उसी ग्राफ में 'समतल 10 मीटर/सेकंड से नीचे उतरने' वाले भाग का भाव है —",
     "In that graph, the part 'descending from the flat 10 m/s' means —",
     ["मंदन — वेग घटकर शून्य की ओर", "त्वरण बढ़ना", "वस्तु पीछे हटना", "नियत वेग"],
     ["Retardation — velocity falling toward zero", "Acceleration rising", "The object reversing", "Constant velocity"],
     0,
     "नीचर उतरती वेग-रेखा गति के मंदन की घोषणा है।",
     "A descending velocity line announces the motion's slowing."),

    ("motion-graphs", "medium",
     "दो वस्तुओं के दूरी-समय ग्राफ परस्पर समांतर सरल रेखाएँ हैं — निष्कर्ष क्या है?",
     "Two objects' distance-time graphs are parallel straight lines — the conclusion?",
     ["दोनों की चाल समान है", "दोनों विराम पर हैं", "एक दूसरे से तेज़ है", "दोनों त्वरित हैं"],
     ["Both have the same speed", "Both are at rest", "One is faster", "Both are accelerating"],
     0,
     "समांतर रेखाएँ = समान ढाल = समान चाल।",
     "Parallel lines = equal slopes = equal speeds."),

    ("motion-graphs", "medium",
     "वेग-समय ग्राफ में रेखा समय-अक्ष के नीचे (ऋणात्मक क्षेत्र) है — इसका अर्थ है —",
     "In a velocity-time graph the line lies below the time axis (negative region) — this means —",
     ["गति चुनी गई धनात्मक दिशा के विपरीत है", "वस्तु विराम पर है", "चाल शून्य है", "ग्राफ गलत है"],
     ["The motion is opposite to the chosen positive direction", "The object is at rest", "Speed is zero", "The graph is wrong"],
     0,
     "ऋण वेग = विपरीत दिशा में गति — चाल (परिमाण) फिर भी धनात्मक।",
     "Negative velocity = motion in the reverse sense — speed (magnitude) still positive."),

    ("motion-graphs", "medium",
     "दूरी-समय ग्राफ की रेखा ऊपर की ओर वक्र (तेज़ होती चाल) बनाती है — ढाल का क्या हो रहा है?",
     "A distance-time line curves upward (speed rising) — what is happening to the slope?",
     ["समय के साथ बढ़ रही है", "समय के साथ घट रही है", "स्थिर है", "शून्य हो गई"],
     ["It grows with time", "It falls with time", "It stays fixed", "It has become zero"],
     0,
     "वक्र की ढाल बदलती है — चढ़ता वक्र चढ़ती ढाल बताता है।",
     "A curve's slope changes — a rising curve shows a rising slope."),

    ("motion-graphs", "medium",
     "एक विद्यार्थी का दूरी-समय ग्राफ मूल बिंदु से मुड़ती हुई नीचे (घटती) रेखा है — उसने क्या भूला?",
     "A student's distance-time graph is a line bending downward (decreasing) from the origin — what did he forget?",
     ["दूरी समय के साथ घटती नहीं — शायद वह विस्थापन-समय ग्राफ बना बैठा", "समय हमेशा ऋणात्मक होता है", "दूरी का मात्रक सेकंड होता है", "ग्राफ हमेशा वक्र होता है"],
     ["Distance never falls with time — he has probably drawn a displacement-time graph instead", "Time is always negative", "Distance's unit is the second", "Graphs must always curve"],
     0,
     "पथ की गिनती एक ही दिशा में चलती है — उतरती रेखा विस्थापन की दुनिया है।",
     "The path's count runs one way — a falling line belongs to displacement's world."),

    ("motion-graphs", "medium",
     "वेग-समय ग्राफ: 0 से 6 मीटर/सेकंड तक 3 सेकंड में सीधी रेखा — रेखा की ढाल (त्वरण) कितनी?",
     "Velocity-time graph: a straight line from 0 to 6 m/s in 3 s — the line's slope (acceleration)?",
     ["2 मीटर/सेकंड²", "18 मीटर/सेकंड²", "0.5 मीटर/सेकंड²", "6 मीटर/सेकंड²"],
     ["2 m/s²", "18 m/s²", "0.5 m/s²", "6 m/s²"],
     0,
     "ढाल = 6/3 = 2 मीटर/सेकंड²।",
     "Slope = 6/3 = 2 m/s²."),

    ("motion-graphs", "medium",
     "नियत वेग 15 मीटर/सेकंड 8 सेकंड तक — वेग-समय ग्राफ के नीचे का क्षेत्रफल (दूरी) कितना?",
     "Constant velocity 15 m/s for 8 s — the area (distance) under the velocity-time graph?",
     ["120 मीटर", "23 मीटर", "1.87 मीटर", "15 मीटर"],
     ["120 metres", "23 metres", "1.87 metres", "15 metres"],
     0,
     "15 × 8 = 120 मीटर।",
     "15 × 8 = 120 m."),

    ("motion-graphs", "medium",
     "दूरी-समय ग्राफ में रेखा का एक खंड क्षैतिज है और अगला खंड तीखा — क्रमशः अर्थ है —",
     "In a distance-time graph one segment is horizontal and the next is steep — the meanings respectively are —",
     ["पहले विराम, फिर तेज़ गति", "पहले तेज़, फिर विराम", "दोनों विराम", "दोनों तेज़"],
     ["First rest, then fast motion", "First fast, then rest", "Both rest", "Both fast"],
     0,
     "समतल खंड = ठहराव; तीखा खंड = रफ्तार।",
     "Flat segment = a halt; steep segment = pace."),

    ("motion-graphs", "medium",
     "वेग-समय ग्राफ की रेखा दो चरणों में है: पहले सीधी चढ़ती, फिर समतल — गति का वर्णन है —",
     "A velocity-time line has two phases: first a straight climb, then flat — the motion is described as —",
     ["पहले एकसमान त्वरण, फिर नियत वेग", "पहले नियत वेग, फिर त्वरण", "पूरी तरह अनियमित", "पूरी तरह विराम"],
     ["First uniform acceleration, then constant velocity", "First constant velocity, then acceleration", "Wholly non-uniform", "Wholly at rest"],
     0,
     "चढ़ाई वेग बढ़ाती है, समतल उसे थामे रखती है।",
     "The climb builds velocity; the flat holds it."),

    ("motion-graphs", "medium",
     "एक ऑटो का वेग-समय ग्राफ समय-अक्ष से शुरू होकर ऊपर सीधी चढ़ती रेखा है — इसकी गति है —",
     "An auto's velocity-time graph starts from the time axis as a straight rising line — its motion is —",
     ["विराम से आरंभ होती एकसमान त्वरित गति", "नियत वेग की गति", "मंदन गति", "विराम"],
     ["Uniformly accelerated motion starting from rest", "Constant-velocity motion", "Retarding motion", "Rest"],
     0,
     "मूल से चढ़ती सीधी रेखा = शून्य से शुरू, नियत ढाल की वृद्धि।",
     "A straight rise from the origin = starting at zero with a constant slope of growth."),

    ("motion-graphs", "medium",
     "कथन A: दूरी-समय ग्राफ से चाल निकलती है। कथन B: वेग-समय ग्राफ की ढाल से चाल निकलती है। सही विकल्प —",
     "Statement A: speed comes from the distance-time graph. Statement B: speed comes from the slope of the velocity-time graph. The correct option —",
     ["A सही, B गलत", "A गलत, B सही", "दोनों सही", "दोनों गलत"],
     ["A right, B wrong", "A wrong, B right", "Both right", "Both wrong"],
     0,
     "दूरी-ग्राफ की ढाल चाल; वेग-ग्राफ की ढाल त्वरण।",
     "The d-t slope is speed; the v-t slope is acceleration."),

    ("motion-graphs", "hard",
     "एक वस्तु का वेग-समय ग्राफ समकोण त्रिभुज है: आधार 10 सेकंड (समय-अक्ष), ऊँचाई 20 मीटर/सेकंड — तय दूरी?",
     "A velocity-time graph forms a right triangle: base 10 s on the time axis, height 20 m/s — distance travelled?",
     ["100 मीटर", "200 मीटर", "20 मीटर", "400 मीटर"],
     ["100 metres", "200 metres", "20 metres", "400 metres"],
     0,
     "क्षेत्रफल = ½ × आधार × ऊँचाई = ½ × 10 × 20 = 100 मीटर।",
     "Area = ½ × base × height = ½ × 10 × 20 = 100 m."),

    ("motion-graphs", "hard",
     "दूरी-समय ग्राफ की रेखा पहले उठती वक्र से चढ़ती है और अंत में सीधी खड़ी होती जाती है — चाल का परिवर्तन है —",
     "A distance-time line climbs with an upward curve and tends to become nearly vertical at the end — the speed is —",
     ["लगातार बढ़ती हुई (त्वरित गति)", "लगातार घटती हुई", "स्थिर", "शून्य होती"],
     ["Rising continuously (accelerated motion)", "Falling continuously", "Constant", "Becoming zero"],
     0,
     "खड़ी होती ढाल = बढ़ती चाल; वक्र की बनावट गति की कहानी कहती है।",
     "A slope turning vertical = rising speed; the curve's shape narrates the motion."),

    ("motion-graphs", "hard",
     "वेग-समय ग्राफ: पहले 4 सेकंड में 0 से 8 मीटर/सेकंड (सीधी रेखा), फिर 6 सेकंड तक 8 मीटर/सेकंड समतल — पूरी 10 सेकंड यात्रा की औसत चाल कितनी?",
     "Velocity-time graph: 0→8 m/s over the first 4 s (straight), then flat at 8 m/s for 6 s — the average speed over the whole 10-second journey?",
     ["6.4 मीटर/सेकंड", "8 मीटर/सेकंड", "4 मीटर/सेकंड", "10 मीटर/सेकंड"],
     ["6.4 m/s", "8 m/s", "4 m/s", "10 m/s"],
     0,
     "कुल दूरी = त्रिभुज ½×4×8 = 16 + आयत 8×6 = 48 → 64 मीटर; औसत चाल = 64 ÷ 10 = 6.4 मीटर/सेकंड।",
     "Total distance = triangle ½×4×8 = 16 + rectangle 8×6 = 48 → 64 m; average speed = 64 ÷ 10 = 6.4 m/s."),
]
