# -*- coding: utf-8 -*-
"""P03 (Force & Laws of Motion) — Part 2: momentum-second-law (37) + action-reaction-friction (37) = 74 tuples.
All items authored with correct_idx=0; rotation happens in gen_p03_questions.py.

T3 momentum-second-law        37 = E15/M16/H6
T4 action-reaction-friction   37 = E14/M17/H6
"""

PART2 = [
    # ================= SECOND LAW & MOMENTUM (37) =================
    # ---- easy (15) ----
    ("momentum-second-law", "easy",
     "न्यूटन के द्वितीय नियम का गणितीय रूप क्या है?",
     "What is the mathematical form of Newton's second law?",
     ["F = ma", "F = mv", "F = m/v", "F = m + a"],
     ["F = ma", "F = mv", "F = m/v", "F = m + a"],
     0,
     "द्वितीय नियम: बल = द्रव्यमान × त्वरण।",
     "Second law: force = mass × acceleration."),

    ("momentum-second-law", "easy",
     "संवेग (momentum) किन राशियों का गुणनफल है?",
     "Momentum is the product of which quantities?",
     ["द्रव्यमान × वेग", "द्रव्यमान × त्वरण", "बल × समय", "द्रव्यमान × आयतन"],
     ["Mass × velocity", "Mass × acceleration", "Force × time", "Mass × volume"],
     0,
     "संवेग p = mv — द्रव्यमान और वेग का गुणनफल।",
     "Momentum p = mv — the product of mass and velocity."),

    ("momentum-second-law", "easy",
     "संवेग का SI मात्रक क्या है?",
     "What is the SI unit of momentum?",
     ["किलोग्राम·मीटर/सेकंड (kg·m/s)", "न्यूटन (N)", "जूल (J)", "किलोग्राम (kg)"],
     ["Kilogram-metre/second (kg·m/s)", "Newton (N)", "Joule (J)", "Kilogram (kg)"],
     0,
     "p = mv से मात्रक = kg × m/s = kg·m/s।",
     "From p = mv the unit is kg × m/s = kg·m/s."),

    ("momentum-second-law", "easy",
     "न्यूटन के अनुसार बल किसकी परिवर्तन-दर है?",
     "According to Newton, force is the rate of change of what?",
     ["संवेग", "द्रव्यमान", "आयतन", "लंबाई"],
     ["Momentum", "Mass", "Volume", "Length"],
     0,
     "द्वितीय नियम: बल = संवेग परिवर्तन की दर।",
     "Second law: force = the rate of change of momentum."),

    ("momentum-second-law", "easy",
     "वस्तु का त्वरण किस दिशा में होता है?",
     "In which direction does an object's acceleration point?",
     ["लगाए गए बल की दिशा में", "गति के विपरीत सदा", "किसी भी दिशा में", "वेग के लंबवत सदा"],
     ["In the direction of the applied force", "Always opposite to the motion", "In any direction", "Always perpendicular to the velocity"],
     0,
     "a = F/m — त्वरण सदा बल की दिशा में।",
     "a = F/m — the acceleration always follows the force."),

    ("momentum-second-law", "easy",
     "1 न्यूटन बल किसे कहते हैं?",
     "What is a force of one newton?",
     ["वह बल जो 1 kg द्रव्यमान में 1 m/s² त्वरण उत्पन्न करे", "वह बल जो 1 kg उठा ले", "वह बल जो 1 m चलाए", "वह बल जो 1 सेकंड तक लगे"],
     ["The force that produces 1 m/s² acceleration in a 1 kg mass", "The force that lifts 1 kg", "The force that moves 1 metre", "The force that acts for 1 second"],
     0,
     "1 N = 1 kg × 1 m/s²।",
     "1 N = 1 kg × 1 m/s²."),

    ("momentum-second-law", "easy",
     "संवेग किस प्रकार की राशि है?",
     "What kind of quantity is momentum?",
     ["सदिश — दिशा वेग की दिशा में", "अदिश — केवल परिमाण", "न सदिश न अदिश", "सदा शून्य"],
     ["A vector — its direction is that of the velocity", "A scalar — magnitude only", "Neither vector nor scalar", "Always zero"],
     0,
     "mv में वेग सदिश है, इसलिए संवेग सदिश है।",
     "Since v is a vector in mv, momentum is a vector."),

    ("momentum-second-law", "easy",
     "विरामावस्था वस्तु का संवेग कितना होता है?",
     "What is the momentum of an object at rest?",
     ["शून्य (v = 0 के कारण)", "अनंत", "द्रव्यमान के बराबर", "ऋणात्मक"],
     ["Zero (because v = 0)", "Infinite", "Equal to its mass", "Negative"],
     0,
     "p = mv = m × 0 = 0।",
     "p = mv = m × 0 = 0."),

    ("momentum-second-law", "easy",
     "द्रव्यमान समान रखकर बल दोगुना कर दें तो त्वरण —",
     "Keeping the mass fixed, if the force is doubled, the acceleration —",
     ["दोगुना हो जाता है", "आधा रह जाता है", "समान रहता है", "शून्य हो जाता है"],
     ["Doubles", "Halves", "Stays the same", "Becomes zero"],
     0,
     "a ∝ F (द्रव्यमान समान) — बल दोगुना, त्वरण दोगुना।",
     "a ∝ F (fixed mass) — double the force, double the acceleration."),

    ("momentum-second-law", "easy",
     "बल समान रहे और द्रव्यमान दोगुना हो जाए तो त्वरण —",
     "With the same force, if the mass doubles, the acceleration —",
     ["आधा रह जाता है", "दोगुना हो जाता है", "चार गुना", "अपरिवर्तित"],
     ["Halves", "Doubles", "Quadruples", "Is unchanged"],
     0,
     "a ∝ 1/m — द्रव्यमान दोगुना, त्वरण आधा।",
     "a ∝ 1/m — double the mass, half the acceleration."),

    ("momentum-second-law", "easy",
     "न्यूटन का द्वितीय नियम किस नाम से भी जाना जाता है?",
     "By what other name is Newton's second law known?",
     ["संवेग का नियम", "जड़त्व का नियम", "क्रिया-प्रतिक्रिया का नियम", "ऊर्जा का नियम"],
     ["The law of momentum", "The law of inertia", "The law of action-reaction", "The law of energy"],
     0,
     "F = Δp/Δt — इसलिए द्वितीय नियम संवेग का नियम है।",
     "F = Δp/Δt — hence the second law is the law of momentum."),

    ("momentum-second-law", "easy",
     "न्यूटन (N) किस भौतिक राशि का मात्रक है?",
     "Newton (N) is the unit of which physical quantity?",
     ["बल", "द्रव्यमान", "संवेग", "चाल"],
     ["Force", "Mass", "Momentum", "Speed"],
     0,
     "बल का SI मात्रक न्यूटन है।",
     "The SI unit of force is the newton."),

    ("momentum-second-law", "easy",
     "द्रव्यमान समान रहे और वेग दोगुना हो जाए तो संवेग —",
     "With the same mass, if the velocity doubles, the momentum —",
     ["दोगुना हो जाता है", "आधा रह जाता है", "समान रहता है", "चार गुना हो जाता है"],
     ["Doubles", "Halves", "Stays the same", "Quadruples"],
     0,
     "p = mv — v दोगुना तो p दोगुना।",
     "p = mv — double v and p doubles."),

    ("momentum-second-law", "easy",
     "a = F/m के अनुसार त्वरण किसके समानुपाती है?",
     "According to a = F/m, the acceleration is proportional to —",
     ["लगाए गए बल के", "द्रव्यमान के", "समय के", "आयतन के"],
     ["The applied force", "The mass", "The time", "The volume"],
     0,
     "m स्थिर हो तो a ∝ F।",
     "With m fixed, a ∝ F."),

    ("momentum-second-law", "easy",
     "किसी वस्तु का द्रव्यमान 4 kg और वेग 0 m/s है — संवेग —",
     "An object has mass 4 kg and velocity 0 m/s — its momentum is —",
     ["0 kg·m/s", "4 kg·m/s", "40 kg·m/s", "अनंत"],
     ["0 kg·m/s", "4 kg·m/s", "40 kg·m/s", "Infinite"],
     0,
     "p = 4 × 0 = 0 kg·m/s।",
     "p = 4 × 0 = 0 kg·m/s."),

    # ---- medium (16) ----
    ("momentum-second-law", "medium",
     "5 kg द्रव्यमान की वस्तु पर 2 m/s² का त्वरण उत्पन्न हो रहा है — लगा बल —",
     "An object of mass 5 kg accelerates at 2 m/s² — the applied force is —",
     ["10 N", "2.5 N", "7 N", "3 N"],
     ["10 N", "2.5 N", "7 N", "3 N"],
     0,
     "F = ma = 5 × 2 = 10 N।",
     "F = ma = 5 × 2 = 10 N."),

    ("momentum-second-law", "medium",
     "10 kg की वस्तु पर 3 m/s² त्वरण के लिए आवश्यक बल —",
     "The force needed to accelerate a 10 kg object at 3 m/s² is —",
     ["30 N", "3.3 N", "13 N", "7 N"],
     ["30 N", "3.3 N", "13 N", "7 N"],
     0,
     "F = 10 × 3 = 30 N।",
     "F = 10 × 3 = 30 N."),

    ("momentum-second-law", "medium",
     "4 kg द्रव्यमान पर 20 N का बल लगे तो त्वरण —",
     "A 20 N force acts on a 4 kg mass — the acceleration is —",
     ["5 m/s²", "80 m/s²", "16 m/s²", "24 m/s²"],
     ["5 m/s²", "80 m/s²", "16 m/s²", "24 m/s²"],
     0,
     "a = F/m = 20/4 = 5 m/s²।",
     "a = F/m = 20/4 = 5 m/s²."),

    ("momentum-second-law", "medium",
     "6 kg की वस्तु पर 12 N बल — उत्पन्न त्वरण —",
     "A 12 N force on a 6 kg object produces an acceleration of —",
     ["2 m/s²", "72 m/s²", "18 m/s²", "0.5 m/s²"],
     ["2 m/s²", "72 m/s²", "18 m/s²", "0.5 m/s²"],
     0,
     "a = 12/6 = 2 m/s²।",
     "a = 12/6 = 2 m/s²."),

    ("momentum-second-law", "medium",
     "2 kg की वस्तु 5 m/s के वेग से चल रही है — उसका संवेग —",
     "A 2 kg object moves at 5 m/s — its momentum is —",
     ["10 kg·m/s", "2.5 kg·m/s", "7 kg·m/s", "25 kg·m/s"],
     ["10 kg·m/s", "2.5 kg·m/s", "7 kg·m/s", "25 kg·m/s"],
     0,
     "p = mv = 2 × 5 = 10 kg·m/s।",
     "p = mv = 2 × 5 = 10 kg·m/s."),

    ("momentum-second-law", "medium",
     "0.5 kg की गेंद 20 m/s से उड़ रही है — संवेग —",
     "A 0.5 kg ball flies at 20 m/s — its momentum is —",
     ["10 kg·m/s", "20 kg·m/s", "40 kg·m/s", "0.025 kg·m/s"],
     ["10 kg·m/s", "20 kg·m/s", "40 kg·m/s", "0.025 kg·m/s"],
     0,
     "p = 0.5 × 20 = 10 kg·m/s।",
     "p = 0.5 × 20 = 10 kg·m/s."),

    ("momentum-second-law", "medium",
     "4 kg वस्तु का वेग 2 m/s से बढ़कर 6 m/s हुआ — संवेग परिवर्तन —",
     "A 4 kg object's velocity rises from 2 m/s to 6 m/s — the change in momentum is —",
     ["16 kg·m/s", "24 kg·m/s", "8 kg·m/s", "4 kg·m/s"],
     ["16 kg·m/s", "24 kg·m/s", "8 kg·m/s", "4 kg·m/s"],
     0,
     "Δp = m(v−u) = 4 × (6−2) = 16 kg·m/s।",
     "Δp = m(v−u) = 4 × (6−2) = 16 kg·m/s."),

    ("momentum-second-law", "medium",
     "4 सेकंड में संवेग 20 kg·m/s बदला — लगने वाला औसत बल —",
     "The momentum changes by 20 kg·m/s in 4 s — the average force is —",
     ["5 N", "80 N", "20 N", "0.2 N"],
     ["5 N", "80 N", "20 N", "0.2 N"],
     0,
     "F = Δp/Δt = 20/4 = 5 N।",
     "F = Δp/Δt = 20/4 = 5 N."),

    ("momentum-second-law", "medium",
     "3 kg वस्तु 4 m/s से चल रही है — संवेग —",
     "A 3 kg object moves at 4 m/s — the momentum is —",
     ["12 kg·m/s", "7 kg·m/s", "0.75 kg·m/s", "34 kg·m/s"],
     ["12 kg·m/s", "7 kg·m/s", "0.75 kg·m/s", "34 kg·m/s"],
     0,
     "p = 3 × 4 = 12 kg·m/s।",
     "p = 3 × 4 = 12 kg·m/s."),

    ("momentum-second-law", "medium",
     "10 N के बल से 5 m/s² त्वरण उत्पन्न होता है — वस्तु का द्रव्यमान —",
     "A 10 N force produces 5 m/s² of acceleration — the object's mass is —",
     ["2 kg", "50 kg", "5 kg", "0.5 kg"],
     ["2 kg", "50 kg", "5 kg", "0.5 kg"],
     0,
     "m = F/a = 10/5 = 2 kg।",
     "m = F/a = 10/5 = 2 kg."),

    ("momentum-second-law", "medium",
     "0.2 kg की गेंद 15 m/s के वेग से जा रही है — संवेग —",
     "A 0.2 kg ball moves at 15 m/s — its momentum is —",
     ["3 kg·m/s", "75 kg·m/s", "15 kg·m/s", "1.5 kg·m/s"],
     ["3 kg·m/s", "75 kg·m/s", "15 kg·m/s", "1.5 kg·m/s"],
     0,
     "p = 0.2 × 15 = 3 kg·m/s।",
     "p = 0.2 × 15 = 3 kg·m/s."),

    ("momentum-second-law", "medium",
     "0.5 kg वस्तु का वेग 3 m/s से 8 m/s हुआ — संवेग में वृद्धि —",
     "A 0.5 kg object speeds up from 3 m/s to 8 m/s — the gain in momentum is —",
     ["2.5 kg·m/s", "4 kg·m/s", "5.5 kg·m/s", "1.5 kg·m/s"],
     ["2.5 kg·m/s", "4 kg·m/s", "5.5 kg·m/s", "1.5 kg·m/s"],
     0,
     "Δp = 0.5 × (8−3) = 0.5 × 5 = 2.5 kg·m/s।",
     "Δp = 0.5 × (8−3) = 0.5 × 5 = 2.5 kg·m/s."),

    ("momentum-second-law", "medium",
     "1000 kg की कार में 2 m/s² का त्वरण देने के लिए चाहिए बल —",
     "To give a 1000 kg car an acceleration of 2 m/s², the force required is —",
     ["2000 N", "500 N", "998 N", "1002 N"],
     ["2000 N", "500 N", "998 N", "1002 N"],
     0,
     "F = 1000 × 2 = 2000 N।",
     "F = 1000 × 2 = 2000 N."),

    ("momentum-second-law", "medium",
     "दो वस्तुओं का संवेग समान है — पहली हल्की है, दूसरी भारी — किसका वेग अधिक होगा?",
     "Two objects have equal momentum — the first is light, the second heavy — which has the greater velocity?",
     ["हल्की वस्तु का", "भारी वस्तु का", "दोनों का समान", "बताया नहीं जा सकता"],
     ["The light one", "The heavy one", "Both equal", "Cannot be determined"],
     0,
     "p समान रखने पर v = p/m — m कम तो v अधिक।",
     "With p fixed, v = p/m — smaller m means larger v."),

    ("momentum-second-law", "medium",
     "6 N का बल 2 सेकंड तक लगा रहा — संवेग परिवर्तन —",
     "A 6 N force acts for 2 seconds — the change in momentum is —",
     ["12 kg·m/s", "3 kg·m/s", "8 kg·m/s", "6 kg·m/s"],
     ["12 kg·m/s", "3 kg·m/s", "8 kg·m/s", "6 kg·m/s"],
     0,
     "Δp = F × t = 6 × 2 = 12 kg·m/s।",
     "Δp = F × t = 6 × 2 = 12 kg·m/s."),

    ("momentum-second-law", "medium",
     "2 kg वस्तु का वेग 6 m/s से घटकर 2 m/s हुआ — संवेग परिवर्तन का परिमाण —",
     "A 2 kg object slows from 6 m/s to 2 m/s — the magnitude of its momentum change is —",
     ["8 kg·m/s", "4 kg·m/s", "12 kg·m/s", "16 kg·m/s"],
     ["8 kg·m/s", "4 kg·m/s", "12 kg·m/s", "16 kg·m/s"],
     0,
     "|Δp| = 2 × (6−2) = 8 kg·m/s (दिशा गति के विपरीत)।",
     "|Δp| = 2 × (6−2) = 8 kg·m/s (opposite to the motion)."),

    # ---- hard (6) ----
    ("momentum-second-law", "hard",
     "5 kg वस्तु विराम से 5 सेकंड में 10 m/s वेग प्राप्त करती है — लगा औसत बल —",
     "A 5 kg object at rest reaches 10 m/s in 5 s — the average force applied is —",
     ["10 N", "50 N", "2 N", "25 N"],
     ["10 N", "50 N", "2 N", "25 N"],
     0,
     "a = (10−0)/5 = 2 m/s²; F = 5 × 2 = 10 N।",
     "a = (10−0)/5 = 2 m/s²; F = 5 × 2 = 10 N."),

    ("momentum-second-law", "hard",
     "0.2 kg की गेंद 5 m/s से दीवार से टकराकर उतनी ही चाल से वापस आती है — संवेग परिवर्तन का परिमाण —",
     "A 0.2 kg ball hits a wall at 5 m/s and rebounds at the same speed — the magnitude of the momentum change is —",
     ["2 kg·m/s", "1 kg·m/s", "0", "4 kg·m/s"],
     ["2 kg·m/s", "1 kg·m/s", "0", "4 kg·m/s"],
     0,
     "दिशा उलटी: |Δp| = 0.2 × (5+5) = 2 kg·m/s।",
     "Direction reverses: |Δp| = 0.2 × (5+5) = 2 kg·m/s."),

    ("momentum-second-law", "hard",
     "50 N का बल 0.1 सेकंड तक लगा — संवेग परिवर्तन —",
     "A 50 N force acts for 0.1 s — the change in momentum is —",
     ["5 kg·m/s", "500 kg·m/s", "50 kg·m/s", "0.5 kg·m/s"],
     ["5 kg·m/s", "500 kg·m/s", "50 kg·m/s", "0.5 kg·m/s"],
     0,
     "Δp = F × t = 50 × 0.1 = 5 kg·m/s।",
     "Δp = F × t = 50 × 0.1 = 5 kg·m/s."),

    ("momentum-second-law", "hard",
     "समान बल समान समय तक 2 kg और 4 kg की वस्तुओं पर लगे — त्वरणों का अनुपात —",
     "The same force acts for the same time on 2 kg and 4 kg objects — the ratio of their accelerations is —",
     ["2 : 1", "1 : 2", "4 : 1", "1 : 4"],
     ["2 : 1", "1 : 2", "4 : 1", "1 : 4"],
     0,
     "a ∝ 1/m → a₁/a₂ = 4/2 = 2, अतः 2 : 1।",
     "a ∝ 1/m → a₁/a₂ = 4/2 = 2, i.e. 2 : 1."),

    ("momentum-second-law", "hard",
     "कथन A: संवेग p = mv है। कथन B: बल संवेग परिवर्तन की दर है। सही विकल्प —",
     "Statement A: momentum is p = mv. Statement B: force is the rate of change of momentum. The correct option —",
     ["A और B दोनों सही", "केवल A सही", "केवल B सही", "दोनों गलत"],
     ["Both A and B are right", "Only A is right", "Only B is right", "Both are wrong"],
     0,
     "p = mv परिभाषा है और F = Δp/Δt द्वितीय नियम — दोनों सही।",
     "p = mv is the definition and F = Δp/Δt is the second law — both hold."),

    ("momentum-second-law", "hard",
     "विरामावस्था 2 kg वस्तु पर 10 N बल 3 सेकंड तक लगा रहा — अंतिम वेग —",
     "A 10 N force acts on a 2 kg object at rest for 3 s — the final velocity is —",
     ["15 m/s", "30 m/s", "5 m/s", "10 m/s"],
     ["15 m/s", "30 m/s", "5 m/s", "10 m/s"],
     0,
     "a = 10/2 = 5 m/s²; v = a × t = 5 × 3 = 15 m/s।",
     "a = 10/2 = 5 m/s²; v = a × t = 5 × 3 = 15 m/s."),

    # ================= THIRD LAW & FRICTION (37) =================
    # ---- easy (14) ----
    ("action-reaction-friction", "easy",
     "न्यूटन का तृतीय नियम क्या कहता है?",
     "What does Newton's third law state?",
     ["प्रत्येक क्रिया के बराबर और विपरीत प्रतिक्रिया होती है", "बल द्रव्यमान और त्वरण का गुणनफल है", "वस्तु अपनी अवस्था बनाए रखती है", "संवेग सदा संरक्षित रहता है"],
     ["Every action has an equal and opposite reaction", "Force is the product of mass and acceleration", "An object keeps its state", "Momentum is always conserved"],
     0,
     "क्रिया-प्रतिक्रिया बराबर परिमाण, विपरीत दिशा — भिन्न वस्तुओं पर।",
     "Action and reaction — equal magnitude, opposite direction — on different bodies."),

    ("action-reaction-friction", "easy",
     "रॉकेट की गति किस नियम पर आधारित है?",
     "On which law is rocket propulsion based?",
     ["न्यूटन का तृतीय नियम", "न्यूटन का प्रथम नियम", "न्यूटन का द्वितीय नियम", "गुरुत्वाकर्षण का नियम"],
     ["Newton's third law", "Newton's first law", "Newton's second law", "The law of gravitation"],
     0,
     "गैस पीछे (क्रिया), रॉकेट आगे (प्रतिक्रिया) — तृतीय नियम।",
     "Gas expelled back (action), rocket pushed forward (reaction) — the third law."),

    ("action-reaction-friction", "easy",
     "तैराक तैरते समय पानी को पीछे धकेलता है — पानी तैराक को किस ओर धकेलता है?",
     "A swimmer pushes water backward while swimming — which way does the water push the swimmer?",
     ["आगे की ओर", "पीछे की ओर", "नीचे की ओर", "किसी ओर नहीं"],
     ["Forward", "Backward", "Downward", "Not at all"],
     0,
     "पानी पर क्रिया पीछे, पानी की प्रतिक्रिया तैराक को आगे।",
     "The action on water is backward; the water's reaction drives the swimmer forward."),

    ("action-reaction-friction", "easy",
     "बंदूक चलाने पर उसे पीछे की ओर झटका लगता है — इसे क्या कहते हैं?",
     "Firing a gun jolts it backward — what is this called?",
     ["प्रतिक्षेप (recoil)", "जड़त्व", "घर्षण", "त्वरण"],
     ["Recoil", "Inertia", "Friction", "Acceleration"],
     0,
     "गोली आगे (क्रिया), बंदूक पीछे (प्रतिक्रिया) — प्रतिक्षेप।",
     "Bullet forward (action), gun backward (reaction) — recoil."),

    ("action-reaction-friction", "easy",
     "घर्षण किसे कहते हैं?",
     "What is friction?",
     ["गति का विरोध करने वाला बल", "गति बढ़ाने वाला बल", "द्रव्यमान का माप", "वेग की दिशा"],
     ["The force that opposes motion", "The force that increases motion", "A measure of mass", "The direction of velocity"],
     0,
     "संपर्क सतहों के बीच गति का विरोध करने वाला बल घर्षण है।",
     "Friction is the force between contact surfaces that opposes motion."),

    ("action-reaction-friction", "easy",
     "घर्षण बल की दिशा कैसी होती है?",
     "What is the direction of the force of friction?",
     ["गति की विपरीत", "गति की समान", "गति के लंबवत", "कोई दिशा नहीं"],
     ["Opposite to the motion", "Same as the motion", "Perpendicular to the motion", "No direction"],
     0,
     "घर्षण सदा गति के विरुद्ध दिशा में लगता है।",
     "Friction always acts against the direction of motion."),

    ("action-reaction-friction", "easy",
     "हम जमीन पर बिना फिसले चल क्यों पाते हैं?",
     "Why can we walk on the ground without slipping?",
     ["घर्षण के कारण", "जड़त्व के कारण", "संवेग के कारण", "त्वरण के कारण"],
     ["Because of friction", "Because of inertia", "Because of momentum", "Because of acceleration"],
     0,
     "पैर और जमीन के घर्षण से ही चलना संभव है।",
     "Friction between foot and ground makes walking possible."),

    ("action-reaction-friction", "easy",
     "मशीनों के हिस्सों का घिस जाना घर्षण का कौन-सा रूप है?",
     "Machine parts wearing out is which aspect of friction?",
     ["हानिकारक रूप", "उपयोगी रूप", "कोई रूप नहीं", "लाभदायक रूप"],
     ["Its harmful aspect", "Its useful aspect", "No aspect at all", "Its profitable aspect"],
     0,
     "घर्षण से घिसाव और ऊर्जा-हानि होती है — यह हानिकारक रूप है।",
     "Friction causes wear and energy loss — its harmful side."),

    ("action-reaction-friction", "easy",
     "मशीन के हिस्सों में तेल या ग्रीस लगाने का उद्देश्य —",
     "The purpose of applying oil or grease to machine parts is —",
     ["घर्षण घटाना (स्नेहन)", "घर्षण बढ़ाना", "रंग सुधारना", "भार बढ़ाना"],
     ["To reduce friction (lubrication)", "To increase friction", "To improve colour", "To add weight"],
     0,
     "स्नेहक बीच में परत बनाकर घर्षण घटाता है।",
     "A lubricant forms a layer that reduces friction."),

    ("action-reaction-friction", "easy",
     "मशीनों में रोलर या बॉल बेयरिंग का उपयोग किसलिए होता है?",
     "Why are rollers or ball bearings used in machines?",
     ["घर्षण घटाने के लिए", "घर्षण बढ़ाने के लिए", "सौंदर्य के लिए", "भार बढ़ाने के लिए"],
     ["To reduce friction", "To increase friction", "For beauty", "To add weight"],
     0,
     "रोलिंग घर्षण स्लाइडिंग से कम होता है — इसलिए रोलर/बेयरिंग।",
     "Rolling friction is less than sliding — hence rollers/bearings."),

    ("action-reaction-friction", "easy",
     "मछलियों और विमानों का धारावाहिक (streamlined) आकार किसलिए है?",
     "Why do fish and aircraft have streamlined shapes?",
     ["वायु/जल का घर्षण घटाने के लिए", "घर्षण बढ़ाने के लिए", "सुंदर दिखने के लिए", "वजन बढ़ाने के लिए"],
     ["To reduce friction with air/water", "To increase friction", "To look beautiful", "To add weight"],
     0,
     "धारावाहिक आकार द्रव/वायु का प्रतिरोध घटाता है।",
     "A streamlined shape cuts down fluid resistance."),

    ("action-reaction-friction", "easy",
     "क्रिया और प्रतिक्रिया बल किन पर लगते हैं?",
     "On what do the action and reaction forces act?",
     ["दो भिन्न वस्तुओं पर", "एक ही वस्तु पर", "किसी पर नहीं", "केवल एक वस्तु पर"],
     ["On two different objects", "On the same object", "On nothing", "On just one object"],
     0,
     "क्रिया एक वस्तु पर, प्रतिक्रिया दूसरी पर — इसीलिए वे कभी संतुलित नहीं करतीं।",
     "Action on one object, reaction on the other — that is why they never balance."),

    ("action-reaction-friction", "easy",
     "नाव आगे बढ़ाने के लिए व्यक्ति पानी पर किस दिशा में बल लगाता है?",
     "To move a boat forward, in which direction does a person push the water?",
     ["पीछे की ओर", "आगे की ओर", "नीचे की ओर", "ऊपर की ओर"],
     ["Backward", "Forward", "Downward", "Upward"],
     0,
     "पानी को पीछे धकेलने पर पानी नाव को आगे धकेलता है (तृतीय नियम)।",
     "Pushing water backward makes the water push the boat forward (third law)."),

    ("action-reaction-friction", "easy",
     "माचिस की तीली को डिब्बे से रगड़ने पर जल जाती है — कारण —",
     "Striking a matchstick against the box lights it — the reason is —",
     ["घर्षण से ऊष्मा उत्पन्न होती है", "जड़त्व से ऊष्मा बनती है", "त्वरण से आग लगती है", "संवेग जलता है"],
     ["Friction generates heat", "Inertia produces heat", "Acceleration ignites it", "Momentum burns it"],
     0,
     "रगड़ के घर्षण से ऊष्मा बनकर तीली जल जाती है।",
     "The rubbing friction produces heat that ignites the match."),

    # ---- medium (17) ----
    ("action-reaction-friction", "medium",
     "क्रिया-प्रतिक्रिया बल संतुलित बल क्यों नहीं कहलाते?",
     "Why are action-reaction forces not called balanced forces?",
     ["ये दो भिन्न वस्तुओं पर लगती हैं, एक ही वस्तु पर नहीं", "इनके परिमाण असमान होते हैं", "इनकी दिशाएँ समान होती हैं", "ये कभी नहीं लगतीं"],
     ["They act on two different objects, not on the same one", "Their magnitudes are unequal", "Their directions are the same", "They never act"],
     0,
     "संतुलन के लिए दोनों बल एक ही वस्तु पर होने चाहिए — क्रिया-प्रतिक्रिया भिन्न वस्तुओं पर हैं।",
     "Balancing needs both forces on one body — action and reaction sit on different bodies."),

    ("action-reaction-friction", "medium",
     "चलते समय पैर जमीन को पीछे धकेलता है — जमीन पैर को किस दिशा में धकेलती है?",
     "While walking the foot pushes the ground backward — which way does the ground push the foot?",
     ["आगे की ओर", "पीछे की ओर", "ऊपर ही", "किसी ओर नहीं"],
     ["Forward", "Backward", "Only upward", "Not at all"],
     0,
     "क्रिया पीछे, प्रतिक्रिया आगे — यही हमें चलाती है।",
     "Action backward, reaction forward — that is what propels us."),

    ("action-reaction-friction", "medium",
     "रॉकेट तीसरे नियम से कैसे चलता है?",
     "How does a rocket move using the third law?",
     ["उछाली गई गैस पीछे जाती है, गैस रॉकेट को आगे धकेलती है", "हवा रॉकेट को खींचती है", "रॉकेट हवा को आगे धकेलता है", "रॉकेट जड़त्व से चलता है"],
     ["The expelled gas goes backward and pushes the rocket forward", "The air pulls the rocket", "The rocket pushes air forward", "The rocket moves by inertia"],
     0,
     "गैस पीछे = क्रिया; गैस द्वारा रॉकेट पर आगे बल = प्रतिक्रिया।",
     "Gas backward = action; the gas's forward push on the rocket = reaction."),

    ("action-reaction-friction", "medium",
     "बर्फ पर चलना कठिन क्यों होता है?",
     "Why is walking on ice difficult?",
     ["घर्षण बहुत कम होने से", "घर्षण बहुत अधिक होने से", "जड़त्व शून्य होने से", "संवेग अधिक होने से"],
     ["Because friction is very low", "Because friction is very high", "Because inertia is zero", "Because momentum is high"],
     0,
     "चिकनी बर्फ पर घर्षण कम — पैर पीछे धकेल नहीं पाता, फिसलन होती है।",
     "Smooth ice offers little friction — the foot cannot push back and slips."),

    ("action-reaction-friction", "medium",
     "मशीन में तेल डालने से मशीन को क्या लाभ होता है?",
     "What does a machine gain by adding oil to it?",
     ["घर्षण और घिसाव घटता है", "घर्षण बढ़ता है", "वजन घटता है", "आकार बदलता है"],
     ["Friction and wear decrease", "Friction increases", "Weight decreases", "Shape changes"],
     0,
     "स्नेहन से घर्षण घटता है — घिसाव और ऊर्जा हानि कम।",
     "Lubrication cuts friction — less wear and energy loss."),

    ("action-reaction-friction", "medium",
     "साइकिल का ब्रेक घर्षण का कौन-सा रूप दिखाता है?",
     "A bicycle brake demonstrates which face of friction?",
     ["उपयोगी रूप — घर्षण ही गाड़ी रोकता है", "हानिकारक रूप — यह गाड़ी घिसाता है", "कोई रूप नहीं", "घर्षण चाल बढ़ाता है"],
     ["Its useful face — friction alone stops the cycle", "Its harmful face — it wears the cycle out", "No face at all", "Friction speeds it up"],
     0,
     "ब्रेक पैड और पहिये के घर्षण से ही रुकना संभव है — उपयोगी।",
     "Only the brake-pad/wheel friction stops it — useful."),

    ("action-reaction-friction", "medium",
     "जूतों के तल में उभार और गहरे निशान क्यों बनाए जाते हैं?",
     "Why do shoe soles carry grooves and deep treads?",
     ["घर्षण बढ़ाकर फिसलन रोकने के लिए", "जूते हल्के करने के लिए", "सौंदर्य बढ़ाने के लिए", "जूते चौड़े करने के लिए"],
     ["To increase friction and prevent slipping", "To make shoes lighter", "To add beauty", "To widen the shoes"],
     0,
     "खुरदरी सतह (उभार) घर्षण बढ़ाती है — पकड़ बेहतर।",
     "Rough surfaces (treads) raise friction — a better grip."),

    ("action-reaction-friction", "medium",
     "गाड़ी के टायरों पर जिग-जैग निशानों का कारण —",
     "The zig-zag patterns on vehicle tyres exist to —",
     ["सड़क के साथ घर्षण बढ़ाना", "घर्षण घटाना", "टायर का वजन बढ़ाना", "रंग जोड़ना"],
     ["Increase friction with the road", "Reduce friction", "Add tyre weight", "Add colour"],
     0,
     "ट्रेड पैटर्न सड़क पर पकड़ (घर्षण) बढ़ाता है — सुरक्षित ब्रेक/मोड़।",
     "The tread pattern grips the road — safer braking and turning."),

    ("action-reaction-friction", "medium",
     "'घर्षण सदा हानिकारक है' — यह कथन —",
     "'Friction is always harmful' — this statement is —",
     ["गलत — चलना, पकड़, ब्रेक सब घर्षण से संभव हैं", "बिल्कुल सही", "आधे समय सही", "न सही न गलत"],
     ["Wrong — walking, gripping and braking all need friction", "Absolutely right", "Right half the time", "Neither right nor wrong"],
     0,
     "घर्षण उपयोगी-हानिकारक दोनों है — यह परीक्षा का प्रसिद्ध जाल है।",
     "Friction is both useful and harmful — a classic exam trap."),

    ("action-reaction-friction", "medium",
     "सड़क पर गिरी तेल की परत को 'फिसलन भरी' क्यों कहा जाता है?",
     "Why is an oil spill on a road called 'slippery'?",
     ["तेल घर्षण कम कर देता है", "तेल घर्षण बढ़ाता है", "तेल जड़त्व बदलता है", "तेल द्रव्यमान बढ़ाता है"],
     ["The oil lowers friction", "The oil raises friction", "The oil alters inertia", "The oil adds mass"],
     0,
     "तेल की परत टायर-सड़क संपर्क में घर्षण घटा देती है — पकड़ खत्म।",
     "The oil film between tyre and road cuts friction — the grip is gone."),

    ("action-reaction-friction", "medium",
     "धीमी गति से गिरते पैराशूट वाले व्यक्ति पर वायु का प्रतिरोध किस दिशा में कार्य करता है?",
     "On a parachutist descending slowly, in which direction does air resistance act?",
     ["गति के विपरीत (ऊपर)", "गति की दिशा में (नीचे)", "क्षैतिज", "कोई दिशा नहीं"],
     ["Opposite to the motion (upward)", "Along the motion (downward)", "Horizontal", "No direction"],
     0,
     "वायु प्रतिरोध गति के विरुद्ध लगता है — धीमी गिरावट में नीचे के बल के लगभग बराबर।",
     "Air drag acts against the motion — in slow descent it nearly balances the downward force."),

    ("action-reaction-friction", "medium",
     "गाड़ी पर आगे की ओर 12 N का बल लगाया गया और घर्षण 5 N पीछे की ओर लगा — प्रभावी बल —",
     "A cart is pushed forward with 12 N while friction pulls 5 N backward — the effective force is —",
     ["7 N आगे", "17 N आगे", "7 N पीछे", "60 N"],
     ["7 N forward", "17 N forward", "7 N backward", "60 N"],
     0,
     "12 − 5 = 7 N आगे की ओर।",
     "12 − 5 = 7 N forward."),

    ("action-reaction-friction", "medium",
     "दीवार को धक्का देने पर हम कभी-कभी पीछे गिरते क्यों हैं?",
     "Why do we sometimes fall backward when pushing a wall?",
     ["दीवार हम पर बराबर-विपरीत बल लगाती है", "दीवार ऊपर उठ जाती है", "हमारा द्रव्यमान शून्य हो जाता है", "घर्षण बढ़ जाता है"],
     ["The wall exerts an equal-opposite force on us", "The wall rises up", "Our mass becomes zero", "Friction increases"],
     0,
     "हमारा धक्का (क्रिया) दीवार पर; दीवार का बल (प्रतिक्रिया) हम पर — पीछे धकेलता है।",
     "Our push (action) on the wall; the wall's force (reaction) on us pushes back."),

    ("action-reaction-friction", "medium",
     "किनारे पर खड़ा व्यक्ति नाव से किनारे की ओर कूदता है — नाव क्या करेगी?",
     "A person standing at the edge jumps from the boat towards the bank — what does the boat do?",
     ["पीछे की ओर खिसकेगी", "आगे बढ़ेगी", "डूब जाएगी", "कुछ नहीं होगा"],
     ["It moves backward", "It moves forward", "It sinks", "Nothing happens"],
     0,
     "कूद आगे = क्रिया; नाव पर विपरीत प्रतिक्रिया — नाव पीछे।",
     "The forward jump (action) gives the boat an opposite reaction — it drifts back."),

    ("action-reaction-friction", "medium",
     "टेनिस खिलाड़ी गेंद को मारता है — क्रिया-प्रतिक्रिया जोड़ी कौन-सी है?",
     "A tennis player strikes the ball — which is the action-reaction pair?",
     ["रैकेट गेंद पर बल (क्रिया) और गेंद रैकेट पर बल (प्रतिक्रिया)", "खिलाड़ी का वजन और जमीन", "गेंद का वेग और समय", "रैकेट का वजन और हवा"],
     ["The racket's force on the ball (action) and the ball's force on the racket (reaction)", "The player's weight and the ground", "The ball's velocity and time", "The racket's weight and the air"],
     0,
     "दो परस्पर बल दो वस्तुओं पर — रैकेट→गेंद और गेंद→रैकेट।",
     "Two mutual forces on two objects — racket→ball and ball→racket."),

    ("action-reaction-friction", "medium",
     "भारी बंदूक से गोली चलाने पर प्रतिक्षेप धक्का हल्की बंदूक की तुलना में कम क्यों लगता है?",
     "Why does a heavy gun kick less than a light one when fired?",
     ["उसी बल के विरुद्ध अधिक द्रव्यमान पर त्वरण (झटका) कम बनता है", "भारी बंदूक में बल नहीं लगता", "गोली भारी होती है", "हवा भारी बंदूक को रोकती है"],
     ["The same opposing force produces less acceleration (kick) on a larger mass", "No force acts on a heavy gun", "The bullet is heavier", "The air stops the heavy gun"],
     0,
     "प्रतिक्रिया बल समान, पर a = F/m — m अधिक तो झटका (त्वरण) कम।",
     "The reaction force is the same, but a = F/m — larger m, smaller kick."),

    ("action-reaction-friction", "medium",
     "गीले फर्श पर फिसलने का भौतिक कारण क्या है?",
     "What is the physical cause of slipping on a wet floor?",
     ["पानी की परत घर्षण घटा देती है", "पानी द्रव्यमान बढ़ाता है", "पानी जड़त्व घटाता है", "पानी संवेग बदलता है"],
     ["The water layer reduces friction", "Water increases mass", "Water reduces inertia", "Water changes momentum"],
     0,
     "पानी पैर-फर्श संपर्क में स्नेहक जैसा काम करता है — घर्षण गिरता है।",
     "Water acts like a lubricant in the foot-floor contact — friction drops."),

    # ---- hard (6) ----
    ("action-reaction-friction", "hard",
     "घोड़ा गाड़ी को आगे खींचता है, गाड़ी भी घोड़े को उतना ही पीछे — फिर गाड़ी चलती क्यों है?",
     "The horse pulls the cart forward and the cart pulls the horse equally backward — why does the cart still move?",
     ["ये बल भिन्न वस्तुओं पर लगते हैं; गाड़ी की गति जमीन-घोड़े बलों के असंतुलन से होती है", "गाड़ी का बल नहीं लगता", "घोड़े का बल बड़ा होता है", "यह असंभव है"],
     ["These forces act on different objects; the cart moves because of the imbalance of ground-horse forces", "The cart exerts no force", "The horse's force is larger", "This is impossible"],
     0,
     "क्रिया-प्रतिक्रिया जोड़ी कभी एक ही वस्तु को संतुलित नहीं करती — गाड़ी तंत्र की शेष बलों से त्वरित होती है।",
     "An action-reaction pair never balances one body — the cart accelerates due to the system's remaining forces."),

    ("action-reaction-friction", "hard",
     "क्रिया और प्रतिक्रिया बराबर हैं, फिर भी दोनों वस्तुओं का त्वरण भिन्न हो सकता है — क्यों?",
     "Action and reaction are equal, yet the two objects can accelerate differently — why?",
     ["त्वरण द्रव्यमान पर निर्भर करता है (a = F/m)", "दोनों बल असमान होते हैं", "दिशाएँ समान होती हैं", "त्वरण बल से स्वतंत्र है"],
     ["Acceleration depends on the mass (a = F/m)", "The two forces are unequal", "The directions are identical", "Acceleration is independent of force"],
     0,
     "समान बल पर हल्की वस्तु अधिक, भारी कम त्वरित होती है।",
     "Under an equal force the lighter object accelerates more, the heavier less."),

    ("action-reaction-friction", "hard",
     "यदि सड़क और टायर के बीच घर्षण पूरी तरह शून्य हो जाए, तो चलती कार को ब्रेक लगाने पर —",
     "If friction between road and tyre became exactly zero, applying the brakes of a moving car would —",
     ["कार नहीं रोक पाए (ब्रेक घर्षण पर निर्भर)", "कार तुरंत रुक जाए", "कार उल्टी दिशा में जाए", "कुछ अंतर नहीं पड़े"],
     ["Not stop the car (brakes depend on friction)", "Stop it instantly", "Send it in reverse", "Make no difference"],
     0,
     "ब्रेक पैड-पहिया घर्षण से पहिया रोकता है, पहिया-सड़क घर्षण से गाड़ी — शून्य घर्षण में असंभव।",
     "Pad-wheel friction stops the wheel; wheel-road friction stops the car — impossible with zero friction."),

    ("action-reaction-friction", "hard",
     "अंतरिक्ष में (बिना वायु के) रॉकेट आगे कैसे बढ़ता है?",
     "How does a rocket advance in space (with no air)?",
     ["पीछे उछाली गैस की प्रतिक्रिया से — वायु की जरूरत नहीं", "वायु को धकेलकर", "सूर्य के प्रकाश से खिंचकर", "जड़त्व से अपने आप"],
     ["By the reaction of the gas it expels backward — no air is needed", "By pushing against air", "By being pulled by sunlight", "By inertia alone"],
     0,
     "प्रतिक्रिया गैस-रॉकेट के बीच है, बाहरी वायु से नहीं — निर्वात में भी संभव।",
     "The reaction is between gas and rocket, not with outside air — it works in vacuum."),

    ("action-reaction-friction", "hard",
     "कथन A: घर्षण दो सतहों के संपर्क का बल है। कथन B: वायु का प्रतिरोध भी गति के विरोधी बल है। सही विकल्प —",
     "Statement A: friction is a force of contact between two surfaces. Statement B: air resistance too is a force opposing motion. The correct option —",
     ["A और B दोनों सही", "केवल A सही", "केवल B सही", "दोनों गलत"],
     ["Both A and B are right", "Only A is right", "Only B is right", "Both are wrong"],
     0,
     "घर्षण संपर्क बल है और वायु प्रतिरोध भी गति विरोधी ही कार्य करता है।",
     "Friction is a contact force and air drag likewise opposes motion."),

    ("action-reaction-friction", "hard",
     "घर्षण घटाने के लिए प्रयुक्त तीन उपायों वाला सही समूह —",
     "Pick the correct set of three methods of reducing friction —",
     ["स्नेहन, रोलर/बॉल बेयरिंग, धारावाहिक आकार", "रूखी सतह, तेल, भारी टायर", "कीले, उभार, खुरदुरापन", "वजन बढ़ाना, ग्रीस, चौड़े तल"],
     ["Lubrication, rollers/ball bearings, streamlined shape", "Rough surface, oil, heavy tyres", "Spikes, treads, roughness", "Adding weight, grease, broad soles"],
     0,
     "मानक तीन उपाय — स्नेहक, रोलिंग (बेयरिंग) और धारावाहिक आकार।",
     "The standard three — lubricants, rolling (bearings) and streamlining."),
]
