# -*- coding: utf-8 -*-
"""P03 (Force & Laws of Motion) — Part 1: force-and-effects (38) + law-of-inertia (38) = 76 tuples.
All items authored with correct_idx=0; rotation happens in gen_p03_questions.py.

T1 force-and-effects 38 = E16/M16/H6
T2 law-of-inertia      38 = E15/M16/H7
"""

PART1 = [
    # ================= FORCE & ITS EFFECTS (38) =================
    # ---- easy (16) ----
    ("force-and-effects", "easy",
     "बल किसे कहते हैं?",
     "What is force?",
     ["वह प्रभाव जो वस्तु की गति अवस्था या आकार बदल सकता है", "केवल वस्तु का भार", "केवल वस्तु में संग्रित ऊर्जा", "वस्तु का आयतन"],
     ["The influence that can change an object's state of motion or shape", "Only the weight of an object", "Only the energy stored in an object", "The volume of an object"],
     0,
     "बल धक्का या खिंचाव है जो गति, दिशा या आकार बदल सकता है।",
     "Force is a push or pull that can change motion, direction or shape."),

    ("force-and-effects", "easy",
     "बल का SI मात्रक क्या है?",
     "What is the SI unit of force?",
     ["न्यूटन (N)", "किलोग्राम (kg)", "जूल (J)", "मीटर/सेकंड (m/s)"],
     ["Newton (N)", "Kilogram (kg)", "Joule (J)", "Metre/second (m/s)"],
     0,
     "बल का SI मात्रक न्यूटन है, जिसे N से लिखते हैं।",
     "The SI unit of force is the newton, written N."),

    ("force-and-effects", "easy",
     "बल लगाने से वस्तु का कौन-सा गुण नहीं बदलता?",
     "Which property of an object does a force NOT change?",
     ["द्रव्यमान", "गति", "दिशा", "आकार"],
     ["Mass", "Motion", "Direction", "Shape"],
     0,
     "बल गति, दिशा या आकार बदल सकता है, पर द्रव्यमान नहीं।",
     "Force can change motion, direction or shape, but not mass."),

    ("force-and-effects", "easy",
     "बल के दो रूप (तरीके) कौन-से हैं?",
     "What are the two forms (ways) of applying a force?",
     ["धक्का और खिंचाव", "ऊर्जा और कार्य", "चाल और वेग", "द्रव्यमान और भार"],
     ["Push and pull", "Energy and work", "Speed and velocity", "Mass and weight"],
     0,
     "बल दो तरीकों से लगता है — धक्का देना और खींचना।",
     "Force acts in two ways — pushing and pulling."),

    ("force-and-effects", "easy",
     "संतुलित बलों का परिणामी बल कितना होता है?",
     "What is the resultant of balanced forces?",
     ["शून्य", "अनंत", "एक", "सदा बढ़ता हुआ"],
     ["Zero", "Infinite", "One", "Always increasing"],
     0,
     "संतुलित बलों का परिणामी शून्य होता है, इसलिए गति अवस्था नहीं बदलती।",
     "The resultant of balanced forces is zero, so the state of motion does not change."),

    ("force-and-effects", "easy",
     "रस्साकशी में दोनों टीमें बराबर बल लगा रही हैं — रस्सी क्या करेगी?",
     "In a tug of war both teams pull with equal force — what does the rope do?",
     ["स्थिर रहेगी", "टीम A की ओर जाएगी", "टीम B की ओर जाएगी", "टूट जाएगी"],
     ["It stays still", "It moves towards team A", "It moves towards team B", "It snaps"],
     0,
     "बराबर-विपरीत बलों से परिणामी शून्य — रस्सी विरामावस्था में रहती है।",
     "Equal and opposite forces give zero resultant — the rope stays at rest."),

    ("force-and-effects", "easy",
     "असंतुलित बल वस्तु में क्या परिवर्तन लाता है?",
     "What change does an unbalanced force bring in an object?",
     ["गति अवस्था में परिवर्तन (त्वरण)", "कुछ भी नहीं", "केवल रंग में परिवर्तन", "द्रव्यमान में वृद्धि"],
     ["A change in the state of motion (acceleration)", "Nothing at all", "Only a change in colour", "An increase in mass"],
     0,
     "असंतुलित बल ही वस्तु की गति अवस्था बदलता है — विराम से गति, गति से विराम, या दिशा/चाल परिवर्तन।",
     "Only an unbalanced force changes the state of motion — rest to motion, motion to rest, or a change of speed/direction."),

    ("force-and-effects", "easy",
     "बल कौन-सी भौतिक राशि है?",
     "What kind of physical quantity is force?",
     ["सदिश राशि (परिमाण + दिशा)", "अदिश राशि (केवल परिमाण)", "न तो सदिश, न अदिश", "केवल संख्या"],
     ["A vector quantity (magnitude + direction)", "A scalar quantity (magnitude only)", "Neither vector nor scalar", "Just a number"],
     0,
     "बल में परिमाण और दिशा दोनों होते हैं, इसलिए यह सदिश राशि है।",
     "Force has both magnitude and direction, so it is a vector quantity."),

    ("force-and-effects", "easy",
     "बल्लेबाज के हिट करने पर गेंद की दिशा बदल जाती है — यह बल का कौन-सा प्रभाव है?",
     "A batter hits the ball and its direction changes — which effect of force is this?",
     ["गति की दिशा में परिवर्तन", "आकार में परिवर्तन", "द्रव्यमान में परिवर्तन", "कोई प्रभाव नहीं"],
     ["A change in the direction of motion", "A change in shape", "A change in mass", "No effect"],
     0,
     "बल गेंद की गति की दिशा बदल देता है।",
     "The force changes the direction of the ball's motion."),

    ("force-and-effects", "easy",
     "रबर की पट्टी खींचने पर वह लंबी हो जाती है — यह बल का कौन-सा प्रभाव है?",
     "A rubber band stretches when pulled — which effect of force is this?",
     ["आकार (और लंबाई) में परिवर्तन", "केवल द्रव्यमान में परिवर्तन", "रंग में परिवर्तन", "कोई परिवर्तन नहीं"],
     ["A change in shape (and length)", "Only a change in mass", "A change in colour", "No change"],
     0,
     "खिंचाव के बल से पट्टी का आकार बदलता है — वह लंबी हो जाती है।",
     "The pull changes the band's shape — it becomes longer."),

    ("force-and-effects", "easy",
     "बल मापने का यंत्र कौन-सा है?",
     "Which instrument measures force?",
     ["स्प्रिंग तुला (स्प्रिंग बैलेंस)", "पैमाना (रूलर)", "थर्मामीटर", "अमीटर"],
     ["A spring balance", "A ruler", "A thermometer", "An ammeter"],
     0,
     "स्प्रिंग बैलेंस में स्प्रिंग के खिंचाव से बल का परिमाण पढ़ा जाता है।",
     "In a spring balance the stretch of the spring gives the force."),

    ("force-and-effects", "easy",
     "मिट्टी के घड़े पर कुम्हार हाथ से दबाव डालता है और आकार बदल जाता है — यह दर्शाता है —",
     "A potter presses the clay and its shape changes — this shows that —",
     ["बल आकार बदल सकता है", "बल द्रव्यमान बदलता है", "बल रंग बदलता है", "मिट्टी में बल नहीं लगता"],
     ["Force can change shape", "Force changes mass", "Force changes colour", "No force acts on the clay"],
     0,
     "हाथ का बल मिट्टी का आकार बदल देता है।",
     "The hand's force changes the clay's shape."),

    ("force-and-effects", "easy",
     "एक ही वस्तु पर कार्यरत दो बराबर और विपरीत बल क्या कहलाते हैं?",
     "Two equal and opposite forces acting on the same object are called —",
     ["संतुलित बल", "असंतुलित बल", "घर्षण बल", "चुंबकीय बल"],
     ["Balanced forces", "Unbalanced forces", "Frictional force", "Magnetic force"],
     0,
     "एक ही वस्तु पर बराबर-विपरीत बल परस्पर संतुलित कर देते हैं।",
     "Equal and opposite forces on the same object balance each other."),

    ("force-and-effects", "easy",
     "विरामावस्था में पड़ी गाड़ी को चलाने के लिए कौन-सा बल चाहिए?",
     "Which force is needed to start a cart at rest?",
     ["असंतुलित बल", "संतुलित बल", "शून्य बल", "कोई बल नहीं चाहिए"],
     ["An unbalanced force", "A balanced force", "Zero force", "No force is needed"],
     0,
     "विराम से गति देने के लिए असंतुलित बल ही अवस्था बदलता है।",
     "Only an unbalanced force changes the state from rest to motion."),

    ("force-and-effects", "easy",
     "साइकिल में ब्रेक लगाने पर कौन-सा परिवर्तन होता है?",
     "What change happens when brakes are applied to a bicycle?",
     ["चाल घटती है", "चाल बढ़ती है", "द्रव्यमान घटता है", "आकार बदलता है"],
     ["The speed decreases", "The speed increases", "The mass decreases", "The shape changes"],
     0,
     "ब्रेक का बल गति का विरोध करके चाल घटाता है।",
     "The braking force opposes the motion and reduces the speed."),

    ("force-and-effects", "easy",
     "'गति अवस्था में परिवर्तन' का अर्थ है —",
     "A 'change in the state of motion' means —",
     ["विराम↔गति, चाल में परिवर्तन, या दिशा में परिवर्तन", "केवल रंग में परिवर्तन", "केवल आकार में परिवर्तन", "केवल भार में परिवर्तन"],
     ["Rest↔motion, a change of speed, or a change of direction", "Only a change of colour", "Only a change of shape", "Only a change of weight"],
     0,
     "अवस्था परिवर्तन तीन तरह का हो सकता है — विराम/गति, चाल या दिशा का बदलाव।",
     "A state change can be of three kinds — rest/motion, speed or direction."),

    # ---- medium (16) ----
    ("force-and-effects", "medium",
     "एक वस्तु पर 10 N पूर्व की ओर और 10 N पश्चिम की ओर बल लग रहे हैं — वस्तु क्या करेगी?",
     "Forces of 10 N east and 10 N west act on an object — what will it do?",
     ["अपनी अवस्था में ही रहेगी (परिणामी शून्य)", "पूर्व की ओर चलेगी", "पश्चिम की ओर चलेगी", "घूमने लगेगी"],
     ["It stays in its existing state (resultant zero)", "It moves east", "It moves west", "It starts spinning"],
     0,
     "10 − 10 = 0 — संतुलित बल, अवस्था में कोई परिवर्तन नहीं।",
     "10 − 10 = 0 — balanced forces, no change of state."),

    ("force-and-effects", "medium",
     "एक गाड़ी पर 8 N दाएँ और 3 N बाएँ बल लग रहे हैं — परिणामी बल क्या होगा?",
     "A cart has 8 N rightward and 3 N leftward forces — what is the resultant?",
     ["5 N दाएँ", "11 N दाएँ", "5 N बाएँ", "शून्य"],
     ["5 N to the right", "11 N to the right", "5 N to the left", "Zero"],
     0,
     "8 − 3 = 5 N, बड़े बल की दिशा में — दाएँ।",
     "8 − 3 = 5 N, in the direction of the larger force — right."),

    ("force-and-effects", "medium",
     "नाव पर 12 N उत्तर और 5 N दक्षिण की ओर बल — परिणामी?",
     "A boat gets 12 N northward and 5 N southward forces — the resultant?",
     ["7 N उत्तर", "17 N उत्तर", "7 N दक्षिण", "शून्य"],
     ["7 N north", "17 N north", "7 N south", "Zero"],
     0,
     "12 − 5 = 7 N उत्तर की ओर।",
     "12 − 5 = 7 N towards north."),

    ("force-and-effects", "medium",
     "एक ही दिशा में 6 N और 8 N के बल एक साथ लगें तो परिणामी बल —",
     "Forces of 6 N and 8 N act in the same direction — the resultant force is —",
     ["14 N उसी दिशा में", "2 N", "48 N", "शून्य"],
     ["14 N in that direction", "2 N", "48 N", "Zero"],
     0,
     "एक ही दिशा के बल जुड़ जाते हैं: 6 + 8 = 14 N।",
     "Forces in the same direction add up: 6 + 8 = 14 N."),

    ("force-and-effects", "medium",
     "संतुलित बल वस्तु के आकार को बदल सकते हैं या नहीं?",
     "Can balanced forces change the shape of an object?",
     ["हाँ, आकार बदल सकते हैं पर गति अवस्था नहीं", "नहीं, कभी कुछ नहीं बदलते", "केवल गति बदलते हैं", "केवल द्रव्यमान बदलते हैं"],
     ["Yes, they can change shape but not the state of motion", "No, they never change anything", "They change only motion", "They change only mass"],
     0,
     "दोनों ओर से बराबर खिंचाव (जैसे रस्सी/स्प्रिंग) आकार बदल देता है, पर विराम-गति नहीं।",
     "Equal pulls from both sides (as on a rope/spring) change shape but not rest/motion."),

    ("force-and-effects", "medium",
     "परिणामी बल किसे कहते हैं?",
     "What is the resultant force?",
     ["वस्तु पर लगने वाले सभी बलों का संयुक्त (सदिश) प्रभाव", "केवल सबसे बड़ा बल", "केवल सबसे छोटा बल", "बलों का औसत"],
     ["The combined (vector) effect of all forces acting on the object", "Only the largest force", "Only the smallest force", "The average of the forces"],
     0,
     "सभी बलों को सदिश विधि से जोड़ने पर जो एक बल मिलता है, वही परिणामी बल है।",
     "Adding all forces as vectors gives the single resultant force."),

    ("force-and-effects", "medium",
     "एक वस्तु पर 3 N और 4 N के बल परस्पर समकोण पर लगे हैं — परिणामी बल का परिमाण —",
     "Forces of 3 N and 4 N act at right angles on an object — the magnitude of the resultant is —",
     ["5 N", "7 N", "1 N", "12 N"],
     ["5 N", "7 N", "1 N", "12 N"],
     0,
     "पाइथागोरस: √(3² + 4²) = √25 = 5 N।",
     "Pythagoras: √(3² + 4²) = √25 = 5 N."),

    ("force-and-effects", "medium",
     "कथन A: बल में परिमाण और दिशा दोनों होते हैं। कथन B: बल में केवल दिशा होती है। सही विकल्प —",
     "Statement A: force has both magnitude and direction. Statement B: force has only direction. The correct option —",
     ["A सही, B गलत", "A गलत, B सही", "दोनों सही", "दोनों गलत"],
     ["A right, B wrong", "A wrong, B right", "Both right", "Both wrong"],
     0,
     "बल सदिश है — परिमाण भी, दिशा भी; केवल दिशा पर्याप्त नहीं।",
     "Force is a vector — magnitude as well as direction; direction alone is not enough."),

    ("force-and-effects", "medium",
     "दो व्यक्ति एक मेज़ को एक ही दिशा में 25 N और 35 N के बल से धकेलते हैं — मेज़ पर कुल बल —",
     "Two people push a table in the same direction with 25 N and 35 N — the total force on the table is —",
     ["60 N उसी दिशा में", "10 N", "25 N", "35 N"],
     ["60 N in that direction", "10 N", "25 N", "35 N"],
     0,
     "समान दिशा में बल जुड़ते हैं: 25 + 35 = 60 N।",
     "Forces in the same direction add: 25 + 35 = 60 N."),

    ("force-and-effects", "medium",
     "एक वस्तु पर तीन बल: 5 N पूर्व, 5 N पश्चिम और 3 N उत्तर — परिणामी बल —",
     "Three forces on an object: 5 N east, 5 N west and 3 N north — the resultant is —",
     ["3 N उत्तर", "13 N", "3 N पूर्व", "शून्य"],
     ["3 N north", "13 N", "3 N east", "Zero"],
     0,
     "पूर्व-पश्चिम के बल कट जाते हैं (5−5=0), बचता है 3 N उत्तर।",
     "The east-west forces cancel (5−5=0); 3 N north remains."),

    ("force-and-effects", "medium",
     "वस्तु पर बल लगाने पर भी उसकी अवस्था नहीं बदलती — इसका निष्कर्ष क्या है?",
     "A force is applied yet the object's state does not change — the conclusion is —",
     ["लगने वाले बल संतुलित हैं (परिणामी शून्य)", "बल कभी अवस्था नहीं बदलता", "वस्तु में द्रव्यमान नहीं है", "वस्तु बहुत ठंडी है"],
     ["The forces acting are balanced (resultant zero)", "Force never changes state", "The object has no mass", "The object is too cold"],
     0,
     "यदि अवस्था अपरिवर्तित रहे, तो परिणामी बल शून्य ही होगा।",
     "If the state stays unchanged, the resultant force must be zero."),

    ("force-and-effects", "medium",
     "पतंग हवा में टिकी रहती है — उस पर कितने बल कार्यरत हैं (न्यूनतम)?",
     "A kite stays steady in the sky — at least how many forces act on it?",
     ["दो से अधिक (धागे का खिंचाव, वायु का बल आदि)", "केवल एक", "कोई नहीं", "अर्ध"],
     ["More than two (the string's pull, the air's push, etc.)", "Only one", "None", "Half"],
     0,
     "स्थिर पतंग पर धागे का तानाव, वायु प्रतिरोध इत्यादि कई बल परस्पर संतुलित कर रहे होते हैं।",
     "A steady kite has several forces — string tension, air resistance and so on — balancing each other."),

    ("force-and-effects", "medium",
     "गतिमान फुटबॉल को रोकने वाला गोलकीपर बल का कौन-सा प्रभाक दिखाता है?",
     "A goalkeeper stopping a moving football demonstrates which effect of force?",
     ["चाल में परिवर्तन (गति से विराम)", "केवल आकार में परिवर्तन", "द्रव्यमान में परिवर्तन", "कोई प्रभाव नहीं"],
     ["A change of speed (motion to rest)", "Only a change of shape", "A change of mass", "No effect"],
     0,
     "हाथ का बल गेंद की चाल शून्य कर देता है।",
     "The hands' force brings the ball's speed to zero."),

    ("force-and-effects", "medium",
     "संतुलित और असंतुलित बलों का मुख्य अंतर क्या है?",
     "What is the key difference between balanced and unbalanced forces?",
     ["परिणामी बल शून्य बनाम परिणामी बल अशून्य", "दोनों का परिणामी सदा समान होता है", "संतुलित बल द्रव्यमान बदलता है", "असंतुलित बल रंग बदलता है"],
     ["Resultant zero versus resultant non-zero", "Both always have the same resultant", "Balanced force changes mass", "Unbalanced force changes colour"],
     0,
     "संतुलित: परिणामी 0, अवस्था अपरिवर्तित; असंतुलित: परिणामी ≠ 0, अवस्था बदलती है।",
     "Balanced: resultant 0, state unchanged; unbalanced: resultant ≠ 0, state changes."),

    ("force-and-effects", "medium",
     "समान वस्तु पर दो बल विपरीत दिशाओं में 9 N और 4 N — वस्तु किस ओर त्वरित होगी?",
     "Two forces of 9 N and 4 N act on a box in opposite directions — which way does the box accelerate?",
     ["9 N वाले बल की ओर (परिणामी 5 N)", "4 N वाले बल की ओर", "किसी ओर नहीं", "ऊपर की ओर"],
     ["Towards the 9 N force (resultant 5 N)", "Towards the 4 N force", "Neither way", "Upwards"],
     0,
     "9 − 4 = 5 N, बड़े बल की दिशा में त्वरण।",
     "9 − 4 = 5 N; acceleration is towards the larger force."),

    ("force-and-effects", "medium",
     "बक्से को धकेलने पर वह नहीं हिला — इसका सबसे तर्कसंगत कारण —",
     "A box is pushed but it does not move — the most reasonable explanation is —",
     ["धक्का बल घर्षण से संतुलित हो गया", "बक्से में बल नहीं लगा", "बल हमेशा व्यर्थ होता है", "बक्सा द्रव्यमानहीन है"],
     ["The push was balanced by friction", "No force acted on the box", "Force is always useless", "The box has no mass"],
     0,
     "घर्षण बल धक्के के बराबर होने पर परिणामी शून्य — बक्सा विराम में रहता है।",
     "When friction equals the push, the resultant is zero — the box stays at rest."),

    # ---- hard (6) ----
    ("force-and-effects", "hard",
     "10 N और 7 N के दो बलों के परिणामी का अधिकतम और न्यूनतम मान क्रमशः हो सकता है —",
     "The maximum and minimum possible resultants of two forces, 10 N and 7 N, are respectively —",
     ["17 N और 3 N", "17 N और 0 N", "10 N और 7 N", "70 N और 3 N"],
     ["17 N and 3 N", "17 N and 0 N", "10 N and 7 N", "70 N and 3 N"],
     0,
     "समान दिशा में अधिकतम 10+7 = 17 N; विपरीत दिशा में न्यूनतम 10−7 = 3 N।",
     "Same direction gives the maximum 10+7 = 17 N; opposite directions the minimum 10−7 = 3 N."),

    ("force-and-effects", "hard",
     "कथन A: संतुलित बल गति अवस्था नहीं बदलते। कथन B: असंतुलित बल वस्तु को त्वरित करता है। सही विकल्प —",
     "Statement A: balanced forces do not change the state of motion. Statement B: an unbalanced force accelerates the object. The correct option —",
     ["A और B दोनों सही", "केवल A सही", "केवल B सही", "दोनों गलत"],
     ["Both A and B are right", "Only A is right", "Only B is right", "Both are wrong"],
     0,
     "परिणामी शून्य → अवस्था अपरिवर्तित; परिणामी अशून्य → त्वरण।",
     "Zero resultant → no change of state; non-zero resultant → acceleration."),

    ("force-and-effects", "hard",
     "एक वस्तु पर चार बल कार्यरत हैं: 5 N पूर्व, 5 N पश्चिम, 3 N उत्तर, 3 N दक्षिण — वस्तु की अवस्था क्या होगी?",
     "Four forces act on an object: 5 N east, 5 N west, 3 N north, 3 N south — what happens to the object's state?",
     ["परिणामी शून्य — अवस्था अपरिवर्तित रहेगी", "वह उत्तर की ओर चलेगी", "वह पूर्व की ओर चलेगी", "वह घूमेगी"],
     ["Resultant zero — its state stays unchanged", "It moves north", "It moves east", "It spins"],
     0,
     "प्रत्येक दिशा के जोड़े (5−5, 3−3) शून्य — कुल परिणामी शून्य।",
     "Each opposing pair (5−5, 3−3) cancels — the total resultant is zero."),

    ("force-and-effects", "hard",
     "जब बल की दिशा गति की दिशा के लंबवत हो, तो बल का मुख्य प्रभाव होता है —",
     "When the force is perpendicular to the direction of motion, its main effect is —",
     ["केवल गति की दिशा बदलना, चाल नहीं", "केवल चाल बदलना", "द्रव्यमान बदलना", "कोई प्रभाव नहीं"],
     ["Changing only the direction of motion, not the speed", "Changing only the speed", "Changing the mass", "No effect"],
     0,
     "लंबवत बल पथ को मोड़ता है (वृत्तीय गति के समान) पर चाल नहीं बदलता।",
     "A perpendicular force bends the path (as in circular motion) without changing the speed."),

    ("force-and-effects", "hard",
     "रस्साकशी में टीम A 100 N तथा टीम B 80 N बल से खींच रही है — रस्सी पर परिणामी बल और दिशा —",
     "In a tug of war team A pulls with 100 N and team B with 80 N — the resultant force on the rope and its direction —",
     ["20 N, टीम A की ओर", "180 N, टीम A की ओर", "20 N, टीम B की ओर", "शून्य, रस्सी स्थिर"],
     ["20 N, towards team A", "180 N, towards team A", "20 N, towards team B", "Zero, the rope stays still"],
     0,
     "100 − 80 = 20 N परिणामी, प्रबलतर टीम A की ओर।",
     "100 − 80 = 20 N resultant, towards the stronger team A."),

    ("force-and-effects", "hard",
     "एक ही रेखा में तीन बल: +6 N, −6 N और +2 N (दाएँ धनात्मक) — वस्तु —",
     "Three collinear forces: +6 N, −6 N and +2 N (rightward positive) — the object —",
     ["2 N दाएँ के त्वरण से चलेगी", "6 N बाएँ जाएगी", "पूर्ण विराम में रहेगी", "14 N दाएँ जाएगी"],
     ["It accelerates with 2 N to the right", "It goes 6 N left", "It stays perfectly at rest", "It goes 14 N right"],
     0,
     "+6 − 6 + 2 = +2 N — शेष 2 N दाएँ, इसलिए दाएँ त्वरण।",
     "+6 − 6 + 2 = +2 N — a leftover 2 N rightward, so rightward acceleration."),

    # ================= LAW OF INERTIA / FIRST LAW (38) =================
    # ---- easy (15) ----
    ("law-of-inertia", "easy",
     "न्यूटन का प्रथम नियम किस नाम से जाना जाता है?",
     "Newton's first law is known by which name?",
     ["जड़त्व का नियम", "संवेग का नियम", "क्रिया-प्रतिक्रिया का नियम", "बल का नियम"],
     ["The law of inertia", "The law of momentum", "The law of action-reaction", "The law of force"],
     0,
     "प्रथम नियम जड़त्व का नियम है — वस्तु अपनी अवस्था बनाए रखती है।",
     "The first law is the law of inertia — an object keeps its state."),

    ("law-of-inertia", "easy",
     "जड़त्व का माप किस भौतिक राशि से होता है?",
     "Which physical quantity measures inertia?",
     ["द्रव्यमान", "आयतन", "घनत्व", "रंग"],
     ["Mass", "Volume", "Density", "Colour"],
     0,
     "द्रव्यमान जितना अधिक, जड़त्व उतना अधिक — द्रव्यमान जड़त्व का माप है।",
     "The greater the mass, the greater the inertia — mass measures inertia."),

    ("law-of-inertia", "easy",
     "खड़ी बस अचानक चलने पर यात्री किस ओर झुकता है?",
     "When a standing bus starts suddenly, which way do passengers lean?",
     ["पीछे की ओर", "आगे की ओर", "ऊपर की ओर", "किसी ओर नहीं"],
     ["Backward", "Forward", "Upward", "Neither way"],
     0,
     "शरीर विराम में रहना चाहता है (विराम की जड़त्व), पैर बस के साथ चलते हैं — धड़ पीछे।",
     "The body wants to stay at rest (inertia of rest) while the feet move with the bus — the torso lags backward."),

    ("law-of-inertia", "easy",
     "चलती बस में अचानक ब्रेक लगे तो यात्री किस ओर गिरता है?",
     "When a moving bus brakes suddenly, which way does a passenger fall?",
     ["आगे की ओर", "पीछे की ओर", "बाएँ", "नीचे ही नहीं गिरता"],
     ["Forward", "Backward", "To the left", "Does not fall at all"],
     0,
     "गति की जड़त्व से धड़ आगे बढ़ता रहता है जब तक बस रुक जाती है।",
     "Inertia of motion keeps the torso moving forward while the bus stops."),

    ("law-of-inertia", "easy",
     "न्यूटन के अनुसार वस्तु अपनी अवस्था तब तक नहीं बदलती जब तक —",
     "According to Newton, an object does not change its state until —",
     ["उस पर बाह्य असंतुलित बल न लगे", "उसे छुआ न जाए", "उसका रंग न बदले", "सूर्य न उगे"],
     ["An external unbalanced force acts on it", "It is touched", "Its colour changes", "The sun rises"],
     0,
     "प्रथम नियम: बाह्य असंतुलित बल के बिना अवस्था परिवर्तन नहीं।",
     "First law: no change of state without an external unbalanced force."),

    ("law-of-inertia", "easy",
     "द्रव्यमान अधिक होने पर जड़त्व —",
     "If the mass is greater, the inertia —",
     ["अधिक होती है", "कम होती है", "समान रहती है", "शून्य हो जाती है"],
     ["Is greater", "Is smaller", "Stays the same", "Becomes zero"],
     0,
     "द्रव्यमान जड़त्व का माप है — द्रव्यमान बढ़ा तो जड़त्व बढ़ी।",
     "Mass measures inertia — more mass, more inertia."),

    ("law-of-inertia", "easy",
     "जड़त्व का अर्थ है —",
     "Inertia means —",
     ["अवस्था न बदलने का प्रवृत्ति (गुण)", "गति करने की इच्छा", "बल लगाना", "वेग मापना"],
     ["The tendency (property) of not changing one's state", "The desire to move", "Applying a force", "Measuring velocity"],
     0,
     "जड़त्व = विराम या गति की अवस्था में बने रहने का गुण।",
     "Inertia = the property of remaining in one's state of rest or motion."),

    ("law-of-inertia", "easy",
     "पेड़ की शाखा हिलाने पर फल गिर जाता है — यह किस जड़त्व का उदाहरण है?",
     "Shaking a branch makes the fruit fall — this is an example of which inertia?",
     ["विराम की जड़त्व", "गति की जड़त्व", "दिशा की जड़त्व", "जड़त्व नहीं है"],
     ["Inertia of rest", "Inertia of motion", "Inertia of direction", "No inertia at all"],
     0,
     "शाखा हिल जाती है पर फल विराम में रहना चाहता है — डंठल टूटकर फल गिरता है।",
     "The branch moves but the fruit tends to stay at rest — the stalk snaps and it falls."),

    ("law-of-inertia", "easy",
     "कालीन (गिलासै) को पीटने पर धूल झड़ जाती है — कारण —",
     "Beating a carpet shakes off the dust — the reason is —",
     ["धूल विराम की जड़त्व से पीछे रह जाती है", "कालीन धूल को खींचता है", "धूल का द्रव्यमान शून्य है", "कालीन में चुंबकत्व है"],
     ["The dust lags behind due to inertia of rest", "The carpet pulls the dust", "The dust has zero mass", "The carpet is magnetic"],
     0,
     "कालीन गति करता है, धूल कण विराम में रहना चाहते हैं — वे झड़ जाते हैं।",
     "The carpet moves; the dust particles tend to stay at rest and drop off."),

    ("law-of-inertia", "easy",
     "काँच के गिलास पर कार्ड रखकर उस पर सिक्का रखा है; कार्ड को तेज़ी से झटका देने पर सिक्का —",
     "A coin rests on a card over a glass; flicking the card sharply makes the coin —",
     ["गिलास में गिरता है", "कार्ड के साथ उड़ जाता है", "ऊपर उठ जाता है", "गायब हो जाता है"],
     ["Drop into the glass", "Fly off with the card", "Rise up", "Vanish"],
     0,
     "सिक्का विराम में रहता है, कार्ड निकल जाता है — सिक्का नीचे गिरता है।",
     "The coin stays at rest while the card slides away — it drops into the glass."),

    ("law-of-inertia", "easy",
     "दौड़ता एथलीट तुरंत क्यों नहीं रुक पाता?",
     "Why cannot a sprinter stop instantly?",
     ["गति की जड़त्व के कारण", "विराम की जड़त्व के कारण", "उसका द्रव्यमान शून्य है", "उसकी चाल सदा समान रहती है"],
     ["Because of inertia of motion", "Because of inertia of rest", "His mass is zero", "His speed is always constant"],
     0,
     "गति की जड़त्व शरीर को चलते रहने पर मजबूर करती है।",
     "Inertia of motion keeps the body moving forward."),

    ("law-of-inertia", "easy",
     "गाड़ियों में सीटबेल्ट क्यों होती है?",
     "Why do vehicles have seat belts?",
     ["अचानक ब्रेक पर आगे गिरने से बचाने (जड़त्व)", "गाड़ी सुंदर दिखाने के लिए", "बैठने का आराम बढ़ाने के लिए", "गाड़ी को तेज़ करने के लिए"],
     ["To prevent being thrown forward on sudden braking (inertia)", "To beautify the vehicle", "For sitting comfort", "To speed up the vehicle"],
     0,
     "ब्रेक पर शरीर गति में बना रहता है; बेल्ट उसे रोकती है।",
     "On braking the body keeps moving; the belt restrains it."),

    ("law-of-inertia", "easy",
     "जड़त्व की अवधारणा सर्वप्रथम किसने दी?",
     "Who first gave the concept of inertia?",
     ["गैलीलियो", "न्यूटन", "आइंस्टीन", "आर्किमिडीज"],
     ["Galileo", "Newton", "Einstein", "Archimedes"],
     0,
     "गैलीलियो ने प्रयोगों से जड़त्व की अवधारणा दी; न्यूटन ने इसे नियम रूप दिया।",
     "Galileo arrived at inertia through experiments; Newton gave it the form of a law."),

    ("law-of-inertia", "easy",
     "जड़त्व के कितने प्रकार बताए जाते हैं?",
     "How many kinds of inertia are usually described?",
     ["तीन — विराम, गति, दिशा", "दो — विराम, गति", "एक ही", "चार"],
     ["Three — rest, motion, direction", "Two — rest, motion", "Only one", "Four"],
     0,
     "विराम की जड़त्व, गति की जड़त्व और दिशा की जड़त्व — तीन प्रकार।",
     "Inertia of rest, inertia of motion and inertia of direction — three kinds."),

    ("law-of-inertia", "easy",
     "संतुलित बलों के अधीन विरामावस्था वस्तु —",
     "An object at rest under balanced forces will —",
     ["विराम में ही रहेगी", "चलने लगेगी", "उड़ने लगेगी", "घूमने लगेगी"],
     ["Remain at rest", "Start moving", "Start flying", "Start spinning"],
     0,
     "परिणामी शून्य हो तो प्रथम नियम के अनुसार अवस्था अपरिवर्तित — विराम ही रहेगा।",
     "With zero resultant the first law keeps the state unchanged — it stays at rest."),

    # ---- medium (16) ----
    ("law-of-inertia", "medium",
     "चलती बस से उतरते समय यात्री अक्सर आगे क्यों गिरता है?",
     "Why does a passenger often lurch forward while getting off a moving bus?",
     ["पायदान रुकती है पर शरीर गति में बना रहता है", "शरीर हल्का हो जाता है", "बस पीछे की ओर खिंचती है", "पायदान चिकनी होती है"],
     ["The step stops but the body stays in motion", "The body becomes lighter", "The bus pulls backward", "The step is slippery"],
     0,
     "जमीन पर पैड रुक जाता है, धड़ गति की जड़त्व से आगे बढ़ता रहता है।",
     "The foot on the ground stops; inertia of motion carries the torso forward."),

    ("law-of-inertia", "medium",
     "ट्रेन में खड़ा यात्री ट्रेन के धीमा होने पर आगे लड़खड़ाता है — कारण —",
     "A standing rail passenger stumbles forward as the train slows — because —",
     ["गति की जड़त्व शरीर को आगे ढकेलती रहती है", "विराम की जड़त्व शरीर को रोकती है", "ट्रेन ऊपर उठती है", "यात्री का द्रव्यमान घटता है"],
     ["Inertia of motion keeps pushing the body forward", "Inertia of rest stops the body", "The train rises up", "The passenger's mass falls"],
     0,
     "ट्रेन धीमी होती है, शरीर पुरानी चाल से चलता रहना चाहता है।",
     "The train slows, but the body tends to continue at the old speed."),

    ("law-of-inertia", "medium",
     "पेड़ की शाखा को झटका देने पर पके आम गिर जाते हैं — कारण लिखिए —",
     "Jerk the branch of a tree and ripe mangoes fall — state the reason —",
     ["शाखा चलती है पर आम विराम में रहना चाहता है, डंठल टूट जाता है", "आम हल्के होने से उड़ जाते हैं", "शाखा आम को खींचती है", "आम में बल नहीं लगता"],
     ["The branch moves while the mango tends to stay at rest; the stalk snaps", "The mangoes, being light, fly off", "The branch pulls the mango", "No force acts on the mango"],
     0,
     "विराम की जड़त्व: शाखा+डंठल हिलते हैं, फल स्थिर — जुड़ाव टूटता है।",
     "Inertia of rest: branch and stalk move, the fruit stays put — the joint breaks."),

    ("law-of-inertia", "medium",
     "हथौड़े का हत्था कसने के लिए उसे जमीन पर क्यों पटकते हैं?",
     "Why is a hammer struck on the ground to tighten its loose head?",
     ["हत्था गति में रहता है, लोहा रुकता है — सिर चढ़ जाता है", "जमीन चुंबक की तरह खींचती है", "लोहे का द्रव्यमान बदल जाता है", "हथौड़ा गर्म हो जाता है"],
     ["The handle keeps moving while the head stops — the head seats itself", "The ground pulls like a magnet", "The iron head's mass changes", "The hammer heats up"],
     0,
     "जमीन पर पटकने पर हत्था अचानक रुकता है, लोहे का सिर गति की जड़त्व से आगे खिसककर कस जाता है।",
     "On striking, the handle stops abruptly; the iron head, by inertia of motion, slides on and tightens."),

    ("law-of-inertia", "medium",
     "1 kg रेत और 5 kg रेत — किसे हिलाना अधिक कठिन है और क्यों?",
     "1 kg of sand versus 5 kg of sand — which is harder to shake and why?",
     ["5 kg — क्योंकि उसका द्रव्यमान व जड़त्व अधिक है", "1 kg — वह अधिक सघन है", "दोनों समान", "5 kg — वह हल्का है"],
     ["5 kg — its mass and inertia are greater", "1 kg — it is denser", "Both equally", "5 kg — it is lighter"],
     0,
     "अधिक द्रव्यमान = अधिक जड़त्व = अवस्था बदलने में अधिक बल।",
     "More mass = more inertia = more force needed to change its state."),

    ("law-of-inertia", "medium",
     "कथन A: जड़त्व द्रव्यमान के समानुपाती है। कथन B: हल्की वस्तु में जड़त्व सदा अधिक होती है। सही विकल्प —",
     "Statement A: inertia is proportional to mass. Statement B: a lighter object always has more inertia. The correct option —",
     ["A सही, B गलत", "A गलत, B सही", "दोनों सही", "दोनों गलत"],
     ["A right, B wrong", "A wrong, B right", "Both right", "Both wrong"],
     0,
     "जड़त्व ∝ द्रव्यमान — हल्की वस्तु में जड़त्व कम होती है, अधिक नहीं।",
     "Inertia ∝ mass — a lighter object has less inertia, not more."),

    ("law-of-inertia", "medium",
     "पैडल न चलाने पर भी साइकिल कुछ दूर तक चलती रहती है — कारण —",
     "Even without pedalling a bicycle keeps rolling some distance — because —",
     ["गति की जड़त्व (घर्षण धीरे-धीरे रोकता है)", "साइकिल पर बल लगता रहता है", "पहिए ऊर्जा बनाते हैं", "साइकिल का द्रव्यमान बढ़ता है"],
     ["Inertia of motion (friction stops it gradually)", "A force keeps acting on it", "The wheels create energy", "The bicycle's mass increases"],
     0,
     "गति की जड़त्व चलायमान रखती है; घर्षण ही धीरे-धीरे उसे रोकता है।",
     "Inertia of motion keeps it rolling; friction alone slows it gradually."),

    ("law-of-inertia", "medium",
     "'आराम का नियम' किस नियम का लोक-नाम है?",
     "'The law of taking it easy' is the folk nickname of which law?",
     ["न्यूटन का प्रथम नियम (जड़त्व)", "न्यूटन का द्वितीय नियम", "न्यूटन का तृतीय नियम", "गुरुत्वाकर्षण का नियम"],
     ["Newton's first law (inertia)", "Newton's second law", "Newton's third law", "The law of gravitation"],
     0,
     "प्रथम नियम कहता है — बल न लगे तो वस्तु 'आराम' (अपनी अवस्था) में रहती है।",
     "The first law says — without a force the object 'relaxes' in its own state."),

    ("law-of-inertia", "medium",
     "चलती ट्रेन की खिड़की से सीधे छोड़ा सिक्का सीधी रेखा में नीचे क्यों गिरता है (ट्रेन की दिशा में आगे नहीं गिरता, यात्री के लिए)?",
     "A coin dropped from the window of a moving train falls straight down relative to the train's path — why does it keep moving along with the train initially?",
     ["सिक्के में गति की जड़त्व है — वह ट्रेन की क्षैतिज चाल बनाए रखता है", "सिक्का बहुत भारी है", "हवा उसे ऊपर उठाती है", "सिक्के में कोई द्रव्यमान नहीं"],
     ["The coin has inertia of motion — it retains the train's horizontal speed", "The coin is very heavy", "The air lifts it", "The coin has no mass"],
     0,
     "छोड़ते समय सिक्के की क्षैतिज चाल ट्रेन जितनी होती है; जड़त्व उसे तब तक बनाए रखती है।",
     "At release the coin's horizontal speed equals the train's; inertia preserves it."),

    ("law-of-inertia", "medium",
     "दौड़ते हुए एथलीट लंबी छलांग क्यों लगा पाता है?",
     "Why can a running athlete leap a long distance?",
     ["दौड़ की गति जड़त्व से शरीर में बनी रहती है और उसी के साथ वह उछलता है", "वह हवा में तैरता है", "उसका द्रव्यमान उछलते ही शून्य हो जाता है", "धरती उसे धकेलती है"],
     ["The run-up speed stays with the body due to inertia and carries the leap", "He floats in the air", "His mass becomes zero as he leaps", "The earth pushes him"],
     0,
     "दौड़ की चाल पहले से शरीर में होती है; कूदते समय वही चाल आगे ले जाती है।",
     "The body already has the run-up speed; that carried speed extends the jump."),

    ("law-of-inertia", "medium",
     "मोटरसाइकिल सवार ब्रेक लगाने पर आगे क्यों झुक जाता है?",
     "Why does a motorcyclist pitch forward on braking?",
     ["गाड़ी रुकती है पर शरीर गति में बना रहता है", "शरीर रुकता है पर गाड़ी चलती रहती है", "हेलमेट भारी होता है", "सड़क ऊपर उठ जाती है"],
     ["The bike stops but the rider's body stays in motion", "The body stops but the bike keeps moving", "The helmet is heavy", "The road rises up"],
     0,
     "गति की जड़त्व — धड़ आगे बढ़ता रहता है जब सवारी रुक जाती है।",
     "Inertia of motion — the torso continues as the bike halts."),

    ("law-of-inertia", "medium",
     "नियत वेग से चलाने के लिए बल आवश्यक है या नहीं?",
     "Is a force necessary to keep moving at a constant velocity?",
     ["नहीं — बल केवल अवस्था बदलने के लिए चाहिए", "हाँ, बिना बल चल ही नहीं सकते", "हाँ, हर क्षण बल चाहिए", "केवल मोड़ पर बल चाहिए"],
     ["No — force is needed only to change the state", "Yes, without force one cannot move at all", "Yes, force is needed every moment", "Force is needed only at turns"],
     0,
     "प्रथम नियम: नियत वेग किसी बल के बिना भी बना रहता है।",
     "First law: constant velocity persists without any force."),

    ("law-of-inertia", "medium",
     "यदि घर्षण और बाह्य बल पूरी तरह समाप्त हो जाएँ तो गतिमान वस्तु —",
     "If friction and external forces vanish completely, a moving object will —",
     ["सदा के लिए उसी चाल से सीधी रेखा में चलती रहेगी", "तुरंत रुक जाएगी", "धीमी होकर रुकेगी", "उल्टी दिशा में चलेगी"],
     ["Keep moving in a straight line at the same speed forever", "Stop at once", "Slow down and stop", "Move in the reverse direction"],
     0,
     "बिना बल बदलाव नहीं — गति अनंत काल तक अपरिवर्तित।",
     "With no force there is no change — the motion continues unaltered indefinitely."),

    ("law-of-inertia", "medium",
     "जड़त्व का मात्रक क्या माना जाता है?",
     "What is regarded as the unit of inertia?",
     ["किलोग्राम (द्रव्यमान का मात्रक, क्योंकि द्रव्यमान ही जड़त्व का माप है)", "न्यूटन", "मीटर", "मीटर/सेकंड"],
     ["Kilogram (the unit of mass, since mass itself measures inertia)", "Newton", "Metre", "Metre/second"],
     0,
     "द्रव्यमान जड़त्व का माप है, इसलिए जड़त्व का मात्रक द्रव्यमान जैसा ही — किलोग्राम।",
     "Since mass measures inertia, inertia carries mass's unit — the kilogram."),

    ("law-of-inertia", "medium",
     "कथन A: विरामावस्था वस्तु पर कोई बल नहीं लग रहा हो — यह आवश्यक नहीं। कथन B: विरामावस्था में वस्तु पर लगे सभी बल परस्पर संतुलित होते हैं। सही विकल्प —",
     "Statement A: an object at rest need not have zero forces acting on it. Statement B: in rest, all forces on the object balance one another. The correct option —",
     ["A और B दोनों सही", "केवल A सही", "केवल B सही", "दोनों गलत"],
     ["Both A and B are right", "Only A is right", "Only B is right", "Both are wrong"],
     0,
     "विराम में बल हो सकते हैं, पर उनका परिणामी शून्य होता है — दोनों कथन सही।",
     "Forces may act at rest, but their resultant is zero — both statements hold."),

    ("law-of-inertia", "medium",
     "खिलौना गाड़ी को धक्का देकर छोड़ देने पर वह धीरे-धीरे रुक जाती है — रुकने का कारण —",
     "A toy car pushed and released slows to a stop — what stops it?",
     ["जमीन व हवा का घर्षण बल", "धक्के का बल", "गाड़ी की जड़त्व", "गाड़ी का आकार"],
     ["The friction of the ground and the air", "The force of the push", "The car's inertia", "The car's shape"],
     0,
     "छोड़ने के बाद धक्का समाप्त; घर्षण ही अवस्था बदलकर रोकता है।",
     "The push ends at release; friction alone changes the state and stops it."),

    # ---- hard (7) ----
    ("law-of-inertia", "hard",
     "5 m/s से चलती वस्तु पर सभी बल हटा लिए जाएँ (घर्षण शून्य) — आगे उसकी चाल —",
     "All forces on an object moving at 5 m/s are removed (zero friction) — thereafter its speed —",
     ["5 m/s ही बनी रहेगी", "धीरे-धीरे शून्य होगी", "बढ़ती रहेगी", "घटकर ऋणात्मक होगी"],
     ["Stays at 5 m/s", "Gradually becomes zero", "Keeps increasing", "Becomes negative"],
     0,
     "प्रथम नियम — बल हटे तो अवस्था (5 m/s की समान चाल) अपरिवर्तित रहती है।",
     "First law — remove the forces and the state (5 m/s uniform) is preserved."),

    ("law-of-inertia", "hard",
     "कथन A: जड़त्व कोई बल नहीं, वस्तु का गुण है। कथन B: प्रथम नियम द्वितीय नियम का ही विशेष रूप है (a = 0 की स्थिति)। सही विकल्प —",
     "Statement A: inertia is not a force but a property of the object. Statement B: the first law is a special case of the second (the a = 0 case). The correct option —",
     ["A और B दोनों सही", "केवल A सही", "केवल B सही", "दोनों गलत"],
     ["Both A and B are right", "Only A is right", "Only B is right", "Both are wrong"],
     0,
     "जड़त्व गुण है, बल नहीं; F = ma में F = 0 रखने पर a = 0 — वही प्रथम नियम।",
     "Inertia is a property, not a force; putting F = 0 in F = ma gives a = 0 — the first law."),

    ("law-of-inertia", "hard",
     "कपड़े पर पानी छिड़कने के लिए कपड़े को जोर से हिलाया जाता है — पानी के छूटने का कारण —",
     "Wet clothes are jerked hard to sprinkle out water — the reason the water comes off is —",
     ["कपड़ा गति करता है, पानी की बूँदें विराम/पुरानी गति में रहना चाहती हैं और अलग हो जाती हैं", "कपड़े में छिद्र होते हैं", "पानी चिपकने वाला नहीं है", "कपड़ा गर्म हो जाता है"],
     ["The cloth moves while the droplets tend to keep their earlier state and separate", "Clothes have pores", "Water is not sticky", "The cloth heats up"],
     0,
     "झटके पर कपड़ा रुक-चलता है; बूँदें जड़त्व से पुरानी गति में बनी रहकर कपड़े से अलग हो जाती हैं।",
     "The jerking cloth changes state; the drops, keeping theirs by inertia, separate."),

    ("law-of-inertia", "hard",
     "निम्न में से गति की जड़त्व के उदाहरण चुनिए — (i) ब्रेक पर यात्री आगे (ii) धूल झड़ना (iii) दौड़ता एथलीट रुकने में देर (iv) सिक्का गिलास में गिरना —",
     "Pick the examples of inertia of MOTION — (i) passenger forward on braking (ii) dust dropping off (iii) a sprinter taking time to stop (iv) coin falling into a glass —",
     ["केवल (i) और (iii)", "केवल (ii) और (iv)", "चारों", "केवल (i)"],
     ["Only (i) and (iii)", "Only (ii) and (iv)", "All four", "Only (i)"],
     0,
     "(ii) और (iv) विराम की जड़त्व हैं; चलती अवस्था बनी रहना (i) व (iii) में है।",
     "(ii) and (iv) are inertia of rest; continuing motion appears in (i) and (iii)."),

    ("law-of-inertia", "hard",
     "बस अचानक मुड़ती है तो यात्री बाहर की ओर झुकता है — यह किस जड़त्व से जुड़ा है?",
     "When a bus turns sharply, passengers lean outward — which inertia is this linked to?",
     ["दिशा की जड़त्व", "विराम की जड़त्व", "द्रव्यमान की जड़त्व", "किसी से नहीं"],
     ["Inertia of direction", "Inertia of rest", "Inertia of mass", "None of these"],
     0,
     "शरीर पुरानी सीधी दिशा में चलना चाहता है — दिशा की जड़त्व।",
     "The body tends to continue in its old straight path — inertia of direction."),

    ("law-of-inertia", "hard",
     "सिक्का-कार्ड प्रयोग में कार्ड को तेज़ झटका देना क्यों जरूरी है?",
     "Why must the card in the coin-and-card trick be flicked quickly?",
     ["धीरे खींचने पर घर्षण सिक्के को भी कार्ड के साथ खींच लेता है; तेज़ झटके पर सिक्का लगभग विराम में रहता है", "तेज़ झटके से सिक्का चिपक जाता है", "कार्ड हल्का होना चाहिए", "सिक्का गर्म होना चाहिए"],
     ["A slow pull lets friction drag the coin along with the card; a sharp flick leaves the coin nearly at rest", "A sharp flick glues the coin", "The card must be light", "The coin must be warm"],
     0,
     "झटका तेज़ = कार्ड-सिक्का संपर्क समय अल्प = घर्षण का संवेग छोटा — सिक्का गिरता है नीचे।",
     "A sharp flick means a tiny contact time, so friction transfers negligible momentum — the coin drops."),

    ("law-of-inertia", "hard",
     "किस अवस्था में वस्तु पर परिणामी बल शून्य होता है?",
     "In which condition is the net force on an object zero?",
     ["विरामावस्था या नियत वेग से सीधी रेखा में गति — दोनों में", "केवल विरामावस्था में", "केवल त्वरित गति में", "केवल वृत्तीय गति में"],
     ["Both at rest and moving in a straight line at constant velocity", "Only at rest", "Only in accelerated motion", "Only in circular motion"],
     0,
     "a = 0 की दोनों स्थितियाँ (विराम और नियत वेग) में F = 0।",
     "F = 0 in both a = 0 situations — rest and constant-velocity straight-line motion."),
]
