# -*- coding: utf-8 -*-
"""P04 (Gravitation, Weight & Pressure) — Part 2: pressure (37) + buoyancy-flotation (37) = 74 tuples.
All items authored with correct_idx=0; rotation happens in gen_p04_questions.py.

T3 pressure            37 = E15/M16/H6
T4 buoyancy-flotation  37 = E14/M17/H6
"""

PART2 = [
    # ================= PRESSURE (37) =================
    # ---- easy (15) ----
    ("pressure", "easy",
     "दाब किसे कहते हैं?",
     "What is pressure?",
     ["एकांक क्षेत्रफल पर लगने वाला अभिलंब बल", "कुल लगने वाला बल", "केवल द्रवों में लगने वाला बल", "वस्तु का कुल भार"],
     ["The normal force acting on unit area", "The total force applied", "A force acting only in liquids", "The total weight of an object"],
     0,
     "दाब = क्षेत्रफल पर बल का घनत्व जैसा — प्रति एकांक क्षेत्रफल बल।",
     "Pressure = force per unit area."),

    ("pressure", "easy",
     "दाब का सूत्र क्या है?",
     "What is the formula for pressure?",
     ["P = F/A", "P = A/F", "P = F×A", "P = F + A"],
     ["P = F/A", "P = A/F", "P = F×A", "P = F + A"],
     0,
     "दाब = बल ÷ क्षेत्रफल।",
     "Pressure = force ÷ area."),

    ("pressure", "easy",
     "दाब का SI मात्रक क्या है?",
     "What is the SI unit of pressure?",
     ["पास्कल (Pa)", "न्यूटन (N)", "जूल (J)", "वाट (W)"],
     ["Pascal (Pa)", "Newton (N)", "Joule (J)", "Watt (W)"],
     0,
     "1 Pa = 1 N/m² — दाब का SI मात्रक पास्कल।",
     "1 Pa = 1 N/m² — the SI unit of pressure is the pascal."),

    ("pressure", "easy",
     "एक पास्कल किसके बराबर होता है?",
     "One pascal equals —",
     ["1 N/m²", "1 N·m", "1 kg/m²", "1 m/N"],
     ["1 N/m²", "1 N·m", "1 kg/m²", "1 m/N"],
     0,
     "1 Pa = 1 न्यूटन प्रति वर्ग मीटर।",
     "1 Pa = 1 newton per square metre."),

    ("pressure", "easy",
     "दाब किन कारकों पर निर्भर करता है?",
     "Pressure depends on which factors?",
     ["बल और क्षेत्रफल", "केवल बल", "केवल क्षेत्रफल", "रंग और आकार"],
     ["Force and area", "Force only", "Area only", "Colour and shape"],
     0,
     "P = F/A — दोनों निर्धारक हैं।",
     "P = F/A — both decide it."),

    ("pressure", "easy",
     "बल समान रखकर क्षेत्रफल घटाएँ तो दाब —",
     "Keeping the force the same, if the area is reduced, the pressure —",
     ["बढ़ता है", "घटता है", "समान रहता है", "शून्य हो जाता है"],
     ["Increases", "Decreases", "Remains the same", "Becomes zero"],
     0,
     "P ∝ 1/A — क्षेत्रफल कम, दाब अधिक।",
     "P ∝ 1/A — smaller area, larger pressure."),

    ("pressure", "easy",
     "द्रव में गहराई बढ़ने के साथ दाब —",
     "As depth in a liquid increases, the pressure —",
     ["बढ़ता है", "घटता है", "समान रहता है", "पहले घटता फिर बढ़ता है"],
     ["Increases", "Decreases", "Stays constant", "First falls then rises"],
     0,
     "ऊपर के द्रव-स्तंभ का भार बढ़ता है — दाब गहराई के साथ बढ़ता है।",
     "The weight of the liquid column above grows — pressure rises with depth."),

    ("pressure", "easy",
     "स्थिर द्रव अपने भीतर दाब किन दिशाओं में लगाता है?",
     "In which directions does a liquid at rest exert pressure inside itself?",
     ["सभी दिशाओं में समान रूप से", "केवल नीचे", "केवल ऊपर", "केवल किनारों पर"],
     ["Equally in all directions", "Only downwards", "Only upwards", "Only on the walls"],
     0,
     "द्रव दाब निर्देश-विहीन होता है — हर दिशा में उतना ही।",
     "Liquid pressure has no preferred direction — the same in every direction."),

    ("pressure", "easy",
     "वायुमंडलीय दाब किसके कारण होता है?",
     "Atmospheric pressure is caused by —",
     ["वायुमंडल की वायु के भार (गुरुत्वाकर्षण)", "सूर्य के प्रकाश से", "चाँद के खिंचाव से", "बादलों के रंग से"],
     ["The weight of the air in the atmosphere (gravitation)", "Sunlight", "The moon's pull", "The colour of clouds"],
     0,
     "हवा का अपना भार है — वही वायुमंडलीय दाब डालता है।",
     "Air itself has weight — that weight creates atmospheric pressure."),

    ("pressure", "easy",
     "नुकीली कील लकड़ी में आसानी से क्यों घुसती है?",
     "Why does a sharp nail enter wood easily?",
     ["नोक का क्षेत्रफल बहुत कम → दाब बहुत अधिक", "कील में बिजली होती है", "लकड़ी नरम होती है", "कील भारी होती है"],
     ["The tip's area is tiny → enormous pressure", "The nail carries electricity", "The wood is soft", "The nail is heavy"],
     0,
     "वही बल छोटे क्षेत्रफल पर — दाब अधिक।",
     "The same force on a tiny area — high pressure."),

    ("pressure", "easy",
     "चौड़े स्कूल-बैग के पट्टे कंधे में क्यों नहीं घुसते?",
     "Why don't the broad straps of a school bag dig into the shoulder?",
     ["चौड़े पट्टे से क्षेत्रफल अधिक → दाब कम", "पट्टे नरम रंग के होते हैं", "बैग हल्का होता है", "कंधा मजबूत होता है"],
     ["Broad straps give more area → less pressure", "The straps are softly coloured", "The bag is light", "The shoulder is strong"],
     0,
     "क्षेत्रफल बढ़ाने से उतने ही बल का दाब घट जाता है।",
     "A larger area spreads the same force into a smaller pressure."),

    ("pressure", "easy",
     "ऊँट रेत में क्यों नहीं धंसता?",
     "Why does a camel not sink into the sand?",
     ["चौड़े पैरों से क्षेत्रफल बड़ा, दाब कम", "ऊँट हल्का होता है", "रेत कठोर होती है", "ऊँट तैरता है"],
     ["Broad feet make a large area and low pressure", "The camel is light", "The sand is hard", "The camel swims"],
     0,
     "भार समान, क्षेत्रफल अधिक — दाब कम — धंसना नहीं।",
     "Same weight over more area — less pressure — no sinking."),

    ("pressure", "easy",
     "चाकू या कैंची की धार तेज़ रखी जाती है — कारण —",
     "Knives and scissors are kept sharp-edged — because —",
     ["कम क्षेत्रफल से अधिक दाब, काटना सरल", "तेज़ धार सुंदर लगती है", "धार भारी बनाती है", "क्षेत्रफल बढ़ता है"],
     ["A small area gives high pressure and easy cutting", "A sharp edge looks beautiful", "The edge adds weight", "The area increases"],
     0,
     "काटने का बल धार के छोटे क्षेत्रफल पर केंद्रित होता है।",
     "The cutting force concentrates on the blade's small edge."),

    ("pressure", "easy",
     "बर्फीली सतह पर स्की के तलवे चौड़े क्यों होते हैं?",
     "Why are skis made broad-bottomed for snowy surfaces?",
     ["चौड़े तल से दाब घटता है, बर्फ में धंसना कम", "चौड़े तल तेज़ चलाते हैं", "बर्फ पिघल जाती है", "स्की हल्की बनती है"],
     ["A broad base lowers the pressure so it sinks less into snow", "Broad bases go faster", "The snow melts away", "The ski becomes light"],
     0,
     "वजन फैल जाता है — दाब कम — बर्फ पर टिके रहना।",
     "The weight spreads out — lower pressure — staying atop the snow."),

    ("pressure", "easy",
     "बल समान रखकर क्षेत्रफल आधा कर दें — दाब —",
     "Keeping the same force, halve the area — the pressure —",
     ["दोगुना हो जाता है", "आधा रह जाता है", "चार गुना", "समान"],
     ["Doubles", "Halves", "Quadruples", "Stays the same"],
     0,
     "P = F/A — A आधा तो P दोगुना।",
     "P = F/A — halve A and P doubles."),

    # ---- medium (16) ----
    ("pressure", "medium",
     "200 N का बल 4 m² क्षेत्रफल पर लगे — दाब —",
     "A force of 200 N acts on an area of 4 m² — the pressure is —",
     ["50 Pa", "800 Pa", "200 Pa", "0.02 Pa"],
     ["50 Pa", "800 Pa", "200 Pa", "0.02 Pa"],
     0,
     "P = 200/4 = 50 Pa।",
     "P = 200/4 = 50 Pa."),

    ("pressure", "medium",
     "500 N बल 5 m² क्षेत्रफल पर — दाब —",
     "A 500 N force on a 5 m² area gives a pressure of —",
     ["100 Pa", "2500 Pa", "50 Pa", "500 Pa"],
     ["100 Pa", "2500 Pa", "50 Pa", "500 Pa"],
     0,
     "P = 500/5 = 100 Pa।",
     "P = 500/5 = 100 Pa."),

    ("pressure", "medium",
     "60 N का बल 0.2 m² क्षेत्रफल पर — दाब —",
     "A 60 N force acts on 0.2 m² — the pressure is —",
     ["300 Pa", "12 Pa", "30 Pa", "120 Pa"],
     ["300 Pa", "12 Pa", "30 Pa", "120 Pa"],
     0,
     "P = 60/0.2 = 300 Pa।",
     "P = 60/0.2 = 300 Pa."),

    ("pressure", "medium",
     "दाब 400 Pa है और क्षेत्रफल 0.5 m² — लगा बल —",
     "The pressure is 400 Pa over an area of 0.5 m² — the force applied is —",
     ["200 N", "800 N", "400 N", "100 N"],
     ["200 N", "800 N", "400 N", "100 N"],
     0,
     "F = P × A = 400 × 0.5 = 200 N।",
     "F = P × A = 400 × 0.5 = 200 N."),

    ("pressure", "medium",
     "500 N बल लगाने पर दाब 1000 Pa आया — क्षेत्रफल —",
     "A 500 N force produces a pressure of 1000 Pa — the area is —",
     ["0.5 m²", "2 m²", "5 m²", "500 m²"],
     ["0.5 m²", "2 m²", "5 m²", "500 m²"],
     0,
     "A = F/P = 500/1000 = 0.5 m²।",
     "A = F/P = 500/1000 = 0.5 m²."),

    ("pressure", "medium",
     "एक ही पात्र में पानी की गहराई तीन गुना कर दें — तल पर दाब —",
     "In the same vessel the water depth is tripled — the pressure at the bottom —",
     ["लगभग तीन गुना", "नौ गुना", "समान", "एक तिहाई"],
     ["About three times", "Nine times", "The same", "One-third"],
     0,
     "द्रव दाब ∝ गहराई — तीन गुना गहराई, तीन गुना दाब।",
     "Liquid pressure ∝ depth — triple depth, triple pressure."),

    ("pressure", "medium",
     "बाँधों की नींव (तल) ऊपर से मोटी क्यों बनाई जाती है?",
     "Why are dams made thicker at the bottom than at the top?",
     ["गहरे पानी का दाब अधिक होता है — मोटी दीवार उसे सहती है", "नीचे पानी ठंडा होता है", "ऊपर मजबूती कम चाहिए", "सौंदर्य के लिए"],
     ["Deep water exerts greater pressure — the thick base bears it", "The water below is cold", "The top needs less strength", "For beauty"],
     0,
     "दाब गहराई के साथ बढ़ता है — तल पर सर्वाधिक।",
     "Pressure grows with depth — greatest at the bottom."),

    ("pressure", "medium",
     "गोताखोर जितना गहरा जाता है, कान पर दबाव —",
     "The deeper a diver goes, the pressure on the ears —",
     ["बढ़ता जाता है", "घटता जाता है", "समान रहता है", "शून्य हो जाता है"],
     ["Keeps increasing", "Keeps decreasing", "Stays the same", "Becomes zero"],
     0,
     "ऊपर जल-स्तंभ लंबा होता जाता है — दाब बढ़ता ही जाता है।",
     "The water column above lengthens — pressure keeps rising."),

    ("pressure", "medium",
     "मकान का पानी टंकी छत पर क्यों रखा जाता है?",
     "Why is a house's water tank placed on the roof?",
     ["ऊँचाई से नलों तक पानी दाब के साथ पहुँचता है", "छत खाली होती है", "टंकी वहाँ सुंदर लगती है", "पानी गरम रहता है"],
     ["The height sends water to the taps with pressure", "The roof is empty", "The tank looks good there", "The water stays warm"],
     0,
     "ऊँची टंकी = बड़ा शिर (height) = अच्छा दाब नलों में।",
     "A high tank gives a big head of pressure at the taps."),

    ("pressure", "medium",
     "भवन की निचली मंज़िल के नल से पानी तेज़ और ऊपरी से धीमा क्यों?",
     "Why does water rush out faster from a ground-floor tap than an upper-floor one?",
     ["निचले नल पर जल-स्तंभ लंबा → दाब अधिक", "ऊपर हवा तेज़ होती है", "निचले नल चौड़े होते हैं", "ऊपर पानी ठंडा होता है"],
     ["A taller water column acts on the lower tap → more pressure", "The wind is stronger upstairs", "Lower taps are wider", "Upstairs water is cold"],
     0,
     "गहराई/ऊँचाई-अंतर अधिक → दाब अधिक → प्रवाह तेज़।",
     "A greater height difference → more pressure → a faster flow."),

    ("pressure", "medium",
     "सॉफ्ट ड्रिंक की पाइप (straw) से पीना संभव किस दाब से होता है?",
     "Drinking through a straw is made possible by which pressure?",
     ["वायुमंडलीय दाब", "जल दाब", "घर्षण", "गुरुत्वीय त्वरण"],
     ["Atmospheric pressure", "Water pressure", "Friction", "Gravitational acceleration"],
     0,
     "सॉर्ब में दाब घटता है → वायुमंडल तरल को ऊपर धकेलता है।",
     "Sucking lowers the pressure inside; the atmosphere pushes the liquid up."),

    ("pressure", "medium",
     "चिम्मी (dropper) में दवा कैसे चढ़ती है?",
     "How does medicine rise into a dropper?",
     ["बल्ब दबाकर छोड़ने पर भीतर दाब घटता है, वायुमंडलीय दाब दवा ऊपर धकेलता है", "दवा ऊपर खिंचती है", "चिम्मी चुंबकीय है", "गुरुत्वाकर्षण दवा ऊपर ले जाता है"],
     ["Releasing the squeezed bulb lowers the inside pressure; atmospheric pressure pushes the liquid up", "The liquid climbs by itself", "The dropper is magnetic", "Gravitation lifts the liquid"],
     0,
     "भीतर कम दाब, बाहर वायुमंडलीय दाब — द्रव ऊपर।",
     "Low pressure inside, atmospheric outside — the liquid rises."),

    ("pressure", "medium",
     "कथन A: द्रव दाब सभी दिशाओं में समान रूप से कार्य करता है। कथन B: द्रव केवल पात्र के तल पर दबाव डालता है। सही विकल्प —",
     "Statement A: liquid pressure acts equally in all directions. Statement B: a liquid presses only on the base of the vessel. The correct option —",
     ["A सही, B गलत", "A गलत, B सही", "दोनों सही", "दोनों गलत"],
     ["A right, B wrong", "A wrong, B right", "Both right", "Both wrong"],
     0,
     "द्रव दीवारों, तल — हर सतह पर, हर दिशा में दबाव डालता है।",
     "A liquid presses on walls and base alike — every direction."),

    ("pressure", "medium",
     "हील वाले जूते कीचड़/घास में अधिक क्यों धंसते हैं?",
     "Why do heeled shoes sink more into mud or grass?",
     ["हील का क्षेत्रफल छोटा → उतने ही भार पर दाब अधिक", "हील भारी धातु की होती है", "कीचड़ हील को पसंद करता है", "जूते नरम होते हैं"],
     ["A heel's small area gives more pressure under the same weight", "Heels are of heavy metal", "The mud likes heels", "The shoes are soft"],
     0,
     "वही भार, छोटा क्षेत्रफल — दाब बढ़ जाता है।",
     "The same weight on a smaller area — higher pressure."),

    ("pressure", "medium",
     "हाइड्रोलिक लिफ्ट छोटे बल से भारी गाड़ी कैसे उठाता है?",
     "How does a hydraulic lift raise a heavy car with a small force?",
     ["द्रव में दाब समान रूप से संचारित होकर बड़े पिस्टन पर बड़ा बल देता है", "द्रव हल्का होता है", "गाड़ी खुद उछलती है", "हवा गाड़ी को खींचती है"],
     ["The pressure transmitted equally through the liquid yields a big force on the big piston", "The liquid is light", "The car jumps itself", "Air pulls the car up"],
     0,
     "छोटे पिस्टन का दाब द्रव में वैसा ही बड़े पिस्टन तक — बड़ा बल।",
     "The small piston's pressure passes undiminished to the large piston — a large force."),

    ("pressure", "medium",
     "समान बल से दो सतहों पर दाब — क्षेत्रफल 1 m² और 5 m² — दाबों का अनुपात —",
     "The same force acts on areas of 1 m² and 5 m² — the ratio of the pressures is —",
     ["5 : 1", "1 : 5", "1 : 1", "25 : 1"],
     ["5 : 1", "1 : 5", "1 : 1", "25 : 1"],
     0,
     "P ∝ 1/A → 1/1 : 1/5 = 5 : 1।",
     "P ∝ 1/A → 1/1 : 1/5 = 5 : 1."),

    # ---- hard (6) ----
    ("pressure", "hard",
     "250 N बल 0.25 m² क्षेत्रफल पर — दाब —",
     "A 250 N force acts on 0.25 m² — the pressure is —",
     ["1000 Pa", "62.5 Pa", "250 Pa", "2500 Pa"],
     ["1000 Pa", "62.5 Pa", "250 Pa", "2500 Pa"],
     0,
     "P = 250/0.25 = 1000 Pa।",
     "P = 250/0.25 = 1000 Pa."),

    ("pressure", "hard",
     "दाब 200 Pa, क्षेत्रफल 4 m² — बल —",
     "Pressure 200 Pa over an area of 4 m² — the force is —",
     ["800 N", "50 N", "200 N", "204 N"],
     ["800 N", "50 N", "200 N", "204 N"],
     0,
     "F = P × A = 200 × 4 = 800 N।",
     "F = P × A = 200 × 4 = 800 N."),

    ("pressure", "hard",
     "600 N का बल पहले 2 m² फिर 0.5 m² क्षेत्रफल पर लगे — दाबों का अनुपात —",
     "A 600 N force acts first on 2 m² then on 0.5 m² — the ratio of the pressures is —",
     ["1 : 4", "4 : 1", "1 : 1", "1 : 2"],
     ["1 : 4", "4 : 1", "1 : 1", "1 : 2"],
     0,
     "P₁ = 300 Pa, P₂ = 1200 Pa → 1 : 4।",
     "P₁ = 300 Pa, P₂ = 1200 Pa → 1 : 4."),

    ("pressure", "hard",
     "एक ही द्रव में 2 m और 6 m की गहराई पर दाबों का अनुपात —",
     "In the same liquid at depths of 2 m and 6 m, the ratio of pressures is —",
     ["1 : 3", "3 : 1", "1 : 9", "1 : 6"],
     ["1 : 3", "3 : 1", "1 : 9", "1 : 6"],
     0,
     "P ∝ h → 2 : 6 = 1 : 3।",
     "P ∝ h → 2 : 6 = 1 : 3."),

    ("pressure", "hard",
     "कथन A: 1 पास्कल = 1 न्यूटन प्रति वर्ग मीटर। कथन B: दाब = क्षेत्रफल/बल। सही विकल्प —",
     "Statement A: 1 pascal = 1 newton per square metre. Statement B: pressure = area/force. The correct option —",
     ["A सही, B गलत (सूत्र उल्टा है)", "A गलत, B सही", "दोनों सही", "दोनों गलत"],
     ["A right, B wrong (the formula is inverted)", "A wrong, B right", "Both right", "Both wrong"],
     0,
     "P = F/A है, A/F नहीं — B उल्टा कथन है।",
     "P = F/A, not A/F — statement B inverts it."),

    ("pressure", "hard",
     "एक ईमानदार तुलना: व्यक्ति A (500 N) 0.01 m² तल पर खड़ा है, व्यक्ति B (1000 N) 0.1 m² तल पर — किसका जमीन पर दाब अधिक?",
     "Compare: person A (500 N) stands on 0.01 m² of sole; person B (1000 N) on 0.1 m² — who exerts more pressure on the ground?",
     ["A (50,000 Pa बनाम B के 10,000 Pa)", "B (भार दोगुना है)", "दोनों समान", "बताया नहीं जा सकता"],
     ["A (50,000 Pa against B's 10,000 Pa)", "B (his weight is double)", "Both equal", "Cannot be determined"],
     0,
     "A: 500/0.01 = 50,000 Pa; B: 1000/0.1 = 10,000 Pa — A का दाब पाँच गुना।",
     "A: 500/0.01 = 50,000 Pa; B: 1000/0.1 = 10,000 Pa — A exerts five times more."),

    # ================= BUOYANCY & FLOTATION (37) =================
    # ---- easy (14) ----
    ("buoyancy-flotation", "easy",
     "उत्प्लावक बल किसे कहते हैं?",
     "What is the buoyant force?",
     ["द्रव द्वारा डूबी वस्तु पर ऊपर की ओर लगाया गया बल", "वस्तु का अपना भार", "वायु का नीचे का बल", "घर्षण बल"],
     ["The upward force a fluid exerts on an immersed object", "The object's own weight", "The downward push of air", "The frictional force"],
     0,
     "द्रव का दबाव नीचे से ऊपर अधिक होता है — शुद्ध बल ऊपर।",
     "Fluid pressure is greater on the underside — a net upward force."),

    ("buoyancy-flotation", "easy",
     "उत्प्लावक बल की दिशा —",
     "The direction of the buoyant force is —",
     ["ऊपर की ओर", "नीचे की ओर", "क्षैतिज", "गति की दिशा में"],
     ["Upwards", "Downwards", "Horizontal", "Along the motion"],
     0,
     "उत्प्लावकता वस्तु को ऊपर धकेलती है।",
     "Buoyancy pushes the object up."),

    ("buoyancy-flotation", "easy",
     "आर्किमिडीज सिद्धांत के अनुसार उत्प्लावक बल किसके बराबर होता है?",
     "According to Archimedes' principle, the buoyant force equals —",
     ["विस्थापित द्रव का भार", "वस्तु का संपूर्ण भार", "वस्तु का द्रव्यमान", "द्रव का संपूर्ण भार"],
     ["The weight of the displaced fluid", "The object's total weight", "The object's mass", "The entire fluid's weight"],
     0,
     "जितना द्रव वस्तु ने हटाया, उतने भार का बल ऊपर।",
     "The weight of the fluid pushed aside comes back as the upward force."),

    ("buoyancy-flotation", "easy",
     "पानी में डूबी वस्तु हल्की क्यों लगती है?",
     "Why does an immersed object feel lighter?",
     ["उत्प्लावक बल भार का कुछ भाग वहन कर लेता है", "वस्तु का द्रव्यमान घटता है", "पानी में g कम हो जाता है", "वस्तु छोटी दिखती है"],
     ["The buoyant force bears part of the weight", "The object's mass decreases", "g becomes less in water", "The object looks smaller"],
     0,
     "अनुभूत भार = वास्तविक भार − उत्प्लावक बल।",
     "Felt weight = true weight − buoyant force."),

    ("buoyancy-flotation", "easy",
     "कोई वस्तु पानी पर तैरती है यदि उसका घनत्व —",
     "An object floats on water if its density is —",
     ["पानी से कम", "पानी से अधिक", "पानी के बराबर", "शून्य"],
     ["Less than water's", "Greater than water's", "Equal to water's", "Zero"],
     0,
     "कम घनत्व → समान भार में अधिक आयतन → पर्याप्त विस्थापन → तैरना।",
     "Lower density → more volume for the same weight → enough displacement to float."),

    ("buoyancy-flotation", "easy",
     "लोहे की छड़ पानी में डूब जाती है क्योंकि —",
     "An iron rod sinks in water because —",
     ["लोहे का घनत्व पानी से बहुत अधिक है", "लोहा चिकना होता है", "लोहा ठंडा होता है", "पानी उसे नहीं पहचानता"],
     ["Iron's density is far greater than water's", "Iron is smooth", "Iron is cold", "Water does not recognise it"],
     0,
     "घनत्व अधिक → पूरा डूबने पर भी उत्प्लावक बल भार से कम।",
     "Higher density → even fully immersed, buoyancy stays below the weight."),

    ("buoyancy-flotation", "easy",
     "लोहे का बना जहाज तैरता है — कारण —",
     "A ship made of iron floats — because —",
     ["इसका औसत घनत्व (खोखलेपन से) पानी से कम हो जाता है", "लोहा पानी से डरता है", "जहाज तेज़ चलता है", "पानी जहाज को उठाता नहीं"],
     ["Its average density (due to hollowness) becomes less than water's", "Iron fears water", "The ship moves fast", "Water does not lift it"],
     0,
     "खोखले भाग हवा से भरे → कुल घनत्व घटता है → तैराव।",
     "The hollow air-filled parts lower the overall density → flotation."),

    ("buoyancy-flotation", "easy",
     "प्लवन के नियम के अनुसार तैरती वस्तु पर उत्प्लावक बल —",
     "By the law of flotation, the buoyant force on a floating object —",
     ["वस्तु के भार के बराबर होता है", "वस्तु के भार से कम होता है", "वस्तु के भार से अधिक होता है", "शून्य होता है"],
     ["Equals the object's weight", "Is less than the object's weight", "Exceeds the object's weight", "Is zero"],
     0,
     "तैरती अवस्था संतुलन की अवस्था है — ऊपर का बल = नीचे का भार।",
     "Floating is equilibrium — the upward force equals the weight."),

    ("buoyancy-flotation", "easy",
     "पानी पर तैरती वस्तु का भार 50 N है — उस पर उत्प्लावक बल —",
     "A floating object weighs 50 N — the buoyant force on it is —",
     ["50 N", "शून्य", "25 N", "500 N"],
     ["50 N", "Zero", "25 N", "500 N"],
     0,
     "तैरना = संतुलन → उत्प्लावक बल = भार = 50 N।",
     "Floating = balance → buoyant force = weight = 50 N."),

    ("buoyancy-flotation", "easy",
     "हीलियम गुब्बारा हवा में ऊपर क्यों जाता है?",
     "Why does a helium balloon rise in air?",
     ["हीलियम का घनत्व हवा से कम — वायु में उत्प्लावकता ऊपर धकेलती है", "गुब्बारा गरम होता है", "हीलियम पक्षी जैसा है", "हवा नीचे की ओर जाती है"],
     ["Helium is less dense than air — buoyancy in air pushes it up", "The balloon is hot", "Helium acts like a bird", "Air moves downwards"],
     0,
     "गैसों में भी उत्प्लावकता होती है — हल्की गैस ऊपर रहती है।",
     "Buoyancy works in gases too — the lighter gas stays on top."),

    ("buoyancy-flotation", "easy",
     "विस्थापित द्रव का भार 20 N है — उत्प्लावक बल —",
     "The displaced fluid weighs 20 N — the buoyant force is —",
     ["20 N", "10 N", "40 N", "पता नहीं चल सकता"],
     ["20 N", "10 N", "40 N", "Cannot be found"],
     0,
     "आर्किमिडीज: उत्प्लावक बल = विस्थापित द्रव का भार = 20 N।",
     "Archimedes: buoyant force = weight of displaced fluid = 20 N."),

    ("buoyancy-flotation", "easy",
     "नाव में और लोग चढ़ने पर वह पहले से —",
     "When more people board a boat, it sits —",
     ["और गहरी धंसती है", "और ऊपर उठती है", "उतनी ही रहती है", "डूब जाती है हमेशा"],
     ["Deeper in the water", "Higher in the water", "Just the same", "Always sinks"],
     0,
     "भार बढ़ा → उतना ही अधिक द्रव विस्थापन चाहिए → गहराई बढ़ती है।",
     "More weight → more displaced fluid needed → it rides lower."),

    ("buoyancy-flotation", "easy",
     "पनडुब्बा (submarine) डूबती-तैरती कैसे रहती है?",
     "How does a submarine keep diving and surfacing?",
     ["अपने टैंकों में पानी भरकर/निकालकर औसत घनत्व बदलकर", "पंखों से तैरती है", "चुंबक से जुड़ती है", "हवा फूँककर भारी होती है"],
     ["By filling/emptying its tanks with water, changing its average density", "It swims with fins", "It clings by magnets", "It gets heavier by blowing air"],
     0,
     "टैंक भरे → घनत्व ↑ → डूबती है; खाली → घनत्व ↓ → तैरती है।",
     "Tanks full → density up → dives; tanks blown → density down → surfaces."),

    ("buoyancy-flotation", "easy",
     "लकड़ी का टुकड़ा पानी पर तैरता है पर लोहे की छड़ नहीं — अंतर का कारण —",
     "A piece of wood floats but an iron rod does not — the cause of the difference is —",
     ["लकड़ी का घनत्व पानी से कम, लोहे का अधिक", "लकड़ी हल्के रंग की होती है", "लोहा चिकना होता है", "पानी लकड़ी पसंद करता है"],
     ["Wood's density is below water's, iron's is above it", "Wood is light-coloured", "Iron is smooth", "Water likes wood"],
     0,
     "प्लवन-डूबन का निर्णय घनत्व-तुलना से होता है।",
     "Float-or-sink is decided purely by the density comparison."),

    # ---- medium (17) ----
    ("buoyancy-flotation", "medium",
     "हवा में 50 N वस्तु पानी में 30 N दिखती है — उत्प्लावक बल —",
     "An object weighs 50 N in air but 30 N in water — the buoyant force is —",
     ["20 N", "50 N", "30 N", "80 N"],
     ["20 N", "50 N", "30 N", "80 N"],
     0,
     "उत्प्लावक बल = 50 − 30 = 20 N।",
     "Buoyant force = 50 − 30 = 20 N."),

    ("buoyancy-flotation", "medium",
     "हवा में 100 N, पानी में 80 N — विस्थापित जल का भार —",
     "100 N in air, 80 N in water — the weight of the displaced water is —",
     ["20 N", "100 N", "80 N", "180 N"],
     ["20 N", "100 N", "80 N", "180 N"],
     0,
     "विस्थापित जल का भार = भार-हानि = 100 − 80 = 20 N।",
     "Displaced water's weight = loss of weight = 100 − 80 = 20 N."),

    ("buoyancy-flotation", "medium",
     "तैरती वस्तु का भार 200 N — विस्थापित द्रव का भार —",
     "A floating object weighs 200 N — the displaced fluid weighs —",
     ["200 N", "100 N", "400 N", "इससे कम"],
     ["200 N", "100 N", "400 N", "Less than this"],
     0,
     "प्लवन का नियम: विस्थापित द्रव-भार = वस्तु-भार।",
     "Law of flotation: displaced fluid's weight = object's weight."),

    ("buoyancy-flotation", "medium",
     "भार 500 N व्यक्ति पानी में खड़ा होकर 400 N अनुभव करता है — उत्प्लावक बल —",
     "A 500 N person standing in water feels 400 N — the buoyant force is —",
     ["100 N", "500 N", "400 N", "900 N"],
     ["100 N", "500 N", "400 N", "900 N"],
     0,
     "500 − 400 = 100 N ऊपर की ओर।",
     "500 − 400 = 100 N upward."),

    ("buoyancy-flotation", "medium",
     "वस्तु का भार 20 N, उत्प्लावक बल 12 N — परिणाम —",
     "An object's weight is 20 N and the buoyant force 12 N — the result —",
     ["शुद्ध 8 N नीचे — वस्तु डूबेगी", "वस्तु तैरेगी", "वस्तु खुद ऊपर आएगी", "वस्तु गायब होगी"],
     ["A net 8 N downwards — it will sink", "It will float", "It will rise by itself", "It will vanish"],
     0,
     "20 − 12 = 8 N नीचे की ओर — डूबना निश्चित।",
     "20 − 12 = 8 N downward — it surely sinks."),

    ("buoyancy-flotation", "medium",
     "वस्तु का भार 20 N, उत्प्लावक बल 25 N — क्या होगा?",
     "Weight 20 N, buoyant force 25 N — what happens?",
     ["शुद्ध 5 N ऊपर — वस्तु ऊपर उठेगी/तैरेगी", "वस्तु डूबेगी", "वस्तु स्थिर रहेगी", "वस्तु पिघल जाएगी"],
     ["A net 5 N upward — it rises/floats", "It sinks", "It stays put", "It melts"],
     0,
     "उत्प्लावक बल > भार → ऊपर की ओर शुद्ध बल।",
     "Buoyancy exceeding weight → a net upward force."),

    ("buoyancy-flotation", "medium",
     "तेल पानी पर क्यों तैरता है?",
     "Why does oil float on water?",
     ["तेल का घनत्व पानी से कम है", "तेल चिपचिपा होता है", "पानी तेल में घुलता है", "तेल गरम होता है"],
     ["Oil's density is less than water's", "Oil is sticky", "Water dissolves in oil", "Oil is hot"],
     0,
     "कम घनत्व वाला द्रव ऊपर रहता है।",
     "The lower-density liquid stays on top."),

    ("buoyancy-flotation", "medium",
     "अंडा सामान्य पानी में डूबता है पर खारे पानी में तैरता है — कारण —",
     "An egg sinks in plain water but floats in salty water — because —",
     ["खारे पानी का घनत्व अधिक → अधिक उत्प्लावक बल", "अंडा नमक पसंद करता है", "नमक अंडे को हल्का करता है", "खारा पानी गाढ़ा दिखता है"],
     ["Salty water is denser → a bigger buoyant force", "The egg likes salt", "Salt makes the egg lighter", "Salty water looks thick"],
     0,
     "घुला नमक जल का घनत्व बढ़ाता है — वही अंडे को ऊपर रखता है।",
     "Dissolved salt raises water's density — that holds the egg up."),

    ("buoyancy-flotation", "medium",
     "मृत सागर में व्यक्ति आसानी से क्यों तैरता है?",
     "Why does a person float easily in the Dead Sea?",
     ["वहाँ का जल अत्यधिक नमकीन (घनत्व अधिक) है — उत्प्लावक बल बड़ा", "वहाँ गहराई कम है", "वहाँ लहरें नहीं हैं", "वहाँ g कम है"],
     ["Its water is extremely salty (high density) — a large buoyant force", "It is shallow there", "There are no waves", "g is lower there"],
     0,
     "उच्च घनत्व का जल शरीर को आसानी से ऊपर रखता है।",
     "The dense water easily holds the body up."),

    ("buoyancy-flotation", "medium",
     "जहाज नदी की तुलना में समुद्र में थोड़ा —",
     "Compared with a river, a ship at sea sits —",
     ["कम डूबता है (समुद्री जल का घनत्व अधिक)", "अधिक डूबता है", "समान डूबता है", "पूरा डूब जाता है"],
     ["A little higher (sea water is denser)", "A little deeper", "Just the same", "Completely sinks"],
     0,
     "घने जल में कम विस्थापन ही पर्याप्त उत्प्लावक बल देता है।",
     "In denser water, less displacement supplies enough buoyancy."),

    ("buoyancy-flotation", "medium",
     "हाइड्रोमीटर किस राशि की माप के लिए है?",
     "A hydrometer is used to measure —",
     ["द्रव का (आपेक्षिक) घनत्व", "द्रव का भार", "द्रव का दाब", "द्रव का ताप"],
     ["A liquid's (relative) density", "A liquid's weight", "A liquid's pressure", "A liquid's temperature"],
     0,
     "हाइड्रोमीटर प्लवन के सिद्धांत पर घनत्व बताता है।",
     "A hydrometer reads density using the flotation principle."),

    ("buoyancy-flotation", "medium",
     "भरी हुई बाल्टी में तैरती वस्तु डालने पर जल स्तर —",
     "A floating object is dropped into a brim-full bucket — the water level —",
     ["बढ़ता है (विस्थापन से), जल बाहर गिरता है", "घटता है", "समान रहता है", "पहले घटता फिर बढ़ता है"],
     ["Rises (displacement) and water spills over", "Falls", "Stays the same", "Falls first then rises"],
     0,
     "वस्तु अपने भार के बराबर जल हटाती है — स्तर बढ़ता है।",
     "The object pushes aside water equal to its weight — the level rises."),

    ("buoyancy-flotation", "medium",
     "कथन A: आर्किमिडीज सिद्धांत पूर्ण या आंशिक रूप से डूबी वस्तुओं पर लागू है। कथन B: उत्प्लावक बल वस्तु के पदार्थ पर नहीं, विस्थापित द्रव पर निर्भर करता है। सही विकल्प —",
     "Statement A: Archimedes' principle applies to fully or partly immersed objects. Statement B: the buoyant force depends on the displaced fluid, not the object's material. The correct option —",
     ["A और B दोनों सही", "केवल A सही", "केवल B सही", "दोनों गलत"],
     ["Both A and B are right", "Only A is right", "Only B is right", "Both are wrong"],
     0,
     "सिद्धांत डूबे भाग पर विस्थापित द्रव के भार से बल देता है — दोनों सही।",
     "The principle keys the force to the displaced fluid — both hold."),

    ("buoyancy-flotation", "medium",
     "पानी में मुट्ठी भींचना/व्यायाम जमीन पर करने से सरल क्यों लगता है?",
     "Why does squeezing a fist or exercising feel easier in water than on ground?",
     ["जल ऊपर का उत्प्लावक बल अनुभूत भार घटाता है", "पानी में मांसपेशियाँ गायब होती हैं", "पानी शरीर को ऊर्जा देता है", "जमीन पर g अधिक है"],
     ["The water's upward buoyancy lowers the felt weight", "Muscles vanish in water", "Water gives the body energy", "g is more on the ground"],
     0,
     "उत्प्लावकता जोड़ों का भार हल्का करती है — चिकित्सीय पूल का आधार।",
     "Buoyancy unloads the joints — the basis of therapy pools."),

    ("buoyancy-flotation", "medium",
     "चादर की गेंद बनाकर डूबाने पर वह डूब जाती है पर उसी चादर की कटोरी पानी पर तैरती है — कारण —",
     "A metal sheet crumpled into a ball sinks, but the same sheet shaped as a bowl floats — because —",
     ["कटोरी के आकार में औसत घनत्व घट जाता है (खोखलापन + हवा)", "गेंद भारी हो जाती है", "कटोरी में चुंबकत्व आ जाता है", "पानी गेंद को नापसंद करता है"],
     ["The bowl shape lowers the average density (hollowness + air)", "The ball becomes heavier", "The bowl turns magnetic", "Water dislikes the ball"],
     0,
     "आकार बदलकर विस्थापन बढ़ता है — उतना उत्प्लावक बल कि भार को संभाले।",
     "The shape raises displacement — enough buoyancy to hold the weight."),

    ("buoyancy-flotation", "medium",
     "डूबती वस्तु का 'पानी में भार' सदा हवा के भार से —",
     "The 'weight in water' of a sinking object is always — than its weight in air —",
     ["कम (उत्प्लावक बल घटाता है)", "अधिक", "बराबर", "दोगुना"],
     ["Less (the buoyant force subtracts)", "More", "Equal", "Double"],
     0,
     "अनुभूत भार = भार − उत्प्लावक बल, जो वास्तविक भार से कम होता है।",
     "Felt weight = weight − buoyancy, which is less than the true weight."),

    ("buoyancy-flotation", "medium",
     "मछली अपने तैरने की सतह (depth) कैसे बदलती है?",
     "How does a fish change its depth in water?",
     ["वायु-कोथ (swim bladder) फुलाकर/सिकोड़कर अपना औसत घनत्व बदलती है", "पूँछ से जमीन खोदती है", "हवा में उड़ती है", "पत्थर निगलती है"],
     ["By inflating/deflating its swim bladder, changing its average density", "It digs the bed with its tail", "It flies into the air", "It swallows stones"],
     0,
     "कोथ भरा → घनत्व ↓ → ऊपर; खाली → घनत्व ↑ → नीचे।",
     "Bladder full → density down → up; empty → density up → down."),

    # ---- hard (6) ----
    ("buoyancy-flotation", "hard",
     "हवा में 49 N वस्तु पानी में 39.2 N — विस्थापित जल का द्रव्यमान (g = 9.8) —",
     "49 N in air, 39.2 N in water — the mass of the displaced water (g = 9.8) is —",
     ["1 kg", "5 kg", "0.8 kg", "4 kg"],
     ["1 kg", "5 kg", "0.8 kg", "4 kg"],
     0,
     "भार-हानि = 49 − 39.2 = 9.8 N → द्रव्यमान = 9.8/9.8 = 1 kg।",
     "Loss of weight = 49 − 39.2 = 9.8 N → mass = 9.8/9.8 = 1 kg."),

    ("buoyancy-flotation", "hard",
     "नाव में बैठा व्यक्ति तालाब में पत्थर डुबो देता है — तालाब का जल स्तर —",
     "From a boat a person drops a stone into the pond — the pond's water level —",
     ["थोड़ा घट जाएगा", "थोड़ा बढ़ जाएगा", "अपरिवर्तित रहेगा", "पहले बढ़ेगा फिर घटेगा"],
     ["Falls slightly", "Rises slightly", "Stays unchanged", "Rises then falls"],
     0,
     "नाव में पत्थर अपना भार विस्थापित करता था; डूबने पर केवल अपना आयतन — विस्थापन घटता है → स्तर घटता है।",
     "In the boat it displaced its weight; sunken it displaces only its volume — less displacement → level falls."),

    ("buoyancy-flotation", "hard",
     "घनत्व 0.8 g/cm³, 1.2 g/cm³, 2.5 g/cm³ और 3.0 g/cm³ की वस्तुओं में पानी (1.0 g/cm³) पर तैरेगी —",
     "Among objects of density 0.8, 1.2, 2.5 and 3.0 g/cm³, the one that floats on water (1.0 g/cm³) is —",
     ["0.8 g/cm³ वाली", "1.2 g/cm³ वाली", "2.5 g/cm³ वाली", "3.0 g/cm³ वाली"],
     ["The 0.8 g/cm³ one", "The 1.2 g/cm³ one", "The 2.5 g/cm³ one", "The 3.0 g/cm³ one"],
     0,
     "केवल 0.8, 1.0 से कम — बाकी सभी पानी से सघन → डूबेंगी।",
     "Only 0.8 lies below 1.0 — the rest are denser than water and sink."),

    ("buoyancy-flotation", "hard",
     "कथन A: जहाज का बनाने वाला लोहा पानी में अकेले डूबता है। कथन B: उसी लोहे का जहाज तैरता है। सही विकल्प —",
     "Statement A: the iron that makes a ship sinks in water alone. Statement B: a ship of that same iron floats. The correct option —",
     ["A और B दोनों सही (आकार से औसत घनत्व बदलता है)", "A सही, B गलत", "A गलत, B सही", "दोनों गलत"],
     ["Both A and B are right (shape changes the average density)", "A right, B wrong", "A wrong, B right", "Both are wrong"],
     0,
     "लोहे का घनत्व जल से अधिक, पर जहाज का औसत घनत्व (खोखलापन) जल से कम।",
     "Iron is denser than water, but the ship's average density (hollowness) is lower."),

    ("buoyancy-flotation", "hard",
     "एक तैरती वस्तु का द्रव में डूबा भाग —",
     "The immersed fraction of a floating object —",
     ["विस्थापित द्रव का भार = वस्तु के कुल भार, इतना होता है कि संतुलन बने", "सदा आधा होता है", "सदा पूरा होता है", "सदा एक तिहाई होता है"],
     ["Is just enough that the displaced fluid's weight equals the object's whole weight", "Is always half", "Is always full", "Is always one-third"],
     0,
     "डूबा भाग तब तक बढ़ता है जब तक उत्प्लावक बल = भार।",
     "The immersed part grows until buoyancy equals the weight."),

    ("buoyancy-flotation", "hard",
     "एक ही वस्तु को पानी में छोड़ा गया — पहले केवल 1/3 डूबी रहती है; द्रव बदलकर घनत्व आधा कर दिया जाए तो वस्तु —",
     "The same object floats with 1/3 immersed in water; if the liquid's density is halved, the object will —",
     ["2/3 डूबेगी (विस्थापन दोगुना)", "1/6 डूबेगी", "पूरी डूब जाएगी निश्चित रूप से", "उतनी ही रहेगी"],
     ["Sit 2/3 immersed (double the displacement)", "Sit 1/6 immersed", "Certainly sink fully", "Stay as before"],
     0,
     "संतुलन: ρल × डूबा-आयतन = वस्तु-घनत्व × कुल आयतन; द्रव-घनत्व आधा → डूबा भाग दोगुना।",
     "Balance: ρ_liq × immersed volume = object's ρV; halving the liquid's density doubles the immersed fraction."),
]
