# -*- coding: utf-8 -*-
"""P04 (Gravitation, Weight & Pressure) — Part 1: gravitation-law (38) + gravity-and-weight (38) = 76 tuples.
All items authored with correct_idx=0; rotation happens in gen_p04_questions.py.

T1 gravitation-law   38 = E16/M16/H6
T2 gravity-and-weight 38 = E15/M16/H7
"""

PART1 = [
    # ================= LAW OF GRAVITATION (38) =================
    # ---- easy (16) ----
    ("gravitation-law", "easy",
     "गुरुत्वाकर्षण किसे कहते हैं?",
     "What is gravitation?",
     ["किन्हीं दो वस्तुओं के बीच लगने वाला आकर्षण बल", "केवल चुंबकों के बीच बल", "केवल विद्युत आवेशों के बीच बल", "वस्तुओं के ठक्कर का बल"],
     ["The attractive force acting between any two objects", "A force only between magnets", "A force only between electric charges", "The force of collision between objects"],
     0,
     "गुरुत्वाकर्षण दो द्रव्यमान वाली वस्तुओं को एक-दूसरे की ओर खींचता है।",
     "Gravitation pulls any two masses towards each other."),

    ("gravitation-law", "easy",
     "गुरुत्वाकर्षण किस प्रकार का बल है?",
     "What kind of force is gravitation?",
     ["आकर्षण बल", "प्रतिकर्षण बल", "कभी आकर्षण, कभी प्रतिकर्षण", "घर्षण बल"],
     ["An attractive force", "A repulsive force", "Sometimes attraction, sometimes repulsion", "A frictional force"],
     0,
     "गुरुत्वाकर्षण सदा आकर्षण करता है, कभी प्रतिकर्षण नहीं।",
     "Gravitation always attracts, never repels."),

    ("gravitation-law", "easy",
     "गुरुत्वाकर्षण को सार्वत्रिक बल क्यों कहा जाता है?",
     "Why is gravitation called a universal force?",
     ["यह किन्हीं भी दो वस्तुओं के बीच, कहीं भी लगता है", "यह केवल पृथ्वी पर लगता है", "यह केवल चाँद पर लगता है", "यह केवल विशाल ग्रहों पर लगता है"],
     ["It acts between any two objects, anywhere", "It acts only on the earth", "It acts only on the moon", "It acts only on giant planets"],
     0,
     "सार्वत्रिक = हर स्थान, हर वस्तु-युग्म पर लागू।",
     "Universal = it applies to every pair of objects, everywhere."),

    ("gravitation-law", "easy",
     "पेड़ से सेब नीचे ही क्यों गिरता है?",
     "Why does an apple fall only downwards from a tree?",
     ["पृथ्वी उसे गुरुत्वाकर्षण से नीचे खींचती है", "हवा उसे नीचे दबाती है", "सेब में बिजली होती है", "पत्ते उसे खींचते हैं"],
     ["The earth pulls it down by gravitation", "The air presses it down", "The apple carries electricity", "The leaves pull it"],
     0,
     "पृथ्वी का गुरुत्वाकर्षण ही सेब को नीचे लाता है।",
     "The earth's gravitation brings the apple down."),

    ("gravitation-law", "easy",
     "पृथ्वी चाँद को किस बल से अपने पास बनाए रखती है?",
     "Which force keeps the moon bound to the earth?",
     ["गुरुत्वाकर्षण बल", "चुंबकीय बल", "विद्युत बल", "घर्षण बल"],
     ["Gravitational force", "Magnetic force", "Electric force", "Frictional force"],
     0,
     "चाँद पृथ्वी की परिक्रमा गुरुत्वाकर्षण ही संभव बनाता है।",
     "Only gravitation makes the moon orbit the earth."),

    ("gravitation-law", "easy",
     "गुरुत्वाकर्षण का सार्वत्रिक नियम किसने दिया?",
     "Who gave the universal law of gravitation?",
     ["न्यूटन", "गैलीलियो", "आइंस्टीन", "कोपरनिकस"],
     ["Newton", "Galileo", "Einstein", "Copernicus"],
     0,
     "न्यूटन ने 1687 में गुरुत्वाकर्षण का सार्वत्रिक नियम प्रतिपादित किया।",
     "Newton formulated the universal law of gravitation in 1687."),

    ("gravitation-law", "easy",
     "दो वस्तुओं का द्रव्यमान बढ़ाने पर उनके बीच गुरुत्वाकर्षण बल —",
     "If the masses of two objects are increased, the gravitational force between them —",
     ["बढ़ता है", "घटता है", "समान रहता है", "शून्य हो जाता है"],
     ["Increases", "Decreases", "Remains the same", "Becomes zero"],
     0,
     "बल ∝ द्रव्यमानों का गुणनफल — द्रव्यमान बढ़ा तो बल बढ़ा।",
     "Force ∝ product of masses — more mass, more force."),

    ("gravitation-law", "easy",
     "दो वस्तुओं के बीच की दूरी बढ़ाने पर गुरुत्वाकर्षण बल —",
     "If the distance between two objects is increased, the gravitational force —",
     ["घटता है", "बढ़ता है", "अपरिवर्तित रहता है", "पहले बढ़ता फिर घटता है"],
     ["Decreases", "Increases", "Stays unchanged", "First increases then decreases"],
     0,
     "बल ∝ 1/दूरी² — दूरी बढ़ी तो बल घटा।",
     "Force ∝ 1/distance² — more distance, less force."),

    ("gravitation-law", "easy",
     "गुरुत्वाकर्षण बल किन दो कारकों पर निर्भर करता है?",
     "On which two factors does the gravitational force depend?",
     ["द्रव्यमान और दूरी", "रंग और आकार", "तापमान और रंग", "गति और दिशा"],
     ["Mass and distance", "Colour and shape", "Temperature and colour", "Speed and direction"],
     0,
     "द्रव्यमान बढ़ाए → बल ↑; दूरी बढ़ाए → बल ↓।",
     "More mass → force up; more distance → force down."),

    ("gravitation-law", "easy",
     "हम जमीन पर स्थिर क्यों बने रहते हैं?",
     "Why do we stay fixed to the ground?",
     ["पृथ्वी का गुरुत्वाकर्षण हमें खींचता है", "हवा हमें दबाती है", "जमीन चिपचिपी है", "हमारा वजन शून्य है"],
     ["The earth's gravitation pulls us", "The air presses on us", "The ground is sticky", "Our weight is zero"],
     0,
     "पृथ्वी हर वस्तु को अपने केंद्र की ओर खींचती है।",
     "The earth pulls every object towards its centre."),

    ("gravitation-law", "easy",
     "चाँद पर खड़ा व्यक्ति वहाँ की मिट्टी पर क्यों टिका रहता है?",
     "Why does a person on the moon stay held to its surface?",
     ["चाँद का अपना गुरुत्वाकर्षण है", "वहाँ हवा बहुत है", "सूट चुंबकीय है", "वहाँ गुरुत्वाकर्षण नहीं है"],
     ["The moon has its own gravitation", "There is plenty of air there", "The suit is magnetic", "There is no gravitation there"],
     0,
     "हर द्रव्यमान गुरुत्वाकर्षण डालता है — छोटा चाँद भी।",
     "Every mass exerts gravitation — the small moon too."),

    ("gravitation-law", "easy",
     "वर्षा की बूँदें नीचे क्यों गिरती हैं?",
     "Why do raindrops fall downwards?",
     ["पृथ्वी का गुरुत्वाकर्षण उन्हें खींचता है", "बादल उन्हें फेंकते हैं", "वे हल्की होती हैं", "हवा उन्हें खींचती है"],
     ["The earth's gravitation pulls them", "The clouds throw them", "They are light", "The wind pulls them"],
     0,
     "गुरुत्वाकर्षण ही जल-बूँदों को धरती पर लाता है।",
     "Gravitation brings the water drops to the earth."),

    ("gravitation-law", "easy",
     "दो वस्तुओं के बीच गुरुत्वाकर्षण बल किस रेखा के अनुदिश कार्य करता है?",
     "Along which line does the gravitational force between two objects act?",
     ["दोनों को जोड़ने वाली रेखा के अनुदिश", "दोनों के लंबवत", "किसी भी दिशा में", "वृत्ताकार पथ में"],
     ["Along the line joining the two", "Perpendicular to both", "In any direction", "Along a circular path"],
     0,
     "आकर्षण दोनों केंद्रों को मिलाने वाली सीधी रेखा में रहता है।",
     "The attraction stays along the straight line joining the two centres."),

    ("gravitation-law", "easy",
     "समान दूरी पर रखी दो वस्तुओं में से अधिक द्रव्यमान वाली वस्तुओं के युग्म पर गुरुत्वाकर्षण बल —",
     "For pairs kept at the same distance, the pair with greater masses experiences a gravitational force that is —",
     ["अधिक होता है", "कम होता है", "समान रहता है", "शून्य होता है"],
     ["Greater", "Smaller", "The same", "Zero"],
     0,
     "बल ∝ m₁×m₂ — बड़े द्रव्यमान-युग्म पर बल बड़ा।",
     "Force ∝ m₁×m₂ — a heavier pair feels a stronger pull."),

    ("gravitation-law", "easy",
     "वायुमंडल पृथ्वी से चिपका क्यों रहता है?",
     "Why does the atmosphere stay attached to the earth?",
     ["पृथ्वी वायु को गुरुत्वाकर्षण से बाँधे रखती है", "वायु चुंबकीय है", "आकाश वायु को रोकता है", "वायु भारी नहीं होती"],
     ["The earth holds the air by gravitation", "The air is magnetic", "The sky stops the air", "Air has no weight"],
     0,
     "गुरुत्वाकर्षण ही वायु के चारों ओर आवरण को बनाए रखता है।",
     "Gravitation alone keeps the blanket of air around the earth."),

    ("gravitation-law", "easy",
     "दो बड़े पिंडों (जैसे पृथ्वी-सूर्य) के बीच गुरुत्वाकर्षण दो छोटी गेंदों की तुलना में —",
     "The gravitation between two huge bodies (say earth-sun) compared with that between two small balls is —",
     ["बहुत अधिक", "बहुत कम", "बराबर", "शून्य"],
     ["Much greater", "Much smaller", "Equal", "Zero"],
     0,
     "विशाल द्रव्यमान → विशाल गुणनफल → अत्यधिक बल।",
     "Huge masses → huge product → an enormous force."),

    # ---- medium (16) ----
    ("gravitation-law", "medium",
     "दो वस्तुओं के बीच दूरी दोगुनी कर दी जाए तो गुरुत्वाकर्षण बल —",
     "If the distance between two objects is doubled, the gravitational force becomes —",
     ["एक चौथाई", "आधा", "दोगुना", "चार गुना"],
     ["One-fourth", "Half", "Double", "Four times"],
     0,
     "F ∝ 1/r² → r दोगुना तो F, (1/2)² = 1/4 गुना।",
     "F ∝ 1/r² → doubling r quarters the force."),

    ("gravitation-law", "medium",
     "एक वस्तु का द्रव्यमान दोगुना कर दें (दूरी वही) — बल —",
     "One object's mass is doubled (same distance) — the force —",
     ["दोगुना हो जाता है", "आधा रह जाता है", "चार गुना", "समान"],
     ["Doubles", "Halves", "Quadruples", "Stays the same"],
     0,
     "F ∝ m₁m₂ — एक द्रव्यमान ×2 → बल ×2।",
     "F ∝ m₁m₂ — doubling one mass doubles the force."),

    ("gravitation-law", "medium",
     "दोनों वस्तुओं के द्रव्यमान दोगुने कर दें — बल —",
     "Both objects' masses are doubled — the force —",
     ["चार गुना हो जाता है", "दोगुना", "आठ गुना", "समान"],
     ["Becomes four times", "Doubles", "Eight times", "Unchanged"],
     0,
     "F ∝ (2m₁)(2m₂) = 4m₁m₂ — बल चार गुना।",
     "F ∝ (2m₁)(2m₂) = 4m₁m₂ — four times the force."),

    ("gravitation-law", "medium",
     "दो वस्तुओं के बीच की दूरी आधी कर दी जाए तो बल —",
     "If the distance between two objects is halved, the force —",
     ["चार गुना हो जाता है", "दोगुना", "आधा", "एक चौथाई"],
     ["Becomes four times", "Doubles", "Halves", "Becomes one-fourth"],
     0,
     "r → r/2, F ∝ 1/r² → F ×4।",
     "r → r/2 with F ∝ 1/r² gives F ×4."),

    ("gravitation-law", "medium",
     "कथन A: गुरुत्वाकर्षण बल द्रव्यमानों के गुणनफल के समानुपाती है। कथन B: यह दूरी के वर्ग के समानुपाती है। सही विकल्प —",
     "Statement A: the gravitational force is proportional to the product of the masses. Statement B: it is proportional to the square of the distance. The correct option —",
     ["A सही, B गलत (दूरी के वर्ग के व्युत्क्रमानुपाती)", "A गलत, B सही", "दोनों सही", "दोनों गलत"],
     ["A right, B wrong (it varies inversely as the square of the distance)", "A wrong, B right", "Both right", "Both wrong"],
     0,
     "समानुपाती गुणनफल से, व्युत्क्रमानुपाती दूरी-वर्ग से।",
     "Proportional to the product; inversely proportional to distance-squared."),

    ("gravitation-law", "medium",
     "दो मित्र एक-दूसरे के पास बैठे हैं पर एक-दूसरे का गुरुत्वाकर्षण खींच अनुभव नहीं करते — क्यों?",
     "Two friends sit close by yet feel no gravitational pull of each other — why?",
     ["द्रव्यमान छोटा होने से बल अत्यंत लघु होता है", "मनुष्यों के बीच गुरुत्वाकर्षण नहीं होता", "दूरी बहुत अधिक है", "कपड़े बल रोकते हैं"],
     ["With small masses the force is extremely tiny", "Gravitation does not act between humans", "The distance is too large", "Clothes block the force"],
     0,
     "बल है, पर मान इतना लघु कि महसूस नहीं होता।",
     "The force exists but is far too small to feel."),

    ("gravitation-law", "medium",
     "समुद्र में ज्वार-भाटा मुख्यतः किसके कारण आते हैं?",
     "What mainly causes tides in the sea?",
     ["चंद्रमा (और सूर्य) का गुरुत्वाकर्षण", "समुद्री हवाओं के कारण", "मछलियों की गति से", "जहाजों के वजन से"],
     ["The gravitation of the moon (and the sun)", "Sea winds", "The motion of fish", "The weight of ships"],
     0,
     "चंद्रमा का गुरुत्वाकर्षण जल को खींचकर ज्वार बनाता है।",
     "The moon's pull lifts the water into tides."),

    ("gravitation-law", "medium",
     "ग्रह सूर्य के चारों ओर निरंतर क्यों घूमते रहते हैं?",
     "Why do the planets keep revolving around the sun?",
     ["सूर्य का गुरुत्वाकर्षण उन्हें बाँधे रखता है", "सूर्य उन्हें धकेलता है", "ग्रह चुंबक हैं", "वायु उन्हें घुमाती है"],
     ["The sun's gravitation keeps them bound", "The sun pushes them away", "The planets are magnets", "Air swirls them around"],
     0,
     "गुरुत्वाकर्षण ही ग्रहों को कक्षा में बाँधता है।",
     "Gravitation alone binds the planets in their orbits."),

    ("gravitation-law", "medium",
     "कथन A: गुरुत्वाकर्षण केवल पृथ्वी से जुड़ा बल है। कथन B: यह किन्हीं दो वस्तुओं के बीच काम करता है। सही विकल्प —",
     "Statement A: gravitation is a force tied only to the earth. Statement B: it acts between any two objects. The correct option —",
     ["A गलत, B सही", "A सही, B गलत", "दोनों सही", "दोनों गलत"],
     ["A wrong, B right", "A right, B wrong", "Both right", "Both wrong"],
     0,
     "गुरुत्वाकर्षण सार्वत्रिक है — हर वस्तु-युग्म पर।",
     "Gravitation is universal — it acts on every pair."),

    ("gravitation-law", "medium",
     "यदि पृथ्वी का गुरुत्वाकर्षण अचानक लुप्त हो जाए, तो वायुमंडल का क्या होगा?",
     "If the earth's gravitation suddenly vanished, what would happen to the atmosphere?",
     ["वायु धीरे-धीरे अंतरिक्ष में फैल जाएगी", "वायु और भी कसकर चिपक जाएगी", "कुछ नहीं होगा", "वायु पानी बन जाएगी"],
     ["The air would gradually escape into space", "The air would cling even more tightly", "Nothing would happen", "The air would turn into water"],
     0,
     "गुरुत्वाकर्षण ही वायु को बाँधता है; वह गया तो आवरण फैल जाएगा।",
     "Gravitation binds the air; without it the envelope would disperse."),

    ("gravitation-law", "medium",
     "दो वस्तुओं A और B के बीच बल F है। A का द्रव्यमान दोगुना और दूरी भी दोगुनी कर दी जाए — नया बल —",
     "The force between two objects A and B is F. A's mass is doubled and the distance too is doubled — the new force is —",
     ["F/2", "2F", "4F", "F"],
     ["F/2", "2F", "4F", "F"],
     0,
     "F′ ∝ 2m/(2r)² = 2/4 = 1/2 → F/2।",
     "F′ ∝ 2m/(2r)² = 2/4 = 1/2 → F/2."),

    ("gravitation-law", "medium",
     "गुरुत्वाकर्षण बल विकर्षण कर सकता है या नहीं?",
     "Can the gravitational force ever repel?",
     ["नहीं, यह सदा आकर्षण है", "हाँ, दूरी बढ़ने पर", "हाँ, रात में", "यह द्रव्यमान पर निर्भर करता है"],
     ["No, it always attracts", "Yes, at large distances", "Yes, at night", "It depends on the mass"],
     0,
     "गुरुत्वाकर्षण कभी विकर्षण नहीं करता — केवल खिंचाव।",
     "Gravitation never repels — it only pulls."),

    ("gravitation-law", "medium",
     "एक ही द्रव्यमान की दो वस्तुओं को पहले 1 m फिर 3 m दूरी पर रखा — बल का नया मान पुराने का —",
     "Two equal masses are kept first 1 m apart and then 3 m apart — the new force is —",
     ["1/9 गुना", "1/3 गुना", "3 गुना", "9 गुना"],
     ["One-ninth", "One-third", "Triple", "Nine times"],
     0,
     "F ∝ 1/r² → r ×3 से F ÷9।",
     "F ∝ 1/r² → tripling r divides the force by 9."),

    ("gravitation-law", "medium",
     "पृथ्वी सेब को जितना खींचती है, सेब पृथ्वी को उतना ही खींचता है — फिर भी हम सेब को गिरते देखते हैं, पृथ्वी को नहीं — कारण —",
     "The earth pulls the apple as hard as the apple pulls the earth — yet we see the apple fall, not the earth — because —",
     ["पृथ्वी का द्रव्यमान अत्यधिक होने से उसका त्वरण नगण्य रह जाता है", "सेब पृथ्वी को खींचता ही नहीं", "पृथ्वी पर सेब का बल नहीं पहुँचता", "यह केवल दिखावा है"],
     ["The earth's huge mass makes its acceleration negligible", "The apple does not pull the earth", "The apple's force never reaches the earth", "It is only an illusion"],
     0,
     "बल समान, पर a = F/m — पृथ्वी का m विशाल → उसका त्वरण अनुभव से बाहर।",
     "The force is equal, but a = F/m — the earth's vast mass makes its acceleration immeasurably small."),

    ("gravitation-law", "medium",
     "ऊपर फेंकी गई वस्तु वापस नीचे क्यों आती है?",
     "Why does an object thrown up come back down?",
     ["पृथ्वी का गुरुत्वाकर्षण उसे लगातार नीचे खींचता है", "हवा उसे नीचे दबाती है", "ऊपर की जगह खत्म हो जाती है", "वस्तु थक जाती है"],
     ["The earth's gravitation keeps pulling it down", "The air presses it down", "The space above runs out", "The object gets tired"],
     0,
     "गुरुत्वाकर्षण नीचे की ओर ही कार्य करता रहता है।",
     "Gravitation keeps acting downwards throughout."),

    ("gravitation-law", "medium",
     "सूर्य और पृथ्वी दोनों एक-दूसरे को खींचते हैं — इस युग्म में बल का आकार —",
     "The sun and the earth pull each other — in this pair the magnitude of the force —",
     ["दोनों पर समान है", "सूर्य पर अधिक है", "पृथ्वी पर अधिक है", "किसी पर नहीं है"],
     ["Is the same on both", "Is greater on the sun", "Is greater on the earth", "Acts on neither"],
     0,
     "गुरुत्वाकर्षण युग्म में दोनों बल बराबर होते हैं; त्वरण द्रव्यमान के कारण भिन्न दिखता है।",
     "Both forces in a gravitational pair are equal; the accelerations differ because of mass."),

    # ---- hard (6) ----
    ("gravitation-law", "hard",
     "दो वस्तुओं के बीच दूरी तीन गुना कर दी जाए तो गुरुत्वाकर्षण बल बन जाएगा —",
     "If the distance between two objects is tripled, the gravitational force becomes —",
     ["F/9", "F/3", "3F", "9F"],
     ["F/9", "F/3", "3F", "9F"],
     0,
     "F ∝ 1/r² → r ×3 ⇒ F ÷ 3² = F/9।",
     "F ∝ 1/r² → r ×3 ⇒ F ÷ 9."),

    ("gravitation-law", "hard",
     "दो द्रव्यमानों m और 2m के बीच दूरी d पर बल F है। यदि द्रव्यमान m, m कर दें और दूरी 2d — नया बल —",
     "Masses m and 2m at distance d feel a force F. If the masses are made m, m and the distance 2d — the new force is —",
     ["F/8", "F/4", "F/2", "F"],
     ["F/8", "F/4", "F/2", "F"],
     0,
     "F ∝ 2m²/d²; F′ ∝ m²/4d² = (1/8)×2m²/d² → F/8।",
     "F ∝ 2m²/d²; F′ ∝ m²/4d² = one-eighth of that → F/8."),

    ("gravitation-law", "hard",
     "दो वस्तुओं के बीच बल 10 N है। दूरी आधी कर दें (द्रव्यमान वही) — नया बल —",
     "The force between two objects is 10 N. The distance is halved (same masses) — the new force is —",
     ["40 N", "20 N", "5 N", "2.5 N"],
     ["40 N", "20 N", "5 N", "2.5 N"],
     0,
     "F ∝ 1/r² → r/2 से F ×4 = 40 N।",
     "F ∝ 1/r² → halving r quadruples F to 40 N."),

    ("gravitation-law", "hard",
     "यदि दूरी d पर बल F हो, तो किस दूरी पर बल F/4 हो जाएगा?",
     "If the force is F at distance d, at what distance does it become F/4?",
     ["2d", "d/2", "4d", "d/4"],
     ["2d", "d/2", "4d", "d/4"],
     0,
     "F ∝ 1/r² → बल चौथाई के लिए r दोगुना = 2d।",
     "F ∝ 1/r² → quarter the force needs twice the distance, 2d."),

    ("gravitation-law", "hard",
     "कथन A: गुरुत्वाकर्षण बल कभी शून्य नहीं होता, चाहे दूरी कितनी भी हो। कथन B: बल बहुत बड़ी दूरी पर नगण्य हो जाता है। सही विकल्प —",
     "Statement A: the gravitational force is never exactly zero, however large the distance. Statement B: at very large distances the force becomes negligible. The correct option —",
     ["A और B दोनों सही", "केवल A सही", "केवल B सही", "दोनों गलत"],
     ["Both A and B are right", "Only A is right", "Only B is right", "Both are wrong"],
     0,
     "1/r² शून्य नहीं होता, पर अत्यधिक r पर मान नगण्य — दोनों कथन सही।",
     "1/r² never reaches zero, yet at huge r the value is negligible — both hold."),

    ("gravitation-law", "hard",
     "दो समान गेंदों के बीच बल F है। एक गेंद का द्रव्यमान तीन गुना और दूरी तीन गुना कर दी जाए — नया बल —",
     "Two identical balls feel a force F. One ball's mass is tripled and the distance too is tripled — the new force is —",
     ["F/3", "3F", "F/9", "F"],
     ["F/3", "3F", "F/9", "F"],
     0,
     "F′ ∝ 3m²/(3r)² = 3/9 = 1/3 → F/3।",
     "F′ ∝ 3m²/(3r)² = 3/9 = 1/3 → F/3."),

    # ================= g & WEIGHT (38) =================
    # ---- easy (15) ----
    ("gravity-and-weight", "easy",
     "पृथ्वी पर गुरुत्वीय त्वरण g का लगभग मान —",
     "The approximate value of the acceleration due to gravity g on the earth is —",
     ["9.8 m/s²", "98 m/s²", "9.8 m/s", "0.98 m/s²"],
     ["9.8 m/s²", "98 m/s²", "9.8 m/s", "0.98 m/s²"],
     0,
     "g ≈ 9.8 m/s² (लगभग 10 m/s² भी प्रयोग होता है)।",
     "g ≈ 9.8 m/s² (about 10 m/s² is also used)."),

    ("gravity-and-weight", "easy",
     "भार किसे कहते हैं?",
     "What is weight?",
     ["पृथ्वी द्वारा वस्तु पर लगाया गया गुरुत्वाकर्षण बल", "वस्तु में भरा पदार्थ", "वस्तु का आयतन", "वस्तु की चाल"],
     ["The gravitational force the earth exerts on the object", "The matter packed in the object", "The object's volume", "The object's speed"],
     0,
     "भार = पृथ्वी का वस्तु पर गुरुत्वीय खिंचाव — यह एक बल है।",
     "Weight = the earth's gravitational pull on the object — a force."),

    ("gravity-and-weight", "easy",
     "भार का सूत्र क्या है?",
     "What is the formula for weight?",
     ["W = mg", "W = m + g", "W = m/g", "W = g/m"],
     ["W = mg", "W = m + g", "W = m/g", "W = g/m"],
     0,
     "भार = द्रव्यमान × गुरुत्वीय त्वरण।",
     "Weight = mass × gravitational acceleration."),

    ("gravity-and-weight", "easy",
     "द्रव्यमान और भार के SI मात्रक क्रमशः हैं —",
     "The SI units of mass and weight respectively are —",
     ["kg और N", "N और kg", "kg और kg", "N और N"],
     ["kg and N", "N and kg", "kg and kg", "N and N"],
     0,
     "द्रव्यमान → किलोग्राम; भार बल है → न्यूटन।",
     "Mass → kilogram; weight is a force → newton."),

    ("gravity-and-weight", "easy",
     "स्थान बदलने पर (पृथ्वी से चाँद पर) द्रव्यमान —",
     "On changing place (earth to moon), the mass —",
     ["वही रहता है", "बढ़ जाता है", "घट जाता है", "शून्य हो जाता है"],
     ["Stays the same", "Increases", "Decreases", "Becomes zero"],
     0,
     "द्रव्यमान पदार्थ की मात्रा है — स्थान से स्वतंत्र।",
     "Mass is the amount of matter — independent of place."),

    ("gravity-and-weight", "easy",
     "चाँद पर वस्तु का भार पृथ्वी की तुलना में लगभग —",
     "On the moon, an object's weight compared with the earth's is about —",
     ["1/6", "1/2", "6 गुना", "समान"],
     ["One-sixth", "Half", "Six times", "The same"],
     0,
     "चाँद का गुरुत्वाकर्षण कमजोर है → भार लगभग छठा भाग।",
     "The moon's weaker pull gives about one-sixth the weight."),

    ("gravity-and-weight", "easy",
     "गुरुत्वीय त्वरण की दिशा हमेशा कहाँ की ओर होती है?",
     "In which direction does the acceleration due to gravity always point?",
     ["पृथ्वी के केंद्र की ओर (नीचे)", "आकाश की ओर", "उत्तर की ओर", "गति की दिशा में"],
     ["Towards the earth's centre (down)", "Towards the sky", "Towards the north", "Along the direction of motion"],
     0,
     "g सदा नीचे, अर्थात् पृथ्वी-केंद्र की ओर रहता है।",
     "g always points down, i.e. towards the earth's centre."),

    ("gravity-and-weight", "easy",
     "स्प्रिंग बैलेंस किसे मापता है?",
     "What does a spring balance measure?",
     ["भार", "द्रव्यमान", "आयतन", "घनत्व"],
     ["Weight", "Mass", "Volume", "Density"],
     0,
     "स्प्रिंग का खिंचाव बल (भार) बताता है।",
     "The spring's stretch indicates the force (weight)."),

    ("gravity-and-weight", "easy",
     "द्रव्यमान मापने की सामान्य युक्ति —",
     "The common device for measuring mass is —",
     ["समता (बीम) तुला", "स्प्रिंग बैलेंस", "थर्मामीटर", "बैरोमीटर"],
     ["A beam (physical) balance", "A spring balance", "A thermometer", "A barometer"],
     0,
     "बीम तुला द्रव्यमान की तुलना करती है, स्थान कोई भी हो।",
     "A beam balance compares mass, whatever the place."),

    ("gravity-and-weight", "easy",
     "पृथ्वी पर 1 kg वस्तु का भार लगभग —",
     "The weight of a 1 kg object on the earth is about —",
     ["9.8 N", "1 N", "98 N", "0.98 N"],
     ["9.8 N", "1 N", "98 N", "0.98 N"],
     0,
     "W = 1 × 9.8 = 9.8 N।",
     "W = 1 × 9.8 = 9.8 N."),

    ("gravity-and-weight", "easy",
     "वायुरहित स्थान में पंख और पत्थर एक साथ गिरते हैं — कारण —",
     "In an air-free space a feather and a stone fall together — because —",
     ["g सभी वस्तुओं के लिए समान है", "पंख भारी हो जाता है", "पत्थर हल्का हो जाता है", "वहाँ गुरुत्वाकर्षण नहीं होता"],
     ["g is the same for all objects", "The feather becomes heavy", "The stone becomes light", "There is no gravitation there"],
     0,
     "वायु-प्रतिरोध हटते ही सभी वस्तुएँ समान g से गिरती हैं।",
     "With air resistance removed, everything falls with the same g."),

    ("gravity-and-weight", "easy",
     "अंतरिक्ष यान में यात्री तैरते दिखते हैं — क्योंकि —",
     "Astronauts appear to float in a spacecraft — because —",
     ["वहाँ भार अनुभव नहीं होता (मुक्त पतन जैसी अवस्था)", "उनका द्रव्यमान शून्य हो जाता है", "गुरुत्वाकर्षण वहाँ काम नहीं करता", "वे हल्के पदार्थ के बने हैं"],
     ["There they feel no weight (a free-fall-like state)", "Their mass becomes zero", "Gravitation does not act there", "They are made of light material"],
     0,
     "यान और यात्री साथ-साथ गिरते हैं — भार-अनुभव शून्य जैसा।",
     "The craft and crew fall together — the felt weight is near zero."),

    ("gravity-and-weight", "easy",
     "g का मान पृथ्वी पर सर्वाधिक कहाँ होता है?",
     "Where on the earth is the value of g greatest?",
     ["ध्रुवों पर", "भूमध्य रेखा पर", "मैदानों में", "पर्वतों की चोटी पर"],
     ["At the poles", "At the equator", "In the plains", "On mountain tops"],
     0,
     "ध्रुवों पर पृथ्वी-त्रिज्या कम → दूरी कम → g अधिक।",
     "The poles are nearer the centre → smaller distance → larger g."),

    ("gravity-and-weight", "easy",
     "किसी वस्तु के भार की दिशा कहाँ की ओर होती है?",
     "In which direction does the weight of an object act?",
     ["पृथ्वी के केंद्र की ओर (नीचे)", "आकाश की ओर", "क्षैतिज दिशा में", "भार की कोई दिशा नहीं"],
     ["Towards the earth's centre (downwards)", "Towards the sky", "Horizontally", "Weight has no direction"],
     0,
     "भार पृथ्वी का गुरुत्वीय खिंचाव है — सदा पृथ्वी-केंद्र की ओर।",
     "Weight is the earth's gravitational pull — always towards the earth's centre."),

    ("gravity-and-weight", "easy",
     "एक ही वस्तु का भार —",
     "The weight of one and the same object —",
     ["स्थान बदलने पर बदल सकता है", "कहीं भी स्थिर रहता है", "कभी नहीं बदलता", "केवल रात में बदलता है"],
     ["Can change from place to place", "Stays fixed everywhere", "Never changes", "Changes only at night"],
     0,
     "W = mg — g स्थान से बदलता है, इसलिए भार भी बदलता है।",
     "W = mg — g varies with place, hence so does weight."),

    # ---- medium (16) ----
    ("gravity-and-weight", "medium",
     "5 kg वस्तु का पृथ्वी पर भार (g = 9.8 m/s²) —",
     "The weight of a 5 kg object on the earth (g = 9.8 m/s²) is —",
     ["49 N", "5 N", "9.8 N", "59 N"],
     ["49 N", "5 N", "9.8 N", "59 N"],
     0,
     "W = 5 × 9.8 = 49 N।",
     "W = 5 × 9.8 = 49 N."),

    ("gravity-and-weight", "medium",
     "10 kg वस्तु का भार लगभग —",
     "The weight of a 10 kg object is about —",
     ["98 N", "10 N", "9.8 N", "980 N"],
     ["98 N", "10 N", "9.8 N", "980 N"],
     0,
     "W = 10 × 9.8 = 98 N।",
     "W = 10 × 9.8 = 98 N."),

    ("gravity-and-weight", "medium",
     "20 kg वस्तु का भार —",
     "The weight of a 20 kg object is —",
     ["196 N", "98 N", "20 N", "1960 N"],
     ["196 N", "98 N", "20 N", "1960 N"],
     0,
     "W = 20 × 9.8 = 196 N।",
     "W = 20 × 9.8 = 196 N."),

    ("gravity-and-weight", "medium",
     "50 kg व्यक्ति का भार (g = 9.8 m/s²) —",
     "The weight of a 50 kg person (g = 9.8 m/s²) is —",
     ["490 N", "50 N", "98 N", "4900 N"],
     ["490 N", "50 N", "98 N", "4900 N"],
     0,
     "W = 50 × 9.8 = 490 N।",
     "W = 50 × 9.8 = 490 N."),

    ("gravity-and-weight", "medium",
     "60 kg यात्री का चाँद पर भार लगभग —",
     "The weight of a 60 kg passenger on the moon is about —",
     ["98 N", "588 N", "60 N", "10 N"],
     ["98 N", "588 N", "60 N", "10 N"],
     0,
     "चाँद पर g ≈ 9.8/6 ≈ 1.63 m/s² → W ≈ 60 × 1.63 ≈ 98 N।",
     "On the moon g ≈ 9.8/6 ≈ 1.63 m/s² → W ≈ 60 × 1.63 ≈ 98 N."),

    ("gravity-and-weight", "medium",
     "किसी वस्तु का भार 98 N है — द्रव्यमान (g = 9.8 m/s²) —",
     "An object weighs 98 N — its mass (g = 9.8 m/s²) is —",
     ["10 kg", "98 kg", "9.8 kg", "49 kg"],
     ["10 kg", "98 kg", "9.8 kg", "49 kg"],
     0,
     "m = W/g = 98/9.8 = 10 kg।",
     "m = W/g = 98/9.8 = 10 kg."),

    ("gravity-and-weight", "medium",
     "भार 49 N वस्तु का द्रव्यमान —",
     "The mass of an object weighing 49 N is —",
     ["5 kg", "49 kg", "4.9 kg", "10 kg"],
     ["5 kg", "49 kg", "4.9 kg", "10 kg"],
     0,
     "m = 49/9.8 = 5 kg।",
     "m = 49/9.8 = 5 kg."),

    ("gravity-and-weight", "medium",
     "भार 29.4 N वस्तु का द्रव्यमान —",
     "The mass of an object weighing 29.4 N is —",
     ["3 kg", "2.94 kg", "30 kg", "6 kg"],
     ["3 kg", "2.94 kg", "30 kg", "6 kg"],
     0,
     "m = 29.4/9.8 = 3 kg।",
     "m = 29.4/9.8 = 3 kg."),

    ("gravity-and-weight", "medium",
     "पृथ्वी पर वस्तु का भार 60 N है — चाँद पर भार लगभग —",
     "An object weighs 60 N on the earth — on the moon it weighs about —",
     ["10 N", "60 N", "360 N", "6 N"],
     ["10 N", "60 N", "360 N", "6 N"],
     0,
     "60 ÷ 6 = 10 N।",
     "60 ÷ 6 = 10 N."),

    ("gravity-and-weight", "medium",
     "एक वस्तु का द्रव्यमान 30 kg है — चाँद पर उसका द्रव्यमान —",
     "An object has a mass of 30 kg — on the moon its mass is —",
     ["30 kg ही", "5 kg", "180 kg", "शून्य"],
     ["Still 30 kg", "5 kg", "180 kg", "Zero"],
     0,
     "द्रव्यमान स्थान से नहीं बदलता — केवल भार बदलता है।",
     "Mass does not change with place — only weight does."),

    ("gravity-and-weight", "medium",
     "ऊपर की ओर फेंकी गई गेंद पर गुरुत्वीय त्वरण की दिशा —",
     "For a ball thrown upwards, the direction of the gravitational acceleration is —",
     ["नीचे की ओर ही (गति की दिशा के बावजूद)", "ऊपर की ओर (गति के साथ)", "क्षैतिज", "शून्य"],
     ["Still downwards (despite the direction of motion)", "Upwards (with the motion)", "Horizontal", "Zero"],
     0,
     "g गति की दिशा से स्वतंत्र है — सदा नीचे।",
     "g is independent of the motion's direction — always downward."),

    ("gravity-and-weight", "medium",
     "कथन A: द्रव्यमान अदिश है। कथन B: भार सदिश है। सही विकल्प —",
     "Statement A: mass is a scalar. Statement B: weight is a vector. The correct option —",
     ["A और B दोनों सही", "केवल A सही", "केवल B सही", "दोनों गलत"],
     ["Both A and B are right", "Only A is right", "Only B is right", "Both are wrong"],
     0,
     "द्रव्यमान केवल परिमाण; भार बल — परिमाण और दिशा।",
     "Mass is magnitude only; weight is a force — magnitude and direction."),

    ("gravity-and-weight", "medium",
     "पहाड़ की चोटी पर वस्तु का भार समुद्र तल की तुलना में —",
     "On a mountain peak an object's weight compared with sea level is —",
     ["थोड़ा कम (g घटता है)", "थोड़ा अधिक", "बिल्कुल समान", "बहुत अधिक"],
     ["Slightly less (g decreases)", "Slightly more", "Exactly the same", "Much greater"],
     0,
     "ऊँचाई से पृथ्वी-केंद्र की दूरी बढ़ती है → g व भार घटते हैं।",
     "Altitude increases the distance from the centre → g and weight fall."),

    ("gravity-and-weight", "medium",
     "ध्रुवों पर भार भूमध्य रेखा की तुलना में अधिक क्यों?",
     "Why is weight greater at the poles than at the equator?",
     ["ध्रुवों पर g अधिक होता है (त्रिज्या कम)", "वहाँ बर्फ का खिंचाव है", "वहाँ द्रव्यमान बढ़ जाता है", "घूर्णन से भार बढ़ता है"],
     ["g is larger at the poles (smaller radius)", "The ice pulls there", "Mass increases there", "Rotation adds weight"],
     0,
     "पृथ्वी ध्रुवों पर थोड़ी चपटी है — दूरी कम, g अधिक, भार अधिक।",
     "The earth is slightly flattened at the poles — less distance, more g, more weight."),

    ("gravity-and-weight", "medium",
     "पानी में पत्थर उठाना हवा में उठाने से सरल क्यों लगता है? (संकेत: इस अध्याय के दायरे में सोचें)",
     "Why does lifting a stone inside water feel easier than in air? (think within this chapter's scope)",
     ["जल ऊपर की ओर उत्प्लावक बल देता है, अनुभूत भार घटता है", "पत्थर पानी में हल्का बन जाता है", "पानी में g शून्य है", "पत्थर का द्रव्यमान घटता है"],
     ["Water gives an upward buoyant force, so the felt weight drops", "The stone becomes light in water", "g is zero in water", "The stone's mass decreases"],
     0,
     "उत्प्लावक बल भार का हिस्सा वहन करता है — उठाना सरल।",
     "The buoyant force carries part of the weight — lifting feels easy."),

    ("gravity-and-weight", "medium",
     "यदि किसी ग्रह पर g = 20 m/s² हो, तो 5 kg वस्तु का वहाँ भार —",
     "If on a planet g = 20 m/s², the weight of a 5 kg object there is —",
     ["100 N", "49 N", "25 N", "4 N"],
     ["100 N", "49 N", "25 N", "4 N"],
     0,
     "W = 5 × 20 = 100 N।",
     "W = 5 × 20 = 100 N."),

    # ---- hard (7) ----
    ("gravity-and-weight", "hard",
     "g = 9.8 m/s² का अर्थ है —",
     "g = 9.8 m/s² means —",
     ["गिरती वस्तु का वेग प्रत्येक सेकंड लगभग 9.8 m/s बढ़ता है", "वस्तु 9.8 m गिरती है", "वेग 9.8 m/s स्थिर रहता है", "भार 9.8 N होता है"],
     ["A falling object's velocity grows by about 9.8 m/s every second", "The object falls 9.8 m", "The velocity stays fixed at 9.8 m/s", "The weight is 9.8 N"],
     0,
     "त्वरण = प्रति सेकंड वेग-वृद्धि — प्रत्येक सेकंड 9.8 m/s की वृद्धि।",
     "Acceleration = velocity gain per second — 9.8 m/s more each second."),

    ("gravity-and-weight", "hard",
     "ऊपर फेंकी गेंद शीर्ष बिंदु पर क्षणभर विराम में रहती है — उस क्षण उस पर g —",
     "A ball thrown up rests momentarily at the highest point — at that instant g on it is —",
     ["9.8 m/s² नीचे की ओर ही", "शून्य", "9.8 m/s² ऊपर की ओर", "अनंत"],
     ["Still 9.8 m/s² downwards", "Zero", "9.8 m/s² upwards", "Infinite"],
     0,
     "वेग शून्य होने पर भी गुरुत्वाकर्षण लगा रहता है — g अपरिवर्तित नीचे।",
     "Even at zero velocity gravitation acts — g stays 9.8 m/s² down."),

    ("gravity-and-weight", "hard",
     "चाँद पर g लगभग 1.63 m/s² है — यह पृथ्वी के g का लगभग —",
     "g on the moon is about 1.63 m/s² — this is roughly —",
     ["एक छठाई", "आधा", "एक तिहाई", "दोगुना"],
     ["One-sixth", "Half", "One-third", "Double"],
     0,
     "9.8/6 ≈ 1.63 — चाँद का g पृथ्वी का लगभग छठा भाग।",
     "9.8/6 ≈ 1.63 — the moon's g is about one-sixth of the earth's."),

    ("gravity-and-weight", "hard",
     "वस्तु का चाँद पर भार 16.3 N है — पृथ्वी पर उसका भार लगभग —",
     "An object weighs 16.3 N on the moon — its weight on the earth is about —",
     ["98 N", "16.3 N", "49 N", "196 N"],
     ["98 N", "16.3 N", "49 N", "196 N"],
     0,
     "पृथ्वी-भार = 6 × चाँद-भार = 6 × 16.3 ≈ 98 N।",
     "Earth-weight = 6 × moon-weight = 6 × 16.3 ≈ 98 N."),

    ("gravity-and-weight", "hard",
     "यदि किसी स्थान पर g शून्य हो जाए, तो वहाँ —",
     "If at some place g became zero, then there —",
     ["भार शून्य होगा पर द्रव्यमान वही रहेगा", "द्रव्यमान भी शून्य हो जाएगा", "भार अनंत हो जाएगा", "द्रव्यमान दोगुना हो जाएगा"],
     ["Weight would be zero but the mass would stay the same", "Mass too would become zero", "Weight would become infinite", "Mass would double"],
     0,
     "W = mg — g = 0 से W = 0; द्रव्यमान पदार्थ का गुण है, बना रहता है।",
     "W = mg — g = 0 gives W = 0; mass is the object's own property and remains."),

    ("gravity-and-weight", "hard",
     "एक ही वस्तु को स्प्रिंग बैलेंस और बीम तुला से चाँद पर तौला गया — सही कथन —",
     "The same object is weighed on the moon with a spring balance and a beam balance — the correct statement is —",
     ["स्प्रिंग बैलेंस का पाठ्यांक घटेगा, बीम तुला वही दिखाएगी", "दोनों घटेंगे", "दोनों बढ़ेंगे", "दोनों अपरिवर्तित रहेंगे"],
     ["The spring balance reading falls; the beam balance shows the same", "Both decrease", "Both increase", "Both stay unchanged"],
     0,
     "स्प्रिंग बैलेंस भार (बल) पढ़ता है → 1/6; बीम तुला द्रव्यमान तुलना करती है → अपरिवर्तित।",
     "A spring balance reads weight → one-sixth; a beam balance compares mass → unchanged."),

    ("gravity-and-weight", "hard",
     "कथन A: भार पृथ्वी के केंद्र की ओर सदिश है। कथन B: भार द्रव्यमान और g के गुणनफल है। सही विकल्प —",
     "Statement A: weight is a vector pointing towards the earth's centre. Statement B: weight is the product of mass and g. The correct option —",
     ["A और B दोनों सही", "केवल A सही", "केवल B सही", "दोनों गलत"],
     ["Both A and B are right", "Only A is right", "Only B is right", "Both are wrong"],
     0,
     "भार नीचे की ओर बल-सदिश है और W = mg से परिभाषित।",
     "Weight is a downward force-vector defined by W = mg."),
]
