# -*- coding: utf-8 -*-
"""P05 (Work, Energy & Power) — Part 1: work (38) + kinetic-energy (38) = 76 tuples.
All items authored with correct_idx=0; rotation happens in gen_p05_questions.py.

T1 work            38 = E16/M16/H6
T2 kinetic-energy  38 = E15/M16/H7
"""

PART1 = [
    # ================= WORK (38) =================
    # ---- easy (16) ----
    ("work", "easy",
     "विज्ञान में कार्य किसे कहते हैं?",
     "What is work in science?",
     ["बल और बल की दिशा में विस्थापन का गुणनफल", "केवल मेहनत करना", "केवल बल लगाना", "समय में बल"],
     ["The product of force and the displacement along the force", "Merely making an effort", "Merely applying a force", "Force times time"],
     0,
     "W = F × s — बल लगे और बल की दिशा में विस्थापन भी हो, तभी भौतिकी में कार्य होता है।",
     "W = F × s — a force must act and a displacement must occur along it for physical work."),

    ("work", "easy",
     "कार्य का SI मात्रक क्या है?",
     "What is the SI unit of work?",
     ["जूल (J)", "न्यूटन (N)", "वाट (W)", "पास्कल (Pa)"],
     ["Joule (J)", "Newton (N)", "Watt (W)", "Pascal (Pa)"],
     0,
     "कार्य का मात्रक जूल है, जो न्यूटन-मीटर के बराबर है।",
     "The unit of work is the joule, equal to a newton-metre."),

    ("work", "easy",
     "एक जूल किसके बराबर होता है?",
     "One joule equals —",
     ["1 न्यूटन बल से 1 मीटर विस्थापन", "1 न्यूटन बल प्रति सेकंड", "1 किलोग्राम × 1 मीटर", "1 वाट × 1 सेकंड का वर्ग"],
     ["A displacement of 1 metre under a 1 newton force", "1 newton of force per second", "1 kilogram × 1 metre", "1 watt × 1 second squared"],
     0,
     "1 J = 1 N × 1 m = 1 N·m।",
     "1 J = 1 N × 1 m = 1 N·m."),

    ("work", "easy",
     "कार्य होने के लिए कौन-सी दो शर्तें आवश्यक हैं?",
     "Which two conditions are necessary for work to be done?",
     ["बल लगे और विस्थापन हो", "केवल बल लगे", "केवल वस्तु गतिमान हो", "बल और समय दोनों बढ़ें"],
     ["A force acts and a displacement occurs", "Only a force acts", "Only the object moves", "Both force and time increase"],
     0,
     "बिना विस्थापन के बल व्यर्थ — कार्य शून्य।",
     "Force without displacement is useless — zero work."),

    ("work", "easy",
     "दीवार को धक्का दिया पर दीवार नहीं हिली — किया गया कार्य —",
     "A wall is pushed but it does not move — the work done is —",
     ["शून्य (विस्थापन शून्य)", "बहुत अधिक", "धक्के के बराबर", "अनंत"],
     ["Zero (the displacement is zero)", "Very large", "Equal to the push", "Infinite"],
     0,
     "s = 0 होने से W = F × 0 = 0 — थकान हो, कार्य नहीं।",
     "With s = 0, W = F × 0 = 0 — fatigue yes, work no."),

    ("work", "easy",
     "जब विस्थापन बल के लंबवत हो, तो उस बल द्वारा किया गया कार्य —",
     "When the displacement is perpendicular to the force, the work done by that force is —",
     ["शून्य", "अधिकतम", "ऋणात्मक", "आधा"],
     ["Zero", "Maximum", "Negative", "Half"],
     0,
     "बल की दिशा में विस्थापन शून्य होने से कार्य शून्य।",
     "No displacement along the force means zero work."),

    ("work", "easy",
     "कार्य किस प्रकार की राशि है?",
     "What kind of quantity is work?",
     ["अदिश (केवल परिमाण)", "सदिश (परिमाण + दिशा)", "न अदिश न सदिश", "सदा शून्य"],
     ["A scalar (magnitude only)", "A vector (magnitude + direction)", "Neither scalar nor vector", "Always zero"],
     0,
     "कार्य का कोई दिशा-मान नहीं होता — यह अदिश राशि है।",
     "Work carries no direction — it is a scalar."),

    ("work", "easy",
     "W = F × s में s का अर्थ है —",
     "In W = F × s, s stands for —",
     ["बल की दिशा में विस्थापन", "कुल दूरी", "लगने वाला समय", "वस्तु का द्रव्यमान"],
     ["The displacement along the direction of the force", "The total distance", "The time taken", "The object's mass"],
     0,
     "सूत्र में केवल बल-दिशा वाला विस्थापन गिना जाता है।",
     "Only the displacement along the force counts in the formula."),

    ("work", "easy",
     "बिना किसी बल के गतिमान वस्तु पर किया गया कार्य —",
     "The work done on an object moving with no force acting is —",
     ["शून्य (F = 0)", "धनात्मक", "ऋणात्मक", "अनंत"],
     ["Zero (F = 0)", "Positive", "Negative", "Infinite"],
     0,
     "F = 0 होने से W = 0 × s = 0।",
     "With F = 0, W = 0 × s = 0."),

    ("work", "easy",
     "1 न्यूटन बल से वस्तु 1 मीटर खिसकी — कार्य —",
     "A 1 newton force moves an object 1 metre — the work done is —",
     ["1 जूल", "0 जूल", "10 जूल", "0.1 जूल"],
     ["1 joule", "0 joule", "10 joule", "0.1 joule"],
     0,
     "W = 1 × 1 = 1 J।",
     "W = 1 × 1 = 1 J."),

    ("work", "easy",
     "जूल किन दो मात्रकों का गुणनफल है?",
     "One joule is the product of which two units?",
     ["न्यूटन × मीटर", "न्यूटन × सेकंड", "किलोग्राम × मीटर", "वाट × सेकंड का वर्ग"],
     ["Newton × metre", "Newton × second", "Kilogram × metre", "Watt × second squared"],
     0,
     "J = N·m — बल-मात्रक और विस्थापन-मात्रक का गुणनफल।",
     "J = N·m — force unit times displacement unit."),

    ("work", "easy",
     "कार्य ऋणात्मक कब होता है?",
     "When is the work negative?",
     ["जब बल व विस्थापन विपरीत दिशाओं में हों", "जब बल व विस्थापन समान दिशा में हों", "जब विस्थापन शून्य हो", "जब बल बहुत बड़ा हो"],
     ["When the force and displacement are in opposite directions", "When the force and displacement are in the same direction", "When the displacement is zero", "When the force is very large"],
     0,
     "विपरीत दिशा में बल कार्य घटाता है — W ऋणात्मक।",
     "A force opposing the motion subtracts — W is negative."),

    ("work", "easy",
     "चलती वस्तु पर घर्षण बल का कार्य होता है —",
     "The work done by friction on a moving object is —",
     ["ऋणात्मक", "धनात्मक", "शून्य", "अनंत"],
     ["Negative", "Positive", "Zero", "Infinite"],
     0,
     "घर्षण गति के विपरीत है — ऋणात्मक कार्य।",
     "Friction opposes the motion — negative work."),

    ("work", "easy",
     "बल और विस्थापन एक ही दिशा में हों तो कार्य —",
     "If the force and displacement are in the same direction, the work is —",
     ["धनात्मक", "ऋणात्मक", "शून्य", "दिशा-निरपेक्ष"],
     ["Positive", "Negative", "Zero", "Direction-free"],
     0,
     "समान दिशा में कार्य जुड़ता है — धनात्मक।",
     "Same direction adds work — positive."),

    ("work", "easy",
     "किसी वस्तु को ऊपर उठाने में किया गया कार्य किसके बराबर होता है?",
     "The work done in lifting an object equals —",
     ["उसकी स्थितिज ऊर्जा में वृद्धि (भार × ऊँचाई)", "उसकी गतिज ऊर्जा", "केवल लगाया बल", "समय × चाल"],
     ["Its gain in potential energy (weight × height)", "Its kinetic energy", "Only the applied force", "Time × speed"],
     0,
     "W = भार × ऊँचाई — वही ऊर्जा स्थितिज रूप में जमा हो जाती है।",
     "W = weight × height — that energy is stored as potential energy."),

    ("work", "easy",
     "1 जूल ऊर्जा से अधिकतम कितना कार्य हो सकता है?",
     "At most how much work can 1 joule of energy do?",
     ["1 जूल (ऊर्जा पूर्णतः कार्य में बदल सकती है)", "अनंत कार्य", "100 जूल", "कोई कार्य नहीं"],
     ["1 joule (energy can convert fully into work)", "Infinite work", "100 joules", "No work at all"],
     0,
     "ऊर्जा कार्य करने की क्षमता है — 1 J ऊर्जा अधिकतम 1 J कार्य कर सकती है।",
     "Energy is the capacity to work — 1 J of energy can do at most 1 J of work."),

    # ---- medium (16) ----
    ("work", "medium",
     "10 N के बल से वस्तु 5 मीटर खिसकती है — कार्य —",
     "A 10 N force moves an object 5 metres — the work done is —",
     ["50 J", "2 J", "15 J", "5 J"],
     ["50 J", "2 J", "15 J", "5 J"],
     0,
     "W = 10 × 5 = 50 J।",
     "W = 10 × 5 = 50 J."),

    ("work", "medium",
     "20 N बल, 3 मीटर विस्थापन — कार्य —",
     "A 20 N force, 3 metres of displacement — the work is —",
     ["60 J", "23 J", "6.7 J", "30 J"],
     ["60 J", "23 J", "6.7 J", "30 J"],
     0,
     "W = 20 × 3 = 60 J।",
     "W = 20 × 3 = 60 J."),

    ("work", "medium",
     "25 N का बल 4 मीटर तक लगा — कार्य —",
     "A 25 N force acts over 4 metres — the work is —",
     ["100 J", "29 J", "6.25 J", "40 J"],
     ["100 J", "29 J", "6.25 J", "40 J"],
     0,
     "W = 25 × 4 = 100 J।",
     "W = 25 × 4 = 100 J."),

    ("work", "medium",
     "8 N बल से 2 मीटर विस्थापन — कार्य —",
     "An 8 N force produces a 2 m displacement — the work is —",
     ["16 J", "4 J", "10 J", "82 J"],
     ["16 J", "4 J", "10 J", "82 J"],
     0,
     "W = 8 × 2 = 16 J।",
     "W = 8 × 2 = 16 J."),

    ("work", "medium",
     "6 N का बल 0.5 मीटर विस्थापन देता है — कार्य —",
     "A 6 N force gives a 0.5 m displacement — the work is —",
     ["3 J", "12 J", "6.5 J", "30 J"],
     ["3 J", "12 J", "6.5 J", "30 J"],
     0,
     "W = 6 × 0.5 = 3 J।",
     "W = 6 × 0.5 = 3 J."),

    ("work", "medium",
     "12 N बल से 6 मीटर चली गाड़ी पर कार्य —",
     "The work done on a cart moved 6 m by a 12 N force is —",
     ["72 J", "2 J", "18 J", "60 J"],
     ["72 J", "2 J", "18 J", "60 J"],
     0,
     "W = 12 × 6 = 72 J।",
     "W = 12 × 6 = 72 J."),

    ("work", "medium",
     "5 मीटर विस्थापन में 100 J कार्य हुआ — औसत बल —",
     "100 J of work is done over a 5 m displacement — the average force is —",
     ["20 N", "500 N", "95 N", "25 N"],
     ["20 N", "500 N", "95 N", "25 N"],
     0,
     "F = W/s = 100/5 = 20 N।",
     "F = W/s = 100/5 = 20 N."),

    ("work", "medium",
     "60 J कार्य 20 N बल से हुआ — विस्थापन —",
     "60 J of work is done by a 20 N force — the displacement is —",
     ["3 m", "1200 m", "40 m", "30 m"],
     ["3 m", "1200 m", "40 m", "30 m"],
     0,
     "s = W/F = 60/20 = 3 m।",
     "s = W/F = 60/20 = 3 m."),

    ("work", "medium",
     "8 मीटर विस्थापन में 40 J कार्य — लगा बल —",
     "40 J of work over an 8 m displacement — the force applied is —",
     ["5 N", "32 N", "48 N", "320 N"],
     ["5 N", "32 N", "48 N", "320 N"],
     0,
     "F = 40/8 = 5 N।",
     "F = 40/8 = 5 N."),

    ("work", "medium",
     "80 J कार्य करने में 16 N बल ने वस्तु को कितनी दूर खिसकाया?",
     "A 16 N force performing 80 J of work moves the object how far?",
     ["5 m", "4 m", "96 m", "64 m"],
     ["5 m", "4 m", "96 m", "64 m"],
     0,
     "s = 80/16 = 5 m।",
     "s = 80/16 = 5 m."),

    ("work", "medium",
     "बक्सा धकेलते रहे पर वह हिला नहीं — 1 मिनट की मेहनत का भौतिक कार्य —",
     "You keep pushing a box but it never moves — the physical work done in 1 minute is —",
     ["शून्य", "बहुत अधिक", "धक्के के समानुपाती", "समय के समानुपाती"],
     ["Zero", "Very large", "Proportional to the push", "Proportional to the time"],
     0,
     "विस्थापन शून्य → W = 0 — यह प्रसिद्ध परीक्षा-जाल है।",
     "Zero displacement → W = 0 — a famous exam trap."),

    ("work", "medium",
     "समान बल में विस्थापन दोगुना कर दें तो कार्य —",
     "Keeping the same force, double the displacement — the work —",
     ["दोगुना हो जाता है", "आधा रह जाता है", "चार गुना", "समान"],
     ["Doubles", "Halves", "Quadruples", "Stays the same"],
     0,
     "W ∝ s (बल स्थिर) — विस्थापन ×2 → कार्य ×2।",
     "W ∝ s (fixed force) — double s, double W."),

    ("work", "medium",
     "समान विस्थापन पर बल आधा कर दें — कार्य —",
     "Halve the force over the same displacement — the work —",
     ["आधा रह जाता है", "दोगुना", "चार गुना", "समान"],
     ["Halves", "Doubles", "Quadruples", "Stays the same"],
     0,
     "W ∝ F — बल आधा तो कार्य आधा।",
     "W ∝ F — half the force, half the work."),

    ("work", "medium",
     "कथन A: केवल बल लगाना कार्य नहीं है। कथन B: विस्थापन के बिना कार्य शून्य है। सही विकल्प —",
     "Statement A: merely applying a force is not work. Statement B: without displacement the work is zero. The correct option —",
     ["A और B दोनों सही", "केवल A सही", "केवल B सही", "दोनों गलत"],
     ["Both A and B are right", "Only A is right", "Only B is right", "Both are wrong"],
     0,
     "दोनों कथन एक ही सिद्धांत के दो पहलू हैं।",
     "Both statements express the same principle."),

    ("work", "medium",
     "गाड़ी पर 500 N का बल 20 मीटर तक लगा — कार्य —",
     "A 500 N force acts on a cart for 20 metres — the work is —",
     ["10,000 J (10 kJ)", "520 J", "25 J", "1000 J"],
     ["10,000 J (10 kJ)", "520 J", "25 J", "1000 J"],
     0,
     "W = 500 × 20 = 10,000 J = 10 kJ।",
     "W = 500 × 20 = 10,000 J = 10 kJ."),

    ("work", "medium",
     "50 N का घर्षण-विरोधी बल और 2 मीटर विस्थापन (गति की विपरीत दिशा में बल) — घर्षण का कार्य —",
     "A 50 N frictional force opposes a 2 m displacement — the work done by friction is —",
     ["−100 J", "+100 J", "शून्य", "25 J"],
     ["−100 J", "+100 J", "Zero", "25 J"],
     0,
     "बल विस्थापन के विपरीत → W = −50 × 2 = −100 J।",
     "Force opposite to displacement → W = −50 × 2 = −100 J."),

    # ---- hard (6) ----
    ("work", "hard",
     "गाड़ी पर आगे का बल 30 N, पीछे घर्षण 10 N, विस्थापन 4 m — नेट कार्य —",
     "A cart feels a 30 N forward force and 10 N backward friction over 4 m — the net work is —",
     ["80 J", "120 J", "40 J", "20 J"],
     ["80 J", "120 J", "40 J", "20 J"],
     0,
     "शुद्ध बल = 30 − 10 = 20 N; W = 20 × 4 = 80 J।",
     "Net force = 30 − 10 = 20 N; W = 20 × 4 = 80 J."),

    ("work", "hard",
     "सिर पर 100 N का बोझ लेकर व्यक्ति क्षैतिज 10 मीटर चलता है — बोझ को सहारा देने वाले ऊर्ध्वाधर बल का कार्य —",
     "A person carries a 100 N load on his head while walking 10 m horizontally — the work done by the carrying force during the horizontal walk is —",
     ["शून्य (बल ऊर्ध्वाधर, विस्थापन क्षैतिज)", "1000 J", "100 J", "10 J"],
     ["Zero (the force is vertical, the displacement horizontal)", "1000 J", "100 J", "10 J"],
     0,
     "ऊर्ध्वाधर बल क्षैतिज विस्थापन पर कार्य नहीं करता — W = 0।",
     "A vertical force does no work on a horizontal displacement — W = 0."),

    ("work", "hard",
     "20 N का बल नीचे की ओर है पर वस्तु 5 मीटर ऊपर जाती है — उस बल का कार्य —",
     "A 20 N force points downward while the object moves 5 m up — the work done by that force is —",
     ["−100 J", "+100 J", "शून्य", "4 J"],
     ["−100 J", "+100 J", "Zero", "4 J"],
     0,
     "विपरीत दिशाएँ → W = −20 × 5 = −100 J।",
     "Opposite directions → W = −20 × 5 = −100 J."),

    ("work", "hard",
     "बल दोगुना और विस्थापन आधा कर दिया जाए — कार्य —",
     "The force is doubled and the displacement halved — the work —",
     ["समान रहता है", "दोगुना", "आधा", "चार गुना"],
     ["Stays the same", "Doubles", "Halves", "Quadruples"],
     0,
     "W = (2F) × (s/2) = F × s — अपरिवर्तित।",
     "W = (2F) × (s/2) = F × s — unchanged."),

    ("work", "hard",
     "0.4 kJ कार्य 8 मीटर विस्थापन में हुआ — बल —",
     "0.4 kJ of work is done over an 8 m displacement — the force is —",
     ["50 N", "3200 N", "20 N", "5 N"],
     ["50 N", "3200 N", "20 N", "5 N"],
     0,
     "0.4 kJ = 400 J; F = 400/8 = 50 N।",
     "0.4 kJ = 400 J; F = 400/8 = 50 N."),

    ("work", "hard",
     "कथन A: घर्षण बल का कार्य सदा ऋणात्मक होता है (गतिमान वस्तु पर)। कथन B: लंबवत बल का कार्य शून्य होता है। सही विकल्प —",
     "Statement A: the work of friction (on a moving object) is always negative. Statement B: the work of a perpendicular force is zero. The correct option —",
     ["A और B दोनों सही", "केवल A सही", "केवल B सही", "दोनों गलत"],
     ["Both A and B are right", "Only A is right", "Only B is right", "Both are wrong"],
     0,
     "घर्षण गति का विरोधी (ऋणात्मक), लंबवत बल की दिशा में विस्थापन शून्य — दोनों सही।",
     "Friction opposes motion (negative); a perpendicular force sees zero displacement along it — both right."),

    # ================= KINETIC ENERGY (38) =================
    # ---- easy (15) ----
    ("kinetic-energy", "easy",
     "गतिज ऊर्जा किसे कहते हैं?",
     "What is kinetic energy?",
     ["गति के कारण वस्तु में धारित ऊर्जा", "ऊँचाई के कारण ऊर्जा", "रंग के कारण ऊर्जा", "समय के कारण ऊर्जा"],
     ["The energy an object has due to its motion", "Energy due to height", "Energy due to colour", "Energy due to time"],
     0,
     "गतिमान वस्तु कार्य कर सकती है — वही गतिज ऊर्जा है।",
     "A moving object can do work — that is kinetic energy."),

    ("kinetic-energy", "easy",
     "गतिज ऊर्जा का सूत्र क्या है?",
     "What is the formula for kinetic energy?",
     ["KE = ½mv²", "KE = mgh", "KE = mv", "KE = ½mv"],
     ["KE = ½mv²", "KE = mgh", "KE = mv", "KE = ½mv"],
     0,
     "गतिज ऊर्जा = आधा × द्रव्यमान × वेग का वर्ग।",
     "Kinetic energy = half × mass × velocity squared."),

    ("kinetic-energy", "easy",
     "विरामावस्था वस्तु की गतिज ऊर्जा —",
     "The kinetic energy of an object at rest is —",
     ["शून्य", "अधिकतम", "द्रव्यमान के बराबर", "अनंत"],
     ["Zero", "Maximum", "Equal to its mass", "Infinite"],
     0,
     "v = 0 → KE = ½m×0 = 0।",
     "v = 0 → KE = ½m×0 = 0."),

    ("kinetic-energy", "easy",
     "गतिज ऊर्जा का SI मात्रक —",
     "The SI unit of kinetic energy is —",
     ["जूल (J)", "वाट (W)", "न्यूटन (N)", "मीटर/सेकंड"],
     ["Joule (J)", "Watt (W)", "Newton (N)", "Metre/second"],
     0,
     "सभी ऊर्जाओं का मात्रक जूल है।",
     "Every form of energy is measured in joules."),

    ("kinetic-energy", "easy",
     "गतिज ऊर्जा किन राशियों पर निर्भर करती है?",
     "On which quantities does kinetic energy depend?",
     ["द्रव्यमान और वेग", "केवल द्रव्यमान", "केवल ऊँचाई", "रंग और आकार"],
     ["Mass and velocity", "Mass only", "Height only", "Colour and shape"],
     0,
     "KE = ½mv² — दोनों निर्धारक हैं।",
     "KE = ½mv² — both decide it."),

    ("kinetic-energy", "easy",
     "द्रव्यमान समान रखकर वेग दोगुना कर दें — गतिज ऊर्जा —",
     "Keeping the mass fixed, double the velocity — the kinetic energy —",
     ["चार गुना हो जाती है", "दोगुनी", "आधी", "समान"],
     ["Becomes four times", "Doubles", "Halves", "Stays the same"],
     0,
     "KE ∝ v² — (2v)² = 4v² → चार गुना।",
     "KE ∝ v² — (2v)² = 4v² → four times."),

    ("kinetic-energy", "easy",
     "वेग आधा हो जाए तो गतिज ऊर्जा —",
     "If the velocity is halved, the kinetic energy —",
     ["एक चौथाई रह जाती है", "आधी", "दोगुनी", "समान"],
     ["Becomes one-fourth", "Halves", "Doubles", "Stays the same"],
     0,
     "(v/2)² = v²/4 → KE एक चौथाई।",
     "(v/2)² = v²/4 → one-fourth the KE."),

    ("kinetic-energy", "easy",
     "वस्तु की चाल बढ़ने पर उसकी गतिज ऊर्जा —",
     "As an object's speed increases, its kinetic energy —",
     ["बढ़ती है", "घटती है", "समान रहती है", "शून्य हो जाती है"],
     ["Increases", "Decreases", "Remains the same", "Becomes zero"],
     0,
     "वेग बढ़ा → v² बढ़ा → KE बढ़ी।",
     "Higher speed → higher v² → higher KE."),

    ("kinetic-energy", "easy",
     "समान वेग से चलती दो वस्तुओं में भारी वस्तु की गतिज ऊर्जा —",
     "Of two objects moving at the same speed, the heavier one's kinetic energy is —",
     ["अधिक", "कम", "बराबर", "शून्य"],
     ["Greater", "Smaller", "Equal", "Zero"],
     0,
     "KE ∝ m — समान v पर अधिक द्रव्यमान = अधिक KE।",
     "KE ∝ m — at the same v, more mass means more KE."),

    ("kinetic-energy", "easy",
     "तेज़ चलती गोली में मुख्य रूप से कौन-सी ऊर्जा होती है?",
     "A fast-moving bullet mainly carries which energy?",
     ["गतिज ऊर्जा", "स्थितिज ऊर्जा", "रासायनिक ऊर्जा", "नाभिकीय ऊर्जा"],
     ["Kinetic energy", "Potential energy", "Chemical energy", "Nuclear energy"],
     0,
     "गोली का वेग ही उसकी ऊर्जा — गतिज।",
     "The bullet's speed is its energy — kinetic."),

    ("kinetic-energy", "easy",
     "बहती हवा और बहता जल किस ऊर्जा के स्रोत हैं?",
     "Moving wind and flowing water are sources of which energy?",
     ["गतिज ऊर्जा", "स्थितिज ऊर्जा", "ऊष्मीय ऊर्जा", "प्रकाश ऊर्जा"],
     ["Kinetic energy", "Potential energy", "Heat energy", "Light energy"],
     0,
     "गति करते द्रव/गैस में गतिज ऊर्जा होती है।",
     "A moving fluid or gas carries kinetic energy."),

    ("kinetic-energy", "easy",
     "गतिज ऊर्जा किस प्रकार की राशि है?",
     "What kind of quantity is kinetic energy?",
     ["अदिश", "सदिश", "न अदिश न सदिश", "सदा ऋणात्मक"],
     ["A scalar", "A vector", "Neither scalar nor vector", "Always negative"],
     0,
     "ऊर्जा की कोई दिशा नहीं — अदिश।",
     "Energy has no direction — a scalar."),

    ("kinetic-energy", "easy",
     "समान द्रव्यमान की वस्तु के वेग 2 m/s और 4 m/s हों — गतिज ऊर्जाओं का अनुपात —",
     "An object of fixed mass has speeds 2 m/s and 4 m/s — the ratio of its kinetic energies is —",
     ["1 : 4", "1 : 2", "2 : 1", "1 : 8"],
     ["1 : 4", "1 : 2", "2 : 1", "1 : 8"],
     0,
     "KE ∝ v² → 2² : 4² = 4 : 16 = 1 : 4।",
     "KE ∝ v² → 2² : 4² = 4 : 16 = 1 : 4."),

    ("kinetic-energy", "easy",
     "पवन चक्की किस ऊर्जा को उपयोगी कार्य में बदलती है?",
     "A windmill converts which energy into useful work?",
     ["चलती हवा की गतिज ऊर्जा", "जल की स्थितिज ऊर्जा", "सूर्य की प्रकाश ऊर्जा", "भोजन की रासायनिक ऊर्जा"],
     ["The kinetic energy of moving air", "The potential energy of water", "The sun's light energy", "The chemical energy of food"],
     0,
     "हवा की गति (गतिज ऊर्जा) पंखुड़ियाँ घुमाती है।",
     "The wind's motion (kinetic energy) turns the blades."),

    ("kinetic-energy", "easy",
     "गतिज ऊर्जा का मान सदा होता है —",
     "The value of kinetic energy is always —",
     ["धनात्मक या शून्य (कभी ऋणात्मक नहीं)", "ऋणात्मक", "अनंत", "एक से कम"],
     ["Positive or zero (never negative)", "Negative", "Infinite", "Less than one"],
     0,
     "v² कभी ऋणात्मक नहीं होता — KE सदा शून्य या धनात्मक।",
     "v² is never negative — KE is zero or positive."),

    # ---- medium (16) ----
    ("kinetic-energy", "medium",
     "2 kg वस्तु 5 m/s से चल रही है — गतिज ऊर्जा —",
     "A 2 kg object moves at 5 m/s — its kinetic energy is —",
     ["25 J", "10 J", "5 J", "50 J"],
     ["25 J", "10 J", "5 J", "50 J"],
     0,
     "KE = ½ × 2 × 5² = 25 J।",
     "KE = ½ × 2 × 5² = 25 J."),

    ("kinetic-energy", "medium",
     "4 kg वस्तु 3 m/s के वेग से — गतिज ऊर्जा —",
     "A 4 kg object at 3 m/s — the kinetic energy is —",
     ["18 J", "12 J", "36 J", "6 J"],
     ["18 J", "12 J", "36 J", "6 J"],
     0,
     "KE = ½ × 4 × 9 = 18 J।",
     "KE = ½ × 4 × 9 = 18 J."),

    ("kinetic-energy", "medium",
     "1 kg पत्थर 10 m/s से फेंका गया — गतिज ऊर्जा —",
     "A 1 kg stone is thrown at 10 m/s — its kinetic energy is —",
     ["50 J", "10 J", "100 J", "5 J"],
     ["50 J", "10 J", "100 J", "5 J"],
     0,
     "KE = ½ × 1 × 100 = 50 J।",
     "KE = ½ × 1 × 100 = 50 J."),

    ("kinetic-energy", "medium",
     "6 kg की गेंद 2 m/s से लुढ़क रही है — उसकी गतिज ऊर्जा —",
     "A 6 kg ball rolls at 2 m/s — its kinetic energy is —",
     ["12 J", "24 J", "6 J", "3 J"],
     ["12 J", "24 J", "6 J", "3 J"],
     0,
     "KE = ½ × 6 × 4 = 12 J।",
     "KE = ½ × 6 × 4 = 12 J."),

    ("kinetic-energy", "medium",
     "10 kg की साइकिल 4 m/s से — गतिज ऊर्जा —",
     "A 10 kg bicycle at 4 m/s — the kinetic energy is —",
     ["80 J", "40 J", "160 J", "20 J"],
     ["80 J", "40 J", "160 J", "20 J"],
     0,
     "KE = ½ × 10 × 16 = 80 J।",
     "KE = ½ × 10 × 16 = 80 J."),

    ("kinetic-energy", "medium",
     "0.5 kg की गेंद 8 m/s से उड़ रही है — गतिज ऊर्जा —",
     "A 0.5 kg ball flies at 8 m/s — the kinetic energy is —",
     ["16 J", "4 J", "32 J", "8 J"],
     ["16 J", "4 J", "32 J", "8 J"],
     0,
     "KE = ½ × 0.5 × 64 = 16 J।",
     "KE = ½ × 0.5 × 64 = 16 J."),

    ("kinetic-energy", "medium",
     "2 kg वस्तु का वेग 5 m/s से बढ़ाकर 10 m/s किया गया — नई गतिज ऊर्जा —",
     "A 2 kg object's speed rises from 5 m/s to 10 m/s — the new kinetic energy is —",
     ["100 J", "50 J", "200 J", "25 J"],
     ["100 J", "50 J", "200 J", "25 J"],
     0,
     "नई KE = ½ × 2 × 10² = 100 J (पुरानी 25 J की चार गुनी)।",
     "New KE = ½ × 2 × 10² = 100 J (four times the old 25 J)."),

    ("kinetic-energy", "medium",
     "द्रव्यमान दोगुना (वेग समान) — गतिज ऊर्जा —",
     "Mass doubled (same velocity) — the kinetic energy —",
     ["दोगुनी", "आधी", "चार गुना", "समान"],
     ["Doubles", "Halves", "Quadruples", "Stays the same"],
     0,
     "KE ∝ m — द्रव्यमान ×2 → KE ×2।",
     "KE ∝ m — double mass, double KE."),

    ("kinetic-energy", "medium",
     "किसी वस्तु की गतिज ऊर्जा 200 J है और वेग 10 m/s — द्रव्यमान —",
     "An object's kinetic energy is 200 J at 10 m/s — its mass is —",
     ["4 kg", "2 kg", "20 kg", "40 kg"],
     ["4 kg", "2 kg", "20 kg", "40 kg"],
     0,
     "m = 2×KE/v² = 400/100 = 4 kg।",
     "m = 2×KE/v² = 400/100 = 4 kg."),

    ("kinetic-energy", "medium",
     "कथन A: गतिज ऊर्जा वेग के वर्ग के समानुपाती है। कथन B: विरामावस्था में गतिज ऊर्जा शून्य होती है। सही विकल्प —",
     "Statement A: kinetic energy is proportional to the square of the velocity. Statement B: at rest the kinetic energy is zero. The correct option —",
     ["A और B दोनों सही", "केवल A सही", "केवल B सही", "दोनों गलत"],
     ["Both A and B are right", "Only A is right", "Only B is right", "Both are wrong"],
     0,
     "½mv² सूत्र दोनों कथनों को सिद्ध करता है।",
     "The ½mv² formula establishes both statements."),

    ("kinetic-energy", "medium",
     "समान गतिज ऊर्जा वाली हल्की व भारी वस्तुओं में किसका वेग अधिक होता है?",
     "Of a light and a heavy object with equal kinetic energies, which has the greater velocity?",
     ["हल्की वस्तु का", "भारी वस्तु का", "दोनों का समान", "कोई नहीं"],
     ["The light one", "The heavy one", "Both the same", "Neither"],
     0,
     "समान KE पर v = √(2KE/m) — m कम तो v अधिक।",
     "At equal KE, v = √(2KE/m) — smaller m, larger v."),

    ("kinetic-energy", "medium",
     "एक ही वेग से चलते ट्रक और साइकिल में किसकी गतिज ऊर्जा अधिक?",
     "A truck and a bicycle move at the same speed — which has more kinetic energy?",
     ["ट्रक की (द्रव्यमान बहुत अधिक)", "साइकिल की", "बराबर", "निर्भर नहीं करता"],
     ["The truck's (far greater mass)", "The bicycle's", "Equal", "It does not depend"],
     0,
     "समान v पर KE द्रव्यमान से — ट्रक विजेता।",
     "At the same v, KE follows mass — the truck wins."),

    ("kinetic-energy", "medium",
     "0.2 kg की गोली 20 m/s से — गतिज ऊर्जा —",
     "A 0.2 kg bullet at 20 m/s — the kinetic energy is —",
     ["40 J", "4 J", "80 J", "20 J"],
     ["40 J", "4 J", "80 J", "20 J"],
     0,
     "KE = ½ × 0.2 × 400 = 40 J।",
     "KE = ½ × 0.2 × 400 = 40 J."),

    ("kinetic-energy", "medium",
     "3 kg वस्तु 4 m/s से दौड़ रही है — गतिज ऊर्जा —",
     "A 3 kg object runs at 4 m/s — the kinetic energy is —",
     ["24 J", "12 J", "48 J", "6 J"],
     ["24 J", "12 J", "48 J", "6 J"],
     0,
     "KE = ½ × 3 × 16 = 24 J।",
     "KE = ½ × 3 × 16 = 24 J."),

    ("kinetic-energy", "medium",
     "5 kg की गेंद 6 m/s से — गतिज ऊर्जा —",
     "A 5 kg ball at 6 m/s — the kinetic energy is —",
     ["90 J", "30 J", "180 J", "60 J"],
     ["90 J", "30 J", "180 J", "60 J"],
     0,
     "KE = ½ × 5 × 36 = 90 J।",
     "KE = ½ × 5 × 36 = 90 J."),

    ("kinetic-energy", "medium",
     "गतिमान वस्तु रुक जाए तो उसकी गतिज ऊर्जा का क्या होता है?",
     "When a moving object stops, what happens to its kinetic energy?",
     ["रूपांतरित हो जाती है (ऊष्मा, ध्वनि आदि में)", "नष्ट हो जाती है", "द्रव्यमान बन जाती है", "रिक्त स्थान में चली जाती है"],
     ["It gets transformed (into heat, sound, etc.)", "It is destroyed", "It turns into mass", "It escapes into vacuum"],
     0,
     "ब्रेक में घर्षण KE को ऊष्मा में बदलता है — ऊर्जा बनी रहती है।",
     "Brake friction converts KE to heat — the energy survives."),

    # ---- hard (7) ----
    ("kinetic-energy", "hard",
     "वेग तीन गुना कर दें — गतिज ऊर्जा —",
     "Triple the velocity — the kinetic energy —",
     ["नौ गुना हो जाती है", "तीन गुना", "छह गुना", "समान"],
     ["Becomes nine times", "Triples", "Six times", "Stays the same"],
     0,
     "(3v)² = 9v² → KE नौ गुना।",
     "(3v)² = 9v² → nine times the KE."),

    ("kinetic-energy", "hard",
     "4 kg वस्तु 5 m/s से चल रही थी; वेग बढ़ाकर 10 m/s किया गया — गतिज ऊर्जा में वृद्धि —",
     "A 4 kg object was moving at 5 m/s; its speed is raised to 10 m/s — the gain in kinetic energy is —",
     ["150 J", "50 J", "200 J", "100 J"],
     ["150 J", "50 J", "200 J", "100 J"],
     0,
     "पुरानी KE = 50 J, नई = 200 J → वृद्धि 150 J।",
     "Old KE = 50 J, new = 200 J → a gain of 150 J."),

    ("kinetic-energy", "hard",
     "द्रव्यमान आधा और वेग दोगुना कर दें — गतिज ऊर्जा —",
     "Halve the mass and double the velocity — the kinetic energy —",
     ["दोगुनी हो जाती है", "आधी", "समान", "चार गुना"],
     ["Doubles", "Halves", "Stays the same", "Quadruples"],
     0,
     "½(m/2)(2v)² = 2 × ½mv² → दोगुनी।",
     "½(m/2)(2v)² = 2 × ½mv² → double."),

    ("kinetic-energy", "hard",
     "किसी वस्तु की गतिज ऊर्जा 100 J है — वेग आधा करने पर नई गतिज ऊर्जा —",
     "An object has 100 J of kinetic energy — halving its velocity gives a new kinetic energy of —",
     ["25 J", "50 J", "100 J", "200 J"],
     ["25 J", "50 J", "100 J", "200 J"],
     0,
     "KE ∝ v² → (½)² = ¼ → 25 J।",
     "KE ∝ v² → (½)² = ¼ → 25 J."),

    ("kinetic-energy", "hard",
     "25 kg वस्तु की गतिज ऊर्जा 800 J है — उसका वेग —",
     "A 25 kg object has 800 J of kinetic energy — its velocity is —",
     ["8 m/s", "32 m/s", "64 m/s", "4 m/s"],
     ["8 m/s", "32 m/s", "64 m/s", "4 m/s"],
     0,
     "v = √(2×800/25) = √64 = 8 m/s।",
     "v = √(2×800/25) = √64 = 8 m/s."),

    ("kinetic-energy", "hard",
     "कथन A: गतिज ऊर्जा सदा धनात्मक होती है। कथन B: वेग की दिशा बदलने पर गतिज ऊर्जा नहीं बदलती। सही विकल्प —",
     "Statement A: kinetic energy is always positive. Statement B: reversing the direction of velocity does not change the kinetic energy. The correct option —",
     ["A और B दोनों सही", "केवल A सही", "केवल B सही", "दोनों गलत"],
     ["Both A and B are right", "Only A is right", "Only B is right", "Both are wrong"],
     0,
     "v² दिशा-निरपेक्ष और धनात्मक — दोनों कथन सही।",
     "v² is direction-free and positive — both statements hold."),

    ("kinetic-energy", "hard",
     "समान गतिज ऊर्जा की दो गेंदें: द्रव्यमान 1 kg और 4 kg — उनके वेगों का अनुपात —",
     "Two balls with equal kinetic energy: masses 1 kg and 4 kg — the ratio of their velocities is —",
     ["2 : 1", "1 : 2", "4 : 1", "1 : 4"],
     ["2 : 1", "1 : 2", "4 : 1", "1 : 4"],
     0,
     "v ∝ 1/√m (समान KE) → v₁ : v₂ = √4 : √1 = 2 : 1।",
     "v ∝ 1/√m (equal KE) → v₁ : v₂ = √4 : √1 = 2 : 1."),
]
