# -*- coding: utf-8 -*-
"""P05 (Work, Energy & Power) — Part 2: potential-energy-conservation (37) + power (37) = 74 tuples.
All items authored with correct_idx=0; rotation happens in gen_p05_questions.py.

T3 potential-energy-conservation  37 = E15/M16/H6
T4 power                          37 = E14/M17/H6
"""

PART2 = [
    # ================= PE & ENERGY CONSERVATION (37) =================
    # ---- easy (15) ----
    ("potential-energy-conservation", "easy",
     "स्थितिज ऊर्जा किसे कहते हैं?",
     "What is potential energy?",
     ["वस्तु की स्थिति या ऊँचाई के कारण धारित ऊर्जा", "गति के कारण ऊर्जा", "रंग के कारण ऊर्जा", "तापमान के कारण ऊर्जा"],
     ["The energy stored due to an object's position or height", "Energy due to motion", "Energy due to colour", "Energy due to temperature"],
     0,
     "ऊँचाई पर रखी वस्तु गिरकर कार्य कर सकती है — यही स्थितिज ऊर्जा है।",
     "An object held high can do work on falling — that stored energy is potential energy."),

    ("potential-energy-conservation", "easy",
     "स्थितिज ऊर्जा का सूत्र क्या है?",
     "What is the formula for potential energy?",
     ["PE = mgh", "PE = ½mv²", "PE = mv", "PE = mg"],
     ["PE = mgh", "PE = ½mv²", "PE = mv", "PE = mg"],
     0,
     "स्थितिज ऊर्जा = द्रव्यमान × g × ऊँचाई।",
     "Potential energy = mass × g × height."),

    ("potential-energy-conservation", "easy",
     "स्थितिज ऊर्जा का SI मात्रक —",
     "The SI unit of potential energy is —",
     ["जूल (J)", "वाट (W)", "न्यूटन-मीटर-सेकंड", "किलोग्राम"],
     ["Joule (J)", "Watt (W)", "Newton-metre-second", "Kilogram"],
     0,
     "प्रत्येक ऊर्जा-रूप का मात्रक जूल ही है।",
     "Every form of energy shares the joule."),

    ("potential-energy-conservation", "easy",
     "धरती पर रखी वस्तु की (धरती को संदर्भ मानकर) स्थितिज ऊर्जा —",
     "Taking the ground as reference, the potential energy of an object lying on it is —",
     ["शून्य (h = 0)", "अधिकतम", "द्रव्यमान के बराबर", "अनंत"],
     ["Zero (h = 0)", "Maximum", "Equal to its mass", "Infinite"],
     0,
     "h = 0 → PE = mg × 0 = 0।",
     "h = 0 → PE = mg × 0 = 0."),

    ("potential-energy-conservation", "easy",
     "ऊँचाई बढ़ने पर स्थितिज ऊर्जा —",
     "As the height increases, the potential energy —",
     ["बढ़ती है", "घटती है", "समान रहती है", "शून्य हो जाती है"],
     ["Increases", "Decreases", "Remains the same", "Becomes zero"],
     0,
     "PE ∝ h — ऊँचाई दोगुनी तो PE दोगुनी।",
     "PE ∝ h — double the height, double the PE."),

    ("potential-energy-conservation", "easy",
     "खींची हुई रबर की पट्टी में कौन-सी ऊर्जा संचित होती है?",
     "Which energy is stored in a stretched rubber band?",
     ["स्थितिज (प्रत्यास्थ) ऊर्जा", "गतिज ऊर्जा", "नाभिकीय ऊर्जा", "प्रकाश ऊर्जा"],
     ["Potential (elastic) energy", "Kinetic energy", "Nuclear energy", "Light energy"],
     0,
     "खिंचाव की स्थिति में ऊर्जा संचित रहती है — स्थितिज रूप।",
     "The stretched state stores energy — a potential form."),

    ("potential-energy-conservation", "easy",
     "ऊर्जा किसे कहते हैं?",
     "What is energy?",
     ["कार्य करने की क्षमता", "केवल बल", "केवल गति", "पदार्थ का रंग"],
     ["The capacity to do work", "Only force", "Only motion", "The colour of matter"],
     0,
     "जितनी ऊर्जा, उतना संभावित कार्य।",
     "As much energy, that much possible work."),

    ("potential-energy-conservation", "easy",
     "ऊर्जा का SI मात्रक क्या है?",
     "What is the SI unit of energy?",
     ["जूल (J)", "न्यूटन (N)", "वाट (W)", "पास्कल (Pa)"],
     ["Joule (J)", "Newton (N)", "Watt (W)", "Pascal (Pa)"],
     0,
     "ऊर्जा और कार्य एक ही मात्रक — जूल — में मापे जाते हैं।",
     "Energy and work share the same unit — the joule."),

    ("potential-energy-conservation", "easy",
     "ऊर्जा संरक्षण का नियम क्या कहता है?",
     "What does the law of conservation of energy state?",
     ["ऊर्जा न बनती है न नष्ट — केवल रूप बदलती है", "ऊर्जा नष्ट हो सकती है", "ऊर्जा सदा बनती रहती है", "ऊर्जा द्रव्यमान में बदलती है"],
     ["Energy is neither created nor destroyed — only transformed", "Energy can be destroyed", "Energy keeps creating itself", "Energy turns into mass"],
     0,
     "कुल ऊर्जा स्थिर रहती है — रूप ही बदलते हैं।",
     "The total energy stays fixed — only its form changes."),

    ("potential-energy-conservation", "easy",
     "गिरती हुई वस्तु में स्थितिज ऊर्जा का रूपांतरण —",
     "In a falling object, the potential energy transforms into —",
     ["गतिज ऊर्जा", "रासायनिक ऊर्जा", "नाभिकीय ऊर्जा", "प्रकाश ऊर्जा"],
     ["Kinetic energy", "Chemical energy", "Nuclear energy", "Light energy"],
     0,
     "गिरने पर ऊँचाई घटती, चाल बढ़ती — PE से KE।",
     "Falling lowers the height and raises the speed — PE to KE."),

    ("potential-energy-conservation", "easy",
     "ऊपर फेंकी गई गेंद ऊपर जाते समय किस रूपांतरण दिखाती है?",
     "A ball thrown upwards shows which transformation while rising?",
     ["गतिज ऊर्जा से स्थितिज ऊर्जा", "स्थितिज से गतिज", "रासायनिक से ऊष्मीय", "प्रकाश से गतिज"],
     ["Kinetic energy into potential energy", "Potential into kinetic", "Chemical into heat", "Light into kinetic"],
     0,
     "चाल घटती, ऊँचाई बढ़ती — KE का PE में रूपांतरण।",
     "Speed falls, height rises — KE converting to PE."),

    ("potential-energy-conservation", "easy",
     "साधारण पेंडुलम के निचले बिंदु पर कौन-सी ऊर्जा सर्वाधिक होती है?",
     "At the lowest point of a simple pendulum, which energy is maximum?",
     ["गतिज ऊर्जा", "स्थितिज ऊर्जा", "रासायनिक ऊर्जा", "शून्य ऊर्जा"],
     ["Kinetic energy", "Potential energy", "Chemical energy", "Zero energy"],
     0,
     "निचले बिंदु पर चाल सर्वाधिक — KE सर्वाधिक।",
     "The speed is greatest at the bottom — maximum KE."),

    ("potential-energy-conservation", "easy",
     "हमारे भोजन में कौन-सी ऊर्जा संचित रहती है?",
     "Which energy is stored in our food?",
     ["रासायनिक ऊर्जा", "गतिज ऊर्जा", "प्रकाश ऊर्जा", "चुंबकीय ऊर्जा"],
     ["Chemical energy", "Kinetic energy", "Light energy", "Magnetic energy"],
     0,
     "भोजन के अणुओं में रासायनिक बंधों में ऊर्जा जमा रहती है।",
     "Energy sits in the chemical bonds of food molecules."),

    ("potential-energy-conservation", "easy",
     "सूर्य से प्राप्त ऊर्जा का मुख्य रूप —",
     "The chief form of energy we receive from the sun is —",
     ["प्रकाश (और ऊष्मा) ऊर्जा", "गतिज ऊर्जा", "ध्वनि ऊर्जा", "चुंबकीय ऊर्जा"],
     ["Light (and heat) energy", "Kinetic energy", "Sound energy", "Magnetic energy"],
     0,
     "सौर ऊर्जा प्रकाश व ऊष्मा के रूप में आती है।",
     "Solar energy arrives as light and heat."),

    ("potential-energy-conservation", "easy",
     "बाँध के ऊँचे जल में मुख्यतः कौन-सी ऊर्जा होती है?",
     "The water high behind a dam mainly holds which energy?",
     ["स्थितिज ऊर्जा", "रासायनिक ऊर्जा", "नाभिकीय ऊर्जा", "ध्वनि ऊर्जा"],
     ["Potential energy", "Chemical energy", "Nuclear energy", "Sound energy"],
     0,
     "ऊँचाई पर जल — स्थितिज ऊर्जा — गिरकर टरबाइन घुमाता है।",
     "Water at height is potential energy — falling, it spins the turbines."),

    # ---- medium (16) ----
    ("potential-energy-conservation", "medium",
     "5 kg वस्तु 2 मीटर ऊँचाई पर (g = 10 m/s²) — स्थितिज ऊर्जा —",
     "A 5 kg object at a height of 2 m (g = 10 m/s²) — its potential energy is —",
     ["100 J", "25 J", "10 J", "50 J"],
     ["100 J", "25 J", "10 J", "50 J"],
     0,
     "PE = 5 × 10 × 2 = 100 J।",
     "PE = 5 × 10 × 2 = 100 J."),

    ("potential-energy-conservation", "medium",
     "10 kg वस्तु 5 मीटर ऊँचाई पर (g = 9.8 m/s²) — स्थितिज ऊर्जा —",
     "A 10 kg object at 5 m height (g = 9.8 m/s²) — the potential energy is —",
     ["490 J", "50 J", "98 J", "980 J"],
     ["490 J", "50 J", "98 J", "980 J"],
     0,
     "PE = 10 × 9.8 × 5 = 490 J।",
     "PE = 10 × 9.8 × 5 = 490 J."),

    ("potential-energy-conservation", "medium",
     "2 kg वस्तु 3 मीटर ऊँचाई पर (g = 9.8) — PE —",
     "A 2 kg object at 3 m (g = 9.8) — the PE is —",
     ["58.8 J", "6 J", "19.6 J", "588 J"],
     ["58.8 J", "6 J", "19.6 J", "588 J"],
     0,
     "PE = 2 × 9.8 × 3 = 58.8 J।",
     "PE = 2 × 9.8 × 3 = 58.8 J."),

    ("potential-energy-conservation", "medium",
     "20 kg बस्ता 1.5 मीटर ऊँचाई पर (g = 10) — स्थितिज ऊर्जा —",
     "A 20 kg bag at 1.5 m height (g = 10) — the potential energy is —",
     ["300 J", "30 J", "200 J", "3000 J"],
     ["300 J", "30 J", "200 J", "3000 J"],
     0,
     "PE = 20 × 10 × 1.5 = 300 J।",
     "PE = 20 × 10 × 1.5 = 300 J."),

    ("potential-energy-conservation", "medium",
     "PE = 196 J, ऊँचाई 4 m, g = 9.8 — द्रव्यमान —",
     "PE = 196 J at a height of 4 m with g = 9.8 — the mass is —",
     ["5 kg", "50 kg", "2 kg", "20 kg"],
     ["5 kg", "50 kg", "2 kg", "20 kg"],
     0,
     "m = PE/(gh) = 196/(9.8 × 4) = 5 kg।",
     "m = PE/(gh) = 196/(9.8 × 4) = 5 kg."),

    ("potential-energy-conservation", "medium",
     "600 J की स्थितिज ऊर्जा, द्रव्यमान 15 kg, g = 10 — ऊँचाई —",
     "A potential energy of 600 J with mass 15 kg and g = 10 — the height is —",
     ["4 m", "40 m", "2 m", "6 m"],
     ["4 m", "40 m", "2 m", "6 m"],
     0,
     "h = PE/(mg) = 600/150 = 4 m।",
     "h = PE/(mg) = 600/150 = 4 m."),

    ("potential-energy-conservation", "medium",
     "ऊँचाई दोगुनी कर दें (द्रव्यमान समान) — स्थितिज ऊर्जा —",
     "Double the height (same mass) — the potential energy —",
     ["दोगुनी", "आधी", "चार गुना", "समान"],
     ["Doubles", "Halves", "Quadruples", "Stays the same"],
     0,
     "PE ∝ h — ऊँचाई ×2 → PE ×2।",
     "PE ∝ h — double height, double PE."),

    ("potential-energy-conservation", "medium",
     "द्रव्यमान आधा कर दें (ऊँचाई समान) — स्थितिज ऊर्जा —",
     "Halve the mass (same height) — the potential energy —",
     ["आधी", "दोगुनी", "चार गुना", "समान"],
     ["Halves", "Doubles", "Quadruples", "Stays the same"],
     0,
     "PE ∝ m — द्रव्यमान आधा तो PE आधी।",
     "PE ∝ m — half the mass, half the PE."),

    ("potential-energy-conservation", "medium",
     "गिरती वस्तु अपनी आधी ऊँचाई पर पहुँची — उस क्षण —",
     "A falling object has reached half its drop — at that instant —",
     ["PE आधी, शेष ऊर्जा गतिज रूप में", "PE पूरी, KE शून्य", "कुल ऊर्जा आधी", "KE शून्य हो गई"],
     ["Half is PE and the rest has become kinetic", "Full PE and zero KE", "The total energy has halved", "The KE has become zero"],
     0,
     "कुल स्थिर; आधी ऊँचाई पर PE आधी — बाकी KE।",
     "The total is fixed; at half height PE is half — the rest is KE."),

    ("potential-energy-conservation", "medium",
     "2 kg वस्तु 5 मीटर से मुक्त गिरी (g = 10) — जमीन से ठीक पहले उसकी गतिज ऊर्जा —",
     "A 2 kg object falls freely from 5 m (g = 10) — its kinetic energy just before hitting the ground is —",
     ["100 J", "20 J", "50 J", "10 J"],
     ["100 J", "20 J", "50 J", "10 J"],
     0,
     "PE = 2 × 10 × 5 = 100 J → पूरी KE में बदल जाती है।",
     "PE = 2 × 10 × 5 = 100 J → fully converted to KE."),

    ("potential-energy-conservation", "medium",
     "कथन A: मुक्त पतन में PE + KE कुल स्थिर रहती है। कथन B: PE और KE अलग-अलग स्थिर रहती हैं। सही विकल्प —",
     "Statement A: in free fall the total PE + KE stays constant. Statement B: PE and KE each stay constant separately. The correct option —",
     ["A सही, B गलत", "A गलत, B सही", "दोनों सही", "दोनों गलत"],
     ["A right, B wrong", "A wrong, B right", "Both right", "Both wrong"],
     0,
     "कुल स्थिर; दोनों आपस में बदलती रहती हैं — B गलत।",
     "The total is fixed while the two keep exchanging — B is wrong."),

    ("potential-energy-conservation", "medium",
     "विद्युत पंखे में ऊर्जा-रूपांतरण —",
     "The energy transformation in an electric fan is —",
     ["विद्युत ऊर्जा से यांत्रिक (गतिज) ऊर्जा", "यांत्रिक से विद्युत", "रासायनिक से प्रकाश", "ऊष्मीय से विद्युत"],
     ["Electrical energy to mechanical (kinetic) energy", "Mechanical to electrical", "Chemical to light", "Heat to electrical"],
     0,
     "मोटर विद्युत लेकर पंखुड़ियाँ घुमाती (गतिज) है।",
     "The motor takes electricity and spins the blades (kinetic)."),

    ("potential-energy-conservation", "medium",
     "विद्युत बल्ब में विद्युत ऊर्जा बदलती है —",
     "In an electric bulb, electrical energy changes into —",
     ["प्रकाश और ऊष्मा ऊर्जा", "केवल गतिज ऊर्जा", "रासायनिक ऊर्जा", "चुंबकीय ऊर्जा"],
     ["Light and heat energy", "Only kinetic energy", "Chemical energy", "Magnetic energy"],
     0,
     "बल्ब प्रकाश देता है और गर्म भी होता है — दोनों रूप।",
     "A bulb gives light and gets hot — both forms."),

    ("potential-energy-conservation", "medium",
     "मोटरगाड़ी का इंजन ईंधन की ऊर्जा को किसमें बदलता है?",
     "A car engine converts the fuel's energy into —",
     ["यांत्रिक (गतिज) ऊर्जा", "प्रकाश ऊर्जा", "चुंबकीय ऊर्जा", "नाभिकीय ऊर्जा"],
     ["Mechanical (kinetic) energy", "Light energy", "Magnetic energy", "Nuclear energy"],
     0,
     "ईंधन की रासायनिक ऊर्जा → इंजन → गाड़ी की गति।",
     "The fuel's chemical energy → engine → the car's motion."),

    ("potential-energy-conservation", "medium",
     "0.5 kg की गेंद 4 मीटर ऊँचाई पर है (g = 10) — स्थितिज ऊर्जा —",
     "A 0.5 kg ball is at 4 m height (g = 10) — the potential energy is —",
     ["20 J", "2 J", "40 J", "5 J"],
     ["20 J", "2 J", "40 J", "5 J"],
     0,
     "PE = 0.5 × 10 × 4 = 20 J।",
     "PE = 0.5 × 10 × 4 = 20 J."),

    ("potential-energy-conservation", "medium",
     "खिंचे धनुष-कमान में तीर चलने तक ऊर्जा-क्रम है —",
     "In a drawn bow, up to the arrow's flight, the energy sequence is —",
     ["स्थितिज (प्रत्यास्थ) ऊर्जा से गतिज ऊर्जा", "गतिज से स्थितिज", "ऊष्मीय से प्रकाश", "विद्युत से रासायनिक"],
     ["Potential (elastic) energy to kinetic energy", "Kinetic to potential", "Heat to light", "Electrical to chemical"],
     0,
     "खिंचाव की स्थितिज ऊर्जा तीर की गतिज ऊर्जा बनती है।",
     "The stretch's potential energy becomes the arrow's kinetic energy."),

    # ---- hard (6) ----
    ("potential-energy-conservation", "hard",
     "10 मीटर से मुक्त गिरती वस्तु की जमीन पर चाल (g = 10, ऊर्जा-संरक्षण से) लगभग —",
     "The speed of an object dropped freely from 10 m on reaching the ground (g = 10, via energy conservation) is about —",
     ["14.14 m/s", "10 m/s", "100 m/s", "20 m/s"],
     ["14.14 m/s", "10 m/s", "100 m/s", "20 m/s"],
     0,
     "mgh = ½mv² → v = √(2 × 10 × 10) = √200 ≈ 14.14 m/s।",
     "mgh = ½mv² → v = √(2 × 10 × 10) = √200 ≈ 14.14 m/s."),

    ("potential-energy-conservation", "hard",
     "3 kg वस्तु 10 मीटर ऊँचाई से गिरी (g = 10) — जमीन पर उसकी गतिज ऊर्जा —",
     "A 3 kg object falls from 10 m (g = 10) — its kinetic energy at the ground is —",
     ["300 J", "30 J", "3000 J", "150 J"],
     ["300 J", "30 J", "3000 J", "150 J"],
     0,
     "KE = PE = 3 × 10 × 10 = 300 J।",
     "KE = PE = 3 × 10 × 10 = 300 J."),

    ("potential-energy-conservation", "hard",
     "गेंद को ऊपर फेंका; शीर्ष पर उसका वेग क्षणभर शून्य — उस क्षण —",
     "A ball is thrown up; at the top its velocity is momentarily zero — at that instant —",
     ["KE शून्य, PE अधिकतम", "KE अधिकतम, PE शून्य", "दोनों शून्य", "दोनों अधिकतम"],
     ["KE is zero and PE is maximum", "KE is maximum and PE zero", "Both zero", "Both maximum"],
     0,
     "चाल शून्य → KE शून्य; ऊँचाई सर्वाधिक → PE चरम।",
     "Zero speed → zero KE; greatest height → peak PE."),

    ("potential-energy-conservation", "hard",
     "द्रव्यमान दोगुना और ऊँचाई आधी कर दें — स्थितिज ऊर्जा —",
     "Double the mass and halve the height — the potential energy —",
     ["समान रहती है", "दोगुनी", "आधी", "चार गुना"],
     ["Stays the same", "Doubles", "Halves", "Quadruples"],
     0,
     "PE = (2m) × g × (h/2) = mgh — अपरिवर्तित।",
     "PE = (2m) × g × (h/2) = mgh — unchanged."),

    ("potential-energy-conservation", "hard",
     "कथन A: घर्षण रहित पतन में कुल ऊर्जा जूल में स्थिर रहती है। कथन B: घर्षण होने पर ऊर्जा नष्ट हो जाती है। सही विकल्प —",
     "Statement A: in frictionless fall the total energy in joules stays constant. Statement B: with friction present, the energy is destroyed. The correct option —",
     ["A सही, B गलत (ऊर्जा ऊष्मा में रूपांतरित होती है)", "A गलत, B सही", "दोनों सही", "दोनों गलत"],
     ["A right, B wrong (the energy transforms into heat)", "A wrong, B right", "Both right", "Both wrong"],
     0,
     "घर्षण भी ऊर्जा को ऊष्मा रूप में बदलता है — नष्ट नहीं करता।",
     "Friction too merely converts energy into heat — it destroys nothing."),

    ("potential-energy-conservation", "hard",
     "मिट्टी में धंसकर रुकी गिरती वस्तु की 100 J स्थितिज ऊर्जा का अंतिम गंतव्य —",
     "A falling object with 100 J of potential energy stops by plunging into soil — the final destination of that energy is —",
     ["ऊष्मा और ध्वनि ऊर्जा के रूप में", "नष्ट", "द्रव्यमान में परिवर्तित", "वापस ऊपर चली जाती है"],
     ["Into heat and sound energy", "Destroyed", "Converted into mass", "It climbs back up"],
     0,
     "धंसने में घर्षण व संपीड़न — ऊर्जा ऊष्मा/ध्वनि बनती है, संरक्षण बना रहता है।",
     "Friction and compression during the plunge turn energy into heat/sound — conservation holds."),

    # ================= POWER (37) =================
    # ---- easy (14) ----
    ("power", "easy",
     "शक्ति किसे कहते हैं?",
     "What is power?",
     ["कार्य करने की दर (प्रति सेकंड कार्य)", "कुल किया गया कार्य", "कुल ऊर्जा", "लगाया गया बल"],
     ["The rate of doing work (work per second)", "The total work done", "The total energy", "The force applied"],
     0,
     "शक्ति बताती है कि कितनी तेज़ी से कार्य हुआ।",
     "Power tells how fast the work was done."),

    ("power", "easy",
     "शक्ति का सूत्र क्या है?",
     "What is the formula for power?",
     ["P = W/t", "P = W × t", "P = t/W", "P = W + t"],
     ["P = W/t", "P = W × t", "P = t/W", "P = W + t"],
     0,
     "शक्ति = कार्य ÷ समय।",
     "Power = work ÷ time."),

    ("power", "easy",
     "शक्ति का SI मात्रक क्या है?",
     "What is the SI unit of power?",
     ["वाट (W)", "जूल (J)", "न्यूटन (N)", "सेकंड (s)"],
     ["Watt (W)", "Joule (J)", "Newton (N)", "Second (s)"],
     0,
     "शक्ति का मात्रक वाट है।",
     "The unit of power is the watt."),

    ("power", "easy",
     "एक वाट किसके बराबर है?",
     "One watt equals —",
     ["1 जूल प्रति सेकंड", "1 सेकंड प्रति जूल", "1 न्यूटन प्रति मीटर", "1 जूल प्रति मीटर"],
     ["1 joule per second", "1 second per joule", "1 newton per metre", "1 joule per metre"],
     0,
     "1 W = 1 J/s।",
     "1 W = 1 J/s."),

    ("power", "easy",
     "1 किलोवाट (kW) कितने वाट होते हैं?",
     "How many watts make 1 kilowatt (kW)?",
     ["1000 W", "100 W", "10 W", "10,000 W"],
     ["1000 W", "100 W", "10 W", "10,000 W"],
     0,
     "1 kW = 1000 W।",
     "1 kW = 1000 W."),

    ("power", "easy",
     "शक्ति किस प्रकार की राशि है?",
     "What kind of quantity is power?",
     ["अदिश", "सदिश", "न अदिश न सदिश", "सदा ऋणात्मक"],
     ["A scalar", "A vector", "Neither scalar nor vector", "Always negative"],
     0,
     "शक्ति दर है — दिशा नहीं, केवल मान।",
     "Power is a rate — no direction, only magnitude."),

    ("power", "easy",
     "समान कार्य कम समय में पूरा किया जाए तो शक्ति —",
     "If the same work is finished in less time, the power is —",
     ["अधिक", "कम", "समान", "शून्य"],
     ["Greater", "Smaller", "The same", "Zero"],
     0,
     "t घटा (W समान) → P = W/t बढ़ी।",
     "Smaller t with the same W → P = W/t rises."),

    ("power", "easy",
     "अधिक शक्तिशाली मशीन क्या करती है?",
     "What does a more powerful machine do?",
     ["एक सेकंड में अधिक कार्य", "कुल अधिक कार्य जरूर करे", "कम ऊर्जा खाती है", "धीमी चलती है"],
     ["More work in one second", "Necessarily more total work", "Consumes less energy", "Runs slower"],
     0,
     "शक्ति = दर — शक्तिशाली मशीन प्रति सेकंड अधिक कार्य करती है।",
     "Power = rate — a powerful machine does more work each second."),

    ("power", "easy",
     "बल्ब पर लिखा '100 W' क्या बताता है?",
     "What does '100 W' printed on a bulb indicate?",
     ["प्रति सेकंड 100 जूल ऊर्जा की खपत", "कुल 100 जूल ऊर्जा", "100 न्यूटन बल", "100 जूल प्रति मीटर"],
     ["It consumes 100 joules of energy per second", "A total of 100 joules", "A force of 100 newtons", "100 joules per metre"],
     0,
     "वाट-रेटिंग = ऊर्जा खपत की दर।",
     "The watt rating = the rate of energy consumption."),

    ("power", "easy",
     "अश्वशक्ति (horse power) किस राशि की इकाई है?",
     "Horse power is a unit of which quantity?",
     ["शक्ति", "ऊर्जा", "बल", "द्रव्यमान"],
     ["Power", "Energy", "Force", "Mass"],
     0,
     "अश्वशक्ति (≈746 W) शक्ति की पुरानी इकाई है।",
     "Horse power (≈746 W) is an old unit of power."),

    ("power", "easy",
     "शक्ति ऊर्जा की दर है — अतः ऊर्जा = —",
     "Power is the rate of energy — hence energy equals —",
     ["शक्ति × समय", "शक्ति ÷ समय", "शक्ति + समय", "समय ÷ शक्ति"],
     ["Power × time", "Power ÷ time", "Power + time", "Time ÷ power"],
     0,
     "E = P × t — जैसे वाट × सेकंड = जूल।",
     "E = P × t — as watt × second = joule."),

    ("power", "easy",
     "100 W का बल्ब 1 सेकंड में कितनी ऊर्जा खाता है?",
     "How much energy does a 100 W bulb consume in 1 second?",
     ["100 J", "1 J", "1000 J", "0.01 J"],
     ["100 J", "1 J", "1000 J", "0.01 J"],
     0,
     "E = 100 W × 1 s = 100 J।",
     "E = 100 W × 1 s = 100 J."),

    ("power", "easy",
     "शक्ति किन कारकों पर निर्भर करती है?",
     "On which factors does power depend?",
     ["कार्य और समय", "केवल कार्य", "केवल समय", "बल और दिशा"],
     ["Work and time", "Work only", "Time only", "Force and direction"],
     0,
     "P = W/t — दोनों निर्धारक।",
     "P = W/t — both decide it."),

    ("power", "easy",
     "साइकिल सवार और मोटरसाइकिल में अधिक शक्तिशाली कौन?",
     "Between a cyclist and a motorcycle, which is more powerful?",
     ["मोटरसाइकिल (प्रति सेकंड अधिक कार्य)", "साइकिल सवार", "दोनों समान", "तुलना असंभव"],
     ["The motorcycle (more work per second)", "The cyclist", "Both equal", "Comparison impossible"],
     0,
     "इंजन प्रति सेकंड बहुत अधिक ऊर्जा खर्च करता है — शक्ति अधिक।",
     "The engine spends far more energy per second — higher power."),

    # ---- medium (17) ----
    ("power", "medium",
     "100 J कार्य 5 सेकंड में — शक्ति —",
     "100 J of work in 5 seconds — the power is —",
     ["20 W", "500 W", "50 W", "5 W"],
     ["20 W", "500 W", "50 W", "5 W"],
     0,
     "P = 100/5 = 20 W।",
     "P = 100/5 = 20 W."),

    ("power", "medium",
     "1000 J कार्य 10 सेकंड में — शक्ति —",
     "1000 J of work in 10 s — the power is —",
     ["100 W", "10,000 W", "1000 W", "10 W"],
     ["100 W", "10,000 W", "1000 W", "10 W"],
     0,
     "P = 1000/10 = 100 W।",
     "P = 1000/10 = 100 W."),

    ("power", "medium",
     "500 J कार्य 50 सेकंड में — शक्ति —",
     "500 J of work in 50 s — the power is —",
     ["10 W", "25,000 W", "550 W", "45 W"],
     ["10 W", "25,000 W", "550 W", "45 W"],
     0,
     "P = 500/50 = 10 W।",
     "P = 500/50 = 10 W."),

    ("power", "medium",
     "600 J कार्य 20 सेकंड में — शक्ति —",
     "600 J of work in 20 s — the power is —",
     ["30 W", "12,000 W", "60 W", "3 W"],
     ["30 W", "12,000 W", "60 W", "3 W"],
     0,
     "P = 600/20 = 30 W।",
     "P = 600/20 = 30 W."),

    ("power", "medium",
     "750 J का कार्य 15 सेकंड में — शक्ति —",
     "750 J of work in 15 s — the power is —",
     ["50 W", "11,250 W", "735 W", "5 W"],
     ["50 W", "11,250 W", "735 W", "5 W"],
     0,
     "P = 750/15 = 50 W।",
     "P = 750/15 = 50 W."),

    ("power", "medium",
     "300 J कार्य 1 मिनट में — शक्ति —",
     "300 J of work in 1 minute — the power is —",
     ["5 W", "300 W", "0.2 W", "50 W"],
     ["5 W", "300 W", "0.2 W", "50 W"],
     0,
     "t = 60 s; P = 300/60 = 5 W।",
     "t = 60 s; P = 300/60 = 5 W."),

    ("power", "medium",
     "50 W शक्ति से 10 सेकंड तक कार्य — कुल कार्य —",
     "Work done at 50 W for 10 s — the total work is —",
     ["500 J", "5 J", "60 J", "5000 J"],
     ["500 J", "5 J", "60 J", "5000 J"],
     0,
     "W = P × t = 50 × 10 = 500 J।",
     "W = P × t = 50 × 10 = 500 J."),

    ("power", "medium",
     "200 W की मशीन 5 सेकंड चली — किया कार्य —",
     "A 200 W machine runs for 5 s — the work done is —",
     ["1000 J", "40 J", "205 J", "200 J"],
     ["1000 J", "40 J", "205 J", "200 J"],
     0,
     "W = 200 × 5 = 1000 J।",
     "W = 200 × 5 = 1000 J."),

    ("power", "medium",
     "400 J कार्य 40 W शक्ति से — लगा समय —",
     "400 J of work at 40 W — the time taken is —",
     ["10 s", "16,000 s", "360 s", "4 s"],
     ["10 s", "16,000 s", "360 s", "4 s"],
     0,
     "t = W/P = 400/40 = 10 s।",
     "t = W/P = 400/40 = 10 s."),

    ("power", "medium",
     "2 kW की मशीन 10 सेकंड चलती है — कुल कार्य —",
     "A 2 kW machine works for 10 s — the total work is —",
     ["20,000 J", "2000 J", "200 J", "0.2 J"],
     ["20,000 J", "2000 J", "200 J", "0.2 J"],
     0,
     "2 kW = 2000 W; W = 2000 × 10 = 20,000 J।",
     "2 kW = 2000 W; W = 2000 × 10 = 20,000 J."),

    ("power", "medium",
     "100 W का बल्ब 1 घंटा जलता है — खपत ऊर्जा —",
     "A 100 W bulb burns for 1 hour — the energy consumed is —",
     ["360,000 J (3.6 लाख जूल)", "100 J", "6000 J", "3600 J"],
     ["360,000 J (0.36 million joules)", "100 J", "6000 J", "3600 J"],
     0,
     "t = 3600 s; E = 100 × 3600 = 360,000 J।",
     "t = 3600 s; E = 100 × 3600 = 360,000 J."),

    ("power", "medium",
     "कथन A: शक्ति कार्य की दर है। कथन B: शक्ति का मात्रक जूल प्रति सेकंड है। सही विकल्प —",
     "Statement A: power is the rate of doing work. Statement B: the unit of power is joule per second. The correct option —",
     ["A और B दोनों सही", "केवल A सही", "केवल B सही", "दोनों गलत"],
     ["Both A and B are right", "Only A is right", "Only B is right", "Both are wrong"],
     0,
     "परिभाषा और मात्रक दोनों एक सिद्धांत के हिस्से।",
     "The definition and the unit belong to the same principle."),

    ("power", "medium",
     "समान कार्य को दोगुने समय में किया जाए — शक्ति —",
     "The same work is done in double the time — the power —",
     ["आधी रह जाती है", "दोगुनी", "चार गुनी", "समान"],
     ["Halves", "Doubles", "Quadruples", "Stays the same"],
     0,
     "P ∝ 1/t (W समान) — समय ×2 → शक्ति ½।",
     "P ∝ 1/t (same W) — double time, half power."),

    ("power", "medium",
     "A 10 सेकंड में 500 J, B 20 सेकंड में 500 J — शक्तियों का अनुपात —",
     "A does 500 J in 10 s, B does 500 J in 20 s — the ratio of their powers is —",
     ["2 : 1", "1 : 2", "1 : 1", "4 : 1"],
     ["2 : 1", "1 : 2", "1 : 1", "4 : 1"],
     0,
     "P_A = 50 W, P_B = 25 W → 2 : 1।",
     "P_A = 50 W, P_B = 25 W → 2 : 1."),

    ("power", "medium",
     "लोहार और मशीन समान कार्य करते हैं, मशीन जल्दी — शक्ति और कार्य का सही कथन —",
     "A blacksmith and a machine do the same work, the machine faster — the correct statement about power and work is —",
     ["कार्य समान, मशीन की शक्ति अधिक", "दोनों की शक्ति समान", "मशीन का कार्य अधिक", "लोहार की शक्ति अधिक"],
     ["The work is equal, the machine's power is greater", "Their powers are equal", "The machine did more work", "The blacksmith's power is greater"],
     0,
     "शक्ति = कार्य की दर — जल्दी करने वाली मशीन अधिक शक्तिशाली, कार्य समान।",
     "Power = rate of work — the faster machine is more powerful, the work being equal."),

    ("power", "medium",
     "60 W का पंखा 2 मिनट चला — खपत ऊर्जा —",
     "A 60 W fan runs for 2 minutes — the energy consumed is —",
     ["7200 J", "120 J", "3600 J", "720 J"],
     ["7200 J", "120 J", "3600 J", "720 J"],
     0,
     "t = 120 s; E = 60 × 120 = 7200 J।",
     "t = 120 s; E = 60 × 120 = 7200 J."),

    ("power", "medium",
     "किलोवाट-घंटा (kWh) किसकी इकाई है?",
     "The kilowatt-hour (kWh) is a unit of which quantity?",
     ["ऊर्जा", "शक्ति", "बल", "समय"],
     ["Energy", "Power", "Force", "Time"],
     0,
     "kWh = किलोवाट × घंटा = ऊर्जा — विद्युत की व्यावसायिक इकाई; यह प्रसिद्ध जाल है।",
     "kWh = kilowatt × hour = energy — the commercial unit of electricity; a famous trap."),

    # ---- hard (6) ----
    ("power", "hard",
     "50 kg व्यक्ति 10 सेकंड में 4 मीटर ऊँची सीढ़ी चढ़ता है (g = 10) — उसकी शक्ति —",
     "A 50 kg person climbs a 4 m staircase in 10 s (g = 10) — the power is —",
     ["200 W", "20 W", "2000 W", "50 W"],
     ["200 W", "20 W", "2000 W", "50 W"],
     0,
     "W = mgh = 50 × 10 × 4 = 2000 J; P = 2000/10 = 200 W।",
     "W = mgh = 50 × 10 × 4 = 2000 J; P = 2000/10 = 200 W."),

    ("power", "hard",
     "60 kg व्यक्ति 20 सेकंड में 5 मीटर ऊपर जाता है (g = 10) — शक्ति —",
     "A 60 kg person ascends 5 m in 20 s (g = 10) — the power is —",
     ["150 W", "300 W", "30 W", "1500 W"],
     ["150 W", "300 W", "30 W", "1500 W"],
     0,
     "W = 60 × 10 × 5 = 3000 J; P = 3000/20 = 150 W।",
     "W = 60 × 10 × 5 = 3000 J; P = 3000/20 = 150 W."),

    ("power", "hard",
     "इंजन 1 मिनट में 18,000 J कार्य करता है — शक्ति —",
     "An engine does 18,000 J of work in 1 minute — the power is —",
     ["300 W", "180 W", "3000 W", "18 W"],
     ["300 W", "180 W", "3000 W", "18 W"],
     0,
     "t = 60 s; P = 18,000/60 = 300 W।",
     "t = 60 s; P = 18,000/60 = 300 W."),

    ("power", "hard",
     "400 W की मशीन 5 मिनट काम करती है — कुल ऊर्जा —",
     "A 400 W machine works for 5 minutes — the total energy is —",
     ["120,000 J (120 kJ)", "2000 J", "4000 J", "2400 J"],
     ["120,000 J (120 kJ)", "2000 J", "4000 J", "2400 J"],
     0,
     "t = 300 s; E = 400 × 300 = 120,000 J।",
     "t = 300 s; E = 400 × 300 = 120,000 J."),

    ("power", "hard",
     "कथन A: kWh ऊर्जा की इकाई है। कथन B: वाट शक्ति की इकाई है। सही विकल्प —",
     "Statement A: the kWh is a unit of energy. Statement B: the watt is a unit of power. The correct option —",
     ["A और B दोनों सही", "केवल A सही", "केवल B सही", "दोनों गलत"],
     ["Both A and B are right", "Only A is right", "Only B is right", "Both are wrong"],
     0,
     "kWh ऊर्जा (व्यावसायिक), वाट शक्ति — दोनों सही।",
     "kWh measures energy (commercial), watt measures power — both right."),

    ("power", "hard",
     "मशीन A 5 सेकंड में 500 J, मशीन B 15 सेकंड में 1500 J — शक्तियों की तुलना —",
     "Machine A does 500 J in 5 s, machine B does 1500 J in 15 s — comparing their powers —",
     ["समान (दोनों 100 W)", "A अधिक शक्तिशाली", "B अधिक शक्तिशाली", "तुलना असंभव"],
     ["Equal (both 100 W)", "A is more powerful", "B is more powerful", "Comparison impossible"],
     0,
     "P_A = 500/5 = 100 W; P_B = 1500/15 = 100 W — बड़ा कार्य बड़ी शक्ति नहीं; यही जाल है।",
     "P_A = 500/5 = 100 W; P_B = 1500/15 = 100 W — bigger work does not mean bigger power; that is the trap."),
]
