# -*- coding: utf-8 -*-
"""P06 (Heat & Temperature) — Part 1: heat-and-temperature (38) + heat-transfer (38) = 76 tuples.
All items authored with correct_idx=0; rotation happens in gen_p06_questions.py.

T1 heat-and-temperature 38 = E16/M16/H6
T2 heat-transfer         38 = E15/M16/H7
"""

PART1 = [
    # ================= HEAT & TEMPERATURE (38) =================
    # ---- easy (16) ----
    ("heat-and-temperature", "easy",
     "ऊष्मा किसे कहते हैं?",
     "What is heat?",
     ["तापांतर के कारण एक वस्तु से दूसरी वस्तु में स्थानांतरित होने वाली ऊर्जा", "केवल गर्मी का अनुभव", "वस्तु का भार", "वस्तु का रंग"],
     ["The energy transferred from one body to another due to a temperature difference", "Only the feeling of warmth", "An object's weight", "An object's colour"],
     0,
     "ऊष्मा ऊर्जा का रूप है जो गर्म पिंड से ठंडे पिंड की ओर बहती है।",
     "Heat is a form of energy flowing from a hot body towards a colder one."),

    ("heat-and-temperature", "easy",
     "ताप किसे कहते हैं?",
     "What is temperature?",
     ["किसी पिंड की गर्मी-ठंडक की तीव्रता का माप", "पिंड की कुल ऊर्जा", "पिंड का द्रव्यमान", "पिंड का आयतन"],
     ["The measure of the intensity of a body's hotness or coldness", "A body's total energy", "A body's mass", "A body's volume"],
     0,
     "ताप बताता है कि वस्तु कितनी गर्म या ठंडी है — यह तीव्रता का माप है।",
     "Temperature tells how hot or cold a body is — a measure of intensity."),

    ("heat-and-temperature", "easy",
     "ऊष्मा का SI मात्रक क्या है?",
     "What is the SI unit of heat?",
     ["जूल (J)", "केल्विन (K)", "वाट (W)", "किलोग्राम (kg)"],
     ["Joule (J)", "Kelvin (K)", "Watt (W)", "Kilogram (kg)"],
     0,
     "ऊष्मा ऊर्जा है — इसका SI मात्रक जूल है (कैलोरी भी प्रचलित)।",
     "Heat is energy — its SI unit is the joule (the calorie is also common)."),

    ("heat-and-temperature", "easy",
     "ताप का SI मात्रक क्या है?",
     "What is the SI unit of temperature?",
     ["केल्विन (K)", "जूल (J)", "डिग्री सेल्सियस (°C)", "कैलोरी (cal)"],
     ["Kelvin (K)", "Joule (J)", "Degree Celsius (°C)", "Calorie (cal)"],
     0,
     "SI में ताप केल्विन में; डिग्री सेल्सियस सामान्य पैमाना है।",
     "In SI, temperature is in kelvin; degree Celsius is the everyday scale."),

    ("heat-and-temperature", "easy",
     "ताप मापने का यंत्र कौन-सा है?",
     "Which instrument measures temperature?",
     ["थर्मामीटर", "कैलोरीमीटर", "बैरोमीटर", "अमीटर"],
     ["Thermometer", "Calorimeter", "Barometer", "Ammeter"],
     0,
     "थर्मामीटर पारे/तरल के फैलाव से ताप बताता है।",
     "A thermometer reads temperature via the expansion of mercury or liquid."),

    ("heat-and-temperature", "easy",
     "ऊष्मा की मात्रा मापने का यंत्र —",
     "The instrument for measuring quantities of heat is —",
     ["कैलोरीमीटर", "थर्मामीटर", "स्प्रिंग बैलेंस", "हाइड्रोमीटर"],
     ["Calorimeter", "Thermometer", "Spring balance", "Hydrometer"],
     0,
     "कैलोरीमीटर ऊष्मा का आदान-प्रदान मापता है।",
     "A calorimeter measures the exchange of heat."),

    ("heat-and-temperature", "easy",
     "ऊष्मा किस दिशा में प्रवाहित होती है?",
     "In which direction does heat flow?",
     ["गर्म पिंड से ठंडे पिंड की ओर", "ठंडे पिंड से गर्म की ओर", "दोनों दिशाओं में समान", "किसी भी दिशा में"],
     ["From the hot body towards the cold body", "From the cold body towards the hot one", "Equally in both directions", "In any direction"],
     0,
     "तापांतर हटने तक ऊष्मा गर्म से ठंडे की ओर ही बहती है।",
     "Heat flows from hot to cold until the temperature difference is gone."),

    ("heat-and-temperature", "easy",
     "1 कैलोरी लगभग कितने जूल होती है?",
     "One calorie is about how many joules?",
     ["4.2 जूल", "1 जूल", "42 जूल", "0.42 जूल"],
     ["4.2 joules", "1 joule", "42 joules", "0.42 joule"],
     0,
     "1 cal ≈ 4.2 J — ऊष्मा की दो इकाइयों का संबंध।",
     "1 cal ≈ 4.2 J — the relation between the two heat units."),

    ("heat-and-temperature", "easy",
     "बर्फ का गलनांक (सामान्य दाब पर) —",
     "The melting point of ice (at normal pressure) is —",
     ["0 °C", "100 °C", "273 °C", "−100 °C"],
     ["0 °C", "100 °C", "273 °C", "−100 °C"],
     0,
     "0 °C पर बर्फ पिघलती है — यही जल का हिमांक है।",
     "Ice melts at 0 °C — water's freezing point."),

    ("heat-and-temperature", "easy",
     "सामान्य दाब पर जल का क्वथनांक —",
     "The boiling point of water at normal pressure is —",
     ["100 °C", "0 °C", "50 °C", "212 °C"],
     ["100 °C", "0 °C", "50 °C", "212 °C"],
     0,
     "100 °C पर जल उबलकर भाप बनता है।",
     "At 100 °C water boils into steam."),

    ("heat-and-temperature", "easy",
     "स्वस्थ मानव शरीर का सामान्य ताप लगभग —",
     "The normal temperature of a healthy human body is about —",
     ["37 °C", "27 °C", "47 °C", "0 °C"],
     ["37 °C", "27 °C", "47 °C", "0 °C"],
     0,
     "शरीर का सामान्य ताप लगभग 37 °C होता है।",
     "The body's normal temperature is about 37 °C."),

    ("heat-and-temperature", "easy",
     "ऊष्मा और ताप में मूल अंतर क्या है?",
     "What is the fundamental difference between heat and temperature?",
     ["ऊष्मा कुल ऊर्जा है, ताप उसकी तीव्रता का माप", "दोनों एक ही हैं", "ताप कुल ऊर्जा है, ऊष्मा तीव्रता", "ऊष्मा दिशा है, ताप द्रव्यमान"],
     ["Heat is the total energy, temperature measures its intensity", "Both are the same", "Temperature is total energy, heat is intensity", "Heat is a direction, temperature is mass"],
     0,
     "ऊष्मा = कितनी ऊर्जा; ताप = कितनी गर्मी की मात्रा का सूचक।",
     "Heat = how much energy; temperature = how intense the hotness is."),

    ("heat-and-temperature", "easy",
     "क्लिनिकल थर्मामीटर की माप सीमा (रेंज) प्रायः —",
     "The measuring range of a clinical thermometer is usually —",
     ["35 °C से 42 °C", "0 °C से 100 °C", "−10 °C से 110 °C", "273 K से 373 K"],
     ["35 °C to 42 °C", "0 °C to 100 °C", "−10 °C to 110 °C", "273 K to 373 K"],
     0,
     "शरीर-ताप के आसपास की सीमा 35–42 °C ही काफी है।",
     "The body-temperature vicinity, 35–42 °C, is all that is needed."),

    ("heat-and-temperature", "easy",
     "केल्विन पैमाने पर जल का क्वथनांक —",
     "On the Kelvin scale, the boiling point of water is —",
     ["373 K", "273 K", "100 K", "473 K"],
     ["373 K", "273 K", "100 K", "473 K"],
     0,
     "K = °C + 273 → 100 + 273 = 373 K।",
     "K = °C + 273 → 100 + 273 = 373 K."),

    ("heat-and-temperature", "easy",
     "केल्विन पैमाने पर बर्फ का गलनांक —",
     "On the Kelvin scale, the melting point of ice is —",
     ["273 K", "373 K", "0 K", "173 K"],
     ["273 K", "373 K", "0 K", "173 K"],
     0,
     "0 + 273 = 273 K।",
     "0 + 273 = 273 K."),

    ("heat-and-temperature", "easy",
     "थर्मामीटर में पारे का उपयोग क्यों होता है?",
     "Why is mercury used in thermometers?",
     ["यह चालक, चमकदार है और समान रूप से फैलता है", "यह सस्ता है", "यह रंगीन है", "यह हल्का है"],
     ["It is conductive, shiny and expands uniformly", "It is cheap", "It is colourful", "It is light"],
     0,
     "पारे का फैलाव ताप के साथ एकसार और दृश्य होता है।",
     "Mercury's expansion is uniform with temperature and clearly visible."),

    # ---- medium (16) ----
    ("heat-and-temperature", "medium",
     "सेल्सियस को केल्विन में बदलने का सूत्र —",
     "The formula for converting Celsius to Kelvin is —",
     ["K = °C + 273", "K = °C − 273", "K = °C × 273", "K = °C + 100"],
     ["K = °C + 273", "K = °C − 273", "K = °C × 273", "K = °C + 100"],
     0,
     "केल्विन = सेल्सियस + 273।",
     "Kelvin = Celsius + 273."),

    ("heat-and-temperature", "medium",
     "27 °C को केल्विन में —",
     "27 °C in kelvin is —",
     ["300 K", "273 K", "246 K", "327 K"],
     ["300 K", "273 K", "246 K", "327 K"],
     0,
     "27 + 273 = 300 K।",
     "27 + 273 = 300 K."),

    ("heat-and-temperature", "medium",
     "30 °C = ? K",
     "30 °C = ? K",
     ["303 K", "300 K", "243 K", "330 K"],
     ["303 K", "300 K", "243 K", "330 K"],
     0,
     "30 + 273 = 303 K।",
     "30 + 273 = 303 K."),

    ("heat-and-temperature", "medium",
     "50 °C केल्विन में —",
     "50 °C in kelvin is —",
     ["323 K", "223 K", "350 K", "273 K"],
     ["323 K", "223 K", "350 K", "273 K"],
     0,
     "50 + 273 = 323 K।",
     "50 + 273 = 323 K."),

    ("heat-and-temperature", "medium",
     "373 K सेल्सियस में —",
     "373 K in Celsius is —",
     ["100 °C", "0 °C", "50 °C", "646 °C"],
     ["100 °C", "0 °C", "50 °C", "646 °C"],
     0,
     "373 − 273 = 100 °C।",
     "373 − 273 = 100 °C."),

    ("heat-and-temperature", "medium",
     "300 K सेल्सियस में —",
     "300 K in Celsius is —",
     ["27 °C", "30 °C", "0 °C", "573 °C"],
     ["27 °C", "30 °C", "0 °C", "573 °C"],
     0,
     "300 − 273 = 27 °C।",
     "300 − 273 = 27 °C."),

    ("heat-and-temperature", "medium",
     "क्लिनिकल थर्मामीटर में कष्ठिका (kink) क्यों होती है?",
     "Why does a clinical thermometer have a kink?",
     ["पढ़ने के समय पारा नीचे न उतरे, रीडिंग टिकी रहे", "पारा ऊपर चढ़े नहीं", "कांच मजबूत रहे", "थर्मामीटर सस्ता रहे"],
     ["So the mercury does not fall back and the reading stays", "So the mercury cannot rise", "To strengthen the glass", "To keep the thermometer cheap"],
     0,
     "कष्ठिका पारे को रोककर पढ़ाई में सहायक बनती है।",
     "The kink traps the mercury so the reading can be read at ease."),

    ("heat-and-temperature", "medium",
     "दो वस्तुओं के बीच ऊष्मा प्रवाह कब रुक जाता है?",
     "When does heat flow between two bodies stop?",
     ["जब दोनों का ताप समान हो जाए (तापीय संतुलन)", "जब दोनों की ऊष्मा समान हो", "जब दोनों का द्रव्यमान समान हो", "कभी नहीं रुकता"],
     ["When both reach the same temperature (thermal equilibrium)", "When both have equal heat", "When both have equal mass", "It never stops"],
     0,
     "तापांतर शून्य → प्रवाह रुकता है।",
     "Zero temperature difference → the flow ceases."),

    ("heat-and-temperature", "medium",
     "छोटे कप की तेज़ गर्म चाय और बड़े बर्तन का गुनगुना पानी — किसमें कुल ऊष्मा अधिक हो सकती है?",
     "A small cup of very hot tea versus a large vessel of lukewarm water — which can hold more total heat?",
     ["बड़े बर्तन में (द्रव्यमान बहुत अधिक)", "छोटे कप में (ताप अधिक)", "दोनों में समान", "निर्धारित नहीं कर सकते"],
     ["The large vessel (far greater mass)", "The small cup (higher temperature)", "Equal in both", "Cannot be determined"],
     0,
     "कुल ऊष्मा द्रव्यमान पर भी निर्भर करती है — यही परीक्षा-जाल है।",
     "Total heat also depends on mass — this is the classic exam trap."),

    ("heat-and-temperature", "medium",
     "कैलोरी किसे कहते हैं?",
     "What is one calorie?",
     ["1 ग्राम जल को 1 °C गर्म करने की आवश्यक ऊष्मा", "1 किलोग्राम को 1 °C गर्म करने की ऊष्मा", "1 ग्राम बर्फ पिघलाने की ऊष्मा", "100 जूल ऊर्जा"],
     ["The heat needed to warm 1 gram of water by 1 °C", "The heat to warm 1 kilogram by 1 °C", "The heat to melt 1 gram of ice", "100 joules of energy"],
     0,
     "1 cal = 1 g जल का 1 °C ताप-वृद्धि लागी ऊष्मा।",
     "1 cal = the heat raising 1 g of water by 1 °C."),

    ("heat-and-temperature", "medium",
     "गर्म वस्तु और ठंडी वस्तु को संपर्क में रखा जाए — अंतिम साम्य ताप —",
     "A hot and a cold body are brought into contact — the final equilibrium temperature lies —",
     ["दोनों के प्रारंभिक तापों के बीच", "गर्म वस्तु के ताप पर", "ठंडी वस्तु के ताप पर", "दोनों से ऊपर"],
     ["Between the two initial temperatures", "At the hot body's temperature", "At the cold body's temperature", "Above both"],
     0,
     "ऊष्मा हस्तांतरण के बाद साम्य ताप मध्यवर्ती हो जाता है।",
     "After the exchange the equilibrium temperature settles in between."),

    ("heat-and-temperature", "medium",
     "आधुनिक डिजिटल थर्मामीटर को पारे वाले पर वरीयता क्यों दी जाती है?",
     "Why are digital thermometers preferred over mercury ones today?",
     ["पारा विषाक्त है — टूटने पर जोखिम", "डिजिटल सस्ता हमेशा", "पारा ठंडा होता है", "डिजिटल रंगीन होता है"],
     ["Mercury is toxic — a breakage poses a risk", "Digitals are always cheaper", "Mercury is cold", "Digitals are colourful"],
     0,
     "पारे के स्वास्थ्य-जोखिम के कारण डिजिटल सुरक्षित माना जाता है।",
     "Digital is safer because mercury poses health hazards."),

    ("heat-and-temperature", "medium",
     "25 °C के कमरे में रखा 40 °C का पानी — ऊष्मा किसकी ओर बहेगी?",
     "Water at 40 °C stands in a 25 °C room — which way does the heat flow?",
     ["पानी से कमरे की ओर", "कमरे से पानी की ओर", "कहीं नहीं", "दोनों ओर समान"],
     ["From the water to the room", "From the room to the water", "Nowhere", "Equally both ways"],
     0,
     "40 से 25 की ओर — गर्म से ठंडे की ओर नियम।",
     "From 40 °C to 25 °C — hot to cold, as the rule goes."),

    ("heat-and-temperature", "medium",
     "कथन A: ताप अदिश राशि है। कथन B: ऊष्मा भी अदिश राशि है। सही विकल्प —",
     "Statement A: temperature is a scalar. Statement B: heat is also a scalar. The correct option —",
     ["A और B दोनों सही", "केवल A सही", "केवल B सही", "दोनों गलत"],
     ["Both A and B are right", "Only A is right", "Only B is right", "Both are wrong"],
     0,
     "ताप और ऊष्मा दोनों केवल परिमाण बताते हैं — दोनों अदिश।",
     "Both temperature and heat carry magnitude only — both scalars."),

    ("heat-and-temperature", "medium",
     "समान ताप के दो पिंड — एक 100 g, दूसरा 500 g — किसमें अधिक ऊष्मा (सामान्यतः)?",
     "Two bodies at the same temperature — one 100 g, the other 500 g — which generally holds more heat?",
     ["500 g वाले में", "100 g वाले में", "समान", "कोई नहीं"],
     ["The 500 g one", "The 100 g one", "Equal", "Neither"],
     0,
     "अधिक द्रव्यमान में उसी ताप पर अधिक कुल ऊर्जा जमा रहती है।",
     "At the same temperature, more mass stores more total energy."),

    ("heat-and-temperature", "medium",
     "क्लिनिकल थर्मामीटर को दोबारा उपयोग से पहले हिलाकर पारा नीचे क्यों लाया जाता है?",
     "Before reuse, why is a clinical thermometer shaken to bring the mercury down?",
     ["कष्ठिका से रुका पारा पिछली रीडिंग पर ही रहता है", "पारा गर्म हो जाता है", "कांच थक जाता है", "पैमाना बदल जाता है"],
     ["The mercury trapped at the kink stays at the last reading", "The mercury gets hot", "The glass tires out", "The scale changes"],
     0,
     "झटका पारे को कष्ठिका के पार उतारकर नई माप के लिए शून्य करता है।",
     "The jerk pushes the mercury past the kink, resetting for a fresh reading."),

    # ---- hard (6) ----
    ("heat-and-temperature", "hard",
     "−40 °C केल्विन में —",
     "−40 °C in kelvin is —",
     ["233 K", "313 K", "−313 K", "273 K"],
     ["233 K", "313 K", "−313 K", "273 K"],
     0,
     "−40 + 273 = 233 K।",
     "−40 + 273 = 233 K."),

    ("heat-and-temperature", "hard",
     "100 g जल को 40 °C से 60 °C गर्म करने में आवश्यक ऊष्मा —",
     "The heat needed to warm 100 g of water from 40 °C to 60 °C is —",
     ["2000 cal", "200 cal", "6000 cal", "1000 cal"],
     ["2000 cal", "200 cal", "6000 cal", "1000 cal"],
     0,
     "Q = 100 × 1 × (60 − 40) = 2000 cal।",
     "Q = 100 × 1 × (60 − 40) = 2000 cal."),

    ("heat-and-temperature", "hard",
     "50 g जल को 20 °C से बढ़ाकर 45 °C करने में ऊष्मा —",
     "Raising 50 g of water from 20 °C to 45 °C takes heat of —",
     ["1250 cal", "250 cal", "2250 cal", "500 cal"],
     ["1250 cal", "250 cal", "2250 cal", "500 cal"],
     0,
     "Q = 50 × 1 × 25 = 1250 cal।",
     "Q = 50 × 1 × 25 = 1250 cal."),

    ("heat-and-temperature", "hard",
     "कथन A: गर्म पिंड में हमेशा अधिक ऊष्मा होती है। कथन B: ताप समान रहने पर भी ऊष्मा भिन्न हो सकती है। सही विकल्प —",
     "Statement A: a hotter body always holds more heat. Statement B: even at the same temperature, the heat can differ. The correct option —",
     ["A गलत, B सही (द्रव्यमान मायने रखता है)", "A सही, B गलत", "दोनों सही", "दोनों गलत"],
     ["A wrong, B right (mass matters)", "A right, B wrong", "Both right", "Both wrong"],
     0,
     "ताप तीव्रता है; कुल ऊष्मा द्रव्यमान पर निर्भर — A जाल, B सही।",
     "Temperature is intensity; total heat depends on mass — A is the trap, B holds."),

    ("heat-and-temperature", "hard",
     "केल्विन पैमाने पर ऋणात्मक ताप क्यों नहीं होता?",
     "Why are there no negative temperatures on the Kelvin scale?",
     ["शून्य केल्विन से नीचे ठंडा संभव नहीं (पूर्ण शून्य सीमा)", "केल्विन गलत पैमाना है", "ऋणात्मक अंक निषिद्ध हैं", "पारा जम जाता है"],
     ["Nothing can be colder than zero kelvin (absolute zero is the limit)", "Kelvin is a wrong scale", "Negative digits are forbidden", "Mercury freezes"],
     0,
     "0 K = पूर्ण शून्य — कणों की न्यूनतम ऊर्जा; इससे नीचे ताप संभव नहीं।",
     "0 K = absolute zero — minimum particle energy; no lower temperature exists."),

    ("heat-and-temperature", "hard",
     "200 g जल को 30 °C से 80 °C गर्म करने में लगी ऊष्मा —",
     "Warming 200 g of water from 30 °C to 80 °C requires heat of —",
     ["10,000 cal", "1000 cal", "16,000 cal", "5000 cal"],
     ["10,000 cal", "1000 cal", "16,000 cal", "5000 cal"],
     0,
     "Q = 200 × 1 × 50 = 10,000 cal।",
     "Q = 200 × 1 × 50 = 10,000 cal."),

    # ================= HEAT TRANSFER (38) =================
    # ---- easy (15) ----
    ("heat-transfer", "easy",
     "ऊष्मा संचरण की तीन विधियाँ कौन-सी हैं?",
     "Which are the three modes of heat transfer?",
     ["चालन, संवहन, विकिरण", "चालन, विद्युत, घर्षण", "संवहन, दाब, प्रवाह", "विकिरण, वाष्पीकरण, संघनन"],
     ["Conduction, convection, radiation", "Conduction, electricity, friction", "Convection, pressure, flow", "Radiation, evaporation, condensation"],
     0,
     "ठोस में चालन, द्रव-गैस में संवहन, बिना माध्यम विकिरण।",
     "Conduction in solids, convection in fluids, radiation needs no medium."),

    ("heat-transfer", "easy",
     "चालन किसे कहते हैं?",
     "What is conduction?",
     ["कण अपने स्थान पर रहकर कंपन से ऊष्मा आगे बढ़ाएँ", "कण स्वयं चलकर ऊष्मा ले जाएँ", "तरंगों से बिना माध्यम ऊष्मा", "ऊष्मा का प्रकाश में बदलना"],
     ["Particles stay put and pass heat on by vibration", "Particles themselves carry the heat away", "Heat travels as waves without a medium", "Heat turning into light"],
     0,
     "चालन में कण अपनी जगह छोड़े बिना ऊष्मा हस्तांतरित करते हैं।",
     "In conduction particles hand on heat without leaving their places."),

    ("heat-transfer", "easy",
     "संवहन किसे कहते हैं?",
     "What is convection?",
     ["गर्म कण हल्के होकर उठते और ठंडे नीचे आते हैं — कणों की स्वयं गति", "कण अपने स्थान पर रहकर ऊष्मा दें", "तरंगों द्वारा ऊष्मा", "ऊष्मा का जमना"],
     ["Hot light particles rise and cold ones sink — actual movement of particles", "Particles pass heat while staying put", "Heat through waves", "Freezing of heat"],
     0,
     "द्रवों-गैसों में कण स्वयं उठ-उतरकर ऊष्मा फैलाते हैं।",
     "In fluids the particles themselves rise and sink, spreading heat."),

    ("heat-transfer", "easy",
     "विकिरण किसे कहते हैं?",
     "What is radiation?",
     ["बिना किसी माध्यम के तरंगों द्वारा ऊष्मा का संचरण", "कणों की गति से ऊष्मा", "कंपन से ऊष्मा", "द्रव में धाराएँ"],
     ["Heat transfer by waves without any medium", "Heat by particle motion", "Heat by vibration", "Currents in liquids"],
     0,
     "सूर्य की गर्मी निर्वात से गुजरकर आती है — विकिरण।",
     "The sun's heat crosses vacuum to reach us — radiation."),

    ("heat-transfer", "easy",
     "किस संचरण विधि को माध्यम की आवश्यकता नहीं होती?",
     "Which mode of transfer needs no medium?",
     ["विकिरण", "चालन", "संवहन", "चालन और संवहन दोनों"],
     ["Radiation", "Conduction", "Convection", "Both conduction and convection"],
     0,
     "केवल विकिरण निर्वात में भी संभव है।",
     "Only radiation works even in vacuum."),

    ("heat-transfer", "easy",
     "धातुएँ ऊष्मा की कैसी चालक हैं?",
     "What kind of heat conductors are metals?",
     ["सुचालक", "कुचालक", "इन्सुलेटर", "चालक ही नहीं"],
     ["Good conductors", "Bad conductors", "Insulators", "Not conductors at all"],
     0,
     "धातुओं में चालन तेज़ होता है।",
     "Metals conduct heat quickly."),

    ("heat-transfer", "easy",
     "लकड़ी और प्लास्टिक ऊष्मा की कैसी चालक हैं?",
     "Wood and plastic are what kind of heat conductors?",
     ["कुचालक (उष्मारोधी)", "सुचालक", "अर्धचालक", "चालक नहीं होती"],
     ["Bad conductors (insulators)", "Good conductors", "Semi-conductors", "Non-conductors"],
     0,
     "इसीलिए बर्तनों के हत्थे लकड़ी/प्लास्टिक के होते हैं।",
     "That is why utensil handles are of wood or plastic."),

    ("heat-transfer", "easy",
     "गर्म सूप में डाला चाकू? नहीं — चम्मच का धातु वाला हिस्सा गर्म हो जाता है — यह कौन-सी विधि है?",
     "The metal part of a spoon dipped in hot soup becomes hot — which mode is this?",
     ["चालन", "संवहन", "विकिरण", "वाष्पीकरण"],
     ["Conduction", "Convection", "Radiation", "Evaporation"],
     0,
     "ऊष्मा धातु के कणों से होते हुए ऊपर चढ़ती है — चालन।",
     "Heat climbs up through the metal's particles — conduction."),

    ("heat-transfer", "easy",
     "सूर्य की गर्मी पृथ्वी तक किस विधि से पहुँचती है?",
     "By which mode does the sun's heat reach the earth?",
     ["विकिरण", "चालन", "संवहन", "चालन+संवहन"],
     ["Radiation", "Conduction", "Convection", "Conduction and convection"],
     0,
     "अंतरिक्ष निर्वात है — केवल विकिरण संभव।",
     "Space is vacuum — only radiation is possible."),

    ("heat-transfer", "easy",
     "पानी गर्म करने पर पूरा पानी गर्म हो जाता है — मुख्य विधि —",
     "Heating water warms the whole bulk — the main mode is —",
     ["संवहन", "चालन", "विकिरण", "संघनन"],
     ["Convection", "Conduction", "Radiation", "Condensation"],
     0,
     "नीचे का गर्म पानी उठता, ऊपर का ठंडा उतरता — संवहन धाराएँ।",
     "Hot water below rises, cold above sinks — convection currents."),

    ("heat-transfer", "easy",
     "ठंड में ऊनी कपड़े गर्म रखते हैं क्योंकि —",
     "Woollen clothes keep us warm in winter because —",
     ["ऊन में फँसी हवा कुचालक है — ऊष्मा बाहर नहीं जाने देती", "ऊन गर्म पैदा करता है", "ऊन विकिरण देता है", "ऊन भारी होता है"],
     ["The air trapped in wool is a bad conductor — heat cannot escape", "Wool generates heat", "Wool radiates", "Wool is heavy"],
     0,
     "ऊन के रोमों में बंद हवा उष्मारोधी काम करती है।",
     "Air locked in wool's fibres acts as insulation."),

    ("heat-transfer", "easy",
     "दिन में समुद्री समीरण किस दिशा से बहती है?",
     "In the daytime the sea breeze blows —",
     ["समुद्र से स्थल की ओर", "स्थल से समुद्र की ओर", "ऊपर की ओर", "किसी भी दिशा में"],
     ["From the sea towards the land", "From the land towards the sea", "Upwards", "In any direction"],
     0,
     "दिन में स्थल जल्दी गर्म → हवा उठती → ठंडी समुद्री हवा भरती है।",
     "Land heats fast by day → air rises → cool sea air moves in."),

    ("heat-transfer", "easy",
     "रात में स्थलीय समीरण किस दिशा से बहती है?",
     "At night the land breeze blows —",
     ["स्थल से समुद्र की ओर", "समुद्र से स्थल की ओर", "नीचे की ओर", "कहीं नहीं"],
     ["From the land towards the sea", "From the sea towards the land", "Downwards", "Nowhere"],
     0,
     "रात में स्थल जल्दी ठंडा → समुद्र की गर्म हवा उठती → स्थल से ठंडी हवा जाती है।",
     "Land cools fast at night → warm sea air rises → cool air flows out from land."),

    ("heat-transfer", "easy",
     "काली सतह विकिरण के प्रति कैसी होती है?",
     "How does a black surface behave towards radiation?",
     ["अच्छी अवशोषक (और उत्सर्जक)", "अच्छी परावर्तक", "उदासीन", "विकिरण रोकती है"],
     ["A good absorber (and emitter)", "A good reflector", "Indifferent", "It blocks radiation"],
     0,
     "गहरा रंग विकिरण सोख लेता है; सफेद चमक परावर्तित करती है।",
     "Dark colours absorb radiation; shiny white reflects it."),

    ("heat-transfer", "easy",
     "थर्मोस फ्लास्क का काम क्या है?",
     "What is the job of a thermos flask?",
     ["ऊष्मा संचरण को रोककर पेय का ताप बनाए रखना", "पेय को गर्म करना", "पेय को ठंडा करना", "पेय उबालना"],
     ["To stop heat transfer and keep the drink's temperature steady", "To heat the drink", "To chill the drink", "To boil the drink"],
     0,
     "फ्लास्क तीनों विधियाँ (चालन, संवहन, विकिरण) रोकती है।",
     "The flask blocks all three modes (conduction, convection, radiation)."),

    # ---- medium (16) ----
    ("heat-transfer", "medium",
     "दिन में समुद्री समीरण चलने का कारण-क्रम है —",
     "The causal chain behind the daytime sea breeze is —",
     ["स्थल तेज़ गर्म → वहाँ की हवा उठती → समुद्र की ठंडी हवा स्थल की ओर", "समुद्र तेज़ गर्म → हवा समुद्र से उठती", "स्थल ठंडा → हवा नीचे उतरती", "सूर्य स्थल पर विकिरण नहीं करता"],
     ["Land heats quickly → its air rises → cool sea air flows landward", "The sea heats fast → air rises from the sea", "Land cools → air sinks", "The sun radiates nothing onto land"],
     0,
     "स्थल की गर्म हल्की हवा संवहन से उठती है और समुद्र की ठंडी हवा जगह लेती है।",
     "Warm light air over land rises by convection and cool sea air takes its place."),

    ("heat-transfer", "medium",
     "रात में दिशा उलट क्यों जाती है?",
     "Why does the breeze reverse at night?",
     ["रात में स्थल जल्दी ठंडा, समुद्र अपेक्षाकृत गर्म → समुद्र की हवा उठती, स्थल से ठंडी हवा जाती है", "रात में समुद्र जम जाता है", "सूर्य रात में ठंडा करता है", "हवा की दिशा स्थिर होती है"],
     ["At night land cools fast while the sea stays warmer → sea air rises and cool land air flows out", "The sea freezes at night", "The sun cools at night", "Wind direction is fixed"],
     0,
     "जल धीरे गर्म/ठंडा होता है — रात में वही अपेक्षाकृत गर्म रहता है।",
     "Water warms and cools slowly — at night it stays relatively warm."),

    ("heat-transfer", "medium",
     "ठोस में संवहन क्यों नहीं होता?",
     "Why does convection not occur in solids?",
     ["ठोस के कण स्थान नहीं बदल सकते", "ठोस में ऊष्मा नहीं होती", "ठोस संघनित गैस है", "ठोस में कण नहीं होते"],
     ["The particles of a solid cannot change places", "Solids hold no heat", "A solid is condensed gas", "Solids lack particles"],
     0,
     "संवहन के लिए कणों का बहाव चाहिए — ठोस में कण जड़े रहते हैं।",
     "Convection needs flowing particles — in solids they are fixed."),

    ("heat-transfer", "medium",
     "वायु और जल कुचालक हैं, फिर भी कमरा/बर्तन गर्म हो जाता है — कारण —",
     "Air and water are bad conductors, yet a room or a vessel gets warm — because —",
     ["उनमें संवहन धाराएँ ऊष्मा फैला देती हैं", "वे सुचालक बन जाते हैं", "विकिरण से ठोस हो जाते हैं", "कुचालक होना अफवाह है"],
     ["Convection currents within them spread the heat", "They turn into conductors", "Radiation solidifies them", "Their being insulators is a rumour"],
     0,
     "कुचालक तरल/गैस में संवहन ही ऊष्मा वहन करता है।",
     "In an insulating fluid or gas, convection carries the heat."),

    ("heat-transfer", "medium",
     "कमरे का हीटर फर्श के पास रखना चाहिए — क्यों?",
     "Why should a room heater be placed near the floor?",
     ["गर्म हवा उठती है और ठंडी नीचे आती — संवहन चक्र पूरा कमरा गर्म करता है", "फर्श गर्म होता है", "दीवार ठंडी होती है", "छत टूट जाती है"],
     ["Hot air rises and cold descends — the convection loop warms the whole room", "The floor gets hot", "The wall is cold", "The ceiling breaks"],
     0,
     "नीचे से गर्म करने पर संवहन धारा पूरे कमरे में चक्कर लगाती है।",
     "Heating from below sets a convection loop circling the whole room."),

    ("heat-transfer", "medium",
     "एसी/कूलर का वेंट ऊपर की दीवार पर क्यों लगाया जाता है?",
     "Why is an AC vent mounted high on the wall?",
     ["ठंडी हवा भारी होकर नीचे उतरती है — पूरा कमरा ठंडा होता है", "ठंडी हवा उपर उठती है", "छत गर्म होती है", "वेंट नीचे नहीं लग सकता"],
     ["Cold air is heavy and sinks — the whole room cools", "Cold air rises", "The ceiling is hot", "A vent cannot be lower"],
     0,
     "ठंडी सघन हवा नीचे बैठती है — ऊपर से ठंडक फैलती है।",
     "Dense cold air settles down — cooling spreads from the top."),

    ("heat-transfer", "medium",
     "ईंटें खोखली क्यों बनाई जाती हैं?",
     "Why are bricks made hollow?",
     ["भीतर बंद हवा कुचालक है — घर गर्म/ठंडा रहता है", "ईंट हल्की लगे", "गारा बचता है", "रंग सुंदर लगे"],
     ["The trapped air is a bad conductor — the house stays warm or cool", "The brick looks light", "Mortar is saved", "The colour looks nice"],
     0,
     "हवा का जाल ही उष्मारोधण करता है।",
     "The air pocket itself provides the insulation."),

    ("heat-transfer", "medium",
     "बर्फ के डिब्बे (freezer) में बर्फ ऊपर के कम्पार्टमेंट में क्यों रखते हैं?",
     "Why is the freezer compartment placed at the top in a fridge?",
     ["ठंडी हवा नीचे उतरकर पूरा डिब्बा ठंडा करती है", "नीचे रखने पर गिर जाती", "ऊपर जगह कम होती है", "प्रकाश ऊपर होता है"],
     ["The cold air sinks and cools the entire cabinet", "It would fall if placed low", "Less space above", "The light is up there"],
     0,
     "ऊपर ठंडा → संवहन से नीचे फैलता है।",
     "Cold at the top → convection spreads it downward."),

    ("heat-transfer", "medium",
     "गर्मियों में सफेद/हल्के रंग के कपड़े क्यों पहनते हैं?",
     "Why are white or light-coloured clothes worn in summer?",
     ["वे सूर्य का विकिरण परावर्तित कर देते हैं — कम गर्मी", "वे हवा देते हैं", "वे भारी होते हैं", "वे पसीना पीते हैं"],
     ["They reflect the sun's radiation — less heating", "They supply air", "They are heavy", "They drink sweat"],
     0,
     "सफेद परावर्तक, काला अवशोषक — गर्मी में सफेद ठंडक।",
     "White reflects, black absorbs — white keeps you cool."),

    ("heat-transfer", "medium",
     "थर्मोस फ्लास्क की दोहरी दीवार के बीच वायु निकाली जाती है — कारण —",
     "The air between a flask's double walls is removed — because —",
     ["निर्वात चालन व संवहन दोनों रोक देता है", "हवा भारी होती है", "कांच टूटता है", "विकिरण बढ़ता है"],
     ["The vacuum stops both conduction and convection", "Air is heavy", "Glass breaks", "Radiation increases"],
     0,
     "कण ही नहीं → चालन/संवहन असंभव; चांदी की परत विकिरण रोकती है।",
     "No particles → no conduction or convection; the silver coat checks radiation."),

    ("heat-transfer", "medium",
     "अंगीठी के पास बैठे चेहरे को गर्मी कैसे मिलती है?",
     "Sitting near a fire, how does your face receive the warmth?",
     ["मुख्यतः विकिरण से", "चालन से", "संवहन से", "वाष्पीकरण से"],
     ["Mainly by radiation", "By conduction", "By convection", "By evaporation"],
     0,
     "हवा से पहले तरंगें पहुँचती हैं — विकिरण का अनुभव।",
     "The waves arrive ahead of the air — the feel of radiation."),

    ("heat-transfer", "medium",
     "बर्तन धातु के और हत्थे लकड़ी/प्लास्टिक के — कारण —",
     "Cooking vessels are metal but their handles wood or plastic — because —",
     ["धातु सुचालक (खाना जल्दी), हत्था कुचालक (हाथ सुरक्षित)", "धातु सस्ती है", "लकड़ी सुंदर है", "धातु भारी होती है"],
     ["Metal conducts well (fast cooking) while the handle insulates (safe grip)", "Metal is cheap", "Wood is beautiful", "Metal is heavy"],
     0,
     "एक ही वस्तु में सुचालक+कुचालक का बुद्धिमान मेल।",
     "A smart pairing of conductor and insulator in one object."),

    ("heat-transfer", "medium",
     "गर्मी में घर की छत पर सफेद चूना पोतने का लाभ —",
     "Whitewashing the roof in summer helps because —",
     ["सफेद सतह सौर विकिरण परावर्तित कर कम गर्म करती है", "चूना ठंडा उत्पन्न करता है", "छत भारी होती है", "बरसात भाग जाती है"],
     ["The white surface reflects solar radiation and heats less", "Lime generates cold", "The roof gets heavy", "Rain runs off"],
     0,
     "परावर्तन बढ़ा → अवशोषण घटा → घर ठंडा।",
     "More reflection → less absorption → a cooler home."),

    ("heat-transfer", "medium",
     "कथन A: चालन के लिए माध्यम आवश्यक है। कथन B: विकिरण निर्वात में भी होता है। सही विकल्प —",
     "Statement A: conduction requires a medium. Statement B: radiation occurs even in vacuum. The correct option —",
     ["A और B दोनों सही", "केवल A सही", "केवल B सही", "दोनों गलत"],
     ["Both A and B are right", "Only A is right", "Only B is right", "Both are wrong"],
     0,
     "चालन/संवहन को कण चाहिए; विकिरण को नहीं — दोनों कथन सही।",
     "Conduction and convection need particles; radiation does not — both hold."),

    ("heat-transfer", "medium",
     "जल को नीचे से गर्म करने पर ऊपर का जल भी गर्म हो जाता है पर ऊपर से गर्म करने पर नीचे का जल ठंडा रह जाता है — कारण —",
     "Water heated from below warms throughout, but heated from above the lower water stays cool — because —",
     ["गर्म जल हल्का ऊपर रहता है, नीचे उतरने का संवहन चक्र नहीं बनता", "नीचे का जल जमा होता है", "ऊपर विकिरण नहीं होता", "जल सुचालक है"],
     ["Warm water stays light at the top — no convection loop forms to carry heat down", "The bottom water is frozen", "No radiation above", "Water is a good conductor"],
     0,
     "संवहन को नीचे से गर्म करना पड़ता है — ऊपर से गर्म करने पर चक्र अपने आप नहीं बनता।",
     "Convection must be driven from below — top heating never starts the loop."),

    ("heat-transfer", "medium",
     "समुद्र-स्थल क्यों तेज़ गर्म/ठंडा होते हैं जबकि जल धीमा?",
     "Why do land and sea surfaces heat and cool at different rates?",
     ["जल की विशिष्ट ऊष्मा अधिक — वह धीरे गर्म और धीरे ठंडा होता है", "स्थल में अधिक ऊर्जा होती है", "जल विकिरण नहीं सोखता", "स्थल के कण तेज़ चलते हैं"],
     ["Water's specific heat is higher — it warms and cools slowly", "Land holds more energy", "Water absorbs no radiation", "Land's particles move faster"],
     0,
     "विशिष्ट ऊष्मा का अंतर ही समीरण-चक्र का मूल कारण है।",
     "The specific-heat difference is the root cause of the breeze cycle."),

    # ---- hard (7) ----
    ("heat-transfer", "hard",
     "निर्वात में ऊष्मा संचरण की कौन-सी विधियाँ संभव हैं?",
     "Which modes of heat transfer are possible in vacuum?",
     ["केवल विकिरण", "चालन और विकिरण", "संवहन और विकिरण", "तीनों"],
     ["Only radiation", "Conduction and radiation", "Convection and radiation", "All three"],
     0,
     "बिना कण के चालन-संवहन असंभव — केवल विकिरण।",
     "Without particles conduction and convection fail — radiation alone."),

    ("heat-transfer", "hard",
     "थर्मोस फ्लास्क में — (i) निर्वात (ii) चांदी की परत — क्रमशः क्या रोकते हैं?",
     "In a thermos flask — (i) the vacuum (ii) the silver coating — respectively stop what?",
     ["(i) चालन+संवहन, (ii) विकिरण", "(i) विकिरण, (ii) चालन", "(i) संवहन, (ii) चालन", "(i) सब, (ii) कुछ नहीं"],
     ["(i) conduction + convection, (ii) radiation", "(i) radiation, (ii) conduction", "(i) convection, (ii) conduction", "(i) everything, (ii) nothing"],
     0,
     "निर्वात कण-माध्यम खत्म; चमकदार परत विकिरण परावर्तित करती है।",
     "The vacuum removes the particle medium; the mirror coat reflects radiation."),

    ("heat-transfer", "hard",
     "धातु की छड़ के एक सिरे पर मोम कागज चिपके हैं — गर्म करने पर सबसे पहले कौन-सा गिरेगा?",
     "Wax papers are stuck along a metal rod — on heating one end, which falls first?",
     ["गर्म सिरे के सबसे पास वाला", "मध्य वाला", "ठंडे सिरे वाला", "एक साथ सब"],
     ["The one nearest the heated end", "The middle one", "The far-end one", "All together"],
     0,
     "चालन में ऊष्मा क्रमशः आगे बढ़ती है — पास वाला पहले गर्म।",
     "Conduction carries heat onward stepwise — the nearest paper heats first."),

    ("heat-transfer", "hard",
     "कथन A: संवहन केवल द्रवों और गैसों में होता है। कथन B: विकिरण के लिए माध्यम वैकल्पिक है। सही विकल्प —",
     "Statement A: convection happens only in liquids and gases. Statement B: for radiation a medium is optional. The correct option —",
     ["A और B दोनों सही", "केवल A सही", "केवल B सही", "दोनों गलत"],
     ["Both A and B are right", "Only A is right", "Only B is right", "Both are wrong"],
     0,
     "ठोस में प्रवाह नहीं → संवहन नहीं; विकिरण स्वतंत्र — दोनों सही।",
     "Solids cannot flow → no convection; radiation is independent — both right."),

    ("heat-transfer", "hard",
     "समुद्र तट पर दिन में मछुआरे अपनी नाव समुद्र की ओर ले जाते हैं — इसका ऊष्मा-आधार —",
     "Fishermen sail out to sea by day — the heat-based reasoning is —",
     ["दिन की समुद्री समीरण (समुद्र → स्थल) नाव को समुद्र से खींचती है", "स्थलीय समीरण खींचती है", "समुद्र गर्म होता है", "विकिरण नाव धकेलता है"],
     ["The daytime sea breeze (sea → land) carries the boat seaward first", "The land breeze pulls it", "The sea is hotter", "Radiation pushes the boat"],
     0,
     "दिन में समुद्री समीरण समुद्र से तट की ओर — तट छोड़ते समय पाल सहायक।",
     "By day the sea breeze blows sea → land — helpful when leaving the coast."),

    ("heat-transfer", "hard",
     "एक ही ताप पर चमकदार और काली चाय-केतली — किसमें चाय जल्दी ठंडी होगी?",
     "At the same temperature, a shiny and a black kettle — whose tea cools faster?",
     ["काली — विकिरण देने में भी अच्छी", "चमकदार", "दोनों समान", "निर्भर नहीं"],
     ["The black one — it is also a good emitter of radiation", "The shiny one", "Both equally", "It does not depend"],
     0,
     "काली सतह अवशोषक और उत्सर्जक दोनों अच्छी — गर्म चाय की ऊष्मा तेज़ विकिरित।",
     "A black surface is both a good absorber and emitter — the hot tea radiates away faster."),

    ("heat-transfer", "hard",
     "दो एक-जैसे चम्मच — एक धातु, एक लकड़ी — उबलते पानी में 5 मिनट — बाहर निकालकर पकड़ने पर —",
     "Two similar spoons — one metal, one wood — kept 5 minutes in boiling water — on grabbing them —",
     ["धातु गर्म लगेगी (चालन से ऊष्मा पूरे चम्मच में), लकड़ी ठंडी (कुचालक)", "दोनों समान गर्म", "लकड़ी अधिक गर्म", "दोनों ठंडी"],
     ["The metal feels hot (conduction all along), the wood cool (insulator)", "Both equally hot", "The wood is hotter", "Both cool"],
     0,
     "पानी का ताप समान होने पर भी संचरण-क्षमता का अंतर अनुभव होता है।",
     "Though the water's temperature is the same, the difference in conduction is felt."),
]
