# -*- coding: utf-8 -*-
"""P06 (Heat & Temperature) — Part 2: change-of-state (37) + evaporation-cooling (37) = 74 tuples.
All items authored with correct_idx=0; rotation happens in gen_p06_questions.py.

T3 change-of-state     37 = E15/M16/H6
T4 evaporation-cooling 37 = E14/M17/H6
"""

PART2 = [
    # ================= CHANGE OF STATE (37) =================
    # ---- easy (15) ----
    ("change-of-state", "easy",
     "अवस्था परिवर्तन किसे कहते हैं?",
     "What is a change of state?",
     ["ऊष्मा देने/लेने पर पदार्थ का ठोस-द्रव-गैस रूप में बदलना", "पदार्थ का रंग बदलना", "पदार्थ का भार बदलना", "पदार्थ का आकार बदलना"],
     ["A substance turning solid-liquid-gas under heat exchange", "A change of colour", "A change of weight", "A change of shape"],
     0,
     "गलन/क्वथन/जमन/संघनन — अवस्था परिवर्तन के नाम हैं।",
     "Melting, boiling, freezing and condensation are the changes of state."),

    ("change-of-state", "easy",
     "पिघलते समय बर्फ का ताप —",
     "While ice is melting, its temperature —",
     ["स्थिर रहता है", "बढ़ता रहता है", "घटता रहता है", "पहले बढ़ता फिर घटता"],
     ["Stays constant", "Keeps rising", "Keeps falling", "Rises first then falls"],
     0,
     "दी गई ऊष्मा गुप्त ऊष्मा बनती है — ताप 0 °C पर रुका रहता है।",
     "The supplied heat becomes latent heat — the temperature holds at 0 °C."),

    ("change-of-state", "easy",
     "उबलते समय जल का ताप —",
     "While water is boiling, its temperature —",
     ["स्थिर रहता है (100 °C पर)", "लगातार बढ़ता है", "घटता है", "शून्य हो जाता है"],
     ["Stays constant (at 100 °C)", "Keeps rising", "Falls", "Becomes zero"],
     0,
     "क्वथनांक पर सारी ऊष्मा वाष्पीकरण में जाती है — ताप स्थिर।",
     "At the boiling point all heat goes into vaporisation — steady temperature."),

    ("change-of-state", "easy",
     "गुप्त ऊष्मा किसे कहते हैं?",
     "What is latent heat?",
     ["अवस्था परिवर्तन के समय बिना ताप बढ़ाए दी/ली गई ऊष्मा", "ताप बढ़ाने वाली ऊष्मा", "खोई हुई ऊष्मा", "छिपाई गई ऊर्जा"],
     ["The heat given or taken during a change of state without any rise in temperature", "Heat that raises temperature", "Lost heat", "Hidden energy"],
     0,
     "गुप्त = छिपा हुआ — थर्मामीटर में न दिखने वाली ऊष्मा।",
     "Latent = hidden — heat that never shows on the thermometer."),

    ("change-of-state", "easy",
     "बर्फ के पिघलने की गुप्त ऊष्मा कितनी होती है?",
     "What is the latent heat of melting of ice?",
     ["80 cal/g", "540 cal/g", "100 cal/g", "1 cal/g"],
     ["80 cal/g", "540 cal/g", "100 cal/g", "1 cal/g"],
     0,
     "1 ग्राम बर्फ 0 °C पर पिघलने में 80 कैलोरी लेती है।",
     "One gram of ice takes 80 calories to melt at 0 °C."),

    ("change-of-state", "easy",
     "जल के क्वथन (वाष्पीकरण) की गुप्त ऊष्मा —",
     "The latent heat of vaporisation of water is —",
     ["540 cal/g", "80 cal/g", "100 cal/g", "5400 cal/g"],
     ["540 cal/g", "80 cal/g", "100 cal/g", "5400 cal/g"],
     0,
     "1 ग्राम जल 100 °C पर भाप बनने में 540 कैलोरी लेता है।",
     "One gram of water takes 540 calories to turn into steam at 100 °C."),

    ("change-of-state", "easy",
     "वाष्पीकरण किसे कहते हैं?",
     "What is evaporation?",
     ["किसी भी ताप पर द्रव की सतह से गैस बनना", "केवल 100 °C पर गैस बनना", "गैस का द्रव बनना", "द्रव का जमना"],
     ["A liquid turning gas at its surface at any temperature", "Turning gas only at 100 °C", "A gas turning liquid", "A liquid freezing"],
     0,
     "सतह के अणु ऊर्जा लेकर उड़ते हैं — वाष्पीकरण।",
     "Surface molecules escape with energy — evaporation."),

    ("change-of-state", "easy",
     "संघनन किसे कहते हैं?",
     "What is condensation?",
     ["गैस का द्रव में बदलना", "द्रव का गैस बनना", "द्रव का ठोस बनना", "ठोस का द्रव बनना"],
     ["A gas turning into a liquid", "A liquid turning gas", "A liquid turning solid", "A solid turning liquid"],
     0,
     "ठंडी सतह पर जलवाष्प का बूँदों में बदलना संघनन है।",
     "Water vapour turning into drops on a cold surface is condensation."),

    ("change-of-state", "easy",
     "जमना (हिमीकरण) किस अवस्था परिवर्तन है?",
     "Freezing is which change of state?",
     ["द्रव → ठोस", "ठोस → द्रव", "द्रव → गैस", "गैस → द्रव"],
     ["Liquid → solid", "Solid → liquid", "Liquid → gas", "Gas → liquid"],
     0,
     "ऊष्मा निकालने पर द्रव जमकर ठोस बनता है।",
     "Removing heat freezes a liquid into a solid."),

    ("change-of-state", "easy",
     "पिघलती बर्फ हाथ पर जल की तुलना में अधिक ठंडक क्यों देती है?",
     "Why does melting ice feel colder on the hand than water?",
     ["पिघलने में वह हाथ से गुप्त ऊष्मा खींच लेती है", "बर्फ हल्की होती है", "बर्फ सफेद होती है", "जल गर्म होता है"],
     ["While melting it draws latent heat from the hand", "Ice is lighter", "Ice is white", "Water is warm"],
     0,
     "0 °C बर्फ पिघलते हुए त्वचा से ऊष्मा चुराती रहती है।",
     "Melting 0 °C ice keeps stealing heat from the skin."),

    ("change-of-state", "easy",
     "100 °C की भाप 100 °C के जल से अधिक जला देती है — कारण —",
     "Steam at 100 °C scalds worse than water at 100 °C — because —",
     ["भाप में 540 cal/g गुप्त ऊष्मा अतिरिक्त होती है", "भाप गर्म होती है", "जल ठंडा होता है", "भाप हल्की होती है"],
     ["Steam carries an extra 540 cal/g of latent heat", "Steam is hotter", "Water is cold", "Steam is light"],
     0,
     "ताप समान, पर भाप की कुल ऊर्जा गुप्त ऊष्मा से कहीं अधिक।",
     "Same temperature, but steam's total energy is far higher due to latent heat."),

    ("change-of-state", "easy",
     "सामान्य दाब पर उबलता जल 100 °C से ऊपर क्यों नहीं जाता?",
     "At normal pressure why does boiling water not go above 100 °C?",
     ["अतिरिक्त ऊष्मा भाप बनाने में लग जाती है", "जल ठंडा हो जाता है", "बर्तन टूट जाता है", "ताप नापा नहीं जा सकता"],
     ["The extra heat goes into making steam", "The water cools", "The vessel breaks", "Temperature cannot be measured"],
     0,
     "क्वथनांक पर सारी नई ऊष्मा गुप्त रूप में जाती है।",
     "At the boiling point all new heat turns latent."),

    ("change-of-state", "easy",
     "पहाड़ों पर जल समुद्र तल से कम ताप पर उबलता है — कारण —",
     "On mountains water boils below 100 °C — because —",
     ["वायुमंडलीय दाब कम होने से क्वथनांक घट जाता है", "वहाँ ठंड अधिक है", "वहाँ जल शुद्ध है", "वहाँ गैस नहीं होती"],
     ["Lower atmospheric pressure lowers the boiling point", "It is colder there", "The water is purer", "There is no gas there"],
     0,
     "दाब घटा → अणु जल्दी उड़ते हैं → कम ताप पर क्वथन।",
     "Less pressure → molecules escape sooner → boiling at lower temperature."),

    ("change-of-state", "easy",
     "गर्म चीज़ को छूने से पहले भाप की अहटकारी आवाज़? नहीं — सीधा प्रश्न: क्वथन के समय बुलबुले कहाँ बनते हैं?",
     "During boiling, where do the bubbles form?",
     ["द्रव के भीतर (तल व आंतरिक भाग में)", "केवल सतह पर", "बर्तन के बाहर", "हवा में"],
     ["Inside the liquid (at the bottom and within)", "Only at the surface", "Outside the vessel", "In the air"],
     0,
     "क्वथन पूरे द्रव की आंतरिक घटना है — बुलबुले भीतर बनते हैं।",
     "Boiling is a bulk phenomenon — bubbles form within the liquid."),

    ("change-of-state", "easy",
     "गलनांक पर पदार्थ की कौन-सी दो अवस्थाएँ साथ-साथ रहती हैं?",
     "At the melting point, which two states of a substance coexist?",
     ["ठोस और द्रव", "द्रव और गैस", "ठोस और गैस", "कोई नहीं"],
     ["Solid and liquid", "Liquid and gas", "Solid and gas", "None"],
     0,
     "गलनांक पर ठोस पिघलता और द्रव जमता रहता है — साम्य।",
     "At the melting point solid melts and liquid freezes — an equilibrium."),

    # ---- medium (16) ----
    ("change-of-state", "medium",
     "10 g बर्फ पिघलाने में आवश्यक ऊष्मा (0 °C पर) —",
     "The heat needed to melt 10 g of ice (at 0 °C) is —",
     ["800 cal", "80 cal", "5400 cal", "8 cal"],
     ["800 cal", "80 cal", "5400 cal", "8 cal"],
     0,
     "Q = 10 × 80 = 800 cal।",
     "Q = 10 × 80 = 800 cal."),

    ("change-of-state", "medium",
     "20 g बर्फ पिघलने के लिए ऊष्मा —",
     "The heat required to melt 20 g of ice is —",
     ["1600 cal", "100 cal", "160 cal", "5400 cal"],
     ["1600 cal", "100 cal", "160 cal", "5400 cal"],
     0,
     "Q = 20 × 80 = 1600 cal।",
     "Q = 20 × 80 = 1600 cal."),

    ("change-of-state", "medium",
     "5 g जल को 100 °C पर पूरी तरह भाप बनाने में ऊष्मा —",
     "The heat to turn 5 g of water fully into steam at 100 °C is —",
     ["2700 cal", "540 cal", "500 cal", "270 cal"],
     ["2700 cal", "540 cal", "500 cal", "270 cal"],
     0,
     "Q = 5 × 540 = 2700 cal।",
     "Q = 5 × 540 = 2700 cal."),

    ("change-of-state", "medium",
     "10 g भाप के संघनित होने पर दी गई ऊष्मा —",
     "The heat released when 10 g of steam condenses is —",
     ["5400 cal", "800 cal", "540 cal", "54000 cal"],
     ["5400 cal", "800 cal", "540 cal", "54000 cal"],
     0,
     "Q = 10 × 540 = 5400 cal (संघनन में गुप्त ऊष्मा मुक्त)।",
     "Q = 10 × 540 = 5400 cal (latent heat released on condensing)."),

    ("change-of-state", "medium",
     "50 g जल 100 °C पर पूरा वाष्पित हो तो ली गई ऊष्मा —",
     "If 50 g of water at 100 °C fully vaporises, the heat taken is —",
     ["27,000 cal", "4000 cal", "5000 cal", "2700 cal"],
     ["27,000 cal", "4000 cal", "5000 cal", "2700 cal"],
     0,
     "Q = 50 × 540 = 27,000 cal।",
     "Q = 50 × 540 = 27,000 cal."),

    ("change-of-state", "medium",
     "बर्फ+जल का मिश्रण गर्म करने पर सारी बर्फ पिघलने तक ताप —",
     "On heating an ice + water mixture, until all the ice melts the temperature —",
     ["0 °C ही रहता है", "तेज़ी से बढ़ता है", "घटता है", "100 °C हो जाता है"],
     ["Stays at 0 °C", "Rises rapidly", "Falls", "Shoots to 100 °C"],
     0,
     "पहले सारी बर्फ गुप्त ऊष्मा लेकर पिघलती है, तब तक ताप स्थिर।",
     "First all the ice absorbs latent heat and melts — the temperature holds."),

    ("change-of-state", "medium",
     "उबलते जल को और तेज़ गर्म करें तो ताप —",
     "If boiling water is heated even harder, the temperature —",
     ["100 °C पर ही रहता है, वाष्पीकरण तेज़ होता है", "100 से ऊपर चला जाता है", "घट जाता है", "0 °C हो जाता है"],
     ["Stays at 100 °C while evaporation speeds up", "Climbs above 100 °C", "Falls", "Drops to 0 °C"],
     0,
     "अतिरिक्त ऊष्मा और भाप बनाती है, ताप नहीं बढ़ता।",
     "Extra heat just makes more steam, not higher temperature."),

    ("change-of-state", "medium",
     "1 kg बर्फ पिघलाने में कुल ऊष्मा —",
     "The total heat to melt 1 kg of ice is —",
     ["80,000 cal (80 kcal)", "800 cal", "540 kcal", "8000 cal"],
     ["80,000 cal (80 kcal)", "800 cal", "540 kcal", "8000 cal"],
     0,
     "1000 g × 80 = 80,000 cal।",
     "1000 g × 80 = 80,000 cal."),

    ("change-of-state", "medium",
     "पिघलती बर्फ का ताप स्थिर क्यों रहता है?",
     "Why does melting ice hold a steady temperature?",
     ["दी गई ऊष्मा अणु-बंध तोड़ने में (गुप्त ऊष्मा) लग जाती है", "ऊष्मा बाहर निकल जाती है", "बर्फ ऊष्मा नहीं लेती", "थर्मामीटर गलत होता है"],
     ["The supplied heat is used up breaking molecular bonds (latent heat)", "The heat leaks out", "Ice absorbs nothing", "The thermometer is wrong"],
     0,
     "गुप्त ऊष्मा अवस्था बदलती है, ताप नहीं।",
     "Latent heat changes the state, not the temperature."),

    ("change-of-state", "medium",
     "2 kg जल को 30 °C से 100 °C गर्म करने में ऊष्मा —",
     "The heat needed to warm 2 kg of water from 30 °C to 100 °C is —",
     ["140,000 cal (140 kcal)", "14,000 cal", "2000 cal", "70,000 cal"],
     ["140,000 cal (140 kcal)", "14,000 cal", "2000 cal", "70,000 cal"],
     0,
     "Q = 2000 × 1 × 70 = 140,000 cal।",
     "Q = 2000 × 1 × 70 = 140,000 cal."),

    ("change-of-state", "medium",
     "क्वथन और वाष्पीकरण में मुख्य अंतर —",
     "The main difference between boiling and evaporation is —",
     ["क्वथन पूरे द्रव में निश्चित ताप पर, वाष्पीकरण सतह पर किसी भी ताप पर", "दोनों एक ही हैं", "वाष्पीकरण तेज़ होता है", "क्वथन सतह पर होता है"],
     ["Boiling occurs through the liquid at a fixed temperature; evaporation at the surface at any temperature", "Both are identical", "Evaporation is faster", "Boiling happens at the surface"],
     0,
     "क्वथन = थोक + निश्चित ताप; वाष्पीकरण = सतह + सभी ताप।",
     "Boiling = bulk + fixed temperature; evaporation = surface + any temperature."),

    ("change-of-state", "medium",
     "कथन A: पिघलने में ताप स्थिर रहता है। कथन B: पिघलने में ऊष्मा शोषित होती है। सही विकल्प —",
     "Statement A: during melting the temperature stays constant. Statement B: during melting heat is absorbed. The correct option —",
     ["A और B दोनों सही", "केवल A सही", "केवल B सही", "दोनों गलत"],
     ["Both A and B are right", "Only A is right", "Only B is right", "Both are wrong"],
     0,
     "ताप स्थिर + ऊष्मा शोषण = गुप्त ऊष्मा की परिभाषा।",
     "Steady temperature + absorbed heat = latent heat by definition."),

    ("change-of-state", "medium",
     "प्रेशर कुकर में खाना जल्दी क्यों पकता है?",
     "Why does food cook faster in a pressure cooker?",
     ["दाब बढ़ने से जल 100 °C से ऊपर उबलता है", "कुकर में जल अधिक होता है", "कुकर धातु का होता है", "वहाँ विकिरण होता है"],
     ["Higher pressure makes water boil above 100 °C", "The cooker holds more water", "The cooker is metallic", "Radiation happens there"],
     0,
     "बढ़ा दाब → बढ़ा क्वथनांक → अधिक ताप पर पकाना।",
     "More pressure → higher boiling point → cooking at a hotter temperature."),

    ("change-of-state", "medium",
     "बर्फ में नमक मिलाने पर मिश्रण का गलनांक —",
     "Mixing salt into ice makes the mixture's melting point —",
     ["घट जाता है (ठंडा मिश्रण बनता है)", "बढ़ जाता है", "समान रहता है", "0 °C हो जाता है"],
     ["Falls (a freezing mixture forms)", "Rises", "Stays unchanged", "Becomes exactly 0 °C"],
     0,
     "नमक गलनांक नीचे लाता है — आइसक्रीम बनाने में उपयोग।",
     "Salt depresses the melting point — used in making ice cream."),

    ("change-of-state", "medium",
     "गलनांक पर बर्फ को ऊष्मा देते रहने पर घटनाक्रम होगा —",
     "On continuously heating ice at its melting point, the sequence is —",
     ["पहले सारी बर्फ 0 °C पर पिघलेगी, फिर जल का ताप बढ़ेगा", "ताप तुरंत बढ़ेगा", "बर्फ सीधे भाप बनेगी", "जल जम जाएगा"],
     ["First all the ice melts at 0 °C, then the water's temperature rises", "The temperature jumps at once", "Ice turns directly to steam", "The water freezes"],
     0,
     "गुप्त ऊष्मा पहले पूरी, ताप-वृद्धि बाद में।",
     "Latent heat first, temperature rise afterwards."),

    ("change-of-state", "medium",
     "भाप से जलने की गंभीरता जल से अधिक — संख्यात्मक आधार (1 g के लिए) —",
     "Steam scalds more severely than water — the numerical basis (per 1 g) is —",
     ["भाप में 540 cal अतिरिक्त गुप्त ऊष्मा", "भार 540 गुना", "ताप 540 °C", "घनत्व 540 गुना"],
     ["Steam holds 540 cal of extra latent heat", "540 times the weight", "540 °C of temperature", "540 times the density"],
     0,
     "संघनित होते हुए भाप त्वचा पर 540 cal/g छोड़ती है।",
     "Condensing on skin, steam releases 540 cal/g."),

    # ---- hard (6) ----
    ("change-of-state", "hard",
     "0 °C की बर्फ बनाम 0 °C का जल — पेय को ठंडा करने में कौन अधिक प्रभावी?",
     "0 °C ice versus 0 °C water — which cools a drink more effectively?",
     ["बर्फ — पिघलते हुए 80 cal/g अतिरिक्त लेती है", "जल — द्रव होने से", "दोनों समान", "कोई नहीं"],
     ["Ice — it draws an extra 80 cal/g while melting", "Water — being liquid", "Both equally", "Neither"],
     0,
     "समान ताप पर भी गुप्त ऊष्मा का फर्क बर्फ को अधिक शीतलक बनाता है।",
     "Even at equal temperature the latent-heat edge makes ice the better coolant."),

    ("change-of-state", "hard",
     "40 g बर्फ (0 °C) को पिघलाकर प्राप्त जल को 40 °C तक गर्म करने की कुल ऊष्मा —",
     "The total heat to melt 40 g of ice at 0 °C and then warm the water to 40 °C is —",
     ["4800 cal", "3200 cal", "1600 cal", "2400 cal"],
     ["4800 cal", "3200 cal", "1600 cal", "2400 cal"],
     0,
     "पिघलना: 40 × 80 = 3200; गर्म करना: 40 × 40 = 1600; कुल 4800 cal।",
     "Melting: 40 × 80 = 3200; warming: 40 × 40 = 1600; total 4800 cal."),

    ("change-of-state", "hard",
     "क्वथन के समय दी गई ऊर्जा का क्या होता है?",
     "What happens to the energy supplied during boiling?",
     ["अणुओं के बंधन तोड़ने में — गुप्त ऊष्मा", "ताप बढ़ाने में", "बर्तन गर्म करने में सब", "नष्ट हो जाती है"],
     ["It breaks the molecular bonds — as latent heat", "It raises the temperature", "It all heats the vessel", "It is destroyed"],
     0,
     "द्रव → गैस संक्रमण में अंतर-अणु बल तोड़ने पर ऊर्जा खर्च होती है।",
     "The energy goes into overcoming intermolecular attraction in liquid → gas."),

    ("change-of-state", "hard",
     "कथन A: 100 °C भाप में जितनी ऊर्जा उसी द्रव्यमान के 100 °C जल से अधिक है। कथन B: संघनन में यह अतिरिक्त ऊर्जा मुक्त हो जाती है। सही विकल्प —",
     "Statement A: steam at 100 °C holds more energy than the same mass of water at 100 °C. Statement B: on condensing this extra energy is released. The correct option —",
     ["A और B दोनों सही", "केवल A सही", "केवल B सही", "दोनों गलत"],
     ["Both A and B are right", "Only A is right", "Only B is right", "Both are wrong"],
     0,
     "गुप्त ऊष्मा भाप में संचित, संघनन पर मुक्त — दोनों सही।",
     "Latent heat is stored in steam and freed on condensing — both right."),

    ("change-of-state", "hard",
     "25 g जल 100 °C पर भाप में बदलने में ली गई ऊष्मा —",
     "The heat absorbed when 25 g of water at 100 °C turns to steam is —",
     ["13,500 cal", "2000 cal", "13,500 J", "2500 cal"],
     ["13,500 cal", "2000 cal", "13,500 J", "2500 cal"],
     0,
     "Q = 25 × 540 = 13,500 cal।",
     "Q = 25 × 540 = 13,500 cal."),

    ("change-of-state", "hard",
     "गर्मी के दिन बर्फ वाले पेय में बर्फ डालने पर पेय 0 °C तक क्यों और कब तक ठंडा होता रहता है?",
     "Why does an iced drink keep cooling down to 0 °C and hold there?",
     ["बर्फ पिघलते हुए पेय से गुप्त ऊष्मा लेती रहती है जब तक सारी बर्फ न घुले", "बर्फ जल में ठंडी हवा छोड़ती है", "बर्फ का रंग ठंडक देता है", "पेय स्वयं 0 °C पर पहुँच जाता है"],
     ["Melting ice keeps drawing latent heat from the drink until all of it dissolves", "Ice releases cold air into the drink", "Ice's colour gives coolness", "The drink reaches 0 °C on its own"],
     0,
     "सारी बर्फ पिघलने तक ताप 0 °C पर रुका रहता है।",
     "The temperature parks at 0 °C until the last ice has melted."),

    # ================= EVAPORATION & COOLING (37) =================
    # ---- easy (14) ----
    ("evaporation-cooling", "easy",
     "वाष्पीकरण से शीतलन क्यों होता है?",
     "Why does evaporation cause cooling?",
     ["सतह के अणु ऊष्मा लेकर उड़ते हैं — बचा द्रव ठंडा रह जाता है", "हवा ठंडी आती है", "द्रव जमता है", "रंग बदलता है"],
     ["Surface molecules escape taking heat — the remaining liquid cools", "Cold air arrives", "The liquid freezes", "The colour changes"],
     0,
     "उड़ने वाले अणु ऊर्जा साथ ले जाते हैं — औसत ऊर्जा घटती है।",
     "Escaping molecules carry energy away — the average energy drops."),

    ("evaporation-cooling", "easy",
     "पसीने से शरीर को ठंडक क्यों मिलती है?",
     "Why does sweat cool the body?",
     ["पसीना वाष्पित होते हुए त्वचा की ऊष्मा लेता है", "पसीना ठंडा होता है", "पसीना भारी होता है", "पसीना नमकीन होता है"],
     ["Evaporating sweat draws heat from the skin", "Sweat is cold by nature", "Sweat is heavy", "Sweat is salty"],
     0,
     "वाष्पीकरण की गुप्त ऊष्मा शरीर से आती है।",
     "The latent heat of evaporation comes from the body."),

    ("evaporation-cooling", "easy",
     "गीले कपड़े पहनने पर ठंडक —",
     "Wearing wet clothes feels cool because —",
     ["जल वाष्पित होते हुए शरीर से ऊष्मा लेता है", "कपड़े हल्के होते हैं", "पानी ठंडा होता है", "कपड़े सफेद होते हैं"],
     ["The evaporating water draws heat from the body", "The clothes are light", "Water is cold", "The clothes are white"],
     0,
     "वाष्पीकरण का शीतलन-प्रभाव।",
     "The cooling effect of evaporation."),

    ("evaporation-cooling", "easy",
     "मिट्टी के सुराही का जल ठंडा क्यों रहता है?",
     "Why does water in an earthen pot stay cool?",
     ["सुराही की दीवारों से जल रिसकर वाष्पित होता है — ऊष्मा निकलती है", "मिट्टी ठंडी होती है", "सुराही छाया में रहता है", "मिट्टी गहरे रंग की होती है"],
     ["Water seeps through the pot's pores and evaporates, carrying heat away", "The clay is cold", "The pot sits in shade", "The clay is dark"],
     0,
     "छिद्रों से वाष्पीकरण — सुराही का जल ठंडा।",
     "Evaporation through the pores keeps the pot's water cool."),

    ("evaporation-cooling", "easy",
     "खुली थाली का पानी गर्मी में धीरे-धीरे कम हो जाता है — कारण —",
     "Water in an open plate slowly disappears in summer — because of —",
     ["वाष्पीकरण", "क्वथन", "संघनन", "जमना"],
     ["Evaporation", "Boiling", "Condensation", "Freezing"],
     0,
     "सतह से अणु उड़ते रहते हैं।",
     "Molecules keep escaping from the surface."),

    ("evaporation-cooling", "easy",
     "स्प्रिट/एल्कोहल लगाने पर त्वचा ठंडी लगती है —",
     "The skin feels cold when spirit (alcohol) is applied because —",
     ["एल्कोहल बहुत तेज़ वाष्पित होता है", "एल्कोहल ठंडा होता है", "एल्कोहल गाढ़ा होता है", "त्वचा नम होती है"],
     ["Alcohol evaporates very fast", "Alcohol is cold", "Alcohol is thick", "The skin is moist"],
     0,
     "उड़नशील तरल जल्दी भागते हैं — तुरंत ठंडक।",
     "Volatile liquids escape quickly — instant coolness."),

    ("evaporation-cooling", "easy",
     "हवा चलने पर वाष्पीकरण —",
     "When wind blows, evaporation —",
     ["तेज़ हो जाता है", "धीमा हो जाता है", "बंद हो जाता है", "उलट दिशा में होता है"],
     ["Speeds up", "Slows down", "Stops", "Happens in reverse"],
     0,
     "हवा भाप को उड़ा लेती है — नई जगह बनती है।",
     "Wind sweeps the vapour away — fresh room for more."),

    ("evaporation-cooling", "easy",
     "कपड़े धूप में जल्दी सूखते हैं —",
     "Clothes dry faster in the sun because —",
     ["ताप अधिक → वाष्पीकरण तेज़", "धूप कपड़े देखती है", "हवा गर्म होती है", "कपड़े हल्के होते हैं"],
     ["Higher temperature → faster evaporation", "The sun watches the clothes", "The wind is warm", "The clothes are light"],
     0,
     "ताप बढ़ा → अणु ऊर्जा लेकर जल्दी उड़े।",
     "Higher temperature → molecules fly off sooner with energy."),

    ("evaporation-cooling", "easy",
     "पेड़ों के पत्ते गर्मी में ठंडे रहते हैं —",
     "Leaves stay cool in summer because —",
     ["पत्तों से जल वाष्पित (वाष्पोत्सर्जन) होता रहता है", "पत्ते हरे होते हैं", "पेड़ छाया देते हैं", "जड़ें ठंडी होती हैं"],
     ["Water keeps evaporating from the leaves (transpiration)", "The leaves are green", "Trees give shade", "The roots are cold"],
     0,
     "वाष्पोत्सर्जन = पौधों का वाष्पीकरण — शीतलन।",
     "Transpiration is the plant's evaporation — it cools."),

    ("evaporation-cooling", "easy",
     "दूध को पतली थाली में फैलाकर रखने पर जल्दी ठंडा होता है —",
     "Milk spread on a shallow plate cools quickly because —",
     ["सतह क्षेत्रफल बढ़ने से वाष्पीकरण तेज़", "थाली ठंडी होती है", "दूध पतला होता है", "थाली सफेद होती है"],
     ["A larger surface area speeds evaporation", "The plate is cold", "The milk is thin", "The plate is white"],
     0,
     "फैलाव → सतह बड़ी → अधिक अणु उड़ें।",
     "Spreading out → bigger surface → more escaping molecules."),

    ("evaporation-cooling", "easy",
     "वाष्पीकरण में द्रव किस अवस्था में बदलता है?",
     "In evaporation a liquid changes into which state?",
     ["गैस", "ठोस", "प्लाज़्मा", "कोई नहीं"],
     ["Gas", "Solid", "Plasma", "None"],
     0,
     "द्रव → गैस ही वाष्पीकरण है।",
     "Liquid → gas is what evaporation means."),

    ("evaporation-cooling", "easy",
     "ठंडी रात में घास पर ओस किस कारण बनती है?",
     "Dew on grass on a cold night forms by which process?",
     ["संघनन — जलवाष्प की बूँदें", "वाष्पीकरण", "क्वथन", "पिघलना"],
     ["Condensation — of water vapour into drops", "Evaporation", "Boiling", "Melting"],
     0,
     "ठंडी सतह पर वायु की जलवाष्प जमा हो जाती है।",
     "On cold surfaces the air's vapour settles into drops."),

    ("evaporation-cooling", "easy",
     "सर्दियों में मुँह से निकलती साँस 'धुएँ' जैसी दिखती है — कारण —",
     "In winter, exhaled breath looks like smoke because of —",
     ["संघनन — गर्म साँस की जलवाष्प ठंडी हवा में बूँदें", "वाष्पीकरण", "विकिरण", "दहन"],
     ["Condensation — the breath's vapour turns to drops in cold air", "Evaporation", "Radiation", "Combustion"],
     0,
     "गर्म जलवाष्प + ठंडी वायु = छोटी बूँदें।",
     "Warm vapour + cold air = tiny droplets."),

    ("evaporation-cooling", "easy",
     "गीले हाथ पर हवा फूँकने पर ठंडक —",
     "Blowing air over a wet hand feels cool because —",
     ["हवा वाष्पीकरण तेज़ कर देती है", "हवा ठंडी होती है", "हाथ सूख जाता है", "हवा गर्म होती है"],
     ["The air speeds up evaporation", "The air is cold", "The hand dries", "The air is warm"],
     0,
     "बहती हवा भाप हटाकर नए अणुओं को उड़ने देती है।",
     "Moving air removes vapour, letting more molecules escape."),

    # ---- medium (17) ----
    ("evaporation-cooling", "medium",
     "थाली और कटोरी में समान जल — वाष्पीकरण किसमें तेज़?",
     "Equal water in a plate and a bowl — in which does evaporation run faster?",
     ["थाली में (सतह क्षेत्रफल अधिक)", "कटोरी में", "दोनों समान", "निर्भर नहीं"],
     ["In the plate (larger surface area)", "In the bowl", "Both equal", "It does not depend"],
     0,
     "बड़ी सतह → एक साथ अधिक अणु उड़ सकते हैं।",
     "Bigger surface → more molecules escape at once."),

    ("evaporation-cooling", "medium",
     "गर्म चाय को झांकने (फूँक मारने) से जल्दी ठंडी करने का कारण —",
     "Blowing on hot tea cools it quickly because —",
     ["भाप हटती है, वाष्पीकरण तेज़ होता है और ऊष्मा उड़ती है", "हवा ठंडी होती है", "चाय हल्की हो जाती है", "कप ठंडा होता है"],
     ["The vapour is swept away, evaporation quickens and heat leaves", "The air is cold", "The tea gets lighter", "The cup cools"],
     0,
     "फूँक = वाष्प हटाना = तेज़ वाष्पीकरण = तेज़ ठंडक।",
     "Blowing = clearing vapour = faster evaporation = faster cooling."),

    ("evaporation-cooling", "medium",
     "पंखा चलाने से कमरे की हवा का ताप नहीं बदलता, फिर भी शरीर को ठंडक —",
     "A fan does not change the room air's temperature, yet the body feels cool —",
     ["पंखे से पसीने का वाष्पीकरण तेज़ होता है", "पंखा ठंडी हवा बनाता है", "पंखा ऊर्जा खा जाता है", "शरीर का ताप गिर जाता है"],
     ["The fan hastens the evaporation of sweat", "The fan creates cold air", "The fan eats energy", "The body temperature drops"],
     0,
     "ठंडक वाष्पीकरण से — हवा की गति से, ताप से नहीं।",
     "The coolness comes from evaporation — via air speed, not temperature."),

    ("evaporation-cooling", "medium",
     "नाखून हटाने वाले एसीटोन की बूँद हाथ पर ठंडी लगती है —",
     "A drop of nail-polish remover (acetone) feels cold on the hand because —",
     ["एसीटोन अत्यंत उड़नशील है — वाष्पीकरण तुरंत ऊष्मा लेता है", "एसीटोन बर्फ से आता है", "एसीटोन भारी है", "हाथ गर्म होता है"],
     ["Acetone is highly volatile — its instant evaporation draws heat", "Acetone comes from ice", "Acetone is heavy", "The hand is hot"],
     0,
     "कम उबालांक वाले द्रव पल भर में उड़ जाते हैं।",
     "Low-boiling liquids vanish within moments."),

    ("evaporation-cooling", "medium",
     "वाष्पीकरण की गति किन कारकों पर निर्भर करती है?",
     "The rate of evaporation depends on which factors?",
     ["ताप, सतह क्षेत्रफल, हवा की गति और आर्द्रता", "केवल ताप", "केवल दाब", "रंग और गंध"],
     ["Temperature, surface area, wind speed and humidity", "Temperature only", "Pressure only", "Colour and smell"],
     0,
     "चारों कारक मिलकर वाष्पीकरण की दर तय करते हैं।",
     "All four factors together fix the rate of evaporation."),

    ("evaporation-cooling", "medium",
     "आर्द्र (उमस भरे) दिन पसीना सूखता नहीं — कारण —",
     "On a humid day sweat does not dry — because —",
     ["वायु में पहले से बहुत जलवाष्प है — नई भाप की जगह नहीं", "पसीना नमकीन होता है", "शरीर ठंडा होता है", "सूर्य छिपा रहता है"],
     ["The air already holds much vapour — no room for more", "Sweat is salty", "The body is cold", "The sun stays hidden"],
     0,
     "आर्द्रता अधिक → वाष्पीकरण धीमा → ठंडक कम।",
     "High humidity → slow evaporation → little cooling."),

    ("evaporation-cooling", "medium",
     "ठंडी पानी की बोतल बाहर रखने पर उस पर बूँदे क्यों जमा होती हैं?",
     "Why do droplets gather on a cold water bottle kept outside?",
     ["वायु की जलवाष्प ठंडी सतह पर संघनित होती है", "बोतल में पानी रिसता है", "बोतल पसीना करती है", "हवा बोतल को चाटती है"],
     ["The air's water vapour condenses on the cold surface", "Water leaks from the bottle", "The bottle sweats", "The air licks the bottle"],
     0,
     "ठंडी सतह वायु को ओस-बिंदु तक ठंडा करती है — संघनन।",
     "The cold surface chills the air to its dew point — condensation."),

    ("evaporation-cooling", "medium",
     "क्या वाष्पीकरण ठंडे मौसम में भी होता है?",
     "Does evaporation occur in cold weather too?",
     ["हाँ — धीमी दर से", "नहीं — कभी नहीं", "केवल बर्फ पर", "केवल रात में"],
     ["Yes — at a slower rate", "No — never", "Only on ice", "Only at night"],
     0,
     "किसी भी ताप पर कुछ अणु पलायन करते हैं; दर ताप से बदलती है।",
     "At any temperature some molecules escape; the rate just varies."),

    ("evaporation-cooling", "medium",
     "कपड़े सूखने में गर्म व शुष्क दिन, आर्द्र दिन से तेज़ — कारण —",
     "Clothes dry faster on a hot dry day than a humid one — because —",
     ["कम आर्द्रता + अधिक ताप = तेज़ वाष्पीकरण", "गर्म दिन में हवा तेज़ होती है", "कपड़े पतले हो जाते हैं", "सूर्य कपड़े सुखाता है"],
     ["Low humidity + high temperature = rapid evaporation", "Wind is faster on hot days", "Clothes get thinner", "The sun dries them"],
     0,
     "दोनों अनुकूल कारक मिले — वाष्पीकरण अधिकतम।",
     "Both favourable factors combine — maximal evaporation."),

    ("evaporation-cooling", "medium",
     "मिट्टी के घड़े का जल दिन में ठंडा — रात में क्या होता है?",
     "An earthen pot's water cools by day — what happens at night?",
     ["वाष्पीकरण जारी रहता है, ठंडक बनी रहती है (कुछ कम)", "जल गर्म हो जाता है", "घड़ा फट जाता है", "वाष्पीकरण उलटा चलता है"],
     ["Evaporation continues, coolness persists (somewhat less)", "The water heats up", "The pot cracks", "Evaporation reverses"],
     0,
     "रात में ताप गिरने से दर घटती है पर रुकती नहीं।",
     "The cooler night lowers the rate but never stops it."),

    ("evaporation-cooling", "medium",
     "कूलर के गीले खस-खस के पैड से हवा ठंडी होकर आती है — तत्व —",
     "A cooler's wet khus pads send out cooled air — the principle is —",
     ["पानी का वाष्पीकरण हवा से ऊष्मा लेता है", "खस बर्फ बनाता है", "पंखा हवा गाड़ता है", "पानी जम जाता है"],
     ["Evaporating water draws heat from the air", "Khus makes ice", "The fan digs the air", "The water freezes"],
     0,
     "गीले पैड से गुजरती हवा वाष्पीकरण-शीतलन से ठंडी।",
     "Air passing wet pads is cooled by evaporative chilling."),

    ("evaporation-cooling", "medium",
     "गर्म दूध को पतली परत में फैलाकर मथने/चलाने से जल्दी ठंडा —",
     "Stirring hot milk spread thin cools it fast — the combined reason is —",
     ["सतह बड़ी + भाप हटती है → वाष्पीकरण दोनों से तेज़", "दूध मीठा होता है", "बर्तन गर्म होता है", "दूध गाढ़ा होता है"],
     ["Bigger surface + vapour removal → evaporation speeds up both ways", "Milk is sweet", "The vessel is hot", "Milk is thick"],
     0,
     "दोनों उपाय वाष्पीकरण की दर बढ़ाते हैं।",
     "Both measures raise the rate of evaporation."),

    ("evaporation-cooling", "medium",
     "कथन A: वाष्पीकरण सतही घटना है। कथन B: क्वथन पूरे द्रव की घटना। सही विकल्प —",
     "Statement A: evaporation is a surface phenomenon. Statement B: boiling is a whole-liquid phenomenon. The correct option —",
     ["A और B दोनों सही", "केवल A सही", "केवल B सही", "दोनों गलत"],
     ["Both A and B are right", "Only A is right", "Only B is right", "Both are wrong"],
     0,
     "वाष्पीकरण सिर्फ सतह से; क्वथन तल सहित सर्वत्र।",
     "Evaporation is surface-only; boiling happens everywhere in the bulk."),

    ("evaporation-cooling", "medium",
     "डाइनिंग टेबल पर ढकी थाली में जल बना रहता है, खुली थाली सूख जाती है — कारण —",
     "Covered water stays; open water dries — because —",
     ["ढक्कन वापस संघनित भाप जल में मिलाता है और आर्द्रता बनाए रखता है", "ढका जल भारी होता है", "खुली थाली गर्म होती है", "ढक्कन पानी पी जाता है"],
     ["The lid returns condensed vapour and keeps the air humid inside", "Covered water is heavy", "The open plate is hot", "The lid drinks the water"],
     0,
     "बंद जगह में जलवाष्प संतुलन — वाष्पीकरण लगभग रुकता है।",
     "Inside a closed space vapour equilibrates — evaporation nearly stops."),

    ("evaporation-cooling", "medium",
     "गर्मी में रेगिस्तान में कपड़े बहुत जल्दी सूखते हैं —",
     "In deserts clothes dry very fast because —",
     ["शुष्क हवा (अत्यल्प आर्द्रता) वाष्पीकरण तीव्र करती है", "रेत गर्म होती है", "वहाँ कपड़े नहीं होते", "सूर्य पास होता है"],
     ["The dry air (very low humidity) makes evaporation intense", "The sand is hot", "There are no clothes there", "The sun is nearer"],
     0,
     "शून्य के पास आर्द्रता = भाप को स्थान अनंत।",
     "Near-zero humidity = unlimited room for vapour."),

    ("evaporation-cooling", "medium",
     "गीले तौलिये में लिपटी ठंडी पानी की बोतल —",
     "A cold water bottle wrapped in a wet towel —",
     ["तौलिये के जल के वाष्पीकरण से और ठंडी रहती है", "जल्दी गर्म हो जाती है", "कोई अंतर नहीं", "तौलिया गर्म करता है"],
     ["Stays cooler still, thanks to the towel-water's evaporation", "Warms up quickly", "No difference", "The towel heats it"],
     0,
     "गीली परत का वाष्पीकरण बोतल से ऊष्मा खींचता रहता है।",
     "The wet layer's evaporation keeps drawing heat from the bottle."),

    ("evaporation-cooling", "medium",
     "आर्द्र (उमस भरे) दिन कूलर का असर क्यों घट जाता है?",
     "Why does a cooler work poorly on a humid day?",
     ["वायु पहले से जलवाष्प से भरी — वाष्पीकरण धीमा — शीतलन कम", "कूलर का पंखा उलटा घूमता है", "पानी गर्म हो जाता है", "कूलर की बत्ती जल जाती है"],
     ["The air is already vapour-laden — slow evaporation — less cooling", "The fan turns backwards", "The water gets hot", "The cooler's bulb burns"],
     0,
     "वाष्पीकरण आधारित शीतलन आर्द्रता बढ़ने पर मंद पड़ता है।",
     "Evaporation-based cooling weakens as humidity rises."),

    # ---- hard (6) ----
    ("evaporation-cooling", "hard",
     "तेज़ बुखार में माथे पर गीली पट्टी — शीतलन का भौतिक आधार —",
     "A wet cloth strip on the forehead in high fever — the physical basis of the relief is —",
     ["पट्टी के जल का वाष्पीकरण माथे से गुप्त ऊष्मा खींचता है", "पट्टी बर्फ है", "पानी दवा है", "कपड़ा ऊर्जा देता है"],
     ["The strip's evaporating water draws latent heat from the forehead", "The strip is ice", "Water is medicine", "The cloth gives energy"],
     0,
     "वाष्पीकरण-शीतलन का सीधा चिकित्सीय उपयोग।",
     "A direct medical use of evaporative cooling."),

    ("evaporation-cooling", "hard",
     "क्या उबलते जल में भी वाष्पीकरण-शीतलन ताप घटाता है?",
     "Does evaporative cooling lower the temperature of boiling water too?",
     ["नहीं — क्वथनांक पर ताप स्थिर रहता है", "हाँ — ताप गिरता है", "कभी-कभी", "ताप ऊपर चढ़ता है"],
     ["No — at the boiling point the temperature stays put", "Yes — it falls", "Sometimes", "The temperature climbs"],
     0,
     "क्वथन के समय दी गई ऊष्मा तुरंत भाप बनती है — ताप न घटता न बढ़ता।",
     "During boiling, supplied heat instantly turns to steam — the temperature neither falls nor rises."),

    ("evaporation-cooling", "hard",
     "फैले हुए गर्म दूध vs ढके गर्म दूध — ठंडा होने की तुलना —",
     "Hot milk spread open versus covered — comparing their cooling —",
     ["फैला दूध जल्दी ठंडा (सतह+वाष्पीकरण+संवहन सब अनुकूल)", "ढका दूध जल्दी", "दोनों समान", "ढका कभी ठंडा नहीं"],
     ["The open spread milk cools faster (surface, evaporation and convection all help)", "The covered one cools faster", "Both the same", "The covered never cools"],
     0,
     "खुली सतह पर तीनों ऊष्मा-हानि मार्ग खुलते हैं।",
     "An open surface opens all three heat-loss routes."),

    ("evaporation-cooling", "hard",
     "कथन A: वाष्पीकरण ताप घटाता है। कथन B: वाष्पीकरण किसी भी ताप पर होता है। सही विकल्प —",
     "Statement A: evaporation lowers the temperature. Statement B: evaporation occurs at any temperature. The correct option —",
     ["A और B दोनों सही", "केवल A सही", "केवल B सही", "दोनों गलत"],
     ["Both A and B are right", "Only A is right", "Only B is right", "Both are wrong"],
     0,
     "दोनों कथन वाष्पीकरण के मूल गुण हैं।",
     "Both statements are core properties of evaporation."),

    ("evaporation-cooling", "hard",
     "उड़नशीलता (volatility) और वाष्पीकरण-दर का संबंध —",
     "How is volatility related to the rate of evaporation?",
     ["अधिक उड़नशील द्रव तेज़ वाष्पित — अधिक शीतलन", "कोई संबंध नहीं", "उलटा — धीमा", "केवल गंध से"],
     ["A more volatile liquid evaporates faster — more cooling", "No relation", "Inverse — slower", "Only through smell"],
     0,
     "पेट्रोल/एसीटोन जल से तेज़ उड़ते हैं — तीव्र ठंडक।",
     "Petrol/acetone escape faster than water — quicker cooling."),

    ("evaporation-cooling", "hard",
     "पेड़ के नीचे बैठने पर गर्मी में भी ठंडक का एक ऊष्मा-आधारित कारण (छाया से इतर) —",
     "Besides shade, one heat-based reason for coolness under a tree is —",
     ["पत्तियों का वाष्पोत्सर्जन आसपास की हवा को ठंडा रखता है", "तना ठंडा होता है", "जड़ें बर्फ पीती हैं", "पत्ते काले होते हैं"],
     ["The leaves' transpiration keeps the surrounding air cool", "The trunk is cold", "The roots drink ice", "The leaves are black"],
     0,
     "लाखों पत्तों का वाष्पोत्सर्जन = प्राकृतिक कूलर।",
     "Millions of transpiring leaves act as a natural cooler."),
]
