# -*- coding: utf-8 -*-
"""P07 (Sound & Its Applications) — Part 2: wave-characteristics (37) + echo-ultrasound (37) = 74 tuples.
All items authored with correct_idx=0; rotation happens in gen_p07_questions.py.

T3 wave-characteristics  37 = E15/M16/H6
T4 echo-ultrasound       37 = E14/M17/H6
"""

PART2 = [
    # ================= WAVE CHARACTERISTICS (37) =================
    # ---- easy (15) ----
    ("wave-characteristics", "easy",
     "तरंगदैर्घ्य किसे कहते हैं?",
     "What is wavelength?",
     ["दो क्रमागत संपीडनों (या विरलनों) के बीच की दूरी", "तरंग की ऊँचाई", "प्रति सेकंड दोलन", "तरंग का रंग"],
     ["The distance between two consecutive compressions (or rarefactions)", "The height of a wave", "Oscillations per second", "The colour of a wave"],
     0,
     "एक चक्र की लंबाई ही तरंगदैर्घ्य λ है।",
     "The length of one full cycle is the wavelength λ."),

    ("wave-characteristics", "easy",
     "आवृत्ति का मात्रक क्या है?",
     "What is the unit of frequency?",
     ["हर्ट्ज़ (Hz)", "मीटर (m)", "सेकंड (s)", "मीटर/सेकंड"],
     ["Hertz (Hz)", "Metre (m)", "Second (s)", "Metre/second"],
     0,
     "1 Hz = 1 दोलन प्रति सेकंड।",
     "1 Hz = one oscillation per second."),

    ("wave-characteristics", "easy",
     "आवर्तकाल (T) किसे कहते हैं?",
     "What is the time period (T)?",
     ["एक पूर्ण दोलन में लगा समय", "एक सेकंड में दोलन", "तरंग की दूरी", "तरंग की चाल"],
     ["The time taken for one complete oscillation", "Oscillations in one second", "The wave's distance", "The wave's speed"],
     0,
     "T = एक चक्र का समय।",
     "T = the time of one cycle."),

    ("wave-characteristics", "easy",
     "ध्वनि तरंग का वेग, तरंगदैर्घ्य और आवृत्ति में संबंध —",
     "The relation among a sound wave's speed, wavelength and frequency is —",
     ["v = λ × ν", "v = λ / ν", "v = ν / λ", "v = λ + ν"],
     ["v = λ × ν", "v = λ / ν", "v = ν / λ", "v = λ + ν"],
     0,
     "चाल = तरंगदैर्घ्य × आवृत्ति।",
     "Speed = wavelength × frequency."),

    ("wave-characteristics", "easy",
     "पिच (तारत्व) किस पर निर्भर करती है?",
     "Pitch depends on which quantity?",
     ["आवृत्ति", "आयाम", "चाल प्रकाश की", "माध्यम का रंग"],
     ["Frequency", "Amplitude", "The speed of light", "The medium's colour"],
     0,
     "आवृत्ति अधिक = सुर तेज़।",
     "Higher frequency = higher note."),

    ("wave-characteristics", "easy",
     "प्रबलता (loudness) किस पर निर्भर करती है?",
     "Loudness depends on which quantity?",
     ["आयाम", "आवृत्ति", "तरंगदैर्घ्य", "तापमान"],
     ["Amplitude", "Frequency", "Wavelength", "Temperature"],
     0,
     "आयाम बड़ा = ध्वनि प्रबल।",
     "Bigger amplitude = louder sound."),

    ("wave-characteristics", "easy",
     "मनुष्य की श्रव्यता सीमा (श्रव्य परास) क्या है?",
     "What is the audible range of humans?",
     ["लगभग 20 Hz से 20,000 Hz", "2 Hz से 200 Hz", "2000 Hz से 2 लाख Hz", "20,000 Hz से ऊपर"],
     ["About 20 Hz to 20,000 Hz", "2 Hz to 200 Hz", "2000 Hz to 200,000 Hz", "Above 20,000 Hz"],
     0,
     "सामान्य मनुष्य 20–20,000 Hz सुनता है।",
     "A normal human hears 20–20,000 Hz."),

    ("wave-characteristics", "easy",
     "20,000 Hz से अधिक आवृत्ति की ध्वनि क्या कहलाती है?",
     "Sound of frequency above 20,000 Hz is called —",
     ["पराश्रव्य (ultrasound)", "अवश्रव्य", "श्रव्य", "प्रकाश"],
     ["Ultrasound", "Infrasound", "Audible sound", "Light"],
     0,
     "ऊपर 20 kHz = पराश्रव्य।",
     "Above 20 kHz = ultrasound."),

    ("wave-characteristics", "easy",
     "20 Hz से कम आवृत्ति की ध्वनि क्या कहलाती है?",
     "Sound of frequency below 20 Hz is called —",
     ["अवश्रव्य (infrasound)", "पराश्रव्य", "श्रव्य", "शोर नहीं"],
     ["Infrasound", "Ultrasound", "Audible", "Not sound at all"],
     0,
     "नीचे 20 Hz = अवश्रव्य (भूकंप तरंगें आदि)।",
     "Below 20 Hz = infrasound (earthquake waves etc.)."),

    ("wave-characteristics", "easy",
     "कुत्ते और चमगादड़ इंसान से अधिक क्या सुन सकते हैं?",
     "What can dogs and bats hear beyond human capability?",
     ["पराश्रव्य (बहुत उच्च आवृत्ति)", "अवश्रव्य केवल", "प्रकाश", "रेडियो"],
     ["Ultrasound (very high frequencies)", "Only infrasound", "Light", "Radio"],
     0,
     "अनेक जानवर 20 kHz से ऊपर की ध्वनि सुनते हैं।",
     "Many animals hear above 20 kHz."),

    ("wave-characteristics", "easy",
     "तीखी (shrill) आवाज़ की आवृत्ति —",
     "A shrill (sharp) voice has a —",
     ["उच्च आवृत्ति", "निम्न आवृत्ति", "शून्य आवृत्ति", "मध्यम आयाम"],
     ["High frequency", "Low frequency", "Zero frequency", "Medium amplitude"],
     0,
     "तीखापन = उच्च आवृत्ति का ही दूसरा नाम।",
     "Shrillness is another name for high frequency."),

    ("wave-characteristics", "easy",
     "भारी (गहरी) आवाज़ की आवृत्ति —",
     "A deep (grave) voice has a —",
     ["निम्न आवृत्ति", "उच्च आवृत्ति", "अनंत आवृत्ति", "कोई आवृत्ति नहीं"],
     ["Low frequency", "High frequency", "Infinite frequency", "No frequency"],
     0,
     "गहरी ध्वनि = कम आवृत्ति।",
     "A deep sound = low frequency."),

    ("wave-characteristics", "easy",
     "संपीडन-विरलन क्रम चलता है —",
     "The compression-rarefaction sequence travels —",
     ["स्रोत से श्रोता की ओर", "श्रोता से स्रोत की ओर", "दोनों ओर समान रूप से नहीं — केवल एक दिशा में सामान्यतः", "कहीं भी"],
     ["From the source towards the listener", "From the listener to the source", "Only one way normally", "Anywhere"],
     0,
     "ऊर्जा स्रोत से बाहर की ओर फैलती है।",
     "The energy spreads outward from the source."),

    ("wave-characteristics", "easy",
     "महिलाओं की आवाज़ पुरुषों से प्रायः अधिक तीखी होती है — कारण —",
     "Women's voices are usually shriller than men's — because —",
     ["उनकी स्वर-पट्टिकाएँ तेज़ आवृत्ति से कंपन करती हैं", "उनका कान तेज़ होता है", "उनकी साँस लंबी होती है", "उनकी जीभ छोटी होती है"],
     ["Their vocal cords vibrate at a higher frequency", "Their ears are sharper", "Their breath is longer", "Their tongue is shorter"],
     0,
     "पट्टिकाओं की बनावट व तनाव आवृत्ति ऊँची रखते हैं।",
     "The cords' build and tension keep the frequency higher."),

    ("wave-characteristics", "easy",
     "तरंगदैर्घ्य का मात्रक —",
     "The unit of wavelength is —",
     ["मीटर (m)", "हर्ट्ज़", "सेकंड", "वाट"],
     ["Metre (m)", "Hertz", "Second", "Watt"],
     0,
     "λ दूरी है — मीटर में।",
     "λ is a distance — in metres."),

    # ---- medium (16) ----
    ("wave-characteristics", "medium",
     "50 Hz ध्वनि का आवर्तकाल —",
     "The time period of a 50 Hz sound is —",
     ["0.02 s", "50 s", "2 s", "0.5 s"],
     ["0.02 s", "50 s", "2 s", "0.5 s"],
     0,
     "T = 1/ν = 1/50 = 0.02 s।",
     "T = 1/ν = 1/50 = 0.02 s."),

    ("wave-characteristics", "medium",
     "100 Hz की आवृत्ति का आवर्तकाल —",
     "The time period of a 100 Hz frequency is —",
     ["0.01 s", "0.1 s", "1 s", "100 s"],
     ["0.01 s", "0.1 s", "1 s", "100 s"],
     0,
     "T = 1/100 = 0.01 s।",
     "T = 1/100 = 0.01 s."),

    ("wave-characteristics", "medium",
     "500 Hz ध्वनि का आवर्तकाल —",
     "The time period of a 500 Hz sound is —",
     ["0.002 s", "0.02 s", "0.2 s", "5 s"],
     ["0.002 s", "0.02 s", "0.2 s", "5 s"],
     0,
     "T = 1/500 = 0.002 s।",
     "T = 1/500 = 0.002 s."),

    ("wave-characteristics", "medium",
     "आवर्तकाल 0.005 s है — आवृत्ति —",
     "The time period is 0.005 s — the frequency is —",
     ["200 Hz", "50 Hz", "500 Hz", "20 Hz"],
     ["200 Hz", "50 Hz", "500 Hz", "20 Hz"],
     0,
     "ν = 1/T = 1/0.005 = 200 Hz।",
     "ν = 1/T = 1/0.005 = 200 Hz."),

    ("wave-characteristics", "medium",
     "वायु में चाल 340 m/s, आवृत्ति 100 Hz — तरंगदैर्घ्य —",
     "Speed in air 340 m/s, frequency 100 Hz — the wavelength is —",
     ["3.4 m", "34 m", "0.34 m", "34000 m"],
     ["3.4 m", "34 m", "0.34 m", "34,000 m"],
     0,
     "λ = v/ν = 340/100 = 3.4 m।",
     "λ = v/ν = 340/100 = 3.4 m."),

    ("wave-characteristics", "medium",
     "v = 344 m/s, ν = 172 Hz — λ —",
     "v = 344 m/s, ν = 172 Hz — λ is —",
     ["2 m", "4 m", "1 m", "0.5 m"],
     ["2 m", "4 m", "1 m", "0.5 m"],
     0,
     "λ = 344/172 = 2 m।",
     "λ = 344/172 = 2 m."),

    ("wave-characteristics", "medium",
     "तरंगदैर्घ्य 0.68 m और चाल 340 m/s — ध्वनि की आवृत्ति —",
     "Wavelength 0.68 m and speed 340 m/s — the frequency of the sound is —",
     ["500 Hz", "50 Hz", "5 kHz", "231 Hz"],
     ["500 Hz", "50 Hz", "5 kHz", "231 Hz"],
     0,
     "ν = v/λ = 340/0.68 = 500 Hz।",
     "ν = v/λ = 340/0.68 = 500 Hz."),

    ("wave-characteristics", "medium",
     "तरंगदैर्घ्य 2 m, आवृत्ति 170 Hz — ध्वनि की चाल —",
     "Wavelength 2 m and frequency 170 Hz — the speed of sound is —",
     ["340 m/s", "85 m/s", "172 m/s", "342 m/s"],
     ["340 m/s", "85 m/s", "172 m/s", "342 m/s"],
     0,
     "v = λν = 2 × 170 = 340 m/s।",
     "v = λν = 2 × 170 = 340 m/s."),

    ("wave-characteristics", "medium",
     "λ = 0.5 m, ν = 680 Hz — v —",
     "λ = 0.5 m, ν = 680 Hz — v is —",
     ["340 m/s", "1360 m/s", "170 m/s", "344 m/s"],
     ["340 m/s", "1360 m/s", "170 m/s", "344 m/s"],
     0,
     "v = 0.5 × 680 = 340 m/s।",
     "v = 0.5 × 680 = 340 m/s."),

    ("wave-characteristics", "medium",
     "वायु में चाल 340 m/s और आवर्तकाल 0.01 s — तरंगदैर्घ्य —",
     "Speed 340 m/s in air and time period 0.01 s — the wavelength is —",
     ["3.4 m", "34 m", "0.34 m", "3.4 cm"],
     ["3.4 m", "34 m", "0.34 m", "3.4 cm"],
     0,
     "λ = v × T = 340 × 0.01 = 3.4 m।",
     "λ = v × T = 340 × 0.01 = 3.4 m."),

    ("wave-characteristics", "medium",
     "कौन-सी ध्वनि पराश्रव्य है?",
     "Which of these sounds is ultrasonic?",
     ["30,000 Hz", "15,000 Hz", "500 Hz", "20 Hz"],
     ["30,000 Hz", "15,000 Hz", "500 Hz", "20 Hz"],
     0,
     "30,000 Hz > 20,000 Hz — पराश्रव्य परास।",
     "30,000 Hz lies beyond 20,000 Hz — the ultrasonic range."),

    ("wave-characteristics", "medium",
     "कौन-सी ध्वनि अवश्रव्य है?",
     "Which of these sounds is infrasonic?",
     ["10 Hz", "100 Hz", "10,000 Hz", "25,000 Hz"],
     ["10 Hz", "100 Hz", "10,000 Hz", "25,000 Hz"],
     0,
     "10 Hz, 20 Hz से नीचे है — अवश्रव्य।",
     "10 Hz is below 20 Hz — infrasonic."),

    ("wave-characteristics", "medium",
     "15,000 Hz की ध्वनि मनुष्य को —",
     "A 15,000 Hz sound is — for humans.",
     ["सुनाई देती है (श्रव्य परास में)", "नहीं सुनाई देती (पराश्रव्य)", "नहीं सुनाई देती (अवश्रव्य)", "दिखाई देती है"],
     ["Audible (within the audible range)", "Inaudible (ultrasonic)", "Inaudible (infrasonic)", "Visible"],
     0,
     "15,000, सीमा 20 और 20,000 के बीच है — श्रव्य।",
     "15,000 lies between the limits 20 and 20,000 — audible."),

    ("wave-characteristics", "medium",
     "रेडियो का वॉल्यूम घटाने पर क्या घटता है?",
     "Turning down a radio's volume decreases what?",
     ["आयाम", "आवृत्ति", "तरंगदैर्घ्य", "चाल"],
     ["The amplitude", "The frequency", "The wavelength", "The speed"],
     0,
     "वॉल्यूम = प्रबलता = आयाम का नियंत्रण।",
     "Volume = loudness = amplitude control."),

    ("wave-characteristics", "medium",
     "कथन A: आवृत्ति बदलने से पिच बदलती है। कथन B: आयाम बदलने से पिच बदलती है। सही विकल्प —",
     "Statement A: changing frequency changes pitch. Statement B: changing amplitude changes pitch. The correct option —",
     ["A सही, B गलत", "A गलत, B सही", "दोनों सही", "दोनों गलत"],
     ["A right, B wrong", "A wrong, B right", "Both right", "Both wrong"],
     0,
     "आयाम से केवल प्रबलता बदलती है।",
     "Amplitude alters only loudness."),

    ("wave-characteristics", "medium",
     "तार (धुन) को छोड़ने की जगह बदलने से क्या बदलता है?",
     "Changing where a string is plucked mainly alters what?",
     ["प्रबलता (और थोड़ा स्वर-रंग), न कि मूल पिच", "आवृत्ति बहुत", "चाल", "माध्यम"],
     ["The loudness (and a bit of tone colour), not the basic pitch", "The frequency a lot", "The speed", "The medium"],
     0,
     "पिच तनाव-लंबाई से; छेड़ने का बल प्रबलता से।",
     "Pitch comes from tension-length; pluck force gives loudness."),

    # ---- hard (6) ----
    ("wave-characteristics", "hard",
     "वायु में चाल 340 m/s — 2 kHz आवृत्ति की तरंग का तरंगदैर्घ्य —",
     "Speed 340 m/s in air — the wavelength of a 2 kHz wave is —",
     ["0.17 m", "1.7 m", "17 m", "0.017 m"],
     ["0.17 m", "1.7 m", "17 m", "0.017 m"],
     0,
     "2000 Hz; λ = 340/2000 = 0.17 m।",
     "2000 Hz; λ = 340/2000 = 0.17 m."),

    ("wave-characteristics", "hard",
     "ध्वनि जल (चाल 1500 m/s) में 1000 Hz रहे — जल में तरंगदैर्घ्य —",
     "A sound keeps 1000 Hz in water (speed 1500 m/s) — its wavelength in water is —",
     ["1.5 m", "0.15 m", "15 m", "3.4 m"],
     ["1.5 m", "0.15 m", "15 m", "3.4 m"],
     0,
     "λ = 1500/1000 = 1.5 m।",
     "λ = 1500/1000 = 1.5 m."),

    ("wave-characteristics", "hard",
     "एक ध्वनि 170 Hz की है — 1 सेकंड में उतनी दूरी तय करते हुए (340 m/s) कितने पूर्ण चक्र बनते हैं अर्थात आवृत्ति —",
     "A 170 Hz sound moving at 340 m/s — the number of complete cycles per second (its frequency) is —",
     ["170", "340", "2", "0.5"],
     ["170", "340", "2", "0.5"],
     0,
     "आवृत्ति स्रोत का गुण — 170 चक्र/सेकंड।",
     "Frequency belongs to the source — 170 cycles/second."),

    ("wave-characteristics", "hard",
     "250 Hz ध्वनि 4 सेकंड बजती रही — कुल दोलन —",
     "A 250 Hz sound plays for 4 s — the total oscillations are —",
     ["1000", "250", "62.5", "4000"],
     ["1000", "250", "62.5", "4000"],
     0,
     "N = ν × t = 250 × 4 = 1000।",
     "N = ν × t = 250 × 4 = 1000."),

    ("wave-characteristics", "hard",
     "कथन A: श्रव्यता सीमा आयु के साथ सिकुड़ती है। कथन B: पराश्रव्य की आवृत्ति 20 kHz से अधिक होती है। सही विकल्प —",
     "Statement A: the audible range shrinks with age. Statement B: ultrasound's frequency exceeds 20 kHz. The correct option —",
     ["A और B दोनों सही", "केवल A सही", "केवल B सही", "दोनों गलत"],
     ["Both A and B are right", "Only A is right", "Only B is right", "Both are wrong"],
     0,
     "बुढ़ापे में उच्च आवृत्ति सीमा घटती है; पराश्रव्य परिभाषा सही।",
     "The upper limit falls with age; the ultrasound definition is correct."),

    ("wave-characteristics", "hard",
     "एक ही माध्यम में दो ध्वनियाँ — उच्च आवृत्ति वाली का तरंगदैर्घ्य —",
     "Two sounds in the same medium — the higher-frequency one has a —",
     ["छोटा तरंगदैर्घ्य (λ = v/ν)", "बड़ा तरंगदैर्घ्य", "समान तरंगदैर्घ्य", "शून्य तरंगदैर्घ्य"],
     ["Shorter wavelength (λ = v/ν)", "Longer wavelength", "The same wavelength", "Zero wavelength"],
     0,
     "v समान रखने पर ν बढ़ा तो λ घटा।",
     "With v fixed, more ν means less λ."),

    # ================= ECHO & ULTRASOUND APPLICATIONS (37) =================
    # ---- easy (14) ----
    ("echo-ultrasound", "easy",
     "प्रतिध्वनि किसे कहते हैं?",
     "What is an echo?",
     ["परावर्तित ध्वनि जो स्रोत से अलग सुनाई दे", "स्रोत की मूल ध्वनि", "ध्वनि का जमना", "ध्वनि का रंग"],
     ["A reflected sound heard separately from the original", "The original sound itself", "The freezing of sound", "The colour of sound"],
     0,
     "बड़ी दूरी से लौटी ध्वनि दूसरी ध्वनि जैसी सुनाई दे तो प्रतिध्वनि।",
     "A sound returning from a far surface, heard as a second sound, is an echo."),

    ("echo-ultrasound", "easy",
     "प्रतिध्वनि किस घटना पर आधारित है?",
     "Echo is based on which phenomenon?",
     ["ध्वनि का परावर्तन", "ध्वनि का अपवर्तन", "ध्वनि का अवशोषण", "ध्वनि का निर्वात"],
     ["Reflection of sound", "Refraction of sound", "Absorption of sound", "Vacuum of sound"],
     0,
     "अवरोधक से टकराकर लौटना ही परावर्तन है।",
     "Bouncing back from an obstacle is reflection."),

    ("echo-ultrasound", "easy",
     "स्पष्ट प्रतिध्वनि के लिए दो ध्वनियों का न्यूनतम समय-अंतराल —",
     "The minimum time gap between two sounds for a clear echo is —",
     ["0.1 s", "1 s", "0.01 s", "10 s"],
     ["0.1 s", "1 s", "0.01 s", "10 s"],
     0,
     "कान 0.1 s से कम अंतराल को अलग नहीं पहचानता।",
     "The ear cannot separate gaps under 0.1 s."),

    ("echo-ultrasound", "easy",
     "0.1 s सुनने-अंतराल के लिए परावर्तक से न्यूनतम दूरी लगभग —",
     "For the 0.1 s hearing gap, the minimum distance from the reflector is about —",
     ["17.2 m", "34.4 m", "172 m", "1.72 m"],
     ["17.2 m", "34.4 m", "172 m", "1.72 m"],
     0,
     "d = (344 × 0.1)/2 = 17.2 m।",
     "d = (344 × 0.1)/2 = 17.2 m."),

    ("echo-ultrasound", "easy",
     "प्रतिध्वनि दूरी नापने में सहायक है — सूत्र —",
     "Echo helps measure distance — the formula is —",
     ["d = v × t / 2", "d = v × t", "d = v / t", "d = t / 2v"],
     ["d = v × t / 2", "d = v × t", "d = v / t", "d = t / 2v"],
     0,
     "ध्वनि दूर जाकर वापस आती है — पथ दोगुना, इसलिए आधा।",
     "The sound goes and returns — double path, hence the half."),

    ("echo-ultrasound", "easy",
     "SONAR का पूरा नाम क्या है?",
     "What is the full form of SONAR?",
     ["Sound Navigation and Ranging", "Solar Navigation and Radio", "Sonar Optical Network", "Sound Noise and Rhythm"],
     ["Sound Navigation and Ranging", "Solar Navigation and Radio", "Sonar Optical Network", "Sound Noise and Rhythm"],
     0,
     "SONAR = ध्वनि द्वारा नौचालन व दूरीमाप।",
     "SONAR = navigation and ranging by sound."),

    ("echo-ultrasound", "easy",
     "SONAR में किस ध्वनि का उपयोग होता है?",
     "Which sound does SONAR use?",
     ["पराश्रव्य (ultrasound)", "अवश्रव्य", "साधारण श्रव्य", "प्रकाश"],
     ["Ultrasound", "Infrasound", "Ordinary audible sound", "Light"],
     0,
     "उच्च आवृत्ति = तीखी, दूर तक स्पष्ट, सटीक माप।",
     "High frequency = sharp, far-reaching, precise."),

    ("echo-ultrasound", "easy",
     "चमगादड़ रात में किस विधि से रास्ता खोजता है?",
     "How do bats find their way at night?",
     ["पराश्रव्य प्रतिध्वनि (echolocation) से", "देखकर", "सूँघकर", "प्रकाश से"],
     ["By ultrasonic echo (echolocation)", "By seeing", "By smelling", "By light"],
     0,
     "चमगादड़ उछाली पराश्रव्य ध्वनि के प्रतिध्वनि-समय से दूरी जाँचता है।",
     "Bats time ultrasonic echoes to gauge distances."),

    ("echo-ultrasound", "easy",
     "पराश्रव्य का एक चिकित्सीय उपयोग —",
     "One medical use of ultrasound is —",
     ["शरीर के आंतरिक अंगों की इमेजिंग (सोनोग्राफी)", "नींद लाना", "बुखार बढ़ाना", "बाल काटना"],
     ["Imaging internal organs (sonography)", "Inducing sleep", "Raising fever", "Cutting hair"],
     0,
     "गर्भावस्था व अंग-जाँच में पराश्रव्य चित्रण।",
     "Ultrasound imaging in pregnancy and organ checks."),

    ("echo-ultrasound", "easy",
     "पराश्रव्य से मशीनों के भागों की सफाई कैसे होती है?",
     "How does ultrasound clean machine parts?",
     ["पराश्रव्य तरंगें सफाई-द्रव में सूक्ष्म बुलबुले-धाराएँ बनाकर मैल हटाती हैं", "वे भाग पिघला देती हैं", "वे भाग रंग देती हैं", "वे भाग सुखा देती हैं"],
     ["Ultrasonic waves create tiny bubbling streams in the cleaning liquid that lift the grime", "They melt the parts", "They colour the parts", "They dry the parts"],
     0,
     "कैविटेशन-क्रिया से कोनों का मैल भी निकलता है।",
     "Cavitation reaches grime even in corners."),

    ("echo-ultrasound", "easy",
     "जहाज़ की गहराई-नापक (fathometer) क्या मापता है?",
     "What does a ship's fathometer (echo sounder) measure?",
     ["समुद्र की गहराई", "हवा की चाल", "जहाज़ का भार", "पानी का ताप"],
     ["The depth of the sea", "The speed of wind", "The ship's weight", "The water's temperature"],
     0,
     "तल से परावर्तित ध्वनि के समय से गहराई।",
     "Depth from the time of the bottom-returned sound."),

    ("echo-ultrasound", "easy",
     "कमरे में सामान्य बातचीत प्रतिध्वनि क्यों नहीं बनती?",
     "Why does ordinary conversation in a room not produce echoes?",
     ["दूरी 17.2 m से कम — प्रतिध्वनि मूल ध्वनि में मिल जाती है", "कमरे में ध्वनि नहीं होती", "दीवारें ध्वनि खा जाती हैं", "कान बंद रहता है"],
     ["The distance is under 17.2 m — the echo merges into the original", "Rooms have no sound", "Walls swallow sound", "Ears stay shut"],
     0,
     "छोटी दूरी पर अंतराल 0.1 s से कम रह जाता है — अलग प्रतिध्वनि नहीं।",
     "At short distances the gap stays under 0.1 s — no separate echo."),

    ("echo-ultrasound", "easy",
     "शहरों में इमारतों पर ध्वनि-अवशोषक पैनल क्यों लगते हैं?",
     "Why do city buildings fit sound-absorbing panels?",
     ["अतिरिक्त प्रतिध्वनि/गूंज घटाने", "इमारत सजाने", "प्रकाश बढ़ाने", "गर्मी बढ़ाने"],
     ["To cut excess echo/reverberation", "To decorate", "To brighten", "To heat up"],
     0,
     "प्रतिध्वनि-नियंत्रण सुनना साफ़ बनाता है।",
     "Echo control makes listening clear."),

    ("echo-ultrasound", "easy",
     "पराश्रव्य का उपयोग नहीं होता —",
     "Ultrasound is NOT used for —",
     ["प्रकाश उत्पन्न करने", "सफाई", "चिकित्सा-इमेजिंग", "SONAR"],
     ["Generating light", "Cleaning", "Medical imaging", "SONAR"],
     0,
     "पराश्रव्य ध्वनि है — प्रकाश नहीं बनाती।",
     "Ultrasound is sound — it makes no light."),

    # ---- medium (17) ----
    ("echo-ultrasound", "medium",
     "परावर्तक से 344 m दूरी पर खड़ा व्यक्ति — प्रतिध्वनि कितने सेकंड बाद सुनेगा?",
     "A person stands 344 m from a reflector — after how many seconds does the echo arrive?",
     ["2 s", "1 s", "4 s", "0.5 s"],
     ["2 s", "1 s", "4 s", "0.5 s"],
     0,
     "t = 2d/v = 688/344 = 2 s।",
     "t = 2d/v = 688/344 = 2 s."),

    ("echo-ultrasound", "medium",
     "दीवार से 86 m दूरी पर ताली — प्रतिध्वनि समय (v = 344) —",
     "A clap 86 m from a wall — the echo time (v = 344) is —",
     ["0.5 s", "0.25 s", "1 s", "2 s"],
     ["0.5 s", "0.25 s", "1 s", "2 s"],
     0,
     "t = 2 × 86/344 = 0.5 s।",
     "t = 2 × 86/344 = 0.5 s."),

    ("echo-ultrasound", "medium",
     "प्रतिध्वनि 1 सेकंड में लौटी (v = 344 m/s) — परावर्तक की दूरी —",
     "An echo returns in 1 s (v = 344 m/s) — the reflector's distance is —",
     ["172 m", "344 m", "86 m", "68.8 m"],
     ["172 m", "344 m", "86 m", "68.8 m"],
     0,
     "d = vt/2 = 344 × 1/2 = 172 m।",
     "d = vt/2 = 344 × 1/2 = 172 m."),

    ("echo-ultrasound", "medium",
     "प्रतिध्वनि 4 सेकंड में लौटी (v = 344) — दूरी —",
     "An echo returns in 4 s (v = 344) — the distance is —",
     ["688 m", "1376 m", "344 m", "172 m"],
     ["688 m", "1376 m", "344 m", "172 m"],
     0,
     "d = 344 × 4/2 = 688 m।",
     "d = 344 × 4/2 = 688 m."),

    ("echo-ultrasound", "medium",
     "SONAR से उछाली पराश्रव्य ध्वनि 4 सेकंड में वापस लौटी (जल में v = 1500 m/s) — समुद्र की गहराई —",
     "A SONAR pulse returns in 4 s (v = 1500 m/s in water) — the sea's depth is —",
     ["3000 m", "6000 m", "1500 m", "750 m"],
     ["3000 m", "6000 m", "1500 m", "750 m"],
     0,
     "d = 1500 × 4/2 = 3000 m।",
     "d = 1500 × 4/2 = 3000 m."),

    ("echo-ultrasound", "medium",
     "SONAR पल्स 2 सेकंड में लौटी (v = 1500) — गहराई —",
     "A SONAR pulse returns in 2 s (v = 1500) — the depth is —",
     ["1500 m", "3000 m", "750 m", "300 m"],
     ["1500 m", "3000 m", "750 m", "300 m"],
     0,
     "d = 1500 × 2/2 = 1500 m।",
     "d = 1500 × 2/2 = 1500 m."),

    ("echo-ultrasound", "medium",
     "प्रतिध्वनि और गूंज (reverberation) में अंतर —",
     "The difference between echo and reverberation is —",
     ["प्रतिध्वनि में परावर्तित ध्वनि अलग सुनाई देती है; गूंज में बार-बार परावर्तन मूल ध्वनि में घुल जाता है", "दोनों एक ही हैं", "गूंज केवल पहाड़ों में होती है", "प्रतिध्वनि केवल रात में होती है"],
     ["In an echo the reflected sound is heard separately; in reverberation repeated reflections blend into the original", "Both are identical", "Reverberation happens only in mountains", "Echo happens only at night"],
     0,
     "अंतराल ≥ 0.1 s = प्रतिध्वनि; कम व बार-बार = गूंज — परीक्षा-जाल।",
     "Gap ≥ 0.1 s = echo; shorter, repeated = reverberation — an exam trap."),

    ("echo-ultrasound", "medium",
     "सबसे कम प्रतिध्वनि-दूरी 17.2 m होने का कारण-गणना —",
     "The reasoning behind the 17.2 m minimum echo distance is —",
     ["0.1 s अंतराल × 344 m/s ÷ 2", "0.1 × 344", "344 × 0.1 × 2", "344/2"],
     ["0.1 s gap × 344 m/s ÷ 2", "0.1 × 344", "344 × 0.1 × 2", "344/2"],
     0,
     "d = v·t/2 = 344 × 0.1/2 = 17.2 m।",
     "d = v·t/2 = 344 × 0.1/2 = 17.2 m."),

    ("echo-ultrasound", "medium",
     "पराश्रव्य से पत्थर की खोज (गुर्दे/पित्त) कैसे होती है?",
     "How does ultrasound locate stones (kidney/gallbladder)?",
     ["अंगों से परावर्तित पराश्रव्य संकेतों के चित्रण से", "पत्थर रंग देकर", "पत्थर पिघलाकर", "रेडियो तरंगों से खींचकर"],
     ["By imaging the echoes reflected from the organs", "By colouring the stone", "By melting the stone", "By pulling with radio waves"],
     0,
     "विभिन्न ऊतकों से भिन्न परावर्तन — चित्र में पत्थर दिखता है।",
     "Different tissues reflect differently — the stone shows in the image."),

    ("echo-ultrasound", "medium",
     "चमगादड़ का इकोलोकेशन SONAR से किस तरह मिलता-जुलता है?",
     "How is a bat's echolocation similar to SONAR?",
     ["दोनों पराश्रव्य भेजकर प्रतिध्वनि-समय से दूरी निकालते हैं", "दोनों प्रकाश भेजते हैं", "दोनों गंध फैलाते हैं", "दोनों अवश्रव्य सुनते हैं"],
     ["Both send ultrasound and derive distance from echo time", "Both send light", "Both spread smell", "Both hear infrasound"],
     0,
     "प्रकृति और तकनीक एक ही सिद्धांत।",
     "Nature and technology share one principle."),

    ("echo-ultrasound", "medium",
     "जल में डॉल्फ़िन रास्ता किस विधि से खोजते हैं?",
     "Dolphins navigate by which method?",
     ["पराश्रव्य क्लिक और प्रतिध्वनि", "देखकर", "सूँघकर", "स्पर्श से"],
     ["Ultrasonic clicks and echoes", "By sight", "By smell", "By touch"],
     0,
     "जल में पराश्रव्य दूर तक काम करता है।",
     "Ultrasound works far in water."),

    ("echo-ultrasound", "medium",
     "विशाल हॉल में गूंज घटाने के दो उपाय —",
     "Two ways to reduce reverberation in a huge hall —",
     ["ध्वनि-अवशोषक पैनल व नरम पर्दे/कालीन", "दीवारें चमकाना और खिड़कियाँ बंद करना", "पंखे चलाना और गाना बंद करना", "प्रकाश घटाना और ताप बढ़ाना"],
     ["Sound-absorbing panels and soft curtains/carpets", "Polishing walls and shutting windows", "Running fans and stopping the song", "Dimming lights and raising heat"],
     0,
     "अवशोषण बढ़ा → बार-बार परावर्तन घटे → गूंज कम।",
     "More absorption → fewer repeated reflections → less blur."),

    ("echo-ultrasound", "medium",
     "प्रतिध्वनि से ध्वनि की चाल मापने का तरीका —",
     "How can echo be used to measure the speed of sound?",
     ["ज्ञात दूरी की दीवार से प्रतिध्वनि-समय नापकर v = 2d/t", "आवृत्ति गिनकर", "आयाम नापकर", "रंग देखकर"],
     ["Time the echo from a wall at a known distance and use v = 2d/t", "By counting frequency", "By measuring amplitude", "By looking at colour"],
     0,
     "d पहले से ज्ञात, t घड़ी से — v निकल आता है।",
     "With d known and t timed, v follows."),

    ("echo-ultrasound", "medium",
     "पराश्रव्य नियमित चिकित्सा-जाँच में सुरक्षित माना जाता है क्योंकि —",
     "Ultrasound is considered safe for routine medical checks because —",
     ["यह विकिरण रहित (गैर-आयनकारी) है", "यह रेडियोधर्मी है", "यह शरीर काटता है", "यह प्रकाश देता है"],
     ["It is radiation-free (non-ionising)", "It is radioactive", "It cuts the body", "It emits light"],
     0,
     "X-किरण के विपरीत पराश्रव्य आयनकारी नहीं।",
     "Unlike X-rays, ultrasound does not ionise."),

    ("echo-ultrasound", "medium",
     "एक व्यक्ति घाटी की दीवार की ओर शोर मचाता है — 5 सेकंड बाद प्रतिध्वनि (v = 344) — दीवार की दूरी —",
     "A person shouts at a valley wall — the echo arrives after 5 s (v = 344) — the wall's distance is —",
     ["860 m", "1720 m", "430 m", "344 m"],
     ["860 m", "1720 m", "430 m", "344 m"],
     0,
     "d = 344 × 5/2 = 860 m।",
     "d = 344 × 5/2 = 860 m."),

    ("echo-ultrasound", "medium",
     "पराश्रव्य हार्ड वायर में दरार खोजने में कैसे काम करता है?",
     "How does ultrasound detect cracks inside metal?",
     ["दरार से परावर्तित संकेत स्वस्थ धातु के संकेत से भिन्न समय पर लौटता है", "दरार रंग बदलती है", "धातु गर्म होती है", "धातु चुंबक बनती है"],
     ["The signal reflected by a crack returns at a different time than the sound metal's", "The crack changes colour", "The metal heats up", "The metal magnetises"],
     0,
     "दोष-परावर्तन का समय-अंतर ही संकेत देता है।",
     "The timing gap of the flaw's reflection betrays it."),

    ("echo-ultrasound", "medium",
     "कथन A: प्रतिध्वनि के लिए परावर्तक बड़ा होना चाहिए। कथन B: परावर्तक कम से कम 17.2 m दूर होना चाहिए। सही विकल्प —",
     "Statement A: the reflector for an echo must be large. Statement B: it must be at least about 17.2 m away. The correct option —",
     ["A और B दोनों सही", "केवल A सही", "केवल B सही", "दोनों गलत"],
     ["Both A and B are right", "Only A is right", "Only B is right", "Both are wrong"],
     0,
     "बड़ा परावर्तक पर्याप्त ध्वनि लौटाए; दूरी 17.2 m स्पष्टता दे।",
     "A large reflector returns enough sound; 17.2 m gives clarity."),

    # ---- hard (6) ----
    ("echo-ultrasound", "hard",
     "एक व्यक्ति 172 m दीवार की ओर चलता है और ताली बजाता है — यदि वह हर सेकंड ताली बजाए तो वह प्रतिध्वनि —",
     "Walking towards a wall 172 m away, clapping once per second, the person —",
     ["हर ताली के साथ प्रतिध्वनि भी सुनेगा (1 s में आने-जाने का पथ 344 m)", "केवल आख़िरी प्रतिध्वनि सुनेगा", "कोई प्रतिध्वनि नहीं सुनेगा", "दो प्रतिध्वनि प्रति ताली सुनेगा"],
     ["Hears the echo with each clap (the 344 m round trip takes 1 s)", "Hears only the last echo", "Hears no echo", "Hears two echoes per clap"],
     0,
     "t = 2 × 172/344 = 1 s — ताली और प्रतिध्वनि की लय मेल।",
     "t = 2 × 172/344 = 1 s — clap and echo fall in rhythm."),

    ("echo-ultrasound", "hard",
     "पनडुब्बी SONAR से मछली-झुंड का पल्स 3 सेकंड में वापस पाती है (v = 1500) — झुंड की दूरी —",
     "A submarine's SONAR gets a shoal's pulse back in 3 s (v = 1500) — the shoal's distance is —",
     ["2250 m", "4500 m", "1500 m", "1125 m"],
     ["2250 m", "4500 m", "1500 m", "1125 m"],
     0,
     "d = 1500 × 3/2 = 2250 m।",
     "d = 1500 × 3/2 = 2250 m."),

    ("echo-ultrasound", "hard",
     "परावर्तक से 34.4 m — प्रतिध्वनि सुनने में समय (v = 344) — और क्या वह स्पष्ट सुनाई देगी?",
     "Reflector at 34.4 m — the echo time (v = 344) — and will it be heard distinctly?",
     ["0.2 s — हाँ, स्पष्ट (0.1 s से अधिक)", "0.1 s — नहीं", "2 s — हाँ", "0.02 s — नहीं"],
     ["0.2 s — yes, distinct (above 0.1 s)", "0.1 s — no", "2 s — yes", "0.02 s — no"],
     0,
     "t = 68.8/344 = 0.2 s > 0.1 s — स्पष्ट प्रतिध्वनि।",
     "t = 68.8/344 = 0.2 s > 0.1 s — a distinct echo."),

    ("echo-ultrasound", "hard",
     "कथन A: पराश्रव्य की तरंगदैर्घ्य श्रव्य से कम होती है। कथन B: इसीलिए वह सूक्ष्म दरारें भी पहचानती है। सही विकल्प —",
     "Statement A: ultrasound's wavelength is shorter than audible sound's. Statement B: that is why it detects even fine cracks. The correct option —",
     ["A और B दोनों सही", "केवल A सही", "केवल B सही", "दोनों गलत"],
     ["Both A and B are right", "Only A is right", "Only B is right", "Both are wrong"],
     0,
     "उच्च आवृत्ति = लघु तरंगदैर्घ्य = सूक्ष्म वस्तुओं से परावर्तन।",
     "High frequency = short wavelength = reflection off tiny features."),

    ("echo-ultrasound", "hard",
     "एक लड़का ताली बजाता है और 0.5 सेकंड बाद प्रतिध्वनि सुनता है (v = 344) — दीवार कितनी दूर है?",
     "A boy claps and hears the echo 0.5 s later (v = 344) — how far is the wall?",
     ["86 m", "172 m", "43 m", "344 m"],
     ["86 m", "172 m", "43 m", "344 m"],
     0,
     "d = 344 × 0.5/2 = 86 m।",
     "d = 344 × 0.5/2 = 86 m."),

    ("echo-ultrasound", "hard",
     "अवश्रव्य का एक प्राकृतिक स्रोत और उसका महत्त्व —",
     "A natural source of infrasound and its significance —",
     ["भूकंप — आने वाले झटके का पूर्व-संकेत (पशु पहले भागते हैं)", "बादल — गर्मी बताते हैं", "नदी — बाढ़ भरती है", "पेड़ — छाया देते हैं"],
     ["Earthquakes — an early warning of coming shocks (animals flee first)", "Clouds — they indicate heat", "Rivers — they flood", "Trees — they give shade"],
     0,
     "भूकंपीय अवश्रव्य से कई पशु पहले सतर्क हो जाते हैं।",
     "Seismic infrasound alerts many animals in advance."),
]
