# -*- coding: utf-8 -*-
"""P08 (Light, Reflection & Refraction) — Part 1: light-propagation-materials (50) + reflection-and-mirrors (50) = 100 tuples.
All items authored with correct_idx=0; rotation happens in gen_p08_questions.py.

T1 light-propagation-materials  50 = E20/M21/H9
T2 reflection-and-mirrors       50 = E20/M21/H9
"""

PART1 = [
    # ================= LIGHT PROPAGATION & MATERIALS (50) =================
    # ---- easy (20) ----
    ("light-propagation-materials", "easy",
     "प्रकाश एक प्रकार की किस चीज़ है?",
     "What kind of thing is light?",
     ["ऊर्जा का एक रूप", "पदार्थ का एक रूप", "गैस का एक रूप", "ध्वनि का एक रूप"],
     ["A form of energy", "A form of matter", "A form of gas", "A form of sound"],
     0,
     "प्रकाश ऊर्जा का रूप है जो हमें देखने योग्य बनाती है।",
     "Light is a form of energy that enables us to see."),

    ("light-propagation-materials", "easy",
     "जिन वस्तुओं से स्वयं प्रकाश निकलता है, उन्हें क्या कहते हैं?",
     "Objects that give out light of their own are called?",
     ["दीप्तिमान (स्वप्रकाशित)", "अदीप्तिमान", "पारदर्शी", "परावर्तक"],
     ["Luminous", "Non-luminous", "Transparent", "Reflecting"],
     0,
     "सूर्य, ज्योतिबिंबु (स्टार) और जुगनू दीप्तिमान वस्तुएँ हैं।",
     "The sun, stars and fireflies are luminous objects."),

    ("light-propagation-materials", "easy",
     "निम्न में से कौन-सी अदीप्तिमान वस्तु है?",
     "Which of the following is a non-luminous object?",
     ["चंद्रमा", "सूर्य", "जुगनू", "मोमबत्ती की लौ"],
     ["The moon", "The sun", "A firefly", "A candle flame"],
     0,
     "चंद्रमा स्वयं प्रकाश नहीं देता; वह सूर्य के प्रकाश को परावर्तित करता है।",
     "The moon gives no light of its own; it reflects sunlight."),

    ("light-propagation-materials", "easy",
     "सूर्य प्रकाश का प्राकृतिक या कृत्रिम स्रोत है?",
     "Is the sun a natural or an artificial source of light?",
     ["प्राकृतिक", "कृत्रिम", "दोनों", "न दोनों"],
     ["Natural", "Artificial", "Both", "Neither"],
     0,
     "सूर्य, तारे और जुगनू प्राकृतिक स्रोत हैं; बल्ब, मोमबत्ती कृत्रिम।",
     "Sun, stars and fireflies are natural sources; bulbs and candles are artificial."),

    ("light-propagation-materials", "easy",
     "जुगनू रात में क्यों चमकता है?",
     "Why does a firefly glow at night?",
     ["वह दीप्तिमान वस्तु है — स्वयं प्रकाश उत्पन्न करती है", "वह सूर्य का प्रकाश सोखती है", "वह चंद्रमा से प्रकाश लेती है", "उसके ऊपर बल्ब जलता है"],
     ["It is a luminous object — it produces light itself", "It absorbs sunlight", "It takes light from the moon", "A bulb glows over it"],
     0,
     "जुगनू शरीर में रासायनिक क्रिया से स्वयं प्रकाश बनाता है।",
     "A firefly makes its own light by a chemical reaction in its body."),

    ("light-propagation-materials", "easy",
     "एकसमान माध्यम में प्रकाश कैसे चलती है?",
     "How does light travel in a uniform medium?",
     ["सीधी रेखा में", "वक्र पथ में", "वृत्त में", "ज़िगज़ैग में"],
     ["In a straight line", "In a curved path", "In a circle", "In a zigzag"],
     0,
     "सीधी रेखा में चलना ही प्रकाश का सरल रेखीय प्रसार है।",
     "Travelling in a straight line is the rectilinear propagation of light."),

    ("light-propagation-materials", "easy",
     "प्रकाश के सरल रेखीय प्रसार का सबसे सीधा प्रमाण क्या है?",
     "What is the most direct evidence of the rectilinear propagation of light?",
     ["छाया का बनना", "इंद्रधनुष बनना", "प्रतिध्वनि सुनाई देना", "चुंबकत्व"],
     ["The formation of shadows", "The formation of rainbows", "The hearing of echoes", "Magnetism"],
     0,
     "छाया और ग्रहण सीधी रेखा में चलने के कारण ही बनते हैं।",
     "Shadows and eclipses form precisely because light travels in straight lines."),

    ("light-propagation-materials", "easy",
     "वह वस्तु जिससे प्रकाश पूरी तरह गुज़र सकती है, क्या कहलाती है?",
     "An object through which light can pass completely is called?",
     ["पारदर्शी", "पारदर्शक", "अपारदर्शी", "परावर्तक"],
     ["Transparent", "Translucent", "Opaque", "Reflector"],
     0,
     "काँच और साफ़ जल पारदर्शी हैं — उनसे होकर वस्तु साफ़ दिखती है।",
     "Glass and clear water are transparent — objects are seen clearly through them."),

    ("light-propagation-materials", "easy",
     "निम्न में से पारदर्शी पदार्थ कौन-सा है?",
     "Which of the following is a transparent material?",
     ["काँच की शीट", "बटर पेपर", "लकड़ी का बोर्ड", "धातु की प्लेट"],
     ["A glass sheet", "Butter paper", "A wooden board", "A metal plate"],
     0,
     "काँच से प्रकाश पूरी तरह गुज़रती है, इसलिए वह पारदर्शी है।",
     "Light passes fully through glass, so glass is transparent."),

    ("light-propagation-materials", "easy",
     "बटर पेपर और फ्रॉस्टेड ग्लास किस वर्ग के पदार्थ हैं?",
     "Butter paper and frosted glass belong to which class of materials?",
     ["पारदर्शक (translucent)", "पारदर्शी (transparent)", "अपारदर्शी (opaque)", "दीप्तिमान (luminous)"],
     ["Translucent", "Transparent", "Opaque", "Luminous"],
     0,
     "पारदर्शक से प्रकाश आंशिक रूप से गुज़रती है — वस्तु धुँधली दिखती है।",
     "Light passes partially through translucent materials — objects look blurred."),

    ("light-propagation-materials", "easy",
     "अपारदर्शी पदार्थ के साथ कौन-सा कथन सही है?",
     "Which statement is correct for an opaque material?",
     ["वह प्रकाश को रोक देता है और अपनी छाया बनाता है", "वह प्रकाश को पूरी तरह पार जाने देता है", "वह प्रकाश को आधा गुज़रने देता है", "वह स्वयं प्रकाश उत्पन्न करता है"],
     ["It blocks light and casts a shadow", "It lets light pass fully", "It lets half the light pass", "It produces its own light"],
     0,
     "लकड़ी, कार्डबोर्ड जैसे अपारदर्शी पदार्थ प्रकाश रोकते हैं।",
     "Opaque materials like wood and cardboard block light."),

    ("light-propagation-materials", "easy",
     "निम्न में से अपारदर्शी वस्तु कौन-सी है?",
     "Which of the following is an opaque object?",
     ["किताब", "साफ़ पानी", "हवा", "काँच"],
     ["A book", "Clear water", "Air", "Glass"],
     0,
     "किताब प्रकाश रोकती है, इसलिए अपारदर्शी है।",
     "A book blocks light, hence it is opaque."),

    ("light-propagation-materials", "easy",
     "निर्वात में प्रकाश की चाल लगभग कितनी होती है?",
     "What is the approximate speed of light in vacuum?",
     ["3 × 10^8 मीटर/सेकंड", "3 × 10^5 मीटर/सेकंड", "344 मीटर/सेकंड", "3 × 10^10 मीटर/सेकंड"],
     ["3 × 10^8 m/s", "3 × 10^5 m/s", "344 m/s", "3 × 10^10 m/s"],
     0,
     "निर्वात में प्रकाश की चाल लगभग 3 × 10^8 मीटर प्रति सेकंड है।",
     "Light travels at about 3 × 10^8 metres per second in vacuum."),

    ("light-propagation-materials", "easy",
     "प्रकाश वर्ष किस चीज़ का मात्रक है?",
     "A light-year is a unit of what?",
     ["दूरी का", "समय का", "चाल का", "ऊर्जा का"],
     ["Distance", "Time", "Speed", "Energy"],
     0,
     "प्रकाश एक वर्ष में जितनी दूरी तय करती है, वही एक प्रकाश वर्ष है — यह दूरी का मात्रक है।",
     "A light-year is the distance light covers in one year — a unit of distance."),

    ("light-propagation-materials", "easy",
     "हम किसी अदीप्तिमान वस्तु को क्यों देख पाते हैं?",
     "Why are we able to see a non-luminous object?",
     ["वस्तु से परावर्तित प्रकाश हमारी आँखों में प्रवेश करती है", "वस्तु स्वयं प्रकाश बनाती है", "आँखें वस्तु तक किरण भेजती हैं", "वस्तु ध्वनि द्वारा दिखती है"],
     ["Light reflected from the object enters our eyes", "The object makes its own light", "Our eyes send rays to the object", "The object is seen via sound"],
     0,
     "देखने के लिए वस्तु से आँख तक परावर्तित प्रकाश पहुँचना ज़रूरी है।",
     "To see an object, light reflected from it must reach our eyes."),

    ("light-propagation-materials", "easy",
     "छेद वाला कैमरा (पिनहोल कैमरा) किस प्रकार का प्रतिबिंब बनाता है?",
     "What type of image does a pinhole camera form?",
     ["उल्टा (वास्तविक)", "सीधा", "आभासी और सीधा", "बड़ा और सीधा"],
     ["Inverted (real)", "Erect", "Virtual and erect", "Enlarged and erect"],
     0,
     "सीधी रेखा में चलती किरणें छेद से गुज़रकर ऊपर-नीचे उलट जाती हैं।",
     "Rays travelling straight cross the hole and get inverted top-to-bottom."),

    ("light-propagation-materials", "easy",
     "सूर्य ग्रहण के समय कौन किसके बीच में होता है?",
     "During a solar eclipse, what lies between what?",
     ["चंद्रमा, सूर्य और पृथ्वी के बीच", "पृथ्वी, सूर्य और चंद्रमा के बीच", "सूर्य, पृथ्वी और चंद्रमा के बीच", "कोई नहीं"],
     ["The moon lies between the sun and the earth", "The earth lies between the sun and the moon", "The sun lies between the earth and the moon", "Nothing lies between them"],
     0,
     "सूर्य ग्रहण में चंद्रमा सूर्य की रोशनी रोकता है; चंद्र ग्रहण में पृथ्वी।",
     "In a solar eclipse the moon blocks sunlight; in a lunar eclipse the earth does."),

    ("light-propagation-materials", "easy",
     "चंद्र ग्रहण केवल किस रात को हो सकता है?",
     "A lunar eclipse can occur only on which night?",
     ["पूर्णिमा की रात", "अमावस्या की रात", "अष्टमी की रात", "किसी भी रात"],
     ["A full-moon night", "A new-moon night", "An eighth-day night", "Any night"],
     0,
     "चंद्र ग्रहण के लिए पृथ्वी को सूर्य-चंद्रमा के ठीक बीच आना ज़रूरी है — यह पूर्णिमा को ही होता है।",
     "For a lunar eclipse the earth must sit exactly between the sun and moon — possible only on a full-moon night."),

    ("light-propagation-materials", "easy",
     "निर्वात में भी सूर्य का प्रकाश पृथ्वी तक पहुँचता है। इसका कारण बताइए।",
     "Sunlight reaches the earth even through vacuum. State the reason.",
     ["प्रकाश को प्रसार के लिए माध्यम की आवश्यकता नहीं होती", "निर्वात में हवा होती है", "सूर्य ध्वनि भी भेजता है", "पृथ्वी प्रकाश खींच लेती है"],
     ["Light does not need a medium to travel", "Vacuum contains air", "The sun also sends sound", "The earth pulls the light"],
     0,
     "प्रकाश विद्युत-चुंबकीय तरंग है — माध्यम के बिना भी चलती है।",
     "Light is an electromagnetic wave — it travels even without a medium."),

    ("light-propagation-materials", "easy",
     "हमें पास की वस्तु की छाया तेज़ क्यों दिखती है?",
     "Why does the shadow of a nearby object look sharp?",
     ["पास की वस्तु की छाया में पूर्ण छाया (umbra) प्रमुख होती है", "दूर की वस्तु प्रकाश बिखेरती है", "पास की वस्तु दीप्तिमान होती है", "छाया रंगीन हो जाती है"],
     ["For a nearby object the full shadow (umbra) dominates", "A distant object scatters light", "A nearby object is luminous", "The shadow becomes coloured"],
     0,
     "पास की वस्तु अधिकांश प्रकाश रोकती है और पूर्ण छाया बड़ी व तेज़ बनती है।",
     "A nearby object blocks most light, forming a large, sharp umbra."),

    # ---- medium (21) ----
    ("light-propagation-materials", "medium",
     "बिंदु स्रोत और विस्तृत स्रोत से बनी छाया में मुख्य अंतर क्या होता है?",
     "What is the main difference between shadows formed by a point source and an extended source?",
     ["बिंदु स्रोत से केवल पूर्ण छाया बनती है, विस्तृत स्रोत से पूर्ण व आंशिक दोनों", "दोनों से एक जैसी छाया बनती है", "विस्तृत स्रोत से छाया नहीं बनती", "बिंदु स्रोत से छाया रंगीन होती है"],
     ["A point source gives only umbra; an extended source gives both umbra and penumbra", "Both give identical shadows", "An extended source gives no shadow", "A point source gives a coloured shadow"],
     0,
     "विस्तृत स्रोत के विभिन्न भागों से आने वाली किरणें आंशिक छाया बनाती हैं।",
     "Rays from different parts of an extended source create a partial shadow too."),

    ("light-propagation-materials", "medium",
     "आंशिक छाया (penumbra) कब बनती है?",
     "When is a penumbra formed?",
     ["जब प्रकाश स्रोत विस्तृत (बड़ा) हो", "जब प्रकाश स्रोत बिंदु हो", "जब वस्तु पारदर्शी हो", "जब वस्तु दीप्तिमान हो"],
     ["When the light source is extended (large)", "When the source is a point", "When the object is transparent", "When the object is luminous"],
     0,
     "बड़े स्रोत की कुछ किरणें वस्तु के किनारे से निकलकर आंशिक छाया बनाती हैं।",
     "Some rays from a large source pass the object's edge, forming the penumbra."),

    ("light-propagation-materials", "medium",
     "पिनहोल कैमरे में छेद छोटा रखने पर प्रतिबिंब कैसा बनता है?",
     "What happens to the image in a pinhole camera when the hole is made smaller?",
     ["प्रतिबिंब अधिक स्पष्ट (तेज़) बनता है", "प्रतिबिंब उल्टा हो जाता है", "प्रतिबिंब बड़ा हो जाता है", "प्रतिबिंब रंगीन हो जाता है"],
     ["The image becomes sharper", "The image gets inverted", "The image becomes larger", "The image becomes coloured"],
     0,
     "छोटे छेद से प्रत्येक बिंदु से कम किरणें गुज़रती हैं, इसलिए प्रतिबिंब स्पष्ट होता है।",
     "A smaller hole lets fewer rays per point pass, so the image is sharper."),

    ("light-propagation-materials", "medium",
     "पिनहोल कैमरे का प्रतिबिंब उल्टा क्यों बनता है?",
     "Why is the image in a pinhole camera inverted?",
     ["क्योंकि प्रकाश सीधी रेखा में चलकर छेद से गुज़रती है और आर-पार हो जाती है", "क्योंकि कैमरे में लेंस होता है", "क्योंकि छेद चुंबकीय होता है", "क्योंकि प्रकाश वक्र रेखा में चलती है"],
     ["Because light travels in straight lines and crosses over at the hole", "Because the camera has a lens", "Because the hole is magnetic", "Because light travels in a curve"],
     0,
     "वस्तु के ऊपरी भाग की किरणें छेद से गुज़रकर पर्दे के निचले भाग पर पड़ती हैं।",
     "Rays from the top of the object cross the hole and land on the bottom of the screen."),

    ("light-propagation-materials", "medium",
     "सूर्य से पृथ्वी तक प्रकाश को लगभग कितना समय लगता है? (दूरी लगभग 1.5 × 10^11 मीटर)",
     "How long does light take from the sun to the earth? (distance about 1.5 × 10^11 m)",
     ["लगभग 500 सेकंड", "लगभग 50 सेकंड", "लगभग 5 सेकंड", "लगभग 5000 सेकंड"],
     ["About 500 seconds", "About 50 seconds", "About 5 seconds", "About 5000 seconds"],
     0,
     "t = d/c = (1.5 × 10^11) / (3 × 10^8) = 500 सेकंड = 8 मिनट 20 सेकंड।",
     "t = d/c = (1.5 × 10^11) / (3 × 10^8) = 500 s = 8 min 20 s."),

    ("light-propagation-materials", "medium",
     "चंद्रमा से पृथ्वी तक प्रकाश को लगभग कितना समय लगता है? (दूरी लगभग 3.8 × 10^8 मीटर)",
     "How long does light take from the moon to the earth? (distance about 3.8 × 10^8 m)",
     ["लगभग 1.3 सेकंड", "लगभग 13 सेकंड", "लगभग 0.13 सेकंड", "लगभग 130 सेकंड"],
     ["About 1.3 seconds", "About 13 seconds", "About 0.13 seconds", "About 130 seconds"],
     0,
     "t = (3.8 × 10^8) / (3 × 10^8) = 1.27 लगभग 1.3 सेकंड।",
     "t = (3.8 × 10^8) / (3 × 10^8) = 1.27, about 1.3 seconds."),

    ("light-propagation-materials", "medium",
     "कोई संकेत 600 सेकंड तक निर्वात में चलता है। वह कितनी दूरी तय करेगा?",
     "A signal travels in vacuum for 600 seconds. What distance does it cover?",
     ["1.8 × 10^11 मीटर", "1.8 × 10^8 मीटर", "1.8 × 10^14 मीटर", "6 × 10^8 मीटर"],
     ["1.8 × 10^11 m", "1.8 × 10^8 m", "1.8 × 10^14 m", "6 × 10^8 m"],
     0,
     "d = c × t = 3 × 10^8 × 600 = 1.8 × 10^11 मीटर।",
     "d = c × t = 3 × 10^8 × 600 = 1.8 × 10^11 m."),

    ("light-propagation-materials", "medium",
     "एक प्रकाश वर्ष में लगभग कितनी दूरी होती है?",
     "Approximately how much distance is one light-year?",
     ["9.5 × 10^12 किलोमीटर", "9.5 × 10^8 किलोमीटर", "3 × 10^8 किलोमीटर", "9.5 × 10^15 किलोमीटर"],
     ["9.5 × 10^12 km", "9.5 × 10^8 km", "3 × 10^8 km", "9.5 × 10^15 km"],
     0,
     "c × एक वर्ष = 3 × 10^8 × 3.15 × 10^7 सेकंड = 9.46 × 10^15 मीटर = 9.5 × 10^12 किलोमीटर।",
     "c × one year = 3 × 10^8 × 3.15 × 10^7 s = 9.46 × 10^15 m = 9.5 × 10^12 km."),

    ("light-propagation-materials", "medium",
     "2 प्रकाश वर्ष बराबर कितने किलोमीटर होंगे?",
     "2 light-years equal how many kilometres?",
     ["लगभग 1.9 × 10^13 किलोमीटर", "लगभग 1.9 × 10^12 किलोमीटर", "लगभग 9.5 × 10^13 किलोमीटर", "लगभग 1.9 × 10^10 किलोमीटर"],
     ["About 1.9 × 10^13 km", "About 1.9 × 10^12 km", "About 9.5 × 10^13 km", "About 1.9 × 10^10 km"],
     0,
     "2 × 9.5 × 10^12 = 1.9 × 10^13 किलोमीटर।",
     "2 × 9.5 × 10^12 = 1.9 × 10^13 km."),

    ("light-propagation-materials", "medium",
     "फ्रॉस्टेड ग्लास से देखने पर वस्तु स्पष्ट क्यों नहीं दिखती?",
     "Why is an object not seen clearly through frosted glass?",
     ["प्रकाश उसमें बिखर जाती है, इसलिए प्रतिबिंब धुँधला बनता है", "फ्रॉस्टेड ग्लास प्रकाश रोक देता है", "वह पूरी प्रकाश सोख लेता है", "वह प्रकाश उत्पन्न करता है"],
     ["Light scatters inside it, so the image is blurred", "Frosted glass blocks all light", "It absorbs all light", "It produces light"],
     0,
     "फ्रॉस्टेड ग्लास पारदर्शक है — आंशिक प्रकाश बिखरकर गुज़रती है।",
     "Frosted glass is translucent — partial light passes after scattering."),

    ("light-propagation-materials", "medium",
     "पानी से भरे गिलास में रखी पेंसिल मुड़ी हुई दिखती है। यह किस घटना का उदाहरण है?",
     "A pencil kept in a glass of water appears bent. Which phenomenon is this?",
     ["अपवर्तन", "परावर्तन", "विक्षेपण", "अवशोषण"],
     ["Refraction", "Reflection", "Dispersion", "Absorption"],
     0,
     "जल और वायु में प्रकाश की चाल भिन्न है, इसलिए किरण दिशा बदलती है — यही अपवर्तन है (विस्तार अगले खंड में)।",
     "Light changes speed between water and air, so the ray bends — this is refraction (detailed later)."),

    ("light-propagation-materials", "medium",
     "वायु, जल और काँच — इन तीनों में प्रकाश की चाल का सही क्रम बताइए।",
     "State the correct order of the speed of light in air, water and glass.",
     ["वायु में सबसे अधिक, फिर जल, फिर काँच में सबसे कम", "काँच में सबसे अधिक, फिर जल, फिर वायु", "तीनों में बराबर", "जल में सबसे अधिक"],
     ["Fastest in air, then water, slowest in glass", "Fastest in glass, then water, then air", "Equal in all three", "Fastest in water"],
     0,
     "जितना सघन माध्यम, उतनी कम चाल — काँच का सघनत्व जल से अधिक है।",
     "The denser the medium, the slower the light — glass is denser than water."),

    ("light-propagation-materials", "medium",
     "पेड़ के पीछे छिपा व्यक्ति दिखाई नहीं देता। इसका कारण बताइए।",
     "A person hidden behind a tree cannot be seen. Give the reason.",
     ["प्रकाश सीधी रेखा में चलती है और अपारदर्शी वृक्ष उसे रोकता है", "व्यक्ति अदीप्तिमान है", "प्रकाश वक्र रेखा में मुड़ जाती है", "वृक्ष प्रकाश सोख लेता है"],
     ["Light travels in a straight line and the opaque tree blocks it", "The person is non-luminous", "Light bends around the tree", "The tree absorbs the light"],
     0,
     "सरल रेखीय प्रसार के कारण वृक्ष के पीछे की किरणें आँख तक नहीं पहुँचतीं।",
     "Due to rectilinear propagation, rays from behind the tree never reach the eye."),

    ("light-propagation-materials", "medium",
     "किसी इमारत की ऊँचाई 2 मीटर वाली छड़ 3 मीटर की छाया बनाती है। उसी समय 4 मीटर लंबी छड़ की छाया कितनी होगी?",
     "A 2 m stick casts a 3 m shadow. At the same time, what shadow will a 4 m stick cast?",
     ["6 मीटर", "3 मीटर", "4.5 मीटर", "12 मीटर"],
     ["6 m", "3 m", "4.5 m", "12 m"],
     0,
     "समान त्रिभुज: छाया/छड़ = 3/2, अतः 4 मीटर छड़ की छाया = 4 × 3/2 = 6 मीटर।",
     "Similar triangles: shadow/stick = 3/2, so a 4 m stick casts 4 × 3/2 = 6 m."),

    ("light-propagation-materials", "medium",
     "ग्रहण के समय चंद्रमा का छाया क्षेत्र पृथ्वी पर गिरता है। यह कौन-सा ग्रहण है?",
     "The moon's shadow falls on the earth during an eclipse. Which eclipse is this?",
     ["सूर्य ग्रहण", "चंद्र ग्रहण", "दोनों", "कोई नहीं"],
     ["A solar eclipse", "A lunar eclipse", "Both", "Neither"],
     0,
     "चंद्रमा की छाया पृथ्वी पर — सूर्य ग्रहण; पृथ्वी की छाया चंद्रमा पर — चंद्र ग्रहण।",
     "Moon's shadow on the earth — solar eclipse; earth's shadow on the moon — lunar eclipse."),

    ("light-propagation-materials", "medium",
     "जब प्रकाश किरण किसी वस्तु से टकराती है तो क्या होता है?",
     "What happens when a light ray strikes an object?",
     ["उसका कुछ भाग परावर्तित, कुछ अवशोषित और कुछ (यदि पारदर्शी हो तो) गुज़र जाता है", "पूरी किरण वापस लौट आती है", "पूरी किरण सोख ली जाती है", "किरण गायब हो जाती है"],
     ["Part is reflected, part absorbed and part (if transparent) transmitted", "The whole ray returns back", "The whole ray is absorbed", "The ray vanishes"],
     0,
     "परावर्तन, अवशोषण और संचरण प्रायः एक साथ होते हैं।",
     "Reflection, absorption and transmission usually happen together."),

    ("light-propagation-materials", "medium",
     "रात में चाँद हमें क्यों चमकता दिखता है?",
     "Why does the moon appear bright to us at night?",
     ["वह सूर्य के प्रकाश को परावर्तित करता है", "वह स्वयं प्रकाश उत्पन्न करता है", "वह तारों का प्रकाश बढ़ा देता है", "पृथ्वी का प्रकाश उस पर पड़ता है"],
     ["It reflects sunlight", "It produces its own light", "It amplifies starlight", "Earth's light falls on it"],
     0,
     "चंद्रमा अदीप्तिमान है — सूर्य-प्रकाश परावर्तित होकर हम तक आता है।",
     "The moon is non-luminous — reflected sunlight reaches us."),

    ("light-propagation-materials", "medium",
     "काँच की शीट पर तेल का थोड़ा लेप लगा दिया जाए तो वह कैसी वस्तु बन जाती है?",
     "If a little oil is smeared on a glass sheet, what does it become?",
     ["पारदर्शक", "अपारदर्शी", "दीप्तिमान", "परावर्तक दर्पण"],
     ["Translucent", "Opaque", "Luminous", "A plane mirror"],
     0,
     "तेल के कारण प्रकाश बिखरकर आंशिक रूप से गुज़रती है — पारदर्शक।",
     "The oil scatters light; only part passes through — translucent."),

    ("light-propagation-materials", "medium",
     "धूप में खड़े व्यक्ति की छाया सुबह लंबी और दोपहर छोटी क्यों होती है?",
     "Why is a person's shadow long in the morning and short at noon?",
     ["सूर्य की दिशा बदलने से प्रकाश आपतन कोण बदलता है", "व्यक्ति की लंबाई दोपहर घट जाती है", "सुबह प्रकाश धीमी चलती है", "छाया रंग बदलती है"],
     ["The sun's direction changes, changing the angle at which light falls", "The person's height decreases at noon", "Light travels slower in the morning", "The shadow changes colour"],
     0,
     "तिरछी किरणें लंबी छाया बनाती हैं; दोपहर की लंबवत किरणें छोटी।",
     "Slanting rays make long shadows; vertical noon rays make short ones."),

    ("light-propagation-materials", "medium",
     "एक बिंदु स्रोत से प्रकाश में गेंद रखने पर पर्दे पर बनी छाया कैसी होती है?",
     "A ball is placed in light from a point source. What is the shadow on the screen like?",
     ["पूर्णतः गहरी (केवल पूर्ण छाया)", "केवल आंशिक छाया", "कोई छाया नहीं", "छल्ले जैसी छाया"],
     ["Completely dark (only umbra)", "Only penumbra", "No shadow", "A ring-shaped shadow"],
     0,
     "बिंदु स्रोत से हर बिंदु से एक ही दिशा में किरणें — केवल पूर्ण छाया बनती है।",
     "A point source sends rays in single directions — only a full shadow forms."),

    ("light-propagation-materials", "medium",
     "सौर ग्रहण में चंद्रमा के आंशिक छाया क्षेत्र (पेनम्ब्रा) में खड़े दर्शक को क्या दिखता है?",
     "What does a viewer standing in the moon's partial shadow (penumbra) during a solar eclipse see?",
     ["आंशिक सूर्य ग्रहण", "पूर्ण सूर्य ग्रहण", "कुछ नहीं", "चंद्र ग्रहण"],
     ["A partial solar eclipse", "A total solar eclipse", "Nothing", "A lunar eclipse"],
     0,
     "पेनम्ब्रा में सूर्य का कुछ भाग दिखता रहता है — आंशिक ग्रहण।",
     "In the penumbra part of the sun remains visible — a partial eclipse."),

    # ---- hard (9) ----
    ("light-propagation-materials", "hard",
     "पिनहोल कैमरे में दो छेद कर दिए जाएँ तो पर्दे पर क्या दिखेगा?",
     "If two holes are made in a pinhole camera, what appears on the screen?",
     ["वस्तु के दो प्रतिबिंब", "एक ही तीखा प्रतिबिंब", "कोई प्रतिबिंब नहीं", "वस्तु का सीधा प्रतिबिंब"],
     ["Two images of the object", "One sharper image", "No image at all", "An erect image of the object"],
     0,
     "प्रत्येक छेद से स्वतंत्र किरण-पुंज गुज़रता है, इसलिए दो प्रतिबिंब बनते हैं।",
     "Each hole passes its own beam, so two images form."),

    ("light-propagation-materials", "hard",
     "पिनहोल कैमरे में पर्दे को छेद से दूर ले जाने पर प्रतिबिंब का आकार कैसे बदलता है?",
     "In a pinhole camera, what happens to the image size when the screen is moved farther from the hole?",
     ["प्रतिबिंब बड़ा हो जाता है", "प्रतिबिंब छोटा हो जाता है", "कोई परिवर्तन नहीं", "प्रतिबिंब सीधा हो जाता है"],
     ["The image becomes larger", "The image becomes smaller", "No change", "The image becomes erect"],
     0,
     "प्रतिबिंब का आकार पर्दे-छेद दूरी के अनुक्रमानुपाती होता है।",
     "Image size grows in proportion to the hole-screen distance."),

    ("light-propagation-materials", "hard",
     "एक वृत्ताकार गेंद को बिंदु स्रोत से दूर ले जाने पर पर्दे पर उसकी छाया का आकार कैसा होगा?",
     "A ball is moved away from a point source. What happens to the size of its shadow on a fixed screen?",
     ["छाया छोटी होती जाती है", "छाया बड़ी होती जाती है", "छाया का आकार अपरिवर्तित रहता है", "छाया पहले बड़ी फिर छोटी होती है"],
     ["The shadow becomes smaller", "The shadow becomes larger", "The shadow size stays unchanged", "It first grows then shrinks"],
     0,
     "वस्तु स्रोत से दूर जाने पर प्रकाश-कोण संकुचित होता जाता है और पर्दे पर छाया छोटी बनती है।",
     "As the object recedes, the shadow cone narrows and the shadow on the screen shrinks."),

    ("light-propagation-materials", "hard",
     "सीधी रबर ट्यूब से मोमबत्ती दिखती है परंतु मुड़ी हुई ट्यूब से नहीं। यह प्रयोग किस तथ्य को सिद्ध करता है?",
     "A candle is visible through a straight rubber tube but not through a bent one. What does this experiment prove?",
     ["प्रकाश सरल रेखा में चलती है", "प्रकाश परावर्तित होती है", "ट्यूब प्रकाश सोखती है", "प्रकाश को माध्यम चाहिए"],
     ["Light travels in straight lines", "Light gets reflected", "The tube absorbs light", "Light needs a medium"],
     0,
     "मुड़ी ट्यूब प्रकाश-पथ को रोकती है, इसलिए दृश्यता समाप्त हो जाती है।",
     "A bent tube blocks the light path, ending visibility."),

    ("light-propagation-materials", "hard",
     "पूर्ण सूर्य ग्रहण के समय पृथ्वी पर ठीक चंद्रमा की पूर्ण छाया (अम्ब्रा) में स्थित स्थान कहलाता है?",
     "During a total solar eclipse, the region on the earth lying exactly in the moon's full shadow (umbra) is called?",
     ["पूर्णता का पथ (टोटैलिटी पथ)", "पेनम्ब्रा मंडल", "दृश्य क्षेत्र", "प्रकाश मंडल"],
     ["The path of totality", "The penumbral zone", "The field of view", "The zone of illumination"],
     0,
     "अम्ब्रा में सूर्य पूर्ण रूप से ढक जाता है — यही पूर्णता का पथ है।",
     "In the umbra the sun is fully covered — this is the path of totality."),

    ("light-propagation-materials", "hard",
     "किसी दूर के ग्रह तक प्रकाश को 4 वर्ष लगते हैं। ग्रह की दूरी पृथ्वी से कितनी है?",
     "Light takes 4 years to reach a planet. How far is the planet from the earth?",
     ["4 प्रकाश वर्ष", "4 × 10^8 मीटर", "4 किलोमीटर", "12 प्रकाश वर्ष"],
     ["4 light-years", "4 × 10^8 m", "4 kilometres", "12 light-years"],
     0,
     "प्रकाश-यात्रा समय जितने वर्ष, दूरी उतने प्रकाश वर्ष।",
     "However many years light travels, the distance equals that many light-years."),

    ("light-propagation-materials", "hard",
     "एक अपारदर्शी गेंद को विस्तृत (बड़े) प्रकाश स्रोत से प्रकाशित किया जाता है। पर्दे पर छाया के कितने भाग बनते हैं?",
     "An opaque ball is lit by an extended (large) source. How many regions does its shadow on the screen have?",
     ["दो — पूर्ण छाया और आंशिक छाया", "एक — केवल पूर्ण छाया", "एक — केवल आंशिक छाया", "तीन — दो पूर्ण, एक आंशिक"],
     ["Two — umbra and penumbra", "One — only umbra", "One — only penumbra", "Three — two umbrae, one penumbra"],
     0,
     "विस्तृत स्रोत से बनी छाया में केंद्र में अम्ब्रा और चारों ओर पेनम्ब्रा होती है।",
     "A shadow from an extended source has a central umbra surrounded by penumbra."),

    ("light-propagation-materials", "hard",
     "पारदर्शक पर्दे से आने वाली रोशनी वाले कमरे में पढ़ना कठिन क्यों होता है?",
     "Why is it hard to read in a room lit only through a translucent screen?",
     ["प्रकाश बिखरकर विभिन्न दिशाओं में आती है और समान रोशनी नहीं मिलती", "कमरे में प्रकाश बिल्कुल नहीं आती", "प्रकाश का रंग बदल जाता है", "आँखें बंद हो जाती हैं"],
     ["Light scatters in many directions, so even illumination is not obtained", "No light enters the room at all", "The colour of light changes", "The eyes close"],
     0,
     "पारदर्शक पर्दा प्रकाश को बिखेर देता है — तीव्र, सीधी रोशनी नहीं मिलती।",
     "A translucent screen scatters light — no direct, intense illumination is available."),

    ("light-propagation-materials", "hard",
     "कोई संकेत 2 × 10^8 मीटर/सेकंड की चाल से चलता है। 5 सेकंड में वह कितनी दूरी तय करेगा?",
     "A signal travels at 2 × 10^8 m/s. How far does it travel in 5 seconds?",
     ["10^9 मीटर", "10^8 मीटर", "10^10 मीटर", "2 × 10^9 मीटर"],
     ["10^9 m", "10^8 m", "10^10 m", "2 × 10^9 m"],
     0,
     "d = v × t = 2 × 10^8 × 5 = 10 × 10^8 = 10^9 मीटर।",
     "d = v × t = 2 × 10^8 × 5 = 10 × 10^8 = 10^9 m."),

    # ================= REFLECTION & MIRRORS (50) =================
    # ---- easy (20) ----
    ("reflection-and-mirrors", "easy",
     "प्रकाश का परावर्तन किसे कहते हैं?",
     "What is reflection of light?",
     ["प्रकाश का किसी सतह से टकराकर उसी माध्यम में वापस लौटना", "प्रकाश का एक माध्यम से दूसरे में जाना", "प्रकाश का सात रंगों में बँटना", "प्रकाश का सोखा जाना"],
     ["Light bouncing back into the same medium after striking a surface", "Light passing from one medium into another", "Light splitting into seven colours", "Light being absorbed"],
     0,
     "उसी माध्यम में वापसी ही परावर्तन है; माध्यम बदलना अपवर्तन है।",
     "Returning into the same medium is reflection; changing medium is refraction."),

    ("reflection-and-mirrors", "easy",
     "आपतन कोण और परावर्तन कोण में क्या संबंध है?",
     "What is the relation between the angle of incidence and the angle of reflection?",
     ["दोनों बराबर होते हैं", "आपतन कोण दुगुना होता है", "परावर्तन कोण आधा होता है", "दोनों का कोई संबंध नहीं"],
     ["They are equal", "The angle of incidence is double", "The angle of reflection is half", "They are unrelated"],
     0,
     "परावर्तन का प्रथम नियम — आपतन कोण सदैव परावर्तन कोण के बराबर होता है।",
     "First law of reflection — the angle of incidence always equals the angle of reflection."),

    ("reflection-and-mirrors", "easy",
     "परावर्तन में अभिलंब (normal) क्या होता है?",
     "What is the normal in reflection?",
     ["आपतन बिंदु पर दर्पण पर लंबवत खींची गई काल्पनिक रेखा", "दर्पण के समांतर रेखा", "आपतित किरण स्वयं", "दर्पण की मोटाई"],
     ["An imaginary line perpendicular to the mirror at the point of incidence", "A line parallel to the mirror", "The incident ray itself", "The thickness of the mirror"],
     0,
     "दोनों कोण अभिलंब से मापे जाते हैं।",
     "Both angles are measured from the normal."),

    ("reflection-and-mirrors", "easy",
     "समतल दर्पण में बना प्रतिबिंब किस प्रकार का होता है?",
     "What type of image is formed by a plane mirror?",
     ["आभासी और सीधा", "वास्तविक और उल्टा", "वास्तविक और सीधा", "आभासी और उल्टा"],
     ["Virtual and erect", "Real and inverted", "Real and erect", "Virtual and inverted"],
     0,
     "समतल दर्पण का प्रतिबिंब आभासी, सीधा और समान आकार का होता है।",
     "A plane mirror forms a virtual, erect, same-size image."),

    ("reflection-and-mirrors", "easy",
     "समतल दर्पण में प्रतिबिंब का आकार वस्तु से कैसा होता है?",
     "How does the size of a plane-mirror image compare with the object?",
     ["बिल्कुल समान", "बड़ा", "छोटा", "आधा"],
     ["Exactly the same", "Larger", "Smaller", "Half"],
     0,
     "समतल दर्पण आकार नहीं बदलता — प्रतिबिंब समान आकार का बनता है।",
     "A plane mirror does not change size — the image is the same size."),

    ("reflection-and-mirrors", "easy",
     "समतल दर्पण का प्रतिबिंब किस दिशा में उलटा होता है?",
     "In which direction does a plane mirror reverse the image?",
     ["बायाँ-दायाँ उलट जाता है (पार्श्व उन्नयन)", "ऊपर-नीचे उलट जाता है", "कुछ नहीं बदलता", "प्रतिबिंब उल्टा और झुका होता है"],
     ["Left and right get interchanged (lateral inversion)", "Top and bottom get interchanged", "Nothing changes", "The image is inverted and tilted"],
     0,
     "पार्श्व उन्नयन में केवल बायाँ-दायाँ बदलता है, ऊपर-नीचे नहीं।",
     "In lateral inversion only left and right swap; top and bottom stay."),

    ("reflection-and-mirrors", "easy",
     "एम्बुलेंस पर AMBULANCE उल्टा क्यों लिखा होता है?",
     "Why is AMBULANCE written in reverse on ambulances?",
     ["ताकि वाहन के दर्पण में वह सीधा पढ़ा जा सके", "सजावट के लिए", "कानून के अनुसार उल्टा लिखना है", "ताकि दूर से दिखे"],
     ["So that it reads correctly in the vehicle's mirror", "For decoration", "The law requires reverse writing", "So that it is visible from far"],
     0,
     "दर्पण पार्श्व उन्नयन करता है — उल्टा लिखा शब्द दर्पण में सीधा दिखता है।",
     "A mirror laterally inverts — the reversed word reads straight in the mirror."),

    ("reflection-and-mirrors", "easy",
     "वस्तु समतल दर्पण से 5 मीटर दूर है। प्रतिबिंब दर्पण से कितनी दूर बनेगा?",
     "An object is 5 m from a plane mirror. How far behind the mirror is the image?",
     ["5 मीटर पीछे", "10 मीटर पीछे", "2.5 मीटर पीछे", "दर्पण पर ही"],
     ["5 m behind", "10 m behind", "2.5 m behind", "On the mirror itself"],
     0,
     "प्रतिबिंब की दूरी = वस्तु की दूरी, दर्पण के पीछे।",
     "Image distance equals object distance, behind the mirror."),

    ("reflection-and-mirrors", "easy",
     "नियमित (सुसंगत) परावर्तन किस सतह से होता है?",
     "Regular (specular) reflection occurs from which surface?",
     ["चिकनी (समतल) सतह जैसे दर्पण", "खुरदरी सतह जैसे दीवार", "काले कपड़े", "लकड़ी का तख्ता"],
     ["A smooth surface like a mirror", "A rough surface like a wall", "Black cloth", "A wooden plank"],
     0,
     "चिकनी सतह पर समांतर किरणें परावर्तन के बाद भी समांतर रहती हैं।",
     "On a smooth surface parallel rays remain parallel after reflection."),

    ("reflection-and-mirrors", "easy",
     "खुरदरी सतह से होने वाले परावर्तन को क्या कहते हैं?",
     "Reflection from a rough surface is called?",
     ["विकीर्ण (असमान) परावर्तन", "नियमित परावर्तन", "अपवर्तन", "अवशोषण"],
     ["Diffused (irregular) reflection", "Regular reflection", "Refraction", "Absorption"],
     0,
     "खुरदरी सतह किरणों को विभिन्न दिशाओं में बिखेर देती है।",
     "A rough surface sends rays off in different directions."),

    ("reflection-and-mirrors", "easy",
     "अवतल दर्पण (concave mirror) किरणों के साथ क्या करता है?",
     "What does a concave mirror do to parallel rays?",
     ["एक बिंदु पर अभिसृत (जमा) कर देता है", "बिखेर देता है", "अपवर्तित कर देता है", "सोख लेता है"],
     ["Converges them to a point", "Diverges them", "Refracts them", "Absorbs them"],
     0,
     "अवतल दर्पण अभिसारी दर्पण है।",
     "A concave mirror is a converging mirror."),

    ("reflection-and-mirrors", "easy",
     "उत्तल दर्पण (convex mirror) किरणों के साथ क्या करता है?",
     "What does a convex mirror do to parallel rays?",
     ["बिखेर देता है", "एक बिंदु पर जमा कर देता है", "सोख लेता है", "रंग बदल देता है"],
     ["Diverges them", "Converges them to a point", "Absorbs them", "Changes their colour"],
     0,
     "उत्तल दर्पण अपसारी दर्पण है।",
     "A convex mirror is a diverging mirror."),

    ("reflection-and-mirrors", "easy",
     "वाहनों के पीछे देखने वाला दर्पण (रियर-व्यू मिरर) कौन-सा होता है?",
     "Which mirror is used as a vehicle's rear-view mirror?",
     ["उत्तल दर्पण", "अवतल दर्पण", "समतल दर्पण", "अर्ध-गोलाकार दर्पण"],
     ["A convex mirror", "A concave mirror", "A plane mirror", "A hemispherical mirror"],
     0,
     "उत्तल दर्पण सदैव सीधा छोटा प्रतिबिंब बनाकर व्यापक क्षेत्र दिखाता है।",
     "A convex mirror always gives an erect, diminished image with a wider field."),

    ("reflection-and-mirrors", "easy",
     "दंत चिकित्सक दाँत का बड़ा प्रतिबिंब देखने के लिए कौन-सा दर्पण उपयोग करता है?",
     "Which mirror does a dentist use to see an enlarged image of a tooth?",
     ["अवतल दर्पण", "उत्तल दर्पण", "समतल दर्पण", "कोई दर्पण नहीं"],
     ["A concave mirror", "A convex mirror", "A plane mirror", "No mirror"],
     0,
     "अवतल दर्पण के फोकस के भीतर रखी वस्तु का बड़ा, सीधा प्रतिबिंब बनता है।",
     "An object within a concave mirror's focus gives an enlarged, erect image."),

    ("reflection-and-mirrors", "easy",
     "वास्तविक प्रतिबिंब की पहचान क्या है?",
     "What is the identifying feature of a real image?",
     ["उसे पर्दे पर प्राप्त किया जा सकता है", "वह कभी पर्दे पर नहीं बनता", "वह सदैव सीधा होता है", "वह केवल काँच में बनता है"],
     ["It can be obtained on a screen", "It can never form on a screen", "It is always erect", "It forms only in glass"],
     0,
     "वास्तविक प्रतिबिंब में प्रकाश वास्तव में मिलती है — पर्दे पर बनता है।",
     "In a real image light actually meets — it forms on a screen."),

    ("reflection-and-mirrors", "easy",
     "गोलीय दर्पण की फोकस दूरी और वक्रता त्रिज्या में क्या संबंध है?",
     "What is the relation between the focal length and the radius of curvature of a spherical mirror?",
     ["f = R/2", "f = R", "f = 2R", "f = R/4"],
     ["f = R/2", "f = R", "f = 2R", "f = R/4"],
     0,
     "गोलीय दर्पण के लिए f = R/2।",
     "For a spherical mirror f = R/2."),

    ("reflection-and-mirrors", "easy",
     "वक्रता त्रिज्या 20 सेमी के अवतल दर्पण की फोकस दूरी कितनी है?",
     "What is the focal length of a concave mirror of radius of curvature 20 cm?",
     ["10 सेमी", "20 सेमी", "40 सेमी", "5 सेमी"],
     ["10 cm", "20 cm", "40 cm", "5 cm"],
     0,
     "f = R/2 = 20/2 = 10 सेमी।",
     "f = R/2 = 20/2 = 10 cm."),

    ("reflection-and-mirrors", "easy",
     "पेरिस्कोप में कौन-से दर्पण लगे होते हैं?",
     "Which mirrors are used in a periscope?",
     ["दो समतल दर्पण 45 डिग्री पर", "दो उत्तल दर्पण", "दो अवतल दर्पण", "एक समतल और एक उत्तल"],
     ["Two plane mirrors at 45 degrees", "Two convex mirrors", "Two concave mirrors", "One plane and one convex"],
     0,
     "45 डिग्री के दो समतल दर्पण प्रकाश को दो बार परावर्तित कर नीचे ले आते हैं।",
     "Two plane mirrors at 45 degrees reflect light twice to send it downward."),

    ("reflection-and-mirrors", "easy",
     "अंधेरे कमरे में दर्पण अकेला क्यों नहीं चमकता?",
     "Why does a mirror alone not glow in a dark room?",
     ["दर्पण केवल परावर्तित प्रकाश दिखाता है; स्वयं प्रकाश नहीं बनाता", "दर्पण प्रकाश सोख लेता है", "दर्पण अपारदर्शी होता है", "दर्पण विद्युत चालक नहीं है"],
     ["A mirror shows only reflected light; it makes none of its own", "The mirror absorbs light", "The mirror is opaque", "The mirror is not an electrical conductor"],
     0,
     "परावर्तन प्रकाश की उपस्थिति में ही संभव है।",
     "Reflection is possible only when light is present."),

    ("reflection-and-mirrors", "easy",
     "समतल दर्पण का प्रतिबिंब वास्तविक क्यों नहीं होता?",
     "Why is a plane mirror's image not real?",
     ["प्रकाश किरणें दर्पण के पीछे वास्तव में नहीं मिलतीं — केवल ऐसा प्रतीत होता है", "प्रतिबिंब पर्दे पर बन जाता है", "प्रतिबिंब आकार में छोटा होता है", "प्रतिबिंब उल्टा होता है"],
     ["The rays never actually meet behind the mirror — they only appear to", "The image forms on a screen", "The image is smaller", "The image is inverted"],
     0,
     "पीछे वाली किरणें काल्पनिक हैं — इसलिए प्रतिबिंब आभासी है।",
     "The backward extensions of rays are imaginary — hence the image is virtual."),

    # ---- medium (21) ----
    ("reflection-and-mirrors", "medium",
     "आपतन कोण 35 डिग्री है। परावर्तन कोण कितना होगा?",
     "The angle of incidence is 35 degrees. What is the angle of reflection?",
     ["35 डिग्री", "55 डिग्री", "70 डिग्री", "0 डिग्री"],
     ["35 degrees", "55 degrees", "70 degrees", "0 degrees"],
     0,
     "∠i = ∠r = 35 डिग्री।",
     "∠i = ∠r = 35 degrees."),

    ("reflection-and-mirrors", "medium",
     "किरण अभिलंब के अनुदिश दर्पण पर गिरती है। आपतन कोण कितना होगा?",
     "A ray falls on a mirror along the normal. What is the angle of incidence?",
     ["0 डिग्री — किरण उसी पथ पर वापस लौटती है", "90 डिग्री", "45 डिग्री", "180 डिग्री"],
     ["0 degrees — the ray retraces its path", "90 degrees", "45 degrees", "180 degrees"],
     0,
     "अभिलंब के अनुदिश किरण के लिए ∠i = 0, अतः ∠r = 0 — किरण वापस उसी रास्ते पर।",
     "Along the normal ∠i = 0, so ∠r = 0 — the ray bounces straight back."),

    ("reflection-and-mirrors", "medium",
     "आपतित किरण और परावर्तित किरण के बीच का कोण 80 डिग्री है। आपतन कोण कितना है?",
     "The angle between the incident ray and the reflected ray is 80 degrees. What is the angle of incidence?",
     ["40 डिग्री", "80 डिग्री", "20 डिग्री", "50 डिग्री"],
     ["40 degrees", "80 degrees", "20 degrees", "50 degrees"],
     0,
     "कोण = ∠i + ∠r = 2∠i = 80, अतः ∠i = 40 डिग्री।",
     "The angle equals ∠i + ∠r = 2∠i = 80, so ∠i = 40 degrees."),

    ("reflection-and-mirrors", "medium",
     "किरण दर्पण की सतह से 55 डिग्री का कोण बनाती है। आपतन कोण कितना है?",
     "A ray makes an angle of 55 degrees with the mirror surface. What is the angle of incidence?",
     ["35 डिग्री", "55 डिग्री", "45 डिग्री", "25 डिग्री"],
     ["35 degrees", "55 degrees", "45 degrees", "25 degrees"],
     0,
     "सतह से कोण 55 डिग्री ⇒ अभिलंब से कोण = 90 − 55 = 35 डिग्री।",
     "55 degrees from the surface means 90 − 55 = 35 degrees from the normal."),

    ("reflection-and-mirrors", "medium",
     "परावर्तन के नियम में आपतित किरण, परावर्तित किरण और अभिलंब कहाँ होते हैं?",
     "According to the laws of reflection, where do the incident ray, the reflected ray and the normal lie?",
     ["एक ही तल में", "तीन अलग तलों में", "केवल दो एक तल में", "कोई नियम नहीं"],
     ["In the same plane", "In three different planes", "Only two in one plane", "There is no such rule"],
     0,
     "द्वितीय नियम — तीनों एक ही तल में होते हैं।",
     "Second law — all three lie in the same plane."),

    ("reflection-and-mirrors", "medium",
     "कथन: खुरदरी सतह पर आपतन कोण परावर्तन कोण के बराबर नहीं होता। यह कथन सही है या गलत?",
     "Statement: On a rough surface the angle of incidence is not equal to the angle of reflection. Is this statement true or false?",
     ["गलत — हर परावर्तन में, खुरदरी सतह के अति सूक्ष्म तलों पर भी, दोनों कोण बराबर रहते हैं", "सही", "आंशिक रूप से सही", "प्रश्न अर्थहीन है"],
     ["False — at every reflection, even on the tiny facets of a rough surface, the two angles are equal", "True", "Partly true", "The question is meaningless"],
     0,
     "नियम सभी सतहों पर लागू है; खुरदरापन केवल दिशाएँ बिखेरता है।",
     "The law holds on all surfaces; roughness merely spreads the directions."),

    ("reflection-and-mirrors", "medium",
     "व्यक्ति समतल दर्पण से 5 मीटर दूर खड़ा है। व्यक्ति और उसके प्रतिबिंब के बीच की दूरी कितनी है?",
     "A person stands 5 m from a plane mirror. What is the distance between the person and the image?",
     ["10 मीटर", "5 मीटर", "2.5 मीटर", "20 मीटर"],
     ["10 m", "5 m", "2.5 m", "20 m"],
     0,
     "वस्तु 5 मीटर आगे + प्रतिबिंब 5 मीटर पीछे = 10 मीटर।",
     "Object 5 m in front + image 5 m behind = 10 m."),

    ("reflection-and-mirrors", "medium",
     "दर्पण से 5 मीटर दूर खड़ा व्यक्ति 2 मीटर दर्पण की ओर चलता है। अब व्यक्ति और प्रतिबिंब के बीच दूरी कितनी है?",
     "A person 5 m from a mirror walks 2 m towards it. What is the new person-image distance?",
     ["6 मीटर", "10 मीटर", "8 मीटर", "3 मीटर"],
     ["6 m", "10 m", "8 m", "3 m"],
     0,
     "नई वस्तु-दूरी 3 मीटर ⇒ प्रतिबिंब 3 मीटर पीछे ⇒ कुल 6 मीटर।",
     "New object distance 3 m ⇒ image 3 m behind ⇒ total 6 m."),

    ("reflection-and-mirrors", "medium",
     "दो समतल दर्पण 90 डिग्री के कोण पर झुकाए गए हैं। बनने वाले प्रतिबिंबों की संख्या कितनी होगी?",
     "Two plane mirrors are inclined at 90 degrees. How many images are formed?",
     ["3", "4", "2", "5"],
     ["3", "4", "2", "5"],
     0,
     "n = 360/θ − 1 = 360/90 − 1 = 3।",
     "n = 360/θ − 1 = 360/90 − 1 = 3."),

    ("reflection-and-mirrors", "medium",
     "किसी वस्तु के 5 प्रतिबिंब देखने के लिए दो दर्पण किस कोण पर रखे जाएँ?",
     "At what angle should two mirrors be placed to obtain 5 images of an object?",
     ["60 डिग्री", "90 डिग्री", "45 डिग्री", "120 डिग्री"],
     ["60 degrees", "90 degrees", "45 degrees", "120 degrees"],
     0,
     "360/60 − 1 = 6 − 1 = 5।",
     "360/60 − 1 = 6 − 1 = 5."),

    ("reflection-and-mirrors", "medium",
     "दो दर्पण 120 डिग्री पर झुके हैं। प्रतिबिंबों की संख्या कितनी बनेगी?",
     "Two mirrors are inclined at 120 degrees. How many images form?",
     ["2", "3", "4", "1"],
     ["2", "3", "4", "1"],
     0,
     "n = 360/120 − 1 = 3 − 1 = 2।",
     "n = 360/120 − 1 = 3 − 1 = 2."),

    ("reflection-and-mirrors", "medium",
     "कैलीडोस्कोप (बहुरूपदर्शक) किस सिद्धांत पर कार्य करता है?",
     "On what principle does a kaleidoscope work?",
     ["समतल दर्पणों में बार-बार परावर्तन से बहुत प्रतिबिंब बनते हैं", "प्रकाश का अपवर्तन", "प्रकाश का विक्षेपण", "प्रकाश का अवशोषण"],
     ["Repeated reflections in plane mirrors create many images", "Refraction of light", "Dispersion of light", "Absorption of light"],
     0,
     "कई झुके दर्पण बार-बार परावर्तन से सुंदर पैटर्न बनाते हैं।",
     "Several inclined mirrors form beautiful patterns via repeated reflection."),

    ("reflection-and-mirrors", "medium",
     "अवतल दर्पण का उपयोग वाहन के हेडलाइट में क्यों किया जाता है?",
     "Why is a concave mirror used in vehicle headlights?",
     ["बल्ब को फोकस पर रखने से समांतर किरण-पुंज मिलता है जो दूर तक जाता है", "वह सदैव छोटा प्रतिबिंब बनाता है", "वह प्रकाश सोखता है", "वह प्रकाश को पीछे भेजता है"],
     ["With the bulb at the focus, a parallel beam is obtained that reaches far", "It always forms a diminished image", "It absorbs light", "It sends light backwards"],
     0,
     "फोकस पर स्रोत का प्रतिबिंब अनंत पर — किरणें समांतर हो जाती हैं।",
     "A source at the focus images at infinity — the rays emerge parallel."),

    ("reflection-and-mirrors", "medium",
     "अवतल दर्पण के फोकस और केंद्र (C) के बीच रखी वस्तु का प्रतिबिंब कहाँ बनता है?",
     "Where is the image formed for an object placed between the focus (F) and centre of curvature (C) of a concave mirror?",
     ["C के बाहर — वास्तविक, उल्टा, बड़ा", "F और C के बीच", "दर्पण के पीछे — आभासी", "ध्रुव पर"],
     ["Beyond C — real, inverted, enlarged", "Between F and C", "Behind the mirror — virtual", "At the pole"],
     0,
     "F और C के बीच की वस्तु का प्रतिबिंब C से दूर बड़ा और उल्टा बनता है।",
     "An object between F and C gives an enlarged, inverted, real image beyond C."),

    ("reflection-and-mirrors", "medium",
     "अवतल दर्पण के केंद्र C पर रखी वस्तु का प्रतिबिंब कहाँ और कैसा बनता है?",
     "What is the image of an object placed at the centre of curvature C of a concave mirror?",
     ["C पर ही — वास्तविक, उल्टा, समान आकार", "F पर — बिंदु रूप में", "पीछे — आभासी, बड़ा", "अनंत पर"],
     ["At C itself — real, inverted, same size", "At F — a point image", "Behind — virtual, enlarged", "At infinity"],
     0,
     "C पर वस्तु का प्रतिबिंब C पर ही समान आकार का उल्टा बनता है।",
     "An object at C images at C, same size but inverted."),

    ("reflection-and-mirrors", "medium",
     "अवतल दर्पण के फोकस F पर रखी वस्तु का प्रतिबिंब कहाँ बनता है?",
     "Where is the image formed when an object is at the focus F of a concave mirror?",
     ["अनंत पर — बहुत बड़ा वास्तविक", "C पर", "P और F के बीच", "दर्पण के पीछे"],
     ["At infinity — highly enlarged and real", "At C", "Between P and F", "Behind the mirror"],
     0,
     "फोकस की किरणें परावर्तन के बाद समांतर हो जाती हैं — प्रतिबिंब अनंत पर।",
     "Rays from the focus emerge parallel after reflection — the image is at infinity."),

    ("reflection-and-mirrors", "medium",
     "उत्तल दर्पण में किसी भी स्थिति की वस्तु का प्रतिबिंब कैसा बनता है?",
     "What is the image of an object at any position in a convex mirror?",
     ["आभासी, सीधा, छोटा — ध्रुव व फोकस के बीच", "वास्तविक, उल्टा", "बड़ा, वास्तविक", "अनंत पर बिंदु"],
     ["Virtual, erect, diminished — between pole and focus", "Real, inverted", "Enlarged, real", "A point at infinity"],
     0,
     "उत्तल दर्पण सदैव छोटा सीधा आभासी प्रतिबिंब बनाता है।",
     "A convex mirror always forms a diminished, erect, virtual image."),

    ("reflection-and-mirrors", "medium",
     "दाढ़ी बनाने का दर्पण (शेविंग मिरर) कौन-सा होता है और क्यों?",
     "Which mirror is used as a shaving mirror and why?",
     ["अवतल — चेहरा फोकस के भीतर रखने पर बड़ा सीधा प्रतिबिंब मिलता है", "उत्तल — व्यापक क्षेत्र दिखता है", "समतल — समान आकार", "कोई भी दर्पण"],
     ["Concave — with the face within the focus, an enlarged erect image is obtained", "Convex — a wider field is seen", "Plane — same size", "Any mirror"],
     0,
     "फोकस के भीतर वस्तु का बड़ा, सीधा, आभासी प्रतिबिंब बनता है।",
     "An object within the focus gives an enlarged, erect, virtual image."),

    ("reflection-and-mirrors", "medium",
     "सौर भट्टी (सोलर फर्नेस) में बड़ा अवतल दर्पण क्यों लगाया जाता है?",
     "Why is a large concave mirror used in a solar furnace?",
     ["सूर्य की समांतर किरणों को फोकस पर केंद्रित कर उच्च ताप पाने के लिए", "प्रकाश बिखेरने के लिए", "प्रकाश सोखने के लिए", "प्रकाश का रंग बदलने के लिए"],
     ["To focus the sun's parallel rays at the focus and obtain high temperature", "To scatter light", "To absorb light", "To change the colour of light"],
     0,
     "सूर्य लगभग अनंत दूरी पर है — किरणें फोकस पर जमा होकर भट्टी गर्म करती हैं।",
     "The sun is effectively at infinity — rays converge at the focus, heating the furnace."),

    ("reflection-and-mirrors", "medium",
     "आवर्धन (magnification) m = −v/u हो तब m ऋणात्मक होने का क्या अर्थ है?",
     "When magnification m = −v/u is negative, what does it mean?",
     ["प्रतिबिंब वास्तविक और उल्टा है", "प्रतिबिंब आभासी और सीधा है", "प्रतिबिंब बड़ा है", "प्रतिबिंब अस्तित्व में नहीं"],
     ["The image is real and inverted", "The image is virtual and erect", "The image is enlarged", "The image does not exist"],
     0,
     "m ऋणात्मक ⇒ उल्टा प्रतिबिंब ⇒ वास्तविक; m धनात्मक ⇒ सीधा ⇒ आभासी।",
     "Negative m ⇒ inverted image ⇒ real; positive m ⇒ erect ⇒ virtual."),

    ("reflection-and-mirrors", "medium",
     "समतल दर्पण के लिए आवर्धन का मान कितना होता है?",
     "What is the magnification produced by a plane mirror?",
     ["+1 (सीधा, समान आकार)", "−1", "0", "अनंत"],
     ["+1 (erect, same size)", "−1", "0", "Infinity"],
     0,
     "m = +1 — प्रतिबिंब सीधा और वस्तु के समान आकार का।",
     "m = +1 — the image is erect and the same size as the object."),

    # ---- hard (9) ----
    ("reflection-and-mirrors", "hard",
     "अवतल दर्पण की फोकस दूरी 10 सेमी है। 15 सेमी दूरी पर वस्तु रखी है। प्रतिबिंब की दूरी कितनी होगी?",
     "A concave mirror has focal length 10 cm. An object is placed 15 cm away. What is the image distance?",
     ["दर्पण से 30 सेमी (वास्तविक, उल्टा, दुगुना)", "15 सेमी", "10 सेमी", "6 सेमी"],
     ["30 cm from the mirror (real, inverted, double size)", "15 cm", "10 cm", "6 cm"],
     0,
     "1/v = 1/f − 1/u = −1/10 + 1/15 = −1/30 ⇒ v = −30 सेमी; m = −v/u = −2।",
     "1/v = 1/f − 1/u = −1/10 + 1/15 = −1/30 ⇒ v = −30 cm; m = −v/u = −2."),

    ("reflection-and-mirrors", "hard",
     "f = 10 सेमी के अवतल दर्पण से 30 सेमी दूर वस्तु रखी है। प्रतिबिंब कहाँ बनेगा?",
     "An object is 30 cm from a concave mirror with f = 10 cm. Where is the image formed?",
     ["दर्पण से 15 सेमी — वास्तविक, उल्टा, आधे आकार का", "30 सेमी", "10 सेमी", "पीछे 30 सेमी"],
     ["15 cm from the mirror — real, inverted, half size", "30 cm", "10 cm", "30 cm behind"],
     0,
     "1/v = −1/10 + 1/30 = −1/15 ⇒ v = −15 सेमी; m = −(−15)/(−30) = −0.5।",
     "1/v = −1/10 + 1/30 = −1/15 ⇒ v = −15 cm; m = −(−15)/(−30) = −0.5."),

    ("reflection-and-mirrors", "hard",
     "उत्तल दर्पण की फोकस दूरी 20 सेमी है, वस्तु 30 सेमी दूर है। प्रतिबिंब कहाँ बनेगा?",
     "A convex mirror has focal length 20 cm and an object is 30 cm away. Where is the image formed?",
     ["दर्पण से 12 सेमी पीछे — आभासी, सीधा, छोटा", "30 सेमी आगे", "20 सेमी पीछे", "अनंत पर"],
     ["12 cm behind the mirror — virtual, erect, diminished", "30 cm in front", "20 cm behind", "At infinity"],
     0,
     "1/v = 1/20 + 1/30 = 5/60 ⇒ v = +12 सेमी; m = −v/u = +0.4।",
     "1/v = 1/20 + 1/30 = 5/60 ⇒ v = +12 cm; m = −v/u = +0.4."),

    ("reflection-and-mirrors", "hard",
     "f = 10 सेमी के अवतल दर्पण से वस्तु 5 सेमी दूरी पर (फोकस के भीतर) है। प्रतिबिंब कैसा होगा?",
     "An object is 5 cm from a concave mirror with f = 10 cm (inside the focus). What is the image like?",
     ["दर्पण के पीछे 10 सेमी — आभासी, सीधा, दुगुना", "30 सेमी आगे — वास्तविक", "5 सेमी पीछे — समान आकार", "कोई प्रतिबिंब नहीं"],
     ["10 cm behind the mirror — virtual, erect, double size", "30 cm in front — real", "5 cm behind — same size", "No image"],
     0,
     "1/v = −1/10 + 1/5 = +1/10 ⇒ v = +10 सेमी; m = −10/(−5) = +2।",
     "1/v = −1/10 + 1/5 = +1/10 ⇒ v = +10 cm; m = −10/(−5) = +2."),

    ("reflection-and-mirrors", "hard",
     "किस स्थिति में अवतल दर्पण आवर्धन +3 देगा?",
     "In which situation does a concave mirror give magnification +3?",
     ["जब वस्तु ध्रुव P और फोकस F के बीच हो", "जब वस्तु C पर हो", "जब वस्तु अनंत पर हो", "जब वस्तु F पर हो"],
     ["When the object lies between the pole P and the focus F", "When the object is at C", "When the object is at infinity", "When the object is at F"],
     0,
     "P और F के बीच वस्तु का बड़ा, सीधा, आभासी प्रतिबिंब बनता है — m धनात्मक।",
     "Between P and F the image is enlarged, erect, virtual — positive m."),

    ("reflection-and-mirrors", "hard",
     "दो दर्पण 30 डिग्री के कोण पर झुके हैं। वस्तु के कितने प्रतिबिंब बनेंगे?",
     "Two mirrors are inclined at 30 degrees. How many images of an object are formed?",
     ["11", "12", "10", "9"],
     ["11", "12", "10", "9"],
     0,
     "n = 360/30 − 1 = 12 − 1 = 11।",
     "n = 360/30 − 1 = 12 − 1 = 11."),

    ("reflection-and-mirrors", "hard",
     "समतल दर्पण को 10 डिग्री घुमाया जाता है (आपतित किरण स्थिर)। परावर्तित किरण कितने अंश से घूमेगी?",
     "A plane mirror is rotated by 10 degrees (incident ray fixed). By how much does the reflected ray rotate?",
     ["20 डिग्री", "10 डिग्री", "5 डिग्री", "40 डिग्री"],
     ["20 degrees", "10 degrees", "5 degrees", "40 degrees"],
     0,
     "दर्पण घूमने पर अभिलंब भी उतना ही घूमता है; ∠i और ∠r दोनों 10-10 डिग्री बढ़ते हैं ⇒ कुल परिवर्तन 2 × 10 = 20 डिग्री।",
     "The normal rotates with the mirror; both ∠i and ∠r grow by 10 degrees ⇒ total shift 2 × 10 = 20 degrees."),

    ("reflection-and-mirrors", "hard",
     "व्यक्ति 1 मीटर/सेकंड की चाल से समतल दर्पण की ओर चलता है। प्रतिबिंब व्यक्ति के प्रति किस चाल से निकट आता प्रतीत होता है?",
     "A person walks towards a plane mirror at 1 m/s. At what speed does the image appear to approach the person?",
     ["2 मीटर/सेकंड", "1 मीटर/सेकंड", "0.5 मीटर/सेकंड", "4 मीटर/सेकंड"],
     ["2 m/s", "1 m/s", "0.5 m/s", "4 m/s"],
     0,
     "वस्तु-दूरी जितनी घटती है, प्रतिबिंब-दूरी उतनी ही — बीच की दूरी दुगुनी गति से घटती है।",
     "As object distance shrinks, image distance shrinks equally — the gap closes at twice the speed."),

    ("reflection-and-mirrors", "hard",
     "गोलीय दर्पण की फोकस दूरी 15 सेमी है। वक्रता त्रिज्या और दर्पण का प्रकार बताइए यदि प्रतिबिंब सदैव आभासी व सीधा बनता है।",
     "A spherical mirror has focal length 15 cm. State the radius of curvature and the mirror type if its image is always virtual and erect.",
     ["R = 30 सेमी, उत्तल दर्पण", "R = 30 सेमी, अवतल दर्पण", "R = 15 सेमी, उत्तल दर्पण", "R = 7.5 सेमी, समतल दर्पण"],
     ["R = 30 cm, convex mirror", "R = 30 cm, concave mirror", "R = 15 cm, convex mirror", "R = 7.5 cm, plane mirror"],
     0,
     "सदैव आभासी-सीधा प्रतिबिंभ उत्तल दर्पण का लक्षण है; R = 2f = 30 सेमी।",
     "An always virtual-erect image marks a convex mirror; R = 2f = 30 cm."),
]
