# -*- coding: utf-8 -*-
"""P08 (Light, Reflection & Refraction) — Part 2: refraction-and-lenses (50) + dispersion-and-human-eye (50) = 100 tuples.
All items authored with correct_idx=0; rotation happens in gen_p08_questions.py.

T3 refraction-and-lenses   50 = E20/M21/H9
T4 dispersion-and-human-eye 50 = E20/M22/H8
"""

PART2 = [
    # ================= REFRACTION & LENSES (50) =================
    # ---- easy (20) ----
    ("refraction-and-lenses", "easy",
     "प्रकाश का अपवर्तन किसे कहते हैं?",
     "What is refraction of light?",
     ["एक माध्यम से दूसरे माध्यम में जाते समय प्रकाश की दिशा में परिवर्तन", "किसी सतह से प्रकाश का वापस लौटना", "प्रकाश का सात रंगों में बँटना", "प्रकाश का सोख लिया जाना"],
     ["The change in direction of light when it passes from one medium to another", "Light bouncing back from a surface", "Light splitting into seven colours", "Light being absorbed"],
     0,
     "माध्यम बदलने पर चाल बदलने से किरण मुड़ जाती है — यही अपवर्तन है।",
     "Changing speed on changing medium bends the ray — that is refraction."),

    ("refraction-and-lenses", "easy",
     "अपवर्तन का मूल कारण क्या है?",
     "What is the basic cause of refraction?",
     ["विभिन्न माध्यमों में प्रकाश की चाल का भिन्न होना", "प्रकाश का रंग", "माध्यम का ताप", "प्रकाश का भार"],
     ["Light travels at different speeds in different media", "The colour of light", "The temperature of the medium", "The weight of light"],
     0,
     "चाल बदलते ही किरण की दिशा दोनों माध्यमों की सीमा पर बदल जाती है।",
     "As soon as the speed changes, the ray bends at the boundary of the two media."),

    ("refraction-and-lenses", "easy",
     "किसी माध्यम का अपवर्तनांक कैसे परिभाषित होता है?",
     "How is the refractive index of a medium defined?",
     ["निर्वात में प्रकाश की चाल और उस माध्यम में चाल का अनुपात", "माध्यम का भार और आयतन का अनुपात", "प्रकाश की तीव्रता का माप", "माध्यम का घनत्व"],
     ["The ratio of the speed of light in vacuum to that in the medium", "The ratio of the medium's weight to volume", "A measure of light intensity", "The density of the medium"],
     0,
     "n = c/v — अपवर्तनांक अनुपात है, इसका कोई मात्रक नहीं।",
     "n = c/v — refractive index is a ratio and has no unit."),

    ("refraction-and-lenses", "easy",
     "जल का अपवर्तनांक लगभग कितना होता है?",
     "What is the approximate refractive index of water?",
     ["1.33", "1.0", "1.5", "2.42"],
     ["1.33", "1.0", "1.5", "2.42"],
     0,
     "जल का n = 1.33; काँच का 1.5; हीरे का 2.42।",
     "Water has n = 1.33; glass 1.5; diamond 2.42."),

    ("refraction-and-lenses", "easy",
     "काँच का अपवर्तनांक लगभग कितना होता है?",
     "What is the approximate refractive index of glass?",
     ["1.5", "1.33", "1.0", "4/3"],
     ["1.5", "1.33", "1.0", "4/3"],
     0,
     "साधारण काँच का अपवर्तनांक लगभग 1.5 है।",
     "Ordinary glass has a refractive index of about 1.5."),

    ("refraction-and-lenses", "easy",
     "उत्तल लेंस किरणों के साथ क्या करती है?",
     "What does a convex lens do to rays of light?",
     ["उन्हें एक बिंदु पर अभिसृत करती है", "उन्हें बिखेर देती है", "उन्हें सोख लेती है", "उनका रंग बदल देती है"],
     ["It converges them to a point", "It diverges them", "It absorbs them", "It changes their colour"],
     0,
     "उत्तल लेंस अभिसारी लेंस है।",
     "A convex lens is a converging lens."),

    ("refraction-and-lenses", "easy",
     "अवतल लेंस किरणों के साथ क्या करती है?",
     "What does a concave lens do to rays of light?",
     ["उन्हें बिखेर देती है", "उन्हें एक बिंदु पर जमा करती है", "उन्हें परावर्तित करती है", "उन्हें रोक देती है"],
     ["It diverges them", "It converges them to a point", "It reflects them", "It stops them"],
     0,
     "अवतल लेंस अपसारी लेंस है।",
     "A concave lens is a diverging lens."),

    ("refraction-and-lenses", "easy",
     "आवर्धक लेंस (magnifying glass) कौन-सी लेंस होती है?",
     "What type of lens is a magnifying glass?",
     ["उत्तल लेंस", "अवतल लेंस", "बाइकॉन्केव", "समतल काँच की शीट"],
     ["A convex lens", "A concave lens", "A biconcave lens", "A flat glass sheet"],
     0,
     "उत्तल लेंस पास रखी वस्तु का बड़ा आभासी प्रतिबिंब बनाती है।",
     "A convex lens forms an enlarged virtual image of a nearby object."),

    ("refraction-and-lenses", "easy",
     "अवतल लेंस किसी भी स्थिति की वस्तु का प्रतिबिंब कैसा बनाती है?",
     "What type of image does a concave lens form for an object at any position?",
     ["आभासी, सीधा, छोटा", "वास्तविक, उल्टा, बड़ा", "वास्तविक, सीधा", "अनंत पर बिंदु-रूप"],
     ["Virtual, erect, diminished", "Real, inverted, enlarged", "Real, erect", "A point at infinity"],
     0,
     "अवतल लेंस सदैव छोटा, सीधा, आभासी प्रतिबिंब बनाती है।",
     "A concave lens always forms a diminished, erect, virtual image."),

    ("refraction-and-lenses", "easy",
     "लेंस का वह बिंदु जिससे होकर प्रकाश किरण बिना विचलित हुए निकल जाती है, क्या कहलाता है?",
     "What is the point of a lens through which a light ray passes undeviated?",
     ["प्रकाशिक केंद्र", "फोकस", "वक्रता केंद्र", "ध्रुव"],
     ["The optical centre", "The focus", "The centre of curvature", "The pole"],
     0,
     "प्रकाशिक केंद्र से गुज़री किरण सीधी रहती है।",
     "A ray through the optical centre passes straight."),

    ("refraction-and-lenses", "easy",
     "लेंस की क्षमता (power) का मात्रक क्या है?",
     "What is the unit of the power of a lens?",
     ["डाइऑप्टर", "वाट", "मीटर", "जूल"],
     ["Dioptre", "Watt", "Metre", "Joule"],
     0,
     "1 डाइऑप्टर = 1 मीटर−1 अर्थात् f = 1 मीटर की लेंस की क्षमता।",
     "1 dioptre = 1 per metre, i.e. the power of a lens with f = 1 m."),

    ("refraction-and-lenses", "easy",
     "लेंस की क्षमता का सूत्र क्या है?",
     "What is the formula for the power of a lens?",
     ["P = 1/f (मीटर में)", "P = f", "P = 2f", "P = 1/2f"],
     ["P = 1/f (with f in metres)", "P = f", "P = 2f", "P = 1/2f"],
     0,
     "P = 1/f; f मीटर में रखने पर P डाइऑप्टर में मिलती है।",
     "P = 1/f; with f in metres, P comes in dioptres."),

    ("refraction-and-lenses", "easy",
     "संघन (अधिक सघन) माध्यम में प्रवेश करते समय प्रकाश किरण अभिलंब के सापेक्ष कैसे झुकती है?",
     "When light enters an optically denser medium, how does the ray bend relative to the normal?",
     ["अभिलंब की ओर झुकती है", "अभिलंब से दूर झुकती है", "बिल्कुल नहीं झुकती", "परावर्तित हो जाती है"],
     ["It bends towards the normal", "It bends away from the normal", "It does not bend at all", "It gets reflected"],
     0,
     "सघन माध्यम में चाल घटती है — किरण अभिलंब की ओर मुड़ती है।",
     "Speed drops in a denser medium — the ray turns towards the normal."),

    ("refraction-and-lenses", "easy",
     "वायु से जल में जाती प्रकाश किरण के लिए सही कथन चुनिए।",
     "Choose the correct statement for a light ray going from air into water.",
     ["किरण अभिलंब की ओर झुकती है क्योंकि जल सघन है", "किरण अभिलंब से दूर जाती है", "किरण बिना विचलन गुज़रती है", "किरण पूर्ण परावर्तित होती है"],
     ["The ray bends towards the normal because water is denser", "The ray bends away from the normal", "The ray passes undeviated", "The ray is totally reflected"],
     0,
     "वायु से जल: विरल से सघन — अभिलंब की ओर।",
     "Air to water: rarer to denser — towards the normal."),

    ("refraction-and-lenses", "easy",
     "तालाब का तल जल में उथला क्यों प्रतीत होता है?",
     "Why does the bottom of a pond appear raised (shallower)?",
     ["जल में अपवर्तन से तल से आने वाली किरणें मुड़ती हैं और तल ऊपर दिखता है", "तालाब का तल वास्तव में ऊपर आ जाता है", "पानी का रंग हल्का होता है", "परावर्तन से तल छुप जाता है"],
     ["Refraction in water bends the rays from the bottom, so it looks raised", "The bottom actually rises", "Water is light in colour", "Reflection hides the bottom"],
     0,
     "अपवर्तन के कारण आभासी गहराई वास्तविक गहराई से कम होती है।",
     "Due to refraction, apparent depth is less than real depth."),

    ("refraction-and-lenses", "easy",
     "लेंस सूत्र (lens formula) क्या है?",
     "What is the lens formula?",
     ["1/v − 1/u = 1/f", "1/v + 1/u = 1/f", "v − u = f", "1/f = 2/v"],
     ["1/v − 1/u = 1/f", "1/v + 1/u = 1/f", "v − u = f", "1/f = 2/v"],
     0,
     "लेंस के लिए 1/v − 1/u = 1/f चिन्ह-परिपाटी के साथ।",
     "For lenses, 1/v − 1/u = 1/f with sign conventions."),

    ("refraction-and-lenses", "easy",
     "उत्तल लेंस की फोकस दूरी का चिह्न (साइन) क्या माना जाता है?",
     "What is the sign of the focal length of a convex lens by convention?",
     ["धनात्मक", "ऋणात्मक", "शून्य", "अनंत"],
     ["Positive", "Negative", "Zero", "Infinite"],
     0,
     "उत्तल लेंस f धनात्मक; अवतल लेंस f ऋणात्मक।",
     "A convex lens has positive f; a concave lens negative f."),

    ("refraction-and-lenses", "easy",
     "दुरबीन, कैमरा और प्रोजेक्टर में प्रमुख रूप से कौन-सी लेंस होती है?",
     "Which lens is the main element in telescopes, cameras and projectors?",
     ["उत्तल लेंस", "अवतल लेंस", "प्रिज़्म", "समतल दर्पण"],
     ["A convex lens", "A concave lens", "A prism", "A plane mirror"],
     0,
     "वास्तविक प्रतिबिंब बनाने के लिए सभी में उत्तल लेंस प्रयुक्त होती है।",
     "All use a convex lens to form real images."),

    ("refraction-and-lenses", "easy",
     "काँच के छड़ (slab) से गुज़रती किरण दूसरी सतह से कैसे निकलती है?",
     "How does a ray emerge after passing through a glass slab?",
     ["आपतित किरण के समांतर (कुछ पार्श्व विचलन के साथ)", "आपतित किरण के लंबवत", "किरण अंदर ही रह जाती है", "किरण सोख ली जाती है"],
     ["Parallel to the incident ray (with some lateral shift)", "Perpendicular to the incident ray", "The ray stays inside", "The ray is absorbed"],
     0,
     "समांतर पार्श्व सतहों पर दो बराबर-विपरीत अपवर्तन — निर्गत किरण समांतर।",
     "Two equal and opposite refractions at parallel faces — the emergent ray is parallel."),

    ("refraction-and-lenses", "easy",
     "सबसे अधिक अपवर्तनांक वाला सामान्य पदार्थ कौन-सा है?",
     "Which common substance has the highest refractive index?",
     ["हीरा (2.42)", "जल (1.33)", "काँच (1.5)", "वायु (1.0003)"],
     ["Diamond (2.42)", "Water (1.33)", "Glass (1.5)", "Air (1.0003)"],
     0,
     "हीरे का अपवर्तनांक 2.42 — प्रकाश उसमें सबसे धीमी चलती है।",
     "Diamond's n = 2.42 — light is slowest there."),

    # ---- medium (21) ----
    ("refraction-and-lenses", "medium",
     "कटोरे में रखा सिक्का पानी भरने पर उठा हुआ दिखता है। कारण बताइए।",
     "A coin in a bowl appears raised when water is poured. State the reason.",
     ["पानी से आने वाली किरणें जल-वायु सीमा पर अपवर्तित होकर आँख तक पहुँचती हैं, सिक्का ऊपर प्रतीत होता है", "सिक्का तैर जाता है", "पानी सिक्के को बड़ा कर देता है", "सिक्का परावर्तित हो जाता है"],
     ["Rays from the coin refract at the water-air boundary, making it appear raised", "The coin floats up", "Water enlarges the coin", "The coin gets reflected"],
     0,
     "अपवर्तन के कारण आभासी प्रतिबिंब वास्तविक सिक्के से ऊपर बनता है।",
     "Refraction forms the coin's virtual image above its real position."),

    ("refraction-and-lenses", "medium",
     "किसी माध्यम में प्रकाश की चाल 2 × 10^8 मीटर/सेकंड है। उसका अपवर्तनांक कितना होगा?",
     "The speed of light in a medium is 2 × 10^8 m/s. What is its refractive index?",
     ["1.5", "1.33", "2.0", "0.67"],
     ["1.5", "1.33", "2.0", "0.67"],
     0,
     "n = c/v = (3 × 10^8) / (2 × 10^8) = 1.5।",
     "n = c/v = (3 × 10^8) / (2 × 10^8) = 1.5."),

    ("refraction-and-lenses", "medium",
     "जल का अपवर्तनांक 4/3 है। जल में प्रकाश की चाल लगभग कितनी होगी?",
     "Water has refractive index 4/3. What is the approximate speed of light in water?",
     ["2.25 × 10^8 मीटर/सेकंड", "3 × 10^8 मीटर/सेकंड", "4 × 10^8 मीटर/सेकंड", "1.5 × 10^8 मीटर/सेकंड"],
     ["2.25 × 10^8 m/s", "3 × 10^8 m/s", "4 × 10^8 m/s", "1.5 × 10^8 m/s"],
     0,
     "v = c/n = 3 × 10^8 ÷ (4/3) = 2.25 × 10^8 मीटर/सेकंड।",
     "v = c/n = 3 × 10^8 ÷ (4/3) = 2.25 × 10^8 m/s."),

    ("refraction-and-lenses", "medium",
     "दो माध्यमों में से जिसका अपवर्तनांक अधिक है, वह कैसा माना जाता है?",
     "Of two media, the one with the higher refractive index is regarded as?",
     ["प्रकाशिक रूप से सघन", "प्रकाशिक रूप से विरल", "पूर्ण पारदर्शी", "परावर्तक"],
     ["Optically denser", "Optically rarer", "Perfectly transparent", "Reflecting"],
     0,
     "अधिक n ⇒ प्रकाशिक सघनता अधिक — यह भौतिक घनत्व से भिन्न बात है।",
     "Higher n means higher optical density — different from mass density."),

    ("refraction-and-lenses", "medium",
     "जल से काँच में जाती किरण कैसे विचलित होती है?",
     "How does a ray bend when going from water into glass?",
     ["जल (n = 1.33) से काँच (n = 1.5) सघनतर है — किरण अभिलंब की ओर झुकती है", "किरण अभिलंब से दूर जाती है क्योंकि काँच विरल है", "किरण बिना विचलन गुज़रती है", "किरण पूर्णतः सोख ली जाती है"],
     ["Water (n = 1.33) to glass (n = 1.5) is denser — the ray bends towards the normal", "The ray bends away because glass is rarer", "The ray passes undeviated", "The ray is fully absorbed"],
     0,
     "1.33 से 1.5 में जाना विरल से सघन में जाना है — अभिलंब की ओर विचलन।",
     "Going from 1.33 to 1.5 is rarer-to-denser — bending towards the normal."),

    ("refraction-and-lenses", "medium",
     "काँच से वायु में आती किरण कैसे विचलित होती है?",
     "How does a ray bend when it goes from glass into air?",
     ["अभिलंब से दूर, क्योंकि वायु विरल माध्यम है", "अभिलंब की ओर", "बिना विचलन", "पूर्ण अवशोषण"],
     ["Away from the normal, because air is the rarer medium", "Towards the normal", "Undeviated", "Fully absorbed"],
     0,
     "सघन से विरल में जाने पर किरण अभिलंब से दूर मुड़ती है।",
     "From denser to rarer, the ray bends away from the normal."),

    ("refraction-and-lenses", "medium",
     "उत्तल लेंस पर समांतर किरणें आती हैं। वे कहाँ मिलती हैं?",
     "Parallel rays fall on a convex lens. Where do they meet?",
     ["दूसरी ओर फोकस पर", "प्रकाशिक केंद्र पर", "2F पर", "लेंस के पीछे अनंत पर"],
     ["At the focus on the other side", "At the optical centre", "At 2F", "At infinity behind the lens"],
     0,
     "समांतर पुंज उत्तल लेंस के दूसरे फोकस पर अभिसृत होता है।",
     "A parallel beam converges at the second focus of a convex lens."),

    ("refraction-and-lenses", "medium",
     "0.5 मीटर फोकस दूरी वाली उत्तल लेंस की क्षमता कितनी है?",
     "What is the power of a convex lens of focal length 0.5 m?",
     ["+2 डाइऑप्टर", "+0.5 डाइऑप्टर", "+5 डाइऑप्टर", "−2 डाइऑप्टर"],
     ["+2 dioptres", "+0.5 dioptres", "+5 dioptres", "−2 dioptres"],
     0,
     "P = 1/f = 1/0.5 = +2 डाइऑप्टर।",
     "P = 1/f = 1/0.5 = +2 D."),

    ("refraction-and-lenses", "medium",
     "2 मीटर फोकस दूरी वाली अवतल लेंस की क्षमता कितनी है?",
     "What is the power of a concave lens of focal length 2 m?",
     ["−0.5 डाइऑप्टर", "+0.5 डाइऑप्टर", "−2 डाइऑप्टर", "+2 डाइऑप्टर"],
     ["−0.5 dioptres", "+0.5 dioptres", "−2 dioptres", "+2 dioptres"],
     0,
     "अवतल लेंस की f ऋणात्मक: P = 1/(−2) = −0.5 डाइऑप्टर।",
     "A concave lens has negative f: P = 1/(−2) = −0.5 D."),

    ("refraction-and-lenses", "medium",
     "25 सेमी फोकस दूरी वाली उत्तल लेंस की क्षमता कितनी है?",
     "What is the power of a convex lens of focal length 25 cm?",
     ["+4 डाइऑप्टर", "+25 डाइऑप्टर", "+0.4 डाइऑप्टर", "−4 डाइऑप्टर"],
     ["+4 dioptres", "+25 dioptres", "+0.4 dioptres", "−4 dioptres"],
     0,
     "25 सेमी = 0.25 मीटर; P = 1/0.25 = +4 डाइऑप्टर।",
     "25 cm = 0.25 m; P = 1/0.25 = +4 D."),

    ("refraction-and-lenses", "medium",
     "+3 डाइऑप्टर और −1 डाइऑप्टर की दो लेंसें संपर्क में रखी हैं। युग्मन की कुल क्षमता कितनी होगी?",
     "Two lenses of +3 D and −1 D are in contact. What is the combined power?",
     ["+2 डाइऑप्टर", "+4 डाइऑप्टर", "−4 डाइऑप्टर", "+3 डाइऑप्टर"],
     ["+2 dioptres", "+4 dioptres", "−4 dioptres", "+3 dioptres"],
     0,
     "P = P1 + P2 = +3 + (−1) = +2 डाइऑप्टर।",
     "P = P1 + P2 = +3 + (−1) = +2 D."),

    ("refraction-and-lenses", "medium",
     "उत्तल लेंस से 2F (दुगुनी फोकस दूरी) पर रखी वस्तु का प्रतिबिंब कहाँ और कैसा बनता है?",
     "Where and how is the image formed for an object at 2F of a convex lens?",
     ["दूसरी ओर 2F पर — वास्तविक, उल्टा, समान आकार", "F पर — बिंदु", "उसी ओर F के भीतर — आभासी", "अनंत पर"],
     ["At 2F on the other side — real, inverted, same size", "At F — a point", "On the same side within F — virtual", "At infinity"],
     0,
     "2F पर वस्तु का प्रतिबिंब 2F पर ही समान आकार का उल्टा बनता है।",
     "An object at 2F images at 2F, same size but inverted."),

    ("refraction-and-lenses", "medium",
     "उत्तल लेंस के F और 2F के बीच रखी वस्तु का प्रतिबिंब कहाँ बनता है?",
     "Where is the image formed for an object between F and 2F of a convex lens?",
     ["2F से परे — वास्तविक, उल्टा, बड़ा (प्रोजेक्टर का सिद्धांत)", "F पर", "2F पर समान आकार", "लेंस के उसी ओर आभासी"],
     ["Beyond 2F — real, inverted, enlarged (the projector principle)", "At F", "At 2F, same size", "On the same side, virtual"],
     0,
     "F–2F के बीच वस्तु देती है 2F के बाहर बड़ा वास्तविक प्रतिबिंब।",
     "Between F and 2F the image is real, enlarged, beyond 2F."),

    ("refraction-and-lenses", "medium",
     "उत्तल लेंस के फोकस F पर रखी वस्तु का प्रतिबिंब कहाँ बनता है?",
     "Where is the image formed when the object is at the focus F of a convex lens?",
     ["अनंत पर — बहुत बड़ा वास्तविक", "2F पर", "F पर ही", "लेंस के उसी ओर छोटा"],
     ["At infinity — highly enlarged and real", "At 2F", "At F itself", "On the same side, small"],
     0,
     "F की किरणें लेंस के बाद समांतर हो जाती हैं — प्रतिबिंब अनंत पर।",
     "Rays from F emerge parallel after the lens — the image is at infinity."),

    ("refraction-and-lenses", "medium",
     "उत्तल लेंस के फोकस के भीतर (F से नज़दीक) रखी वस्तु का प्रतिबिंब कैसा होता है?",
     "What is the image like for an object placed within the focus of a convex lens?",
     ["आभासी, सीधा, बड़ा — आवर्धक काँच की तरह", "वास्तविक, उल्टा, बड़ा", "वास्तविक, उल्टा, छोटा", "आभासी, सीधा, छोटा"],
     ["Virtual, erect, enlarged — like a magnifying glass", "Real, inverted, enlarged", "Real, inverted, diminished", "Virtual, erect, diminished"],
     0,
     "F के भीतर वस्तु का प्रतिबिंभ वस्तु की ओर, बड़ा और सीधा बनता है।",
     "Within F the image forms on the object's side — enlarged and erect."),

    ("refraction-and-lenses", "medium",
     "आवर्धन m = −1 का क्या अर्थ है (लेंस के लिए)?",
     "What does magnification m = −1 mean (for a lens)?",
     ["प्रतिबिंब वास्तविक, उल्टा और वस्तु के समान आकार का है", "प्रतिबिंब आभासी और बड़ा है", "प्रतिबिंब बिल्कुल नहीं बनता", "प्रतिबिंब सीधा और छोटा है"],
     ["The image is real, inverted and the same size as the object", "The image is virtual and enlarged", "No image forms", "The image is erect and diminished"],
     0,
     "|m| = 1 आकार समान; ऋण चिह्न उल्टा वास्तविक प्रतिबिंब।",
     "|m| = 1 means same size; the negative sign means inverted and real."),

    ("refraction-and-lenses", "medium",
     "कैमरे में प्रतिबिंब फिल्म/सेंसर पर कैसा बनता है?",
     "What kind of image forms on the film/sensor in a camera?",
     ["वास्तविक, उल्टा, छोटा", "आभासी, सीधा, छोटा", "वास्तविक, सीधा, बड़ा", "आभासी, उल्टा"],
     ["Real, inverted, diminished", "Virtual, erect, small", "Real, erect, enlarged", "Virtual, inverted"],
     0,
     "दूर की वस्तु लेंस के फोकस के पास छोटा उल्टा वास्तविक प्रतिबिंब बनाती है।",
     "A distant object forms a small, inverted, real image near the focus."),

    ("refraction-and-lenses", "medium",
     "फिल्म प्रोजेक्टर में फिल्म को लेंस के कहाँ रखा जाता है ताकि पर्दे पर बड़ा प्रतिबिंब बने?",
     "Where is the film placed relative to the projector lens to get a large image on the screen?",
     ["F और 2F के बीच", "2F पर", "F पर", "2F से बहुत दूर"],
     ["Between F and 2F", "At 2F", "At F", "Far beyond 2F"],
     0,
     "F–2F के बीच फिल्म का 2F से परे बड़ा उल्टा प्रतिबिंब बनता है (इसीलिए फिल्म उल्टी रखी जाती है)।",
     "Between F and 2F the film projects an enlarged inverted image beyond 2F (hence the film is inserted inverted)."),

    ("refraction-and-lenses", "medium",
     "गिलास के पानी में डूबा नींबू बड़ा दिखता है। कारण बताइए।",
     "A lemon immersed in a glass of water appears bigger. State the reason.",
     ["पानी से निकलने वाली किरणें अपवर्तित होकर बड़ा आभासी प्रतिबिंब बनाती हैं", "नींबू पानी सोखकर बड़ा हो जाता है", "गिलास का काँच नींबू पिघला देता है", "परावर्तन से नींबू दोहरा दिखता है"],
     ["Rays leaving the water refract and form a magnified virtual image", "The lemon absorbs water and swells", "The glass melts the lemon", "Reflection doubles the lemon"],
     0,
     "जल की सतह से अपवर्तन — आभासी प्रतिबिंब बड़ा।",
     "Refraction at the water surface — the virtual image is magnified."),

    ("refraction-and-lenses", "medium",
     "मछली जल में वास्तविक स्थान से ऊपर दिखती है। यदि आप उसे देखकर भाला मारें तो कहाँ चुनेंगे?",
     "A fish in water appears above its real position. If you spear it, where should you aim?",
     ["दिखाई देने वाली स्थिति से थोड़ा नीचे", "ठीक दिखाई देने वाली स्थिति पर", "दिखाई देने वाली स्थिति से ऊपर", "मछली को नहीं मारा जा सकता"],
     ["Slightly below the apparent position", "Exactly at the apparent position", "Above the apparent position", "The fish cannot be speared"],
     0,
     "अपवर्तन से मछली ऊपर प्रतीत होती है — वास्तविक मछली नीचे होती है।",
     "Refraction raises the apparent fish — the real fish is lower."),

    ("refraction-and-lenses", "medium",
     "अपवर्तन में किरण किस स्थिति में बिना मुड़े माध्यम बदल लेती है?",
     "In refraction, when does a ray cross into another medium without bending?",
     ["जब वह अभिलंब के अनुदिश गिरे (∠i = 0)", "जब ∠i = 45 डिग्री हो", "जब दोनों माध्यम समान हों तो भी वह मुड़ती है", "ऐसा कभी नहीं होता"],
     ["When it falls along the normal (∠i = 0)", "When ∠i = 45 degrees", "It still bends when both media are identical", "This never happens"],
     0,
     "∠i = 0 पर ∠r भी 0 — कोई दिशा-परिवर्तन नहीं।",
     "For ∠i = 0, ∠r is also 0 — no change of direction."),

    # ---- hard (9) ----
    ("refraction-and-lenses", "hard",
     "f = 10 सेमी की उत्तल लेंस से 30 सेमी दूर वस्तु रखी है। प्रतिबिंब की दूरी और प्रकृति बताइए।",
     "An object is 30 cm from a convex lens with f = 10 cm. Find the image distance and nature.",
     ["15 सेमी — वास्तविक, उल्टा, आधा आकार", "30 सेमी — समान आकार", "15 सेमी — आभासी, सीधा", "10 सेमी — बिंदु-रूप"],
     ["15 cm — real, inverted, half size", "30 cm — same size", "15 cm — virtual, erect", "10 cm — a point"],
     0,
     "1/v = 1/f + 1/u = 1/10 − 1/30 = 2/30 = 1/15 ⇒ v = +15 सेमी; m = v/u = 15/(−30) = −0.5।",
     "1/v = 1/f + 1/u = 1/10 − 1/30 = 1/15 ⇒ v = +15 cm; m = v/u = 15/(−30) = −0.5."),

    ("refraction-and-lenses", "hard",
     "f = 10 सेमी की उत्तल लेंस से वस्तु 20 सेमी दूर है। प्रतिबिंब कैसा बनेगा?",
     "An object is 20 cm from a convex lens with f = 10 cm. What is the image like?",
     ["20 सेमी पर — वास्तविक, उल्टा, समान आकार (m = −1)", "10 सेमी पर — बिंदु", "40 सेमी पर — दुगुना", "आभासी और सीधा"],
     ["At 20 cm — real, inverted, same size (m = −1)", "At 10 cm — a point", "At 40 cm — double size", "Virtual and erect"],
     0,
     "1/v = 1/10 − 1/20 = 1/20 ⇒ v = 20 सेमी; m = 20/(−20) = −1।",
     "1/v = 1/10 − 1/20 = 1/20 ⇒ v = 20 cm; m = 20/(−20) = −1."),

    ("refraction-and-lenses", "hard",
     "f = 10 सेमी की उत्तल लेंस से वस्तु 15 सेमी दूर है। प्रतिबिंब कहाँ बनेगा?",
     "An object is 15 cm from a convex lens with f = 10 cm. Where is the image formed?",
     ["30 सेमी पर — वास्तविक, उल्टा, दुगुना", "15 सेमी पर", "10 सेमी पर", "उसी ओर 30 सेमी पर आभासी"],
     ["At 30 cm — real, inverted, double size", "At 15 cm", "At 10 cm", "Virtual at 30 cm on the same side"],
     0,
     "1/v = 1/10 − 1/15 = 1/30 ⇒ v = +30 सेमी; m = 30/(−15) = −2।",
     "1/v = 1/10 − 1/15 = 1/30 ⇒ v = +30 cm; m = 30/(−15) = −2."),

    ("refraction-and-lenses", "hard",
     "f = 10 सेमी की अवतल लेंस से वस्तु 30 सेमी दूर है। प्रतिबिंब कहाँ और कैसा बनेगा?",
     "An object is 30 cm from a concave lens with f = 10 cm. Where and how is the image formed?",
     ["वस्तु की ही ओर लगभग 7.5 सेमी पर — आभासी, सीधा, एक-चौथाई आकार", "30 सेमी पर वास्तविक", "10 सेमी पर बड़ा", "अनंत पर"],
     ["About 7.5 cm on the same side — virtual, erect, one-quarter size", "Real at 30 cm", "Enlarged at 10 cm", "At infinity"],
     0,
     "1/v = 1/f + 1/u = −1/10 − 1/30 = −4/30 ⇒ v = −7.5 सेमी; m = (−7.5)/(−30) = +0.25।",
     "1/v = 1/f + 1/u = −1/10 − 1/30 = −4/30 ⇒ v = −7.5 cm; m = (−7.5)/(−30) = +0.25."),

    ("refraction-and-lenses", "hard",
     "उत्तल लेंस m = −2 दे रही है। वस्तु कहाँ रखी होगी?",
     "A convex lens gives m = −2. Where must the object be?",
     ["F और 2F के बीच", "2F पर", "F पर", "F के भीतर"],
     ["Between F and 2F", "At 2F", "At F", "Within F"],
     0,
     "m = −2 ऋणात्मक (वास्तविक-उल्टा) और बड़ा — यह F–2F की स्थिति का प्रतिबिंब है।",
     "m = −2 is negative (real-inverted) and enlarged — that is the F–2F case."),

    ("refraction-and-lenses", "hard",
     "किसी लेंस की क्षमता −0.5 डाइऑप्टर है। लेंस का प्रकार और फोकस दूरी बताइए।",
     "A lens has power −0.5 D. State the lens type and its focal length.",
     ["अवतल लेंस, f = −2 मीटर", "उत्तल लेंस, f = +2 मीटर", "अवतल लेंस, f = −0.5 मीटर", "उत्तल लेंस, f = +0.5 मीटर"],
     ["Concave lens, f = −2 m", "Convex lens, f = +2 m", "Concave lens, f = −0.5 m", "Convex lens, f = +0.5 m"],
     0,
     "f = 1/P = 1/(−0.5) = −2 मीटर; ऋणात्मक f ⇒ अवतल।",
     "f = 1/P = 1/(−0.5) = −2 m; negative f ⇒ concave."),

    ("refraction-and-lenses", "hard",
     "किसी उत्तल लेंस में वस्तु 15 सेमी पर रखने पर प्रतिबिंब 30 सेमी पर बनता है। लेंस की फोकस दूरी कितनी है?",
     "For a convex lens, an object at 15 cm gives an image at 30 cm. What is the focal length?",
     ["10 सेमी", "15 सेमी", "30 सेमी", "45 सेमी"],
     ["10 cm", "15 cm", "30 cm", "45 cm"],
     0,
     "1/f = 1/v − 1/u = 1/30 − (−1/15) = 1/30 + 1/15 = 1/10 ⇒ f = 10 सेमी।",
     "1/f = 1/v − 1/u = 1/30 + 1/15 = 1/10 ⇒ f = 10 cm."),

    ("refraction-and-lenses", "hard",
     "4 सेमी ऊँची वस्तु का प्रतिबिंब m = −2 से बनता है। प्रतिबिंब की ऊँचाई कितनी और कैसी होगी?",
     "A 4 cm tall object forms an image with m = −2. What is the image height and nature?",
     ["8 सेमी, उल्टी", "8 सेमी, सीधी", "2 सेमी, उल्टी", "4 सेमी, सीधी"],
     ["8 cm, inverted", "8 cm, erect", "2 cm, inverted", "4 cm, erect"],
     0,
     "h′ = m × h = −2 × 4 = −8 सेमी — ऋण उल्टन संकेत करता है।",
     "h′ = m × h = −2 × 4 = −8 cm — the negative sign means inverted."),

    ("refraction-and-lenses", "hard",
     "हीरे में प्रकाश की चाल लगभग 1.25 × 10^8 मीटर/सेकंड है। हीरे का अपवर्तनांक निकालिए।",
     "The speed of light in diamond is about 1.25 × 10^8 m/s. Find the refractive index of diamond.",
     ["2.4", "1.25", "0.42", "3.0"],
     ["2.4", "1.25", "0.42", "3.0"],
     0,
     "n = 3 × 10^8 ÷ 1.25 × 10^8 = 2.4 (लगभग 2.42)।",
     "n = 3 × 10^8 ÷ 1.25 × 10^8 = 2.4 (about 2.42)."),

    # ================= DISPERSION & HUMAN EYE (50) =================
    # ---- easy (20) ----
    ("dispersion-and-human-eye", "easy",
     "प्रकाश का विक्षेपण (dispersion) किसे कहते हैं?",
     "What is dispersion of light?",
     ["श्वेत प्रकाश का अपने सात घटक रंगों में विभाजित होना", "प्रकाश का दर्पण से लौटना", "प्रकाश का माध्यम बदलना", "प्रकाश का सोखा जाना"],
     ["The splitting of white light into its seven constituent colours", "Light returning from a mirror", "Light changing medium", "Light being absorbed"],
     0,
     "प्रिज़्म श्वेत प्रकाश को सात रंगों में बाँट देता है।",
     "A prism splits white light into seven colours."),

    ("dispersion-and-human-eye", "easy",
     "प्रिज़्म से गुज़रने पर श्वेत प्रकाश कितने रंगों में विभाजित होती है?",
     "Into how many colours does white light split on passing through a prism?",
     ["सात", "पाँच", "तीन", "दस"],
     ["Seven", "Five", "Three", "Ten"],
     0,
     "बैंगनी, इंडिगो, नीला, हरा, पीला, नारंगी और लाल — सात रंग।",
     "Violet, indigo, blue, green, yellow, orange and red — seven in all."),

    ("dispersion-and-human-eye", "easy",
     "VIBGYOR किसका स्मरण-क्रम है?",
     "VIBGYOR is the memory order of what?",
     ["स्पेक्ट्रम के रंग — बैंगनी से लाल तक", "ग्रहों के नाम", "तरंगों के प्रकार", "लेंसों के प्रकार"],
     ["The colours of the spectrum — violet to red", "The names of planets", "Types of waves", "Types of lenses"],
     0,
     "V-I-B-G-Y-O-R: बैंगनी, इंडिगो, नीला, हरा, पीला, नारंगी, लाल।",
     "V-I-B-G-Y-O-R: violet, indigo, blue, green, yellow, orange, red."),

    ("dispersion-and-human-eye", "easy",
     "श्वेत प्रकाश वास्तव में क्या है?",
     "What exactly is white light?",
     ["सात रंगों का मिश्रण", "शुद्ध एक रंग", "केवल नीली किरणें", "अदृश्य विकिरण"],
     ["A mixture of seven colours", "A single pure colour", "Only blue rays", "Invisible radiation"],
     0,
     "सभी सात रंग मिलकर श्वेत संवेदन देते हैं।",
     "All seven colours together give the sensation of white."),

    ("dispersion-and-human-eye", "easy",
     "इंद्रधनुष किस घटना का परिणाम है?",
     "A rainbow is the result of which phenomenon?",
     ["जल की बूँदों द्वारा प्रकाश का विक्षेपण", "प्रकाश का परावर्तन", "ध्वनि का परावर्तन", "प्रकाश का अवशोषण"],
     ["Dispersion of light by water droplets", "Reflection of light", "Reflection of sound", "Absorption of light"],
     0,
     "वर्षा की बूँदें छोटे प्रिज़्म की तरह व्यवहार करती हैं।",
     "Raindrops behave like tiny prisms."),

    ("dispersion-and-human-eye", "easy",
     "प्रिज़्म में किस रंग का विचलन सबसे कम होता है?",
     "Which colour is deviated the least in a prism?",
     ["लाल", "बैंगनी", "नीला", "हरा"],
     ["Red", "Violet", "Blue", "Green"],
     0,
     "लाल का विचलन न्यूनतम, बैंगनी का अधिकतम।",
     "Red is deviated least, violet most."),

    ("dispersion-and-human-eye", "easy",
     "मानव नेत्र का लेंस किस प्रकार का होता है?",
     "What type of lens is the human eye lens?",
     ["उत्तल (अभिसारी)", "अवतल (अपसारी)", "समतल", "बाइकॉन्केव"],
     ["Convex (converging)", "Concave (diverging)", "Plane", "Biconcave"],
     0,
     "नेत्र-लेंस जिली जैसा उत्तल लेंस है जो प्रतिबिंब रेटिना पर बनाता है।",
     "The eye lens is a convex, jelly-like lens that images onto the retina."),

    ("dispersion-and-human-eye", "easy",
     "नेत्र में आइरिस (iris) का कार्य क्या है?",
     "What is the function of the iris in the eye?",
     ["पुतली (pupil) का आकार नियंत्रित करना", "प्रतिबिंब बनाना", "रंग पहचानना", "आँख को ठंडा रखना"],
     ["To control the size of the pupil", "To form the image", "To recognise colours", "To cool the eye"],
     0,
     "आइरिस पुतली को फैलाती/सिकोड़ती है और प्रकाश-प्रवेश नियंत्रित करती है।",
     "The iris dilates/contracts the pupil, controlling light entry."),

    ("dispersion-and-human-eye", "easy",
     "नेत्र की पुतली (pupil) का कार्य क्या है?",
     "What is the role of the pupil in the eye?",
     ["नेत्र के भीतर प्रकाश का प्रवेश द्वार", "प्रतिबिंब बनाना", "रंग बताना", "आँख घुमाना"],
     ["The aperture through which light enters the eye", "To form the image", "To indicate colour", "To rotate the eye"],
     0,
     "पुतली वह छिद्र है जिससे प्रकाश नेत्र-लेंस तक पहुँचती है।",
     "The pupil is the hole through which light reaches the eye lens."),

    ("dispersion-and-human-eye", "easy",
     "नेत्र में प्रतिबिंब कहाँ बनता है?",
     "Where is the image formed in the eye?",
     ["रेटिना पर", "आइरिस पर", "पुतली पर", "कॉर्निया पर"],
     ["On the retina", "On the iris", "On the pupil", "On the cornea"],
     0,
     "रेटिना नेत्र का पर्दा है — यहीं वास्तविक प्रतिबिंब बनता है।",
     "The retina is the eye's screen — the real image forms there."),

    ("dispersion-and-human-eye", "easy",
     "निकट-दृष्टि दोष (myopia) में व्यक्ति को क्या स्पष्ट नहीं दिखता?",
     "In myopia (short-sightedness), what cannot be seen clearly?",
     ["दूर की वस्तुएँ", "पास की वस्तुएँ", "कोई नहीं", "केवल रंग"],
     ["Distant objects", "Nearby objects", "Nothing at all", "Only colours"],
     0,
     "निकट-दृष्टि में प्रतिबिंब रेटिना के सामने बनता है — दूर की वस्तुएँ धुँधली।",
     "In myopia the image forms in front of the retina — distant objects blur."),

    ("dispersion-and-human-eye", "easy",
     "दीर्घ-दृष्टि दोष (hypermetropia) में क्या स्पष्ट नहीं दिखता?",
     "In hypermetropia (long-sightedness), what is not seen clearly?",
     ["पास की वस्तुएँ", "दूर की वस्तुएँ", "कोई नहीं", "केवल रात में"],
     ["Nearby objects", "Distant objects", "Nothing at all", "Only at night"],
     0,
     "दीर्घ-दृष्टि में प्रतिबिंब रेटिना के पीछे बनता है — पास की वस्तुएँ धुँधली।",
     "In hypermetropia the image forms behind the retina — near objects blur."),

    ("dispersion-and-human-eye", "easy",
     "निकट-दृष्टि दोष किस लेंस से सुधारा जाता है?",
     "Which lens corrects myopia?",
     ["अवतल लेंस", "उत्तल लेंस", "बाइफोकल", "समतल"],
     ["A concave lens", "A convex lens", "A bifocal", "A plane one"],
     0,
     "अवतल लेंस किरणों को पहले बिखेरता है — प्रतिबिंब रेटिना पर आ जाता है।",
     "A concave lens diverges rays first — the image lands on the retina."),

    ("dispersion-and-human-eye", "easy",
     "दीर्घ-दृष्टि दोष किस लेंस से सुधारा जाता है?",
     "Which lens corrects hypermetropia?",
     ["उत्तल लेंस", "अवतल लेंस", "बाइफोकल", "प्रिज़्म"],
     ["A convex lens", "A concave lens", "A bifocal", "A prism"],
     0,
     "उत्तल लेंस अभिसारी बनाकर प्रतिबिंब रेटिना पर लाता है।",
     "A convex lens adds convergence to bring the image onto the retina."),

    ("dispersion-and-human-eye", "easy",
     "दृष्टि का स्थायित्व (persistence of vision) कितने समय तक रहता है?",
     "How long does persistence of vision last?",
     ["लगभग 1/16 सेकंड", "1 सेकंड", "1 मिनट", "1/100 मिनट"],
     ["About 1/16 of a second", "1 second", "1 minute", "1/100 of a minute"],
     0,
     "नेत्र पर प्रतिबिंब लगभग सोलहवें सेकंड तक बना रहता है।",
     "An image lingers on the eye for about a sixteenth of a second."),

    ("dispersion-and-human-eye", "easy",
     "नेत्र का अंधबिंदु (blind spot) क्यों बनता है?",
     "Why does the blind spot of the eye exist?",
     ["वहाँ दृश्य-कोशिकाएँ (रॉड्स/कोन्स) नहीं होतीं — दृश्य तंत्रिका वहाँ से निकलती है", "वहाँ प्रकाश नहीं पहुँचती", "वहाँ लेंस होता है", "वहाँ आँसू बनते हैं"],
     ["It has no visual cells (rods/cones) — the optic nerve leaves there", "Light never reaches there", "The lens is located there", "Tears form there"],
     0,
     "दृश्य तंत्रिका-निकास पर कोशिकाएँ अनुपस्थित — कोई दृष्टि नहीं।",
     "At the optic-nerve exit there are no receptor cells — no vision."),

    ("dispersion-and-human-eye", "easy",
     "नेत्र-लेंस की फोकस दूरी बदलने की क्षमता को क्या कहते हैं?",
     "What is the ability of the eye lens to change its focal length called?",
     ["अनुकूलन (accommodation)", "विक्षेपण", "स्थायित्व", "अपवर्तन"],
     ["Accommodation", "Not accommodation — dispersion", "Persistence", "Refraction"],
     0,
     "सिलियरी मांसपेशियाँ लेंस की वक्रता बदलकर फोकस दूरी बदलती हैं।",
     "Ciliary muscles change lens curvature to alter the focal length."),

    ("dispersion-and-human-eye", "easy",
     "नेत्र में रंग देखने के लिए कौन-सी कोशिकाएँ उत्तरदायी हैं?",
     "Which cells are responsible for colour vision in the eye?",
     ["शंकु कोशिकाएँ (cones)", "दंड कोशिकाएँ (rods)", "दोनों समान रूप से", "कोर्निया कोशिकाएँ"],
     ["Cone cells", "Rod cells", "Both equally", "Cornea cells"],
     0,
     "शंकु (कोन्स) तीव्र प्रकाश में रंग बताते हैं; दंड (रॉड्स) मद्धम प्रकाश में देखते हैं।",
     "Cones handle colour in bright light; rods handle dim light."),

    ("dispersion-and-human-eye", "easy",
     "मद्धम/कम प्रकाश में देखने के लिए कौन-सी कोशिकाएँ कार्य करती हैं?",
     "Which cells work in dim light?",
     ["दंड कोशिकाएँ (rods)", "शंकु कोशिकाएँ (cones)", "अंधबिंदु कोशिकाएँ", "कोई नहीं"],
     ["Rod cells", "Cone cells", "Blind-spot cells", "None"],
     0,
     "रॉड्स अत्यल्प प्रकाश में भी संवेदन देते हैं पर रंग नहीं बताते।",
     "Rods sense very little light but cannot tell colours."),

    ("dispersion-and-human-eye", "easy",
     "फिल्म देखते समय अलग-अलग स्थिर चित्र चलते हुए क्यों प्रतीत होते हैं?",
     "Why do still pictures in a film appear to move?",
     ["दृष्टि के स्थायित्व से आँख चित्रों को जोड़ देती है", "पर्दे की गति से", "ध्वनि के प्रभाव से", "प्रकाश के रंग बदलने से"],
     ["Persistence of vision makes the eye blend the frames", "The screen moves", "The sound effect", "Colours of light change"],
     0,
     "1/16 सेकंड तक टिकी प्रतिबिंब अगले चित्र से जुड़ जाती है।",
     "The 1/16 s lingering image merges with the next frame."),

    # ---- medium (22) ----
    ("dispersion-and-human-eye", "medium",
     "प्रिज़्म में बैंगनी रंग का विचलन लाल से अधिक क्यों होता है?",
     "Why is violet deviated more than red in a prism?",
     ["बैंगनी का अपवर्तनांक सर्वाधिक होता है, इसलिए वह सबसे अधिक मुड़ती है", "बैंगनी सबसे तेज़ चलती है", "लाल सबसे धीमी चलती है", "बैंगनी भारी होती है"],
     ["Violet has the highest refractive index, so it bends the most", "Violet travels fastest", "Red travels slowest", "Violet is heavier"],
     0,
     "काँच में बैंगनी की चाल न्यूनतम — विचलन अधिकतम।",
     "Violet is slowest in glass — hence maximum deviation."),

    ("dispersion-and-human-eye", "medium",
     "दो समरूप प्रिज़्म उल्टे क्रम में रखने पर स्पेक्ट्रम से क्या प्राप्त होता है?",
     "What do we get when two identical prisms are placed in inverted order after one another?",
     ["पुनः श्वेत प्रकाश", "दुगुना स्पेक्ट्रम", "केवल लाल प्रकाश", "अंधकार"],
     ["White light again", "A doubled spectrum", "Only red light", "Darkness"],
     0,
     "पहला प्रिज़्म बाँटता है, दूसरा उसी क्रम में जोड़ देता है — न्यूटन का प्रयोग।",
     "The first prism splits, the second recombines — Newton's experiment."),

    ("dispersion-and-human-eye", "medium",
     "प्राथमिक इंद्रधनुष में बाहरी वृत्त पर कौन-सा रंग होता है?",
     "Which colour lies on the outer edge of a primary rainbow?",
     ["लाल", "बैंगनी", "नीला", "हरा"],
     ["Red", "Violet", "Blue", "Green"],
     0,
     "लाल का विचलन न्यूनतम — इसलिए वह चाप के बाहरी भाग पर दिखता है।",
     "Red deviates least — hence it appears on the outer arc."),

    ("dispersion-and-human-eye", "medium",
     "इंद्रधनुष देखने के लिए सूर्य कहाँ होना चाहिए?",
     "Where should the sun be for a rainbow to be seen?",
     ["देखने वाले की पीठ के पीछे", "देखने वाले के सामने", "ठीक ऊपर सिर पर", "कहीं भी"],
     ["Behind the viewer", "In front of the viewer", "Exactly overhead", "Anywhere"],
     0,
     "प्रकाश पीछे से आकर बूँदों में विक्षेपित होकर दर्शक की ओर लौटती है।",
     "Light from behind disperses in droplets and returns to the viewer."),

    ("dispersion-and-human-eye", "medium",
     "निकट-दृष्टि दोष में दूर की वस्तु का प्रतिबिंब कहाँ बनता है?",
     "In myopia, where is the image of a distant object formed?",
     ["रेटिना के सामने", "रेटिना पर", "रेटिना के पीछे", "अंधबिंदु पर"],
     ["In front of the retina", "On the retina", "Behind the retina", "On the blind spot"],
     0,
     "अति-अभिसरण के कारण प्रतिबिंब रेटिना से पहले बन जाता है।",
     "Excess convergence forms the image before the retina."),

    ("dispersion-and-human-eye", "medium",
     "दीर्घ-दृष्टि दोष में पास की वस्तु का प्रतिबिंब कहाँ बनता है?",
     "In hypermetropia, where is the image of a near object formed?",
     ["रेटिना के पीछे", "रेटिना पर", "रेटिना के सामने", "पुतली पर"],
     ["Behind the retina", "On the retina", "In front of the retina", "On the pupil"],
     0,
     "अभिसरण कमी के कारण प्रतिबिंब रेटिना के पीछे बनता है।",
     "Insufficient convergence forms the image behind the retina."),

    ("dispersion-and-human-eye", "medium",
     "निकट-दृष्टि दोष के दो कारण बताइए।",
     "State two causes of myopia.",
     ["नेत्र-गोला अत्यधिक लंबा या लेंस की वक्रता अत्यधिक", "नेत्र-गोला छोटा या लेंस बहुत पतला", "आँसू की कमी", "रॉड्स की कमी"],
     ["Excessive eyeball length or excessive curvature of the lens", "Short eyeball or too thin a lens", "Deficiency of tears", "Deficiency of rods"],
     0,
     "दोनों स्थितियों में अभिसरण बढ़ जाता है — प्रतिबिंब आगे बनता है।",
     "Both increase convergence — the image forms too early."),

    ("dispersion-and-human-eye", "medium",
     "वृद्धावस्था में उत्पन्न दोष जिसमें लेंस की लोच घट जाती है, क्या कहलाता है?",
     "The defect of old age in which the lens loses elasticity is called?",
     ["वृद्ध-दृष्टि (presbyopia)", "निकट-दृष्टि", "दीर्घ-दृष्टि", "रंग-अंधता"],
     ["Presbyopia", "Myopia", "Hypermetropia", "Colour blindness"],
     0,
     "सिलियरी मांसपेशियों का दुर्बल होना भी कारण है — बाइफोकल लेंस से सुधार।",
     "Weakening ciliary muscles also contribute — corrected with bifocals."),

    ("dispersion-and-human-eye", "medium",
     "बाइफोकल लेंस में निचला भाग किस प्रकार का होता है और क्यों?",
     "What is the lower part of a bifocal lens and why?",
     ["उत्तल — पास का काम (पढ़ना) सपष्ट करने के लिए", "अवतल — दूर देखने के लिए", "समतल — सजावट", "प्रिज़्म — विक्षेपण के लिए"],
     ["Convex — to make near work (reading) clear", "Concave — for distance vision", "Plane — decorative", "Prism — for dispersion"],
     0,
     "नीचे के भाग से पढ़ते समय आँख नीचे देखती है; उत्तल भाग पास को स्पष्ट करता है।",
     "While reading the eye looks through the bottom; the convex part clarifies near vision."),

    ("dispersion-and-human-eye", "medium",
     "नेत्र का न्यूनतम दृष्टि-दूरी (सुस्पष्ट देखने की न्यूनतम दूरी) कितनी होती है?",
     "What is the least distance of distinct vision for a normal eye?",
     ["25 सेमी", "2.5 सेमी", "250 सेमी", "अनंत"],
     ["25 cm", "2.5 cm", "250 cm", "Infinity"],
     0,
     "सामान्य नेत्र 25 सेमी से नज़दीक की वस्तु सुस्पष्ट नहीं देख सकता।",
     "A normal eye cannot focus clearly closer than 25 cm."),

    ("dispersion-and-human-eye", "medium",
     "रेटिना पर बनने वाला प्रतिबिंब कैसा होता है?",
     "What is the image formed on the retina like?",
     ["वास्तविक, उल्टा, छोटा", "आभासी, सीधा, छोटा", "वास्तविक, सीधा", "आभासी, उल्टा, बड़ा"],
     ["Real, inverted, diminished", "Virtual, erect, small", "Real, erect", "Virtual, inverted, enlarged"],
     0,
     "नेत्र-लेंस उत्तल है — प्रतिबिंब वास्तविक और उल्टा बनता है; मस्तिष्क उसे सीधा अनुभव कराता है।",
     "The convex eye lens forms a real, inverted image; the brain interprets it upright."),

    ("dispersion-and-human-eye", "medium",
     "कोई व्यक्ति केवल 2 मीटर तक की वस्तुएँ स्पष्ट देख सकता है। उसके लिए सुधार-लेंस की फोकस दूरी और क्षमता क्या होगी?",
     "A person sees clearly only up to 2 m. What are the focal length and power of the correcting lens?",
     ["f = −2 मीटर, P = −0.5 डाइऑप्टर (अवतल)", "f = +2 मीटर, P = +0.5 डाइऑप्टर", "f = −0.5 मीटर, P = −2 डाइऑप्टर", "f = 25 सेमी, P = +4 डाइऑप्टर"],
     ["f = −2 m, P = −0.5 D (concave)", "f = +2 m, P = +0.5 D", "f = −0.5 m, P = −2 D", "f = 25 cm, P = +4 D"],
     0,
     "अनंत की वस्तु को दूर-बिंदु 2 मीटर पर प्रतिबिंब बनाना है: f = −2 मीटर; P = 1/(−2) = −0.5 डाइऑप्टर।",
     "Distant objects must image at the 2 m far point: f = −2 m; P = 1/(−2) = −0.5 D."),

    ("dispersion-and-human-eye", "medium",
     "किसी दीर्घ-दृष्टि दोष वाले व्यक्ति की निकट-बिंदु 50 सेमी है। 25 सेमी की पुस्तक पढ़ने के लिए आवश्यक लेंस की क्षमता निकालिए।",
     "A hypermetropic person has a near point of 50 cm. Find the power of the lens needed to read a book at 25 cm.",
     ["+2 डाइऑप्टर उत्तल", "−2 डाइऑप्टर अवतल", "+0.5 डाइऑप्टर", "+4 डाइऑप्टर"],
     ["+2 D convex", "−2 D concave", "+0.5 D", "+4 D"],
     0,
     "u = −25, v = −50: 1/f = 1/(−50) − 1/(−25) = −1/50 + 1/25 = 1/50 ⇒ f = +50 सेमी; P = +2 डाइऑप्टर।",
     "u = −25, v = −50: 1/f = −1/50 + 1/25 = 1/50 ⇒ f = +50 cm; P = +2 D."),

    ("dispersion-and-human-eye", "medium",
     "सामान्य नेत्र द्वारा दूर की वस्तु देखते समय लेंस कैसा हो जाता है?",
     "What happens to the eye lens when viewing distant objects?",
     ["पतला — फोकस दूरी बढ़ती है", "मोटा — फोकस दूरी घटती है", "बिल्कुल नहीं बदलता", "गोल होकर हट जाता है"],
     ["It becomes thinner — focal length increases", "It becomes thicker — focal length decreases", "It does not change at all", "It rounds off and shifts"],
     0,
     "सिलियरी मांसपेशियाँ शिथिल होती हैं — लेंस पतला, अभिसरण कम।",
     "Ciliary muscles relax — the lens thins and converges less."),

    ("dispersion-and-human-eye", "medium",
     "पास की वस्तु देखते समय नेत्र-लेंस की वक्रता कैसी होती है?",
     "What is the curvature of the eye lens like when viewing near objects?",
     ["बढ़ती है — फोकस दूरी घटती है", "घटती है", "स्थिर रहती है", "शून्य हो जाती है"],
     ["It increases — focal length decreases", "It decreases", "It stays constant", "It becomes zero"],
     0,
     "मांसपेशियाँ सिकुड़ती हैं — लेंस मोटा, वक्रता अधिक।",
     "The muscles contract — the lens thickens with more curvature."),

    ("dispersion-and-human-eye", "medium",
     "प्रकाश की तीव्रता अधिक होने पर पुतली का आकार कैसा होता है?",
     "What happens to the pupil size in intense light?",
     ["सिकुड़ती है", "फैलती है", "अपरिवर्तित रहती है", "बंद हो जाती है"],
     ["It contracts", "It dilates", "It remains unchanged", "It closes fully"],
     0,
     "आइरिस पुतली सिकुड़कर प्रकाश-प्रवेश घटाती है — नेत्र-सुरक्षा।",
     "The iris shrinks the pupil, cutting light entry to protect the eye."),

    ("dispersion-and-human-eye", "medium",
     "कम प्रकाश (रात) में पुतली का आकार क्यों बड़ा हो जाता है?",
     "Why does the pupil enlarge in dim light (at night)?",
     ["अधिक प्रकाश भीतर लेने के लिए", "प्रकाश रोकने के लिए", "आँख बंद करने के लिए", "रंग बदलने के लिए"],
     ["To let more light in", "To block light", "To close the eye", "To change colour"],
     0,
     "फैली पुतली अधिक किरणें एकत्र करती है — मद्धम में भी दृश्य।",
     "A dilated pupil gathers more rays — vision even in dim light."),

    ("dispersion-and-human-eye", "medium",
     "नेत्र-गोले में प्रवेश करती प्रकाश का सबसे पहला और सबसे बड़ा अपवर्तन कहाँ होता है?",
     "Where does the first and largest refraction of entering light occur in the eye?",
     ["कॉर्निया पर", "रेटिना पर", "पुतली पर", "अंधबिंदु पर"],
     ["At the cornea", "At the retina", "At the pupil", "At the blind spot"],
     0,
     "कॉर्निया-वायु सीमा पर चांगुल अंतर से सबसे अधिक विचलन।",
     "The cornea-air boundary bends light the most, owing to the big index gap."),

    ("dispersion-and-human-eye", "medium",
     "स्पेक्ट्रम के बैंगनी सिरे के पार का विकिरण क्या कहलाता है जो दृश्य नहीं होता?",
     "What is the radiation just beyond the violet end of the spectrum called?",
     ["पराबैंगनी (UV)", "अवरक्त", "एक्स-रे", "माइक्रोवेव"],
     ["Ultraviolet", "Infrared", "X-ray", "Microwave"],
     0,
     "बैंगनी से आगे पराबैंगनी; लाल से आगे अवरक्त — दोनों अदृश्य।",
     "Beyond violet lies ultraviolet; beyond red, infrared — both invisible."),

    ("dispersion-and-human-eye", "medium",
     "लाल सिरे के पार का अदृश्य विकिरण जिससे गर्मी अनुभव होती है, क्या है?",
     "What is the invisible radiation beyond the red end that is felt as heat?",
     ["अवरक्त (infrared)", "पराबैंगनी", "गामा", "रेडियो तरंग"],
     ["Infrared", "Ultraviolet", "Gamma", "Radio waves"],
     0,
     "अवरक्त विकिरण ऊष्मा का संवेदन देता है — दूरस्थ संवेदक इसी पर आधारित।",
     "Infrared radiation gives the sensation of heat — remote sensors use it."),

    ("dispersion-and-human-eye", "medium",
     "सामान्य नेत्र की दूर-बिंदु (far point) कहाँ मानी जाती है?",
     "Where is the far point of a normal eye taken to be?",
     ["अनंत", "25 सेमी", "1 मीटर", "50 सेमी"],
     ["At infinity", "25 cm", "1 metre", "50 cm"],
     0,
     "सामान्य नेत्र अनंत तक की वस्तु भी रेटिना पर केंद्रित कर लेता है।",
     "A normal eye can focus even objects at infinity on the retina."),

    ("dispersion-and-human-eye", "medium",
     "चिड़िया घर में पक्षी तालाब के पानी में मछली को देखकर चोंच मारता है पर छूट जाती है। कारण बताइए।",
     "A bird dives at a fish seen in a pond but misses. Give the reason.",
     ["अपवर्तन से मछली वास्तविक स्थान से ऊपर दिखती है", "मछली बहुत तेज़ तैरती है", "पक्षी की आँख कमज़ोर है", "पानी में परावर्तन नहीं होता"],
     ["Refraction makes the fish appear above its real position", "The fish swims too fast", "The bird's eyes are weak", "No reflection occurs in water"],
     0,
     "जल-वायु सीमा पर अपवर्तन — आभासी स्थिति वास्तविक से ऊपर।",
     "Refraction at the water-air surface — the apparent position is above the real one."),

    # ---- hard (8) ----
    ("dispersion-and-human-eye", "hard",
     "किसी निकट-दृष्टि दोष वाले व्यक्ति की दूर-बिंदु 1.5 मीटर है। सुधार-लेंस की क्षमता लगभग कितनी होगी?",
     "A myopic person has a far point of 1.5 m. What is the approximate power of the correcting lens?",
     ["−0.67 डाइऑप्टर", "−1.5 डाइऑप्टर", "+0.67 डाइऑप्टर", "+1.5 डाइऑप्टर"],
     ["−0.67 D", "−1.5 D", "+0.67 D", "+1.5 D"],
     0,
     "f = −1.5 मीटर; P = 1/(−1.5) ≈ −0.67 डाइऑप्टर।",
     "f = −1.5 m; P = 1/(−1.5) ≈ −0.67 D."),

    ("dispersion-and-human-eye", "hard",
     "किसी दीर्घ-दृष्टि दोष वाले व्यक्ति की निकट-बिंदु 1 मीटर है। 25 सेमी पर पढ़ने हेतु लेंस की क्षमता कितनी चाहिए?",
     "A hypermetropic person has a near point of 1 m. What power is needed to read at 25 cm?",
     ["+3 डाइऑप्टर", "+1 डाइऑप्टर", "+4 डाइऑप्टर", "−3 डाइऑप्टर"],
     ["+3 D", "+1 D", "+4 D", "−3 D"],
     0,
     "u = −25, v = −100: 1/f = −1/100 + 1/25 = 3/100 ⇒ f = 33.3 सेमी; P = 100/33.3 = +3 डाइऑप्टर।",
     "u = −25, v = −100: 1/f = −1/100 + 1/25 = 3/100 ⇒ f = 33.3 cm; P = +3 D."),

    ("dispersion-and-human-eye", "hard",
     "बाइफोकल लेंस किस दोष-युग्म के सुधार में प्रयुक्त होता है और उसका ऊपरी भाग कैसा होता है?",
     "Which combined defect does a bifocal lens correct, and what is its upper part?",
     ["वृद्ध-दृष्टि (प्रेस्बायोपिया) — ऊपरी भाग दूर-दृष्टि हेतु अवतल/कम क्षमता", "निकट-दृष्टि — ऊपरी भाग उत्तल", "रंग-अंधता — ऊपरी भाग प्रिज़्म", "अंधबिंदु — ऊपरी भाग समतल"],
     ["Presbyopia — the upper part (distance vision) is concave/weaker", "Myopia — the upper part is convex", "Colour blindness — the upper part is a prism", "Blind spot — the upper part is plane"],
     0,
     "ऊपरी भाग दूर देखने के लिए (अवतल यदि निकट-दृष्टि भी हो), निचला उत्तल पढ़ने के लिए।",
     "The upper segment serves distance (concave if also myopic), the lower convex serves reading."),

    ("dispersion-and-human-eye", "hard",
     "नेत्र-लेंस और कैमरे के तुल्य अंगों का सही युग्म चुनिए।",
     "Choose the correct pair of analogous parts of the eye lens system and a camera.",
     ["रेटिना-फिल्म, पुतली-एपर्चर, नेत्र-लेंस-कैमरा लेंस", "रेटिना-शटर, पुतली-फिल्म, कॉर्निया-ट्राइपॉड", "अंधबिंदु-एपर्चर, आइरिस-फिल्म", "लेंस-बैटरी, रेटिना-लेंस"],
     ["Retina-film, pupil-aperture, eye lens-camera lens", "Retina-shutter, pupil-film, cornea-tripod", "Blind spot-aperture, iris-film", "Lens-battery, retina-lens"],
     0,
     "रेटिना = फिल्म/सेंसर; पुतली = एपर्चर; नेत्र-लेंस = ऑब्जेक्टिव लेंस।",
     "Retina = film/sensor; pupil = aperture; eye lens = objective lens."),

    ("dispersion-and-human-eye", "hard",
     "प्रिज़्म से श्वेत प्रकाश गुज़रती है। स्क्रीन पर बैंगनी और लाल किनारों की स्थिति आधार के सापेक्ष बताइए।",
     "White light passes through a prism. State the positions of the violet and red edges at the base.",
     ["बैंगनी प्रिज़्म के आधार की ओर अधिक झुकती है; लाल सबसे कम झुकती है", "लाल आधार की ओर अधिक झुकती है", "दोनों समान झुकती हैं", "कोई झुकती नहीं"],
     ["Violet bends most towards the base of the prism; red bends least", "Red bends most towards the base", "Both bend equally", "Neither bends"],
     0,
     "अधिक अपवर्तनांक वाला बैंगनी आधार की ओर सर्वाधिक विचलित होता है।",
     "Violet, with the highest index, deviates most towards the base."),

    ("dispersion-and-human-eye", "hard",
     "नेत्र-प्रतिबिंब रेटिना पर बनता है पर हम वस्तु सीधी देखते हैं। इसकी व्याख्या बताइए।",
     "The retinal image is inverted, yet we see objects upright. Explain.",
     ["मस्तिष्क उल्टे प्रतिबिंब की व्याख्या उलटकर करता है — अनुभव सीखा हुआ/तंत्रिका-प्रक्रिया है", "रेटिना प्रतिबिंब को पहले सीधा करती है", "लेंस दो बार उल्टता है", "पुतली प्रतिबिंब घुमा देती है"],
     ["The brain interprets the inverted image the right way up — a learned neural process", "The retina first erects the image", "The lens inverts it twice", "The pupil rotates the image"],
     0,
     "मस्तिष्क में प्रतिबिंब-प्रसंस्करण से सीधा अनुभव बनता है।",
     "Image processing in the brain creates the upright experience."),

    ("dispersion-and-human-eye", "hard",
     "सिनेमा की पर्दे पर प्रति सेकंड आमतौर पर 24 चित्र दिखाए जाते हैं। निरंतर गति का अनुभव किस सिद्धांत से होता है और 1/16 सेकंड से इसका संबंध क्या है?",
     "Cinema shows 24 frames per second. Which principle gives continuous motion, and how does it relate to 1/16 s?",
     ["दृष्टि स्थायित्व: प्रत्येक चित्र 1/16 सेकंड से कम समय बदलता है, अतः अगला चित्र पिछले से जुड़ जाता है", "विक्षेपण: रंग जुड़ते हैं", "अपवर्तन: किरणें झुकती हैं", "अनुकूलन: लेंस बदलता है"],
     ["Persistence of vision: each frame changes in less than 1/16 s, so it merges with the next", "Dispersion: colours merge", "Refraction: rays bend", "Accommodation: the lens changes"],
     0,
     "24 चित्र/सेकंड ⇒ अंतराल ≈ 0.042 सेकंड, जो 1/16 ≈ 0.0625 सेकंड से कम है — चित्र अविच्छिन्न जुड़ते हैं।",
     "24 fps ⇒ interval ≈ 0.042 s, below 1/16 ≈ 0.0625 s — frames join seamlessly."),

    ("dispersion-and-human-eye", "hard",
     "किसी व्यक्ति को दूर और पास — दोनों दृष्टियों में दिक्कत है और उम्र 60 वर्ष है। सर्वाधिक संभावित दोष और सुधार बताइए।",
     "A 60-year-old has trouble with both distant and near vision. State the most likely defect and its correction.",
     ["वृद्ध-दृष्टि (प्रेस्बायोपिया) — बाइफोकल लेंस", "केवल निकट-दृष्टि — अवतल लेंस", "केवल दीर्घ-दृष्टि — उत्तल लेंस", "रंग-अंधता — कोई लेंस नहीं"],
     ["Presbyopia — bifocal lenses", "Only myopia — concave lens", "Only hypermetropia — convex lens", "Colour blindness — no lens"],
     0,
     "लेंस लोच क्षीण होने से अनुकूलन क्षमता घटती है — दोनों दूरियों में धुँधलापन; बाइफोकल उपाय।",
     "Loss of lens elasticity cuts accommodation — blur at both ranges; bifocals help."),
]
