# -*- coding: utf-8 -*-
"""P09 (Electricity & Electric Circuits) — Part 2: resistance-and-combinations (50) + electric-power-and-safety (50) = 100 tuples.
All items authored with correct_idx=0; rotation happens in gen_p09_questions.py.

T3 resistance-and-combinations  50 = E20/M21/H9
T4 electric-power-and-safety    50 = E20/M22/H8
"""

PART2 = [
    # ================= RESISTANCE AND COMBINATIONS (50) =================
    # ---- easy (20) ----
    ("resistance-and-combinations", "easy",
     "प्रतिरोध किसे कहते हैं?",
     "What is resistance?",
     ["विद्युत धारा के प्रवाह में आने वाली बाधा", "धारा का मात्रक", "विभवांतर का माप", "धारा बढ़ाने वाला गुण"],
     ["The obstruction offered to the flow of electric current", "A unit of current", "A measure of potential difference", "A property that increases current"],
     0,
     "प्रतिरोध धारा को रोकने की प्रवृत्ति है; मात्रक ओम।",
     "Resistance is the tendency to oppose current; its unit is the ohm."),

    ("resistance-and-combinations", "easy",
     "प्रतिरोध का SI मात्रक क्या है?",
     "What is the SI unit of resistance?",
     ["ओम (Ω)", "वोल्ट (V)", "वाट (W)", "कूलॉम (C)"],
     ["Ohm (Ω)", "Volt (V)", "Watt (W)", "Coulomb (C)"],
     0,
     "प्रतिरोध ओम में मापा जाता है; 1 Ω = 1 V/A।",
     "Resistance is measured in ohms; 1 Ω = 1 V/A."),

    ("resistance-and-combinations", "easy",
     "समान पदार्थ के तार की लंबाई बढ़ाने पर प्रतिरोध का क्या होता है?",
     "What happens to the resistance of a wire of the same material if its length is increased?",
     ["बढ़ जाता है", "घट जाता है", "अपरिवर्तित रहता है", "शून्य हो जाता है"],
     ["It increases", "It decreases", "It remains unchanged", "It becomes zero"],
     0,
     "R ∝ l — लंबा रास्ता, अधिक बाधा।",
     "R ∝ l — a longer path offers more opposition."),

    ("resistance-and-combinations", "easy",
     "तार की मोटाई (अनुप्रस्थ काट का क्षेत्रफल) बढ़ाने पर प्रतिरोध कैसा होता है?",
     "What happens to resistance when the wire's thickness (cross-sectional area) is increased?",
     ["घट जाता है", "बढ़ जाता है", "समान रहता है", "दोगुना हो जाता है"],
     ["It decreases", "It increases", "It stays the same", "It doubles"],
     0,
     "R ∝ 1/A — मोटा तार, कम प्रतिरोध।",
     "R ∝ 1/A — a thicker wire has less resistance."),

    ("resistance-and-combinations", "easy",
     "श्रेणी क्रम में जुड़े प्रतिरोधों का समतुल्य प्रतिरोध कैसा होता है?",
     "What is the equivalent resistance of resistors joined in series?",
     ["सभी प्रतिरोधों का योग (R = R₁ + R₂)", "सभी का गुणनफल", "सबसे छोटे प्रतिरोध जितना", "शून्य"],
     ["The sum of all the resistances (R = R₁ + R₂)", "The product of all", "Equal to the smallest one", "Zero"],
     0,
     "श्रेणी में प्रतिरोध जुड़ जाते हैं।",
     "In series, resistances add up."),

    ("resistance-and-combinations", "easy",
     "समान्तर क्रम में जुड़े प्रतिरोधों का समतुल्य प्रतिरोध कैसा होता है?",
     "What is the equivalent resistance of resistors joined in parallel?",
     ["सबसे छोटे प्रतिरोध से भी कम", "सबसे बड़े प्रतिरोध से अधिक", "सभी का योग", "सभी का गुणनफल"],
     ["Less than even the smallest resistance", "More than the largest resistance", "The sum of all", "The product of all"],
     0,
     "समान्तर में धारा के अनेक मार्ग बन जाते हैं — कुल बाधा घटती है।",
     "Parallel paths give the current more routes — total opposition falls."),

    ("resistance-and-combinations", "easy",
     "श्रेणी परिपथ में प्रत्येक अवयव से गुज़रने वाली धारा कैसी होती है?",
     "What is the current through each component in a series circuit?",
     ["सभी में समान", "भिन्न-भिन्न", "क्रमशः घटती", "शून्य"],
     ["The same through all", "Different in each", "Successively decreasing", "Zero"],
     0,
     "श्रेणी में धारा का एक ही मार्ग होता है — हर अवयव से वही धारा बहती है।",
     "A series circuit has a single path — the same current runs through every component."),

    ("resistance-and-combinations", "easy",
     "समान्तर परिपथ में प्रत्येक अवयव के सिरों पर विभवांतर कैसा होता है?",
     "What is the PD across each component in a parallel circuit?",
     ["सभी में समान", "भिन्न-भिन्न", "क्रमशः बढ़ता", "शून्य"],
     ["The same across all", "Different for each", "Successively increasing", "Zero"],
     0,
     "समान्तर शाखाओं के सिरे समान दो बिंदुओं से जुड़े होते हैं।",
     "Parallel branches connect across the same two points."),

    ("resistance-and-combinations", "easy",
     "प्रतिरोधकता (resistivity) का SI मात्रक क्या है?",
     "What is the SI unit of resistivity?",
     ["ओम-मीटर (Ω m)", "ओम", "वोल्ट", "वाट"],
     ["Ohm-metre (Ω m)", "Ohm", "Volt", "Watt"],
     0,
     "R = ρl/A में ρ का मात्रक Ω m है।",
     "In R = ρl/A, ρ has the unit Ω m."),

    ("resistance-and-combinations", "easy",
     "ताँबा और एल्युमिनियम विद्युत चालन के लिए उपयुक्त क्यों हैं?",
     "Why are copper and aluminium suitable for electrical conduction?",
     ["इनकी प्रतिरोधकता बहुत कम होती है", "इनका गलनांक कम होता है", "ये हल्के रंग के होते हैं", "ये चुंबकीय होते हैं"],
     ["Their resistivity is very low", "Their melting point is low", "They are light-coloured", "They are magnetic"],
     0,
     "कम प्रतिरोधकता — ऊर्जा हानि न्यूनतम।",
     "Low resistivity means minimum energy loss."),

    ("resistance-and-combinations", "easy",
     "नाइक्रोम का उपयोग तापक उपकरणों के तार में क्यों होता है?",
     "Why is nichrome used for the wires of heating appliances?",
     ["इसकी प्रतिरोधकता बहुत अधिक होती है", "यह सस्ता होता है", "यह चालक होता है", "यह प्रकाश देता है"],
     ["Its resistivity is very high", "It is cheap", "It is a conductor", "It gives light"],
     0,
     "उच्च प्रतिरोधकता से तार में अधिक ऊष्मा विकसित होती है।",
     "High resistivity makes the wire release more heat."),

    ("resistance-and-combinations", "easy",
     "घरेलू विद्युत परिपथ में उपकरण किस क्रम में जुड़े होते हैं?",
     "How are appliances connected in household wiring?",
     ["समान्तर क्रम में", "श्रेणी क्रम में", "मिश्रित में से केवल श्रेणी", "कोई निश्चित क्रम नहीं"],
     ["In parallel", "In series", "Only series of the mixed kind", "No fixed order"],
     0,
     "समान्तर जोड़ से प्रत्येक उपकरण को पूरा वोल्टेज और स्वतंत्र नियंत्रण मिलता है।",
     "Parallel connection gives every appliance full voltage and independent control."),

    ("resistance-and-combinations", "easy",
     "दो समान प्रतिरोध R को समान्तर में जोड़ने पर समतुल्य प्रतिरोध कितना होगा?",
     "Two equal resistances R are joined in parallel. What is the equivalent resistance?",
     ["R/2", "2R", "R", "R/4"],
     ["R/2", "2R", "R", "R/4"],
     0,
     "समान दो प्रतिरोध समान्तर में आधा देते हैं।",
     "Two identical resistors in parallel give half."),

    ("resistance-and-combinations", "easy",
     "किसी तार का प्रतिरोध किन कारकों पर निर्भर करता है?",
     "On what factors does the resistance of a wire depend?",
     ["लंबाई, अनुप्रस्थ काट, पदार्थ और ताप", "केवल लंबाई", "केवल रंग और आकार", "केवल वोल्टेज"],
     ["Length, cross-section, material and temperature", "Only length", "Only colour and shape", "Only voltage"],
     0,
     "R = ρl/A — निर्माण व ताप दोनों मायने रखते हैं।",
     "R = ρl/A — both construction and temperature matter."),

    ("resistance-and-combinations", "easy",
     "किसी परिपथ में एक प्रतिरोध और जोड़ने पर कुल प्रतिरोध का क्या होगा (श्रेणी)?",
     "What happens to total resistance when one more resistor is added in series?",
     ["बढ़ जाता है", "घट जाता है", "समान रहता है", "शून्य हो जाता है"],
     ["It increases", "It decreases", "It stays the same", "It becomes zero"],
     0,
     "श्रेणी में हर नया प्रतिरोध योग में जुड़ता है।",
     "Every added series resistor adds to the sum."),

    ("resistance-and-combinations", "easy",
     "किसी समान्तर संयोजन में एक और शाखा जोड़ने पर कुल प्रतिरोध का क्या होता है?",
     "What happens to total resistance when one more branch is added in parallel?",
     ["घट जाता है", "बढ़ जाता है", "अपरिवर्तित रहता है", "अनंत हो जाता है"],
     ["It decreases", "It increases", "It remains unchanged", "It becomes infinite"],
     0,
     "धारा को एक और मार्ग मिलता है — कुल बाधा घटती है।",
     "The current gains one more route — total opposition falls."),

    ("resistance-and-combinations", "easy",
     "समान लंबाई के दो तार — एक मोटा, एक पतला। किसका प्रतिरोध कम होगा?",
     "Two wires of equal length — one thick, one thin. Which has lower resistance?",
     ["मोटे तार का", "पतले तार का", "दोनों का समान", "तार की मोटाई से कोई संबंध नहीं"],
     ["The thick wire's", "The thin wire's", "Equal for both", "Thickness has no relation to resistance"],
     0,
     "अधिक क्षेत्रफल — अधिक जगह से धारा बहना — कम प्रतिरोध।",
     "More area means more room for the current — lower resistance."),

    ("resistance-and-combinations", "easy",
     "श्रेणी और समान्तर परिपथ में धारा के मार्गों का अंतर बताइए।",
     "State the difference in current paths between series and parallel circuits.",
     ["श्रेणी में एक ही मार्ग, समान्तर में अनेक मार्ग", "श्रेणी में अनेक मार्ग, समान्तर में एक", "दोनों में एक ही मार्ग", "दोनों में अनेक मार्ग"],
     ["Series has a single path; parallel has many paths", "Series has many; parallel has one", "Both have a single path", "Both have many paths"],
     0,
     "मार्गों की संख्या ही दोनों संयोजनों का मूल अंतर है।",
     "The number of paths is the core difference between the two connections."),

    ("resistance-and-combinations", "easy",
     "प्रतिरोधक (resistor) का परिपथ में क्या कार्य है?",
     "What does a resistor do in a circuit?",
     ["धारा को नियंत्रित (घटाना) करना", "वोल्टेज पैदा करना", "धारा पैदा करना", "आवेश भरना"],
     ["To control (reduce) the current", "To generate voltage", "To generate current", "To store charge"],
     0,
     "उपयुक्त प्रतिरोध चुनकर धारा वांछित मान तक घटाई जाती है।",
     "A suitable resistance brings the current down to the desired value."),

    ("resistance-and-combinations", "easy",
     "घरेलू वायरिंग में मुख्य तार मोटे क्यों रखे जाते हैं?",
     "Why are the main wires in household wiring kept thick?",
     ["मोटे तार का प्रतिरोध कम होता है, बड़ी धारा सुरक्षित रूप से बह सकती है", "मोटे तार सस्ते होते हैं", "मोटे तार हल्के होते हैं", "मोटे तार अधिक ऊर्जा खाते हैं"],
     ["Thick wires have low resistance, letting large currents flow safely", "Thick wires are cheaper", "Thick wires are lighter", "Thick wires consume more energy"],
     0,
     "कम प्रतिरोध से तार अधिक गर्म नहीं होते।",
     "Low resistance keeps the wires from overheating."),

    # ---- medium (21) ----
    ("resistance-and-combinations", "medium",
     "2 ओम, 3 ओम और 5 ओम के प्रतिरोध श्रेणी में जुड़े हैं। कुल प्रतिरोध निकालिए।",
     "Resistors of 2 Ω, 3 Ω and 5 Ω are connected in series. Find the total resistance.",
     ["10 ओम", "1 ओम", "30 ओम", "5 ओम"],
     ["10 Ω", "1 Ω", "30 Ω", "5 Ω"],
     0,
     "R = 2 + 3 + 5 = 10 ओम।",
     "R = 2 + 3 + 5 = 10 Ω."),

    ("resistance-and-combinations", "medium",
     "3 ओम और 6 ओम के प्रतिरोध समान्तर में जुड़े हैं। समतुल्य प्रतिरोध निकालिए।",
     "3 Ω and 6 Ω resistors are connected in parallel. Find the equivalent resistance.",
     ["2 ओम", "9 ओम", "18 ओम", "4.5 ओम"],
     ["2 Ω", "9 Ω", "18 Ω", "4.5 Ω"],
     0,
     "1/R = 1/3 + 1/6 = 1/2 ⇒ R = 2 ओम।",
     "1/R = 1/3 + 1/6 = 1/2 ⇒ R = 2 Ω."),

    ("resistance-and-combinations", "medium",
     "दो 2 ओम के प्रतिरोध समान्तर में हैं। समतुल्य प्रतिरोध कितना है?",
     "Two 2 Ω resistors are in parallel. What is the equivalent resistance?",
     ["1 ओम", "4 ओम", "2 ओम", "0.5 ओम"],
     ["1 Ω", "4 Ω", "2 Ω", "0.5 Ω"],
     0,
     "समान दो प्रतिरोध: R/2 = 2/2 = 1 ओम।",
     "Two identical resistors: R/2 = 2/2 = 1 Ω."),

    ("resistance-and-combinations", "medium",
     "चार 8 ओम के प्रतिरोध समान्तर में जुड़े हैं। कुल प्रतिरोध निकालिए।",
     "Four 8 Ω resistors are connected in parallel. Find the total resistance.",
     ["2 ओम", "32 ओम", "8 ओम", "0.5 ओम"],
     ["2 Ω", "32 Ω", "8 Ω", "0.5 Ω"],
     0,
     "n समान प्रतिरोध समान्तर में: R/n = 8/4 = 2 ओम।",
     "n identical resistors in parallel: R/n = 8/4 = 2 Ω."),

    ("resistance-and-combinations", "medium",
     "7 ओम प्रतिरोध वाले तार की लंबाई दोगुनी कर दी जाए तो नया प्रतिरोध कितना होगा?",
     "A wire of resistance 7 Ω is doubled in length. What is the new resistance?",
     ["14 ओम", "3.5 ओम", "7 ओम", "28 ओम"],
     ["14 Ω", "3.5 Ω", "7 Ω", "28 Ω"],
     0,
     "R ∝ l — लंबाई दोगुनी ⇒ प्रतिरोध दोगुना = 14 ओम।",
     "R ∝ l — double length ⇒ double resistance = 14 Ω."),

    ("resistance-and-combinations", "medium",
     "10 ओम प्रतिरोध वाले तार की मोटाई (क्षेत्रफल) दोगुनी कर दी जाए तो प्रतिरोध कितना रह जाएगा?",
     "The thickness (area) of a 10 Ω wire is doubled. What is the new resistance?",
     ["5 ओम", "20 ओम", "10 ओम", "2.5 ओम"],
     ["5 Ω", "20 Ω", "10 Ω", "2.5 Ω"],
     0,
     "R ∝ 1/A — क्षेत्रफल दोगुना ⇒ प्रतिरोध आधा = 5 ओम।",
     "R ∝ 1/A — doubled area ⇒ halved resistance = 5 Ω."),

    ("resistance-and-combinations", "medium",
     "9 ओम प्रतिरोध वाले तार की लंबाई एक-तिहाई कर दी जाए तो प्रतिरोध क्या होगा?",
     "The length of a 9 Ω wire is reduced to one-third. What is the resistance now?",
     ["3 ओम", "27 ओम", "9 ओम", "6 ओम"],
     ["3 Ω", "27 Ω", "9 Ω", "6 Ω"],
     0,
     "R ∝ l — लंबाई 1/3 ⇒ प्रतिरोध 9/3 = 3 ओम।",
     "R ∝ l — one-third length ⇒ resistance 9/3 = 3 Ω."),

    ("resistance-and-combinations", "medium",
     "12 वोल्ट की बैटरी से 4 ओम और 8 ओम श्रेणी में जुड़े हैं। धारा तथा प्रत्येक पर विभवांतर निकालिए।",
     "A 12 V battery feeds 4 Ω and 8 Ω in series. Find the current and the PD across each.",
     ["1 एम्पियर; 4 वोल्ट और 8 वोल्ट", "12 एम्पियर; 0 वोल्ट", "2 एम्पियर; 6 वोल्ट प्रत्येक", "1 एम्पियर; 6 वोल्ट प्रत्येक"],
     ["1 A; 4 V and 8 V", "12 A; 0 V", "2 A; 6 V each", "1 A; 6 V each"],
     0,
     "R = 12 Ω; I = 12/12 = 1 A; V = IR से 4×1 = 4 V और 8×1 = 8 V।",
     "R = 12 Ω; I = 12/12 = 1 A; V = IR gives 4×1 = 4 V and 8×1 = 8 V."),

    ("resistance-and-combinations", "medium",
     "समान दो 6 ओम प्रतिरोधों को समान्तर में जोड़ने पर परिपथ का कुल प्रतिरोध कितना हो जाता है?",
     "What does the total circuit resistance become when two identical 6 Ω resistors are joined in parallel?",
     ["3 ओम", "12 ओम", "6 ओम", "1.5 ओम"],
     ["3 Ω", "12 Ω", "6 Ω", "1.5 Ω"],
     0,
     "समान दो प्रतिरोध समान्तर में आधा देते हैं: 6/2 = 3 ओम।",
     "Two identical resistors in parallel give half: 6/2 = 3 Ω."),

    ("resistance-and-combinations", "medium",
     "श्रेणी परिपथ में बड़े प्रतिरोध वाले अवयव पर विभवांतर कैसा होता है?",
     "In a series circuit, how is the PD across the higher-resistance component?",
     ["अधिक — विभवांतर प्रतिरोध के अनुक्रमानुपाती", "कम", "शून्य", "समान"],
     ["Larger — PD is proportional to resistance", "Smaller", "Zero", "Equal"],
     0,
     "एक ही धारा बहती है; V = IR से बड़े R पर बड़ा V।",
     "The same current flows; V = IR gives more V across the bigger R."),

    ("resistance-and-combinations", "medium",
     "श्रेणी में जुड़े तीन बल्बों में एक का फिलामेंट टूट गया। शेष बल्बों का क्या होगा?",
     "One of three series-connected bulbs fuses. What happens to the rest?",
     ["सभी बुझ जाते हैं — परिपथ खुल गया", "बाकी पहले से अधिक चमकते हैं", "केवल एक बुझता है", "कोई प्रभाव नहीं"],
     ["All go off — the circuit is broken", "The rest glow brighter than before", "Only one goes off", "No effect"],
     0,
     "श्रेणी का एक मार्ग टूटा मानो पूरा मार्ग टूटा।",
     "A single break in the series path stops everything."),

    ("resistance-and-combinations", "medium",
     "समान्तर में जुड़े तीन बल्बों में एक बंद कर दिया गया। शेष बल्बों का क्या होगा?",
     "One of three parallel-connected bulbs is switched off. What happens to the others?",
     ["वे सामान्य ही जलते रहते हैं", "वे भी बुझ जाते हैं", "उनकी चमक घट जाती है", "उन पर वोल्टेज बढ़ जाता है"],
     ["They keep glowing normally", "They also go off", "Their brightness falls", "Their voltage rises"],
     0,
     "समान्तर शाखाएँ स्वतंत्र होती हैं।",
     "Parallel branches are independent."),

    ("resistance-and-combinations", "medium",
     "तार A लंबा और पतला है, तार B छोटा और मोटा (उसी पदार्थ का)। किसका प्रतिरोध कम है?",
     "Wire A is long and thin; wire B is short and thick (same material). Which has lower resistance?",
     ["B", "A", "दोनों समान", "पदार्थ से तय नहीं होता"],
     ["B", "A", "Both equal", "It is not decided by the material"],
     0,
     "छोटी लंबाई + बड़ा क्षेत्रफल दोनों B का प्रतिरोध घटाते हैं।",
     "Shorter length and larger area both cut B's resistance."),

    ("resistance-and-combinations", "medium",
     "समान मापों के ताँबे और नाइक्रोम तारों में किसका प्रतिरोध अधिक होगा?",
     "Between copper and nichrome wires of identical dimensions, which has higher resistance?",
     ["नाइक्रोम — प्रतिरोधकता अधिक", "ताँबा", "दोनों समान", "मापों से तय नहीं"],
     ["Nichrome — higher resistivity", "Copper", "Both equal", "Not decided by dimensions"],
     0,
     "प्रतिरोधकता पदार्थ-गुण है; नाइक्रोम का ρ ताँबे से बहुत अधिक।",
     "Resistivity is a material property; nichrome's ρ far exceeds copper's."),

    ("resistance-and-combinations", "medium",
     "यदि घर के सभी बल्ब श्रेणी में जुड़े होते तो क्या समस्या आती?",
     "What problem would arise if all house bulbs were connected in series?",
     ["एक बल्ब बंद करते ही सब बंद; वोल्टेज बँटकर चमक घटती", "बिजली बिल दोगुना हो जाता", "बल्ब जल्दी फटते", "कोई समस्या नहीं"],
     ["Switching one off kills all; shared voltage dims every bulb", "The bill would double", "Bulbs would blow quickly", "No problem at all"],
     0,
     "इसीलिए घरेलू परिपथ समान्तर बनाए जाते हैं।",
     "That is why household circuits are wired in parallel."),

    ("resistance-and-combinations", "medium",
     "1 मीटर तार का प्रतिरोध 2 ओम है। उसी तार के 3 मीटर का प्रतिरोध कितना होगा?",
     "A 1 m wire has resistance 2 Ω. What is the resistance of 3 m of the same wire?",
     ["6 ओम", "2 ओम", "3 ओम", "0.67 ओम"],
     ["6 Ω", "2 Ω", "3 Ω", "0.67 Ω"],
     0,
     "R ∝ l: 3 गुना लंबाई ⇒ 3 × 2 = 6 ओम।",
     "R ∝ l: triple length ⇒ 3 × 2 = 6 Ω."),

    ("resistance-and-combinations", "medium",
     "एक ही तार ठंडी अवस्था की तुलना में गर्म होने पर कम धारा देता है। कारण बताइए।",
     "The same wire passes less current when hot than when cold. Give the reason.",
     ["ताप बढ़ने पर धातु का प्रतिरोध बढ़ जाता है", "ताप बढ़ने पर वोल्टेज घटता है", "गर्म तार आवेश सोखता है", "गर्मी से इलेक्ट्रॉन गिर जाते हैं"],
     ["A metal's resistance increases with temperature", "Voltage drops with temperature", "A hot wire absorbs charge", "Electrons fall off due to heat"],
     0,
     "अधिक प्रतिरोध पर I = V/R से धारा घटती है।",
     "Higher R means lower I at the same V."),

    ("resistance-and-combinations", "medium",
     "4 ओम, 4 ओम और 2 ओम के तीन प्रतिरोध समान्तर में जुड़े हैं। कुल प्रतिरोध निकालिए।",
     "Three resistors of 4 Ω, 4 Ω and 2 Ω are in parallel. Find the total resistance.",
     ["1 ओम", "10 ओम", "2 ओम", "0.5 ओम"],
     ["1 Ω", "10 Ω", "2 Ω", "0.5 Ω"],
     0,
     "1/R = 1/4 + 1/4 + 1/2 = 1 ⇒ R = 1 ओम।",
     "1/R = 1/4 + 1/4 + 1/2 = 1 ⇒ R = 1 Ω."),

    ("resistance-and-combinations", "medium",
     "श्रेणी परिपथ में अमीटर का पाठ्यांक किसी भी स्थान पर क्यों एक ही रहता है?",
     "Why does an ammeter read the same value at any point of a series circuit?",
     ["धारा का एक ही मार्ग है — आवेश न बनता है न नष्ट होता है", "अमीटर हर जगह वोल्टेज मापता है", "तार हर जगह मोटे होते हैं", "बैटरी धारा बढ़ा देती है"],
     ["There is a single path — charge is neither created nor destroyed", "The ammeter measures voltage everywhere", "The wires are thick everywhere", "The battery boosts the current"],
     0,
     "आवेश संरक्षण के कारण श्रेणी धारा सर्वत्र समान।",
     "Conservation of charge keeps the series current identical everywhere."),

    ("resistance-and-combinations", "medium",
     "दो 6 ओम प्रतिरोधों को पहले श्रेणी में, फिर समान्तर में जोड़ा गया। दोनों स्थितियों में कुल प्रतिरोधों का अनुपात कितना है?",
     "Two 6 Ω resistors are first joined in series, then in parallel. What is the ratio of the two total resistances?",
     ["4 : 1", "1 : 4", "2 : 1", "1 : 1"],
     ["4 : 1", "1 : 4", "2 : 1", "1 : 1"],
     0,
     "श्रेणी 12 Ω, समान्तर 3 Ω — अनुपात 12:3 = 4:1।",
     "Series 12 Ω, parallel 3 Ω — ratio 12:3 = 4:1."),

    ("resistance-and-combinations", "medium",
     "संयोजन तारों (connecting wires) का प्रतिरोध नगण्य क्यों माना जाता है?",
     "Why is the resistance of connecting wires considered negligible?",
     ["वे छोटे, मोटे और कम-प्रतिरोधकता वाले (ताँबे) होते हैं", "वे रोधी होते हैं", "उनमें धारा नहीं बहती", "वे रबर के बनते हैं"],
     ["They are short, thick and of low-resistivity copper", "They are insulators", "No current flows in them", "They are made of rubber"],
     0,
     "R = ρl/A — तीनों कारक मिलकर प्रतिरोध लगभग शून्य कर देते हैं।",
     "R = ρl/A — all three factors push the resistance towards zero."),

    # ---- hard (9) ----
    ("resistance-and-combinations", "hard",
     "8 ओम प्रतिरोध वाले तार को दोहरा कर (मोड़कर) समान्तर में जोड़ दिया जाए तो कुल प्रतिरोध कितना होगा?",
     "A wire of 8 Ω is folded into two equal parts joined in parallel. What is the total resistance?",
     ["2 ओम", "4 ओम", "8 ओम", "16 ओम"],
     ["2 Ω", "4 Ω", "8 Ω", "16 Ω"],
     0,
     "मोड़ने पर प्रत्येक आधा 4 Ω का; दोनों समान्तर: 4/2 = 2 ओम।",
     "Folding gives two 4 Ω halves in parallel: 4/2 = 2 Ω."),

    ("resistance-and-combinations", "hard",
     "4 ओम का प्रतिरोध उस संयोजन से श्रेणी में है जिसमें 3 ओम और 6 ओम समान्तर जुड़े हैं। कुल प्रतिरोध निकालिए।",
     "A 4 Ω resistor is in series with a parallel combination of 3 Ω and 6 Ω. Find the total resistance.",
     ["6 ओम", "13 ओम", "9 ओम", "2 ओम"],
     ["6 Ω", "13 Ω", "9 Ω", "2 Ω"],
     0,
     "समान्तर भाग = 2 ओम; श्रेणी योग = 4 + 2 = 6 ओम।",
     "Parallel part = 2 Ω; series sum = 4 + 2 = 6 Ω."),

    ("resistance-and-combinations", "hard",
     "6 ओम और 3 ओम श्रेणी में 18 वोल्ट स्रोत से जुड़े हैं। प्रत्येक पर विभवांतर निकालिए।",
     "6 Ω and 3 Ω are in series across an 18 V source. Find the PD across each.",
     ["6 ओम पर 12 वोल्ट; 3 ओम पर 6 वोल्ट", "6 ओम पर 6 वोल्ट; 3 ओम पर 12 वोल्ट", "दोनों पर 9 वोल्ट", "6 ओम पर 18 वोल्ट; 3 ओम पर शून्य"],
     ["12 V across 6 Ω; 6 V across 3 Ω", "6 V across 6 Ω; 12 V across 3 Ω", "9 V across each", "18 V across 6 Ω; zero across 3 Ω"],
     0,
     "I = 18/9 = 2 A; V = IR से 6×2 = 12 V और 3×2 = 6 V।",
     "I = 18/9 = 2 A; V = IR gives 6×2 = 12 V and 3×2 = 6 V."),

    ("resistance-and-combinations", "hard",
     "6 ओम और 3 ओम समान्तर में 6 वोल्ट स्रोत पर हैं। किस शाखा में धारा अधिक और कितनी होगी?",
     "6 Ω and 3 Ω are in parallel across a 6 V source. Which branch carries more current, and how much?",
     ["3 ओम वाली — 2 एम्पियर (6 ओम वाली में 1 एम्पियर)", "6 ओम वाली — 2 एम्पियर", "दोनों में 2 एम्पियर", "3 ओम वाली — 0.5 एम्पियर"],
     ["The 3 Ω branch — 2 A (the 6 Ω branch gets 1 A)", "The 6 Ω branch — 2 A", "2 A in both", "The 3 Ω branch — 0.5 A"],
     0,
     "I = V/R: 6/3 = 2 A और 6/6 = 1 A — कम प्रतिरोध, अधिक धारा।",
     "I = V/R: 6/3 = 2 A and 6/6 = 1 A — lower resistance, higher current."),

    ("resistance-and-combinations", "hard",
     "2 ओम प्रतिरोध वाले तार को खींचकर लंबाई दोगुनी कर दी गई (आयतन स्थिर)। नया प्रतिरोध कितना होगा?",
     "A wire of 2 Ω is stretched to double its length (volume constant). What is the new resistance?",
     ["8 ओम", "4 ओम", "2 ओम", "1 ओम"],
     ["8 Ω", "4 Ω", "2 Ω", "1 Ω"],
     0,
     "लंबाई दोगुनी और क्षेत्रफल आधा — दोनों कारण मिलकर R चार गुना = 8 ओम।",
     "Length doubles while area halves — together R becomes four times = 8 Ω."),

    ("resistance-and-combinations", "hard",
     "2 ओम, 3 ओम और 6 ओम के तीनों प्रतिरोध समान्तर में जुड़े हैं। कुल प्रतिरोध निकालिए।",
     "Resistors of 2 Ω, 3 Ω and 6 Ω are all in parallel. Find the total resistance.",
     ["1 ओम", "11 ओम", "3.67 ओम", "0.5 ओम"],
     ["1 Ω", "11 Ω", "3.67 Ω", "0.5 Ω"],
     0,
     "1/R = 1/2 + 1/3 + 1/6 = 1 ⇒ R = 1 ओम।",
     "1/R = 1/2 + 1/3 + 1/6 = 1 ⇒ R = 1 Ω."),

    ("resistance-and-combinations", "hard",
     "2 ओम का प्रतिरोध उस संयोजन से श्रेणी में है जिसमें 4 ओम और 4 ओम समान्तर जुड़े हैं। परिपथ 12 वोल्ट पर है। धारा निकालिए।",
     "A 2 Ω resistor is in series with a parallel pair of 4 Ω and 4 Ω. The circuit runs on 12 V. Find the current.",
     ["3 एम्पियर", "6 एम्पियर", "1.5 एम्पियर", "2 एम्पियर"],
     ["3 A", "6 A", "1.5 A", "2 A"],
     0,
     "समान्तर भाग 2 ओम; कुल 4 ओम; I = 12/4 = 3 एम्पियर।",
     "Parallel part 2 Ω; total 4 Ω; I = 12/4 = 3 A."),

    ("resistance-and-combinations", "hard",
     "ताँबे का तार: प्रतिरोधकता 1.7 × 10^-8 ओम-मीटर, लंबाई 2 मीटर, क्षेत्रफल 10^-6 वर्ग मीटर। प्रतिरोध निकालिए।",
     "A copper wire: resistivity 1.7 × 10^-8 Ω m, length 2 m, area 10^-6 m². Find its resistance.",
     ["0.034 ओम", "0.34 ओम", "0.0085 ओम", "3.4 ओम"],
     ["0.034 Ω", "0.34 Ω", "0.0085 Ω", "3.4 Ω"],
     0,
     "R = ρl/A = (1.7 × 10^-8 × 2) ÷ 10^-6 = 0.034 ओम।",
     "R = ρl/A = (1.7 × 10^-8 × 2) ÷ 10^-6 = 0.034 Ω."),

    ("resistance-and-combinations", "hard",
     "नियत वोल्टेज के परिपथ में एक प्रतिरोध और श्रेणी में जोड़ने पर अमीटर का पाठ्यांक घट जाता है। व्याख्या कीजिए।",
     "In a fixed-voltage circuit, adding one more series resistor lowers the ammeter reading. Explain.",
     ["कुल प्रतिरोध बढ़ता है, इसलिए I = V/R से धारा घटती है", "बैटरी कमज़ोर हो जाती है", "वोल्टेज बढ़ जाता है", "आवेश खर्च हो जाता है"],
     ["Total resistance rises, so I = V/R gives a smaller current", "The battery weakens", "The voltage increases", "Charge gets used up"],
     0,
     "V स्थिर, R बढ़ा ⇒ I घटी — ओम के नियम का सीधा परिणाम।",
     "Fixed V with larger R ⇒ smaller I — a direct consequence of Ohm's law."),

    # ================= ELECTRIC POWER AND SAFETY (50) =================
    # ---- easy (20) ----
    ("electric-power-and-safety", "easy",
     "विद्युत शक्ति का SI मात्रक क्या है?",
     "What is the SI unit of electrical power?",
     ["वाट (W)", "जूल (J)", "कूलॉम (C)", "ओम (Ω)"],
     ["Watt (W)", "Joule (J)", "Coulomb (C)", "Ohm (Ω)"],
     0,
     "शक्ति का मात्रक वाट है; 1 W = 1 J/s।",
     "The unit of power is the watt; 1 W = 1 J/s."),

    ("electric-power-and-safety", "easy",
     "विद्युत शक्ति का सूत्र क्या है?",
     "What is the formula for electrical power?",
     ["P = VI", "P = V/I", "P = I/V", "P = V + I"],
     ["P = VI", "P = V/I", "P = I/V", "P = V + I"],
     0,
     "P = VI — वोल्ट और एम्पियर के गुणनफल से वाट मिलते हैं।",
     "P = VI — volts times amperes gives watts."),

    ("electric-power-and-safety", "easy",
     "1 वाट किसके बराबर होता है?",
     "What is 1 watt equal to?",
     ["1 वोल्ट × 1 एम्पियर", "1 वोल्ट ÷ 1 एम्पियर", "1 जूल × 1 सेकंड", "1 कूलॉम प्रति सेकंड"],
     ["1 volt × 1 ampere", "1 volt ÷ 1 ampere", "1 joule × 1 second", "1 coulomb per second"],
     0,
     "1 W = 1 V × 1 A = 1 जूल प्रति सेकंड।",
     "1 W = 1 V × 1 A = 1 joule per second."),

    ("electric-power-and-safety", "easy",
     "विद्युत ऊर्जा के व्यावसायिक मात्रक को क्या कहते हैं?",
     "What is the commercial unit of electrical energy called?",
     ["किलोवाट-घंटा (यूनिट)", "किलोजूल", "वाट", "एम्पियर-घंटा"],
     ["Kilowatt-hour (the unit)", "Kilojoule", "Watt", "Ampere-hour"],
     0,
     "बिजली की खपत यूनिट में बेची जाती है; 1 यूनिट = 1 kWh।",
     "Electricity is sold in units; 1 unit = 1 kWh."),

    ("electric-power-and-safety", "easy",
     "1 किलोवाट-घंटा (1 यूनिट) किसके बराबर है?",
     "What is 1 kilowatt-hour (1 unit) equal to?",
     ["1 kW का उपकरण 1 घंटा चलने की ऊर्जा", "1 W का 1 घंटा", "1000 W का 1 सेकंड", "1 kW का 1 सेकंड"],
     ["The energy of a 1 kW appliance running 1 hour", "1 W for 1 hour", "1000 W for 1 second", "1 kW for 1 second"],
     0,
     "1 kWh = 1 kW × 1 h।",
     "1 kWh = 1 kW × 1 h."),

    ("electric-power-and-safety", "easy",
     "फ्यूज़ का परिपथ में क्या कार्य है?",
     "What does a fuse do in a circuit?",
     ["अत्यधिक धारा बहने पर पिघलकर परिपथ तोड़ देता है", "वोल्टेज बढ़ाता है", "धारा मापता है", "प्रतिरोध घटाता है"],
     ["It melts and breaks the circuit when excessive current flows", "It raises the voltage", "It measures current", "It lowers resistance"],
     0,
     "फ्यूज़ अति-धारा से परिपथ की रक्षा करता है।",
     "A fuse protects the circuit from excess current."),

    ("electric-power-and-safety", "easy",
     "फ्यूज़ का तार किस गुण वाली मिश्रधातु का बनता है?",
     "What property should the alloy of a fuse wire have?",
     ["कम गलनांक — जल्दी पिघल जाए", "बहुत ऊँचा गलनांक", "बहुत अधिक मोटाई", "रोधी होना"],
     ["A low melting point — so it melts quickly", "A very high melting point", "Very large thickness", "Being an insulator"],
     0,
     "कम गलनांक वाला मिश्रधातु (टिन-सीसा) अधिक धारा पर तुरंत पिघलता है।",
     "A low-melting alloy (tin-lead) melts at once on overload."),

    ("electric-power-and-safety", "easy",
     "फ्यूज़ तार परिपथ में किस तार से जोड़ा जाता है?",
     "The fuse wire is connected to which wire of the circuit?",
     ["लाइव (जीवित) तार से", "न्यूट्रल से", "अर्थ से", "किसी से भी"],
     ["The live wire", "The neutral", "The earth", "Any of them"],
     0,
     "लाइव तार में फ्यूज़ लगाने से अति-धारा पर स्रोत ही जुड़ाव से कट जाता है।",
     "Putting the fuse in the live wire disconnects the source itself on overload."),

    ("electric-power-and-safety", "easy",
     "अर्थिंग (भू-संपर्क) का क्या उद्देश्य है?",
     "What is the purpose of earthing?",
     ["उपकरण की धातु बॉडी का धरती से संपर्क — लीक होने पर धारा ज़मीन में चली जाए और झटका न लगे", "वोल्टेज बढ़ाना", "बिल घटाना", "प्रतिरोध बढ़ाना"],
     ["Connecting the metal body to the earth so leakage current passes into the ground instead of shocking the user", "To raise the voltage", "To lower the bill", "To increase resistance"],
     0,
     "अर्थ तार लीकेज धारा को सुरक्षित मार्ग देता है।",
     "The earth wire gives leakage current a safe path."),

    ("electric-power-and-safety", "easy",
     "MCB क्या है?",
     "What is an MCB?",
     ["स्वचालित सर्किट ब्रेकर — अधिक धारा पर स्वयं बंद हो जाता है", "धारा मापने का यंत्र", "उच्च वोल्टेज बनाने का यंत्र", "एक प्रकार का सेल"],
     ["A miniature circuit breaker — it switches itself off on excess current", "A current-measuring device", "A high-voltage generator", "A type of cell"],
     0,
     "MCB अति-भार होने पर परिपथ स्वतः काट देता है।",
     "An MCB cuts the circuit automatically on overload."),

    ("electric-power-and-safety", "easy",
     "विद्युत बिल किस इकाई में बनाया जाता है?",
     "In what unit is the electricity bill prepared?",
     ["यूनिट (kWh)", "वाट", "एम्पियर", "जूल"],
     ["Units (kWh)", "Watts", "Amperes", "Joules"],
     0,
     "खपत ऊर्जा यूनिट में गिनी जाती है।",
     "Consumed energy is counted in units."),

    ("electric-power-and-safety", "easy",
     "12 वोल्ट पर 2 एम्पियर लेने वाले उपकरण की शक्ति निकालिए।",
     "Find the power of a device drawing 2 A at 12 V.",
     ["24 वाट", "6 वाट", "14 वाट", "0.17 वाट"],
     ["24 W", "6 W", "14 W", "0.17 W"],
     0,
     "P = VI = 12 × 2 = 24 वाट।",
     "P = VI = 12 × 2 = 24 W."),

    ("electric-power-and-safety", "easy",
     "1 किलोवाट का गीज़र 1 घंटा चले तो कितने यूनिट खर्च होंगे?",
     "How many units are consumed if a 1 kW geyser runs for 1 hour?",
     ["1 यूनिट", "0.5 यूनिट", "60 यूनिट", "1000 यूनिट"],
     ["1 unit", "0.5 unit", "60 units", "1000 units"],
     0,
     "1 kW × 1 h = 1 kWh = 1 यूनिट।",
     "1 kW × 1 h = 1 kWh = 1 unit."),

    ("electric-power-and-safety", "easy",
     "विद्युत स्विच को गीले हाथ से क्यों नहीं छूना चाहिए?",
     "Why should an electrical switch not be touched with wet hands?",
     ["गीली त्वचा का प्रतिरोध बहुत घट जाता है — झटका लगने का खतरा", "स्विच गीला होकर खराब हो जाता है", "बिल बढ़ता है", "तार जल जाते हैं"],
     ["Wet skin's resistance drops greatly — risk of a shock", "The switch spoils by getting wet", "The bill rises", "The wires burn"],
     0,
     "नमी शरीर को चालक बना देती है।",
     "Moisture turns the body into a conductor."),

    ("electric-power-and-safety", "easy",
     "निम्न में से सर्वाधिक शक्ति खाने वाला उपकरण कौन-सा है?",
     "Which of the following consumes the most power?",
     ["विद्युत गीज़र (लगभग 2000 वाट)", "LED बल्ब (लगभग 9 वाट)", "पंखा (लगभग 60 वाट)", "मोबाइल चार्जर (लगभग 20 वाट)"],
     ["An electric geyser (about 2000 W)", "An LED bulb (about 9 W)", "A fan (about 60 W)", "A mobile charger (about 20 W)"],
     0,
     "तापक उपकरण सबसे अधिक शक्ति लेते हैं।",
     "Heating appliances draw the most power."),

    ("electric-power-and-safety", "easy",
     "LED बल्ब ऊर्जा-बचत के लिए क्यों कहे जाते हैं?",
     "Why are LED bulbs called energy-saving?",
     ["वे उतनी ही रोशनी बहुत कम वाट में देते हैं", "वे सस्ते होते हैं", "वे बिना बिजली चलते हैं", "वे ठंडक देते हैं"],
     ["They give the same light at far fewer watts", "They are cheap", "They run without electricity", "They provide cooling"],
     0,
     "कम वाट — कम यूनिट — कम बिल।",
     "Fewer watts — fewer units — a smaller bill."),

    ("electric-power-and-safety", "easy",
     "P = I²R सूत्र किस राशि का द्योतक है?",
     "What quantity does the formula P = I²R represent?",
     ["विद्युत शक्ति (वाट में)", "विद्युत आवेश", "विभवांतर", "प्रतिरोधकता"],
     ["Electrical power (in watts)", "Electric charge", "Potential difference", "Resistivity"],
     0,
     "P = VI = I²R = V²/R — तीनों रूप शक्ति के ही हैं।",
     "P = VI = I²R = V²/R — all three are forms of power."),

    ("electric-power-and-safety", "easy",
     "उपकरण पर अंकित '1000 W' का क्या अर्थ है?",
     "What does '1000 W' printed on an appliance mean?",
     ["वह प्रति सेकंड 1000 जूल ऊर्जा लेता है", "वह 1000 वोल्ट पर चलता है", "वह 1000 एम्पियर धारा लेता है", "वह 1000 यूनिट बिजली खाता है"],
     ["It takes 1000 joules of energy every second", "It runs at 1000 volts", "It draws 1000 amperes", "It consumes 1000 units"],
     0,
     "वाट रेटिंग प्रति सेकंड ऊर्जा-खपत बताती है: 1000 W = 1000 जूल प्रति सेकंड।",
     "The watt rating gives energy use per second: 1000 W = 1000 J each second."),

    ("electric-power-and-safety", "easy",
     "विद्युत अति-भार (overload) से क्या तात्पर्य है?",
     "What is meant by electrical overload?",
     ["एक ही परिपथ में इतने उपकरण जुड़ जाना कि धारा सुरक्षित सीमा से बढ़ जाए", "वोल्टेज घट जाना", "तार मोटा होना", "फ्यूज़ जुड़ना"],
     ["Connecting so many appliances on one circuit that the current exceeds the safe limit", "The voltage falling", "The wire being thick", "A fuse being connected"],
     0,
     "अति-भार पर तार गर्म होकर खतरा पैदा कर सकते हैं।",
     "Overloaded wires heat up and can create hazards."),

    ("electric-power-and-safety", "easy",
     "लघुपथ (शॉर्ट सर्किट) कब कहलाता है?",
     "When is it called a short circuit?",
     ["जब लाइव और न्यूट्रल तार सीधे छू जाएँ — प्रतिरोध लगभग शून्य, धारा अत्यधिक", "जब बल्ब फट जाए", "जब स्विच बंद हो", "जब फ्यूज़ सही हो"],
     ["When the live and neutral wires touch directly — resistance near zero, huge current", "When a bulb bursts", "When the switch is off", "When the fuse is intact"],
     0,
     "शून्य-प्रतिरोध पथ खतरनाक रूप से बड़ी धारा खींचता है।",
     "A near-zero resistance path draws dangerously large current."),

    # ---- medium (22) ----
    ("electric-power-and-safety", "medium",
     "220 वोल्ट पर 0.5 एम्पियर लेने वाले उपकरण की शक्ति निकालिए।",
     "Find the power of a device drawing 0.5 A at 220 V.",
     ["110 वाट", "440 वाट", "55 वाट", "220.5 वाट"],
     ["110 W", "440 W", "55 W", "220.5 W"],
     0,
     "P = VI = 220 × 0.5 = 110 वाट।",
     "P = VI = 220 × 0.5 = 110 W."),

    ("electric-power-and-safety", "medium",
     "220 वोल्ट पर 1100 वाट का गीज़र कितनी धारा लेगा?",
     "What current does an 1100 W geyser draw at 220 V?",
     ["5 एम्पियर", "2 एम्पियर", "0.2 एम्पियर", "242,000 एम्पियर"],
     ["5 A", "2 A", "0.2 A", "242,000 A"],
     0,
     "I = P/V = 1100/220 = 5 एम्पियर।",
     "I = P/V = 1100/220 = 5 A."),

    ("electric-power-and-safety", "medium",
     "220 वोल्ट-100 वाट के बल्ब का प्रतिरोध निकालिए।",
     "Find the resistance of a 220 V-100 W bulb.",
     ["484 ओम", "2.2 ओम", "22 ओम", "48.4 ओम"],
     ["484 Ω", "2.2 Ω", "22 Ω", "48.4 Ω"],
     0,
     "R = V²/P = 48400/100 = 484 ओम।",
     "R = V²/P = 48400/100 = 484 Ω."),

    ("electric-power-and-safety", "medium",
     "2 एम्पियर धारा 10 ओम प्रतिरोध से बहती है। व्यय शक्ति निकालिए।",
     "A current of 2 A flows through a 10 Ω resistor. Find the power spent.",
     ["40 वाट", "20 वाट", "5 वाट", "0.5 वाट"],
     ["40 W", "20 W", "5 W", "0.5 W"],
     0,
     "P = I²R = 4 × 10 = 40 वाट।",
     "P = I²R = 4 × 10 = 40 W."),

    ("electric-power-and-safety", "medium",
     "44 ओम का तापक 220 वोल्ट पर जुड़ा है। उसकी शक्ति निकालिए।",
     "A 44 Ω heater is connected to 220 V. Find its power.",
     ["1100 वाट", "5 वाट", "220 वाट", "9680 वाट"],
     ["1100 W", "5 W", "220 W", "9680 W"],
     0,
     "P = V²/R = 48400/44 = 1100 वाट।",
     "P = V²/R = 48400/44 = 1100 W."),

    ("electric-power-and-safety", "medium",
     "100 वाट का बल्ब रोज़ 10 घंटे जले तो एक दिन में कितने यूनिट खर्च होंगे?",
     "A 100 W bulb glows 10 hours daily. How many units per day?",
     ["1 यूनिट", "10 यूनिट", "0.1 यूनिट", "100 यूनिट"],
     ["1 unit", "10 units", "0.1 unit", "100 units"],
     0,
     "E = Pt = 100 W × 10 h = 1000 Wh = 1 kWh।",
     "E = Pt = 100 W × 10 h = 1000 Wh = 1 kWh."),

    ("electric-power-and-safety", "medium",
     "2 किलोवाट का गीज़र 3 घंटे चला। खर्च यूनिट निकालिए।",
     "A 2 kW geyser runs for 3 hours. Find the units consumed.",
     ["6 यूनिट", "2 यूनिट", "1.5 यूनिट", "5 यूनिट"],
     ["6 units", "2 units", "1.5 units", "5 units"],
     0,
     "E = 2 kW × 3 h = 6 kWh = 6 यूनिट।",
     "E = 2 kW × 3 h = 6 kWh = 6 units."),

    ("electric-power-and-safety", "medium",
     "एक माह 30 यूनिट खपत हुई; दर 5 रुपये प्रति यूनिट है। बिल कितना बनेगा?",
     "A month's consumption is 30 units at 5 rupees per unit. What is the bill?",
     ["150 रुपये", "35 रुपये", "6 रुपये", "300 रुपये"],
     ["150 rupees", "35 rupees", "6 rupees", "300 rupees"],
     0,
     "बिल = 30 × 5 = 150 रुपये।",
     "Bill = 30 × 5 = 150 rupees."),

    ("electric-power-and-safety", "medium",
     "1 kWh जूल में कितने होते हैं?",
     "How many joules are in 1 kWh?",
     ["3.6 × 10^6 जूल", "3.6 × 10^3 जूल", "1000 जूल", "3.6 × 10^9 जूल"],
     ["3.6 × 10^6 J", "3.6 × 10^3 J", "1000 J", "3.6 × 10^9 J"],
     0,
     "1000 W × 3600 s = 3.6 × 10^6 जूल।",
     "1000 W × 3600 s = 3.6 × 10^6 J."),

    ("electric-power-and-safety", "medium",
     "100 वाट का बल्ब 1 मिनट में कितनी ऊर्जा (जूल में) खाता है?",
     "How much energy (in joules) does a 100 W bulb use in 1 minute?",
     ["6000 जूल", "100 जूल", "600 जूल", "360,000 जूल"],
     ["6000 J", "100 J", "600 J", "360,000 J"],
     0,
     "E = Pt = 100 × 60 = 6000 जूल।",
     "E = Pt = 100 × 60 = 6000 J."),

    ("electric-power-and-safety", "medium",
     "60 वाट का बल्ब 5 घंटे जले तो kWh में ऊर्जा कितनी?",
     "A 60 W bulb burns for 5 hours. What is the energy in kWh?",
     ["0.3 kWh", "3 kWh", "300 kWh", "0.03 kWh"],
     ["0.3 kWh", "3 kWh", "300 kWh", "0.03 kWh"],
     0,
     "E = 60 W × 5 h = 300 Wh = 0.3 kWh।",
     "E = 60 W × 5 h = 300 Wh = 0.3 kWh."),

    ("electric-power-and-safety", "medium",
     "5 एम्पियर के फ्यूज़ वाले परिपथ में 10 एम्पियर खाने वाला उपकरण जोड़ा गया। क्या होगा?",
     "An appliance drawing 10 A is connected on a circuit with a 5 A fuse. What happens?",
     ["फ्यूज़ पिघलकर परिपथ तोड़ देगा — यही उसका काम है", "उपकरण सामान्य चलेगा", "फ्यूज़ धारा बढ़ा देगा", "बिल घट जाएगा"],
     ["The fuse melts and breaks the circuit — that is its job", "The appliance runs normally", "The fuse raises the current", "The bill falls"],
     0,
     "रेटिंग से अधिक धारा पर फ्यूज़ सुरक्षा काटता है।",
     "Above its rating the fuse cuts in for protection."),

    ("electric-power-and-safety", "medium",
     "अर्थिंग किस प्रकार झटके से बचाती है?",
     "How does earthing protect against shocks?",
     ["लीक हुई धारा कम-प्रतिरोध वाले अर्थ-मार्ग से ज़मीन में चली जाती है, शरीर से नहीं", "वह वोल्टेज शून्य कर देती है", "वह धारा रोक देती है", "वह बिजली सोख लेती है"],
     ["Leaked current finds the low-resistance earth path into the ground, not through the body", "It zeroes the voltage", "It stops the current", "It absorbs the electricity"],
     0,
     "अर्थ पथ का प्रतिरोध शरीर से बहुत कम होता है।",
     "The earth path's resistance is far lower than the body's."),

    ("electric-power-and-safety", "medium",
     "MCB फ्यूज़ की तुलना में सुविधाजनक क्यों माना जाता है?",
     "Why is an MCB considered more convenient than a fuse?",
     ["शॉर्ट/ओवरलोड के बाद उसे बदलने की ज़रूरत नहीं — स्विच उठाकर पुनः चालू", "वह सस्ता होता है", "वह धारा बढ़ाता है", "वह वोल्टेज घटाता है"],
     ["After a trip it needs no replacement — just reset the switch", "It is cheaper", "It increases current", "It lowers voltage"],
     0,
     "फ्यूज़ तार हर बार बदलना पड़ता है; MCB पुनः चालू हो जाता है।",
     "A fuse wire must be replaced each time; an MCB is simply reset."),

    ("electric-power-and-safety", "medium",
     "एक ही सॉकेट में अनेक उच्च-शक्ति उपकरण जोड़ना क्यों खतरनाक है?",
     "Why is plugging many high-power appliances into one socket dangerous?",
     ["कुल धारा सुरक्षा सीमा पार कर जाती है — तार गर्म, आग का खतरा", "वोल्टेज दोगुना हो जाता है", "प्रतिरोध शून्य हो जाता है", "बिल स्वतः नहीं आता"],
     ["The total current crosses the safe limit — wires heat up, fire risk", "The voltage doubles", "The resistance becomes zero", "The bill stops coming"],
     0,
     "अति-भार से बचने के लिए भार बाँटना ज़रूरी।",
     "Loads must be spread out to avoid overload."),

    ("electric-power-and-safety", "medium",
     "श्रेणी में जुड़े बल्ब समान्तर की तुलना में मंद क्यों जलते हैं?",
     "Why do series-connected bulbs glow dimmer than parallel ones?",
     ["प्रत्येक बल्ब को वोल्टेज बँट जाता है — कम V, कम शक्ति", "श्रेणी में धारा शून्य हो जाती है", "समान्तर में वोल्टेज बँटता है", "बल्ब गर्म नहीं होते"],
     ["The voltage divides among the bulbs — less V, less power", "Series current becomes zero", "In parallel the voltage divides", "The bulbs do not heat up"],
     0,
     "शक्ति ∝ वोल्टेज; बँटे वोल्टेज पर चमक घटती है।",
     "Power scales with voltage; shared voltage dims the glow."),

    ("electric-power-and-safety", "medium",
     "220 वोल्ट पर 0.4 एम्पियर लेने वाले पंखे की शक्ति निकालिए।",
     "Find the power of a fan drawing 0.4 A at 220 V.",
     ["88 वाट", "550 वाट", "220.4 वाट", "44 वाट"],
     ["88 W", "550 W", "220.4 W", "44 W"],
     0,
     "P = 220 × 0.4 = 88 वाट।",
     "P = 220 × 0.4 = 88 W."),

    ("electric-power-and-safety", "medium",
     "500 वाट की मिक्सी 12 मिनट चली। kWh में ऊर्जा निकालिए।",
     "A 500 W mixer runs for 12 minutes. Find the energy in kWh.",
     ["0.1 kWh", "6 kWh", "0.5 kWh", "100 kWh"],
     ["0.1 kWh", "6 kWh", "0.5 kWh", "100 kWh"],
     0,
     "12 मिनट = 0.2 घंटा; E = 0.5 kW × 0.2 h = 0.1 kWh।",
     "12 min = 0.2 h; E = 0.5 kW × 0.2 h = 0.1 kWh."),

    ("electric-power-and-safety", "medium",
     "दो 100 वाट के बल्ब समान्तर में जुड़े हैं। कुल शक्ति कितनी?",
     "Two 100 W bulbs are connected in parallel. What is the total power?",
     ["200 वाट", "100 वाट", "50 वाट", "400 वाट"],
     ["200 W", "100 W", "50 W", "400 W"],
     0,
     "प्रत्येक को पूरा वोल्टेज — दोनों पूरी शक्ति — योग 200 वाट।",
     "Each gets full voltage — both draw full power — total 200 W."),

    ("electric-power-and-safety", "medium",
     "1.5 किलोवाट का एसी 8 घंटे चला। यूनिट निकालिए।",
     "A 1.5 kW air conditioner runs for 8 hours. Find the units.",
     ["12 यूनिट", "1.5 यूनिट", "8 यूनिट", "9.5 यूनिट"],
     ["12 units", "1.5 units", "8 units", "9.5 units"],
     0,
     "E = 1.5 × 8 = 12 kWh = 12 यूनिट।",
     "E = 1.5 × 8 = 12 kWh = 12 units."),

    ("electric-power-and-safety", "medium",
     "विद्युत मरम्मत के समय रबर के दस्ताने क्यों पहने जाते हैं?",
     "Why are rubber gloves worn during electrical repairs?",
     ["रबर रोधी है — धारा को शरीर तक नहीं पहुँचने देता", "रबर नरम होता है", "रबर से पकड़ मज़बूत होती है", "रबर ठंडा रखता है"],
     ["Rubber insulates — it does not let current reach the body", "Rubber is soft", "Rubber gives a better grip", "Rubber keeps hands cool"],
     0,
     "रोधी सामग्री विद्युत-पथ शरीर तक आने से पहले ही काट देती है।",
     "Insulating material cuts the electrical path before it reaches the body."),

    ("electric-power-and-safety", "medium",
     "मरम्मत से पहले मेन स्विच बंद करना क्यों ज़रूरी है?",
     "Why is it essential to switch off the mains before repairs?",
     ["परिपथ को स्रोत से पूर्णतः अलग करना ताकि कोई धारा न बहे", "बिल बचता है", "तार ठंडे हो जाते हैं", "बल्ब जल्दी नहीं जलते"],
     ["To isolate the circuit from the source so that no current can flow", "It saves the bill", "The wires cool down", "Bulbs do not burn out"],
     0,
     "खुले परिपथ में काम करना ही सुरक्षित तरीका है।",
     "Working on an open circuit is the only safe way."),

    # ---- hard (8) ----
    ("electric-power-and-safety", "hard",
     "60 वाट और 100 वाट के दो बल्ब (दोनों 220 वोल्ट के) श्रेणी में जुड़े हैं। कौन-सा अधिक चमकेगा?",
     "A 60 W and a 100 W bulb (both 220 V) are connected in series. Which glows more?",
     ["60 वाट वाला — उसका प्रतिरोध अधिक है, एक ही धारा पर P = I²R अधिक", "100 वाट वाला", "दोनों समान", "कोई नहीं जलेगा"],
     ["The 60 W one — its resistance is higher, and the same current gives more P = I²R", "The 100 W one", "Both equally", "Neither will glow"],
     0,
     "R = V²/P से 60 W बल्ब का R अधिक; श्रेणी में समान I बहती है — अधिक R वाला अधिक शक्ति खाता है।",
     "R = V²/P makes the 60 W bulb's R higher; series carries one current — higher R dissipates more power."),

    ("electric-power-and-safety", "hard",
     "दो समरूप बल्ब (प्रत्येक 220 V-100 W) श्रेणी में 220 वोल्ट पर जुड़े हैं। संयोजन की कुल शक्ति कितनी होगी (R स्थिर मानकर)?",
     "Two identical bulbs (each 220 V-100 W) are in series across 220 V. What is the total power (take R constant)?",
     ["50 वाट — प्रत्येक बल्ब पर आधा वोल्टेज, प्रत्येक केवल 25 वाट देता है", "200 वाट", "100 वाट", "25 वाट"],
     ["50 W — each bulb gets half the voltage and yields only 25 W", "200 W", "100 W", "25 W"],
     0,
     "प्रत्येक बल्ब पर 110 V; R = 484 Ω ⇒ P = 110²/484 = 25 W — कुल 50 वाट।",
     "Each bulb gets 110 V; R = 484 Ω ⇒ P = 110²/484 = 25 W — total 50 W."),

    ("electric-power-and-safety", "hard",
     "किसी परिपथ की सामान्य धारा 4 एम्पियर है। उपयुक्त फ्यूज़ रेटिंग क्या होनी चाहिए?",
     "A circuit normally carries 4 A. What should the suitable fuse rating be?",
     ["लगभग 5 एम्पियर — सामान्य धारा से थोड़ी अधिक, अति-भार पर तुरंत कट जाए", "20 एम्पियर — बड़ा ही सुरक्षिका", "2 एम्पियर — सस्ता विकल्प", "60 एम्पियर — मुख्य लाइन जैसा"],
     ["About 5 A — slightly above the normal current, cutting off instantly on overload", "20 A — a bigger safety margin", "2 A — a cheaper option", "60 A — like the main line"],
     0,
     "बहुत कम रेटिंग बार-बार कटेगी; बहुत अधिक रेटिंग अति-भार पर भी नहीं कटेगी — दोनों असुरक्षित।",
     "Too small a rating trips repeatedly; too large never trips — both unsafe."),

    ("electric-power-and-safety", "hard",
     "एक घर में 100 वाट के बल्ब 6 घंटे और 500 वाट का तापक 2 घंटे रोज़ चलते हैं। 30 दिन की कुल यूनिट निकालिए।",
     "A home runs a 100 W bulb 6 h and a 500 W heater 2 h daily. Find the total units for 30 days.",
     ["48 यूनिट", "18 यूनिट", "30 यूनिट", "66 यूनिट"],
     ["48 units", "18 units", "30 units", "66 units"],
     0,
     "बल्ब: 0.1 × 6 × 30 = 18; तापक: 0.5 × 2 × 30 = 30; कुल 48 यूनिट।",
     "Bulb: 0.1 × 6 × 30 = 18; heater: 0.5 × 2 × 30 = 30; total 48 units."),

    ("electric-power-and-safety", "hard",
     "पतले तार वाले एक्सटेंशन बोर्ड पर भारी उपकरण चलाना क्यों खतरनाक है?",
     "Why is running heavy appliances on a thin-wired extension board dangerous?",
     ["पतले तार का प्रतिरोध अधिक — उसी धारा पर P = I²R से तार अत्यधिक गर्म हो जाता है", "पतले तार वोल्टेज बढ़ा देते हैं", "पतले तार धारा रोक देते हैं", "बोर्ड हल्का हो जाता है"],
     ["Thin wire has higher resistance — at the same current P = I²R overheats it", "Thin wires raise the voltage", "Thin wires stop the current", "The board becomes light"],
     0,
     "ऊष्मा विकास धारा के वर्ग और प्रतिरोध दोनों पर बढ़ता है।",
     "Heat production grows with both the square of current and the resistance."),

    ("electric-power-and-safety", "hard",
     "220 वोल्ट-100 वाट का बल्ब (प्रतिरोध स्थिर मानकर) 110 वोल्ट पर जोड़ा गया। अब शक्ति कितनी होगी?",
     "A 220 V-100 W bulb (resistance assumed constant) is connected at 110 V. What is the power now?",
     ["25 वाट", "50 वाट", "100 वाट", "200 वाट"],
     ["25 W", "50 W", "100 W", "200 W"],
     0,
     "R = 484 Ω; P = V²/R = 12100/484 = 25 वाट — वोल्टेज आधा, शक्ति एक-चौथाई।",
     "R = 484 Ω; P = V²/R = 12100/484 = 25 W — half voltage, quarter power."),

    ("electric-power-and-safety", "hard",
     "एक कमरे में 3 बल्ब (प्रत्येक 60 वाट) रोज़ 4 घंटे 30 दिन तक जलते हैं। कुल यूनिट निकालिए।",
     "A room has 3 bulbs (60 W each) burning 4 h daily for 30 days. Find the total units.",
     ["21.6 यूनिट", "7.2 यूनिट", "216 यूनिट", "72 यूनिट"],
     ["21.6 units", "7.2 units", "216 units", "72 units"],
     0,
     "0.06 × 3 × 4 × 30 = 21.6 kWh = 21.6 यूनिट।",
     "0.06 × 3 × 4 × 30 = 21.6 kWh = 21.6 units."),

    ("electric-power-and-safety", "hard",
     "लघुपथ की स्थिति में 220 वोल्ट और 0.5 ओम पथ-प्रतिरोध पर धारा कितनी बहती है और फ्यूज़/MCB क्यों ज़रूरी है?",
     "In a short circuit with 220 V and 0.5 Ω path resistance, how much current flows, and why are fuses/MCBs essential?",
     ["440 एम्पियर — ऐसी अति-धारा तार तपा सकती है; सुरक्षा यंत्र तुरंत परिपथ काटते हैं", "22 एम्पियर — कोई खतरा नहीं", "4400 एम्पियर — कुछ नहीं किया जा सकता", "44 एम्पियर — बिल बढ़ता है"],
     ["440 A — such excessive current can heat wires dangerously; protective devices cut the circuit instantly", "22 A — no danger", "4400 A — nothing can be done", "44 A — only the bill rises"],
     0,
     "I = 220/0.5 = 440 एम्पियर; फ्यूज़/MCB इसे मिनटों में काट देते हैं।",
     "I = 220/0.5 = 440 A; a fuse or MCB cuts it off within moments."),
]
