# -*- coding: utf-8 -*-
"""P10 (Magnetism & Electromagnetic Effects) — Part 1: magnetism-and-magnetic-field (50) + earths-magnetism (50) = 100 tuples.
All items authored with correct_idx=0; rotation happens in gen_p10_questions.py.

T1 magnetism-and-magnetic-field  50 = E20/M21/H9
T2 earths-magnetism              50 = E20/M21/H9
"""

PART1 = [
    # ================= MAGNETISM AND MAGNETIC FIELD (50) =================
    # ---- easy (20) ----
    ("magnetism-and-magnetic-field", "easy",
     "चुंबक के उन दो स्थानों को क्या कहते हैं जहाँ आकर्षण सबसे अधिक होता है?",
     "What are the two places on a magnet where attraction is strongest called?",
     ["ध्रुवों (उत्तरी और दक्षिणी) को", "मध्य-बिंदु को", "किनारों को", "सतह के केंद्र को"],
     ["Poles (north and south)", "The mid-point", "The edges", "The centre of the surface"],
     0,
     "चुंबकीय बल ध्रुवों पर सांद्रित होता है।",
     "Magnetic force is concentrated at the poles."),

    ("magnetism-and-magnetic-field", "easy",
     "चुंबक के समान ध्रुव एक-दूसरे के प्रति क्या करते हैं?",
     "What do like poles of two magnets do to each other?",
     ["प्रतिकर्षित करते हैं", "आकर्षित करते हैं", "कुछ प्रभाव नहीं", "पहले आकर्षित फिर प्रतिकर्षित"],
     ["They repel each other", "They attract each other", "No effect", "First attract then repel"],
     0,
     "उत्तर-उत्तर या दक्षिण-दक्षिण — प्रतिकर्षण; उत्तर-दक्षिण — आकर्षण।",
     "North-north or south-south — repulsion; north-south — attraction."),

    ("magnetism-and-magnetic-field", "easy",
     "चुंबक के विपरीत (भिन्न) ध्रुव एक-दूसरे के प्रति क्या करते हैं?",
     "What do unlike poles of two magnets do to each other?",
     ["आकर्षित करते हैं", "प्रतिकर्षित करते हैं", "कोई प्रभाव नहीं होता", "एक-दूसरे को नष्ट करते हैं"],
     ["They attract each other", "They repel each other", "No effect occurs", "They destroy each other"],
     0,
     "विपरीत ध्रुवों में आकर्षण होता है।",
     "Unlike poles attract."),

    ("magnetism-and-magnetic-field", "easy",
     "दो चुंबकों के ध्रुवों के बीच प्रतिकर्षण देखा गया। ध्रुवों का प्रकार बताइए।",
     "Repulsion is observed between the poles of two magnets. State the type of the poles.",
     ["दोनों समान ध्रुव हैं", "दोनों विपरीत ध्रुव हैं", "एक समान एक विपरीत", "पता नहीं लगाया जा सकता"],
     ["Both are like poles", "Both are unlike poles", "One like, one unlike", "It cannot be determined"],
     0,
     "प्रतिकर्षण केवल समान ध्रुवों में होता है।",
     "Repulsion occurs only between like poles."),

    ("magnetism-and-magnetic-field", "easy",
     "चुंबक के बाहर चुंबकीय बल रेखाएँ किस ध्रुव से किस ध्रुव की ओर जाती हैं?",
     "Outside a magnet, magnetic field lines run from which pole to which pole?",
     ["उत्तरी से दक्षिणी की ओर", "दक्षिणी से उत्तरी की ओर", "दोनों दिशाओं में", "किसी भी दिशा में बेतरतीब"],
     ["From north to south", "From south to north", "In both directions", "Randomly in any direction"],
     0,
     "बाहर का मार्ग N से S; चुंबक के भीतर S से N — रेखाएँ पूर्ण लूप बनाती हैं।",
     "Outside the path is N to S; inside the magnet S to N — the lines form complete loops."),

    ("magnetism-and-magnetic-field", "easy",
     "निम्न में से कौन-सी चुंबकीय धातु नहीं है?",
     "Which of the following is NOT a magnetic metal?",
     ["ताँबा", "लोहा", "निकल", "कोबाल्ट"],
     ["Copper", "Iron", "Nickel", "Cobalt"],
     0,
     "लोहा, निकल और कोबाल्ट प्रमुख चुंबकीय धातुएँ हैं; ताँबा अचुंबकीय।",
     "Iron, nickel and cobalt are the chief magnetic metals; copper is non-magnetic."),

    ("magnetism-and-magnetic-field", "easy",
     "चुंबक द्वारा आकर्षित नहीं किया जा सकता — इनमें से कौन?",
     "Which of these cannot be attracted by a magnet?",
     ["लकड़ी का टुकड़ा", "लोहे की कील", "निकल की चादर", "कोबाल्ट का टुकड़ा"],
     ["A piece of wood", "An iron nail", "A nickel sheet", "A piece of cobalt"],
     0,
     "लकड़ी, प्लास्टिक, काँच, ताँबा जैसे पदार्थ अचुंबकीय हैं।",
     "Wood, plastic, glass and copper are non-magnetic."),

    ("magnetism-and-magnetic-field", "easy",
     "लोहे की कील को चुंबक के पास लाने पर वह स्वयं चुंबक की तरह व्यवहार करने लगती है। इस घटना को क्या कहते हैं?",
     "An iron nail brought near a magnet itself starts behaving like a magnet. What is this phenomenon called?",
     ["चुंबकीय प्रेरण", "विद्युत-चुंबकीय प्रेरण", "प्रतिकर्षण", "चुंबकीय पृथक्करण"],
     ["Magnetic induction", "Electromagnetic induction", "Repulsion", "Magnetic separation"],
     0,
     "चुंबक के प्रभाव से लोहे में अस्थायी चुंबकत्व आता है — चुंबकीय प्रेरण।",
     "A magnet induces temporary magnetism in iron — magnetic induction."),

    ("magnetism-and-magnetic-field", "easy",
     "छड़ चुंबक को दो बराबर टुकड़ों में तोड़ा गया। प्रत्येक टुकड़े का क्या होता है?",
     "A bar magnet is broken into two equal pieces. What happens to each piece?",
     ["प्रत्येक टुकड़ा पूर्ण द्विध्रुवीय चुंबक बन जाता है", "उत्तरी ध्रुव अलग, दक्षिणी ध्रुव अलग हो जाता है", "टुकड़े चुंबकत्व खो देते हैं", "एक टुकड़ा चुंबक रहता है, दूसरा नहीं"],
     ["Each piece becomes a complete dipole magnet", "The north pole separates from the south pole", "The pieces lose their magnetism", "One piece stays magnetic, the other does not"],
     0,
     "एकध्रुवीय चुंबक संभव नहीं — हर टुकड़े में N और S दोनों ध्रुव बनते हैं।",
     "A monopole is impossible — every piece develops both N and S poles."),

    ("magnetism-and-magnetic-field", "easy",
     "चुंबकीय क्षेत्र का मात्रक क्या है?",
     "What is the unit of magnetic field?",
     ["टेस्ला (T)", "न्यूटन", "वोल्ट", "वाट"],
     ["Tesla (T)", "Newton", "Volt", "Watt"],
     0,
     "चुंबकीय क्षेत्र की तीव्रता टेस्ला में मापी जाती है।",
     "Magnetic field strength is measured in tesla."),

    ("magnetism-and-magnetic-field", "easy",
     "चुंबकीय क्षेत्र रेखाएँ एक-दूसरे को क्यों नहीं काटतीं?",
     "Why do magnetic field lines never intersect each other?",
     ["प्रतिच्छेदन बिंदु पर क्षेत्र की दो दिशाएँ बन जाएँगी, जो असंभव है", "रेखाएँ एक-दूसरे से डरती हैं", "रेखाएँ बहुत मोटी होती हैं", "काटने पर चुंबक टूट जाता है"],
     ["At a crossing point the field would have two directions, which is impossible", "The lines fear each other", "The lines are too thick", "The magnet breaks on crossing"],
     0,
     "क्षेत्र के किसी बिंदु पर सुई को एक ही दिशा मिलती है — दो दिशाएँ असंभव।",
     "At any point a compass gets a single direction — two directions are impossible."),

    ("magnetism-and-magnetic-field", "easy",
     "जिस क्षेत्र में चुंबकीय बल महसूस किया जा सकता है, उसे क्या कहते हैं?",
     "What is the region where a magnetic force can be felt called?",
     ["चुंबकीय क्षेत्र", "विद्युत क्षेत्र", "गुरुत्वीय क्षेत्र", "प्रकाश पुंज"],
     ["Magnetic field", "Electric field", "Gravitational field", "Light beam"],
     0,
     "चुंबक के चारों ओर बल-प्रभाव का क्षेत्र चुंबकीय क्षेत्र कहलाता है।",
     "The region of force influence around a magnet is its magnetic field."),

    ("magnetism-and-magnetic-field", "easy",
     "चुंबकीय क्षेत्र रेखाओं का घनत्व किस बात का संकेत देता है?",
     "What does the density of magnetic field lines indicate?",
     ["क्षेत्र की तीव्रता — घनी रेखाएँ अधिक तीव्र क्षेत्र", "चुंबक का रंग", "चुंबक की आयु", "ध्रुवों की संख्या"],
     ["The field strength — denser lines mean a stronger field", "The magnet's colour", "The magnet's age", "The number of poles"],
     0,
     "जहाँ रेखाएँ सघन हैं वहाँ बल अधिक तीव्र होता है।",
     "Where the lines crowd together the force is stronger."),

    ("magnetism-and-magnetic-field", "easy",
     "दिक्सूचक (कंपास) सुई किस धातु से बनी होती है?",
     "What metal is a compass needle made of?",
     ["चुंबकित लोहे (स्टील) की", "ताँबे की", "एल्युमिनियम की", "चाँदी की"],
     ["Magnetised iron (steel)", "Copper", "Aluminium", "Silver"],
     0,
     "सुई चुंबकित स्टील की होती है ताकि वह क्षेत्र की दिशा दर्शाए।",
     "The needle is magnetised steel so that it aligns with the field."),

    ("magnetism-and-magnetic-field", "easy",
     "लोहे की बुरादा यदि चुंबक के चारों ओर फेंकी जाए तो वह कहाँ चिपकेगी?",
     "If iron filings are sprinkled around a magnet, where do they stick?",
     ["ध्रुवों के पास सबसे अधिक", "समान रूप से चारों ओर", "केवल मध्य में", "कहीं नहीं चिपकती"],
     ["Most thickly near the poles", "Uniformly all around", "Only at the middle", "They do not stick anywhere"],
     0,
     "बुरादे का विन्यास बल रेखाओं का चित्र बनाता है — ध्रुवों पर सबसे सघन।",
     "The filings trace the field-line pattern — densest at the poles."),

    ("magnetism-and-magnetic-field", "easy",
     "स्थायी चुंबक किस पदार्थ से बनाया जाता है?",
     "What material is a permanent magnet made of?",
     ["स्टील (कठोर इस्पात)", "नर्म लोहा", "ताँबा", "प्लास्टिक"],
     ["Steel (hard iron)", "Soft iron", "Copper", "Plastic"],
     0,
     "स्टील का चुंबकत्व स्थायी रहता है इसलिए स्थायी चुंबक उसी से बनते हैं।",
     "Steel retains magnetism, so permanent magnets are made of it."),

    ("magnetism-and-magnetic-field", "easy",
     "चुंबक के पास रखी नर्म लोहे की छड़ का चुंबकत्व कैसा होता है?",
     "How does a soft iron rod kept near a magnet behave?",
     ["प्रबल लेकिन अस्थायी चुंबकत्व धारण करती है", "स्थायी चुंबक बन जाती है", "कोई प्रभाव नहीं होता", "चुंबक को हटा देती है"],
     ["It acquires strong but temporary magnetism", "It becomes a permanent magnet", "No effect occurs", "It pushes the magnet away"],
     0,
     "नर्म लोहा शीघ्र चुंबकित और शीघ्र निष्चुंबकित होता है — इसीलिए विद्युत-चुंबक में उपयोगी।",
     "Soft iron magnetises and demagnetises quickly — hence its use in electromagnets."),

    ("magnetism-and-magnetic-field", "easy",
     "किसी छड़ चुंबक को मुक्त रूप से लटकाया जाए तो वह किस दिशा में स्थिर होता है?",
     "When a bar magnet is suspended freely, in which direction does it come to rest?",
     ["लगभग उत्तर-दक्षिण दिशा में", "पूर्व-पश्चिम में", "किसी भी दिशा में", "ऊपर-नीचे"],
     ["Approximately in the north-south direction", "East-west", "In any direction", "Up-down"],
     0,
     "पृथ्वी के चुंबकीय क्षेत्र के कारण निलंबित चुंबक N-S में विराजता है।",
     "Due to the earth's magnetic field a suspended magnet settles along N-S."),

    ("magnetism-and-magnetic-field", "easy",
     "चुंबकत्व किसके कारण उत्पन्न होता है?",
     "What gives rise to magnetism?",
     ["परमाणुओं में इलेक्ट्रॉनों की गति से बने लघु चुंबकीय प्रभावों से", "परमाणुओं के भार से", "पदार्थ के रंग से", "घर्षण से"],
     ["Tiny magnetic effects created by the motion of electrons inside atoms", "The weight of atoms", "The colour of the material", "Friction"],
     0,
     "इलेक्ट्रॉनों की गति ही पदार्थ में चुंबकीय गुण का मूल स्रोत है।",
     "Electron motion is the basic source of magnetic behaviour in materials."),

    ("magnetism-and-magnetic-field", "easy",
     "चुंबकीय बल रेखाओं का पूर्ण विन्यास कैसा होता है?",
     "What is the overall pattern of magnetic field lines?",
     ["संवृत (बंद) वक्र — जो कहीं आरंभ या अंत नहीं लेते", "मुक्त सीधी रेखाएँ", "खुले वृत्त", "बिखरे हुए बिंदु"],
     ["Closed curves — they have no beginning or end", "Open straight lines", "Open circles", "Scattered dots"],
     0,
     "बाहर N→S और भीतर S→N — रेखाएँ निरंतर लूप बनाती हैं।",
     "Outside N→S and inside S→N — the lines form continuous loops."),

    # ---- medium (21) ----
    ("magnetism-and-magnetic-field", "medium",
     "चुंबक की कौन-सी विशेषता उसे विद्युत आवेश से पृथक करती है?",
     "Which feature distinguishes a magnet from an electric charge?",
     ["चुंबक सदैव दो ध्रुव रखता है, जबकि आवेश अकेला (एकध्रुवीय) हो सकता है", "चुंबक का कोई बल नहीं होता", "आवेश प्रतिकर्षित नहीं करते", "दोनों में कोई अंतर नहीं"],
     ["A magnet always has two poles, whereas a charge can exist alone", "A magnet exerts no force", "Charges never repel", "There is no difference"],
     0,
     "चुंबकीय एकध्रुव अस्तित्व में नहीं; धनावेश या ऋणावेश अकेले मिलते हैं।",
     "Magnetic monopoles do not exist; positive or negative charges occur alone."),

    ("magnetism-and-magnetic-field", "medium",
     "दो चुंबकों को ऐसे पास लाया गया कि पहले आकर्षण हुआ। ध्रुवों के बारे में क्या कहा जा सकता है?",
     "Two magnets are brought close and attraction occurs. What can be said about the poles?",
     ["सामने वाले ध्रुव विपरीत प्रकार के हैं", "सामने वाले ध्रुव समान हैं", "दोनों चुंबक उत्तरी हैं", "कुछ कहा नहीं जा सकता"],
     ["The facing poles are of opposite type", "The facing poles are alike", "Both magnets are north-type", "Nothing can be concluded"],
     0,
     "आकर्षण विपरीत ध्रुवों का प्रमाण है।",
     "Attraction is the signature of unlike poles."),

    ("magnetism-and-magnetic-field", "medium",
     "लोहे की एक कील को छड़ चुंबक के उत्तरी ध्रुव से छुआ गया। कील में दूर वाले सिरे पर कौन-सा ध्रुव बनेगा?",
     "An iron nail is touched with the north pole of a bar magnet. Which pole develops at the far end of the nail?",
     ["उत्तरी ध्रुव — चुंबक के N के सामने वाला सिरा दक्षिणी बनता है", "दक्षिणी ध्रुव", "कोई ध्रुव नहीं बनता", "दोनों सिरों पर दक्षिणी"],
     ["South pole — the near end turns north", "North pole", "No pole develops", "South at both ends"],
     0,
     "प्रेरित चुंबकत्व में चुंबक के N ध्रुव के सामने कील का सिरा S और दूर का सिरा N बनता है।",
     "In induced magnetism the nail's near face turns S (facing the magnet's N) and the far face turns N."),

    ("magnetism-and-magnetic-field", "medium",
     "चुंबकीय क्षेत्र रेखाओं पर विचार कीजिए — कौन-सा कथन गलत है?",
     "Consider magnetic field lines — which statement is WRONG?",
     ["दो रेखाएँ एक-दूसरे को काट सकती हैं", "रेखाएँ बंद वक्र हैं", "धनी रेखाएँ प्रबल क्षेत्र दर्शाती हैं", "बाहर N से S की ओर जाती हैं"],
     ["Two lines can cross each other", "The lines are closed curves", "Dense lines indicate a strong field", "Outside they run N to S"],
     0,
     "प्रतिच्छेदन असंभव है — एक बिंदु पर क्षेत्र की एक ही दिशा होती है।",
     "Crossing is impossible — the field has only one direction at a point."),

    ("magnetism-and-magnetic-field", "medium",
     "समान दूरी पर चुंबक के ध्रुव पर बल मध्य भाग से अधिक क्यों होता है?",
     "Why is the force at a magnet's pole greater than at its middle at the same distance?",
     ["ध्रुवों पर बल रेखाएँ सबसे सघन होती हैं", "मध्य भाग खोखला होता है", "ध्रुव बड़े होते हैं", "मध्य में रेखाएँ नहीं होतीं"],
     ["Field lines are densest at the poles", "The middle is hollow", "The poles are larger", "There are no lines at the middle"],
     0,
     "रेखाओं का सघनतम बंडल ध्रुवों पर निकलता है — तीव्रता अधिकतम।",
     "The densest bundle of lines emerges at the poles — maximum intensity."),

    ("magnetism-and-magnetic-field", "medium",
     "किसी निर्धारित बिंदु पर चुंबकीय क्षेत्र की दिशा कैसे ज्ञात की जाती है?",
     "How is the direction of the magnetic field at a given point found?",
     ["उस बिंदु पर रखी कंपास सुई के उत्तरी ध्रुव की दिशा से", "उस बिंदु की लंबाई से", "चुंबक के रंग से", "वहाँ तापमान मापकर"],
     ["From the direction of the north pole of a compass needle placed at that point", "From the length of that point", "From the magnet's colour", "By measuring the temperature there"],
     0,
     "कंपास सुई का उत्तरी सिरा क्षेत्र की दिशा बताता है।",
     "The needle's north tip indicates the field direction."),

    ("magnetism-and-magnetic-field", "medium",
     "एक छड़ चुंबक को तीन बराबर टुकड़ों में काटा गया। कुल कितने चुंबक बनें और कितने ध्रुव होंगे?",
     "A bar magnet is cut into three equal pieces. How many magnets form and how many poles in all?",
     ["3 चुंबक, 6 ध्रुव", "3 चुंबक, 2 ध्रुव", "1 चुंबक, 6 ध्रुव", "2 चुंबक, 6 ध्रुव"],
     ["3 magnets, 6 poles", "3 magnets, 2 poles", "1 magnet, 6 poles", "2 magnets, 6 poles"],
     0,
     "हर टुकड़ा द्विध्रुवीय — 3 × 2 = 6 ध्रुव।",
     "Every piece is a dipole — 3 × 2 = 6 poles."),

    ("magnetism-and-magnetic-field", "medium",
     "कथन A: चुंबक लोहे को दूर से भी खींचता है। कथन B: चुंबक का प्रभाव बल-रेखाओं वाले पूरे क्षेत्र में रहता है। सही विकल्प चुनिए।",
     "Statement A: a magnet pulls iron even from a distance. Statement B: the magnet's influence exists throughout the field-line region. Choose the correct option.",
     ["A और B दोनों सही हैं", "केवल A सही", "केवल B सही", "दोनों गलत"],
     ["Both A and B are true", "Only A is true", "Only B is true", "Both are false"],
     0,
     "दूरी पर बल घटता है पर समाप्त नहीं होता — दोनों कथन क्षेत्र-अवधारणा पर टिके हैं।",
     "The force weakens with distance but persists — both statements rest on the field idea."),

    ("magnetism-and-magnetic-field", "medium",
     "लोहे की छड़ को चुंबक के संपर्क में रखकर उसका चुंबकत्व बढ़ाने की विधि क्या कहलाती है?",
     "What is the method of magnetising an iron rod by contact with a magnet called?",
     ["स्पर्श विधि (एकल स्पर्श)", "विद्युत-चुंबकीय प्रेरण विधि", "प्रतिकर्षण विधि", "शीतलन विधि"],
     ["The contact (single touch) method", "The electromagnetic induction method", "The repulsion method", "The cooling method"],
     0,
     "चुंबक को छड़ के सिरे से रगड़ने/छूने से प्रेरित चुंबकत्व आता है।",
     "Stroking or touching with a magnet induces magnetism in the rod."),

    ("magnetism-and-magnetic-field", "medium",
     "नर्म लोहा बनाम स्टील — अस्थायी चुंबकत्व किसमें अधिक उपयुक्त है?",
     "Soft iron versus steel — which suits temporary magnetism better?",
     ["नर्म लोहा — धारा हटते ही चुंबकत्व समाप्त", "स्टील — चुंबकत्व स्थायी बना रहता है", "दोनों समान", "कोई नहीं"],
     ["Soft iron — its magnetism vanishes as soon as the current stops", "Steel — its magnetism persists", "Both equally", "Neither"],
     0,
     "निष्चुंबकन की सरलता ही अस्थायी अनुप्रयोगों की शर्त है।",
     "Easy demagnetisation is the very condition for temporary applications."),

    ("magnetism-and-magnetic-field", "medium",
     "एक चुंबक को गर्म करने या पीटने पर उसका चुंबकत्व क्या होता है?",
     "What happens to a magnet's magnetism on heating or hammering it?",
     ["कमज़ोर हो सकता है या समाप्त हो सकता है", "बढ़ जाता है", "अपरिवर्तित रहता है", "दुगुना हो जाता है"],
     ["It may weaken or be lost", "It increases", "It remains unchanged", "It doubles"],
     0,
     "अव्यवस्थित ऊष्मीय/यांत्रिक कंपन अंदरूनी चुंबकीय विन्यास बिखेर देते हैं।",
     "Heat or mechanical shocks disorder the internal magnetic arrangement."),

    ("magnetism-and-magnetic-field", "medium",
     "चुंबकीय पदार्थों का वर्गीकरण बताइए — निम्न समूह में से सही समूह कौन-सा है?",
     "Classify magnetic materials — which of the following groups is correct?",
     ["लोहा, निकल, कोबाल्ट — चुंबकीय", "ताँबा, लोहा, काँच — चुंबकीय", "एल्युमिनियम, निकल, लकड़ी — चुंबकीय", "प्लास्टिक, कोबाल्ट, रबर — चुंबकीय"],
     ["Iron, nickel, cobalt — magnetic", "Copper, iron, glass — magnetic", "Aluminium, nickel, wood — magnetic", "Plastic, cobalt, rubber — magnetic"],
     0,
     "Fe, Ni, Co ही विद्यालय स्तर के प्रमुख चुंबकीय तत्व हैं।",
     "Fe, Ni and Co are the chief magnetic elements at school level."),

    ("magnetism-and-magnetic-field", "medium",
     "चुंबक द्वारा आकर्षित पदार्थ अपने आप में कैसा व्यवहार करने लगता है?",
     "How does a material attracted by a magnet start behaving itself?",
     ["स्वयं एक अस्थायी चुंबक की तरह", "विद्युत स्रोत की तरह", "रोधी की तरह", "ऊष्मा स्रोत की तरह"],
     ["Like a temporary magnet itself", "Like an electric source", "Like an insulator", "Like a heat source"],
     0,
     "प्रेरित चुंबकत्व से वह अन्य लोहे की वस्तुओं को भी खींच सकता है।",
     "By induced magnetism it can even attract other iron objects."),

    ("magnetism-and-magnetic-field", "medium",
     "दो कंपास सुइयों को नज़दीक रखा गया। उनके उत्तरी सिरे एक-दूसरे की ओर कैसे प्रतिक्रिया करेंगे?",
     "Two compass needles are placed close together. How do their north tips react to each other?",
     ["प्रतिकर्षित करेंगे — समान ध्रुव", "आकर्षित करेंगे", "कोई प्रतिक्रिया नहीं", "घुमना बंद कर देंगे"],
     ["They repel — like poles", "They attract", "No reaction", "They stop rotating"],
     0,
     "प्रत्येक सुई लघु छड़ चुंबक है — N-N प्रतिकर्षण।",
     "Each needle is a tiny bar magnet — N-N repulsion."),

    ("magnetism-and-magnetic-field", "medium",
     "चुंबकीय क्षेत्र के भीतर रखी कंपास सुई विशेष दिशा में क्यों अनुगत होती है?",
     "Why does a compass needle inside a magnetic field align in a particular direction?",
     ["क्षेत्र का बल सुई पर घूर्णी प्रभाव डालता है और सुई क्षेत्र-रेखा के अनुदिश स्थिर होती है", "सुई में मोटर लगी होती है", "हवा सुई को घुमाती है", "सुई भार से घूमती है"],
     ["The field exerts a turning effect and the needle settles along the field line", "The needle has a motor inside", "Air turns the needle", "Gravity rotates the needle"],
     0,
     "घूर्णी बल-आघूर्ण सुई को क्षेत्र की दिशा में संरेखित करता है।",
     "A turning torque aligns the needle with the field direction."),

    ("magnetism-and-magnetic-field", "medium",
     "किसी तार को किसी चुंबकीय पदार्थ से बाँधकर चुंबक बनाने की आवश्यकता क्यों नहीं पड़ती?",
     "Why is there no need to tie a wire to any magnetic material to make an electromagnet?",
     ["क्षेत्र वाहक तार के चारों ओर स्वयं उत्पन्न होता है", "तार में पहले से चुंबकत्व होता है", "चुंबक तार को खींचता है", "बाँधने से धारा रुक जाती है"],
     ["The field arises around the current-carrying wire itself", "The wire is already magnetic", "A magnet pulls the wire", "Tying stops the current"],
     0,
     "धारा का चुंबकीय प्रभाव तार के चारों ओर क्षेत्र सीधा उत्पन्न करता है।",
     "The magnetic effect of current creates the field around the wire directly."),

    ("magnetism-and-magnetic-field", "medium",
     "निलंबित छड़ चुंबक का उत्तरी ध्रुव लगभग भौगोलिक उत्तर की ओर रहता है। इससे कौन-सा निष्कर्ष निकलता है?",
     "The north pole of a suspended bar magnet points roughly towards geographic north. What conclusion follows?",
     ["पृथ्वी स्वयं एक विशाल चुंबक है", "चुंबक में मोटर है", "उत्तर दिशा में लोहा है", "चुंबक गुरुत्व से घूमता है"],
     ["The earth itself is a giant magnet", "The magnet has a motor", "There is iron in the north", "The magnet turns by gravity"],
     0,
     "दिशा-निर्देशन पृथ्वी के चुंबकीय क्षेत्र का ही प्रमाण है।",
     "The directional setting is itself evidence of the earth's magnetic field."),

    ("magnetism-and-magnetic-field", "medium",
     "किरण-चुंबक (horseshoe) का आकार क्यों चुना जाता है?",
     "Why is the horseshoe shape chosen for magnets?",
     ["दोनों ध्रुव पास-पास आ जाते हैं — बीच के क्षेत्र में प्रबल आकर्षण", "यह सस्ता पड़ता है", "यह हल्का होता है", "इसमें एक ही ध्रुव होता है"],
     ["Both poles come close together — strong attraction in the gap", "It costs less", "It is lighter", "It has only one pole"],
     0,
     "U-आकार में N और S निकट होने से बीच वाला क्षेत्र एकदम प्रबल होता है।",
     "The U-shape brings N and S near, making the gap field very strong."),

    ("magnetism-and-magnetic-field", "medium",
     "यदि किसी वस्तु को चुंबक के पास लाने पर हल्का धक्का मिले तो वह वस्तु किस प्रकार की है?",
     "If an object is gently pushed away when brought near a magnet, what type of object is it?",
     ["चुंबकीय — उसका समान ध्रुव सामने है", "अचुंबकीय", "विद्युत-रोधी", "पारदर्शी"],
     ["Magnetic — its like pole faces the magnet", "Non-magnetic", "An electrical insulator", "Transparent"],
     0,
     "धक्का (प्रतिकर्षण) केवल चुंबकीय वस्तु से ही मिलता है — अचुंबकीय कोई प्रतिक्रिया नहीं देती।",
     "A push (repulsion) can come only from a magnetic object — non-magnetic ones show no reaction."),

    ("magnetism-and-magnetic-field", "medium",
     "निम्न में से कौन-सा समूह पूर्णतः अचुंबकीय पदार्थों का है?",
     "Which of the following groups consists entirely of non-magnetic materials?",
     ["ताँबा, काँच, लकड़ी", "लोहा, निकल, कोबाल्ट", "लोहा, ताँबा, काँच", "निकल, लकड़ी, प्लास्टिक"],
     ["Copper, glass, wood", "Iron, nickel, cobalt", "Iron, copper, glass", "Nickel, wood, plastic"],
     0,
     "केवल ताँबा-काँच-लकड़ी वाले समूह में कोई चुंबकीय धातु नहीं है।",
     "Only the copper-glass-wood group contains no magnetic metal."),

    ("magnetism-and-magnetic-field", "medium",
     "रेफ्रिजरेटर के दरवाज़े के किनारे चुंबकीय पट्टी क्यों लगी होती है?",
     "Why is a magnetic strip fitted along the edge of a refrigerator door?",
     ["हल्के आकर्षण से दरवाज़ा बंद बना रहे और भीतर की ठंडक बनी रहे", "दरवाज़ा रंगीन दिखने के लिए", "पट्टी से बिजली बचती है", "पट्टी दरवाज़ा स्वतः खोलती है"],
     ["A light attraction keeps the door shut and the cold sealed in", "To make the door look colourful", "The strip saves electricity", "The strip opens the door by itself"],
     0,
     "चुंबकीय पट्टी दरवाज़े को ढीला नहीं होने देती — चुंबकत्व का घरेलू अनुप्रयोग।",
     "The magnetic strip keeps the door from staying ajar — a household use of magnetism."),

    # ---- hard (9) ----
    ("magnetism-and-magnetic-field", "hard",
     "चुंबक N के क्षेत्र में लटकी कंपास सुई का उत्तरी सिरा चुंबक से दूर मुड़ जाता है। चुंबक का निकट ध्रुव कौन-सा है?",
     "The north tip of a compass needle deflects away from a nearby magnet. Which pole of the magnet is facing the needle?",
     ["उत्तरी ध्रुव", "दक्षिणी ध्रुव", "दोनों", "कोई नहीं"],
     ["The north pole", "The south pole", "Both", "Neither"],
     0,
     "सुई के N का विकर्षण सामने चुंबक के N से — समान ध्रुव प्रतिकर्षित करते हैं।",
     "The needle's N is repelled by the magnet's facing N — like poles repel."),

    ("magnetism-and-magnetic-field", "hard",
     "दो समान छड़ चुंबक N-S और S-N क्रम में एक पंक्ति में रखे हैं। बीच के संपर्क बिंदु पर क्या होगा?",
     "Two identical bar magnets lie in a line in the order N-S S-N. What happens at the middle contact point?",
     ["पहले चुंबक का S सिरा दूसरे के S सिरे से छूता है और प्रतिकर्षण होता है", "आकर्षण होता है", "कुछ नहीं होता", "चुंबक टूट जाते हैं"],
     ["The first magnet's S touches the other's S and repulsion occurs", "Attraction occurs", "Nothing happens", "The magnets break"],
     0,
     "क्रम N-S S-N में बीच में S-S मिलते हैं — प्रतिकर्षण।",
     "In the order N-S S-N the middle faces are S-S — repulsion."),

    ("magnetism-and-magnetic-field", "hard",
     "चुंबकीय क्षेत्र रेखाओं के गुणों पर तीन कथन: (i) ये बंद वक्र हैं (ii) ये एक-दूसरे को नहीं काटतीं (iii) इनका घनत्व क्षेत्र की तीव्रता बताता है। कितने सही हैं?",
     "Three statements about field lines: (i) they are closed curves (ii) they never cross (iii) their density shows field strength. How many are correct?",
     ["तीनों सही", "केवल दो सही", "केवल एक सही", "कोई सही नहीं"],
     ["All three are correct", "Only two are correct", "Only one is correct", "None is correct"],
     0,
     "तीनों गुण चुंबकीय बल रेखाओं की परिभाषित विशेषताएँ हैं।",
     "All three are defining properties of magnetic field lines."),

    ("magnetism-and-magnetic-field", "hard",
     "एक छड़ चुंबक को चार बराबर भागों में काटा गया। प्रत्येक भाग की चुंबकीय तीव्रता मूल चुंबक की तुलना में कैसी होगी?",
     "A bar magnet is cut into four equal parts. How does the magnetic strength of each part compare with the original?",
     ["प्रत्येक भाग कमज़ोर चुंबक है पर दोनों ध्रुव रखता है", "प्रत्येक भाग उतना ही प्रबल है", "भागों में ध्रुव नहीं बचते", "एक भाग N और एक भाग S हो जाता है"],
     ["Each part is a weaker magnet but retains both poles", "Each part is equally strong", "The parts retain no poles", "One part becomes N and another S"],
     0,
     "टुकड़े हर हाल में द्विध्रुवीय रहते हैं, यद्यपि तीव्रता घटती है।",
     "The pieces remain dipoles, though weaker."),

    ("magnetism-and-magnetic-field", "hard",
     "चुंबक के अंदर बल रेखाओं की दिशा बाहर की तुलना में कैसी होती है?",
     "How is the direction of field lines inside a magnet compared with outside?",
     ["भीतर दक्षिण से उत्तर की ओर — बाहर के विपरीत, लूप पूर्ण करती है", "भीतर भी उत्तर से दक्षिण", "भीतर कोई रेखा नहीं", "भीतर रेखाएँ काटती हैं"],
     ["Inside they run south to north — opposite to outside, completing the loop", "Inside also north to south", "There are no lines inside", "The lines cross inside"],
     0,
     "संवृत लूप की निरंतरता भीतर S→N दिशा से पूरी होती है।",
     "Continuity of the closed loop is maintained by the inner S→N path."),

    ("magnetism-and-magnetic-field", "hard",
     "कथन: चुंबक अपने क्षेत्र में रखे लोहे पर बल लगाता है, चुंबक और लोहे के बीच सीधा स्पर्श होना ज़रूरी नहीं। यह कथन —",
     "Statement: a magnet exerts force on iron placed in its field; direct contact between them is not necessary. This statement is —",
     ["सही है — बल क्षेत्र के माध्यम से कार्य करता है", "गलत है", "केवल बड़े चुंबकों के लिए सही", "केवल विद्युत-चुंबक के लिए सही"],
     ["True — the force acts through the field", "False", "True only for large magnets", "True only for electromagnets"],
     0,
     "बल-क्षेत्र स्पर्श के बिना ही प्रभाव डालता है।",
     "The field acts without any contact."),

    ("magnetism-and-magnetic-field", "hard",
     "एक अचुंबकीय छड़ और एक चुंबकित छड़ एक जैसे दिखते हैं। बिना किसी उपकरण के इन्हें कैसे पहचानें?",
     "A non-magnetic rod and a magnetised rod look identical. How can you tell them apart without any apparatus?",
     ["किसी एक छड़ को दूसरे के दोनों सिरों से क्रमशः लाइए — एक ही छड़ के एक सिरे से आकर्षण और दूसरे से प्रतिकर्षण मिलेगा तो वही चुंबक है", "दोनों को तौलिए", "रंग देखिए", "पानी में डुबोइए"],
     ["Bring one rod near both ends of the other in turn — if one end attracts and the other repels, that rod is the magnet", "Weigh both", "Look at the colours", "Dip them in water"],
     0,
     "आकर्षण तो लोहा भी दिखाए; प्रतिकर्षण केवल चुंबक ही दर्शाता है।",
     "Iron also shows attraction; only a magnet shows repulsion."),

    ("magnetism-and-magnetic-field", "hard",
     "चुंबकीय बल रेखाएँ चुंबक के भीतर और बाहर मिलाकर कुल कितने प्रतिशत मार्ग बंद रखती हैं?",
     "Combining inside and outside the magnet, what fraction of their path do field lines keep closed?",
     ["पूर्ण 100% — संवृत लूप", "50%", "75%", "शून्य %"],
     ["Fully 100% — closed loops", "50%", "75%", "Zero %"],
     0,
     "चुंबकीय बल रेखा कहीं भी आरंभ या विराम नहीं लेती — पूर्ण लूप।",
     "A field line begins and ends nowhere — a complete loop."),

    ("magnetism-and-magnetic-field", "hard",
     "तीन समान छड़ चुंबकों को एक-दूसरे के ऊपर N-S-N-S-N-S श्रृंखला में चिपकाया गया। संयुक्त विन्यास कितने प्रभावी ध्रुव दिखाएगा?",
     "Three identical bar magnets are stuck in a chain N-S N-S N-S. How many effective poles does the combined arrangement show?",
     ["2 — श्रृंखला एक बड़ी द्विध्रुवीय छड़ जैसी", "6", "3", "4"],
     ["2 — the chain acts like one long dipolar bar", "6", "3", "4"],
     0,
     "श्रेणी-श्रृंखला में बीच के ध्रुव आपस में निष्प्रभावी हो जाते हैं — सिरों पर N और S।",
     "In the chain the middle poles neutralise — only end N and end S remain effective."),

    # ================= EARTH'S MAGNETISM (50) =================
    # ---- easy (20) ----
    ("earths-magnetism", "easy",
     "पृथ्वी किस रूप में व्यवहार करती है?",
     "The earth behaves in which form?",
     ["एक विशाल चुंबक के रूप में", "एक विशाल विद्युत सेल के रूप में", "एक विशाल दर्पण के रूप में", "एक विशाल प्रिज़्म के रूप में"],
     ["Like a giant magnet", "Like a giant electric cell", "Like a giant mirror", "Like a giant prism"],
     0,
     "पृथ्वी के चारों ओर चुंबकीय क्षेत्र है — इसीलिए कंपास काम करता है।",
     "The earth has a magnetic field all around — that is why a compass works."),

    ("earths-magnetism", "easy",
     "कंपास (दिक्सूचक) की सुई किसके कारण दिशा बताती है?",
     "Because of what does a compass needle indicate direction?",
     ["पृथ्वी के चुंबकीय क्षेत्र के कारण", "हवा के कारण", "सूर्य के प्रकाश के कारण", "गुरुत्वाकर्षण के कारण"],
     ["Due to the earth's magnetic field", "Due to wind", "Due to sunlight", "Due to gravity"],
     0,
     "सुई पृथ्वी के क्षेत्र रेखाओं के अनुदिश संरेखित हो जाती है।",
     "The needle aligns along the earth's field lines."),

    ("earths-magnetism", "easy",
     "कंपास की सुई प्रायः किस दिशा में रुकती है?",
     "In which direction does a compass needle usually settle?",
     ["लगभग उत्तर-दक्षिण", "पूर्व-पश्चिम", "ऊपर-नीचे", "बेतरतीब"],
     ["Approximately north-south", "East-west", "Up-down", "Randomly"],
     0,
     "पृथ्वी का चुंबकीय अक्ष लगभग भौगोलिक अक्ष के समीप है।",
     "The earth's magnetic axis lies close to its geographic axis."),

    ("earths-magnetism", "easy",
     "नाविक और यात्री प्राचीन काल से किस यंत्र से दिशा जानते आए हैं?",
     "Since ancient times sailors and travellers have found direction using which instrument?",
     ["चुंबकीय कंपास से", "दर्पण से", "थर्मामीटर से", "माइक्रोस्कोप से"],
     ["The magnetic compass", "A mirror", "A thermometer", "A microscope"],
     0,
     "चुंबकीय कंपास ने समुद्री यात्राओं की दिशा निर्धारित की।",
     "The magnetic compass guided sea voyages."),

    ("earths-magnetism", "easy",
     "पृथ्वी के चुंबकीय क्षेत्र का मुख्य लाभ क्या है?",
     "What is the chief benefit of the earth's magnetic field?",
     ["सूर्य से आने वाले आवेशित कणों से रक्षा और दिशा-ज्ञान", "वर्षा कराना", "भोजन पकाना", "रोशनी देना"],
     ["Protection from charged particles of the sun and direction-finding", "Bringing rain", "Cooking food", "Giving light"],
     0,
     "चुंबकीय क्षेत्र सौर कणों को विक्षेपित कर वायुमंडल की रक्षा करता है।",
     "The field deflects solar particles and shields the atmosphere."),

    ("earths-magnetism", "easy",
     "उत्तर दिशा दिखाने वाले कंपास सुई के सिरे को क्या कहते हैं?",
     "What is the tip of a compass needle that points north called?",
     ["उत्तरी ध्रुव (N सिरा)", "दक्षिणी ध्रुव", "निरपेक्ष सिरा", "मध्य सिरा"],
     ["The north pole (N tip)", "The south pole", "The neutral tip", "The middle tip"],
     0,
     "सुई का लाल/चिह्नित सिरा प्रायः उत्तरी ध्रुव होता है।",
     "The red/marked tip is usually the north pole."),

    ("earths-magnetism", "easy",
     "चुंबकीय दिक्पात (magnetic declination) किसे कहते हैं?",
     "What is magnetic declination?",
     ["भौगोलिक अक्ष और चुंबकीय अक्ष के बीच का कोण", "दो चुंबकों के बीच का बल", "कंपास की लंबाई", "पृथ्वी का त्रिज्या-मान"],
     ["The angle between the geographic axis and the magnetic axis", "The force between two magnets", "The length of a compass", "The radius of the earth"],
     0,
     "दोनों अक्ष पूरी तरह समान नहीं — इसी अंतर को दिक्पात कहते हैं।",
     "The two axes are not identical — the difference is declination."),

    ("earths-magnetism", "easy",
     "पृथ्वी का चुंबकीय क्षेत्र किसके समान दूर तक फैला है?",
     "The earth's magnetic field extends around it like what?",
     ["एक विशाल छड़ चुंबक के क्षेत्र के समान", "एक बल्ब की रोशनी के समान", "एक घंटी की ध्वनि के समान", "एक पंखे की हवा के समान"],
     ["Like the field of a giant bar magnet", "Like the light of a bulb", "Like the sound of a bell", "Like a fan's breeze"],
     0,
     "अंतरिक्ष में पृथ्वी का क्षेत्र छड़-चुंबक जैसा विन्यास दर्शाता है।",
     "In space the earth's field shows a bar-magnet-like pattern."),

    ("earths-magnetism", "easy",
     "कंपास की सुई विशेषतः किस ग्रह के प्रभाव में दिशा दर्शाती है?",
     "Under the influence of which planet does a compass needle show direction?",
     ["पृथ्वी", "मंगल", "शुक्र", "बृहस्पति"],
     ["The earth", "Mars", "Venus", "Jupiter"],
     0,
     "दिशा-बल स्थानीय रूप से पृथ्वी के ही क्षेत्र से आता है।",
     "The directional force comes from the local field of the earth itself."),

    ("earths-magnetism", "easy",
     "चुंबकीय उत्तरी ध्रुव किस भौगोलिक स्थान के निकट माना जाता है?",
     "The magnetic north pole of the earth is considered near which geographic place?",
     ["भौगोलिक उत्तरी ध्रुव के निकट", "भौगोलिक दक्षिणी ध्रुव के निकट", "विषुवत रेखा के निकट", "कोलकाता के निकट"],
     ["Near the geographic north pole", "Near the geographic south pole", "Near the equator", "Near Kolkata"],
     0,
     "चुंबकीय ध्रुव भौगोलिक ध्रुवों के निकट (थोड़ा विचलित) स्थित हैं।",
     "The magnetic poles lie near (slightly offset from) the geographic poles."),

    ("earths-magnetism", "easy",
     "पक्षी और कुछ प्राणी लंबी यात्राओं में दिशा कैसे पहचानते हैं ऐसा माना जाता है?",
     "How are birds and some animals believed to find direction on long journeys?",
     ["पृथ्वी के चुंबकीय क्षेत्र को संवेदना से पहचानकर", "चाँद की रोशनी से", "तारों की गिनती से", "हवा की गंध से"],
     ["By sensing the earth's magnetic field", "By moonlight", "By counting stars", "By the smell of air"],
     0,
     "अनेक प्रवासी प्राणियों में चुंबकीय संवेदना के प्रमाण मिले हैं।",
     "Many migratory creatures show evidence of magnetic sense."),

    ("earths-magnetism", "easy",
     "पृथ्वी के चुंबकीय क्षेत्र का कारण मुख्यतः क्या माना जाता है?",
     "What is chiefly believed to cause the earth's magnetic field?",
     ["पृथ्वी के भीतर गले धातु (लोहा-निकल) की धाराएँ जैसी गति", "पृथ्वी की घास", "बादल", "समुद्री लहरें"],
     ["Motions in the molten iron-nickel material inside the earth", "The earth's grass", "Clouds", "Sea waves"],
     0,
     "भीतरी तरल धातु की गति से विद्युत-चुंबकीय प्रभाव बनता है।",
     "Moving molten metal inside produces the electromagnetic effect."),

    ("earths-magnetism", "easy",
     "उत्तर ध्रुव की ओर संकेत करने वाली सुई का उत्तरी सिरा पृथ्वी के चुंबकत्व के किस ध्रुव की ओर आकर्षित होता है?",
     "The north tip of a needle pointing north is attracted towards which magnetic pole of the earth?",
     ["पृथ्वी के चुंबकीय दक्षिणी ध्रुव की ओर (जो भौगोलिक उत्तर के पास है)", "चुंबकीय उत्तरी ध्रुव की ओर", "किसी की ओर नहीं", "दोनों की ओर"],
     ["Towards the earth's magnetic south pole (which lies near geographic north)", "Towards the magnetic north pole", "Towards neither", "Towards both"],
     0,
     "आकर्षण विपरीत ध्रुवों में — सुई का N पृथ्वी के चुंबकीय S की ओर।",
     "Attraction is between unlike poles — the needle's N faces the earth's magnetic S."),

    ("earths-magnetism", "easy",
     "पृथ्वी के चुंबकत्व के कारण समुद्री नेविगेशन किस उपकरण से संभव हुआ?",
     "Navigation at sea became possible due to the earth's magnetism using which device?",
     ["चुंबकीय कंपास", "सोनार", "रडार", "पेरिस्कोप"],
     ["The magnetic compass", "SONAR", "Radar", "Periscope"],
     0,
     "कंपास ने दिशा-ज्ञान से महासागरों की यात्रा सुगम की।",
     "The compass made ocean voyages navigable."),

    ("earths-magnetism", "easy",
     "कंपास को चुंबकीय पदार्थों (जैसे लोहे की छड़) से दूर क्यों रखा जाता है?",
     "Why is a compass kept away from magnetic materials like an iron rod?",
     ["लोहे का क्षेत्र सुई को गलत दिशा में घुमा सकता है", "लोहा कंपास को गर्म करता है", "लोहा काँच तोड़ता है", "कंपास लोहे में घुल जाता है"],
     ["The iron's field can deflect the needle the wrong way", "Iron heats the compass", "Iron breaks the glass", "The compass dissolves into iron"],
     0,
     "बाहरी चुंबकीय पदार्थ पृथ्वी-क्षेत्र पर हावी होकर पाठ्यांक बिगाड़ते हैं।",
     "External magnetic materials override the earth's field and spoil the reading."),

    ("earths-magnetism", "easy",
     "पृथ्वी का चुंबकीय क्षेत्र वायुमंडल की रक्षा किस विकिरण-समूह से करता है?",
     "The earth's field protects the atmosphere from which group of radiations?",
     ["सौर हवा के आवेशित कणों से", "ध्वनि तरंगों से", "रेडियो तरंगों से", "प्रकाश किरणों से"],
     ["From the charged particles of the solar wind", "From sound waves", "From radio waves", "From light rays"],
     0,
     "क्षेत्र आवेशित कणों को विक्षेपित करता है; प्रकाश जैसी विद्युत-उदासीन विकिरण अप्रभावित रहती है।",
     "The field deflects charged particles; neutral radiation like light is unaffected."),

    ("earths-magnetism", "easy",
     "ध्रुवीय ज्योति (aurora) किस कारण उत्पन्न होती है?",
     "What causes the aurora (polar lights)?",
     ["सौर आवेशित कण ऊपरी वायुमंडल से टकराने पर", "वर्षा की बूँदों से", "बादलों की गरज से", "ज्वालामुखी से"],
     ["Solar charged particles striking the upper atmosphere", "Raindrops", "Thunderclouds", "Volcanoes"],
     0,
     "चुंबकीय क्षेत्र कणों को ध्रुवों की ओर मोड़ता है — वहीं चमक बनती है।",
     "The field steers the particles towards the poles — the glow forms there."),

    ("earths-magnetism", "easy",
     "मुक्त रूप से लटकाई गई चुंबकीय सुई किसी स्थान पर क्षैतिज तल में कौन-सी दिशा दर्शाती है?",
     "A freely suspended magnetic needle at a place indicates which direction in the horizontal plane?",
     ["चुंबकीय उत्तर-दक्षिण दिशा", "पूर्व-पश्चिम", "कोई निश्चित दिशा नहीं", "सीधी नीचे"],
     ["The magnetic north-south direction", "East-west", "No definite direction", "Straight down"],
     0,
     "क्षैतिज घूर्णन करने वाली सुई क्षेत्र की क्षैतिज दिशा पकड़ती है।",
     "A horizontally free needle takes the field's horizontal direction."),

    ("earths-magnetism", "easy",
     "उत्तर-दक्षिण दिशा बताने के लिए प्राचीन भारत में किस साधन का उल्लेख मिलता है?",
     "Which device is mentioned in ancient India for finding the north-south direction?",
     ["मत्स्य-यंत्र जैसा चुंबकीय दिक्सूचक", "दर्पण", "सूर्य-घड़ी", "पानी की छलक"],
     ["A fish-shaped magnetic direction-finder", "A mirror", "A sundial", "A water spill"],
     0,
     "समुद्रगुप्त काल के विवरणों में लोहे से बनी 'मत्स्य' दिशा बताती थी।",
     "Accounts from ancient India describe an iron 'fish' that pointed direction."),

    ("earths-magnetism", "easy",
     "यदि कंपास को चुंबकीय उत्तरी ध्रुव के ठीक ऊपर रखा जाए तो सुई का व्यवहार कैसा होगा?",
     "If a compass is placed right above the magnetic north pole, how does the needle behave?",
     ["सुई लगभग ऊध्र्वाधर झुक जाती है", "सुई घूमना बंद कर देती है", "सुई टूट जाती है", "कोई परिवर्तन नहीं"],
     ["The needle dips almost vertically", "The needle stops turning", "The needle breaks", "No change"],
     0,
     "ध्रुव पर क्षेत्र लगभग ऊर्ध्वाधर प्रवेश करता है — सुई झुक जाती है।",
     "At the pole the field enters nearly vertically — the needle dips."),

    # ---- medium (21) ----
    ("earths-magnetism", "medium",
     "पृथ्वी के भौगोलिक उत्तर के पास स्थित चुंबकीय ध्रुव वास्तव में कौन-सा ध्रुव है?",
     "The magnetic pole located near the earth's geographic north is actually which pole?",
     ["चुंबकीय दक्षिणी ध्रुव", "चुंबकीय उत्तरी ध्रुव", "उत्तरी भी और दक्षिणी भी", "कोई ध्रुव नहीं"],
     ["The magnetic south pole", "The magnetic north pole", "Both north and south", "No pole at all"],
     0,
     "सुई का N उसी की ओर खिंचता है, अतः वहाँ पृथ्वी-चुंबक का S ध्रुव है।",
     "The needle's N is drawn there, so the earth-magnet's S pole lies there."),

    ("earths-magnetism", "medium",
     "कंपास सुई और निलंबित छड़ चुंबक दोनों ही उत्तर-दक्षिण क्यों रुकते हैं?",
     "Why do both a compass needle and a suspended bar magnet settle north-south?",
     ["दोनों पृथ्वी के चुंबकीय क्षेत्र में घूर्णी बल अनुभव करते हैं", "दोनों पर हवा चलती है", "दोनों भारी होते हैं", "संयोग से"],
     ["Both experience a turning torque in the earth's magnetic field", "Wind blows on both", "Both are heavy", "By coincidence"],
     0,
     "एक ही कारण — पृथ्वी-क्षेत्र का घूर्णी प्रभाव।",
     "One single cause — the turning effect of the earth's field."),

    ("earths-magnetism", "medium",
     "चुंबकीय दिक्पात के कारण कंपास द्वारा बताई उत्तर और भौगोलिक उत्तर में क्या संबंध है?",
     "Due to magnetic declination, what is the relation between compass north and geographic north?",
     ["दोनों में थोड़ा अंतर (कोण) हो सकता है", "दोनों सदैव बिल्कुल समान होते हैं", "कंपास उत्तर पश्चिम दिखाता है", "भौगोलिक उत्तर बदल जाता है"],
     ["There can be a small angular difference between them", "They are always exactly the same", "The compass shows northwest", "The geographic north changes"],
     0,
     "दो अक्षों के अंतर कोण के कारण विचलन आता है।",
     "The angle between the two axes produces the offset."),

    ("earths-magnetism", "medium",
     "किसी स्थान पर निलंबित चुंबकीय सुई ऊपर की ओर क्षैतिज से कोण बनाती झुकी रहती है। इस झुकाव को क्या कहते हैं?",
     "At a place a suspended magnetic needle rests tilted at an angle to the horizontal. What is this tilt called?",
     ["चुंबकीय नति (dip)", "चुंबकीय दिक्पात", "चुंबकीय विषुवत", "चुंबकीय बल"],
     ["Magnetic dip (inclination)", "Magnetic declination", "Magnetic equator", "Magnetic force"],
     0,
     "क्षेत्र-रेखाएँ सामान्यतः क्षैतिज नहीं होतीं — झुकाव 'नति' कहलाता है।",
     "Field lines are generally not horizontal — the tilt is called dip."),

    ("earths-magnetism", "medium",
     "चुंबकीय विषुवत रेखा पर चुंबकीय नति का मान कितना होता है?",
     "What is the value of magnetic dip at the magnetic equator?",
     ["शून्य — सुई क्षैतिज रहती है", "90 डिग्री", "45 डिग्री", "30 डिग्री"],
     ["Zero — the needle stays horizontal", "90 degrees", "45 degrees", "30 degrees"],
     0,
     "विषुवत पर क्षेत्र रेखाएँ क्षैतिज होती हैं।",
     "At the equator the field lines are horizontal."),

    ("earths-magnetism", "medium",
     "चुंबकीय ध्रुवों पर नति का मान कितना होता है?",
     "What is the value of dip at the magnetic poles?",
     ["90 डिग्री — सुई ऊर्ध्वाधर", "शून्य", "45 डिग्री", "60 डिग्री"],
     ["90 degrees — the needle stands vertical", "Zero", "45 degrees", "60 degrees"],
     0,
     "ध्रुव पर क्षेत्र-रेखाएँ ऊर्ध्वाधर प्रवेश करती हैं।",
     "At the poles the field lines enter vertically."),

    ("earths-magnetism", "medium",
     "कथन: चुंबकीय उत्तरी ध्रुव भौगोलिक उत्तरी ध्रुव के ठीक बिंदु पर स्थित है। यह कथन —",
     "Statement: the magnetic north pole lies exactly at the geographic north pole. This statement is —",
     ["गलत — दोनों में कुछ अंतर होता है", "सही", "आंशिक सही नहीं — पूर्ण सही", "प्रमाणित नहीं किया जा सकता"],
     ["False — there is some difference between the two", "True", "Not partly true — fully true", "It cannot be verified"],
     0,
     "दोनों अक्ष संपाती नहीं — इसी से दिक्पात परिभाषित होता है।",
     "The axes do not coincide — that defines declination."),

    ("earths-magnetism", "medium",
     "भूचुंबकत्व के कारण कौन-सा उद्योग संभव हुआ?",
     "Which industry became possible due to geomagnetism?",
     ["समुद्री नेविगेशन और मानचित्रण", "कपड़ा बुनाई", "चीनी निर्माण", "मिट्टी के बर्तन"],
     ["Sea navigation and mapping", "Textile weaving", "Sugar manufacture", "Pottery"],
     0,
     "कंपास के बिना विश्व-व्यापार मार्ग संभव नहीं थे।",
     "Without the compass, world trade routes were impossible."),

    ("earths-magnetism", "medium",
     "कंपास सुई और लोहे की पट्टी एक साथ रखी हैं। कंपास का पाठ्यांक कैसा होगा?",
     "A compass needle and an iron strip are placed together. How will the compass reading be?",
     ["प्रभावित हो सकता है — पट्टी क्षेत्र में विक्षेप आ सकता है", "पूर्णतः सही रहेगा", "सुई उलट जाएगी", "कंपास खराब हो जाएगा"],
     ["It may be affected — the strip can deflect the needle", "It will stay perfectly correct", "The needle reverses", "The compass breaks"],
     0,
     "निकट लोहा स्थानीय क्षेत्र बदलता है — पाठ्यांक अशुद्ध।",
     "Nearby iron alters the local field — the reading turns faulty."),

    ("earths-magnetism", "medium",
     "पृथ्वी के चुंबकीय क्षेत्र की तुलना किस रूप में की जाती है?",
     "The earth's magnetic field is compared to which form?",
     ["केंद्र में छड़ चुंबक वाले गोले के क्षेत्र के रूप में", "बिजली के तार के क्षेत्र के रूप में", "बल्ब के प्रकाश के रूप में", "पंखे की हवा के रूप में"],
     ["To the field of a sphere with a bar magnet at its centre", "To the field of a power line", "To a bulb's light", "To a fan's air"],
     0,
     "गोलीय पृथ्वी के क्षेत्र का मॉडल केंद्रीय छड़-चुंबक है।",
     "The model of the spherical earth's field is a central bar magnet."),

    ("earths-magnetism", "medium",
     "मानव शरीर में लगी शल्य-चुंबक क्या दर्शाता है?",
     "What does a surgical magnet implanted in the human body demonstrate?",
     ["जीव-शरीर भी हल्का चुंबकीय अनुक्रिया दर्शाते हैं — अनुप्रयोग की विविधता", "शरीर में बिजली भरी है", "चुंबक शरीर को उड़ाता है", "शरीर रोधी नहीं है"],
     ["Living bodies also show mild magnetic response — variety of applications", "The body is full of electricity", "The magnet flies the body", "The body is not an insulator"],
     0,
     "चुंबकत्व के चिकित्सा-अनुप्रयोग भी स्कूली ज्ञान का भाग हैं।",
     "Medical applications of magnetism are part of school knowledge too."),

    ("earths-magnetism", "medium",
     "समुद्री मानचित्रों में चुंबकीय दिक्पात का उल्लेख क्यों किया जाता है?",
     "Why is magnetic declination mentioned on nautical charts?",
     ["ताकि नाविक कंपास के पाठ्यांक को सही भौगोलिक दिशा में बदल सकें", "जहाज़ का रंग बताने के लिए", "समुद्र की गहराई बताने के लिए", "मौसम बताने के लिए"],
     ["So that sailors can convert compass readings into true geographic directions", "To show the ship's colour", "To show the sea's depth", "To show the weather"],
     0,
     "दिक्पात का ज्ञान कंपास-उत्तर को वास्तविक उत्तर में बदलने के लिए आवश्यक है।",
     "Knowing the declination is needed to convert compass north into true north."),

    ("earths-magnetism", "medium",
     "पृथ्वी के चुंबकीय क्षेत्र में रखे निलंबित चुंबक का उत्तरी सिरा अचर रूप से किस ओर स्थिर होता है?",
     "In the earth's field, towards which side does the north end of a suspended magnet settle consistently?",
     ["चुंबकीय उत्तर की ओर (लगभग भौगोलिक उत्तर)", "चुंबकीय दक्षिण की ओर", "पूर्व की ओर", "नीचे की ओर केवल"],
     ["Towards magnetic north (roughly geographic north)", "Towards magnetic south", "Towards east", "Only downwards"],
     0,
     "पृथ्वी-चुंबक का S (भौगोलिक उत्तर के पास) सुई के N को खींचता है।",
     "The earth-magnet's S (near geographic north) draws the needle's N."),

    ("earths-magnetism", "medium",
     "दो स्थानों A (विषुवत के पास) और B (ध्रुव के पास) में कंपास सुई की स्थिति में क्या अंतर होगा?",
     "What is the difference in the compass needle's position between place A (near the equator) and place B (near the pole)?",
     ["A पर लगभग क्षैतिज; B पर अधिक झुकी (नति अधिक)", "दोनों पर ऊर्ध्वाधर", "A पर झुकी; B पर क्षैतिज", "दोनों पर समान क्षैतिज"],
     ["Nearly horizontal at A; more tilted at B (greater dip)", "Vertical at both", "Tilted at A; horizontal at B", "Equally horizontal at both"],
     0,
     "नति विषुवत से ध्रुव तक बढ़ती है — 0° से 90°।",
     "Dip increases from equator to pole — 0° to 90°."),

    ("earths-magnetism", "medium",
     "चुंबकीय कंपास के आविष्कार से पूर्व नाविक किस साधन से दिशा जानते थे?",
     "Before the magnetic compass, what aids did sailors use for direction?",
     ["तारों और सूर्य की स्थिति से", "कंपास से ही", "रडार से", "GPS से"],
     ["The positions of stars and the sun", "The compass itself", "Radar", "GPS"],
     0,
     "खगोलीय संदर्भ सीमित थे — कंपास ने दिशा-ज्ञान क्रांतिकारी बनाया।",
     "Celestial references were limited — the compass revolutionised navigation."),

    ("earths-magnetism", "medium",
     "पृथ्वी के चुंबकीय क्षेत्र को 'ढाल' कहा जाता है क्योंकि —",
     "The earth's magnetic field is called a 'shield' because —",
     ["यह आवेशित सौर कणों को विक्षेपित कर वायुमंडल की रक्षा करता है", "यह वर्षा रोकता है", "यह भूकंप रोकता है", "यह ठंडी हवा रोकता है"],
     ["It deflects charged solar particles, protecting the atmosphere", "It stops rain", "It stops earthquakes", "It blocks cold winds"],
     0,
     "क्षेत्र का विक्षेपण-कार्य ढाल जैसा ही है।",
     "The field's deflecting action works like a shield."),

    ("earths-magnetism", "medium",
     "चंद्रमा पर कंपास काम नहीं करता। सबसे संभावित कारण क्या है?",
     "A compass does not work on the moon. What is the most likely reason?",
     ["चंद्रमा का अपना चुंबकीय क्षेत्र लगभग नहीं के बराबर है", "चंद्रमा पर हवा नहीं", "चंद्रमा दूर है", "चंद्रमा ठंडा है"],
     ["The moon has almost no magnetic field of its own", "There is no air on the moon", "The moon is far away", "The moon is cold"],
     0,
     "सुई को दिशा देने वाला स्थानीय क्षेत्र ही वहाँ अनुपस्थित है।",
     "The local field that would steer the needle simply is absent there."),

    ("earths-magnetism", "medium",
     "चुंबकीय क्षेत्र में स्थित असंख्य बिंदुओं पर कंपास दिशा दर्शाते रखें तो क्या प्राप्त होता है?",
     "If compasses are placed at numerous points in a magnetic field, what is obtained?",
     ["क्षेत्र-रेखाओं का पूरा चित्र", "विद्युत धारा", "ऊष्मा मानचित्र", "दाब मानचित्र"],
     ["A complete picture of the field lines", "An electric current", "A heat map", "A pressure map"],
     0,
     "बिंदु-दर-बिंदु दिशाओं को मिलाने से बल-रेखा विन्यास उभरता है।",
     "Joining point-by-point directions brings out the field-line pattern."),

    ("earths-magnetism", "medium",
     "भौगोलिक अक्ष और चुंबकीय अक्ष के बीच कोण किसका कारण है?",
     "The angle between the geographic axis and the magnetic axis is the reason for what?",
     ["चुंबकीय दिक्पात का", "नति का", "गुरुत्व का", "दिन-रात का"],
     ["Magnetic declination", "Dip", "Gravity", "Day and night"],
     0,
     "दिक्पात उसी कोण से परिभाषित है।",
     "Declination is defined by that very angle."),

    ("earths-magnetism", "medium",
     "पृथ्वी-चुंबक के कारण ऊपरी वायुमंडल में आयनित गैस और प्रकाश की परत ध्रुवों पर दिखती है। इसका नाम क्या है?",
     "Due to the earth-magnet, glowing ionised layers appear near the poles in the upper atmosphere. What are they called?",
     ["ऑरोरा (ध्रुवीय ज्योति)", "इंद्रधनुष", "ओजोन छिद्र", "वायुमंडलीय दाब"],
     ["Auroras (polar lights)", "Rainbows", "Ozone hole", "Atmospheric pressure"],
     0,
     "ध्रुवीय ज्योति चुंबकीय क्षेत्र-कण अंतःक्रिया का दृश्य परिणाम है।",
     "Auroras are the visible result of field-particle interaction."),

    ("earths-magnetism", "medium",
     "यदि किसी ग्रह का प्रबल चुंबकीय क्षेत्र हो तो उसके वायुमंडल की स्थिति कैसी रहती है?",
     "If a planet has a strong magnetic field, what is the state of its atmosphere?",
     ["सौर कणों से बेहतर सुरक्षित रहता है", "तुरंत समाप्त हो जाता है", "गर्म हो जाता है", "ठंडा हो जाता है"],
     ["Better protected from solar particles", "It vanishes immediately", "It heats up", "It cools down"],
     0,
     "प्रबल क्षेत्र अपक्षय (erosion) को घटाता है।",
     "A strong field reduces atmospheric erosion."),

    # ---- hard (9) ----
    ("earths-magnetism", "hard",
     "चुंबकीय दक्षिणी ध्रुव भौगोलिक उत्तर के निकट है — इस कथन की पुष्टि कंपास के किस व्यवहार से होती है?",
     "The magnetic south pole lies near geographic north — which compass behaviour confirms this statement?",
     ["सुई का उत्तरी सिरा उत्तर की ओर अभिविन्यस्त रहता है (विपरीत ध्रुव आकर्षण)", "सुई घूमती नहीं", "सुई दक्षिण दिखाती है", "सुई ऊपर उठती है"],
     ["The needle's north tip stays aligned north (unlike-pole attraction)", "The needle does not turn", "The needle points south", "The needle rises up"],
     0,
     "सुई का N उत्तर की ओर ही रहेगा यदि वहाँ पृथ्वी का S हो।",
     "The needle's N can face north only if the earth's S lies there."),

    ("earths-magnetism", "hard",
     "एक निलंबित छड़ चुंबक के नीचे लोहे की बड़ी प्लेट लाई गई। छड़ के विश्राम विन्यास पर क्या प्रभाव पड़ेगा?",
     "A large iron plate is brought beneath a suspended bar magnet. What happens to the magnet's resting orientation?",
     ["लोहे के आकर्षण से विन्यास बिगड़ सकता है — पाठ्यांक अविश्वसनीय", "कोई प्रभाव नहीं", "छड़ और अधिक सटीक N-S दिखाएगी", "छड़ ऊपर उड़ जाएगी"],
     ["The iron's attraction can disturb the orientation — the reading turns unreliable", "No effect", "The magnet shows N-S more accurately", "The magnet flies up"],
     0,
     "स्थानीय चुंबकीय पदार्थ भू-क्षेत्र पर हावी हो जाते हैं।",
     "Local magnetic material overpowers the earth's field."),

    ("earths-magnetism", "hard",
     "कंपास सुई को विद्युत तारों के पास रखने पर विचलन क्यों होता है?",
     "Why does a compass needle deflect when placed near electric wires?",
     ["धारावाही तार के चारों ओर चुंबकीय क्षेत्र बनता है", "तार गर्म होता है", "तार हवा बनाता है", "तार प्रकाश छोड़ता है"],
     ["A magnetic field forms around the current-carrying wire", "The wire heats up", "The wire creates air currents", "The wire emits light"],
     0,
     "धारा का चुंबकीय प्रभाव — कंपास उसका संवेदक है।",
     "The magnetic effect of current — the compass detects it."),

    ("earths-magnetism", "hard",
     "मंगल ग्रह पर कंपास का उपयोग करना अविश्वसनीय क्यों माना जाता है?",
     "Why is using a compass on Mars considered unreliable?",
     ["वहाँ का चुंबकीय क्षेत्र बहुत कमज़ोर और अनियमित है", "मंगल पर हवा नहीं", "मंगल लाल है", "वहाँ रात होती है"],
     ["Its magnetic field is very weak and irregular", "There is no air on Mars", "Mars is red", "Night occurs there"],
     0,
     "दिशा-संकेत के लिए क्षेत्र नियमित और पर्याप्त प्रबल होना चाहिए।",
     "For direction-finding the field must be regular and strong enough."),

    ("earths-magnetism", "hard",
     "चुंबकीय नति (dip) को मापने वाले यंत्र को क्या कहते हैं?",
     "What is the instrument that measures magnetic dip called?",
     ["नतिमापी (dip circle/needle)", "गैल्वेनोमीटर", "एमीटर", "बैरोमीटर"],
     ["Dip circle (dip needle)", "Galvanometer", "Ammeter", "Barometer"],
     0,
     "नतिमापी सुई ऊर्ध्वाधर तल में घूमकर नति बताती है।",
     "A dip needle rotates in the vertical plane to show dip."),

    ("earths-magnetism", "hard",
     "यदि पृथ्वी का चुंबकीय क्षेत्र उलट जाए तो कंपास सुइयों का क्या होगा?",
     "If the earth's magnetic field reversed, what would happen to compass needles?",
     ["सुइयाँ उलट दिशा दिखाने लगेंगी", "सुइयाँ काम करना बंद कर देंगी", "सुइयाँ पिघल जाएँगी", "कुछ नहीं होगा"],
     ["The needles would indicate reversed directions", "The needles would stop working", "The needles would melt", "Nothing would happen"],
     0,
     "भूवैज्ञानिक इतिहास में ध्रुव-पलट घटित हुए हैं — सुई नए क्षेत्र के अनुसार मुड़ेगी।",
     "Pole reversals have occurred in geological history — needles would follow the new field."),

    ("earths-magnetism", "hard",
     "दो स्थानों के बीच चुंबकीय क्षेत्र की तीव्रता — विषुवत बनाम ध्रुव — कहाँ अधिक होती है?",
     "Between two places — equator versus pole — where is the magnetic field stronger?",
     ["सामान्यतः ध्रुवों के पास अधिक", "विषुवत पर अधिक", "समान", "कहीं नहीं"],
     ["Usually stronger near the poles", "Stronger at the equator", "Equal", "Nowhere"],
     0,
     "ध्रुवों पर रेखाएँ अभिसृत होती हैं — क्षेत्र सघन।",
     "Field lines converge at the poles — the field is concentrated."),

    ("earths-magnetism", "hard",
     "पृथ्वी के चुंबकीय क्षेत्र के बिना सौर विकिरण के आवेशित कणों का जीवन पर क्या प्रभाव पड़ता?",
     "Without the earth's magnetic field, what would be the impact of charged solar particles on life?",
     ["कण सीधे वायुमंडल-जीवन पर प्रहार करते — अनेक खतरे", "कोई प्रभाव नहीं", "जीवन खत्म हो जाता", "प्रकाश बढ़ जाता"],
     ["The particles would strike the atmosphere and life directly — many hazards", "No effect", "Life would end completely", "Light would increase"],
     0,
     "क्षेत्र की ढाल-भूमिका जीवन के अस्तित्व की दृष्टि से महत्वपूर्ण मानी जाती है।",
     "The field's shield role is considered vital for life's survival."),

    ("earths-magnetism", "hard",
     "एक अंतरिक्ष यान में यात्री कंपास से दिशा नहीं ले सकते जब वे पृथ्वी से बहुत दूर हों। कारण बताइए।",
     "Travellers in a spacecraft cannot use a compass for direction when far from the earth. State the reason.",
     ["पृथ्वी का क्षेत्र वहाँ अत्यंत दुर्बल हो जाता है", "अंतरिक्ष में दिशाएँ होती ही नहीं", "कंपास को हवा चाहिए", "कंपास को पानी चाहिए"],
     ["The earth's field becomes extremely weak there", "There are no directions in space", "A compass needs air", "A compass needs water"],
     0,
     "दूरी के साथ क्षेत्र तीव्रता घटती जाती है — सुई कोई निश्चित दिशा नहीं पकड़ पाती।",
     "Field strength falls with distance — the needle finds no firm direction."),
]
