# -*- coding: utf-8 -*-
"""P10 (Magnetism & Electromagnetic Effects) — Part 2: electromagnet (50) + motor-generator-effect (50) = 100 tuples.
All items authored with correct_idx=0; rotation happens in gen_p10_questions.py.

T3 electromagnet            50 = E20/M21/H9
T4 motor-generator-effect   50 = E20/M22/H8
"""

PART2 = [
    # ================= ELECTROMAGNET (50) =================
    # ---- easy (20) ----
    ("electromagnet", "easy",
     "विद्युत-चुंबक किसे कहते हैं?",
     "What is an electromagnet?",
     ["धारावाही कुंडली में नर्म लोहे की छड़ डालकर बनाया गया अस्थायी चुंबक", "स्थायी स्टील चुंबक", "बिना धारा का चुंबक", "प्राकृतिक चुंबक"],
     ["A temporary magnet made by placing a soft iron rod inside a current-carrying coil", "A permanent steel magnet", "A magnet needing no current", "A natural magnet"],
     0,
     "धारा चालू तो चुंबकत्व, धारा बंद तो चुंबकत्व समाप्त।",
     "Current on — magnetism on; current off — magnetism gone."),

    ("electromagnet", "easy",
     "विद्युत-चुंबक बनाने के लिए कुंडली के भीतर कौन-सी छड़ रखी जाती है?",
     "Which rod is placed inside the coil to make an electromagnet?",
     ["नर्म लोहे की", "ताँबे की", "लकड़ी की", "प्लास्टिक की"],
     ["Soft iron", "Copper", "Wood", "Plastic"],
     0,
     "नर्म लोहा प्रबल चुंबकत्व तुरंत ग्रहण और त्याग करता है।",
     "Soft iron picks up and drops strong magnetism instantly."),

    ("electromagnet", "easy",
     "विद्युत-चुंबक का चुंबकत्व कब तक बना रहता है?",
     "How long does an electromagnet keep its magnetism?",
     ["जब तक कुंडली में धारा बहती है (अस्थायी चुंबक)", "सदा के लिए", "धारा बंद होने पर भी अनंत काल तक", "कभी नहीं"],
     ["Only while current flows in the coil (a temporary magnet)", "Forever", "Infinitely long even after the current stops", "Never"],
     0,
     "धारा बंद होते ही नर्म लोहा निष्चुंबकित हो जाता है।",
     "As soon as the current stops, the soft iron demagnetises."),

    ("electromagnet", "easy",
     "विद्युत-चुंबक का चुंबकत्व किस बटन से नियंत्रित होता है?",
     "The magnetism of an electromagnet is controlled by what?",
     ["धारा के चालू-बंद स्विच से", "चुंबक के रंग से", "मौसम से", "कमरे की रोशनी से"],
     ["By the switch that turns the current on or off", "By the magnet's colour", "By the weather", "By the room's lighting"],
     0,
     "स्विच से चुंबकत्व को तुरंत पाया या समाप्त किया जा सकता है।",
     "The switch can create or remove the magnetism instantly."),

    ("electromagnet", "easy",
     "धारावाही तार के चारों ओर क्या उत्पन्न होता है?",
     "What is produced around a current-carrying wire?",
     ["चुंबकीय क्षेत्र", "गुरुत्वीय क्षेत्र", "प्रकाशीय क्षेत्र", "ध्वनि क्षेत्र"],
     ["A magnetic field", "A gravitational field", "An optical field", "A sound field"],
     0,
     "धारा का चुंबकीय प्रभाव — ओरस्टेड के प्रयोग की खोज।",
     "The magnetic effect of current — Oersted's discovery."),

    ("electromagnet", "easy",
     "धारावाही तार के पास कंपास सुई विचलित हो जाती है। इसकी खोज किसने की?",
     "Who discovered that a compass needle deflects near a current-carrying wire?",
     ["ओरस्टेड (Oersted)", "न्यूटन", "गैलीलियो", "डार्विन"],
     ["Oersted", "Newton", "Galileo", "Darwin"],
     0,
     "1820 में ओरस्टेड ने धारा-चुंबकत्व संबंध का प्रयोग दिखाया।",
     "In 1820 Oersted demonstrated the current-magnetism connection."),

    ("electromagnet", "easy",
     "सोलेनोइड (कुंडली) के भीतर चुंबकीय क्षेत्र कैसा होता है?",
     "What is the magnetic field like inside a solenoid?",
     ["लगभग एकसमान (समांतर रेखाएँ)", "शून्य", "बेतरतीब", "वृत्ताकार घूर्णन"],
     ["Nearly uniform (parallel lines)", "Zero", "Random", "Circular whirls"],
     0,
     "कुंडली के भीतर रेखाएँ समानांतर होती हैं — छड़ चुंबक जैसा व्यवहार।",
     "Inside the coil the lines run parallel — it behaves like a bar magnet."),

    ("electromagnet", "easy",
     "धारावाही सोलेनोइड किसके समान व्यवहार करता है?",
     "A current-carrying solenoid behaves like what?",
     ["छड़ चुंबक", "बल्ब", "सेल", "प्रतिरोध"],
     ["A bar magnet", "A bulb", "A cell", "A resistor"],
     0,
     "सोलेनोइड के सिरों पर N और S जैसे ध्रुव बन जाते हैं।",
     "The solenoid's ends develop N- and S-like poles."),

    ("electromagnet", "easy",
     "विद्युत-चुंबक की शक्ति बढ़ाने का एक उपाय क्या है?",
     "What is one way to increase the strength of an electromagnet?",
     ["कुंडली के फेरों की संख्या बढ़ाना", "फेरे घटाना", "लोहे की छड़ हटाना", "तार पतला करना"],
     ["Increasing the number of turns in the coil", "Reducing the turns", "Removing the iron core", "Making the wire thinner"],
     0,
     "अधिक फेरे — अधिक क्षेत्र-योगदान — प्रबल चुंबक।",
     "More turns — more field contribution — a stronger magnet."),

    ("electromagnet", "easy",
     "विद्युत-चुंबक की शक्ति बढ़ाने के लिए धारा का क्या करना चाहिए?",
     "What should be done to the current to strengthen an electromagnet?",
     ["धारा बढ़ानी चाहिए", "धारा घटानी चाहिए", "धारा बंद करनी चाहिए", "धारा उलटनी चाहिए"],
     ["The current should be increased", "The current should be decreased", "The current should be switched off", "The current should be reversed"],
     0,
     "धारा बढ़ने पर क्षेत्र प्रबल होता है।",
     "A larger current makes a stronger field."),

    ("electromagnet", "easy",
     "कचरा-पृथक्करण कार्यों में विद्युत-चुंबक का उपयोग कैसे होता है?",
     "How is an electromagnet used in waste-separation work?",
     ["लोहे के टुकड़े चुंबक से उठाकर अलग किए जाते हैं", "कागज़ जलाया जाता है", "प्लास्टिक पिघलाया जाता है", "काँच तोड़ा जाता है"],
     ["Iron pieces are lifted away with the magnet", "Paper is burnt", "Plastic is melted", "Glass is broken"],
     0,
     "क्रेन वाला विद्युत-चुंबक लोहा उठाता और छोड़ता है — अस्थायी चुंबकत्व का लाभ।",
     "A crane electromagnet lifts and releases iron — the benefit of temporary magnetism."),

    ("electromagnet", "easy",
     "विद्युत घंटी (electric bell) में कौन-सा घटक घंटी बजाता है?",
     "Which component makes an electric bell ring?",
     ["विद्युत-चुंबक से चुंबकित होकर घर्षित हथौड़ा", "पंखा", "हीटर", "रेडियो"],
     ["A hammer magnetised by the electromagnet striking the gong", "A fan", "A heater", "A radio"],
     0,
     "विद्युत-चुंबक हथौड़े को खींचता है; संपर्क टूटते ही वापस — बार-बार ध्वनि।",
     "The electromagnet pulls the hammer; breaking contact sends it back — repeated ringing."),

    ("electromagnet", "easy",
     "रिले (relay) क्या है?",
     "What is a relay?",
     ["विद्युत-चुंबक से चलने वाला स्विच जो कमज़ोर संकेत से बड़ा परिपथ चालू करता है", "एक प्रकार का मोटर", "ऊर्जा का मात्रक", "प्रकाश का स्रोत"],
     ["An electromagnetic switch that turns a large circuit on with a weak signal", "A type of motor", "A unit of energy", "A source of light"],
     0,
     "रिले छोटे संकेत से भारी धारा वाले परिपथ को सुरक्षित चालू करता है।",
     "A relay safely switches a heavy-current circuit using a small signal."),

    ("electromagnet", "easy",
     "धारावाही तार के चारों ओर बनने वाली क्षेत्र रेखाओं का आकार कैसा होता है?",
     "What is the shape of field lines around a straight current-carrying wire?",
     ["संकेंद्र वृत्त", "सीधी रेखाएँ", "परवलय", "बिखरे बिंदु"],
     ["Concentric circles", "Straight lines", "Parabolas", "Scattered dots"],
     0,
     "तार के चारों ओर क्षेत्र वृत्ताकार लूपों में होता है।",
     "Around the wire the field forms circular loops."),

    ("electromagnet", "easy",
     "तार में धारा की दिशा उलट देने पर चुंबकीय क्षेत्र का क्या होता है?",
     "What happens to the magnetic field if the current direction in the wire is reversed?",
     ["क्षेत्र की दिशा उलट जाती है", "क्षेत्र समाप्त हो जाता है", "क्षेत्र दुगुना हो जाता है", "कोई परिवर्तन नहीं"],
     ["The field direction reverses", "The field vanishes", "The field doubles", "No change"],
     0,
     "क्षेत्र की दिशा धारा की दिशा पर निर्भर करती है।",
     "The field direction depends on the current direction."),

    ("electromagnet", "easy",
     "विद्युत-चुंबक की ध्रुवता बदलने के लिए क्या करते हैं?",
     "What is done to change the polarity of an electromagnet?",
     ["धारा की दिशा उलट दी जाती है", "धारा बंद की जाती है", "फेरे गिने जाते हैं", "छड़ लंबी की जाती है"],
     ["The direction of the current is reversed", "The current is switched off", "The turns are counted", "The rod is lengthened"],
     0,
     "धारा-दिशा पलटने से कुंडली के N और S बदल जाते हैं।",
     "Reversing the current swaps the coil's N and S."),

    ("electromagnet", "easy",
     "ओरस्टेड के प्रयोग ने विद्युत और किसके बीच संबंध स्थापित किया?",
     "Oersted's experiment established the connection between electricity and what?",
     ["चुंबकत्व", "प्रकाश", "ध्वनि", "ऊष्मा"],
     ["Magnetism", "Light", "Sound", "Heat"],
     0,
     "धारा का चुंबकीय प्रभाव दोनों क्षेत्रों को जोड़ता है।",
     "The magnetic effect of current links the two domains."),

    ("electromagnet", "easy",
     "उद्योगों में भारी लोहा उठाने वाले क्रेन में कौन-सा चुंबक होता है?",
     "Which magnet is used in industrial cranes that lift heavy iron?",
     ["विद्युत-चुंबक", "अचुंबकीय पट्टिका", "रबर चुंबक पट्टिका नहीं — प्लास्टिक", "प्राकृतिक चुंबक"],
     ["An electromagnet", "A non-magnetic plate", "A plastic plate", "A natural magnet"],
     0,
     "धारा बंद कर ही सामान छोड़ा जा सकता है — यही विद्युत-चुंबक की विशेषता।",
     "Switching off releases the load — the electromagnet's speciality."),

    ("electromagnet", "easy",
     "विद्युत-चुंबक की तुलना में स्थायी चुंबक की कमी क्या है?",
     "What is a drawback of a permanent magnet compared to an electromagnet?",
     ["उसकी शक्ति को आवश्यकतानुसार बंद करना कठिन", "वह लोहा नहीं खींचता", "वह टिकता नहीं", "वह महँगा नहीं होता"],
     ["Its strength cannot be switched off at will", "It does not attract iron", "It does not last", "It is not costly"],
     0,
     "नियंत्रण की स्वतंत्रता ही विद्युत-चुंबक का बड़ा लाभ है।",
     "Freedom of control is the electromagnet's big advantage."),

    ("electromagnet", "easy",
     "टेलीफोन डायाफ्राम (स्पीकर) में ध्वनि किस प्रभाव से उत्पन्न होती है?",
     "In a telephone diaphragm (speaker), sound is produced by which effect?",
     ["विद्युत-चुंबकीय आकर्षण-प्रतिकर्षण से कंपन", "गुरुत्व से", "घर्षण से", "ऊष्मा से"],
     ["Vibrations from electromagnetic attraction-repulsion", "Gravity", "Friction", "Heat"],
     0,
     "बदलती धारा विद्युत-चुंबक को कंपित करती है — ध्वनि तरंगें बनती हैं।",
     "A varying current vibrates the electromagnet — sound waves result."),

    # ---- medium (21) ----
    ("electromagnet", "medium",
     "विद्युत-चुंबक में नर्म लोहा ही क्यों चुना जाता है, स्टील क्यों नहीं?",
     "Why is soft iron, not steel, chosen for an electromagnet?",
     ["नर्म लोहा धारा बंद होते ही चुंबकत्व छोड़ देता है, स्टील नहीं छोड़ता", "नर्म लोहा सस्ता होता है", "स्टील भारी होता है", "नर्म लोहा चमकता है"],
     ["Soft iron sheds magnetism the moment the current stops; steel does not", "Soft iron is cheaper", "Steel is heavy", "Soft iron shines"],
     0,
     "अस्थायी चुंबकत्व के लिए त्वरित निष्चुंबकन आवश्यक है।",
     "Temporary magnetism demands quick demagnetisation."),

    ("electromagnet", "medium",
     "एक विद्युत-चुंबक की कुंडली में 100 फेरे हैं। फेरे बढ़ाकर 300 करने पर चुंबकत्व कैसा होगा?",
     "An electromagnet's coil has 100 turns. What happens to its magnetism if the turns are raised to 300?",
     ["लगभग तीन गुना प्रबल (उसी धारा पर)", "एक-तिहाई रह जाएगा", "समान रहेगा", "समाप्त हो जाएगा"],
     ["About three times stronger (at the same current)", "It falls to one-third", "It stays the same", "It vanishes"],
     0,
     "क्षेत्र फेरों के अनुक्रमानुपाती — 300/100 = 3 गुना।",
     "The field scales with turns — 300/100 = 3 times."),

    ("electromagnet", "medium",
     "उसी कुंडली में धारा दुगुनी करने पर विद्युत-चुंबक की शक्ति का क्या होगा?",
     "What happens to an electromagnet's strength if the current is doubled in the same coil?",
     ["बढ़ जाती है (लगभग दुगुनी)", "आधी रह जाती है", "समान रहती है", "शून्य हो जाती है"],
     ["It increases (nearly doubles)", "It halves", "It remains the same", "It becomes zero"],
     0,
     "धारा बढ़ने पर क्षेत्र तीव्रता बढ़ती है।",
     "Raising the current raises the field intensity."),

    ("electromagnet", "medium",
     "विद्युत-चुंबक के दो फायदे गिनाइए।",
     "List two advantages of an electromagnet.",
     ["शक्ति इच्छानुसार नियंत्रित; चालू-बंद संभव", "सदैव चुंबक रहता है; रखरखाव नहीं", "सस्ता; रंगीन", "हल्का; पारदर्शी"],
     ["Strength controlled at will; can be switched on/off", "Always magnetic; no maintenance", "Cheap; colourful", "Light; transparent"],
     0,
     "नियंत्रण योग्यता और अस्थायीपन — दो मुख्य लाभ।",
     "Controllability and temporariness — the two main benefits."),

    ("electromagnet", "medium",
     "सोलेनोइड में लोहे की छड़ डालने पर क्षेत्र क्यों प्रबल हो जाता है?",
     "Why does the field become stronger when an iron rod is inserted in a solenoid?",
     ["लोहा स्वयं चुंबकित होकर कुंडली के क्षेत्र में योगदान जोड़ता है", "लोहा धारा बढ़ाता है", "लोहा प्रतिरोध घटाता है", "लोहा ऊष्मा देता है"],
     ["The iron magnetises and adds its own contribution to the coil's field", "Iron increases the current", "Iron lowers the resistance", "Iron supplies heat"],
     0,
     "कुंडली-क्षेत्र + प्रेरित लोहे-क्षेत्र = कुल प्रबल क्षेत्र।",
     "Coil field + induced iron field = a much stronger total field."),

    ("electromagnet", "medium",
     "विद्युत घंटी में हथौड़ा बार-बार किस प्रक्रिया से घंटी से टकराता है?",
     "In an electric bell, by what process does the hammer strike the gong repeatedly?",
     ["विद्युत-चुंबक चालू-बंद होते रहने से हथौड़े का आगे-पीछे दोलन", "मोटर के घूमने से", "पंखे की हवा से", "गुरुत्व के बदलने से"],
     ["Rapid to-and-fro oscillation of the hammer as the electromagnet switches on and off", "A rotating motor", "A fan's breeze", "Changing gravity"],
     0,
     "संपर्क टूटता-जुड़ता रहता है — हथौड़ा दोलन करता है।",
     "The contact breaks and remakes — the hammer oscillates."),

    ("electromagnet", "medium",
     "चिकित्सा में चुंबकीय अनुनाद (MRI) परीक्षण किस पर आधारित है — स्कूली स्तर पर सर्वाधिक उपयुक्त उत्तर चुनिए?",
     "On what is the medical MRI test based — choose the most school-appropriate option?",
     ["प्रबल चुंबकीय क्षेत्र और शरीर के भीतर उसकी अनुक्रिया", "क्ष-किरण छायांकन", "ध्वनि की प्रतिध्वनि", "रासायनिक विरंजन"],
     ["A strong magnetic field and the body's response to it", "X-ray imaging", "Echoes of sound", "Chemical bleaching"],
     0,
     "शरीर-ऊतक चुंबकीय क्षेत्र में संकेत देते हैं — चुंबकत्व का चिकित्सा-अनुप्रयोग।",
     "Body tissues signal in a magnetic field — a medical use of magnetism."),

    ("electromagnet", "medium",
     "धारावाही तार के चारों ओर क्षेत्र की दिशा ज्ञात करने का सरल नियम कौन-सा है?",
     "Which simple rule gives the direction of the field around a current-carrying wire?",
     ["दाहिने हाथ के अंगूठे का नियम", "फ्लेमिंग का वाम हस्त नियम", "लेंज़ का नियम", "पास्कल का नियम"],
     ["The right-hand thumb rule", "Fleming's left-hand rule", "Lenz's law", "Pascal's law"],
     0,
     "अंगूठा धारा की दिशा में — मुड़ी उँगलियाँ क्षेत्र की दिशा में।",
     "Thumb along the current — curled fingers give the field direction."),

    ("electromagnet", "medium",
     "सोलेनोइड का जो सिरा क्षेत्र-रेखाएँ बाहर छोड़ता है, वह कौन-सा ध्रुव है?",
     "The end of a solenoid from which field lines emerge is which pole?",
     ["उत्तरी ध्रुव", "दक्षिणी ध्रुव", "निरपेक्ष ध्रुव", "कोई ध्रुव नहीं"],
     ["The north pole", "The south pole", "A neutral pole", "No pole"],
     0,
     "बाहर निकलती रेखाएँ N से ही आती हैं — छड़ चुंबक जैसा।",
     "Emerging lines come from N — just like a bar magnet."),

    ("electromagnet", "medium",
     "एक परीक्षण में तार में धारा बढ़ाने पर निकट रखी कंपास सुई का विचलन बढ़ता गया। इसका क्या निष्कर्ष है?",
     "In a test, increasing the current increased the deflection of a nearby compass needle. What is the conclusion?",
     ["क्षेत्र की तीव्रता धारा के साथ बढ़ती है", "क्षेता धारा से स्वतंत्र है", "सुई खराब है", "धारा घट रही थी"],
     ["The field strength grows with the current", "The field is independent of current", "The needle is faulty", "The current was falling"],
     0,
     "विचलन क्षेत्र-तीव्रता का सीधा सूचक है।",
     "Deflection is a direct indicator of field strength."),

    ("electromagnet", "medium",
     "विद्युत-चुंबक बनाम स्थायी चुंबक — ध्रुव बदलने की सुविधा किसमें है?",
     "Electromagnet versus permanent magnet — which offers the convenience of changing poles?",
     ["केवल विद्युत-चुंबक में (धारा की दिशा पलटकर)", "दोनों में", "केवल स्थायी चुंबक में", "किसी में नहीं"],
     ["Only the electromagnet (by reversing the current)", "Both", "Only the permanent magnet", "Neither"],
     0,
     "स्थायी चुंबक के ध्रुव स्थिर रहते हैं।",
     "A permanent magnet's poles are fixed."),

    ("electromagnet", "medium",
     "कथन A: विद्युत-चुंबक की शक्ति नियंत्रण योग्य है। कथन B: स्थायी चुंबक की शक्ति सामान्यतः नियंत्रण योग्य नहीं। सही कौन-सा है?",
     "Statement A: an electromagnet's strength is controllable. Statement B: a permanent magnet's strength is generally not controllable. Which is correct?",
     ["A और B दोनों", "केवल A", "केवल B", "दोनों गलत"],
     ["Both A and B", "Only A", "Only B", "Both false"],
     0,
     "धारा/फेरे बदलकर विद्युत-चुंबक की शक्ति घटाई-बढ़ाई जाती है।",
     "By varying current or turns, an electromagnet's strength is tuned."),

    ("electromagnet", "medium",
     "भारी लोहे के स्क्रैप वाले यार्ड में स्थायी चुंबक के बजाए विद्युत-चुंबक क्यों?",
     "In a heavy scrap-iron yard, why an electromagnet instead of a permanent magnet?",
     ["सामान जहाँ चाहिए वहीं छोड़ने के लिए चुंबकत्व बंद किया जा सकता है", "स्थायी चुंबक लोहा नहीं उठाता", "विद्युत-चुंबक सस्ता नहीं होता", "स्थायी चुंबक ज़्यादा उठाता है"],
     ["The magnetism can be switched off to drop the load exactly where needed", "A permanent magnet cannot lift iron", "An electromagnet is not cheaper", "A permanent magnet lifts more"],
     0,
     "उतारने की सुविधा ही स्क्रैप-यार्ड की मुख्य ज़रूरत है।",
     "Controlled release is the scrap yard's core need."),

    ("electromagnet", "medium",
     "किसी तार की कुंडली में धारा दिशा बदलने पर कुंडली के पास कंपास सुई का क्या होगा?",
     "What happens to a compass needle near a coil when the current direction in the coil is reversed?",
     ["सुई विपरीत दिशा में विचलित होगी", "सुई वहीं रहेगी", "सुई घूमना बंद करेगी", "सुई टूटेगी"],
     ["The needle deflects the opposite way", "The needle stays put", "The needle stops turning", "The needle breaks"],
     0,
     "धारा-दिशा पलटने से क्षेत्र-दिशा पलटती है।",
     "Reversing current reverses the field."),

    ("electromagnet", "medium",
     "विद्युत-चुंबक में फेरों की संख्या आधी करने पर (धारा व छड़ वही) शक्ति कैसी होगी?",
     "If the turns of an electromagnet are halved (same current and core), what happens to its strength?",
     ["घट जाएगी", "बढ़ जाएगी", "दुगुनी होगी", "अपरिवर्तित रहेगी"],
     ["It decreases", "It increases", "It doubles", "It stays unchanged"],
     0,
     "फेरे घटने से क्षेत्र-योगदान घटता है।",
     "Fewer turns mean less field contribution."),

    ("electromagnet", "medium",
     "अस्पताल की मशीनरी वाले कमरे में प्रबल विद्युत-चुंबक लाने पर क्या खतरा हो सकता है?",
     "What risk can arise if a strong electromagnet is brought into a hospital machinery room?",
     ["मशीनों के चुंबकीय भाग/पेसमेकर जैसे उपकरण प्रभावित हो सकते हैं", "मशीनें ठंडी हो जाती हैं", "बिजली का बिल घटता है", "कमरा प्रकाशित होता है"],
     ["Magnetic parts of machines and devices like pacemakers can be affected", "Machines cool down", "The bill falls", "The room lights up"],
     0,
     "चुंबकीय क्षेत्र संवेदनशील उपकरणों के कार्य में बाधा डालता है।",
     "Magnetic fields disturb sensitive equipment."),

    ("electromagnet", "medium",
     "शृंखला में दो विद्युत-चुंबकों को जोड़ने पर एक ही धारा दोनों से बहती है। प्रत्येक की शक्ति अलग-अलग किस उपाय से बदली जा सकती है?",
     "Two electromagnets in series carry the same current. By what means can each one's strength be changed individually?",
     ["प्रत्येक की फेरों की संख्या अलग रखकर", "धारा बदलकर (दोनों बदलेंगे)", "छड़ हटाकर (दोनों क्षीण)", "स्विच से धारा बंद कर"],
     ["By giving each a different number of turns", "By changing the current (both change)", "By removing the cores (both weaken)", "By switching the current off"],
     0,
     "श्रेणी में धारा साझा है — फेरों से ही व्यक्तिगत अंतर आता है।",
     "In series the current is shared — only turns differentiate them."),

    ("electromagnet", "medium",
     "कंपास सुई के नीचे धारावाही तार उत्तर-दक्षिण दिशा में रखा जाए तो सुई का व्यवहार कैसा होगा?",
     "A current-carrying wire is placed under a compass needle along the north-south direction. How does the needle behave?",
     ["सुई विचलित होकर अपनी सामान्य दिशा से हट जाती है", "सुई कोई परिवर्तन नहीं दिखाती", "सुई उड़ जाती है", "सुई पिघल जाती है"],
     ["The needle deflects away from its usual direction", "The needle shows no change", "The needle flies off", "The needle melts"],
     0,
     "तार का क्षेत्र पृथ्वी-क्षेत्र पर अध्यारोपित होकर सुई घुमाता है।",
     "The wire's field superposes on the earth's field and turns the needle."),

    ("electromagnet", "medium",
     "विद्युत-चुंबक का कोर बार-बार चुंबकित-निष्चुंबकित होता है। ऐसे कोर से होने वाली ऊर्जा-हानि को कम करने के लिए कोर कैसा चुना जाता है?",
     "An electromagnet's core is magnetised and demagnetised repeatedly. How is the core chosen to reduce the resulting energy loss?",
     ["नर्म चुंबकीय पदार्थ से — प्रत्यावर्तन हानि न्यूनतम", "कठोर स्टील से", "ताँबे से", "रबर से"],
     ["A soft magnetic material — minimum reversal loss", "Hard steel", "Copper", "Rubber"],
     0,
     "नर्म पदार्थ में चुंबकत्व बार-बार बदलने पर हानि कम रहती है।",
     "In soft materials repeated reversal wastes little energy."),

    ("electromagnet", "medium",
     "एक विद्युत-चुंबक उठा सकता है 20 किलोग्राम। यदि धारा बंद कर दें तो लोहा गिर जाएगा — यह किस गुण का परिणाम है?",
     "An electromagnet can lift 20 kg. If the current is switched off, the iron falls — this results from which property?",
     ["अस्थायी चुंबकत्व", "स्थायी चुंबकत्व", "अचुंबकत्व", "प्रतिकर्षण"],
     ["Temporary magnetism", "Permanent magnetism", "Non-magnetism", "Repulsion"],
     0,
     "नियंत्रित उठाना-गिराना अस्थायीपन से ही संभव है।",
     "Controlled lift-and-drop is possible only because of temporariness."),

    ("electromagnet", "medium",
     "साइकिल की डायनेमो किस सिद्धांत पर काम करती है?",
     "On what principle does a bicycle dynamo work?",
     ["चालक की गति से चुंबकीय क्षेत्र में धारा प्रेरण", "धारा से गति", "ऊष्मा से धारा", "प्रकाश से धारा"],
     ["Current induced by a conductor moving in a magnetic field", "Motion from current", "Current from heat", "Current from light"],
     0,
     "डायनेमो = लघु जनित्र — गतिज ऊर्जा से विद्युत।",
     "A dynamo is a small generator — mechanical energy to electrical."),

    # ---- hard (9) ----
    ("electromagnet", "hard",
     "विद्युत-चुंबक की कुंडली में 200 फेरे और 2 एम्पियर धारा है। फेरे 600 तथा धारा 1 एम्पियर कर दी जाए तो शक्ति की तुलना कीजिए।",
     "An electromagnet has 200 turns and 2 A current. If the turns are made 600 and the current 1 A, compare the strength.",
     ["बढ़ेगी — लगभग 1.5 गुना (फेरे तीन गुने, धारा आधी)", "आधी रह जाएगी", "दुगुनी हो जाएगी", "समाप्त हो जाएगी"],
     ["It increases — about 1.5 times (threefold turns, half current)", "It halves", "It doubles", "It vanishes"],
     0,
     "क्षेत्र ∝ फेरे × धारा: 200×2 = 400; 600×1 = 600 — शुद्ध 600/400 = 1.5 गुना।",
     "Field ∝ turns × current: 200×2 = 400; 600×1 = 600 — net 600/400 = 1.5 times."),

    ("electromagnet", "hard",
     "दाहिने हाथ के अंगूठे के नियम में अंगूठा क्या दर्शाता है?",
     "In the right-hand thumb rule, what does the thumb indicate?",
     ["धारा की दिशा (सीधे तार में)", "क्षेत्र की तीव्रता", "बल की दिशा", "विभवांतर"],
     ["The direction of the current (in a straight wire)", "The field strength", "The force direction", "The potential difference"],
     0,
     "मुड़ी उँगलियाँ क्षेत्र-वृत्तों की दिशा बताती हैं।",
     "The curled fingers show the direction of the field circles."),

    ("electromagnet", "hard",
     "फ्लेमिंग के वाम-हस्त नियम की तीन उँगलियाँ क्रमशः क्या दर्शाती हैं?",
     "What do the three fingers of Fleming's left-hand rule indicate respectively?",
     ["आगे की उँगली — क्षेत्र, पीछे की — धारा, अंगूठा — बल", "आगे की उँगली — धारा, पीछे की — क्षेत्र, अंगूठा — बल", "अंगूठा — क्षेत्र, सब — धारा", "कोई नियम नहीं"],
     ["Forefinger — field, middle/back finger — current, thumb — force", "Forefinger — current, back finger — field, thumb — force", "Thumb — field, all — current", "No such rule"],
     0,
     "वाम हस्त नियम धारावाही चालक पर बल की दिशा देता है (मोटर प्रभाव)।",
     "The left-hand rule gives the force on a current-carrying conductor (motor effect)."),

    ("electromagnet", "hard",
     "फ्लेमिंग का वाम-हस्त नियम किस यंत्र की कार्यविधि समझाने में उपयोगी है?",
     "Fleming's left-hand rule is useful in explaining the working of which device?",
     ["विद्युत मोटर", "विद्युत जनित्र", "ट्रांसफार्मर", "सोलर पैनल"],
     ["The electric motor", "The electric generator", "A transformer", "A solar panel"],
     0,
     "मोटर में धारा + क्षेत्र → बल/गति — वाम हस्त नियम।",
     "In a motor, current + field → force/motion — the left-hand rule."),

    ("electromagnet", "hard",
     "फ्लेमिंग का दक्षिण-हस्त नियम किस स्थिति में लगाया जाता है?",
     "When is Fleming's right-hand rule applied?",
     ["चालक की गति से प्रेरित धारा की दिशा ज्ञात करने में (जनित्र)", "धारावाही चालक पर बल ज्ञात करने में", "क्षेत्र की तीव्रता नापने में", "प्रतिरोध निकालने में"],
     ["To find the direction of induced current from a conductor's motion (generator)", "To find force on a current-carrying conductor", "To measure field strength", "To calculate resistance"],
     0,
     "दक्षिण-हस्त नियम प्रेरण (जनित्र) से जुड़ा है।",
     "The right-hand rule belongs to induction (generator)."),

    ("electromagnet", "hard",
     "एक विद्युत-चुंबक की कुंडली का फेरा उलट दिया गया (धारा उसी दिशा में)। ध्रुवों पर क्या प्रभाव पड़ेगा?",
     "The winding sense of an electromagnet's coil is reversed (current direction unchanged at the terminals). What happens to its poles?",
     ["ध्रुव आपस में बदल जाएँगे", "ध्रुव वही रहेंगे", "चुंबकत्व समाप्त", "केवल शक्ति बढ़ेगी"],
     ["The poles swap", "The poles stay the same", "The magnetism vanishes", "Only the strength grows"],
     0,
     "कुंडली की लपेटन बदलने से क्षेत्र-दिशा उलट जाती है।",
     "Reversing the winding sense flips the field direction."),

    ("electromagnet", "hard",
     "सोलेनोइड के ऊपरी फलक पर ऊपर से देखने पर धारा प्रति-घड़ी (anticlockwise) दिशा में बह रही है। ऊपरी फलक कौन-सा ध्रुव बनेगा?",
     "Viewed from above, current in a solenoid flows anticlockwise at the top face. Which pole does the top face become?",
     ["उत्तरी ध्रुव", "दक्षिणी ध्रुव", "कोई नहीं", "दोनों"],
     ["The north pole", "The south pole", "Neither", "Both"],
     0,
     "प्रति-घड़ी धारा वाला फलक N ध्रुव बनाता है — अंगूठा नियम से।",
     "An anticlockwise current face acts as the N pole — by the thumb rule."),

    ("electromagnet", "hard",
     "एक कुंडली में 5 वोल्ट पर 2 एम्पियर बहता है। यदि फेरे दुगुने और उसी प्रकार की दूसरी कुंडली श्रेणी में जोड़ दी जाए तो चुंबकत्व की प्रवृत्ति क्या होगी (धारा लगभग समान मानकर)?",
     "A coil draws 2 A at 5 V. If the turns are doubled and an identical second coil is added in series (current nearly unchanged), what is the tendency of the magnetism?",
     ["वृद्धि — कुल फेरे लगभग दुगुने से अधिक", "कोई परिवर्तन नहीं", "घटेगी", "समाप्त होगी"],
     ["It increases — total turns well beyond double", "No change", "It decreases", "It vanishes"],
     0,
     "फेरों का योग बढ़ता है — क्षेत्र प्रबल होता है।",
     "The added turns raise the total — a stronger field results."),

    ("electromagnet", "hard",
     "विद्युत-चुंबक के कोर में स्टील प्रयोग करने पर स्विच बंद करने के बाद क्या होगा?",
     "What happens after switching off if steel is used as an electromagnet's core?",
     ["स्टील चुंबकत्व बनाए रखेगा — सामान छोड़ना कठिन", "सामान तुरंत गिरेगा", "कोर पिघल जाएगा", "धारा उलट जाएगी"],
     ["The steel retains magnetism — releasing the load becomes difficult", "The load drops instantly", "The core melts", "The current reverses"],
     0,
     "स्टील की शेष-चुंबकत्व (retentivity) अधिक है — नियंत्रण खो जाता है।",
     "Steel's high retentivity spoils the control."),

    # ================= MOTOR-GENERATOR EFFECT (50) =================
    # ---- easy (20) ----
    ("motor-generator-effect", "easy",
     "चुंबकीय क्षेत्र में रखे धारावाही चालक पर क्या लगता है?",
     "What is experienced by a current-carrying conductor placed in a magnetic field?",
     ["बल", "ऊष्मा", "प्रकाश", "ध्वनि"],
     ["A force", "Heat", "Light", "Sound"],
     0,
     "क्षेत्र और धारा का संयोग चालक पर बल उत्पन्न करता है — मोटर प्रभाव।",
     "The combination of field and current produces a force — the motor effect."),

    ("motor-generator-effect", "easy",
     "विद्युत मोटर किस ऊर्जा को किस ऊर्जा में बदलती है?",
     "An electric motor converts which energy into which?",
     ["विद्युत को गतिज", "गतिज को विद्युत", "ऊष्मीय को विद्युत", "विद्युत को प्रकाश"],
     ["Electrical into mechanical", "Mechanical into electrical", "Thermal into electrical", "Electrical into light"],
     0,
     "मोटर धारा से घूर्णन बनाती है।",
     "A motor turns current into rotation."),

    ("motor-generator-effect", "easy",
     "विद्युत जनित्र किस ऊर्जा को किस ऊर्जा में बदलता है?",
     "An electric generator converts which energy into which?",
     ["गतिज को विद्युत", "विद्युत को गतिज", "प्रकाश को ऊष्मा", "रासायनिक को गतिज"],
     ["Mechanical into electrical", "Electrical into mechanical", "Light into heat", "Chemical into mechanical"],
     0,
     "जनित्र घूर्णन से धारा बनाता है।",
     "A generator makes current from rotation."),

    ("motor-generator-effect", "easy",
     "विद्युत-चुंबकीय प्रेरण किसे कहते हैं?",
     "What is electromagnetic induction?",
     ["चुंबकीय क्षेत्र में चालक की गति से उसमें धारा उत्पन्न होना", "धारा से चुंबकत्व बनना", "चुंबक से लोहा खिंचना", "घर्षण से ऊष्मा बनना"],
     ["The production of current in a conductor moving in a magnetic field", "Magnetism produced by current", "Iron pulled by a magnet", "Heat produced by friction"],
     0,
     "गति + क्षेत्र → प्रेरित धारा — जनित्र का आधार।",
     "Motion + field → induced current — the generator's basis."),

    ("motor-generator-effect", "easy",
     "प्रेरित धारा की खोज किसने की?",
     "Who discovered induced current?",
     ["माइकल फैराडे", "न्यूटन", "आइंस्टीन", "एडिसन"],
     ["Michael Faraday", "Newton", "Einstein", "Edison"],
     0,
     "1831 में फैराडे ने विद्युत-चुंबकीय प्रेरण की खोज की।",
     "In 1831 Faraday discovered electromagnetic induction."),

    ("motor-generator-effect", "easy",
     "जनित्र किस खोज पर आधारित है?",
     "The generator is based on which discovery?",
     ["विद्युत-चुंबकीय प्रेरण", "ओम का नियम", "गुरुत्वाकर्षण", "प्रकाश का विक्षेपण"],
     ["Electromagnetic induction", "Ohm's law", "Gravitation", "Dispersion of light"],
     0,
     "फैराडे का प्रेरण-प्रयोग ही जनित्र का मूल है।",
     "Faraday's induction experiment is the generator's root."),

    ("motor-generator-effect", "easy",
     "प्रेरित धारा किस यंत्र से जाँची जाती है?",
     "With which instrument is induced current detected?",
     ["गैल्वेनोमीटर", "वोल्टमीटर", "थर्मामीटर", "बैरोमीटर"],
     ["A galvanometer", "A voltmeter", "A thermometer", "A barometer"],
     0,
     "गैल्वेनोमीटर सूक्ष्म धारा का विचलन दर्शाता है।",
     "A galvanometer shows a deflection for tiny currents."),

    ("motor-generator-effect", "easy",
     "कुंडली के पास चुंबक को ले जाने पर गैल्वेनोमीटर की सुई हरकत करती है। इसका कारण क्या है?",
     "The galvanometer needle moves when a magnet is moved near a coil. What is the reason?",
     ["कुंडली में प्रेरित धारा बनती है", "कुंडली गरम होती है", "कुंडली चुंबक बन जाती है", "सुई टूटती है"],
     ["An induced current flows in the coil", "The coil heats up", "The coil becomes a magnet", "The needle breaks"],
     0,
     "चुंबक की गति क्षेत्र बदलती है — प्रेरण होता है।",
     "The magnet's motion changes the field — induction occurs."),

    ("motor-generator-effect", "easy",
     "चुंबक को कुंडली के पास स्थिर रखने पर प्रेरित धारा की स्थिति क्या होती है?",
     "What is the state of the induced current when the magnet is held stationary near the coil?",
     ["कोई धारा नहीं — प्रेरण के लिए बदलता क्षेत्र चाहिए", "अधिकतम धारा", "अर्ध-धारा", "उलटी धारा"],
     ["No current — induction needs a changing field", "Maximum current", "Half current", "Reversed current"],
     0,
     "स्थिर चुंबक = अपरिवर्ती क्षेत्र = शून्य प्रेरण।",
     "A stationary magnet = an unchanging field = zero induction."),

    ("motor-generator-effect", "easy",
     "मोटर की घूमती हुई कुंडली किसके बीच रखी होती है?",
     "The rotating coil of a motor is placed between what?",
     ["विपरीत ध्रुवों वाले दो चुंबकों (चुंबकीय क्षेत्र) के बीच", "दो सेलों के बीच", "दो बल्बों के बीच", "दो प्रतिरोधों के बीच"],
     ["Between the opposite poles of two magnets (a magnetic field)", "Between two cells", "Between two bulbs", "Between two resistors"],
     0,
     "क्षेत्र में ही धारावाही कुंडली बल अनुभव करती है।",
     "Only in a field does the current-carrying coil feel a force."),

    ("motor-generator-effect", "easy",
     "मोटर में विद्युत-चुंबकीय बल-आघूर्ण किस युग्म से उत्पन्न होता है?",
     "In a motor, the electromagnetic torque arises from which pair?",
     ["धारा और चुंबकीय क्षेत्र", "वोल्टेज और प्रतिरोध", "ऊष्मा और दाब", "प्रकाश और ध्वनि"],
     ["Current and magnetic field", "Voltage and resistance", "Heat and pressure", "Light and sound"],
     0,
     "बल ∝ धारा × क्षेत्र — मोटर का मूल संबंध।",
     "Force ∝ current × field — the motor's basic relation."),

    ("motor-generator-effect", "easy",
     "मोटर और जनित्र में ऊर्जा-रूपांतरण की दिशा कैसी है?",
     "How do the energy-conversion directions of a motor and a generator compare?",
     ["एक-दूसरे के विपरीत", "दोनों एक ही दिशा में", "दोनों में कोई रूपांतरण नहीं", "मोटर में दो, जनित्र में कोई नहीं"],
     ["Opposite to each other", "Both in the same direction", "Neither converts energy", "Two in the motor, none in the generator"],
     0,
     "मोटर: विद्युत→गतिज; जनित्र: गतिज→विद्युत।",
     "Motor: electrical→mechanical; generator: mechanical→electrical."),

    ("motor-generator-effect", "easy",
     "घरेलू बिजली की आपूर्ति में धारा की दिशा बार-बार बदलती है। ऐसी धारा क्या कहलाती है?",
     "In domestic supply the current direction reverses repeatedly. What is such current called?",
     ["प्रत्यावर्ती धारा (AC)", "दिष्ट धारा (DC)", "मूल धारा", "प्रेरित शून्य"],
     ["Alternating current (AC)", "Direct current (DC)", "Root current", "Zero induction"],
     0,
     "AC की दिशा चक्रीय रूप से बदलती रहती है।",
     "AC keeps reversing its direction cyclically."),

    ("motor-generator-effect", "easy",
     "टॉर्च की बैटरी से मिलने वाली धारा कौन-सी होती है?",
     "The current from a torch battery is which type?",
     ["दिष्ट धारा (DC)", "प्रत्यावर्ती (AC)", "दोनों मिश्रित", "कोई धारा नहीं"],
     ["Direct current (DC)", "Alternating (AC)", "A mixture of both", "No current"],
     0,
     "बैटरी एक ही दिशा में धारा देती है।",
     "A battery supplies current in one direction only."),

    ("motor-generator-effect", "easy",
     "भारत में घरेलू AC की आवृत्ति लगभग कितनी होती है?",
     "What is the approximate frequency of domestic AC in India?",
     ["50 हर्ट्ज़", "60 हर्ट्ज़", "5 हर्ट्ज़", "500 हर्ट्ज़"],
     ["50 hertz", "60 hertz", "5 hertz", "500 hertz"],
     0,
     "भारतीय विद्युत बोर्ड 50 Hz चक्र प्रति सेकंड आपूर्ति करते हैं।",
     "Indian supply boards provide 50 cycles per second."),

    ("motor-generator-effect", "easy",
     "पंखा (fan) किस विद्युत मशीन का घरेलू रूप है?",
     "A fan is the household form of which electrical machine?",
     ["मोटर", "जनित्र", "ट्रांसफार्मर", "रेक्टिफायर"],
     ["A motor", "A generator", "A transformer", "A rectifier"],
     0,
     "पंखे की मोटर विद्युत से घूर्णन बनाती है।",
     "The fan's motor turns electricity into rotation."),

    ("motor-generator-effect", "easy",
     "जल-विद्युत गृह में टरबाइन किस यंत्र को घुमाती है?",
     "In a hydro power house, the turbine drives which device?",
     ["विद्युत जनित्र", "विद्युत मोटर", "ट्रांसफार्मर", "हीटर"],
     ["An electric generator", "An electric motor", "A transformer", "A heater"],
     0,
     "जल की गतिज ऊर्जा → टरबाइन → जनित्र → विद्युत।",
     "Kinetic energy of water → turbine → generator → electricity."),

    ("motor-generator-effect", "easy",
     "साइकिल की डायनेमो घुमाने पर लैंप जलता है। यह किसका उदाहरण है?",
     "A lamp glows when a bicycle dynamo is spun. This is an example of what?",
     ["विद्युत-चुंबकीय प्रेरण (लघु जनित्र)", "मोटर प्रभाव", "ओम का नियम", "ऊष्मीय प्रभाव"],
     ["Electromagnetic induction (a small generator)", "The motor effect", "Ohm's law", "The heating effect"],
     0,
     "गति से प्रेरित धारा — डायनेमो।",
     "Motion-induced current — a dynamo."),

    ("motor-generator-effect", "easy",
     "मोटर के शaft (धुरी) का घूर्णन किसके कारण होता है?",
     "What causes the rotation of a motor's shaft?",
     ["चुंबकीय क्षेत्र में धारावाही कुंडली पर लगने वाला बल", "बैटरी का गरम होना", "तारों का कंपन", "गुरुत्वाकर्षण"],
     ["The force on the current-carrying coil in the magnetic field", "The battery heating up", "Vibration of wires", "Gravitation"],
     0,
     "कुंडली के दो विपरीत भुजाओं पर विपरीत बल — घूर्णन।",
     "Opposite forces on the coil's opposite sides — rotation."),

    ("motor-generator-effect", "easy",
     "जनित्र और मोटर का मूल नियम एक ही है — विद्युत-चुंबकत्व। दोनों के कार्य का अंतर किस राशि की दिशा से होता है?",
     "Generators and motors obey the same root science. The difference in their roles is the direction of which quantity?",
     ["ऊर्जा-रूपांतरण", "रंग", "द्रव्यमान", "आयतन"],
     ["Energy conversion", "Colour", "Mass", "Volume"],
     0,
     "ऊर्जा के प्रवाह की दिशा ही दोनों को अलग करती है।",
     "The direction of energy flow alone separates the two."),

    # ---- medium (22) ----
    ("motor-generator-effect", "medium",
     "चुंबक को कुंडली में तेज़ी से घुसेड़ने पर गैल्वेनोमीटर विचलन कैसा होता है?",
     "What happens to the galvanometer deflection when a magnet is pushed into a coil faster?",
     ["विचलन बढ़ता है", "विचलन घटता है", "शून्य हो जाता है", "उल्टा जाता है"],
     ["The deflection increases", "The deflection decreases", "It becomes zero", "It reverses"],
     0,
     "तीव्र गति = शीघ्र क्षेत्र-परिवर्तन = बड़ी प्रेरित धारा।",
     "Faster motion = quicker field change = larger induced current."),

    ("motor-generator-effect", "medium",
     "चुंबक को कुंडली से बाहर खींचने पर प्रेरित धारा की दिशा कैसी होती है (अंदर जाने की तुलना में)?",
     "Compared with pushing in, how is the direction of induced current when the magnet is pulled out of the coil?",
     ["विपरीत होती है", "समान रहती है", "शून्य होती है", "दुगुनी होती है"],
     ["It is opposite", "It stays the same", "It is zero", "It doubles"],
     0,
     "क्षेत्र-परिवर्तन की दिशा बदलती है — धारा भी उलटती है।",
     "The field change reverses — so does the current."),

    ("motor-generator-effect", "medium",
     "प्रेरित धारा का परिमाण किन कारकों पर निर्भर करता है?",
     "On what factors does the magnitude of the induced current depend?",
     ["चुंबक की शक्ति, गति की तीव्रता और कुंडली के फेरे", "केवल कुंडली का रंग", "केवल तार की लंबाई", "केवल मौसम"],
     ["The magnet's strength, the speed of motion and the coil's turns", "Only the coil's colour", "Only the wire's length", "Only the weather"],
     0,
     "शीघ्रतर गति, प्रबल चुंबक, अधिक फेरे — बड़ी प्रेरित धारा।",
     "Faster motion, stronger magnet, more turns — larger induced current."),

    ("motor-generator-effect", "medium",
     "मोटर में कुंडली की धारा दिशा हर आधे चक्र में क्यों बदलनी पड़ती है?",
     "Why must the current direction in a motor's coil reverse every half cycle?",
     ["ताकि कुंडली एक ही दिशा में निरंतर घूमती रहे", "धारा बचाने के लिए", "ऊष्मा घटाने के लिए", "बिल घटाने के लिए"],
     ["So that the coil keeps rotating in the same direction", "To save current", "To reduce heat", "To lower the bill"],
     0,
     "दिशा-परिवर्तन से बल-आघूर्ण एक ही दिशा में बना रहता है।",
     "Commutated reversal keeps the torque in one direction."),

    ("motor-generator-effect", "medium",
     "मोटर में विद्युत ऊर्जा का एक भाग ऊष्मा में भी बदलता है। यह ऊष्मा किससे आती है?",
     "Part of a motor's electrical energy turns into heat too. Where does this heat come from?",
     ["कुंडली के प्रतिरोध से (ऊष्मीय प्रभाव)", "चुंबक के रंग से", "घूर्णन के रंग से", "वायु से"],
     ["From the coil's resistance (heating effect)", "From the magnet's colour", "From the rotation's colour", "From air"],
     0,
     "कुंडली का प्रतिरोध ऊर्जा का अंश ऊष्मा में व्यय करता है।",
     "The coil's resistance spends part of the energy as heat."),

    ("motor-generator-effect", "medium",
     "जनित्र में कुंडली घुमाने वाली मशीनी ऊर्जा कहाँ से आ सकती है — उदाहरण सहित बताइए।",
     "Where can the mechanical energy that spins a generator's coil come from — answer with an example.",
     ["जल, भाप या वायु टरबाइन से — जैसे जल-विद्युत गृह में", "बैटरी से", "बल्ब से", "रेडियो से"],
     ["From water, steam or wind turbines — as in a hydro power house", "From a battery", "From a bulb", "From a radio"],
     0,
     "प्राकृतिक गतिज स्रोत टरबाइन घुमाते हैं।",
     "Natural mechanical sources drive the turbines."),

    ("motor-generator-effect", "medium",
     "AC के लिए जनित्र-कुंडली का घूर्णन दिष्ट धारा में बदलने की आवश्यकता क्यों नहीं पड़ती?",
     "Why does an AC generator's coil rotation not need conversion into one-way current?",
     ["AC का उपयोग सीधे गृह-आपूर्ति में होता है — दिशा-परिवर्तन ही AC की पहचान है", "AC खतरनाक होती है", "AC धीमी होती है", "AC में वोल्टेज नहीं होता"],
     ["AC is supplied to homes directly — periodic reversal is AC's very identity", "AC is dangerous", "AC is slow", "AC has no voltage"],
     0,
     "प्रत्यावर्ती धारा की नियमित दिशा-परिवर्तनशीलता ही उसका स्वरूप है।",
     "The periodic reversal is exactly what defines AC."),

    ("motor-generator-effect", "medium",
     "50 हर्ट्ज़ AC का एक चक्र कितने समय का होता है?",
     "How long is one cycle of 50 Hz AC?",
     ["0.02 सेकंड", "0.2 सेकंड", "2 सेकंड", "50 सेकंड"],
     ["0.02 s", "0.2 s", "2 s", "50 s"],
     0,
     "T = 1/ν = 1/50 = 0.02 सेकंड।",
     "T = 1/ν = 1/50 = 0.02 s."),

    ("motor-generator-effect", "medium",
     "50 हर्ट्ज़ AC में धारा की दिशा एक सेकंड में कितनी बार बदलती है?",
     "In 50 Hz AC, how many times does the current direction change in one second?",
     ["100 बार", "50 बार", "25 बार", "200 बार"],
     ["100 times", "50 times", "25 times", "200 times"],
     0,
     "प्रत्येक चक्र में दो बार पलटना — 50 × 2 = 100।",
     "Each cycle flips twice — 50 × 2 = 100."),

    ("motor-generator-effect", "medium",
     "मोटर की कुंडली में धारा बढ़ाने पर घूर्णन-बल का क्या होता है?",
     "What happens to a motor's torque if the current in its coil is increased?",
     ["बढ़ता है", "घटता है", "समाप्त होता है", "उलट जाता है"],
     ["It increases", "It decreases", "It vanishes", "It reverses"],
     0,
     "बल धारा के अनुक्रमानुपाती है।",
     "The force is proportional to the current."),

    ("motor-generator-effect", "medium",
     "मोटर में अधिक शक्तिशाली चुंबक लगाने से क्या लाभ है?",
     "What is the benefit of fitting stronger magnets in a motor?",
     ["क्षेत्र बढ़ता है — उसी धारा पर अधिक बल-आघूर्ण", "धारा घटती है", "वोल्टेज बढ़ता है", "ऊष्मा शून्य होती है"],
     ["A stronger field — more torque at the same current", "The current falls", "The voltage rises", "Heat becomes zero"],
     0,
     "बल ∝ क्षेत्र — प्रबल चुंबक प्रबल घूर्णन।",
     "Force ∝ field — stronger magnet, stronger rotation."),

    ("motor-generator-effect", "medium",
     "एक जनित्र की कुंडली 100 फेरों की है। उसी आकार की 400 फेरों की कुंडली उसी गति से घुमाने पर प्रेरित वोल्टेज कैसा होगा?",
     "A generator coil has 100 turns. If a 400-turn coil of the same size is spun at the same speed, how does the induced voltage change?",
     ["लगभग चार गुना", "आधा", "समान", "शून्य"],
     ["About four times", "Half", "The same", "Zero"],
     0,
     "प्रेरित वोल्टेज फेरों के अनुक्रमानुपाती — 400/100 = 4।",
     "Induced voltage scales with turns — 400/100 = 4."),

    ("motor-generator-effect", "medium",
     "प्रेरण-कुंडली के सामने चुंबक को विरामावस्था से तेज़ गति से मोड़ा गया। गैल्वेनोमीटर पहले एक ओर, फिर दूसरी ओर विचलित हुआ। कारण बताइए।",
     "A magnet is quickly flipped in front of a coil. The galvanometer deflects one way, then the other. Explain.",
     ["चुंबक के पलटने से क्षेत्र-परिवर्तन की दिशा बदल गई — प्रेरित धारा ने दिशा बदली", "गैल्वेनोमीटर खराब है", "कुंडली ने चुंबक खा लिया", "बैटरी जुड़ गई"],
     ["Flipping reverses the field change — the induced current reverses", "The galvanometer is faulty", "The coil ate the magnet", "A battery got connected"],
     0,
     "प्रेरण की दिशा क्षेत्र-परिवर्तन की दिशा से नियत होती है।",
     "Induction direction follows the direction of field change."),

    ("motor-generator-effect", "medium",
     "मोटर और जनित्र एक-दूसरे के विपरीत हैं — यह कथन किस अर्थ में सत्य है?",
     "In what sense is the statement 'a motor and a generator are opposites' true?",
     ["ऊर्जा-रूपांतरण की दिशा विपरीत है", "दोनों के पुर्जे भिन्न होते हैं", "दोनों का आविष्कार अलग हुआ", "दोनों में चुंबक नहीं होते"],
     ["Their energy-conversion directions are opposite", "Their parts differ", "They were invented separately", "Neither has magnets"],
     0,
     "मूल भौतिकी एक; प्रयोग विपरीत दिशा में।",
     "The core physics is one; the applications run opposite ways."),

    ("motor-generator-effect", "medium",
     "पवन चक्की (विंड टरबाइन) विद्युत कैसे बनाती है?",
     "How does a wind turbine generate electricity?",
     ["ब्लेड के घूर्णन से जनित्र की कुंडली घूमती है — प्रेरण से धारा", "हवा से बैटरी चलती है", "हवा रगड़ से बिजली", "हवा प्रकाश बनाती है"],
     ["Blade rotation spins the generator coil — current by induction", "Wind runs a battery", "Wind makes electricity by rubbing", "Wind makes light"],
     0,
     "गतिज ऊर्जा → जनित्र → विद्युत ऊर्जा।",
     "Kinetic energy → generator → electrical energy."),

    ("motor-generator-effect", "medium",
     "कुंडली घूमने की दर बढ़ाने पर जनित्र का प्रेरित वोल्टेज कैसा होता है?",
     "What happens to a generator's induced voltage when the coil is spun faster?",
     ["बढ़ता है", "घटता है", "समान रहता है", "शून्य हो जाता है"],
     ["It increases", "It decreases", "It stays the same", "It becomes zero"],
     0,
     "तेज़ घूर्णन = शीघ्र क्षेत्र-परिवर्तन = बड़ा वोल्टेज।",
     "Faster spin = quicker field change = bigger voltage."),

    ("motor-generator-effect", "medium",
     "मोटर से जुड़ा पंखा बिजली बंद होते ही रुक जाता है। ऊर्जा-शृंखला पूरी कीजिए।",
     "A fan stops as soon as the power goes off. Complete the energy chain.",
     ["विद्युत → गतिज (+ थोड़ी ऊष्मा)", "गतिज → विद्युत", "ऊष्मा → विद्युत", "प्रकाश → गतिज"],
     ["Electrical → mechanical (+ a little heat)", "Mechanical → electrical", "Heat → electrical", "Light → mechanical"],
     0,
     "मोटर मुख्य रूपांतरण के साथ अपनी हानि ऊष्मा भी देती है।",
     "The motor's main conversion carries a small heat loss too."),

    ("motor-generator-effect", "medium",
     "प्रेरित धारा की दिशा ज्ञात करने का नियम कौन-सा है?",
     "Which rule gives the direction of the induced current?",
     ["फ्लेमिंग का दक्षिण-हस्त नियम", "फ्लेमिंग का वाम-हस्त नियम", "दाहिने अंगूठे का नियम", "लेंज़ का नियम नहीं — पास्कल"],
     ["Fleming's right-hand rule", "Fleming's left-hand rule", "The right-hand thumb rule", "Not Lenz's — Pascal's"],
     0,
     "गति + क्षेत्र → धारा की दिशा — दक्षिण-हस्त नियम।",
     "Motion + field → current direction — the right-hand rule."),

    ("motor-generator-effect", "medium",
     "धारावाही चालक पर लगने वाले बल की दिशा बदलने के दो उपाय कौन-से हैं?",
     "What are the two ways to reverse the force on a current-carrying conductor?",
     ["धारा की दिशा बदलना या चुंबकीय क्षेत्र की दिशा बदलना", "धारा बढ़ाना या घटाना", "चालक को गरम या ठंडा करना", "चालक को लंबा या छोटा करना"],
     ["Reverse the current direction or reverse the field direction", "Increase or decrease the current", "Heat or cool the conductor", "Lengthen or shorten the conductor"],
     0,
     "बल की दिशा धारा × क्षेत्र के क्रस-गुणन पर निर्भर।",
     "The force direction depends on the cross product of current and field."),

    ("motor-generator-effect", "medium",
     "जनित्र की कुंडली क्षेत्र में समतल क्षैतिज स्थिति में विराम करती है — उस क्षण प्रेरित धारा की स्थिति सरल शब्दों में कैसी होती है?",
     "A generator coil momentarily lies flat (parallel to the field) — in simple terms, what is the induced current at that instant?",
     ["उस क्षण क्षेत्र-परिवर्तन सबसे तेज़ होता है — धारा चरम पर", "धारा शून्य होती है", "धारा उलट जाती है", "धारा अनंत होती है"],
     ["At that instant the field change is fastest — the current is at a peak", "The current is zero", "The current reverses", "The current is infinite"],
     0,
     "कुंडली के फलक के क्षेत्र के समानांतर होने पर बहता प्रवाह सबसे तेज़ बदलता है।",
     "When the coil's face swings parallel to the field, the flux changes fastest."),

    ("motor-generator-effect", "medium",
     "मिक्सर-ग्राइंडर में मोटर की शक्ति 750 वाट है। 4 सेकंड चलने पर लगभग कितनी ऊर्जा व्यय होगी?",
     "A mixer's motor is rated 750 W. Roughly how much energy does it use in 4 s?",
     ["3000 जूल", "187.5 जूल", "750 जूल", "300 जूल"],
     ["3000 J", "187.5 J", "750 J", "300 J"],
     0,
     "E = Pt = 750 × 4 = 3000 जूल (P = VI से जुड़ी मोटर-शक्ति)।",
     "E = Pt = 750 × 4 = 3000 J (motor power tied to P = VI)."),

    ("motor-generator-effect", "medium",
     "ऊर्जा-संरक्षण के अनुसार जनित्र बिना प्रयास के विद्युत नहीं दे सकता। टरबाइन को घुमाने वाली ऊर्जा का स्रोत ही क्या है जल-विद्युत में?",
     "By energy conservation a generator cannot give electricity for free. In hydro power, what is the source that drives the turbine?",
     ["जल के ऊँचाई से गिरने की स्थितिज/गतिज ऊर्जा", "तारों की ऊर्जा", "चुंबकों की ऊर्जा", "हवा की ऊर्जा सदैव"],
     ["The potential/kinetic energy of falling water from a height", "Energy of the wires", "Energy of the magnets", "Always wind energy"],
     0,
     "जल से टरबाइन, टरबाइन से जनित्र — ऊर्जा शृंखला संरक्षित।",
     "Water to turbine, turbine to generator — the energy chain is conserved."),

    # ---- hard (8) ----
    ("motor-generator-effect", "hard",
     "मोटर की कुंडली में 2 एम्पियर धारा बह रही है। धारा 6 एम्पियर करने पर बल-आघूर्ण लगभग कितना गुना होगा?",
     "A motor's coil carries 2 A. If the current is raised to 6 A, the torque becomes about how many times?",
     ["3 गुना", "9 गुना", "समान", "एक-तिहाई"],
     ["3 times", "9 times", "The same", "One-third"],
     0,
     "बल ∝ धारा: 6/2 = 3 गुना।",
     "Force ∝ current: 6/2 = 3 times."),

    ("motor-generator-effect", "hard",
     "जनित्र की कुंडली प्रति सेकंड 5 चक्र घूमती है। 2 सेकंड में कुल कितने पूर्ण चक्र पूरे होंगे?",
     "A generator's coil rotates 5 cycles per second. How many complete cycles finish in 2 s?",
     ["10 चक्र", "5 चक्र", "2.5 चक्र", "20 चक्र"],
     ["10 cycles", "5 cycles", "2.5 cycles", "20 cycles"],
     0,
     "5 × 2 = 10 पूर्ण चक्र।",
     "5 × 2 = 10 complete cycles."),

    ("motor-generator-effect", "hard",
     "एक जनित्र 50 हर्ट्ज़ आवृत्ति से 0.02 सेकंड का चक्र देता है। यदि आवृत्ति बढ़कर 100 हर्ट्ज़ हो तो चक्र-काल कितना होगा?",
     "A generator gives 50 Hz output (0.02 s per cycle). If the frequency rises to 100 Hz, what is the period?",
     ["0.01 सेकंड", "0.04 सेकंड", "0.02 सेकंड", "0.1 सेकंड"],
     ["0.01 s", "0.04 s", "0.02 s", "0.1 s"],
     0,
     "T = 1/ν = 1/100 = 0.01 सेकंड — आवृत्ति दुगुनी, काल आधा।",
     "T = 1/ν = 1/100 = 0.01 s — double the frequency, half the period."),

    ("motor-generator-effect", "hard",
     "कुंडली में चुंबक 0.5 सेकंड तक एकसमान गति से घुसेड़ा गया और गैल्वेनोमीटर स्थिर विचलन दिखाता रहा। चुंबक पूरी तरह रुकने पर विचलन का क्या होगा?",
     "A magnet is pushed steadily into a coil for 0.5 s with a steady galvanometer deflection. What happens to the deflection when the magnet stops fully?",
     ["विचलन शून्य हो जाता है", "विचलन बढ़ता है", "विचलन उलट जाता है", "विचलन दुगुना होता है"],
     ["The deflection falls to zero", "The deflection grows", "The deflection reverses", "The deflection doubles"],
     0,
     "गति बंद = क्षेत्र-परिवर्तन बंद = प्रेरित धारा शून्य।",
     "Motion stops = field change stops = zero induced current."),

    ("motor-generator-effect", "hard",
     "मोटर-जनित्र युग्मन का एक व्यावहारिक उदाहरण — रेलगाड़ी का पुनर्योजी ब्रेकिंग (regenerative braking) किस सिद्धांत पर आधारित है?",
     "Regenerative braking of trains is a practical motor-generator pairing. On what principle is it based?",
     ["चलती गाड़ी के मोटर को जनित्र की तरह चलाकर गतिज ऊर्जा विद्युत में बदलना", "घर्षण बढ़ाकर ऊष्मा बनाना", "चुंबकों से गाड़ी रोकना", "हवा से रोकना"],
     ["Running the moving vehicle's motors as generators — converting kinetic energy into electricity", "Increasing friction to make heat", "Stopping with magnets", "Stopping with air"],
     0,
     "मोटर-जनित्र द्वैत उपयोग — ऊर्जा वापस प्रणाली में।",
     "The motor-generator duality at work — energy returned to the system."),

    ("motor-generator-effect", "hard",
     "प्रेरण-प्रयोग में कुंडली के फेरे 200 से 600 किए गए (गति व चुंबक वही)। प्रेरित वोल्टेज का नया मान पुराने का लगभग कितना गुना होगा?",
     "In an induction experiment the coil's turns are raised from 200 to 600 (same magnet, same speed). The new induced voltage is about how many times the old?",
     ["3 गुना", "9 गुना", "समान", "एक-तिहाई"],
     ["3 times", "9 times", "The same", "One-third"],
     0,
     "V ∝ फेरे: 600/200 = 3।",
     "V ∝ turns: 600/200 = 3."),

    ("motor-generator-effect", "hard",
     "मोटर में विद्युत इनपुट 1000 जूल/सेकंड है और उत्पादित यांत्रिक शक्ति 800 वाट है। शेष 200 वाट कहाँ जाता है?",
     "A motor takes 1000 J/s of electrical input and yields 800 W of mechanical power. Where do the remaining 200 W go?",
     ["मुख्यतः ऊष्मा (कुंडली प्रतिरोध व घर्षण) के रूप में", "वापस बैटरी में", "प्रकाश में", "ध्वनि में पूरा"],
     ["Mostly as heat (coil resistance and friction)", "Back into the battery", "Into light", "Entirely into sound"],
     0,
     "ऊर्जा संरक्षण — अंतर ऊष्मा-हानि रूप में व्यय।",
     "Energy conservation — the difference is spent as heat loss."),

    ("motor-generator-effect", "hard",
     "एक कुंडली और गैल्वेनोमीटर के पास दो समान चुंबक विपरीत क्रम में एक साथ डाले गए (एक N-पहले, दूसरा S-पहले)। निकट गैल्वेनोमीटर का शुद्ध विचलन कैसा रहेगा?",
     "Two identical magnets are inserted together in opposite orientations (one N-first, the other S-first) near a coil with a galvanometer. What is the net deflection?",
     ["दोनों के प्रेरण प्रभाव एक-दूसरे को निरस्त करेंगे — शुद्ध विचलन लगभग शून्य", "दुगुना विचलन", "एक ही दिशा में बड़ा विचलन", "अनंत विचलन"],
     ["The two inductions cancel — net deflection nearly zero", "Double deflection", "A large one-way deflection", "Infinite deflection"],
     0,
     "विपरीत क्षेत्र-परिवर्तन एक-दूसरे को काट देते हैं।",
     "Opposite field changes cancel each other."),
]
