# -*- coding: utf-8 -*-
"""P11 part 2 — Effects of Electric Current & Energy (chapter-11).
T3 magnetic-effect-of-current (E20/M21/H9) + T4 electric-energy-and-sources (E20/M22/H8).
Tuple: (topic, difficulty, q_hi, q_en, opts_hi[4], opts_en[4], correct_idx=0, expl_hi, expl_en)
All authored with correct_idx 0; answer-position rotation happens in gen script.
Magnetic items stay at 'current's magnetic effect' (Oersted / devices) level —
deep magnetism (field lines, solenoid polarity, strength factors) belongs to P10.
"""

PART2 = [
    # ================= MAGNETIC EFFECT OF CURRENT (50) =================
    # ---- easy (20) ----
    ("magnetic-effect-of-current", "easy",
     "धारा के चुंबकीय प्रभाव की खोज किसने की?",
     "Who discovered the magnetic effect of current?",
     ["ओस्टेड ने", "न्यूटन ने", "गैलीलियो ने", "आर्किमिडीज़ ने"],
     ["Oersted", "Newton", "Galileo", "Archimedes"],
     0,
     "ओस्टेड ने देखा कि धारा बहते तार के पास कंपास सुई विचलित हो जाती है।",
     "Oersted saw a compass needle deflect near a current-carrying wire."),

    ("magnetic-effect-of-current", "easy",
     "धारावाही चालक तार के चारों ओर क्या बन जाता है?",
     "What is formed around a current-carrying conductor?",
     ["एक चुंबकीय क्षेत्र", "कोई क्षेत्र नहीं बनता", "केवल ऊष्मा", "प्रकाश किरणें"],
     ["A magnetic field", "No field is formed", "Only heat", "Light rays"],
     0,
     "गतिमान आवेश (धारा) के कारण तार के चारों ओर चुंबकीय क्षेत्र बनता है।",
     "Moving charge (current) creates a magnetic field around the wire."),

    ("magnetic-effect-of-current", "easy",
     "तार में स्विच ऑन करते ही पास रखी कंपास सुई घूम जाती है। यह किसका प्रमाण है?",
     "A nearby compass needle swings the moment a wire's switch is turned on. What is this proof of?",
     ["तार में धारा बह रही है और उसका चुंबकीय प्रभाव है", "तार बहुत गर्म है", "तार में वोल्टेज शून्य है", "कमरे में हवा चल रही है"],
     ["Current is flowing in the wire and exerting its magnetic effect", "The wire is very hot", "The wire's voltage is zero", "There is a draught in the room"],
     0,
     "कंपास का विचलन धारा के चुंबकीय प्रभाव का सीधा संकेत है।",
     "A compass deflection directly signals the magnetic effect of current."),

    ("magnetic-effect-of-current", "easy",
     "विद्युत-चुंबक किस प्रभाव पर कार्य करता है?",
     "An electromagnet works on which effect?",
     ["विद्युत धारा के चुंबकीय प्रभाव पर", "तापीय प्रभाव पर", "रासायनिक प्रभाव पर", "विद्युत अपघटन पर"],
     ["The magnetic effect of electric current", "The heating effect", "The chemical effect", "Electrolysis"],
     0,
     "कुंडली में धारा बहते ही वह चुंबक बन जाती है।",
     "The coil becomes a magnet as soon as current flows."),

    ("magnetic-effect-of-current", "easy",
     "विद्युत घंटी किस प्रभाव पर कार्य करती है?",
     "An electric bell works on which effect?",
     ["विद्युत धारा के चुंबकीय प्रभाव पर", "तापीय प्रभाव पर", "रासायनिक प्रभाव पर", "गुरुत्व प्रभाव पर"],
     ["The magnetic effect of electric current", "The heating effect", "The chemical effect", "The gravitational effect"],
     0,
     "घंटी का विद्युत-चुंबक हथौड़ा खींचता है और घंटी बजती है।",
     "An electromagnet in the bell pulls the hammer to strike the gong."),

    ("magnetic-effect-of-current", "easy",
     "रिले एक किस प्रकार का उपकरण है जो धारा के चुंबकीय प्रभाव से चलता है — इसका कार्य क्या है?",
     "A relay, a device running on the magnetic effect of current, does what job?",
     ["छोटी धारा वाले सर्किट से बड़े सर्किट का स्विच चालू-बंद करना", "पानी गर्म करना", "धातु की परत चढ़ाना", "वोल्टेज बढ़ाना"],
     ["Using a small-current circuit to switch a large circuit on and off", "Heating water", "Plating a metal", "Raising voltage"],
     0,
     "रिले का विद्युत-चुंबक संपर्क खींचकर मुख्य सर्किट जोड़ता-तोड़ता है।",
     "The relay's electromagnet moves contacts to make or break the main circuit."),

    ("magnetic-effect-of-current", "easy",
     "पंखे की मोटर में विद्युत ऊर्जा मुख्यतः किस रूप में बदलती है?",
     "In a fan's motor, electrical energy mainly converts into which form?",
     ["यांत्रिक ऊर्जा (घूर्णन)", "रासायनिक ऊर्जा", "प्रकाश ऊर्जा", "ध्वनि ऊर्जा"],
     ["Mechanical energy (rotation)", "Chemical energy", "Light energy", "Sound energy"],
     0,
     "मोटर विद्युत लेकर ब्लेड घुमाती है — विद्युत से यांत्रिक।",
     "The motor takes electricity and spins the blades — electrical to mechanical."),

    ("magnetic-effect-of-current", "easy",
     "ओस्टेड के प्रयोग में कंपास सुई को धारावाही तार के नीचे किस स्थिति में रखा गया था?",
     "In Oersted's experiment, how was the compass needle placed relative to the current-carrying wire?",
     ["तार के समानांतर (उसके नीचे)", "तार के लंबवत", "तार से बहुत दूर", "तार के ऊपर विरुद्ध दिशा में"],
     ["Parallel to the wire (below it)", "Perpendicular to the wire", "Far away from the wire", "Above the wire, in the opposite sense"],
     0,
     "समानांतर रखने पर विचलन स्पष्ट दिखता है — इसी से प्रभाव पकड़ में आया।",
     "Parallel placement makes the deflection clear — that is how the effect was caught."),

    ("magnetic-effect-of-current", "easy",
     "तार में धारा की दिशा उलट देने पर कंपास सुई का विचलन क्या होगा?",
     "If the direction of current in the wire is reversed, what happens to the compass deflection?",
     ["विचलन की दिशा भी उलट जाती है", "विचलन उतना ही रहता है, दिशा वही", "विचलन समाप्त हो जाता है", "सुई घूमना बंद कर देती है"],
     ["The deflection reverses direction too", "The deflection stays the same way", "The deflection disappears", "The needle stops turning"],
     0,
     "धारा की दिशा बदलने से चुंबकीय प्रभाव की दिशा बदल जाती है।",
     "Reversing current reverses the direction of its magnetic action."),

    ("magnetic-effect-of-current", "easy",
     "तार में धारा बंद कर देने पर उसके चारों ओर बना चुंबकीय प्रभाव का क्या होता है?",
     "What happens to the magnetic effect around a wire when the current is switched off?",
     ["वह समाप्त हो जाता है", "वह और बढ़ जाता है", "वह स्थायी रह जाता है", "वह उलट जाता है"],
     ["It disappears", "It grows further", "It becomes permanent", "It reverses"],
     0,
     "धारा रुकते ही तार एक साधारण चालक लौट आता है।",
     "Once current stops, the wire is just an ordinary conductor again."),

    ("magnetic-effect-of-current", "easy",
     "निम्न में से कौन-सा उपकरण धारा के चुंबकीय प्रभाव पर आधारित नहीं है?",
     "Which of these devices is NOT based on the magnetic effect of current?",
     ["विद्युत इस्त्री", "विद्युत घंटी", "रिले", "विद्युत मोटर"],
     ["An electric iron", "An electric bell", "A relay", "An electric motor"],
     0,
     "इस्त्री तापीय प्रभाव से गर्म होती है।",
     "An iron works by the heating effect."),

    ("magnetic-effect-of-current", "easy",
     "हीटर, विद्युत-घंटी और विद्युतलेपन टैंक — इनमें चुंबकीय प्रभाव किसमें है?",
     "A heater, an electric bell and an electroplating tank — which of these involves the magnetic effect?",
     ["विद्युत-घंटी में", "हीटर में", "विद्युतलेपन टैंक में", "तीनों में"],
     ["The electric bell", "The heater", "The electroplating tank", "All three"],
     0,
     "हीटर = तापीय, लेपन = रासायनिक, घंटी = चुंबकीय प्रभाव।",
     "Heater = heating, plating = chemical, bell = magnetic effect."),

    ("magnetic-effect-of-current", "easy",
     "विद्युत घंटी में हथौड़ा घंटी से टकराता है — इसे खींचने का काम कौन करता है?",
     "In an electric bell the hammer strikes the gong — what pulls it?",
     ["विद्युत-चुंबक, जब धारा बहती है", "स्थायी चुंबक, बिना धारा के", "स्प्रिंग ही", "गुरुत्वाकर्षण"],
     ["The electromagnet, while current flows", "A permanent magnet, without any current", "Only the spring", "Gravity"],
     0,
     "धारा बहते ही विद्युत-चुंबक आर्मेचर-हथौड़े को खींचता है।",
     "As current flows, the electromagnet pulls the armature-hammer."),

    ("magnetic-effect-of-current", "easy",
     "धारावाही तार के पास कंपास सुई का विचलन बढ़ाने के लिए धारा की मात्रा कैसी चाहिए?",
     "To increase the deflection of a compass near a current-carrying wire, how should the current change?",
     ["धारा बढ़ानी चाहिए", "धारा घटानी चाहिए", "धारा बंद कर देनी चाहिए", "धारा का विचलन से कोई संबंध नहीं"],
     ["The current should be increased", "The current should be decreased", "The current should be switched off", "Current has no relation to deflection"],
     0,
     "धारा जितनी अधिक, चुंबकीय प्रभाव उतना प्रबल — विचलन बढ़ता है।",
     "More current, stronger magnetic action — larger deflection."),

    ("magnetic-effect-of-current", "easy",
     "मोटर किस प्रभाव के आधार पर घूर्णन देती है?",
     "On the basis of which effect does a motor produce rotation?",
     ["चुंबकीय प्रभाव — चुंबकीय क्षेत्र में धारावाही कुंडली पर बल", "तापीय प्रभाव", "रासायनिक प्रभाव", "गुरुत्वीय प्रभाव"],
     ["The magnetic effect — force on a current-carrying coil in a magnetic field", "The heating effect", "The chemical effect", "The gravitational effect"],
     0,
     "क्षेत्र में धारावाही कुंडली बल अनुभव करती है और घूमने लगती है।",
     "A current-carrying coil in a field experiences force and spins."),

    ("magnetic-effect-of-current", "easy",
     "धारा के चुंबकीय प्रभाव का मूल कारण क्या है?",
     "What is the root cause of the magnetic effect of current?",
     ["आवेशों की गति (प्रवाह)", "आवेशों का विराम", "तार का रंग", "तार की मोटाई"],
     ["The motion (flow) of charges", "Charges at rest", "The colour of the wire", "The thickness of the wire"],
     0,
     "गतिमान आवेश ही चुंबकीय प्रभाव पैदा करते हैं।",
     "Moving charges alone create the magnetic effect."),

    ("magnetic-effect-of-current", "easy",
     "कंपास-विचलन पर आधारित सरल 'धारा-संसूचक' क्या बताता है?",
     "A simple compass-deflection 'current detector' tells us what?",
     ["परिपथ में धारा बह रही है या नहीं", "धारा का ठीक मान एम्पियर में", "वोल्टेज का मान", "प्रतिरोध का मान"],
     ["Whether current is flowing in the circuit or not", "The exact value of current in amperes", "The value of voltage", "The value of resistance"],
     0,
     "विचलन दिखे तो धारा है — यह गुणात्मक परीक्षण है, माप नहीं।",
     "A deflection means current flows — a qualitative test, not a measurement."),

    ("magnetic-effect-of-current", "easy",
     "धारा के तीन प्रभावों में से कौन-सा प्रभाव विद्युत घंटी, रिले और मोटर को एक साथ चलाता है?",
     "Which one of the three effects of current runs the electric bell, relay and motor together?",
     ["चुंबकीय प्रभाव", "तापीय प्रभाव", "रासायनिक प्रभाव", "कोई प्रभाव नहीं"],
     ["The magnetic effect", "The heating effect", "The chemical effect", "No effect"],
     0,
     "तीनों उपकरण धारा के चुंबकीय प्रभाव पर कार्य करते हैं।",
     "All three devices work on the magnetic effect of current."),

    ("magnetic-effect-of-current", "easy",
     "विद्युत-चुंबक बनाम स्थायी चुंबक — घंटी जैसे उपकरण में विद्युत-चुंबक का विशेष लाभ क्या है?",
     "Electromagnet vs permanent magnet — what is the special advantage of an electromagnet in a device like a bell?",
     ["धारा चालू/बंद करके उसका आकर्षण चालू/बंद किया जा सकता है", "उसे बिना बिजली चलाया जा सकता है", "वह कभी कमज़ोर नहीं होता", "वह सस्ता चुंबक है"],
     ["Its attraction can be switched on/off with the current", "It can be run without electricity", "It never weakens", "It is a cheap magnet"],
     0,
     "बार-बंद आकर्षण से ही हथौड़ा बार-बार टकराता है — यही स्थायी चुंबक नहीं कर सकता।",
     "Repeated on/off attraction lets the hammer strike repeatedly — a permanent magnet can't."),

    ("magnetic-effect-of-current", "easy",
     "साधारण घंटी सर्किट में बटन दबाते ही धारा का क्या होता है?",
     "In a simple bell circuit, what happens to the current when the button is pressed?",
     ["परिपथ पूर्ण होकर धारा बहने लगती है", "धारा उलट दिशा में बहती है", "धारा वोल्टेज बढ़ा देती है", "धारा पूरी रुक जाती है"],
     ["The circuit completes and current starts flowing", "The current flows backwards", "The current raises the voltage", "The current stops entirely"],
     0,
     "बटन दबाने से सर्किट बंद होता है — धारा बहती है, विद्युत-चुंबक काम करता है।",
     "Pressing the button closes the circuit — current flows, the electromagnet acts."),

    # ---- medium (21) ----
    ("magnetic-effect-of-current", "medium",
     "ओस्टेड की खोज का वैज्ञानिक महत्व क्या रहा?",
     "What was the scientific importance of Oersted's discovery?",
     ["इससे विद्युत और चुंबकत्व का अंतर्संबंध स्थापित हुआ", "इससे गुरुत्वाकर्षण का नियम बना", "इससे प्रकाश की चाल निकली", "इससे ऊष्मा का नियम बना"],
     ["It established the connection between electricity and magnetism", "It produced the law of gravitation", "It found the speed of light", "It made the law of heat"],
     0,
     "पहली बार सिद्ध हुआ कि विद्युत धारा चुंबकीय प्रभाव उत्पन्न करती है।",
     "It was first proved that electric current produces magnetic action."),

    ("magnetic-effect-of-current", "medium",
     "विद्युत-चुंबक बनाते समय तार को कुंडली (कॉइल) के रूप में क्यों लपेटा जाता है?",
     "Why is the wire wound as a coil while making an electromagnet?",
     ["कुंडली के फेरों के चुंबकीय प्रभाव जुड़कर क्षेत्र को मजबूत बनाते हैं", "कुंडली से तार सुंदर दिखता है", "कुंडली में प्रतिरोध शून्य हो जाता है", "कुंडली धारा रोक देती है"],
     ["The magnetic actions of the coil's turns add up and strengthen the field", "The coil looks neat", "The coil's resistance becomes zero", "The coil blocks current"],
     0,
     "कई फेरों के प्रभाव संचित होते हैं — कुंडली विद्युत-चुंबक का आधार है।",
     "Many turns stack their effects — the coil is the basis of an electromagnet."),

    ("magnetic-effect-of-current", "medium",
     "रिले का उपयोग उद्योगों में स्वचालन और सुरक्षा में क्यों होता है?",
     "Why are relays used for automation and safety in industries?",
     ["कम धारा वाले नियंत्रण सर्किट सुरक्षित रहते हैं, जो बड़ी धारा वाले मुख्य उपकरण को चालू-बंद करते हैं", "रिले से बिजली बनती है", "रिले धातु चढ़ाता है", "रिले पानी गर्म करता है"],
     ["A low-current control circuit stays safe while switching high-current main equipment", "A relay generates electricity", "A relay plates metals", "A relay heats water"],
     0,
     "ऑपरेटर छोटे सर्किट से ही बड़े मोटर आदि चलाता है — सुरक्षित स्वचालन।",
     "The operator runs big motors through a small circuit — safe automation."),

    ("magnetic-effect-of-current", "medium",
     "विद्युत घंटी की सही क्रियाविधि का क्रम क्या है?",
     "What is the correct sequence of an electric bell's working?",
     ["बटन दबा → धारा → विद्युत-चुंबक → हथौड़ा टकराया → घंटी बजी", "बटन दबा → तार गरम → घंटी बजी", "बटन दबा → विलयन अपघटित → घंटी बजी", "बटन दबा → धारा उलटी → घंटी बजी"],
     ["Button pressed → current → electromagnet → hammer strikes → bell rings", "Button pressed → wire heats → bell rings", "Button pressed → solution decomposes → bell rings", "Button pressed → current reverses → bell rings"],
     0,
     "चुंबकीय प्रभाव ही हथौड़े को गति देता है।",
     "The magnetic action is what moves the hammer."),

    ("magnetic-effect-of-current", "medium",
     "किसी विद्युत-चुंबक की कुंडली में धारा की दिशा उलट दें तो उसके ध्रुवों का क्या होगा?",
     "If the current direction in an electromagnet's coil is reversed, what happens to its poles?",
     ["ध्रुव आपस में बदल जाते हैं (N↔S)", "ध्रुव वही रहते हैं", "चुंबकत्व समाप्त हो जाता है", "दोनों ध्रुव उत्तरी बन जाते हैं"],
     ["The poles swap (N↔S)", "The poles stay the same", "The magnetism vanishes", "Both poles become north"],
     0,
     "धारा की दिशा बदलने पर क्षेत्र की दिशा उलट जाती है।",
     "Reversing current reverses the field direction."),

    ("magnetic-effect-of-current", "medium",
     "मोटर की कुंडली घूमने का अंतिम कारण क्या है?",
     "What is the ultimate cause of a motor coil's rotation?",
     ["चुंबकीय क्षेत्र में धारावाही कुंडली पर लगने वाला बल", "कुंडली का गर्म होना", "कुंडली में रासायनिक अभिक्रिया", "कुंडली का गुरुत्व से गिरना"],
     ["The force experienced by a current-carrying coil in a magnetic field", "The coil getting hot", "A chemical reaction in the coil", "The coil falling under gravity"],
     0,
     "चुंबकीय प्रभाव से मिलने वाला बल ही घूर्णन बनाता है।",
     "The force from the magnetic effect is what creates the rotation."),

    ("magnetic-effect-of-current", "medium",
     "कारण-प्रभाव मिलाइए: मोटर चालू होते ही शाफ्ट घूमने लगती है, क्योंकि —",
     "Match cause and effect: the shaft starts spinning as soon as the motor is switched on, because —",
     ["धारावाही कुंडली पर चुंबकीय क्षेत्र से बल लगता है", "कुंडली में विलयन जमा होता है", "कुंडली पिघल जाती है", "बैटरी ठंडी हो जाती है"],
     ["A force acts on the current-carrying coil from the magnetic field", "A solution deposits in the coil", "The coil melts", "The battery cools down"],
     0,
     "धारा + क्षेत्र = बल = घूर्णन।",
     "Current + field = force = rotation."),

    ("magnetic-effect-of-current", "medium",
     "दो कथन: (i) धारावाही तार के चारों ओर चुंबकीय क्षेत्र होता है। (ii) धारा बंद होने पर यह क्षेत्र समाप्त हो जाता है। सही विकल्प:",
     "Two statements: (i) There is a magnetic field around a current-carrying wire. (ii) When the current stops, this field vanishes. The correct option:",
     ["दोनों सही हैं", "केवल (i) सही", "केवल (ii) सही", "दोनों गलत"],
     ["Both are correct", "Only (i)", "Only (ii)", "Both wrong"],
     0,
     "क्षेत्र धारा पर निर्भर — धारा है तो क्षेत्र है।",
     "The field depends on current — current present, field present."),

    ("magnetic-effect-of-current", "medium",
     "कंपास सुई के नीचे तार उत्तर-दक्षिण दिशा में रखा है। विचलन सबसे स्पष्ट कब दिखेगा?",
     "A wire lies north-south just below a compass needle. When is the deflection seen most clearly?",
     ["जब तार और सुई शुरुआत में समानांतर हों और धारा पर्याप्त हो", "जब तार सुई के लंबवत हो", "जब धारा बहुत कम हो", "जब तार में कोई धारा न हो"],
     ["When wire and needle start parallel and the current is sufficient", "When the wire is perpendicular to the needle", "When the current is very small", "When no current flows"],
     0,
     "समानांतर अवस्था में तार का क्षेत्र सुई को सबसे अच्छा घुमाता है।",
     "In the parallel position the wire's field turns the needle best."),

    ("magnetic-effect-of-current", "medium",
     "उपकरण-प्रभाव मिलान में गलत जोड़ी कौन-सी है?",
     "Which device-effect pairing is WRONG?",
     ["रिले — रासायनिक प्रभाव", "हीटर — तापीय प्रभाव", "घंटी — चुंबकीय प्रभाव", "विद्युतलेपन — रासायनिक प्रभाव"],
     ["Relay — chemical effect", "Heater — heating effect", "Bell — magnetic effect", "Electroplating — chemical effect"],
     0,
     "रिले चुंबकीय प्रभाव पर चलता है, रासायनिक पर नहीं।",
     "A relay runs on the magnetic effect, not the chemical one."),

    ("magnetic-effect-of-current", "medium",
     "कबाड़खाने में लोहे के टुकड़े उठाने और छोड़ने के लिए कौन-सा चुंबक सबसे उपयुक्त है?",
     "Which magnet is most suitable for lifting and dropping iron pieces in a scrapyard?",
     ["विद्युत-चुंबक — धारा बंद करते ही टुकड़े छूट जाते हैं", "स्थायी चुंबक — कभी नहीं छोड़ेगा", "कोई चुंबक नहीं", "चुंबकीय अयस्क"],
     ["An electromagnet — switch off the current and the pieces drop", "A permanent magnet — it never lets go", "No magnet", "Magnetic ore"],
     0,
     "धारा ऑफ करने पर आकर्षण समाप्त — ढेर जहाँ चाहें छोड़ दें।",
     "Current off, attraction gone — drop the load wherever needed."),

    ("magnetic-effect-of-current", "medium",
     "विद्युत घंटी लगातार बजती रहती है बिना रुके। इसकी क्रियाविधि में निरंतरता किससे आती है?",
     "An electric bell keeps ringing continuously. What gives this continuity in its mechanism?",
     ["संपर्क बार-बार बनता-टूटता है, जिससे विद्युत-चुंबक बार-बार हथौड़ा खींचता है", "बैटरी बार-बार बदली जाती है", "घंटी में पानी भरा रहता है", "हथौड़े में विलयन रहता है"],
     ["The contact repeatedly makes and breaks, so the electromagnet pulls the hammer again and again", "The battery is replaced repeatedly", "The bell stays filled with water", "The hammer holds a solution"],
     0,
     "आर्मेचर के झूलने से सर्किट बार-बार बनता-टूटता है।",
     "The swinging armature breaks and remakes the circuit — ding-dong! Joining this completes the answer."),

    ("magnetic-effect-of-current", "medium",
     "घंटी के सर्किट में धारा की दिशा उलट दी जाए तो घंटी का क्या होगा?",
     "If the current direction in a bell's circuit is reversed, what happens to the bell?",
     ["घंटी फिर भी बजेगी — विद्युत-चुंबक दोनों दिशाओं में आकर्षित करता है", "घंटी बंद हो जाएगी", "घंटी उलटी आवाज़ करेगी", "घंटी पिघल जाएगी"],
     ["The bell still rings — an electromagnet attracts either way", "The bell stops", "The bell rings backwards", "The bell melts"],
     0,
     "आकर्षण ध्रुव-निरपेक्ष होता है; दिशा बदलने से आकर्षण नहीं रुकता।",
     "The attraction is pole-agnostic; reversing current doesn't stop it."),

    ("magnetic-effect-of-current", "medium",
     "तीन उपकरण — इस्त्री, विद्युत-घंटी, विद्युतलेपन — इनके प्रभावों का सही क्रम है:",
     "Three devices — iron, electric bell, electroplating — the correct order of their effects is:",
     ["तापीय, चुंबकीय, रासायनिक", "रासायनिक, तापीय, चुंबकीय", "चुंबकीय, रासायनिक, तापीय", "तीनों तापीय"],
     ["Heating, magnetic, chemical", "Chemical, heating, magnetic", "Magnetic, chemical, heating", "All heating"],
     0,
     "उद्देश्य से प्रभाव पहचानें — यही परीक्षा का पक्का प्रश्न है।",
     "Identify the effect from the purpose — a classic exam ask."),

    ("magnetic-effect-of-current", "medium",
     "रिले के भीतर विद्युत-चुंबक बना होता है। यह किस काम आता है?",
     "A relay contains an electromagnet. What does it do there?",
     ["धारा बहते ही वह संपर्क-पट्टी खींचकर मुख्य सर्किट जोड़ देता है", "वह तार गर्म करता है", "वह विलयन अपघटित करता है", "वह बैटरी चार्ज करता है"],
     ["As current flows it pulls the contact strip and closes the main circuit", "It heats the wires", "It decomposes a solution", "It charges the battery"],
     0,
     "विद्युत-चुंबक का खिंचाव ही रिले की स्विचिंग है।",
     "The electromagnet's pull is the relay's switching action."),

    ("magnetic-effect-of-current", "medium",
     "प्रयोग: तार के ऊपर कंपास रखा, स्विच ऑन किया, सुई विचलित हुई; स्विच ऑफ करते ही सुई वापस उत्तर-दक्षिण में आ गई। निष्कर्ष क्या है?",
     "Experiment: a compass over a wire deflects when the switch is on and returns to north-south when switched off. What is the conclusion?",
     ["तार का चुंबकीय प्रभाव धारा पर निर्भर है", "तार स्थायी चुंबक बन गया", "कंपास खराब है", "धारा से कोई प्रभाव नहीं"],
     ["The wire's magnetic effect depends on the current", "The wire became a permanent magnet", "The compass is faulty", "Current has no effect"],
     0,
     "धारा आते-जाते क्षेत्र आता-जाता है — नियंत्रण धारा के हाथ में।",
     "Field comes and goes with the current — the current is in control."),

    ("magnetic-effect-of-current", "medium",
     "मोटर और विद्युत घंटी में क्या समानता है?",
     "What is common between a motor and an electric bell?",
     ["दोनों धारा के चुंबकीय प्रभाव पर कार्य करते हैं", "दोनों में विलयन होता है", "दोनों रासायनिक प्रभाव से चलते हैं", "दोनों में फ्यूज़ होता है"],
     ["Both work on the magnetic effect of current", "Both contain a solution", "Both run on the chemical effect", "Both contain a fuse"],
     0,
     "चुंबकीय प्रभाव से ही एक घुमाता है, दूसरा बजाता है।",
     "The magnetic effect makes one spin and the other ring."),

    ("magnetic-effect-of-current", "medium",
     "किसी तार को कंपास के चारों ओर लपेटकर प्रयोग किया जाए तो विचलन एकल सीधे तार की तुलना में कैसा होगा?",
     "If a wire is wound several times around a compass for the experiment, how is the deflection compared with a single straight wire?",
     ["अधिक — कई फेरों के प्रभाव जुड़ जाते हैं", "कम", "समान", "शून्य"],
     ["Larger — the effects of several turns add up", "Smaller", "The same", "Zero"],
     0,
     "फेरे बढ़ाने से उसी धारा का चुंबकीय प्रभाव तेज होता है।",
     "More turns amplify the magnetic action of the same current."),

    ("magnetic-effect-of-current", "medium",
     "धारा की उपस्थिति कंपास-विचलन से पकड़ी जा सकती है। टूटे (खुले) परिपथ में यह परीक्षण क्या दिखाएगा?",
     "The presence of current can be detected by compass deflection. What will this test show in a broken (open) circuit?",
     ["कोई विचलन नहीं — धारा बह नहीं रही", "बड़ा विचलन", "उलटा विचलन", "सुई घूमती रहेगी"],
     ["No deflection — no current is flowing", "A large deflection", "A reversed deflection", "The needle keeps spinning"],
     0,
     "खुला परिपथ = शून्य धारा = शून्य चुंबकीय प्रभाव।",
     "Open circuit = zero current = zero magnetic action."),

    ("magnetic-effect-of-current", "medium",
     "विद्युत-चुंबक का उपयोग करने वाली घंटी में वसंत-स्प्रिंग का कार्य क्या है?",
     "In a bell using an electromagnet, what is the role of the return spring?",
     ["धारा टूटते ही हथौड़े को वापस खींचना, ताकि संपर्क बने और चक्र दोहराए", "हथौड़े को गर्म करना", "घंटी को रंगना", "धारा का मान नापना"],
     ["To pull the hammer back when current breaks, so contact remakes and the cycle repeats", "To heat the hammer", "To colour the bell", "To measure current"],
     0,
     "स्प्रिंग का वापसी-झटका ही टन-टन की लय बनाता है।",
     "The spring's return kick sets the ding-dong rhythm."),

    ("magnetic-effect-of-current", "medium",
     "एक उपकरण में विद्युत-चुंबक और वापसी-स्प्रिंग दोनों का प्रयोग होता है। यह उपकरण और कारण कौन-सा है?",
     "A device uses both an electromagnet and a return spring. Which device and reason is it?",
     ["विद्युत घंटी — चुंबक खींचता है, स्प्रिंग छोड़ता है, इससे हथौड़ा बार-बार टकराता है", "विद्युत इस्त्री — स्प्रिंग ताप बढ़ाती है", "फ्यूज़ — स्प्रिंग तार पिघलाती है", "हीटर — स्प्रिंग ऊष्मा बाँटती है"],
     ["An electric bell — the magnet pulls, the spring releases, so the hammer strikes repeatedly", "An electric iron — the spring raises the temperature", "A fuse — the spring melts the wire", "A heater — the spring distributes heat"],
     0,
     "खींचना और छोड़ना दोनों चाहिए — तभी बार-बार ध्वनि बनती है।",
     "Both pull and release are needed — only then does repeated striking occur."),

    # ---- hard (9) ----
    ("magnetic-effect-of-current", "hard",
     "ओस्टेड के प्रयोग में विचलन क्यों होता है — भौतिक रूप से क्या जुड़ता है?",
     "Why does deflection occur in Oersted's experiment — what physically combines?",
     ["पृथ्वी के क्षेत्र और तार के चुंबकीय क्षेत्र का अध्यारोपण, जिससे अनुतुलित घूर्णन बल बनता है", "तार की ऊष्मा से सुई फैलती है", "तार का रंग सुई पर पड़ता है", "तार का गुरुत्व सुई खींचता है"],
     ["Superposition of the earth's field and the wire's magnetic field, creating an unbalanced turning force", "The wire's heat expands the needle", "The wire's colour affects the needle", "The wire's gravity pulls the needle"],
     0,
     "दो क्षेत्रों के मिलान से लौह सुई पर शुद्ध बल-आघूर्ण आता है।",
     "The two fields combine to give the steel needle a net torque."),

    ("magnetic-effect-of-current", "hard",
     "कंपास-विचलन आधारित धारा-संसूचक से टूटे तार वाले परिपथ की पहचान कैसे होती है?",
     "How can a compass-deflection current detector identify a circuit with a broken wire?",
     ["जहाँ विचलन बिल्कुल नहीं मिलता, वहाँ धारा पथ टूटा है — क्रम से जाँचकर स्थान पकड़ा जाता है", "विचलन जहाँ सबसे तेज है वहीं तार टूटा है", "सुई उलट घूमती है", "यह संसूचक टूटा तार नहीं पकड़ सकता"],
     ["Where no deflection appears, the current path is broken — checking in sequence locates it", "The break is where deflection is strongest", "The needle spins backwards", "This detector cannot find a break"],
     0,
     "धारा-पथ के साथ-साथ जाँच से मौन-बिंदु ही टूटन का संकेत देता है।",
     "Moving along the path, the silent point marks the break."),

    ("magnetic-effect-of-current", "hard",
     "रिले बनाम फ्यूज़ — दोनों सर्किट में काम आते हैं। इनकी भूमिकाओं में अंतर है:",
     "Relay vs fuse — both serve circuits. Their roles differ:",
     ["फ्यूज़ अधिक धारा पर सुरक्षा से सर्किट काटता है; रिले चुंबकीय प्रभाव से स्विचिंग करता है", "दोनों एक ही काम करते हैं", "फ्यूज़ स्विचिंग करता है, रिले पिघलता है", "दोनों धातु चढ़ाते हैं"],
     ["A fuse cuts the circuit for safety on excess current; a relay does switching via the magnetic effect", "Both do the same job", "A fuse switches, a relay melts", "Both plate metals"],
     0,
     "फ्यूज़ = तापीय प्रभाव से रक्षा; रिले = चुंबकीय प्रभाव से नियंत्रण।",
     "Fuse = protection via heating effect; relay = control via magnetic effect."),

    ("magnetic-effect-of-current", "hard",
     "विद्युत घंटी की आर्मेचर पट्टी किस धातु की बनाई जाती है और क्यों?",
     "The armature strip of an electric bell is made of which metal and why?",
     ["नरम लोहे की — आसानी से चुंबकित होकर तुरंत हथौड़ा खींचती है और धारा टूटते ही चुंबकत्व छोड़ देती है", "तांबे की — वह चुंबकित नहीं होता, फिर भी खिंचती है", "एल्युमिनियम की — हल्की है", "प्लास्टिक की — कुचालक है"],
     ["Soft iron — it magnetises easily to pull the hammer at once and drops its magnetism the moment current breaks", "Copper — it does not magnetise yet still pulls", "Aluminium — it is light", "Plastic — it is an insulator"],
     0,
     "नरम लोहे की त्वरित चुंबकन-विचुंबकन ही घंटी की तेज लय बनाती है।",
     "Soft iron's quick magnetise-demagnetise makes the bell brisk."),

    ("magnetic-effect-of-current", "hard",
     "यदि किसी कारण मोटर की कुंडली पर चुंबकीय बल ही न लगे, तो क्या होगा?",
     "If, for some reason, no magnetic force acts on a motor's coil, what happens?",
     ["कुंडली घूमेगी नहीं — धारा बहे तब भी घूर्णन नहीं", "मोटर और तेज घुमेगी", "मोटर पिघल जाएगी", "मोटर बिजली बनाने लगेगी"],
     ["The coil will not rotate — no rotation even if current flows", "The motor spins faster", "The motor melts", "The motor starts generating electricity"],
     0,
     "घूर्णन का एकमात्र स्रोत चुंबकीय बल है।",
     "The sole source of rotation is the magnetic force."),

    ("magnetic-effect-of-current", "hard",
     "तीन कथन: (i) ओस्टेड ने धारा का चुंबकीय प्रभाव खोजा। (ii) धारा बंद होने पर भी तार का चुंबकीय क्षेत्र बना रहता है। (iii) रिले चुंबकीय प्रभाव से कार्य करता है। गलत कथन कौन-सा है?",
     "Three statements: (i) Oersted discovered the magnetic effect of current. (ii) The wire's magnetic field persists even when the current is off. (iii) A relay works by the magnetic effect. Which is wrong?",
     ["कथन (ii)", "कथन (i)", "कथन (iii)", "तीनों सही"],
     ["Statement (ii)", "Statement (i)", "Statement (iii)", "All three correct"],
     0,
     "धारा रुकते ही क्षेत्र समाप्त — (ii) गलत है।",
     "The field ends when current stops — (ii) is wrong."),

    ("magnetic-effect-of-current", "hard",
     "कंपास सुई का विचलन उलटने के दो अलग तरीके कौन-से हैं?",
     "What are two distinct ways to reverse a compass needle's deflection?",
     ["तार में धारा की दिशा उलटना, या कंपास को तार के दूसरी ओर रखना", "धारा बढ़ाना या घटाना", "तार मोटा करना या पतला करना", "स्विच ऑन करना या ऑफ करना"],
     ["Reverse the current's direction, or place the compass on the other side of the wire", "Increase or decrease the current", "Thicken or thin the wire", "Switch on or off"],
     0,
     "दिशा-परिवर्तन या ओर-परिवर्तन — दोनों से शुद्ध क्षेत्र-योग उलट जाता है।",
     "Flip direction or flip side — either reverses the net field sum."),

    ("magnetic-effect-of-current", "hard",
     "एक विद्युत-घंटी बज ही नहीं रही। बटन दबाने पर भी कोई खट-खट नहीं। सबसे संभावित भौतिक कारण क्या हो सकता है?",
     "An electric bell is not ringing at all — no clatter even on pressing the button. What is the most likely physical cause?",
     ["परिपथ में कहीं धारा ही नहीं बह रही (टूटा तार/खस्ता संपर्क), इसलिए विद्युत-चुंबक बनता ही नहीं", "घंटी बहुत नई है", "हथौड़ा बहुत चिकना है", "कमरे में रोशनी कम है"],
     ["No current flows anywhere in the circuit (broken wire/loose contact), so the electromagnet never forms", "The bell is too new", "The hammer is too smooth", "The room is dimly lit"],
     0,
     "धारा नहीं = चुंबकत्व नहीं = हथौड़ा नहीं — सर्वप्रथम धारा-पथ जाँचें।",
     "No current = no magnetism = no hammer — check the current path first."),

    ("magnetic-effect-of-current", "hard",
     "जल-विद्युत संयंत्र से चलने वाले विद्युत पंखे की पूरी ऊर्जा-श्रृंखला क्या है?",
     "What is the full energy chain of an electric fan running from a hydro power plant?",
     ["जल की स्थितिज ऊर्जा → विद्युत ऊर्जा → पंखे की यांत्रिक ऊर्जा", "विद्युत ऊर्जा → जल की स्थितिज ऊर्जा → यांत्रिक ऊर्जा", "रासायनिक ऊर्जा → प्रकाश ऊर्जा → ऊष्मा", "यांत्रिक ऊर्जा → ऊष्मा → प्रकाश"],
     ["Potential energy of water → electrical energy → mechanical energy of the fan", "Electrical energy → potential energy of water → mechanical energy", "Chemical energy → light energy → heat", "Mechanical energy → heat → light"],
     0,
     "बांध का पानी → जनित्र → मोटर — क्रम यही है।",
     "Dam water → generator → motor — that is the order."),

    # ================= ELECTRIC ENERGY AND SOURCES (50) =================
    # ---- easy (20) ----
    ("electric-energy-and-sources", "easy",
     "निम्न में से कौन-सा नवीनीकरणीय ऊर्जा स्रोत है?",
     "Which of the following is a renewable source of energy?",
     ["सौर ऊर्जा", "कोयला", "पेट्रोल", "प्राकृतिक गैस"],
     ["Solar energy", "Coal", "Petrol", "Natural gas"],
     0,
     "सूरज की ऊर्जा खत्म नहीं होती — यह पुनः उपलब्ध रहती है।",
     "The sun's energy does not run out — it keeps renewing."),

    ("electric-energy-and-sources", "easy",
     "कोयला किस वर्ग का ऊर्जा स्रोत है?",
     "Coal belongs to which class of energy sources?",
     ["अनवीनीकरणीय (जीवाश्म ईंधन)", "नवीनीकरणीय", "असीमित", "कृत्रिम"],
     ["Non-renewable (fossil fuel)", "Renewable", "Unlimited", "Artificial"],
     0,
     "कोयला लाखों वर्षों में बना और सीमित भंडार में है।",
     "Coal formed over millions of years and its stock is limited."),

    ("electric-energy-and-sources", "easy",
     "जीवाश्म ईंधनों का उदाहरण कौन-सा युग्म है?",
     "Which pair are examples of fossil fuels?",
     ["कोयला और पेट्रोलियम", "पवन और सौर", "जल और बायोगैस", "ज्वारीय और भूतापीय"],
     ["Coal and petroleum", "Wind and solar", "Hydro and biogas", "Tidal and geothermal"],
     0,
     "जीवाश्म ईंधन प्राचीन जीवों से बने — कोयला, पेट्रोल, गैस।",
     "Fossil fuels came from ancient organisms — coal, petrol, gas."),

    ("electric-energy-and-sources", "easy",
     "सौर ऊर्जा से सीधे विद्युत बनाने वाला यंत्र क्या कहलाता है?",
     "What is the device that converts solar energy directly into electricity called?",
     ["सौर सेल (सोलर पैनल)", "पवन चक्की", "टरबाइन", "जनित्र"],
     ["A solar cell (solar panel)", "A windmill", "A turbine", "A dynamo"],
     0,
     "सौर सेल प्रकाश ऊर्जा को सीधे विद्युत में बदलता है।",
     "A solar cell converts light energy straight into electricity."),

    ("electric-energy-and-sources", "easy",
     "पवन ऊर्जा से विद्युत पैदा करने वाला संयंत्र किस पर आधारित है?",
     "A plant generating electricity from wind energy is based on what?",
     ["चलती हवा से घूमती पवन चक्की (टरबाइन)", "गर्म पानी की भाप", "बांध का पानी", "गोबर का गैस"],
     ["A wind turbine spun by moving air", "Hot water steam", "Dam water", "Dung gas"],
     0,
     "हवा की गतिज ऊर्जा चक्की घुमाकर जनित्र चलाती है।",
     "Wind's kinetic energy spins the turbine driving a generator."),

    ("electric-energy-and-sources", "easy",
     "जल-विद्युत उत्पादन में जनित्र किससे घुमाया जाता है?",
     "In hydro electricity generation, what drives the generator?",
     ["बांध से गिरते पानी से घूमती टरबाइन", "कोयले की भट्टी से", "हवा की चक्की से", "डीज़ल इंजन से"],
     ["A turbine spun by water falling from a dam", "A coal furnace", "A windmill", "A diesel engine"],
     0,
     "ऊँचाई से गिरता पानी टरबाइन घुमाता है।",
     "Water falling from height spins the turbine."),

    ("electric-energy-and-sources", "easy",
     "बायोगैस मुख्यतः किससे बनती है?",
     "Biogas is mainly produced from what?",
     ["पशुओं के गोबर और जैविक कचरे के अपघटन से", "पत्थर तोड़कर", "समुद्री लहरों से", "कोयला जलाकर"],
     ["Decomposition of animal dung and organic waste", "Crushing stones", "Sea waves", "Burning coal"],
     0,
     "गोबर-गैस संयंत्र में कचरा किण्वित होकर दहनशील गैस देता है।",
     "In a dung-gas plant waste ferments into burnable gas."),

    ("electric-energy-and-sources", "easy",
     "भूतापीय ऊर्जा का स्रोत क्या है?",
     "What is the source of geothermal energy?",
     ["पृथ्वी के भीतर की गर्मी (गर्म जल/भाप)", "चाँद का प्रकाश", "हवा की गति", "नदियों का पानी"],
     ["Heat within the earth (hot water/steam)", "Moonlight", "Moving air", "River water"],
     0,
     "गहराई की गर्मी से भाप निकलकर टरबाइन चला सकती है।",
     "Steam from deep underground heat can run turbines."),

    ("electric-energy-and-sources", "easy",
     "नवीनीकरणीय स्रोतों की ओर जाना क्यों जरूरी है?",
     "Why is the shift to renewable sources necessary?",
     ["जीवाश्म ईंधन सीमित हैं और एक दिन खत्म हो जाएँगे", "क्योंकि वे महँगे हैं", "क्योंकि वे घरों में आसानी से बनते हैं", "क्योंकि वे नए हैं"],
     ["Fossil fuels are limited and will one day run out", "Because they are costly", "Because they can be produced easily at home", "Because they are new"],
     0,
     "भंडार सीमित — माँग बढ़ती है, इसलिए विकल्प जरूरी।",
     "The stock is finite while demand grows — alternatives are essential."),

    ("electric-energy-and-sources", "easy",
     "सौर कुकर किस ऊर्जा का उपयोग करता है?",
     "A solar cooker uses which energy?",
     ["सूर्य के प्रकाश/ऊष्मा की", "कोयले की", "पवन की", "परमाणु की"],
     ["The sun's light/heat", "Coal", "Wind", "Nuclear"],
     0,
     "सौर कुकर सूर्य-ताप से भोजन पकाता है — ईंधन शून्य।",
     "A solar cooker cooks with sun-heat — zero fuel."),

    ("electric-energy-and-sources", "easy",
     "ऊर्जा स्रोतों के वर्गीकरण के दो वर्ग कौन-से हैं?",
     "What are the two classes in the classification of energy sources?",
     ["नवीनीकरणीय और अनवीनीकरणीय", "घरेलू और विदेशी", "सस्ते और महँगे", "तरल और ठोस"],
     ["Renewable and non-renewable", "Domestic and foreign", "Cheap and costly", "Liquid and solid"],
     0,
     "पुनः भरने की क्षमता ही वर्गीकरण का आधार है।",
     "The ability to replenish is the basis of classification."),

    ("electric-energy-and-sources", "easy",
     "पेट्रोल को अनवीनीकरणीय क्यों कहा जाता है?",
     "Why is petrol called non-renewable?",
     ["यह लाखों वर्षों में बनता है, माँग की गति से दोबारा नहीं बन सकता", "यह बहुत महँगा है", "यह तरल है", "यह गाड़ियों में जलता है"],
     ["It forms over millions of years — far too slow to renew against demand", "It is very costly", "It is a liquid", "It burns in vehicles"],
     0,
     "बनने की गति खपत से अत्यंत मंद — इसलिए अनवीनीकरणीय।",
     "Its formation rate is far slower than consumption — hence non-renewable."),

    ("electric-energy-and-sources", "easy",
     "विद्युत ऊर्जा घरों तक कैसे पहुँचती है?",
     "How does electrical energy reach homes?",
     ["ऊर्जा संयंत्रों से तारों (पारेषण लाइनों) द्वारा", "ट्रकों से", "रेडियो तरंगों से", "नदियों से"],
     ["Via wires (transmission lines) from power plants", "By trucks", "By radio waves", "By rivers"],
     0,
     "पारेषण लाइनें विद्युत को दूर-दूर तक ले जाती हैं।",
     "Transmission lines carry electricity over long distances."),

    ("electric-energy-and-sources", "easy",
     "पुराने फिलामेंट बल्ब में भुगतान की गई विद्युत ऊर्जा का बड़ा हिस्सा किस रूप में जाता है?",
     "In an old filament bulb, the bulk of the paid electrical energy goes into which form?",
     ["ऊष्मा के रूप में (प्रकाश बहुत कम)", "प्रकाश के रूप में ही", "ध्वनि में", "यांत्रिक कार्य में"],
     ["Heat (very little as light)", "Entirely as light", "Sound", "Mechanical work"],
     0,
     "फिलामेंट बल्ब ऊर्जा का अधिकांश ऊष्मा में बर्बाद करता है — यही जाल है।",
     "A filament bulb wastes most energy as heat — the classic trap."),

    ("electric-energy-and-sources", "easy",
     "CFL/LED बल्ब ऊर्जा-बचत में कैसे मदद करते हैं?",
     "How do CFL/LED bulbs help save energy?",
     ["कम विद्युत खाकर लगभग उतना ही प्रकाश देते हैं", "अधिक विद्युत खाते हैं", "केवल ऊष्मा देते हैं", "वोल्टेज बढ़ाते हैं"],
     ["They give nearly the same light while drawing much less electricity", "They draw more electricity", "They give only heat", "They raise the voltage"],
     0,
     "कम खपत-समान प्रकाश = ऊर्जा बचत।",
     "Less consumption for similar light = energy saving."),

    ("electric-energy-and-sources", "easy",
     "घर में बिजली बचाने का सबसे सरल तरीका क्या है?",
     "What is the simplest way to save electricity at home?",
     ["जरूरत न होने पर स्विच और उपकरण बंद रखना", "दिन-रात बल्ब जलाते रहना", "सभी उपकरण एक साथ चालू रखना", "पंखे को पूरी रात चालू रखना"],
     ["Keeping switches and devices off when not needed", "Leaving bulbs on day and night", "Running all devices together", "Leaving the fan on all night"],
     0,
     "अप्रयुक्त उपकरण बंद = सीधी बचत।",
     "Idle devices off = direct saving."),

    ("electric-energy-and-sources", "easy",
     "सौर पैनल आमतौर पर घर की छत पर क्यों लगाए जाते हैं?",
     "Why are solar panels usually installed on house rooftops?",
     ["वहाँ सूरज की रोशनी सबसे अधिक और अबाधित मिलती है", "क्योंकि छतें हमेशा खाली रहती हैं", "वहाँ हवा तेज होती है", "वहाँ पानी जमा रहता है"],
     ["Rooftops get the most unobstructed sunlight", "Because rooftops always stay empty", "The wind is stronger there", "Water collects there"],
     0,
     "पैनल को अधिकतम सूर्य-प्रकाश चाहिए।",
     "Panels need maximum sunlight."),

    ("electric-energy-and-sources", "easy",
     "जल-विद्युत में पानी की कौन-सी ऊर्जा मुख्य रूप से काम आती है?",
     "In hydro power, which energy of water is mainly used?",
     ["बांध के ऊँचाई वाले पानी की स्थितिज ऊर्जा", "पानी की ऊष्मा", "पानी का रंग", "पानी में घुला लवण"],
     ["The potential energy of water stored at height in the dam", "The heat of water", "The colour of water", "Dissolved salts"],
     0,
     "गिरते समय स्थितिज ऊर्जा गतिज में बदलकर टरबाइन घुमाती है।",
     "While falling, potential energy turns kinetic and spins the turbine."),

    ("electric-energy-and-sources", "easy",
     "निम्न में से कौन-सा नवीनीकरणीय स्रोत नहीं है?",
     "Which of these is NOT a renewable source?",
     ["प्राकृतिक गैस", "पवन ऊर्जा", "बायोगैस", "ज्वारीय ऊर्जा"],
     ["Natural gas", "Wind energy", "Biogas", "Tidal energy"],
     0,
     "प्राकृतिक गैस जीवाश्म ईंधन है — अनवीनीकरणीय।",
     "Natural gas is a fossil fuel — non-renewable."),

    ("electric-energy-and-sources", "easy",
     "बिजली का उत्पादन बढ़ाने से पहले ऊर्जा-बचत को प्राथमिकता क्यों दी जाती है?",
     "Why is energy conservation prioritised before increasing electricity production?",
     ["बचाई गई ईंधन-ऊर्जा सस्ती और प्रदूषण-मुक्त होती है; नया संयंत्र महँगा पड़ता है", "बचत से बिजली खराब होती है", "उत्पादन हमेशा हानिकारक है", "बचत असंभव है"],
     ["Saved fuel-energy is cheap and pollution-free; a new plant is costly", "Saving spoils electricity", "Production is always harmful", "Saving is impossible"],
     0,
     "बचत एक ओर, उत्पादन दूसरी ओर — बचत पहले सस्ती।",
     "A unit saved beats a unit generated — saving is cheaper."),

    # ---- medium (22) ----
    ("electric-energy-and-sources", "medium",
     "जीवाश्म ईंधन के जलने से पर्यावरण को क्या हानि है?",
     "What environmental harm comes from burning fossil fuels?",
     ["हवा में धुएँ और हानिकारक गैसें मिलती हैं (वायु प्रदूषण)", "हवा साफ हो जाती है", "मिट्टी उपजाऊ हो जाती है", "वर्षा बंद हो जाती है और बाकी सब सही"],
     ["Smoke and harmful gases enter the air (air pollution)", "The air becomes clean", "The soil turns fertile", "Rains stop and everything else is fine"],
     0,
     "दहन से CO₂ व धुआँ — प्रदूषण और ग्लोबल ताप में वृद्धि।",
     "Combustion releases CO₂ and smoke — pollution and global warming."),

    ("electric-energy-and-sources", "medium",
     "सौर ऊर्जा के दो प्रमुख लाभ कौन-से हैं?",
     "What are two major advantages of solar energy?",
     ["प्रदूषण-मुक्त होना और अक्षय (खत्म न होना)", "रात में भी चलना और सस्ती बैटरी", "जगह न लेना और भारी होना", "धुआँ और गैस देना"],
     ["It is pollution-free and inexhaustible", "Working at night and cheap batteries", "Taking no space and being heavy", "Giving smoke and gas"],
     0,
     "सूर्य स्वच्छ और असीमित ऊर्जा-स्रोत है।",
     "The sun is a clean and unlimited energy source."),

    ("electric-energy-and-sources", "medium",
     "पवन ऊर्जा की मुख्य सीमा क्या है?",
     "What is the chief limitation of wind energy?",
     ["हवा सदा एक-सी नहीं बहती — शांत दिनों में उत्पादन रुक जाता है", "हवा प्रदूषण करती है", "क्योंकि पवन चक्कियाँ आवाज़ करती हैं", "हवा से ऊर्जा नहीं मिलती"],
     ["Wind is not steady — output stops on calm days", "Wind pollutes", "Because windmills make noise", "Wind gives no energy"],
     0,
     "प्रकृति पर निर्भरता ही पवन-ऊर्जा की जड़ सीमा है।",
     "Dependence on nature is wind power's core limitation."),

    ("electric-energy-and-sources", "medium",
     "बड़े जल-बांधों से जुड़ी पर्यावरणीय चिंता क्या है?",
     "What is the environmental concern linked with large dams?",
     ["बड़े क्षेत्र जलमग्न होते हैं — वनस्पति, वन्यजीव और बसाव विस्थापित होते हैं", "बांध से धुआँ निकलता है", "बांध मिट्टी उपजाऊ बनाता है", "बांध से गैस बनती है"],
     ["Large areas submerge — vegetation, wildlife and settlements get displaced", "Dams emit smoke", "Dams fertilise soil", "Dams produce gas"],
     0,
     "जलमग्न क्षेत्र और विस्थापन — जलविद्युत का कठिन पक्ष।",
     "Submergence and displacement — hydro power's hard side."),

    ("electric-energy-and-sources", "medium",
     "गोबर गैस (बायोगैस) संयंत्र ग्रामीण क्षेत्रों में क्यों लोकप्रिय है?",
     "Why are biogas plants popular in rural areas?",
     ["गोबर-कचरे से ईंधन गैस मिलती है और शेष खाद भी", "वे बिजली सीधे देते हैं", "वे पवन ऊर्जा से चलते हैं", "वे पेट्रोल बनाते हैं"],
     ["Dung and waste yield fuel gas, and the leftover is manure", "They directly give electricity", "They run on wind energy", "They make petrol"],
     0,
     "एक ही संयंत्र से ईंधन + उर्वरक — दोहरा लाभ।",
     "One plant gives fuel + fertiliser — a double benefit."),

    ("electric-energy-and-sources", "medium",
     "भूतापीय ऊर्जा संयंत्र कहाँ संभव होते हैं?",
     "Where are geothermal energy plants feasible?",
     ["जहाँ भूमि के नीचे गर्म जल/भाप के स्रोत पास हों", "जहाँ बर्फ गिरती है", "जहाँ नदियाँ सूख जाती हैं", "हर गाँव में एक-सा"],
     ["Where sources of hot water/steam lie close beneath the ground", "Where snow falls", "Where rivers dry up", "Equally in every village"],
     0,
     "भू-गर्म स्रोत विशेष स्थानों पर ही मिलते हैं।",
     "Geothermal sources exist only at specific locations."),

    ("electric-energy-and-sources", "medium",
     "जल-विद्युत उत्पादन का सही क्रम क्या है?",
     "What is the correct sequence of hydro electricity generation?",
     ["बांध का पानी → टरबाइन → जनित्र → विद्युत", "टरबाइन → पानी → विद्युत → जनित्र", "विद्युत → जनित्र → टरबाइन → पानी", "जनित्र → विद्युत → पानी → टरबाइन"],
     ["Dam water → turbine → generator → electricity", "Turbine → water → electricity → generator", "Electricity → generator → turbine → water", "Generator → electricity → water → turbine"],
     0,
     "गिरता पानी टरबाइन, टरबाइन जनित्र, जनित्र विद्युत देता है।",
     "Falling water → turbine → generator → electricity."),

    ("electric-energy-and-sources", "medium",
     "सौर पैनल रात में विद्युत क्यों नहीं देते?",
     "Why do solar panels give no electricity at night?",
     ["प्रकाश उपलब्ध नहीं होता — सौर सेल प्रकाश से ही चलते हैं", "रात में पैनल गर्म हो जाते हैं", "रात में वोल्टेज बढ़ जाता है", "क्योंकि रात में तापमान गिर जाता है"],
     ["No light is available — solar cells run on light alone", "Panels overheat at night", "Voltage rises at night", "Because the temperature falls at night"],
     0,
     "सौर सेल का ईंधन प्रकाश ही है।",
     "A solar cell's fuel is light itself."),

    ("electric-energy-and-sources", "medium",
     "कोयला-आधारित ऊर्जा संयंत्र में टरबाइन कैसे घूमती है?",
     "How does the turbine turn in a coal-based power plant?",
     ["कोयला जलाकर भाप बनाई जाती है, भाप टरबाइन घुमाती है", "हवा से टरबाइन घूमती है", "पानी सीधे टरबाइन पर गिरता है", "टरबाइन हाथ से घुमाई जाती है"],
     ["Coal is burnt to make steam, and the steam spins the turbine", "Wind turns the turbine", "Water falls directly on the turbine", "The turbine is cranked by hand"],
     0,
     "रासायनिक ऊर्जा → ऊष्मा → भाप → घूर्णन → विद्युत।",
     "Chemical energy → heat → steam → rotation → electricity."),

    ("electric-energy-and-sources", "medium",
     "नवीनीकरणीय और अनवीनीकरणीय स्रोतों का मूल अंतर किस बात में है?",
     "What is the fundamental difference between renewable and non-renewable sources?",
     ["पुनः भरने में लगने वाले समय में — प्राकृतिक दर बनाम मानवीय खपत की दर", "रंग में", "कीमत में ही", "देश में"],
     ["In the renewal timescale — natural replenishment rate versus human consumption rate", "In colour", "Only in price", "In the country of origin"],
     0,
     "खपत दर पुनर्भरण दर से तेज हो तो स्रोत अनवीनीकरणीय।",
     "If use outruns replenishment, the source is non-renewable."),

    ("electric-energy-and-sources", "medium",
     "10 वाट का LED बल्ब 100 वाट के पुराने बल्ब जितनी रोशनी देता है। इससे ऊर्जा की कितनी बचत होती है?",
     "A 10 W LED gives as much light as an old 100 W bulb. How much energy is saved?",
     ["लगभग 90 वाट की (90%)", "10 वाट की", "100 वाट की", "कोई बचत नहीं"],
     ["About 90 watt (90%)", "10 watt", "100 watt", "None"],
     0,
     "100 − 10 = 90 W — इसीलिए LED को ऊर्जा-कुशल कहा जाता है।",
     "100 − 10 = 90 W — hence LEDs are called energy-efficient."),

    ("electric-energy-and-sources", "medium",
     "घरेलू बिजली बचत का सबसे प्रभावी अभ्यास कौन-सा है?",
     "Which is the most effective household electricity-saving practice?",
     ["जरूरत न होने पर उपकरण पूरी तरह बंद करना (स्टैंडबाई सहित)", "बल्ब जलाकर खुली खिड़की से प्रकाश निकालना", "रेफ्रिजरेटर का दरवाज़ा बार-बार खोलना", "एअरकंडीशनर को खुले दरवाज़े पर चलाना"],
     ["Fully switching off devices when unneeded (including standby)", "Burning bulbs and letting light out of open windows", "Opening the refrigerator repeatedly", "Running the AC with doors open"],
     0,
     "स्टैंडबाई-खपत भी बड़ी होती है — पूरा बंद ही सच्ची बचत।",
     "Standby drain adds up — full switch-off is true saving."),

    ("electric-energy-and-sources", "medium",
     "ऊर्जा संरक्षण का अर्थ स्पष्ट कीजिए:",
     "Clarify what energy conservation means:",
     ["उपयोगी कार्य में आने वाली ऊर्जा को बर्बादी से बचाकर कम खपत से वही कार्य लेना", "ऊर्जा का निर्माण करना", "ऊर्जा बेचना", "ऊर्जा रखने के लिए बर्तन खरीदना"],
     ["Getting the same useful work with less consumption by avoiding waste", "Creating energy", "Selling energy", "Buying vessels to store energy"],
     0,
     "संरक्षण = बर्बादी रोकना, न कि ऊर्जा 'बनाना'।",
     "Conservation = stopping waste, not 'making' energy."),

    ("electric-energy-and-sources", "medium",
     "बिजली के बिल में ऊर्जा किस इकाई में लिखी जाती है?",
     "In an electricity bill, in which unit is the energy written?",
     ["किलोवाट-घंटा (kWh, यूनिट)", "एम्पियर", "ओम", "वोल्ट"],
     ["Kilowatt-hour (kWh, unit)", "Ampere", "Ohm", "Volt"],
     0,
     "1 kWh = 1 यूनिट — विद्युत ऊर्जा का व्यावसायिक माप।",
     "1 kWh = 1 unit — the commercial measure of electrical energy."),

    ("electric-energy-and-sources", "medium",
     "सौर जल-तापक बनाम विद्युत गीज़र — ऊर्जा-दृष्टि से अंतर समझाइए:",
     "Solar water heater vs electric geyser — explain the difference from the energy viewpoint:",
     ["सौर तापक सूर्य की निःशुल्क ऊर्जा लेता है, गीज़र खरीदी हुई विद्युत ऊर्जा", "दोनों एक ही ऊर्जा लेते हैं", "सौर तापक अधिक बिजली खाता है", "गीज़र सूर्य से चलता है"],
     ["The solar heater uses the sun's free energy; the geyser uses purchased electricity", "Both use the same energy", "The solar heater consumes more electricity", "The geyser runs on the sun"],
     0,
     "स्रोत का चुनाव ही बचत तय करता है।",
     "The choice of source decides the saving."),

    ("electric-energy-and-sources", "medium",
     "ग्रामीण परिवार के लिए गोबर-गैस संयंत्र के दोहरे लाभ क्या हैं?",
     "What are the twin benefits of a dung-gas plant for a rural family?",
     ["खाना पकाने हेतु गैस और खेती हेतु उच्च गुणवत्ता की खाद", "बिजली और पेट्रोल", "पवन और जल", "केवल गैस, कोई खाद नहीं"],
     ["Gas for cooking and good manure for the fields", "Electricity and petrol", "Wind and water", "Only gas, no manure"],
     0,
     "कचरा ईंधन बनता है और शेष उर्वरक।",
     "Waste becomes fuel and the rest becomes fertiliser."),

    ("electric-energy-and-sources", "medium",
     "उपकरण और उनमें ऊर्जा-रूपांतरण का गलत युग्म कौन-सा है?",
     "Which device and energy-conversion pairing is WRONG?",
     ["विद्युत पंखा — विद्युत से ऊष्मा मुख्य रूपांतरण", "हीटर — विद्युत से ऊष्मा", "मोटर — विद्युत से यांत्रिक", "बल्ब — विद्युत से प्रकाश व ऊष्मा"],
     ["Electric fan — electricity to heat as the main conversion", "Heater — electricity to heat", "Motor — electricity to mechanical", "Bulb — electricity to light and heat"],
     0,
     "पंखे में मुख्य रूपांतरण यांत्रिक है, ऊष्मा नहीं।",
     "A fan's main conversion is mechanical, not heat."),

    ("electric-energy-and-sources", "medium",
     "प्रदूषण-दृष्टि से सबसे स्वच्छ विकल्प कौन-सा है — बिजली घर के लिए?",
     "From the pollution viewpoint, which is the cleanest option for a power plant?",
     ["पवन आधारित", "कोयला आधारित", "डीज़ल आधारित", "गैस आधारित"],
     ["Wind based", "Coal based", "Diesel based", "Gas based"],
     0,
     "पवन में दहन ही नहीं — शून्य धुआँ।",
     "Wind involves no combustion — zero smoke."),

    ("electric-energy-and-sources", "medium",
     "जीवाश्म ईंधन की कीमतें समय के साथ क्यों बढ़ती जाती हैं?",
     "Why do fossil fuel prices keep rising over time?",
     ["भंडार सीमित हैं और माँग लगातार बढ़ रही है", "भंडार बढ़ रहे हैं", "माँग घट रही है", "खनन रुक गया है"],
     ["Stocks are limited while demand keeps growing", "Stocks are growing", "Demand is falling", "Mining has stopped"],
     0,
     "सीमित आपूर्ति + बढ़ती माँग = महँगाई।",
     "Limited supply + rising demand = higher prices."),

    ("electric-energy-and-sources", "medium",
     "ज्वारीय ऊर्जा किस घटना से मिलती है?",
     "Tidal energy comes from which phenomenon?",
     ["समुद्र में नियमित ज्वार-भाटा (पानी का उतार-चढ़ाव)", "नदियों की धारा", "भूमि की गर्मी", "हवा के झोंके"],
     ["The regular rise and fall of tides in the sea", "River currents", "Heat of the ground", "Gusts of wind"],
     0,
     "ज्वार की गतिज ऊर्जा टरबाइन घुमाती है।",
     "The kinetic energy of tides spins turbines."),

    ("electric-energy-and-sources", "medium",
     "मौसम और समय चाहे जैसा हो, सबसे स्थिर रूप से विद्युत देने वाला नवीनीकरणीय स्रोत कौन-सा है?",
     "Regardless of weather or hour, which renewable source supplies electricity most steadily?",
     ["भूतापीय", "सौर", "पवन", "ज्वारीय"],
     ["Geothermal", "Solar", "Wind", "Tidal"],
     0,
     "पृथ्वी की गर्मी दिन-रात एक-सी बनी रहती है।",
     "The earth's heat stays the same day and night."),

    ("electric-energy-and-sources", "medium",
     "तीन कथन: (i) कोयला और पेट्रोल अनवीनीकरणीय हैं। (ii) सौर ऊर्जा प्रदूषण उत्पन्न नहीं करती। (iii) बायोगैस जीवाश्म ईंधन है। सही समूह चुनें:",
     "Three statements: (i) Coal and petrol are non-renewable. (ii) Solar energy creates no pollution. (iii) Biogas is a fossil fuel. Pick the correct set:",
     ["(i) और (ii) सही, (iii) गलत", "तीनों सही", "केवल (iii) सही", "(i) गलत, (ii) गलत, (iii) सही"],
     ["(i) and (ii) correct, (iii) wrong", "All three correct", "Only (iii) correct", "(i) wrong, (ii) wrong, (iii) correct"],
     0,
     "बायोगैस जैविक कचरे से बनती है — जीवाश्म ईंधन नहीं।",
     "Biogas comes from organic waste — not a fossil fuel."),

    # ---- hard (8) ----
    ("electric-energy-and-sources", "hard",
     "सौर पैनल → बैटरी → रात में LED प्रकाश — इस व्यवस्था में ऊर्जा-रूपांतरणों का क्रम क्या है?",
     "Solar panel → battery → LED light at night — what is the sequence of energy conversions in this setup?",
     ["प्रकाश ऊर्जा → विद्युत ऊर्जा → रासायनिक ऊर्जा → पुनः विद्युत → प्रकाश", "विद्युत → प्रकाश → विद्युत → प्रकाश", "रासायनिक → यांत्रिक → प्रकाश", "ऊष्मा → ध्वनि → प्रकाश"],
     ["Light → electrical → chemical → electrical again → light", "Electrical → light → electrical → light", "Chemical → mechanical → light", "Heat → sound → light"],
     0,
     "पैनल प्रकाश था, बैटरी ने रासायनिक बनाकर संचित किया, LED ने पुनः प्रकाश दिया।",
     "Panel took light, battery stored it chemically, LED gave back light."),

    ("electric-energy-and-sources", "hard",
     "एक विद्युत उपकरण में 'आउटपुट ऊर्जा' इनपुट ऊर्जा से अधिक क्यों नहीं हो सकती?",
     "Why can the 'output energy' of an electrical device never exceed the input energy?",
     ["ऊर्जा संरक्षण का नियम — ऊर्जा न बनती है न नष्ट; कुछ ऊर्जा सदैव ऊष्मा के रूप में बचती/हानि होती है", "क्योंकि उपकरण छोटे होते हैं", "क्योंकि उपकरण धीमी गति से चलते हैं", "क्योंकि बिजली धीमी होती है"],
     ["Law of conservation of energy — energy is neither created nor destroyed; some always ends up as heat", "Because devices are small", "Because devices run slowly", "Because electricity is slow"],
     0,
     "इनपुट = उपयोगी आउटपुट + हानि (मुख्यतः ऊष्मा)।",
     "Input = useful output + losses (mainly heat)."),

    ("electric-energy-and-sources", "hard",
     "कथन: 'नवीनीकरणीय स्रोत असीमित हैं, इसलिए बचत की जरूरत नहीं।' इस पर सही टिप्पणी क्या है?",
     "Statement: 'Renewable sources are unlimited, so there is no need to conserve.' What is the correct comment?",
     ["भ्रामक — उपकरण, स्थापना और पर्यावरण-दबाव सीमित हैं; खपत जितनी कम, तंत्र उतना टिकाऊ", "पूर्णतः सही", "केवल सौर ऊर्जा के लिए सही", "क्योंकि सभी स्रोत एक-से ही हैं"],
     ["Misleading — devices, installation and environmental pressure are limited; lower consumption keeps the system sustainable", "Completely correct", "Correct only for solar", "Because all sources are the same"],
     0,
     "'असीमित स्रोत' भी उपकरण-सीमा और ज़मीन की सीमा से बंधे हैं।",
     "Even 'unlimited sources' are bounded by equipment and land limits."),

    ("electric-energy-and-sources", "hard",
     "कोयला-संयंत्र बनाम पवन-संयंत्र की ऊर्जा-श्रृंखलाओं का सही अंतर क्या है?",
     "What is the correct difference between the energy chains of a coal plant and a wind plant?",
     ["कोयला: रासायनिक → ऊष्मा → यांत्रिक → विद्युत; पवन: गतिज (हवा) → यांत्रिक → विद्युत", "दोनों की श्रृंखला समान है", "कोयला: विद्युत → रासायनिक; पवन: विद्युत → गतिज", "पवन में दहन होता है, कोयले में नहीं"],
     ["Coal: chemical → heat → mechanical → electrical; wind: kinetic (air) → mechanical → electrical", "Both chains are identical", "Coal: electrical → chemical; wind: electrical → kinetic", "Wind involves combustion, coal does not"],
     0,
     "दहन-स्रोत में ऊष्मा-चरण आता है, प्रत्यक्ष-गति स्रोत में नहीं।",
     "A combustion source has a heat stage; a direct-motion source does not."),

    ("electric-energy-and-sources", "hard",
     "एक गाँव ग्रिड से बहुत दूर है। वहाँ विद्युत का सबसे व्यावहारिक नवीनीकरणीय विकल्प क्या है?",
     "A village lies far from the grid. What is the most practical renewable alternative for electricity there?",
     ["सौर पैनल (स्थानीय, बिखरा हुआ स्रोत)", "दूर तक लंबी लाइन खींचना", "डीज़ल जनरेटर", "कोयला संयंत्र"],
     ["Solar panels (a local, distributed source)", "Pulling a long line to it", "Diesel generator", "A coal plant"],
     0,
     "जहाँ ग्रिड नहीं, वहाँ स्थानीय सूर्य सबसे व्यवहार्य।",
     "Where the grid can't reach, local sunshine works best."),

    ("electric-energy-and-sources", "hard",
     "सौर जल-तापक का उपयोग विद्युत गीज़र की जगह करने से परिवार और देश दोनों को क्या लाभ है?",
     "Replacing an electric geyser with a solar water heater benefits both family and nation how?",
     ["परिवार का बिल घटता है और देश की विद्युत माँग (तथा ईंधन खपत) कम होती है", "परिवार का बिल बढ़ता है, देश को लाभ", "दोनों को हानि", "केवल सर्दियों में हानि"],
     ["The family's bill falls and the nation's electricity demand (and fuel use) drops", "The family's bill rises, nation gains", "Both lose", "Loss only in winters"],
     0,
     "हर यूनिट घर की बचत = ईंधन की बचत राष्ट्र के लिए।",
     "Every unit saved at home = fuel saved for the nation."),

    ("electric-energy-and-sources", "hard",
     "पवन-ऊर्जा क्षेत्र स्थापित करने के लिए किस प्रकार के भौगोलिक क्षेत्र सर्वाधिक उपयुक्त हैं?",
     "Which kind of geographic areas are most suitable for installing wind-energy farms?",
     ["खुले मैदान, तटीय पट्टियाँ और दर्रे जहाँ हवा लगातार तेज बहती है", "घने जंगल वाली गहरी घाटियाँ", "भूमिगत गुफाएँ", "शांत, बंद घाटियाँ"],
     ["Open plains, coastal strips and passes where strong winds blow steadily", "Deep forested valleys", "Underground caves", "Still, enclosed valleys"],
     0,
     "लगातार प्रबल हवा ही पवन-संयंत्र की ज़रूरत है।",
     "Steady strong winds are what a wind farm needs."),

    ("electric-energy-and-sources", "hard",
     "LED बल्ब फिलामेंट बल्ब से 'ऊर्जा-कुशल' माना जाता है। इस कथन का भौतिक आधार क्या है?",
     "An LED is called 'energy-efficient' compared with a filament bulb. What is the physical basis of this statement?",
     ["LED इनपुट ऊर्जा का अधिकांश प्रकाश में बदलता है, फिलामेंट बल्ब अधिकांश ऊष्मा में", "LED अधिक बिजली खाता है", "LED में फ्यूज़ होता है", "फिलामेंट बल्ब ठंडा चलता है"],
     ["An LED turns most input energy into light; a filament bulb turns most into heat", "An LED consumes more electricity", "An LED contains a fuse", "A filament bulb runs cool"],
     0,
     "उपयोगी आउटपुट/इनपुट अनुपात ही दक्षता है — LED का यह अनुपात ऊँचा।",
     "Useful output over input is efficiency — the LED's ratio is high."),
]
