# -*- coding: utf-8 -*-
"""P12 part 1 — Space, Earth & Basic Physical Phenomena (chapter-12).
T1 solar-system (E20/M21/H9) + T2 day-night-and-seasons (E20/M21/H9).
Tuple: (topic, difficulty, q_hi, q_en, opts_hi[4], opts_en[4], correct_idx=0, expl_hi, expl_en)
All authored with correct_idx 0; answer-position rotation happens in gen script.
Only facts present in chapter-12 meta.json are used — no dates, distances or
missions beyond Aryabhata / Chandrayaan / Mangalyaan / ISRO.
"""

PART1 = [
    # ================= SOLAR SYSTEM (50) =================
    # ---- easy (20) ----
    ("solar-system", "easy",
     "सौर परिवार में कुल कितने ग्रह हैं?",
     "How many planets are there in the solar system in total?",
     ["आठ", "सात", "नौ", "छह"],
     ["Eight", "Seven", "Nine", "Six"],
     0,
     "बुध, शुक्र, पृथ्वी, मंगल, बृहस्पति, शनि, अरुण और वरुण — आठ ग्रह।",
     "Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus and Neptune — eight planets."),

    ("solar-system", "easy",
     "सूर्य क्या है?",
     "What is the Sun?",
     ["एक तारा", "एक ग्रह", "एक उपग्रह", "एक छाया-पिंड"],
     ["A star", "A planet", "A satellite", "A shadow-body"],
     0,
     "सूर्य स्वयं प्रकाशमान है, इसलिए वह तारा है।",
     "The Sun glows by itself, so it is a star."),

    ("solar-system", "easy",
     "सूर्य के सबसे निकट वाला ग्रह कौन-सा है?",
     "Which planet is nearest to the Sun?",
     ["बुध", "शुक्र", "पृथ्वी", "मंगल"],
     ["Mercury", "Venus", "Earth", "Mars"],
     0,
     "बुध सूर्य के सबसे निकट है।",
     "Mercury is closest to the Sun."),

    ("solar-system", "easy",
     "सौर परिवार का सबसे बड़ा ग्रह कौन-सा है?",
     "Which is the largest planet of the solar system?",
     ["बृहस्पति", "शनि", "पृथ्वी", "मंगल"],
     ["Jupiter", "Saturn", "Earth", "Mars"],
     0,
     "बृहस्पति आकार में सबसे बड़ा ग्रह है।",
     "Jupiter is the largest planet in size."),

    ("solar-system", "easy",
     "सौर परिवार का सबसे छोटा ग्रह कौन-सा है?",
     "Which is the smallest planet of the solar system?",
     ["बुध", "वरुण", "अरुण", "शनि"],
     ["Mercury", "Neptune", "Uranus", "Saturn"],
     0,
     "बुध आकार में सबसे छोटा ग्रह है।",
     "Mercury is the smallest planet."),

    ("solar-system", "easy",
     "सबसे गर्म ग्रह कौन-सा है?",
     "Which is the hottest planet?",
     ["शुक्र", "बुध", "मंगल", "बृहस्पति"],
     ["Venus", "Mercury", "Mars", "Jupiter"],
     0,
     "शुक्र सबसे गर्म ग्रह है — बुध सूर्य के निकट होने पर भी।",
     "Venus is the hottest planet — even though Mercury is nearer the Sun."),

    ("solar-system", "easy",
     "रात के आकाश में पृथ्वी से दिखने वाला सबसे चमकीला ग्रह कौन-सा है?",
     "Which is the brightest planet seen from the Earth in the night sky?",
     ["शुक्र", "मंगल", "बुध", "शनि"],
     ["Venus", "Mars", "Mercury", "Saturn"],
     0,
     "शुक्र पृथ्वी से दिखने वाला सबसे चमकीला पिंड-ग्रह है।",
     "Venus is the brightest planet seen from the Earth."),

    ("solar-system", "easy",
     "ग्रहों में गिनती में पृथ्वी सूर्य से कौन-सी है?",
     "What is Earth's position among the planets from the Sun?",
     ["तीसरी", "पहली", "दूसरी", "चौथी"],
     ["Third", "First", "Second", "Fourth"],
     0,
     "बुध-शुक्र के बाद पृथ्वी तीसरे स्थान पर है।",
     "After Mercury and Venus, Earth is third."),

    ("solar-system", "easy",
     "पृथ्वी का प्राकृतिक उपग्रह कौन-सा है?",
     "Which is the Earth's natural satellite?",
     ["चंद्रमा", "शुक्र", "बृहस्पति", "ध्रुवतारा"],
     ["The Moon", "Venus", "Jupiter", "The Pole Star"],
     0,
     "चंद्रमा पृथ्वी का उपग्रह है।",
     "The Moon is the Earth's satellite."),

    ("solar-system", "easy",
     "ग्रह स्वयं प्रकाशमान होते हैं या नहीं?",
     "Do planets shine with their own light?",
     ["नहीं — ग्रह सूर्य के प्रकाश से जगमगाते हैं", "हाँ, हर ग्रह स्वयं जलता है", "केवल पृथ्वी स्वयं जगती है", "केवल बृहस्पति जगता है"],
     ["No — planets shine by the Sun's light", "Yes, every planet burns on its own", "Only Earth glows by itself", "Only Jupiter glows"],
     0,
     "ग्रह सूर्य का प्रकाश परावर्तित करते हैं, स्वयं प्रकाशमान नहीं होते।",
     "Planets reflect sunlight; they are not self-luminous."),

    ("solar-system", "easy",
     "तारा और ग्रह में मूल अंतर क्या है?",
     "What is the basic difference between a star and a planet?",
     ["तारे स्वयं प्रकाशमान होते हैं, ग्रह नहीं", "ग्रह स्वयं प्रकाशमान होते हैं, तारे नहीं", "दोनों स्वयं प्रकाशमान होते हैं", "कोई अंतर नहीं होता"],
     ["Stars are self-luminous, planets are not", "Planets are self-luminous, stars are not", "Both are self-luminous", "There is no difference"],
     0,
     "अपने प्रकाश का होना ही तारे की पहचान है।",
     "Having its own light is the very identity of a star."),

    ("solar-system", "easy",
     "सूर्य से दूरी के क्रम में पहले दो ग्रह कौन-से हैं?",
     "Which are the first two planets in order of distance from the Sun?",
     ["बुध और शुक्र", "शुक्र और पृथ्वी", "पृथ्वी और मंगल", "मंगल और बृहस्पति"],
     ["Mercury and Venus", "Venus and Earth", "Earth and Mars", "Mars and Jupiter"],
     0,
     "क्रम बुध, शुक्र, पृथ्वी, मंगल… से शुरू होता है।",
     "The order begins Mercury, Venus, Earth, Mars…"),

    ("solar-system", "easy",
     "सूर्य से सबसे दूर स्थित ग्रह कौन-सा है?",
     "Which planet lies farthest from the Sun?",
     ["वरुण", "अरुण", "शनि", "बृहस्पति"],
     ["Neptune", "Uranus", "Saturn", "Jupiter"],
     0,
     "आठवें और अंतिम स्थान पर वरुण है।",
     "Neptune is eighth and last in the order."),

    ("solar-system", "easy",
     "पृथ्वी के बगल के दो ग्रह कौन-से हैं?",
     "Which two planets are Earth's neighbours?",
     ["शुक्र और मंगल", "बुध और शुक्र", "मंगल और बृहस्पति", "शनि और अरुण"],
     ["Venus and Mars", "Mercury and Venus", "Mars and Jupiter", "Saturn and Uranus"],
     0,
     "क्रम में पृथ्वी से पहले शुक्र, बाद में मंगल है।",
     "In order, Venus precedes Earth and Mars follows it."),

    ("solar-system", "easy",
     "मंगल ग्रह का रंग प्रायः कैसा दिखता है?",
     "How does the planet Mars generally appear in colour?",
     ["लालिमा लिए लाल", "हरा", "नीला-सफ़ेद", "काला"],
     ["Reddish with a red tinge", "Green", "Blue-white", "Black"],
     0,
     "मंगल को उसकी लालिमा के कारण लाल ग्रह कहा जाता है।",
     "Mars is called the red planet because of its red tinge."),

    ("solar-system", "easy",
     "सौर परिवार के केंद्र में कौन है?",
     "Who is at the centre of the solar system?",
     ["सूर्य", "पृथ्वी", "चंद्रमा", "ध्रुवतारा"],
     ["The Sun", "The Earth", "The Moon", "The Pole Star"],
     0,
     "सभी ग्रह सूर्य की परिक्रमा करते हैं — सूर्य केंद्र है।",
     "All planets revolve around the Sun — it is the centre."),

    ("solar-system", "easy",
     "निम्न में से कौन-सा ग्रह नहीं है?",
     "Which of the following is NOT a planet?",
     ["ध्रुवतारा", "शनि", "अरुण", "मंगल"],
     ["The Pole Star", "Saturn", "Uranus", "Mars"],
     0,
     "ध्रुवतारा एक तारा है, ग्रह नहीं।",
     "The Pole Star is a star, not a planet."),

    ("solar-system", "easy",
     "सूर्य के चारों ओर ग्रह क्या करते हैं?",
     "What do the planets do around the Sun?",
     ["परिक्रमा करते हैं", "सोते हैं", "गिरते हैं", "बुझ जाते हैं"],
     ["They revolve around it", "They sleep", "They fall", "They extinguish"],
     0,
     "हर ग्रह सूर्य की परिक्रमा में रहता है।",
     "Every planet keeps revolving around the Sun."),

    ("solar-system", "easy",
     "शुक्र ग्रह किस विशेषता के लिए जाना जाता है?",
     "What is the planet Venus known for?",
     ["सबसे गर्म और सबसे चमकीला होने के लिए", "सबसे ठंडा होने के लिए", "सबसे बड़ा होने के लिए", "सबसे अधिक उपग्रह होने के लिए"],
     ["Being the hottest and the brightest", "Being the coldest", "Being the largest", "Having the most moons"],
     0,
     "शुक्र गर्मी और चमक — दोनों में शीर्ष पर है।",
     "Venus tops both heat and brightness."),

    ("solar-system", "easy",
     "बृहस्पति की तुलना में पृथ्वी का आकार कैसा है?",
     "How is Earth's size compared with Jupiter?",
     ["पृथ्वी छोटी है — बृहस्पति सबसे बड़ा ग्रह है", "पृथ्वी बड़ी है", "दोनों बराबर हैं", "तुलना संभव नहीं"],
     ["Earth is smaller — Jupiter is the largest planet", "Earth is larger", "Both are equal", "No comparison is possible"],
     0,
     "बृहस्पति के आगे पृथ्वी आकार में छोटी है।",
     "Compared with Jupiter, Earth is small in size."),

    # ---- medium (21) ----
    ("solar-system", "medium",
     "बुध सूर्य के सबसे निकट है, फिर भी सबसे गर्म शुक्र क्यों है?",
     "Mercury is nearest to the Sun, yet why is Venus the hottest?",
     ["शुक्र का घना वायुमंडल ऊष्मा को रोककर रखता है, इसलिए निकटता ही निर्णायक नहीं होती", "बुध में सूर्य की रोशनी नहीं पहुँचती", "शुक्र सूर्य के सबसे निकट है", "बुध एक तारा है"],
     ["Venus's dense atmosphere traps heat, so nearness alone is not decisive", "Sunlight never reaches Mercury", "Venus is nearest to the Sun", "Mercury is a star"],
     0,
     "गर्मी केवल दूरी से तय नहीं होती — वायुमंडल की चादर भी तय करती है; इसीलिए शुक्र सबसे गर्म है।",
     "Heat is not decided by distance alone — the blanket of the atmosphere matters too; hence Venus is hottest."),

    ("solar-system", "medium",
     "सूर्य से दूरी के बढ़ते क्रम में तीसरे और चौथे स्थान के ग्रह कौन-से हैं?",
     "Which planets occupy the third and fourth places in increasing distance from the Sun?",
     ["पृथ्वी और मंगल", "शुक्र और पृथ्वी", "मंगल और बृहस्पति", "बुध और शुक्र"],
     ["Earth and Mars", "Venus and Earth", "Mars and Jupiter", "Mercury and Venus"],
     0,
     "क्रम — बुध, शुक्र, पृथ्वी, मंगल…",
     "The order — Mercury, Venus, Earth, Mars…"),

    ("solar-system", "medium",
     "शनि के बाद और वरुण से पहले कौन-सा ग्रह आता है?",
     "Which planet comes after Saturn and before Neptune?",
     ["अरुण", "बृहस्पति", "मंगल", "पृथ्वी"],
     ["Uranus", "Jupiter", "Mars", "Earth"],
     0,
     "क्रम का सातवाँ ग्रह अरुण है।",
     "Uranus is the seventh planet in the order."),

    ("solar-system", "medium",
     "आकाश में एक पिंड सदा एक जैसी चमक से टिमटिमाता है और दूसरा चमकीला पर स्थिर प्रकाश फैलाता हुआ दिखता है। तारा और ग्रह की पहचान कीजिए:",
     "In the sky, one object twinkles with varying brightness and another looks bright with a steady glow. Identify the star and the planet:",
     ["टिमटिमाने वाला तारा है, स्थिर चमक वाला ग्रह", "टिमटिमाने वाला ग्रह है, स्थिर चमक वाला तारा", "दोनों तारे हैं", "दोनों ग्रह हैं"],
     ["The twinkling one is a star, the steady glow is a planet", "The twinkling one is a planet, the steady one is a star", "Both are stars", "Both are planets"],
     0,
     "तारों का प्रकाश वायुमंडल में काँपता दिखता है; ग्रहों की चमक स्थिर लगती है।",
     "Starlight shimmers in the atmosphere; a planet's glow looks steady."),

    ("solar-system", "medium",
     "अगर ग्रह स्वयं प्रकाशमान होते, तो रात के आकाश में क्या अंतर दिखता?",
     "If planets were self-luminous, what difference would appear in the night sky?",
     ["ग्रह भी तारों जैसे अपनी बिंदु-चमक से टिमटिमाते", "ग्रह अदृश्य हो जाते", "तारे बुझ जाते", "कोई अंतर नहीं पड़ता"],
     ["Planets too would twinkle with their own point-like light like stars", "Planets would become invisible", "Stars would go out", "No difference would occur"],
     0,
     "ग्रहों की पहचान उनकी परावर्तित, स्थिर चमक से ही होती है।",
     "Planets are recognised precisely by their reflected, steady glow."),

    ("solar-system", "medium",
     "सूर्य को ग्रह क्यों नहीं कहा जाता?",
     "Why is the Sun not called a planet?",
     ["सूर्य अपना प्रकाश स्वयं बनाता है — यह तारे की विशेषता है", "सूर्य चंद्रमा की परिक्रमा करता है", "सूर्य उपग्रह है", "सूर्य ठंडा पिंड है"],
     ["The Sun produces its own light — the mark of a star", "The Sun revolves around the Moon", "The Sun is a satellite", "The Sun is a cold body"],
     0,
     "स्व-प्रकाश ही तारे की परिभाषा है; ग्रह परावर्तन करते हैं।",
     "Self-light defines a star; planets only reflect."),

    ("solar-system", "medium",
     "वरुण से पहले के ग्रह का नाम और स्थान बताइए:",
     "Name the planet just before Neptune and give its position:",
     ["अरुण — सातवाँ ग्रह", "शनि — छठा ग्रह", "बृहस्पति — पाँचवाँ ग्रह", "मंगल — चौथा ग्रह"],
     ["Uranus — the seventh planet", "Saturn — the sixth planet", "Jupiter — the fifth planet", "Mars — the fourth planet"],
     0,
     "क्रम में सातवाँ अरुण, आठवाँ वरुण।",
     "Seventh is Uranus, eighth Neptune."),

    ("solar-system", "medium",
     "दिए गए ग्रहों में से बेमेल (असंगत) कौन-सा है?",
     "Which of the given planets is the odd one out?",
     ["ध्रुवतारा — शेष तीनों ग्रह हैं", "बुध — शेष तीनों तारे हैं", "पृथ्वी — शेष तीनों गैस-से-बड़े हैं", "शनि — शेष तीनों छोटे हैं"],
     ["The Pole Star — the other three are planets", "Mercury — the other three are stars", "Earth — the other three are gas giants", "Saturn — the other three are small"],
     0,
     "शुक्र-पृथ्वी-मंगल ग्रह हैं; ध्रुवतारा तारा।",
     "Venus, Earth and Mars are planets; the Pole Star is a star."),

    ("solar-system", "medium",
     "सूर्य से दूरी के क्रम में पाँचवाँ ग्रह कौन-सा है?",
     "Which is the fifth planet in order of distance from the Sun?",
     ["बृहस्पति", "शनि", "मंगल", "अरुण"],
     ["Jupiter", "Saturn", "Mars", "Uranus"],
     0,
     "बुध, शुक्र, पृथ्वी, मंगल के बाद बृहस्पति पाँचवाँ।",
     "After Mercury, Venus, Earth and Mars, Jupiter is fifth."),

    ("solar-system", "medium",
     "बुध और शुक्र में सूर्य के निकटतम होने की दौड़ कौन जीतता है?",
     "In the race of being closest to the Sun, who wins between Mercury and Venus?",
     ["बुध — वह पहला ग्रह है", "शुक्र — वह पहला ग्रह है", "दोनों बराबर दूरी पर", "यह बदलता रहता है"],
     ["Mercury — it is the first planet", "Venus — it is the first planet", "Both lie at equal distance", "It keeps changing"],
     0,
     "क्रम में पहला ग्रह बुध ही सूर्य के सबसे निकट है।",
     "Mercury, the first planet, is nearest to the Sun."),

    ("solar-system", "medium",
     "रात में साफ़ आकाश में सबसे चमकीला ग्रह देखकर कोई विद्यार्थी उसे तारा मान लेता है। उसे कैसे समझाएँ?",
     "A student mistakes the brightest planet in a clear night sky for a star. How to explain it to him?",
     ["ग्रह की चमक स्थिर होती है और वह टिमटिमाता नहीं — चमकीला होना तारा होना नहीं सिद्ध करता", "तारे हमेशा ग्रहों से मंद होते हैं", "ग्रह कभी चमकीले नहीं होते", "तारे दिन में दिखते हैं"],
     ["A planet glows steadily without twinkling — being bright does not make it a star", "Stars are always dimmer than planets", "Planets are never bright", "Stars appear in daytime"],
     0,
     "शुक्र सबसे चमकीला ग्रह है, पर स्थिर चमक उसे तारे से अलग करती है।",
     "Venus is the brightest planet, but its steady glow sets it apart from stars."),

    ("solar-system", "medium",
     "ग्रहों का सही क्रम कौन-सा है?",
     "Which is the correct order of the planets?",
     ["बुध, शुक्र, पृथ्वी, मंगल", "शुक्र, बुध, पृथ्वी, मंगल", "पृथ्वी, शुक्र, बुध, मंगल", "बुध, पृथ्वी, शुक्र, मंगल"],
     ["Mercury, Venus, Earth, Mars", "Venus, Mercury, Earth, Mars", "Earth, Venus, Mercury, Mars", "Mercury, Earth, Venus, Mars"],
     0,
     "सूर्य से शुरुआती क्रम बुध → शुक्र → पृथ्वी → मंगल।",
     "From the Sun the opening order is Mercury → Venus → Earth → Mars."),

    ("solar-system", "medium",
     "कथन: 'सूर्य सबसे बड़ा ग्रह है।' इसका सही निर्णय कीजिए:",
     "Statement: 'The Sun is the largest planet.' Judge it correctly:",
     ["गलत — सूर्य ग्रह ही नहीं, तारा है; सबसे बड़ा ग्रह बृहस्पति है", "सही — सूर्य ग्रहों में सबसे बड़ा है", "आंशिक सही — सूर्य दूसरा सबसे बड़ा ग्रह है", "प्रश्न ही अर्थहीन है"],
     ["Wrong — the Sun is not a planet but a star; Jupiter is the largest planet", "Correct — the Sun is the largest planet", "Partly right — the Sun is the second-largest planet", "The question itself is meaningless"],
     0,
     "श्रेणी ही गलत मिली — तारे की तुलना ग्रहों से नहीं होती।",
     "The category itself is wrong — a star is not ranked among planets."),

    ("solar-system", "medium",
     "पृथ्वी और शुक्र में सूर्य से दूरी की दृष्टि से कौन पहले आता है?",
     "Between Earth and Venus, which comes first in distance from the Sun?",
     ["शुक्र — दूसरा ग्रह; पृथ्वी तीसरी", "पृथ्वी — दूसरा ग्रह; शुक्र तीसरा", "दोनों एक साथ", "पृथ्वी सूर्य के सबसे निकट है"],
     ["Venus — the second planet; Earth is third", "Earth — the second planet; Venus is third", "Both together", "Earth is nearest the Sun"],
     0,
     "शुक्र दूसरे और पृथ्वी तीसरे स्थान पर।",
     "Venus is second and Earth third."),

    ("solar-system", "medium",
     "चार ग्रहों — शनि, वरुण, बृहस्पति, अरुण — को सूर्य से दूरी के बढ़ते क्रम में लगाइए:",
     "Arrange the four planets — Saturn, Neptune, Jupiter, Uranus — in increasing distance from the Sun:",
     ["बृहस्पति, शनि, अरुण, वरुण", "शनि, बृहस्पति, वरुण, अरुण", "बृहस्पति, अरुण, शनि, वरुण", "अरुण, शनि, बृहस्पति, वरुण"],
     ["Jupiter, Saturn, Uranus, Neptune", "Saturn, Jupiter, Neptune, Uranus", "Jupiter, Uranus, Saturn, Neptune", "Uranus, Saturn, Jupiter, Neptune"],
     0,
     "बाहरी क्रम — बृहस्पति(5), शनि(6), अरुण(7), वरुण(8)।",
     "The outer order — Jupiter(5), Saturn(6), Uranus(7), Neptune(8)."),

    ("solar-system", "medium",
     "ग्रहों की चमक का स्रोत क्या है?",
     "What is the source of the planets' glow?",
     ["सूर्य का परावर्तित प्रकाश", "ग्रहों का अपना ज्वालामुखी", "चंद्रमा का प्रकाश", "तारों का संग्रह"],
     ["Sunlight reflected by the planets", "The planets' own volcanoes", "The Moon's light", "A collection of stars"],
     0,
     "ग्रह सूर्य-प्रकाश परावर्तित करते हैं — अपनी चमक उनकी नहीं है।",
     "Planets reflect sunlight — the shine is not their own."),

    ("solar-system", "medium",
     "दो कथन: (i) बुध सबसे छोटा ग्रह है। (ii) बुध सूर्य के सबसे निकट है। सही विकल्प:",
     "Two statements: (i) Mercury is the smallest planet. (ii) Mercury is nearest to the Sun. The correct option:",
     ["दोनों सही हैं", "केवल (i) सही", "केवल (ii) सही", "दोनों गलत"],
     ["Both are correct", "Only (i)", "Only (ii)", "Both wrong"],
     0,
     "बुध आकार में सबसे छोटा और दूरी में सूर्य के सबसे निकट।",
     "Mercury is smallest in size and nearest in distance."),

    ("solar-system", "medium",
     "यदि किसी ग्रह की सूर्य से दूरी सबसे कम हो, तो वह ग्रह कौन-सा होगा और उसका आकार-स्थान क्या होगा?",
     "If a planet's distance from the Sun is the least, which planet is it and what is its size status?",
     ["बुध — साथ ही आकार में सबसे छोटा ग्रह", "बुध — आकार में सबसे बड़ा", "शुक्र — सबसे छोटा", "वरुण — सबसे छोटा"],
     ["Mercury — also the smallest planet in size", "Mercury — the largest in size", "Venus — the smallest", "Neptune — the smallest"],
     0,
     "बुध दोनों सूचियों में है — निकटतम और लघुतम।",
     "Mercury tops both lists — nearest and smallest."),

    ("solar-system", "medium",
     "सबसे चमकीले और सबसे गर्म ग्रह का सही युग्म है:",
     "The correct pair of brightest and hottest planet is:",
     ["शुक्र — दोनों विशेषताएँ एक ही ग्रह की", "बुध — दोनों", "बृहस्पति — चमक; शुक्र — गर्मी", "मंगल — दोनों"],
     ["Venus — both traits belong to the same planet", "Mercury — both", "Jupiter — brightness; Venus — heat", "Mars — both"],
     0,
     "शुक्र चमक और गर्मी दोनों में प्रथम है।",
     "Venus ranks first in both brightness and heat."),

    ("solar-system", "medium",
     "रात्रि-प्रेक्षण में एक वस्तु बहुत चमकीली है पर टिमटिमाती नहीं। वह तारा होगी या ग्रह?",
     "In a night observation an object is very bright but does not twinkle. Is it a star or a planet?",
     ["ग्रह — स्थिर चमक ग्रह का लक्षण है", "तारा — चमकीली वस्तु तारा ही होती है", "उपग्रह", "धूमकेतु"],
     ["A planet — a steady glow is the mark of a planet", "A star — any bright object must be a star", "A satellite", "A comet"],
     0,
     "टिमटिमाना छोड़ देना ही ग्रह की पहचान बन जाता है।",
     "Not twinkling at all becomes the planet's identity."),

    ("solar-system", "medium",
     "सूर्य और ग्रहों के बीच 'प्रकाश का स्रोत' की दृष्टि से संबंध क्या है?",
     "What is the relation between the Sun and the planets from the viewpoint of 'source of light'?",
     ["सूर्य स्रोत है, ग्रह परावर्तक", "ग्रह स्रोत हैं, सूर्य परावर्तक", "दोनों स्रोत हैं", "दोनों परावर्तक हैं"],
     ["The Sun is the source, the planets are reflectors", "The planets are sources, the Sun reflects", "Both are sources", "Both are reflectors"],
     0,
     "एक जलता है, बाकी उसी का प्रकाश दिखाते हैं।",
     "One burns; the rest show its light."),

    # ---- hard (9) ----
    ("solar-system", "hard",
     "तीन कथन: (i) सूर्य तारा है। (ii) सभी ग्रह स्व-प्रकाशमान हैं। (iii) बृहस्पति सबसे बड़ा ग्रह है। गलत कथन कौन-सा है?",
     "Three statements: (i) The Sun is a star. (ii) All planets are self-luminous. (iii) Jupiter is the largest planet. Which is wrong?",
     ["कथन (ii)", "कथन (i)", "कथन (iii)", "तीनों सही"],
     ["Statement (ii)", "Statement (i)", "Statement (iii)", "All three correct"],
     0,
     "ग्रह स्व-प्रकाशमान नहीं होते — यही कथन गलत है।",
     "Planets are not self-luminous — that statement is wrong."),

    ("solar-system", "hard",
     "किसी ग्रह के लिए 'सबसे गर्म' का दावा जाँचने का सही तर्क क्या है?",
     "What is the correct logic for checking a planet's claim of being 'the hottest'?",
     ["केवल सूर्य से निकटता देखना पर्याप्त नहीं — वायुमंडल द्वारा ऊष्मा-रोकना भी देखें; शुक्र इसी से सर्वाधिक गर्म है", "सिर्फ दूरी देखें — निकटतम सबसे गर्म", "सिर्फ आकार देखें — बड़ा सबसे गर्म", "रंग देखें — लाल सबसे गर्म"],
     ["Nearness to the Sun alone is not enough — check heat-trapping by the atmosphere too; Venus is hottest on this count", "Look only at distance — nearest is hottest", "Look only at size — biggest is hottest", "Look at colour — red is hottest"],
     0,
     "शुक्र निकटतम नहीं, फिर भी सबसे गर्म — यही जाँच-तर्क है।",
     "Venus is not nearest yet is hottest — that is the checking logic."),

    ("solar-system", "hard",
     "सूर्य से दूरी के क्रम में छठा ग्रह कौन-सा है?",
     "Which is the sixth planet in order of distance from the Sun?",
     ["शनि", "बृहस्पति", "अरुण", "मंगल"],
     ["Saturn", "Jupiter", "Uranus", "Mars"],
     0,
     "बृहस्पति(5) के बाद शनि(6) आता है।",
     "After Jupiter(5) comes Saturn(6)."),

    ("solar-system", "hard",
     "पृथ्वी, बुध और शुक्र — तीनों में सूर्य की परिक्रमा का घेरा किसका सबसे छोटा माना जाएगा?",
     "Among Earth, Mercury and Venus, whose orbit around the Sun would be considered the smallest?",
     ["बुध का — वह सबसे निकट है", "शुक्र का", "पृथ्वी का", "तीनों का बराबर"],
     ["Mercury's — it is nearest", "Venus's", "Earth's", "All equal"],
     0,
     "जितना निकट, उतना छोटा घेरा — बुध की परिक्रमा सबसे छोटी।",
     "The nearer the planet, the smaller its loop — Mercury's orbit is smallest."),

    ("solar-system", "hard",
     "क्रम-पहेली: बुध और पृथ्वी के ठीक बीच का ग्रह कौन-सा है?",
     "Order puzzle: which planet lies exactly between Mercury and Earth?",
     ["शुक्र", "मंगल", "बृहस्पति", "शनि"],
     ["Venus", "Mars", "Jupiter", "Saturn"],
     0,
     "क्रम बुध-शुक्र-पृथ्वी में बीच वाला शुक्र है।",
     "In the order Mercury-Venus-Earth, the middle one is Venus."),

    ("solar-system", "hard",
     "यदि 'सबसे चमकीला ग्रह' और 'सूर्य का सबसे निकटतम ग्रह' एक ही नहीं हैं, तो दोनों क्रमशः कौन हैं?",
     "If the 'brightest planet' and the 'planet nearest the Sun' are not the same, who are they respectively?",
     ["शुक्र और बुध", "बुध और शुक्र", "बृहस्पति और बुध", "शुक्र और मंगल"],
     ["Venus and Mercury", "Mercury and Venus", "Jupiter and Mercury", "Venus and Mars"],
     0,
     "चमक में शुक्र प्रथम, निकटता में बुध प्रथम।",
     "Venus leads in brightness; Mercury leads in nearness."),

    ("solar-system", "hard",
     "एक कथन-समूह पर विचार कीजिए: (i) पृथ्वी तीसरा ग्रह है। (ii) मंगल चौथा है। (iii) बुध दूसरा है। सही कथनों का समूह चुनिए:",
     "Consider a set of statements: (i) Earth is the third planet. (ii) Mars is fourth. (iii) Mercury is second. Choose the group of correct statements:",
     ["(i) और (ii) सही, (iii) गलत", "तीनों सही", "केवल (iii) सही", "(i) गलत, (ii) गलत, (iii) सही"],
     ["(i) and (ii) correct, (iii) wrong", "All three correct", "Only (iii) correct", "(i) wrong, (ii) wrong, (iii) correct"],
     0,
     "बुध पहला ग्रह है, दूसरा नहीं।",
     "Mercury is the first planet, not the second."),

    ("solar-system", "hard",
     "ग्रह-पहचान: मैं सूर्य की परिक्रमा करता हूँ, पृथ्वी से बड़ा हूँ और सौर परिवार में मुझसे बड़ा कोई ग्रह नहीं। मैं कौन हूँ?",
     "Planet riddle: I revolve around the Sun, I am bigger than Earth, and no planet in the solar system is bigger than me. Who am I?",
     ["बृहस्पति", "शनि", "अरुण", "वरुण"],
     ["Jupiter", "Saturn", "Uranus", "Neptune"],
     0,
     "पृथ्वी से बड़े और सर्वाधिक बड़े — बृहस्पति।",
     "Bigger than Earth and biggest of all — Jupiter."),

    ("solar-system", "hard",
     "ग्रह-पहचान: मैं सूर्य के सबसे निकट हूँ, सबसे छोटा हूँ, पर सबसे गर्म नहीं। मैं कौन हूँ?",
     "Planet riddle: I am nearest the Sun and the smallest, but not the hottest. Who am I?",
     ["बुध", "शुक्र", "मंगल", "अरुण"],
     ["Mercury", "Venus", "Mars", "Uranus"],
     0,
     "निकटतम + लघुतम + गर्म नहीं = बुध; सबसे गर्म शुक्र है।",
     "Nearest + smallest + not hottest = Mercury; Venus is the hottest."),

    # ================= DAY-NIGHT AND SEASONS (50) =================
    # ---- easy (20) ----
    ("day-night-and-seasons", "easy",
     "दिन और रात किस कारण होते हैं?",
     "What causes day and night?",
     ["पृथ्वी के अपने अक्ष पर घूर्णन से", "पृथ्वी के सूर्य से दूर जाने से", "चंद्रमा की परिक्रमा से", "बादलों के ढकने से"],
     ["The Earth's rotation on its own axis", "The Earth moving away from the Sun", "The Moon's revolution", "Covering by clouds"],
     0,
     "घूर्णन से पृथ्वी का एक भाग सूर्य की ओर आता है, दूसरा हटता है।",
     "Rotation brings one part of Earth toward the Sun and takes another away."),

    ("day-night-and-seasons", "easy",
     "पृथ्वी अपने अक्ष पर किस दिशा में घूमती है?",
     "In which direction does the Earth rotate on its axis?",
     ["पश्चिम से पूर्व", "पूर्व से पश्चिम", "उत्तर से दक्षिण", "दक्षिण से उत्तर"],
     ["West to east", "East to west", "North to south", "South to north"],
     0,
     "पश्चिम से पूर्व घूर्णन के कारण सूर्य पूर्व में उगता दिखता है।",
     "West-to-east rotation makes the Sun appear to rise in the east."),

    ("day-night-and-seasons", "easy",
     "ऋतुओं के बदलाव का मुख्य कारण क्या है?",
     "What is the main cause of the change of seasons?",
     ["पृथ्वी का तिर्यक अक्ष लेकर सूर्य की परिक्रमा करना", "पृथ्वी का केवल घूर्णन", "चंद्रमा की छाया", "तारों की चमक"],
     ["The Earth revolving around the Sun on a tilted axis", "The Earth's rotation alone", "The Moon's shadow", "The twinkle of stars"],
     0,
     "तिर्यक अक्ष + परिक्रमा = ऋतु परिवर्तन।",
     "Tilted axis + revolution = seasonal change."),

    ("day-night-and-seasons", "easy",
     "जब पृथ्वी का कोई भाग सूर्य की ओर होता है तो वहाँ क्या होता है?",
     "When a part of the Earth faces the Sun, what is it there?",
     ["दिन", "रात", "ग्रहण", "ऋतु नहीं बदलती"],
     ["Day", "Night", "An eclipse", "No change of season"],
     0,
     "सूर्य की ओर मुड़ा भाग दिन में रहता है।",
     "The part turned toward the Sun stays in day."),

    ("day-night-and-seasons", "easy",
     "जब पृथ्वी का कोई भाग सूर्य से हटा हुआ होता है तो वहाँ क्या होता है?",
     "When a part of the Earth is turned away from the Sun, what is it there?",
     ["रात", "दिन", "दोपहर", "सूर्यग्रहण"],
     ["Night", "Day", "Noon", "A solar eclipse"],
     0,
     "सूर्य से दूर मुड़े भाग में रात होती है।",
     "The part turned away from the Sun has night."),

    ("day-night-and-seasons", "easy",
     "सूर्य किस दिशा में उगता प्रतीत होता है?",
     "In which direction does the Sun appear to rise?",
     ["पूर्व में", "पश्चिम में", "उत्तर में", "दक्षिण में"],
     ["In the east", "In the west", "In the north", "In the south"],
     0,
     "पृथ्वी के पश्चिम-से-पूर्व घूर्णन से सूर्य पूर्व दिशा में उगता दिखता है।",
     "Earth's west-to-east rotation makes the Sun rise in the east."),

    ("day-night-and-seasons", "easy",
     "पृथ्वी की परिक्रमा का केंद्र कौन है?",
     "What is the centre of the Earth's revolution?",
     ["सूर्य", "चंद्रमा", "ध्रुवतारा", "बृहस्पति"],
     ["The Sun", "The Moon", "The Pole Star", "Jupiter"],
     0,
     "पृथ्वी सूर्य की परिक्रमा करती है।",
     "The Earth revolves around the Sun."),

    ("day-night-and-seasons", "easy",
     "पृथ्वी का घूर्णन और परिक्रमा में क्या संबंध है?",
     "What is the relation between the Earth's rotation and revolution?",
     ["घूर्णन अपने अक्ष पर, परिक्रमा सूर्य के चारों ओर", "दोनों एक ही हैं", "घूर्णन सूर्य के चारों ओर होता है", "परिक्रमा अपने अक्ष पर होती है"],
     ["Rotation is on its own axis, revolution is around the Sun", "Both are the same", "Rotation is around the Sun", "Revolution is on its own axis"],
     0,
     "घूर्णन = अक्ष पर चक्कर; परिक्रमा = सूर्य का चक्कर।",
     "Rotation = spin on the axis; revolution = round of the Sun."),

    ("day-night-and-seasons", "easy",
     "उत्तरी गोलार्ध में जब गर्मी होती है तो दक्षिणी गोलार्ध में क्या होता है?",
     "When it is summer in the northern hemisphere, what is it in the southern hemisphere?",
     ["सर्दी", "भी गर्मी", "वर्षा", "ग्रहण"],
     ["Winter", "Summer too", "Rainy season", "An eclipse"],
     0,
     "तिर्यक अक्ष के कारण दोनों गोलार्धों में ऋतुएँ उलट होती हैं।",
     "Because of the tilted axis, the two hemispheres have opposite seasons."),

    ("day-night-and-seasons", "easy",
     "पृथ्वी का घूर्णन अक्ष सीधा है या तिरछा?",
     "Is the Earth's axis of rotation upright or tilted?",
     ["तिरछा", "पूर्ण सीधा", "कभी सीधा कभी तिरछा", "लेटा हुआ"],
     ["Tilted", "Perfectly upright", "Sometimes straight, sometimes tilted", "Lying down"],
     0,
     "पृथ्वी तिर्यक अक्ष पर घूमती है — यही ऋतुओं का आधार है।",
     "The Earth spins on a tilted axis — the basis of seasons."),

    ("day-night-and-seasons", "easy",
     "एक बार दिन और एक बार रात मिलकर क्या बनाते हैं?",
     "One day and one night together make what?",
     ["एक दिन (पूरा)", "एक ऋतु", "एक वर्ष", "एक माह"],
     ["One full day", "One season", "One year", "One month"],
     0,
     "दिन-रात का पूरा चक्र ही एक दिन कहलाता है।",
     "The full cycle of day and night is called one day."),

    ("day-night-and-seasons", "easy",
     "दोपहर में सूर्य आकाश में कहाँ दिखता है?",
     "Where does the Sun appear in the sky at noon?",
     ["लगभग सबसे ऊँचाई पर", "क्षितिज के पास", "पूर्व में उगते हुए", "पश्चिम में डूबते हुए"],
     ["Almost at its highest point", "Near the horizon", "Rising in the east", "Setting in the west"],
     0,
     "दोपहर सूर्य अपनी अधिकतम ऊँचाई पर पहुँचता है।",
     "At noon the Sun reaches its highest point."),

    ("day-night-and-seasons", "easy",
     "सूर्योदय के समय सूर्य किस दिशा में दिखता है?",
     "In which direction is the Sun seen at sunrise?",
     ["पूर्व", "पश्चिम", "उत्तर", "दक्षिण"],
     ["East", "West", "North", "South"],
     0,
     "उगता सूर्य पूर्व दिशा में होता है।",
     "The rising Sun is in the east."),

    ("day-night-and-seasons", "easy",
     "सूर्यास्त के समय सूर्य किस दिशा में डूबता दिखता है?",
     "In which direction does the Sun appear to set?",
     ["पश्चिम", "पूर्व", "उत्तर", "दक्षिण"],
     ["West", "East", "North", "South"],
     0,
     "पश्चिम में डूबता सूर्य घूर्णन का ही परिणाम है।",
     "The setting Sun in the west is also a result of rotation."),

    ("day-night-and-seasons", "easy",
     "रात होने का कारण क्या है?",
     "What is the reason for night?",
     ["पृथ्वी का वह भाग सूर्य के सामने से हट जाता है", "सूर्य बुझ जाता है", "चंद्रमा सूर्य को ढक लेता है", "बादल सूर्य को छिपा लेते हैं"],
     ["That part of the Earth turns away from the Sun", "The Sun goes out", "The Moon covers the Sun", "Clouds hide the Sun"],
     0,
     "सूर्य कभी नहीं बुझता — हटने वाले भाग में रात होती है।",
     "The Sun never goes out — the turning-away part has night."),

    ("day-night-and-seasons", "easy",
     "गर्मी के दिनों में दिन और रात में से कौन लंबा होता है?",
     "In the summer days, which is longer — day or night?",
     ["दिन", "रात", "दोनों बराबर", "यह जगह से निर्भर नहीं करता"],
     ["The day", "The night", "Both equal", "It does not depend on place"],
     0,
     "गर्मी में उस गोलार्ध के दिन लंबे हो जाते हैं।",
     "In summer, days become longer in that hemisphere."),

    ("day-night-and-seasons", "easy",
     "सर्दी के दिनों में दिन और रात में से कौन लंबा होता है?",
     "In the winter days, which is longer — day or night?",
     ["रात", "दिन", "दोनों बराबर", "हर जगह दिन"],
     ["The night", "The day", "Both equal", "The day everywhere"],
     0,
     "सर्दी में उस गोलार्ध की रातें लंबी हो जाती हैं।",
     "In winter, nights become longer in that hemisphere."),

    ("day-night-and-seasons", "easy",
     "पृथ्वी की परिक्रमा ऋतुओं से कैसे जुड़ी है?",
     "How is the Earth's revolution linked with the seasons?",
     ["तिर्यक अक्ष पर परिक्रमा करते हुए प्रत्येक भाग को सूर्य की तीव्र या तिर्छी किरणें बदलते-बदलते मिलती हैं", "परिक्रमा से दिन-रात बदलते हैं", "परिक्रमा से पृथ्वी ठंडी हो जाती है", "परिक्रमा का ऋतुओं से कोई संबंध नहीं"],
     ["Revolving on a tilted axis, each part gets direct or slanting rays alternately", "Revolution changes day and night", "Revolution cools the Earth", "Revolution has no link with seasons"],
     0,
     "परिक्रमा के दौरान किरणों का झुकाव बदलना ही ऋतुओं का आधार है।",
     "The changing slant of rays during revolution is the basis of seasons."),

    ("day-night-and-seasons", "easy",
     "पृथ्वी पर प्रकाश और ऊष्मा का मुख्य स्रोत कौन है?",
     "What is the main source of light and heat on the Earth?",
     ["सूर्य", "चंद्रमा", "तारे", "बिजली"],
     ["The Sun", "The Moon", "The stars", "Electricity"],
     0,
     "सूर्य ही पृथ्वी के लिए प्रकाश-ऊष्मा का मूल स्रोत है।",
     "The Sun is the prime source of light and heat for the Earth."),

    ("day-night-and-seasons", "easy",
     "घूर्णन से होने वाली मुख्य घटना कौन-सी है?",
     "Which is the main phenomenon caused by rotation?",
     ["दिन-रात का बदलाव", "ऋतु बदलाव", "चंद्र कला बदलना", "ग्रहण"],
     ["The change of day and night", "Change of seasons", "Change of moon phases", "Eclipses"],
     0,
     "घूर्णन = दिन-रात; परिक्रमा = ऋतुएँ।",
     "Rotation = day-night; revolution = seasons."),

    # ---- medium (21) ----
    ("day-night-and-seasons", "medium",
     "सूर्य वास्तव में उगता-डूबता नहीं है, फिर भी हमें ऐसा क्यों दिखता है?",
     "The Sun actually neither rises nor sets, so why does it appear so to us?",
     ["पृथ्वी के घूर्णन से सूर्य की स्थिति बदलती प्रतीत होती है", "सूर्य पृथ्वी की परिक्रमा करता है", "चंद्रमा सूर्य को खिसकाता है", "वायुमंडल सूर्य को हिलाता है"],
     ["The Earth's rotation makes the Sun's position appear to change", "The Sun revolves around the Earth", "The Moon pushes the Sun", "The atmosphere shakes the Sun"],
     0,
     "गति हमारी है, दिखना सूर्य का — घूर्णन का भ्रम।",
     "The motion is ours; the appearance is the Sun's — an illusion of rotation."),

    ("day-night-and-seasons", "medium",
     "यदि पृथ्वी घूर्णन करना बंद कर दे (परिक्रमा जारी रहे), तो क्या होगा?",
     "If the Earth stopped rotating (revolution continuing), what would happen?",
     ["एक ओर स्थायी दिन, दूसरी ओर स्थायी रात", "ऋतुएँ बंद हो जाएँगी", "दिन-रात पहले जैसे ही रहेंगे", "चंद्रमा गिर जाएगा"],
     ["Permanent day on one side, permanent night on the other", "Seasons would stop", "Day-night would stay as before", "The Moon would fall"],
     0,
     "दिन-रात घूर्णन की देन है — घूर्णन रुका तो एक ओर अंधेरा छाया रहेगा।",
     "Day-night is rotation's gift — stop rotation and one side stays dark."),

    ("day-night-and-seasons", "medium",
     "यदि पृथ्वी का अक्ष पूरी तरह सीधा हो जाए, तो ऋतुओं का क्या होगा?",
     "If the Earth's axis became perfectly upright, what would happen to the seasons?",
     ["ऋतु बदलाव लगभग नहीं जैसा रह जाएगा — सूर्य की किरणें हर समय उतनी ही सीधी आएँगी", "ऋतुएँ और तेज़ बदलेंगी", "कुछ नहीं बदलेगा", "सिर्फ रातें लंबी होंगी"],
     ["Seasonal change would nearly vanish — the Sun's rays would fall equally straight all year", "Seasons would change more sharply", "Nothing would change", "Only nights would lengthen"],
     0,
     "तिरछापन ही किरणों के झुकाव को बदलता है; सीधे अक्ष पर यह खेल समाप्त।",
     "The tilt alone changes the rays' slant; an upright axis ends that game."),

    ("day-night-and-seasons", "medium",
     "'पृथ्वी सूर्य के अधिक निकट आने से गर्मी होती है' — इस धारणा का सही निर्णय कीजिए:",
     "'Summer occurs because the Earth comes closer to the Sun' — judge this notion correctly:",
     ["भ्रांति — ऋतुएँ अक्ष के तिरछेपन से होती हैं, निकटता से नहीं", "पूर्णतः सही", "आंशिक सही", "यह केवल सर्दी पर लागू होता है"],
     ["A misconception — seasons come from the axial tilt, not nearness", "Completely correct", "Partly correct", "It applies only to winter"],
     0,
     "गर्मी में पृथ्वी सूर्य के सबसे निकट भी नहीं होती — तिर्यक किरणें ही कारण हैं।",
     "In summer the Earth is not even nearest the Sun — slanting rays are the cause."),

    ("day-night-and-seasons", "medium",
     "गर्मी में गर्मी क्यों अधिक लगती है — किरणों की दृष्टि से समझाइए:",
     "Explain from the viewpoint of rays why summer feels hotter:",
     ["उस गोलार्ध पर सूर्य की किरणें लगभग सीधी और केंद्रित पड़ती हैं", "किरणें तिरछी और फैली हुई पड़ती हैं", "किरणें रात में भी आती हैं", "किरणें चंद्रमा से टकराती हैं"],
     ["The Sun's rays fall almost straight and concentrated on that hemisphere", "The rays fall slanting and spread out", "The rays also come at night", "The rays strike the Moon"],
     0,
     "सीधी किरणें छोटे क्षेत्र में अधिक ऊष्मा देती हैं।",
     "Straight rays deliver more heat to a smaller area."),

    ("day-night-and-seasons", "medium",
     "सर्दी में उसी गोलार्ध को सूर्य की किरणें कैसी मिलती हैं?",
     "How does the same hemisphere receive the Sun's rays in winter?",
     ["तिरछी और फैली हुई — कम ऊष्मा", "अधिक सीधी — अधिक ऊष्मा", "बिल्कुल नहीं मिलतीं", "दोगुनी तेज़"],
     ["Slanting and spread out — less heat", "More direct — more heat", "Not received at all", "Twice as intense"],
     0,
     "तिरछी किरणें बड़े क्षेत्र पर फैलकर कम गर्मी देती हैं।",
     "Slanting rays spread over a larger area and give less warmth."),

    ("day-night-and-seasons", "medium",
     "दोपहर की अपेक्षा सुबह सूर्य की गर्मी कम क्यों लगती है?",
     "Why does the Sun feel less hot in the morning compared with noon?",
     ["सुबह किरणें तिरछी पड़ती हैं, दोपहर में लगभग सीधी", "सुबह सूर्य छोटा होता है", "सुबह सूर्य सूख जाता है", "दोपहर में सूर्य पृथ्वी के निकट आ जाता है"],
     ["In the morning the rays strike slanting; near noon almost straight", "The Sun is smaller in the morning", "The Sun dries out in the morning", "At noon the Sun comes nearer the Earth"],
     0,
     "किरणों का झुकाव बदलने से ऊष्मा का बंटवारा बदलता है।",
     "As the rays' slant changes, the spread of heat changes."),

    ("day-night-and-seasons", "medium",
     "पृथ्वी के दो विपरीत गोलार्धों में ऋतुएँ उलट क्यों होती हैं?",
     "Why are seasons opposite in the Earth's two opposite hemispheres?",
     ["एक गोलार्ध सूर्य की ओर अधिक झुका होता है जब दूसरा हटा होता है — तिरछे अक्ष का परिणाम", "दोनों गोलार्ध अलग-अलग गति से घूमते हैं", "चंद्रमा एक ओर खींचता है", "एक गोलार्ध रात में रहता है"],
     ["One hemisphere tilts toward the Sun while the other tilts away — the result of the tilted axis", "The hemispheres spin at different speeds", "The Moon pulls one side", "One hemisphere stays in night"],
     0,
     "एक साथ दोनों की सूर्य-दशा उलट हो ही नहीं सकती — अक्ष झुका है।",
     "With the axis tilted, the two sides cannot face the Sun equally at once."),

    ("day-night-and-seasons", "medium",
     "जब भारत में गर्मी हो, तो ऑस्ट्रेलिया में कौन-सी ऋतु होगी?",
     "When it is summer in India, which season will it be in Australia?",
     ["सर्दी — दोनों विपरीत गोलार्धों में हैं", "भी गर्मी", "वर्षा", "ऋतु वहाँ नहीं बदलती"],
     ["Winter — they lie in opposite hemispheres", "Summer too", "Rainy season", "Seasons do not change there"],
     0,
     "भारत उत्तर में, ऑस्ट्रेलिया दक्षिण में — ऋतुएँ उलट।",
     "India in the north, Australia in the south — opposite seasons."),

    ("day-night-and-seasons", "medium",
     "घूर्णन और परिक्रमा के परिणामों का सही मिलान कौन-सा है?",
     "Which is the correct matching of the results of rotation and revolution?",
     ["घूर्णन — दिन-रात; परिक्रमा — ऋतुएँ", "घूर्णन — ऋतुएँ; परिक्रमा — दिन-रात", "दोनों — दिन-रात", "दोनों — ऋतुएँ"],
     ["Rotation — day and night; revolution — seasons", "Rotation — seasons; revolution — day and night", "Both — day and night", "Both — seasons"],
     0,
     "हर घटना का अपना अलग गति-आधार है।",
     "Each phenomenon has its own basis of motion."),

    ("day-night-and-seasons", "medium",
     "कथन-जाँच: (i) पृथ्वी घूर्णन से दिन-रात देती है। (ii) तिर्यक अक्ष पर परिक्रमा से ऋतुएँ। (iii) ऋतुएँ चंद्रमा की परिक्रमा से आती हैं। सही समूह:",
     "Statement check: (i) Rotation gives day-night. (ii) Revolution on a tilted axis gives seasons. (iii) Seasons come from the Moon's revolution. Correct set:",
     ["(i) और (ii) सही, (iii) गलत", "तीनों सही", "केवल (iii) सही", "(i) गलत, (ii) सही, (iii) सही"],
     ["(i) and (ii) correct, (iii) wrong", "All three correct", "Only (iii) correct", "(i) wrong, (ii) correct, (iii) correct"],
     0,
     "चंद्रमा की परिक्रमा कलाओँ से जुड़ी है, ऋतुओं से नहीं।",
     "The Moon's revolution relates to phases, not seasons."),

    ("day-night-and-seasons", "medium",
     "वास्तविकता में 'सूर्य की परिक्रमा' कौन किसकी करता है?",
     "In reality, who revolves around whom as 'revolution around the Sun'?",
     ["पृथ्वी सूर्य की", "सूर्य पृथ्वी की", "चंद्रमा सूर्य की", "तारे पृथ्वी की"],
     ["The Earth around the Sun", "The Sun around the Earth", "The Moon around the Sun", "The stars around the Earth"],
     0,
     "पृथ्वी सहित सभी ग्रह सूर्य की परिक्रमा करते हैं।",
     "All planets including the Earth revolve around the Sun."),

    ("day-night-and-seasons", "medium",
     "किसी स्थान पर सूर्योदय से सूर्यास्त तक का समय बदलता रहता है। इसका सही कारण चुनिए:",
     "The span from sunrise to sunset keeps changing at a place. Choose the correct reason:",
     ["तिर्यक अक्ष पर परिक्रमा के कारण सूर्य की दशा और किरणों का झुकाव बदलता रहता है", "पृथ्वी की गति रुक-रुककर चलती है", "चंद्रमा दिन खींच लेता है", "बादलों की गिनती बदलती है"],
     ["On the tilted-axis revolution, the Sun's aspect and the rays' slant keep changing", "The Earth moves in fits and starts", "The Moon stretches the day", "The count of clouds changes"],
     0,
     "वर्ष भर किरणों के झुकाव का बदलाव ही दिन की लंबाई बदलता है।",
     "The year-round change in the rays' slant alters day length."),

    ("day-night-and-seasons", "medium",
     "दिन में सूर्य 'चलता' दिखने का कारण-प्रभाव युग्म क्या है?",
     "What is the cause-effect pair for the Sun appearing to 'move' during the day?",
     ["कारण — पृथ्वी का घूर्णन; प्रभाव — सूर्य का पूर्व से पश्चिम बढ़ना प्रतीत होना", "कारण — सूर्य की गाड़ी; प्रभाव — आकाश-पथ", "कारण — बादल; प्रभाव — छाया", "कारण — चंद्रमा; प्रभाव — ज्वार"],
     ["Cause — the Earth's rotation; effect — the Sun appearing to march east to west", "Cause — the Sun's chariot; effect — the sky path", "Cause — clouds; effect — shadow", "Cause — the Moon; effect — tides"],
     0,
     "पृथ्वी घूमती है, सूर्य की चाल दिखती है।",
     "The Earth spins; the Sun seems to travel."),

    ("day-night-and-seasons", "medium",
     "पृथ्वी का घूर्णन और चंद्रमा की कलाएँ — इनमें क्या संबंध है?",
     "What is the relation between the Earth's rotation and the Moon's phases?",
     ["दोनों अलग-अलग घटनाएँ हैं — कलाएँ चंद्रमा की परिक्रमा से जुड़ी हैं", "घूर्णन से ही कलाएँ बदलती हैं", "कलाओँ से पृथ्वी घूमती है", "दोनों एक ही घटना हैं"],
     ["They are separate phenomena — phases relate to the Moon's revolution", "Phases change due to rotation itself", "The Earth spins because of phases", "Both are one phenomenon"],
     0,
     "दिन-रात और कलाएँ दो अलग खेल हैं।",
     "Day-night and phases are two different games."),

    ("day-night-and-seasons", "medium",
     "उत्तरी गोलार्ध पर गर्मी के समय सूर्य की दशा कैसी होती है?",
     "What is the Sun's aspect over the northern hemisphere during its summer?",
     ["उत्तरी गोलार्ध सूर्य की ओर झुका होता है — किरणें अधिक सीधी", "वह सूर्य से हटा होता है", "किरणें बिल्कुल नहीं पड़तीं", "किरणें केवल रात में आती हैं"],
     ["The northern hemisphere tilts toward the Sun — rays fall more directly", "It tilts away from the Sun", "No rays fall at all", "Rays come only at night"],
     0,
     "झुकाव सूर्य की ओर ही गर्मी का संकेत है।",
     "Tilting toward the Sun is the very sign of summer."),

    ("day-night-and-seasons", "medium",
     "एक ही दिन में भारत में सुबह होते ही अमेरिका में अभी रात क्यों चल रही होती है?",
     "On the same date, why is it still night in America while it is morning in India?",
     ["दोनों पृथ्वी के विपरीत भागों पर हैं — एक साथ एक ओर दिन, दूसरी ओर रात", "अमेरिका का सूर्य देर से उगता है", "अमेरिका पर चंद्रमा छाया रहता है", "अमेरिका की घड़ियाँ ठीक नहीं"],
     ["They lie on opposite parts of the Earth — one side in day, the other in night at the same time", "America's Sun rises late", "The Moon stays over America", "American clocks are wrong"],
     0,
     "गोल पृथ्वी के दो ओर की दशा एक साथ उलट होती है।",
     "The two sides of a globe face opposite conditions at once."),

    ("day-night-and-seasons", "medium",
     "घूर्णन के कारण पृथ्वी पर बनती 'दिन-रेखा' का अर्थ क्या है?",
     "What is the meaning of the 'day-night line' formed on the Earth due to rotation?",
     ["वह काल्पनिक सीमा जहाँ दिन और रात के भाग मिलते हैं और जो घूर्णन से खिसकती रहती है", "वह रेखा जहाँ ऋतुएँ बदलती हैं", "वह रेखा जहाँ ग्रहण होता है", "वह रेखा जो चंद्रमा बनाता है"],
     ["The imaginary boundary where the day and night parts meet, which keeps shifting with rotation", "The line where seasons change", "The line where eclipses happen", "The line drawn by the Moon"],
     0,
     "आधी पृथ्वी रोशन, आधी अंधेरी — बीच की हद दिन-रेखा।",
     "Half the Earth lit, half dark — the boundary between is the day-night line."),

    ("day-night-and-seasons", "medium",
     "किसी वर्ष में गर्मी से सर्दी और सर्दी से गर्मी तक का पूरा चक्र किस गति से पूरा होता है?",
     "The full cycle from summer to winter and back to summer in a year is completed by which motion?",
     ["पृथ्वी की सूर्य-परिक्रमा से", "पृथ्वी के घूर्णन से", "चंद्रमा की परिक्रमा से", "सूर्य के घूर्णन से"],
     ["By the Earth's revolution around the Sun", "By the Earth's rotation", "By the Moon's revolution", "By the Sun's rotation"],
     0,
     "ऋतु-चक्र परिक्रमा का ही चक्र है।",
     "The season cycle is the revolution's cycle."),

    ("day-night-and-seasons", "medium",
     "दो कथन: (i) दिन-रात और ऋतुएँ दोनों एक ही गति से होते हैं। (ii) ऋतुओं में अक्ष का तिरछापन अनिवार्य है। सही विकल्प:",
     "Two statements: (i) Day-night and seasons both arise from one and the same motion. (ii) The axial tilt is essential for seasons. The correct option:",
     ["(i) गलत, (ii) सही", "दोनों सही", "दोनों गलत", "(i) सही, (ii) गलत"],
     ["(i) wrong, (ii) correct", "Both correct", "Both wrong", "(i) correct, (ii) wrong"],
     0,
     "दिन-रात घूर्णन से, ऋतुएँ तिरछे अक्ष पर परिक्रमा से — गतियाँ अलग हैं।",
     "Day-night from rotation, seasons from tilted revolution — the motions differ."),

    ("day-night-and-seasons", "medium",
     "ग्रहों के लिए 'दिन-रात होना' क्या दर्शाता है?",
     "What does 'having day and night' indicate for a planet?",
     ["वह अपने अक्ष पर घूमता है", "वह स्थिर है", "उसका कोई उपग्रह है", "वह सूर्य के चारों ओर नहीं घूमता"],
     ["It rotates on its axis", "It is stationary", "It has a satellite", "It does not revolve around the Sun"],
     0,
     "घूर्णन ही किसी भी ग्रह पर दिन-रात लाता है।",
     "Rotation brings day-night to any planet."),

    # ---- hard (9) ----
    ("day-night-and-seasons", "hard",
     "पृथ्वी सूर्य से थोड़ी-सी दूरी पर निकट आती-जाती रहती है, फिर भी यह ऋतुओं का कारण नहीं। निर्णायक कारण स्पष्ट कीजिए:",
     "The Earth's distance from the Sun keeps changing slightly, yet it is not the cause of seasons. State the decisive cause:",
     ["अक्ष का तिरछापन — जिससे किरणों का झुकाव और दिन की अवधि बदलती है", "समुद्रों की गहराई", "चंद्रमा की छाया", "वायु की दिशा"],
     ["The axial tilt — which changes the rays' slant and the day length", "The depth of oceans", "The Moon's shadow", "The wind's direction"],
     0,
     "दूरी का थोड़ा बदलाव व्यर्थ है; झुकाव ही निर्णायक है।",
     "The slight change of distance is immaterial; the tilt decides."),

    ("day-night-and-seasons", "hard",
     "तीन कथन: (i) घूर्णन पश्चिम से पूर्व है। (ii) इसीलिए सूर्य पूर्व से उगता प्रतीत होता है। (iii) वास्तव में सूर्य आकाश में घूमता है। गलत कथन:",
     "Three statements: (i) Rotation is west to east. (ii) Hence the Sun appears to rise in the east. (iii) Actually the Sun travels around the sky. The wrong statement:",
     ["कथन (iii) — सूर्य नहीं, पृथ्वी घूमती है", "कथन (i)", "कथन (ii)", "तीनों सही"],
     ["Statement (iii) — the Earth, not the Sun, moves", "Statement (i)", "Statement (ii)", "All three correct"],
     0,
     "आकाश-गति सूर्य की दिखने वाली भ्रम-गति है।",
     "The sky journey is the Sun's apparent, illusory motion."),

    ("day-night-and-seasons", "hard",
     "उत्तरी गोलार्ध में 21 जून के आसपास की स्थिति में सूर्य की किरणें कैसी पड़ती हैं और परिणाम क्या होता है?",
     "Around 21 June, how do the Sun's rays fall on the northern hemisphere and what is the result?",
     ["लगभग सीधी — उत्तरी गोलार्ध में गर्मी और लंबे दिन", "तिरछी — सर्दी और लंबी रातें", "कोई किरण नहीं पड़ती", "किरणें दक्षिणी गोलार्ध पर सीधी पड़ती हैं"],
     ["Almost direct — summer and long days in the northern hemisphere", "Slanting — winter and long nights", "No rays fall", "The rays fall straight on the southern hemisphere"],
     0,
     "उत्तरी झुकाव की चरम स्थिति में गर्मी और लंबे दिन आते हैं।",
     "At the peak of the northern tilt come summer and long days."),

    ("day-night-and-seasons", "hard",
     "मान लीजिए किसी ग्रह का अक्ष बिल्कुल सीधा है और वह परिक्रमा करता है। उस ग्रह पर क्या बदलेगा?",
     "Suppose a planet's axis is perfectly upright and it revolves. What will change on that planet?",
     ["दिन-रात बदलेंगे, ऋतु-बदलाव लगभग नहीं जैसा रहेगा", "ऋतुएँ बदलेंगी, दिन-रात नहीं", "दोनों बंद हो जाएँगे", "कुछ भी नहीं बदलेगा"],
     ["Day-night will change but seasonal change will nearly vanish", "Seasons will change but not day-night", "Both will stop", "Nothing will change"],
     0,
     "घूर्णन जारी है तो दिन-रात हैं; तिरछापन नहीं तो ऋतु-खेल नहीं।",
     "With rotation on, day-night stays; without tilt, no season play."),

    ("day-night-and-seasons", "hard",
     "दो शहर विषुवत रेखा के ठीक उत्तर और ठीक दक्षिण में बराबर दूरी पर हैं। ऋतु-दृष्टि से इनकी दशा कैसी होगी?",
     "Two cities lie at equal distances just north and just south of the equator. How will their conditions be season-wise?",
     ["लगभग उलट — जब एक में गर्मी की दशा होगी तो दूसरे में सर्दी जैसी", "दोनों में हमेशा एक ही ऋतु", "दोनों में कभी ऋतु नहीं बदलती", "दोनों में छह-छह ऋतुएँ"],
     ["Roughly opposite — when one has summer-like conditions the other has winter-like", "Always the same season in both", "Seasons never change in either", "Six seasons in each"],
     0,
     "विषुवत रेखा के आर-पार ऋतु-दशाएँ उलट दिशा में चलती हैं।",
     "Across the equator, seasonal conditions run opposite."),

    ("day-night-and-seasons", "hard",
     "'पृथ्वी गोल है' — इस तथ्य का दिन-रात से क्या संबंध है?",
     "How is the fact that 'the Earth is round' related to day and night?",
     ["गोलाई के कारण एक ही समय पर आधी पृथ्वी रोशन और आधी अंधेरी रह सकती है", "गोलाई से दिन लंबे होते हैं", "गोलाई से रात गर्म होती है", "कोई संबंध नहीं"],
     ["Because of roundness, half the Earth can be lit and half dark at the same time", "Roundness makes days longer", "Roundness makes nights warm", "No relation"],
     0,
     "समतल होती तो सब एक साथ रोशन होता; गोलाई आधे-आधे बंटवारे की जननी है।",
     "Were it flat, all would light up together; roundness births the half-half split."),

    ("day-night-and-seasons", "hard",
     "कारण-प्रभाव का गलत युग्म चुनिए:",
     "Choose the WRONG cause-effect pair:",
     ["पृथ्वी का घूर्णन — ऋतु परिवर्तन", "पृथ्वी का घूर्णन — दिन-रात", "तिर्यक अक्ष पर परिक्रमा — ऋतु परिवर्तन", "परिक्रमा — वर्ष का चक्र"],
     ["The Earth's rotation — change of seasons", "The Earth's rotation — day and night", "Revolution on tilted axis — change of seasons", "Revolution — the yearly cycle"],
     0,
     "घूर्णन से ऋतु नहीं बदलती — यही युग्म गलत है।",
     "Rotation does not change seasons — that pair is wrong."),

    ("day-night-and-seasons", "hard",
     "एक यात्री पृथ्वी की सतह पर रात के दौरान सूर्य को नहीं देख पाता। इसका भौतिक कारण क्या है?",
     "A traveller on the Earth's surface cannot see the Sun during night. What is the physical reason?",
     ["उसका भाग सूर्य के सामने नहीं है — पृथ्वी का ढाँचा ही उसे सूर्य से ढक देता है", "रात में सूर्य बुझ जाता है", "चंद्रमा सूर्य को रोक लेता है", "तारे सूर्य को बाँध देते हैं"],
     ["His part does not face the Sun — the Earth's own bulk blocks it", "The Sun extinguishes at night", "The Moon stops the Sun", "The stars tie up the Sun"],
     0,
     "पृथ्वी का गोल शरीर ही सूर्य-प्रकाश की रात की दीवार है।",
     "The Earth's own globe is the wall that blocks sunlight at night."),

    ("day-night-and-seasons", "hard",
     "गर्मी में दिन लंबे और सर्दी में छोटे क्यों होते हैं? सबसे सही व्याख्या चुनिए:",
     "Why are days longer in summer and shorter in winter? Choose the most correct explanation:",
     ["गोलार्ध के सूर्य की ओर या दूर झुकने से प्रकाशित चाप का आकार बदल जाता है", "सूर्य की गति बदल जाती है", "पृथ्वी की गति बदल जाती है", "चंद्रमा दिन खींचता-सिकोड़ता है"],
     ["The hemisphere's tilt toward or away from the Sun changes the size of its lit arc", "The Sun's speed changes", "The Earth's speed changes", "The Moon stretches and shrinks the day"],
     0,
     "झुके गोलार्ध का बड़ा चाप रोशनी में रहता है — दिन लंबा।",
     "A tilted hemisphere keeps a larger arc in sunlight — a longer day."),
]
