# -*- coding: utf-8 -*-
"""P12 part 2 — Space, Earth & Basic Physical Phenomena (chapter-12).
T3 moon-phases-and-eclipses (E20/M21/H9) + T4 indian-space-missions (E20/M22/H8).
Tuple: (topic, difficulty, q_hi, q_en, opts_hi[4], opts_en[4], correct_idx=0, expl_hi, expl_en)
All authored with correct_idx 0; answer-position rotation happens in gen script.
Named facts restricted to meta content: Aryabhata (first Indian satellite),
Chandrayaan, Mangalyaan, ISRO; satellite uses = communication/weather/broadcasting.
"""

PART2 = [
    # ================= MOON PHASES AND ECLIPSES (50) =================
    # ---- easy (20) ----
    ("moon-phases-and-eclipses", "easy",
     "चंद्रमा पृथ्वी का क्या है?",
     "What is the Moon for the Earth?",
     ["उपग्रह", "ग्रह", "तारा", "सूर्य का भाई"],
     ["A satellite", "A planet", "A star", "The Sun's brother"],
     0,
     "चंद्रमा पृथ्वी की परिक्रमा करने वाला प्राकृतिक उपग्रह है।",
     "The Moon is the natural satellite revolving around the Earth."),

    ("moon-phases-and-eclipses", "easy",
     "चंद्रमा की कलाएँ किस कारण बदलती हैं?",
     "Why do the Moon's phases change?",
     ["सूर्य-पृथ्वी-चंद्रमा की बदलती स्थितियों के कारण", "बादलों के ढकने से", "चंद्रमा के आकार बदलने से", "पृथ्वी की छाया से रोज़"],
     ["Due to the changing positions of the Sun, Earth and Moon", "Due to covering by clouds", "Because the Moon's size changes", "Due to the Earth's shadow daily"],
     0,
     "स्थिति बदलती है तो चंद्रमा का रोशन भाग अलग-अलग दिखता है।",
     "As the arrangement changes, a different lit portion of the Moon faces us."),

    ("moon-phases-and-eclipses", "easy",
     "चंद्रमा अपना प्रकाश स्वयं बनाता है या नहीं?",
     "Does the Moon produce its own light?",
     ["नहीं — वह सूर्य का प्रकाश परावर्तित करता है", "हाँ, वह स्वयं जलता है", "वह तारों से प्रकाश लेता है", "वह पृथ्वी का प्रकाश लौटाता है"],
     ["No — it reflects the Sun's light", "Yes, it burns on its own", "It takes light from stars", "It returns the Earth's light"],
     0,
     "चंद्रमा परावर्तक है, ज्वालामुखी नहीं।",
     "The Moon is a reflector, not a lamp."),

    ("moon-phases-and-eclipses", "easy",
     "चंद्र ग्रहण कैसे होता है?",
     "How does a lunar eclipse occur?",
     ["जब चंद्रमा पृथ्वी की छाया में आ जाता है", "जब सूर्य चंद्रमा को ढक देता है", "जब चंद्रमा सूर्य को ढक देता है", "जब बादल चाँद को ढक लेते हैं"],
     ["When the Moon enters the Earth's shadow", "When the Sun covers the Moon", "When the Moon covers the Sun", "When clouds hide the Moon"],
     0,
     "पृथ्वी की छाया में चंद्रमा = चंद्र ग्रहण (नोट्स का ही कथन)।",
     "The Moon in the Earth's shadow = lunar eclipse (the notes' own statement)."),

    ("moon-phases-and-eclipses", "easy",
     "सूर्य ग्रहण कैसे होता है?",
     "How does a solar eclipse occur?",
     ["जब चंद्रमा सूर्य को ढक देता है", "जब पृथ्वी सूर्य को ढक देती है", "जब सूर्य बुझ जाता है", "जब चंद्रमा पृथ्वी की छाया में आता है"],
     ["When the Moon covers the Sun", "When the Earth covers the Sun", "When the Sun goes out", "When the Moon enters the Earth's shadow"],
     0,
     "चंद्रमा सूर्य को ढक देता है = सूर्य ग्रहण।",
     "The Moon covering the Sun = solar eclipse."),

    ("moon-phases-and-eclipses", "easy",
     "चंद्र ग्रहण में सूर्य, पृथ्वी और चंद्रमा में मध्य कौन होता है?",
     "In a lunar eclipse, who is in the middle among the Sun, Earth and Moon?",
     ["पृथ्वी", "चंद्रमा", "सूर्य", "कोई नहीं"],
     ["The Earth", "The Moon", "The Sun", "None"],
     0,
     "सूर्य → पृथ्वी → चंद्रमा क्रम में पृथ्वी बीच में रहती है।",
     "In the order Sun → Earth → Moon, the Earth stays in between."),

    ("moon-phases-and-eclipses", "easy",
     "सूर्य ग्रहण में मध्य में कौन होता है?",
     "Who lies in the middle during a solar eclipse?",
     ["चंद्रमा", "पृथ्वी", "सूर्य", "शुक्र"],
     ["The Moon", "The Earth", "The Sun", "Venus"],
     0,
     "सूर्य → चंद्रमा → पृथ्वी — चंद्रमा बीच का पिंड।",
     "Sun → Moon → Earth — the Moon is the middle body."),

    ("moon-phases-and-eclipses", "easy",
     "पूर्णमासी की रात चंद्रमा कैसा दिखता है?",
     "How does the Moon look on the night of a full moon?",
     ["पूरा गोल चमकीला चाँद", "बिल्कुल अदृश्य", "आधा चाँद", "एक पतली लकीर"],
     ["A full round bright disc", "Completely invisible", "Half a disc", "A thin crescent"],
     0,
     "पूर्णमासी में चंद्रमा का रोशन भाग पूरा दिखता है।",
     "On a full moon the whole lit face is seen."),

    ("moon-phases-and-eclipses", "easy",
     "अमावस्या की रात चंद्रमा क्यों नहीं दिखता?",
     "Why is the Moon not seen on the new-moon night?",
     ["उस रात चंद्रमा का रोशन भाग पृथ्वी की ओर नहीं होता", "चंद्रमा उस रात गिर जाता है", "चंद्रमा बुझ जाता है", "सूर्य चंद्रमा को खा जाता है"],
     ["That night the Moon's lit side is not toward the Earth", "The Moon falls that night", "The Moon extinguishes", "The Sun swallows the Moon"],
     0,
     "अर्ध-रोशन चंद्रमा का जो भाग धूप में है वह हमसे दूर होता है।",
     "The half of the Moon that is sunlit faces away from us."),

    ("moon-phases-and-eclipses", "easy",
     "सूर्य ग्रहण के समय दिन में क्या दिखता है?",
     "What is seen in the daytime during a solar eclipse?",
     ["चंद्रमा सूर्य को ढक देता है और उसकी चमक घट जाती है", "सूर्य दोगुना बड़ा दिखता है", "रात हो जाती है पूरी", "चाँद लाल हो जाता है"],
     ["The Moon covers the Sun and its brightness falls", "The Sun appears twice as large", "Full night falls", "The Moon turns red"],
     0,
     "चंद्रमा की आड़ से सूर्य का प्रकाश घटता है।",
     "The Moon's blockage cuts the Sun's light."),

    ("moon-phases-and-eclipses", "easy",
     "चंद्रमा पृथ्वी की क्या करता है?",
     "What does the Moon do around the Earth?",
     ["परिक्रमा करता है", "कुछ नहीं करता", "सूर्य की परिक्रमा सीधी करता है", "पृथ्वी का पीछा करता है"],
     ["It revolves around it", "It does nothing", "It orbits the Sun directly", "It chases the Earth"],
     0,
     "उपग्रह होने के नाते चंद्रमा पृथ्वी की परिक्रमा में रहता है।",
     "Being a satellite, the Moon keeps revolving around the Earth."),

    ("moon-phases-and-eclipses", "easy",
     "चंद्र ग्रहण में छाया किसकी होती है?",
     "In a lunar eclipse, whose shadow is it?",
     ["पृथ्वी की", "चंद्रमा की", "सूर्य की", "मंगल की"],
     ["The Earth's", "The Moon's", "The Sun's", "Mars's"],
     0,
     "पृथ्वी की छाया चंद्रमा पर पड़ती है।",
     "The Earth's shadow falls on the Moon."),

    ("moon-phases-and-eclipses", "easy",
     "सूर्य ग्रहण में जो पिंड आड़ बनाता है, वह कौन-सा है?",
     "Which body forms the obstruction in a solar eclipse?",
     ["चंद्रमा", "पृथ्वी", "शुक्र", "बृहस्पति"],
     ["The Moon", "The Earth", "Venus", "Jupiter"],
     0,
     "चंद्रमा ही सूर्य और पृथ्वी के बीच आता है।",
     "The Moon alone comes between the Sun and the Earth."),

    ("moon-phases-and-eclipses", "easy",
     "चंद्रमा का 'रोशन भाग' वास्तव में क्या है?",
     "What really is the Moon's 'lit part'?",
     ["सूर्य के प्रकाश से जगमगाता भाग", "चंद्रमा की आग", "पृथ्वी की रोशनी", "तारों का प्रकाश"],
     ["The part glowing with the Sun's light", "The Moon's fire", "The Earth's glow", "Starlight"],
     0,
     "सूर्य ही चंद्रमा को रोशन करता है।",
     "The Sun alone lights the Moon."),

    ("moon-phases-and-eclipses", "easy",
     "ग्रहण दो प्रकार के होते हैं — कौन-से?",
     "Eclipses are of two kinds — which ones?",
     ["सूर्य ग्रहण और चंद्र ग्रहण", "दिन ग्रहण और रात ग्रहण", "ग्रह ग्रहण और तारा ग्रहण", "भागीय और पूर्ण वर्ष"],
     ["Solar eclipse and lunar eclipse", "Day eclipse and night eclipse", "Planet eclipse and star eclipse", "Partial and full year"],
     0,
     "सूर्य और चंद्र — दोनों के ग्रहण बताए गए हैं।",
     "Eclipses of both the Sun and the Moon are stated."),

    ("moon-phases-and-eclipses", "easy",
     "कलाओँ का बदलना चंद्रमा की किस गति से जुड़ा है?",
     "The changing of phases is linked with which motion of the Moon?",
     ["पृथ्वी की परिक्रमा से", "अपने अक्ष के झूले से", "सूर्य की सीधी परिक्रमा से", "किसी गति से नहीं"],
     ["Its revolution around the Earth", "Its swinging on its axis", "Its direct orbit of the Sun", "No motion at all"],
     0,
     "परिक्रमा से स्थितियाँ बदलती हैं और कलाएँ बदलती हैं।",
     "Revolution changes the arrangements, and the phases change."),

    ("moon-phases-and-eclipses", "easy",
     "सूर्य ग्रहण सदा किस समय होता है?",
     "A solar eclipse always occurs at what time?",
     ["दिन में", "रात में", "सुबह-सुबह", "दोपहर ठीक बारह बजे"],
     ["In the daytime", "At night", "Early morning", "Exactly at noon"],
     0,
     "सूर्य आकाश में होगा तभी तो उसका ग्रहण दिखेगा।",
     "Only with the Sun in the sky can its eclipse be seen."),

    ("moon-phases-and-eclipses", "easy",
     "चंद्र ग्रहण किस समय देखा जा सकता है?",
     "At what time can a lunar eclipse be seen?",
     ["रात में, जब चाँद आकाश में हो", "दोपहर में", "सूर्योदय के क्षण में ही", "कभी नहीं"],
     ["At night, when the Moon is in the sky", "At noon", "Only at the moment of sunrise", "Never"],
     0,
     "चाँद की छाया-दशा रात में ही देखी जा सकती है।",
     "The Moon's shadowed state can be watched only at night."),

    ("moon-phases-and-eclipses", "easy",
     "पृथ्वी की छाया किस दिशा में बनती है?",
     "In which direction does the Earth's shadow form?",
     ["सूर्य के ठीक विपरीत ओर", "सूर्य की ओर", "उत्तर की ओर", "चंद्रमा की ओर सदा"],
     ["Exactly opposite to the Sun", "Toward the Sun", "Toward the north", "Always toward the Moon"],
     0,
     "प्रकाश के स्रोत के पीछे छाया बनती है — नियम सदा लागू।",
     "A shadow forms behind the light source — the rule always applies."),

    ("moon-phases-and-eclipses", "easy",
     "अमावस्या और पूर्णमासी में से किस दिन चाँद सबसे अधिक चमकीला दिखता है?",
     "Between new-moon and full-moon days, on which day does the Moon look brightest?",
     ["पूर्णमासी", "अमावस्या", "दोनों पर समान", "किसी पर नहीं"],
     ["Full moon", "New moon", "Equal on both", "On neither"],
     0,
     "पूर्णमासी को पूरा रोशन चेहरा दिखता है।",
     "On a full moon the whole bright face is visible."),

    # ---- medium (21) ----
    ("moon-phases-and-eclipses", "medium",
     "चंद्र ग्रहण की स्थिति में चंद्रमा की कला कैसी होती है?",
     "What is the Moon's phase in the arrangement of a lunar eclipse?",
     ["पूर्णमासी जैसी — सूर्य और चंद्रमा पृथ्वी के दो विपरीत ओर", "अमावस्या जैसी", "आधी कला", "कोई कला नहीं"],
     ["Like a full moon — the Sun and the Moon on opposite sides of the Earth", "Like a new moon", "Half phase", "No phase"],
     0,
     "पृथ्वी बीच में हो तो चाँद पूरा रोशन दिखता है और छाया में आ सकता है।",
     "With the Earth in between, the Moon looks full and can enter the shadow."),

    ("moon-phases-and-eclipses", "medium",
     "सूर्य ग्रहण की स्थिति में चंद्रमा की कला कैसी होती है?",
     "What is the Moon's phase in the arrangement of a solar eclipse?",
     ["अमावस्या जैसी — चंद्रमा सूर्य और पृथ्वी के बीच", "पूर्णमासी जैसी", "आधी कला", "पूर्ण गोला"],
     ["Like a new moon — the Moon between the Sun and the Earth", "Like a full moon", "Half phase", "A full disc"],
     0,
     "बीच वाला चंद्रमा हमें अपना अंधेरा भाग दिखाता है।",
     "A Moon in the middle shows us its dark side."),

    ("moon-phases-and-eclipses", "medium",
     "कलाएँ बदलने का परीक्षण: यदि चंद्रमा स्वयं प्रकाशमान होता, तो अमावस्या संभव होती?",
     "Testing phases: if the Moon were self-luminous, would a new moon be possible?",
     ["नहीं — स्व-प्रकाशमान चंद्रमा हर रात एक जैसा जगता; अंधेरी अमावस्या परावर्तन का प्रमाण है", "हाँ, वैसे ही होती", "अमावस्या और भी रोशन होती", "चंद्रमा अदृश्य ही नहीं होता"],
     ["No — a self-luminous Moon would glow identically every night; the dark new moon proves reflection", "Yes, just the same", "The new moon would be even brighter", "The Moon would never be invisible"],
     0,
     "अमावस्या की अंधेरी रात ही बताती है कि चाँद उधार की रोशनी दिखाता है।",
     "The dark night of the new moon itself shows the Moon shows borrowed light."),

    ("moon-phases-and-eclipses", "medium",
     "चंद्र ग्रहण और सूर्य ग्रहण में पृथ्वी की भूमिका क्रमशः क्या है?",
     "What is the Earth's role in a lunar eclipse and in a solar eclipse respectively?",
     ["छाया डालने वाला; देखने वाला (चंद्रमा आड़ बनाता है)", "आड़ बनाने वाला; छाया डालने वाला", "दोनों में आड़", "दोनों में केवल दर्शक"],
     ["Shadow-caster; viewer (the Moon obstructs)", "Obstructor; shadow-caster", "Obstructor in both", "Only a spectator in both"],
     0,
     "चंद्र-ग्रहण की छाया पृथ्वी की, सूर्य-ग्रहण की आड़ चंद्रमा की।",
     "The lunar eclipse's shadow is the Earth's; the solar eclipse's block is the Moon's."),

    ("moon-phases-and-eclipses", "medium",
     "सही क्रम-स्थिति का मिलान कीजिए — (i) चंद्र ग्रहण (ii) सूर्य ग्रहण:",
     "Match the correct arrangements — (i) lunar eclipse (ii) solar eclipse:",
     ["(i) सूर्य-पृथ्वी-चंद्रमा, (ii) सूर्य-चंद्रमा-पृथ्वी", "(i) सूर्य-चंद्रमा-पृथ्वी, (ii) सूर्य-पृथ्वी-चंद्रमा", "दोनों में सूर्य-पृथ्वी-चंद्रमा", "दोनों में सूर्य-चंद्रमा-पृथ्वी"],
     ["(i) Sun-Earth-Moon, (ii) Sun-Moon-Earth", "(i) Sun-Moon-Earth, (ii) Sun-Earth-Moon", "Sun-Earth-Moon in both", "Sun-Moon-Earth in both"],
     0,
     "बीच का पिंड ही ग्रहण की पहचान है।",
     "The middle body is the very identity of the eclipse."),

    ("moon-phases-and-eclipses", "medium",
     "पूर्णमासी की रात चाँद पूरा गोल दिखता है। उस रात सूर्य और चाँद आपस में कैसे स्थित होते हैं?",
     "On a full-moon night the Moon looks a full disc. How are the Sun and the Moon placed relative to each other that night?",
     ["पृथ्वी के दो विपरीत ओर — धरती बीच में", "एक ही ओर आमने-सामने", "चाँद सूर्य के ठीक पीछे", "दोनों जमीन पर"],
     ["On opposite sides of the Earth — the Earth in between", "On the same side face to face", "The Moon just behind the Sun", "Both on the ground"],
     0,
     "सामने से पूरा रोशन चेहरा तभी दिखता है जब सूर्य पीछे हो।",
     "The full bright face shows only when the Sun is behind us."),

    ("moon-phases-and-eclipses", "medium",
     "अमावस्या की स्थिति में सूर्य, चंद्रमा और पृथ्वी का क्रम क्या होता है?",
     "What is the order of the Sun, Moon and Earth in the new-moon arrangement?",
     ["सूर्य-चंद्रमा-पृथ्वी (चंद्रमा बीच में)", "सूर्य-पृथ्वी-चंद्रमा", "पृथ्वी-सूर्य-चंद्रमा", "कोई निश्चित क्रम नहीं"],
     ["Sun-Moon-Earth (the Moon in between)", "Sun-Earth-Moon", "Earth-Sun-Moon", "No fixed order"],
     0,
     "चाँद बीच में और उसका रोशन भाग हमसे परे।",
     "The Moon in the middle, its lit side beyond us."),

    ("moon-phases-and-eclipses", "medium",
     "चंद्रमा की कलाएँ बदलती हैं पर पृथ्वी की छाया का इससे रोज़ कोई लेना-देना नहीं। यह कथन कैसे सही है?",
     "The Moon's phases change, but the Earth's shadow has nothing to do with them daily. How is this statement right?",
     ["कलाएँ दृश्य कोण और स्थिति से बदलती हैं; छाया तो केवल ग्रहण के समय चंद्रमा तक पहुँचती है", "छाया रोज़ चाँद को ढकती है", "कलाएँ छाया से ही बनती हैं", "कथन गलत है"],
     ["Phases change with viewing angle and arrangement; the shadow reaches the Moon only during an eclipse", "The shadow covers the Moon daily", "Phases are made by the shadow", "The statement is wrong"],
     0,
     "ग्रहण विशेष घटना है, कला-चक्र सामान्य नियम — दोनों अलग।",
     "An eclipse is a special event; the phase cycle is the normal rule — two different things."),

    ("moon-phases-and-eclipses", "medium",
     "दो कथन: (i) चंद्र ग्रहण पृथ्वी की छाया से होता है। (ii) सूर्य ग्रहण चंद्रमा द्वारा सूर्य के ढके जाने से। सही विकल्प:",
     "Two statements: (i) A lunar eclipse happens by the Earth's shadow. (ii) A solar eclipse by the Moon covering the Sun. The correct option:",
     ["दोनों सही", "केवल (i)", "केवल (ii)", "दोनों गलत"],
     ["Both correct", "Only (i)", "Only (ii)", "Both wrong"],
     0,
     "यही दो परिभाषाएँ नोट्स में दी गई हैं।",
     "These are exactly the two definitions given in the notes."),

    ("moon-phases-and-eclipses", "medium",
     "चंद्रमा को 'पृथ्वी का उपग्रह' कहने का आधार क्या है?",
     "What is the basis for calling the Moon 'the Earth's satellite'?",
     ["वह पृथ्वी की परिक्रमा करता है", "वह पृथ्वी से बड़ा है", "वह सूर्य की परिक्रमा करता है", "वह चमकीला है"],
     ["It revolves around the Earth", "It is bigger than the Earth", "It revolves around the Sun", "It is bright"],
     0,
     "परिक्रमा ही उपग्रहता की परिभाषा है।",
     "Revolution around a body is the very definition of a satellite."),

    ("moon-phases-and-eclipses", "medium",
     "चंद्र ग्रहण के समय चंद्रमा अपनी सामान्य चमक क्यों खो देता है?",
     "Why does the Moon lose its usual brightness during a lunar eclipse?",
     ["पृथ्वी की छाया उस पर पड़ती है और सूर्य-प्रकाश उस तक नहीं पहुँचता", "चंद्रमा बुझ जाता है", "सूर्य ठंडा हो जाता है", "चंद्रमा पीछे हट जाता है"],
     ["The Earth's shadow falls on it and sunlight no longer reaches it", "The Moon extinguishes", "The Sun cools down", "The Moon retreats"],
     0,
     "छाया = प्रकाश का रुकना = चमक का मंद पड़ना।",
     "Shadow = light cut off = dimming."),

    ("moon-phases-and-eclipses", "medium",
     "सूर्य ग्रहण और चंद्र ग्रहण में से कौन-सा केवल दिन में ही संभव है?",
     "Which of the two — solar or lunar eclipse — is possible only in the daytime?",
     ["सूर्य ग्रहण", "चंद्र ग्रहण", "दोनों", "कोई नहीं"],
     ["Solar eclipse", "Lunar eclipse", "Both", "Neither"],
     0,
     "सूर्य दिन में ही दिखता है, इसलिए उसका ग्रहण भी दिन में।",
     "The Sun is seen only by day, so its eclipse too comes by day."),

    ("moon-phases-and-eclipses", "medium",
     "पूर्णमासी से अमावस्या तक के दौरान चाँद का दिखने वाला रोशन भाग कैसा बदलता है?",
     "From full moon to new moon, how does the visible lit portion of the Moon change?",
     ["घटता-घटता लगभग शून्य हो जाता है", "बढ़ता-बढ़ता पूरा", "स्थिर रहता है", "उलट-पुलट होता रहता है"],
     ["It keeps shrinking to nearly none", "It keeps growing to full", "It stays constant", "It flips back and forth"],
     0,
     "कला-चक्र में रोशन भाग घटता और बढ़ता दोनों दिखता है।",
     "In the phase cycle the lit part both wanes and waxes."),

    ("moon-phases-and-eclipses", "medium",
     "रात-दर-रात चाँद का दिखने वाला रोशन भाग बढ़ता दिखा। चाँद किस ओर बदल रहा था?",
     "Night after night the Moon's visible lit portion appeared to grow. Toward what was the Moon changing?",
     ["अमावस्या से पूर्णमासी की ओर (बढ़ता चाँद)", "पूर्णमासी से अमावस्या की ओर (घटता चाँद)", "किसी ओर नहीं — स्थिर रहा", "पहले घटा, फिर बढ़ा"],
     ["Toward full moon from new moon (a waxing Moon)", "Toward new moon from full moon (a waning Moon)", "Toward none — it stayed fixed", "It first shrank, then grew"],
     0,
     "रोशन भाग का बढ़ना ही बढ़ते चाँद की पहचान है।",
     "A growing lit portion is the very mark of a waxing Moon."),

    ("moon-phases-and-eclipses", "medium",
     "किसी रात चाँद का केवल आधा रोशन भाग दिखा। यह कौन-सी स्थिति है?",
     "One night exactly half of the Moon's disc appeared lit. What condition is this?",
     ["अर्ध-कला — देखने की स्थिति का परिणाम", "ग्रहण की स्थिति", "चंद्रमा का टूटना", "बादलों का खेल"],
     ["A half phase — the result of the viewing arrangement", "An eclipse condition", "The Moon breaking", "A play of clouds"],
     0,
     "स्थितियों के बीच की कलाएँ आधे-अधूरे रोशन चेहरे दिखाती हैं।",
     "Midway arrangements show half-lit faces."),

    ("moon-phases-and-eclipses", "medium",
     "ग्रहण और कला — दोनों में साझा आधार क्या है?",
     "What is common between eclipses and phases as their shared basis?",
     ["सूर्य-पृथ्वी-चंद्रमा की स्थितियाँ", "बादलों की गति", "तारों की चमक", "पृथ्वी का घूर्णन"],
     ["The arrangements of the Sun, Earth and Moon", "The motion of clouds", "The twinkle of stars", "The Earth's rotation"],
     0,
     "स्थिति-विज्ञान ही दोनों घटनाओं की जड़ है।",
     "The science of arrangements is the root of both phenomena."),

    ("moon-phases-and-eclipses", "medium",
     "एक बच्चा सोचता है कि अमावस्या की रात चाँद 'बुझ गया' है। उसकी भूल क्या है?",
     "A child thinks the Moon has 'gone out' on a new-moon night. What is his error?",
     ["चाँद बुझा नहीं — उसका रोशन भाग उस समय पृथ्वी की ओर नहीं है", "चाँद सच में बुझता है", "चाँद उस रात गिरता है", "चाँद छोटा हो जाता है"],
     ["The Moon has not gone out — its lit side simply does not face the Earth then", "The Moon really extinguishes", "The Moon falls that night", "The Moon shrinks"],
     0,
     "बुझना और न दिखना — दो अलग बातें।",
     "Going out and not being seen are two different things."),

    ("moon-phases-and-eclipses", "medium",
     "चंद्र ग्रहण के समय सूर्य और चंद्रमा आपस में कैसे होते हैं?",
     "During a lunar eclipse, how are the Sun and the Moon placed with respect to each other?",
     ["पृथ्वी के विपरीत ओर — लगभग एक सीध में", "एक ही ओर", "चंद्रमा सूर्य के पीछे छिपा", "दोनों अदृश्य"],
     ["On opposite sides of the Earth — nearly in one line", "On the same side", "The Moon hidden behind the Sun", "Both invisible"],
     0,
     "पृथ्वी-बीच की सीध ही छाया की शर्त है।",
     "The Earth-middle alignment is the very condition for the shadow."),

    ("moon-phases-and-eclipses", "medium",
     "कला-चक्र में 'एक जैसी दिखने वाली रातें' बार-बार आती हैं। इसका कारण क्या है?",
     "In the phase cycle, 'similar-looking nights' keep recurring. What is the reason?",
     ["चंद्रमा की परिक्रमा लगातार चलती रहती है, इसलिए स्थितियाँ दोहराती हैं", "बादल वैसे ही आते हैं", "पृथ्वी रुक-रुककर चलती है", "सूर्य बदल जाता है"],
     ["The Moon's revolution continues steadily, so the arrangements repeat", "Clouds come the same way", "The Earth moves in stops", "The Sun changes"],
     0,
     "आवर्ती गति = आवर्ती स्थितियाँ = आवर्ती कलाएँ।",
     "Recurring motion = recurring arrangements = recurring phases."),

    ("moon-phases-and-eclipses", "medium",
     "सूर्य ग्रहण में पृथ्वी पर बैठे दर्शक के लिए चंद्रमा कहाँ होता है?",
     "For a viewer seated on the Earth during a solar eclipse, where is the Moon?",
     ["दर्शक और सूर्य के ठीक बीच", "सूर्य के पीछे", "दर्शक के पीछे", "क्षितिज के नीचे कहीं दूर"],
     ["Exactly between the viewer and the Sun", "Behind the Sun", "Behind the viewer", "Far below the horizon"],
     0,
     "आड़ की यही स्थिति सूर्य को ढकती है।",
     "This in-between position is what covers the Sun."),

    ("moon-phases-and-eclipses", "medium",
     "'कलाएँ बदलने के लिए चंद्रमा की परिक्रमा जिम्मेदार है, पृथ्वी का घूर्णन नहीं' — इस कथन का मूल्यांकन कीजिए:",
     "'The Moon's revolution, not the Earth's rotation, is responsible for the changing phases' — evaluate this statement:",
     ["सही है — कलाएँ स्थिति-बदलाव से आती हैं और स्थितियाँ चंद्रमा की परिक्रमा से बदलती हैं", "गलत है — पृथ्वी के घूर्णन से कलाएँ बदलती हैं", "गलत है — सूर्य के ठंडा होने से कलाएँ बदलती हैं", "आंशिक सही — दोनों बराबर जिम्मेदार हैं"],
     ["Correct — phases come from changing arrangements, and the arrangements change with the Moon's revolution", "Wrong — phases change due to the Earth's rotation", "Wrong — phases change because the Sun cools", "Partly right — both are equally responsible"],
     0,
     "घूर्णन दिन-रात का कारण है; कलाओँ का कारण परिक्रमा है।",
     "Rotation causes day-night; revolution causes the phases."),

    # ---- hard (9) ----
    ("moon-phases-and-eclipses", "hard",
     "तीन कथन: (i) चंद्रमा परावर्तक है। (ii) कलाएँ स्थिति से बदलती हैं। (iii) चंद्र ग्रहण चंद्रमा की छाया से होता है। गलत कथन:",
     "Three statements: (i) The Moon is a reflector. (ii) Phases change with arrangement. (iii) A lunar eclipse is caused by the Moon's shadow. The wrong statement:",
     ["कथन (iii) — चंद्र ग्रहण पृथ्वी की छाया से होता है", "कथन (i)", "कथन (ii)", "तीनों सही"],
     ["Statement (iii) — a lunar eclipse is caused by the Earth's shadow", "Statement (i)", "Statement (ii)", "All three correct"],
     0,
     "छाया का मालिक बताओ — ग्रहण की पहचान बन जाएगी।",
     "Name the shadow's owner — the eclipse identifies itself."),

    ("moon-phases-and-eclipses", "hard",
     "सोच-परीक्षण: यदि पृथ्वी कोई छाया ही नहीं बनाती (काल्पनिक पारदर्शी पृथ्वी), तो कौन-सा ग्रहण समाप्त हो जाएगा?",
     "Thought experiment: if the Earth cast no shadow at all (an imaginary transparent Earth), which eclipse would end?",
     ["चंद्र ग्रहण — वह पृथ्वी की छाया पर टिका है", "सूर्य ग्रहण", "दोनों", "कोई नहीं"],
     ["The lunar eclipse — it depends on the Earth's shadow", "The solar eclipse", "Both", "Neither"],
     0,
     "चंद्र-ग्रहण की जड़ पृथ्वी की अपारदर्शिता है।",
     "The lunar eclipse is rooted in the Earth's opacity."),

    ("moon-phases-and-eclipses", "hard",
     "सूर्य ग्रहण चंद्रमा की आड़ से है। यदि चंद्रमा पृथ्वी की परिक्रमा न करता, तो सूर्य ग्रहण?",
     "A solar eclipse is the Moon's blockage. If the Moon did not revolve around the Earth, solar eclipses would —",
     ["संभव नहीं होते — आड़ बनाने वाला ही नहीं", "और अधिक होते", "वैसे ही रहते", "केवल रात में होते"],
     ["Not be possible — there would be no obstructor", "Occur even more often", "Continue as before", "Occur only at night"],
     0,
     "बिना चंद्रमा के बीच आने के, ढकने का प्रश्न ही नहीं।",
     "Without the Moon coming in between, the question of covering does not arise."),

    ("moon-phases-and-eclipses", "hard",
     "चंद्र ग्रहण की रात सभी ओर से चाँद एक जैसा मंद दिखता है, पर कलाएँ रोज़ बदलती हैं। दोनों में गुणात्मक अंतर क्या है?",
     "On a lunar-eclipse night the Moon looks uniformly dim from everywhere, yet phases change daily. What is the qualitative difference between the two?",
     ["ग्रहण छाया की एक विशेष घटना है; कलाएँ स्थिति-जनित सामान्य चक्र", "दोनों एक ही घटना के नाम हैं", "कलाएँ विशेष, ग्रहण सामान्य", "अंतर केवल देखने वाले पर निर्भर"],
     ["An eclipse is a special shadow event; phases are the normal arrangement-driven cycle", "Both are names of one event", "Phases special, eclipse normal", "The difference depends only on the viewer"],
     0,
     "एक असामान्य सीध, दूसरा नित्य खेल।",
     "One is an unusual alignment; the other, an everyday play."),

    ("moon-phases-and-eclipses", "hard",
     "पूर्णमासी की रात हर बार चंद्र ग्रहण क्यों नहीं होता? शालेय स्तर पर सही स्पष्टीकरण चुनिए:",
     "Why is there no lunar eclipse on every full-moon night? Choose the correct school-level explanation:",
     ["ग्रहण के लिए सूर्य-पृथ्वी-चंद्रमा का लगभग पूर्ण सीध में होना जरूरी है; हर पूर्णमासी उस सटीक सीध में नहीं होती", "चंद्रमा हर पूर्णमासी को सो जाता है", "पृथ्वी की छाया हर रात गायब रहती है", "सूर्य हर पूर्णमासी को बदल जाता है"],
     ["An eclipse needs the Sun-Earth-Moon nearly in one exact line; not every full moon reaches that precise alignment", "The Moon sleeps every full moon", "The Earth's shadow vanishes every night", "The Sun changes every full moon"],
     0,
     "पूर्णमासी सामान्य स्थिति है, सटीक सीध विशेष — यही ग्रहण की शर्त।",
     "A full moon is common; the exact line is special — that is the eclipse condition."),

    ("moon-phases-and-eclipses", "hard",
     "क्रम-पहेली: जिस ग्रहण में 'आड़ बनाने वाला पिंड' और 'छाया पाने वाला पिंड' अलग-अलग हैं, वह कौन-सा है?",
     "Order puzzle: in which eclipse are the 'obstructing body' and the 'shadowed body' different?",
     ["सूर्य ग्रहण — चंद्रमा आड़ देता है, पृथ्वी पर छाया-प्रभाव पड़ता है", "चंद्र ग्रहण — दोनों एक ही पिंड", "दोनों में एक जैसा", "कोई नहीं"],
     ["Solar eclipse — the Moon obstructs, the effect falls on the Earth", "Lunar eclipse — both are the same body", "Identical in both", "Neither"],
     0,
     "सूर्य-ग्रहण में ढकने वाला और प्रभाव पाने वाला अलग हैं।",
     "In a solar eclipse the coverer and the affected are different."),

    ("moon-phases-and-eclipses", "hard",
     "दो कथन: (i) सूर्य ग्रहण की स्थिति और अमावस्या की स्थिति में चंद्रमा का स्थान समान है। (ii) चंद्र ग्रहण की स्थिति और पूर्णमासी की स्थिति में पृथ्वी का स्थान समान है। सही विकल्प:",
     "Two statements: (i) In a solar eclipse and in a new moon, the Moon's position is alike. (ii) In a lunar eclipse and in a full moon, the Earth's position is alike. The correct option:",
     ["दोनों सही — अंतर केवल सटीक सीध में होने-न होने में", "केवल (i) सही", "केवल (ii) सही", "दोनों गलत"],
     ["Both correct — the difference lies only in the exactness of the alignment", "Only (i)", "Only (ii)", "Both wrong"],
     0,
     "स्थितियाँ मिलती हैं, ग्रहण तब जब सीध त्रुटिहीन हो।",
     "The arrangements match; an eclipse occurs only when the line is perfect."),

    ("moon-phases-and-eclipses", "hard",
     "एक विद्यार्थी कहता है — 'चंद्र ग्रहण में चाँद और सूर्य ग्रहण में चाँद, दोनों में एक ही चीज़ होती है — चाँद छाया में चला जाता है।' उसकी गलती पकड़िए:",
     "A student says — 'In a lunar and a solar eclipse the same thing happens — the Moon goes into a shadow.' Spot his error:",
     ["सूर्य ग्रहण में चाँद छाया में नहीं जाता — वह स्वयं आड़ बनता है; छाया पृथ्वी पर प्रभाव डालती है", "उसका कथन पूर्णतः सही है", "दोनों में सूर्य छाया में जाता है", "दोनों में पृथ्वी आड़ बनाती है"],
     ["In a solar eclipse the Moon does not enter a shadow — it itself becomes the obstruction; its shadow's effect falls on the Earth", "His statement is fully correct", "In both, the Sun goes into shadow", "In both, the Earth obstructs"],
     0,
     "एक बार चाँद छाया खाता है, दूसरी बार छाया बनाता है।",
     "Once the Moon eats a shadow; the other time it makes one."),

    ("moon-phases-and-eclipses", "hard",
     "ग्रहण-काल में 'सूर्य-पृथ्वी-चंद्रमा' तीनों की सापेक्ष स्थिति क्या कहलाती है?",
     "During an eclipse, what is the relative placement of the Sun-Earth-Moon called?",
     ["लगभग एक सीध में होना (संरेखण)", "त्रिभुज बनाना", "वृत्त में घिरना", "बिखर जाना"],
     ["Lying nearly in one straight line (alignment)", "Forming a triangle", "Enclosed in a circle", "Scattered apart"],
     0,
     "सीध में संरेखण ही छाया-पतन की शर्त है।",
     "Straight-line alignment is the condition for the shadow to strike."),

    # ================= INDIAN SPACE MISSIONS (50) =================
    # ---- easy (20) ----
    ("indian-space-missions", "easy",
     "भारत का पहला कृत्रिम उपग्रह कौन-सा था?",
     "Which was India's first artificial satellite?",
     ["आर्यभट्ट", "चंद्रयान", "मंगलयान", "INSAT"],
     ["Aryabhata", "Chandrayaan", "Mangalyaan", "INSAT"],
     0,
     "आर्यभट्ट प्रथम भारतीय उपग्रह था।",
     "Aryabhata was the first Indian satellite."),

    ("indian-space-missions", "easy",
     "चंद्रयान अभियान किससे संबंधित है?",
     "The Chandrayaan mission is related to what?",
     ["चंद्रमा", "मंगल", "सूर्य", "शुक्र"],
     ["The Moon", "Mars", "The Sun", "Venus"],
     0,
     "चंद्रयान का लक्ष्य चंद्रमा है।",
     "Chandrayaan's target is the Moon."),

    ("indian-space-missions", "easy",
     "मंगलयान अभियान किस ग्रह के लिए है?",
     "The Mangalyaan mission is for which planet?",
     ["मंगल", "बृहस्पति", "शनि", "बुध"],
     ["Mars", "Jupiter", "Saturn", "Mercury"],
     0,
     "मंगलयान मंगल ग्रह के अभियान का नाम है।",
     "Mangalyaan is the name of the Mars mission."),

    ("indian-space-missions", "easy",
     "भारतीय अंतरिक्ष अभियानों को कौन-सी संस्था चलाती है?",
     "Which organisation runs India's space missions?",
     ["ISRO", "NASA", "WHO", "UNESCO"],
     ["ISRO", "NASA", "WHO", "UNESCO"],
     0,
     "ISRO भारतीय अंतरिक्ष अभियानों का संचालक है।",
     "ISRO runs India's space missions."),

    ("indian-space-missions", "easy",
     "कृत्रिम उपग्रह किसे कहते हैं?",
     "What is an artificial satellite?",
     ["मनुष्य द्वारा बनाकर छोड़ा गया उपग्रह", "प्रकृति में स्वतः बना उपग्रह", "हर तारा", "चंद्रमा"],
     ["A satellite made and launched by humans", "A satellite formed by nature itself", "Every star", "The Moon"],
     0,
     "कृत्रिम = मानवनिर्मित; प्राकृतिक उपग्रह चंद्रमा है।",
     "Artificial = man-made; the natural satellite is the Moon."),

    ("indian-space-missions", "easy",
     "चंद्रमा किस प्रकार का उपग्रह है?",
     "What kind of satellite is the Moon?",
     ["प्राकृतिक", "कृत्रिम", "दोनों", "कोई नहीं"],
     ["Natural", "Artificial", "Both", "Neither"],
     0,
     "चंद्रमा प्रकृति का बनाया प्राकृतिक उपग्रह है।",
     "The Moon is a natural satellite made by nature."),

    ("indian-space-missions", "easy",
     "कृत्रिम उपग्रह मुख्यतः किसकी परिक्रमा करते हैं?",
     "Artificial satellites mainly revolve around what?",
     ["पृथ्वी", "सूर्य", "चंद्रमा", "ध्रुवतारा"],
     ["The Earth", "The Sun", "The Moon", "The Pole Star"],
     0,
     "अधिकांश कृत्रिम उपग्रह पृथ्वी की परिक्रमा में रहते हैं।",
     "Most artificial satellites stay in orbit around the Earth."),

    ("indian-space-missions", "easy",
     "मौसम की भविष्यवाणी में कौन सहायक होता है?",
     "What assists in weather forecasting?",
     ["मौसम उपग्रह", "साइकिल", "पंखा", "रेडियो का एंटीना"],
     ["Weather satellites", "A bicycle", "A fan", "A radio antenna"],
     0,
     "मौसम-उपग्रह बादलों और तूफानों की सूचना देते हैं।",
     "Weather satellites report clouds and storms."),

    ("indian-space-missions", "easy",
     "दूर बैठे लोगों से बात करने और संदेश भेजने में कृत्रिम उपग्रह किस रूप में काम आते हैं?",
     "How do artificial satellites help in talking to and messaging distant people?",
     ["संचार (कम्युनिकेशन) के माध्यम के रूप में", "ईंधन के रूप में", "भोजन के रूप में", "पानी के रूप में"],
     ["As a medium of communication", "As fuel", "As food", "As water"],
     0,
     "संचार-उपग्रह संदेशों को दूर तक पहुँचाते हैं।",
     "Communication satellites carry messages afar."),

    ("indian-space-missions", "easy",
     "टेलीविज़न के कार्यक्रम देशभर में पहुँचने में सहायक तकनीक कौन-सी है?",
     "Which technology helps TV programmes reach across the country?",
     ["प्रसारण (ब्रॉडकास्टिंग) में सहायक उपग्रह", "डाक कबूतर", "ट्रक", "मोर्चा"],
     ["Satellites assisting broadcasting", "Carrier pigeons", "Trucks", "Scaffolding"],
     0,
     "दूरसंचार-प्रसारण के लिए उपग्रह काम आते हैं।",
     "Satellites serve telecommunication and broadcasting."),

    ("indian-space-missions", "easy",
     "'चंद्रयान' नाम में 'चंद्र' किसे दर्शाता है?",
     "What does 'Chandra' in 'Chandrayaan' indicate?",
     ["चंद्रमा — अभियान का लक्ष्य", "सूर्य", "पृथ्वी", "तारा"],
     ["The Moon — the mission's target", "The Sun", "The Earth", "A star"],
     0,
     "नाम ही लक्ष्य बताता है — चंद्र + यान।",
     "The name itself reveals the target — Chandra + yaan."),

    ("indian-space-missions", "easy",
     "'मंगलयान' नाम से ही अभियान का लक्ष्य पहचानिए:",
     "Identify the mission's target from the name 'Mangalyaan' itself:",
     ["मंगल ग्रह", "चंद्रमा", "शुक्र", "शनि"],
     ["Mars", "The Moon", "Venus", "Saturn"],
     0,
     "मंगल + यान = मंगल की यात्रा।",
     "Mangal + yaan = journey to Mars."),

    ("indian-space-missions", "easy",
     "उपग्रहों के उपयोग के तीन क्षेत्र कौन-से हैं?",
     "Which are the three fields of satellite use?",
     ["संचार, मौसम, दूरसंचार-प्रसारण", "खेल, नींद, भोजन", "नृत्य, संगीत, चित्रकला", "कृषि, मछली, शिकार"],
     ["Communication, weather, telecommunication-broadcasting", "Sports, sleep, food", "Dance, music, painting", "Farming, fishing, hunting"],
     0,
     "नोट्स में यही तीन उपयोग गिनाए गए हैं।",
     "These three uses are listed in the notes."),

    ("indian-space-missions", "easy",
     "ISRO किस देश का अंतरिक्ष कार्यक्रम चलाता है?",
     "Which country's space programme does ISRO run?",
     ["भारत", "अमेरिका", "रूस", "जापान"],
     ["India", "America", "Russia", "Japan"],
     0,
     "ISRO भारतीय अंतरिक्ष कार्यक्रम से जुड़ा है।",
     "ISRO is tied to India's space programme."),

    ("indian-space-missions", "easy",
     "चंद्रयान और मंगलयान में से कौन-सा ग्रह की ओर गया?",
     "Between Chandrayaan and Mangalyaan, which one went toward a planet?",
     ["मंगलयान — मंगल ग्रह की ओर", "चंद्रयान — मंगल की ओर", "दोनों चंद्रमा की ओर", "कोई नहीं"],
     ["Mangalyaan — toward Mars", "Chandrayaan — toward Mars", "Both toward the Moon", "Neither"],
     0,
     "चंद्रमा उपग्रह है, ग्रह नहीं — मंगलयान ग्रह-अभियान है।",
     "The Moon is a satellite, not a planet — Mangalyaan is the planet mission."),

    ("indian-space-missions", "easy",
     "आर्यभट्ट का उल्लेख इतिहास में किस रूप में आता है?",
     "In what capacity does Aryabhata appear in history?",
     ["प्रथम भारतीय कृत्रिम उपग्रह", "प्रथम भारतीय रेल", "प्रथम भारतीय हवाई जहाज़", "प्रथम भारतीय जहाज़"],
     ["The first Indian artificial satellite", "India's first railway", "India's first aeroplane", "India's first ship"],
     0,
     "आर्यभट्ट नाम प्रथम उपग्रह के रूप में दर्ज है।",
     "The name Aryabhata is recorded as the first satellite."),

    ("indian-space-missions", "easy",
     "कृत्रिम उपग्रह कहाँ स्थित रहकर काम करते हैं?",
     "From where do artificial satellites work?",
     ["पृथ्वी की कक्षा (ऑर्बिट) में रहकर", "पानी के नीचे", "ज़मीन के भीतर", "चंद्रमा पर खड़े होकर"],
     ["Staying in the Earth's orbit", "Under water", "Inside the ground", "Standing on the Moon"],
     0,
     "कक्षा में घूमते हुए वे अपने काम करते हैं।",
     "Circling in orbit, they do their jobs."),

    ("indian-space-missions", "easy",
     "तूफान या चक्रवात के पूर्व सूचना देने में कौन महत्वपूर्ण भूमिका निभाता है?",
     "Who plays a key role in giving advance warning of storms or cyclones?",
     ["मौसम उपग्रह", "सड़क के लैंप", "बस स्टॉप", "पेड़"],
     ["Weather satellites", "Street lamps", "Bus stops", "Trees"],
     0,
     "मौसम-उपग्रह आगाही देकर जान-माल बचाते हैं।",
     "Weather satellites save lives and property with alerts."),

    ("indian-space-missions", "easy",
     "निम्न में से कौन-सा भारतीय अंतरिक्ष अभियानों का नाम नहीं है?",
     "Which of these is NOT a name of India's space missions?",
     ["NASA", "चंद्रयान", "मंगलयान", "आर्यभट्ट (उपग्रह)"],
     ["NASA", "Chandrayaan", "Mangalyaan", "Aryabhata (satellite)"],
     0,
     "NASA किसी और देश की संस्था है, भारतीय अभियान नहीं।",
     "NASA is another country's agency, not an Indian mission."),

    ("indian-space-missions", "easy",
     "देश के एक कोने से दूसरे कोने तक सीधा प्रसारण संभव किससे हुआ?",
     "What made direct broadcasting from one corner of the country to another possible?",
     ["प्रसारण-सहायक कृत्रिम उपग्रहों से", "माइक से", "भोंपू से", "डाक-तार से"],
     ["Through broadcasting-assisted artificial satellites", "Through a microphone", "Through a megaphone", "Through the telegraph"],
     0,
     "उपग्रहों ने दूरसंचार-प्रसारण की सीमा बदल दी।",
     "Satellites changed the reach of telecommunication and broadcasting."),

    # ---- medium (22) ----
    ("indian-space-missions", "medium",
     "प्राकृतिक और कृत्रिम उपग्रह में मूल अंतर स्पष्ट कीजिए:",
     "Clarify the basic difference between a natural and an artificial satellite:",
     ["प्राकृतिक प्रकृति का बना (जैसे चंद्रमा), कृत्रिम मनुष्य का बनाया", "दोनों मनुष्य के बनाए हैं", "दोनों प्रकृति के बनाए हैं", "कृत्रिम उपग्रह पृथ्वी की परिक्रमा नहीं करते"],
     ["A natural one is made by nature (like the Moon); an artificial one is man-made", "Both are man-made", "Both are made by nature", "Artificial satellites do not orbit the Earth"],
     0,
     "बनाने वाला कौन — यही विभाजन रेखा है।",
     "Who made it — that is the dividing line."),

    ("indian-space-missions", "medium",
     "चंद्रयान और मंगलयान के लक्ष्यों का सही मिलान कीजिए:",
     "Match correctly the targets of Chandrayaan and Mangalyaan:",
     ["चंद्रयान — चंद्रमा; मंगलयान — मंगल", "चंद्रयान — मंगल; मंगलयान — चंद्रमा", "दोनों — चंद्रमा", "दोनों — मंगल"],
     ["Chandrayaan — the Moon; Mangalyaan — Mars", "Chandrayaan — Mars; Mangalyaan — the Moon", "Both — the Moon", "Both — Mars"],
     0,
     "नाम और लक्ष्य की जोड़ी याद रखें।",
     "Remember the name-target pairing."),

    ("indian-space-missions", "medium",
     "मौसम उपग्रह किस प्रकार की सूचनाएँ देते हैं?",
     "What kind of information do weather satellites provide?",
     ["बादल, तूफान और मौसम की स्थितियाँ", "शेयर बाज़ार के भाव", "फिल्म के गाने", "खेल के स्कोर"],
     ["Clouds, storms and weather conditions", "Share-market prices", "Film songs", "Sports scores"],
     0,
     "मौसम-चित्रण ही मौसम-उपग्रह का काम है।",
     "Weather mapping is the weather satellite's job."),

    ("indian-space-missions", "medium",
     "संचार उपग्रह बिना तार बिछाए दूर संचार कैसे संभव करता है?",
     "How does a communication satellite make distant communication possible without laying wires?",
     ["ऊपर से संकेतों को आगे बढ़ाकर (रिले करके) दूर के क्षेत्रों तक पहुँचाकर", "ज़मीन में सुरंग बनाकर", "कबूतरों पर बिठाकर", "आवाज़ चिल्लाकर"],
     ["By relaying signals from above to distant areas", "By digging tunnels underground", "By putting them on pigeons", "By shouting"],
     0,
     "आकाश से रिले = तार-रहित दूरसंचार।",
     "Relaying from the sky = wireless long-distance communication."),

    ("indian-space-missions", "medium",
     "सोचिए — समुद्र में डूबते जहाज़ का संकट-संदेश तुरंत कैसे दूर तक जा सकता है?",
     "Think — how can a sinking ship's distress message instantly travel far?",
     ["संचार उपग्रहों के माध्यम से", "बात करते-करते", "पत्र डालकर", "धुआँ उड़ाकर"],
     ["Via communication satellites", "By talking on and on", "By posting a letter", "By blowing smoke"],
     0,
     "उपग्रह-संचार ने दूरियों को छोटा कर दिया।",
     "Satellite communication shrank the distances."),

    ("indian-space-missions", "medium",
     "किसान को बारिश-तूफान की पूर्व सूचना किस तकनीक के आधार पर मिलती है?",
     "On the basis of which technology does a farmer get advance notice of rain and storms?",
     ["मौसम उपग्रह आधारित पूर्वानुमान", "टीवी के विज्ञापन", "रेडियो का कलर", "पंचांग का आकार"],
     ["Weather-satellite-based forecasting", "TV advertisements", "The colour of a radio", "The shape of an almanac"],
     0,
     "मौसम-उपग्रह की सूचनाएँ कृषि के लिए वरदान हैं।",
     "Weather-satellite information is a boon for farming."),

    ("indian-space-missions", "medium",
     "दो कथन: (i) आर्यभट्ट प्रथम भारतीय उपग्रह था। (ii) चंद्रयान मंगल का अभियान है। सही विकल्प:",
     "Two statements: (i) Aryabhata was the first Indian satellite. (ii) Chandrayaan is the Mars mission. The correct option:",
     ["(i) सही, (ii) गलत", "दोनों सही", "दोनों गलत", "(i) गलत, (ii) सही"],
     ["(i) correct, (ii) wrong", "Both correct", "Both wrong", "(i) wrong, (ii) correct"],
     0,
     "चंद्रयान चंद्रमा का अभियान है, मंगल का नहीं।",
     "Chandrayaan is the Moon's mission, not Mars's."),

    ("indian-space-missions", "medium",
     "उपग्रह-आधारित मौसम-सूचना से समाज को क्या लाभ है?",
     "What benefit does society get from satellite-based weather information?",
     ["आपदा से पूर्व तैयारी और जान-माल की सुरक्षा", "केवल मनोरंजन", "केवल फैशन", "कोई लाभ नहीं"],
     ["Advance disaster preparedness and safety of lives and property", "Only entertainment", "Only fashion", "No benefit"],
     0,
     "पूर्व-चेतावनी ही बचाव की पहली शर्त है।",
     "Early warning is the first condition of safety."),

    ("indian-space-missions", "medium",
     "चंद्रमा और आर्यभट्ट दोनों उपग्रह हैं — इनमें वर्गीकरण-अंतर बताइए:",
     "The Moon and Aryabhata are both satellites — state the classification difference:",
     ["चंद्रमा प्राकृतिक, आर्यभट्ट कृत्रिम", "चंद्रमा कृत्रिम, आर्यभट्ट प्राकृतिक", "दोनों कृत्रिम", "दोनों प्राकृतिक"],
     ["The Moon is natural, Aryabhata is artificial", "The Moon is artificial, Aryabhata natural", "Both artificial", "Both natural"],
     0,
     "एक प्रकृति की संतान, दूसरा मानव की कृति।",
     "One is nature's child; the other, a human creation."),

    ("indian-space-missions", "medium",
     "ISRO से जुड़े नामों का सही समूह कौन-सा है?",
     "Which is the correct group of names associated with ISRO?",
     ["आर्यभट्ट, चंद्रयान, मंगलयान", "NASA, ESA, JAXA", "ध्रुवतारा, मंगल, शनि", "गंगा, यमुना, ब्रह्मपुत्र"],
     ["Aryabhata, Chandrayaan, Mangalyaan", "NASA, ESA, JAXA", "The Pole Star, Mars, Saturn", "Ganga, Yamuna, Brahmaputra"],
     0,
     "तीनों भारतीय अंतरिक्ष-कार्यक्रम की उपलब्धियाँ हैं।",
     "All three are achievements of India's space programme."),

    ("indian-space-missions", "medium",
     "दूरदराज के गाँव में रेडियो/टीवी का प्रसारण पहुँचाने में उपग्रह की भूमिका क्या है?",
     "What is the satellite's role in bringing radio/TV broadcasts to a remote village?",
     ["वह प्रसारण-संकेतों को विशाल क्षेत्रों तक पहुँचाता है", "वह बिजली बनाता है", "वह सड़क बनाता है", "वह फसल उगाता है"],
     ["It carries broadcast signals across vast areas", "It generates electricity", "It builds roads", "It grows crops"],
     0,
     "प्रसारण-क्षेत्र का विस्तार ही उपग्रह-प्रसारण का लाभ है।",
     "Extending the broadcast footprint is the benefit of satellite broadcasting."),

    ("indian-space-missions", "medium",
     "'यान' प्रत्यय वाले भारतीय अभियानों के लक्ष्य पहचानिए — चंद्रयान और मंगलयान:",
     "Identify the targets of the Indian missions with the 'yaan' suffix — Chandrayaan and Mangalyaan:",
     ["चंद्रमा और मंगल", "मंगल और चंद्रमा", "सूर्य और शुक्र", "पृथ्वी और शनि"],
     ["The Moon and Mars", "Mars and the Moon", "The Sun and Venus", "The Earth and Saturn"],
     0,
     "नाम का पहला शब्द लक्ष्य बताता है।",
     "The first word of the name tells the target."),

    ("indian-space-missions", "medium",
     "उपग्रह आकाश में गिरता क्यों नहीं है? शालेय स्तर की समझ चुनिए:",
     "Why does a satellite not fall from the sky? Choose the school-level understanding:",
     ["वह पृथ्वी की परिक्रमा में लगातार बना रहता है — उसकी कक्षीय गति ही उसे परिक्रमा में रखती है", "उसे रस्सी से बाँधा है", "वह हवा से टिका है", "वह इतना हल्का है कि गिर ही नहीं सकता"],
     ["It keeps revolving around the Earth — its orbital motion keeps it in orbit", "It is tied with a rope", "It rests on air", "It is so light it cannot fall"],
     0,
     "कक्षा में घूमता उपग्रह परिक्रमा करता रहता है — यही सरल समझ है।",
     "A satellite in orbit keeps revolving — that is the simple understanding."),

    ("indian-space-missions", "medium",
     "मौसम-उपग्रह और संचार-उपग्रह के कार्यों का गलत मिलान कौन-सा है?",
     "Which is the WRONG matching of the jobs of a weather satellite and a communication satellite?",
     ["मौसम-उपग्रह — दूर के लोगों से बात कराना", "मौसम-उपग्रह — तूफान की चेतावनी", "संचार-उपग्रह — संदेश पहुँचाना", "संचार-उपग्रह — प्रसारण में सहायता"],
     ["Weather satellite — making distant people talk", "Weather satellite — storm warnings", "Communication satellite — carrying messages", "Communication satellite — assisting broadcasts"],
     0,
     "बात कराना संचार-उपग्रह का काम है।",
     "Making people talk is the communication satellite's job."),

    ("indian-space-missions", "medium",
     "कथन: 'चंद्रयान एक उपग्रह है।' सावधानी से निर्णय कीजिए:",
     "Statement: 'Chandrayaan is a satellite.' Judge carefully:",
     ["शब्द-रूप से भ्रामक — चंद्रयान एक अभियान (मिशन) है चंद्रमा के लिए; आर्यभट्ट उपग्रह का नाम है", "पूर्णतः सही", "पूर्णतः गलत — यह तारा है", "यह व्यक्ति का नाम है"],
     ["Misleading in wording — Chandrayaan is a mission for the Moon; Aryabhata is the satellite's name", "Fully correct", "Fully wrong — it is a star", "It is a person's name"],
     0,
     "अभियान और उपग्रह की श्रेणियाँ अलग हैं।",
     "The categories of mission and satellite differ."),

    ("indian-space-missions", "medium",
     "पहाड़ों से घिरे दूर के क्षेत्र में मोबाइल संचार पहुँचाने में कौन-सी तकनीक सहायक होती है?",
     "Which technology helps bring mobile communication to a far region surrounded by mountains?",
     ["संचार उपग्रह", "कोयला-भट्टी", "पवन चक्की", "सौर कुकर"],
     ["Communication satellites", "A coal furnace", "A windmill", "A solar cooker"],
     0,
     "जहाँ तार नहीं पहुँचते, वहाँ उपग्रह-संकेत पहुँचते हैं।",
     "Where wires cannot reach, satellite signals do."),

    ("indian-space-missions", "medium",
     "उपग्रह-प्रसारण बनाम ज़मीनी नुक्ता-प्रसारण — पूर्व का लाभ क्या है?",
     "Satellite broadcasting vs ground point-to-point broadcasting — what is the advantage of the former?",
     ["एक ही बार में विशाल और दूर के क्षेत्रों को कवर करना", "क्योंकि यह बहुत महँगी तकनीक है", "यह ध्वनि खराब करता है", "इसमें कोई अंतर नहीं"],
     ["Covering vast and distant areas at once", "Because it is a very costly technology", "It spoils the sound", "There is no difference"],
     0,
     "विस्तृत कवरेज ही उपग्रह-प्रसारण की ताकत है।",
     "Wide coverage is the strength of satellite broadcasting."),

    ("indian-space-missions", "medium",
     "तीन कथन: (i) ISRO भारतीय अंतरिक्ष अभियान चलाता है। (ii) मंगलयान चंद्रमा के लिए है। (iii) मौसम-उपग्रह तूफान की सूचना देते हैं। गलत कथन:",
     "Three statements: (i) ISRO runs India's space missions. (ii) Mangalyaan is for the Moon. (iii) Weather satellites give storm information. The wrong statement:",
     ["कथन (ii)", "कथन (i)", "कथन (iii)", "तीनों सही"],
     ["Statement (ii)", "Statement (i)", "Statement (iii)", "All three correct"],
     0,
     "मंगलयान मंगल के लिए है।",
     "Mangalyaan is for Mars."),

    ("indian-space-missions", "medium",
     "उपग्रह-तकनीक से सीधे लाभान्वित होने वाले दो व्यवसाय चुनिए:",
     "Pick two occupations that directly benefit from satellite technology:",
     ["किसान (मौसम-सूचना) और प्रसारक (दूर प्रसारण)", "लोहार और बढ़ई", "दर्जी और मोची", "माली और नाई"],
     ["Farmers (weather information) and broadcasters (distant broadcasting)", "Blacksmith and carpenter", "Tailor and cobbler", "Gardener and barber"],
     0,
     "मौसम और प्रसारण — दोनों में उपग्रह सीधे काम आते हैं।",
     "In both weather and broadcasting, satellites directly serve."),

    ("indian-space-missions", "medium",
     "चंद्रयान-मंगलयान की सफलता का सामान्य नागरिक के जीवन से कोई संबंध बताइए:",
     "State any link between the success of Chandrayaan-Mangalyaan and a common citizen's life:",
     ["अंतरिक्ष-तकनीक के विकास से संचार-मौसम-प्रसारण की सेवाएँ और सक्षम होती हैं", "इनका जीवन से कोई लेना-देना नहीं", "इनसे केवल फिल्में बनती हैं", "इनसे केवल खेल होते हैं"],
     ["Advances in space technology make communication, weather and broadcasting services more capable", "They have nothing to do with life", "Only films are made from them", "Only games happen from them"],
     0,
     "अंतरिक्ष-उपलब्धियाँ आम सेवाओं को भी सशक्त बनाती हैं।",
     "Space achievements also empower everyday services."),

    ("indian-space-missions", "medium",
     "कृत्रिम उपग्रह और चंद्रमा — दोनों पृथ्वी की परिक्रमा करते हैं। दोनों का सही वर्गीकरण क्रमशः है:",
     "An artificial satellite and the Moon — both revolve around the Earth. Their correct classification respectively is:",
     ["कृत्रिम उपग्रह और प्राकृतिक उपग्रह", "प्राकृतिक और कृत्रिम", "ग्रह और तारा", "तारा और ग्रह"],
     ["Artificial satellite and natural satellite", "Natural and artificial", "Planet and star", "Star and planet"],
     0,
     "परिक्रमा समान, उत्पत्ति भिन्न।",
     "The revolution is alike; the origin differs."),

    ("indian-space-missions", "medium",
     "मौसम-आगाही मिलने पर मछुआरे किनारे नहीं जाते — इस निर्णय के पीछे कौन-सी उपग्रह-सेवा है?",
     "Fishermen avoid going to sea on receiving a weather alert — which satellite service backs this decision?",
     ["मौसम-उपग्रह आधारित चेतावनी", "संचार-उपग्रह आधारित गाना", "प्रसारण-उपग्रह आधारित विज्ञापन", "कोई उपग्रह नहीं"],
     ["A weather-satellite-based warning", "A communication-satellite-based song", "A broadcast-satellite-based advertisement", "No satellite"],
     0,
     "मौसम-सूचना से जीवन-रक्षा का निर्णय सहज बनता है।",
     "Weather information makes life-saving decisions natural."),

    # ---- hard (8) ----
    ("indian-space-missions", "hard",
     "आर्यभट्ट को 'प्रथम' कहने का तात्पर्य समझाइए:",
     "Explain what calling Aryabhata 'the first' means:",
     ["उससे पहले भारत का कोई कृत्रिम उपग्रह नहीं था — वह पहला था", "वह सबसे बड़ा उपग्रह था", "वह अंतिम उपग्रह था", "वह चंद्रमा से पहले था"],
     ["No Indian artificial satellite existed before it — it was the first", "It was the largest satellite", "It was the last satellite", "It came before the Moon"],
     0,
     "'प्रथम भारतीय उपग्रह' = शुरुआत की मील का पत्थर।",
     "'First Indian satellite' = the starting milestone."),

    ("indian-space-missions", "hard",
     "चंद्रयान का लक्ष्य चंद्रमा है — यह कथन खगोलीय श्रेणी की दृष्टि से सटीक क्यों है?",
     "Chandrayaan's target is the Moon — why is this statement exact from the viewpoint of astronomical categories?",
     ["चंद्रमा हमारा निकटतम खगोलीय पड़ोसी है — पृथ्वी का उपग्रह", "चंद्रमा सबसे बड़ा ग्रह है", "चंद्रमा एक तारा है", "चंद्रमा सूर्य का उपग्रह है"],
     ["The Moon is our nearest celestial neighbour — the Earth's satellite", "The Moon is the largest planet", "The Moon is a star", "The Moon is the Sun's satellite"],
     0,
     "लक्ष्य की पहचान श्रेणी-ज्ञान से आती है।",
     "Identifying the target comes from knowing the category."),

    ("indian-space-missions", "hard",
     "मंगलयान-अभियान के लिए मंगल ग्रह को चुना जाना कक्षा 6-10 की दृष्टि से किस तथ्य पर टिका है?",
     "From a class 6-10 viewpoint, the choice of Mars for the Mangalyaan mission rests on which fact?",
     ["मंगल सूर्य का चौथा ग्रह है — पृथ्वी का आगे का पड़ोसी", "मंगल सबसे गर्म ग्रह है", "मंगल सबसे बड़ा ग्रह है", "मंगल एक तारा है"],
     ["Mars is the fourth planet from the Sun — Earth's next-door neighbour onward", "Mars is the hottest planet", "Mars is the largest planet", "Mars is a star"],
     0,
     "ग्रह-क्रम का ज्ञान ही अभियान-लक्ष्य की पृष्ठभूमि है।",
     "Knowledge of the planet order is the backdrop of the mission target."),

    ("indian-space-missions", "hard",
     "तीन कथन: (i) कृत्रिम उपग्रह मनुष्य के बनाए हैं। (ii) चंद्रमा कृत्रिम उपग्रह है। (iii) संचार-उपग्रह संदेश रिले करते हैं। गलत कथन:",
     "Three statements: (i) Artificial satellites are man-made. (ii) The Moon is an artificial satellite. (iii) Communication satellites relay messages. The wrong statement:",
     ["कथन (ii) — चंद्रमा प्राकृतिक उपग्रह है", "कथन (i)", "कथन (iii)", "तीनों सही"],
     ["Statement (ii) — the Moon is a natural satellite", "Statement (i)", "Statement (iii)", "All three correct"],
     0,
     "चंद्रमा की उत्पत्ति प्रकृति में हुई।",
     "The Moon originated in nature."),

    ("indian-space-missions", "hard",
     "यदि किसी देश के पास मौसम-उपग्रह न हों, तो सबसे अधिक असर किस क्षेत्र पर पड़ेगा?",
     "If a country had no weather satellites, which field would be hit hardest?",
     ["आपदा-पूर्वानुमान और कृषि-नियोजन", "फिल्म उद्योग", "फैशन उद्योग", "पेंटिंग"],
     ["Disaster forecasting and farm planning", "The film industry", "The fashion industry", "Painting"],
     0,
     "मौसम-सूचना की अनुपस्थिति आपदा-प्रबंधन को सबसे अधिक कमज़ोर करती है।",
     "The absence of weather information weakens disaster management the most."),

    ("indian-space-missions", "hard",
     "उपग्रह-प्रसारण में 'रिले' की भूमिका तर्कसंगत रूप से समझाइए:",
     "Explain logically the role of 'relay' in satellite broadcasting:",
     ["संकेत ऊपर उपग्रह तक जाता है और वहाँ से विस्तृत क्षेत्रों में वापस भेजा जाता है — सीधी रेखा की सीमा पार हो जाती है", "रिले से आवाज़ बदल जाती है", "रिले से बिजली बनती है", "रिले केवल खेलों में होता है"],
     ["A signal goes up to the satellite and is sent back over wide areas — the limit of the straight line is crossed", "Relay changes the voice", "Relay generates electricity", "Relay happens only in sports"],
     0,
     "ऊँचाई से फैलाव — यही रिले का तर्क है।",
     "Spreading from a height — that is relay's logic."),

    ("indian-space-missions", "hard",
     "आर्यभट्ट (उपग्रह) और चंद्रमा की तुलना में सही कथन चुनिए:",
     "Choose the correct statement comparing Aryabhata (the satellite) and the Moon:",
     ["दोनों पृथ्वी की परिक्रमा करते हैं, पर एक कृत्रिम है और दूसरा प्राकृतिक", "दोनों कृत्रिम हैं", "दोनों प्राकृतिक हैं", "कोई पृथ्वी की परिक्रमा नहीं करता"],
     ["Both revolve around the Earth, but one is artificial and the other natural", "Both are artificial", "Both are natural", "Neither revolves around the Earth"],
     0,
     "कक्षा साझा, उत्पत्ति भिन्न — यही तुलना का सार है।",
     "Shared orbit, different origin — that is the crux of the comparison."),

    ("indian-space-missions", "hard",
     "भारतीय अंतरिक्ष-कार्यक्रम का क्रम-बोध: पहले उपग्रह, फिर चंद्रमा और मंगल के अभियान। इस क्रम का उचित औचित्य क्या है?",
     "Understanding the sequence of India's space programme: first a satellite, then missions to the Moon and Mars. What is the proper justification of this order?",
     ["पहले कक्षा-क्षमता (उपग्रह) का विकास, फिर दूर के लक्ष्यों की ओर बढ़ना — क्रमिक विकास का स्वाभाविक पथ", "क्रम पूर्णतः यादृच्छिक है", "मंगल के बाद ही उपग्रह बनते हैं", "उपग्रहों की जरूरत कभी नहीं थी"],
     ["First developing orbital capability (satellites), then reaching for distant targets — the natural path of stepwise growth", "The order is entirely random", "Satellites are made only after Mars", "Satellites were never needed"],
     0,
     "छोटे कदम से बड़े लक्ष्य — विकास का यही तर्क है।",
     "Small steps to big targets — that is the logic of growth."),
]
